### ISSUE TITLE
Question: How to bind TextboxHelper.ButtonCommand in Caliburn.Micro way?

### ISSUE THREAD

**Issue by topvis** [MahApps/MahApps.Metro#1005]
I have a SearchMetroTextBox like this:

``` xml
<TextBox Text="Text"
         Style="{DynamicResource SearchMetroTextBox}"
         metro:TextboxHelper.ButtonCommand="{Binding TestCmd, Mode=OneWay}" />
```

Is it possible to use Carliburn.Micro's Message.Attach?

``` xml
<Button cal:Message.Attach="[Event MouseEnter] = [Action Save]">
```

**Comment by elendil-softwares** [comment]
Hi,

I tried to apply the solution that remcoros gave. But a get the error : Cannot find the static member 'ButtonCommand' on the type 'TextBoxHelper'

I took exactly the same RoutedEventTrigger class and in the XAML I put:

<TextBox controls:TextBoxHelper.Watermark="Search..."
               Style="{DynamicResource SearchMetroTextBox}">
        <i:Interaction.Triggers>
                <events:RoutedEventTrigger RoutedEvent="{x:Static controls:TextBoxHelper.ButtonCommand}">
                        <cal:ActionMessage MethodName="SearchObject" />
                </events:RoutedEventTrigger>
        </i:Interaction.Triggers>
</TextBox>

Do I missed something

**Comment by xmedeko** [comment]
You can turn Commad to the custom event, see http://stackoverflow.com/a/29027266/254109
Or create a custom dependency property to do the magic http://stackoverflow.com/a/35429704/254109
