### ISSUE TITLE
problem with web browser jump

### ISSUE THREAD

**Issue by dlebedynskyi** [MahApps/MahApps.Metro#101]
Hi, 
I've got some problems with MetroWindow and position of webbrowser in it
![bug](http://s15.postimage.org/y1h9u1h2j/Capture_1.png)

It happens on every window open. If I resize window - everything becomes normal 
![ok](http://s16.postimage.org/dgsoqb0n9/Capture_2.png)

you can just move mouse on maximize button.  

markup is very simple 

<metro:MetroWindow
    <Grid
        <Webbroser in grid cell

if I remove MetroWindow  and place simple Window - everything is ok from the start. 

I use 
<package id="MahApps.Metro" version="0.8.0.0" />
<package id="MahApps.Metro.Resources.Standalone" version="0.1.0.0" />

Can you help with this issue? is there any fix or something?

**Comment by ant-fx** [comment]
I know this report is old but I get the same thing with v1.1.2.0.

With a WebBrowser in a Grid cell the `WebBrowser` has a gap beside it. If I resize the window or even hover over the max/min buttons the gap goes away.

Setting `WindowTransitionsEnabled` to `false` fixes the problem.

Example XAML

````
<Controls:MetroWindow 
    x:Class="tellyabroad.win.app.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:local="clr-namespace:tellyabroad.win.app"
    xmlns:Controls="clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro"
    mc:Ignorable="d"
    Title="SomeWindow" 
    Height="600" 
    Width="1024"
    >
    <Grid Margin="5">
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="250" />
            <ColumnDefinition Width="*" />
        </Grid.ColumnDefinitions>

        <Border 
            Grid.Column="0" 
            HorizontalAlignment="Stretch" 
            BorderBrush="Black" 
            BorderThickness="0"
            Background="Green"
            >
            <StackPanel >
                <TextBlock>
                    This is some text
                </TextBlock>
            </StackPanel>
        </Border>

        <Border 
            Grid.Column="1"
            HorizontalAlignment="Stretch"
            VerticalAlignment="Stretch"
            BorderBrush="Black" 
            BorderThickness="0"
            >
            <WebBrowser 
                Name="TvBrowser"
                HorizontalAlignment="Stretch"
                VerticalAlignment="Stretch"
                >
            </WebBrowser>
        </Border>
    </Grid>
</Controls:MetroWindow>

````
