### ISSUE TITLE
Cannot change title bar background color.

### ISSUE THREAD

**Issue by bukanijam** [MahApps/MahApps.Metro#1025]
I want my title bar background color looks like visual studoi 2013 or microsoft office 2013. Title bar background color property is not exposed. I have to manually edit file MetroWindow.xaml and change from this:

```
                    <Rectangle x:Name="PART_WindowTitleBackground"
                               Fill="{DynamicResource WindowTitleColorBrush}"
```

to this:

```
                    <Rectangle x:Name="PART_WindowTitleBackground"
                               Fill="{x:Null}"
```

How can i change the title bar background color without changing Mahapps metro library?

Thanks.

**Comment by crclayton** [comment]
Using clean style does change the titlebar background, yes, but it doesn't solve the problem. Why is there a TitleForeground attribute but not a TitleBackground attribute for MetroWindow?

**Comment by punker76** [comment]
@crclayton `WindowTitleBrush` at `MetroWindow` works only for normal metro window not for the clean style. if you want a clean style with cusrom title background you must create your own style.

**Comment by crclayton** [comment]
I don't want a clean style though, I just want to change the titlebar color. I'll write a new issue explaining.

**Comment by punker76** [comment]
@crclayton so `WindowTitleBrush` is your friend

**Comment by crclayton** [comment]
Ahhhh! Thank you! You're right, that's what I want. No need to open the new issue.
