### ISSUE TITLE
Change color dynamically

### ISSUE THREAD

**Issue by clodewyks** [MahApps/MahApps.Metro#1026]
Hi There,

This is a request, not an issue, just didn't know where to put it.

Is there a way to dynamically change the color of the window? I would like to give the user the option to choose their preferred color.

So the question is will I be able to set this:

```
            <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/BaseLight.xaml" />
            <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/Blue.xaml" />
```

In code behind dependant on user settings?

**Comment by iscum** [comment]
Why color dont update after (ThemeManager.ChangeAppStyle(Application.Current....) in controls:flyout...(Background="{DynamicResource AccentColorBrush}")
