### ISSUE TITLE
Icon color not changing on theme change

### ISSUE THREAD

**Issue by Tide** [MahApps/MahApps.Metro#1029]
I am using a circle button like so:

```
                    <Button 
                            Width="50"
                            Height="50"
                            Margin="0"
                            Style="{DynamicResource MetroCircleButtonStyle}">
                        <Rectangle Width="20" Height="20">
                            <Rectangle.Fill>
                                <VisualBrush Stretch="Fill" Visual="{StaticResource appbar_arrow_right}" />
                            </Rectangle.Fill>
                        </Rectangle>
                    </Button>
```

When I change the theme everything is updating but the arrow icon.  If I start with the dark theme the arrow will stay white then switching to the light theme and vice versa.

**Comment by gigios** [comment]
I'm trying to use some icons in my application.
For the normal usage all works fine but if I try to change the theme the icons does not changes the color.
I have tried also to move the icon resource in the windows but without success. Only if I put the icon resource directly in my usercontrol the icon change the color when the user change the theme.
Seems that the only way to apply the new colors is to recreate the control (I have seen the same effect in the MetroDemo, if the Icon window is shown, if I change the theme the colors does not changes, if I close and reopen the window the icons use the correct colors).

There is a way to fix this behavior without close/reopen the page?
