### ISSUE TITLE
InvalidOperationException when closing Window

### ISSUE THREAD

**Issue by michaelmairegger** [MahApps/MahApps.Metro#1044]
Reproduction Steps.

Open **MetroWindow** from MainWindow and set Owner of opening window to **MainWindow**. Close MainWindow.

Error:
Cannot set Visibility or call Show, ShowDialog, or WindowInteropHelper.EnsureHandle after a Window has closed.

Location:
https://github.com/MahApps/MahApps.Metro/blob/master/MahApps.Metro/Controls/GlowWindow.xaml.cs?source=cc#L206

**Comment by Pekshev** [comment]
Still not fixed :-(
I use version 1.1.2 and catch this error
Note: i'm use it in autocad's plugin

**Comment by punker76** [comment]
@Pekshev please create a new issue with more information like debug output or a stacktrace or something else. thx
