### ISSUE TITLE
Drag & Drop tabitems (Reordring)

### ISSUE THREAD

**Issue by williamwallace** [MahApps/MahApps.Metro#1045]
Hi everyone,

I have a little problem with AnimatedSingleRowTabControl when Reordering tabitems.
i have 20+ tabitems in each tabcontrol of my app, with AnimatedSingleRowTabControl some tabitems are hidden and i have to click on left/right arrows to see them. it works fine, but when i want to Drop my tabitem on a hidden(i have to click on right arrow in order to see it) tabitem.
for example : 
dragsource index : 1 
droptarget index : 32

how can i make tabitems scroll (when dragging) in order to see my droptarget.
Cordially

**Comment by punker76** [comment]
@williamwallace it sounds like you need this one
https://github.com/ButchersBoy/Dragablz
it works also with MahApps
https://github.com/ButchersBoy/DragablzMeetzMahApps
