### ISSUE TITLE
TextmarkHelper.Watermark and Caliburn.Micro

### ISSUE THREAD

**Issue by holgergubbels** [MahApps/MahApps.Metro#1059]
Hi,

Behaviour:
I have three textboxes: username, email and message. All three textboxes are using TextboxHelper.Watermark. The watermark is not visible although the boxes are empty (other boxes on other windows are filled with watermarks). When I change the textbox with the user-message, the other 2 textboxes getting a watermark - with the text of the user-message....

Reason:
I use caliburn.micro. My TextBox for the usermessage is bound to a ViewModel-Property "Message".
Caliburn.micro has this "property"-magic, where bindings are made via x:Name. Unfortunately the TextBlock for the Watermark in the Textbox-Template (Controls.TextBox.xaml) is called "Message" as well. 
So every textbox-watermark is bound to ViewModel-Message instead of TextboxHelper.Watermark...

Solution:
Can you just change inner names of properties or names of controls in the template to a name, which is not very likely to be used by any application? Like x:Name="mahapps_Message"?
Because it is really difficult to find out those problems... ;o)

Thank you!!

**Comment by punker76** [comment]
changed/fixed with badef24e1dbc6bb75e96e30bb2a7f5fe24e77e56
