### ISSUE TITLE
MahApps MessageBoxes using MVVM

### ISSUE THREAD

**Issue by Camuvingian** [MahApps/MahApps.Metro#1129]
Simple question for the MahApps Merry Men. I have implemented an application using your great metro styled controls using Caliburn.Micro for the MVVM stuff. The new message dialogs look great, but currently there is not clear way of launching these dialogs with out writing my own wrapper (which I am not against). However, has this been done or is there something I missing so that I can invoke a message box from a view model without any fuss?

Thanks for your time.

**Comment by waleswood** [comment]
> My fear of hiding the main "dialog" to show the confirmation is that it will be confusing to the end user, I would think.
> 
> I have a dedicated ticket to see if there is something in the MahApps framework that I missed whereas I can still have the SimpleDialog + provide a confirmation prompt without needing a child window. Although I realize I can build an external window for the confirmation, it's something I'm trying to avoid.

Finally, how did you solve it?
