### ISSUE TITLE
ComboBox has Virtualizing disabled

### ISSUE THREAD

**Issue by michaelmairegger** [MahApps/MahApps.Metro#1132]
Virtualizing is not working with __ComboBox__es when loading long list of data.
After loading the data the ComboBox takes very long time to open, because virtualization is disabled.

A solution is to replace the 
`<ItemsPresenter x:Name="ItemsPresenter" KeyboardNavigation.DirectionalNavigation="Contained" />`
 with **VirtualizingStackPanel** but then the grouping does not work anymore.

How do I enable Virtualization in ComboBoxes?

**Comment by Hypenate** [comment]
I had to add  your code, else it was unbareable slow.
It went from 17 seconds to instant open now!
```
<Style TargetType="{x:Type ComboBox}"
       BasedOn="{StaticResource MetroComboBox}">
  <Setter Property="ScrollViewer.CanContentScroll"
          Value="True" />
  <Setter Property="ItemsPanel">
    <Setter.Value>
      <ItemsPanelTemplate>
        <VirtualizingStackPanel IsItemsHost="True"
                                KeyboardNavigation.DirectionalNavigation="Contained"
                                VirtualizationMode="Recycling" />
      </ItemsPanelTemplate>
    </Setter.Value>
  </Setter>
</Style>
```

**Comment by punker76** [comment]
You can use the VirtualisedMetroComboBox style
Am 22.05.2016 6:13 nachm. schrieb "Ben" <notifications@github.com>:
