### ISSUE TITLE
Have an option to disable animations

### ISSUE THREAD

**Issue by josephxxv** [MahApps/MahApps.Metro#1154]
As much as I love the animations in MahApps, I work in an environment that uses Citrix remote desktops with terrible network connections. Any animations cause the experience to be unusable. I would love to use this framework for an application, but the animations are a showstopper. I would like to optionally turn off the animations.

**Comment by punker76** [comment]
dep property added by https://github.com/MahApps/MahApps.Metro/pull/1746
