### ISSUE TITLE
[RFC] Windows XP support

### ISSUE THREAD

**Issue by flagbug** [MahApps/MahApps.Metro#1176]
So Windows XPs [lifetime is ending](http://windows.microsoft.com/en-us/windows/lifecycle)

Currently (at least I think, I've never tested for it :smile:), we support Windows XP

In my opinion, support for it should be dropped in the next release, that'll make all of our lives easier.

/cc @MahApps/contributors

**Comment by hyacinthus** [comment]
Hello All:
    I hate win xp so much.
    But in my current project, my customs use XP day after day.

    I don't know the result of this discussion.

    Shall we write down the system requirement in README file by versions. Then I'll know if I should accept a version update or not.

    Thanks!
