### ISSUE TITLE
Metro Window Drag Issue

### ISSUE THREAD

**Issue by xamlfactory** [MahApps/MahApps.Metro#1216]
Clicking anywhere on Metro Window allowing user to drag. This is making confusion with other drag operations inside Metro Window. Drag and Move should happen only on title bar.

**Comment by okatip1** [comment]
Hi,
@flagbug 
@punker76 
@xamlfactory 

When do you implement this?
" ShowTitleBar="False" should ideally disable drag moving window behavior. **Also drag move should work only within the bounds of TitleBarHeight.**"

I need this? Please help!

**Comment by okatip1** [comment]
I figured out the problem like this:

        private void MetroWindow_MouseDown(object sender, MouseButtonEventArgs e)
        {
            if (e.Source != null && e.Source.GetType() == typeof(MainWindow))
            {
                e.Handled = false;
            }
            else
            {
                e.Handled = true;
            }
        }
