### ISSUE TITLE
Change titlebar text from captitals to lowercase

### ISSUE THREAD

**Issue by ghost** [MahApps/MahApps.Metro#123]
Hi,

is it posible to change the size of the titlebar text from capitals to normal text anyhow?
I would really appriciate some help :)

Thanks,

Marsychen

**Comment by tsasioglu** [comment]
This is now an option on MetroWindow.

TitleCaps="False"

**Comment by Matix-Media** [comment]
Update: The Option has been renamed to `TitleCharacterCasing` and has now the options:
- `Normal`
- `Upper`
- `Lower`
