### ISSUE TITLE
Any elegant way to override the style of Control, specifically, the DataGridRow?

### ISSUE THREAD

**Issue by oloopy** [MahApps/MahApps.Metro#1243]
I tried to hide some of the rows in the DataGrid through DataBinding by changing the RowStyle.

```
<DataGrid.RowStyle>
    <Style TargetType="DataGridRow">
        <Setter Property="Visibility" Value="{Binding Path=Visibility}"/>
    </Style>
</DataGrid.RowStyle>
```

While adding the code above into routine would prevent other predefined RowStyle developed by Mahapps work correctly.

What I do now is to copy all the code related to the DataGridRow from [Controls.DataGrid.xaml](https://github.com/MahApps/MahApps.Metro/blob/master/MahApps.Metro/Styles/Controls.DataGrid.xaml) and add them with the above code together into my routine. This time works.

I would like to know if there is an elegant way to change the style without copying&pasting a bunch of code from the source code.

Thanks!

**Comment by Flem100** [comment]
Thank you so much.The double inherit worked for me.
