### ISSUE TITLE
Window going behind other windows on program start

### ISSUE THREAD

**Issue by Tide** [MahApps/MahApps.Metro#1251]
I started noticing that when I start my application that the main window would go behind other windows on program startup some times.  I thought at first it may just be my application as I had added splash screen to it around that same time.

I believe this started happening around 3-19-2014 (Not sure exactly the day).  Well today I was playing with adding a new control to M.A.M. and using the demo to test it.  The same bug appeared on occasion.

If you have other windows open and start the application it will start then quickly go behind other windows.  The weird thing is it does not happen all the time.  

I experience this most while debugging in Visual Studio.  I rarely run my application enough for it to happen in application use.  However, I debug it often in the course of working on the application and so I notice it more often while debugging.  Just to be clear though it happens when I run my application on its own as well.  

One thing I have noticed when it does happen and I am debugging I can change the value of a property from lets say False to True and debug again and it will occur.  If I continue to repeat this process and change the bool value in xaml and debug ti will continue to happen each time.  If I leave the bool the same and debug again the program will act normal.  The hard part is getting the bug to happen in the first place.  If it ever happens and you do as I just described you can get ti to happen every time.

The next thing you may think (I did) is well what does that have to do with when you run it on its own outside the Visual Studio debugger.  My answer is I have no idea.

I feel bad even posting this but it has happened enough that I know something is up.

I can't give you any more information as like I said you do not know when it is going to happen.

I just wanted to put this up so if others are experiencing the same thing they will not think they are crazy and maybe can figure out what makes it happen.

**Comment by punker76** [comment]
@Tide fixed with 6b0a8fa5762e850c8e8913d86965fac69ec6d1e8

**Comment by AndreasSchmid1** [comment]
This error appeared to me in v 1.2.4
