### ISSUE TITLE
TextBox with textboxhelper cleartextbtn doesnt work after visibilty change

### ISSUE THREAD

**Issue by gilimak** [MahApps/MahApps.Metro#1268]
Hi,
I have a grid with 2 columns.
col 0 is visible and have a button that change the visibility col 1 visible.
in col 0 the textbox which works fine:

                    <TextBox Grid.Col="0" VerticalAlignment="Center"
                             Text="{Binding Model.ComputerName, Delay=2500,
                                            UpdateSourceTrigger=PropertyChanged,
                                            Mode=TwoWay}"
                             controls:TextboxHelper.ClearTextButton="True"
                             controls:TextboxHelper.Watermark="{Binding Path=Model.TotalCount,
                                                                        StringFormat='{} Any ({0})'}" />

and in col 1 i have the same text box (with different text binding property).
the problame is that in col 1 (after visibilty of the grid change to visible) the cleartextbutton doesnt work (it appears but not clearing the text).
if i remove the visibility binding from the grid so both columns will be visible it works.
any ideas for a solution?
thanks.

**Comment by JoeRobich** [comment]
I ran into this same issue. I tried calling ApplyTemplate from the Loaded event but it broke the layout of the button within the textbox. I ended up leaving the textbox's container visible until the loaded event fired which got everything working.

**Comment by thoemmi** [comment]
I can confirm this bug. When the textbox is hidden while loaded, the code 
```C#
var button = template.FindName("PART_ClearText", textbox) as Button;
```
in `TextBoxHelper.TextBoxLoaded` returns `null`.

Unfortunately, I don't know how to fix it. :disappointed:
