### ISSUE TITLE
Dialog overlapping titlebar 

### ISSUE THREAD

**Issue by erdmenchen** [MahApps/MahApps.Metro#1272]
Is there an easy way to **not** overlay the window titlebar with a MetroDialog? 
So that the user still can minimize or close the window or drag it around?

At the moment (version 0.12.1.0) the dark background overlay is also overlapping the titlebar...

It would be phenomenal if it could be set via the MetroDialogSettings like the animation flag...

**Comment by punker76** [comment]
i close this, cause #2109 is the same and will be fixed soon...
