### ISSUE TITLE
Closing a MetroTabItem added from a child.

### ISSUE THREAD

**Issue by andySF** [MahApps/MahApps.Metro#1278]
I have a MetroAnimatedSingleRowTabControl in my Window and from a UserControl I add programmaticaly a MetroTabItem to it like so:

```
object foundTabControl = parentWindow.FindName("metroAnimatedSingleRowTabControl");
MetroAnimatedSingleRowTabControl metroAnimatedSingleRowTabControl = (MetroAnimatedSingleRowTabControl)foundTabControl;
MetroTabItem metroTabItem = new MetroTabItem();
metroTabItem.Content = newSomeUserControl;
metroTabItem.CloseButtonEnabled = true;
metroAnimatedSingleRowTabControl.Items.Insert(index,metroTabItem);
metroAnimatedSingleRowTabControl.SelectedIndex = index;
metroAnimatedSingleRowTabControl.Items.MoveCurrentToLast();
```

When I close this tab I get a *InvalidOperationException* saying that *Operation is not valid due to the current state of the object.*

The other tabs added from XAML don't have a close button but if I set the **CloseButtonEnabled="True"** it's working. The problem is just with the TabItems added from the child. 

Is this a limitation or I just lack the knowledge to do this?

**Comment by punker76** [comment]
@andySF @oloopy 
To override default style for the `MetroTabItem` control it's necessary to inherit from `{StaticResource {x:Type controls:MetroTabItem}}`

```xaml
<Style TargetType="controls:MetroTabItem"
        x:Key="MyMetroTabItem"
        BasedOn="{StaticResource {x:Type controls:MetroTabItem}}" />
```
