### ISSUE TITLE
About the customize of glow and drop shadow

### ISSUE THREAD

**Issue by ovear** [MahApps/MahApps.Metro#1311]
Hello, recently i used this library to my project, it's excellent! But i didn't find the way to set the radius of glow or drop shadows.So is there any way to set it?

Thanks.

**Comment by punker76** [comment]
it's possible to customize the glow brush (and border) and drop shadow (since we use the glow shadow for it), all testable in the latest alpha.

**Comment by tcortega** [comment]
> it's possible to customize the glow brush (and border) and drop shadow (since we use the glow shadow for it), all testable in the latest alpha.

Well and how do we do it? 🤔

**Comment by timunie** [comment]
> Well and how do we do it? 🤔

Easiest is to download the source of MahApps and play around with the sample App provided there: 

https://github.com/MahApps/MahApps.Metro/blob/7b50db6f7a55de217eabdb9f481af6f3eec35c97/src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindow.xaml#L21-L23 

Note: This is only working in latest preview / nightly build. If you need it for v2.x, change the branch in your git client first.
