### ISSUE TITLE
Hiding the minimimze/maximize/close buttons when `ShowTitleBar = false`, yay or nay?

### ISSUE THREAD

**Issue by flagbug** [MahApps/MahApps.Metro#1329]
From version 0.12 to 0.13 we changed the way the TitleBar behaves. `ShowTitleBar = false` now hides _every_  item in the TitleBar, while previously, the Minimzie/Maximize and Close buttons were unaffected.

Some people tripped over this (#1328 #1317 #1172) as they relied on the previous behavior.

Do we want the old behavior back, or leave it as is and tell people to use the clean window or add 

``` xml
<Controls:WindowButtonCommands Panel.ZIndex="1"
                                 HorizontalAlignment="Right"
                                 VerticalAlignment="Top"
                                 Height="{Binding TitlebarHeight, Mode=OneWay, RelativeSource={RelativeSource FindAncestor, AncestorType={x:Type Controls:MetroWindow}}}" />
```

Alternatively, as @vikingcode suggested in #1328, we could add a flag similiar to `ShowWindowCommandsOnTop`

/cc @MahApps/contributors

**Comment by JobaDiniz** [comment]
#1414 was reverted?

I want to hide the titlebar but allow user to close the window, how to accomplish that?

**Comment by JobaDiniz** [comment]
Forget it... the close button is shown even after settting `ShowTitleBar="False"`. My problem is that my window has WPF WebBrowser and the button is behind it.
