### ISSUE TITLE
Black border at bottom or right side when SizeToContent défined

### ISSUE THREAD

**Issue by jfbaudracco** [MahApps/MahApps.Metro#1332]
A border line bleck appears at bottom of window when SizeToContent is defined to Height ! It seems to me this problem has been fixed. But it appears since last version. Perhaps, the problem is in my code. I'm using the last stable version.
![mahapps](https://cloud.githubusercontent.com/assets/5718363/2876054/69830f0e-d42d-11e3-848e-6a423f39532e.png)
Thanks,
Jean-François

**Comment by punker76** [comment]
@jfbaudracco can you re-test this with 1.0 (or/and latest alpha version) ? this should be fixed now. thx
