### ISSUE TITLE
Title Bar Font Size

### ISSUE THREAD

**Issue by mrichman** [MahApps/MahApps.Metro#1355]
How can I change the Title Bar font size? I applied the CleanWindow style as follows:

```
<ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Colors.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/Steel.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/BaseLight.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Clean/CleanWindow.xaml"/>
            </ResourceDictionary.MergedDictionaries>
```

So now the title bar font is centered and there is no background color (both are what I want), but I lost the icon in the top left.
![2014-05-13 21_06_17-cmc installer v1 0 36097](https://cloud.githubusercontent.com/assets/11228/2965973/ee42bb9a-db03-11e3-96fc-8f0043424013.png)

**Comment by patrickpissurno** [comment]
Came here looking for the very same thing and found out that it changed from `WindowTitleFontSize` to `MahApps.Font.Size.Window.Title`.

Sorry for necro'ing the issue, but just leaving this here for future readers.
