### ISSUE TITLE
How to remove tile border and highlight on mouse over?

### ISSUE THREAD

**Issue by warffen** [MahApps/MahApps.Metro#1360]
I have an application that is using an old version of MA.M, which used to have the Panorama view with tiles. My application is a version control for our main software, and my groups are separated by versions.

As you can see the image below, the first item of each group has a border (gray-ish), and when I put the mouse over an item, the border gets blue. (second tile of the image)

![image](https://cloud.githubusercontent.com/assets/3089401/2984161/1103bb26-dc2f-11e3-9d6a-6e0bac3f726c.png)

Can someone help me to remove these borders? For me, there is no problem to change the downloaded MA.M source code that I have here.

**Comment by warffen** [comment]
The border arount the tile is still appearing for me. Can someone help me to remove? I have tried many ways to remove the "blue-ish" border, but nothing worked as expected. :(

**Comment by punker76** [comment]
@warffen i think this is outdated. we removed the panorama a long time ago (too many bugs or so).
but i have now updated the `Tile` to get some similar usage.

![image](https://cloud.githubusercontent.com/assets/658431/9671043/552765a4-5290-11e5-8fbe-5f9892646a63.png)

![image](https://cloud.githubusercontent.com/assets/658431/9671047/5bb4748e-5290-11e5-9cf3-d8c63e4afa4b.png)
