### ISSUE TITLE
Flyouts not visible in designer

### ISSUE THREAD

**Issue by akhalid** [MahApps/MahApps.Metro#1378]
Hi,

I just updated to latest version and now I cannot see the flyout preview in the designer. I am using VS 2012. Is this an issue/bug or something in my designer settings? They do however work just fine when I run the application.

Thanks,

AK

**Comment by Henka-Programmer** [comment]
Henka has left a gift for you in Topface.

Get the gift
http://topface.com/mp/?m_pl=st&m_action=inviteContact&m_page=Topface%5CProfile%5CProfilePage&m_page_params%5Buser_id%5D=95773512&m_link_params%5Bref%5D=m_inviteContact&m_link_params%5Bmailsrv%5D=gmail.com&m_link_params%5Bm_id%5D=b46f8b0ce6704d5cd4831ef4ae457893&m_link_params%5Bm_t%5D=1428785358&m_link_params%5Bm_exp%5D=&m_link_params%5Bsender_id%5D=95773512&m_link_params%5Binvite_email%5D=reply%2B00420e538b5e9494e7b0c8f169d8bad58b149882820a556692cf00000001107f8a0392a169ce020d12d6%40reply.github.com&m_link_params%5Bemail%5D=1&m_cl=bt1&plain=1

Find out more
http://topface.com/mp/?m_pl=st&m_action=inviteContact&m_page=Topface%5CProfile%5CProfilePage&m_page_params%5Buser_id%5D=95773512&m_link_params%5Bref%5D=m_inviteContact&m_link_params%5Bmailsrv%5D=gmail.com&m_link_params%5Bm_id%5D=b46f8b0ce6704d5cd4831ef4ae457893&m_link_params%5Bm_t%5D=1428785358&m_link_params%5Bm_exp%5D=&m_link_params%5Bsender_id%5D=95773512&m_link_params%5Binvite_email%5D=reply%2B00420e538b5e9494e7b0c8f169d8bad58b149882820a556692cf00000001107f8a0392a169ce020d12d6%40reply.github.com&m_link_params%5Bemail%5D=1&m_cl=bt2&plain=1

Good luck, 
Topface team

**Comment by barryBithead** [comment]
The latest version of the code seems to have the same bug as well...
