### ISSUE TITLE
HideMetroDialogAsync not working

### ISSUE THREAD

**Issue by AidasS** [MahApps/MahApps.Metro#1386]
Hello,

I'm new one so it might be a stupid question, but I was using old version of Mahapps.Metro from 2013 and now I updated to newest one and HideMetroDialogAsync started giving me a Exception: "Unable to find the dialog closing storyboard. Did you forget to add BaseMetroDialog.xaml to your merged dictionaries?"

Checked twice, tried to go back to old version and indeed this is cause by the updated version of Metro, all of the code is same. 

A little of the code how I am calling and ending the dialog:

        private async void OpenNewCase(object sender, RoutedEventArgs e)
        {
            _NewCaseOne = new NewCaseOne();
            dialog = (BaseMetroDialog)_NewCaseOne;
           await this.ShowMetroDialogAsync(dialog);

        }
        public async void CloseNewCase()
        {
            await this.HideMetroDialogAsync(dialog);
        }

Dialog opens fine, works but doesn't want to close. What could be the reason?
Thank you!

**Comment by oshpak92** [comment]
The same problem. Workaround is to move resources to your App.xaml then exception should disappear. 
```
<Dialog:BaseMetroDialog.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="/Resources/Icons.xaml"/>
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Dialog:BaseMetroDialog.Resources>
```
For some reasons you can't add resources to your dialogs.

**Comment by FrankMarin** [comment]
This works for me:
Add resources to a Grid, then you can use icons.

`<Grid.Resources>`
`            <ResourceDictionary>`
`                <ResourceDictionary.MergedDictionaries>`
`                    <ResourceDictionary Source="/Resources/Icons.xaml" />`
`                </ResourceDictionary.MergedDictionaries>`
`            </ResourceDictionary>`
`        </Grid.Resources>`
