### ISSUE TITLE
Metro but transparent

### ISSUE THREAD

**Issue by michal12PN** [MahApps/MahApps.Metro#1413]
Hello:)

First of all I want to say, that Yours application is brilliant!!!. I have never seen such simply way to do such great UI thanks this layer! Especially when somebody like me is just beginner:). Can I ask about 2 little things?:)
1. How set metrowindow as transparent? I'm tying to do tool bar on top screen, so I want have window transpart, the only non transparent thing will be border with my background as image? How I can archieve this in Your packet? Becouse in normal WPF I made this, but in MetroWindow I have still black background
2. Maybe it's funny, but is there any method or properties in Your packet, to enable snapping to edge of screen?

Thanks really in advance for any help!!

**Comment by wojiaofsp** [comment]
hi Amrykid 
"For your first question, you should be able to set AllowsTransparency to true and set Background to Transparent. Maybe set ShowTitlebar to false as well."
it didn't work now.The windows' background is Black.not transparent.please help me.thanks

**Comment by punker76** [comment]
@wojiaofsp you must do this at the loaded window event

**Comment by wojiaofsp** [comment]
@punker76 thanks alot,I've find this answer,thanks :)
