### ISSUE TITLE
DragMove when TitleBar is hidden

### ISSUE THREAD

**Issue by AleksandarDev** [MahApps/MahApps.Metro#1429]
This "feature" is redundant when implementing custom title bar. I set `ShowTitleBar` to false and implemented my own title bar, I now don't want to allow user to drag window anywhere else other than with my title bar. Is there a flag already that I don't know about?

**Comment by punker76** [comment]
you can now set the `IsWindowDraggable` property on `MetroWindow` (latest alpha)

**Comment by AleksandarDev** [comment]
Great, thanks!
