### ISSUE TITLE
Expose Progress Ring Ellipse Diameter Properties

### ISSUE THREAD

**Issue by chenliu0831** [MahApps/MahApps.Metro#1431]
Currently it's set as width/8 which is not flexible for many practical use. It would be nice to expose some of the private properties so users can customize. Thanks.

**Comment by HugzM** [comment]
Hello, I'm interested to work on it !
Sorry for dummy question by i'm new contributor on opensource projects what is the next step ? I need to create a new pull request ?

**Comment by chenliu0831** [comment]
@HugzM Is this resolved? Can I close this?
