### ISSUE TITLE
Command Binding with an ItemsSource on a DropDownButton

### ISSUE THREAD

**Issue by dealproc** [MahApps/MahApps.Metro#1443]
For the list of items, how do I bind the item in the list to some sort of a command handler? My expectation of this control was that it would allow me to create a "new" button, and I could provide one of several types of "new" things to do.

I'm presently working with Caliburn Micro, so if someone could specifically respond on that front, I'd be even more appreciative.

Thanks.

**Comment by punker76** [comment]
@dealproc Is this still an issue for you if you try the 1.3.0?

**Comment by dealproc** [comment]
That job has long since passed on... Will take a look at this however, as I believe i still have use cases for this. I'll close this case, for now, and re-open if necessary.
