### ISSUE TITLE
Window corner resize not working

### ISSUE THREAD

**Issue by Bodekaer** [MahApps/MahApps.Metro#1462]
With the latest alpha (via NuGet), when I try to resize a Window from e.g. the lower right corner, it only allows me to resize up/down, or left/right. Not both simultaneously.
I'm using CleanWindowStyle.

**Comment by navhaxs** [comment]
I can reproduce this on MahApps.Metro (1.1.2 from nuget) as long as GlowBrush is set on the MetroWindow, for example:

    GlowBrush="Red"
