### ISSUE TITLE
Glitching UI

### ISSUE THREAD

**Issue by Glowings** [MahApps/MahApps.Metro#1473]
I have created a video to explain the issue I am experiencing, 

Sorry for the bad quality used my phone to try and show there is no interference from other applications
Also Recorded with a program.
Sorry if this a duplicate, If you would like any other information just contact me via a reply on this or directly to my email at iCamelized@gmail.com

Video 1 ( Phone [ External ] ) - http://youtu.be/zjUBQEkQqsQ
Video 2 ( PC [ Internal ] ) - http://youtu.be/IDFeTHPtkKw
ps.
This issue is intermittent and I don't know whats causing it,

**Comment by punker76** [comment]
@Glowings is this still an issue?
