### ISSUE TITLE
Modal dialogs and VS window style does not work

### ISSUE THREAD

**Issue by robertstefan** [MahApps/MahApps.Metro#1476]
Using the VS window style and the modal windows [tested with MessageAsync and LoginAsync with the latest source from git] gives not the most pleasant result:

![image](https://cloud.githubusercontent.com/assets/1000718/3606568/74e51a9c-0d38-11e4-8f81-9d1972f70de0.png)
 
@djengineerllc @Amrykid , what am I missing? :(

Off-topic a little bit: What is the problem/reason why the min-max-close group buttons look so strange? :unamused:

**Comment by punker76** [comment]
@robertstefan dialogs and VS window style works now with the latest alpha (and upcoming v1.2.0)

![image](https://cloud.githubusercontent.com/assets/658431/8020696/1fc7c802-0c83-11e5-9937-8508b7ac1fe4.png)

**Comment by emodel** [comment]
In App.xaml replace Application.Resources node with this (it worked for me): 

    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
                
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Themes/Light.Blue.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>
    
Regards
