### ISSUE TITLE
ControlsHelper.IsUnderlined Position

### ISSUE THREAD

**Issue by amkuchta** [MahApps/MahApps.Metro#1478]
@flagbug is it possible to adjust where the underline on the TabControl is based on where the TabControl is located (i.e. top of the window vs. left side vs. right side).  I think for this to be a completely functional property, the "Underline" should transition with the control:

Examples:
If the TabControl is docked to the left of the screen, the underline should be on the right
If the TabControl is docked to the right of the screen, the underline should be on the left

**Comment by HugzM** [comment]
I'll working on it
