### ISSUE TITLE
controls inside MetroContentControl not inheriting styles

### ISSUE THREAD

**Issue by markawil** [MahApps/MahApps.Metro#148]
I created a UserControl then changed it to a Controls:MetroContentControl, it shows up fine inside a ContentControl on the Main Window.  But the textboxes and buttons are not inheriting the default metro styles.  The buttons that are on the Main Window however do inherit the styles correctly.

I don't want to make my UserControl a MetroWindow as it loads inside the main window dynamically.

So basically, how do you get a UserControl to inherit the Metro styles?

thanks.

**Comment by dcuccia** [comment]
I had the same issue. Deleted the "UserControl.Resources" section bringing in the MahApps.Metro styles, and things propagated correctly.
