### ISSUE TITLE
MessageBox like Metro

### ISSUE THREAD

**Issue by NukeDev** [MahApps/MahApps.Metro#1488]
Hello, 
the message box like metro dosen't work.
Wich is the correct code?

Cordially

**Comment by akshithrajesh** [comment]
How to Call Async Show Dialog Method in Usercontrol

(When I tried to call from Usercontrol I am getting Error ) 

So How can I call Async await Show Dialog Methods in Usercontrol in wpf

**Comment by afreeman2** [comment]
can you rewrite code in vb plz?

**Comment by RikenChoksi** [comment]
can change font color of Message box ?
