### ISSUE TITLE
Fullscreen with no Windows Taskbar

### ISSUE THREAD

**Issue by beachwalker** [MahApps/MahApps.Metro#1495]
When opening up a Standard WPF window with properties set as follows:
  WindowStyle="None"
  ResizeMode="NoResize"
  WindowState="Maximized"
  ShowInTaskbar="False"
the Window should appear in fullscreen mode and the windows taskbar should be hidden by the window (no start button etc. visible).
Currently, the MetroWindow gets maximized (and you can also hide the title bar) but the Windows Taskbar is still visible at the bottom.

**Comment by Kabennsky** [comment]
How does this IgnoreTaskBarOnMaximize works? Is it possible to do something like this on a normal Window? Its a ugly problem when working with Borderless windows. Already looked for usage in code, but it seems not to be used.
