### ISSUE TITLE
TextBox.TextBoxHelper.ButtonCommand won't execute

### ISSUE THREAD

**Issue by PantelisAr** [MahApps/MahApps.Metro#1502]
I have a search TextBox bound to a command on my viewmodel which does not execute. Is there anything that could be blocking the command? 

    <TextBox 
        x:Name="TextBoxSearch"
        Grid.Column="2" Margin="8" Width="300"
        HorizontalAlignment="Right" VerticalAlignment="Center"
        mahapps:ControlsHelper.ButtonWidth="28"
        mahapps:TextboxHelper.Watermark="{lex:Loc inStorHDRadio:Lang:search}"                            
        mahapps:TextboxHelper.ButtonCommand="{Binding SearchChannelsCommand}"
        mahapps:TextboxHelper.ButtonCommandParameter="{Binding ElementName=TextBoxSearch, Path=Text}"
        Style="{DynamicResource SearchMetroTextBox}" />

    private RelayCommand<string> _searchChannelsCommand;
    public RelayCommand<string> SearchChannelsCommand { get { return _searchChannelsCommand; } }

    // Search channels by keyword command
    _searchChannelsCommand = new RelayCommand<string>(
        keyword =>
        {
            if (string.IsNullOrWhiteSpace(keyword))
                return;

           // Populating an observable collection here based on keyword           
       });

**Comment by punker76** [comment]
@PantelisAr is this still an issue?

**Comment by PantelisAr** [comment]
I've implemented it with an ICommand eventually, since I could not figure out what was wrong at that point.
