### ISSUE TITLE
How to adjust the color of the WindowCommands separator?

### ISSUE THREAD

**Issue by laschmoove** [MahApps/MahApps.Metro#1503]
Hi,
I am not sure if this is an issue or just a mistake on my side. Maybe someone can help me out:

I use the WindowCommands as you suggest in your QuickStart guide and it looks fine. Like this:

![nosplash](https://cloud.githubusercontent.com/assets/417399/3934997/1801a99c-2491-11e4-9b07-e74da9a21387.JPG)

But as soon as the window is not the first to be started, but is proceeded by a splash screen (which is an ordinary window, not a MetroWindow), my TitleBar changes to this:

![withsplash](https://cloud.githubusercontent.com/assets/417399/3934996/17ff64f2-2491-11e4-94df-c935b1af224d.JPG)

What may I be doing wrong? And is there a way to set the color of the separator or remove it?

Thanks for helping!
Best,
laschmoove

**Comment by punker76** [comment]
@laschmoove this should be fixed by https://github.com/MahApps/MahApps.Metro/pull/1788
after this change, the separator should use the `IdealForegroundColorBrush` correctly.
