### ISSUE TITLE
NumericUpDown event handlers

### ISSUE THREAD

**Issue by PhilPJL** [MahApps/MahApps.Metro#1512]
Some of the events on NumericUpDown are badly named.  It's a breaking change but could we rename

IncrementValue -> ValueIncremented
DecrementValue -> ValueDecremented

**Comment by collegedude** [comment]
Since the ValueIncremented and ValueDecremented events are raised before the Value property is changed, I would think the correct names should be ValueIncrementing and ValueDecrementing?
