### ISSUE TITLE
App after publish crash

### ISSUE THREAD

**Issue by RiderOfTheli** [MahApps/MahApps.Metro#1531]
I was trying to publish my WPF app with MahApps.metro dll. After publish it throws Program has stopped working. I've add strong names for MahApps.Metro. When I'm trying to biuld it it works fine...

Thank you very much for any suggestions

**Comment by tivie** [comment]
Actually I have the exact same issue. In the debugger, the application runs fine, but when running the app.exe from debug/release folder it crashes without any relevant message. The event logger show exactly the same thing @RiderOfTheli reports.

For testing purposes I've done the following:

 - Create a new C# WPF App targeting .net 4
 - Use NuGet to import MahApps.Metro
 - Add the following lines to App.xaml
```xml
<Application.Resources>
  <ResourceDictionary>
    <ResourceDictionary.MergedDictionaries>
      <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
      <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
      <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Colors.xaml" />
      <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/Blue.xaml" />
      <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/BaseLight.xaml" />
    </ResourceDictionary.MergedDictionaries>
  </ResourceDictionary>
</Application.Resources>
```

As soon as I add those lines, the app.exe crashes. Any suggestions?

**Comment by balkarov** [comment]
I have exactly the same problem! Has anyone found a solution?

**Comment by bigworld12** [comment]
Upgrade to .net 4.6 check if this fixes
