### ISSUE TITLE
some unexpected behaviors from minimize-restore-animations changes

### ISSUE THREAD

**Issue by punker76** [MahApps/MahApps.Metro#1539]
i reverted some changes from the pr ##1514 minimize-restore-animations.

what happens:

- if a window starts with ```WindowState = "Maximized"``` the window is not completely maximized
- nasty window painting, if a user maximize or minimize the window (caused by ```WindowStyle = WindowStyle.SingleBorderWindow`` )

![2014-09-05_13h16_23](https://cloud.githubusercontent.com/assets/658431/4165320/dc5f3028-3500-11e4-9ca7-4e1a5bc6f3f0.png)
![2014-09-05_13h16_40](https://cloud.githubusercontent.com/assets/658431/4165321/deb67534-3500-11e4-8080-d6c447c76f4f.png)

/cc @Amrykid @flagbug @mrahhal @AdditionalPylons any ideas? if it's possible to fix, then it would be nice to enable/disable this, cause some people are not interessted by this animation (maybe)...

**Comment by AdditionalPylons** [comment]
@punker76 Hey, I'm currently looking into this again (After like... 7 months of not even looking at this problem). When you have time, could you try out https://github.com/AdditionalPylons/MahApps.Metro/tree/minimize-restore-animations
and let me know if the nasty painting bug is still there? I stepped through the frame by frame of a video capture, and can't seem to reproduce this issue. I assume that I'm either not doing the correct steps to get this bug, or my video capture missed the frames or something.

Thanks!
