### ISSUE TITLE
External Dialog Title and Button follows Internal Padding

### ISSUE THREAD

**Issue by thalelinh** [MahApps/MahApps.Metro#1544]
After some tests I found out that the external Dialogs, called with both ShowModalDialogExternally() and ShowDialogExternally(), kind of follows the last Internal Dialog shown size and their title appears lower than they should, and buttons higher. And even more if the dialog has not been shown internally.

First: Open an External one... Title is almost at the middle, and so does the button.
![1](https://cloud.githubusercontent.com/assets/8299832/4234479/78ee7088-39b7-11e4-8188-fb66943197ad.png)

Then, open an Internal. Title is as up as it gets, and button down low.
![2](https://cloud.githubusercontent.com/assets/8299832/4234480/78fab1ae-39b7-11e4-8e15-d2aeb9e0363b.png)

Later, opening an external shows the title with a little less top distance and button with less down distance.
![3](https://cloud.githubusercontent.com/assets/8299832/4234481/78fc5400-39b7-11e4-947f-9ad56488f442.png)

When opening an Internal on a Maximized window, title is still up and button down, as I would like it...
![4](https://cloud.githubusercontent.com/assets/8299832/4234483/7902036e-39b7-11e4-998f-8f3b4279aa37.png)

And the same occurs with it on the External.
![5](https://cloud.githubusercontent.com/assets/8299832/4234482/78ffb79e-39b7-11e4-9f8f-c3ed93477e94.png)

**Comment by punker76** [comment]
@thalelinh is still present with the latest alpha?
