### ISSUE TITLE
TextboxHelper.ClearTextButton is always visible in execution

### ISSUE THREAD

**Issue by kanekotic** [MahApps/MahApps.Metro#1564]
This attached behaviour shows in execution time by default and when 

'Setter Property="controls:TextboxHelper.ClearTextButton" Value="False" /'

It still do nothing till
'Setter Property="controls:TextboxHelper.ClearTextButton" Value="True" /'

Any idea why it still showing even if property is set to false?

**Comment by punker76** [comment]
@alvarojosepl with which control happens this issue? can you re-test this with the latest alpha version (master-branch)
