### ISSUE TITLE
Microsoft Shell Library files reuse the Microsoft Shell namespace, causing conflicts with the actual .NET shell implementation

### ISSUE THREAD

**Issue by rgemperl** [MahApps/MahApps.Metro#1570]
The namespace in these files should be changed everywhere in these files to be MahApps.Metro.Windows.Shell.  Then in places where these class are used, the MahApps.Metor.Windows.Shell should be referenced.

The same applies to the use of the namespace Standard in all files in ./Standard/*.xaml.

**Comment by punker76** [comment]
we leave this as it is.
