### ISSUE TITLE
MetroCircleToggleButtonStyle BorderBrush not using Template Binding

### ISSUE THREAD

**Issue by johanneswanzek** [MahApps/MahApps.Metro#1573]
MetroCircleToggleButtonStyle Ellipse used for MouseOver Border Effect not using BorderBrush Tempalte Binding.

https://github.com/MahApps/MahApps.Metro/blob/master/MahApps.Metro/Styles/Controls.Buttons.xaml

Line 648:
Stroke="#ADADAD"

Compared to MetroCircleButtonStyle
Line 103:
Stroke="{TemplateBinding BorderBrush}"

**Comment by punker76** [comment]
fixed with 1de3304d40cb7425c346e06ff0d65be954e88836
