### ISSUE TITLE
GlowBrush showing on top of child windows

### ISSUE THREAD

**Issue by NickThissen** [MahApps/MahApps.Metro#1578]
I found a small issue when using a GlowBrush in combination with 'child windows', by which I mean a window that has its Owner property set to some other window. 

If you put a child window on top of its parent, then maximize the parent (the child window will remain visible on top because it's a child window), then restore the parent window size (double click header), the glow of the parent window will show on top of the child window:
![borders](https://cloud.githubusercontent.com/assets/7407292/4592021/9da960e8-5075-11e4-8135-b7c6485be350.jpg)

It seems the glow brush window is going on top of the child window, which should not be possible (a child window should always be on top of its parent I believe?). 

The screenshot shows 'clean' windows but the same issue appears with regular MetroWindows.

**Comment by punker76** [comment]
@NickThissen this should be fixed with latest alpha
