### ISSUE TITLE
Allow configuration on MetroWindow WindowsCommands Template

### ISSUE THREAD

**Issue by shudson302** [MahApps/MahApps.Metro#1581]
The ControlTemplate.Triggers has a hardcoded color set for the IsEnabled = False

```xml
<Trigger Property="IsEnabled" Value="false">
    <Setter Property="Foreground" Value="#ADADAD" />
</Trigger>
```

There is no way to alter this behavior without rewriting the template. 
Could you please make this a color resource so that it can be changed.

This is under `Themes/MetroWindow.xaml`

**Comment by punker76** [comment]
fixed by d29bcf004526583e92fe8c64567af728bca10893
