### ISSUE TITLE
Provide debugging symbols on symbolsource.org for easier debugging

### ISSUE THREAD

**Issue by BrunoJuchli** [MahApps/MahApps.Metro#1583]
It would be nice if you could publish the debugging symbols to symbolsource.org so as to make debugging easier:

[Symbolsource.org: Creating symbol packages with nuget](http://www.symbolsource.org/Public/Wiki/Publishing)

(If i'd know enough about it i would have provided a pull request directly ;-) ).

**Comment by BrunoJuchli** [comment]
duplicate #1879

**Comment by punker76** [comment]
the pdb files are now included
