### ISSUE TITLE
Titlebar foreground color

### ISSUE THREAD

**Issue by ghost** [MahApps/MahApps.Metro#160]
Is it currently possible to change the titbar foreground color? This snippet from MetroWindow.xaml seemed to indicate that it's hardcoded:

``` xml
<TextBlock
                                    x:Name="WindowTitleTextBlock"
                                    Grid.Column="1"
                                    Text="{TemplateBinding Title}"
                                    HorizontalAlignment="Left" 
                                    TextTrimming="CharacterEllipsis"
                                    VerticalAlignment="Center" 
                                    Margin="8 -1 0 0" 
                                    FontSize="16" 
                                    FontFamily="{DynamicResource HeaderFontFamily}"
                                    Foreground="White"/>
```

When one is changing the background color to a lighter color (as described in [issue 133](https://github.com/MahApps/MahApps.Metro/issues/133)), the foreground needs to change or the contrast is too low.

Is it possible that this can be pulled out into a resource in the accent files?  Presumably the min/max/close normal highlight colors would also have to be theme-able.

Thanks.

**Comment by crclayton** [comment]
Is it possible to get this same feature for the TitleBackground?
