### ISSUE TITLE
How to display a flyout from a XAML UserControl

### ISSUE THREAD

**Issue by rcalado** [MahApps/MahApps.Metro#1620]
I am using MahApps Version 0.14.0.0
Is there a way to get the FlyoutsControl to work from within a xaml UserControl?

Take your MetroDemo Sample UI for an example.....you call usercontrols for each of your tab screens.  (which is exactly what we do).  The main functionality is contained within each exampleView Usercontrol.  So getting the Flyout to work from here would be fantastic since the usercontrol is already "wrapped" by the MetroWindow.

```xaml
 <Controls:MetroAnimatedSingleRowTabControl Grid.Row="1" x:Name="MainTabControl">
                <TabItem Header="buttons">
                    <exampleViews:ButtonsExample DataContext="{Binding}" />
                </TabItem>
                <TabItem Header="text">
                    <exampleViews:TextExamples DataContext="{Binding}" />
                </TabItem>
</TabControl>
```

If anyone has come up with a solution or even a hack to get the flyout control to work from the UserControl please paste a sample of what you did to get it to work.

**Comment by rcalado** [comment]
Just wanted to comment back that I was able to get this to work following AndySF's solution.
Created the mainFlyout control on the "mainwindow" control  and was able to launch the flyout from within the tab user control with AndSF's code.

**Comment by maciz84** [comment]
I still think this should be a feature out of the box the need to use this control in a usercontrol is very common

**Comment by barishamil** [comment]
Flyouts should appear in MainWindow in visual tree regardless of where you put them like Popups

**Comment by CDDFERREIRA** [comment]
I understand the solution provided to access the Flyout on the UserControl form the Parent. 
However, how can I do this if I am using the MVVM design?

**Comment by mxsoftware** [comment]
See: https://github.com/alsiola/FlyoutManager.
