### ISSUE TITLE
Controls:MetroWindow Question

### ISSUE THREAD

**Issue by ghost** [MahApps/MahApps.Metro#1633]
Hi there is it possible to use a menu inside Controls:MetroWindow for a button so for example if user clicks Settings it will dropdown a menu like contextmenu strip?

**Comment by fandisus** [comment]
Good @thoemmi sir, can you please specify the namespace of Infrastructure:ContextMenuOnLeftClickBehavior

**Comment by thoemmi** [comment]
`ContextMenuOnLeftClickBehavior` is not part of MahApps.Metro but written
in another project by mine. You can find the code here:
https://github.com/thoemmi/Solutionizer/blob/master/Solutionizer/Infrastructure/ContextMenuOnLeftClickBehavior.cs


Best regards
Thomas
