### ISSUE TITLE
How can I get rid of border around controls (when selected)

### ISSUE THREAD

**Issue by danwalmsley** [MahApps/MahApps.Metro#1644]
![comboborder](https://cloud.githubusercontent.com/assets/4672627/4975358/d500e50a-68d7-11e4-888f-0063ea31b275.png)
![menu](https://cloud.githubusercontent.com/assets/4672627/4975359/d7e51a3e-68d7-11e4-9235-dd3bee744e78.png)

There seems to be a white border around my controls, when they have focus or are selected. The first image is a combobox, the second obviously a menuitem.

I know this may not be a bug but I didn't know how else to contact you.

Thanks Dan

**Comment by kishorejangid** [comment]
@danwalmsley  This is not about FocusVisualStyle, but may be you have to remove the Border for those controls.
