### ISSUE TITLE
Weird Border When receiving WS_HSCROLL

### ISSUE THREAD

**Issue by myrnazhou** [MahApps/MahApps.Metro#1661]
Hi Guys,
I have issue when I want to receive horizontal scroll in MahApps window. So in order to receive horizontal scroll I need to tell the window to use WS_HSCROLL. But then there is this weird border everytime the window loses focus 

![weird border](https://cloud.githubusercontent.com/assets/1266072/5136670/fb871f04-7166-11e4-8b14-4d00c4f03e90.PNG)

Below is the code that I added in the MetroDemo\MainWindow.xaml.cs:

        protected override void OnSourceInitialized(EventArgs e)
        {
            base.OnSourceInitialized(e);
            HwndSource source = PresentationSource.FromVisual(this) as HwndSource;

            int style = GetWindowLong(source.Handle, GWL_STYLE);
            SetWindowLong(source.Handle, GWL_STYLE, style | WS_HSCROLL);
            SetWindowPos(source.Handle, IntPtr.Zero, 0, 0, 0, 0, SWP_NOMOVE | SWP_NOSIZE | SWP_NOZORDER | SWP_FRAMECHANGED);

            source.AddHook(WndProc);
        }

**Comment by punker76** [comment]
i think thats not possible to fix for you, too specialized... sorry
