### ISSUE TITLE
how do i change the window close button's color to red ?

### ISSUE THREAD

**Issue by trlanfeng** [MahApps/MahApps.Metro#1682]
I find the property named "windowclosebuttonstyle" , but i don't know how to change it , i just want to change the close button's color to red . I need the help .

**Comment by vekcro** [comment]
> I find the property named "windowclosebuttonstyle" , but i don't know how to change it , i just want to change the close button's color to red . I need the help .

Use OverrideDefaultWindowCommandsBrush property
