### ISSUE TITLE
Watermark/Text Alignment of DatePicker and NumericUpDown controls

### ISSUE THREAD

**Issue by ankushrayabhari** [MahApps/MahApps.Metro#1683]
I am using v0.14. When I set the HorizontalContentAlignment of either a DatePicker or NumericUpDown control, nothing happens and it stays right aligned (numeric up down) or left aligned ( date picker).

**Comment by punker76** [comment]
@ankushrayabhari the content of the `NumericUpDown` is already changable by `TextAlignment` but now also by `HorizontalContentAlignment`. Fixed also Horizontal-/VerticalContenAlignment.
-> d68ca7e299332a19a12303beb7a0ad9c73d7cfa5
