### ISSUE TITLE
ILMERGE Compatibility

### ISSUE THREAD

**Issue by jammerxd** [MahApps/MahApps.Metro#1689]
Hello, 
I have a project and I used ILMerge.exe to combine all the referenced dlls into the project and then on project run, it crashes with App.xaml being the problem:

It could not locate any of the MahApps dll files because they were merged into one exe. The part that threw the exception was the ResourceDictionary.MergedDictionaries and all the ResourceDictionary tags. The exception was file not found. I am assuming that the program is still looking in the directory for the dll files. Is there any way to make it not be dependent on the external files and look internally for them since they are merged into one exe?
Screenshot: http://gyazo.com/c948dd42066431e9cb966d6f5d319f59

**Comment by HerrVoennchen** [comment]
Since ILMerge does not merge WPF assemblies, i use fody costura do accomplish this. It works the same as ILMerge. Some assemblies are not found anyway so i recommend to use the "CreateTemporaryAssemblies" Option. 

https://github.com/Fody/Costura

**Comment by timotei** [comment]
I know this is pretty old, but FYI IL Repack has support for WPF apps merging: https://github.com/gluck/il-repack

**Comment by Suplanus** [comment]
ILRepack have also problems with MahApps ressources:
https://github.com/gluck/il-repack/issues/170
