### ISSUE TITLE
Initialization of control failed because "The calling thread cannot access this object because a different thread owns it."

### ISSUE THREAD

**Issue by eggapauli** [MahApps/MahApps.Metro#1690]
Creating a new window from an STA thread with a random control (I tried a `ComboBox` as well as a `TextBox`) fails with the exception mentioned in the title if your application references MahApps' `Styles/Controls.xaml` and `Styles/Colors.xaml`. This doesn't happen when you don't reference any resources. [See this gist](https://gist.github.com/eggapauli/22a93f385d3bdf61942f). Note that this is a simplified example to keep the main aspects clear.

**Comment by eggapauli** [comment]
Sorry, but what does this mean?

**Comment by punker76** [comment]
@eggapauli maybe a mistake to close this, but i think it's not a mahapps problem...
-> https://gist.github.com/eggapauli/22a93f385d3bdf61942f#comment-1348650

**Comment by eggapauli** [comment]
I also tried the suggested solution, but it didn't work. And it works as expected when the exact same code is used in native WPF. Any ideas?

**Comment by thoemmi** [comment]
Try to use window resources instead of application resources, see #1792.

**Comment by eggapauli** [comment]
I tried that just now and it seems to work, thanks.
