### ISSUE TITLE
Problem running demo application

### ISSUE THREAD

**Issue by Ruwan-Ranganath** [MahApps/MahApps.Metro#1695]
I downloaded the application MahApps.Metro-master' file from the page and after i tried to open 
Samples--> MetroDemo--> MainWindow.xaml 
It says 4 errors : 
-------1----
Error	18	The name "MainWindowViewModel" does not exist in the namespace "clr-namespace:MetroDemo".	C:\Users\Ruwan Ranganath\Downloads\MahApps.Metro-master\MahApps.Metro-master\samples\MetroDemo\MainWindow.xaml	22	23	MetroDemo
==================

------------2 ------------------
Error	21	The build restored NuGet packages. Build the project again to include these packages in the build. For more information, see http://go.microsoft.com/fwlink/?LinkID=317568.	C:\Users\Ruwan Ranganath\Downloads\MahApps.Metro-master\MahApps.Metro-master\samples\MetroDemo\MetroDemo.csproj	342	5	MetroDemo
==========================================

------------------3---------------
Error	8	The name "ToggleSwitch" does not exist in the namespace "clr-namespace:MahApps.Metro.Controls".	C:\Users\Ruwan Ranganath\Downloads\MahApps.Metro-master\MahApps.Metro-master\MahApps.Metro\Styles\Controls.xaml	1	1	MahApps.Metro.NET45
================================================

------------------4-------------------
Error	9	The name "ToggleSwitch" does not exist in the namespace "clr-namespace:MahApps.Metro.Controls".	C:\Users\Ruwan Ranganath\Downloads\MahApps.Metro-master\MahApps.Metro-master\MahApps.Metro\Styles\Controls.xaml	1	1	MahApps.Metro.NET45
===================================

I restored missing plugin from nuget manager by using restore button. sill not working , 
Thanks :+1:

**Comment by freMea** [comment]
Hi,

Same issue.

A release page with working demo would be useful to learn and see all the features in live. Source demo as if they were created by anyone using nuget package would be even more useful to learn.

1. I cloned to VS 2015, chosen Master Branch and opened the solution (I think I get the Master Branch like that, don't I ?). 
2. Then I Restore NuGet Pakages for solution: `All packages are already installed and there is nothing to restore.`
3. Clean Solution
```
1>------ Clean started: Project: Mahapps.Metro.Tests.NET40, Configuration: Debug Any CPU ------
2>------ Clean started: Project: MahApps.Metro.Caliburn.Demo.NET45, Configuration: Debug Any CPU ------
3>------ Clean started: Project: MahApps.Metro.Caliburn.Demo.NET40, Configuration: Debug Any CPU ------
4>------ Clean started: Project: MahApps.Metro.Demo.NET45, Configuration: Debug Any CPU ------
5>------ Clean started: Project: MahApps.Metro.Demo.NET40, Configuration: Debug Any CPU ------
6>------ Clean started: Project: MahApps.Metro.NET45, Configuration: Debug Any CPU ------
7>------ Clean started: Project: MahApps.Metro.NET40, Configuration: Debug Any CPU ------
========== Clean: 7 succeeded, 0 failed, 0 skipped ==========
```
4. Rebuild Solution _(55 errors, 185 warnings)_: _Rebuild All: 1 succeeded, 6 failed, 0 skipped_ [log (errors only)](http://pastebin.com/38snmTsh)
5. F5 Start Debugging => fail _(31 errors, 15 warnings)_ [log (errors only)](http://pastebin.com/r2CjRxW5)
6. Open MainWindow.xaml from default Demo.NET40 project _(32 errors, 15 warnings)_ [log (all)](http://pastebin.com/awSw3geS)

Did I miss something to make the demo sources run?

**My setup**:

- VS 2015 community (last update)
- Windows 10 pro x64 (last update)

**Comment by alexjw90** [comment]
I had this issue as well and fixed it.

solution: clean/build each project (.proj) individually.

reason: the referenced .dll for each project is not yet created when you pull down the code, therefore the references are broken until you build the projects.
