### ISSUE TITLE
Watermark with icon?

### ISSUE THREAD

**Issue by JobaDiniz** [MahApps/MahApps.Metro#1697]
Is there a way to set TextBox Watermark attached property to use icon + text?

**Comment by aloisdg** [comment]
Are you looking for a native way to do it or a custom way can fit your need ?

**Comment by JobaDiniz** [comment]
I

**Comment by aloisdg** [comment]
Ok check this : [Watermark / hint text / placeholder TextBox in WPF](http://stackoverflow.com/a/836463/1248177). I am using it right now ! (Well we are a bit of-topic)

**Comment by JobaDiniz** [comment]
Thanks, I'll look into it.

**Comment by AhmadMustafaa** [comment]
Guys did you find any solution of icon in watermark ?
