### ISSUE TITLE
DropdownButton with all UpperCase label

### ISSUE THREAD

**Issue by fjlaga** [MahApps/MahApps.Metro#1701]
How can the DropdownButton be made to show its label in all upper case like a regular button? All my attempts to do something similar to what the Button does with the ToUpperConvert and ControlTemplate.Triggers have failed miserably. Any help is greatly appreciated.
-Frank

**Comment by punker76** [comment]
fixed with 10b684c2680999eb1beae5a590e3b20f9f9af45d
you can now set `Controls:ControlsHelper.ContentCharacterCasing="Upper"` on yout `DropDownButton`s.
