### ISSUE TITLE
MetroDialog default button

### ISSUE THREAD

**Issue by cham01** [MahApps/MahApps.Metro#1715]
I'm a newbie with mahapps (which I think is superb BTW), but having a problem with default buttons on a metrodialog. It may be related to issues #773 and / or #1684 which I believe are fixed in the version I'm using (1.0.0.0). 

I'm using a standard dialog with three buttons using ShowMessageAsync. I understand from the above issues that when using MessageBoxStyle.AffirmativeAndNegativeAndSingleAuxiliary,  the Negative button gets focus by default when the dialog opens (which I can see when tabbing between the three buttons). The issue really is that the first of the three buttons (the affirmative) looks like it is the active button based on it's style being different from the other two (visually the affirmative button looks like it is the active button). Its not overly obvious that the negative button has focus, so when you open the dialog and press ENTER you think you are pressing "affirmative", but actually the result is negative.

Is there any way of either choosing the active / focussed button in code using a property maybe or by making all three buttons visually styled the same ?

I can't find any way of doing this.

**Comment by punker76** [comment]
Default button for message dialog can now be set by the [new settings property](https://github.com/MahApps/MahApps.Metro/commit/da43741f4d7ebe16aa02974c6daa24a90c97abf9) `DefaultButtonFocus`, available in v1.2.3
