### ISSUE TITLE
TransitioningContentControl should block KeyDown and MouseDown event when transitioning.

### ISSUE THREAD

**Issue by stackia** [MahApps/MahApps.Metro#1726]
I use TransitioningContentControl as a page container in my app. User can navigation between pages with cool animations provided by TransitioningContentControl. If I have a button in one page which navigates to another page on clicked, the user can click it several times before the button transitioning out, which causes a mess that several pages initialized and pushed to the navigation stack.
The solution is simple, just block KeyDown and MouseDown event from passing down to the content controls.

In TransitioningContentControl.cs, add the following lines to the class constructor:
```c#
            PreviewMouseDown += (sender, args) =>
            {
                args.Handled = IsTransitioning;
            };
            PreviewKeyDown += (sender, args) =>
            {
                args.Handled = IsTransitioning;
            };
```

**Comment by punker76** [comment]
@stackia I think this should be done by the user itself. So other users can be confused if MahApps doesn't allow mouse down and key down in some situations.
