### ISSUE TITLE
ControlsHelper.IsUnderlined Exception

### ISSUE THREAD

**Issue by alvarojosepl** [MahApps/MahApps.Metro#1730]
After updating to latest nuget package, and run I get:

System.InvalidOperationException: Property path is not valid. 'ControlsHelper' does not have a public property named 'IsUnderlined'.

package.config regarding are:
 - package id="MahApps.Metro" version="1.0.0.0" targetFramework="net451" 
 - package id="MahApps.Metro.Resources" version="0.4.0.0" targetFramework="net451" 

this probably is happening when trying to load of tab control. This is the only extra information I could  add.

**Comment by flagbug** [comment]
As stated in the [Migration Guide](https://github.com/MahApps/MahApps.Metro/blob/4a632d28331cc83fd4d46882329c21455b85846c/docs/v1.0-Migration-Guide.md), the `IsUnderlined` property is now in the `TabControlHelper` class

**Comment by alvarojosepl** [comment]
thanks, and sorry for the misunderstanding.
