### ISSUE TITLE
An error occured while finding the resource dictionary "/Resources/Icons.xaml"

### ISSUE THREAD

**Issue by chickenxcouncil** [MahApps/MahApps.Metro#1733]
as the title says, that is my issue.  I installed the Mahapps.Metro.Resources package as well as the regular MahApps.Metro package.  all of the resources can be found from the Matro package but I cant find the resources one.  I am using Visual studio 2013 express.  Here is the output form the package installer.  Tried installing and uninstalling a few times

------- Installing...MahApps.Metro.Resources 0.4.0.0 -------
Attempting to resolve dependency 'MahApps.Metro (≥ 1.0.0)'.
Installing 'MahApps.Metro.Resources 0.4.0.0'.
Added file 'Entypo-license.txt' to folder 'MahApps.Metro.Resources.0.4.0.0\content\Resources'.
Added file 'Entypo.ttf' to folder 'MahApps.Metro.Resources.0.4.0.0\content\Resources'.
Added file 'Icons.xaml' to folder 'MahApps.Metro.Resources.0.4.0.0\content\Resources'.
Added file 'WindowsIcons-license.txt' to folder 'MahApps.Metro.Resources.0.4.0.0\content\Resources'.
Added file 'MahApps.Metro.Resources.0.4.0.0.nuspec' to folder 'MahApps.Metro.Resources.0.4.0.0'.
Added file 'MahApps.Metro.Resources.0.4.0.0.nupkg' to folder 'MahApps.Metro.Resources.0.4.0.0'.
Successfully installed 'MahApps.Metro.Resources 0.4.0.0'.
Adding 'MahApps.Metro.Resources 0.4.0.0' to WpfApplication1.
'Resources\WindowsIcons-license.txt' already exists. Skipping...
'Resources\Icons.xaml' already exists. Skipping...
'Resources\Entypo-license.txt' already exists. Skipping...
'Resources\Entypo.ttf' already exists. Skipping...
Added file 'packages.config'.
Successfully added 'MahApps.Metro.Resources 0.4.0.0' to WpfApplication1.
==============================

Any help would be appreciated, thanks!

**Comment by punker76** [comment]
@chickenxcouncil have you tried this?
```xaml
<ResourceDictionary Source="pack://application:,,,/YourAppName;component/Resources/Icons.xaml" />
```
