### ISSUE TITLE
When flyout visibility=visible, not closeable

### ISSUE THREAD

**Issue by vincegio** [MahApps/MahApps.Metro#1734]
When I assign my flyout to visible, the arrow close button is not doing anything.. Meaning that the flyout isn't closing.

After closer inspection I see that the default tag is "hidden", maybe this should be fixed with making it possible to close the flyout even if the visibility is visible. 
Just to smooth the edges :)

**Comment by erotavlas** [comment]
What is the workaround for enabling the close button (->)  at the very top?  Clicking it does nothing and I cannot edit it in Visual Studio (I can't click on it in the designer, and I don't know what property or control it belongs to in the flyout)

**Comment by punker76** [comment]
@vincegio @erotavlas there are 2 options to close a flyout

1. `IsOpen` : you can bind to the `IsOpen` property to handle the visibility
2. `CloseCommand` : you can bind an `ICommand` to this property and set the `IsOpen` property to `false` to close the flyout

**Comment by erotavlas** [comment]
Yes i realized it later I could use the CloseCommand, and deleted my post.  Thank you for the response and the alternative solutions.
