### ISSUE TITLE
MouseLeftButtonDown/MouseDown events are intercepted!!

### ISSUE THREAD

**Issue by sunfly2015** [MahApps/MahApps.Metro#1738]
![image1](https://cloud.githubusercontent.com/assets/10437586/5649331/e71390f0-96cf-11e4-8e10-d68d61cd5bb8.jpg)
![image2](https://cloud.githubusercontent.com/assets/10437586/5649330/e6a6a8f0-96cf-11e4-86c6-4b5519f59f7a.jpg)

Look above this simple animation，When you use the left mouse button it's effect is not normal, but use the right mouse button is normal.I also tried using MouseLeftButtonDown / PreviewMouseDown event triggers, also does not work.

The same effect in the general WPF form completely normal.

I wrote a few words on top of that is very difficult, because my English is not good.

Please allow me to repeat it again with a Chinese:
当我在一个完全空白的MahApps.Metro窗体中放置一个Canvas矢量图像，我想实现鼠标移动上去出现DropShadowEffect的效果，鼠标点击图片后DropShadowEffect效果的光晕颜色变色，鼠标弹起则颜色变回原来的，当鼠标移开之后DropShadowEffect效果消失。
可是我发现这些效果在使用鼠标右键的时候是正常的，但是如果使用鼠标左键，MouseDown时的效果没有动画，是直接变化到结果颜色，而MouseUp时完全没有任何效果，也就是说MouseUp效果没有被触发。

**Comment by sunfly2015** [comment]
After that I will upgrade to version 1.0.0.0, PreviewMouseDown event can be used.

**Comment by punker76** [comment]
should be fixed in v1.2.3
