### ISSUE TITLE
Passing parameters window

### ISSUE THREAD

**Issue by alexeygritsenko** [MahApps/MahApps.Metro#1743]
Arguments do not work when you create a window!
example:
public MainWindow(int idManager)
        {
            InitializeComponent();
            idManagerGlobal = idManager;
        }

causes the so:
Window main = new MainWindow(id);
                main.Show();
                this.Close();

**Comment by punker76** [comment]
@alexeygritsenko what doesn't work?

**Comment by alexeygritsenko** [comment]
Excuse me, is the error was not due to the design.
More information: "There was no appropriate constructor for type" WpfApplication2.MainWindow ".
The fact is that I do not always pass of the arguments...
Then I tried Optional Arguments, it did not help (

example:
public MainWindow(int idManager = 0)
        {
            InitializeComponent();
            //idManagerGlobal = idManager;
        }

**Comment by punker76** [comment]
@alexeygritsenko if this is the *main* window than you must remove the `StartupUri="MainWindow.xaml"` from your `App.xaml` and handle the showing self.

**Comment by alexeygritsenko** [comment]
Solution: create another constructor, only without parameters:
public MainWindow(int idManager) : this()
        {
            idManagerGlobal = idManager;
        }
