### ISSUE TITLE
VS theme Contextmenu

### ISSUE THREAD

**Issue by NicoTravassos** [MahApps/MahApps.Metro#1744]
Hi @punker76 why is my VS listbox Contextmenu looking so terrible Must i overwrite a style or something if so how do i do this? 

![untitled](https://cloud.githubusercontent.com/assets/7794777/5667555/5ceb95a6-9771-11e4-83ff-ba3c625d0858.png)

**Comment by robertstefan** [comment]
@NicoTravassos the way I managed to fix this was to create a new dictionary with the values for text brush and other elements that don't respect the design.
```
<Color x:Key="AccentColor">#2D2D30</Color>
    <Color x:Key="BlackColor">#000000</Color>
    <Color x:Key="WhiteColor">#2D2D30</Color>
    <FontFamily x:Key="DefaultFont">Segoe UI, Lucida Sans Unicode, Verdana</FontFamily>
    <Color x:Key="IdealForegroundColor">White</Color>
    <SolidColorBrush x:Key="IdealForegroundColorBrush" Color="{StaticResource IdealForegroundColor}"/>
    <SolidColorBrush x:Key="WindowTitleColorBrush" Color="{StaticResource AccentColor}" />

    <SolidColorBrush x:Key="BlackBrush" Color="{StaticResource BlackColor}" />
    <SolidColorBrush x:Key="WhiteBrush" Color="{StaticResource WhiteColor}" />
    <SolidColorBrush x:Key="AccentColorBrush" Color="{StaticResource AccentColor}"/>
    <SolidColorBrush x:Key="TextBrush" Color="{StaticResource BlackColor}" />
    <SolidColorBrush x:Key="BlackColorBrush" Color="{StaticResource BlackColor}" />
```

Used it once also, and this happened: https://github.com/MahApps/MahApps.Metro/issues/1476

**Comment by NicoTravassos** [comment]
@robertstefan Does this give it a original look like for the menuitem inside MENU will the contextmenu look the same?

**Comment by robertstefan** [comment]
@NicoTravassos yes. After i created the dictionary (with the color codes taken from the respective accent file provided for MA.M), everything turned out just fine in the end.

This is the final result, using the Cyan.xaml
![vs style](https://cloud.githubusercontent.com/assets/1000718/5688633/666c1744-9862-11e4-9604-4bf570e5a009.png)

**Comment by NicoTravassos** [comment]
@robertstefan  Thanks i will surley give this a shot also do maybe have a answer for this ? 

#1731 <----

**Comment by robertstefan** [comment]
Unfortunately no @NicoTravassos :(
Did not encounter this requirement in any of my projects; so can't help;

**Comment by NicoTravassos** [comment]
@robertstefan  okay thanks man

**Comment by NicoTravassos** [comment]
@robertstefan Hi there sorry quick question how would i fix the forecolor and the grey lines between each item

![untitled](https://cloud.githubusercontent.com/assets/7794777/5691969/bf028682-98e8-11e4-972f-a6a49306f5b3.png)
