### ISSUE TITLE
Multi window at once

### ISSUE THREAD

**Issue by AyoubDar** [MahApps/MahApps.Metro#1745]
i just begin learn mahapps and i have window call mainwindow and i create another, i want to call it inside the mainwindow if there's any way to do that help me with it.
i try to do function show but it don't work.

**Comment by amellini** [comment]
What do you mean with "inside" like an MDI?
Probably you need do use a frame and use page instead window.

**Comment by AyoubDar** [comment]
ok it's works with pages thanks u
