### ISSUE TITLE
Ability to use appbar icons in Menu header

### ISSUE THREAD

**Issue by NicoTravassos** [MahApps/MahApps.Metro#1747]
Ability to use appbar icons in Menu header SEE Image

![capture](https://cloud.githubusercontent.com/assets/7794777/5694934/c4540596-998a-11e4-9cac-da4e3c7ac0da.PNG)

If you can already do this How?

**Comment by Dotnetifier** [comment]
That button in Visual Studio is probably not part of a menu. A horizontal StackPanel (or something equivalent) is probably used to place that toggle button right next to the menu bar.

**Comment by AJ-Santos** [comment]
Here's a guide to doing something like this. http://mahapps.com/guides/quick-start.html#customization
