### ISSUE TITLE
Quick Start seems incomplete

### ISSUE THREAD

**Issue by raginruffalo** [MahApps/MahApps.Metro#1751]
The quick start on the website seems incomplete to someone who has never used custom controls before. I find myself designing this wonderful UI with no way to execute code from it. Is there any way this could be updated? (Specifically the Right Window Commands, I have no way of actually doing anything with them).

**Comment by flagbug** [comment]
Well, the QuickStart is just a QuickStart, not a "Learn WPF tutorial"

As for the window commands, just use them like you use a normal button, no magic here:

```
<Controls:MetroWindow.RightWindowCommands>
  <Controls:WindowCommands>
    <Button Content="settings" Click="YourEventHandler" />
  </Controls:WindowCommands>
</Controls:MetroWindow.RightWindowCommands>
```

**Comment by raginruffalo** [comment]
Ok, but with the Flyout menu as well, I've created it and there is no errors but it doesn't pop out. Even setting the IsEnabled property doesn't seem to do anything.

**Comment by flagbug** [comment]
Set the `IsOpen` property, not `IsEnabled`
