### ISSUE TITLE
Feature request(s)

### ISSUE THREAD

**Issue by jyrka98** [MahApps/MahApps.Metro#1753]
Would it be possible to add/optionally change  the following things? 
option to not show the context menu on the window icon;
option to use a metro style context menu on window icon instead of the standard Windows one;

**Comment by mrahhal** [comment]
Not showing the context menu is of course possible, but I don't think showing it with a different style is since the context menu is a direct call to the Win32 api.

**Comment by jyrka98** [comment]
@mrahhal by chaning the style i mean use a WPF contextmenu

**Comment by punker76** [comment]
@jyrka98 this is the windows system menu and can not be styled

**Comment by mrahhal** [comment]
@punker76 @jyrka98 possibly means that instead of using the system context menu we can make our own and replicate it.

**Comment by punker76** [comment]
na, i dont want this, it's an OS menu that can be different between win 7 vor 8 vor 10, so let it be

**Comment by mrahhal** [comment]
@jyrka98 I'm with @punker76, it's not worth it much.

**Comment by jyrka98** [comment]
Ok. Well, what about an option to not show it?

**Comment by mrahhal** [comment]
@jyrka98 doable. Make another issue as a feature request for this option (not showing the context menu) and close this one. Unless if you yourself want to introduce this option, in that case just make a PR.

**Comment by jyrka98** [comment]
https://github.com/MahApps/MahApps.Metro/issues/1778
