### ISSUE TITLE
Custom color for TitleBar

### ISSUE THREAD

**Issue by homerunjack** [MahApps/MahApps.Metro#1754]
Hi,

I realized that I can change the color of the theme with changing the xaml file...

How can I download one of the MahApps.Metro/MahApps.Metro/Styles/Accents files and bring them to my project?

**Comment by aggietech** [comment]
You could fork the project or just download the source to get the xaml

**Comment by homerunjack** [comment]
Hey, 
I'm new in C# programming. How can I fork this files?

**Comment by punker76** [comment]
[https://help.github.com/articles/fork-a-repo/](https://help.github.com/articles/fork-a-repo/)
