### ISSUE TITLE
MessageDialog NegativeButton styling

### ISSUE THREAD

**Issue by soend** [MahApps/MahApps.Metro#1755]
MessageDialog NegativeButton styling is not set to AccentedDialogSquareButton. Would be nice if it would use also this style so text casing would stay same as it is when i set it.

**Comment by punker76** [comment]
@soend which version?

**Comment by soend** [comment]
master branch of Mahapps.
https://github.com/MahApps/MahApps.Metro/blob/master/MahApps.Metro/Themes/Dialogs/MessageDialog.xaml

**Comment by soend** [comment]
NegativeButton still does not respect the casing set in string: NegativeButtonText = "No"
Nuget package 1.0.1-ALPHA047

**Comment by flagbug** [comment]
@soend This is the expected behavior. Use the `ButtonHelper.PreserveTextCase` attached property if you don't want the buttons to change the casing

**Comment by soend** [comment]
Im little lost here, when i pull the source from github and run the MetroDemo and open the MessageDialog from menu then the text casing is preserved. But in my application its not. Can anybody point out where in MetroDemo is ButtonHelper.PreserveTextCase set?

**Comment by soend** [comment]
I noticed that text casing is preserved when i use `ColorScheme = MetroDialogColorScheme.Theme` and not preserved when i use `ColorScheme = MetroDialogColorScheme.Accented` in the `MetroDialogSettings`, is this expected behavior?

**Comment by flagbug** [comment]
@soend Sounds like a bug. Anyways, when you use the `ButtonHelper.PreserveTextCase` property, it should always be preserved

**Comment by soend** [comment]
Could you give me example how to use this property?

**Comment by flagbug** [comment]
My fault, it's currently only possible in custom dialogs

**Comment by punker76** [comment]
@soend @flagbug -> https://github.com/MahApps/MahApps.Metro/pull/1793
