### ISSUE TITLE
Flyout Vertical and Horizontal Alignment

### ISSUE THREAD

**Issue by robichaud** [MahApps/MahApps.Metro#1762]
This is more of a feature request than an issue. Currently the VerticalAlignment and HorizontalAlignment properties are set to Stretch in the ApplyAnimation method. Something like a  property to override these would be great. There are cases (notifications) where a smaller (e.g. VerticalAlignment.Top) flyout would be useful.

**Comment by robichaud** [comment]
On second thought, this is an issue. The style for the Flyout is setting the VerticalAlignment/HorizontalAlignment to Stretch. Why force it to be stretch in the code (ApplyAnimation) if it would default to stretch based on the style? If it relied on the style we could easily override it to any VerticalAlignment/HorizontalAlignment we choose.

**Comment by robichaud** [comment]
I misspoke there, it's set in the ApplyAnimation because of the Position property. So back to the original thought, perhaps properties to override these based on position, e.g. IsVerticalFlexible and FlexibleVerticalAlignment -- IsHorizontalFlexible and FlexibleHorizontalAlignment with a simple check in ApplyAnimation to apply.

**Comment by punker76** [comment]
@robichaud maybe [MahApps.Metro.SimpleChildWindow](https://github.com/punker76/MahApps.Metro.SimpleChildWindow) can help you with a little notification child window...
