### ISSUE TITLE
Clear TextBox Button doesn't seem to be fully working

### ISSUE THREAD

**Issue by CobyBorel** [MahApps/MahApps.Metro#1764]
In the Demo App, TextExamples.xaml line 41, the 3rd textbox

Changed to this:
<TextBox Margin="0, 10, 0, 0" Text="">

When running the app I get this behaviour. 
Change tab to "text" 
Enter "asdf" into the 3rd textbox  
ClearTextButton appears 
Click ClearTextButton and nothing happens
Tab to another tab "dates" and tab back "text"
Click ClearTextButton and text clears
enter text "asdf" into the 3rd textbox
ClearTextButton appears 
Click ClearTextButton and text clears 
Tab to another tab "dates" and tab back "text"
enter text into the 3rd textbox "asdf" 
ClearTextButton appears 
Click ClearTextButton and nothing happens

I'm thinking something is out of synce or not being updated.

I'm experiencing the same thing in my app as well when bound to an object. 

Thanks for any help or advise.

**Comment by punker76** [comment]
@CobyBorel which version you are using? i can't reproduce this with the latest github source.

**Comment by CobyBorel** [comment]
I downloaded the MahApps.Metro-master.zip on 12/23/2014
TextExamples.xaml line 41-43, the 3rd textbox 
remove
line 42: Controls:TextBoxHelper.ButtonCommand="{Binding TextBoxButtonCmd, Mode=OneWay}"
line 43:  Text=""

**Comment by thoemmi** [comment]
I was able to reproduce this issue. The problem is, that `Controls:TextBoxHelper.ClearTextButton="true"` is set via the style. I guess the value is applied **after** the `TextBox` is loaded, so `TextBoxLoaded` will never be called. If I change the code in `TextBoxHelper.ButtonCommandOrClearTextChanged` to this (note the `if (textbox.IsLoaded)...`) it works:
```C#
private static void ButtonCommandOrClearTextChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
{
    var textbox = d as TextBox;
    if (textbox != null)
    {
        // only one loaded event
        textbox.Loaded -= TextBoxLoaded;
        textbox.Loaded += TextBoxLoaded;
        if (textbox.IsLoaded) {
            TextBoxLoaded(textbox, new RoutedEventArgs());
        }
    }
    //...
```

**Comment by punker76** [comment]
@thoemmi seems like we should do this always and for the password and combo box too

**Comment by thoemmi** [comment]
That's what I think too. Should I create a PR?

**Comment by punker76** [comment]
@thoemmi jepp :+1:
