### ISSUE TITLE
Flyout covers title bar and/or status bar

### ISSUE THREAD

**Issue by ToBiMaR** [MahApps/MahApps.Metro#1765]
Is it possible to have the flyout (from left and right) flyout between the title bar and the status bar (if one is put in)?

**Comment by punker76** [comment]
@ToBiMaR You can e.g. set the margin of the `FlyoutsControl` to the height values of the title bar and status bar...

```xaml
<Controls:MetroWindow.Flyouts>
    <Controls:FlyoutsControl Margin="0 30 0 25">
...
```
