### ISSUE TITLE
Appbar flyout

### ISSUE THREAD

**Issue by di48l069** [MahApps/MahApps.Metro#1767]
Is it possible to use the appbar flyout outside the window and the bottom of the window?

**Comment by punker76** [comment]
@NicoTravassos sorry, that's not yet possible

**Comment by NicoTravassos** [comment]
@punker76 is there plan for it to be feature.

**Comment by punker76** [comment]
@di48l069 No plan for such feature. Maybe a way for you, create a custom borderless window that looks like a flyout and set it's location at bottom or where do you want.
