### ISSUE TITLE
Application Accent not changing when BaseLight theme is set

### ISSUE THREAD

**Issue by soend** [MahApps/MahApps.Metro#1770]
I have set the BaseLight theme in my Application.Resources:
```
  <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Colors.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/olive.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/BaseLight.xaml" />
                <ResourceDictionary Source="Resources/Icons.xaml"/>
            </ResourceDictionary.MergedDictionaries>
            <viewModel:ViewModelLocator x:Key="Locator" d:IsDataSource="True"  />
        </ResourceDictionary>
    </Application.Resources>
```

But now when i try to change the Accent from my code (viewmodel) then its just not changing to red accent. Heres how i try to change it:
```
var theme = ThemeManager.DetectAppStyle(Application.Current);
ThemeManager.ChangeAppStyle(Application.Current, ThemeManager.GetAccent("Red"), theme.Item1);
```

Using the latest version from nuget package.

**Comment by soend** [comment]
I found a workaround for the issue where calling ChangeAppStyle does not change the accent color.
Heres the code i use now:
 var theme = ThemeManager.DetectAppStyle(Application.Current);
var accent = ThemeManager.GetAccent("Red");
ThemeManager.ChangeAppStyle(Application.Current.Resources, accent, theme.Item1);

I just use ChangeAppStyle overload method what takes resourceDictionary instead of Application.

**Comment by punker76** [comment]
the accents and themes are case sensitive!!! `....../Styles/Accents/Olive.xaml" />` not `....../Styles/Accents/olive.xaml" />`
