### ISSUE TITLE
Flyout closing event after closing a dialog/window

### ISSUE THREAD

**Issue by mike-ward** [MahApps/MahApps.Metro#1771]
Has ShowWindowCommandsOnTop been romoved? It's no longer a dependency property for Metro Window. The flyouts demo in the sample app does not appear to work either.

**Comment by punker76** [comment]
@mike-ward yes, it's removed, the demo must become an update... you can now use `xyzOverlayBehavior` properties with

- `Never`
- `OverlayFlyout`
- `OverlayHiddenTitleBar`
- `Always`

https://github.com/MahApps/MahApps.Metro/blob/master/docs/release-notes/0.14.0.md#fine-grained-control-over-the-titlebar-element-overlay-behavior

**Comment by mike-ward** [comment]
OK, I see it. I noticed that if the application is closed when a flyout is
open, the closing finished event does not fire. Is this expected?

**Comment by punker76** [comment]
>I noticed that if the application is closed when a flyout is open, the closing finished event does not fire. Is this expected?

I don't know if MahApps should do this or the user itself...
^ /cc @flagbug @thoemmi

**Comment by mike-ward** [comment]
As far as I can tell, it's the only closing event for a flyout window.

**Comment by thoemmi** [comment]
Well, I think that's the correct behaviour: the window closes with open flyouts. I can't think of a scenario where I do want to receive a flyout's Closing event when the window is closed. If the user has entered some essential data in the flyout, he should have pressed Enter, Ok, or something like that to get the data stored, but not the close button of the hosting window.

**Comment by mike-ward** [comment]
Scenario: Alt+F4

I can't think of a scenario where I would not want the closing event
raised. The window is closing, therefore I should get a closing event. What
the user does or does not do is not relevant.

On Fri, Feb 6, 2015 at 1:40 PM, Thomas Freudenberg <notifications@github.com

**Comment by flagbug** [comment]
I think @thoemmi is talking about the Flyout's closing event, while @mike-ward is talking about the hosting *Windows's* closing event, right?

**Comment by punker76** [comment]
@flagbug i think so

**Comment by punker76** [comment]
so, the Problem seems to be, we don't get a closing event in Alt+F4

**Comment by mike-ward** [comment]
That's the easiest way to reproduce the issue. I was able to work around
the issue in Markdown Edit. I guess the question is, "should" the flyout
get a close event? I suppose it could be interpreted either way. It just
struck me as odd that a closing event did not fire on program close.
Perhaps "closing" is the wrong term here. Maybe "collapse" is better.
Anyways, when I see an event like, "closing" I have expectations. Whether
those expectations are founded or not is subject to debate. :)

**Comment by thoemmi** [comment]
@mike-ward just to be sure I get you right: you criticize that when the window is closed, `Flyout.ClosingFinished` isn't raised?

**Comment by mike-ward** [comment]
Correct.

On Sun, Feb 8, 2015 at 8:34 AM, Thomas Freudenberg <notifications@github.com

**Comment by thoemmi** [comment]
Well, from the Flyout's perspective, I guess it's never closed. The window just closes with the flyout still open.

**Comment by flagbug** [comment]
I agree with @thoemmi , while the Flyout disappears when the window closes, it isn't *really* closed, it's just that the hosting window closes

**Comment by crclayton** [comment]
Might want to update the last paragraph of this: http://mahapps.com/controls/flyouts.html

**Comment by punker76** [comment]
@mike-ward @thoemmi So, should MahApps close all open Flyouts on the window closing event? Or should we block the closing like we now do it with open Dialogs?

**Comment by mike-ward** [comment]
I don't see value in holding up the close due to open flyouts.

**Comment by thoemmi** [comment]
IMHO flyouts are like tool windows or non-modal dialog and should not prevent the main window from closing. If a user of MahApps.Metro wants to suppress the closing he's still able to intercept the `Window.OnClosing` event. 
Additionally flyouts shouldn't close automatically when the window is closed. In my feelings they just provide additional secondary space for information/controls. E.g. in Markdown Edit, when the settings flyout is open and you've changed some settings, those changes shouldn't be applied (and persisted) when you close the main window.

**Comment by punker76** [comment]
@mike-ward @thoemmi I agree with Thomas. Users can do this if they want, so I close this issue now. Regards, Jan
