### ISSUE TITLE
Chrome panel incorrect behavior when there is no enough space

### ISSUE THREAD

**Issue by mrahhal** [MahApps/MahApps.Metro#1773]
The chrome panel renders its components in a way that hides the window buttons (the most important component) first when there is no enough space.
![capture_old](https://cloud.githubusercontent.com/assets/4404199/5937625/4dfe9d52-a6fa-11e4-955b-3ddf6038f881.JPG)

**Comment by punker76** [comment]
@mrahhal i saw this too about a week ago, maybe we say window buttons always visible and hide the left or right commands...

**Comment by mrahhal** [comment]
@punker76 check #1774
