### ISSUE TITLE
[Feature request] Add option to not show the system menu.

### ISSUE THREAD

**Issue by jyrka98** [MahApps/MahApps.Metro#1778]

**Comment by flagbug** [comment]
What's the benefit of this/why would anyone want to do this?

**Comment by jyrka98** [comment]
Closing issue. PR created. https://github.com/MahApps/MahApps.Metro/pull/1780

**Comment by punker76** [comment]
and was is the benefit? @jyrka98

**Comment by jyrka98** [comment]
Well some people may not like it. It's optional to not show it, not forced..

**Comment by flagbug** [comment]
It adds a maintenance overhead for a feature that is a standard across all Windows programs and therefore users expect this to be available

**Comment by jyrka98** [comment]
@flagbug You have a option to not show the menu when right clicking on titlebar.. which is also "standard".
