### ISSUE TITLE
Suggestion: make flyouts overlap Winforms controls

### ISSUE THREAD

**Issue by QuantumDeveloper** [MahApps/MahApps.Metro#1779]
Hello @punker76 and @flagbug 
For now flyout and (I think appbar too) cannot overlap winforms controls because winforms rendering after wpf and always on top of them.

So, it would be great to make them overlap winforms controls.
Maybe it could be transparent popup, which will contain flyout and appbar?

What do you think about that?

**Comment by QuantumDeveloper** [comment]
@punker76 

So, after some time playing with this issue I found out the following:
Solution from Dwayne Need is working only on Win8. On Win7 it working very-very bad (even with stucking the whole WPF application). In both cases it affects performance and I loose ~3-5 framaes per second during rendering my 3d game content using this solution.

Also I found that WPF team wanted to include something similar in official WPF 4.5, but they found some issues and completely remove redirection and composition from .Net framework. 

So, there is no good solution for airspace issue for now unfortunately.
And in 2015 we still have to struggle of this...

**Comment by surendrakandira93** [comment]
Hello everyone I have one problem in win form using wpf controls 
![mouse scroll issue 1](https://cloud.githubusercontent.com/assets/10044538/10658796/dbed4192-78b7-11e5-9e97-6c1c082f9d94.JPG) this is issue in wpf control 

![right](https://cloud.githubusercontent.com/assets/10044538/10658803/f3d6cc42-78b7-11e5-8f91-ecd057b972db.PNG) This is right image 

Please help me and give me suggestion
