### ISSUE TITLE
Grid row foreground

### ISSUE THREAD

**Issue by olegsavelos** [MahApps/MahApps.Metro#1782]
Hi.
In some cases i get one or few grid row items foreground becoming white.
I am not sure how to replicate this but i think it occurs when i switch between multiple grids contained in a tab or other controls.

Anyone aware of this bug?

**Comment by punker76** [comment]
@olegsavelos can you tell us more informations?
https://github.com/MahApps/MahApps.Metro/wiki/About-Bug-Reports

**Comment by olegsavelos** [comment]
I cant tell much more than this seem to be happening if grid is unloaded and reloaded.
This guy here have same problem i suppose https://github.com/MahApps/MahApps.Metro/issues/1728

**Comment by punker76** [comment]
duplicate #1728
