### ISSUE TITLE
How can I bind to the PasswordBox Text

### ISSUE THREAD

**Issue by Camuvingian** [MahApps/MahApps.Metro#1784]
The issue I have is simple, I want to get the password text from the `PasswordBox` control in my ViewModel. I can seem to bind to `Text` or `Password` (as the latter is not a DP). How can I get the password entered in my ViewModel?

Also, I am also having problems with this https://github.com/MahApps/MahApps.Metro/issues/1718.

Thanks for your time.

**Comment by robertstefan** [comment]
Have you tried this for password bingind? http://www.wpftutorial.net/PasswordBox.html

**Comment by Camuvingian** [comment]
Oh, okay, fair enough, I thought that this control was set to work "out-of-the-box". I will implement this...
