### ISSUE TITLE
Cannot create new window in a thread

### ISSUE THREAD

**Issue by phylix** [MahApps/MahApps.Metro#1792]
Trying to create a window with MahApps resource dictionaries results in

    System.Windows.Markup.XamlParseException: {"'Initialization of 'MahApps.Metro.Controls.NumericUpDown' threw an exception.' Line number '31' and line position '198'."}

    InnerException: {"The calling thread cannot access this object because a different thread owns it."}

Code:

    Thread foo = new Thread(delegate()
    {
        var window = new SettingsWindow();
        window.Show();

        System.Windows.Threading.Dispatcher.Run();
    });

    foo.IsBackground = true;
    foo.SetApartmentState(ApartmentState.STA);
    foo.Start();

Creating a new window without the resource dictionaries works fine.

**Comment by thoemmi** [comment]
That's not an MahApps.Metro issue but WPF in general. See [Threading model in WPF and application resources](http://sergey-yatsenko.blogspot.de/2010/09/threading-model-in-wpf-and-application.html). The solution given in mentioned article: use window resources instead of application resources.
