### ISSUE TITLE
Using Metro dialog

### ISSUE THREAD

**Issue by sberube** [MahApps/MahApps.Metro#1802]
I have a couple of questions concerning the Metro dialog.

1. Why window key bindings and application menu are not disabled when a dialog (ie: ShowMessageAsync) is shown? 
2. Why when showing a metro dialog (or modal flyout) the focus is not put on these new element that are shown?
3. What do you think of using dialog ShowMessageAsync in a catch since you cannot use the await keyword in a catch/finally statement?

Thanks!

**Comment by flagbug** [comment]
1. I guess because nobody has implemented that yet
2. Actually that should happen, do you have a reproduction?
3. It's possible in C# 6. In the meanwhile set a bool in the catch block and if that's true after the catch block, show the dialog

**Comment by sberube** [comment]
I have a reproduction for number 2. Here the link to the sample project that I've created (FlyoutFocusIssue.zip).

http://1drv.ms/1Lc5gau

Thanks!

**Comment by punker76** [comment]
@sberube @flagbug the problem for this is, the flyout trys to find a focusable element, in your example there is no focusable element, maybe we can change this and select the button if there is no focusable element

**Comment by sberube** [comment]
Actually, is it possible to have an option to automatically bind the escape key to close the current opened flyout or metro dialog?

Thanks!

**Comment by punker76** [comment]
>Why window key bindings and application menu are not disabled when a dialog (ie: ShowMessageAsync) is shown?

#2400

>Why when showing a metro dialog (or modal flyout) the focus is not put on these new element that are shown?

done

>What do you think of using dialog ShowMessageAsync in a catch since you cannot use the await keyword in a catch/finally statement?

 it's possible with c# 6.0

>Actually, is it possible to have an option to automatically bind the escape key to close the current opened flyout or metro dialog?

possible by using the `CloseButtonIsCancel` property
