### ISSUE TITLE
Notification counter MetroWindow.RightWindowCommands

### ISSUE THREAD

**Issue by JobaDiniz** [MahApps/MahApps.Metro#1804]
Hi, I've added a toggle button that act like a notification center (much like facebook) in RightWindowCommands:

![capture](https://cloud.githubusercontent.com/assets/165290/6216487/fccb09dc-b5f1-11e4-80f2-b5ea39a4a6ea.PNG)

But now I want to show how many notifications are unread... I'd like to show in the top right corner of the *"globe"* button. Any ideas?

**Comment by bigworld12** [comment]
yes there is an easy idea
1 - get how many notifications
2 - name the "image" control of the "globe" button any name : like globeImg
3 -you have two ways
   3-1 create a new image and write text to it 
    3-2 adding a textblock ABOVE the image and write how many notifications you want using codebehind

**Comment by JobaDiniz** [comment]
Sorry for not being specific. I want ideas of how to implement the UI part. Code behind I already implemented hehe.

Here is the current code (I use icons, not image):

```
<ToggleButton>
  <Rectangle Fill="White">
        <Rectangle.OpacityMask>
            <VisualBrush Visual="{StaticResource appbar_globe}" Stretch="Fill" />
        </Rectangle.OpacityMask>
    </Rectangle>
</ToggleButton>
```

I'll try the *TextBlock* suggestion. Thanks.

**Comment by justinhhorner** [comment]
Hello @JobaDiniz,

My notification badge design uses a combination of my vector art with two borders that have a corner radius of 50 to give this appearance. I have a centered TextBlock inside the second border bound to the unread notification count.

![notification_bell_design](https://cloud.githubusercontent.com/assets/4635843/6286571/f70ae1ec-b8d6-11e4-82ca-87225f2992ac.PNG)

I hope this helps.

**Comment by JobaDiniz** [comment]
*This icon is what I wanted hehe... I even opened a suggestion issue (https://github.com/Templarian/WindowsIcons/issues/208) for it.*

Your vector is really nice, however, if I understood right, when there is no notification, the red circle will be shown with "0" inside it. That's not what I want.

Thanks for sharing, though :+1:

**Comment by justinhhorner** [comment]
Thank you for the kind words.  Actually no, when there are no unread notifications, a visibility binding causes the borders to go away, leaving only the bell.

**Comment by JobaDiniz** [comment]
Awesome. Would you mind to share code?

**Comment by justinhhorner** [comment]
Absolutely, I'll pull it out of my project to post an isolated example and share the link here.

**Comment by justinhhorner** [comment]
I've created a repository for you to check out [here](https://github.com/justinhhorner/wpf-notificationbadge). I hope this helps :)

**Comment by JobaDiniz** [comment]
thanks! I'll check it out later
