### ISSUE TITLE
How to set startup window to MahApps.Metro used window?

### ISSUE THREAD

**Issue by Sharuru** [MahApps/MahApps.Metro#1807]
Hello, I am using MahApps.Metro developing a WPF application. 

Once I need to let my project folder facing MVVC model, I try to set my MainWindow.xaml under View folder and changing my App.xaml where 'StartupUri="MainWindow.xaml"' to 'StartupUri="View\MainWindow.xaml"'.

After pressing F5 in my VS, it gives me an error.

I create another windows not using MahApps.Metro and changing my App.xaml as above, this time it works well, so I believe there is something wrong with my code.

Please help me. :cry:

**Comment by thoemmi** [comment]
> After pressing F5 in my VS, it gives me an error.

Can you give some more details?

**Comment by Sharuru** [comment]
Here is the info:
An unhandled exception of type 'System.Windows.Markup.XamlParseException' occurred in PresentationFramework.dll

Others:
A first chance exception of type 'System.IO.IOException' occurred in PresentationFramework.dll
A first chance exception of type 'System.IO.IOException' occurred in PresentationCore.dll
'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xaml.resources\v4.0_4.0.0.0_zh-Hans_b77a5c561934e089\System.Xaml.resources.dll'. Module was built without symbols.
A first chance exception of type 'System.Xaml.XamlObjectWriterException' occurred in System.Xaml.dll
A first chance exception of type 'System.Windows.Markup.XamlParseException' occurred in PresentationFramework.dll
'Express Tracker.vshost.exe' (CLR v4.0.30319: Express Tracker.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\mscorlib.resources\v4.0_4.0.0.0_zh-Hans_b77a5c561934e089\mscorlib.resources.dll'. Module was built without symbols.
A first chance exception of type 'System.Reflection.TargetInvocationException' occurred in mscorlib.dll
A first chance exception of type 'System.Reflection.TargetInvocationException' occurred in mscorlib.dll
A first chance exception of type 'System.Xaml.XamlObjectWriterException' occurred in System.Xaml.dll
A first chance exception of type 'System.Windows.Markup.XamlParseException' occurred in PresentationFramework.dll
An unhandled exception of type 'System.Windows.Markup.XamlParseException' occurred in PresentationFramework.dll

It stopped here:
![20150219220429](https://cloud.githubusercontent.com/assets/3275627/6267923/507d015a-b883-11e4-8339-deda55971b6a.png)

I try to change my Startup object in order to merging my project into a single EXE using these codes: http://blogs.interknowlogy.com/2011/07/13/merging-a-wpf-application-into-a-single-exe/

Here is my project structure:

![9220535](https://cloud.githubusercontent.com/assets/3275627/6267973/af0afccc-b883-11e4-82ee-0fd3a8c5bfe3.png)
 
Thank you.

**Comment by thoemmi** [comment]
Maybe the thread for issue #1689 can help on merging assemblies into a single executable.

**Comment by Sharuru** [comment]
Thank you, I tried it before I post this issue.
It works well without MahApps.Metro, both tools and codes. :sob:

**Comment by bigworld12** [comment]
you can use the tutorial i made 
http://stackoverflow.com/questions/27891550/embedding-dlls-inside-of-a-wpf-application-with-pictures-visual-basic

**Comment by Sharuru** [comment]
@bigworld12 Thank you.
I've tried this tutorial but still can't work.
My program using 'Program.cs' to handle DLLs, it will run 'App.Main()' at the end.
I also set my project's start object to 'namespace.Program', so if I press F5, it will first start 'Program.cs'    handling DLLs, after that, it will call 'App.Main()' to run WPF codes.

**Comment by thoemmi** [comment]
If your application should start with the `Main` method in `program.cs`, you have to remove the `StartupUri` from `App.xaml`. Otherwise your application would have two entrypoints.

**Comment by Sharuru** [comment]
Yes, I removed `StartupUri` from `App.xaml`.
This time it won't give me an error message, but it also won't call the WPF window. (It will run `App.Main()`, but no WPF window is shown)

**Comment by thoemmi** [comment]
Without knowing your code, I guess you should call `App.Run()`

**Comment by Sharuru** [comment]
Hello, here is the code: https://github.com/Sharuru/Csharp-xto/tree/test

**Comment by bigworld12** [comment]
i saw your code
just remove app.run()

**Comment by Sharuru** [comment]
@bigworld12 After I remove it, no error raised but also no WPF windows shown.

**Comment by bigworld12** [comment]
set the startup item to the metro window
and move the codes from program.cs to application events (as shown in my tutorial)
http://stackoverflow.com/questions/27891550/embedding-dlls-inside-of-a-wpf-application-with-pictures-visual-basic

**Comment by justinhhorner** [comment]
Hello Sharuru,

If you want to accomplish this from Main.cs you could do it like this.

var app = new csxto.App();
var window = new MainWindow() { Visibility = System.Windows.Visibility.Visible };
app.MainWindow = window;
app.Run();

Note that in order to load the resources set in your App.xaml file, you'll need to add a a constructor to App.xaml.cs that calls the InitializeComponent method like so.

public App()
{	
	InitializeComponent();
}

I hope this helps.

**Comment by punker76** [comment]
@Sharuru https://github.com/Sharuru/Csharp-xto/pull/10
you forgot to embed your resources

**Comment by justinhhorner** [comment]
@Sharuru you'll also need to change your Icon path on MainWindow to "..\app.ico"

**Comment by Sharuru** [comment]
@bigworld12 @punker76 @justinhhorner 
Thank you very much.

I still can not solve this problem.
Try my best solving this...
By the way, I tried don't merge my DLLs together, just let my `MainWindow.xaml` under 'View' folder, it also gives my the same error message.
I think there must be something magic with my codes.

**Comment by Sharuru** [comment]
'By the way, I tried don't merge my DLLs together, just let my MainWindow.xaml under 'View' folder, it also gives my the same error message.'

So I create a new branch named 'playground': https://github.com/Sharuru/Csharp-xto/tree/playground
I think solving this problem is the first step solve all my problems :cry:

**Comment by punker76** [comment]
and i say, please stop discussing this here

**Comment by Sharuru** [comment]
I am sorry, I've create this problem on stackoverflow: http://stackoverflow.com/questions/28630438/how-to-set-startup-window-to-mahapps-metro-used-window
