### ISSUE TITLE
Window Placement and Border Snaps

### ISSUE THREAD

**Issue by mike-ward** [MahApps/MahApps.Metro#1811]
In Windows 8.1 when one can size a window and as it gets near a screen edge, it snaps the window. Problem is, the window position is not "remembered" when the application is closed and reopened. It seems that window position is not captured whenever one of these "snap" operations occurs.

Steps to reproduce:

1. Open Markdown Edit (https://github.com/mike-ward/Markdown-Edit/releases/download/v1.3.2/MarkdownEditSetup.msi)
2. Click and drag bottom window border to bottom edge of screen and release mouse
3. Window will snap to top and bottom edges
4. Close program and reopen

Expected: Window should return to same position and size when it was closed.

Actual: Window opens at previous window and size before resizing (snapping) operation.

I've done some research on this issue and it appears to be a hard problem to solve. Something about GetWindowPlacement not receiving the correct coordinates.

**Comment by flagbug** [comment]
How do you persist the window location between application restarts?

**Comment by mike-ward** [comment]
Sorry, should have mentioned I'm using MahApps `SaveWindowPosiion="True"` attribute on the main window which is a `MetroWindow`.

**Comment by punker76** [comment]
i'll look what we can do to fix this, but i just say its a bug with the
windows GetWindowPlacement method...
Am 21.02.2015 17:21 schrieb "Mike Ward" <notifications@github.com>:

**Comment by thoemmi** [comment]
There lots of questions regarding this at StackOverflow. [The general advise is to call `GetWindowRect()`](http://stackoverflow.com/a/12629214/4747):

> The workaround is to call `GetWindowRect()` to get the actual window coordinates and copy them over the bad coordinates in `WINDOWPLACEMENT::rcNormalPosition`.
