### ISSUE TITLE
ShowIconOnTitleBar not fully working in 1.1.0

### ISSUE THREAD

**Issue by sheepinaball** [MahApps/MahApps.Metro#1817]
Hi,

With the new version, setting `ShowIconOnTitleBar` to `False` in the XAML seems to have no effect, and it is the same if i put this in te constructor. However, it worked when i put `this.ShowIconOnTitleBar = false;` in the `Loaded` method. 

Is it the expected behaviour, or a side effect of #1810 ?

**Comment by punker76** [comment]
@sheepinaball this should now work after 1e2c54e94b220edcc15f876f022eb20b696d0a68

note: if you say `IconOverlayBehavior=HiddenTitleBar` and `ShowTitleBar=false` the Icon stays visible
