### ISSUE TITLE
As of version 1.1.1 the problem descibed in issue #1608 remain.

### ISSUE THREAD

**Issue by JacBal** [MahApps/MahApps.Metro#1818]
<h3>The test</h3>
Demo App from source code =>
  * Set IsTabStop=false for the first NumericUpDown in TextExamples.xaml.
  * Run, navigate to the Text page
  * Tab across the controls => this NumericUpDown still receive the keyboard focus.

<h3>The Fix</h3>
Modify the template in NumericUpDown.xaml:
For the TextBox x:Name="PART_TextBox" 
1. Change Focusable=True to Focusable="{TemplateBinding Focusable}"
2.  Add  IsTabStop="{TemplateBinding IsTabStop}"
That will keep these properties synchronized with the parent.

__Since I don't know how to participate to that outstanding project, I hope that one of the developers will fix it in the next release.__
Thanks

**Comment by JacBal** [comment]
<h1>Edit:</h1>
I was too fast !!!
The Focusable property  of "PART_TextBox" should stay like it is: Focusable="True". 
Still need to add IsTabStop="{TemplateBinding IsTabStop}"
Therefore the behavior of NumericUpDown IsTabStop property will be like others WPF controls.

**Comment by punker76** [comment]
fixed with ada9f1bd6d38e16f1ab7d05bb530686e3ac5a255
