### ISSUE TITLE
Textbox styling

### ISSUE THREAD

**Issue by ChristopherStamm** [MahApps/MahApps.Metro#1824]
Hello,
i want to overrride the default Textbox-Style.
The Isssue is that this style isnot applyed on the first Textbox.

Sample screenshot:
![unbenannt](https://cloud.githubusercontent.com/assets/11272334/6442405/c32a51f2-c0ef-11e4-958b-7cd8c250e8a3.PNG)

Sample Window:
```xaml
<Window x:Class="WpfApplication19.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        Title="MainWindow" Height="350" Width="525">
    <Window.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Colors.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/Blue.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/BaseLight.xaml" />
                <ResourceDictionary>
                    <Style TargetType="TextBox">
                        <Setter Property="BorderThickness" Value="10"/>
                    </Style>
                </ResourceDictionary>
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Window.Resources>
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto"/>
            <RowDefinition Height="Auto"/>
            <RowDefinition Height="Auto"/>
            <RowDefinition Height="121*"/>
        </Grid.RowDefinitions>
        <TextBox Margin="5" />
        <TextBox  Margin="5" Grid.Row="1"/>
        <TextBox  Margin="5" Grid.Row="2"/>
    </Grid>
</Window>
```
 Sample Project:

**Comment by punker76** [comment]
@ChristopherStamm what's up?

**Comment by ChristopherStamm** [comment]
Hi

Hitting enter too fast ☺

I want to override the default Textbox-Style (and other styles).
The Isssue is that this style is not applied on the first Textbox.

Here is my Samplecode and Screenshot .NET 4.5

Sample Window:
<Window x:Class="WpfApplication19.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        Title="MainWindow" Height="350" Width="525">
    <Window.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Colors.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/Blue.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/BaseLight.xaml" />
                <ResourceDictionary>
                    <Style TargetType="TextBox">
                        <Setter Property="BorderThickness" Value="10"/>
                    </Style>
                </ResourceDictionary>
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Window.Resources>
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto"/>
            <RowDefinition Height="Auto"/>
            <RowDefinition Height="Auto"/>
            <RowDefinition Height="121*"/>
        </Grid.RowDefinitions>
        <TextBox Margin="5" />
        <TextBox  Margin="5" Grid.Row="1"/>
        <TextBox  Margin="5" Grid.Row="2"/>
    </Grid>
</Window>

Thanks
Christopher Stamm

Von: Jan Karger [mailto:notifications@github.com]
Gesendet: Montag, 2. März 2015 15:22
An: MahApps/MahApps.Metro
Cc: Christopher Stamm (AGIS GmbH)
Betreff: Re: [MahApps.Metro] Textbox styling (#1824)


@ChristopherStamm<https://github.com/ChristopherStamm> what's up?

**Comment by chuuddo** [comment]
try this 
```xaml
    <Window.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Colors.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/Blue.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/BaseLight.xaml" />
            </ResourceDictionary.MergedDictionaries>
            <Style TargetType="TextBox">
                <Setter Property="BorderThickness" Value="10" />
            </Style>
        </ResourceDictionary>
    </Window.Resources>
```

**Comment by ChristopherStamm** [comment]
Thanks

Works like a charm
