### ISSUE TITLE
Using MetroNavigationWindow

### ISSUE THREAD

**Issue by ClintPearson-KPMG** [MahApps/MahApps.Metro#1828]
There's nothing in the docs that I can see about using the `MetroNavigationWindow`, I've tried the following:

```xaml
<controls:MetroNavigationWindow x:Class="PackageCreator.MainWindow" />
```

But I get `MahApps.Metro.Controls.MetroNavigationWindow' cannot be the root of a XAML file because it was defined using XAML`

**Comment by robertstefan** [comment]
@ClintPearson-KPMG  `MetroNavigationWindow` it's not like a control. You have to use it the same way as the `MetroWindow`.

**Comment by ClintPearson-KPMG** [comment]
@robertstefan I gathered, I also tried to have the .xaml.cs file inherit from `MetroNavigationWindow` as well, problem is the XAML error still happens, then changing the XAML to `MetroWindow` but leaving the derivation as `MetroNavigationWindow` causes an error about differing base classes.

**Comment by robertstefan** [comment]
So, in the end; how does your code look like?

**Comment by ClintPearson-KPMG** [comment]
## Scenario 1
```xaml
<MetroNavigationWindow ...>
```
> The `MainWindow.xaml` file

```csharp
public partial class MainWindow : MetroNavigationWindow
{
  // Content Here
}
```
> The `MainWindow.xaml.cs` file

Produces error: `... cannot be root of XAML file because it is defined using XAML`

## Scenario 2
```xaml
<MetroNavigationWindow ...>
```

```csharp
public partial class MainWindow : MetroWindow
{

}
```

Produces error `... partial class cannot have differing base class`

**Comment by robertstefan** [comment]
So, taken from the [example](https://github.com/MahApps/MahApps.Metro/blob/master/samples/MetroDemo/MainWindow.xaml.cs#L258) application provided by the community, you will have to use it like this:

```
var navWin = new MetroNavigationWindow();
navWin.Title = "Navigation Demo";
navWin.Show();
navWin.Navigate(new Navigation.HomePage());
```

where HomePage you can find it [here](https://github.com/MahApps/MahApps.Metro/tree/master/samples/MetroDemo/Navigation).

**Comment by ClintPearson-KPMG** [comment]
Oh, so it doesn't support being used in XAML in the slightest? This framework keeps seeming less and less MVVM friendly. Thanks for your help though!

**Comment by punker76** [comment]
@ClintPearson-KPMG i you can make something better MVVM "friendly", so do it!

**Comment by Amrykid** [comment]
@ClintPearson-KPMG the issue with the MetroNavigationWindow is that the XAML designer in Visual Studio doesn't support loading NavigationWindow subclasses.

**Comment by xmedeko** [comment]
Yep, the problem is, that `MahApps.Metro\Themes\MetroNavigationWindow.xaml` defines content of the `MetroNavigationWindow`. The solution is either to define the content in the code only, or define the content as a Style Template, see http://svetoslavsavov.blogspot.gr/2009/09/user-control-inheritance-in-wpf.html.

**Comment by lostmsu** [comment]
@ckpearson why is this issue closed? There's no way to solve the problem from MapApps side?

**Comment by xe7485** [comment]
For anyone that would like to go with my crappy code, here is a version that works for me and is XAML compatible.
Essentially a rewrite of existing XAML to code.

[NavigationWindow.cs.txt](https://github.com/MahApps/MahApps.Metro/files/1547093/NavigationWindow.cs.txt)
