### ISSUE TITLE
Flyout theme colors with Foreground binding converters

### ISSUE THREAD

**Issue by JobaDiniz** [MahApps/MahApps.Metro#1831]
Hi, my app uses light theme, but when I open a flyout, it uses dark theme. That's ok, but how does it work?

Sometimes, I show the same view in the light theme and in the flyout (dark) and because I have some logic about the color, some text colors do  not change to white in the flyout:

```
<phoneConverters:RejectedOrMissedCallColorConverter x:Key="RejectedOrMissedCallColorConverter" MatchColor="Red" DefaultColor="{StaticResource BlackColorBrush}"/>
```
```
 <TextBlock Text="{Binding Callers[0].Display}">
                        <TextBlock.Foreground>
                            <MultiBinding Converter="{StaticResource RejectedOrMissedCallColorConverter}">
                                <Binding Path="Rejected" />
                                <Binding Path="Missed" />
                            </MultiBinding>
                        </TextBlock.Foreground>
                    </TextBlock>
```

`DefaultColor="{StaticResource BlackColorBrush}"`will always be **black**, even in the flyout.

**Comment by thoemmi** [comment]
See #1024 about changing a flyout's theme.

**Comment by JobaDiniz** [comment]
Hi, I don't want to change the flyout's theme. I want my views to match the theme applied to flyout.

**Comment by JobaDiniz** [comment]
It's not a bug... It's a question... with no answer so far...

**Comment by flagbug** [comment]
Have you tried `DynamicResource`?

**Comment by JobaDiniz** [comment]
Yes... DynamicResource can't be used there...
