### ISSUE TITLE
Window Borderthickness

### ISSUE THREAD

**Issue by vincenzkoop** [MahApps/MahApps.Metro#1834]
Hi there,

i have a very strange Problem with BorderThickness of my MainWindow. Its a MetroWindow. When i set BorderThickness to 1 it renders a Border with about 3-4 px thickness. When I set it to 0.5 it renders a 1 px Border on the right and bottom. top and left are invisible. I checked all my styles but there is no place where i override the BorderThickness.

Best

Vin

**Comment by punker76** [comment]
@vincenzkoop what was the problem? do you fix it by your self?

**Comment by vincenzkoop** [comment]
Yes it was my fault! I just had the glow brush and borderthickness applied to the metrowindow. I know ist quite stupid!

 

Now i have a problem with multiple glow-metrowindows calling each other as a dialog. Every time when i close one of them, the glowwindowbehavior stays attached to the dialog and throws nullreferenceexeptions.

 

When i detach it manually the eventhandlers still seem to be double registered because oft he mainwindow.

 

Von: Jan Karger [mailto:notifications@github.com] 
Gesendet: Freitag, 13. März 2015 21:14
An: MahApps/MahApps.Metro
Cc: vincenzkoop
Betreff: Re: [MahApps.Metro] Window Borderthickness (#1834)

 

@vincenzkoop <https://github.com/vincenzkoop>  what was the problem? do you fix it by your self?
