### ISSUE TITLE
Is there a way to make Flyouts behave like Expander?

### ISSUE THREAD

**Issue by ppradeepk** [MahApps/MahApps.Metro#1836]
I was wondering if it is possible to make Flyouts slide in say from left and 'nudge' the controls in the container instead of overlapping them, something like an Expander control?

**Comment by mpartipilo** [comment]
I achieved this by setting a style trigger that changed the Grid.Margin when Flyout.IsOpen is true"

    <DataTrigger Binding="{Binding ElementName=MainWindowInstance, Path=RightPanelOpen}" Value="True">
        <Setter Property="Margin" Value="0,0,320,0" />
    </DataTrigger>

An Expander control would be much nicer of course.

**Comment by punker76** [comment]
@ppradeepk sorry it's not possible for now
