### ISSUE TITLE
Dynamically Changing Flyout Control Theme to and from Accent

### ISSUE THREAD

**Issue by ActivationRequired** [MahApps/MahApps.Metro#1838]
I am having issues with the background not being replaced when switching between the the themes dynamically. Everything seems to work correctly when switching between Light, Dark, Inverse, and Adapt. However, if I choose Accent the background sticks.

I don't believe this is the same issue as #1024

**Comment by punker76** [comment]
seems to work (just using the latest alpha)

![2015-07-10 09h43_15](https://cloud.githubusercontent.com/assets/658431/8614232/e9520330-26e7-11e5-9d05-bcc97ae79bec.gif)
