### ISSUE TITLE
Dynamically Changing Flyout Control Position causing incorrect Transition Effect

### ISSUE THREAD

**Issue by ActivationRequired** [MahApps/MahApps.Metro#1839]
I am getting an incorrect transition when update the flyout controls position binding to a dynamic resource. The transition effect is correct on the first position bound value but once the property updates the effect no longer looks correct. The slide effect is replaced with a bottom-right to top-left effect. I was able to duplicate the issue with the latest demo code. Any ideas?

**Comment by punker76** [comment]
question is, why do you want (need) this? which version? some sample?
