### ISSUE TITLE
MahApps.Metro library for .Net 3.5

### ISSUE THREAD

**Issue by arunkumar4003** [MahApps/MahApps.Metro#1844]
Is it possible to use MahApps.Metro library for .Net 3.5 applications? The current 4.0 & 4.5 versions of Mahapps.Metro libraries are not compatible for .Net 3.5 applications. 

The requirement is to write an application for Windows XP SP2, which supports .Net 3.5 applications only. But the installation of .Net 4.0 client profile is successful provided the two installers WindowsInstaller 3.1 (WindowsInstaller-KB893803-v2-x86.exe) and wic_x86_enu.exe installed in it. 

Now the system has .Net 4.0 client profile in it and the MahApps 4.0 test application also running in it. However the application is giving run time exception when we closed it. 

Can i use .Net 4.0 application with .Net 4.0 Mahapps.Metro library to run in Windows XP SP2, or is there any older version of Mahapps.Metro library (change history) where i can download the library for .Net 3.5?

Thanks in advance....

**Comment by robertstefan** [comment]
As far as I know, MA.M was never designed to worked on .NET versions lower than 4.0.

> However the application is giving run time exception when we closed it.
What error does it throw?

**Comment by arunkumar4003** [comment]
![mahapps_crash_windowsxpsp2](https://cloud.githubusercontent.com/assets/10240026/6681086/8a87e63c-cc86-11e4-8a9b-8a5a223ca28b.png)

**Comment by robertstefan** [comment]
Yeah, that. That... is not helpful enough. 

Can you launch it through VS and see what happens?

**Comment by xinlmain** [comment]
Man... I used this library in my project. I thought it supports .Net 3.5. Then it turns out it only supports 4.0 higher. But my application need to support .Net 3.5... What should I do?
