### ISSUE TITLE
Fibonacci intervals with numericcontrol

### ISSUE THREAD

**Issue by swalter** [MahApps/MahApps.Metro#1848]
It's more a request than an issue:
I've written a little wpf app to calculate estimation times for our scrum teams.
To set the values for estimated implementation duration I use the numeric controls.
In fact we do not use intervals of "1, 2, 3, 4... " or "1, 3, 5..." but intervals of the fibonacci numbers that sums-up the values with the one before like "1, 1, 2, 3, 5, 8, 13 …".

Is there a way to manipulate the numeric controls to use this custom interval with no fixe value of interval?

**Comment by AndrewNoyes** [comment]
Here's a hacky approach using code behind for the OnValueIncrement/Decrement events.
```xaml
<Controls:NumericUpDown x:Name="FibNumericCtrl"
                        ValueIncremented="FibNumericCtrl_OnValueIncremented"
                        ValueDecremented="FibNumericCtrl_OnValueDecremented"/>
```
```C#
private int _index = 0;
        
private void FibNumericCtrl_OnValueIncremented(object sender, NumericUpDownChangedRoutedEventArgs e)
{
    FibNumericCtrl.Value = GetFibonacciIntegerAtIndex(++_index);
    e.Handled = true;
}

private void FibNumericCtrl_OnValueDecremented(object sender, NumericUpDownChangedRoutedEventArgs e)
{
    if (_index > 0)
         FibNumericCtrl.Value = GetFibonacciIntegerAtIndex(--_index);
    e.Handled = true;
}

private int GetFibonacciIntegerAtIndex(int pIndex)
{
    if (pIndex == 0)
          return 0;

    if (pIndex == 1)
          return 1;

    return GetFibonacciIntegerAtIndex(pIndex - 1) + GetFibonacciIntegerAtIndex(pIndex - 2);
}

**Comment by evilbaschdi** [comment]
I had to set the index to 2 to get this working in my case, but now it runs perfectly. thank you!
