### ISSUE TITLE
System menu present everywhere when fullscreen is toggled on

### ISSUE THREAD

**Issue by Evangelink** [MahApps/MahApps.Metro#1849]
When having a MetroWindow in fullscreen you end up with the titlebar system menu on right click (Restore, minimize...) that appears everywhere on the application.

To test this behavior you can either use the MahApps metro demo application or just create a new MetroWindow and set the following properties:
IgnoreTaskbarOnMaximize="True"
UseNoneWindowStyle="True"
WindowState="Maximized"
Now if you right click anywhere in the window you will see the title bar system menu.

You can avoid this problem by setting the ShowSystemMenuOnRightClick property to False but I am guessing it is not a correct default behavior for the window, what do you think?

**Comment by MuhKuh7** [comment]
I have the same problem. Would be great if it could be fixed.

**Comment by punker76** [comment]
@Evangelink just set `ShowSystemMenuOnRightClick` to `false`

**Comment by MuhKuh7** [comment]
@punker76 yes, this is a workaround as @Evangelink has already mentioned in the initial post, but there is still a bug in MahApps.Metro

**Comment by QuantumDeveloper** [comment]
@punker76 maybe this is because somehow window title is streched to the whole window?
Maybe the same issue is for #2036
