### ISSUE TITLE
DataGridNumericUpDownColumn binding with timespan is not working

### ISSUE THREAD

**Issue by fra9001** [MahApps/MahApps.Metro#1851]
Hi,

I'm using the `DataGridNumericUpDownColumn` to add or remove some time to a TimeSpan, but the binding is not working. I tried this

                <DataGridTextColumn Header="Spent Time"
                                    Binding="{Binding SpentTime}"
                                    />
                <mah:DataGridNumericUpDownColumn Header="Spent Time"
                                                      Binding="{Binding SpentTime}"
                                                      Minimum="0"
                                                      />

`SpentTime` is a TimeSpan, and it is correctly showing in the first column, while in the `DataGridNumericUpDownColumn` it stays empty, and if I click the plus button it just goes from 0 onwards. Is TimeSpan currently supported in this control?

**Comment by thoemmi** [comment]
The value property of `NumericUpDown` and thus `DataGridNumericUpDownColumn` is of type `double`. Binding to a `TimeSpan` cannot work.
