### ISSUE TITLE
Set Background transparent,different OS,different appearance.

### ISSUE THREAD

**Issue by wojiaofsp** [MahApps/MahApps.Metro#1854]
hi guys,
There is a strange things.
create a metro program.in MainWindow.xaml,set Background="Transparent" and                     WindowState="Maximized", in MainWindow.xaml.cs, in MainWindow(), write down this: 
            InitializeComponent();
            AllowsTransparency = true;

then,start this program,some computer(win7 or win8) is correct,but other computer is not correct.
any one can help me?thanks.

**Comment by punker76** [comment]
what is not correct? which mahapps version? any stack trace? can you provide screenshots or sample code?
