### ISSUE TITLE
RequestCloseAsync() in CustomDialog returns null exception 

### ISSUE THREAD

**Issue by bigworld12** [MahApps/MahApps.Metro#1858]
i have a simple code
```
  Private Async Sub Button_Click(sender As Object, e As RoutedEventArgs)
        Await RequestCloseAsync()
    End Sub
```
and in designer it gives me this error

Cannot create an instance of "CustomDialog"

**Comment by marcpiechura** [comment]
Maybe it's a duplicate of #1850 ?

I already submitted a pull request to fix this issue #1857
