### ISSUE TITLE
Glow windows are positioned incorrectly when window is aerosnapped

### ISSUE THREAD

**Issue by jyrka98** [MahApps/MahApps.Metro#1865]
Glow windows are positioned incorrectly when i aerosnap the window to the left or right of the screen..
![mam_bug_zoomed](https://cloud.githubusercontent.com/assets/7345717/6990621/28928d14-da79-11e4-97f4-51ccfabedc70.png)
Ar first i thought there was something wrong with my program, but then i also tried the demo app and the same thing happend.

**Comment by punker76** [comment]
should be fixed with latest alpha
