### ISSUE TITLE
when targeting x64 or any CPU I get an overflow exception

### ISSUE THREAD

**Issue by ajmcateer** [MahApps/MahApps.Metro#1866]
I have an issue on my PC where if I target x64 or AnyCPU it will give me the following error.
 
A first chance exception of type 'System.OverflowException' occurred in mscorlib.dll

This ran fine until today. I pulled the latest build which runs fine on my other machine and it started crashing. I uninstalled and re installed mahapps.metro and it still causes the issue. If I revert to old builds that never had this issue it still crashes. If I target x86 it runs fine. What am I missing, is there something I overlooked?

This is what I see in the Call Stack

mscorlib.dll!System.IntPtr.ToInt32()

**Comment by flagbug** [comment]
Please give us a real stacktrace

**Comment by punker76** [comment]
@ajmcateer it maybe the same like here #1880

**Comment by punker76** [comment]
@ajmcateer nevertheless a complete stacktrace would be nice

**Comment by punker76** [comment]
@ajmcateer PUSH! what's going on?

**Comment by ajmcateer** [comment]
@punker76 Hi I apologize I opened this ticket right before the holidays and when I went to visit family I didn't know their internet was down. I have been unable to replicate this issue since coming home.the program compiles fine and no longer gives me the error. If it happens again I will reopen the ticket.
