### ISSUE TITLE
Binding error when scrolling horizontally in datagrid or listview

### ISSUE THREAD

**Issue by bigworld12** [MahApps/MahApps.Metro#1871]
i am getting this error when i change the horizontal scroll bar position (scroll horizontally) 
```
System.Windows.Data Error: 5 : Value produced by BindingExpression is not valid for target property.; Value='-0.0704441041347614' 
BindingExpression:Path=CellsPanelHorizontalOffset; 
DataItem='DataGrid' (Name='ServerList'); target element is 'Button' (Name=''); target property is 'Width' (type 'Double')
```

**Comment by Dimigergo** [comment]
I have the same problem.

**Comment by punker76** [comment]
@bigworld12 @Dimigergo i can't reproduce this with the main demo. can you give us any repro instructions? is there maybe a custom style or something else?

**Comment by bigworld12** [comment]
Create a datagrid with many columns until you can see horizontal scroll bar then drag it any where and u get the error

**Comment by punker76** [comment]
@bigworld12 how many columns? i don't get this error :-(

**Comment by punker76** [comment]
@bigworld12 can you try without MahApps, cause at this place there is the style taken from microsoft

**Comment by bigworld12** [comment]
it's fixed somehow in the new alpha versions ...it's solved now
