### ISSUE TITLE
Animated TabControl Underline Position

### ISSUE THREAD

**Issue by jammerxd** [MahApps/MahApps.Metro#1872]
Hello,
I have noticed that on the Animated TabControl that the underline does not go under the text if the TabStripPlacement setting is set to Left or Right. Is there a way to set it so that the underline position is underneath the text instead of to the left or right? Also, is there a way to set a custom margin for the underline? I want it to ignore the padding so that I can place the underline as close or as far away from the text as possible.

**Comment by punker76** [comment]
@jammerxd I made some changes for the underline stuff (latest source for 1.5.0), so please look at the latest code. I think you can create your own style for the TabItems to get what you need. Just let me know if you need some help for it.
