### ISSUE TITLE
Change theme color using button

### ISSUE THREAD

**Issue by furiousbuilder** [MahApps/MahApps.Metro#1875]
Hi, 

I read a lot but I couldn't find a solution : in vb.net i'm not able to change the theme, even with 
Imports MahApps.Metro.Controls
Imports MahApps.Metro

ThemeManager.ChangeTheme is not recognized.

What is the working code ? 

Thanks !

**Comment by jammerxd** [comment]
You should use 
`ThemeManager.ChangeAppTheme(Application.Current, "BaseLight")`
or
`ThemeManager.ChangeAppTheme(Application.Current, "BaseDark")`
