### ISSUE TITLE
CleanWindow style not considered for statusbar

### ISSUE THREAD

**Issue by rasigle** [MahApps/MahApps.Metro#1877]
My app is using predefined CleanWindow style. However when putting a statusbar inside a window, the background of the statusbar still uses the current MahApps accent-color. Is this the intended behaviour?

The issue can be reproduced by simply inserting an arbitrary statusbar in CleanWindowDemo.xaml from MetroDemo sample-app. See the screenshot below:

![bild 1](https://cloud.githubusercontent.com/assets/10853340/7114678/119542a0-e1e0-11e4-9597-835a14ce47b8.png)

**Comment by thoemmi** [comment]
The **CleanWindow** style only refers to the window chrome. Controls such as the `StatusBar` control are not affected.

**Comment by rasigle** [comment]
Thanks for the clarification. I thought CleanWindow style could be applied like an overall theme and affects also the child controls.

I will simply add an additional "clean" (grey-like) accent style to my application.
