### ISSUE TITLE
ThemeManager does not change Theme if old Theme Resource is a nested MergedDictionary

### ISSUE THREAD

**Issue by BrunoJuchli** [MahApps/MahApps.Metro#1882]
`ThemeManager.ChangeAppStyle(ResourceDictionary, Tuple<AppTheme, Accent>, Accent, AppTheme)` contains the following code:

```
var oldThemeResource = resources.MergedDictionaries.FirstOrDefault(d => d.Source == oldTheme.Resources.Source);
```

This does not consider `MergedDictionaries` of `MergedDictionaries` (`resources.MergedDictionaries.SelectMany(x => x.MergedDictionaries)`)  or even more deeply nested `ResourceDictionary`s.
Now for specific reasons given later (*) in my application i have App.Xaml which has a `MergedDictionary` `App.GlobalResources.Xaml` which in turn again has a `MergedDictionary` `BaseLight.Xaml` (the Theme `ResourceDictionary`).
Is there a compulsory reason for this logic?

Furthermore, besides failing to change the theme the `ThemeManager` does not inform me that it failed. In conjunction with #1879 this leaves the user staring at the computer and wondering what went wrong.

---

I'd suggest changing the `ThemeManager` to throw an exception if it didn't change the theme. An exception can provide a meaningful reason why the theme wasn't changed ("could not find resource of old theme '.....'. Make sure you add it as `MergedDictionaries` to `App.xaml` directly").

_However_ i'm uncertain if the path "no old theme to remove found" is a valid one: Consider an example where there is no `BaseLight.xaml` `MergedDictionaries` anywhere put instead the user chose to initialize theming in the Bootstrapper - by using the  `ThemeManager`.

If that's the case, however, I'd suggest creating a separate method `InitializeTheme` which does not unload but just load the new Theme + Accent.

---

(*) My reason not to reference the theme dictionary directly in `App.xaml` is:
i'm putting all my shared/global resources in a separate `ResourceDictionary` because i need them for unit testing. However, during unit testing, I'm not able to load `App.xaml` (because it's triggering the entire bootstrapping mechanism and so forth..).

**Comment by BrunoJuchli** [comment]
Update: I've changed my App.xaml from:

    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="GlobalResources.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>

to

    <Application.Resources>
        <ResourceDictionary Source="GlobalResources.xaml"/>
    </Application.Resources>

This means I'm just using a redirect instead of merging the dictionary. It works - partially. Now i can change the theme, but the theme changes are not directly applied. If i load a new view - the new theme applies. However the view i'm currently looking at doesn't change.
Now i suspected that that is caused by me doing something wrong, like using a top-level `StaticResource` instead of a `DynamicResource`. However, that's not the case. When i move the contents of `GlobalResources.xaml` into `App.xaml` *everything* works fine. When i reference `GlobalResources.xaml` instead (redirect), it doesn't. But i think they should be equivalent. Why are they not? I don't know...

**Comment by punker76** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/MahApps/MahApps.Metro/releases) and then please use the [issue template](https://github.com/MahApps/MahApps.Metro/issues/new/choose).

If you have enough time then it would be nice to test this issue against the latest alpha version (availabe via [NuGet](https://www.nuget.org/packages/MahApps.Metro) and [appveyor](https://ci.appveyor.com/project/punker76/mahapps-metro/history)).

Thank you! 🙏

**Comment by BrunoJuchli** [comment]
@punker76 
I switched companies and I don't have access to the source anymore. It's too bad I didn't publish a  proper repro for this the last time. Will take this as a lesson learned (to always provide a minimal and verifiable repro case).
