### ISSUE TITLE
Typo in the website :D...

### ISSUE THREAD

**Issue by ClaudiuCornici** [MahApps/MahApps.Metro#1884]
Sorry if it's not the right place but I just wanted to report this to the devs.

at  http://mahapps.com/controls/split_dropdownbutton.html

theres a typo in the last sentance from  "This control almost the same as SplitButton with few differences: It has no SelectedItem and SelectedIndex properties and also has no SelectionChanged event. The content of the button also doesn't change, it's static. The Dropdownlist is a context menu instead of Listbox in SplitButton. <b>Inj</b> all other aspects it's identical to SplitButton."

**Comment by punker76** [comment]
@ClaudiuCornici hi, you can fork https://github.com/MahApps/mahapps.github.com and change (https://github.com/MahApps/mahapps.github.com/tree/master/controls) this, and after that push it by a pr...
