### ISSUE TITLE
Bug with Controls:NumericUpDown when setting Maximum programaticaly

### ISSUE THREAD

**Issue by ghost** [MahApps/MahApps.Metro#1885]
I have a Flyout panel with some elements on it.
1. ComboBox
2. ComboBox
3. NumericUpDown -> Maximum is set programaticaly based on value selected in 2. Minimum is set to 0 in xaml.

If I go and select a value in 1. then go select a value in 2. and go and click on any of the +- signs in 3. , they are disabled. I fix this by entering a number manualy, then going and clicking on another control (1. or 2.) then coming back to 3. Arrows are now finaly enabled. This doesn't happen if I set the Maximum only from XAML. I tried setting both in xaml and again in codebehind but issue still occurs

EDIT: I also tryied binding it from XAML to a int in codebehind, issue still occurs.

**Comment by punker76** [comment]
@xxMUROxx can you look at this? thx

**Comment by xxMUROxx** [comment]
@punker76 yes

**Comment by xxMUROxx** [comment]
@ghost can you try following PR if this exception is present also there?
https://github.com/MahApps/MahApps.Metro/pull/2245
