### ISSUE TITLE
Possible new issue with Datagrid column sorting ?

### ISSUE THREAD

**Issue by bradws** [MahApps/MahApps.Metro#1886]
Hi,

The standard DataGrid in the demo app "MetroDemo.NET45" that comes with v1.2.2 doesn't seem to be able to sort the columns ?!?

I have:
1. Added CanUserSortColumns="True" to the <DataGrid/>
2. Added SortMemberPath="Title" to the <DataGridTextColumn/>
3. Added CanUserSort="True" to the same <DataGridTextColumn/>

...yet when clicking on the column does nothing.

Please see the following snippet:

(In file samlpes/MetroDemo.NET45/ExampleViews/DataGridExamples.xaml  -  approx line 135 built with VS2012 .NET 4.5)

 ```
<DataGrid x:Name="MetroDataGrid"
    ...
    CanUserSortColumns="True">
    <DataGrid.Columns>
        ...
        <DataGridTextColumn Header="Title"
                                    Binding="{Binding Title}"
                                    SortMemberPath="Title"
                                    CanUserSort="True" />
        ...
    </DataGrid.Columns>
 <DataGrid>
```

Thanks,
Brad.

**Comment by punker76** [comment]
@bradws that's not a MahApps related issue. it's only because the demo doesn't handle the sort mechanism (it's not implemented...)
