### ISSUE TITLE
How to add image in a tile in MahApps

### ISSUE THREAD

**Issue by tayyabvohra** [MahApps/MahApps.Metro#1887]
I am trying to add a simply add a image icon inside a tile. Right now i have a .png file inside my source folder Iqra.png and i want to insert the image in a tile how i can do it. ?? I am very new to wpf forms and also not very fimilar with this... 

    <Controls:Tile Height="110" Background="#9c6b50" Width="180" VerticalAlignment="Top" HorizontalAlignment="Right" Margin="0,1,612,0">
            <Controls:Tile.Content>
                <TextBlock Text="Setup Your Savings Account" TextWrapping="Wrap" Width="121" HorizontalAlignment="Center" VerticalAlignment="Center"/>
            </Controls:Tile.Content>
        </Controls:Tile>

**Comment by BrunoJuchli** [comment]
The issues on github is primarily for filing bugs or feature requests, not for asking questions.

For asking questions, go to [stackoverflow.com](http://www.stackoverflow.com).
However, this is a question which has been asked many times before. So entering a few appropriate query strings should lead to the desired result.

General wpf questions should be tagged [[wpf]](http://stackoverflow.com/questions/tagged/wpf).
If you have Mahapps.metro related questions you should tag them [[mahapps.metro]](http://stackoverflow.com/questions/tagged/mahapps.metro).

**Comment by tayyabvohra** [comment]
ok
