### ISSUE TITLE
FlipView.xaml is not reusing `MetroCircleButtonStyle`

### ISSUE THREAD

**Issue by BrunoJuchli** [MahApps/MahApps.Metro#1888]
FlipView.xaml is defining it's own button style called `ControlButton`. Visually it's very similar to the `MetroCircleButtonStyle` of Button.xaml.

is there a specific reason that it uses a custom style which is not at least based on `MetroCircleButtonStyle`?

If not i'd suggest re-using `MetroCircleButtonStyle` in FlipView.xaml to make the code-base to maintain a little bit smaller ;-)

Also, for the chevron paths defined in FlipView.xaml exist very similar ones @ MahApps.Metro.Resources Icons.xaml.

**Comment by punker76** [comment]
mh the two styles are not similar and the MahApps.Metro.Resources are not part of MahApps itself
