### ISSUE TITLE
Windows 8 Scaling

### ISSUE THREAD

**Issue by atom0s** [MahApps/MahApps.Metro#1889]
I've been using MahApps.Metro for a while and love it, however recently more Windows 8 users are popping up and using my applications. With that I am getting a load of bug reports saying parts of my apps are cutting off at the bottom now while using them on Windows 8. I develop everything on Windows 7 at the current time and on my machine and test machines (WinXP, Win7) all is fine. However on Windows 8 the controls seem to get pushed down further and causes the window size to be invalid for Windows 8 machines. Here is an example of what I mean.

On Windows 7, the bottom bar is visible and fine:
http://i.imgur.com/B31n2i6.png

On Windows 8 the bar is completely pushed off the window and cannot be seen:
http://i.imgur.com/SMSCyfZ.png

I am not using any fancy or static positioning, it is all done via grid with columns/rows. Just like an html table, so there is nothing being done to enforce any specific location on the window. The window size is static to a specific size and non-resizable since it is not needed in general. 

DPI settings are not an issue as I have tested this in a Windows 8 VM and system and both have the problem too. DPI is set to normal 100% just like my Windows 7 machine and still no-go with working fine. 

Any idea(s) why this happens and how to fix it?

**Comment by killnine** [comment]
Can you paste some XAML for this usercontrol?

**Comment by atom0s** [comment]
I cannot paste things for this project since it is commercial. I can send it to a developer via email though if it will help find the problem. The issue is not resolved.

**Comment by punker76** [comment]
@atom0s you can contact me via twitter @punker76

**Comment by atom0s** [comment]
Sent you a message on Twitter.
