### ISSUE TITLE
dialog.TryFindParent<MetroWindow>() returns null

### ISSUE THREAD

**Issue by ye4241** [MahApps/MahApps.Metro#1891]
ShowProgressAsync of a MetroWindow with a Accented ColorScheme >> the code decetes the window theme and returns null.
__in BaseMetroDialog.cs__
```
            //null
            var window = dialog.TryFindParent<MetroWindow>();
```
__in TreeHelper.cs__
_TryFindParent<T>_
```
...
            //null
            DependencyObject parentObject = GetParentObject(child);
...
```
_GetParentObject_
```
...
                //null,cause return the next code
                DependencyObject parent = frameworkElement.Parent; 
...
            //null
            return VisualTreeHelper.GetParent(child);
```

The widnow returns null, __however the dialog's OwningWindow is not null.__

**Comment by punker76** [comment]
@ye4241 can you tets the latest alpha? maybe it's fixed now...
