### ISSUE TITLE
TreeView and large data

### ISSUE THREAD

**Issue by bloodyroll** [MahApps/MahApps.Metro#1896]
Please test TreeView with large data. There is big problems with data perfomance because VirtualizingStackPanel is disabled.
The following properties do not work:
                 > VirtualizingStackPanel.IsVirtualizing="True"
                 > VirtualizingStackPanel.VirtualizationMode="Recycling"

**Comment by punker76** [comment]
@bloodyroll i will do that for 1.2.0
