### ISSUE TITLE
Disable window animation on start-up ?

### ISSUE THREAD

**Issue by barryBithead** [MahApps/MahApps.Metro#1897]
Love the library !

However, my boss isn't too keen on the little slide animation that happens with the MainWindow when the app starts up. How can I disable that ?

**Comment by mike-ward** [comment]
Same here. When I start Markdown Edit there's a window frame that appears very briefly before the application appears. I've set `WindowTransistionsEnabled="False"` in the main window

**Comment by barryBithead** [comment]
That did it !....thanx !

**Comment by mike-ward** [comment]
Not exactly what I meant but glad it worked for you! I've set this in my program (Markdown Edit) and still see a brief frame paint before the window appears.

**Comment by barryBithead** [comment]
Ahh, yes... I noticed it now. I can live with that, assuming there is no cleaner method...

**Comment by punker76** [comment]
@mike-ward the alpha #1.1.3.21 fix this issue "...and still see a brief frame paint before the window appears."

**Comment by barryBithead** [comment]
1.1.3.21 does fix it ?....your message was ambiguous.
If it does fix it, how stable is 1.1.3.21 ?
Thanks, Barry

**Comment by punker76** [comment]
mh... should be stable enough 8-D

**Comment by patrykdawid** [comment]
Hi! I downloaded version 1.1.3-ALPHA028 (the latest of Nuget). Unfortunately, "zoom-in" effect persists even after setting WindowTransistionsEnabled = "False".
How can it be effectively turn off this effect?

**Comment by punker76** [comment]
@patrykdawid the "zoom-in" effect is a hard/heart created "feature" for borderless MahApps MetroWindow....
