### ISSUE TITLE
How do you over-ride the title bar background colour ?

### ISSUE THREAD

**Issue by barryBithead** [MahApps/MahApps.Metro#1898]
Hi,

I'm using the default theme, and I need to over-ride the window title bar colour to a specific value. Its default is a teal colour...I need to be able to make it whatever I need it to be. I saw something about "UseIdeal" or something like that, but no specific example. Anyway, I need to be able to bind to whatever colour I want.

Thanks,

Barry

![image](https://cloud.githubusercontent.com/assets/8738827/7302351/c89caa32-e9b6-11e4-9b08-35adddca4db4.png)

**Comment by thoemmi** [comment]
As far as I can see it is [`MetroWindow.WindowTitleBrush`](https://github.com/MahApps/MahApps.Metro/blob/master/MahApps.Metro/Controls/MetroWindow.cs#L546-L553)

**Comment by barryBithead** [comment]
That was it...thanx..

"Mental note to self - look at the properties bar for the window, as it's been re-designed by MetroWindow !"....
