### ISSUE TITLE
Cannot Publish

### ISSUE THREAD

**Issue by LokizFenrir** [MahApps/MahApps.Metro#1899]
It seems there is an issue with compiling the WPF MahApp project.
I have tested my own code as well as numerous other, including samples such as (https://github.com/punker76/MahApps.Metro.Simple.Demo).
All of these exit with an OutOfMemoryException in PresentationCore:

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	MahApps.Metro.Simple.Demo.exe
  Problem Signature 02:	1.0.0.0
  Problem Signature 03:	5539e9ab
  Problem Signature 04:	PresentationCore
  Problem Signature 05:	4.0.30319.34209
  Problem Signature 06:	5348bc89
  Problem Signature 07:	55b7
  Problem Signature 08:	e
  Problem Signature 09:	System.OutOfMemoryException
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	7177
  Additional Information 1:	3ab4
  Additional Information 2:	3ab442b5d19fd115811fc50705552796
  Additional Information 3:	5adb
  Additional Information 4:	5adb5d203664585eb3210f2e595a8304

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

Please assist or explain why/how to publish and compile MahApp.Metro apps.

**Comment by punker76** [comment]
@LokizFenrir which MahApps version? maybe a full stacktrace can be helpful.

**Comment by LokizFenrir** [comment]
Thanks for the quick reply, within VS2013 it runs/debugs fine, but in the published source it fails on the application file with the previous message on both MahApp 1.0.0.8 and 1.1.2.0                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Jan KargerSent: Friday 24 April 2015 9:24 AMTo: MahApps/MahApps.MetroReply To: MahApps/MahApps.MetroCc: LokizFenrirSubject: Re: [MahApps.Metro] Cannot Publish (#1899)@LokizFenrir which MahApps version? maybe a full stacktrace can be helpful.

—Reply to this email directly or view it on GitHub.

**Comment by LokizFenrir** [comment]
On MahApp 1.0.0.8:
'MahApps.Metro.Simple.Demo.vshost.exe' (CLR v4.0.30319: MahApps.Metro.Simple.Demo.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MahApps.Metro.Simple.Demo.vshost.exe' (CLR v4.0.30319: MahApps.Metro.Simple.Demo.vshost.exe): Loaded 'C:\Windows\assembly\GAC_MSIL\Microsoft.VisualStudio.HostingProcess.Utilities\12.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.HostingProcess.Utilities.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MahApps.Metro.Simple.Demo.vshost.exe' (CLR v4.0.30319: MahApps.Metro.Simple.Demo.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MahApps.Metro.Simple.Demo.vshost.exe' (CLR v4.0.30319: MahApps.Metro.Simple.Demo.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MahApps.Metro.Simple.Demo.vshost.exe' (CLR v4.0.30319: MahApps.Metro.Simple.Demo.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MahApps.Metro.Simple.Demo.vshost.exe' (CLR v4.0.30319: MahApps.Metro.Simple.Demo.vshost.exe): Loaded 'C:\Windows\assembly\GAC_MSIL\Microsoft.VisualStudio.HostingProcess.Utilities.Sync\12.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.HostingProcess.Utilities.Sync.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MahApps.Metro.Simple.Demo.vshost.exe' (CLR v4.0.30319: MahApps.Metro.Simple.Demo.vshost.exe): Loaded 'C:\Windows\assembly\GAC_MSIL\Microsoft.VisualStudio.Debugger.Runtime\12.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.Debugger.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MahApps.Metro.Simple.Demo.vshost.exe' (CLR v4.0.30319: MahApps.Metro.Simple.Demo.vshost.exe): Loaded 'C:\Users\Laurens Strydom\Documents\Visual Studio 2013\Projects\Insurance\WPF\MahApps.Metro.Simple.Demo\MahApps.Metro.Simple.Demo\bin\Debug\MahApps.Metro.Simple.Demo.vshost.exe'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MahApps.Metro.Simple.Demo.vshost.exe' (CLR v4.0.30319: MahApps.Metro.Simple.Demo.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MahApps.Metro.Simple.Demo.vshost.exe' (CLR v4.0.30319: MahApps.Metro.Simple.Demo.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MahApps.Metro.Simple.Demo.vshost.exe' (CLR v4.0.30319: MahApps.Metro.Simple.Demo.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MahApps.Metro.Simple.Demo.vshost.exe' (CLR v4.0.30319: MahApps.Metro.Simple.Demo.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.CSharp\v4.0_4.0.0.0__b03f5f7f11d50a3a\Microsoft.CSharp.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MahApps.Metro.Simple.Demo.vshost.exe' (CLR v4.0.30319: MahApps.Metro.Simple.Demo.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MahApps.Metro.Simple.Demo.vshost.exe' (CLR v4.0.30319: MahApps.Metro.Simple.Demo.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Data.DataSetExtensions\v4.0_4.0.0.0__b77a5c561934e089\System.Data.DataSetExtensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MahApps.Metro.Simple.Demo.vshost.exe' (CLR v4.0.30319: MahApps.Metro.Simple.Demo.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MahApps.Metro.Simple.Demo.vshost.exe' (CLR v4.0.30319: MahApps.Metro.Simple.Demo.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MahApps.Metro.Simple.Demo.vshost.exe' (CLR v4.0.30319: MahApps.Metro.Simple.Demo.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_64\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MahApps.Metro.Simple.Demo.vshost.exe' (CLR v4.0.30319: MahApps.Metro.Simple.Demo.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The thread 0x37b8 has exited with code 259 (0x103).
The thread 0x2dd0 has exited with code 259 (0x103).
The thread 0x1430 has exited with code 0 (0x0).
The thread 0x36d4 has exited with code 259 (0x103).
'MahApps.Metro.Simple.Demo.vshost.exe' (CLR v4.0.30319: MahApps.Metro.Simple.Demo.vshost.exe): Loaded 'C:\Users\Laurens Strydom\Documents\Visual Studio 2013\Projects\Insurance\WPF\MahApps.Metro.Simple.Demo\MahApps.Metro.Simple.Demo\bin\Debug\MahApps.Metro.Simple.Demo.exe'. Symbols loaded.
'MahApps.Metro.Simple.Demo.vshost.exe' (CLR v4.0.30319: MahApps.Metro.Simple.Demo.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Accessibility\v4.0_4.0.0.0__b03f5f7f11d50a3a\Accessibility.dll'. Cannot find or open the PDB file.
'MahApps.Metro.Simple.Demo.vshost.exe' (CLR v4.0.30319: MahApps.Metro.Simple.Demo.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MahApps.Metro.Simple.Demo.vshost.exe' (CLR v4.0.30319: MahApps.Metro.Simple.Demo.vshost.exe): Loaded 'C:\Users\Laurens Strydom\Documents\Visual Studio 2013\Projects\Insurance\WPF\MahApps.Metro.Simple.Demo\MahApps.Metro.Simple.Demo\bin\Debug\MahApps.Metro.dll'. Module was built without symbols.
'MahApps.Metro.Simple.Demo.vshost.exe' (CLR v4.0.30319: MahApps.Metro.Simple.Demo.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.Aero\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.Aero.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MahApps.Metro.Simple.Demo.vshost.exe' (CLR v4.0.30319: MahApps.Metro.Simple.Demo.vshost.exe): Loaded 'System.Windows.Interactivity'. Cannot find or open the PDB file.
'MahApps.Metro.Simple.Demo.vshost.exe' (CLR v4.0.30319: MahApps.Metro.Simple.Demo.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemXml\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemXml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MahApps.Metro.Simple.Demo.vshost.exe' (CLR v4.0.30319: MahApps.Metro.Simple.Demo.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\UIAutomationProvider\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationProvider.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'MahApps.Metro.Simple.Demo.vshost.exe' (CLR v4.0.30319: MahApps.Metro.Simple.Demo.vshost.exe): Loaded 

'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\UIAutomationTypes\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationTypes.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The thread 0x37d4 has exited with code 259 (0x103).
The thread 0xcac has exited with code 259 (0x103).
The program '[11384] MahApps.Metro.Simple.Demo.vshost.exe: Program Trace' has exited with code 0 (0x0).
The program '[11384] MahApps.Metro.Simple.Demo.vshost.exe' has exited with code 0 (0x0).

**Comment by LokizFenrir** [comment]
On MahApp 1.1.2.0:

'MetroInsu.vshost.exe' (CLR v4.0.30319: MetroInsu.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Cannot find or open the PDB file.
'MetroInsu.vshost.exe' (CLR v4.0.30319: MetroInsu.vshost.exe): Loaded 'C:\Windows\assembly\GAC_MSIL\Microsoft.VisualStudio.HostingProcess.Utilities\12.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.HostingProcess.Utilities.dll'. Cannot find or open the PDB file.
'MetroInsu.vshost.exe' (CLR v4.0.30319: MetroInsu.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll'. Cannot find or open the PDB file.
'MetroInsu.vshost.exe' (CLR v4.0.30319: MetroInsu.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll'. Cannot find or open the PDB file.
'MetroInsu.vshost.exe' (CLR v4.0.30319: MetroInsu.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll'. Cannot find or open the PDB file.
'MetroInsu.vshost.exe' (CLR v4.0.30319: MetroInsu.vshost.exe): Loaded 'C:\Windows\assembly\GAC_MSIL\Microsoft.VisualStudio.HostingProcess.Utilities.Sync\12.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.HostingProcess.Utilities.Sync.dll'. Cannot find or open the PDB file.
'MetroInsu.vshost.exe' (CLR v4.0.30319: MetroInsu.vshost.exe): Loaded 'C:\Windows\assembly\GAC_MSIL\Microsoft.VisualStudio.Debugger.Runtime\12.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.Debugger.Runtime.dll'. 
'MetroInsu.vshost.exe' (CLR v4.0.30319: MetroInsu.vshost.exe): Loaded 'C:\Users\Laurens Strydom\Documents\Visual Studio 2013\Projects\Insurance\WPF\MetroInsu\MetroInsu\bin\x86\Debug\MetroInsu.vshost.exe'. Cannot find or open the PDB file.
'MetroInsu.vshost.exe' (CLR v4.0.30319: MetroInsu.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll'. Cannot find or open the PDB file.
'MetroInsu.vshost.exe' (CLR v4.0.30319: MetroInsu.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll'. Cannot find or open the PDB file.
'MetroInsu.vshost.exe' (CLR v4.0.30319: MetroInsu.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll'. Cannot find or open the PDB file.
'MetroInsu.vshost.exe' (CLR v4.0.30319: MetroInsu.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.CSharp\v4.0_4.0.0.0__b03f5f7f11d50a3a\Microsoft.CSharp.dll'. Cannot find or open the PDB file.
'MetroInsu.vshost.exe' (CLR v4.0.30319: MetroInsu.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll'. Cannot find or open the PDB file.
'MetroInsu.vshost.exe' (CLR v4.0.30319: MetroInsu.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Data.DataSetExtensions\v4.0_4.0.0.0__b77a5c561934e089\System.Data.DataSetExtensions.dll'. Cannot find or open the PDB file.
'MetroInsu.vshost.exe' (CLR v4.0.30319: MetroInsu.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll'. Cannot find or open the PDB file.
'MetroInsu.vshost.exe' (CLR v4.0.30319: MetroInsu.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll'. Cannot find or open the PDB file.
'MetroInsu.vshost.exe' (CLR v4.0.30319: MetroInsu.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_32\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll'. Cannot find or open the PDB file.
'MetroInsu.vshost.exe' (CLR v4.0.30319: MetroInsu.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll'. Cannot find or open the PDB file.
The thread 0x2460 has exited with code 259 (0x103).
The thread 0x2e18 has exited with code 259 (0x103).
The thread 0x2674 has exited with code 259 (0x103).
'MetroInsu.vshost.exe' (CLR v4.0.30319: MetroInsu.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Cannot find or open the PDB file.
'MetroInsu.vshost.exe' (CLR v4.0.30319: MetroInsu.vshost.exe): Loaded 'C:\Windows\assembly\GAC_MSIL\Microsoft.VisualStudio.HostingProcess.Utilities\12.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.HostingProcess.Utilities.dll'. Cannot find or open the PDB file.
'MetroInsu.vshost.exe' (CLR v4.0.30319: MetroInsu.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll'. Cannot find or open the PDB file.
'MetroInsu.vshost.exe' (CLR v4.0.30319: MetroInsu.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll'. Cannot find or open the PDB file.
'MetroInsu.vshost.exe' (CLR v4.0.30319: MetroInsu.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll'. Cannot find or open the PDB file.
'MetroInsu.vshost.exe' (CLR v4.0.30319: MetroInsu.vshost.exe): Loaded 'C:\Windows\assembly\GAC_MSIL\Microsoft.VisualStudio.HostingProcess.Utilities.Sync\12.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.HostingProcess.Utilities.Sync.dll'. Cannot find or open the PDB file.
'MetroInsu.vshost.exe' (CLR v4.0.30319: MetroInsu.vshost.exe): Loaded 'C:\Windows\assembly\GAC_MSIL\Microsoft.VisualStudio.Debugger.Runtime\12.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.Debugger.Runtime.dll'. 
'MetroInsu.vshost.exe' (CLR v4.0.30319: MetroInsu.vshost.exe): Loaded 'C:\Users\Laurens Strydom\Documents\Visual Studio 2013\Projects\Insurance\WPF\MetroInsu\MetroInsu\bin\x86\Debug\MetroInsu.vshost.exe'. Cannot find or open the PDB file.
'MetroInsu.vshost.exe' (CLR v4.0.30319: MetroInsu.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll'. Cannot find or open the PDB file.
'MetroInsu.vshost.exe' (CLR v4.0.30319: MetroInsu.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll'. Cannot find or open the PDB file.
'MetroInsu.vshost.exe' (CLR v4.0.30319: MetroInsu.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll'. Cannot find or open the PDB file.
'MetroInsu.vshost.exe' (CLR v4.0.30319: MetroInsu.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.CSharp\v4.0_4.0.0.0__b03f5f7f11d50a3a\Microsoft.CSharp.dll'. Cannot find or open the PDB file.
'MetroInsu.vshost.exe' (CLR v4.0.30319: MetroInsu.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll'. Cannot find or open the PDB file.
'MetroInsu.vshost.exe' (CLR v4.0.30319: MetroInsu.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Data.DataSetExtensions\v4.0_4.0.0.0__b77a5c561934e089\System.Data.DataSetExtensions.dll'. Cannot find or open the PDB file.
'MetroInsu.vshost.exe' (CLR v4.0.30319: MetroInsu.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll'. Cannot find or open the PDB file.
'MetroInsu.vshost.exe' (CLR v4.0.30319: MetroInsu.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll'. Cannot find or open the PDB file.
'MetroInsu.vshost.exe' (CLR v4.0.30319: MetroInsu.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_32\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll'. Cannot find or open the PDB file.
'MetroInsu.vshost.exe' (CLR v4.0.30319: MetroInsu.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll'. Cannot find or open the PDB file.
The program '[8336] MetroInsu.vshost.exe: Program Trace' has exited with code 0 (0x0).
The program '[8336] MetroInsu.vshost.exe' has exited with code 0 (0x0).
The thread 0x2630 has exited with code 259 (0x103).
The thread 0x1358 has exited with code 259 (0x103).
'MetroInsu.vshost.exe' (CLR v4.0.30319: MetroInsu.vshost.exe): Loaded 'C:\Users\Laurens Strydom\Documents\Visual Studio 2013\Projects\Insurance\WPF\MetroInsu\MetroInsu\bin\x86\Debug\MetroInsu.exe'. Symbols loaded.
'MetroInsu.vshost.exe' (CLR v4.0.30319: MetroInsu.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Accessibility\v4.0_4.0.0.0__b03f5f7f11d50a3a\Accessibility.dll'. Cannot find or open the PDB file.
'MetroInsu.vshost.exe' (CLR v4.0.30319: MetroInsu.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll'. Cannot find or open the PDB file.
'MetroInsu.vshost.exe' (CLR v4.0.30319: MetroInsu.vshost.exe): Loaded 'C:\Users\Laurens Strydom\Documents\Visual Studio 2013\Projects\Insurance\WPF\MetroInsu\MetroInsu\bin\x86\Debug\MahApps.Metro.dll'. Module was built without symbols.
'MetroInsu.vshost.exe' (CLR v4.0.30319: MetroInsu.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.Aero\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.Aero.dll'. Cannot find or open the PDB file.
'MetroInsu.vshost.exe' (CLR v4.0.30319: MetroInsu.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemXml\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemXml.dll'. Cannot find or open the PDB file.
'MetroInsu.vshost.exe' (CLR v4.0.30319: MetroInsu.vshost.exe): Loaded 'C:\Users\Laurens Strydom\Documents\Visual Studio 2013\Projects\Insurance\WPF\MetroInsu\MetroInsu\bin\x86\Debug\System.Windows.Interactivity.dll'. Cannot find or open the PDB file.
'MetroInsu.vshost.exe' (CLR v4.0.30319: MetroInsu.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemXmlLinq\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemXmlLinq.dll'. Cannot find or open the PDB file.
'MetroInsu.vshost.exe' (CLR v4.0.30319: MetroInsu.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\UIAutomationProvider\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationProvider.dll'. Cannot find or open the PDB file.
'MetroInsu.vshost.exe' (CLR v4.0.30319: MetroInsu.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\UIAutomationTypes\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationTypes.dll'. Cannot find or open the PDB file.
The thread 0x37ec has exited with code 259 (0x103).
The thread 0xe7c has exited with code 259 (0x103).
The program '[12584] MetroInsu.vshost.exe: Program Trace' has exited with code 0 (0x0).
The program '[12584] MetroInsu.vshost.exe' has exited with code 0 (0x0).

**Comment by punker76** [comment]
@LokizFenrir mh, why do you start the `MetroInsu.vshost.exe` ? or is this the visual studio run?

**Comment by LokizFenrir** [comment]
Visual studio run, as this is the only way the application executes.It seems there is problems with mahApp's internal references to dot net libraries it uses.                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Jan KargerSent: Friday 24 April 2015 10:30 AMTo: MahApps/MahApps.MetroReply To: MahApps/MahApps.MetroCc: LokizFenrirSubject: Re: [MahApps.Metro] Cannot Publish (#1899)@LokizFenrir mh, why do you start the MetroInsu.vshost.exe ? or is this the visual studio run?

—Reply to this email directly or view it on GitHub.

**Comment by punker76** [comment]
@LokizFenrir mh, sorry, i have no problems with that, you are the first one with this...

**Comment by LokizFenrir** [comment]
Can I send my code to you, maybe there is just a strange lil bug somewhere that for the life of me I cannot find?                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Jan KargerSent: Friday 24 April 2015 10:55 AMTo: MahApps/MahApps.MetroReply To: MahApps/MahApps.MetroCc: LokizFenrirSubject: Re: [MahApps.Metro] Cannot Publish (#1899)@LokizFenrir mh, sorry, i have no problems with that, you are the first one with this...

—Reply to this email directly or view it on GitHub.

**Comment by bigworld12** [comment]
I had the same problem
1 - are you sure your dlls are with the exe
2 - are you sure the program is running in a read / write folder (not read
only)

**Comment by LokizFenrir** [comment]
Difinitely in a read write directory, and all the dll's have been included, based on the nuget package, also double checked it.                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: bigworld12Sent: Friday 10 July 2015 6:31 PMTo: MahApps/MahApps.MetroReply To: MahApps/MahApps.MetroCc: LokizFenrirSubject: Re: [MahApps.Metro] Cannot Publish (#1899)I had the same problem
1 - are you sure your dlls are with the exe
2 - are you sure the program is running in a read / write folder (not read
only)


—Reply to this email directly or view it on GitHub.
