### ISSUE TITLE
NumericUpDown won't focus programatically

### ISSUE THREAD

**Issue by PhilPJL** [MahApps/MahApps.Metro#1903]
I'm unable to find a method from code to set the focus on a NumericUpDown control, e.g.

.Focus()
FocusManager.SetFocusedElement

don't work.

**Comment by JacBal** [comment]
Same problem here.
Very annoying.

**Comment by punker76** [comment]
@PhilPJL @JacBal -> https://github.com/MahApps/MahApps.Metro/pull/1959
