### ISSUE TITLE
ToggleSwitch Click event handler is never called

### ISSUE THREAD

**Issue by andyste1** [MahApps/MahApps.Metro#1908]
As the title says, I've wired up a Click event handler but it never gets called.

**Comment by punker76** [comment]
@andyste1 i tested with teh following code and it works...
```xaml
<Controls:ToggleSwitch IsChecked="True"
                        Checked="ToggleSwitch_OnChecked"
                        Unchecked="ToggleSwitch_OnUnchecked"
                        Header="ToggleSwitch Header" />
```

```csharp
private void ToggleSwitch_OnChecked(object sender, RoutedEventArgs e)
{
    MessageBox.Show("OnChecked");
}

private void ToggleSwitch_OnUnchecked(object sender, RoutedEventArgs e)
{
    MessageBox.Show("OnUnchecked");
}
```

**Comment by N0ct3** [comment]
Actually, I think he was referring to the "Click" event handler. I just made the test, it was working in version 0.13.1, and it is no longer working since at least version 1.1.2 (haven't tried with every version).

**Comment by fahminlb33** [comment]
I'm facing the same issue. Click/Checked/Unchecked never get called.
Checked called only first time when app launches.
