### ISSUE TITLE
Minimized and not ShowInTaskbar shows windows buttons command 

### ISSUE THREAD

**Issue by Antonyo** [MahApps/MahApps.Metro#1912]
Hello, if you set the property *ShowInTaskbar* to false in any MetroWindow and the window is minimized, when mouse over the minimized window it displays the standard Windows buttons commands which does not fit with the style. 

It would be nice if the Metro Windows Commands button shows instead or at least not display the Windows one.

You an recreate it by setting *ShowInTaskbar* as false in any of your examples.

Thanks

**Comment by punker76** [comment]
@Antonyo can you show me a screenshot? which MahApps version?

**Comment by punker76** [comment]
@Antonyo ???

**Comment by Antonyo** [comment]
Sorry about this, the version I'm using is 1.1.3-ALPHA009 and this is a recording of the case

https://antonyo.tinytake.com/sf/MTY3NTAyXzEwNTk1NzY

Thanks in advance

**Comment by Antonyo** [comment]
No, I just cropped the video by a region of my screen but when minimized there´s no icon in taskbar (that´s the point of ShowInTaskbar=false).
