### ISSUE TITLE
TabItem rotation and style issue

### ISSUE THREAD

**Issue by Coloris** [MahApps/MahApps.Metro#1913]
Hello,

I'm trying to set some tabitems headers vertically but doing so disable mahapps style:

![mahappstabitems](https://cloud.githubusercontent.com/assets/5500198/7436087/ec117634-f017-11e4-8599-44c53dfd0765.png)
my XAML :

    <TabControl Height="422" HorizontalAlignment="Left" Margin="12,12,0,0" Name="tabControl1"     VerticalAlignment="Top" Width="1058">
            <TabItem Header="tabItem1" Name="tabItem1">
                <TabControl TabStripPlacement="Left">
                    <TabControl.Resources>
                        <Style TargetType="{x:Type TabItem}">
                            <Setter Property="Padding" Value="8" />
                            <Setter Property="HeaderTemplate">
                                <Setter.Value>
                                    <DataTemplate>
                                        <ContentPresenter Content="{TemplateBinding Content}">
                                            <ContentPresenter.LayoutTransform>
                                                <RotateTransform Angle="270" />
                                            </ContentPresenter.LayoutTransform>
                                        </ContentPresenter>
                                    </DataTemplate>
                                </Setter.Value>
                            </Setter>
                        </Style>
                    </TabControl.Resources>

                    <TabItem Header="Item 1" />
                    <TabItem Header="Item 2" />
                </TabControl>
            </TabItem>
        </TabControl>

If I use Style="{DynamicResource MetroTabItem}" the style works but my text is horizontal again.

**Comment by punker76** [comment]
@Coloris you should inherit your custom style from the base style
```xaml
<Style TargetType="{x:Type TabItem}" BasedOn="{StaticResource MetroTabItem}">
...
</Style>
```

**Comment by Coloris** [comment]
Thank you it works :)
