### ISSUE TITLE
Binding to NumericUpDown.IsReadOnly does not work

### ISSUE THREAD

**Issue by scionwest** [MahApps/MahApps.Metro#1914]
<controls:NumericUpDown Width="50"
                            VerticalAlignment="Center"
                            HideUpDownButtons="True"
                            IsReadOnly="{Binding Path=IsReadOnly}"
                            Minimum="0"
                            TabIndex="1"
                            TextAlignment="Center"
                            Validation.ErrorTemplate="{x:Null}"
                            Value="{Binding Path=ACRandomNumberCoreForm.LotNumber}" />

When I bind to the IsReadOnly property on the NumericUpDown control, the control does not go in to a readonly state. In this example, the IsReadOnly property is true, but the control still allows users to edit it.

Is this a known issue? I'm using MahApps 1.1.2.0.

**Comment by xxMUROxx** [comment]
I have fixed this issue in f484271 see #1840. It is currently not published to the stable version on nuget. You could try using the current prerelease version.
