### ISSUE TITLE
Flyout : IsPinned is not working, How to pin a flyout?

### ISSUE THREAD

**Issue by Girishiyoo** [MahApps/MahApps.Metro#1916]
Flyout should close automatically when mouse out of it and how to pin a flyout?

![mahapperror](https://cloud.githubusercontent.com/assets/12268044/7488772/4f9f8830-f3ec-11e4-92c2-8fbf08c49fb7.png)

**Comment by punker76** [comment]
>Flyout should close automatically when mouse out of it

should already work

>and how to pin a flyout?

set `IsPinned` to false on `Flyout` (so you can create your own `HeaderTemplate` with an additional toggle button to do this
