### ISSUE TITLE
ToggleSwitch validation shows red border but doesn't show error text

### ISSUE THREAD

**Issue by TravyDale** [MahApps/MahApps.Metro#1917]
I am attempting to use the ToggleSwitch and have validation on it. The red border is appearing but it doesn't show the error text popup like it normally does on a texbox or some other control. Is this even possible?

**Comment by punker76** [comment]
@TravyDale after merging #1945 pr the default mahapps validation error template is supported, also if you click on the header, content or toggle button the switch is focused.
