### ISSUE TITLE
Cannot find Control TextboxHelper

### ISSUE THREAD

**Issue by spprtmechanic** [MahApps/MahApps.Metro#1918]
Updated to latest version on NuGet for my project that uses MahApps.Metro and received the error: Cannot find TextboxHelper.ClearTextButton (and others).
New version appears to be 1.1.2.0.

The problem is the previous versions used TextboxHelper.(whatever) as opposed to the new one using TextBoxHelper.(whatever). The b in box is now an upper case. Changing the existing control to match the correct case resolves the problem.

**Comment by flagbug** [comment]
Yes, this was a change in version 1.0.0:

https://github.com/MahApps/MahApps.Metro/releases/tag/1.0.0

**Comment by spprtmechanic** [comment]
Hello Dennis,

I saw that in the previous notes but I had updated from 1.1 to 1.1.2 when
it happened.That is why I thought I would mention it.

thanks,

Jeff Hamilton

**Comment by punker76** [comment]
@spprtmechanic sometimes it's necessary to clean yout `obj` and `bin` folders and restart visual studio.
