### ISSUE TITLE
JIT Compiler encountered an internal limitation

### ISSUE THREAD

**Issue by dizruptor** [MahApps/MahApps.Metro#1919]
I created a new WPF 4.5 C# project in VS2013 on Win7 64bit then installed with nuget: Install-Package MahApps.Metro ('MahApps.Metro 1.1.2.0'). Then I did exactly as in the "Quick Start". The app builds without any errors or warnings - however, when I try to run, I get a System.InvalidProgramException error: "JIT Compiler encountered an internal limitation."

Any ideas why I'm getting this and how to resolve would be appreciated? 

All my other projects run OK.

Here are the error details:
System.InvalidProgramException occurred
  _HResult=-2146233030
  _message=JIT Compiler encountered an internal limitation.
  HResult=-2146233030
  IsTransient=false
  Message=JIT Compiler encountered an internal limitation.
  Source=MahApps.Metro
  StackTrace:
       at MahApps.Metro.Controls.TreeHelper.TryFindParent[T](DependencyObject child)
       at MahApps.Metro.Controls.WindowCommands.OnApplyTemplate()
  InnerException: 

Thanks, Simon

**Comment by punker76** [comment]
@dizruptor can you check this -> https://support.microsoft.com/en-us/kb/312544
if this doesn't help, can you provide a full stack trace?
thx

**Comment by dizruptor** [comment]
Thanks for the link. I've done a bit more testing and the error only occurs on x86 builds when run within  VS. Also have an issue that the min, restore and close window controls don't work when run from within VS. I'll test on a different VS environment when I'm back at work next week.

**Comment by S3NS4Ti0N** [comment]
Even i got this issue.

If self compiled or installed by NuGet

 	MahApps.Metro.dll!MahApps.Metro.Controls.WindowCommands.OnApplyTemplate()	C#
 	PresentationFramework.dll!System.Windows.FrameworkElement.ApplyTemplate()	C#
 	PresentationFramework.dll!System.Windows.FrameworkElement.MeasureCore(System.Windows.Size availableSize = {unbekannt})	C#
 	PresentationCore.dll!System.Windows.UIElement.Measure(System.Windows.Size availableSize = {unbekannt})	C#
 	PresentationFramework.dll!MS.Internal.Helper.MeasureElementWithSingleChild(System.Windows.UIElement element = {unbekannt}, System.Windows.Size constraint = {unbekannt})	C#
 	PresentationFramework.dll!System.Windows.Controls.ContentPresenter.MeasureOverride(System.Windows.Size constraint = {unbekannt})	C#
 	PresentationFramework.dll!System.Windows.FrameworkElement.MeasureCore(System.Windows.Size availableSize = {unbekannt})	C#
 	PresentationCore.dll!System.Windows.UIElement.Measure(System.Windows.Size availableSize = {unbekannt})	C#
 	PresentationFramework.dll!System.Windows.Controls.Grid.MeasureCell(int cell = {unbekannt}, bool forceInfinityV = {unbekannt})	C#
 	PresentationFramework.dll!System.Windows.Controls.Grid.MeasureCellsGroup(int cellsHead = {unbekannt}, System.Windows.Size referenceSize = {unbekannt}, bool ignoreDesiredSizeU = {unbekannt}, bool forceInfinityV = {unbekannt}, out bool hasDesiredSizeUChanged = {unbekannt})	C#
 	PresentationFramework.dll!System.Windows.Controls.Grid.MeasureCellsGroup(int cellsHead = {unbekannt}, System.Windows.Size referenceSize = {unbekannt}, bool ignoreDesiredSizeU = {unbekannt}, bool forceInfinityV = {unbekannt})	C#
 	PresentationFramework.dll!System.Windows.Controls.Grid.MeasureOverride(System.Windows.Size constraint = {unbekannt})	C#
 	PresentationFramework.dll!System.Windows.FrameworkElement.MeasureCore(System.Windows.Size availableSize = {unbekannt})	C#
 	PresentationCore.dll!System.Windows.UIElement.Measure(System.Windows.Size availableSize = {unbekannt})	C#
 	PresentationFramework.dll!System.Windows.Controls.Decorator.MeasureOverride(System.Windows.Size constraint = {unbekannt})	C#
 	PresentationFramework.dll!System.Windows.Documents.AdornerDecorator.MeasureOverride(System.Windows.Size constraint = {unbekannt})	C#
 	PresentationFramework.dll!System.Windows.FrameworkElement.MeasureCore(System.Windows.Size availableSize = {unbekannt})	C#
 	PresentationCore.dll!System.Windows.UIElement.Measure(System.Windows.Size availableSize = {unbekannt})	C#
 	PresentationFramework.dll!System.Windows.Controls.Grid.MeasureOverride(System.Windows.Size constraint = {unbekannt})	C#
 	PresentationFramework.dll!System.Windows.FrameworkElement.MeasureCore(System.Windows.Size availableSize = {unbekannt})	C#
 	PresentationCore.dll!System.Windows.UIElement.Measure(System.Windows.Size availableSize = {unbekannt})	C#
 	PresentationFramework.dll!System.Windows.Window.MeasureOverrideHelper(System.Windows.Size constraint = {unbekannt})	C#
 	PresentationFramework.dll!System.Windows.Window.MeasureOverride(System.Windows.Size availableSize = {unbekannt})	C#
 	PresentationFramework.dll!System.Windows.FrameworkElement.MeasureCore(System.Windows.Size availableSize = {unbekannt})	C#
 	PresentationCore.dll!System.Windows.UIElement.Measure(System.Windows.Size availableSize = {unbekannt})	C#
 	PresentationCore.dll!System.Windows.Interop.HwndSource.SetLayoutSize()	C#
 	PresentationCore.dll!System.Windows.Interop.HwndSource.RootVisualInternal.set(System.Windows.Media.Visual value = {unbekannt})	C#
 	PresentationCore.dll!System.Windows.Interop.HwndSource.RootVisual.set(System.Windows.Media.Visual value = {unbekannt})	C#
 	PresentationFramework.dll!SourceWindowHelper.RootVisual.set(System.Windows.Media.Visual value = {unbekannt})	C#
 	PresentationFramework.dll!System.Windows.Window.SetRootVisual()	C#
 	PresentationFramework.dll!System.Windows.Window.SetRootVisualAndUpdateSTC()	C#
 	PresentationFramework.dll!System.Windows.Window.SetupInitialState(double requestedTop = {unbekannt}, double requestedLeft = {unbekannt}, double requestedWidth = {unbekannt}, double requestedHeight = {unbekannt})	C#
 	PresentationFramework.dll!System.Windows.Window.CreateSourceWindow(bool duringShow = {unbekannt})	C#
 	PresentationFramework.dll!System.Windows.Window.CreateSourceWindowDuringShow()	C#
 	PresentationFramework.dll!System.Windows.Window.SafeCreateWindowDuringShow()	C#
 	PresentationFramework.dll!System.Windows.Window.ShowHelper(object booleanBox = {unbekannt})	C#
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback = {unbekannt}, object args = {unbekannt}, int numArgs = {unbekannt})	C#
>	WindowsBase.dll!MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(object source = {unbekannt}, System.Delegate method = {unbekannt}, object args = {unbekannt}, int numArgs = {unbekannt}, System.Delegate catchHandler = {unbekannt})	C#
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source = {unbekannt}, System.Delegate callback = {unbekannt}, object args = {unbekannt}, int numArgs = {unbekannt}, System.Delegate catchHandler = {unbekannt})	C#
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.WrappedInvoke(System.Delegate callback = {unbekannt}, object args = {unbekannt}, int numArgs = {unbekannt}, System.Delegate catchHandler = {unbekannt})	C#
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.InvokeImpl()	C#
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(object state = {unbekannt})	C#
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext = {unbekannt}, System.Threading.ContextCallback callback = {unbekannt}, object state = {unbekannt}, bool preserveSyncCtx = {unbekannt})	C#
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext = {unbekannt}, System.Threading.ContextCallback callback = {unbekannt}, object state = {unbekannt}, bool preserveSyncCtx = {unbekannt})	C#
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext = {unbekannt}, System.Threading.ContextCallback callback = {unbekannt}, object state = {unbekannt})	C#
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.Invoke()	C#
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.ProcessQueue()	C#
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.WndProcHook(System.IntPtr hwnd = {unbekannt}, int msg = {unbekannt}, System.IntPtr wParam = {unbekannt}, System.IntPtr lParam = {unbekannt}, ref bool handled = {unbekannt})	C#
 	WindowsBase.dll!MS.Win32.HwndWrapper.WndProc(System.IntPtr hwnd = {unbekannt}, int msg = {unbekannt}, System.IntPtr wParam = {unbekannt}, System.IntPtr lParam = {unbekannt}, ref bool handled = {unbekannt})	C#
 	WindowsBase.dll!MS.Win32.HwndSubclass.DispatcherCallbackOperation(object o = {unbekannt})	C#
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback = {unbekannt}, object args = {unbekannt}, int numArgs = {unbekannt})	C#
 	WindowsBase.dll!MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(object source = {unbekannt}, System.Delegate method = {unbekannt}, object args = {unbekannt}, int numArgs = {unbekannt}, System.Delegate catchHandler = {unbekannt})	C#
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source = {unbekannt}, System.Delegate callback = {unbekannt}, object args = {unbekannt}, int numArgs = {unbekannt}, System.Delegate catchHandler = {unbekannt})	C#
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.WrappedInvoke(System.Delegate callback = {unbekannt}, object args = {unbekannt}, int numArgs = {unbekannt}, System.Delegate catchHandler = {unbekannt})	C#
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority priority = {unbekannt}, System.TimeSpan timeout = {unbekannt}, System.Delegate method = {unbekannt}, object args = {unbekannt}, int numArgs = {unbekannt})	C#
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.Invoke(System.Windows.Threading.DispatcherPriority priority = {unbekannt}, System.Delegate method = {unbekannt}, object arg = {unbekannt})	C#
 	WindowsBase.dll!MS.Win32.HwndSubclass.SubclassWndProc(System.IntPtr hwnd = {unbekannt}, int msg = {unbekannt}, System.IntPtr wParam = {unbekannt}, System.IntPtr lParam = {unbekannt})	C#
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.TranslateAndDispatchMessage(ref System.Windows.Interop.MSG msg = {unbekannt})	C#
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame frame = {unbekannt})	C#
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame frame = {unbekannt})	C#
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.Run()	C#
 	PresentationFramework.dll!System.Windows.Application.RunDispatcher(object ignore = {unbekannt})	C#
 	PresentationFramework.dll!System.Windows.Application.RunInternal(System.Windows.Window window = {unbekannt})	C#
 	PresentationFramework.dll!System.Windows.Application.Run(System.Windows.Window window = {unbekannt})	C#
 	PresentationFramework.dll!System.Windows.Application.Run()	C#
 	BTDJ.Player.exe!BTDJ.Player.Application.Main()	Basic
 	mscorlib.dll!System.AppDomain.nExecuteAssembly(System.Reflection.RuntimeAssembly assembly = {unbekannt}, string[] args = {unbekannt})	C#
 	mscorlib.dll!System.AppDomain.ExecuteAssembly(string assemblyFile = {unbekannt}, System.Security.Policy.Evidence assemblySecurity = {unbekannt}, string[] args = {unbekannt})	C#
 	Microsoft.VisualStudio.HostingProcess.Utilities.dll!Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()	C#
 	mscorlib.dll!System.Threading.ThreadHelper.ThreadStart_Context(object state = {unbekannt})	C#
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext = {unbekannt}, System.Threading.ContextCallback callback = {unbekannt}, object state = {unbekannt}, bool preserveSyncCtx = {unbekannt})	C#
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext = {unbekannt}, System.Threading.ContextCallback callback = {unbekannt}, object state = {unbekannt}, bool preserveSyncCtx = {unbekannt})	C#
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext = {unbekannt}, System.Threading.ContextCallback callback = {unbekannt}, object state = {unbekannt})	C#
 	mscorlib.dll!System.Threading.ThreadHelper.ThreadStart()	C#

**Comment by punker76** [comment]
@dizruptor @S3NS4Ti0N -> https://github.com/MahApps/MahApps.Metro/pull/1971

**Comment by S3NS4Ti0N** [comment]
Thx Guys !
