### ISSUE TITLE
Masked text box

### ISSUE THREAD

**Issue by fredericoregateiro** [MahApps/MahApps.Metro#1920]
Hello,

First thanks for this awesome project.

I don't know if this is the right place to ask for a feature, if not, please redirect me to the correct place.

Is there any plans for a maked textbox, or an attached property for this efect?

Thanks,
Frederico

**Comment by Ruwan-Ranganath** [comment]
you can make it with 
<PasswordBox x:Name="passwordBox" PasswordChar="*" />

- notice the PasswordChar="*"

**Comment by fredericoregateiro** [comment]
Hello,

PasswordBox is a different control for a specific scenario.
The type of control i'm talking is like:

http://wpftoolkit.codeplex.com/wikipage?title=MaskedTextBox&referringTitle=Home

Thanks,
Frederico

**Comment by feinstein** [comment]
I would love this feature too!

**Comment by petvetbr** [comment]
I'll start working on it.

**Comment by punker76** [comment]
@petvetbr I have already a solution in pipeline, so please wait until i published is via PR, so you can just look if it's the solution you also think it's good

**Comment by petvetbr** [comment]
@punker76 sure, no problem, I'll wait. I was offering to belo because I saw the issue was not assigned. I'll look at another issue.

**Comment by chrisklepeis** [comment]
A recommendation to make it 100x easier than the WPF Toolkit maskedtextbox is to intelligently handle cursor position.

As an example, lets assume the mask if for a US phone number:  (___) ___-____
If the user didn't enter in any data, then the cursor should be placed immediately after the ( when the control gets focus.

If the control does have data, like this:   (345) 12_-____
and the user clicks anywhere after the 2, then the cursor should be forced to go immediately after the 2. If the user clicks anywhere before the 2, then the cursor should just go to where they clicked. 
If the control gets focus through something other than a mouse click, cursor position should be after the 2.

Hope this makes sense.

**Comment by tloltman** [comment]
You can also use the [Extended WPF Toolkit](https://github.com/xceedsoftware/wpftoolkit) [MaskedTextBox](https://github.com/xceedsoftware/wpftoolkit/wiki/MaskedTextBox) and simply apply the MetroTextBox Style to it. You just add the MahApps.Metro TextBox resource dictionary to your App.xaml MargedDictionaries and then you can add a Style "BasedOn" MetroTextBox with the MaskedTextBox TargetType as shown below:

```
<Application ...
             xmlns:xctk="http://schemas.xceed.com/wpf/xaml/toolkit"
             ...>
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.TextBox.xaml" />
            </ResourceDictionary.MergedDictionaries>
            <Style BasedOn="{StaticResource MetroTextBox}" TargetType="{x:Type xctk:MaskedTextBox}" />
        </ResourceDictionary>
    </Application.Resources>
    ...
</Application>
```

**Comment by punker76** [comment]
It's also possible to do this with a behavior like [TextBoxInputMaskBehavior](https://github.com/punker76/TextBoxInputMaskBehavior)

**Comment by punker76** [comment]
-> https://github.com/ControlzEx/ControlzEx/issues/45
