### ISSUE TITLE
Autocompletion for any text in items 

### ISSUE THREAD

**Issue by jmecosta** [MahApps/MahApps.Metro#1921]
Hi,

in combo-box with IsEditable="True" i am able to autocomplete based on the start of the text. Is it possible to autocomple based on any text and any position

thanks
jc

**Comment by punker76** [comment]
@jmecosta that's not possible without creating some stuff

maybe this can help you

http://www.broculos.net/2014/04/wpf-autocompletebox-autocomplete-text.html
