### ISSUE TITLE
Controls/Animations unresponsive when using DispatcherTimer

### ISSUE THREAD

**Issue by akhalid** [MahApps/MahApps.Metro#1928]
Hello. Most if not all of the controls such as Progress Ring, Metro Progress Bar, Slider, etc. become very sluggish, jerky and slow when a DispatcherTimer function starts. Is there anything that can be done to make them more responsive/smooth? Thanks.

**Comment by QuantumDeveloper** [comment]
I think you can use MVVM with asyncMode = true. It should help.

**Comment by akhalid** [comment]
Thanks for the input. Can you please elaborate? Maybe an example?

**Comment by QuantumDeveloper** [comment]
http://stackoverflow.com/questions/1725554/wpf-simple-textbox-data-binding

https://msdn.microsoft.com/en-us/library/vstudio/ms771319(v=vs.90).aspx

This should help, I think.
To make binding async you need to add property IsAsync=true inside binding like this:
```
<TextBox Text="{Binding Path=Name2, IsAsync=true}"/>
```

**Comment by akhalid** [comment]
Thank you for the details. I am not sure if this will work in my case. I am using the DispatchTimer to get data from unmanaged code and while the timer is running, the metro controls and animations on the wpf window are not smooth. Not all the data coming from the unmanaged code is going to a textbox or needs to be displayed. I am thinking that maybe I am not using the DispatchTimer correctly.

**Comment by QuantumDeveloper** [comment]
I think its not related to M.A. lib itself. Its incorrectly usage of WPF. You need to use Threads or better Tasks.
Read about them in MSDN or stackoverflow.

**Comment by akhalid** [comment]
You are right, its not directly related to the M.A. lib, but I thought someone else may have had the same issue. I did a bit more digging and testing and a combination of BackgroundWorker and DispatcherTimer seems to do the trick. If anyone has any questions, I will be happy to share :)
