### ISSUE TITLE
Datagrid ValidationRule issue

### ISSUE THREAD

**Issue by fredericoregateiro** [MahApps/MahApps.Metro#1930]
Hello,
I'm trying to use a custom validationrule to validate values entered on a datagrid and the applied themes seems to hide the validation template defined on RowValidationErrorTemplate.
The validation template i'm using is the same on the msdn docs https://msdn.microsoft.com/en-us/library/ee622975%28v=vs.110%29.aspx

I'm i doing something wrong here?

Thanks,
Frederico

**Comment by fredericoregateiro** [comment]
Can anyone help me with this?

I've uploaded a small sample:
https://onedrive.live.com/redir?resid=d5bfec549c6c660e!10682&authkey=!AJrXKHXo5Tj0Vg0&ithint=file%2czip

Thanks,
Frederico

**Comment by Insighter2k** [comment]
Hi everyone,

I still have this issue. Using the one from the msdn docs too.
