### ISSUE TITLE
Modal dialogs not showing in Visual Studio plugin

### ISSUE THREAD

**Issue by TheAngryByrd** [MahApps/MahApps.Metro#1931]
Hey there,

I'm working on the GUI component for the Paket Visual Studio plugin and I've run into a problem with modal dialogs.  I'm probably doing something stupid, hopefully you all can help.

I'm using the latest nuget package of mahapps (1.1.2.0), 

What I'm doing here is trying to open a dialog to show an error message but the screen dims and the dialog never shows up and get this in the output window

    A first chance exception of type 'System.NullReferenceException' occurred in MahApps.Metro.dll

![metrodialognotshowing](https://cloud.githubusercontent.com/assets/1490044/7717570/b5027536-fe71-11e4-9eda-33ad0c2c6c17.gif)

The code can be located here:
https://github.com/TheAngryByrd/Paket.VisualStudio/tree/AddPackageUIModalError

You may have to have the Visual Studio SDK installed (https://www.microsoft.com/en-us/download/details.aspx?id=40758)

Once you have the code loaded and built the xaml files are located
Paket.Visualstudio/Commands/PackageGui

![xamlfiles](https://cloud.githubusercontent.com/assets/1490044/7717657/f9c15948-fe72-11e4-9383-6b2d834c65cf.PNG)

Start debugging (F5) and it will attempt to open another instance of Visual Studio (this might take awhile)
From there just open up the same project Paket.VisualStudio

From there you can right click on the paket.references and click on add package 
![paketreferencesaddpackage](https://cloud.githubusercontent.com/assets/1490044/7717716/e2d1ffe8-fe73-11e4-85a6-bcc471ed3c6a.png)

The gui should show up (maybe not depending on other Visual Studio Extensions and strongly typed names... did I mention making VSIXs are hard?)

Just type anything in the search box, I've set it up to show to show a dialog box.

Sorry I can't provide a simpler sample.

Thanks!

**Comment by punker76** [comment]
@TheAngryByrd the bug is found 8-D and now it works on my machine™

![image](https://cloud.githubusercontent.com/assets/658431/7732852/15cab0a4-ff2b-11e4-9df2-af033a350a90.png)

**Comment by TheAngryByrd** [comment]
![ninjaturtledance](https://cloud.githubusercontent.com/assets/1490044/7732972/d52e163e-fef9-11e4-8c21-8e1f4fca93e2.gif)

**Comment by punker76** [comment]
@TheAngryByrd you can use MahApps.Metro 1.1.3-ALPHA049

**Comment by TheAngryByrd** [comment]
Awesome thanks!

**Comment by holroy** [comment]
Could this be related to why a custom dialog based upon BaseMetroDialog won't show up in VS2013 Designer?

**Comment by holroy** [comment]
Is there a workaround to use while we are waiting for 1.2.0?

**Comment by punker76** [comment]
@holroy you can use the pre alpha version from nuget

**Comment by holroy** [comment]
It is for a commercial product, so not to keen on using a pre-release version. Are there other options? 

Den 10. juni 2015 21.51.52 CEST, skrev Jan Karger <notifications@github.com>:
>@holroy you can use the pre alpha version from nuget
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/MahApps/MahApps.Metro/issues/1931#issuecomment-110891243

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
