### ISSUE TITLE
Login Dialog doesn't Prevent the Keyboard Keys.

### ISSUE THREAD

**Issue by Henka-Programmer** [MahApps/MahApps.Metro#1932]
when showing Login Dialog the Window still accept the Keyboard shortcuts, normally all keyboards keys and navigation prevented.

**Comment by jyrka98** [comment]
because the mahapps dialogs are not actual windows, they are just controls that overlay the other controls on the  window.

**Comment by punker76** [comment]
->https://github.com/MahApps/MahApps.Metro/issues/2400
