### ISSUE TITLE
Title bar button should overlap WindowCommands

### ISSUE THREAD

**Issue by xmedeko** [MahApps/MahApps.Metro#1936]
I have `Controls:MetroWindow.LeftWindowCommands` containing a menu. When a user resizes window to be very narrow, then the Minimize, Maximize and Close buttons start disappearing, but the `WindowCommands` stays. (The close button is already missing on the image bellow.)

![Small Window](http://i.imgur.com/N6qdrid.png)

I think the right behaviour should be the opposite - the title bar buttons are the most important and they should stay last.

**Comment by Henka-Programmer** [comment]
yes you are right i thing it should be work like the  WPF Toolbar, i means overly the commands in a popup or an other strategy like adding two arrow left right to navigate the command or some think like that to avoid this Issue. thank you xmedeko.

**Comment by punker76** [comment]
See also #3408
