### ISSUE TITLE
ListView ColumnHeader

### ISSUE THREAD

**Issue by avechuche** [MahApps/MahApps.Metro#1946]
Hello, I have a little problem with the listview ColumHeader. I dont know what option need modify in the source code of "MahApps.Metro" for the header, start from the edge of the form, and no (5?) Pixels to the right. Thx!
![sin titulo](https://cloud.githubusercontent.com/assets/11781418/7898990/8460d3e4-06e8-11e5-8d12-373314357b77.jpg)

**Comment by punker76** [comment]
@avechuche you can override the `MetroGridViewScrollViewerStyle` and set the Margin for the `GridViewHeaderRowPresenter`
