### ISSUE TITLE
Some classes crashe if window is closed immediately after showing it

### ISSUE THREAD

**Issue by szogun1987** [MahApps/MahApps.Metro#1950]
I found two classes like that:
- WindowChromeWorker
- BorderlessWindowBehavior
I've prepared example fix. But I tested it only with one app.

**Comment by punker76** [comment]
@szogun1987 can you show us the full stack trace or a short sample to reproduce the issue? thx

**Comment by szogun1987** [comment]
I've prepared pull request. I needed issue to name branch.

**Comment by punker76** [comment]
@szogun1987 yeah i see it, but how can i repoduce the issue?

**Comment by szogun1987** [comment]
@punker76  I'm not allowed to publish my app, even if I was it works only with server which is available only inside of my company. I can try to prepare app which reproduce issue for 10 hours.
