### ISSUE TITLE
Watermark on ComboBox where IsEditable="False"

### ISSUE THREAD

**Issue by amkuchta** [MahApps/MahApps.Metro#1953]
Currently, the only way to display a watermark on a ```ComboBox``` control is to set ```IsEditable="True"```.  Is there any way to display a watermark when this is set to ```False```?  I want to have prompt text for the user but cannot give them the option to type because of a converter that I have in place.

Thanks in advance!

**Comment by punker76** [comment]
@amkuchta i'll look into

**Comment by amkuchta** [comment]
Thanks @punker76!!

**Comment by punker76** [comment]
@amkuchta ->https://github.com/MahApps/MahApps.Metro/pull/1958
