### ISSUE TITLE
Does not compile, error in generated file - does not like composite namespaces

### ISSUE THREAD

**Issue by joe-oli** [MahApps/MahApps.Metro#1954]
Steps to reproduce: 
===============
1. Using Visual Studio 2012.

2. Create a new project called "Demo.MahApps" (notice the dot between Demo and MahApps)

3. Install latest stable release of MahApps.Metro from Nuget 1.1.2.0

4. Follow your QuickStart guide to rename a window to Controls:MetroWindow
http://mahapps.com/guides/quick-start.html

5. Rebuild the project - DOES NOT COMPILE. Error is
"The type or namespace name 'Metro' does not exist in the namespace 'Demo.MahApps' (are you missing an assembly reference?)"
Error located in file \Demo.MahApps\obj\Debug\MainWindow.g.cs	

Screenshots
==========

![1 install mahapps metro](https://cloud.githubusercontent.com/assets/12735408/7968090/e59ce36e-0a71-11e5-9b62-69e868bdf49a.png)

![2 namespace with two levels](https://cloud.githubusercontent.com/assets/12735408/7968154/3d0ecafe-0a72-11e5-87f7-4bf7d9b1e15d.png)

![3 does not compile error in filename_g_cs](https://cloud.githubusercontent.com/assets/12735408/7968104/fe351036-0a71-11e5-9eba-9fd82eb74afb.png)

![4 error_double namespace](https://cloud.githubusercontent.com/assets/12735408/7968124/129743fa-0a72-11e5-9afb-7518f4ba8fd9.png)

Comment: 
=======
Resolved after spending 6 hours trying to trace the problem. Was it VS 2012 not being supported? was the NuGet package broken? was it a dodgy application ?

It turned out using a one-level namespace solved the problem. But how is a newbie supposed to know that ?! Please update the user guide to reflect this so others don't waste their time.

**Comment by punker76** [comment]
@joe-oli he, sorry for loosing 6 hours in your life ;-) i see this for me for the first time. i must look into some google vodoo search what here happens, sorry.

**Comment by jyrka98** [comment]
try "global::MahApps.Metro.Controls.MetroWindow"

**Comment by thoemmi** [comment]
The compiler error says it all: 
> The type or namespace name 'Metro' does not exist in the namespace 'Demo.MahApps'

The issue is that your application's namespace is `Demo.MahApps`, so the compiler tries to expand `MahApps.Metro.Control.MetroWindow` to `Demo.MahApps.Metro.Control.MetroWindow`. 

Either change your application's namespace, or use `global::MahApps.Metro...`

**Comment by joe-oli** [comment]
I started from scratch and used Foo.Bar as app name / namespace and it worked correctly first time :-) So am i forbidden in using the "MahApps" string anywhere in my namespace? would MahApps.Demo have worked?

@thoemmi Help me understand this please, in the case i used Foo.Bar the compiler expands it to what?

**Comment by thoemmi** [comment]
@joe-oli, it's not forbidden to use *MahApps* in your namespace name. It's that using *MahApps* is ambiguous. The compiler first tries to resolve class names relatively, then globally. In other words, your namespace name 'Demo.MahApps' "hides" 'MahApps.Metro...'
If you still want to use *MahApps* in your own namespace name, you have to prefix `MahApps.Metro...` with `global::`. See [How to: Use the Global Namespace Alias (C# Programming Guide)](https://msdn.microsoft.com/en-us/library/c3ay4x3d.aspx) for more information.
