### ISSUE TITLE
PasswordBox enhancement

### ISSUE THREAD

**Issue by spoiledtechie** [MahApps/MahApps.Metro#1955]
I would love to see the password box have an enhancement.  I don't want the user to type their password twice, so it would be great if the password box can have another command to SHOW the password when held down.

You can see the example here: http://www.techfeb.com/wp-content/uploads/2012/12/remove-eye-feature-from-internet-explorer-10-1.png

**Comment by punker76** [comment]
@spoiledtechie there will be a `Win8MetroPasswordBox` style in v1.2.0 (or just now in the latest alpha)
