### ISSUE TITLE
Keep open validation popup 

### ISSUE THREAD

**Issue by xmedeko** [MahApps/MahApps.Metro#1957]
I want to see the Validation popup always, not just when the `TextBox` has a focus. I have edited `ValidationErrorTemplate.xaml` and changed 
    <controls:CustomValidationPopup IsOpen="True">

And it works. Is there any other way, how to set `IsOpen="True"` without copy&paste whole file `ValidationErrorTemplate.xaml`? (I am a beginner in to WPF).

Thanks

**Comment by punker76** [comment]
@xmedeko i think that's a good solution for it
