### ISSUE TITLE
Loading an accent from app.config

### ISSUE THREAD

**Issue by jammerxd** [MahApps/MahApps.Metro#1961]
Hello,
I am wondering how to change my application accent to a custom created accent from the app.config. The app.config contains the hex color codes as found in the Styles/Accents/Blue.xaml, Red.xaml, etc...
However, I would like the accent to be generated on the fly. In other words, I want to do it so that the user can choose which colors he/she wants to use by changing the values in the app.config file. This is the current code I have: 
```
            ResourceDictionary myResourceDictionary = new ResourceDictionary();

            myResourceDictionary.Source = new Uri("Styles/Custom.xaml", UriKind.Relative);
            myResourceDictionary["AccentColor"] = (Color)ColorConverter.ConvertFromString("#" + Settings.Interface.WINDOW_COLOR);
            
            MahApps.Metro.Accent temp = new MahApps.Metro.Accent();
            temp.Resources = myResourceDictionary;
            temp.Name = "Custom";
            Application.Current.Dispatcher.Invoke(()=>{
                var theme =  MahApps.Metro.ThemeManager.DetectAppStyle(Application.Current);
                MahApps.Metro.ThemeManager.ChangeAppStyle(Application.Current,temp,MahApps.Metro.ThemeManager.GetAppTheme("BaseDark"));
            });
```

As you can see, I create a resourcedictionary from a template xaml file copied from the Blue.xaml (taken from Mahapps.Metro source project files). I then change the resourcedictionary values to my own. At runtime the application loads colors from the app.config into my static class Settings.Interface. However, This code does NOT change the accents at all. Can anyone provide guidance on how to do this without a strict dependence on the xaml file and load colors from the app.config into an accent to be used immediately?

**Comment by punker76** [comment]
@jammerxd hi, the `ThemeManager` doesn't know where your custom accent/theme is located.
so just add it, to work with it
```csharp
ThemeManager.AddAccent("CustomAccent1", new Uri("pack://application:,,,/MahAppsMetroThemesSample;component/CustomAccents/CustomAccent1.xaml"));
```
[here](https://github.com/punker76/code-samples/blob/master/MahAppsMetroThemesSample/MahAppsMetroThemesSample/ThemeManagerHelper.cs#L48) is an good example for completely custom accent resource

**Comment by jammerxd** [comment]
I see in your example that it saves the code to a file and then reloads it. Is there a way to do it without creating a file(I.E. no save, just a resource dictionary)?

**Comment by punker76** [comment]
@jammerxd i think that's not possible
