### ISSUE TITLE
Mahapps Accents

### ISSUE THREAD

**Issue by warffen** [MahApps/MahApps.Metro#1965]
I have an application which used the mahapps framework, but I'm using an old version, and I want to update to the newsest version. However, my application uses a different color from those defined on accents folder.

My question is: all the definition of a specific color are defined on "Styles/Accents/<color file>.xaml" ? 
For exemple, I want to change the Green color, will be enough if I change the "Green.xaml" file ?

Thanks.

**Comment by punker76** [comment]
@warffen you can create your own custom green accent and add it to the theme manager to use it

**Comment by warffen** [comment]
@punker76 Hum, but how do I set this new custom green accent on the resource dictionary?

**Comment by punker76** [comment]
@warffen here are some links for more information
http://jkarger.de/archive/2014/11/27/mahapps-metro-themes/
https://github.com/punker76/code-samples#mahappsmetro-themes
http://mahapps.com/guides/styles.html

**Comment by warffen** [comment]
@punker76 Thank you, I'll look for it. Another question: do the colors on this custom green color must have the same name to work, right?

**Comment by punker76** [comment]
@warffen yes, you should only override the value, not the key.

**Comment by warffen** [comment]
@punker76 thank you!
