### ISSUE TITLE
(multi screen)drag will throw an overflow crash

### ISSUE THREAD

**Issue by mulky5858** [MahApps/MahApps.Metro#1967]
when I drag my metro window to window.top is less than zero(like -100), the app will crash.

**Comment by punker76** [comment]
@mulky5858 how do you drag your window? per mouse or keyboard? is this a window without title bar? can you provide a full stack trace?

**Comment by deepak-rathi** [comment]
@mulky5858  look into https://github.com/ButchersBoy/Dragablz  Repository for nice drag feature, like in browsers. Might be of some use.

![image](https://cloud.githubusercontent.com/assets/5453503/8454794/a3b1a464-201d-11e5-8de8-f1fac002dc24.png)

**Comment by punker76** [comment]
@deepak-rathi What does that have to do with this issue?
