### ISSUE TITLE
Possible Uri Exception if MahApps is running in a test environment (or non wpf app)

### ISSUE THREAD

**Issue by punker76** [MahApps/MahApps.Metro#1968]
after some discussion in this [so](http://stackoverflow.com/a/30729113/920384)

we should just tell the user that we need a wpf environment and throw an exception if MahApps is located in a test (without a wpf app) or console app etc.

so here is a simple line that causes the exception

`new Uri("pack://application:,,,/...")`

in MahApps

```csharp
_accents = new List<Accent>(colors.Length);

foreach (var color in colors)
{
    _accents.Add(new Accent(color, new Uri(string.Format("pack://application:,,,/MahApps.Metro;component/Styles/Accents/{0}.xaml", color))));
}

return _accents;
```

**Comment by shiftkey** [comment]
Skimmed the SO thread so I might be missing some details, but I'm concerned about making the library "too clever" to detect this - which feels like an outlier issue. Did you find an appropriate hook to verify the context? Themes is a likely place where users might try and run things in a funny context to verify behaviour, not sure if there's other areas you've seen...

**Comment by punker76** [comment]
@shiftkey the idea was only to fire an exception with a better text info what happens...

**Comment by shiftkey** [comment]
:thumbsup:
