### ISSUE TITLE
Assembly Strong Name

### ISSUE THREAD

**Issue by JacBal** [MahApps/MahApps.Metro#1969]
I would like to test the latest prerelease version available through nugget.org.
However, when I compile my solution I got the error:  Assembly generation failed -- Referenced assembly 'MahApps.Metro' does not have a strong name… 
Is there something that I must do in order to compile my app with the prerelease versions?

Jac
PS: Thanks for this awesome library 

**Comment by jyrka98** [comment]
Uncheck    Properties>Signing>"Sign the assembly"

**Comment by JacBal** [comment]
Just call me IDIOT !!!!
Thanks a lot for your help.
My apologies to all others readers for this ridiculous question.

Jac
