### ISSUE TITLE
Behaviours:BorderlessWindowBehavior  is build with older Vesion of Blend SDK

### ISSUE THREAD

**Issue by hannespreishuber** [MahApps/MahApps.Metro#1970]
a blank WPF VB Project  Visual Studio 2015 RC can not build

**Comment by punker76** [comment]
@hannespreishuber can you give us more information? have you looked to the references if the correct lib is added?

**Comment by hannespreishuber** [comment]
C:\WPF\wpfdesigntest\packages\MahApps.Metro.1.1.3-ALPHA068\lib\net45\MahApps.Metro.dll 1.1.3.68

**Comment by hannespreishuber** [comment]
Schweregrad	Code	Beschreibung	Projekt	Datei	Zeile
Fehler		Der Typ "BorderlessWindowBehavior" aus Assembly "MahApps.Metro" wurde mit einer älteren Version von Blend SDK erstellt und wird in einem Windows Presentation Framework 4-Projekt nicht unterstützt.	wpfdesigntest	C:\WPF\wpfdesigntest\wpfdesigntest\MainWindow.xaml	14

**Comment by punker76** [comment]
@hannespreishuber I compiled a private project with VS 2015 RC and got no error. Can you test with the VS 2015 RC too?

**Comment by hannespreishuber** [comment]
take https://github.com/hannespreishuber/wpfdesigntest

**Comment by punker76** [comment]
@hannespreishuber with 2015 rc i can compile your test repo with removing [this](https://github.com/hannespreishuber/wpfdesigntest/blob/master/wpfdesigntest/MainWindow.xaml#L15-L16) lines, cause this properties are gone... (all tested with the latest stable/alpha version)

`ResizeWithGrip` and `AllowsTransparency` are obsolete/deleted properties.

```xaml
    <i:Interaction.Behaviors>
        <Behaviours:BorderlessWindowBehavior 
            ResizeWithGrip="True"
             AllowsTransparency="False"
            EnableDWMDropShadow="True"  />
    </i:Interaction.Behaviors>
```

**Comment by punker76** [comment]
@hannespreishuber any news?

**Comment by jumulr** [comment]
Hi, using **Visual Studio 2015 update 3, .Net 4.6.2** i get those two errors, alternatively and randomely :
- The type BorderlessWindowBehavior from assembly MahApps.Metro was created with a previous version of Blend SDK which is not supported in a Windows Presentation Framework 4 project.
- Can't add an instance of type 'BorderlessWindowBehavior' to a collection of type 'BehaviorCollection'. Only elements of type 'T' are allowed.

It doesn't prevent from executing the app, but the behavior isn't applied.
Same goes for other Mahapps' behaviors.
**It breaks starting from .Net 4.5 and System.Windows.Interactivity.dll 4.5.0.0**
