### ISSUE TITLE
Changing Close button icon.

### ISSUE THREAD

**Issue by thndrwrks** [MahApps/MahApps.Metro#1972]
How might I go about changing the icons of the close button? My app can only be closed from the system tray (think Spotify) so I would like to change the close icon to be more indicative of it's behavior.

**Comment by thoemmi** [comment]
The icons of the window buttons are currently hard-coded paths in the [style for WindowButtonCommands](https://github.com/MahApps/MahApps.Metro/blob/master/MahApps.Metro/Themes/MetroWindow.xaml#L515-L629). You have to create your own style if you want to change the icons.

**Comment by punker76** [comment]
@thndrwrks @thoemmi or you can set the `WindowCloseButtonStyle` with your own style that sets the content

**Comment by punker76** [comment]
@thndrwrks @thoemmi na, my fail, yet not possible to override the content

**Comment by punker76** [comment]
@thndrwrks is it maybe enough for you to disable or hide the button? if so, you can set `IsCloseButtonEnabled` or `ShowCloseButton`

**Comment by thoemmi** [comment]
I think you're right, @punker76 . By overriding `WindowCloseButtonStyle` you could change `Button.Content` to replace the `Path` with something else.

**Comment by punker76** [comment]
@thoemmi no, it's not possible, cause the content is set explicit https://github.com/MahApps/MahApps.Metro/blob/master/MahApps.Metro/Themes/MetroWindow.xaml#L598-L600
don't really know if we should change this
