### ISSUE TITLE
How do I create RightWindowCommands windows?

### ISSUE THREAD

**Issue by pleasega** [MahApps/MahApps.Metro#1978]
I want to create different RightWindowCommands windows that are under the same back coding of this UI, like different tabs just that it is under the RightWindowCommands, how do I do that? Please guide me! An example is LeagueSharp. 
![scr1](https://cloud.githubusercontent.com/assets/12874842/8145266/bd8da830-1233-11e5-8a1b-85ea73006fb0.png)
![scr2](https://cloud.githubusercontent.com/assets/12874842/8145267/bd908b22-1233-11e5-976e-6e4c6c733a69.png)

However, this time in VB.net . Please help me on what do I need to do, like do I need to make a new window? What is the code to link the MainWindow to the second window, for example "CalculatorWindow" in VB.

**Comment by thoemmi** [comment]
You can use `ToggleButton`s in `RightWindowCommands`, see the [demo app](https://github.com/MahApps/MahApps.Metro/blob/master/samples/MetroDemo/MainWindow.xaml#L132-L138).

**Comment by pleasega** [comment]
Hi, may I know what does this `IsChecked="{Binding MagicToggleButtonIsChecked}"` and `IsChecked="{Binding QuitConfirmationEnabled}"` mean? Do I have to include them for mine?

**Comment by pleasega** [comment]
Hi, also how do I switch the content of the window but not switch the window itself? Is it possible?

**Comment by thoemmi** [comment]
You can subscribe to the `Click` event, if you use code behind, or use an `ICommand` of the ToogleButton when using the MVVM pattern. In the handler just switch the content of the window.

**Comment by pleasega** [comment]
Hi, I am now using the click event. I want to know how do I write a code so that when a button is clicked, the tabcontrol selection will be = 1

Here is what I have in my MainWindow, RightWindowCommands:

 `<Button Content="Information" Cursor="Hand" Click="InformationButton_OnClick"
                      ToolTip="View the information"
                      x:Name="InformationView"/>`
I want to know how to come out with the code so that `InformationButton_OnClick` gives me `tabControl.SelectedIndex = 1`. Please guide me on writing this code out

**Comment by thoemmi** [comment]
Here's a possible solution in C#:
```
private void InformationButton_OnClick(object sender, RoutedEventArgs e) {
    if (sender == InformationView) {
        tabControl.SelectedIndex = 1;
    }
}
```
Anyway, it doesn't seem as your issue isn't specific to Mahapps.Metro, but WPF in general. This isn't a forum for generic programming issues.

**Comment by pleasega** [comment]
hi, im sorry, i want the code in visual basic, is it possible?

**Comment by thoemmi** [comment]
If **you** know VB you should be able to write a simple `if` statement and an assignment expression.

**Comment by pleasega** [comment]
Sorry, but I am new to VB. I tried and what I got was `handles clause requires a withevents variable defined in the containing type or one of its base`. Please guide me!

**Comment by RiderOfTheli** [comment]
You should ask on WPF Forum how to do this.

go here and try to play with the tabcontrol.

http://www.dotnetheaven.com/article/wpf-tab-control-in-vb.net1
