### ISSUE TITLE
WindowCommandButton + Flyout

### ISSUE THREAD

**Issue by warffen** [MahApps/MahApps.Metro#1982]
I have four WindowCommandButton on the right side, and a flyout that is also on the right side, and it's modal. When the flyout is open, I'm able to click on the window command buttons behind the flyout. 

I already set RightWindowCommandsOverlayBehavior="HiddenTitleBar" on the window.

Am I missing something? What can I do to disable the click event of these window command buttons?

Thanks.
![clickable windowcommandbutton](https://cloud.githubusercontent.com/assets/3089401/8161919/8920afe8-1350-11e5-9410-7a4c27b38fb9.png)

**Comment by punker76** [comment]
@warffen just set the `WindowButtonCommandsOverlayBehavior` to hide the `WindowCommandButton`

**Comment by warffen** [comment]
@punker76 I have just tried all the options of `WindowButtonCommandsOverlayBehavior` and it didn't hide the WindowCommandButtons

**Comment by punker76** [comment]
@warffen which version of MahApps?

**Comment by warffen** [comment]
@punker76 1.1.3. I think I haven't expressed myself correctly as I wanted on the question. The WindowCommandButtons that stay behind the flyout are hidden, but the "home" that is not behind the flyout is still clickable.
