### ISSUE TITLE
Proposed Textbox / ComboBox Enhancement

### ISSUE THREAD

**Issue by amkuchta** [MahApps/MahApps.Metro#1983]
Adding built-in support for ```TextTrimmingStyle``` would be awesome for ```MetroTextBox``` and ```MetroComboBox```.  I can roll my own styles to include these, but it causes loss of support for items such as ```TextBoxHelper.Watermark```

**Comment by punker76** [comment]
same as here https://github.com/MahApps/MahApps.Metro/issues/650
