### ISSUE TITLE
MetroFlatButton KeyBoard Focused Color

### ISSUE THREAD

**Issue by amkuchta** [MahApps/MahApps.Metro#1984]
Currently, when a ```Button``` control style with ```MetroFlatButton``` has keyboard focus (i.e. is tabbed to), its color does not change.  Can this be updated to match the same color as when the mouse is over it?

**Comment by punker76** [comment]
@amkuchta You can override the `MetroFlatButton` style with the focused trigger and set the Background to what you want.
