### ISSUE TITLE
User control not animated after visibility changed programatically.

### ISSUE THREAD

**Issue by erangatennakoon** [MahApps/MahApps.Metro#1990]
In a `<Controls:MetroContentControl>` I've set few user controls as follows, in the main metro window. (`<Controls:MetroWindow>`)

```
<views:LoginScreen DataContext="{Binding}" Visibility="Visible" Grid.Row="1" Grid.Column="0" x:Name="ucLoginControl" />
<views:GridControl DataContext="{Binding}" Visibility="Collapsed" Grid.Row="1" Grid.Column="0" x:Name="ucGridControl" />
<views:ApplicationMainMenu DataContext="{Binding}" Visibility="Collapsed" Grid.Row="0" Grid.Column="0" x:Name="ucApplicationMenu" />
<views:ApplicationStatusBar DataContext="{Binding}" Grid.Row="2" Grid.Column="0" />
```

LoginScreen visible on the main window at the time of application execute. In the code behind I toggled the controls as follows.

```
ucLoginControl.Visibility = Visibility.Collapsed;
ucGridControl.Visibility = Visibility.Visible;
ucApplicationMenu.Visibility = Visibility.Visible;
```

All the user controls toggled, but I cannot see the animation that move the controls into the main window as a slide. Can anyone help me on this please.

**Comment by punker76** [comment]
@erangatennakoon the animation is only triggered after the content of  `MetroContentControl` has changed and your content doesn't change.

**Comment by erangatennakoon** [comment]
@punker76 Thanks. So that means toggling the user controls not identify as a content change of  MetroContentControl and trigger the animation. In that case how can I achieve this, keep the animation on toggle.

**Comment by punker76** [comment]
@erangatennakoon you can try call `Reload()` method after setting your visibilities
