### ISSUE TITLE
TargetParameterCountException when receiving WM_CLOSE from external app

### ISSUE THREAD

**Issue by RickRockhold** [MahApps/MahApps.Metro#1991]
Steps to reproduce:
1. Create a new WPF app, reference MahApps.
2. In XAML, change Window to MetroWindow.
3. In App.xaml, add ' Exit="Application_Exit" ' attribute to Application element (application will stay running now after window is closed.
4. Run program, and close main window (app should still be running in background).
5. Send WM_CLOSE to this program from another program.
6. TargetParameterCountException occurs.

If step 2 is omitted, there is no exception.

Sending WM_CLOSE is a common way for installers to close running applications. In our case, the installer sends a WM_CLOSE to our application, causing a crash during uninstall.

**Comment by punker76** [comment]
@RickRockhold I tried to reproduce this with your instructions, but I don't get this TargetParameterCountException. Can you maybe provide some simple code or something else? thx.
