### ISSUE TITLE
Document Viewer Search Highlight

### ISSUE THREAD

**Issue by shamindera** [MahApps/MahApps.Metro#1992]
HI, iam using mahapps metro plugin on my two apps, its great and working fine. I have added "DocumentViewer" to both the apps to view my reports in XPS and PDF format. DocumentViewer is doing great too, but when i try to search using inbuilt search of DocumentViewer, font doesnt get highlighted but page scrolls to searched term which means search is working but highlighting. When i tried to add DocumentViewer to simple app (without mahapps metro theming) it works absolutely fine without changing any code, so i think thers something messing up with highlighting text styling which i couldnt find. Can you guys help me out of it ? Thanx in advance.

**Comment by petvetbr** [comment]
Tried adding a WPF DocumentViewer with a XPS file created in MS Office Word 2016 and the search highlight worked (below). Does this happen in any specific situation? Can you send a sample XPS/PDF where this happens?

![xpstest](https://cloud.githubusercontent.com/assets/778016/13382800/4ef02092-de5c-11e5-972c-810b510ec76a.PNG)
