### ISSUE TITLE
MetroComboBox dropdown list background color

### ISSUE THREAD

**Issue by FatimaRmayhi** [MahApps/MahApps.Metro#2002]
Sometimes, this issue occurs with my project:
1- open a form containing many controls (a combobox + 2 buttons for example).
2- Press Tab to move between controls.
3- click on the combobox, dropdownlist background color is colored by Style color.

**Comment by punker76** [comment]
@FatimaRmayhi i don't understand point 3. can you provide a screenshot?

**Comment by FatimaRmayhi** [comment]
Find the screenshot below
the style I used is blue, if you use Orange style color, the items will be colored in orange.
![screenshot](https://cloud.githubusercontent.com/assets/13048540/8375856/dc44b856-1c09-11e5-9064-9ddba8129a75.png)

**Comment by punker76** [comment]
@FatimaRmayhi so now with the given screenshot... sorry you are at the wrong github repo. 
you should post this issue here -> https://github.com/viperneo/winforms-modernui

**Comment by FatimaRmayhi** [comment]
Ok thank you
