### ISSUE TITLE
WindowCommands not working properly when starting minimized.

### ISSUE THREAD

**Issue by Dreamcooled** [MahApps/MahApps.Metro#2008]
I have a MetroWindow with a WindowCommand:

    <controls:MetroWindow.RightWindowCommands>
        <controls:WindowCommands>
            <Button Command="{Binding SettingsCommand, ElementName=Window}">
                <Rectangle Width="20" Height="20"
                   Fill="{Binding RelativeSource={RelativeSource AncestorType=Button}, Path=Foreground}">
                    <Rectangle.OpacityMask>
                        <VisualBrush Stretch="Fill"
                         Visual="{StaticResource appbar_settings}" />
                    </Rectangle.OpacityMask>
                </Rectangle>
            </Button>
        </controls:WindowCommands>
    </controls:MetroWindow.RightWindowCommands>

Normally this works fine, The Button is displayed and the command works.

However, if I add Hide() to the end of the constructor:

    InitializeComponent();
    Hide();

Then the Button is displayed, but clicking it does not trigger the Action.

Code: https://github.com/Dreamcooled/sjupdater (MainWindow)

**Comment by thoemmi** [comment]
@Dreamcooled I tried your code. During start-up a warning is generated when the window is hidden:

> System.Windows.Data Error: 4 : Cannot find source for binding with reference 'ElementName=Window'. BindingExpression:Path=SettingsCommand; DataItem=null; target element is 'Button' (Name=''); target property is 'Command' (type 'ICommand')

I.e. the binding fails when the window is not visible. I don't think that this is a MahApps.Metro issue.

I got your code working locally by moving the `SettingsCommand` to `MainWindowViewModel`. Even if the window is not visible, its `DataContext` still works.

**Comment by Dreamcooled** [comment]
@thoemmi 
Thanks for looking into it and for your response. I appreciate it.
You're probably right, it's not a MahApps.Metro Issue.  I overlooked that error.

But why is this error even generated in the first place? I thought that binding expressions would be evaluated on the logical tree, so it shouldn't matter whether or not the Window is actually visible or not. Am I missing something?

Moving the `SettingsCommand` to the `MainWindowViewModel` seems to be the "right choice", but still this issue is kind of strange....
