### ISSUE TITLE
Can't see minimize icon for ResizeMode="NoResize" in MetroWindow

### ISSUE THREAD

**Issue by itijain91** [MahApps/MahApps.Metro#2011]
I want my Window to be No Resizeable so I set  ResizeMode="NoResize", But I can't see minimize icon  now.

**Comment by punker76** [comment]
@itijain91 that's right, because it's the default behavior for normal windows too.
![image](https://cloud.githubusercontent.com/assets/658431/8425372/6e64fdec-1f05-11e5-843f-d2c990ba448d.png)
