### ISSUE TITLE
New MahApps vb.net Application stopped working after opening it

### ISSUE THREAD

**Issue by pleasega** [MahApps/MahApps.Metro#2015]
I made a New vb.net WPF application, I installed MahApps package and the resource package. I have this code in the Mainwindow.xaml
                
        <Controls:MetroWindow x:Class="MainWindow"
        xmlns:Controls="clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WpfApplication1"
        mc:Ignorable="d"
        Title="MainWindow" Height="350" Width="525">
    <Grid>
        
    </Grid>
    </Controls:MetroWindow>

and 

    <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary        Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Colors.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/Blue.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/BaseLight.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>

that code in the application resources

The problem is when I open the application outside of the debug folder, I drag the .exe to my desktop it doesnt open. It just opens and force closes so it shows nothing. However it will open but only with a bunch of other stuff in the debug folder, tested it with release too but its the same, any way to let it so that it works by itself? 
It seems that the bunch of other stuff that is crucial for it to work is the `MahApps.Metro.dll` and the `System.Windows.Interactivity`. I think that this application could work by itself right? How can I fix it?
What is the error here? Anymore information that I can provide to solve this issue?

No codes are inside. Clean application. Please help!

**Comment by punker76** [comment]
@pleasega its nececarry to ship `MahApps.Metro.dll` and `System.Windows.Interactivity.dll` with your exe (-> https://github.com/MahApps/MahApps.Metro/issues/2016)
