### ISSUE TITLE
Place DLL dependencies elsewhere

### ISSUE THREAD

**Issue by pleasega** [MahApps/MahApps.Metro#2016]
As the program need MahApps.Metro and the system.windows.interactivity DLLs, how I do put them in a folder like bin folder but still make the program work? I tried and it stopped working, please help!

**Comment by bigworld12** [comment]
I created a tutorial on stack over flow to merge dlls into exe but i am not on computer now

**Comment by pleasega** [comment]
oh if i could see that, it would be great

**Comment by bigworld12** [comment]
http://stackoverflow.com/questions/27891550/embedding-dlls-inside-of-a-wpf-application-with-pictures-visual-basic/27891551#27891551

**Comment by pleasega** [comment]
hi bigworld, I tried but I cant find file properties, only reference properties. Please assist me, im still new to this wpf. thank you!

**Comment by pleasega** [comment]
how do i set the resource file type to binary? please help me!

**Comment by pleasega** [comment]
thank you so much!!! worked like a charm!!! THANK YOU
