### ISSUE TITLE
NumericUpDown Text Color

### ISSUE THREAD

**Issue by QuantumPhi** [MahApps/MahApps.Metro#2020]
Selecting the `NumericUpDown` column of the last element after selecting any other elements makes the text color of the `NumericUpDown` elements in the previously selected elements white, making them invisible on a white background.

VS2013, .NET4.5

**Comment by punker76** [comment]
@QuantumPhi which mahapps version?

**Comment by QuantumPhi** [comment]
Version 1.1.3-ALPHA122





From: Jan Karger
Sent: ‎Wednesday‎, ‎July‎ ‎8‎, ‎2015 ‎13‎:‎13
To: MahApps/MahApps.Metro
Cc: Tarik





@QuantumPhi which mahapps version?

**Comment by QuantumPhi** [comment]
Version `1.1.3-ALPHA122`

Also tested on `v1.1.3-ALPHA099`, `v1.1.2`; same issue present.
- - -
Some clarification on the issue: when an element is selected, it is usually set with a white text color. After an element (except for the last one) has its `NumericUpDown` element triggered, selection of that element no longer sets the text color in the `NumericUpDown` column to white.
- - -
Before the `NumericUpDown` element is triggered:
![foo](https://cloud.githubusercontent.com/assets/5723421/8664284/e37d4042-2989-11e5-9f7d-bad856b81477.png)

After the `NumericUpDown` element is triggered:
![bar](https://cloud.githubusercontent.com/assets/5723421/8664290/f7b8f736-2989-11e5-9b28-7e87dc85959c.png)

Image of issue described in first comment:
![qux](https://cloud.githubusercontent.com/assets/5723421/8664295/02aefcee-298a-11e5-8480-b0c4bc9d1514.png)

**Comment by punker76** [comment]
@QuantumPhi thx for the clarification. one another question, do you use the `NumericUpDown` in a `ListBox` or something else?

**Comment by punker76** [comment]
@QuantumPhi and what do you mean with `triggered`

**Comment by QuantumPhi** [comment]
I use `NumericUpDown` in a `DataGrid`. (I guess I should say I use a `DataGridNumericUpDownColumn`)

What I mean by `triggered` is when the `NumericUpDown` column is double clicked to show the `+` and `-` elements.
- - -
![baz](https://cloud.githubusercontent.com/assets/5723421/8730343/fd16989c-2ba4-11e5-8799-af4f6948c04b.png)
`triggered`

**Comment by punker76** [comment]
@QuantumPhi Can you provide a short simple example to demonstrate this? Cause I still don't understand this...

**Comment by QuantumPhi** [comment]
I wrote a minimal working example [here](https://github.com/QuantumPhi/FooProject) that you can use to easily replicate the error yourself (I hope).
- - -
Start the program, and highlight all of the lines as a baseline
![pre_action](https://cloud.githubusercontent.com/assets/5723421/8841906/8824b0f6-30a8-11e5-9526-c6a9b483d998.PNG)
Double click on any number except for the very last one to bring up the `DataGridNumericUpDownColumn`
![action](https://cloud.githubusercontent.com/assets/5723421/8841920/bad8e346-30a8-11e5-90c2-02128f3f3ead.PNG)
Selecting the double-clicked number along with any other line (except for the last one) should now show how the text color is not changed on selection
![post_action](https://cloud.githubusercontent.com/assets/5723421/8841944/0a9cd4e6-30a9-11e5-8448-2163b05aa448.PNG)
Selecting the last row also sets the text color of the double-clicked element to white (original reason for bug filing)
![bug](https://cloud.githubusercontent.com/assets/5723421/8841962/37ce9288-30a9-11e5-9fbd-44b14d7a6777.PNG)
- - -
:rocket:
