### ISSUE TITLE
Flyout shows at the back.

### ISSUE THREAD

**Issue by rhalf** [MahApps/MahApps.Metro#2021]
Hi sir good day, I am new to wpf and want to use MahApps.Metro for my first project. Flyouts is working fine here
![flyout1](https://cloud.githubusercontent.com/assets/4572641/8510606/feeea126-22fa-11e5-9c5c-29bed56d8914.png)

But when I add webbrowser or other controls like button, flyout shows at the back of webbrowser(controls). Panel.Zindex doesnt work here.
 
![flyout2](https://cloud.githubusercontent.com/assets/4572641/8510608/02bd31a0-22fb-11e5-9b92-d7f163610e4a.png)

Here's my xaml.
![flyout3](https://cloud.githubusercontent.com/assets/4572641/8510609/1d38e6fa-22fb-11e5-84f9-ccb4ca45693f.png)

Thank you sir and regards.

**Comment by bigworld12** [comment]
It's a bug with just the web browser

**Comment by thoemmi** [comment]
See the [FAQ](https://github.com/MahApps/MahApps.Metro/wiki/FAQ), it's an airspace issue with WPF. Classic Win32 controls such as the web browser control don't work well with the composition engine of WPF.

**Comment by rhalf** [comment]
hi bigworld12 and thoemmi  thank you for your immediate and informative response to this bug.
