### ISSUE TITLE
ScrollBarHelper.VerticalScrollBarOnLeftSide brake horizontal scrollbar

### ISSUE THREAD

**Issue by QuantumDeveloper** [MahApps/MahApps.Metro#2025]
Using this line of code in TreeView
```
controls:ScrollBarHelper.VerticalScrollBarOnLeftSide="True"
```
leads to broken horizontal scrollbar like on the screenshot below
![broken scrollviewer](https://cloud.githubusercontent.com/assets/6085009/8578383/37f9bc30-25b7-11e5-95a8-11b438009dfa.png)

When deleting this code, everything works correctly:
![image](https://cloud.githubusercontent.com/assets/6085009/8578431/7571fcf8-25b7-11e5-8583-9d9b2d09bc12.png)

**Comment by punker76** [comment]
fixed with c0c94fb39cc4d8892f260af462d026655042fb01
