### ISSUE TITLE
Dear Master . Mahapps's   DataGrid   innser  button can't  display when lost focus . 

### ISSUE THREAD

**Issue by DaqingFeng** [MahApps/MahApps.Metro#2027]
Dear Master, 
        I found mahapps solution is pretty good. 
       But  when i using Datagrid ,I find  some issues.  I make a   customize  cell  datatemplate.  Datagrid  can't  display  when I the cell lost focus .How can i fixed the issue  .The picture like below 
 
1. When I selected row and click the cell. the control can display.
![1](https://cloud.githubusercontent.com/assets/10512467/8599743/d0463986-2694-11e5-9ed1-38de3574ad52.png)

2.Lost focus the select value disappear.
![2](https://cloud.githubusercontent.com/assets/10512467/8599754/d9ce3918-2694-11e5-9707-a378f3b4e8a4.png)

3. This is my behind code . 
![3](https://cloud.githubusercontent.com/assets/10512467/8599763/e02d5dde-2694-11e5-9635-caadd2ae7526.png)

     thanks  for you patience !

**Comment by jimbobsmith** [comment]
Hi.   You'll need to define a CellTemplate too, where you bind your date value to a control, like textblock, to make it visible when not editing that cell

e.g.
<DataGridTemplateColumn.CellTemplate>  <DataTemplate> <TextBlock Text={Binding NextNotifyTime, stringFormat={}{0:d}}"/> </DataTemplate></DataGridTEmplateColumn.CellTemplate>

please note i wrote this code in this editor...

**Comment by DaqingFeng** [comment]
Hi  jmbobosmith, Thank you very much ,It's working!
