### ISSUE TITLE
can't override styles

### ISSUE THREAD

**Issue by kayone** [MahApps/MahApps.Metro#203]
I'm trying to override some styles eg. metro button in my app,

``` xml
    <Style TargetType="{x:Type Button}" BasedOn="{StaticResource MetroButton}">
        <Setter Property="FontFamily" Value="./resources/#Roboto Light"/>
        <Setter Property="FontSize" Value="20"/>
    </Style>
```

but it doesn't work, if I don't add this, then I get the proper metro style, but when I add this only this style is applied and none of the MetroButton style is merged in. it seems like `BasedOn` attribute is ignored.

this is the merged dictionaries that i have in my `app.xaml`

``` xml
  <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary>
                    <local:Bootstrapper x:Key="bootstrapper" />
                    <WpfExtentions:BooleanToVisibilityConverter x:Key="HiddenIfTrue" TriggerValue="True" IsHidden="True"/>
                    <WpfExtentions:BooleanToVisibilityConverter x:Key="HiddenIfFalse" TriggerValue="False" IsHidden="True"/>
                    <WpfExtentions:BooleanToVisibilityConverter x:Key="CollapsedIfTrue" TriggerValue="True" IsHidden="False"/>
                    <WpfExtentions:BooleanToVisibilityConverter x:Key="CollapsedIfFalse" TriggerValue="False" IsHidden="False"/>
                    <WpfExtentions:StringNullOrEmptyToVisibilityConverter x:Key="HasValue"/>
                </ResourceDictionary>
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Colours.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.AnimatedSingleRowTabControl.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/Blue.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/BaseLight.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/FlatButton.xaml" />
                <ResourceDictionary Source="MyResource.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>
```

**Comment by TheFlow0360** [comment]
I also cannot override styles, in my case the flyout style. I tried to move everything in an own ResourceDictionary and used `<Style x:Key="DefaultFlyout" TargetType="controls:Flyout" BasedOn="{StaticResource {x:Type controls:Flyout}}">` like suggested by @kayone , but it always ends up to have only the last styles I applied....

I use it like this:
Controls.xaml:

    <ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                        xmlns:controls="http://metro.mahapps.com/winfx/xaml/controls">

        <ResourceDictionary.MergedDictionaries>
            <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />

            ... 

            <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.AnimatedSingleRowTabControl.xaml" />
        </ResourceDictionary.MergedDictionaries>
        ...
        <Style x:Key="DefaultFlyout" TargetType="controls:Flyout" BasedOn="{StaticResource {x:Type controls:Flyout}}">
            <Setter Property="Theme" Value="Accent" />
        </Style>
    </ResourceDictionary>

The app.xaml:

    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
                <ResourceDictionary Source="pack://application:,,,/SLtime;component/View/Controls.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.AnimatedSingleRowTabControl.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Colors.xaml" />
                <ResourceDictionary Source="pack://application:,,,/SLtime;component/View/CustomAccent.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/baselight.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>

And the part where i want to use it, inside the `<controls:MetroWindow.Flyouts><controls:FlyoutsControl>`

    <controls:FlyoutsControl.ItemContainerStyle>
        <Style BasedOn="{StaticResource DefaultFlyout}"
           TargetType="{x:Type controls:Flyout}">
            <Setter Property="Header"
                Value="{Binding Header}" />
            <Setter Property="IsOpen"
                Value="{Binding Visible}" />
            <Setter Property="Position"
                Value="{Binding Position, Converter={StaticResource FlyoutPositionConverter}}" />
            <Setter Property="IsModal"
                Value="{Binding IsModal}" />
        </Style>
    </controls:FlyoutsControl.ItemContainerStyle>`

See the result on this [screenshot](http://i.imgur.com/yqDUJUM.png). It should be a blue flyout because i used `<Setter Property="Theme" Value="Accent" />` but it doesn't work.

Has anyone an idea why this doesn't work? I don't really like the idea of copying the whole flyout style just to make my changes...
