### ISSUE TITLE
using TextBoxHelper.ClearTextButton on a NumericUpDown won't rise its value changed event

### ISSUE THREAD

**Issue by bigworld12** [MahApps/MahApps.Metro#2031]
`<Controls:NumericUpDown Controls:TextBoxHelper.ClearTextButton="True"/>`
this won't raise the "ValueChanged" event of the numeric up down when pressing the button and clearing the text

**Comment by punker76** [comment]
fixed with dc6fed50330a2d3d6e3c6b45195d2a57f193c6ae
