### ISSUE TITLE
No Title Bar in Mvx Composite WPF Application

### ISSUE THREAD

**Issue by DCMBhoy** [MahApps/MahApps.Metro#2035]
Using MahApps Metro 1.1.2.0 in a .net 4.5 WPF MvvmCross (HotTuna 3.5.0) composite application, developing on Windows 7 and running on Windows 7 and 8.1.

Have followed the quick start guide but when I run the app I see no title bar on the window.

The resources are added to the host application and I am not seeing System.Windows.ResourceDictionary Warnings, e.g. 9 : Resource not found; ResourceKey='IdealForegroundColorBrush'

I have manually added the following properties to MainWindow.xaml but still no joy.
              ResizeMode="CanResize"
              ShowCloseButton="True"
              ShowIconOnTitleBar="True"
              ShowInTaskbar="True"
              ShowMaxRestoreButton="True"
              ShowMinButton="True"
              ShowSystemMenuOnRightClick="True"
              ShowTitleBar="True"

I added padding before the first control and made the background transparent on the mvx user control which is loaded into mainwindow by the view presenter to ensure it was not sitting on top of the menu, but all I see is a black background from the top of the window until the content begins.

Interestingly, adding a GlowBrush to main window does have an effect: GlowBrush="{DynamicResource AccentColorBrush}"

Snoop shows the ShowXYZ properties as true, and the title bar height set to 30 etc.

Any help welcome. 
Thanks

**Comment by punker76** [comment]
@DCMBhoy can you provide some code (mayber where your resources are located, etc)? thx

**Comment by DCMBhoy** [comment]
The MainHost has no resources other than those added to application as per the quick start guide.

A module (.dll) is loaded with User Controls (derived from mvvm cross controls) and that module has it's own resources which are held in Xaml / ResourceDictionary files in the dll - these are then included on the controls as needed.

I tried adding Mahapps.Metro to the module as well and also adding merging the resources that were placed in the application into one of the resource dictionaries used by the initial user control - sadly this made no difference (as it shouldn't as in theory these should be seperate from the MainWindow?).

Cheers

**Comment by punker76** [comment]
@DCMBhoy Is this still an issue for you? I think this is not MahApps related, feels more it is a wrong configuration together with MvvmCross.
