### ISSUE TITLE
Avalondock Anchorables could not be dragged inside MetroWindow

### ISSUE THREAD

**Issue by QuantumDeveloper** [MahApps/MahApps.Metro#2036]
HI. I noticed that when Iam  using MetroWindow with avalondock, I cannot drag AnchorableGroup out of the WIndow. It just moves th whole window itself. But with standart WPF window, everything working correct.

Could this issue be fixed somehow?

For me its critical, because it affect features of docking control.

**Comment by punker76** [comment]
it would be nice if you create a small test application, to demonstrate the issue

**Comment by QuantumDeveloper** [comment]
here is the link on 2 apps demostrating the issue.
https://onedrive.live.com/?id=650F345C1F75A314%217115&cid=650F345C1F75A314&group=0

**Comment by QuantumDeveloper** [comment]
@punker76 are there any updates to this issue?
