### ISSUE TITLE
Static Code Analysis

### ISSUE THREAD

**Issue by amkuchta** [MahApps/MahApps.Metro#2037]
I don't think this is the best place for this, but I can't think of a better one.  I have access to HP Fortify, a static code analysis tool, and was able to run a scan of the Mahapps.Metro library.   I would like to provide the results to the developers to give a road map for code cleanup, but am not sure how to get it to you.  Any takers?

**Comment by amkuchta** [comment]
@punker76 I never got a response to this?  Should I assume that there is no interest in the scan results? I would offer to fork and provide some cleanup myself, but I absolutely zero time to do so.

**Comment by bigworld12** [comment]
send it to me and i will create PRs with performance improvements

**Comment by punker76** [comment]
@amkuchta I closed this cause I don't have this HP Fortify tool to review the analysis, which propably show us some code cleanup...

**Comment by amkuchta** [comment]
@bigworld12 will do, can you send an email to amkuchta@gmail.com so I know where to send it?  @punker76 the results are in a PDF format, so anyone can use them (who can view a PDF, anyway)
