### ISSUE TITLE
Ignore taskbar on maximize and the taskbar

### ISSUE THREAD

**Issue by spasas** [MahApps/MahApps.Metro#2039]
If there are any windows [partially] behind the taskbar (e.g. Visual Studio in screenshot #1) before clicking the "Ignore taskbar on maximize" Window option, they will be displayed in front of the taskbar after either clicking "Ignore taskbar on maximize" again (e.g. Visual Studio in screenshot #2) or by restoring MahApps' original size before it was maximized (e.g. Visual Studio & MahApps in screenshot #3) by clicking the window's "Restore Down" button at the top right of the window.

The taskbar remains in the background until the focus on the MahApps window is lost. 

![1 - vs in the back of taskbar](https://cloud.githubusercontent.com/assets/6651890/8750223/365fd49a-2c74-11e5-8e0f-4f073348bb86.png)
![2 - vs in the front of taskbar](https://cloud.githubusercontent.com/assets/6651890/8750224/36627164-2c74-11e5-874b-4ce01bbafbd2.png)
![3 - mahapps vs in the front of taskbar](https://cloud.githubusercontent.com/assets/6651890/8750222/365ceec4-2c74-11e5-836c-6b076bf925be.png)

**Comment by punker76** [comment]
@spasas maybe its an issue by running the demo from vs with debugging.

**Comment by spasas** [comment]
We can reproduce in release also. Only on Windows 7 though. Windows 8.1 seems to work fine.

**Comment by punker76** [comment]
@spasas I would like to close this issue, cause first, the menu point was created to demonstrate the possibility of ignoring the taskbar (not really at runtime, only used for the demo), and second, maybe a Windows function is causing this.

**Comment by spasas** [comment]
That's fine with me.

**Comment by punker76** [comment]
@spasas :+1:
