### ISSUE TITLE
Looks like Win10, resizes like Win8

### ISSUE THREAD

**Issue by planetarian** [MahApps/MahApps.Metro#2042]
In Windows 10 (and Visual Studio even in prior versions), Microsoft has dropped the visible window border down to a single pixel wide as part of the new metro-inspired window chrome theme. The resize handles are actually the same size as before, though, but they are invisible and located outside the window itself.

Meanwhile, apps created with MahApps.Metro bear a significant resemblance to Visual Studio and all other apps on Windows 10, however they do not replicate the resize handle mechanism, with the resize handles being 1) within the window boundaries, and 2) narrower than is standard.

This creates an odd inconsistency, where the app appears to blend well with the OS visually, but the resize mechanism does not behave consistently with existing apps of the same style.

**Comment by punker76** [comment]
@planetarian can you give us more specific informations with your problems and win 10? i just installed win 10 preview in vmware and can't see a problem with the borders and resizing the window.

**Comment by planetarian** [comment]
![GIF demonstration of resizing differences](https://piro.blob.core.windows.net/shotweb/6bd950367b47243d333b9de28e4d9f.gif)

^ as shown here, the VS window's handles (much like the handles of all apps in win10) are actually invisible and outside the app's outer edge. If one attempts to try to use a MahApps.Metro app the same way, you'd click straight through to whatever's behind it, since its handles are *inside* its outer edge.

This is largely a circumstance of previous versions of windows having their handles inside the outer edge (since they had visible resize handles). VS 2013 introduced the new 'invisible outside' handles, and win10 adopted them globally, for all apps using the standard window chrome. This makes any apps with 'inside' handles stick out quite a bit, especially when they otherwise look very much like the native metro-ish style.

**Comment by punker76** [comment]
ok, now i understand, but this has nothing to do with win 10, mabe we can fix/change this win 1.x.x or 2.x.x

**Comment by punker76** [comment]
@planetarian i fixed this issue in 3c90b1ebd1c9c4ebdeeb7d7993a61cb66ca88b78 (available via nuget pre) for the `Glow` behavior. for now it's not possible for the `Border` only behavior. if this ok for you so let me know it.
