### ISSUE TITLE
Not being able to change Title in a Caliburn.Micro Conductor View

### ISSUE THREAD

**Issue by Acaspita** [MahApps/MahApps.Metro#2043]
I'm doing like so:

    <Controls:MetroWindow x:Class="BS.Expert.Client.App.Views.ShellView"
        xmlns:Controls="clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        ShowTitleBar="True"
        Title="My Title">

The thing is that this it at the same time a defined main conductor on the main window with which I control navigation through other windows, so I'm not able to inherit from MetroWindow to at least trying change the title in the ViewModel:

    public class ShellViewModel : Conductor<IScreen>.Collection.OneActive, IShell
    {
        public ShellViewModel()
        {
            #region mahApps Theme Loading

            var theme = ThemeManager.DetectAppStyle(Application.Current);
            var appTheme = ThemeManager.GetAppTheme(App.Configuration.Theme);
            ThemeManager.ChangeAppStyle(Application.Current, theme.Item2, appTheme);

            #endregion
            //TODO: Changing Title here is not possible ((MetroWindow)this).Title = "No way";
            // Tudo bem na seguinte liña
            LocalizeDictionary.Instance.Culture = new System.Globalization.CultureInfo("pt-BR");
            ShowPageOne();
        }

        public void ShowPageOne()
        {
            ActivateItem(new PageOneViewModel());
        }
    }

How should I change the title?

**Comment by Allann** [comment]
I am having the same issue, nothing to do with caliburn though.  Straight use of MetroWindow in simple WPF application.

**Comment by punker76** [comment]
@Acaspita @Allann MahApps uses for the Caliburn demo version 2.0.0.6 and uses this

```csharp
protected override void OnInitialize()
{
    base.OnInitialize();
    this.DisplayName = "Caliburn Metro Demo";
}
```

which works fine.

![2015-12-09_09h34_36](https://cloud.githubusercontent.com/assets/658431/11680378/18dcb072-9e58-11e5-8e74-2c3f13167374.png)

**Comment by Allann** [comment]
Thanks for the quick response, will test it in the morning when I'm back at work.

**Comment by Allann** [comment]
This does fix the initial issue.  So I suppose this question can be closed.  It does indeed work when using Caliburn Screen types (the owner of DisplayName).

Do you want me to raise a new bug for the standard MetroWindow?  Can't change the Title of that using the standard WPF window title property.

**Comment by punker76** [comment]
@Allann Yeah, you can open a new issue, but maybe I can't help you, cause I'm not really firm with Caliburn.Micro...
