### ISSUE TITLE
Adopt Windows 10 Text Style Names

### ISSUE THREAD

**Issue by bloritsch** [MahApps/MahApps.Metro#2046]
See the online documentation for full reference: https://msdn.microsoft.com/en-us/library/windows/apps/Hh700394.aspx

What MahApps currently has using separate keys for font families, font sizes etc. Microsoft has packaged up into preset styles you can simply use.  The link I provided shows the table with the style name, font family, font size, line size, font weight, etc.

That can get rid of the need for my other issue on documentation and you can just post a link to that page.

**Comment by punker76** [comment]
@bloritsch that's all fine, but it's for UWP apps...

**Comment by bloritsch** [comment]
Doesn't Mahapps get us a lot closer to being able to do those apps on Windows 7 boxes?

I like the concept of the style names I can just use and it does everything consistently.  If we adopt names that will be used when I can graduate to programming UWP it just means less relearning later on.  I'm not set on the sizes, etc.  I just like the convenience of not having to replicate four settings on each text element when I'm rendering a chart with axis labels, etc.  It's easier to communicate to the other guys on my team.
