### ISSUE TITLE
Missing method exception using 1.1.3-Alpha

### ISSUE THREAD

**Issue by mos8580** [MahApps/MahApps.Metro#2047]
Hi,

I've set up a sample project to try the new DialogCoordinator functionality of the next version of mahapps.metro. It works very well on my virtual machine that has windows 8.1 and VS 2013 community.

On my work machine, it compiles fine, but throws a runtime error during the initialization of the main window. I will include the stacktrace below, although I apologize my work machine is localized in french and is locked down administratively. Hopefully it will still help. The OS is windows 7 Ultimate 64-bit and I have VS 2012 pro.

From the inner exception, it's like it cannot find a method from mscorlib. I have verified while running, and the assembly is loaded correctly from the GAC at runtime...

The interesting thing is that everything works fine with the latest stable build from Nuget (1.1.2) if I comment out the new functionality from my code.

Thank you for any insight!

L'exception System.Windows.Markup.XamlParseException s'est produite
  HResult=-2146233087
  Message='L'initialisation de 'PrismDemo.Views.MainWindow' a levé une exception.' numéro de ligne '28' et position de ligne '7'.
  Source=PresentationFramework
  LineNumber=28
  LinePosition=7
  StackTrace:
       à System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
       à System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
       à System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
       à System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
       à PrismDemo.Views.MainWindow.InitializeComponent() dans c:\Document\Projets\PrismMVVMTemplate\PrismDemo\Views\MainWindow.xaml:ligne 1
       à PrismDemo.Views.MainWindow..ctor() dans c:\Document\Projets\PrismMVVMTemplate\PrismDemo\Views\MainWindow.xaml.cs:ligne 12
  InnerException: System.MissingMethodException
       HResult=-2146233069
       Message=Méthode introuvable : 'Void System.Runtime.InteropServices.Marshal.StructureToPtr(!!0, IntPtr, Boolean)'.
       Source=MahApps.Metro
       StackTrace:
            à Microsoft.Windows.Shell.SystemParameters2._InitializeCaptionButtonLocation()
            à Microsoft.Windows.Shell.SystemParameters2..ctor()
            à Microsoft.Windows.Shell.SystemParameters2.get_Current()
            à Microsoft.Windows.Shell.WindowChrome..ctor()
            à MahApps.Metro.Behaviours.BorderlessWindowBehavior.OnAttached()
            à System.Windows.Interactivity.Behavior.Attach(DependencyObject dependencyObject)
            à System.Windows.Interactivity.BehaviorCollection.ItemAdded(Behavior item)
            à System.Windows.Interactivity.AttachableCollection`1.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
            à System.Windows.FreezableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
            à System.Windows.FreezableCollection`1.OnCollectionChanged(NotifyCollectionChangedAction action, Int32 oldIndex, T oldValue, Int32 newIndex, T newValue)
            à System.Windows.FreezableCollection`1.AddHelper(T value)
            à System.Windows.FreezableCollection`1.Add(T value)
            à MahApps.Metro.Behaviours.StylizedBehaviors.OnPropertyChanged(DependencyObject dpo, DependencyPropertyChangedEventArgs e)
            à System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
            à System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
            à System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
            à System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
            à System.Windows.StyleHelper.ApplyStyleOrTemplateValue(FrameworkObject fo, DependencyProperty dp)
            à System.Windows.StyleHelper.InvalidateContainerDependents(DependencyObject container, FrugalStructList`1& exclusionContainerDependents, FrugalStructList`1& oldContainerDependents, FrugalStructList`1& newContainerDependents)
            à System.Windows.StyleHelper.DoThemeStyleInvalidations(FrameworkElement fe, FrameworkContentElement fce, Style oldThemeStyle, Style newThemeStyle, Style style)
            à System.Windows.StyleHelper.UpdateThemeStyleCache(FrameworkElement fe, FrameworkContentElement fce, Style oldThemeStyle, Style newThemeStyle, Style& themeStyleCache)
            à System.Windows.FrameworkElement.OnThemeStyleChanged(DependencyObject d, Object oldValue, Object newValue)
            à System.Windows.StyleHelper.GetThemeStyle(FrameworkElement fe, FrameworkContentElement fce)
            à System.Windows.FrameworkElement.UpdateThemeStyleProperty()
            à System.Windows.FrameworkElement.OnInitialized(EventArgs e)
            à System.Windows.FrameworkElement.TryFireInitialized()
            à System.Windows.FrameworkElement.EndInit()
            à MS.Internal.Xaml.Runtime.ClrObjectRuntime.InitializationGuard(XamlType xamlType, Object obj, Boolean begin)
       InnerException:

**Comment by bigworld12** [comment]
3 of my customers had the same problem they fixed it by upgrading to netframework  4.6
Error :
http://i.imgur.com/A9fhxdc.png

**Comment by mos8580** [comment]
Thank you for your input,

At least I'm not alone with this problem. I hope there is another solution because I won't be able to install new versions on the framework in my corporate environment.

I wonder what change in the source since the last stable release could cause this?

**Comment by tomato3107** [comment]
I was able to fix a similar problem (NET4 application would crash on NET4 machines with XamlParseException but work fine on NET 4.5.2 machines) by compiling the NET4 MahApps.Metro.dll myself instead of using the official Nuget one.

**Comment by mos8580** [comment]
I really wish I understood why, but this workaround actually worked, thanks.

**Comment by punker76** [comment]
@mos8580 @tomato3107 @bigworld12 with which version of target framework is this happen? .net 4 or .net 4.5? or hopefully not with both?

**Comment by mos8580** [comment]
The whole solution is targeting 4.5.

I can make a test sln with .net 4 if it helps.

**Comment by tomato3107** [comment]
My application targets .NET4 Client profile.

**Comment by bigworld12** [comment]
Personally i target 4.5

**Comment by punker76** [comment]
@mos8580 @tomato3107 @bigworld12 it would be nice to test out MahApps.Metro 1.1.3-ALPHA127
so it would be really great to create 2 simple apps, one for .net 4, the other for .net 4.5 and test for the missing method exception. a stack trace and some informations about the target os (and framework) would be really nice.

**Comment by mos8580** [comment]
Hi Jan,

I did two sample projects that target .Net 4 and 4.5, here are my findings:

On .Net 4.5, I got a vhost32.exe crash. I went to build settings and unchecked "Prefer 32 bits" and it worked well.

On .net 4, I got the same exception as before for which the stacktrace is in first post. On this project, the "prefer 32 bit" setting is grayed out (and unchecked). I forced the "Target platform" to x64 but this had no effect, same exception was thrown.

Hope it helps.

**Comment by punker76** [comment]
@mos8580 can you post this two samples? what is your OS and what .net framework is installed?

**Comment by mos8580** [comment]
@punker76 
- OS is Windows 7 Enterprise 64 bit localized in french.
- .Net Framework installed: 4.5, 4.5 Multi-Targeting Pack, 4.5 SDK, 4.5 SDK - French language module
- Visual Studio 2012 Professional (french also)

The projects are just empty WPF projects from VS2012 with mahapps installed and MainWindow changed to a MetroWindow. Maybe I can send via email?

**Comment by punker76** [comment]
@mos8580 punkerat76 [ at ] gmail [ dot ] com

**Comment by thoemmi** [comment]
There seems to be a major issue in .NET 4.6, see [Why you should wait on upgrading to .Net 4.6](http://nickcraver.com/blog/2015/07/27/why-you-should-wait-on-dotnet-46/):

> This critical bug is specific to .Net 4.6 and RyuJIT (64-bit). I'll make this big and bold so we get to the point quickly:
> **The methods you call can get different parameter values than you passed in.**

**Comment by punker76** [comment]
@mos8580 @tomato3107 @bigworld12 next test candidate MahApps.Metro 1.1.3-ALPHA138

**Comment by mos8580** [comment]
@punker76

unfortunately, the issues persist.

**Comment by punker76** [comment]
@mos8580 I have a feeling that this is not a problem of MahApps :-(

**Comment by mos8580** [comment]
@punker76

That's entirely possible. It could be anything, really. Fortunately people affected can use the workarounds.

Thanks for investigating.

**Comment by mos8580** [comment]
@punker76
This morning I noticed that the debug window of my project was flooded with:

First chance exception [...] MissingMethodException in MahApps.Metro.dll

Sure enough, the app crashes if I run the .exe directly.

I reverted the nuget package from Alpha-138 to Alpha-127 and did not experience this problem.

**Comment by punker76** [comment]
@mos8580 can you post your source? any another stack trace?

**Comment by mos8580** [comment]
@punker76

It looks like the debugger is handling the exceptions as the app continues to run in debug mode. Just dragging the MetroWindow around generates a bunch of exceptions in the debug window.

The missing method is the same as before:

System.Runtime.InteropService.Marshal.StructureToPtr(!!0, IntPtr, Boolean)
Source=MahApps.Metro
StackTrace:
At Microsoft.Windows.Shell.WindowChromeWorker._HandleWindowPosChanging(WM uMsg, IntPtr wParam, IntPtr lParam, Boolean& handled).


I made a vanilla test project from the MahApps template, I will send it tonight (can't from work).

**Comment by punker76** [comment]
@mos8580 so give the MahApps.Metro 1.1.3-ALPHA139 a chance

**Comment by mos8580** [comment]
@punker76

Same thing happens :(

As before stack trace says this happens at line 478 of WindowChromeWorker.cs

**Comment by punker76** [comment]
@mos8580 another question: do you use a vm?

**Comment by mos8580** [comment]
@punker 76

I'm not, running on metal.

**Comment by punker76** [comment]
@mos8580 that's really annoying, i have tested with 2 machines and 1 vm and don't get this. one with win 7 64 bit, than with win 8.1 64 bit and a vm with win 10 preview 64 bit.

**Comment by punker76** [comment]
@mos8580 I give up! If there is someone who can fix this, please do it. for me and my machines ™ all works fine.

**Comment by mos8580** [comment]
@punker76

I understand. The regression from Alpha-138 compared to Alpha-127 puzzles me though.

The actual missing method is marked obsolete in 4.5 according to MSDN. 

Thanks a lot for trying!

**Comment by bigworld12** [comment]
@punker76
Did you change iny thing in app / window constructor ?

**Comment by punker76** [comment]
@bigworld12 sorry, i don't understand what do you mean.

**Comment by bigworld12** [comment]
In the MetroWinow constructor did you change any thing ?

**Comment by punker76** [comment]
@bigworld12 -> private chat on gitter

**Comment by punker76** [comment]
@mos8580 @bigworld12 @tomato3107 #1.1.3.149 is waiting for you (the teamcity build server has possible produced wrong assemblies)

**Comment by mos8580** [comment]
@punker76
I confirm Alpha 149 fixes the issue for both .Net 4 and .Net 4.5.

Logical conclusion considering our previous exchange on Gitter :)

Thank you very much for all the effort spent researching this issue!

**Comment by punker76** [comment]
http://gifs.joelglovier.com/big-lebowski/dancing.gif

**Comment by punker76** [comment]
![dancing](https://cloud.githubusercontent.com/assets/658431/8987112/ad0149a6-36df-11e5-9d22-a15cc62f95d1.gif)
