### ISSUE TITLE
DropDownButton and SplitButton doesn't works

### ISSUE THREAD

**Issue by Iworb** [MahApps/MahApps.Metro#2051]
Today I've installed MathApps.Metro and trie dto add DropDownButton into a new MetroWindow, but nothing happend. I mean, there is a new control on window, but some properties doesn't work: background always same color (even if I changed it), DropDownList is empty even if it contains some items.

Here how it looks

![image](https://cloud.githubusercontent.com/assets/658431/16686393/17f2eaee-4512-11e6-8456-ce78120af930.png)

And here is XAML

```xaml
<Controls:MetroWindow x:Class="MahApps.Metro.Application1.MainWindow"
                     xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                     xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                     xmlns:Controls="http://metro.mahapps.com/winfx/xaml/controls"
                     Title="MainWindow"
                     Height="350"
                     Width="525">
    <Grid>
        <Controls:DropDownButton HorizontalAlignment="Left" Margin="223,107,0,0" VerticalAlignment="Top" Height="89" Width="120" Background="#FFCB4C4C">
            <Controls:DropDownButton.Items>
                <Button/>
                <Button/>
            </Controls:DropDownButton.Items>
        </Controls:DropDownButton>
 
    </Grid>
</Controls:MetroWindow>
```

**Comment by punker76** [comment]
you should give your controls some content, what do you expect with empty contents?

**Comment by Iworb** [comment]
Content just a text or whatever else to display, but I want to change Background for a whole DropDownButton.
Thats what I've talked about: http://s27.postimg.org/x3gqnycqr/image.png
XAML: http://pastebin.com/zg6pq8Vi
Even with Content in DropDownButton and internal Buttons nothing happend - Background wasn't change and list is empty.

**Comment by punker76** [comment]
setting the background should be fixed in the latest alpha

**Comment by Iworb** [comment]
Should I use -Pre version?

**Comment by punker76** [comment]
yepp, try it
Am 23.07.2015 11:17 schrieb "Alexander" <notifications@github.com>:

**Comment by Iworb** [comment]
Background was fixed, but dropdownlisp still empty =(

**Comment by Iworb** [comment]
Any changes? DropDown items isn't empty, but shown list is.
