### ISSUE TITLE
Setting FlowDirection = RightToLeft on MetroWindow kills Maximize functionaliy

### ISSUE THREAD

**Issue by jonyadamit** [MahApps/MahApps.Metro#2053]
When `FlowDirection` is set to `RightToLeft`, while `BorderlessWindowBehavior` is applied, the following happens when the window is maximized:

* Window appears the same size, only aligned to the top left
* Window becomes 'unclickable'. Every click brings background windows to the front. If there are not background windows, the click interacts with the desktop.
* The window is completely unusable and there is no way to close or restore it.

**Comment by punker76** [comment]
this is fixed in the latest alpha version. look at #1927 #1924
