### ISSUE TITLE
ToggleButton foreground color when selected

### ISSUE THREAD

**Issue by melance** [MahApps/MahApps.Metro#2056]
The foreground color of the standard toggle button is hard to read when selected:

![image](https://cloud.githubusercontent.com/assets/8439866/8913781/c5359a94-3460-11e5-8963-9c9e4d6434d0.png)

Although it seems like less of an issue in the dark theme:

![image](https://cloud.githubusercontent.com/assets/8439866/8913793/db873a96-3460-11e5-95d6-e36c76f8e2e7.png)

It would be nice to see the foreground color change to white when selected.

**Comment by punker76** [comment]
@thoemmi wdyt?

**Comment by punker76** [comment]
@melance I've moved the ControlTemplate triggers to Style triggers, so you can now create your own Style where you only need to override the IsChecked trigger.

```xaml
<Style TargetType="ToggleButton" BasedOn="{StaticResource MetroToggleButton}">
  <Style.Triggers>
    <Trigger Property="IsChecked" Value="True">
      <Setter Property="Foreground" Value="White" />
    </Trigger>
  </Style.Triggers>
</Style>
```
