### ISSUE TITLE
Percentage Box

### ISSUE THREAD

**Issue by Rajivhost** [MahApps/MahApps.Metro#2057]
Hi,
That will be great if we can have a percentage box just like VIBlend does.

http://www.viblend.com/products/net/wpf/controls/free-wpf-controls.aspx

![image](https://cloud.githubusercontent.com/assets/3539984/8926234/281ffc58-3506-11e5-9fd3-a27826db27e8.png)

**Comment by bigworld12** [comment]
Or you can just have a property in a numeric up down box to make it a
percentage box

**Comment by xxMUROxx** [comment]
@Rajivhost use `NumericUpDown` and set `StringFormat` to `p`. To change the value by one percent you have to set the `Interval` property to 0.01.

```xaml
<NumericUpDown StringFormat="p" 
               Inverval="0.01" 
               Maximal="1"
               Minimal="0"
               Value="{Binding Path=YourPercentageProperty}" />
```
If your backing field rapresents not a value between 0 and 1 but from 0 to 100 you have to customize the StringFormat to `"{}{0:##0} %"`. then everything should work.

**Comment by Rajivhost** [comment]
Ok, I will test it and feedback.
