### ISSUE TITLE
NumericUpDown Integer only

### ISSUE THREAD

**Issue by feinstein** [MahApps/MahApps.Metro#2059]
Well I guess the title says it all, but I want to be able to only show integers in the NumericUpDown, so if the user types, 2.1 it will be automatically converted to 2.

**Comment by bigworld12** [comment]
You can use the value changed event to set the value to the intger part only

**Comment by feinstein** [comment]
Yeah, and I can user the FormatString "#" which helps most of the time, but having something like `IsIntger="True"` would help a lot.

**Comment by thoemmi** [comment]
IMHO this requirement is too particular to add it to this library.

**Comment by xxMUROxx** [comment]
You could work with `Behaviors` to implement such a feature.
See [How do I get a TextBox to only accept numeric input in WPF?](http://stackoverflow.com/a/8015485/2964291)

**Comment by feinstein** [comment]
WPF Extended Toolkit has it 

http://wpftoolkit.codeplex.com/wikipage?title=IntegerUpDown&referringTitle=Home

And I use it, that's why I am asking for it.

**Comment by feinstein** [comment]
@xxMUROxx the same Stackoverflow link you posted have an answer about the Extented WPF Toolkit.

**Comment by xxMUROxx** [comment]
The implementaion of Extendet WPF Toolkit is way different then that one I have implemented. My implementation is a single class where Xceed's implementation have different classes for each int/double/short.
I use the control a lot, for that I have implemented it, and have no problems with binding smaller datatypes than double. Just provide a Min/Max range.

----- Ursprüngliche Nachricht -----
Von: "feinstein" <notifications@github.com>
Gesendet: ‎29.‎07.‎2015 17:20
An: "MahApps/MahApps.Metro" <MahApps.Metro@noreply.github.com>
Cc: "Michael Mairegger" <michael.mairegger@yahoo.de>
Betreff: Re: [MahApps.Metro] NumericUpDown Integer only (#2059)

@xxMUROxx the same Stackoverflow link you posted have an answer about the Extented WPF Toolkit.

**Comment by feinstein** [comment]
I know it doesn't have a problem binding to int, I am using it binded to an integer, but the user can input "2.3", the integer will become "2" and that's probably what the user wants (even if the user will see "2.3"),  but I think that limiting this in the control will be a more "clean" solution and the implementation shouldn't be hard to do. I will look into it on my spare time I guess and see if I can submit a pull request on this feature if you don't mind.

**Comment by thoemmi** [comment]
@feinstein, I'm convinced that your requirement is totally comprehensible. However, what's when the next developer requires float only? Or scientific notation (6.022E17)? Should dependency properties such as `IsFloat` or `IsScientific` too? All of these are totally reasonable, but from the library perspective I think it's overkill. @xxMUROxx linked to a simple way how to achieve it with simple behaviours with no need to change MahApps.Metro.

**Comment by bigworld12** [comment]
The problem is not adding new functions it's that everyone wants his own
function so it's better to leave it like that and let everyone customize it
as they wish

**Comment by feinstein** [comment]
@thoemmi `NumericUpDown` currently supports scientific notation, if you type `1e10` it will convert it to `10` once the control loses focus.

It's not about the type...int, float, it's about having decimal separators or not...I can change the name to "HasDecimalSeparator" or whatever, I didn't change the type in my PR, it's still a `double?`, I just removed the ',' or '.', depending on the `Culture`.

I don't see why someone will need something else than that, like `float` as you said, since the inner type is the same and they can cast it. Again: It works with `int`, the UI is just not showing to the user what he's getting, and I wanted to avoid it in a practical way.

**Comment by feinstein** [comment]
@bigworld12 well I agree when it's something that will just pollute the library and if you are sure this is the case, so feel free to dismiss my PR. But as far I can see, I think it's a nice feature to have, specially for people moving from the Extented WPF Toolkit.

**Comment by feinstein** [comment]
I changed the property name to `HasDecimals` so it won't make the users think there is actually an `int` on it.

**Comment by feinstein** [comment]
Well I confess I am a bit surprised this got merged in #2065 after all the opinions here. Thank you for all the feedback and hope the community enjoy it!
