### ISSUE TITLE
SplitButton usage question

### ISSUE THREAD

**Issue by m5112638** [MahApps/MahApps.Metro#2060]
I am trying to use SplitButton in an application and would like the following behaviors:

1. The content of the button (PART_Button) doesn't change when popup item from PART_Popup is changed.

2. The appearance of the SplitButton is similar to other types of buttons (e.g. DefaultButton) so they can be used together.

Can the current implementation of the split button do that with some customization?

**Comment by QuantumDeveloper** [comment]
@m5112638  this is more like dropdown button and not split button behavior.
