### ISSUE TITLE
Red Border remains on textbox even after data is exists

### ISSUE THREAD

**Issue by ifourdharmesh** [MahApps/MahApps.Metro#2062]
I have added Required validation on TextBox. Issue is that Red Border remains on textbox always even after data is exists when I open filled window with data in edit mode,

I have added below code to get validation on textbox.

TextBox:
```
<TextBox HorizontalAlignment="Stretch" Grid.Column="1"
                        VerticalAlignment="Center" Text="{Binding ConstantName, UpdateSourceTrigger=PropertyChanged, Mode=TwoWay, ValidatesOnDataErrors=True}" />''

```

Property:

```
[Required(ErrorMessage = @"Enter Constant Name")]
        public string ConstantName
        {
            get { return _constantName; }
            set
            {
                if (value == _constantName) return;
                _constantName = value;
                OnPropertyChanged("ConstantName");
            }
        }

```

Style:

```
<Style TargetType="{x:Type TextBox}" BasedOn="{StaticResource MetroTextBox}">
        <Setter Property="Margin" Value="5"></Setter>
        <Setter Property="VerticalContentAlignment" Value="Center"></Setter>
        <Style.Triggers >
            <Trigger Property="Validation.HasError" Value="true">
                <Setter Property="ToolTip"
                            Value="{Binding RelativeSource={RelativeSource Self}, Path=(Validation.Errors)[0].ErrorContent}" />
            </Trigger>
        </Style.Triggers>
    </Style>
```

Please help me to resolve this issue

![bug](https://cloud.githubusercontent.com/assets/13567092/8977300/72932da4-36b5-11e5-9da1-deeb153b39f6.png)

**Comment by Biegal** [comment]
I'm fighting exactly same problem right now :/
What I've noticed is, that if I remove whole text from textbox, and start typing again it starts to work fine.

**Comment by punker76** [comment]
@ifourdharmesh With which version get you this issue?

**Comment by ifourdharmesh** [comment]
I am using latest Metro UI version for .net framework 4.5. I have downloded from nuget also tried from Git.

**Comment by punker76** [comment]
I think it's the same as here https://github.com/MahApps/MahApps.Metro/issues/2536
