### ISSUE TITLE
MetroProgressBar issue when binding Visibility property

### ISSUE THREAD

**Issue by bbougot** [MahApps/MahApps.Metro#2067]
I encountered an issue when using the MetroProgressBar with IsIndeterminate = True property. 
The code is pretty simple:

< controls:MetroProgressBar 
EllipseDiameter="5"
Width="{Binding RelativeSource={RelativeSource FindAncestor, AncestorType=Grid}, Path=ActualWidth, Mode=OneWay}"
Foreground="{DynamicResource AccentColorBrush}"
IsIndeterminate="True"
Visibility="{Binding IsMovieLoading, Converter={StaticResource BoolToInverseVisibilityConverter}}"/>

Everything is working well without the binding set on Visilibity property (setting Visible or Collapsed works the expected way), but as soon as the binding is set, MetroProgressBar acts like if IsIndeterminate was set to false.

N.B : the binding works, my converter is OK too

**Comment by punker76** [comment]
@bbougot  With which version get you this issue?

**Comment by bbougot** [comment]
I'm using the lastest version, the one from the 29th July. I can't test anymore because I found a workaround regarding my use case, having a Storyboard and a DataTrigger which manually set the correct Visibility property. The issue is quiet uncommon, as the MetroProgressBar seems to ignore the IsIndeterminate DependencyProperty as soon as Visibility is bound to something.

**Comment by bbougot** [comment]
I found my screenshots to illustrate the issue :

When Visibility binding is not set (Visibility="Visible") :
![88b96424-3afa-11e5-8c3d-fba34c481938](https://cloud.githubusercontent.com/assets/8962802/9170233/660dbbee-3f61-11e5-8161-f73d571f8083.jpg)

When Visibility is bound :
![7de7aaf6-3afa-11e5-96db-aec34c1078b0](https://cloud.githubusercontent.com/assets/8962802/9170241/71f0a57a-3f61-11e5-9928-797030f27fc1.jpg)

**Comment by punker76** [comment]
@bbougot can you try it anyway with latest after fa6cd6d27014bef67bdc03ec8430f2d1769b5678?

**Comment by bbougot** [comment]
Ok, I'll check this soon.

**Comment by 537mfb** [comment]
I just had this issue using the latest stable version of `MahApps`
I found a solution but I'm not sure of the cause.

Here's my use case:
My app requires a browser so I'm using `CEFSharp`
I have a `Grid` and in row 1 i have a `MetroProgressBar` and in row 2 I have the browser
`MetroProgressBar.Visibility` is bound to the browser's `IsLoading` property

If my xaml is like:

    <MahApps:MetroProgressBar Grid.Row="1" Grid.Column="0" Grid.ColumnSpan="5" IsIndeterminate="True" Visibility="{Binding ElementName=Browser, Path=IsLoading, Converter={StaticResource BoolToVis}}" />
    <wpf:ChromiumWebBrowser x:Name="Browser" Grid.Row="2" Grid.Column="0" Grid.ColumnSpan="5"  Address="https://www.google.com" />

When a page is loading in the browser, row 1 shows up (uncollapses) but not rhe `MetroProgressBar`
Once the page is finished loading, row 1 collapses as expected

If `MetroProgressBar.Visibility` is not bound to the browsers `IsLoading` property, the row doesn't collapse and `MetroProgressBar` shows up as expected

However if i change the order and nothing else:

    <wpf:ChromiumWebBrowser x:Name="Browser" Grid.Row="2" Grid.Column="0" Grid.ColumnSpan="5"  Address="https://www.google.com" />
    <MahApps:MetroProgressBar Grid.Row="1" Grid.Column="0" Grid.ColumnSpan="5" IsIndeterminate="True" Visibility="{Binding ElementName=Browser, Path=IsLoading, Converter={StaticResource BoolToVis}}" />

Then everything works as expected: The row is collapsed until a page starts loading, at which time the row uncollapses and `MetroProgressBar` shows up as expected, until the page finishes loading, collapsing the row again

If I use a regular `ProgressBar` instead, it works with either order just fine
