### ISSUE TITLE
[Question] Transparent background of MetroWindow

### ISSUE THREAD

**Issue by maratoss** [MahApps/MahApps.Metro#2068]
Hi!
Can i make transparent background of MetroWindow?
I tried to do it as it is in the stackoverflow [sample](http://stackoverflow.com/questions/21461017/wpf-window-with-transparent-background-containing-opaque-controls), but for MetroWindow it's not working.

```xml
<Window x:Class="WpfApplication3.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        Title="MainWindow" Height="350" Width="525"
        AllowsTransparency="True" WindowStyle="None">
    <Window.Background>
        <SolidColorBrush Opacity="0.5" Color="White"/>
    </Window.Background>
    <Grid>
        <Button Width="200" Height="50">button</Button>
    </Grid>
</Window>
```

**Comment by MrSquirrely** [comment]
You need to make sure your program is using MetroWindow
It has:
```xaml
<Window x:Class="WpfApplication3.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        Title="MainWindow" Height="350" Width="525"
        AllowsTransparency="True" WindowStyle="None">
    <Window.Background>
        <SolidColorBrush Opacity="0.5" Color="White"/>
    </Window.Background>
    <Grid>
        <Button Width="200" Height="50">button</Button>
    </Grid>
</Window>
```

It should be:
```xaml
<Window:MetroWindow 
        xmlns:Controls="clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro"
        x:Class="WpfApplication3.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        Title="MainWindow" Height="350" Width="525"
        AllowsTransparency="True" WindowStyle="None"
        Opacity="0.5" Color="White">
    <Grid>
        <Button Width="200" Height="50">button</Button>
    </Grid>
</Window:MetroWindow >
```

This should work. 
Remember to read this to get started:
http://mahapps.com/guides/quick-start.html

**Comment by maratoss** [comment]
Yes, right right.
i did following, but it doesn't work:
```xml
<controls:MetroWindow x:Class="MyApplication.App_Start.Windows.TestWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        GlowBrush="{DynamicResource AccentColorBrush}"
        BorderBrush="{DynamicResource AccentColorBrush}"
        xmlns:controls="http://metro.mahapps.com/winfx/xaml/controls"
        Title="TestWindow"
        UseNoneWindowStyle="True"
        AllowsTransparency="True"
        WindowStyle="None" WindowStartupLocation="CenterOwner" WindowState="Maximized">
    
    <controls:MetroWindow.Background>
        <SolidColorBrush Color="White" Opacity="0.5"/>
    </controls:MetroWindow.Background>
    
</controls:MetroWindow>
```

if you try to set AllowTransparency property via CodeBehind, this window will appear invisible:
```cs
    using MahApps.Metro.Controls;

    public partial class TestWindow : MetroWindow
    {
        public TestWindow()
        {
            this.InitializeComponent();
            AllowsTransparency = true;
        }
    }
```

Your sample doesn't work as well

**Comment by MrSquirrely** [comment]
Quick question, what exactly are you trying to accomplish? Do you want the screen to be slightly opaque with no user controls or with one?

**Comment by maratoss** [comment]
I just want to have the window with the transparent background and non transparent controls inside this window.

I downloaded mahapps repository and tried to make window with transparent background in the demo project and this is working there, i'll try to find out what is wrong.

i'm using 1.1.2.0 version and .net 4

**Comment by maratoss** [comment]
I seems found the problem, i'll try to explain it :)
you can reproduce it in MetroDemo propject from MahApps.Metro repository:

if you set AllowTransparency = true (after InitializeComponent()) and WindowState="Normal", you can't maximize your window (it just moves window in top-left corner of the screen and  this window doesn't react on any action). In this case you can set Opacity=0.5 for background and this will work.
if you set AllowTransparency = true and WindowState="Maximized", you will never see the window, because this window is invisible

**Comment by punker76** [comment]
@maratoss cause that's all, MahApps set the `AllowsTransparency` explicit to `false`. cause `true` hase some bad implicit issues that we don't want. to solve your issue (and for people who want the true) we can add a dp to the BorderlessWindowBehavior to force this value, like `ForceAllowsTransparency`. All other will not be implemented...

**Comment by maratoss** [comment]
I thought it was a bug.
> to solve your issue (and for people who want the true) we can add a dp to the BorderlessWindowBehavior

As you wish, i solved my issue.

**Comment by djmiller9975** [comment]
AllowsTransparency="False" doesn't work with WindowsFormsHost.  I also tried the solution to role my own window with adding.
                      xmlns:i="http://schemas.microsoft.com/expression/2010/interactivity"
                      xmlns:Behaviours="clr-namespace:MahApps.Metro.Behaviours;assembly=MahApps.Metro"
and adding
 <i:Interaction.Behaviors>
        <Behaviours:BorderlessWindowBehavior/>
    </i:Interaction.Behaviors>
It says that AllowsTransparency is unknown or inaccessible.  What am I missing?

**Comment by BestOwl** [comment]
It doesn't seem to work for MahApps.Metro 1.6.5, there is no any properties like ForceAllowsTransparency in BorderlessWindowBehavior
