### ISSUE TITLE
A simple way to show a dialog to get two values from user

### ISSUE THREAD

**Issue by epsi1on** [MahApps/MahApps.Metro#2070]
Hi,
Is there a simple way to create a dialog for gettings two values (numeric values) from user in MahApp?

**Comment by bigworld12** [comment]
Yes use custom dialog and make your own

**Comment by epsi1on** [comment]
thanks,
you mean inherit a new one from CustomDialog?

**Comment by bigworld12** [comment]
Yes

**Comment by epsi1on** [comment]
is there a tutorial for this? Its system is a little complex to inherit from

**Comment by epsi1on** [comment]
I need to create a new dialog with custom content but with button with same style as other dialogs, how can i implement that?
Thanks

**Comment by bigworld12** [comment]
create a new user control in xaml 
add these
 xmlns:Dialog="clr-namespace:MahApps.Metro.Controls.Dialogs;assembly=MahApps.Metro"        
 xmlns:Controls="http://metro.mahapps.com/winfx/xaml/controls"

then change <UserControl to this
<Dialog:CustomDialog
in code behind it should be changed automatically , (btw you don't need to inherit from custom dialog , just create a new instance of it and modify it)

**Comment by Elite182** [comment]
Hi I open again this subject because I can't display my CustomDialog. 

I create my custom like bigworld said, and I call it like this :

    MyCustom Dialog = new MyCustom(Results);
    await App.CurrentWindow.ShowMetroDialogAsync(Dialog);

the popup appair but no content are display ... just an empty dialog...

Have you an idea ?
Thx in advance !

**Comment by punker76** [comment]
I close this for now, feel free to reopen it if it's still an issue.
