### ISSUE TITLE
Show icon as a header for TabItem with styling

### ISSUE THREAD

**Issue by RiderOfTheli** [MahApps/MahApps.Metro#2071]
Hi,

I would like to ask you, if it's possible to set an icon as a header for TabItem in MetroAnimatedTabControl but to keep all the styling that standard header has? (GrayNormalBrush, GrayHoverBrush etc.)

Previously, there was an MetroImage, now I use rectangle to set an icon. 

Thank you for any advice.

**Comment by punker76** [comment]
@RiderOfTheli you can use the `HeaderTemplate` for such usage, see also #2107
