### ISSUE TITLE
GlowWindow Question

### ISSUE THREAD

**Issue by di48l069** [MahApps/MahApps.Metro#2072]
hi, i downloaded the latest pre-release and im getting this back when i debug.

see image below

![glow](https://cloud.githubusercontent.com/assets/7794777/9208398/90ff5b1a-4073-11e5-8497-99c2ffd55157.PNG)

Am i using it incorrectly?

```
<Controls:MetroWindow.GlowBrush>
 <SolidColorBrush Color="{DynamicResource AccentColor}" />
</Controls:MetroWindow.GlowBrush>
```

Or did something change?

**Comment by RiderOfTheli** [comment]
@di48l069 Try to add it just like that:

<Controls:MetroWindow x:Class="MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:Controls="clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro"
        xmlns:I="http://schemas.microsoft.com/expression/2010/interactivity"
        Title="Bla Bla Bla" 
        GlowBrush="{StaticResource AccentColorBrush}">

**Comment by RiderOfTheli** [comment]
@di48l069 Try to add it just like that:


    <Controls:MetroWindow x:Class="MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:Controls="clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro"
        xmlns:I="http://schemas.microsoft.com/expression/2010/interactivity"
        Title="Bla Bla Bla" 
        GlowBrush="{StaticResource AccentColorBrush}">

**Comment by di48l069** [comment]
Hi @RiderOfTheli I have tried that please see https://github.com/di48l069/7DTD-SMP in the Mainwindow i have applied what you said above and still showing me same error.

**Comment by punker76** [comment]
@di48l069 I can build and start your app, the only error is this (I use VS 2013):

```
log4net:ERROR XmlHierarchyConfigurator: Cannot find Property [conversionPattern] to set object on [log4net.Appender.RollingFileAppender]
log4net:ERROR XmlHierarchyConfigurator: Cannot find Property [conversionPattern] to set object on [log4net.Appender.RollingFileAppender]
```

![image](https://cloud.githubusercontent.com/assets/658431/9218976/92076d54-40d7-11e5-93e2-af0541c7b87f.png)

![image](https://cloud.githubusercontent.com/assets/658431/9218977/9591eb3e-40d7-11e5-806a-6182a2bb536d.png)

**Comment by di48l069** [comment]
@punker76  Drop a break point in MainWindow.cs

line:84

```
        private void Window_Closing(object sender, System.ComponentModel.CancelEventArgs e)
        {
			_isClosing = true;

            if (handler.GetConnectionState() == ConnectionState.Open)
            {
				Console.WriteLine("Connection open, shutdown.");
                handler.CloseConnection();
            }
        }
```

once app closes you will see this below

![glow](https://cloud.githubusercontent.com/assets/7794777/9232837/32c8db4e-4130-11e5-851a-fe367e8aa631.PNG)
