### ISSUE TITLE
How to increase the spacing between Tab Items?

### ISSUE THREAD

**Issue by feinstein** [MahApps/MahApps.Metro#2074]
Well, I guess the title says it all but...

I have a `TabControl` with several `TabItems`, but the `Header` of the `TabItems` are too close to each other. Is it there a way to increase their spacing? I tried `Margin` but this separates the `Underline` too.

Right now I am making it as `Header="  Text  "`, it works but it's a hack.

**Comment by punker76** [comment]
@feinstein you can change the `Padding` instead the `Margin`

**Comment by feinstein** [comment]
Have you tried it? Padding doesn't make a difference for me, if it does for you, please let me know so I can see what's wrong with my system.

**Comment by Malavos** [comment]
@feinstein  Please post your Window Xaml code! :pray:

**Comment by feinstein** [comment]
It's quite big...the tab part it's just:

	<mahapps:MetroTabItem mahapps:ControlsHelper.HeaderFontSize="{StaticResource TabFontSize}"                                  
						  Header="  My Header Text  " >                
	</mahapps:MetroTabItem>

And my Tab Control is:

	<mahapps:MetroTabControl mahapps:TabControlHelper.IsUnderlined="True" >
		<TabControl.Resources>
			<clr:Double x:Key="TabFontSize">18</clr:Double>                        
		</TabControl.Resources>

My general Resources.xaml file has nothing on tabs, and the rest of the Window xaml is just menu items and `WindowCommands`

**Comment by Malavos** [comment]
@feinstein Don't you have any other window property that's interfering with the tab disposition? Like responsive windows/etc?

**Comment by punker76** [comment]
@feinstein it's a bug with the `MetroTabItem`, i'll fix this now

**Comment by feinstein** [comment]
Thanks!
Em 26/08/2015 16:31, "Jan Karger" <notifications@github.com> escreveu:

**Comment by feinstein** [comment]
@punker76 Why should I use a `MetroTabItem` instead of a `TabItem`? What do I get from it? Same question for `MetroTabControl`.

**Comment by punker76** [comment]
@feinstein the difference is that you can have a close button with `CloseButtonEnabled="True"`

**Comment by feinstein** [comment]
@punker76 and what about `MetroTabControl`?

**Comment by punker76** [comment]
@feinstein 
- it generates by default `MetroTabControl`s if you bind a collection to `ItemsSource`
- you can define a `CloseTabCommand` which will also execute if you close a `MetroTabItem`
- you can define `TabStripMargin` for the tab item panel

**Comment by punker76** [comment]
@feinstein @Malavos the `Padding` issue with the `MetroTabItem` should be fixed with b67193def4b8d57b5aa8362d920bf37ab54e27ea (latest alpha 154)

**Comment by feinstein** [comment]
@punker76 Great! Last question:

Can I make the MetroTabControl expand the tabs evenly to take all the available size? 

For example:

![Demo Screen](https://cloud.githubusercontent.com/assets/8120472/9504504/57bc13ce-4c13-11e5-8adc-66d8c878bba5.jpg)

**Comment by feinstein** [comment]
@punker76 do you have any expected release date to have a Nuget Package for this release?

**Comment by Malavos** [comment]
@feinstein  alpha 154.. https://www.nuget.org/packages/MahApps.Metro/1.1.3-ALPHA154

**Comment by punker76** [comment]
@feinstein you can try create your own `TabPanel` and override the `MeasureOverride` and `ArrangeOverride` methods to fill the entire space.

**Comment by feinstein** [comment]
@Malavos I meant a proper release, I don't like to use Alphas and Betas.

**Comment by Malavos** [comment]
@feinstein  oh yes, sorry about that.

**Comment by punker76** [comment]
@feinstein sorry No due date yet

**Comment by gutyina70** [comment]
How can I achive the same result in a WinForms application?

**Comment by timunie** [comment]
Hi @gutyina70 ,
MahApps is WPF only, so we do not support WinForms. Thank you for your understanding. 
Maybe this link helps you: https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.integration.elementhost?redirectedfrom=MSDN&view=netframework-4.8

Happy coding,
Tim
