### ISSUE TITLE
Can't Change Checkbox Border Style

### ISSUE THREAD

**Issue by wwarby** [MahApps/MahApps.Metro#2075]
Hi,

I'm trying override the BorderBrush style of the CheckBox control, and having little success (I suspect because I'm doing something wrong rather than the problem being a bug). Specifically what I want to achieve is to make the checkbox control have no border when it is disabled (I haven't put the trigger in yet, for now I just wanted to try to make it have no border at any time).

I've read the source for Controls.CheckBox.xaml and I can see it's using TemplateBinding to the BorderBrush property, so I thought I could just override it with a simple setter in the default checkbox style, but it isn't working. Can anybody explain why? (incidentally, this style definitely does apply to all checkboxes in my solution. If I remove the "BasedOn" attribute, they look quite different).

	<Style TargetType="{x:Type CheckBox}" BasedOn="{StaticResource MetroCheckBox}">
		<Setter Property="BorderBrush" Value="{x:Null}" />
	</Style>

**Comment by punker76** [comment]
@wwarby just set `BorderThickness` to `0`

**Comment by wwarby** [comment]
@punker76 I've tried that too - doesn't seem to make a difference, the border persists.

**Comment by punker76** [comment]
@wwarby try the latest alpha

**Comment by wwarby** [comment]
Apologies for the delayed response - just to confirm that yes, this does work in the latest alpha, thanks!
