### ISSUE TITLE
If a TextBox has a Button, keying Enter should (optionally) invoke a button click

### ISSUE THREAD

**Issue by mkb137** [MahApps/MahApps.Metro#2082]
If a text box has a button via `TextBoxHelper.ButtonCommand`, typing text then keying Enter (while still in the text box) should (optionally) cause the button to be clicked.  Alternatively, there should be some way to set the button as the default.  

For example, imagine a text box with a search button.  A user would typically type in the search query and then hit "Enter".  If the search button is implemented as a standalone button with `IsDefault=True`, the search command will execute immediately.  If we replace the standalone search button with an embedded Metro button using `TextBoxHelper.ButtonCommand` and the `SearchMetroTextBox` style, hitting "Enter" will do nothing.

**Comment by xmedeko** [comment]
:+1:

**Comment by punker76** [comment]
@mkb137 I think you can get this by using the InputBindings of the TextBox itself. Don't know if MahApps should introduce a new property for this.

```xaml
<TextBox x:Name="SearchTextBox" TextBoxHelper.ButtonCommand="{Binding SearchCommand, Mode=OneWay}">
  <TextBox.InputBindings>
    <KeyBinding Command="{Binding SearchCommand, Mode=OneWay}"
                CommandParameter="{Binding ElementName=SearchTextBox, Path=Text, Mode=OneWay}"
                Key="Return" />
  </TextBox.InputBindings>
</TextBox>
```

**Comment by punker76** [comment]
@mkb137 just added a sample in 55a0bfc049c13eed56edf516d34f3b79401a3801
