### ISSUE TITLE
Tooltip for metro window maximize button

### ISSUE THREAD

**Issue by bksharma13** [MahApps/MahApps.Metro#2085]
Hi,
I am using the metro window control in my appilcation. While testing I found out that he tooltip for maximize button is incorrect when it is already maximized. It always shows restore down irrespective of the window state.
I was not able to upload the screenshot for now, due to upload error. But will do when possible.

Can you help me understand whether this bug is at my end or the library level. I am using DLL version 1.0.0.

**Comment by jyrka98** [comment]
I believe this was already fixed. Use a newer version.

**Comment by punker76** [comment]
@bksharma13 this is already fixed (try the alpha version instead)
