### ISSUE TITLE
Issue on MouseOver of a ListBoxItem (e.g RadioButton)

### ISSUE THREAD

**Issue by bbougot** [MahApps/MahApps.Metro#2088]
The commit https://github.com/MahApps/MahApps.Metro/commit/788f1aa0151423d463e23544862f415e58f441da cause an issue when using RadioButton as a ListBoxItem. On mouseover, the accent color takes all of the place on the right of the control, as shown below:

![sans-titre-2](https://cloud.githubusercontent.com/assets/8962802/9428353/9a99f036-49ab-11e5-8436-b9caf57ccce6.jpg)

Which should normally be:

![sans-titre-1](https://cloud.githubusercontent.com/assets/8962802/9428355/a25bf59e-49ab-11e5-9311-b9935250f1d5.jpg)

The concern lines seem to be 90 and 92. (Should be Stretch instead)

**Comment by punker76** [comment]
@bbougot the listbox items style uses now
```xaml
<Setter Property="HorizontalContentAlignment"
  Value="{Binding HorizontalContentAlignment, RelativeSource={RelativeSource AncestorType={x:Type ItemsControl}}}" />
```
and the listbox itself set this to
```xaml
<Setter Property="HorizontalContentAlignment"
  Value="Stretch" />
```

**Comment by bbougot** [comment]
Yes this is perfectly working now, thanks @punker76

**Comment by punker76** [comment]
@bbougot :+1:
