### ISSUE TITLE
DisplayMemberPath property of CheckListBox("Extended WPF ToolKit") can not work correctly in MahApps.Metro

### ISSUE THREAD

**Issue by FOCUSWEB** [MahApps/MahApps.Metro#2089]
It may be a bug, When I use MahApps.Metro in the Application. DisplayMemberPath of CheckListBox can not work currectly. The original object will be display in the UI.

image:
![](http://chuantu.biz/t2/13/1440441878x-1566638177.png)

**Comment by punker76** [comment]
@FOCUSWEB MahApps has no style for the CheckListBox, so its not a MahApps related bug.
