### ISSUE TITLE
WrapPanel border

### ISSUE THREAD

**Issue by Narzum** [MahApps/MahApps.Metro#2091]
When using WrapPanel in MetroWindow it has redunant border 1px height at the bottom. With regular window everything seems fine. 
![2015-08-25 15_05_01-mainwindow](https://cloud.githubusercontent.com/assets/11868819/9466101/d6eaaac2-4b3a-11e5-9a41-1164929ba1ae.png)

**Comment by punker76** [comment]
@Narzum which MahApps version? can you provide some xaml code? your screenshot looks like that you are not using MahApps right.

**Comment by Narzum** [comment]
It's 1.1.2 from NuGet. I excluded all the styles trying to eliminate this side effect, but nothing helped.  Here\s the code:

<met:MetroWindow x:Class="WpfApplication1.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:met="http://metro.mahapps.com/winfx/xaml/controls"
        Title="MainWindow" Height="350" Width="525">
    <Grid Background="White">
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto"/>
        </Grid.RowDefinitions>
        <WrapPanel Grid.Row="0" Background="DeepPink">
            <Border Width="30" Height="30" Background="White"/>
        </WrapPanel>
    </Grid>
</met:MetroWindow>

**Comment by punker76** [comment]
@Narzum ah ok, just use the latest alpha, it's a bug with UseLayoutRounding, should be fixed now

**Comment by Narzum** [comment]
Thanks for help. Hope to see new release soon.
