### ISSUE TITLE
Change the Validation Error Position

### ISSUE THREAD

**Issue by feinstein** [MahApps/MahApps.Metro#2093]
The Validation Error Popup is blocking the Description of my Texbox since it's on the **right** side by default. Is it there a way to change it to the **left**?

Here's my situation:

![captura_de_tela_082615_053528_pm](https://cloud.githubusercontent.com/assets/8120472/9505519/51a9d77c-4c19-11e5-9bae-676786c6a2dd.jpg)

And this is the original Form:

![captura_de_tela_082615_053554_pm](https://cloud.githubusercontent.com/assets/8120472/9505527/63bad1b4-4c19-11e5-92e7-137222869a5a.jpg)

So when the window opens, the user can't see there is a field called "Name", just something that can't be blank, but he can't know what he's supposed to type. 

I tried a watermark instead, but I didn't like it for this particular application, I rather a Form style, as it is.

---

**EDIT :**

I tried this code in my Resources.xaml:

```
<Style TargetType="{x:Type mahapps:CustomValidationPopup}">        
    <Setter Property="Placement" Value="Left" />
</Style>
```

But it didn't make any difference.

**Comment by punker76** [comment]
@feinstein Which version of MahApps are you using?

**Comment by feinstein** [comment]
1.1.2, the latest stable version.

**Comment by punker76** [comment]
@feinstein so, please try the latest alpha. there was something changed. you can now inherit from a base style for the `CustomValidationPopup`.

```xaml
    <Style x:Key="MetroValidationPopup"
           TargetType="{x:Type controls:CustomValidationPopup}">
        <Setter Property="HorizontalAlignment"
                Value="Right" />
        <Setter Property="HorizontalOffset"
                Value="0" />
        <Setter Property="VerticalOffset"
                Value="0" />
        <Setter Property="PopupAnimation"
                Value="Fade" />
        <Setter Property="Placement"
                Value="Right" />
    </Style>
```

**Comment by punker76** [comment]
@feinstein any news for this?

**Comment by feinstein** [comment]
@punker76 I will let you know as soon as I get to the office.

**Comment by feinstein** [comment]
@punker76 I have good and bad news....

I used your code, and changed it to `Left`. It works, but on the first interaction with the new Window I have the validation adorner get's shifted to the left. After I click or change the `TextBox` I am in or any other thing I do, it goes to the correct position.

Here's an image of what happens, I tested it with `Right` and `Left`, and it's a before and after. You can see how both scenarios have a shift to the left.

![captura_de_tela_091015_040102_pm](https://cloud.githubusercontent.com/assets/8120472/9798088/2678d37e-57d5-11e5-84bc-274e7ff18e82.jpg)

**Comment by punker76** [comment]
@feinstein it would be really nice if this could be separated in a single short app to demonstrate/reproduce this (for debugging...).

**Comment by feinstein** [comment]
@punker76 ok, let me see if I can make one for you quickly.

**Comment by feinstein** [comment]
@punker76 it appears to be an issue with a `Window` with no width and heigh and this properties:

	GlowBrush="{DynamicResource AccentColorBrush}"
	NonActiveGlowBrush="DarkGray"
	SizeToContent="WidthAndHeight" 
	ResizeMode="NoResize" 
	WindowStartupLocation="CenterOwner"

How do you prefer for me to send you the demo app's files?

**Comment by punker76** [comment]
@feinstein just come to gitter and send me a zip via private chat

**Comment by aluran** [comment]
Could you please paste the full code that is showing how we can position the valisation popup.
Is it possible to show it below the textbox.

**Comment by thanoue** [comment]
how to use a CustomValidationPopup?

**Comment by romigrabarz** [comment]
> Could you please paste the full code that is showing how we can position the valisation popup.
> Is it possible to show it below the textbox.

Please, paste a simple example. I don't know how to set validation error position on combobox.

**Comment by romigrabarz** [comment]
I need help with position of Validation popup.
My xaml like this:
```xaml
<mah:MetroWindow x:Class="WpfApp2.MainWindow"
                 xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"                  
                 xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                 xmlns:mah="http://metro.mahapps.com/winfx/xaml/controls"
                 Title="MainWindow" Height="450" Width="800">
    <Grid>
        <TextBox Width="200" Height="50" Text="{Binding Tekst, UpdateSourceTrigger=PropertyChanged, ValidatesOnDataErrors=True}"/>
    </Grid>
</mah:MetroWindow>
```

Validation popup allways still right.
https://drive.google.com/file/d/1dkZYAAtIfG1p6F0XSiRrowXXzHJBSEhM/view?usp=sharing

I want to change position that poup to TOP. How to achive this?
Please full example code.

**Comment by punker76** [comment]
@romigrabarz You can override the style of the popup by adding this to the resources of your App.xaml

```xaml
<Style BasedOn="{StaticResource MahApps.Styles.CustomValidationPopup}" TargetType="{x:Type controls:CustomValidationPopup}">
    <Setter Property="Placement" Value="Top" />
    <Setter Property="HorizontalOffset" Value="5" />
    <Setter Property="VerticalOffset" Value="-2" />
</Style>
```

You can play with the offset properties if you don't like the position.

![image](https://user-images.githubusercontent.com/658431/93218414-7b924900-f76a-11ea-8501-54dfb9bdcaa4.png)

**Comment by romigrabarz** [comment]
Thanks! Works with Application resources, but not when I add this resource in my xaml view:
````xaml
<mah:MetroWindow x:Class="WpfApp2.MainWindow"
                 xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"                  
                 xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                 xmlns:mah="http://metro.mahapps.com/winfx/xaml/controls"
                 Title="MainWindow" Height="450" Width="800">
    <mah:MetroWindow.Resources>
        <ResourceDictionary>
            <Style BasedOn="{StaticResource MahApps.Styles.CustomValidationPopup}" TargetType="{x:Type mah:CustomValidationPopup}">
                <Setter Property="Placement" Value="Top" />
                <Setter Property="HorizontalOffset" Value="5" />
                <Setter Property="VerticalOffset" Value="-2" />
            </Style>
        </ResourceDictionary>
    </mah:MetroWindow.Resources>
    <StackPanel>
        <TextBox Width="200" Height="50" Text="{Binding Tekst, UpdateSourceTrigger=PropertyChanged, ValidatesOnDataErrors=True}"/>
    </StackPanel>
</mah:MetroWindow>

````

How to make this works with XAML view, not in App.xaml?

**Comment by punker76** [comment]
@romigrabarz Is there a specific reason why you need this at your window?

**Comment by romigrabarz** [comment]
I don't have App.xaml because I wirte class library with xaml views and pass this as extensions to another third exe program (not WPF). Everything works fine (mah controls etc.) but I can't add styles into App.xaml.
Every styles I have to added to ResourceDictionary into my view.
