### ISSUE TITLE
Open Flyout from another UserControl

### ISSUE THREAD

**Issue by furiousbuilder** [MahApps/MahApps.Metro#2096]
Hi,

I'm doing an application with MahApps. I need to make a Flyout appear using code from my UserControl but the Flyout is in my MainWindow.

Here is my application : 
![screenshot 29](https://cloud.githubusercontent.com/assets/10899984/9525407/492fb79e-4ce4-11e5-85ef-aedf42f2e559.png)

All controls you see here, are a UserControl, when a click the icon at the top left (4 bars) to open the Flyout, nothing happens and an operation is still working in the background because if I close the application, VS is still debugging like here : 

![screenshot 31](https://cloud.githubusercontent.com/assets/10899984/9525485/9c1d5e70-4ce4-11e5-83d6-47cd94dab516.png)

Here is my code (in VB.Net) : 
Dim main as New MainWindow
main.TrainingFlyout.IsOpen = True

The Flyout can be correctly opened using "Non enregistré" button.
If you want, my project is here : http://www.mediafire.com/download/ty3zkk11wm35t3p/WorkoutHelper.zip

I think it's a bug, but I'm not sure at all, it's the first time I try to open a Flyout which isn't in the current window. I'm using MahApps Alpha 158.

Thanks,
Clément.

PS : Sorry for my English, I'm French :)

**Comment by bigworld12** [comment]
this is a basic instancing problem, i will try to make it easy
your application consists of 1 window that contains some user controls
what you want here is to pass the main window instance that had been already created by the program when you start debugging to the user controls.
one easy way i use in my code is to add a shared "Instance" in my main window

check this : 
```
'put this in the MainWindow class in code behind
Private Shared m_instance As MainWindow
 Public Shared ReadOnly Property Instance() As MainWindow
            Get
                Return m_instance
            End Get
 End Property
```
and in the constructor or the loaded event you add
```
m_instance = Me
```
and you are done, now you can access any of the flyouts like this
```
MainWindow.Instance.BlaBlaBlaOpenFlyout()
```
the reason it didn't work is that you created a new instance of the mainwindow class (New Window)
instead you should pass the current instance

**Comment by furiousbuilder** [comment]
Ahhh thank you :) It worked !

**Comment by furiousbuilder** [comment]
Another thing, now, I need to do the same thing but the control is in a SetupChildWindow named "MainSetup". Inside the code of the ChildWindow, I need to use something like this at loading : 
m_instance = Me
Of course "Me" isn't correct, how can I do ? Sorry, I don't have a lot of experience in WPF...
