### ISSUE TITLE
ComboBox not displaying correctly in Windows 10?

### ISSUE THREAD

**Issue by NickP13** [MahApps/MahApps.Metro#2099]
I have an app with a ComboBox that was working fine in Windows 7, it looked like this - 
![mahapps1](https://cloud.githubusercontent.com/assets/12263462/9544604/300936f2-4d50-11e5-9787-1ed7d242d2a7.png)

But now in Windows 10 this is what I get - 
![mahapps2](https://cloud.githubusercontent.com/assets/12263462/9544609/3b75ed50-4d50-11e5-9cd6-5bdd9677a5cc.png)
![mahapps3](https://cloud.githubusercontent.com/assets/12263462/9544611/3ce93d40-4d50-11e5-8ad3-a499dd013b3a.png)

As you can see, the drop down list is still displaying correctly but the ComboBox itself seems to be using the default Windows 10 appearance. I had been using an old version of Mahapps.Metro, so I updated to 1.1.2 and I'm still having the same issue. 

Strangely, the XAML designer in Visual Studio shows the ComboBox correctly at first until the drop down menu is expanded, then it looks like the third picture i posted. When I actually build and run the app it shows the default Windows 10 ComboBox right from the start. Not really sure what could be causing this, any ideas?

**Comment by punker76** [comment]
@NickP13 can you provide a short xaml code from your combobox? it looks like your combobox does not get the mahapps style. i checked the main demo under win 10 and all works fine...

**Comment by NickP13** [comment]
@punker76  Here are the relevant parts from the xaml. Let me know if there's anything else you'd need to see, I'm still pretty new at WPF. Thanks.

<Controls:MetroWindow x:Name="Main_window" x:Class="BOM_v2.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:Controls="clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro"
        
...

<ComboBox x:Name="txtCustomer" HorizontalAlignment="Left" Height="23" Margin="26,101,0,0" VerticalAlignment="Top" Width="200" Foreground="#FFFBF5F5" BorderBrush="#FF00D1FF"  Background="#FF131111" IsEditable="True">
    <ComboBoxItem Background="#FF131111" Content="Test 1" />
    <ComboBoxItem Background="#FF131111" Content="Test 2"/>
    <ComboBoxItem Background="#FF131111" Content="Test 3"/>
    <ComboBoxItem Background="#FF131111" Content="Test 4"/>
</ComboBox>

**Comment by punker76** [comment]
@NickP13 happens this only in the designer?

**Comment by NickP13** [comment]
No, in the designer it looks correct until you open the drop down list, then it changes to the default Windows 10 ComboBox like in the 3rd picture.

When i build and run the app it shows the Windows 10 ComboBox as soon as the app starts.

**Comment by punker76** [comment]
ok, this seems to be another visual studio designer bug.
