### ISSUE TITLE
How to change the style of the header in a flyout?

### ISSUE THREAD

**Issue by jmecosta** [MahApps/MahApps.Metro#2100]
Hi

Trying to change the size of the header, possible also reducing the size of the arrow. Any examples that I can use?

Thanks

Jorge Costa

**Comment by punker76** [comment]
@jmecosta you can create your own `HeaderTemplate` https://github.com/MahApps/MahApps.Metro/blob/master/MahApps.Metro/Themes/Flyout.xaml#L270-L271
just look in to the default template https://github.com/MahApps/MahApps.Metro/blob/master/MahApps.Metro/Themes/Flyout.xaml#L12-L109

**Comment by jmecosta** [comment]
Yep, I've reverted to that yes. Thanks
