### ISSUE TITLE
Window buttons(minimize, maximize, close) are always shown on top

### ISSUE THREAD

**Issue by prateekmaheshwari** [MahApps/MahApps.Metro#2101]
![issue](https://cloud.githubusercontent.com/assets/13113989/9574668/7fdff330-4fe6-11e5-9d0b-2fc75d395650.png)

While using MahApps Metro window for my application, I am facing an issue, as the Window buttons i.e. the Minimize, Maximize and Close buttons are always on top. I even  gave the floating grid a Z-Index = 1 but it didn't help. Is there a way to keep floating grid on top of the window buttons.

See attached image.

**Comment by kanaksony** [comment]
I am also seeing this issue in my application :(

**Comment by thoemmi** [comment]
The window buttons have `Panel.ZIndex="1"`, so try `2`.

**Comment by prateekmaheshwari** [comment]
I have tried Panel.ZIndex="2" for floating grid also, still the same issue :(

**Comment by moser96** [comment]
I think I found the solution for your problem in the **[docs](http://mahapps.com/controls/flyouts.html)**
at the bottom of the page you can see there exists a property **ShowWindowCommandsOnTop** with the **default value True**. I haven't tried it but it should work if you set this property to false :wink:

**Comment by prateekmaheshwari** [comment]
ShowWindowCommandsOnTop, this property is not available in version 1.1.2 (which I am using currently) and not even in version 0.9.0.0 (which I was using earlier).
Please provide a correct solution. :(

**Comment by punker76** [comment]
@prateekmaheshwari since 0.9 we changed something.

to avoid overlapping the right commands and window button commands you should set these properties at the MetroWindow tag:

```
RightWindowCommandsOverlayBehavior="Never"
WindowButtonCommandsOverlayBehavior="Never"
```

or if you use Flyouts

```
RightWindowCommandsOverlayBehavior="Flyouts"
WindowButtonCommandsOverlayBehavior="Flyouts"
```

**Comment by prateekmaheshwari** [comment]
@punker76 my actual problem is not the overlapping of right commands and window button commands.
The issue I am actually facing is that when I take my floating grid over over the title bar, then the items of title bar are coming on top of the floating grid, which is not desired. Please refer to the attached file.

Here, I have a textblock with text="World" and when I take the floating grid over the title bar, the textblock, minimize and maximize button come on top of the floating grid, which is not desired.

Is there a way to keep floating grid on top of them.

![issuemetrowindow](https://cloud.githubusercontent.com/assets/13113989/9630921/0305b596-519b-11e5-9794-db59161b9d53.png)

**Comment by punker76** [comment]
@prateekmaheshwari ok, so this is not possible. maybe only with a custom flyout with margin. but what do you want do?

**Comment by prateekmaheshwari** [comment]
@punker76  I only want that when I drag my Floating Grid over the Title bar, then the items on the title bar (Left/Right Buttons or Window Buttons) should not come over the grid as it is happening (refer the above screenshot).

**Comment by punker76** [comment]
@prateekmaheshwari that's not possible

**Comment by bigworld12** [comment]
did you try something like ZIndex=99 ?
