### ISSUE TITLE
Flyouts exception in designer

### ISSUE THREAD

**Issue by tasc18** [MahApps/MahApps.Metro#2102]
so, when i opened visual studio after saving my application, the designer is not working. I found that the flyout is bugging it, and i cannot edit it in the designer any more. Here is the exception:

ArgumentException: Cannot add instance of type 'SetFlyoutOpenAction' to a collection of type 'TriggerActionCollection'. Only items of type 'T' are allowed.

StackTrace
 at System.Windows.FreezableCollection`1.Cast(Object value)
   at System.Windows.FreezableCollection`1.System.Collections.IList.Add(Object value)
   at System.Xaml.Schema.XamlTypeInvoker.AddToCollection(Object instance, Object item)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.Add(Object collection, XamlType collectionType, Object value, XamlType valueXamlType)

InnerException: None

**Comment by punker76** [comment]
@tasc18 which MahApps version? any other special thing with your flyouts?

**Comment by tasc18** [comment]
@punker76 I'm working with the 1.1.2
my flyouts work just right when i add it, this excpetion only happen when i close and reopen the visual studio. I've found some workaround, like cut the flyout xaml code and saving the project, and restarting the visual studio, and then pasting the code again. When i do this the designer go back to normal with all of my flyout content. But i'm not sure this work every time.

**Comment by punker76** [comment]
@tasc18 if you want then try the latest alpha, there is something fixed wirth flyouts and the designer.

**Comment by tasc18** [comment]
For some reason the latest alpha wasn't accepting the xaml modification to use MahApps. But now it's working. The designer now is working perfectly with the flyouts and everything every time i reopen the VS. I'll post again if this happens again. Sorry my english btw. And thank you @punker76 =D
