### ISSUE TITLE
Fix MetroWindow dialog behavior

### ISSUE THREAD

**Issue by moser96** [MahApps/MahApps.Metro#2103]
If you have a MetroWindow and want to display this from an other window by using:
```
otherWindow.ShowDialog();
```
There is one issues with the dialog behavior:
If you click on the parent window it doesn't react as spectated, but you **shouldn't be able to switch back to the parent window by using the Taskswitcher.**

**Comment by bigworld12** [comment]
Do you mean it doesn't review focus ?

**Comment by moser96** [comment]
It does receive the focus, but you can switch to the parent window by using Alt + TAB and that's not the dialog behavior I expect.

**Comment by punker76** [comment]
@moser96 maybe you forgot to set the `Owner` property

**Comment by bigworld12** [comment]
This is the actual behavior , try messagebox.show
And it will also have the same behavior
If you want your behavior you can do windowinstance.Show()
And implement your own functions to get the result

**Comment by moser96** [comment]
@punker76  THX, I totally forgot it! Now it works as expected :smile:
