### ISSUE TITLE
Strange Freezzing issue when combining the MahApps MetroWindow and some Infragistics WPF components

### ISSUE THREAD

**Issue by ubx-caloca** [MahApps/MahApps.Metro#2104]
I'm seeing a long application (10 seconds) freeze when using the MahApps (version 1.1.2)  in combination with the XamDockManager and XamNetworkNode Infragistics WPF components. Can you please help me out in coming out with a fix?.

To reproduce the issue one must install the latest Infragistics WPF components trial version, run the attachment visual studio project and zoom in (a lot) in the graph (using the mouse wheel button), then  float the "Gra Pane" by double clicking on the Pane title window. The result is that the application freezes for about 10 seconds. If you don't see the freeze, then you must zoom in more in the graphic component. 

If I make the MainWindow.xaml control extend from a normal WPF window instead of contros:MetroWindow, the issue is gone. I have contacted the Infragistics support team and they told me that fixing the issue from their end would involved restructuring their entire component architect and they will not do it in the short term (maybe never). I'm hesitant to remove the MahApps MetroWindow from the application because I like the MetroWindow custom style that I made and I also like the  window functionality that it provides to my application.

Sample VS project:
https://www.dropbox.com/s/wy5c6tf75skjh2f/WpfApplicationTestXamNetNode.zip?dl=0

Video demonstrating the issue:
https://www.youtube.com/watch?v=ODhmkeHP_to

**Comment by punker76** [comment]
@ubx-caloca i have test your app with the latest source and updated app.xaml and it seems that it is fixed now

```xaml
<Application x:Class="WpfApplicationTestXamNetNode.App"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             StartupUri="MainWindow.xaml">
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Colors.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/Blue.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/BaseLight.xaml" />

                <ResourceDictionary Source="Resources/CustomBorderlessWindowResDict.xaml" />
                <ResourceDictionary Source="Resources/CosmopolitanStyleResourceDictionary.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>
</Application>
```

**Comment by ubx-caloca** [comment]
Hi again,

Yep, the issue is gone with the latest source. Thanks for your time, the issue was giving me some headaches. Keep up the great work!!
