### ISSUE TITLE
text inside TextBox is moving right/left when enter/delete it

### ISSUE THREAD

**Issue by QuantumDeveloper** [MahApps/MahApps.Metro#2105]
I think issue could be in layout rounding optiona enabled.

**Comment by punker76** [comment]
@QuantumDeveloper can you more specify what is going wrong? i don't really know what do you mean?

**Comment by QuantumDeveloper** [comment]
I mean that when you enter text inside textbox, text moves to one/two pixels from rigth to left and back. And it seems that it happens because in template enabled layout rounding option.

**Comment by punker76** [comment]
@QuantumDeveloper i don't see this in latest source

**Comment by QuantumDeveloper** [comment]
Please, try this inside datagrid column

**Comment by punker76** [comment]
@QuantumDeveloper works fine in the demo, so create a short sample and/or make a creencast...
