### ISSUE TITLE
VS Designer warning: A value of type 'MetroAnimatedSingleRowTabControl' cannot be added to a collection or dictionary of type 'UIElementCollection'

### ISSUE THREAD

**Issue by gigios** [MahApps/MahApps.Metro#2106]
Often, in my Visual Studio editor (2013 and 2015) I have a warning (the editor underline code) with this message:

A value of type 'MetroAnimatedSingleRowTabControl' cannot be added to a collection or dictionary of type 'UIElementCollection'

This problem happen when I have a MetroAnimatedSingleRowTabControl inside a grid.
I have attached a screenshot of the error also in the MetroDemo application (TabControlExamples.xaml).
![warning01](https://cloud.githubusercontent.com/assets/8749627/9601054/52f3547a-509f-11e5-9831-158260f89efc.jpg)

Have you any idea or suggestion to solve this 'annoying' problem?
Regards
Luigi.

**Comment by bigworld12** [comment]
Replace TabControl with
Controls: MetroAnimatedSingleRowTabControl

**Comment by gigios** [comment]
Sorry but it is not clear for me.
I'm using the Controls:MetroAnimatedSingleRowTabControl!
The screenshot is related the sample 'MetroDemo' present in this repository.

**Comment by bigworld12** [comment]
You have
<TabControl.Resources>
Replace it with
< Controls:MetroAnimatedSingleRowTabControl>

**Comment by gigios** [comment]
Ok, this for the 'sample' but in my application I don't have any 'resources' section for the TabControl.
I'm not sure that the problem is related to the MahApps because, after a new build, the warning disappear, but if I close and reopen the Visual Studio the warning reappear.

**Comment by punker76** [comment]
@gigios the visual studio designer is not perfect. this is not MahApps related.

**Comment by Ghislain1** [comment]
From the  Properties Window of VS remove the Custom Tool Value or replace it!
