### ISSUE TITLE
Complex TabItem Header loses style

### ISSUE THREAD

**Issue by eggapauli** [MahApps/MahApps.Metro#2107]
(Might be a duplicate of #2071, but since nobody responded I'll try it again)

I have a `TabItemControl` with `TabItem`s that have a more complex header than just a string.

E.g. this XAML code

```
<TabControl>
    <TabItem Header="Comments">
        <!-- ... -->
    </TabItem>
    <TabItem>
        <TabItem.Header>
            <StackPanel Orientation="Horizontal">
                <Label>Include current project?</Label>
                <CheckBox VerticalAlignment="Center" />
            </StackPanel>
        </TabItem.Header>
        <!-- ... -->
    </TabItem>
    <!-- ... -->
</TabControl>
```
produces this layout:
![image](https://cloud.githubusercontent.com/assets/237707/9655618/bd660fd4-5232-11e5-9008-b5e66e13eef7.png)

Is it possible to apply the standard style to tab items with complex headers as well?

**Comment by punker76** [comment]
@eggapauli for such 'complex' header you should better use the `HeaderTemplate`.

**Comment by eggapauli** [comment]
Ahh, didn't know about that. Works like a charm. Thanks for the amazingly quick response.
