### ISSUE TITLE
Is it Possible to create Flyout on sacrollable window?

### ISSUE THREAD

**Issue by Nadeem1989** [MahApps/MahApps.Metro#2108]
Hi I am new on MahApps.Metro, I have used this few days back and Now wish to add Flyout on scrollable window on bottom like fix menu bar. Is it possible?

**Comment by punker76** [comment]
@Nadeem1989 yes of course, set the `Position` property to `Bottom`

**Comment by Nadeem1989** [comment]
Thanks for reply sir, I have set Positio to Bottom, But the problem is when I scroll up on the screen it gets inside the bottom no-viewable area and when I again scroll down then only I am able to watch the Flyout

**Comment by punker76** [comment]
@Nadeem1989 so show us the xaml of your window...

**Comment by Nadeem1989** [comment]
<Controls:FlyoutsControl>
            <Controls:Flyout Header="Actions" Name="TestFlyout" VerticalAlignment="Bottom" Position="Top" Width="990" Theme="Adapt">
                <Grid>
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="20*"></ColumnDefinition>
                        <ColumnDefinition Width="20*"></ColumnDefinition>
                    </Grid.ColumnDefinitions>
                    <Button Content="Save" Width="70" Height="30" HorizontalAlignment="Left" Grid.Column="0"></Button>
                    <Button Content="Cancel" Width="70" Height="30" HorizontalAlignment="Left" Grid.Column="1"></Button>
                </Grid>
            </Controls:Flyout>
        </Controls:FlyoutsControl>

**Comment by Nadeem1989** [comment]
Unable to sahre complete code here, Dont know why, watch below link for code snippent:
http://stackoverflow.com/questions/32391077/wpf-is-it-possible-to-create-flyout-on-scrollable-window-using-mahapps-metro

**Comment by punker76** [comment]
@Nadeem1989 maybe you forgot to put your flyout in the flyouts. and use `Position="Bottom"` not `VerticalAlignment="Bottom"`

```xaml
<Controls:MetroWindow.Flyouts>
    <Controls:FlyoutsControl>
        <Controls:Flyout Header="Actions"
                            Name="TestFlyout"
                            Position="Bottom"
                            Width="990"
                            Theme="Adapt">
            <Grid>
                <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="20*"></ColumnDefinition>
                    <ColumnDefinition Width="20*"></ColumnDefinition>
                </Grid.ColumnDefinitions>
                <Button Content="Save"
                        Width="70"
                        Height="30"
                        HorizontalAlignment="Left"
                        Grid.Column="0"></Button>
                <Button Content="Cancel"
                        Width="70"
                        Height="30"
                        HorizontalAlignment="Left"
                        Grid.Column="1"></Button>
            </Grid>
        </Controls:Flyout>
    </Controls:FlyoutsControl>

</Controls:MetroWindow.Flyouts>
```

**Comment by Nadeem1989** [comment]
Getting This Error I Trid your code on WPF Page (I am using WPF Page Not Window)
-->The member "Flyouts" is not recognized or is not accessible.

**Comment by punker76** [comment]
@Nadeem1989 yeah that's right, it's only available for `MetroWindow`, so please post your complete page xaml.

**Comment by Nadeem1989** [comment]
<Page x:Class="WPFNavigation.Pages.NewSIMIssue"
      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
      xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
      xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
      xmlns:Controls="clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro"
      mc:Ignorable="d" d:DesignWidth="600"
	Title="New SIM Card Issue" SizeChanged="Page_SizeChanged_1" d:DesignHeight="898">


    <ScrollViewer Name="scrlMain" CanContentScroll="True" HorizontalScrollBarVisibility="Auto" VerticalScrollBarVisibility="Auto" VerticalAlignment="Stretch">
        <Canvas Name="cnvMain" Margin="10,0,0,0" Width="800" Height="890" HorizontalAlignment="Left">
            
            <Grid HorizontalAlignment="Center" >
                <Grid.RowDefinitions>
                    <RowDefinition />
                    <RowDefinition />
                    <RowDefinition />
                    <RowDefinition />
                </Grid.RowDefinitions>
                <StackPanel Grid.Row="0" Background="#F5F5F5" Grid.Column="0" Width="995" Margin="0,5,0,5">
                    <TextBlock Height="42">
                    <Image Height="20" Width="20" Source="C:\Apps\R&amp;D\WPFNavigation\WPFNavigation\Images\View1.png"
                    />
                    <TextBlock FontSize="20"><TextBlock FontSize="25" Foreground="Green"> Issue SIM Card - </TextBlock> Customer Name
                </TextBlock>
                </TextBlock>
                </StackPanel>
                <GroupBox Header="Payment Mode" Grid.Row="1" Name="grpPayment" HorizontalAlignment="Left" Width="995" Margin="1,0,-2,0" VerticalAlignment="Top" Height="80">
                    <Grid>
                        <Grid.ColumnDefinitions>
                            <ColumnDefinition Width="0.20*" />
                            <ColumnDefinition Width="0.20*" />
                            <ColumnDefinition Width="0.20*" />
                            <ColumnDefinition Width="0.20*" />
                            <ColumnDefinition Width="0.20*" />
                        </Grid.ColumnDefinitions>
                        <RadioButton Name="rbtnCash" Click="rbtnCash_Click_1" Content="Cash" Grid.Column="0" GroupName="PaymentMode"></RadioButton>
                        <RadioButton Name="rbnCC" Click="rbnCC_Click_1" Content="CC"  Grid.Column="1" GroupName="PaymentMode"></RadioButton>
                        <RadioButton Content="Web"  Grid.Column="2" GroupName="PaymentMode"></RadioButton>
                        <RadioButton Content="Agency"  Grid.Column="3" GroupName="PaymentMode"></RadioButton>
                        <RadioButton Content="LA/RE"  Grid.Column="4" GroupName="PaymentMode"></RadioButton>
                        
                    </Grid>
                </GroupBox>
                <Grid Grid.Row="2">
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="995" />
                    </Grid.ColumnDefinitions>
                    <Grid.RowDefinitions>
                        <RowDefinition Height="0.30*" />
                        <RowDefinition Height="0.30*" />
                        <RowDefinition Height="0.60*" />
                    </Grid.RowDefinitions>
                    <TextBlock Margin="200,0,712,61" Grid.Column="0" Grid.Row="1" VerticalAlignment="Bottom" Height="16">Scan Barcode
                    </TextBlock>

                    <TextBox Controls:TextBoxHelper.ClearTextButton="True" Grid.Row="1" Margin="287,19,558,59" x:Name="txtBarCode"/>
                    <Button x:Name="btnSearch" Content="Search" Grid.Row="1" HorizontalAlignment="Left" Margin="444,17,0,0" VerticalAlignment="Top" Width="75" Height="29"/>

                    <Button x:Name="btnRemove" Grid.Row="0" Content="Remove" HorizontalAlignment="Left" Margin="527,17,0,0" VerticalAlignment="Top" Width="75" Height="29" Grid.RowSpan="2"/>
                    <GroupBox Grid.Row="1" Width="760" Header="Product Details" Margin="2,49,233,-10" Grid.RowSpan="2">
                        <Grid>
                            <Grid.ColumnDefinitions>
                                <ColumnDefinition Width="38*"></ColumnDefinition>
                                <ColumnDefinition Width="28*"></ColumnDefinition>
                                <ColumnDefinition Width="9*"></ColumnDefinition>
                                <ColumnDefinition Width="25*"></ColumnDefinition>
                            </Grid.ColumnDefinitions>
                            <Grid.RowDefinitions>
                                <RowDefinition></RowDefinition>
                                <RowDefinition></RowDefinition>
                            </Grid.RowDefinitions>
                            <Label Grid.Row="0" Grid.Column="0" Margin="-6,0,6,1" Grid.RowSpan="2">Discount Coupon</Label>
                            <TextBox Controls:TextBoxHelper.ClearTextButton="False" x:Name="txtCoupon" Margin="94,2,0,-2" Grid.Row="0" Grid.Column="0" Grid.RowSpan="2" HorizontalAlignment="Left" Width="118" />
                            <Button x:Name="btnCalcDiscount" Content="Calculate Discount" Margin="215,2,145,-2" Grid.RowSpan="2" Grid.ColumnSpan="2"/>
                            <Label Grid.Column="1" Margin="75,0,0,-2" Grid.RowSpan="2" HorizontalAlignment="Left" Width="66">SIM Value</Label>
                            <TextBox Controls:TextBoxHelper.ClearTextButton="False" x:Name="txtSimVal" Grid.Column="1" Margin="142,2,8,-2" Grid.RowSpan="2"/>
                            <Label Grid.Column="2" Margin="2,0,6,-2" Grid.RowSpan="2">Dis. Amt.</Label>
                            <TextBox x:Name="txtDisAmt" Grid.Column="2" Controls:TextBoxHelper.ClearTextButton="True" Margin="62,2,132,-2" Grid.RowSpan="2" Grid.ColumnSpan="2"/>

                            <Label Grid.Column="3" Margin="61,0,66,-2" Grid.RowSpan="2">SIM Amt.</Label>
                            <TextBox Width="60" x:Name="txtAmt" Grid.Column="3" Controls:TextBoxHelper.ClearTextButton="True" Margin="122,2,5,-2" Grid.RowSpan="2"/>
                            <Grid Grid.Row="1">
                                <Grid.ColumnDefinitions>
                                    <ColumnDefinition Width="0.20*"></ColumnDefinition>
                                    <ColumnDefinition Width="0.20*"></ColumnDefinition>
                                    <ColumnDefinition Width="0.20*"></ColumnDefinition>
                                    <ColumnDefinition Width="0.20*"></ColumnDefinition>
                                    <ColumnDefinition Width="0.20*"></ColumnDefinition>
                                </Grid.ColumnDefinitions>
                                <Grid.RowDefinitions>
                                    <RowDefinition></RowDefinition>
                                    <RowDefinition ></RowDefinition>
                                </Grid.RowDefinitions>
                                <Label Margin="-12,114,0,-126" Grid.Row="1">Mobile No.</Label>
                                <TextBox  Margin="3,112,27,-124"  x:Name="txtMob" Grid.Column="1" Grid.ColumnSpan="2" Grid.Row="1"/>

                                <Label Margin="45,112,26.667,-124" Grid.Row="1" Grid.ColumnSpan="3" Grid.Column="2">Delivery Charges</Label>
                                <TextBox  Margin="28.333,112,-54.333,-124"  x:Name="txtDelvCharge" Grid.Column="4" Grid.Row="1"/>

                                <Label Margin="-12,141,25,-153" Grid.Row="1" Grid.ColumnSpan="2">Product Code</Label>

                                <ComboBox Grid.Column="1" Grid.Row="1" Grid.ColumnSpan="2" Margin="17,142,11.667,-154" Width="70" x:Name="cbProductCode">
                                    <ComboBoxItem Content="Select" IsSelected="True"></ComboBoxItem>
                                </ComboBox>


                                <Label Margin="42,141,24.667,-153" Grid.Row="1" Grid.ColumnSpan="3" Grid.Column="2">Voucher Quantity</Label>

                                <ComboBox Grid.Column="4" Grid.Row="1" Margin="29.667,142,-42.667,-154" Width="70" x:Name="cbVoucherQty">
                                    <ComboBoxItem Content="Select" IsSelected="True"></ComboBoxItem>
                                </ComboBox>
                                <Label Margin="105.333,141,-153.333,-153" Grid.Row="1" Grid.Column="4">Recharge Amount</Label>
                                <TextBox  Margin="210.333,141,-203.333,-153"  x:Name="txtRechargeAmt" Grid.Column="4" Grid.Row="1"/>

                                <Label Margin="263.333,141,-272.333,-153" Grid.Row="1" Grid.Column="4">Total Sales</Label>
                                <TextBox  Margin="330.333,141,-323.333,-153"  x:Name="txtTotSale" Grid.Column="4" Grid.Row="1"/>

                                <Label Margin="387.333,141,-396.333,-153" Grid.Row="1" Grid.Column="4">ATV Price</Label>
                                
                                <Label Margin="448.333,141,-441.333,-153" Grid.Row="1" Grid.Column="4">458</Label>

                            </Grid>
                            <DataGrid Grid.Row="1" ScrollViewer.CanContentScroll="True" Grid.Column="0" VerticalAlignment="Top" x:Name="dgSIMData" IsReadOnly="True" Width="990" Margin="0,37,-246,-96" Grid.ColumnSpan="4" Height="86">
                                <DataGrid.Columns>
                                    <DataGridTextColumn Header="ID" Binding="{Binding ID}"/>

                                    <DataGridTextColumn Header="SIMCode" Binding="{Binding Age}"/>

                                    <DataGridTextColumn Header="Agreement No." Binding="{Binding EmailID}"/>

                                    <DataGridTextColumn Header="SIM No." Binding="{Binding MobileNo}"/>

                                    <DataGridTextColumn Header="Mobile No." Binding="{Binding City}"/>

                                    <DataGridTextColumn Header="Bar Code" Binding="{Binding City}"/>

                                    <DataGridTextColumn Header="Amount" Binding="{Binding City}"/>

                                    <DataGridTextColumn Header="Promotion No." Binding="{Binding City}"/>

                                    <DataGridTextColumn Header="Item Name" Binding="{Binding City}"/>

                                    <DataGridTextColumn Header="Platform" Binding="{Binding City}"/>

                                    <DataGridTextColumn Header="Type" Binding="{Binding City}"/>

                                    <DataGridTextColumn Header="Kit No." Binding="{Binding City}"/>
                                    <DataGridTextColumn Header="Add Network" Binding="{Binding City}"/>
                                </DataGrid.Columns>
                            </DataGrid>

                        </Grid>


                    </GroupBox>
                </Grid>

                <GroupBox Header="Passport Details" Height="230" Grid.Row="3" Width="995" Margin="0,160,-2,-133" >
                    <Grid Width="760" Height="120" Margin="0,-2,0,53">
                        <Grid.ColumnDefinitions>
                            <ColumnDefinition Width="0.25*"></ColumnDefinition>
                            <ColumnDefinition Width="0.25*"></ColumnDefinition>
                            <ColumnDefinition Width="0.25*"></ColumnDefinition>
                            <ColumnDefinition Width="0.25*"></ColumnDefinition>
                        </Grid.ColumnDefinitions>
                        <Grid.RowDefinitions>
                            <RowDefinition/>
                            <RowDefinition/>
                            <RowDefinition/>
                            <RowDefinition/>
                            <RowDefinition/>
                        </Grid.RowDefinitions>

                        <Label Grid.Row="0" Grid.Column="0" Margin="0,-9,92,9">Customer Name</Label>
                        <TextBox x:Name="txtCustName" Grid.ColumnSpan="2" Grid.Column="0" Grid.Row="0" Margin="155,-10,1,8"/>
                        <ComboBox Margin="106,-10,36,8" Grid.Row="0" x:Name="cbCustGender">
                            <ComboBoxItem Content="Mr." IsSelected="True"></ComboBoxItem>
                            <ComboBoxItem Content="Mrs." ></ComboBoxItem>
                            <ComboBoxItem Content="Ms." ></ComboBoxItem>
                            <ComboBoxItem Content="Miss" ></ComboBoxItem>
                        </ComboBox>
                        <Button x:Name="btnScanFront" Grid.Column="2" Content="Scan Front Page" Margin="21,-9,64,8"/>
                        <Button x:Name="btnScanAddress" Grid.Column="2" Content="Scan Address Page" Margin="132,-9,133,8" Grid.ColumnSpan="2"/>
                        <Button x:Name="btnBoarding" Grid.Column="3" Content="Scan Boarding Pass" Margin="62,-9,8,8"/>

                        <Label Grid.Column="0" Margin="0,16,113,5" Grid.RowSpan="2">Passport No.</Label>
                        <TextBox x:Name="txtPassportNo" Grid.Column="0" Margin="81,20,9,2" Grid.RowSpan="2" />

                        <Label Margin="188,20,94,4" Grid.RowSpan="2" Grid.ColumnSpan="2">Date Of Birth</Label>
                        <DatePicker x:Name="txtDOB" Grid.Column="1" Margin="76,20,2,2" Grid.RowSpan="2" SelectedDateFormat="Short" />

                        <Label Grid.Column="1" Margin="184,20,67,4" Grid.ColumnSpan="2" Grid.RowSpan="2">Date Of Issue Passport</Label>
                        <DatePicker x:Name="txtDOI" Grid.Column="2" Margin="121,20,147,2" Grid.RowSpan="2" SelectedDateFormat="Short" Grid.ColumnSpan="2" />

                        <Label Grid.Column="0" Margin="0,0,113,0" Grid.Row="2">Sex</Label>
                        <RadioButton GroupName="grpSex" Width="50" Grid.Column="0" Grid.Row="2" Margin="35,2,105,0">Male</RadioButton>
                        <RadioButton GroupName="grpSex" Width="70" Grid.Column="0" Grid.Row="2" Margin="88,2,32,0">Female</RadioButton>

                        <Label Margin="166,1,62,20" Grid.ColumnSpan="2" Grid.Row="2" Grid.RowSpan="2">Date Of Expiry of Passport</Label>
                        <DatePicker x:Name="txtDOExpPassport" Grid.Column="1" Margin="125,2,143,20" Grid.RowSpan="2" SelectedDateFormat="Short" Grid.ColumnSpan="2" Grid.Row="2" />

                        <Label Margin="52,1,55,20" Grid.Row="2" Grid.RowSpan="2" Grid.Column="2">Place Of Issue Name</Label>
                        <TextBox x:Name="txtPlaceOfIssue" Grid.Column="2" Margin="133,3,147,19" Grid.RowSpan="2" Grid.ColumnSpan="2" Grid.Row="2" />

                        <GroupBox Header="Cutomer Sign." Grid.Column="3" Grid.RowSpan="4"  Margin="47,1,5,-17" Grid.Row="1">
                            <Image Grid.Column="3" Grid.RowSpan="3" Source="C:\Apps\R&amp;D\WPFNavigation\WPFNavigation\Images\SignMine.png" Margin="1,1,3,-1"/>
                        </GroupBox>
                        <Button x:Name="btnOk" Content="Ok" Grid.Row="4" Grid.Column="3" HorizontalAlignment="Left" Margin="31,47,0,-55" VerticalAlignment="Top" Width="50" Height="32" />
                        <Button x:Name="btnClear" Content="Clear" Grid.Row="4" Grid.Column="3" HorizontalAlignment="Left" Margin="87,47,0,-55" Width="50" />
                        <Button x:Name="btnCancel" Content="Cancel" Grid.Row="4" Grid.Column="3" Margin="142,47,-2,-55" />

                        <Label Grid.Row="3" Grid.Column="0" Margin="0,9,109,14" Grid.RowSpan="2">Place Of Birth</Label>
                        <TextBox x:Name="txtPlaceOfBirth" Grid.Column="0" Grid.Row="3" Margin="80,9,10,13" Grid.RowSpan="2" />

                        <Label Grid.Row="3" Grid.Column="1" Margin="0,6,109,17" Grid.RowSpan="2">Address</Label>
                        <TextBox x:Name="txtAddress" TextWrapping="Wrap" ScrollViewer.VerticalScrollBarVisibility="Auto" AcceptsReturn="True" Grid.Column="1" Grid.Row="3" Margin="56,11,4,-3" Grid.ColumnSpan="2" Grid.RowSpan="2"/>

                        <Label Grid.Row="4" Grid.Column="0" Margin="0,17,123,-19" >Post Code</Label>
                        <TextBox x:Name="txtPostCode" Grid.Column="0" Grid.Row="4" Margin="80,18,10,-23" />

                        <Label Grid.Row="4" Grid.Column="0" Margin="0,50,123,-52" >Nationality</Label>
                        <TextBox x:Name="txtNationality" Grid.Column="0" Grid.Row="4" Margin="80,51,10,-53"  />

                        <Label Grid.Row="4" Grid.Column="1" Margin="1,50,90,-52" >Agreement Date</Label>
                        <DatePicker x:Name="txtAgreementDate" Grid.Column="1" Grid.Row="4" Margin="99,51,169,-53" Grid.ColumnSpan="2"  SelectedDateFormat="Short" Width="112" />

                        <Label Grid.Row="4" Grid.Column="2" Margin="29,29,88,-31" >SM Name</Label>
                        <ComboBox Margin="127,29,183,-31" Grid.Column="2" Grid.Row="4" x:Name="cbSMName" Grid.ColumnSpan="2">
                            <ComboBoxItem Content="Select" IsSelected="True"></ComboBoxItem>
                        </ComboBox>

                        <Label Grid.Row="4" Grid.Column="2" Margin="29,61,67,-63" >Promoter Name</Label>
                        <ComboBox Margin="127,61,183,-63" Grid.Column="2" Grid.Row="4" x:Name="cbSPromoter" Grid.ColumnSpan="2">
                            <ComboBoxItem Content="Select" IsSelected="True"></ComboBoxItem>
                        </ComboBox>
                    </Grid>
                </GroupBox>

                <GroupBox Height="180" Header="Other Information" Margin="0,392,-2,-315" Grid.Row="3" >
                    <Grid>
                        <Grid.ColumnDefinitions>
                            <ColumnDefinition Width="0.25*"></ColumnDefinition>
                            <ColumnDefinition Width="0.25*"></ColumnDefinition>
                            <ColumnDefinition Width="0.25*"></ColumnDefinition>
                            <ColumnDefinition Width="0.25*"></ColumnDefinition>
                        </Grid.ColumnDefinitions>
                        <Grid.RowDefinitions>
                            <RowDefinition/>
                            <RowDefinition/>
                            <RowDefinition/>
                            <RowDefinition/>
                        </Grid.RowDefinitions>
                        <Label Grid.Column="0" Margin="0,5,161,4" Grid.Row="0" Content="Credit Card No." />
                        <TextBox HorizontalAlignment="Left" Grid.Row="0" Grid.Column="0" Height="26" TextWrapping="Wrap" VerticalAlignment="Top" Width="154" Margin="96,5,0,0"/>

                        <Label Grid.Column="1" Margin="0,-2,435,7" Grid.Row="0" Content="Expiry Date" />
                        <DatePicker x:Name="txtExpDate" Grid.Column="1" Margin="126,0,263,5"  SelectedDateFormat="Short" />

                        <Label Grid.Column="1" Margin="324,-4,55,14" Grid.Row="0" Content="Passport Reader" />
                        <TextBox x:Name="txtPassportReader" Width="200" Grid.Column="1" Grid.Row="0" Grid.RowSpan="2"  TextWrapping="Wrap" ScrollViewer.VerticalScrollBarVisibility="Auto" AcceptsReturn="True" Margin="295,21,15,11" />

                        <Label Margin="0,6,190,4" Content="E-Mail ID" Grid.Row="1" />
                        <TextBox HorizontalAlignment="Left" Grid.Column="0" Height="26" TextWrapping="Wrap" VerticalAlignment="Top" Width="154" Margin="96,5,0,0" Grid.Row="1"/>

                        <Label Margin="0,0,384,8" Content="Contact (Mandatory)" Grid.Column="1" Grid.Row="1" />
                        <TextBox HorizontalAlignment="Left" Grid.Column="1" Height="26" TextWrapping="Wrap" VerticalAlignment="Top" Width="154" Margin="124,2,0,0" Grid.Row="1"/>

                        <Label Margin="0,4,170,5" Content="Visa No." Grid.Row="2" />
                        <TextBox HorizontalAlignment="Left" Height="26" TextWrapping="Wrap" VerticalAlignment="Top" Width="154" Margin="96,3,0,0" Grid.Row="2"/>

                        <Label Margin="2,32,412,14" Content="Phone" Grid.Row="1" Grid.Column="1" Grid.RowSpan="2" />
                        <TextBox HorizontalAlignment="Left" Height="26" TextWrapping="Wrap" VerticalAlignment="Top" Width="154" Margin="123,32,0,0" Grid.Row="1" Grid.Column="1" Grid.RowSpan="2"/>

                        <Label Margin="280,25,134,0" VerticalAlignment="Top" Content="Company Name" Grid.Row="1" Grid.Column="1" Grid.RowSpan="2" />
                        <TextBox HorizontalAlignment="Left" Height="26" TextWrapping="Wrap" VerticalAlignment="Top" Width="131" Margin="378,26,0,0" Grid.Row="1" Grid.Column="1" Grid.RowSpan="2"/>

                        <Label Margin="-1,4,164,0" VerticalAlignment="Top" Content="Designation" Grid.Row="3" />
                        <TextBox Name="txtDesignation" HorizontalAlignment="Left" Height="26" TextWrapping="Wrap" VerticalAlignment="Top" Width="153" Margin="96,4,0,0" Grid.Row="3" Grid.Column="0"/>

                        <Label Margin="4,33,410,0" VerticalAlignment="Top" Content="Remarks" Grid.Row="2" Grid.Column="1" Grid.RowSpan="2" />
                        <TextBox x:Name="txtRemarks" Width="200" Grid.Column="1" Grid.Row="2" Grid.RowSpan="2"  TextWrapping="Wrap" ScrollViewer.VerticalScrollBarVisibility="Auto" AcceptsReturn="True" Margin="123,26,187,5" />
                    </Grid>
                </GroupBox>
                <GroupBox Header="Visa Type" Width="995" Margin="0,574,-2,-387" Grid.Row="3">
                    <Grid>
                        <Grid.RowDefinitions>
                            <RowDefinition></RowDefinition>
                        </Grid.RowDefinitions>
                        <Grid.ColumnDefinitions>
                            <ColumnDefinition Width="8*"></ColumnDefinition>
                            <ColumnDefinition Width="50*"></ColumnDefinition>
                        </Grid.ColumnDefinitions>

                        <RadioButton GroupName="grpVisaType" Grid.Column="0" Content="Work Visa"></RadioButton>
                        <RadioButton GroupName="grpVisaType" Grid.Column="1" Content="Other Visa"></RadioButton>
                    </Grid>

                </GroupBox>
            </Grid>

            <Button x:Name="btnSave" Style="{StaticResource AccentedSquareButtonStyle}" Height="34" Width="70" Canvas.Bottom="11" Canvas.Left="396" Canvas.Top="841"
                    Content="Save" VerticalAlignment="Bottom" Click="btnSave_Click_1" HorizontalAlignment="Center">
            </Button>

            <Button Name="btnCancelMain" Height="34" Width="80" Canvas.Bottom="11" Style="{StaticResource AccentedSquareButtonStyle}" Canvas.Left="470" Canvas.Top="841"
                    Content="Cancel" VerticalAlignment="Bottom" HorizontalAlignment="Center" Click="btnCancelMain_Click">
            </Button>

            



            

            <Controls:FlyoutsControl>
                <Controls:Flyout Header="Actions" Name="TestFlyout" VerticalAlignment="Bottom" Position="Top" Width="990" Theme="Adapt">
                    <Grid>
                        <Grid.ColumnDefinitions>
                            <ColumnDefinition Width="20*"></ColumnDefinition>
                            <ColumnDefinition Width="20*"></ColumnDefinition>
                        </Grid.ColumnDefinitions>
                        <Button Content="Save" Width="70" Height="30" HorizontalAlignment="Left" Grid.Column="0"></Button>
                        <Button Content="Cancel" Width="70" Height="30" HorizontalAlignment="Left" Grid.Column="1"></Button>
                    </Grid>
                </Controls:Flyout>
            </Controls:FlyoutsControl>
        </Canvas>

    </ScrollViewer>
</Page>

**Comment by punker76** [comment]
@Nadeem1989 put your flyout over the scrolviewer

```xaml
<Grid>
    <ScrollViewer Name="scrlMain" CanContentScroll="True" HorizontalScrollBarVisibility="Auto" VerticalScrollBarVisibility="Auto" VerticalAlignment="Stretch">

    </ScrollViewer>

    <Controls:FlyoutsControl>
        <Controls:Flyout Header="Actions" Name="TestFlyout" VerticalAlignment="Bottom" Position="Top" Width="990" Theme="Adapt">
            <Grid>
                <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="20*"></ColumnDefinition>
                    <ColumnDefinition Width="20*"></ColumnDefinition>
                </Grid.ColumnDefinitions>
                <Button Content="Save" Width="70" Height="30" HorizontalAlignment="Left" Grid.Column="0"></Button>
                <Button Content="Cancel" Width="70" Height="30" HorizontalAlignment="Left" Grid.Column="1"></Button>
            </Grid>
        </Controls:Flyout>
    </Controls:FlyoutsControl>

</Grid>
```

**Comment by Nadeem1989** [comment]
Thanks Alot Sir
