### ISSUE TITLE
Size of MahApps Dialog background..

### ISSUE THREAD

**Issue by KlioHome** [MahApps/MahApps.Metro#2109]
Hi! Can you help me?
Here is a regular MahApps Dialog.
![1](https://cloud.githubusercontent.com/assets/13899351/9682928/dd745f6a-5313-11e5-80c0-ca953c745750.png)
I wonder whether you can make the dialog did not close the title?
Somthing like this...
![2](https://cloud.githubusercontent.com/assets/13899351/9682933/e1ff1656-5313-11e5-8784-a2fbab439513.png)
Thank oyu for your help!

**Comment by AndreasSchmid1** [comment]
any news on this issue?

**Comment by smedasn** [comment]
I also need this feature because I want to close the application during a dialog. If this is does not find a way into a stable build. Is there a workaround how to achieve it? Thank you in advance
