### ISSUE TITLE
Expander in DataGrid shows VerticalScrollBar

### ISSUE THREAD

**Issue by alexiej** [MahApps/MahApps.Metro#2113]
Hi,

I have below DataGrid with Expander.

```xaml
<DataGrid.GroupStyle>
    <GroupStyle>
        <GroupStyle.HeaderTemplate>
            <DataTemplate>
                <StackPanel>
                    <TextBlock FontWeight="Bold" Text="{Binding Name}"/>
                </StackPanel>
            </DataTemplate>
        </GroupStyle.HeaderTemplate>
        <GroupStyle.ContainerStyle>
            <Style TargetType="{x:Type GroupItem}">
                <Setter Property="Template">
                    <Setter.Value>
                        <ControlTemplate TargetType="{x:Type GroupItem}">
                            <Expander IsExpanded="True">
                                <Expander.Header>
                                    <StackPanel Orientation="Horizontal">
                                        <TextBlock FontWeight="Bold" Text="{Binding Name}"/>
                                    </StackPanel>
                                </Expander.Header>
                                <ItemsPresenter/>
                            </Expander>
                        </ControlTemplate>
                    </Setter.Value>
                </Setter>
            </Style>
        </GroupStyle.ContainerStyle>
    </GroupStyle>
</DataGrid.GroupStyle>
```

And Columns with dataGrid with one column with width="*".

```xaml
<DataGridTemplateColumn Width="*"/>
```

In this situation this should take left space.
This works fine without expander. But with epxander it always set size for the column too wide. I need to manualy change size for each column in DataGrid. 

![2015-09-04_19-09-30](https://cloud.githubusercontent.com/assets/12593751/9689819/dd203e7e-5338-11e5-98a6-9ef4a98e07e0.png)

Is it possibility to change size for the column autamitcly including Expander.

**Comment by punker76** [comment]
@alexiej possible you must change the margin of the expander...

**Comment by punker76** [comment]
@alexiej any news for this?

**Comment by robkite** [comment]
I'm having the exact issue described here. I found that I can get the correct width if I set the Expander border and padding to 0 (as below), but this does remove part of the styling I want.

`<Expander IsExpanded="True" BorderThickness="0" Padding="0">`

 Any ideas on how I can keep the border and padding without the expander causes the datagrid to overflow?
