### ISSUE TITLE
ProgressDialog not showing when not using Task.Delay()

### ISSUE THREAD

**Issue by fubar-coder** [MahApps/MahApps.Metro#2115]
It seems that the ```ProgressDialog``` doesn't show up when ```Task.Delay(1)``` isn't used. The window gets dark, but the message (and the progress bar) doesn't show up (or update) when no ```Task.Delay(1)``` isn't used.

You can easily replicate this behavior, when you replace all ```Task.Delay``` with ```Thread.Sleep``` in the demo application in ```MainWindow.ShowProgressDialog```.

**Comment by thoemmi** [comment]
Calling `Thread.Sleep` blocks the UI thread. Of course the progress dialog can't update, as any other UI component as well.
