### ISSUE TITLE
TreeView style when using HierarchicalDataTemplate

### ISSUE THREAD

**Issue by spirosi** [MahApps/MahApps.Metro#2117]
I can't get default MetroTreeView style when im using HierarchicalDataTemplate. Im receivind frames with same color as selected item and with length of the longest item.
<Grid.ColumnDefinitions>
            <ColumnDefinition Width="199*"/>
            <ColumnDefinition Width="244*"/>
        </Grid.ColumnDefinitions>
        
        <TreeView BorderBrush="{StaticResource AccentColorBrush}" BorderThickness="1" Grid.Column="0" Margin="0,0,10,0">
            <TreeView ItemsSource="{Binding Countries}">
                    <TreeView.ItemContainerStyle>
                        <Style BasedOn="{StaticResource MetroTreeViewItem}" TargetType="{x:Type TreeViewItem}">
                            <Setter Property="IsExpanded" Value="{Binding IsExpanded, Mode=TwoWay}" />
                            <Setter Property="IsSelected" Value="{Binding IsSelected, Mode=TwoWay}" />
                        </Style>
                    </TreeView.ItemContainerStyle>

                <TreeView.Resources>
                    <HierarchicalDataTemplate DataType="{x:Type viewModel:CountryViewModel}" ItemsSource="{Binding Children}">
                            <TextBlock Text="{Binding CountryName}" />
                    </HierarchicalDataTemplate>

                    <DataTemplate DataType="{x:Type viewModel:CityViewModel}">
                            <TextBlock Text="{Binding CityName}" />
                    </DataTemplate>
                </TreeView.Resources>
            </TreeView>
        </TreeView>
        
        <TreeView BorderThickness="1" BorderBrush="{StaticResource AccentColorBrush}" Grid.Column="1" Margin="10,0,0,0">
            <TreeViewItem Header="Item 1">
                <TreeViewItem Header="Item 1.1">
                    <TreeViewItem Header="Item 1.1.1" />
                    <TreeViewItem Header="Item 1.1.2" />
                </TreeViewItem>
                <TreeViewItem Header="Item 1.2" />
                <TreeViewItem Header="Item 1.3" />
            </TreeViewItem>
            <TreeViewItem Header="Item 22" />
            <TreeViewItem Header="Item 3">
                <TreeViewItem Header="Item 3.1">
                    <TreeViewItem Header="Item 3.1.1" />
                    <TreeViewItem Header="Item 3.1.2" />
                </TreeViewItem>
                <TreeViewItem Header="Item 3.2" />
                <TreeViewItem Header="Item 3.3" />
            </TreeViewItem>
        </TreeView>

![1](https://cloud.githubusercontent.com/assets/8955003/9730411/68e2c1de-5627-11e5-9812-bcd03d3ae877.jpg)

**Comment by punker76** [comment]
@spirosi what version of MahApps are you using?

**Comment by spirosi** [comment]
I'm using 1.1.2.0

**Comment by punker76** [comment]
@spirosi can you try the latest alpha? so maybe this is solved their.

**Comment by spirosi** [comment]
Almost solved. 
![2](https://cloud.githubusercontent.com/assets/8955003/9730966/2c8317b2-562b-11e5-9279-02cebc38b943.jpg)

**Comment by punker76** [comment]
@spirosi :+1:
