### ISSUE TITLE
Glow border is missing the corners

### ISSUE THREAD

**Issue by tgjones** [MahApps/MahApps.Metro#2118]
It's a little bit subtle, but you can see in this screenshot that there's no glow border at the corner (and the same is true for the other 3 corners). Is that as-designed, or a bug? It looks pretty odd, and isn't what the "standard" Windows glow looks like.

![mahapps-glow](https://cloud.githubusercontent.com/assets/102049/9731991/076aa1c0-5653-11e5-9212-fba501518f3e.png)

**Comment by punker76** [comment]
@tgjones it's now as-designed, maybe changed in 2.x.x

**Comment by tgjones** [comment]
@punker76 Okay, thanks. I'm guessing there were good technical reasons for the change (in 1.0.0 it used the standard Windows glow / shadow, right?) Looking through the issues list here, I notice a number related to this area, but I couldn't find one detailing why the change was made.
