### ISSUE TITLE
Showing a dialog throws NullReferenceException (but not in latest source)

### ISSUE THREAD

**Issue by ThomasWeiss** [MahApps/MahApps.Metro#2119]
I'm trying to display dialogs from my `MetroWindow` class:
```
await this.ShowMessageAsync("Connection", "Connecting to database...");
```
but this throws a `NullReferenceException`.

So I downloaded the source and referenced the project in order to step into the call and see where the NRE is thrown but... it works fine from the source. So I guess that there was some issue that got recently fixed, which leads me to the question: is there a new release scheduled soon?

Thanks

**Comment by punker76** [comment]
@ThomasWeiss you can download the pre nuget version which is the latest source. it should be work like a stable version ;-P
