### ISSUE TITLE
PasswordBoxHelper enhancement to support Password binding

### ISSUE THREAD

**Issue by gigios** [MahApps/MahApps.Metro#2120]
One big problem of the PasswordBox control is that it is not possible to bind directly the Password property.
My suggestion is to enhance the PasswordBoxHelper with an additional property 'Password' (for example) that allow to bind a ViewModel property directly to the Password property of the control.

**Comment by thoemmi** [comment]
There's already `PasswordBoxBindingBehavior`. See its usage in the [`LoginDialog`](https://github.com/MahApps/MahApps.Metro/blob/master/MahApps.Metro/Themes/Dialogs/LoginDialog.xaml#L34).

**Comment by gigios** [comment]
Sorry :(
I have checked only the PasswordBoxHelper and PasswordBox styles withoud check the examples.

Thanks for the answer.

**Comment by thoemmi** [comment]
You're welcome :relaxed:

**Comment by GreatFireWall** [comment]
Can you renew the link? It's dead..
