### ISSUE TITLE
Window is flickering while resizing

### ISSUE THREAD

**Issue by valentinhuber** [MahApps/MahApps.Metro#2121]
![resizebug](https://cloud.githubusercontent.com/assets/11440294/9764069/36f2ab08-570d-11e5-8fd6-211c132e12a1.gif)

It seems that there is a resize issue at the MetroWindow. When the window is resized at the left side, the right edge flickers. The same issue appears on the top edge, in that case the bottom edge flickers.
However, resizing from the bottom and the right edge works perfectly fine.

**Comment by punker76** [comment]
@valentinhuber which version of MahApps? this should be better in the latest alpha.

**Comment by valentinhuber** [comment]
Version 1.1.2.
Thanks for your reply, I'm going to test it later on and will provide you with feedback.

**Comment by valentinhuber** [comment]
![resizebug](https://cloud.githubusercontent.com/assets/11440294/9787168/8dedbeda-57c0-11e5-9229-768021dd7b95.gif)

Tried the latest alpha (Version 1.1.3-ALPHA 170), you were right, it looks much better now, even though the flickering is not gone yet.

**Comment by punker76** [comment]
@valentinhuber it's not possible to fix this completely. if you compare with a normal window, then you can see that the inner content also flickers. so out content flickers too, but a little bit better.

**Comment by bigworld12** [comment]
Would also point that top left is the measure point for all content so it's
normal to flicker when changing this point

**Comment by QuantumDeveloper** [comment]
When you resize window, the whole device with swapchain must be recteated (this is relevant for DX 9, on which WPF is working) So, recteating device + swapchain causing this small flickering effect.
