### ISSUE TITLE
Use behavior/attached property to control window dragging

### ISSUE THREAD

**Issue by luciusli** [MahApps/MahApps.Metro#2122]
I have a `MetroWindow` with custom title bar by setting `ShowTitleBar="False"` and `IsWindowDraggle="False"`, but I also want this custom title bar to be draggable. It would be nice if there is a helper behavior that once attached, mouse down on the associated object would start dragging the window as this approach is more flexible and reusable. What do you think?

**Comment by punker76** [comment]
@luciusli Setting `IsWindowDraggle="False"` and `also want this custom title bar to be draggable` makes no sense... I would suggest if you want this then you should implement it by yourself.
but after #2226 it should be possible what you want if you leave `IsWindowDraggle` to true and set your custom title bar to `TitleBarHeight`...
