### ISSUE TITLE
Maximize MetroWindow crash 

### ISSUE THREAD

**Issue by MasoudRahmani** [MahApps/MahApps.Metro#2123]
Hello.

When i set `FlowDirection = "RightToLeft"` and try to *maximize window* it breaks apart

```Xaml
<Controls:MetroWindow 
    x:Class="DBMain.myShell" 
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" 
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" 
    ResizeMode="CanResizeWithGrip" 
    Language="fa-IR" 
    FlowDirection="RightToLeft" 
    xmlns:prism="http://www.codeplex.com/prism" 
    xmlns:Controls="http://metro.mahapps.com/winfx/xaml/controls">
```

![untitled](https://cloud.githubusercontent.com/assets/5321268/9813542/9c687d7a-589b-11e5-8f1e-e027abe65edb.jpg)

![untitled1](https://cloud.githubusercontent.com/assets/5321268/9813550/bc9a8692-589b-11e5-80fc-2999b1a145a7.jpg)

**Spec**
* .Net 4.0 Full
* Mahapps.Metro 1.1.2.0

Thanks for Great Project . i hope it gets fixed.

**Comment by punker76** [comment]
@MasoudRahmani this should already be fixed in the latest alpha (also available on nuget)

**Comment by MasoudRahmani** [comment]
oh Thanks.
it was bugging me for several days ,i couldn't find a search result .
Great work .

just a question , is the alpha 1.1.3-ALPHA170 good enough to use on a enterprise application ?
or should i use the one before and use a workaround for the problem ?

**Comment by punker76** [comment]
@MasoudRahmani the latest alpha should be usable as is....

**Comment by MasoudRahmani** [comment]
thanks
