### ISSUE TITLE
release demo application with every new build

### ISSUE THREAD

**Issue by ErdnussFlipS** [MahApps/MahApps.Metro#2125]
use appveyor for auto deployment to github

**Comment by ErdnussFlipS** [comment]
why closed?

**Comment by punker76** [comment]
where should appveyor put the executable?

**Comment by ErdnussFlipS** [comment]
As asset for the release. See in my repo https://github.com/ErdnussFlipS/WindowsFirewallDashboard/blob/dev/appveyor.yml#L110 the artifacts section and deploy section.

**Comment by punker76** [comment]
ok, i will take a look after i get the appveyor config and the v1.2.0 is released

**Comment by thoemmi** [comment]
@ErdnussFlipS What would be the benefit? I don't think it's worth to upload a sample app for every CI build. The screenshots (esp the animated gif @punker76 added a few weeks ago) give a very good first impression, and those who want to have a closer look will download the sources or clone the repository. I guess there's only a handful of people who will download a sample app.

**Comment by ErdnussFlipS** [comment]
@thoemmi it could also be only on release builds (should be better, you are right), not on every single commit.
Those who want to use this library, like me, use nuget for dependency management and don't want to clone the repo and make an own build. So I think.

And it's not the world to add an command to appveyor build config.

@punker76 I'd like to do it for you and do a pull request but you don't use a appveyor.yml until now, so I can't do this. But you can also configure that in appveyor's configuration gui.

**Comment by punker76** [comment]
I'll add demo on release page for 1.3.0
