### ISSUE TITLE
[Suggestion] Add the possibility to set an empty header in the GroupBox

### ISSUE THREAD

**Issue by gigios** [MahApps/MahApps.Metro#2128]
I know that it is very easy to use a Border with the AccentColor to simulate my suggestion but if in future the GroupBox style change I need to replicate these changes also in my border style (ok, it is a small problem :)).
My sugestion is to add, in the trigger section of the style, the following lines, in this way the 'Header' border where normally there is the 'header' content, could be 'collapsed'.

                        <Trigger Property="Header" Value="">
                            <Setter TargetName="HeaderSite" Property="Visibility" Value="Collapsed" />
                        </Trigger>
                        <Trigger Property="Header" Value="{x:Null}">
                            <Setter TargetName="HeaderSite" Property="Visibility" Value="Collapsed" />
                        </Trigger>

With this change it is possible to create a border without the 'Header' part but with the same style of the normal GroupBox.

If this is not a good idea can you suggest me how create a style based on the default MetroGroupBox and add additional triggers?

EDIT: I have tried to change the last style and now I need to set the Height property to 1 instead the Visibility (related the HeaderSite border object).

**Comment by punker76** [comment]
@gigios I think using a `Border` is simple enought, why do you need a special thing with `GroupBox`?

**Comment by gigios** [comment]
Yes, it's true, with the border is more easy but if I change the style of the border I need to rewrite also the style of the border used as a groupbox to have the same style. This was the reason :)
