### ISSUE TITLE
TabItem header size and default style for TextBlock

### ISSUE THREAD

**Issue by Evangelink** [MahApps/MahApps.Metro#2129]
Hi all,

I am having a weird behavior with the ControlsHelper.HeaderFontSize attached property and a default style and I was wondering if one of you would have any idea on how to fix it.

I have a WPF application with a default style for the textblock (mainly to set the size) that is merged into the app.xaml. On my window I have a TabControl (same problem with MetroTabControl and MetroAnimatedTabControl) where I want to specify the size of my header. Doing so everything is good on the designer but when running the app, the tabcontrol headers are using the size of my default textblock style.

For an easy test, you can past the following lines into the App.xaml of the MetroDemo.NET45 project and then run the demo (the last example, the one with the close button is supposed to have different sizes)
```xaml
<Style TargetType="{x:Type TextBlock}" x:Key="BodyTextBlockStyle">
    <Setter Property="FontSize" Value="15" />
</Style>
<Style TargetType="{x:Type TextBlock}" BasedOn="{StaticResource BodyTextBlockStyle}" />
```

Thank you

**Comment by punker76** [comment]
@Evangelink there are also something other issues with global TextBlock styles, so it's not recommend to have a global TextBlock style.

```xaml
<!-- never ever make a default style for TextBlock in App.xaml !!!  -->
```

**Comment by Evangelink** [comment]
@punker76 Thank you for your feedback, I should have paid attention to that comment...
Is there a problem merging for Labels and TextBox?

I had a look to the other related issues and haven't found any recommendation about how to change the default font family and font size? Do you merge the style in every views? Do you define font name and font size with the same name as mahApps ones so the DynamicResource will pick up my style? Do you always explicitly write the style? Is there a better way?

Thank you.

**Comment by thoemmi** [comment]
If you want to have the same font size for all controls and you're using MahApps.Metro, you're able to override them. See [**Fonts.xaml**](https://github.com/MahApps/MahApps.Metro/blob/master/MahApps.Metro/Styles/Fonts.xaml) for reference.
