### ISSUE TITLE
Child Window Minimize Event Minimizes Owner Window Two

### ISSUE THREAD

**Issue by ueoueoueo** [MahApps/MahApps.Metro#2130]
* With normal WPF windows,
Main Window creates a new Window and shows it with ShowDialog(). When the dialog window is minimized, Main Window stays in Normal state.

* With Metro Window,
Main MetroWindow creates a new MetroWindow and shows it with ShowDialog(). When the dialog window is minimized, Main MetroWindow is minimized too.

**Comment by punker76** [comment]
@ueoueoueo Which MahApps version? Have you tried the latest alpha?

**Comment by ueoueoueo** [comment]
Hi, I've used the version 1.1.3.174.

**Comment by punker76** [comment]
@ueoueoueo here is my example with this notice `ShowDialog(); // Minimizing a modal window will also minimize its parent.`

```csharp
private void btnModal_Click(object sender, RoutedEventArgs e)
{
    Window win = new Window();
    win.Title = "Modal child - " + DateTime.Now.ToLongTimeString();
    win.ShowDialog(); // Minimizing a modal window will also minimize its parent.
}

private void btnModeless_Click(object sender, RoutedEventArgs e)
{
    Window win = new Window();
    win.Title = "Modeless window - " + DateTime.Now.ToLongTimeString();
    win.Show();
}
```

**Comment by punker76** [comment]
@ueoueoueo so i doesn't see a bug with MahApps

**Comment by ueoueoueo** [comment]
Oh, I made the same test but I can see now that I've missed something. Sorry for that and thanks for your support.
