### ISSUE TITLE
Unable to cast object of type 'Microsoft.VisualStudio.DesignTools.Markup.DocumentModel.DocumentCompositeNode' to type 'System.Windows.Style'.

### ISSUE THREAD

**Issue by aryaei** [MahApps/MahApps.Metro#2132]
i am using latest mahapps.metro in my project and when i add a list box to my window it throws this exception in my designer. when i run project it works just fine but designer doesn't work anymore.

i think it's a problem with mahapps metro styles dictionery which causes this.also i have put resource dictionery in app.xaml as mentioned in tutorial.

**Comment by punker76** [comment]
@aryaei i don't think this is MahApps related problem. https://connect.microsoft.com/VisualStudio/feedback/details/772730/xaml-designer-broken-when-adding-resource-dictionaries-to-data-or-control-templates It seems VS has some problem with resource dictionaries.

**Comment by aryaei** [comment]
The topic u mentioned is from 2012 and i think since then they should have fixed it.it's a crippling bug and makes it impossible to develop app.there should be a workaround for it.

**Comment by punker76** [comment]
...I won't fix Visual Studio bugs...

**Comment by thoemmi** [comment]
Not to mention that the reported bug in Connect has the status "Closed, won't fix"...

**Comment by aryaei** [comment]
changed target framework from 4.5.2 to 4.5 and reinstalled mahapps metro from nuget and it's solved...thanks anyay

**Comment by ye4241** [comment]
same problem came, and i sloved by reinstalling mahapps metro from nuget rather than adding reference of the project.
