### ISSUE TITLE
Not an Issue, just a feed back!

### ISSUE THREAD

**Issue by JacBal** [MahApps/MahApps.Metro#2133]
All lot of great work have been done since version 1.1.2.
One of my desktop app, originally built with version 1.1.3 ALPHA 143, is used by 3 persons on different OS (W10, W8.1 .net 4.6, W7 .net 4.6). 
Build with VS 2015 and targeting .Net 4.6, this touch enabled app intensively make use of dynamic Flyouts, custom Dialogs, NumericUpDown ..., plus EF6, System.Data.Sqlite and my own MVVM layer.
I keep upgrading the users with a newest version every 2 new alpha release of MahApps. 

**So far the users have not reported any problems due to the interface** (which is not the case with my coding part :) ).
  
**Even more**: the W10 computer is an ASUS Transformer Book T100 Chi, a tablet equipped with a full HD 10" screen and powered by a small (but impressive) Intel® Bay Trail Quad Core Z3775.
With such small specifications the interface is still **working fluently and reactively**, which emphasizes the quality of the job that you guys have done with MahApps.

To conclude : **Well done guys and many thanks from a happy user of your library!**
Jacques

PS: One of the coolest thing with W10 on a tablet : when the OS is switched to tablet mode the keyboard pops-up automatically as soon as the user touch an input field (does not happen if a keyboard is connected). WPF allows you to specify the initial layout of the keyboard (standard, number, email, ...) by setting the InputScope property on each input controls (textbox, numericupdows, ...).

**Comment by thoemmi** [comment]
Thanks @JacBal, your feedback is very much appreciated :blush:

**Comment by punker76** [comment]
Thanks @JacBal !

\cc @Amrykid @shiftkey @flagbug 

![leo-toast](https://cloud.githubusercontent.com/assets/658431/9905259/40c3418e-5c84-11e5-8cc2-f672b0932498.gif)

![gazelle-popcorn](https://cloud.githubusercontent.com/assets/658431/9905264/454c8c74-5c84-11e5-8107-40291417e729.gif)

**Comment by JacBal** [comment]
I love the Gerenuk :). 
Also love the Internet that allowed me to find out that it was not a 'hear-tattooed hornless deer' but the tallest of the antelope also know as giraffe-necked antelope : https://en.wikipedia.org/wiki/Gerenuk
After more than 20 years of using it, the Internet keep blowing my mind !
