### ISSUE TITLE
Cannot await in the body of a catch caluse

### ISSUE THREAD

**Issue by itechy21** [MahApps/MahApps.Metro#2135]
So there is no way the default `await this.ShowMessageAsync("Error!", "Message" + ex.Message);` code can be used in a catch clause. Is there a way around this?

**Comment by bigworld12** [comment]
Try using dispatcher.invoke and put the code inside it

**Comment by jyrka98** [comment]
It's possible with C# 6.
If you can't use it then you can try do something like this: http://stackoverflow.com/a/8869589/3515415

**Comment by itechy21** [comment]
Thanks for the link with a code example I'll report back later...
