### ISSUE TITLE
Right-to-Left Dialogs - Poisition of controls and text flow direction 

### ISSUE THREAD

**Issue by zazkapulsk** [MahApps/MahApps.Metro#2137]
Hi

Is there a way to set all the suit of MahApps dialogs to RTL?
Thanks

**Comment by punker76** [comment]
@zazkapulsk set window property `FlowDirection="RightToLeft"`

**Comment by zazkapulsk** [comment]
Hi @punker76 
I am assuming you are referring to the window in the call "this". I don't want to set the entire windows to RTL, since MahApps windows acts weird in RTL.
Is there a way to just set the dialogue to RTL?
Thanks

**Comment by punker76** [comment]
@zazkapulsk "...MahApps windows acts weird in RTL." this is fixed in latest alpha version. to set dialog only you must create your own dialog style and override the default one.

**Comment by zazkapulsk** [comment]
@punker76  - Thanks. Got it.
I'd appreciate a link to the said alpha version. I am downloading and installing MahApps in offline via NuGet.

**Comment by punker76** [comment]
@zazkapulsk in pm console `Install-Package MahApps.Metro -Pre` from [nuget](https://www.nuget.org/packages/MahApps.Metro/1.1.3-ALPHA174)

**Comment by zazkapulsk** [comment]
Thanks!
