### ISSUE TITLE
DynamicResource error occurs on multithread UI

### ISSUE THREAD

**Issue by llinyu** [MahApps/MahApps.Metro#2138]
I create a SplashWindow on seperate thread, and create a MainWindow on another thread. 

SplashWindow has a ProgressBar and MainWindow has a MetroButton style Button,
error occurs on startup.

* If only MainWindow, no error.
* If remove ProgressBar or set its style to null in SplashWindow.xaml file, no error.
* If TextBoxBorderBrush to static resource in Colors.xaml file, no error.
`
    <SolidColorBrush x:Key="TextBoxBorderBrush" Color="{StaticResource Gray6}"/>
`
* If BorderBrush to Gray6 in Controls.Button.xaml file, no error.
`
    <Setter Property="BorderBrush" Value="{DynamicResource Gray6}"/>
`

Does dual DynamicResource reference cause this error?
Controls.Button.xaml
`
    <Setter Property="BorderBrush" Value="{DynamicResource TextBoxBorderBrush}"/>
`
Colors.xaml
`
    <SolidColorBrush x:Key="TextBoxBorderBrush" Color="{DynamicResource Gray6}"/>
`
 

ToggleButton is the same, because of `<Setter Property="BorderBrush" Value="{DynamicResource TextBoxBorderBrush}"/> `setting.

demo on  https://github.com/llinyu/MahAppsDemo

**Comment by punker76** [comment]
@llinyu It's necessary to add the MahApps resources to each window itself to work with multi threads correctly.
