### ISSUE TITLE
Change link colour of button in Left/Right WindowCommands

### ISSUE THREAD

**Issue by xlyashuk** [MahApps/MahApps.Metro#2140]
Hi,

I want to change link button color in WindowCommands, but I don't want to disable the title bar (as suggested in docs).
My title bar background color is white and link color is also white, so it's not seen. 
Is there any way to change the color, maybe even in library sources?

From documentation:
The foreground (link) colour of (Left-/Right-) WindowCommands will always be white, unless the titlebar is disabled, in which case it will be the reverse of whatever theme you have selected. For example, using the White/Light theme, the foreground colour will be black.
![05_windowcommands](https://cloud.githubusercontent.com/assets/14789223/10022822/7e17be66-6157-11e5-8ffb-bf67dfd68af2.png)
I want to make 'settings' label black for example.

**Comment by tkzaum10** [comment]
Hi xlyashuk, actually you can setup your windowCommands the way you like. Punker releases a prism/mahapps application that you can rely to get your problems solved.

Check this,
https://github.com/steve600/PrismMahAppsSample

tkzaum10

**Comment by punker76** [comment]
@tkzaum10 the samples are from @steve600
@xlyashuk the `WindowCommands` now easier to change, take a look in to https://github.com/MahApps/MahApps.Metro/blob/master/MahApps.Metro/Themes/WindowCommands.xaml#L178-L183 (documentation will be changed soon)
