### ISSUE TITLE
DialogCoordinator doesn't pass DataContext

### ISSUE THREAD

**Issue by pikaupet** [MahApps/MahApps.Metro#2145]
Hey guys,

ran into this problem with DialogCoordinator. When I try to show a dialog from my PatientVM view-model the provided DataContext is not available for the dialog's content
```C#
AddWeightDialog = new CustomDialog { Title = justATitle, Content = new AddWeight() };
await DialogCoordinator.Instance.ShowMetroDialogAsync(this,AddWeightDialog);
```
Using the code above, AddWeight doesn't have the passed PatientVM as DataContext, rather just the MainWindow's DataContext

```C#
AddWeightDialog = new CustomDialog { Title = justATitle, Content = new AddWeight { DataContext = this } };
await DialogCoordinator.Instance.ShowMetroDialogAsync(this,AddWeightDialog);
```
Assigning DataContext manually works as expected. Is there an issue with DialogCoordinator or is there a different meaning to the context parameter?

**Comment by punker76** [comment]
@pikaupet what is AddWeight in
```csharp
 AddWeightDialog = new CustomDialog { Title =justATitle, Content = new AddWeight() };
```
i think the DataContext in AddWeight has nothing to do with the DataContext of the Dialog itself
```csharp
AddWeightDialog = new CustomDialog { Title = justATitle, Content = new AddWeight { DataContext = this } };
```

**Comment by pikaupet** [comment]
Shouldn't the user control (AddWeight) inherit dialog's context? As it's dialog's content?
