### ISSUE TITLE
Manually invoke main window blurring

### ISSUE THREAD

**Issue by zazkapulsk** [MahApps/MahApps.Metro#2153]
I'm calling another MahApps window from the main MahApps window using ShowModal. I'd like to simulate the blurring/fading the calling window gets when one uses the built-in dialogs, like in http://mahapps.com/controls/dialogs.html.

Thanks!

**Comment by punker76** [comment]
@zazkapulsk you can call the overlay methods by yourself

```
public System.Threading.Tasks.Task ShowOverlayAsync()

public System.Threading.Tasks.Task HideOverlayAsync()
```

**Comment by zazkapulsk** [comment]
Great! Thanks!
What a fast support.
