### ISSUE TITLE
Metro window titlebar splitted in different parts

### ISSUE THREAD

**Issue by NeomMob** [MahApps/MahApps.Metro#2154]
Hello,

I am looking a way to get the titlebar of metrowindow splitted in different parts, aligned to the window content. Something like this

![s1](https://cloud.githubusercontent.com/assets/658431/14575072/cee1bc7a-035f-11e6-9ca0-921e7982aa8a.jpg)

(It is a mac app but the concept is there)

different panes from the title bar to the status bar. Any idea to achieve this?

**Comment by punker76** [comment]
@NeomMob Apossible solution can be to remove the default MahApps TitleBar and create all by yourself. You can reuse e.g. the WindowButtonCommands for the min/max/close stuff
