### ISSUE TITLE
GlowBrush Effect Layout Bug

### ISSUE THREAD

**Issue by yoyokits** [MahApps/MahApps.Metro#2157]
<img width="120" alt="mahappsbug" src="https://cloud.githubusercontent.com/assets/15078875/10418632/06bd349a-7061-11e5-9b99-335cb1502f07.png">

<controls:MetroWindow
    x:Class="MainWindow"
   ...
    BorderBrush="{DynamicResource AccentColorBrush}"
    BorderThickness="1"
    GlowBrush="{DynamicResource AccentColorBrush}"
 ...

I use Windows 10, .Net 4.5, MahApps.Metro 1.1.2.0, and Wpf Toolkit with AvalonDock 2.5.0.0.
As we can see in the attachment, if the Window is moved then there is some strange outline (border is moving about 1 pixel and makes background is drawn between border and Window). In this attachment, the 1 pixel gab is above Window.

**Comment by punker76** [comment]
@yoyokits you should test it with the latest alpha, cause this should be fixed.
