### ISSUE TITLE
Flyouts sometimes will not close

### ISSUE THREAD

**Issue by TravyDale** [MahApps/MahApps.Metro#2160]
I'm sorry in advance. I know it is never a fun issue when it happens randomly. I cannot narrow down what is causing this to happen. I will try my best to explain what's happening.

I have a flyout that has its IsOpen property bound to a boolean property in my ViewModel. My flyout let's the user enter in information to search my database. Once the user hits the button to search the database, I disable the controls in the flyout and show a MetroProgressBar inside of the flypout. Once all the data is pulled fine, I enable the controls,  hide the progressbar, and then set the property bound to IsOpen to False. Most of the time, this will close the flyout and everything is fine.

I am using this app on what I would call sub-par tablets. They just don't have a lot of CPU power so they can be kinda laggy. Anyway, maybe 1 out of 1000 times I do this action, the flyout is still visible, but the internal software thinks it is closed. In other words, the overlay of the main window is no longer there and when I click the arrow to close the flyout, it does nothing. It is basically drawn on the window but all the internal code (your DLL and my app) thinks it is closed.

If I were to force the IsOpen property to true in this situation, it would do the flyout animation and do what it is supposed to, but once I close the "new" flyout, the "old" flyout is still shown. It seems like some sort of drawing issue but I have no clue on how to fix it. 

Is anyone else running into this issue? Does anyone have a suggestion on how to resolve this?

When I get it to happen again, I will try to get some screenshots.

**Comment by punker76** [comment]
@TravyDale Which version are you using?

**Comment by TravyDale** [comment]
1.1.2.0

**Comment by TravyDale** [comment]
I will add this. I hope it helps.

I noticed that the process of the flyout closing is to remove the gray background from the window the flyout is covering. Then slide out of view. When my flyout freaks out, imagine that it removes the gray background but it doesn't slide out of view. It will look exactly like that. I am just unable to close the flyout in this situation.

**Comment by punker76** [comment]
@TravyDale Can you try the alpha release (latest source)? it's also available through NuGet.

**Comment by TravyDale** [comment]
I will. I will report back in a week or so if things improve.

**Comment by punker76** [comment]
@TravyDale :+1:

**Comment by TravyDale** [comment]
Version 1.1.3.0 does not fix the issue. Just had it happen today where the flyout did not close.

**Comment by punker76** [comment]
@TravyDale Please try the latest pre-release, I changed some for the Flyouts close button

**Comment by TravyDale** [comment]
Will do. Thanks for the update.

**Comment by punker76** [comment]
@TravyDale Any news?

**Comment by TravyDale** [comment]
So far no issues. Let's call this closed and if I see it, I will let you know. Thanks!
