### ISSUE TITLE
DWM Colored Theme/Accent

### ISSUE THREAD

**Issue by usagirei** [MahApps/MahApps.Metro#2163]
Would be nice to have an Accent/Theme that Matches the current Aero Color on Windows 7/8/10

Working Implementation: https://gist.github.com/usagirei/a2cfe768e4cf5fb34694

The implementation above will also change colors when using Automatic Accents and Rotating wallpapers on windows 10.

I may have missed something, since Scrollbars and DataGrid are still blue even with the Accent Applied, Probably more controls, but i only noticed those.

**Comment by punker76** [comment]
@usagirei nice idea, i will take it to the feature list...

**Comment by spasas** [comment]
This is exactly what we asked in the chat a while ago. We are looking forward for this feature to be added in a future release :)

**Comment by paulwallas** [comment]
@spasas Please can I ask what chat? I'm new to github and wpf and I'm looking for some help with mahapps. Not sure where to ask

**Comment by thoemmi** [comment]
@paulwallas  it's [Gitter](https://gitter.im/MahApps/MahApps.Metro)

**Comment by spasas** [comment]
@paulwallas like @thoemmi said.

**Comment by evilbaschdi** [comment]
What's the current state her? With the latest preview version I still can change the former "accent" color to everything I want, but I'm not able to switch between "Light" and "Dark" anymore.

**Comment by punker76** [comment]
This is implemented now with the current ThemeManager stuff from ControlzEx.
