### ISSUE TITLE
Full screen or normal screen bug when screen is switched from the broken window 10.

### ISSUE THREAD

**Issue by LeeMinWoo81** [MahApps/MahApps.Metro#2164]
Full screen or normal screen bug when screen is switched from the broken window 10.
Is it a bug in Windows 10? Or is it a bug in the MahApps?

**Comment by punker76** [comment]
@LeeMinWoo81 what do you mean with "Full screen or normal screen bug" ? can you tell us your MahApps version?

**Comment by LeeMinWoo81** [comment]
![screencrash](https://cloud.githubusercontent.com/assets/10267498/10536361/5bf01136-7425-11e5-90a1-caff0710cae7.png)

**Comment by LeeMinWoo81** [comment]
@punker76  2015-10-05 latest version.

**Comment by punker76** [comment]
@LeeMinWoo81 please re-try 1.1.3-ALPHA197, thx!

**Comment by punker76** [comment]
@LeeMinWoo81 any news?

**Comment by LeeMinWoo81** [comment]
@punker76 
Again this is the same .
" Window-> Toggle FullScreen (no taskbar, window style = null) from the menu and select" menu , when the window is changed to the original size , the screen will be corrupted .
However , it has been lost focus in the window, and re- acquired , the screen will be normal .

**Comment by punker76** [comment]
@LeeMinWoo81 mh, yeah, don't know what's going wrong on your machine. it's Wirkung for me, so it's nice if any developer see this too and have a solution, sorry.

**Comment by punker76** [comment]
@LeeMinWoo81 and by the way, this menu action was only added to show the possibility of a maximized taskbar free window...

**Comment by LeeMinWoo81** [comment]
@punker76 
I tried to change the order in which to apply the  WPF property in Windows10.
Screen cracking did not occur ... I do not know the exact cause ...

MainWindow code line is 52...

Changed code -
                   -Original
                    //metroWindow.UseNoneWindowStyle = true;
                    //metroWindow.IgnoreTaskbarOnMaximize = true;
                    //metroWindow.WindowState = WindowState.Maximized;

                    -Modify
                    metroWindow.WindowState = WindowState.Maximized;
                    metroWindow.UseNoneWindowStyle = true;
                    metroWindow.IgnoreTaskbarOnMaximize = true;
                }
                else
                {
                   -Original
                    //metroWindow.UseNoneWindowStyle = false;
                    //metroWindow.ShowTitleBar = true; // <-- this must be set to true
                    //metroWindow.IgnoreTaskbarOnMaximize = false;
                    //metroWindow.WindowState = WindowState.Normal;
                    
                    -Modify
                    metroWindow.WindowState = WindowState.Normal;
                    metroWindow.UseNoneWindowStyle = false;
                    metroWindow.ShowTitleBar = true; // <-- this must be set to true
                    metroWindow.IgnoreTaskbarOnMaximize = false;
                }
