### ISSUE TITLE
Controls Do not get distinct automation ID's

### ISSUE THREAD

**Issue by jublin** [MahApps/MahApps.Metro#2166]
When using controls such as NumericUpDown, I am unable to get a unique automationID from the control. They all show up as this: The name is being set in the Xaml. Unfortunately I cannot really give a code snippet.
![mahappsautiomationid](https://cloud.githubusercontent.com/assets/1799126/10550290/ff9cdd08-73fa-11e5-9a29-f81ab6103251.png)

The problem is my group is trying to test a window with multiple NumericUpDowns and other controls with this same issue. Automating a test becomes impossible to do with this.

**Comment by punker76** [comment]
@jublin it seems you should give your controls a `x:Name="xyz123"` for the automatic tester...

**Comment by jublin** [comment]
@punker76 I have done that. 

```
<metroControls:NumericUpDown StringFormat="N0" 
 DataContext="{Binding Source=(Removed)" 
HorizontalAlignment="Left" HorizontalContentAlignment="Left" 
KeyDown="Offset_KeyDown" 
Value="{Binding Offset}" Width="100" x:Name="OffsetControl"  
/>
```

With Name being defined as x:Name= or Name=, I get 

![image](https://cloud.githubusercontent.com/assets/1799126/10704127/7dd4952e-7989-11e5-9170-aea605d8a310.png) 

The updown buttons also have no name. The overall control does not appear as a focus element.

**Comment by punker76** [comment]
@jublin what automatic tool is this?

**Comment by jublin** [comment]
@punker76 This is the "VisualUIAVerify" tool from the windows SDK

**Comment by punker76** [comment]
@jublin ok, thx, i will take a look after releasing v1.2.0

**Comment by jublin** [comment]
This also applies to the Back/down buttons on MetroWindow Flyouts. The automation ID is seen as "nav" for each one. Getting a back button by automationID in testing may not return the intended button for the flyout.

**Comment by petvetbr** [comment]
@punker76 I'm working on a solution for this

**Comment by petvetbr** [comment]
I´m working on a new implementation based on AutomationPeers. Should be available soon.

**Comment by lightwalker01** [comment]
@punker76, @petvetbr any news on this issue?
For the moment i have implemented a workaround subclassing NumericUpDown and taking inspiration from [DatePickerAutomationPeer](https://www.dotnetframework.org/default.aspx/4@0/4@0/DEVDIV_TFS/Dev10/Releases/RTMRel/wpf/src/Framework/System/Windows/Automation/Peers/DatePickerAutomationPeer@cs/1305600/DatePickerAutomationPeer@cs) original code:


 ```csharp
 public class AutomationNumericUpDown : NumericUpDown
 {
        protected override AutomationPeer OnCreateAutomationPeer()
        {
            if (GenericAutomationPeer.IsEnabled)
            {
                var ap = new AutomationNumericUpDownAutomationPeer(this);
               
                return ap;
            }
            return base.OnCreateAutomationPeer();
        }

        private sealed class AutomationNumericUpDownAutomationPeer : FrameworkElementAutomationPeer, IValueProvider
        {
            private NumericUpDown _owner;

            public AutomationNumericUpDownAutomationPeer(NumericUpDown owner)
                : base(owner)
            {
                _owner = owner;

                var automationContext = owner.GetValue(AutomationHelpers.AutomationContextProperty) as string;
                if (!string.IsNullOrWhiteSpace(automationContext) && owner.Template != null)
                {
                    var txt = owner.Template.FindName("PART_TextBox", owner) as TextBox;
                    if (txt != null)
                    {
                        txt.SetValue(AutomationProperties.AutomationIdProperty, $"txt_{automationContext}");
                    }

                    var up = owner.Template.FindName("PART_NumericUp", owner) as ButtonBase;
                    if (up != null)
                    {
                        up.SetValue(AutomationProperties.AutomationIdProperty, $"btn_{automationContext}.Up");
                    }

                    var down = owner.Template.FindName("PART_NumericDown", owner) as ButtonBase;
                    if (down != null)
                    {
                        down.SetValue(AutomationProperties.AutomationIdProperty, $"btn_{automationContext}.Down");
                    }
                }
            }

            public override object GetPattern(PatternInterface patternInterface)
            {
                if (patternInterface == PatternInterface.Value)
                {
                    return this;
                }

                return base.GetPattern(patternInterface);
            }

            #region IValueProvider 

            bool IValueProvider.IsReadOnly
            {
                get { return false; }
            }

            string IValueProvider.Value
            {
                get { return _owner.Value?.ToString(); }
            }

            void IValueProvider.SetValue(string value)
            {
                if(double.TryParse(value, out double num))
                {
                    _owner.Value = num; 
                }
                else
                {
                    _owner.Value = null;
                }
            }

            #endregion IValueProvider

            protected override string GetLocalizedControlTypeCore() => "numeric up down";

            protected override string GetClassNameCore() => "NumericUpDown";

            protected override AutomationControlType GetAutomationControlTypeCore() => AutomationControlType.Custom;
        }
}
```

**Comment by petvetbr** [comment]
@lightwalker01 No news on this front. I was not able to implement this, sorry.

**Comment by noubar** [comment]
Thank You @lightwalker01 for your post of workaround. This library is really terrible in terms of automation. But your workaround really works

There is also a bug  #4454 posted for a really long while which blocks the whole process of test automation, and it is not fixed. I find it unfortunate that we need to implement workarounds.

**Comment by timunie** [comment]
@noubar this is a totally free time project and the devs work on things they need. So things are done when they are done. Contribtions are welcome if you want to speed things up. 

Thanks for your understanding.
