### ISSUE TITLE
Button Text Capitalization

### ISSUE THREAD

**Issue by Memphizzz** [MahApps/MahApps.Metro#2168]
Is there a way to make the text of buttons not all lower case? I was hoping for something like "TitleCaps" but for buttons...

**Comment by punker76** [comment]
@Memphizzz If you use the latest alpha, there is a new attached property `ContentCharacterCasing` in `ControlsHelper` to handle this https://github.com/MahApps/MahApps.Metro/blob/master/MahApps.Metro/Controls/Helper/ControlsHelper.cs#L39

**Comment by Memphizzz** [comment]
@punker76 Thanks for the quick reply. I'm currently using the package from NuGet. I guess Ill just wait for this to get merged into the next release :)
