### ISSUE TITLE
How to get WindowChrome 

### ISSUE THREAD

**Issue by myrnazhou** [MahApps/MahApps.Metro#2169]
Hi guys,
I want to manipulate some property inside WindowChrome, but whenever I tried to get the value from my Window I always got null, below is the snippet:
```
void WindowBase_Loaded(object sender, RoutedEventArgs e)
{
      var chrome = WindowChrome.GetWindowChrome(this);
}
```
Is there anything wrong in my code?

**Comment by thoemmi** [comment]
Is your window derived from `MetroWindow`? The WindowChrome property is initialized by `BorderlessWindowBehavior`, which is set in `MetroWindow`'s style.

**Comment by punker76** [comment]
@myrnazhou any news here?

**Comment by myrnazhou** [comment]
Thanks @thoemmi,  yes it's derived from ```MetroWindow```, I think the problem is because ```WindowChrome``` class is defined inside mahapps solution not the one from ```Windows.Shell.WindowChrome```, so I still can't get it.

**Comment by punker76** [comment]
@myrnazhou you should use the `Microsoft.Windows.Shell.WindowChrome` namespace

```csharp
void MainWindow_Loaded(object sender, RoutedEventArgs e)
{
    var chrome = Microsoft.Windows.Shell.WindowChrome.GetWindowChrome(this);

    // or

    var chrome = this.GetValue(Microsoft.Windows.Shell.WindowChrome.WindowChromeProperty);
}
```

**Comment by myrnazhou** [comment]
I've tried that as well, I got ```'WindowChrome' is inaccessible due to its protection level```. Then I tried to use ```Microsoft.Windows.Shell``` from the ```nuget```, but then it's different type than the one that is added from ```BorderlessWindowBehavior```, so it returns ```null```.

**Comment by thoemmi** [comment]
I can't reproduce your issue. `WindowChrome` is a public type.

I just added this working code to the c'tor of `MainWindow` in MetroDemo:
```
Loaded += (sender, args) => {
    var chrome = WindowChrome.GetWindowChrome(this);
};
```
and it works:
![image](https://cloud.githubusercontent.com/assets/73690/10727933/f0b4d490-7bdd-11e5-8518-59c5266ebe95.png)

**Comment by myrnazhou** [comment]
I think that's the problem, I can get the ```object``` when using the demo but not when in my own project. I added ```MahApps``` from ```nuget```.

**Comment by thoemmi** [comment]
Maybe you're using an additional NuGet package coming with its own copy of Microsoft.Windows.Shell?

**Comment by myrnazhou** [comment]
Yes I've mentioned it in my prev comment, I'm using ```Microsoft.Windows.Shell``` from ```nuget```, since it won't compile without it. With just including MahApps, I got ```'WindowChrome' is inaccessible due to its protection level.```

**Comment by thoemmi** [comment]
Sorry, I didn't notice you rcomment. In fact, `WindowChrome` was internal, but was changed to public with commit 82aca23c.
Can you please try the latest pre-release?

**Comment by myrnazhou** [comment]
Ah ok, thanks, it works now. Never realized there was pre-release build. :)
