### ISSUE TITLE
NullReferenceException if Theme set via ThemeManager

### ISSUE THREAD

**Issue by Memphizzz** [MahApps/MahApps.Metro#2170]
As I want my application to be as customizable as possible I'm using the ThemeManager approach to select the theme in the App.xaml's "OnStartUp" event.
Unfortunately though I just encountered an error which looks like is related to this approach.
If I only add "Controls.xaml", "Fonts.xaml" and "Colors.xaml" to the App.xaml ResourceDictionary and try to call `this.ShowProgressAsync("Please wait...", "Progress message");` I get a NullReferenceException which leads to"BaseMetroDialog.HandleTheme()". I've narrowed it down to the "DetectTheme" method which uses "ThemeManager.DetectAppStyle(window)" but doesn't find anything in the resources of course.

Any help is appreciated.

Regards,
MemphiZ

**Comment by punker76** [comment]
@Memphizzz it's recommended to add  an accent and theme resource too!

**Comment by Memphizzz** [comment]
@punker76 So If I have a settings FlyOut where the user can choose any theme or accent I have to add all of them to the App.xaml for the Dialogs to work? Because of course I want to have the dialog themed like the theme that is currently selected by the user...

**Comment by Memphizzz** [comment]
I figured it out. I just need to add BaseLight and BaseDark to the App.xaml, accents are not needed.
