### ISSUE TITLE
Background color of StatusBar

### ISSUE THREAD

**Issue by thoemmi** [MahApps/MahApps.Metro#2173]
Currently the background color of `StatusBar` is fixed (except when [it's disabled](https://github.com/MahApps/MahApps.Metro/blob/master/MahApps.Metro/Styles/Controls.StatusBar.xaml#L84-L89)). However; i prefer it to match the title bar, i.e. when the window is not active, not only the title's background should change, but the status bar's too.

To achieve that, I added an additional trigger in my app, which looks like this:
```xml
<StatusBar Grid.Row="1">
  <!-- -->
  <StatusBar.Style>
    <Style TargetType="{x:Type StatusBar}" BasedOn="{StaticResource MetroStatusBar}">
      <Setter Property="Background" Value="{DynamicResource WindowTitleColorBrush}" />
      <Style.Triggers>
        <DataTrigger Binding="{Binding RelativeSource={RelativeSource FindAncestor, AncestorType={x:Type Window}}, Path=IsActive}" Value="False">
          <Setter Property="Background" Value="{Binding Path=NonActiveWindowTitleBrush, Mode=OneWay, RelativeSource={RelativeSource FindAncestor, AncestorType={x:Type controls:MetroWindow}}}" />
        </DataTrigger>
      </Style.Triggers>
    </Style>
  </StatusBar.Style>
</StatusBar>
```
How about adding this to the MahApps style by default?

**Comment by punker76** [comment]
@thoemmi  +1 from me

**Comment by thoemmi** [comment]
Ok, I'll prepare a PR. Currently `StatusBar`'s background is set to [`AccentColorBrush`](https://github.com/MahApps/MahApps.Metro/blob/master/MahApps.Metro/Styles/Controls.StatusBar.xaml#L60-L61). I would change that to `WindowTitleColorBrush` too, ok?

**Comment by thoemmi** [comment]
May it would even be better to use 
`{Binding Path=WindowTitleBrush, Mode=OneWay, RelativeSource={RelativeSource FindAncestor, AncestorType={x:Type controls:MetroWindow}}}`

**Comment by thoemmi** [comment]
Since #2174 was merged, I close this issue.
