### ISSUE TITLE
Selectable or copyable dialog text

### ISSUE THREAD

**Issue by laurencee** [MahApps/MahApps.Metro#2179]
Hello,

Is there a way to allow the text in the MahApps.Metro dialog to be selectable?

For an error message I was wanting to provide some helpful references but that's not so great if the user has to type them manually to look them up.

**Comment by Jehoel** [comment]
For people still finding this issue thread today - I worked-around this problem by adding a button action to the dialog which then invokes a custom method that copies the dialog's text to the clipboard.
