### ISSUE TITLE
Textbox validator tooltip and scrollviewer

### ISSUE THREAD

**Issue by MrNorth35** [MahApps/MahApps.Metro#2183]
Hi!

I have noticed that if I place a textbox in a scrollviewer and validate the textbox, causing the red tooltip/adorner to appear, and then start scrolling or move the window, the tooltip doesn't follow the textbox, but is rather stuck at where it was created.

Am I doing something wrong, or is this a bug?

/H

**Comment by punker76** [comment]
This is fixed now with #3794.
