### ISSUE TITLE
SplitButton IsPressed trigger won't change Foreground

### ISSUE THREAD

**Issue by Interforce** [MahApps/MahApps.Metro#2185]
I am trying to get the PART_Button of SplitButton to behave like a normal button would do. I created a custom ButtonDropDownStyle and added a trigger to IsPressed-property to change the Fontcolor to white as long as said button is pressed but this somehow only changes the Background

    <Trigger Property="IsPressed" Value="True">
        <Setter TargetName="Border" Property="Background" Value="{DynamicResource GrayBrush6}" />
        <Setter Property="Foreground" Value="White"/>
    </Trigger>

**Comment by punker76** [comment]
@Interforce Which version? Please try latest alpha.

**Comment by Interforce** [comment]
Master from 22.10, compiled with VS2015.
Ok I tested the latest ALPHA216 directly from nuget. 
Background changes fine, Foreground doesn't.

**Comment by punker76** [comment]
@Interforce There will be 2 new properties ArrowMouseOverBrush, ArrowPressedBrush after PR #2572
