### ISSUE TITLE
ribbon doesn't works

### ISSUE THREAD

**Issue by aryaei** [MahApps/MahApps.Metro#2186]
i want to work on metro style ribbon but it doesn't work i commented out the codes about running ribbon demo but it throws many exceptions

can somemone help me work it out?

**Comment by punker76** [comment]
@aryaei the ribbon is outdated in MahApps. i suggest you to use [Fluent.Ribbon](https://github.com/fluentribbon/Fluent.Ribbon). it also supports MahApps.
