### ISSUE TITLE
WindowCommands.ShowSeparators=False is ignored

### ISSUE THREAD

**Issue by MrMitch** [MahApps/MahApps.Metro#2188]
When adding a set of commands to the MetroWindow, the separator are always visible even with the `ShowSeparators` attribute set to false.

I have created a basic project demonstrating this here : https://github.com/MrMitch/MahAppsSeparatorsError

Tested with version `MahApps.Metro.1.1.3-ALPHA217`

![image](https://cloud.githubusercontent.com/assets/576772/10849977/9c234116-7f23-11e5-8e3c-10ee8286aa41.png)

**Comment by punker76** [comment]
@MrMitch that's not good :-D will look into
