### ISSUE TITLE
Image button become invisible if margin positionement is applied

### ISSUE THREAD

**Issue by remygrandin** [MahApps/MahApps.Metro#2190]
Hi,

I'm stating to use MahApps.Metro but i have some trouble with positionnin an image button as I would like. Here is my xaml : 

	<sesmInstallerV2:MasterUserControl x:Class="SESMInstallerV2.Pages.P1_Mode"
		  xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
		  xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
		  xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
		  xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
		  xmlns:local="clr-namespace:SESMInstallerV2.Pages"
		  xmlns:sesmInstallerV2="clr-namespace:SESMInstallerV2"
		  mc:Ignorable="d" 
		  d:DesignHeight="580" d:DesignWidth="780">
		<UserControl.Resources>
			<ResourceDictionary>
				<ResourceDictionary.MergedDictionaries>
					<ResourceDictionary Source="/Resources/Icons.xaml" />
				</ResourceDictionary.MergedDictionaries>
			</ResourceDictionary>
		</UserControl.Resources>
		<Grid>
			<Button Width="50" Height="50" Style="{DynamicResource MetroButton}">
				<Rectangle Width="20" Height="20" Fill="{Binding Path=Foreground, RelativeSource={RelativeSource FindAncestor, AncestorType={x:Type Button}}}">
					<Rectangle.OpacityMask>
						<VisualBrush Stretch="Fill" Visual="{DynamicResource appbar_arrow_down}" />
					</Rectangle.OpacityMask>
				</Rectangle>
			</Button>
		</Grid>
	</sesmInstallerV2:MasterUserControl>

Although, it I try to move my button in the designer (giving it **Margin** attribute), it don't show anymore.

**Comment by punker76** [comment]
@remygrandin seems to be a visual studio designer issue... works on my machine™ and visual studio 2013.

![image](https://cloud.githubusercontent.com/assets/658431/10879457/64b387e4-8154-11e5-87a3-721816b04149.png)

**Comment by punker76** [comment]
@remygrandin any news? is this still an issue for you?
