### ISSUE TITLE
Styling ShowInputAsync ?

### ISSUE THREAD

**Issue by barryBithead** [MahApps/MahApps.Metro#2191]
Is there a way to customize the styling of the dialog window(s) ? In particular the background color of the buttons, font size etc.

My app uses a color scheme from a config file, and I've managed to wire it to the rest of my Metro implementation where I need it, by doing this (for buttons):

Style x:Key="CustomButtonStyle" TargetType="{x:Type Button}" BasedOn="{StaticResource MetroWindowButtonStyle}"

...and then use my customs colors as property values within the style definition, and then set my custom definition as the style for my buttons in the main window.. It works great, but now I need to apply the same above custom style to the Dialogs: ShowInputAsync etc.

Please advise.

**Comment by punker76** [comment]
@barryBithead You can use your custom styles via [`MetroDialogSettings.CustomResourceDictionary`](https://github.com/MahApps/MahApps.Metro/blob/master/MahApps.Metro/Controls/Dialogs/BaseMetroDialog.cs#L409)

**Comment by barryBithead** [comment]
For some reason I'm not getting CustomResourceDictionary as a property of MetroDialogSettings ?

**Comment by punker76** [comment]
yeah, sorry for that, it's available in the alpha version.

**Comment by barryBithead** [comment]
So I'm toast ? :-)

**Comment by barryBithead** [comment]
Allo ?...:-)
