### ISSUE TITLE
For ComboBox the TextBoxHelper.Watermark only works when IsEditable

### ISSUE THREAD

**Issue by dsaf** [MahApps/MahApps.Metro#2192]
Also when I set ```IsEditable``` to ```True``` then it will select the text on selecting item. So it is not ideal.

**Comment by punker76** [comment]
that's fixed in upcoming v1.2.0 (alpha version)
-> Watermark on ComboBox where IsEditable="False" #1958 #1953

**Comment by dsaf** [comment]
Understood, thank you.
