### ISSUE TITLE
Dynamically changing Themes not working on content control

### ISSUE THREAD

**Issue by girija45701** [MahApps/MahApps.Metro#2194]
Hi all,
Somehow not able to get this working. I have a single MetroWindow which loads with default Color. I have an option for user to change the style. In the window I use a Content control to set the user control dynamically from code behind when initializing this window (This window is initialized from another application so there is no app.xaml and I use the resources in the window itself). The code of the main windows is below. In the User Control I am using some labels and a tab control. On the window I have an option for user to be able to change the theme choosing from available themes (as in your demo project). In all labels I use dynamics resources.

When the window loads for first time the default color is applied and all inner controls have the same theme as well. When I change the theme from window top, the window border, title, glow changes but the inner control stays the old theme (like the tab control headers etc.) I have tried everything but that does not seem to change.

Any help is appreciated

Below is my code:

```xaml
<Controls:MetroWindow x:Class="Test.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:Controls="clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro"
        Title="MainWindow" Height="300" Width="300" ShowMaxRestoreButton="False" ShowMinButton="False" 
        BorderBrush="{DynamicResource HighlightBrush}"
        GlowBrush="{DynamicResource HighlightBrush}" WindowStartupLocation="CenterScreen" 
        ResizeMode="NoResize" WindowTransitionsEnabled="False" TitleForeground="White" TitleCaps="True"
        BorderThickness="1">
    
    
    <Border Margin="5" BorderBrush="Transparent" BorderThickness="0">
        <ContentControl x:Name="ChildContentControl"
                    HorizontalAlignment="Stretch" 
                    VerticalAlignment="Stretch">
        </ContentControl>
    </Border>
</Controls:MetroWindow>
```

**Comment by punker76** [comment]
@girija45701 same answer as [here](http://stackoverflow.com/a/33606001/920384)

I think you have 2 options to solve this.

- Create your `Test.UCDemo` as DataTemplate for the `VMDemo` type and pass the `VMDemo` for this template to the `Content`, so your `ContentControl` will automatically do the magic for you (it's just only a suggestion, i don't tested it)
- Put the resources in your `Test.UCDemo` too.

Hope that helps.
