### ISSUE TITLE
Icons not working

### ISSUE THREAD

**Issue by girija45701** [MahApps/MahApps.Metro#2196]
Hi all,

I have installed the MahApps.Metro from nugget. After that I installed the MahApps.Metro.Resources as well. This created a folder called resources in my project. I use the icons.xaml file in my window resources. I used some icons in the buttons of my usercontrol (embedded in main window within a content control). But when I run the icons do not appear. only the gray circle is visible.

I opened the icons.xaml and saw the Fill property where Fill={DynamicResource BlackBrush} is error out. If I change the fill to Fill="Black" then I can see the icons. But if the Accent is Dark it creates an issue.

Am I missing something here ?

- Girija

**Comment by punker76** [comment]
@girija45701 In the main demo is a short usage for circle button and icons. [here]https://github.com/MahApps/MahApps.Metro/blob/master/samples/MetroDemo/ExampleViews/ButtonsExample.xaml#L141-L152

It's also descriped [here](http://mahapps.com/guides/icons-and-resources.html)

**Comment by girija45701** [comment]
Hi,
I did see the demo project before I posted the question. I again just now uninstalled the MahApps.Metro.Resources and installed it again and used:

<ResourceDictionary Source="pack://application:,,,/MahApps.Metro.Resources;component/Icons.xaml" />

But while running the application I get this error..

Could not load file or assembly 'MahApps.Metro.Resources.

- Girija

**Comment by girija45701** [comment]
Hi @punker76 

I did see the samples and the link and that did not work for me. I just now have tried uninstalling the MahApps.Metro.Resources and then installing it again and referring it in my usercontrol (within the window) as well as with a  test button on my window but still I see only the gray circle and no icon.
I referenced by using the below code

<Window.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="/Demo.Test;component/Resources/Icons.xaml"></ResourceDictionary>
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Window.Resources>

As said earlier in my icon.xaml for all icons I see the fill error out and error is "Cannot find resource BlackBrush"

I tried adding "<ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Colors.xaml" />" as a merged dictionary in the icons.xaml. The error disappeared but it still does not show the icons :(

The issue is closed so I do not know if you will check this but anyway posting it. Please let me know if I need to open another issue for this ?

- Girija

**Comment by punker76** [comment]
@girija45701 to point out whats going wrong, create a short app sample. so it's easier to find out...

**Comment by girija45701** [comment]
Hi @punker76 ,

I tried creating a sample. I added nugget Mahapps.metro and Mahapps.metro.resources I created a window, refrenced all MahApps.Metro xaml with the resources xaml. Then I added a User control in the project with same responses. In the user control I added a button and I added a button in the window as well. When I run the sample I donot see any of the icons (in window direct as well as within user control)

When I compare with the demo application I do not see any difference apart from the fact that in demo you have a separate class library for the icons.xaml.

Below is my code. Please have a look if you have time and suggest if anything strikes.

- Girija

<Window x:Class="TestApp.Demo.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:Controls="clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro"
        xmlns:local="clr-namespace:TestApp.Demo"
        Title="MainWindow" Height="350" Width="525">
    <Window.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Colors.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/Blue.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/BaseLight.xaml" />
                
                <ResourceDictionary Source="/Resources/Icons.xaml" />
            </ResourceDictionary.MergedDictionaries>

        </ResourceDictionary>
    </Window.Resources>
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="auto"/>
            <RowDefinition Height="*"/>
        </Grid.RowDefinitions>
        <Button Grid.Row="0" Width="50" 
 Height="50" 
Style="{DynamicResource MetroCircleButtonStyle}">
            <Rectangle Width="20" 
Height="20" 
Fill="{Binding Path=Foreground, RelativeSource={RelativeSource FindAncestor, AncestorType={x:Type Button}}}">
                <Rectangle.OpacityMask>
                    <VisualBrush Stretch="Fill" 
                    Visual="{DynamicResource appbar_city}" />
                </Rectangle.OpacityMask>
            </Rectangle>
        </Button>
        <local:UCTest Grid.Row="1"/>
    </Grid>
</Window>


<UserControl x:Class="TestApp.Demo.UCTest"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
             xmlns:Controls="clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro"
             mc:Ignorable="d" 
             d:DesignHeight="300" d:DesignWidth="300">
    <UserControl.Resources>
        <ResourceDictionary>
                    <ResourceDictionary.MergedDictionaries>
                        <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
                        <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
                        <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Colors.xaml" />
                        <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/Blue.xaml" />
                        <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/BaseLight.xaml" />
                        <ResourceDictionary Source="pack://application:,,,/TestApp.Demo;component/Resources/Icons.xaml" />
            </ResourceDictionary.MergedDictionaries>
                </ResourceDictionary>
    </UserControl.Resources>
    <Grid>
        <Grid>
            <Button Width="50" 
 Height="50" 
Style="{DynamicResource MetroCircleButtonStyle}">
                <Rectangle Width="20" 
Height="20" 
Fill="{Binding Path=Foreground, RelativeSource={RelativeSource FindAncestor, AncestorType={x:Type Button}}}">
                    <Rectangle.OpacityMask>
                        <VisualBrush Stretch="Fill" 
                    Visual="{DynamicResource appbar_city}" />
                    </Rectangle.OpacityMask>
                </Rectangle>
            </Button>

        </Grid>
    </Grid>
</UserControl>

**Comment by punker76** [comment]
You have 2 options to solve your problem.

First option is to use `StaticResource` instead `DynamicResource`.

    <VisualBrush Stretch="Fill" Visual="{StaticResource appbar_city}" />

Second option is to put your resources to the `App.xaml`, so you can still use `DynamicResource`.

    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Colors.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/Blue.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/BaseLight.xaml" />
                <ResourceDictionary Source="/Resources/Icons.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>
