### ISSUE TITLE
Autohide taskbar, MahApps MetroWindow

### ISSUE THREAD

**Issue by pixolit** [MahApps/MahApps.Metro#220]
If the taskbar is set to autohide and a MetroWindow is maximized, going with the mouse cursor to the bottom of the screen doesn't unhide the taskbar.

I could reproduce it with the newest version in NuGet (0.9.0.0) on Windows 7.

**Comment by nalka0** [comment]
I still have this issue on windows 10 (also had it before moving to windows 10 but I can't remember what version it was) with `MetroWindow` (focus doesn't matter), using MahApps.Metro 2.4.3 and .Net framework 4.6.1

**Comment by timunie** [comment]
Hi @nalka0 ,

can you please open a new issue, use the issue template and provide your code (not working sample App would be the best). Answering closed issues is not a good idea as the developers might miss your issues. 

Thanks and happy coding
Tim
