### ISSUE TITLE
Problem with bitmap effect in window inner border

### ISSUE THREAD

**Issue by suhan3z** [MahApps/MahApps.Metro#2206]
Hi, i try to use BorderlessWindowBehavior on window but see this black border instead of bitmap effect http://screencast.com/t/K14knJ7cIIX
 ``` 
<Window x:Class="View.FilteringLog.FilteringLogView"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:i="http://schemas.microsoft.com/expression/2010/interactivity"
        xmlns:behaviours="http://metro.mahapps.com/winfx/xaml/shared"
        WindowStyle="None"
        AllowsTransparency="True"
        Background="Transparent"
        d:DesignHeight="595"
        d:DesignWidth="815"
        mc:Ignorable="d">
    <i:Interaction.Behaviors>
        <behaviours:BorderlessWindowBehavior/>
    </i:Interaction.Behaviors>
    <Border Style="{StaticResource BorderDialogWindowStyle}">
```
	
	and this is Border style:
```	 
	 <Style x:Key="BorderDialogWindowStyle" TargetType="Border">
        <Setter Property="BorderThickness" Value="20" />
        <Setter Property="CornerRadius" Value="{StaticResource CornerRadiusDialogWindow}" />
        <Setter Property="BitmapEffect" Value="{StaticResource WindowShadowEffect}" />
    </Style> 
```

Is it bug, or i do something wrong?

**Comment by suhan3z** [comment]
Looks like its going on because of this code in BorderlessWindowBehavior
``` 
 // no transparany, because it hase more then one unwanted issues
            var windowHandle = new WindowInteropHelper(AssociatedObject).Handle;
            if (!AssociatedObject.IsLoaded && windowHandle == IntPtr.Zero)
            {
                try
                {
                    AssociatedObject.AllowsTransparency = false;
                }
                catch (Exception)
                {
                    //For some reason, we can't determine if the window has loaded or not, so we swallow the exception.
                }
            }
```
So this mean i can't use window with allowed transparency?

**Comment by bloritsch** [comment]
You are aware that BitmapEffects are deprecated in WPF now, right?  They have some rendering issues associated with them, and are replaced by shader effects like the new DropShadowEffect.

It's worth trying it out:

     <Style x:Key="BorderDialogWindowStyle" TargetType="Border">
        <Setter Property="BorderThickness" Value="20" />
        <Setter Property="CornerRadius" Value="{StaticResource CornerRadiusDialogWindow}" />
        <Setter Property="Effect">
             <Setter.Value>
                 <DropShadowEffect/>
             </Setter.Value>
        </Setter>
    </Style> 

The new effects run in the GPU rather than the CPU, and aren't as limited as bitmapeffects.  They were marked as obsolete in .NET 4.0 (https://msdn.microsoft.com/en-us/library/system.windows.media.effects.bitmapeffect(v=vs.100).aspx) with an animateable replacement: https://msdn.microsoft.com/en-us/library/system.windows.media.effects.effect(v=vs.110).aspx

**Comment by suhan3z** [comment]
Thanks for reply. I changed this effect on glow effect from metro window, it looks better. So i close this issue
