### ISSUE TITLE
Combobox watermark padding changes with IsEditable

### ISSUE THREAD

**Issue by kfpulver** [MahApps/MahApps.Metro#2210]
The watermark padding on Comboboxes differs with the IsEditable setting.  A much larger than necessary padding is applied for non-editable Comboboxes.

![capture](https://cloud.githubusercontent.com/assets/15821076/11126204/7adb3800-8933-11e5-8226-6ea3ab0a3194.PNG)

First Combobox IsEditable=true; next two Comboboxes IsEditable=false.  Asterisks have been added to show the difference in watermark padding. IsEditable=false results in watermark cropping.

**Comment by punker76** [comment]
is fixed now

![image](https://cloud.githubusercontent.com/assets/658431/11164297/56fe57b8-8aec-11e5-8643-997322ebf6ad.png)
