### ISSUE TITLE
How to show customdialog on the webbrowser control

### ISSUE THREAD

**Issue by WELL-E** [MahApps/MahApps.Metro#2212]
How to show customdialog on the webbrowser control.

**Comment by WELL-E** [comment]
The webbrowser control block the dialog.

**Comment by punker76** [comment]
@WELL-E That's a problem of the WebBrowser control itself. You should use [CefSharp](https://github.com/cefsharp/CefSharp) or the [AirspaceDecorator](https://microsoftdwayneneed.codeplex.com/)

**Comment by WELL-E** [comment]
Jan Karger, thank you very much!
