### ISSUE TITLE
SplitButton does not respect GroupStyle

### ISSUE THREAD

**Issue by bloritsch** [MahApps/MahApps.Metro#2215]
SplitButton extents ItemsCollection, which allows me to specify a GroupStyle (useful in configurations where I want to supply a set of standard static colors and a set of theme colors).

The "PART_ListBox" needs to bind the "GroupStyle" collection in SplitButton to the ListBox.GroupStyle collection.  The short term work around was to subclass the SplitButton and override the OnApplyTemplate() call.

    public override void OnApplyTemplate()
    {
        base.OnApplyTemplate();

        // Can't use the EnforceType<ListBox> method in the base class because it's private.
        ListBox listBox = GetTemplateChild("PART_ListBox") as ListBox;

        if(listBox == null) { return; }

        foreach(GroupStyle style in GroupStyle)
        {
            listBox.GroupStyle.Add(style);
        }
    }

**Comment by bloritsch** [comment]
Addendum, I also had to bind the ItemsPanel property:

    BindingOperations.SetBinding(listBox, ItemsPanelProperty, new Binding
    {
        Source = this,
        Path = new PropertyPath(ItemsPanelProperty)
    });

**Comment by punker76** [comment]
> 'GroupStyle' property is read-only and cannot be set from markup.

I'll add the template binding for the ItemsPanel.
