### ISSUE TITLE
Why in the MetroButtonTextBox the visibility of PART_ClearText is not managed as the MetroTextBox?

### ISSUE THREAD

**Issue by gigios** [MahApps/MahApps.Metro#2220]
I want to manage the MetroButtonTextBox Visibility behavior in the same way of the MetroTextBox (when there is Text in the TextBox the button should be visible, otherwise collapsed).
I have checked the style and I have seed that the PART_ClearText dows not have any binding in the Visibility property.
Is it a missing binding or there are a different way to hide the button?

**Comment by punker76** [comment]
@gigios it's now possible since https://github.com/MahApps/MahApps.Metro/pull/2387

**Comment by gigios** [comment]
Thank you!
