### ISSUE TITLE
Generate cursor from Mahapps.Resources icons?

### ISSUE THREAD

**Issue by bloritsch** [MahApps/MahApps.Metro#2221]
Based on a StackOverflow issue there is a way to generate a cursor from a BitmapSource: http://stackoverflow.com/questions/2835502/rotating-cursor-according-to-rotated-textbox/2836904#2836904

And I figured out a way to generate a DrawingGeometry from the Canvas icons listed here: http://mahapps.com/guides/icons-and-resources.html

That should make custom zoom tool cursors and such like a lot easier to implement and still retain a consistent look and feel rather than Windows 7 icons over a Windows 8/10 looking application.

For 90% of the icons in Modern UI ICons (and the noun project), converting the Canvas to a Geometry is pretty straightforward since they use the same shorthand notation:

    public static Geometry ExtractFrozenGeometry(Canvas icon)
    {
        Path iconPath = icon.Children.OfType<Path>().FirstOrDefault();
        Geometry iconGeometry;

        if(iconPath == null)
        {
            // appbar_moon_full uses an ellipse
            Ellipse iconEllipse = icon.Children.OfType<Ellipse>().FirstOrDefault();

            if (iconEllipse == null)
            {
                Debug.Fail("There's an unexpected Canvas implementation!");
            }

            iconGeometry = new EllipseGeometry
            {
                RadiusX = iconEllipse.Width / 2,
                RadiusY = iconEllipse.Height / 2
            }
        }
        else
        {
            iconGeometry = new iconPath.Data.Clone();
        }

        iconGeometry.Freeze();
        return iconGeometry;
    }

There are one or two Canvas icons that have multiple paths, and that would require building a CombinedGeometry with GeometryCombineMode="Union".

What I'm working on can't be forked/etc. but I can post the final code for once we have a geometry.

**Comment by bloritsch** [comment]
I've got a working routine that depends on the ExtractFrozenGeometry() method above.  The code could use some cleanup, but here goes:

    const int CursorSize = 24; // technically it's usually 32, but the modern icons look cartoonish then

    public static Cursor VectorIconToCursor(Canvas icon, Brush color, double hotSpotX, double hotSPotY)
    {
        Debug.Assert(hotSpotX >= 0 && hotSPotX <= 1);
        Debug.Assert(hotSpotY >= 0 && hotSPotY <= 1);

        short hotXPixel = (short)((CursorSize * hotSPotX) + 0.5);
        short hotYPixel = (short)((CursorSize * hotSPotY) + 0.5);

        RenderTargetBitmap rtb = new RenderTargetBitmap(CursorSize, CursorSize, 96, 96, PixelFormats.Default);
        DrawingVisual visual = new DrawingVisual();
        using(DrawingContext context = visual.RenderOption())
        {
            GeometryDrawing drawing = new GeometryDrawing(color, null, ExtractFrozenGeometry(icon);
            DrawingBrush brush = new DrawingBrush(drawing);
            context.DrawRectangle(brush, null, new Rect(new Point(), new Size(CursorSize,CursorSize)));
        }

        rtb.Render(visual);

        byte[] imageBytes;

        using(MemoryStream imageStream = new MemoryStream())
        {
            // starting in Vista, we can use PNG content for cursors and icons
            PngBitmapEncoder encoder = new PngBitmapEncoder();
            encoder.Frames.Add(BitmapFrame.Create(rtb));
            encoder.Save(stream);

            imageBytes = stream.ToArray();
        }

        // now to package the image into a cursor file format
        using(MemoryStream stream = new MemoryStream())
        {
            // Write the ICONDIR structure (all Little Endian)
            WriteShort(stream, 0); // always short 0
            WriteShort(stream, 2); // 1 means ICO, 2 means CUR
            WriteShort(stream, 1); // number of files, only one for CUR files

            // Write the ICONDIRENTRY record
            stream.WriteByte(0); // always 0
            stream.WriteByte(CursorSize); // x dimension in pixels
            stream.WriteByte(CursorSize); // y dimension in pixels
            stream.WriteByte(0); // reserved, just use 0
            WriteShort(stream, hotXPixel); // for CUR, hotspot, pixels from left
            WriteShort(stream, hotYPixel); // for CUR, hotspot, pixels from top
            WriteInt32(stream, imageBytes.Length); // size of image data in bytes
            WriteInt32(stream, 6+16); // offset from start of file for image data (account for header data)

            // Write the image itself
            stream.Write(imageBytes, 0, imageBytes.Length);
            stream.Seek(0, SeekOrigin.Begin); // rewind so we can read the image stream

            return new Cursor(stream);
        }
    }

    private static void WriteShort(Stream stream, short number)
    {
        byte[] bytes = BitConverter.GetBytes(number);
        // ICO/CUR format is always little endian
        if(!BitConverter.IsLittleEndian)
        {
            Array.Reverse(bytes);
        }

        stream.Write(bytes, 0, bytes.Length);
    }

    private static void WriteInt32(Stream stream, Int32 number)
    {
        byte[] bytes = BitConverter.GetBytes(number);
        // ICO/CUR format is always little endian
        if(!BitConverter.IsLittleEndian)
        {
            Array.Reverse(bytes);
        }

        stream.Write(bytes, 0, bytes.Length);
    }

It works pretty well.  For debugging, I did put a File.WriteAllBytes() to save the PNG image and the Cursor file.  I'll have to make some minor modifications to create a white cursor with a 1px border, but this is a good start.  Geometries do make that a bit easier.

**Comment by bloritsch** [comment]
The only change to add a black outline is to replace the section of code with the drawing context:

    Rect rect = new new Rect(new Point(), new Size(CursorSize,CursorSize));
    using (DrawingContext context = visual.RenderOpen())
    {
        Geometry insideGeometry = ExtractFrozenGeometry(icon);
        GeometryDrawing drawing = new GeometryDrawing(color, new Pen(Brushes.Black, 1), insideGeometry);
        DrawingBrush brush = new DrawingBrush(drawing);
        context.DrawRectangle(brush, null, rect);
    }

NOTE: you can't just reassign the drawing brush/pen values

**Comment by punker76** [comment]
@bloritsch Thx for publishing your code! You should maybe put this in a gist. I'll close this, cause I think it's non MahApps.
