### ISSUE TITLE
Call ASync  MessageDialog Box in User control

### ISSUE THREAD

**Issue by akshithrajesh** [MahApps/MahApps.Metro#2231]
How to Call Async Show Dialog Method in Usercontrol

(When I tried to call from Usercontrol I am getting Error )

So How can I call Async await Show Dialog Methods in Usercontrol in wpf

**Comment by thoemmi** [comment]
`ShowMessageAsync` is an extension method for `MetroWindow`, so this code should work:
```csharp
var metroWindow = (Application.Current.MainWindow as MetroWindow); 
await metroWindow.ShowMessageAsync(title, message);
```

**Comment by akshithrajesh** [comment]
Outstanding You rock

**Comment by akshithrajesh** [comment]
How to call ShowMessageDialog in user control 

  public async void ShowMessageDialog(object sender, RoutedEventArgs e)
        {
            // This demo runs on .Net 4.0, but we're using the Microsoft.Bcl.Async package so we have async/await support
            // The package is only used by the demo and not a dependency of the library!
            var mySettings = new MetroDialogSettings()
            {
                AffirmativeButtonText = "Hi",
                NegativeButtonText = "Go away!",
                FirstAuxiliaryButtonText = "Cancel",
                ColorScheme = MetroDialogOptions.ColorScheme
            };

            MessageDialogResult result = await this.ShowMessageAsync("Hello!", "Welcome to the world of metro!",
                MessageDialogStyle.AffirmativeAndNegativeAndSingleAuxiliary, mySettings);

            if (result != MessageDialogResult.FirstAuxiliary)
                await this.ShowMessageAsync("Result", "You said: " + (result == MessageDialogResult.Affirmative ? mySettings.AffirmativeButtonText : mySettings.NegativeButtonText +
                    Environment.NewLine + Environment.NewLine + "This dialog will follow the Use Accent setting."));
        }
