### ISSUE TITLE
How to Change user controls Dynamically on Buttonclick

### ISSUE THREAD

**Issue by akshithrajesh** [MahApps/MahApps.Metro#2233]
Change view Dynamically on Button click in MahApps  I had created custom Usercontrols for my Application Now I need to change the usercontrols on Button click Event

**Comment by thoemmi** [comment]
I don't think that this is an issue of **MahApps.Metro**.

**Comment by akshithrajesh** [comment]
How can I achieve or call it

**Comment by akshithrajesh** [comment]
Could you please let me know how Can I achieve it I wasted huge time just because of it.

**Comment by thoemmi** [comment]
This is not a general support forum for learning WPF. Buy a book, google for it, or ask at [Stackoverflow](https://stackoverflow.com).
