### ISSUE TITLE
[Help] Different colors for data validation

### ISSUE THREAD

**Issue by Andyi19** [MahApps/MahApps.Metro#2234]
I'm trying to get 3 different colors for data validation, for example:
Red (already exists): Error
Orange: Warning
Green: OK

The colors are all in .../Styles/Colors.xaml. I have added my colors and created a ValidationWarningTemplate.xaml und ValidationConfirmTemplate.xaml (just colors changed from ValidationErrorTemplate.xaml). The problem is, that the templates are hard-coded in the controls, ex. from Controls.TextBox.xaml:
<Setter Property="Validation.ErrorTemplate"
Value="{DynamicResource ValidationErrorTemplate}" />

I can't change this to my template as I want to show all of them, depending on certain conditions.

Is there any easy way to add all templates, or can I even somehow just access the template from my project and change the colors?

Thank you all :)

**Comment by punker76** [comment]
@Andyi19 you can change it to what you want, it's not "hardcoded".

change it in style

```
<Setter Property="Validation.ErrorTemplate"
                Value="{DynamicResource CustomValidationErrorTemplate}" />
```

and it's also changable by your own triggers.

**Comment by Andyi19** [comment]
Thanks, working now

**Comment by punker76** [comment]
:+1:
