### ISSUE TITLE
ControlsHelper design time error on Button

### ISSUE THREAD

**Issue by jseger** [MahApps/MahApps.Metro#2237]
I'm getting a design time error on a button.  ControlsHelper does not have a public property named ContentCharacterCasing.

Version 1.1.3.234

<Button Content="Help" Command="{Binding NavigateCommand}" CommandParameter="Help"/>

**Comment by punker76** [comment]
@jseger please try cleaning up obj/bin folders and maybe clear the visual studio designer cache, after that make a rebuild.

**Comment by jseger** [comment]
I'm now using 1.1.2.  But I think I know what might have caused it.  I am separating the project into modules and I wasn't loading the resource dictionaries in the project.  I was only loading them in the main project.  That's why I could still run it without error.
