### ISSUE TITLE
Add padding to window icons

### ISSUE THREAD

**Issue by bloritsch** [MahApps/MahApps.Metro#2242]
The MetroWindow title bar is not a standard size for icons.  We had an icon that looked sharp with normal windows because it would select the 16x16 icon and add space around the image so it was centered.  The MetroWindow instead scales the image to fit the full square edge to edge, but the title bar isn't big enough to trigger the more detailed 32x32 image that's part of the icon.

As a temporary stop gap I had to create a DrawingImage with a rectangle geometry under the image I wanted.  It allowed me to use the cooler vector images, but this is what my window declaration looked like:

    <controls:MetroWindow>
        <controls:MetroWindow.Icon>
            <DrawingImage>
                <DrawingImage.Drawing>
                    <DrawingGroup>
                    <GeometryDrawing Brush="Transparent">
                        <GeometryDrawing.Geometry>
                            <RectangleGeometry Rect="0,0,72,72"/>
                        </GeometryDrawing.Geometry>
                    </GeometryDrawing>
                    <GeometryDrawing Brush="{StaticResource IconColorBrush}" Geometry="F1 .... Z"/>
                    </DrawingGroup>
                </DrawingImage.Drawing>
            </DrawingImage>
        </controls:MetroWindow.Icon>
    </controls:MetroWindow>

I got the effect I was going for, and if I want I can independently change the foreground and background colors.  However, it would be really nice if I could simply specify an `IconPadding` or an `IconArrange` and specify "Stretch" or "Center" to handle the heavy lifting for me.

**Comment by punker76** [comment]
@bloritsch have you seen the `IconTemplate` property? it's maybe what you need... (also used in the main demo)

**Comment by bloritsch** [comment]
So with the IconTemplate I can stick the ImageSource in a Grid and let that do the centering....  Hmmm.

I didn't see that as part of the API or as part of the writeup on the MetroWindow (quick guide or Controls/MetroWindow).  Some generated API docs would be awesome.  I find myself constantly opening up the GitHub link to examine code and check for the names of resources.

**Comment by thoemmi** [comment]
The [default `IconTemplate`](https://github.com/MahApps/MahApps.Metro/blob/master/MahApps.Metro/Themes/MetroWindow.xaml#L607-L617) uses the [`MultiFrameImage`](https://github.com/MahApps/MahApps.Metro/blob/master/MahApps.Metro/Controls/MultiFrameImage.cs) control, which is expected to select the [best matching size](https://github.com/MahApps/MahApps.Metro/blob/master/MahApps.Metro/Controls/MultiFrameImage.cs#L60-L62) from the icon. Is anything wrong with this algorithm?

**Comment by bloritsch** [comment]
It's stretching the icon rather than centering it if the best match is between sizes.  The behavior is different than with the stock Window control, which I think sets the icon image area to only 16x16.

**Comment by thoemmi** [comment]
Well, I could add a property to `MultiFrameImage` to not stretch the icon but use the original sizes. But I don't want to add another property to MetroWindow, you would have to specify a custom `IconTemplate` for that option.

@punker76 What do you think?

**Comment by bloritsch** [comment]
Sounds OK.  It might just be me, but it seems to be stretching to the first non-transparent pixel in the icon.  I'll see if I can get some screenshots together so you can see what I mean.

**Comment by thoemmi** [comment]
With the current implementation `MultiFrameImage` uses the smallest frame from the icon that is larger or equal to the available space and shrinks it to the available space.

For demonstration purposes I created this icon (all following images are in their original size and zoomed to 400%):
![image](https://cloud.githubusercontent.com/assets/73690/11567465/75f9092e-99e7-11e5-991a-2eb7fbb447c8.png) ![image](https://cloud.githubusercontent.com/assets/73690/11567708/976c0fd8-99e8-11e5-9b93-719fb686b3c1.png)


The available space is 30x30, so the algorithm takes the 32x32 frame and shrinks it:
![image](https://cloud.githubusercontent.com/assets/73690/11567498/8f05e644-99e7-11e5-9a50-b4dcec0a683e.png) ![image](https://cloud.githubusercontent.com/assets/73690/11567531/ac5523b8-99e7-11e5-8739-b553038d844b.png)

I changed the algoritm to select the largest frame smaller or equal to the available space and draws it in its original size:
![image](https://cloud.githubusercontent.com/assets/73690/11567646/3bb8e1fc-99e8-11e5-90f5-682d3d87527d.png) ![image](https://cloud.githubusercontent.com/assets/73690/11567666/5083bb48-99e8-11e5-8a26-491bff720bb1.png)

Actually I don't know what the lesser of two evils :confused: 
/cc @punker76

**Comment by bloritsch** [comment]
I wonder if the true problem is the algorithm used for scaling the icon.
I'm working on an application on an unconnected network so there's issues
with getting proper screenshots or blessed code snippets.  I have a couple
other utilities to support a website on the internet where I'm using
MahApps.Metro and the icon issue boils down to how sharp it looks.

With the stock window, the icon is stretched, but it still looks sharp and
distinct.  However, the same icon in a MetroWindow is blocky and muddled
looking.  I ran across a couple things that might be the real culprit:

http://10rem.net/blog/2010/05/01/crappy-image-resizing-in-wpf-try-renderoptionsbitmapscalingmode

http://www.hanselman.com/blog/BeAwareOfDPIWithImagePNGsInWPFImagesScaleWeirdOrAreBlurry.aspx

The first one suggests using bitmap scaling mode.

The second one suggests that you account for the DPI flags embedded in PNGs
and force the PNG to be evaluated as 96 DPI (the definition of a WPF
display unit).  For the record, ICO images can contain PNGs and when you
use something like GIMP to make them it's probably embedding PNGs.

I have a feeling the latter may be the real issue here.

**Comment by punker76** [comment]
@thoemmi I'm with your second solution with an additional property on `MultiFrameImage`, cause we can...
- use
```xaml `IconBitmapScalingMode` and `IconEdgeMode` on `MetroWindow`
RenderOptions.BitmapScalingMode="{Binding IconBitmapScalingMode, Mode=OneWay, RelativeSource={RelativeSource FindAncestor, AncestorType={x:Type Controls:MetroWindow}}}"
RenderOptions.EdgeMode="{Binding IconEdgeMode, Mode=OneWay, RelativeSource={RelativeSource FindAncestor, AncestorType={x:Type Controls:MetroWindow}}}"
```
- and/or let the user create there own `IconTemplate` with a `MultiFrameImage` where the user can change the property to what he want

**Comment by bloritsch** [comment]
Works for me.  Explicitly setting the height and width in the icon area affects the size of the icon in the task bar, but that's essentially what we ended up doing for the time being.

**Comment by punker76** [comment]
@thoemmi Can I close this? Or should we do something here?

**Comment by thoemmi** [comment]
Sorry, I've totally forgotten this issue. Why I'm not the assignee? 😜 
Let me have a closer look next weekend, ok?

**Comment by punker76** [comment]
@thoemmi 👍
