### ISSUE TITLE
Not an issue, just a...

### ISSUE THREAD

**Issue by punker76** [MahApps/MahApps.Metro#2243]
He,

I just realized, that MahApps.Metro is maybe used more than once (e.g. [Xamarin Inspector](https://blog.xamarin.com/inspect-visualize-and-debug-your-app-live/)).
It can be also used with other awesome third party libs (e.g. [Material Design In XAML Toolkit](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit)) as well...

So, give us some feedback...

What I mean: give us a short description of your app or lib or something else with a cool nice looking (png) screenshot and put it here as answer, so we can add it to our cool [website](http://mahapps.com)...

And by the way, thx to all contributors, users and testers and...

THX

Jan

**Comment by punker76** [comment]
@/all really? no one? ...mh... :disappointed:

**Comment by thoemmi** [comment]
Well, I use MahApps.Metro in several small applications but most of them are for internal use only. The only public application I wrote using MA.M is [Solutionizer](https://github.com/thoemmi/Solutionizer).

Additionally I wrote another small MVVM library, [TinyLittleMvvm](https://github.com/thoemmi/TinyLittleMvvm). I was sick writing the same boilerplate code again and again :laughing:

**Comment by dsaf** [comment]
We have used it in two financial applications internally and they look good, but the company is strict and I am afraid to share any screenshots. It's very pleasant to use WPF after having to deal with Angular and HTML.

**Comment by moser96** [comment]
I'm using Mahapps for my school project which calls James. It's currently under construction, but you can use my screenshots if you like them ;).

James can help you browsing your files and you can make your ohne workflows for it. Basically something like https://www.alfredapp.com/ for windows ;)
![01](https://cloud.githubusercontent.com/assets/13469452/11918132/09dc652e-a725-11e5-91b7-eccaacc6fef8.PNG)
![02](https://cloud.githubusercontent.com/assets/13469452/11918133/09f5b4a2-a725-11e5-9d20-17ca44d1057d.PNG)
![03](https://cloud.githubusercontent.com/assets/13469452/11918134/09fead5a-a725-11e5-8ea5-e92dacd85b30.PNG)

**Comment by CADbloke** [comment]
I'm going to use it for www.tvCAD.tv. Today is day zero so I have no bugs. Tomorrow is another day.
