### ISSUE TITLE
Context Menu Theme not Getting Updated

### ISSUE THREAD

**Issue by jammerxd** [MahApps/MahApps.Metro#2244]
Hello,
I have a commandwindow button that has the appbar_settings icon on it and it has a contextmenu bound to it and with the help of a helper, it is bound to the  left mouse button. this button on the window changes the theme and accents. The only downside is that the context menu only updates themes when right clicked after a changed theme. If I continue to left click, the old theme is still visible on the context menu and looks ugly. 

Code for changing theme: https://gist.github.com/jammerxd/b6c2f3075d059d3e5a4d

Code for XAML: https://gist.github.com/jammerxd/e7737e6fa442944ef8ba

Code for the ContextMenuLeftClockHelper: https://gist.github.com/jammerxd/3ad2477a29648522a675

I am not sure if that helps or not, but there is definitely something I'm doing wrong.

**Comment by bloritsch** [comment]
I've had issues with the stock ThemeManager.  The basic approach that it takes is that it will load merged dictionaries for the theme/accent you pick, but only if the application is set up the right way.  It first checks the current window, then the current application.

If you include your BaseLight/BaseDark and accent color resources in your App.xaml or Window definition, the ThemeManager can't seem to unload it.  I essentially wrote an application specific wrapper to the theme manager to handle all this for the way my app was set up.

I looked at your XAML, and your styles do include the BasedOn attribute, just make sure that the resource dictionary for the MahApps Controls.xaml is accessible from that resource.  If not, another way to define it that should work with anything is to declare it like this:

    <Style x:Key="AppThemeMenuItemStyle"
                   TargetType="{x:Type MenuItem}"
                   BasedOn="{DynamicResource {x:Type MenuItem}}">

Essentially you are extending the style for MenuItem as it is currently defined.  By making that declaration DynamicResource you are making the code less sensitive to the order of how things got overridden.  When you include your Controls.xaml resource dictionary it's free to style your menu items without problem.

**Comment by punker76** [comment]
I think you need the x:Shared0"False" on you Ellipses. I close this for now, feel free to reopen it if it's still an issue.

**Comment by yoker** [comment]
get preview theme contextmenu after click on button. if i right click on label first, i got updated theme contextmenu when i click the button.

XAML:
`
<mahapps:MetroWindow x:Class="WpfApplication1.Window1"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:mahapps="http://metro.mahapps.com/winfx/xaml/controls"
        BorderThickness="0" GlowBrush="Red"
        Title="test contextmenu" Height="150" Width="300">
    <DockPanel>
        <StackPanel DockPanel.Dock="Bottom" Orientation="Horizontal" HorizontalAlignment="Center" Margin="0 10" Height="30">
            <Button Content="open contextmenu" Click="Button_Click" Margin="5 0"/>
            <Button Content="change theme &amp; accent" Click="Button_Click_1" Margin="5 0"/>
        </StackPanel>
        <Label x:Name="menulabel" Content="test menu" Background="AliceBlue">
            <Label.ContextMenu>
                <ContextMenu>
                    <MenuItem Header="Menu 1">
                        <MenuItem Header="Submenu 1" />
                        <MenuItem Header="Submenu 2" />
                    </MenuItem>
                    <MenuItem Header="Menu 2" />
                </ContextMenu>
            </Label.ContextMenu>
        </Label>
    </DockPanel>
</mahapps:MetroWindow>
`

code behind:
`
using MahApps.Metro;
using MahApps.Metro.Controls;
using System.Windows;

namespace WpfApplication1
{
    public partial class Window1 : MetroWindow
    {
        public Window1()
        {
            InitializeComponent();
        }
        private void Button_Click(object sender, RoutedEventArgs e)
        {
            menulabel.ContextMenu.IsOpen = !menulabel.ContextMenu.IsOpen;
        }
        private void Button_Click_1(object sender, RoutedEventArgs e)
        {
            var theme = ThemeManager.DetectAppStyle(Application.Current);
            var appTheme = ThemeManager.GetAppTheme(theme.Item1.Name == "BaseDark" ? "BaseLight" : "BaseDark");
            var appAccent = ThemeManager.GetAccent(theme.Item2.Name == "Red" ? "Blue" : "Red");
            ThemeManager.ChangeAppStyle(Application.Current, appAccent, appTheme);
        }
    }
}
`

**Comment by BornToBeRoot** [comment]
I have the same problem as @yoker when opening the context from a notify icon

```csharp
 private void NotifyIcon_MouseDown(object sender, System.Windows.Forms.MouseEventArgs e)
{
      if (e.Button == MouseButtons.Right)
      {
           System.Windows.Controls.ContextMenu trayMenu = (System.Windows.Controls.ContextMenu)FindResource("contextMenuNotifyIcon");
               trayMenu.IsOpen = true;
       }
 }
```

@punker76  maybe you can re-open the issue

**Comment by punker76** [comment]
@BornToBeRoot Please create a new issue. And a short app with this scenario would be cool. Thx

**Comment by punker76** [comment]
@BornToBeRoot The trick is to set the `PlacementTarget` too at the click event...

private void Button_Click(object sender, RoutedEventArgs e)
{
    menulabel.ContextMenu.PlacementTarget = sender as UIElement;
    menulabel.ContextMenu.IsOpen = true;
}

![contextmenu](https://cloud.githubusercontent.com/assets/658431/21396441/8d33b58e-c7a0-11e6-8cd6-1bcdec150655.gif)

**Comment by BornToBeRoot** [comment]
@punker76 This wont fix it... the background is still white when changing the theme to dark.

![image](https://cloud.githubusercontent.com/assets/16019165/21396928/28fed092-c7a2-11e6-86c4-d4dcd7a8182a.png)

Only restarting the application fix it.
![image](https://cloud.githubusercontent.com/assets/16019165/21396984/571f05aa-c7a2-11e6-8262-b0a7682e295f.png)

**Comment by punker76** [comment]
@BornToBeRoot PR added to your app.
