### ISSUE TITLE
Visual Studio 2015 - Flyout - XAML Designer Not working.

### ISSUE THREAD

**Issue by ProIcons** [MahApps/MahApps.Metro#2246]
Well i get a strange error while i'm opening my XAML Designer on VS2015

__Cannot add instance of type 'SetFlyoutOpenAction' to a collection of type 'TriggerActionCollection'. Only items of type 'T' are allowed__

I Get this error, but i'm able to Compile and run the programm without a problem. Everything works like a charm on compiling, but i cannot design anything while i have Flyout on my xaml..

It's just saying: Main.xaml cannot be edited in the Design view.

This error is happening sometimes in VS2013, but designer never broke. In VS2013 after compile error gone away.

**Comment by ProIcons** [comment]
<Controls:Flyout IsOpen="True" IsPinned="True" CloseButtonVisibility="Collapsed">
                <Grid Margin="5,0,0,0">
                    <Grid Margin="0,-71,0,0" Height="204" VerticalAlignment="Top">
                        <Image Height="120" VerticalAlignment="Bottom" Margin="0,0,0,84" Source="Resources/header_logo_el.png"/>
                        <TextBlock Text="Νικόλαος Μαυρόπουλος" FontSize="16" TextAlignment="Center" TextWrapping="Wrap" FontWeight="Bold" Margin="0,138,0,0" Height="66" VerticalAlignment="Top"  />
                    </Grid>
                    <Grid Margin="0,132,0,37">
                        <Controls:MetroTabControl x:Name="TabCtrl" HorizontalAlignment="Left" Width="180" Margin="15,0,-10,0" TabStripPlacement="Left">
                            <Controls:MetroTabItem TabIndex="0" x:Name="Tab1B" Header="Στοιχεία" Width="175"/>
                            <Controls:MetroTabItem TabIndex="1" x:Name="Tab2B" Header="Πρόγραμμα" Width="175"/>
                            <Controls:MetroTabItem TabIndex="2" x:Name="Tab3B" Header="Βαθμοί" Width="175"/>
                            <Controls:MetroTabItem TabIndex="3" x:Name="Tab4B" Header="Mail" Width="175"/>

                        </Controls:MetroTabControl>
                    </Grid>
                    <Button Click="Button_Click" Content="Button" HorizontalAlignment="Left" Margin="48,483,0,0" VerticalAlignment="Top" Width="75" RenderTransformOrigin="0.227,0.773"/>
                </Grid>
            </Controls:Flyout>

**Comment by punker76** [comment]
@ProIcons I tested your xaml code in my VS 2015 designer (in the MahApps main demo) and all works fine™. I just googled about it and found these two things, maybe its the same like yours
- https://social.msdn.microsoft.com/Forums/en-US/8caf3bcb-3e07-4d08-a86e-c7068e8e8305/upgrasded-to-net-45-and-now-get-cannot-add-instance-of-xxx-to-a-collection-of-type?forum=wpf
- http://stackoverflow.com/a/32492987/920384
