### ISSUE TITLE
Show window without effects

### ISSUE THREAD

**Issue by Pekshev** [MahApps/MahApps.Metro#2247]
Hi. I'm using metrowindow to show my own message box. What should be done to show a window without openning effect?

**Comment by punker76** [comment]
@Pekshev so what opening effect do you mean?

**Comment by Pekshev** [comment]
Forgive me if I write it is not clear - I use Google translator
I am referring to the effect of the appearance of the window. Sliding Apparently it. I think that because of the effect of the window opens a little longer (a few miilisekund, but it is noticeable). And I need a window to appear quickly (as standrat messagebox)

**Comment by punker76** [comment]
@Pekshev You can turn off the sliding effect by setting `WindowTransitionsEnabled="False"` on the MetroWindow.

https://github.com/MahApps/MahApps.Metro/blob/master/MahApps.Metro/Controls/MetroWindow.cs#L65

**Comment by Pekshev** [comment]
Thanks. That's what I need

**Comment by punker76** [comment]
:+1:
