### ISSUE TITLE
NumericUpDown PreviewMouseDown event

### ISSUE THREAD

**Issue by fredericoregateiro** [MahApps/MahApps.Metro#2249]
Hello,

Is there a way to handle the click event on the NumericUpDown control, only on the textbox, and ignore the up dand down buttons?
I need to show a custom popup, only when the user clicks on the textbox, and if i handle the PreviewMouseDown event, it's also fired when the user clicks on the up and down buttons.

Thanks,
Frederico

**Comment by xxMUROxx** [comment]
That is not the desired behavior of any WPF-control.
All base-controls fire the *PreviewMouseDown*Event with the control itself as *sender*. If you try to subscribe to the event on a *DatePicker* you will see that there is no difference whether you click on a *date* or *month* button.

**Comment by fredericoregateiro** [comment]
Yes i know, i was just wondering if there was a way to tell the difference.
I'm using these control on a app that should respond to click events differently if the user click on the textbox or the up/down buttons.
If the the user click on the textbox i could open a custom keypad popup.
The app is going to run on a POS machine, and the user doesn't always have a physical keyboard.

Thanks,
Frederico
