### ISSUE TITLE
Validation Errors Showing after formload Event. I need to show Error Message after Button CLick

### ISSUE THREAD

**Issue by akshithrajesh290** [MahApps/MahApps.Metro#2251]
Sample MainwindowViewModel Code

   DateTime? _datePickerDate;
        public DateTime? DatePickerDate
        {
            get { return this._datePickerDate; }
            set
            {
                if (Equals(value, _datePickerDate))
                {
                    return;
                }

                _datePickerDate = value;
                RaisePropertyChanged("DatePickerDate");
            }
        }

        public string this[string columnName]
        {
            get
            {
               
                if (columnName == "IntegerGreater10Property" && this.IntegerGreater10Property < 10)
                {
                    return "Number is not greater than 10!";
                }

                if (columnName == "DatePickerDate" && this.DatePickerDate == null)
                {
                    return "No Date given!";
                }

                if (columnName == "FirstName")
                {
                    if (string.IsNullOrEmpty(FirstName) || FirstName.Length < 3)
                        return "Please Enter  First Name";
                }
                if (columnName == "LastName")
                {
                    if (string.IsNullOrEmpty(FirstName) || FirstName.Length < 3)
                        return "Please Enter Last Name";
                }

                return null;
            }
        }

TextBox  Code

     <TextBox  Name="txt_LA_FirstName"
                         Controls:TextBoxHelper.Watermark="First Name"
                         Controls:TextBoxHelper.UseFloatingWatermark="True"
                         ToolTip="First Name" Grid.Row="2" Grid.Column="1" VerticalAlignment="Center" HorizontalAlignment="Stretch"  Text="{Binding FirstName, ValidatesOnDataErrors=True, UpdateSourceTrigger=PropertyChanged, NotifyOnValidationError=True}" />
![error](https://cloud.githubusercontent.com/assets/16162616/11607444/b44ffa8a-9b6c-11e5-9d4c-b0efa5d34f1c.png)

**Comment by punker76** [comment]
-> http://stackoverflow.com/q/34103675/920384
