### ISSUE TITLE
Resource with the name {x} cannot be found

### ISSUE THREAD

**Issue by taori** [MahApps/MahApps.Metro#2254]
I'm getting this error in design time for my static resources.

Markup: 
```xaml
<UserControl x:Class="ImmoCrawler.Client.Views.Sections.CrawlerDataKeyMasterView"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:cal="http://www.caliburnproject.org"
             xmlns:vm="clr-namespace:ImmoCrawler.Client.ViewModels.Sections"
             xmlns:controls="http://metro.mahapps.com/winfx/xaml/controls"
             cal:Bind.AtDesignTime="True"
			 x:Name="Self"
			 d:DataContext="{d:DesignInstance vm:CrawlerDataKeyMasterViewModel}"
             mc:Ignorable="d" 
             d:DesignHeight="300" d:DesignWidth="300">
	<DockPanel>
		<Button cal:Message.Attach="Save"  Content="Speichern" DockPanel.Dock="Bottom" Margin="0,10,0,0"></Button>
		<TextBox  Text="{Binding Path=InsertionName, Mode=TwoWay, ValidatesOnNotifyDataErrors=True, UpdateSourceTrigger=PropertyChanged}"
                  controls:TextBoxHelper.Watermark="Feldname"
				  ToolTip="Feldname"
		          DockPanel.Dock="Bottom"
		          FontSize="20">
			<TextBox.InputBindings>
				<KeyBinding Key="Enter" Command="{Binding Path=InsertCommand}"></KeyBinding>
			</TextBox.InputBindings>
		</TextBox>

		<ListView ItemsSource="{Binding Path=Keys}">
			<ListView.ItemContainerStyle>
				<Style TargetType="{x:Type ListViewItem}" BasedOn="{StaticResource MetroListViewItem}" >
					<Setter Property="Margin" Value="0,0,0,3" />
				</Style>
			</ListView.ItemContainerStyle>
			<ListView.ItemTemplate>
				<DataTemplate DataType="vm:CrawlerKey">
					<Grid>
						<Grid.ColumnDefinitions>
							<ColumnDefinition Width="*"/>
							<ColumnDefinition Width="Auto"/>
						</Grid.ColumnDefinitions>

						<TextBlock Grid.ColumnSpan="2" Padding="4" FontSize="18" Text="{Binding Path=Name}" Foreground="{StaticResource TextBrush}" Background="{StaticResource AccentColorBrush}"></TextBlock>
						<Border Grid.Column="1" Padding="10" BorderBrush="Black" BorderThickness="1,0,0,0">
							<Border.InputBindings>
								<MouseBinding MouseAction="LeftClick" 
									CommandParameter="{Binding Path=.}" 
									Command="{Binding ElementName=Self, Path=DataContext.RemoveCommand}" />
							</Border.InputBindings>
							<Rectangle Fill="White" Width="10" Height="10" >
								<Rectangle.OpacityMask>
									<VisualBrush Visual="{StaticResource appbar_close}" Stretch="Fill" />
								</Rectangle.OpacityMask>
							</Rectangle>
							<Border.Style>
								<Style TargetType="Border">
									<Setter Property="Background" Value="{StaticResource AccentColorBrush4}" />
									<Style.Triggers>
										<Trigger Property="IsMouseOver" Value="True">
											<Setter Property="Background" Value="{StaticResource ControlsValidationBrush}" />
										</Trigger>
									</Style.Triggers>
								</Style>
							</Border.Style>
						</Border>
					</Grid>
				</DataTemplate>
			</ListView.ItemTemplate>
		</ListView>
	</DockPanel>
</UserControl>
```

The errors are reported for "AccentColorBrush" and "TextBrush"

- If i replace StaticResource with DynamicResource for those 2 keys, the errors disappear but the rendered result is incorrect.
- It does render just fine when the project is running with both dynamic and static resource for the 2.

design time with DynamicResource
![dynamicresource](https://cloud.githubusercontent.com/assets/5545184/11614184/ae9f709c-9c3a-11e5-8649-479bf7991aed.PNG)

actual rendering
![actualrendering](https://cloud.githubusercontent.com/assets/5545184/11614185/bf402f72-9c3a-11e5-803b-db5a5446f5fa.PNG)

This error started happening with the upgrade from 1.1.2 to 1.1.3 alpha 240, in case that helps tracking down the problem.

**Comment by xxMUROxx** [comment]
Don't bother with design time issues. In my case during design time sometimes the colors are displayed with correct background sometimes not. Seems to be a VS issue.
Furthermore I suggest you to use *DynamicResources* this gives you the possibility to change theme during runtime.

**Comment by taori** [comment]
*"Don't bother"* is not how issues are resolved. it works perfectly fine with 1.1.2. It does not with 1.1.3 alpha 240. So its obviously NOT a VS issue.

I also mentioned that i did try DynamicResources, which results in incorrect rendering as you can see in the 2 screenshots i provided

**Comment by punker76** [comment]
@taori @xxMUROxx Please, not another VS designer discussion here...

@taori

- Where are your resources defines?
- After changing to new MahApps it's good to clear the VS designer cache.
- The VS designer always killing me :-D

**Comment by taori** [comment]
@punker76 

- They are defined in the App.xaml file pretty much exactly like suggested in the "get started" docus.
- VS designer cache can be cleared seperately? I've only used clean solution. that usually resolved designer issues for me
- solution cleared
- Yup, i remember back in 2012 it was even more of a pain than now. Back then restarting VS fixed issues but clearing the solution didn't always fix it :)

**Comment by taori** [comment]
@punker76 Jump in = pull requests accepted? I'm willing to do it if you can give me a brief description of how to detect such design time issues (Haven't done it before).

My guess is i have to launch devenv with debugger attached and just listen to every exception?

**Comment by taori** [comment]
@punker76 alright... clean solution != delete bin/obj. sorry then

**Comment by CADbloke** [comment]
just leaving this here ... https://marketplace.visualstudio.com/items?itemName=Johan20D.KilltheWPFDesigner#overview
