### ISSUE TITLE
SpellCheck ContextMenuItems not appearing

### ISSUE THREAD

**Issue by ImaBrokeDude** [MahApps/MahApps.Metro#2257]
Because SpellCheck Context MenuItems cannot be styled, I wonder if they are not being added. I know there is a simple workaround: Override ContextMenuOpening and add them ourselves using the functions and properties available in SpellCheck. Could we add this as a behavior?

**Comment by punker76** [comment]
@ImaBrokeDude this is already available https://github.com/MahApps/MahApps.Metro/blob/master/MahApps.Metro/Controls/Helper/TextBoxHelper.cs#L42
