### ISSUE TITLE
ComboBox context menu.

### ISSUE THREAD

**Issue by ZhiCeYang** [MahApps/MahApps.Metro#2261]
Hi, thanks to develop such a useful tool for WPF developers! Now I got a situation is that I have a combo box, it allows people to edit, but I don't really want the context menu which prompt when I right click the input box. It is not work to set it's context menu property to null, I checked the code, the context menu is from the text box named "PART_EditableTextBox", so how can I remove it ? thank you!

**Comment by punker76** [comment]
@ZhiCeYang This will be possible with 1.4.0. You can then disable the ContextMenu.

```xaml
<ComboBox.ContextMenu>
    <ContextMenu IsEnabled="False"
                 Visibility="Collapsed" />
</ComboBox.ContextMenu>
```
