### ISSUE TITLE
Code Style (ReSharper)

### ISSUE THREAD

**Issue by xxMUROxx** [MahApps/MahApps.Metro#2270]
Does anybody uses ReSharper?

I think it would be interesting to modify the existing [MahApps.Metro.sln.DotSettings](https://github.com/MahApps/MahApps.Metro/blob/master/MahApps.Metro.sln.DotSettings) to have a neat way to cleanup the code using ReSharper. This will provide a code style that is overarching the complete project.

Until now I have seen following code style issues:
* private modifier is missing
* existence of unused using-directives
* number of blank lines (somtimes 1 blank line sometimes multiple)
* non-uniform curly brackets-placements (bracket on new line, bracket on same line)
* method order (no strict order according modifier, kind, name)

ReSharper provides a neat way to enforce - by showing solution errors - some rules. Furthermore by using *Code-Cleanup* the predefined code style is followed.

**Comment by punker76** [comment]
@xxMUROxx it's already on my todo list...

**Comment by punker76** [comment]
@xxMUROxx also the XAML style...

**Comment by xxMUROxx** [comment]
Below you see my current *.DotSettings* file that I use as global style for my projects.
[Settings.DotSettings.txt](https://github.com/MahApps/MahApps.Metro/files/61051/Settings.DotSettings.txt)

**Comment by sachokFoX** [comment]
for xaml code I am using https://visualstudiogallery.msdn.microsoft.com/3de2a3c6-def5-42c4-924d-cc13a29ff5b7 extension.

**Comment by xxMUROxx** [comment]
@sachokFoX same for me. Nice extension :+1:

**Comment by punker76** [comment]
@xxMUROxx just added, i close this, continued in #2350

**Comment by xxMUROxx** [comment]
@punker76 thanks
