### ISSUE TITLE
AnimationException was unhandled

### ISSUE THREAD

**Issue by sous2817** [MahApps/MahApps.Metro#2271]
Hello,

Over the last few alpha builds, I've been getting an AnimationException was unhanded error when trying to open a CustomDialog.  It doesn't happen on all CustomDialogs, but everything worked fine back in MahApps.Metro 1.1.3-ALPHA229.  I upgraded to ALPHA254 and started getting the error (and still there in ALPHA257).  

I'm not sure which version the error gets introduced.  I'll see about going through and trying to narrow it down.   For what it's worth, I'm not doing any animation, and like I said above, everything worked in ALPHA229.

The Exception Detalis:{"Cannot animate the 'MaxHeight' property on a 'System.Windows.Controls.Grid' using a 'System.Windows.Media.Animation.DoubleAnimation'. For details see the inner exception."}

InnerException: {"'System.Windows.Media.Animation.DoubleAnimation' cannot use default origin value of 'Infinity'."}

Please let me know if there's any additional details I can provide.

Thanks!

***Update:  The breaking change was introduced in ALPHA237.  ALPHA236 it works fine.  Installing ALPHA237 throws up the AnimationException.  Hope that helps narrow it down!  Let me know if there's anything else I can provide.

**Comment by punker76** [comment]
@sous2817 dou you have any custom styles for e.g. TextBox? cause there was a inner style change with https://github.com/MahApps/MahApps.Metro/commit/1919458bce35ba5c5815e2c9982721836263cdb2

**Comment by sous2817** [comment]
@punker76 Here is the view that is throwing up the error.  Don't think it's anything too complicated, anything grab you as being problematic?

    <dialogs:CustomDialog x:Class="DataIntegrationTool.MainProgram.Dialogs.OpenFile.OpenFileDialogView"
                      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                      xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
                      xmlns:dialogs="clr-namespace:MahApps.Metro.Controls.Dialogs;assembly=MahApps.Metro"
                      xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
                      xmlns:metro="http://metro.mahapps.com/winfx/xaml/controls"
                      DataContext="{Binding OpenFileDialog,
                                            Source={StaticResource Locator}}"
                      d:DesignHeight="300"
                      d:DesignWidth="300"
                      mc:Ignorable="d">
    <DockPanel LastChildFill="False">
        <TextBox Margin="0,0,0,2.5"
                 DockPanel.Dock="Top"
                 Style="{StaticResource OpenFileMetroTextBox}"
                 Text="{Binding Path=FileName,
                                Mode=TwoWay,
                                UpdateSourceTrigger=PropertyChanged}"
                 metro:TextBoxHelper.ButtonCommand="{Binding OpenFileDialogCommand}"
                 metro:TextBoxHelper.Watermark="Enter full file path or press folder icon..." />
        <TextBox Margin="0,2.5,0,0"
                 DockPanel.Dock="Top"
                 Text="{Binding Path=ShortName,
                                Mode=TwoWay,
                                UpdateSourceTrigger=PropertyChanged}"
                 metro:TextBoxHelper.UseFloatingWatermark="True"
                 metro:TextBoxHelper.Watermark="Short file descrpition" />
    </DockPanel>
    <dialogs:CustomDialog.DialogBottom>
        <Grid MinHeight="0"
              MaxHeight="50"
              Margin="0,0,0,5">
            <Grid.ColumnDefinitions>
                <ColumnDefinition />
                <ColumnDefinition />
                <ColumnDefinition />
                <ColumnDefinition />
                <ColumnDefinition />
            </Grid.ColumnDefinitions>
            <Button Grid.Column="1"
                    Command="{Binding SendFilePathMessageCommand}"
                    Content="OK"
                    DockPanel.Dock="Top" />
            <Button Grid.Column="3"
                    Command="{Binding SendCancelMessageCommand}"
                    Content="Cancel"
                    DockPanel.Dock="Top" />
        </Grid>

    </dialogs:CustomDialog.DialogBottom>
    </dialogs:CustomDialog>

**Comment by sous2817** [comment]
@punker76  Bah!  Clearly something I did.  I was getting a resource error so I took the style out of the source code and added it to my project and referenced that, which got rid of the error.  But since I didn't update the style w/ the changes you made in subsequent releases, it was getting angry.  If I get the latest alpha build, don't use my style but use yours, all seems to be working fine. 

Now I just have to figure out how to get the icon I was using in the metro:TextBoxHelper.ButtonContent...

**Comment by punker76** [comment]
@sous2817 I think the problem is the name of your Grid in the template, it should not named `contentPresenter`...

**Comment by punker76** [comment]
@sous2817 I will change the inner names to `PART_ContentPresenter` soon, hopefully without breaking anything...

**Comment by sous2817** [comment]
@punker  Changed the grid names and still getting error.  

For what it's worth, using the most recent version and setting the style to:

    Style="{DynamicResource MetroButtonTextBox}"

it works fine.  I'm not married to how I set the style, I did it the way I outlined above to get a "folder" image for the button using a Path.  I'm going to try the approach outlined here (https://github.com/MahApps/MahApps.Metro/issues/849) and use a .png instead.

**Comment by sous2817** [comment]
Ok, this worked for me using the latest ALPHA build.  Sorry for taking up your time:

    <TextBox Margin="0,0,0,2.5"
                 DockPanel.Dock="Top"
                 Style="{DynamicResource MetroButtonTextBox}"
                 Text="{Binding Path=FileName,
                                Mode=TwoWay,
                                UpdateSourceTrigger=PropertyChanged}"
                 metro:TextBoxHelper.ButtonCommand="{Binding OpenFileDialogCommand}"
                 metro:TextBoxHelper.Watermark="Enter full file path or press folder icon...">
            <metro:TextBoxHelper.ButtonContent>
                <Canvas Width="15"
                        Height="15"
                        Clip="F1 M 0,0L 48,0L 48,48L 0,48L 0,0">
                    <Path Width="15.7781"
                          Height="15.7781"
                          Data="F1 M 16.6668,20L 13,28.5336L 13,16L 23,16L 23,15C 23,13.8954 23.8954,13 25,13L 32,13C 33.1046,13 35,14.8954 35,16L 35,20L 16.6668,20 Z M 35,32L 28,32L 13,32L 17.5833,21L 39.5833,21L 35,32 Z "
                          Fill="{DynamicResource TextBrush}"
                          Stretch="Fill" />
                </Canvas>
            </metro:TextBoxHelper.ButtonContent>
    </TextBox>

**Comment by punker76** [comment]
@sous2817 no worries
