### ISSUE TITLE
Corner resize issues with GlowBrush enabled

### ISSUE THREAD

**Issue by theznerd** [MahApps/MahApps.Metro#2279]
This issue was previously reported (https://github.com/MahApps/MahApps.Metro/issues/1462), but was marked closed until a better bug report was produced.  Not sure if opening a new issue is the preferred method, so feel free to close this and reopen the other issue if that is preferred.

Using: .NET 4.6.1, Windows 10, MahApps.Metro 1.1.2

When attempting to corner resize a MetroWindow with a GlowBrush the window will only resize in one direction IF the resize is selected on the outer boundary of the corner cursor (NSEW and NWSE).  Inside the boundary resizing works as expected.  I've taken a screen capture of the issue and placed it here:

http://gfycat.com/OffbeatSomeHorsechestnutleafminer

**Comment by punker76** [comment]
@theznerd please try this with the latest alpha version, which is also available via nuget, cause the issue should be fixed in there...

**Comment by theznerd** [comment]
@punker76 Still seems to be an issue in 1.1.3-ALPHA257

**Comment by punker76** [comment]
@theznerd Do you use a higher DPI setting?

**Comment by theznerd** [comment]
Yes I do now actually - didn't even think to mention that, but it makes sense why I didn't notice it in my old development machine.

**Comment by punker76** [comment]
@theznerd found it and fixed it :-D
