### ISSUE TITLE
TextBoxHelper.ClearTextButton show error

### ISSUE THREAD

**Issue by Cologler** [MahApps/MahApps.Metro#2280]
if I add this as resource in App.xaml, `TextBoxHelper.ClearTextButton` will display wrong.

``` xml
<Style TargetType="TextBlock">
    <Setter Property="FontFamily"
            Value="Microsoft YaHei UI Light" />
</Style>
```

**Comment by punker76** [comment]
@Cologler it's not recommended to make a default TextBlock syle for the hole application, this have some bad side effect e.g. to TabItems...

**Comment by Cologler** [comment]
Could you specify the font for `TextBoxHelper.ClearTextButton`?
