### ISSUE TITLE
[Feature Request] DateTimePicker?

### ISSUE THREAD

**Issue by xxMUROxx** [MahApps/MahApps.Metro#2281]
Dear Community: I have created a DateTimePicker-control with MahApps style. Is there any interest in adding this control to MahApps?

![datepickersample](https://cloud.githubusercontent.com/assets/4341039/11932696/993e32ec-a7f7-11e5-8645-a023e434706c.png)

**Comment by Allann** [comment]
looks good.  looking forward to trying it out.  well done and thanks.

**Comment by p76984275** [comment]
:+1: A promising and practical feature. Hope MahApps can have this in the future.

**Comment by AndrewNoyes** [comment]
Dang, that looks sweet! Nice work
