### ISSUE TITLE
Is there a way to style the buttons inside a MessageDialog without replacing the ControlTemplate?

### ISSUE THREAD

**Issue by taori** [MahApps/MahApps.Metro#2283]
Basically i think the default focus visualization is too subtle and i'm wondering if there's a more convenient method of affecting the styling there.

**Comment by punker76** [comment]
@taori Yes, you can override it via the [CustomResourceDictionary](https://github.com/MahApps/MahApps.Metro/blob/master/MahApps.Metro/Controls/Dialogs/BaseMetroDialog.cs#L414) property.

**Comment by taori** [comment]
@punker76 ok, cool. looking forward to the documentation. right now intellisense is not picking it up yet because it's no dependency property. Hence documentation would indeed be useful.

**Comment by punker76** [comment]
@taori the custom dictionary can be set  in code behind on a custom settings which can be used for the message dialog

**Comment by smlacombe** [comment]
@punker76  Is there a documentation for the usage of CustomResourceDictionary ? I noticed that it is just a resource dictionary included in the BaseMetroDialog resource, I guess it must be useful for custom dialogs but I don't understand how it can be useful for overiding MessageDialog button style. I have also seen this [post ](http://stackoverflow.com/questions/30751663/how-to-change-mahapps-metro-dialog-content-template-width) but the provided solution has only the effect of overriding the BaseMetroDialogTemplate and not the MessageDialogTemplate. Am I missing something ?

Thanks
