### ISSUE TITLE
element is shaking when i drag it

### ISSUE THREAD

**Issue by robert0814** [MahApps/MahApps.Metro#2284]
I am using ZoomControl which belongs to WPF Extensions.
when I drag the rectangle from the sample, the rectangle shakes. if i change the metrowindow to normal window, it goes fine.
I have no idea how it comes.
u  could download code from https://wpfextensions.codeplex.com/
and try zoomcontrol. Drag the rectangle slowly. u will see it.

**Comment by punker76** [comment]
@robert0814 What do you mean with `shaking`? Can you try the latest Alpha version? Thx.

**Comment by robert0814** [comment]
the version is 1.1.2
when u move rectangle slowly, the rectangle will not move smoothly. it is
like the object moved from old position to a new position.
i hard to describe it, cos my english is very pool.
u could try wpfextensions from https://wpfextensions.codeplex.com/.


cheers
robert

**Comment by robert0814** [comment]
thx @punker76 , the problem has been fixed. my project has been updated to version 1.2.3, no such issue comes out.
please close this bug.
