### ISSUE TITLE
Validation Message does not display if window is maximized

### ISSUE THREAD

**Issue by taori** [MahApps/MahApps.Metro#2285]
![image](https://cloud.githubusercontent.com/assets/5545184/12065665/81d373c4-afdb-11e5-8338-07d76ce10fe2.png)
![image](https://cloud.githubusercontent.com/assets/5545184/12065673/953646f8-afdb-11e5-8120-20db461034ae.png)
![image](https://cloud.githubusercontent.com/assets/5545184/12065679/adda6d60-afdb-11e5-8a2b-b009720b86c4.png)

As visible in the screenshots the placement adapts correctly to insufficient rendering space on the right/left side of it, but can't deal with full screen. In this particular case placing the error label just above/below would be good i guess.

I have tried the suggestion here https://github.com/MahApps/MahApps.Metro/issues/2093#issuecomment-139153767 with Placement Bottom, but that didn't produce a different result as compared to screenshot number 3.

**Comment by DJmRek** [comment]
Run into the same issue. Do you find any way to cahnge the position?

**Comment by taori** [comment]
@DJmRek I ended using a validationsummary to gather validation errors. Doesn't help you unfortunately.
