### ISSUE TITLE
Titlebar tooltip no longer works in 1.2

### ISSUE THREAD

**Issue by mike-ward** [MahApps/MahApps.Metro#2286]
I set the title bar tooltip as follows:
```
        private void TitleBarTooltip()
        {
            var titleBar = GetTemplateChild("PART_TitleBar") as UIElement;
            var textBlock = titleBar?.GetDescendantByType<TextBlock>();
            var fileNameBinding = new Binding {Path = new PropertyPath("FileName"), Source = Editor};
            textBlock?.SetBinding(ToolTipProperty, fileNameBinding);
        }
```
This worked in 1.1.2

The values are not null so the property binding is set but there's no tooltip when I hover over the ttitle bar.

See https://github.com/mike-ward/Markdown-Edit (MainWindow.xaml.cs)

**Comment by punker76** [comment]
@mike-ward The problem is the thumb for the title dragging. It steals the hittest. I can bind a dependency property on the tooltip property of the thumb. only problem is, if it's used on the whole content.

**Comment by mike-ward** [comment]
OK, no worries. I'll add a icon or something...

**Comment by punker76** [comment]
@mike-ward can I help you with something other? what was the content of the tooltip? do you have maybe any other suggestion or solution?

**Comment by mike-ward** [comment]
I was using the hover to show the full document name. I'm thinking I'll just add it to the save button or maybe document stats when I add it. No worries.

**Comment by punker76** [comment]
@mike-ward :+1:
