### ISSUE TITLE
IsWindowDraggable broke starting in 1.2

### ISSUE THREAD

**Issue by TyBarthel** [MahApps/MahApps.Metro#2287]
Is this broke in 1.2 or did the behavior change?  I don't appear to be able to drag even a basic vanilla window by mouse clicking/dragging on any position except the title bar.

**Comment by iskenxan** [comment]
I just tested it out and it worked fine for me, if you check IsWindowDraggable property that you mentioned,  you will be able to drag and move the window , if you leave it unchecked , you can only resize it.

**Comment by Alkalinee** [comment]
@iskenxan yes, when you drag using the titlebar, but in version 1.1.2 it meant dragging from everywhere (for example if ShowTitleBar is false).

**Comment by TyBarthel** [comment]
@Alkalinee Yep, exactly.  @iskenxan set ShowTitleBar to false and you won't be able to move the window anywhere because the title bar is the only place to grab.

**Comment by iskenxan** [comment]
@Alkalinee Yeah , it only works for title bar , sorry about that

**Comment by xiperware** [comment]
Can replicate bug on win 10, create an empty MetroWindow with ShowTitleBar="False", run, can't drag window from anywhere, reverting to older version and it works fine.

**Comment by beachwalker** [comment]
Can replicate this, too.

ShowTitleBar="False" and you can't move the window bei drag the Titlebar.
Workaround: Set Title="". I use Style="{DynamicResource CleanWindowStyleKey}".

**Comment by TyBarthel** [comment]
I updated to 1.2.4, but still appear to not be able to drag a window outside of the title bar.

ShowTitleBar="False"
IsWindowDraggable="True"

**Comment by punker76** [comment]
@TyBarthel If you have controls in your window which are hittest visible, so there is no chance to drag the window.

**Comment by beachwalker** [comment]
works for me now with 1.2.4

**Comment by TyBarthel** [comment]
@punker76 I think something else might possibly be going on where something else changed between 1.1.2 and 1.2. While my app is on 1.1.2, I can drag move all over the place. Once I upgrade to 1.2+ (including 1.2.4) I cannot.

I'll do some more investigating when I get a chance and see if I can narrow it down or provide a more concrete example to repro.

**Comment by TyBarthel** [comment]
@punker76 I think I see what happened.  Prior to 1.2 you used to do drag/move by handling the window's MouseDown event, then in 1.2 you now do it with the PR that uses Thumb.  My case might be special, but I essentially have controls (i.e. tabs) all the way to the top of the window (i.e. Edge, Firefox, Chrome, etc.).  The old way works because it's based on just mouse down where the new Thumb way doesn't because my controls must be eating those events and is related to IsHitTestVisible.

![image](https://cloud.githubusercontent.com/assets/8278570/12539912/680c9f98-c2c2-11e5-90a8-f771c5c00c09.png)
