### ISSUE TITLE
First 30 units of flyout aren't clickable

### ISSUE THREAD

**Issue by Alkalinee** [MahApps/MahApps.Metro#2288]
Hey,
I just updated to the new MahApps.Metro version and noticed the the first 30 units of a flyout aren't clickable because there lays an invisible grid.
![FlyoutNotClickable](http://fs5.directupload.net/images/160103/4w5gya39.png)
(As you can see on the picture, even if the mouse is directly over the button, the hover style doesn't get applied)

First, I was sure that it was my fault and I forgot to hide a grid, so I wrote some code which shows the element directly under the cursor in the title bar.
![Small Video](http://fs5.directupload.net/images/160103/is9fp39o.gif)

Here is the code to display the current element in the title bar (you can also set a break point to analyze the element):
```
        private void MainWindow_OnMouseMove(object sender, MouseEventArgs e)
        {
            var element = Mouse.DirectlyOver as UIElement;
            Title = element?.ToString() ?? "";
        }
```

I will also take a look at the mahapps code but I thought that it would be the best if I create an issue first, perhaps somebody knows where the grid comes from.

**Comment by Alkalinee** [comment]
Okay, I figured out that this part in flyout.xaml causes the problem:
```
            <Thumb Style="{StaticResource WindowTitleThumbStyle}"
                   Height="{Binding Path=TitlebarHeight, Mode=OneWay, RelativeSource={RelativeSource FindAncestor, AncestorType={x:Type Controls:MetroWindow}}}"
                   VerticalAlignment="Top"
                   x:Name="PART_WindowTitleThumb" />
```

If I set the title bar height to 0, everything is awesome. I think that you've missed in the implementation that you can adjust the flyout height and that it doesn't have to overlay the title bar. I have no idea how I could solve this problem because I don't know why you need that.

**Comment by N0ct3** [comment]
Same issue here.
I have to get this part by name and set its template to null to potentially make the whole flyout surface clickable.

**Comment by PavelLvou** [comment]
I have the same proble in version 1.2.4 and in alpha 1.3.0

Here my xaml code
```
<controls:MetroWindow ShowCloseButton="False" WindowStyle="None" TitlebarHeight="100"
        ResizeMode="NoResize" Height="630" Width="450">
    <controls:MetroWindow.TitleTemplate>
        <DataTemplate>
            <Border x:Name="RootBorder">
                <Grid Background="Transparent">
                    <Button Name="SomeButton" Command="{Binding Path=ClickButtonCommand}">
                        <TextBox Text="Button in title"></TextBox>
                    </Button>
                </Grid>
            </Border>
        </DataTemplate>
    </controls:MetroWindow.TitleTemplate>
    <Border>
        <Button Name="SomeButton" Command="{Binding Path=ClickButtonCommand}">
            <TextBox Text="Button in body"></TextBox>
        </Button>
    </Border>
</controls:MetroWindow>
```
and relust
[
![part_windowtitlethumb](https://cloud.githubusercontent.com/assets/18031537/13988064/60c14090-f11b-11e5-85e3-0c91409ef0f5.png)
](url)

Button in title aren't clickable, because there lays an invisible grid

**Comment by punker76** [comment]
@PavelLvou You should use `LeftWindowCommands` or `RightWindowCommands` for button stuff

**Comment by PavelLvou** [comment]
Thank you for help, but I still have a problem.
Gray rectangle appears if window lose focus
I try find this elements and find next
[
![fullversion](https://cloud.githubusercontent.com/assets/18031537/14042234/260cd332-f289-11e5-82f2-b0622bba2649.png)
](url)

Here xaml
```
<controls:MetroWindow  ResizeMode="NoResize"
        EnableDWMDropShadow="False"  WindowTransitionsEnabled="False"
        ShowMaxRestoreButton="False" ShowCloseButton="False" ShowMinButton="False" ShowIconOnTitleBar="False"
        WindowStyle="None" AllowsTransparency="True" WindowTitleBrush="Transparent" BorderBrush="Transparent" Background="Transparent"
        TitlebarHeight="100" Height="630" Width="450">
    <controls:MetroWindow.RightWindowCommands>
        <controls:WindowCommands Background="Transparent">
            <Border x:Name="RootBorder" BorderBrush="Red"
                    Width="450" Height="100"
                    BorderThickness="2, 2, 2, 0" CornerRadius="7,7,0,0"
                    Background="Green">
                <Label Content="Title"></Label>
            </Border>
        </controls:WindowCommands>
    </controls:MetroWindow.RightWindowCommands>
    <Border Width="450" BorderThickness="2, 0, 2, 2" CornerRadius="0, 0, 7, 7" BorderBrush="Red" Background="DarkGreen">
        <Label Content="Body"></Label>
    </Border>
</controls:MetroWindow>
```
All my elements have width 450
Why I have element with width more than my elements and how I can fix it?
And why I have this gray rectangle after window lose focus?

Thank you
