### ISSUE TITLE
Setting WindowButtonCommands styles

### ISSUE THREAD

**Issue by zynthar** [MahApps/MahApps.Metro#2290]
I'm currently changing the styles of the Min, Max and Close buttons with these properties: https://github.com/MahApps/MahApps.Metro/blob/develop/MahApps.Metro/Controls/MetroWindow.cs#L88-L93

However as they have been marked as `Obsolete` I wanted to update my code as requested in the obsolete messages. The problem is that there seems to be no other way of changing the `WindowButtonCommands` styles, as the `MetroWindow`'s instance of `WindowButtonCommands` is set to `internal`. I first assumed that it must be me being a total noob (still might be the case), so I've posted on stackoverflow about it here: http://stackoverflow.com/questions/34563155/setting-windowbuttoncommands-styles-in-mahapps-metro

But the more I look into this, the more it looks like this whole situation was an oversight. Especially since the properties has not been removed in v1.2.0 as the obsolete messages indicated. I'm leaning towards rolling my own titlebar, so I can probably just have my own instance of `WindowButtonCommands` there, solving the issue in my case. However I figured I'd bring this to your attention in case it is in fact a bug/oversight.

**Comment by punker76** [comment]
@zynthar Hi, based on @crumbl3d [changes](https://github.com/MahApps/MahApps.Metro/pull/2152), a short how to...

There are now two styles (Light, Dark) which will be used based on `OverrideDefaultWindowCommandsBrush` and it's lightness (default is the Light style).

So, put these at your `App.xaml`

```
<Style x:Key="CustomLightMetroWindowButtonStyle" TargetType="{x:Type Button}" BasedOn="{StaticResource LightMetroWindowButtonStyle}">
    <Setter Property="Foreground" Value="Chocolate" />
</Style>

<Style x:Key="CustomDarkMetroWindowButtonStyle" TargetType="{x:Type Button}" BasedOn="{StaticResource DarkMetroWindowButtonStyle}">
    <Setter Property="Foreground" Value="Crimson" />
</Style>

<Style TargetType="{x:Type controls:WindowButtonCommands}" BasedOn="{StaticResource {x:Type controls:WindowButtonCommands}}">
    <Setter Property="LightMinButtonStyle" Value="{StaticResource CustomLightMetroWindowButtonStyle}" />
    <Setter Property="LightMaxButtonStyle" Value="{StaticResource CustomLightMetroWindowButtonStyle}" />
    <Setter Property="LightCloseButtonStyle" Value="{StaticResource CustomLightMetroWindowButtonStyle}" />
    <Setter Property="DarkMinButtonStyle" Value="{StaticResource CustomDarkMetroWindowButtonStyle}" />
    <Setter Property="DarkMaxButtonStyle" Value="{StaticResource CustomDarkMetroWindowButtonStyle}" />
    <Setter Property="DarkCloseButtonStyle" Value="{StaticResource CustomDarkMetroWindowButtonStyle}" />
</Style>
```

Hope this helps.

**Comment by crumbl3d** [comment]
I guess I should've written a how to when I posted the pull request. I couldn't have thought a way to do this easier without removing much of the available code. That said though I don't think this is hard since the only thing you need to do is make a style and bind it to `WindowsButtonCommands` like @punker76 posted above. If you have any problems feel free to post them here and tag me since I don't visit too often. :smiley:

**Comment by zynthar** [comment]
Thanks guys! I'll try this out later today :)
