### ISSUE TITLE
Flyouts not working after upgrade to 4.6

### ISSUE THREAD

**Issue by GAMP** [MahApps/MahApps.Metro#2291]
Hi.

I have upgraded my project to .NET 4.6 and since then whenever there is a fly-out to be opened an exception occurs with following error

Cannot add instance of type 'SetFlyoutOpenAction' to a collection of type 'TriggerActionCollection'. Only items of type 'T' are allowed.

I have made sure that the interactivity dll referenced is .NET 4.5 version but still was not able to make it work.

**Comment by bigworld12** [comment]
delete bin, object folders and re build solution

**Comment by GAMP** [comment]
Same problem :(

**Comment by GAMP** [comment]
Fixed. I had a different assembly loaded by some code that seem to have caused this error.
