### ISSUE TITLE
Align Tile Title

### ISSUE THREAD

**Issue by happschinson** [MahApps/MahApps.Metro#2293]
How can I align the title of a Metro Tile to center?

**Comment by punker76** [comment]
@happschinson That's not possible for now, so you must create your own style based on this one https://github.com/MahApps/MahApps.Metro/blob/develop/MahApps.Metro/Themes/Tile.xaml#L6-L95

**Comment by happschinson** [comment]
thanks und grüße aus kölle! ;)

**Comment by punker76** [comment]
@happschinson I added two new dependency properties for `Tile` control: `HorizontalTitleAlignment` and `VerticalTitleAlignment`
