### ISSUE TITLE
ThemeManager.cs NullReferenceException

### ISSUE THREAD

**Issue by Memphizzz** [MahApps/MahApps.Metro#2300]
I've just updated to 1.2.0. and found this NullReferenceException when changing the Applications Theme using the ThemeManager in code behind.

This line: `var key = oldAccent.Resources.Source.ToString().ToLower();` in ThemeManager.cs is causing it. It appears that the "Source" is null in this case.

HTH

**Comment by punker76** [comment]
@Memphizzz Please, can you give us more information? How do you add the MahApps style resoureces? How do you set the default theme? Which version do you use?

**Comment by GeertvanHorrik** [comment]
![image](https://cloud.githubusercontent.com/assets/1246444/13059071/f1e0f8ec-d427-11e5-9f97-cba3d100f4a1.png)

**Comment by GeertvanHorrik** [comment]
I have exactly the same issue. I think it's better to change the code a bit:

```
                var oldAccent = oldThemeInfo.Item2;
                if (oldAccent != null && oldAccent.Name != newAccent.Name)
                {
                    var oldResourceDictionarySource = oldAccent.Resources.Source;
                    if (oldResourceDictionarySource != null)
                    {
						var key = oldResourceDictionarySource.ToString().ToLower();
						var oldAccentResource = resources.MergedDictionaries.Where(x => x.Source != null).FirstOrDefault(d => d.Source.ToString().ToLower() == key);
						if (oldAccentResource != null)
						{
							resources.MergedDictionaries.Remove(oldAccentResource);
						}
                    }
					
					resources.MergedDictionaries.Add(newAccent.Resources);
					themeChanged = true;
                }
```

But not sure if this causes other implications.

**Comment by punker76** [comment]
@GeertvanHorrik seems ok for the first, but it could be interessted why the `Source` for the `oldAccent` is null

**Comment by GeertvanHorrik** [comment]
We use Runtime Access dictionaries in Orchestra for a few years now. I think I recently updated to 1.2.4. The old accent is also a runtime accent, so let me check if it's something we create at runtime as well.

**Comment by GeertvanHorrik** [comment]
It's awesome that we can step through MahApps code now, much easier to debug :+1:

**Comment by punker76** [comment]
@GeertvanHorrik :-D

**Comment by GeertvanHorrik** [comment]
Does MahApps somehow create "Runtime accent" somewhere?

**Comment by GeertvanHorrik** [comment]
Yep, this is the cause:

https://github.com/MahApps/MahApps.Metro/blob/6b44cbd4952f978fda00991e7cd54b460a0a6ae0/MahApps.Metro/ThemeManager.cs#L206

**Comment by punker76** [comment]
@GeertvanHorrik should be easy to fix with a test too

**Comment by GeertvanHorrik** [comment]
So what happens is I call ThemeManager.ChangeAppStyle, then it calls DetectAppStyle and creates the runtime dictionary.

**Comment by GeertvanHorrik** [comment]
Not sure if this is something I can fix on my side. Sent you a screenshot via Gitter.

**Comment by amkuchta** [comment]
Pretty sure this can be tied back to #2440
