### ISSUE TITLE
1 pixel border on metro window - 1.2

### ISSUE THREAD

**Issue by laurencee** [MahApps/MahApps.Metro#2301]
After updating to 1.2 one of my app windows appears to have a 1 pixel border from "PART_Border".

My metro window view contains a Border control with a margin, I do this because I stack multiple windows vertically above each other and like to have some spacing between the windows.

Before 1.2 this worked fine but now it doesn't look right because of the PART_Border element having its own border.

I've downgraded back to 1.1.2 for the time being.

Repro code, notice the border around the transparent margin background

```xaml
<controls:MetroWindow x:Class="WpfApplication1.MainWindow"
                      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                      xmlns:controls="http://metro.mahapps.com/winfx/xaml/controls"
                      WindowStyle="None" UseLayoutRounding="True"
                      AllowsTransparency="True" Background="Transparent"                       
                      ShowActivated="False" Topmost="True" ShowInTaskbar="False"
                      ShowTitleBar="False" ShowCloseButton="False" ShowIconOnTitleBar="False" ShowMaxRestoreButton="False" ShowMinButton="False"
                      SizeToContent="WidthAndHeight"
                      Title="MainWindow">
    <controls:MetroWindow.Resources>
        <DataTemplate x:Key="MessageTemplate">
            <Border x:Name="border" Background="#FF0A1429" BorderThickness="0"  Margin="5">
                <Border.Effect>
                    <DropShadowEffect ShadowDepth="0" Opacity="0.8" BlurRadius="10" />
                </Border.Effect>
                <Grid Margin="6">
                    <TextBlock Text="Hello border" Foreground="White" HorizontalAlignment="Center" />
                </Grid>
            </Border>
        </DataTemplate>
    </controls:MetroWindow.Resources>
    <ContentControl ContentTemplate="{StaticResource MessageTemplate}" />
</controls:MetroWindow>
```

**Comment by punker76** [comment]
@laurencee Hi, there is a change in the BorderlessWindow behavior, sorry for that. But you can fix this by doing this

- set `BorderThickness="0"` for MetroWindow
- set `AllowsTransparency="True"`` in the Initialized event

```
private void MainWindow_OnInitialized(object sender, EventArgs e)
{
    AllowsTransparency = true;
}
```
![2016-01-08_13h53_30](https://cloud.githubusercontent.com/assets/658431/12198326/3a11bfde-b60f-11e5-9b7e-092029ef0972.png)

**Comment by laurencee** [comment]
Ah setting BorderThickness on the MetroWindow was the key, not sure why I didn't think to do that ;)

Cheers for the quick reply, looks all good now. 

I actually set the transparency/other window parameters through caliburn micro so I never ran into the transparency issue until I ran a plain old WPF application for testing this bug out heh...

**Comment by laurencee** [comment]
By the way, the transparency thing might be more of an issue than the border for others if that's a new change in that it has to be applied after window initialization.

**Comment by punker76** [comment]
@laurencee MahApps sets the AllowsTransparency always to false, cause true has some beast bugs...
