### ISSUE TITLE
Confirm before closing MetroTabItem

### ISSUE THREAD

**Issue by kmetic** [MahApps/MahApps.Metro#2302]
I have a MetroTabControl with ItemsSource bound to ObservableCollection<MetroTabItem>. All MetroTabItems have CloseButtonEnabled set to true. Each MetroTabItem represents a document, which the user can edit. 

I would like to show a modal dialog when the user presses the close button on the MetroTabItem with message 'are you sure?' and buttons 'yes' and 'no'. Any ideas how to do this?

PS - I am using https://github.com/Fody/PropertyChanged if it has any impact on the code. The 'yes'/'no' dialog should be displayed only if the document in the MetroTabItem has changed, but this is not a problem because I know when the viewmodel it is dirty.

MainWindow.xaml:
```xml
<controls:MetroWindow DataContext="{Binding RelativeSource={RelativeSource Self}} ...
...
<Button Click="BtnNewDocumentClick" Content="New document">
...
<controls:MetroTabControl ItemsSource="{Binding ViewModel.TabItems}">
</controls:MetroTabControl>
```
MainWindow.xaml.cs:
```c#
[ImplementPropertyChanged]
public partial class MainWindow
{
	public MainWindowViewModel ViewModel { get; private set; }

	public MainWindow()
	{
		InitializeComponent();

		ViewModel = new MainWindowViewModel();
	}

	private void BtnNewDocumentClick(object sender, RoutedEventArgs e)
	{
		ViewModel.InsertEmpty();
	}
}
```
MainWindowViewModel.cs:
```c#
public void InsertEmpty()
{
	var viewModel = new DocumentViewModel();
	var view = new DocumentView { ViewModel = viewModel };
	var newItem = new MetroTabItem
	{
		Header = view.ViewModel.HeaderText,
		CloseButtonEnabled = true,
		Content = view,
		// I gues I have to use CloseTabCommand or CloseTabCommandParameter here
		// with MetroWindow.ShowMessageAsync and await the result somehow...?
		// The dialog should be called only when the viewmodel is dirty, but this is not a problem
		// (something like if(view.ViewModel.IsDirty) { ... }
	};
	TabItems.Add(newItem);
	newItem.IsSelected = true;
}
```

**Comment by punker76** [comment]
@kmetic You can use the [TabItemClosingEvent](https://github.com/MahApps/MahApps.Metro/blob/develop/MahApps.Metro/Controls/MetroTabControl.cs#L75-L81) for such scenarios, simply set the Cancel to true and the TabItem doesn't close.

**Comment by bboxstart** [comment]
@punker76 This works fine when not using MVVM. However, when using MVVM One would like to have control of cancelling the close action in the command body and not in a code behind event.

**Comment by thoemmi** [comment]
@kmetic As far as I can see you have two options:
* `MetroTabItem.CloseTabCommand`<br>However, you can cancel the closing of tab; this command is executed if the tab is about top be closed.
* `MetroTabControl.CloseTabCommand`<br>If this property is set on the tab control, you are responsible for removing the tab from the Tabs collection, but I guess that's what you try to achieve.

**Comment by bboxstart** [comment]
@thoemmi Thanks. I already read about the CloseTabCommand on the TabControl, but was under the impression that it was the predecessor of the command on the tab itself. I indeed need to remove the tab from the collection myself, so I guess that this will be the solution for my situation. I will try it tomorrow.

**Comment by bboxstart** [comment]
@thoemmi I implemented the MetroTabControl.CloseTabCommand. It is worth mentioning that I also needed to use MetroTabItem.CloseTabCommandParameter (on the TabItem, there is none on the TabControl). I was not able to use the CloseTabCommand without parameter by using the selected tab item property on my view model, because that one did not update (when closing another tab than the selected one) before my CloseTabCommand was called and as a result it would close the selected tab instead of the tab that I wanted to close. Thanks again for your suggestion.

**Comment by thoemmi** [comment]
You're right: the parameter for `MetroTabControl.CloseTabCommand` is the tab's `CloseTabCommandParameter`, if it's not `null`; otherwise it's the tab itself. Maybe you should consider to change `CloseTabCommandParameter`'s value to somewhat supporting all your requirements.

**Comment by bboxstart** [comment]
@thoemmi I pass the ViewModel as the Command parameter. All my view models implement the same interface.

**Comment by thoemmi** [comment]
I guess you have binded an `ObservableCollection` of your viewmodels to `MetroTabControl.ItemsSource`. If the user of your application confirms the closing of tab, why can't you just remove the viewmodel from that collection?

**Comment by bboxstart** [comment]
@thoemmi That's exactly what I do. I do pass the Viewmodel as command argument, so that I know which view model to remove from the collection. Everything works fine right now.

**Comment by thoemmi** [comment]
Nice to hear that. Can this issue be closed then?

**Comment by bboxstart** [comment]
@thoemmi This issue already is closed for a while  :) I commented to provide some background info.

**Comment by thoemmi** [comment]
🤦‍♂️ 😉

**Comment by dan-garkusha** [comment]
So, the way I understand it,  there is no way to prevent the closing of a tab via **MetroTabItem**.CloseTabCommand without the use of TabItemClosingEvent in code-behind? Any chance of adding that as an option in the future versions of this control?

**Comment by s0ndos** [comment]
@bboxstart can you share your solution? You seem to be the only person on the internet who attempted this 😋
