### ISSUE TITLE
Lagging when adding to a collection from a FlyOut

### ISSUE THREAD

**Issue by KRSogaard** [MahApps/MahApps.Metro#2306]
I am not sure 100% where the problem is located. But i know it only occurs when a Fly out is involved. But when i add a new view model, to an observable collection that is bound to a TabControl, will my whole UI start lagging. 

I have recorded an example here https://www.youtube.com/watch?v=dPjwpJzlv-M&feature=youtu.be (Sorry about the music, forgot to close spotify when i recorded it, so Youtube forced me to replace the sound with none copyrighted music)
I have removed everything inside the TabControl, and everything in the view model to make sure that is not it.
In the video do i add 2 new view models to my TabController, the first is done without the Flyout and the second is done though the flyout. and the lag only starts when the flyout is used.
I have a usercontrol to that handel adding a new viewmodel, and it is the same that is used in the tab item and in the flow out.
 
My main view mode: https://github.com/KRSogaard/AudioView2/blob/LagTest/AudioView/ViewModels/MainViewModel.cs
The view model being added to the tab control: (Everything is commented out to ensure it is not my code that is the problem) 
https://github.com/KRSogaard/AudioView2/blob/LagTest/AudioView/ViewModels/MeasurementViewModel.cs
XAML: https://github.com/KRSogaard/AudioView2/blob/LagTest/AudioView/MainWindow.xaml
All code:
https://github.com/KRSogaard/AudioView2/tree/LagTest

**Comment by KRSogaard** [comment]
I have found that just opening at closing the flow out will cause the lagging, so i do not need to run a command from it for it to start lagging.

**Comment by punker76** [comment]
@KRSogaard Is this still an issue? (with the latest source/pre-release)

**Comment by KRSogaard** [comment]
Sorry for not getting back sooner, yes updating to a newer version fixed the logging problems.
