### ISSUE TITLE
Sequence contains more than one element

### ISSUE THREAD

**Issue by nicky112** [MahApps/MahApps.Metro#2309]
Hello,

I am using SimpleChildWindow. If I display one childwindow and make a call to the msgbox the msgbox is displayed as expected. However, if I create another childwindow from that already opened childwindow and make a call to show a msgbox, I get the following error:

Sequence contains more than one element. 

**The error occurs on calling ShowMessageDialog("...");**

Basically ShowMessageDialog() would crash if two childwindows are opened at the same time. Any ideas what's going on?

**Comment by jonny123d** [comment]
@nicky112 Check if this issue is solved with MahApps.Metro.SimpleChildWindow v1.3.0 and MahApps.Metro v1.2.3

**Comment by punker76** [comment]
should be solved in 1.2.3
