### ISSUE TITLE
Beginner tiles Doubt

### ISSUE THREAD

**Issue by Ashwani44** [MahApps/MahApps.Metro#2310]
I am beginner in WPF. I am making one project using Mahapps.Metro.
On my main window i have made some tiles . i have 5 user controls . On click of my 1st tile i want to navigate to my 1st user control. how do i do that ??
Any help would be appreciated.
Thank you

**Comment by iskenxan** [comment]
Can you be more specific,maybe send a screen shot? What exactly do you mean by navigate to 1st user control? You could try using NavigationService, you can read more on that here-http://paulstovell.com/blog/wpf-navigation

**Comment by Ashwani44** [comment]
can anybody tell how do i implement paging on my datagrid ???. i don't want
to use any 3rd party control .
Any alternative
Thank you

**Comment by punker76** [comment]
@Ashwani44 Please try using [stackoverflow.com](http://stackoverflow.com/) for your beginner questions or try first learn more about WPF...

**Comment by Ashwani44** [comment]
I am doing so. Thanks Jan 😃
