### ISSUE TITLE
ComboBox won't toggle closed in ribbon

### ISSUE THREAD

**Issue by bloritsch** [MahApps/MahApps.Metro#2311]
I understand it's not a common usage for the ComboBox, but I've extended the ComboBox to create a color picker for my app.  Thank's to Microsoft's cranky and redundant Ribbon API I either have to use a standard control in a Ribbon or have two controls.  Since the RibbonCategory doesn't have a style in Mahapps, and I hate duplicity because the freaking API writers got lazy, we opted for one control.

Here's the situation:

Embed a stock ComboBox without the Mahapps.Metro styles in a ribbon tab/group and it behaves just as it would otherwise.  As soon as you apply the Mahapps.Metro style, you can toggle the combobox open, but every time you try to toggle it closed it re-opens immediately.

Unfortunately I work for a company who's IT is staffed by Mordac the Preventer (Dilbert cartoons), so I can't even check this at work.  I will be attempting to use Blend to figure out the key functional differences between the metro style and the stock style.  My luck has been mixed with this approach though.

**Comment by bloritsch** [comment]
I was not able to find anything in the style.  For my control, I added a property change callback on IsDropDownOpenProperty and forced it to the old value if the change was less than 1/10th of a second in the past.

**Comment by punker76** [comment]
@bloritsch Can you create a short example for this situation? Also testing the latest source (pre-release), cause I changed a little bit on the style, thx!

**Comment by bloritsch** [comment]
OK.  I'll try and git'er done soon.

**Comment by punker76** [comment]
@bloritsch :+1:

**Comment by bloritsch** [comment]
So the ribbon styles don't appear to be included in the Mahapps.Metro DLL even for .NET 4.5

I'll embed them directly based on what you have in Git

**Comment by bloritsch** [comment]
I've created a repository here: https://github.com/bloritsch/Mahapps.BadRibbon

Since the Ribbon styles are

1. Not included in any Mahapps.Metro
2. Don't do the job correctly
3. Don't use any of Mahapps.Metro styles (DynamicResources for theme colors) etc.
3. Microsoft's Ribbon control is FUBAR for any application

It might be worth just removing those files from the Mahapps repository.  In an application that is developed offline, I only used those styles as a starting point, and I went through great pains to make the ribbon look/feel like the rest of the application and use the theme colors.

I still don't understand what in the combobox theme would cause the behavior I'm seeing when it's embedded in a Ribbon directly.  My experience with MS Ribbon is that it should be cast into outer darkness and the developers should be sentenced to gnashing of teeth.

If Mahapps were to ever include a ribbon feature, it would be far more efficient to create a tabbed toolbar.

**Comment by punker76** [comment]
@bloritsch MahApps will not add a ribbon feature. -> see comment on https://github.com/MahApps/MahApps.Metro/pull/1202

I recommend to use [Fluent.Ribbon](https://github.com/fluentribbon/Fluent.Ribbon), maintained by @batzen
It supports also MahApps.

**Comment by punker76** [comment]
@bloritsch But I found the reason for the click stuff -> d6d4e2bd1060581a2afc6c723b34dc334d073905

**Comment by bloritsch** [comment]
Excellent!  And verified that it works.

**Comment by bloritsch** [comment]
I'll look into fluent ribbon, but you also should just take the unsupported files out of your solution.  It just makes it look like you support something that you don't.  While the styles are a good start for making the MS ribbon look close to right, they don't work for night theme and only hide the gradients embedded in the MS style.  I do recommend ripping the bandaid off.  MS Ribbon is a lost cause.
