### ISSUE TITLE
Progress ring visibility

### ISSUE THREAD

**Issue by akshithrajesh290** [MahApps/MahApps.Metro#2312]

**Comment by punker76** [comment]
@akshithrajesh290 What's your problem with the `ProgressRing` visibilty?

**Comment by bigworld12** [comment]
maybe github problem but here is what he wrote 

Need to show Progress ring for at least 5 seconds in My Application

I tried using Threads But I am getting exception Is there any way to show the progress ring for few seconds

—

**Comment by punker76** [comment]
@bigworld12 It's more a SO question.

**Comment by bigworld12** [comment]
oh ok xd
