### ISSUE TITLE
Comparing the assembly name resulted in the mismatch: PUBLIC KEY TOKEN

### ISSUE THREAD

**Issue by Memphizzz** [MahApps/MahApps.Metro#2313]
After upgrading to 1.2.1 all applications using MahApps.Metro show a "Set property 'System.Windows.ResourceDictionary.DeferrableContent' threw an exception." on start which is due to a mismatch of the public key token.

Any Idea how to fix this?

**Comment by BrunoJuchli** [comment]
hmm.. guess we got the same issue: https://github.com/MahApps/MahApps.Metro/issues/2314 posted the issue just a few minutes apart, too ;-)

**Comment by punker76** [comment]
-> #2314
