### ISSUE TITLE
After upgrading from MahApps.Metro.1.1.2.0 to MahApps.Metro.1.2.1.0, application fails to start with because it tries to load an unsigned version of MahApps.Metro

### ISSUE THREAD

**Issue by BrunoJuchli** [MahApps/MahApps.Metro#2314]
Hi
I've got kind-of a strange problem here. After upgrading from MahApps.Metro.1.1.2.0 to MahApps.Metro.1.2.1.0, i've got a `FileLoadException` because it tries to load an unsigned version of MahApps.Metro.
Here's the FusionLog of the exception:

  > Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Running under executable  C:\development\current\03_Source\DesktopDispatchConsole\DesktopDispatchConsole\bin\Debug\Pmr.DesktopDispatchConsole.exe
> --- A detailed error log follows. 

> === Pre-bind state information ===
> LOG: DisplayName = MahApps.Metro, PublicKeyToken=null
 (Partial)
> WRN: Partial binding information was supplied for an assembly:
> WRN: Assembly Name: MahApps.Metro, PublicKeyToken=null > Domain ID: 1
> WRN: A partial bind occurs when only part of the assembly display name is provided.
> WRN: This might result in the binder loading an incorrect assembly.
> WRN: It is recommended to provide a fully specified textual identity for the assembly,
> WRN: that consists of the simple name, version, culture, and public key token.
> WRN: See whitepaper http://go.microsoft.com/fwlink/?LinkId=109270 for more information and common solutions to this issue.
> LOG: Appbase = file:///C:/development/current/03_Source/DesktopDispatchConsole/DesktopDispatchConsole/bin/Debug/
> LOG: Initial PrivatePath = NULL
> Calling assembly : PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.
> '===
> LOG: This bind starts in default load context.
> LOG: Using application configuration file: C:\development\current\03_Source \DesktopDispatchConsole\DesktopDispatchConsole\bin\Debug\Pmr.DesktopDispatchConsole.exe.Config
> LOG: Using host configuration file: 
> LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
> LOG: Policy not being applied to reference at this time (private, custom, partial, or location-based assembly bind).
> LOG: Attempting download of new URL file:///C:/development/current/03_Source/DesktopDispatchConsole/DesktopDispatchConsole/bin/Debug/MahApps.Metro.DLL.
> WRN: Comparing the assembly name resulted in the mismatch: PUBLIC KEY TOKEN
> ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.

The exception happens when instantiating `MetroTabControl`: 
> {"'The invocation of the constructor on type 'MahApps.Metro.Controls.MetroTabControl' that matches the specified binding constraints threw an exception.' Line number '86' and line position '22'."}

It's got an InnerException `XamlParseException`
> {"Set property 'System.Windows.ResourceDictionary.DeferrableContent' threw an exception."}
and `BaseUri` `{pack://application:,,,/MahApps.Metro;component/Themes/DropDownButton.xaml}`

That exception again contains the `FileLoadExeption`.

Now here's what I've tried so far:
--------------------

 - checked the reference in the csproj. It contains `PublicKeyToken`. The upgrade just changed the version (+HintPath) and removed `<SpecificVersion>False</SpecificVersion>`:

    <Reference Include="MahApps.Metro, Version=1.2.1.0, Culture=neutral, PublicKeyToken=f4fb5a3c4d1e5b4f, processorArchitecture=MSIL">
      <HintPath>..\..\..\04_ThirdParty\nuget-packages\MahApps.Metro.1.2.1.0\lib\net45\MahApps.Metro.dll</HintPath>
      <Private>True</Private>
    </Reference>

 - clean / rebuilt solution numerous times
 - in the output folder, verified that there is the correct version of the DLL
 -  removed the code which triggers the exception: `same` `XamlParseException` with same `FileLoadException` occurs somewhere else. It's also got the same message `Set property 'System.Windows.ResourceDictionary.DeferrableContent' threw an exception.`.
 -- managed to have the same exception thrown in 3 different places, always the same

Questions:
--------------------

 - Why is it trying to load a non-signed version if clearly a signed version is referenced?
 - Why does the problem occur now, after the upgrade, but not before?
 - and of course, anybody an idea how i can fix it?

Notes:
--------------------
I'm using VS2013 Update 5, project is targeting .net 4.5.2
There's also MahApps.Resources installed.

Thank you!

**Comment by bigworld12** [comment]
try deleting obj and bin folder

**Comment by BrunoJuchli** [comment]
@bigworld12 
been there, done that ;-)

**Comment by punker76** [comment]
@BrunoJuchli I'll fix this, it's the fu...g strong name signing stuff

**Comment by punker76** [comment]
Fixed with v1.2.2

**Comment by BrunoJuchli** [comment]
@punker76 thanks for all the good work! :-)
