### ISSUE TITLE
Remove Globalization Folders

### ISSUE THREAD

**Issue by vinaydwivedi** [MahApps/MahApps.Metro#2315]
Hi, is there a way to remove the globalization folders automatically created in the build folder? Total size of those folders is 221 KB, don't need any other language support.

**Comment by punker76** [comment]
@vinaydwivedi what "globalization folders" do you mean?

**Comment by vinaydwivedi** [comment]
Sorry localization folders - Just started using MahApps.Metro in my test build to evaluate, but upon building the solution - debug folder has multiple copies of System.Windows.Interactivity.resources.dll for each locale. Is there any way to disable that?

**Comment by punker76** [comment]
@vinaydwivedi this comes not from MahApps. Do you have another library that contains `System.Windows.Interactivity`?

**Comment by vinaydwivedi** [comment]
No I did not add an explicit reference to System.Windows.Interactivity (there is none in my project). Started seeing these folders after I added reference to MahApps.Metro.dll.

I just downloaded the code from GITHub. May be I am using a wrong build.

If you look at debug folder at path (Github code) - ..\..\..\..\MahApps.Metro-develop\MahApps.Metro-develop\samples\Caliburn.Metro.Demo\bin\Debug - you can see these files created as well after build.

**Comment by punker76** [comment]
@vinaydwivedi These comes with `Caliburn.Micro.Platform.dll`
![2016-01-13_13h30_53](https://cloud.githubusercontent.com/assets/658431/12294343/ed0dd7e2-b9f9-11e5-9d58-1a9dde128cbe.png)

**Comment by vinaydwivedi** [comment]
MahApps.Metro project has reference to this dll as well. 

![untitled](https://cloud.githubusercontent.com/assets/9931326/12296070/59126ce6-ba40-11e5-861d-0fa8400ca7ab.png)



Many thanks.

**Comment by punker76** [comment]
@vinaydwivedi Yes, but to its own local lib folder.

**Comment by vinaydwivedi** [comment]
Ok - So I tried referencing to MahApps.Metro.dll "MahApps.Metro-develop\MahApps.Metro-develop\MahApps.Metro\bin\Debug\NET45" Which DLL should I refer to in my project?

Just tried a new WPF project, added refrence to MahApps.Metro.Dll - Build and these folders are back.

**Comment by thoemmi** [comment]
That's weird. These localization assemblies are neither included in the NuGet package nor is Interactivity referenced as dependency:
![image](https://cloud.githubusercontent.com/assets/73690/12297205/5102e334-ba0c-11e5-8208-915f56308210.png)

Do you use NuGet, or do you reference a local build?

**Comment by vinaydwivedi** [comment]
referencing from local build after getting the source from Git.

**Comment by thoemmi** [comment]
Then I guess because of Caliburn the localization DLLs are copied to the output folder (`bin\debug\`). When you reference the `MahApps.Metro.dll` from that folder, Visual Studio detects the dependency on `System.Windows.Interactivity` and copies it along with its localization assemblies.

Have you tried to use the NuGet package?

**Comment by vinaydwivedi** [comment]
Yes, it works well with NuGet package. But I am thinking to modify the project a bit to suit my project theme. Why does project 'MahApps.Metro' reference System.Windows.Interactivity? Is there any real dependency?

**Comment by thoemmi** [comment]
Just search from `System.Windows.Interactivity` in the source code. MahApps.Metro uses and implements several triggers and behaviors.

**Comment by punker76** [comment]
So I think this is not an issue by MahApps...

**Comment by thoemmi** [comment]
Yeah, I think you can close this issue.

**Comment by CountJung** [comment]
this issue was closed already, but I struggle with this same issue like globalization folder (/de).
Still can't find exact reason of dependency problem.
as written above mention Simply delete /de resource folder and program runs Well.

**Comment by punker76** [comment]
@CountJung The localizations in the current release are ok, it's for the color names of the [ColorPicker](https://mahapps.com/docs/controls/ColorPicker) control.
