### ISSUE TITLE
How to close CustomDialog on Cancel Key press (Code attached)

### ISSUE THREAD

**Issue by vinaydwivedi** [MahApps/MahApps.Metro#2316]
CustomDialog dialog = new CustomDialog() { Title = "About", Height = 150, Width = 300 };
            AboutVM aboutViewModel = new AboutVM(x => _dialogCoordinator.HideMetroDialogAsync(this, dialog));
            dialog.Content = aboutViewModel;
            await _dialogCoordinator.ShowMetroDialogAsync(this, dialog);

aboutViewModel has a OK button with Close command - Works good with Enter press (default button), but would like to get it working with Cencel Key press as well. Please suggest.

**Comment by thoemmi** [comment]
`Button`s have a property named [`IsCancel`](https://msdn.microsoft.com/en-us/library/system.windows.controls.button.iscancel(v=vs.110).aspx):
> Gets or sets a value that indicates whether a Button is a Cancel button. A user can activate the Cancel button by pressing the ESC key.

Just add something like this:
```xml
<Button MinWidth="80"
        IsCancel="True"
        Command="{Binding CancelCommand}"
        Content="Cancel" />
```

**Comment by vinaydwivedi** [comment]
Awesome, many thanks.
