### ISSUE TITLE
Message dialog overlay is not displayed

### ISSUE THREAD

**Issue by jonny123d** [MahApps/MahApps.Metro#2318]
Hello,
I some cases when the message dialog is shown using ShowMessageAsync() method the dark overlay is not displayed. In my own project it happens a lot of times, but is hard to reproduce all cases because I use a dll library, threads, ASP.NET Identity for login, large code file,... I have found a simple example when it happens, may be fixing this bug solves all cases.

This is my environment:
- Windows 8.1 Pro (64 bits)
- Visual Studio Ultimate 2013 Update 4

I'm using Mahapps stable libraies:
- Mahapps.Metro 1.2.2.0
- Mahapps.Metro.SimpleChildWindow 1.2.0.0

Here is the sample code to reproduce de issue (I don't know why, but I can't uplad it to this post):
http://1drv.ms/1JJWO5G

You can follow the 4 steps in the application, one for each button, and you will see this 3 message dialogs:

When step 1 button is clicked (fine):
![01 fine dialog](https://cloud.githubusercontent.com/assets/4820376/12289591/ad893bb0-b9dc-11e5-80f9-448daf492244.png)

When step 2 (show child window) and 3 buttons are clicked (improvable, the displayed overlay is because the child window is shown, but message dialog overlay is not displayed):
![02 improvable dialog](https://cloud.githubusercontent.com/assets/4820376/12289852/3f99b538-b9de-11e5-9777-b907ffff9e02.png)

And when the step 4 button is clicked (wrong):
![03 wrong dialog](https://cloud.githubusercontent.com/assets/4820376/12289865/5895b2e4-b9de-11e5-983c-5e03ab2121f1.png)

Due to SimpleChildWindow is involved, I will open another issue in it's repository.

**Comment by punker76** [comment]
should be fixed with MahApps.Metro.SimpleChildWindow v1.3.0 and MahApps.Metro v1.2.3

**Comment by jonny123d** [comment]
Thank you very much @punker76 I will try it on monday with my solution
