### ISSUE TITLE
Is MetroWindow Per-Monitor DPI-Aware?

### ISSUE THREAD

**Issue by aaad** [MahApps/MahApps.Metro#2319]
Does MetroWindow use Per-Monitor DPI-Aware features provided by Windows 8.1+?

https://msdn.microsoft.com/en-us/library/windows/desktop/ee308410%28v=vs.85%29.aspx

If no: feature request :)

Thanks!

**Comment by csabar** [comment]
Unfortunately it is not Per-Monitor DPI-Aware. But it would be fine to have built in support. I found a project which adds this functionality to MahApps.Metro: https://github.com/circuitdiagram/CircuitDiagram.DPIWindow

**Comment by punker76** [comment]
Since .Net 4.5 it's possible to get DPI aware on application level. https://github.com/Microsoft/WPF-Samples/tree/master/PerMonitorDPI

**Comment by strican** [comment]
Why was this closed? The DPI helpers were added in [.NET 4.6.2](https://msdn.microsoft.com/en-us/library/system.windows.media.visualtreehelper.getdpi(v=vs.110).aspx). .NET 4.5 apps still need to do this manually.

**Comment by Insire** [comment]
because you can add DPI awarenes via an app.manifest file. @punker76 linked a repo containing a sample for that.
