### ISSUE TITLE
window cant be moved around using a touch screen

### ISSUE THREAD

**Issue by simonmau** [MahApps/MahApps.Metro#2320]
if you use a touch device, a window cant be moved around like a normal wpf window, you have to use a mouse

**Comment by punker76** [comment]
fixed in v1.2.3

**Comment by TyBarthel** [comment]
@punker76 I think something else might possibly be going on where something else changed between 1.1.2 and 1.2.  While my app is on 1.1.2, I can drag move all over the place.  Once I upgrade to 1.2+ (including 1.2.4) I cannot.

I'll do some more investigating when I get a chance and see if I can narrow it down or provide a more concrete example to repro.
