### ISSUE TITLE
ToggleSwitch doesn't show that little border

### ISSUE THREAD

**Issue by GreenEyedAndy** [MahApps/MahApps.Metro#2323]
Hi,
in your demo app that ToggleSwitches all have a little border around the SwitchOnBrush or the SwitchOffBrush.
If I try to use your control I don't get this border.
Is that an error or something that can be adjusted?
![image](https://cloud.githubusercontent.com/assets/2870571/12350786/82787a78-bb79-11e5-86b7-63977002a53e.png) yours
![image](https://cloud.githubusercontent.com/assets/2870571/12350848/cf3d809c-bb79-11e5-97ba-c9b170f17d59.png) mine

**Comment by punker76** [comment]
@GreenEyedAndy Can you just post some XAML code?

**Comment by GreenEyedAndy** [comment]
I use it just like in this line.
~~~xml
<controls:ToggleSwitch Grid.Row="1" Grid.Column="9" OffSwitchBrush="#FFB4B4B4" OnSwitchBrush="YellowGreen" ThumbIndicatorBrush="Black" ThumbIndicatorDisabledBrush="Gray" Margin="100,0,50,0" BorderBrush="#FF898989" IsChecked="True" />
~~~

**Comment by punker76** [comment]
@GreenEyedAndy Mh, just tested your code...

![image](https://cloud.githubusercontent.com/assets/658431/12351334/164d9e92-bb7d-11e5-954f-41c4a36eeb30.png)

...looks fine.

**Comment by GreenEyedAndy** [comment]
I made a little video - I have no Idea why it doesn't show that border.
[2016-01-15_1146.zip](https://github.com/MahApps/MahApps.Metro/files/91717/2016-01-15_1146.zip)

**Comment by GreenEyedAndy** [comment]
Maybe I must include some dynamic resources?

**Comment by punker76** [comment]
@GreenEyedAndy Your video shows only the designer, so is this also an issue if you run your app? Do you put the resources on the right place (App.xaml)?

**Comment by GreenEyedAndy** [comment]
Ha, that's the problem! I didn't put the resources in the app.xaml.

Thanks for your help.

BTW: great components

**Comment by punker76** [comment]
@GreenEyedAndy Thx
