### ISSUE TITLE
DataGrid activated by Titlebar

### ISSUE THREAD

**Issue by dmex** [MahApps/MahApps.Metro#2324]
Hello,

I've found a weird issue where the DataGrid is activated when clicking the Titlebar of separate windows within the same application.

Requirements:
* 2 WPF windows with any MahApps theme.
- The first window containing only a DataGrid with say 100 items and 6 columns (each subitem also containing items).
- The second window containing nothing (but can contain anything).

The bug becomes very, very obvious under the following conditions:
1. The first window is maximized.
2. The second window is positioned somewhere on the left of the screen and must be anywhere between columns 1-4.

Sample project can be downloaded here:
http://1drv.ms/23c9XLg

Repro Steps:
Run the sample project, click the "Open Secondary Window" button at the top right then simply click and drag the secondary window to see items on the DataGrid of the first window becoming highlighted.

I've tested this on Windows 7 and Windows 10 from MahApps versions 1.1.2 to 1.2.3 and confirmed the behavior is still present but if you make the main window smaller it becomes much harder to reproduce and it also helps to position the secondary window Titlebar closer to the Datagrid headers of the first window.

If anyone can confirm the bug or knows a workaround it would be appreciated :)

**Comment by punker76** [comment]
@dmex I've got it
