### ISSUE TITLE
Window resize stutters when TextBox is focused

### ISSUE THREAD

**Issue by Dotnetifier** [MahApps/MahApps.Metro#2327]
I resized a MetroWindow, and the bottom-right corner of the MetroWindow just lagged behind the cursor. This only occurs when a TextBox field was focused and does not occur in a non-MAM styled application.

This bug can be reproduced in the latest version of the `develop` branch (tested against 7cc74858f19cbe2497a09a244777cf569ea84f68) on a Windows 10 10586.63 x64 setup (I'm using an NVIDIA GeForce GTX 750 Ti, maybe it's important since it is a graphical issue I suppose). It can be reproduced by selecting a text field and resizing the window.

![screencapture_22-1-2016_00](https://cloud.githubusercontent.com/assets/6247359/12498082/2cb03b86-c0a0-11e5-8089-1a5162e6140b.gif)

Before selecting the TextBox, resize performance is OK, considering the number of elements and the crappy GIF. After focusing the TextBox, it is way slower and if you look closely, the glow borders get 'detached' from the window.

I'm not certain if it is just my computer doing this to me, or if it is an MAM related issue. If so, I have no idea what is causing this.

**Comment by punker76** [comment]
@Dotnetifier please try latest alpha, but sometimes WPF causes such issues...
