### ISSUE TITLE
Validation Message is displayed twice in ComboBox when setting TextBoxHelper.ClearTextButton to true

### ISSUE THREAD

**Issue by nicolausanne** [MahApps/MahApps.Metro#2329]
![sicpa-net_chl0112367_20160126_130819_nthal_visa issuing system vis - embassy](https://cloud.githubusercontent.com/assets/2971680/12580323/caece25e-c42e-11e5-8808-98235f48e8a5.png)
![sicpa-net_chl0112367_20160126_130835_nthal_visa issuing system vis - embassy](https://cloud.githubusercontent.com/assets/2971680/12580324/caeee310-c42e-11e5-8009-3f3668cf69dd.png)

Using MahApps 1.2.4

Scenario to reproduce issue:
    - Add a ComboBox
    - Set TextBoxHelper.ClearTextButton to true (to be able to clear the SelectedItem)
    - Bind the ComboBox to a ViewModel implementing INotifyDataErrorInfo
    - Add one single error message to the list of error in this ViewModel
    - The error message will be displayed twice
    - It is displayed only once when setting TextBoxHelper.ClearTextButton to false

**Comment by punker76** [comment]
@nicolausanne is this an editable combobox? can you show us the INotifyDataErrorInfo implementation?

**Comment by nicolausanne** [comment]
@punker76 This is not an editable combobox.

The XAML is the following:
![xaml](https://cloud.githubusercontent.com/assets/2971680/12581251/bd603dc8-c435-11e5-86c7-dac0d1f4bd71.png)

In the ViewModel, I just add only ONCE the message. I tried removing the <Style> in the XAML and the error message is displayed only one.
Unfortunately, I cannot show you the ViewModel implementation.

Let me know if you need more info.

**Comment by punker76** [comment]
@nicolausanne Hi, can you try to use latest pre-release? And if it's still an issue create a short reproducable app? Thx!

**Comment by nicolausanne** [comment]
@punker76 It's not reproducable with the latest pre-release. Thanks a lot!
