### ISSUE TITLE
ShowMetroDialogAsync - Move main window

### ISSUE THREAD

**Issue by VOCCTQ** [MahApps/MahApps.Metro#2331]
Why it's not possible to move main windows while a dialog is shown with ShowMetroDialogAsync?
Can this be fixed in newer release or is it desired? If its's desired can it be set by an option?

Thanks

**Comment by jyrka98** [comment]
Well it's a dialog, so yes, it's meant to be like that.
Just add this to your windows constructor..

**Comment by punker76** [comment]
@VOCCTQ You can now use `ShowDialogsOverTitleBar` if you need moving the window while showing a dialog (pre-release)
