### ISSUE TITLE
DateTimePicker does not pick the Validation ErrorTemplate

### ISSUE THREAD

**Issue by dimio5** [MahApps/MahApps.Metro#2334]
I know DateTimePicker is not released yet, but I was playing around with it and found out that if the user types an invalid date in the textbox, the validation popup is not shown although the border turns red.

I don't know the dev status of this control, so I am sorry if I shouldn't open an issue.
This can be easily replicated in the demo app by appending any letter in the textbox and tabbing out and then tabbing back.

**Comment by xxMUROxx** [comment]
@dimio85 thank for the feedback. I will look into it

**Comment by punker76** [comment]
@xxMUROxx should be work, or not?

**Comment by xxMUROxx** [comment]
@punker76 as I remember I have seen that the issue should exists. But this was a month ago. Do not know if it is still present but as I remember the validation is not always called and thus the red-bar not correctly updated. Unfortunately I am not on a development environment today so I cannot check it now.

**Comment by punker76** [comment]
Fixed with 3d9605d37f5ee9848da17b5ea2e5457993e58be7
