### ISSUE TITLE
CustomDialog uses empty BaseMetroDialog constructor -> OwningWindow = null

### ISSUE THREAD

**Issue by aaad** [MahApps/MahApps.Metro#2336]
I use MahApps.Metro.Controls.Dialogs.CustomDialog in the context of a window which is not Application.Current.Window.

It's not possible to use CustomDialog with a set OwningWindow -> the base class BaseMetroDialog  trieds to do stuff on Application.Current.MainWindow.

Can you make OwningWindow writeable?

Thank you in advance :)

**Comment by thoemmi** [comment]
You can show the dialog in an external window. You have to call [`DialogManager.ShowModalDialogExternally`](https://github.com/MahApps/MahApps.Metro/blob/develop/MahApps.Metro/Controls/Dialogs/DialogManager.cs#L463). Does this help?

**Comment by aaad** [comment]
I would prefer to show it in my window, which is not Application.Current.MainWindow. Is there a reason to make OwningWindow read-only?

**Comment by thoemmi** [comment]
If you inherit from `BaseMetroDialog` it has a protected constructor where you can pass the owning window (which must be a `MetroWindow` though). Doesn't that help in your scenario?
