### ISSUE TITLE
Flyout style from Accent to Light is not working

### ISSUE THREAD

**Issue by coussej** [MahApps/MahApps.Metro#2337]
In my code, I have a flyout called _modalFlyoutRight_ defined in my MainWindows.xaml, which I then use from child elements in the following form:

``` c#
Window parentWindow = Window.GetWindow(this);
object obj = parentWindow.FindName("modalFlyoutRight");
Flyout flyout = (Flyout)obj;
flyout.Theme = FlyoutTheme.Light;
flyout.Content = ...
```

I use the same flyout for different content, and style it with both light and accent themes. When I go from Light -> Accent, all works, but from Accent to light the background remains in the Accent color. Maybe some properties are not explicitly set when selecting the light theme?

First call with **FlyoutTheme.Light**:
![image](https://cloud.githubusercontent.com/assets/9944663/12811081/705f3974-cb2a-11e5-9676-4695c7142eb9.png)

Second call with **FlyoutTheme.Accent**:
![image](https://cloud.githubusercontent.com/assets/9944663/12811109/9bb8a858-cb2a-11e5-8ef0-bf8e85b5c4c6.png)

Third call with **FlyoutTheme.Light**:
![image](https://cloud.githubusercontent.com/assets/9944663/12811119/b79b3298-cb2a-11e5-9ea4-1b647d93862a.png)

**Comment by punker76** [comment]
@coussej changing the Flyout `Theme` on the fly is currently not fully supported

**Comment by coussej** [comment]
Can you think of a possible workarround to achieve what I'm trying here?

**Comment by punker76** [comment]
@coussej maybe i found the cause why this happens, I'll look what I can do for a fix....

**Comment by coussej** [comment]
talk about service... :smile: thanks man!

**Comment by punker76** [comment]
@coussej Hi, I know it's late, but if this still an issue then please test the latest 1.5.0-alpha014. Thx.
