### ISSUE TITLE
Impossible to toggle the visibility of TitleBar with UseNoneWindowStyle!

### ISSUE THREAD

**Issue by gigios** [MahApps/MahApps.Metro#2338]
I have the necessity to start a window without border/control buttons/resize. To do this I have added some binding to the MetroWindow properies (UseNoneWindowStyle, IsWindowDraggable and ShowSystemMenuOnRightClick).
With this settings all works fine but when I change the property defined in the ViewModel (in binding with UseNoneWindowStyle), **the ShowTitleBar property stay False**!
I have checked the code and in the MetroWindow.cs, the method ToggleNoneWindowStyle, set the ShowTitleBar ONLY to false without any 'restore' to true when the useNoneWindowStyle is set to false.
Another behavior is that, if I have set a binding with the ShowTitleBar, I lose this binding!

**Comment by petvetbr** [comment]
@punker76 If you want I can look at this. I took a look at the code and the fix initially seems simple.

**Comment by punker76** [comment]
@gigios There is a coerce value callback for the ShowTitleBar property which causes your binding

```csharp
private static object OnShowTitleBarCoerceValueCallback(DependencyObject d, object value)
{
    // if UseNoneWindowStyle = true no title bar should be shown
    if (((MetroWindow)d).UseNoneWindowStyle)
    {
        return false;
    }
    return value;
}
```
