### ISSUE TITLE
The Glow border does not follow the window is is used the UseNoneWindowStyle property!

### ISSUE THREAD

**Issue by gigios** [MahApps/MahApps.Metro#2339]
I'm playing to simulate the WindowStyle = None behavior, to do this I set some properties in the MetroWindow (UseNoneWindowStyle, IsWindowDraggable).
If my app start with the UseNoneWindowStyle set to false, I can see the TitleBar and I'm able to drag the window with the correct glow effect.
If I change in my ViewModel the UseNoneWindowStyle property (in binding with the Win property) the window hide the TitleBar and I'm not able to drag (because I have also IsWindowDraggable in binding), and this is correct!
If my app start immediately with the UseNoneWindowStyle set to true and IsWindowDraggable to false, the window is not draggable correctly but, when I change my properies in the ViewModel, I'm able to drag the window and to see (not perfectly, but this is another issue) the TitleBar.
The problem is that the glow border does not follow the dragging window!

**Comment by Camuvingian** [comment]
I also have this problem. The glow was working fine before I updated to the very latest version...

**Comment by punker76** [comment]
@gigios @Camuvingian the glow is explicit ignored if the `UseNoneWindowStyle` is true or no `GlowBrush` is set

**Comment by punker76** [comment]
don't know if this makes sense

**Comment by punker76** [comment]
^ /cc @thoemmi what do you think? i think we can delete this check.

**Comment by thoemmi** [comment]
As far as I can see the problem is that `GlowWindowBehavior.IsGlowDisabled` is checked only right after the window is loaded/source is initialized. It was never meant to be changed at runtime, so if you change `UseNoneWindowStyle` or `GlowBrush` afterwards it is too late. 

I guess removing the check in `GlowWindowBehavior.OnAttached` would be ok.

**Comment by punker76** [comment]
@gigios The glow is now also available if `UseNoneWindowStyle` is set to true. 7ca466655ec705c70f44d1a7ef01b5da8f5bf4a7
