### ISSUE TITLE
Update Icon Guides

### ISSUE THREAD

**Issue by bloritsch** [MahApps/MahApps.Metro#2341]
Since Mahapps has the new PackIconMaterial and PackIconModern, the http://mahapps.com/guides/icons-and-resources.html guide is a bit out of date.  It would be really useful if we could have that updated with some generated HTML.

Have a quick guide for how to declare the icon in code, then a table with the "Kind" enum values under the icon image itself (this part would be generated from code).  That way as things progress the docs stay up to date and there's a quick and easy guide to finding the icons we want to use.

**Comment by punker76** [comment]
-> https://github.com/MahApps/mahapps.github.com/issues/20
