### ISSUE TITLE
Flyout

### ISSUE THREAD

**Issue by barryBithead** [MahApps/MahApps.Metro#2342]
1) Is there a way to scale the close arrow (button) of an open Flyout ? It's a bit bigger than the Circle Button used to open it, and it would be nice to have them the same size. (i.e. the Flyout button needs to be smaller to match my circle button, not the other way around).

2) Is there a way to position a Flyout,  that opens on the rights side, and that is half the height of the parent window, so that it open at the top of the parent window, instead of in the middle, as it seems to do by default ? The VerticalAlignment = top property had to effect.

Thanks,

Barry
bitHeads

**Comment by barryBithead** [comment]
This fixed issue 2) https://github.com/MahApps/MahApps.Metro/issues/1280

**Comment by petvetbr** [comment]
@barryBithead I´m not sure if I understood the first issue. Can you please provide an example/printscreens?

**Comment by punker76** [comment]
@barryBithead You must override the HeaderTemplate with your own style if you want a different button style.
