### ISSUE TITLE
Can't edit TextBoxHelper.ClearTextButton properties

### ISSUE THREAD

**Issue by yoave23** [MahApps/MahApps.Metro#2345]
Please give an option to edit the TextBoxHelper.ClearTextButton properties such as color and font size.

**Comment by punker76** [comment]
@yoave23 There is now a new attached dependency property `TextBoxHelper.ButtonFontSize`. This should also be the last extra attached dp, all other can be changed via `TextBoxHelper.ButtonTemplate`.
