### ISSUE TITLE
How to switch to regular casing for all the UI elements

### ISSUE THREAD

**Issue by MoonStorm** [MahApps/MahApps.Metro#2347]
I get some of the UI elements with their content in uppercase. I managed to set the normal casing for buttons with ``ControlsHelper.ContentCharacterCasing`` but I have yet to find a way for the metro window. To be honest I haven't seen too many apps in the wild that behave like this so I have no idea why this was chosen as the default for this toolkit. It looks distasteful.

Is there a way to have this behavior switched off for all the controls?

**Comment by punker76** [comment]
@MoonStorm Use `TitleCaps` `true/false` for `MetroWindow` and you can change the default behavior for all other controls by yourself in the `App.xaml` by overriding this styles.

**Comment by MoonStorm** [comment]
Yeah that did it. Thanks.

**Comment by punker76** [comment]
@Ahmetcanb The `TitleCaps` property is obsolete. You should use the `TitleCharacterCasing` instead.

If you put this key in your `App.xaml`

```xaml
<Style x:Key="CustomWindowStyleKey" TargetType="{x:Type Controls:MetroWindow}">
    <Setter Property="TitleCharacterCasing" Value="CharacterCasing.Normal" />
</Style>
```

you can use then this key on your windows like

```xaml
<mah:MetroWindow x:Class="YourMainWindow"
                 xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                 xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                 xmlns:mah="clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro"
                 Style="{DynamicResource CustomWindowStyleKey}" />
```

Hope this helps!

**Comment by Ahmetcanb** [comment]
> @Ahmetcanb The `TitleCaps` property is obsolete. You should use the `TitleCharacterCasing` instead.
> 
> If you put this key in your `App.xaml`
> 
> ```
> <Style x:Key="CustomWindowStyleKey" TargetType="{x:Type Controls:MetroWindow}">
>     <Setter Property="TitleCharacterCasing" Value="CharacterCasing.Normal" />
> </Style>
> ```
> 
> you can use then this key on your windows like
> 
> ```
> <mah:MetroWindow x:Class="YourMainWindow"
>                  xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
>                  xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
>                  xmlns:mah="clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro"
>                  Style="{DynamicResource CustomWindowStyleKey}" />
> ```
> 
> Hope this helps!

Thanks a lot!
