### ISSUE TITLE
Thumb height of slider control

### ISSUE THREAD

**Issue by KKauK** [MahApps/MahApps.Metro#2348]
Hello,

is there a way of changing the height of the slider thumb (Controls.Slider.xaml). This seems to be bound to the Track Height set to 18. 
My current solution is to change this value to "Auto". Then I can change the height by setting HorizontalThumbHeight etc. in my code

```
<Track x:Name="PART_Track" Grid.Row="1" Height="Auto">
```

I would prefer to change this setting by templating not by changing your source code.

Thanks in advance.

**Comment by RejectKid** [comment]
@punker76 i see you assigned this to yourself, tho i was looking into this a bit.  Figured it could be an easier one for me to get started with.

I've started stubbing out a thumb height depProp in the SliderHelper class.  Having trouble getting access to the thumb though as my typical

var track = slider.Template.FindName("PART_Track", slider) as Track;

isn't finding it?

tho if youve already started with this i can move onto something else
