### ISSUE TITLE
ThemeManager.ChangeAppStyle() has no effect if used with window parameter

### ISSUE THREAD

**Issue by DJmRek** [MahApps/MahApps.Metro#2351]
I'm having issues changing the style of an other window than MainWindow. If I change the style via xaml everthing works, but if I use `ThemeManager.ChangeAppStyle(Window w,...)`, it dosn't change the style. [In this project](https://github.com/DJmRek/MahAppsTest) I tried to show the issue.

Informations:

Win 8.1 Pro
Visual Studio 2013 Professional
.NET 4.5
MahApps V 1.2.4 via Nuget
MahApps  Ressources V 0.4.0.0

Anyway great work you doing here! :)

**Comment by punker76** [comment]
@DJmRek 
- https://github.com/MahApps/MahApps.Metro#contributing-to-this-project
- https://github.com/MahApps/MahApps.Metro/blob/develop/CONTRIBUTING.md

**Comment by DJmRek** [comment]
Sry first post was a failpost, I've updated it! Thx for your quick response!

**Comment by DJmRek** [comment]
@punker76 Ahhh crap found the solution in your blog:
Out of the mahapps.com documentation, I thought  I could change style of the window by using the Xaml approach **OR** the ThemeManager solution.  But we need the Xaml anytime, like you described in your blog! So this issue can be closed and maybe add a bit more clearer documentation on mahapps.com :)
