### ISSUE TITLE
Can't set ComboBox buttons width with ControlsHelper.ButtonWidth

### ISSUE THREAD

**Issue by iSlaffko** [MahApps/MahApps.Metro#2352]
If you set a height of a ComboBox to a larger number than a default one, you may see, that buttons (two with editable ComboBox) take a lot of space comared to other similar controls. Here is an example of ridiculously tall ComboBox in demonstrational purpose (note: ClearTextButton is pressed):

![image](https://cloud.githubusercontent.com/assets/17061461/13052306/25729f94-d40f-11e5-8c79-984948bacb84.png)

If I understood it right, buttons' shape is set to be square in ComboBox XAML:

```XAML
<ColumnDefinition Width="{Binding RelativeSource={RelativeSource FindAncestor, AncestorType={x:Type Grid}}, Path=ActualHeight, Mode=OneWay}" />
```

I'd like to have the ability to set buttons' width using `Controls:ControlsHelper.ButtonWidth="22"` as it is allowed in TextBox 
```XAML
<ColumnDefinition x:Name="ButtonColumn" Width="Auto" />
...
<Button x:Name="PART_ClearText"
    Width="{Binding RelativeSource={RelativeSource TemplatedParent}, Path=(Controls:ControlsHelper.ButtonWidth), Mode=OneWay}"
...
```

What I'd like to have in a case of such a huge control is:

![image](https://cloud.githubusercontent.com/assets/17061461/13052409/ca646fc8-d40f-11e5-8557-bdb5fe1bb575.png)

**Comment by punker76** [comment]
@iSlaffko just saw this on `TextBox` too and I'd also say that `ButtonWidth` should be respect...
