### ISSUE TITLE
ShowMetroDialogAsync is not modal

### ISSUE THREAD

**Issue by dzaliznyak** [MahApps/MahApps.Metro#2353]
When a child dialog is opened via ShowMetroDialogAsync it is looks like modal dialog but the parent dialog still can be controlled pressing Tab, Enter, Esc and Space buttons.

**Comment by pfattisc** [comment]
Can't reproduce the behaviour of @dzaliznyak  **BUT**:
When a dialog is shown (via ShowMetroDialogAsync) and you press _Ctrl + Tab_ the keyboard focus switches to the main window and then it receives keyboard inputs...
That makes ShowMetroDialogAsync not modal.

**Comment by punker76** [comment]
->https://github.com/MahApps/MahApps.Metro/issues/2400
