### ISSUE TITLE
TextBoxHelper.ButtonClicked should pass ButtonCommandParameter to ButtonCommand.CanExecute

### ISSUE THREAD

**Issue by xmedeko** [MahApps/MahApps.Metro#2354]
`TextBoxHelper.ButtonClicked` call `ButtonCommand.Execute` and `ButtonCommand.CanExecute` with different parameters. If should use same parameter for both of them. I.e.

    command.CanExecute(commandParameter)

**Comment by punker76** [comment]
@xmedeko you're right, i'll change this

**Comment by punker76** [comment]
@xmedeko done with https://github.com/MahApps/MahApps.Metro/commit/9672a56bd61963dbc02e98606f777a865366f4db

**Comment by xmedeko** [comment]
Wow, fixed in 7 minutes!
