### ISSUE TITLE
DataGrid  and GroupStyle    Error Binding

### ISSUE THREAD

**Issue by xardison** [MahApps/MahApps.Metro#2356]
I have a simple MahApps.Metro DataGrid with 6 columns. I filled the DataGridwith about 500 rows of data and tried grouping by a column header. While the grouping works the computer cpu usage shoots up to 99% and i cant do much else other than close the app.

The output in VS 

```
System.Windows.Data Error: 4 
:Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Control.Datagrid', AncestorLevel=1'".
 BindingExpression:Path=AreRowDetailsFrozen; Dataitem=null; target element is 'DataGridDetailsPresenter' (Name="); 
target property is 'SelectiveScrollingOrientation' (type 'SelectiveScrollingOrientation')
```

```
System.Windows.Data Error: 4 
:Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Control.Datagrid', AncestorLevel=1'".
 BindingExpression:Path=HeadersVisibility; Dataitem=null; target element is 'DataGridRowHeader' (Name="); 
target property is 'Visibility' (type 'Visibility')
```

``` xaml
<DataGrid.GroupStyle>
    <!-- Style for groups at top level. -->
    <GroupStyle>
      <GroupStyle.ContainerStyle>
        <Style TargetType="{x:Type GroupItem}">
          <Setter Property="Template">
            <Setter.Value>
              <ControlTemplate TagetType="GroupItem">
                <Expander IsExpanded="false">
                  <Expander.Header>
                    <StackPanel Orientation="Horizontal">
                      <TextBlock VerticalAlignment="Bottom" FontSize="13" FontWeight="Bold" Foreground="Ghostwhite" Text="{Binding Name}" />
                      <TextBlock Margin="10,0,0,0" VerticalAlignment="Bottom" FontSize="13" FontStyle="Italic" FontWeight="Bold" Foreground="Green" Text="{Binding ItemCount}" />
                    </StackPanel>
                  </Expander.Header>
                  <ItemsPresenter />
                </Expander>
              </ControlTemplate>
            </Setter.Value>
          </Setter>
        </Style>
      </GroupStyle.ContainerStyle>
    </GroupStyle>
  </DataGrid.GroupStyle>
```

**Comment by punker76** [comment]
@xardison which version? do you use .net 4.5 or 4.0? cause grouping breaks virtualization in 4.0.

**Comment by xardison** [comment]
4.5

**Comment by xardison** [comment]
version mahapps 1.2.4

**Comment by punker76** [comment]
@xardison this doesn't help?
```
<DataGrid EnableColumnVirtualization="True" EnableRowVirtualization="True" VirtualizingPanel.IsVirtualizingWhenGrouping="True">
```

**Comment by xardison** [comment]
I got 3 errors instead of 1500.   already you can use

System.Windows.Data Error: 4 
:Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Control.Datagrid', AncestorLevel=1'".
 BindingExpression:Path=AreRowDetailsFrozen; Dataitem=null; target element is 'DataGridDetailsPresenter' (Name="); 
target property is 'SelectiveScrollingOrientation' (type 'SelectiveScrollingOrientation')


System.Windows.Data Error: 4 
:Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Control.Datagrid', AncestorLevel=1'".
 BindingExpression:Path=HeadersVisibility; Dataitem=null; target element is 'DataGridRowHeader' (Name="); 
target property is 'Visibility' (type 'Visibility')



System.Windows.Data Error: 4 
:Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Control.Datagrid', AncestorLevel=1'".
 BindingExpression:Path=SelectionUnit; Dataitem=null; target element

**Comment by punker76** [comment]
@xardison Please try latest version 1.3.0. There are some changes to the DataGrid style which maybe fix your issues. I'll close this now, feel free to re-open it if you still get errors. Thx
