### ISSUE TITLE
'Save as' or 'Save add' icon

### ISSUE THREAD

**Issue by iSlaffko** [MahApps/MahApps.Metro#2357]
I've noticed a lack of different 'Save' icons.
There is only one actual 'Save' icon:

![image](https://cloud.githubusercontent.com/assets/17061461/13107296/ffdf8128-d57d-11e5-8634-cced32dbff16.png)

And a few of 'Disk' icons:

![image](https://cloud.githubusercontent.com/assets/17061461/13107303/0a77a08e-d57e-11e5-99fc-e3a6b9f2e3b7.png)

I think, that it would be nice to have at least 'SaveAs' and, maybe, 'SaveAll' icons.
I've done 'SaveAs' icon by modifying the 'Save' icon, so here's XAML for it:

```XAML
    <Canvas x:Key="appbar_saveas" Width="76" Height="76" Clip="F1 M 0,0L 76,0L 76,76L 0,76L 0,0">
        <Path Width="34.8333" Height="34.8333" Canvas.Left="20.5833" Canvas.Top="20.5833" Stretch="Fill" Fill="{DynamicResource BlackBrush}" Data=" F1  M43.4167,48.4167 L43.4167,54.4167 48.4167,54.4167 48.4167,48.4167 54.4167,48.4167 54.4167,43.4167 48.4167,43.4167 48.4167,37.4167 43.4167,37.4167 43.4167,43.4167 37.4167,43.4167 37.4167,48.4167  z  M20.5833,20.5833 L55.4167,20.5833 L55.4167,55.4167 L42.4167,55.4167 L42.4167,49.4167 L36.4167,49.4167 L36.4167,44.3333 L30.0833,44.3333 L30.0833,55.4167 L20.5833,55.4167 L20.5833,20.5833  Z  M 33.25,55.4167L 33.25,50.6667L 39.5833,50.6667L 39.5833,55.4167L 33.25,55.4167  Z  M 26.9167,23.75L 26.9167,33.25L 49.0833,33.25L 49.0833,23.75L 26.9167,23.75  Z  "/>
    </Canvas>
```

And that's how it looks in Demo app:

![image](https://cloud.githubusercontent.com/assets/17061461/13107466/ea339854-d57e-11e5-8feb-2f925e543460.png)

**Comment by CADbloke** [comment]
In a lot of Windows Apps the "save as" icon is a floppy disk with a pencil. Have a look at Excel etc. Ditto with MS Paint. That's not to say I don't like your icon (it makes sense to me) but I'm just pointing out that Windows users are used to seeing the disk + pencil / pen. Seems to be the consensus with [Google image search](https://www.google.com.au/search?q=%22save+as%22+icon&tbm=isch) too.

Save All seems to be universally a few stacked disks.

**Comment by thoemmi** [comment]
@CADbloke is right, see Word's icon for _Save As_ in this screenshot (I only have a German version at hand currently)
![image](https://cloud.githubusercontent.com/assets/73690/13110049/c3d941dc-d57d-11e5-909b-b4f1d2a081c7.png)

**Comment by iSlaffko** [comment]
@CADbloke @thoemmi Yes, I'm aware of common icon and maybe it is better to call my version of it somewhat like 'SavePlus' and to create proper icons for 'SaveAs' and 'SaveAll'.
