### ISSUE TITLE
Possible to add flyouts to simpleChildWindow?

### ISSUE THREAD

**Issue by AndreasSchmid1** [MahApps/MahApps.Metro#2361]
Hallo guys, is it possible to add flyout support to the mahapps childWindow?
I tried something like that without success.

`  <simpleChildWindow:ChildWindow.Flyouts>
        <controls:FlyoutsControl>
            <controls:Flyout  >
               //Content
            </controls:Flyout>
        </controls:FlyoutsControl>
    </simpleChildWindow:ChildWindow.Flyouts>`

**Comment by punker76** [comment]
@AndreasSchmid1 First, SimpleChildWindow is not a MetroWindow, so this is not possible. Second, this is the wrong repo, you should go to https://github.com/punker76/MahApps.Metro.SimpleChildWindow
