### ISSUE TITLE
Theme inheritance with children controls.

### ISSUE THREAD

**Issue by kiwidoggie** [MahApps/MahApps.Metro#2364]
It seems a duplicate of https://github.com/MahApps/MahApps.Metro/issues/715 which I have looked and there is no InheritAccentColorsAndTheme in the current build of MahApps.Metro 1.2.4. Did this get deprecated? I currently am having the same exact issue. I would like some assistance to figure out how to re-enable that flag or if there is an error in my code.

I am currently using AvalonDock as well. I have the the metro window resources set to those as found in http://mahapps.com/guides/styles.html. One thing I do have to note is, my MainWindow isn't the entry point for the application. The window gets created later so I'm not sure if that has anything to do with it.

The way it works is I have a Binding for AvalonDock to automatically create the UserControl's

`<avalonDock:DockingManager.Resources>
                    <DataTemplate DataType="{x:Type ui:PluginViewModel}">
                        <UserControl Content="{Binding MainControl}">
                            <UserControl.Resources>
                            </UserControl.Resources>
                        </UserControl>
                    </DataTemplate>
                </avalonDock:DockingManager.Resources>
`

Even setting the theme in the UserControl's ResourceDictionary doesn't work properly.

Here is an image, it looks like half of the theme gets applied while on others it doesn't.
http://i.imgur.com/ZYadLIl.png

Using .NET Framework 4.6.1

Here is the link to a test project that shows the same problem.
https://github.com/kiwidoggie/AvalonDockMVVMMetroBug

**Comment by punker76** [comment]
@kiwidoggie You should style the avalon `LayoutItem`, it's not a `TabItem`, it's a custom FrameworkElement from AvalonDock.
