### ISSUE TITLE
Custom TextBox : nested control in ContentControl

### ISSUE THREAD

**Issue by SamOxyPlot** [MahApps/MahApps.Metro#2366]
Hi

I don't know if its possible to style my own set of framework controls.
I have a System.Windows.Controls.ContentControl object with a nested control inside of it. For example a normal TextBox. I call it a FwTextBox.

Currently I do have problems with styling the control. Because I can't use my own targettype...

**I use MahApps.Metro v1.1.2.**

This line doesn't work:
**Style="{DynamicResource MetroButtonTextBox}"** 
Because it targets a TextBox and not an FwTextBox.

```
<fwcontrols:FwTextBox Controls:TextBoxHelper.Watermark="Custom icon style"
                                      Controls:TextBoxHelper.ButtonContent="s"
                                      Style="{DynamicResource MetroButtonTextBox}"
                                      Grid.Row="0" Grid.Column="4" />
```

If more info is needed, just tell me.

Hopefully there is a sollution for this?

**Comment by punker76** [comment]
@SamOxyPlot Hi, try inherit your `FwTextBox` from `MetroButtonTextBox` instead normal `TextBox` style.

```xaml
<Style x:Key="FwTextBoxStyle" TargetType="FwTextBox" BasedOn="{StaticResource MetroButtonTextBox}">
  <!-- your Style Setters -->
</Style>
```

**Comment by SamOxyPlot** [comment]
Hi Punker76.

Thanks for the fast reply!

I've tried this allready, but I'm stuck on it.

This is the error:

<code>
An exception of type 'System.InvalidOperationException' occurred in PresentationFramework.dll but was not handled in user code

Additional information: Can only base on a Style with target type that is base type 'FwTextBox'.
</code>

**Comment by punker76** [comment]
@SamOxyPlot Seems like you have inherited the FwTextBox? Can you post the code behind and style? if so, then you must copy all the MahApps style to sytle your custom control/TextBox

**Comment by SamOxyPlot** [comment]
Hi Punker76

Some more background information:

public class FwTextBox : FwFrameworkElement<TextBox>

public abstract class FwFrameworkElement<TNestedControl> : ContentControl

The content of the FwFrameworkElement instance is set to the NestedControl (in this case an TextBox)

So we don't inherit from a TextBox directly. Because in our framework we do some extra logic for 'our' own controls. 

---------------------------------------------------------------------
We do have 3 projects:

Framework.App
Framework.Wpf
   --> Contains reference to MahApps.Metro
   --> Contains FwTextBox, FwFrameworkElement, ...
Project.Wpf
   --> Contains a View with a FwTextBox

So the styles are shared between 2 projects also. 

What should I add/modify to make the MahApps style working?

**Comment by punker76** [comment]
@SamOxyPlot Thx for additional information. I think, if I understand right, that you only must set the inner TextBox (your content) style to `MetroButtonTextBox` (or your own custom one).

**Comment by SamOxyPlot** [comment]
@punker76 

Thanks again for the fast reply!

Well it should be defined in the XAML, not in codebehind.

I have:

```
xmlns:Controls="http://metro.mahapps.com/winfx/xaml/controls"
xmlns:fwcontrols="clr-namespace:Framework.Wpf.Controls;assembly=Framework.Wpf"
```

```
<Style x:Key="FwTextBoxStyle" TargetType="fwcontrols:FwTextBox" BasedOn="{StaticResource MetroButtonTextBox}">
     <Setter Property="Background" Value="Black" />
     <Setter Property="FontStyle" Value="Italic" />
</Style>
```

```
<TextBox x:Name="Works" Controls:TextBoxHelper.Watermark="Custom icon style"
            Controls:TextBoxHelper.ButtonContent="s"
            Grid.Row="0" Grid.Column="4" />

<fwcontrols:FwTextBox x:Name="DontWorks" Controls:TextBoxHelper.Watermark="Custom icon style"
            Controls:TextBoxHelper.ButtonContent="s"
            Grid.Row="0" Grid.Column="5" />
```

When I apply the style on my FwTextBox control:

```
<fwcontrols:FwTextBox x:Name="DontWorks" Controls:TextBoxHelper.Watermark="Custom icon style"
            Controls:TextBoxHelper.ButtonContent="s"
            Style="{DynamicResource FwTextBoxStyle}"
            Grid.Row="0" Grid.Column="5" />
```
Following error commes:

```
An exception of type 'System.InvalidOperationException' occurred in PresentationFramework.dll but was not handled in user code

Additional information: Can only base on a Style with target type that is base type 'FwTextBox'.

```

Is there a way to target the innercontrol (TextBox) of a FwTextBox?

**Comment by punker76** [comment]
@SamOxyPlot You can make a Dependency Property (e.g. InnerControlStyle) on your FwTextBox/FwFrameworkElement. So you can set and use it in XAML.

**Comment by SamOxyPlot** [comment]
@punker76 

Good propasal!

For now I tried with a nested style

```
        <Style x:Key="FwTextBoxStyle" TargetType="fwcontrols:FwTextBox">
            <Style.Resources>
                <Style TargetType="TextBox" BasedOn="{StaticResource MetroButtonTextBox}">
                    <Setter Property="Background" Value="Black" />
                    <Setter Property="Foreground" Value="Red" />
                    <Setter Property="FontStyle" Value="Italic" />
                </Style>
            </Style.Resources>
        </Style>
```

```
<fwcontrols:FwTextBox x:Name="textbox" Grid.Row="0" Grid.Column="1" Style="{DynamicResource FwTextBoxStyle}" 
                                      Controls:TextBoxHelper.Watermark="Custom icon style" ></fwcontrols:FwTextBox>
```

I don't get errors when running, but the style isn't applied. 

**Is there something that could overrule it?**

**Comment by punker76** [comment]
@SamOxyPlot :+1:

**Comment by SamOxyPlot** [comment]
@punker76 
 
**Thanks for the quick support!**
