### ISSUE TITLE
PasswordBoxBindingBehavior NullReferenceException during Detach

### ISSUE THREAD

**Issue by thomasjoscht** [MahApps/MahApps.Metro#2369]
Hey, I encounter a NullReferenceException in PasswordBoxBindingBehavior by navigating away from a page containing a PasswordBox with Style Win8MetroPasswordBox/MetroButtonRevealedPasswordBox and used PasswordBoxBindingBehavior :

System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei MahApps.Metro.Behaviours.PasswordBoxBindingBehavior.OnDetaching() in C:\TeamCity\buildAgent\work\b90af7509433a217\MahApps.Metro\Behaviours\PasswordBoxBindingBehavior.cs:Zeile 92.
   bei System.Windows.Interactivity.Behavior.Detach()
   bei MahApps.Metro.Behaviours.StylizedBehaviors.FrameworkElementUnloaded(Object sender, RoutedEventArgs e) in C:\TeamCity\buildAgent\work\b90af7509433a217\MahApps.Metro\Behaviours\StylizedBehaviors.cs:Zeile 94.
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bei System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   bei System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   bei System.Windows.BroadcastEventHelper.BroadcastUnloadedEvent(Object root)
   bei MS.Internal.LoadedOrUnloadedOperation.DoWork()
   bei System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   bei System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   bei System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   bei System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by punker76** [comment]
@thomasjoscht Please retest it with MahApps.Metro 1.3.0-ALPHA039, thx!

**Comment by thomasjoscht** [comment]
@punker76 Thanks a lot! It works in my case.
