### ISSUE TITLE
Flyout Background changes when i change Accent

### ISSUE THREAD

**Issue by MattBg** [MahApps/MahApps.Metro#2373]
## What steps will reproduce this issue?

I created a method that sets the Accent in my application. When i open a flyout without change Accent, it's background it's the same as the Theme (BaseDark/Light), but if i change accent with my method, the Flyout Background will become like the selected Accent.

I'm using this VB code for change Accent and Theme

```
Dim theme = ThemeManager.DetectAppStyle(Application.Current)
ThemeManager.ChangeAppStyle(Application.Current, ThemeManager.GetAccent(_accentToUse), ThemeManager.GetAppTheme(_themeToUse))
```
For now i fixed this issue simply by changing manually  the Background of my Flyouts, but i wonder if there's a Flyout's property that keeps his color (the one like the theme color) and doesn't change when i switch accent.

My feeling is that i'm changing the Accent/Theme in a bad way, can you suggest a way that does not touch the flyout?

### Expected outcome

It would be great if the background of my Flyout remain unchanged

--
### Environment

- MahApps.Metro __v1.2.4.0__
- Windows __7__
- Visual Studio __2013__
- .NET Framework __4.0__

**Comment by punker76** [comment]
@MattBg Which `Theme` do you set on your `Flyout`?

Maybe this?

```xaml
<Controls:Flyout Header="Accented" Theme="Accent" />
```

**Comment by MattBg** [comment]
Thank you, the Theme property was set on Accent instead of Adapt, now the Flyouts behave as expected. Thank you again and sorry because i realized just now how my issue was trivial, i don't know how i could miss that.

**Comment by punker76** [comment]
@MattBg np, happy coding :+1:
