### ISSUE TITLE
MahApps.Metro consistent style and template names/keys

### ISSUE THREAD

**Issue by punker76** [MahApps/MahApps.Metro#2384]
MahApps.Metro styles and template keys are non consostent.
### Expected outcome

Consistent names/keys for all styles and templates.

e.g.

`Win10WindowButtonCommandsTemplate` -> `MahApps.Metro.Templates.WindowButtonCommands.Win10`
`MetroFlatButton` -> `MahApps.Metro.Styles.FlatButton`

etc

**Comment by amkuchta** [comment]
This is going to be so tedious :no_mouth: :no_mouth:

**Comment by punker76** [comment]
@amkuchta v2.0 will be a great release -:-D

**Comment by Evangelink** [comment]
Hi @punker76,

Is this ticket still active? If so, which naming do you want to go for? 

I'd be happy to give some help.

**Comment by Evangelink** [comment]
@punker76 what do you think about the following convention:

`MahApps.Metro.` 
\+ `Style.` or `Template.` 
\+ Category (e.g. `Metro`, `Flat`, `Square`, `Win10`...) 
\+ Control (e.g. `Button`, `ToggleButton`...) 
\+ optional specifier (e.g. `Light`, `Dark`, `Accented`...)

which would give the following names:

- `MahApps.Metro.Style.Flat.Button`
- `MahApps.Metro.Style.Metro.Button`
- `MahApps.Metro.Style.Metro.WindowButton.Base`
- `MahApps.Metro.Style.Metro.WindowButton.Light`
- `MahApps.Metro.Style.Metro.TextBox.Search`
- `MahApps.Metro.Style.Metro.TextBox.Button`

Remarks:

- We could omit the `Metro` after `Style.`/`Template.` to avoid the redundancy but it would be less of a standard construction

- We could omit the `Metro` after `MahApps.` but I don't know from a product name POV if that's ok.

- We could merge the Control and specifier parts to get something like `SearchTextBox`, `ButtonTextBox`, `LightWindowButton`, `DarkWindowButton`...

WDYT?

**Comment by punker76** [comment]
@Evangelink You are going in the same direction as I want to go:

I already changed some of the styles with these naming, like

- `MahApps.Metro.Styles.xyz`
- `MahApps.Metro.Styles.DataGrid.xyz` ... `xyz.Win10`
- `MahApps.Metro.Styles.Slider.xyz` ... `xyz.Win10`
- `MahApps.Metro.Styles.FlatSlider.xyz` ...

and

- `MahApps.Metro.Templates.WindowButtonCommands.xyz`
- `MahApps.Metro.Templates.MetroTabControl.xyz`

and so on.

So my convention was

`MahApps.Metro`
+ `Styles` or `Templates` or `Brushes`
+ `Control` (e.g. `DataGrid`, `Slider`, ...)
+ `Optional Specifier`
+ `Catagory` (e.g. `Win10`)

And yes, I'm also with these

- omit `Metro` after `MahApps`, because we are more and more MahApps ;-D (because of teh Win10 styles)
- merge Control and specifier parts

**Comment by Evangelink** [comment]
Final naming chosen is:

`MahApp.`
+ the resource type which is one of `Colors.`, `Brushes.`, `Templates.`, `Sizes.`, `Fonts.`, `Storyboard.`, `Styles.`
+ the target control for `Templates` and `Styles` (e.g. `Slider.`, `Window.`...)
+ an optional specifier which gives more context (e.g. `Slider` for `MahApps.Styles.Thumb` which helps understanding that this thumb style is for the context of a slider)
+ an optional category (e.g. `Metro`, `Flat`, `Square`, `Win10`...)
