### ISSUE TITLE
ButtonCommandMetroTextBox text displaid over icon.

### ISSUE THREAD

**Issue by GAMP** [MahApps/MahApps.Metro#2385]
![new bitmap image](https://cloud.githubusercontent.com/assets/4171664/13436463/08483854-dfe8-11e5-8da4-befd74873c2d.jpg)

- MahApps.Metro Nightly
- Windows 10
- Visual Studio 2015
- .NET Framework 4.6.1

**Comment by punker76** [comment]
@GAMP thx, i'll look at this tonight

**Comment by punker76** [comment]
@GAMP done by https://github.com/MahApps/MahApps.Metro/pull/2387
