### ISSUE TITLE
Text blurry after Upgrading from V1.1.2 to V1.2.4

### ISSUE THREAD

**Issue by mavo1848** [MahApps/MahApps.Metro#2401]
## What steps will reproduce this issue?

Since upgrading MahApps.Metro in my Project from V1.1.2 to V1.2.4 some Text seems to be blurry. 

Version 1.1.2:
![diag1](https://cloud.githubusercontent.com/assets/5233112/13577727/3f2dbc80-e494-11e5-99bd-152de80998ef.png)

Version 1.2.4:
![diag2](https://cloud.githubusercontent.com/assets/5233112/13577728/40c5df5a-e494-11e5-813b-76dbd7a593a0.png)

What can be the reason for this and how can i avoid this behavior?

Text is normal (not blurry) when there is no DropShadowEffect at the Border like this:

>     <Border.Effect>
      <DropShadowEffect BlurRadius="3" Opacity=".5" />
    </Border.Effect>

--
### Environment

- MahApps.Metro __v1.2.4__
- Windows __10__
- Visual Studio __2015__
- .NET Framework __4.0__

**Comment by punker76** [comment]
@mavo1848 Please try the latest pre-release (also available on nuget). There was a wrong usage of text options in transition control. Also using an effect on a border with content makes the content always blurry, that's caused by WPF.

**Comment by mavo1848** [comment]
Thank you very much! The latest pre-release solves this issue not but your hint with the Border was the solution.
