### ISSUE TITLE
How to change theme/accent in a WPF library class and affect UserControls inside it

### ISSUE THREAD

**Issue by MattBg** [MahApps/MahApps.Metro#2406]
## What steps will reproduce this issue?

I created a wpf application that uses mahapps. It works great and all my usercontrols are able to change theme and accent only by using the ChangeAppStyle method.

The big problem was raised when i converted my application into a WPF Class Library, because i must insert this application inside a bigger project. I converted all, i crearted a custom resource dictionary ResDic.xaml inside my project who contains all mahapps dictionaires. 

In the xaml of every UC or Window, i create a resourceDisctionary with my custom ResDict as source, in this way i'm able to use a WPF application as a dll inside another project (basically it's a workaround because as dll i have no application.xaml / app.config)

I must use This/Me in the first argument of the ChangeAppStyle  method but it works only for the current window, it does not affect the user controls inside it.

How can i change the theme of the window and all user controls inside? I don't know how apply ChangeAppStyle  to a userControl, or call ChangeAppStyle ina way that affects every item inside it.

In my UserControls i have bindings `like BorderBrush="{DynamicResource AccentColorBrush}"`
that gives me always the default blue accent and are not affected when i change accent in the main window with ChangeAppStyle

### Environment

- MahApps.Metro __v1.2.4.0__
- Windows __7__
- Visual Studio __2013__
- .NET Framework __4.0__

**Comment by punker76** [comment]
@MattBg You can pass also a Window to the ChangeAppStyle method

```csharp
public static void ChangeAppStyle(Window window, Accent newAccent, AppTheme newTheme)
```

or with

```csharp
public static void ChangeAppStyle(ResourceDictionary resources, Accent newAccent, AppTheme newTheme)
```

**Comment by MattBg** [comment]
Thank you, but i already tryed by creating a ResourceDictionary object with a source Uri to my ResDict but doesn't work, my application always keeps the default white & blue theme. 

I'm totally clueless about how handle resources in this situation, i must pass the current ResiurceDictionay used by main window to the userControl methos, or i must create a global one?

And if i use a window, it affects only the window passed and not others, additionally my usercontrols are not windows and i can't use that method on them, is there a way to use ChangeAppStyle on usercontrols?

**Comment by punker76** [comment]
@MattBg You must pass the resource dictionary (not the global one which you defined) of the Window or UserControl or whatever

```csharp
// this can be the Window/UserControl or whatever
ChangeAppStyle(this, newAccent, newTheme);
// or
ChangeAppStyle(this.Resources, newAccent, newTheme);
```

**Comment by punker76** [comment]
@MattBg If you want to notice about theme changes in your UserControl, you can use this event

```chsarp
ThemeManager.IsThemeChanged += ThemeManagerOnIsThemeChanged;

...

private void ThemeManagerOnIsThemeChanged(object sender, OnThemeChangedEventArgs e)
{
  var appTheme = e.AppTheme;
  var accent = e.Accent;
}

```

**Comment by MattBg** [comment]
This works perfectly. I resolved by creating a method inside the UC that changes the theme with Me.Resourcer. Thank you very much, you saved my day (as usual :] ) !

**Comment by punker76** [comment]
:+1:
