### ISSUE TITLE
MetroWindow can be closed while a modal dialog is shown

### ISSUE THREAD

**Issue by pfattisc** [MahApps/MahApps.Metro#2409]
## What steps will reproduce this issue?
While a modal dialog is shown the user can close the metrowindow using the contextmenu of the taskbar (right click on taskbar => close window).

### Expected outcome

While a modal dialog is shown the MetroWindow shouldn't close in any case.

--
### Environment

- MahApps.Metro __v1.2.4__
- Windows __7 x64__
- Visual Studio __2013__
- .NET Framework __4.5__

**Comment by punker76** [comment]
@pfattisc this is by design, cause dialogs in mahapps not modal, they are async... i'll take a look

**Comment by pfattisc** [comment]
I think the overlay dialog is a modal dialog and therefore should prevent a close of the application.
The overlay does also prevent the user from using the window's control box (minimize, restore, close) so why should the user be able to circumvent this by using the taskbar?
