### ISSUE TITLE
Request for Accordion Control

### ISSUE THREAD

**Issue by jammerxd** [MahApps/MahApps.Metro#2412]
Hello, I would like to request an accordion style control that is animated and similar to the treeview but where you use an arrow and it rotates down as the content animates in. The animation would be similar to a tabcontrol and tabitem but I am unsure as to how to do this on my own.

EDIT: The control I am looking for is the expander...if you could add an animated template for it, similar to the tab controls, that would be awesome!

Thank you! I absolutely LOVE this framework!

**Comment by chrisklepeis** [comment]
The accordion is in the WPF toolkit http://www.c-sharpcorner.com/uploadfile/dpatra/accordion-in-wpf-toolkit/ 

Just needs some metro lovin'

**Comment by xxMUROxx** [comment]
@chrisklepeis this would introduce a dependency on WPF toolkit to MahApps. I would not add to many 3rd party libraries as dependency to MahApps

**Comment by chrisklepeis** [comment]
Ya, thought about that after posting... Would have to be a custom control or just perhaps a control template over an existing control.
