### ISSUE TITLE
TransitioningContentControl makes content look aliased

### ISSUE THREAD

**Issue by AbelToy** [MahApps/MahApps.Metro#2417]
## What steps will reproduce this issue?

Create a UserControl that displays big text, something like

```XAML
<TextBlock FontSize="{DynamicResource HeaderFontSize}" FontFamily="{DynamicResource HeaderFontFamily}">
    Feature Demos!
</TextBlock>
```
Display that UserControl inside a ContentControl and inside a TransitioningContentControl.

### Expected outcome

Both should look anti-aliased, but only ContentControl looks anti-aliased. The text on TransitioningContentControl looks aliased (as well as the shapes in it if you place some).

--
### Environment

- MahApps.Metro __v1.2.4__
- Windows __10__
- Visual Studio __2015__
- .NET Framework __4.6.1__

**Comment by punker76** [comment]
@AbelToy please try latest pre-release, it should be already fixed

**Comment by AbelToy** [comment]
Yep, it works in the pre-release version! Thanks!

**Comment by punker76** [comment]
![giphy](https://cloud.githubusercontent.com/assets/658431/13634209/a268ea70-e5f4-11e5-882e-38a1bb14de99.gif)
