### ISSUE TITLE
[Question] Datagrid

### ISSUE THREAD

**Issue by di48l069** [MahApps/MahApps.Metro#2418]
Hi,

In Datagrid example how did you highlight the entire row a specific color for example your sample was `red`

**Comment by punker76** [comment]
@di48l069 Just take a look at the [sample](https://github.com/MahApps/MahApps.Metro/blob/develop/samples/MetroDemo/ExampleViews/DataGridExamples.xaml#L134-L181)

**Comment by di48l069** [comment]
@punker76 I see it thanks
