### ISSUE TITLE
DialogManager ShowMetroDialogAsync ignores MetroDialogSettings parameter

### ISSUE THREAD

**Issue by pfattisc** [MahApps/MahApps.Metro#2419]
## What steps will reproduce this issue?
DialogManager.ShowMetroDialogAsync() has an overload with MetroDialogSettings.
These settings are ignored.

### Expected outcome
ShowMetroDialogAsync should be aware of the settings parameter.

--
### Environment

- MahApps.Metro __v1.2.4__
- Windows __7 x64__
- Visual Studio __2013__
- .NET Framework __4.5__

**Comment by punker76** [comment]
@pfattisc this is in dev branch fixed
