### ISSUE TITLE
NumericUpDown Validation Error Message.

### ISSUE THREAD

**Issue by feinstein** [MahApps/MahApps.Metro#2426]
## What steps will reproduce this issue?

_Place a `NumericUpDown` with a validation from MVVM, like:_

         <mahapps:NumericUpDown Value="{Binding MyInt, ValidatesOnDataErrors=True, UpdateSourceTrigger=PropertyChanged}" .................

And the Property being Binded as:

        [Range(1, int.MaxValue, ErrorMessage = "Value out of Range.")]
        public int MyInt
        {
            get { return this.myInt; }
            set { SetProperty(ref myInt, value); } // This sets the property and raises the INotifyPropertyChanged event.
        }

And make sure your class derives from this class (it makes the validation on all `Attributes`:

	public abstract class BindableDataErrorInfoBase : BindableBase, IDataErrorInfo
    {
        [NotMapped]
        public bool IsValid
        {
            get
            {
                return Validator.TryValidateObject(this, new ValidationContext(this), new Collection<ValidationResult>(), true);
            }
        }

        #region IDataErrorInfo Members
        /// <summary>
        /// IDataErrorInfo Interface Error Message for the object.
        /// </summary>
        [NotMapped]
        public string Error
        {
            get { throw new NotImplementedException(); }
        }

        /// <summary>
        /// Valida uma propriety com o nome enviado para o indexer.
        /// </summary>
        /// <param name="propertyName">Nome da Property.</param>
        /// <returns>Um erro de validação, ou null caso nao tenha erros.</returns>
        public string this[string propertyName]
        {
            get
            {
                var context = new ValidationContext(this)
                {
                    MemberName = propertyName
                };

                var results = new Collection<ValidationResult>();
                bool isValid = Validator.TryValidateObject(this, context, results, true);

                if (!isValid)
                {
                    ValidationResult result = results.SingleOrDefault(p =>
                                                                      p.MemberNames.Any(memberName =>
                                                                                        memberName == propertyName));

                    return result == null ? null : result.ErrorMessage;
                }

                return null;
            }
        }
        #endregion
    }

This Class uses `BindableBase` which can be found on Prism 5 (latest stable) over NuGet. Or don't use it and just implement your `IDataErrorInfo`, it has to have the same outcome, since in my tests this validations are not being executed, the error is shown before, so I am guessing it's something in the control `NumericUpDown` itself.

And erase the value on the `NumericUpDown` and get out of the control, making it lose focus.

The `NumericUpDown` will show this Error Message:

![valuecouldnotbeconvertederrornumericupdown](https://cloud.githubusercontent.com/assets/8120472/13691940/a36a64f8-e71b-11e5-8144-114b4a678c99.jpg)

### Expected outcome

_The validation Pop Up should show the Error Message `Value out of Range.`_

--
### Environment

- MahApps.Metro __v1.2.4__
- Windows __7x64__
- Visual Studio __2015__
- .NET Framework __4.5__

**Comment by punker76** [comment]
@feinstein I think this is not a bug in MahApps it's more that you must handle this by yourself.

http://stackoverflow.com/q/6153302/920384
http://stackoverflow.com/q/28931250/920384
https://joshsmithonwpf.wordpress.com/2008/11/14/using-a-viewmodel-to-provide-meaningful-validation-error-messages/

**Comment by feinstein** [comment]
@punker76 yes, I think you are right... I am sorry about this,  I am a little rust on validation... I guess it has been half a year since I had come around any validations from the the binding pipeline.
