### ISSUE TITLE
SquareButtonStyle Text Lowercase

### ISSUE THREAD

**Issue by ThePenguinRocks** [MahApps/MahApps.Metro#2430]
## What steps will reproduce this issue?

<Button Content="Save" Style="{DynamicResource SquareButtonStyle}"/>

Button Text = "save"
The Buttons Text is lowercase

### Expected outcome

Button Text = "Save" 

### Environment

- MahApps.Metro __v1.2.4__
- Windows __10__
- Visual Studio __2015__
- .NET Framework __4.6.1__

**Comment by punker76** [comment]
@ThePenguinRocks You can change this by set `ControlsHelper.ContentCharacterCasing` attached property.

**Comment by ThePenguinRocks** [comment]
Thank You
