### ISSUE TITLE
unable to give glowbrush property in code behind

### ISSUE THREAD

**Issue by aabhishrma** [MahApps/MahApps.Metro#2431]
## var _objHomeWindow = new MetroWindow();
          _objHomeWindow.GlowBrush.SetValue(blah blah );

I am new to WPFand metro window  please help me to give glowbrush  in code behind

Windows

- MahApps.Metro 1.2.4.0
- Windows 10
- Visual Studio 2013
- .NET Framework 4.5

**Comment by punker76** [comment]
@aabhishrma 

```
_objHomeWindow.GlowBrush = Brushes.Green;
```

If this doesn't help, then it's maybe necessary to to this in the loaded event

```
_objHomeWindow.Loaded += (s, e) => _objHomeWindow.GlowBrush = Brushes.Green;
```
