### ISSUE TITLE
Missing Icons? (appbar_control_skip_forward)

### ISSUE THREAD

**Issue by chrisklepeis** [MahApps/MahApps.Metro#2433]
I'm trying to use some icons from the sample project. For the most part they're working, but it can't find a few, specifically appbar_control_skip_forward.

I'm using the instructions here to get it setup http://mahapps.com/guides/icons-and-resources.html (again, other icons are working)

Works:
```
<Rectangle Width="8" Height="8">
    <Rectangle.Fill>
        <VisualBrush Stretch="Fill" Visual="{StaticResource appbar_chevron_right}" />
    </Rectangle.Fill>
</Rectangle>

```

Does not work:

```
<Rectangle Width="8" Height="8">
    <Rectangle.Fill>
        <VisualBrush Stretch="Fill" Visual="{StaticResource appbar_control_skip_forward}" />
    </Rectangle.Fill>
</Rectangle>
```

> Cannot find resource named 'appbar_control_skip_forward'. Resource names are case sensitive.

In my App.xaml (resources installed via nuget package):

```
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Colors.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/Steel.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/BaseLight.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/FlatButton.xaml" />
                <ResourceDictionary Source="/Resources/Icons.xaml" />
...
```

**Comment by punker76** [comment]
@chrisklepeis The icons are `appbar_control_fastforward` or `appbar_control_fastforward_variant`

![2016-03-16_22h21_11](https://cloud.githubusercontent.com/assets/658431/13829122/906c40d4-ebc5-11e5-8127-3e6a53712208.png)

**Comment by chrisklepeis** [comment]
So I should assume they were removed? It does show up in the demo project

![capture](https://cloud.githubusercontent.com/assets/16291940/13829326/ce3a0fd2-eb9c-11e5-85b2-99a455a3e5d4.PNG)

**Comment by punker76** [comment]
@chrisklepeis oh, you're right, but then I don't know what's wrong with your code

![2016-03-16_22h32_59](https://cloud.githubusercontent.com/assets/658431/13829419/309af338-ebc7-11e5-8bd4-d030cd12b847.png)

**Comment by punker76** [comment]
@chrisklepeis which MahApps version and which MahApps resources version are you using?

**Comment by chrisklepeis** [comment]
The latest 

```
  <package id="MahApps.Metro" version="1.2.4.0" targetFramework="net46" />
  <package id="MahApps.Metro.Resources" version="0.4.0.0" targetFramework="net46" />
```

**Comment by chrisklepeis** [comment]
The recent nuget package update (0.5.0.0) fixed the issue.

Thanks.
