### ISSUE TITLE
Remove space on top of the Flyouts

### ISSUE THREAD

**Issue by jeromeMartinet** [MahApps/MahApps.Metro#2436]
How to remove the space on the top of the flyouts ? 
I hide the close button and the title but it's not enough

Thxs
--
### Environment

- MahApps.Metro 1.2.4
- Windows 10
- Visual Studio 2015
- .NET Framework 4.5.2

**Comment by punker76** [comment]
@jeromeMartinet What do you really mean with `space`? do you mean the title bar height?

**Comment by punker76** [comment]
@jeromeMartinet ???
