### ISSUE TITLE
Resource interchange problem when using x:Shared="False"

### ISSUE THREAD

**Issue by xxMUROxx** [MahApps/MahApps.Metro#2440]
I think the problem with x:Shared="False" is a .NET problem. I have reported the issue in [Microsoft Connect](https://connect.microsoft.com/VisualStudio/feedback/details/2497914/nullreferenceexception-when-calling-this-resources-mergeddictionaries-add)

This item is to not forget about the issue and have reference to Microsoft Connect site.

@punker76  

See also: https://github.com/MahApps/MahApps.Metro/issues/2300

**Comment by punker76** [comment]
@xxMUROxx There is now a new MahApps.Metro.Resources 0.6.0 which includes a new resource `IconsNonShared.xaml`. It contains the Icons with the `x:Shared="False"`, so all other users who doesn't need this and had the same issue with the exception can now sleep again :-D

**Comment by punker76** [comment]
-> https://github.com/MahApps/MahApps.Metro.Resources/issues/1
