### ISSUE TITLE
Custom TitleTemplate no longer receives any mouse events, specifically double click

### ISSUE THREAD

**Issue by zmakerss** [MahApps/MahApps.Metro#2442]
## What steps will reproduce this issue?

_Write problem description here_

### Expected outcome

_Write expected outcome here_

--
### Environment

- MahApps.Metro __v?.?.?__
- Windows __??__
- Visual Studio __20xx__
- .NET Framework __?.?__

**Comment by zmakerss** [comment]
Custom TitleTemplate no longer receives any mouse events, specifically double click. Lets say I have a custom title bar, which I want to double click and capture this event, in the latest release the double click event is no longer passed from title bar to the items in title bar template.

**Comment by punker76** [comment]
@zmakerss I understand that you want a custom titlebar with a custom template, but why do you need capture the double click event? The change is, that we use now a thumb to dragmove and max/restore the window.

**Comment by zmakerss** [comment]
Lets say you want to give user the ability to rename the window, which is my requirement. I created a custom title template which displays a textblock with the window name, then a user can double click the textblock, and in the double click event I hide the textblock and display a textbox, where a user can enter a new name, press enter, and save the changes. With the latest release, the double click even is no longer passed to the title template children.

**Comment by punker76** [comment]
@zmakerss This is fixed in the pre-release now
