### ISSUE TITLE
Flyout Background Is White

### ISSUE THREAD

**Issue by Hikerakashiya** [MahApps/MahApps.Metro#2443]
## What steps will reproduce this issue?

I am using MahApps.Metro with Caliburn.Micro and implemented flyouts the same way they were implemented in the Caliburn.Metro.Demo project. I started noticing the issue after I updated the MahApp.Metro package to the latest version. Originally I had the theme of the flyout being set in the constructor of the flyout view model. I was using the Dark theme. I set the style of the flyouts control and binded the Theme property to a property in my view model.

```
<controls:MetroWindow.Flyouts>
        <controls:FlyoutsControl ItemsSource="{Binding Flyouts}">
            <controls:FlyoutsControl.ItemTemplate>
                <DataTemplate>
                    <ContentControl cal:View.Model="{Binding}" />
                </DataTemplate>
            </controls:FlyoutsControl.ItemTemplate>
            <controls:FlyoutsControl.ItemContainerStyle>
                <Style BasedOn="{StaticResource {x:Type controls:Flyout}}" TargetType="{x:Type controls:Flyout}">
                    <Setter Property="Header" Value="{Binding Header}" />
                    <Setter Property="IsOpen" Value="{Binding IsOpen}" />
                    <Setter Property="Position" Value="{Binding Position}" />
                    <Setter Property="Theme" Value="{Binding Theme}" />
                </Style>
            </controls:FlyoutsControl.ItemContainerStyle>
        </controls:FlyoutsControl>
    </controls:MetroWindow.Flyouts>
```

After looking at the latest source code I noticed you no longer were setting the theme of the flyout as a view model property, but using a resource in the user control. However I noticed, all of the flyout examples did not have the BaseDark theme set as a user control resource so I was unable to determine what was making the flyouts have a dark background in the demo project.

```
    <UserControl.Resources>
        <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/BaseDark.xaml" />
    </UserControl.Resources>
```

I tried setting the theme of the flyouts in the view model and I tried setting the theme of the flyouts in the xaml and hardcoded the theme property in the setter. I even removed my custom theme.

```
<Setter Property="Theme" Value="Dark" />
```

Custom Theme:

```
<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">

    <!--ACCENT COLORS-->
    <Color x:Key="HighlightColor">#FF20366A</Color>

    <!--80%-->
    <Color x:Key="AccentColor">#CC20366A</Color>
    <!--60%-->
    <Color x:Key="AccentColor2">#9920366A</Color>
    <!--40%-->
    <Color x:Key="AccentColor3">#6620366A</Color>
    <!--20%-->
    <Color x:Key="AccentColor4">#3320366A</Color>

    <SolidColorBrush x:Key="HighlightBrush" Color="{StaticResource HighlightColor}" />
    <SolidColorBrush x:Key="AccentColorBrush" Color="{StaticResource AccentColor}" />
    <SolidColorBrush x:Key="AccentColorBrush2" Color="{StaticResource AccentColor2}" />
    <SolidColorBrush x:Key="AccentColorBrush3" Color="{StaticResource AccentColor3}" />
    <SolidColorBrush x:Key="AccentColorBrush4" Color="{StaticResource AccentColor4}" />

    <SolidColorBrush x:Key="WindowTitleColorBrush" Color="{StaticResource AccentColor}" />

    <LinearGradientBrush x:Key="ProgressBrush" EndPoint="0.001,0.5" StartPoint="1.002,0.5">
        <GradientStop Color="{StaticResource HighlightColor}" Offset="0" />
        <GradientStop Color="{StaticResource AccentColor3}" Offset="1" />
    </LinearGradientBrush>

    <SolidColorBrush x:Key="CheckmarkFill" Color="{StaticResource AccentColor}" />
    <SolidColorBrush x:Key="RightArrowFill" Color="{StaticResource AccentColor}" />

    <Color x:Key="IdealForegroundColor">White</Color>
    <SolidColorBrush x:Key="IdealForegroundColorBrush" Color="{StaticResource IdealForegroundColor}" />
    <SolidColorBrush x:Key="IdealForegroundDisabledBrush" Color="{StaticResource IdealForegroundColor}" Opacity="0.4" />
    <SolidColorBrush x:Key="AccentSelectedColorBrush" Color="{StaticResource IdealForegroundColor}" />

    <SolidColorBrush x:Key="MetroDataGrid.HighlightBrush" Color="{StaticResource AccentColor}" />
    <SolidColorBrush x:Key="MetroDataGrid.HighlightTextBrush" Color="{StaticResource IdealForegroundColor}" />
    <SolidColorBrush x:Key="MetroDataGrid.MouseOverHighlightBrush" Color="{StaticResource AccentColor3}" />
    <SolidColorBrush x:Key="MetroDataGrid.FocusBorderBrush" Color="{StaticResource AccentColor}" />
    <SolidColorBrush x:Key="MetroDataGrid.InactiveSelectionHighlightBrush" Color="{StaticResource AccentColor2}" />
    <SolidColorBrush x:Key="MetroDataGrid.InactiveSelectionHighlightTextBrush" Color="{StaticResource IdealForegroundColor}" />
</ResourceDictionary>

        protected override void OnStartup(StartupEventArgs e)
        {
            ThemeManager.AddAccent("Theme", new Uri("pack://application:,,,/Accents/Theme.xaml"));

            ThemeManager.ChangeAppStyle(Current, ThemeManager.GetAccent("Theme"), ThemeManager.GetAppTheme("BaseLight"));

            base.OnStartup(e);
        }
```

Whatever I do, I either have flyouts that always have a white background, or if I do not set a theme at all (in app.xaml or app.xaml.cs), I have flyouts that always have a transparent background.

I do not understand what I am doing wrong. I keep looking at the Caliburn.Metro.Demo project and see that all the flyouts in the demo have a dark theme. Please help.

![image](https://cloud.githubusercontent.com/assets/12399352/13997647/736007b6-f109-11e5-8906-8d4e5cb98e82.png)

### Expected outcome

Flyouts use the theme that is set for it.

--
### Environment

- Caliburn.Micro __v3.0.0__
- MahApps.Metro __v1.2.4__
- Windows __7__
- Visual Studio __2013__
- .NET Framework __4.5__

**Comment by Hikerakashiya** [comment]
This is interesting ...

I failed to mention I had originally removed the Blue and BaseLight accents from the App.xaml because I was using my custom theme which was manually set in the App.xaml.cs. I figured I no longer need the Blue and BaseLight accent since my custom theme took care of this.

I removed this from the App.xaml Application.Resources:
```
<ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/Blue.xaml" />
<ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/BaseLight.xaml" />
```

I just tried readding these back to the App.xaml and the Flyout control started obeying the Theme I set for it.

```
I tried <Setter Property="Theme" Value="Dark" />. It worked! It was now dark.
I tried <Setter Property="Theme" Value="Accent" /> It worked! It was now a dark blue which was defined in my custom theme.
I tried removing <Setter Property="Theme" Value="Dark" /> and it was still dark. Is Dark the default theme of flyouts if you do not set the theme of the flyout?
```

The issue appears to be with using a custom theme and not having any accents set in the App.xaml.
Why is this? For the Flyout Theming to work, I had to add:

```
<ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/Blue.xaml" />
<ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/BaseLight.xaml" />
```

to my App.xaml, even though I was setting the theme using the ThemeManager in the App.xaml.cs.

**Comment by punker76** [comment]
@Hikerakashiya I've updated the `Caliburn.Micro` sample. There was a problem in `ViewLocator.GetOrCreateViewType`, it adds the resources to all created types, so for the Flyouts UserControls too. This UserControls are shown for each Flyout. But adding these resources to each UserControl was bad, cause the Flyout itself handles the `Theme` and adds the corresponding MahApps theme resource. So in this case it doesn't override the UserControl resources. I hope my explanation is good enough. By the way, your custom accent is not uptodate :-D

**Comment by Hikerakashiya** [comment]
Can you explain what you mean by the custom accent is not up to date? I used the stock Blue.xaml accent as a reference.

**Comment by Hikerakashiya** [comment]
@punker76 This issue is back. I updated to the latest release and none of my flyouts have a theme to them.
