### ISSUE TITLE
WindowCommand.ItemsSource bindings issue

### ISSUE THREAD

**Issue by igorushi** [MahApps/MahApps.Metro#2444]
## What steps will reproduce this issue?

in version 1.2.4 WindowCommand.ItemsSource bindings became broken. e.g.
```
<Metro:WindowCommands ItemsSource="{Binding WindowCommands}"
ItemTemplate="..." /> is not showing binded items.
```
[This commit](https://github.com/MahApps/MahApps.Metro/commit/d2d73649d3592b83d8abb73e5d77e86e8e1410e0) added cast of item to UIElement, it is not correct for MVVM scenarios and as result binded windows command items are always collapsed.

### Expected outcome
trivial
--
### Environment

- MahApps.Metro __v1.2.4__
- Windows __10__
- Visual Studio __2015__
- .NET Framework __4.5__

**Comment by punker76** [comment]
@igorushi Can you try the pre-release? Cause I've changed something at this point https://github.com/MahApps/MahApps.Metro/commit/79f895ebf9d77b9047f33544d87bfe92c1b6a28b
Thx!

**Comment by igorushi** [comment]
in 1.3.0-alpha101 it doesn't reproduce, thanks.
