### ISSUE TITLE
Window title bar buttons (close, maximize, etc.) occasionally appear in "classic style"

### ISSUE THREAD

**Issue by Deadpikle** [MahApps/MahApps.Metro#2445]
## Problem
Sometimes, the window's minimize/maximize/close buttons look like old Windows XP classic style buttons until they are moused over. See the following image:
![badmenubuttonicons](https://cloud.githubusercontent.com/assets/5092399/14019362/c94bddfe-f1a8-11e5-8bc3-46695bb120b5.png)
Once you mouse over the buttons, they return to normal.

### Expected outcome

The window title bar buttons should always appear like so (colors as appropriate for your theme):
![goodbuttons](https://cloud.githubusercontent.com/assets/5092399/14019376/e18d1022-f1a8-11e5-9f2a-a570ffae16ba.png)
## What steps will reproduce this issue?

Unfortunately, this bug is a bit random. It often occurs when I go into and out of full screen mode, which is when I also hide the menu and title bars.
Going into full screen:
```
UseNoneWindowStyle = true;
IgnoreTaskbarOnMaximize = true;
ShowTitleBar = false;
WindowState = WindowState.Maximized;
WindowStyle = WindowStyle.None;
ResizeMode = ResizeMode.NoResize;
//
MenuBar.Visibility = Visibility.Collapsed;
//
ShowTitleBar = false;
ShowMinButton = false;
ShowMaxRestoreButton = false;
ShowCloseButton = false;
```
Coming out of full screen:
```
UseNoneWindowStyle = false;
IgnoreTaskbarOnMaximize = false;
ShowTitleBar = true;
WindowState = WindowState.Normal;
WindowStyle = WindowStyle.SingleBorderWindow;
ResizeMode = ResizeMode.CanResize;
//
MenuBar.Visibility = Visibility.Visible;
//
ShowTitleBar = true;
ShowMinButton = true;
ShowMaxRestoreButton = true;
ShowCloseButton = true;
```
Often, when I go out of full screen mode, the window buttons look fine until I mouse into the window.

## Test Case
[MahAppsBugFullscreen.zip](https://github.com/MahApps/MahApps.Metro/files/188061/MahAppsBugFullscreen.zip) (see test case with latest dev code a few comments down)

--
### Environment

- MahApps.Metro 1.2.4
- Windows 8.1
- Visual Studio 2015
- .NET Framework 4.5.2

**Comment by punker76** [comment]
@Deadpikle Can you test it with the pre-release? thx!

**Comment by Deadpikle** [comment]
@punker76  Tested it with the latest code available on the develop branch. Still has the same issue (although it took more tries to reproduce).

Here's the test case with the latest code:
[Test Case w latest dev code](https://github.com/MahApps/MahApps.Metro/files/188067/MahAppsBugFullscreen.zip)

**Comment by punker76** [comment]
@Deadpikle I think the seuqence is important, I tried this and doesn't get the issue

```
private void buttonFull_Click(object sender, RoutedEventArgs e)
{
    WindowState = WindowState.Maximized;
    UseNoneWindowStyle = true;
    IgnoreTaskbarOnMaximize = true;
    ShowTitleBar = false;
    //
    MenuBar.Visibility = Visibility.Collapsed;
    //
    ShowTitleBar = false;
    ShowMinButton = false;
    ShowMaxRestoreButton = false;
    ShowCloseButton = false;
    ResizeMode = ResizeMode.NoResize;
}

private void buttonExitFull_Click(object sender, RoutedEventArgs e)
{
    ResizeMode = ResizeMode.CanResize;
    WindowState = WindowState.Normal;
    UseNoneWindowStyle = false;
    ShowTitleBar = true;
    IgnoreTaskbarOnMaximize = false;
    //
    MenuBar.Visibility = Visibility.Visible;
    //
    ShowTitleBar = true;
    ShowMinButton = true;
    ShowMaxRestoreButton = true;
    ShowCloseButton = true;
}
```

**Comment by Deadpikle** [comment]
@punker76 Yes, I can confirm that the rearranging of the ResizeMode call fixes the issue.

Thanks for your assistance! I suppose I'll close this because it didn't end up being an actual bug.
