### ISSUE TITLE
Style disables ListView UI virtualization

### ISSUE THREAD

**Issue by ahumeniy** [MahApps/MahApps.Metro#2446]
## What steps will reproduce this issue?

Create an empty WPF project, with a ListView and bind it to a collection of several thousands items. With no style ListView uses UI virtualization as default. After aplying the styles of MahApps.Metro UI virtualization is disabled for ListView and the app hangs generating all of the List Items. It also defeats data virtualization since it won't stop asking for items until all of them has been loaded.

### Expected outcome

UI virtualization should be left enabled as expected

--
### Environment

- MahApps.Metro 1.2.4 Still happens on 1.3.0
- Windows 10 build 14291
- Visual Studio 2015
- .NET Framework 4.5

**Comment by punker76** [comment]
@ahumeniy There is also a style forvirtualization

```xaml
<Style x:Key="VirtualisedMetroListView"
           BasedOn="{StaticResource MetroListView}"
           TargetType="{x:Type ListView}">
        <Setter Property="ScrollViewer.CanContentScroll" Value="True" />
        <Setter Property="ScrollViewer.IsDeferredScrollingEnabled" Value="True" />
        <Setter Property="VirtualizingStackPanel.IsVirtualizing" Value="True" />
        <Setter Property="VirtualizingStackPanel.VirtualizationMode" Value="Recycling" />
    </Style>
```

or you set the properties by youself on your ListView

**Comment by ahumeniy** [comment]
Thanks, that did it.

Is there a reason why isn't that the default style for ListView? 

Also, it is not on the documentation either.

**Comment by battleguard** [comment]
This should really be switched to the default style it makes using listviews in mahapps completely worthless without your code added to the style.

**Comment by eggapauli** [comment]
I came across the same issue and totally agree that virtualization should be _on_ by default. However you can quite easily turn it on for all list views using

    <Style BasedOn="{StaticResource VirtualisedMetroListView}" TargetType="ListView" />
