### ISSUE TITLE
how create a combobox just in last blank item in datagrid with MahApps ?

### ISSUE THREAD

**Issue by lamjar** [MahApps/MahApps.Metro#2447]
## What steps will reproduce this issue?

_Write problem description here_

### Expected outcome

_Write expected outcome here_

--
### Environment

- Metro UI v1.3
- Windows 7
- Visual Studio __2013_
- .NET Framework 4.5

**Comment by punker76** [comment]
@lamjar Can you please give us more specific informations? Do you mean combobox in a cell? thx

**Comment by lamjar** [comment]
i would create a combobox that a new rows in this datagrid ( blanck row) 
![image_thumb 5](https://cloud.githubusercontent.com/assets/5993938/14043229/34503ae4-f282-11e5-8dba-dad0b9e76781.png)

**Comment by lamjar** [comment]
i would combobox contains a list of Campany , i use the "DataTrigger" to control the element to show ( combobox or others) but does not created
