### ISSUE TITLE
"System.MissingMethodException" after update 1.2.4

### ISSUE THREAD

**Issue by Pekshev** [MahApps/MahApps.Metro#2448]
## What steps will reproduce this issue?

_After update from 1.1.2 to 1.2.4 has exception MissingMethodException:
"Void MahApps.Metro.Controls.MetroWindow.set_GlowBrush(System.Windows.Media.SolidColorBrush)"_

--
### Environment

- MahApps.Metro __v1.2.4__
- Windows __10__
- Visual Studio __2015__
- .NET Framework __4.0__

**Comment by punker76** [comment]
@Pekshev can you post the complete stacktrace?

**Comment by Pekshev** [comment]
When I was debugging it was not an error. The error is now - at work compile the application. I will try in the evening. Just thought a bug known

Translated by Google translate

**Comment by thoemmi** [comment]
The type of the `GlowBrush` property was changed from `SolidColorBrush` to `Brush` in 5cfb3776. It will work after you have recompiled the calling code.

**Comment by Pekshev** [comment]
Now it is clear. Unfortunately have to go back to the old version, because I have a plugin application and need to rebuild more than 40 projects
