### ISSUE TITLE
Visual bug while using RightWindowCommands

### ISSUE THREAD

**Issue by PavelLvou** [MahApps/MahApps.Metro#2449]
## What steps will reproduce this issue?

Hello,
I have a problem.
Gray rectangle appears if window lose focus
I try find this elements and find next
[
![fullversion](https://cloud.githubusercontent.com/assets/18031537/14042234/260cd332-f289-11e5-82f2-b0622bba2649.png)
](url)

Here xaml
```
<controls:MetroWindow  ResizeMode="NoResize"
        EnableDWMDropShadow="False"  WindowTransitionsEnabled="False"
        ShowMaxRestoreButton="False" ShowCloseButton="False" ShowMinButton="False" ShowIconOnTitleBar="False"
        WindowStyle="None" AllowsTransparency="True" WindowTitleBrush="Transparent" BorderBrush="Transparent" Background="Transparent"
        TitlebarHeight="100" Height="630" Width="450">
    <controls:MetroWindow.RightWindowCommands>
        <controls:WindowCommands Background="Transparent">
            <Border x:Name="RootBorder" BorderBrush="Red"
                    Width="450" Height="100"
                    BorderThickness="2, 2, 2, 0" CornerRadius="7,7,0,0"
                    Background="Green">
                <Label Content="Title"></Label>
            </Border>
        </controls:WindowCommands>
    </controls:MetroWindow.RightWindowCommands>
    <Border Width="450" BorderThickness="2, 0, 2, 2" CornerRadius="0, 0, 7, 7" BorderBrush="Red" Background="DarkGreen">
        <Label Content="Body"></Label>
    </Border>
</controls:MetroWindow>
```

### Expected outcome

All my elements have width 450
Why I have element whose width more than my elements and how I can fix it?
And why I have this gray rectangle after window lose focus?

Thank you

### Environment

- MahApps.Metro __v1.2.4.0__
- Windows __7__
- Visual Studio __2015__
- .NET Framework __4.6__

**Comment by punker76** [comment]
@PavelLvou So you customize the custom MahApps solution. Here some points which you should know (latest source)
- WindowStyle is already None
- MahApps doesn't support `AllowsTransparency="True"` cause it has some nasty side effects
- you must set `AllowsTransparency="True"` in the Initialized event
- set also `NonActiveWindowTitleBrush="Transparent"`
![2016-03-25_23h09_21](https://cloud.githubusercontent.com/assets/658431/14055043/af429cae-f2de-11e5-9624-9a9874e76dac.png)

**Comment by PavelLvou** [comment]
Thanks, but I still have problem
All my elements have width 450
Why I have element whose width more than my elements?
And still after lose focus window have gray border

[
![fullversionv2](https://cloud.githubusercontent.com/assets/18031537/14078040/f429ac18-f4fa-11e5-85c3-2fc719250ff5.png)
](url)

**Comment by sergey-tihon** [comment]
@punker76 Could you please help to fix https://github.com/MahApps/MahApps.Metro/issues/2449#issuecomment-202369247

**Comment by punker76** [comment]
@sergey-tihon @PavelLvou Here is my testcase with the latest source and using the TitleTemplate instead the RightWindowCommands
```xaml
<controls:MetroWindow x:Class="MetroDemo.ExampleWindows.AllowTransparencyDemo"
                      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                      xmlns:controls="clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro"
                      Width="450"
                      Height="630"
                      Background="Transparent"
                      BorderBrush="Transparent"
                      EnableDWMDropShadow="False"
                      Initialized="AllowTransparencyDemo_OnInitialized"
                      NonActiveBorderBrush="Transparent"
                      NonActiveWindowTitleBrush="Transparent"
                      ResizeMode="NoResize"
                      ShowCloseButton="False"
                      ShowIconOnTitleBar="False"
                      ShowMaxRestoreButton="False"
                      ShowMinButton="False"
                      TitlebarHeight="100"
                      WindowTitleBrush="Transparent"
                      WindowTransitionsEnabled="False">

    <controls:MetroWindow.TitleTemplate>
        <DataTemplate>
            <Border x:Name="RootBorder"
                    Background="Green"
                    BorderBrush="Red"
                    BorderThickness="2 2 2 0"
                    CornerRadius="7,7,0,0">
                <Label Content="Title" />
            </Border>
        </DataTemplate>
    </controls:MetroWindow.TitleTemplate>

    <Border Background="DarkGreen"
            BorderBrush="Red"
            BorderThickness="2 0 2 2"
            CornerRadius="0, 0, 7, 7">
        <Label Content="Body" />
    </Border>

</controls:MetroWindow>
```
```csharp
public partial class AllowTransparencyDemo : MetroWindow
{
    public AllowTransparencyDemo()
    {
        InitializeComponent();
    }

    private void AllowTransparencyDemo_OnInitialized(object sender, EventArgs e)
    {
        this.AllowsTransparency = true;
    }
}
```
![2016-04-12_22h04_16](https://cloud.githubusercontent.com/assets/658431/14474798/1a57515a-00ff-11e6-972a-cc9e59461e4d.png)

**Comment by JinOptimist** [comment]
@punker76 
But here https://github.com/MahApps/MahApps.Metro/issues/2288#issuecomment-200367456
you say use another.
I have a problem, my button in title aren't clickable, because there lays an invisible grid

**Comment by PavelLvou** [comment]
Hi, can you answer, is it possible avoid both of problems, please?
If I use TitleTemplate, than I can't use button into Title. Here [example](https://github.com/MahApps/MahApps.Metro/issues/2288#issuecomment-200367456)
If I use RightWindowCommands, than I have problem with layout.

**Comment by punker76** [comment]
@PavelLvou @JinOptimist The problem is the introduced thumb for drag&move, it will be fixed with https://github.com/MahApps/MahApps.Metro/issues/2477
