### ISSUE TITLE
Multiline ComboBox DropdownButton Width

### ISSUE THREAD

**Issue by chrisklepeis** [MahApps/MahApps.Metro#2450]
Using the latest release version of Mahapps (1.2.4) on .Net 4.6.1 I have a ComboBox whose DisplayMemberPath is a string with line breaks in it. The drop down button gets too wide as the height of the ComboBox gets taller. Looking at the template, it looks like it should be honoring Controls:ControlsHelper.ButtonWidth but this is not the case. Seen below is a SplitButton followed by a ComboBox with the wide drop down button.

![capture](https://cloud.githubusercontent.com/assets/16291940/14079650/51dd4410-f4cd-11e5-9106-729ec5d8e619.PNG)

For me, ideally the drop down button width would remain what it is when the combobox is at its minheight (26 I believe). Either that or have a way to set it without modifying the control template.

**Comment by punker76** [comment]
@chrisklepeis This is fixed in the pre-release

**Comment by chrisklepeis** [comment]
@punker76 Ok, thanks, I'll update my project to use that instead.

**Comment by punker76** [comment]
@chrisklepeis v1.3.0 is coming very soon
