### ISSUE TITLE
Text not updated to new value when a NumericUpDown's value is changed in Maximum/MinimumReached

### ISSUE THREAD

**Issue by ericBG** [MahApps/MahApps.Metro#2451]
## What steps will reproduce this issue?

Make a NumericUpDown which has an event on Maximum/MinimumReached, which changes its value.
### Expected outcome

The value that was set last (during the Maximum/MinimumReached) is displayed in the textbox. Instead, the other value that is reached is then used in the textbox, but as soon as the value is changed again the textbox fixes itself.

This is because these events are triggered before the text is set in the textbox (they are raised in [line 774](https://github.com/MahApps/MahApps.Metro/blob/master/MahApps.Metro/Controls/NumericUpDown.cs#L774) and [line 788](https://github.com/MahApps/MahApps.Metro/blob/master/MahApps.Metro/Controls/NumericUpDown.cs#L788) but the text is set at [line 794](https://github.com/MahApps/MahApps.Metro/blob/master/MahApps.Metro/Controls/NumericUpDown.cs#L774). I would do a PR for this but I'm not sure if there's a reason why it's being done this way.
## 
### Environment
- MahApps.Metro **v1.1.2.0**
- Windows **10 Pro**
- Visual Studio **2015**
- .NET Framework **4.5.2**

**Comment by punker76** [comment]
@ericBG I know, it's a long time ago, but IMHO I would say, changing the value in these events makes no sense, cause the value is already coerced by using the Up/Down keys, the Inc./Dec.-Buttons, the mousewheel or tabbing out the control. So why changing again? I will close this for now. Feel free to reopen this issue if there is any critical reason to do this (changing the value). Thx.
