### ISSUE TITLE
Window close button symbol missing on mouseover since 1.2.4

### ISSUE THREAD

**Issue by beachwalker** [MahApps/MahApps.Metro#2453]
## What steps will reproduce this issue?

Start Window with Clean Design. Try to use the mouse to hover the close button on top right. x hides.
Functionality on click is still there but graphic while hovering is gone.

### Expected outcome

Should mark the close button red when hovered by mouse.

--
### Environment

- MahApps.Metro __v1.2.4__
- Windows __7__
- Visual Studio __2013__
- .NET Framework __4.5__

**Comment by punker76** [comment]
@beachwalker Can you show the xaml source for the clean window usage? is this also present in the pre-release?

**Comment by beachwalker** [comment]
This is the XAML for the Clean Window:

```xml
<controls:MetroWindow x:Class="MyApp.Components.Presentation.Shells.Default.ShellView"
                      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                      xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
                      xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
                      xmlns:controls="http://metro.mahapps.com/winfx/xaml/controls"
                      xmlns:cal="http://www.caliburnproject.org"
                      xmlns:myapp="clr-namespace:MyApp.Client.UI.Controls;assembly=MyApp.Client.UI.Controls"
                      xmlns:lex="http://wpflocalizeextension.codeplex.com"
                      xmlns:behaviours="http://metro.mahapps.com/winfx/xaml/shared"
                      xmlns:i="http://schemas.microsoft.com/expression/2010/interactivity"
                      xmlns:behaviours1="clr-namespace:MyApp.Components.Presentation.Shells.Default.Behaviours"
                      Icon="Resources/Company.ico"
                      ShowIconOnTitleBar="False"
                      Title="{Binding Title}"
                      GlowBrush="{StaticResource WindowTitleColorBrush}"
                      ResizeMode="CanResizeWithGrip"
                      WindowTransitionsEnabled="True"
                      TitleCaps="False"
                      mc:Ignorable="d"
                      d:DesignHeight="500"
                      x:Name="mainWindow"
                      d:DesignWidth="900"
                      ShowSystemMenuOnRightClick="False"
                      IgnoreTaskbarOnMaximize="True"
                      RightWindowCommandsOverlayBehavior="Never"
                      behaviours1:FullscreenBehavior.IsFullscreen="{Binding Fullscreen}"
                      lex:ResxLocalizationProvider.DefaultAssembly="MyApp.Client.UI.Modules.Default"
                      lex:ResxLocalizationProvider.DefaultDictionary="Resources"
                      Style="{DynamicResource CleanWindowStyleKey}" BorderThickness="0">
    <i:Interaction.Behaviors>
        <behaviours:BorderlessWindowBehavior />
        <behaviours:WindowsSettingBehaviour />
        <behaviours:GlowWindowBehavior />
    </i:Interaction.Behaviors>

    <controls:MetroWindow.LeftWindowCommands>
        <controls:WindowCommands>
        </controls:WindowCommands>
    </controls:MetroWindow.LeftWindowCommands>
    <controls:MetroWindow.RightWindowCommands>
        <controls:WindowCommands>
            <controls:MetroContentControl cal:View.Model="{Binding Session}" />
        </controls:WindowCommands>
    </controls:MetroWindow.RightWindowCommands>

    <myapp:ActiveContentControl IsActive="{Binding IsWaiting}"
                                 CanCancel="{Binding CanCancel}"
                                 InfoText="{lex:Loc ProgressRing_LoadingExercise}"
                                 cal:View.Model="{Binding ActiveItem}" />
</controls:MetroWindow>
```

**Comment by punker76** [comment]
@beachwalker 

- you don't need set the `Behaviors`, it's already done by the style
- if you have a Flyout then RightWindowCommandsOverlayBehavior="Never" means that you never see the commands if the Flyout is open
- is this issue also present with the latest pre-release?

Jan

**Comment by punker76** [comment]
@beachwalker ?

**Comment by beachwalker** [comment]
Still alive... as well as the bug in the latest published pre-releases. ;-)

**Comment by punker76** [comment]
@beachwalker ok, do you maybe mean the "clean window" sytel hover effect, which is shown in the main demo? so maybe you forgot to add the "clean" styles

```xaml
<Window.Resources>
    <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Clean/Clean.xaml" />
</Window.Resources>
```
![2016-04-13_12h51_47](https://cloud.githubusercontent.com/assets/658431/14491005/841c0b54-0176-11e6-937f-6544f434e4c5.png)

**Comment by beachwalker** [comment]
When hovering with the mouse... ![image](https://cloud.githubusercontent.com/assets/2715897/14499312/0d82521e-019e-11e6-8eda-4093b3c6f7b1.png)

**Comment by punker76** [comment]
@beachwalker Can you show us your App.xaml? Do you have some special styles?

**Comment by beachwalker** [comment]
<Application x:Class="MyApp.Applications.Client.App"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:controls="clr-namespace:MyApp.Client.UI.Controls;assembly=MyApp.Client.UI.Controls"
             xmlns:system="clr-namespace:System;assembly=mscorlib"
             xmlns:exercises="clr-namespace:MyApp.Client.UI.Modules.Default.Start;assembly=MyApp.Client.UI.Modules.Default"
             xmlns:client="clr-namespace:MyApp.Applications.Client"
             Startup="OnStartup"
             Exit="OnExit"
             DispatcherUnhandledException="OnDispatcherUnhandledException">

    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary>
                    <client:Bootstrapper x:Key="Bootstrapper" />
                </ResourceDictionary>                
                
                <ResourceDictionary Source="pack://application:,,,/MyApp.Applications.Client;component/Resources/ThemeBrushes.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
                
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Clean/Clean.xaml"/>
                <ResourceDictionary Source="/Resources/Converter.xaml" />
                <ResourceDictionary Source="/Resources/Icons.xaml" />
                <ResourceDictionary Source="/Resources/OwnIcons.xaml" />
                <ResourceDictionary Source="/Resources/Styles.xaml" />
                <ResourceDictionary Source="/Resources/TabControlStyle.xaml" />
            </ResourceDictionary.MergedDictionaries>



            <BitmapImage x:Key="placeHolder"
                         UriSource="/Resources/placeholder.png" />


            <BitmapImage x:Key="MyAppLogo"
                         UriSource="/Resources/MyAppLogo.PNG" />

            <BitmapImage x:Key="rdeLogo"
                         UriSource="/Resources/Rheinmetall_defence_logo_small.png" />


            


            <Style x:Key="Graphics/RdeBlueLeft"
                   TargetType="Path">
                <Setter Property="Fill"
                        Value="{StaticResource Brush/RdeBlue}" />
                <Setter Property="Data"
                        Value="M0,0 L40,0 20,40 0,40 z" />
                <Setter Property="HorizontalAlignment"
                        Value="Left" />
                <Setter Property="VerticalAlignment"
                        Value="Center" />
                <Setter Property="Width"
                        Value="40" />
                <Setter Property="Height"
                        Value="40" />
            </Style>


            <Style x:Key="Graphics/RdeBlueRight"
                   TargetType="Path">
                <Setter Property="Fill"
                        Value="{StaticResource Brush/RdeBlue}" />
                <Setter Property="Data"
                        Value="M20,0 L60,0 40,40 0,40 z" />
                <Setter Property="HorizontalAlignment"
                        Value="Left" />
                <Setter Property="VerticalAlignment"
                        Value="Center" />
                <Setter Property="Width"
                        Value="40" />
                <Setter Property="Height"
                        Value="40" />
            </Style>


            <Style x:Key="Graphics/RdeGrayRight"
                   TargetType="Path">
                <Setter Property="Fill"
                        Value="{StaticResource Brush/RdeLightGray}" />
                <Setter Property="Data"
                        Value="M20,0 40,0 40,40 0,40 z" />
                <Setter Property="HorizontalAlignment"
                        Value="Right" />
                <Setter Property="VerticalAlignment"
                        Value="Center" />
                <Setter Property="Width"
                        Value="40" />
                <Setter Property="Height"
                        Value="40" />
            </Style>

            <Style x:Key="Graphics/RdeGrayRightNarrow"
                   TargetType="Path">
                <Setter Property="Fill"
                        Value="{StaticResource Brush/RdeDarkGray}" />
                <Setter Property="Data"
                        Value="M20,0 L30,0 10,40 0,40 z" />
                <Setter Property="HorizontalAlignment"
                        Value="Right" />
                <Setter Property="VerticalAlignment"
                        Value="Center" />
                <Setter Property="Width"
                        Value="30" />
                <Setter Property="Height"
                        Value="40" />
            </Style>



            



            

            <Style TargetType="Button"
                   x:Key="StandardButton">
                <Setter Property="MinWidth"
                        Value="80" />
                <Setter Property="Margin"
                        Value="2" />
                <Setter Property="Height"
                        Value="24" />
                <Setter Property="TextElement.Foreground"
                        Value="White" />
                <Setter Property="Background"
                        Value="{StaticResource Brush/RdeBlue}" />
                <Setter Property="Template">
                    <Setter.Value>
                        <ControlTemplate TargetType="ButtonBase">
                            <Border Background="{TemplateBinding Background}"
                                    BorderBrush="{TemplateBinding BorderBrush}"
                                    BorderThickness="{TemplateBinding BorderThickness}">
                                <Grid>
                                    <TextBlock Text="{TemplateBinding Content}"
                                               HorizontalAlignment="{TemplateBinding HorizontalContentAlignment}"
                                               VerticalAlignment="{TemplateBinding VerticalContentAlignment}"
                                               Style="{StaticResource MetaNormalRoman}" />
                                </Grid>
                            </Border>
                            <ControlTemplate.Triggers>

                                





                                <Trigger Property="IsEnabled"
                                         Value="false">

                                    <Setter Property="Opacity"
                                            Value="0.5" />
                                </Trigger>

                            </ControlTemplate.Triggers>
                        </ControlTemplate>
                    </Setter.Value>
                </Setter>
            </Style>


            

            <Style TargetType="{x:Type controls:MetroCircleTextButton}"
                   x:Key="NavigationButtonBase">

                <Setter Property="Background"
                        Value="Transparent" />
                <Setter Property="BorderThickness"
                        Value="1" />
                <Setter Property="FlowDirection"
                        Value="LeftToRight" />

                <Setter Property="Margin"
                        Value="2,0,2,0" />
                <Setter Property="IconBrush"
                        Value="{DynamicResource Brush/MetroButton/IconBrush}" />

                <Setter Property="BorderBrush"
                        Value="{DynamicResource Brush/MetroButton/BorderBrush}" />

                <Setter Property="Foreground"
                        Value="{DynamicResource Brush/MetroButton/Foreground}" />

                <Setter Property="ContentForegroundBrush"
                        Value="White" />

                <Setter Property="HorizontalContentAlignment"
                        Value="Center" />
                <Setter Property="VerticalContentAlignment"
                        Value="Center" />

                <Setter Property="HorizontalAlignment"
                        Value="Center" />
                <Setter Property="VerticalAlignment"
                        Value="Center" />
                <Setter Property="Padding"
                        Value="4" />
                <Setter Property="MaxWidth"
                        Value="64" />
                <Setter Property="ToolTip"
                        Value="{Binding RelativeSource={RelativeSource Self}, Path=Text}" />
                <Setter Property="Template">
                    <Setter.Value>

                        <ControlTemplate TargetType="{x:Type controls:MetroCircleTextButton}">

                            <Grid ShowGridLines="False">
                                <Grid.RowDefinitions>
                                    <RowDefinition Height="Auto" />
                                    <RowDefinition Height="Auto" />
                                </Grid.RowDefinitions>


                                
                                <Grid HorizontalAlignment="Center"
                                      Width="{TemplateBinding Diameter}"
                                      Height="{TemplateBinding Diameter}"
                                      VerticalAlignment="Center">
                                    <Ellipse Fill="{TemplateBinding Background}"
                                             StrokeThickness="0" />

                                    <Ellipse x:Name="ellipsebg"
                                             Fill="{DynamicResource Brush/MetroButton/BackgroundBrush}"
                                             Opacity="0"
                                             StrokeThickness="0" />

                                    <Ellipse x:Name="ellipse"
                                             Opacity="0"
                                             Stroke="{TemplateBinding BorderBrush}"
                                             StrokeThickness="{Binding RelativeSource={x:Static RelativeSource.TemplatedParent}, Path=BorderThickness.Left}" />



                                    <Viewbox HorizontalAlignment="Center"
                                             Margin="{TemplateBinding Padding}"
                                             VerticalAlignment="Center">
                                        <Path Data="{TemplateBinding Icon}"
                                              RenderTransformOrigin="0.5,0.5"
                                              Stretch="Fill"
                                              Fill="{TemplateBinding IconBrush}">

                                            <Path.RenderTransform>
                                                <TransformGroup>
                                                    <TransformGroup.Children>
                                                        <RotateTransform Angle="{Binding RelativeSource={RelativeSource TemplatedParent}, Path = IconRotationAngle}" />
                                                        <ScaleTransform ScaleX="1"
                                                                        ScaleY="1" />
                                                    </TransformGroup.Children>
                                                </TransformGroup>
                                            </Path.RenderTransform>
                                        </Path>
                                    </Viewbox>


                                    <ContentPresenter HorizontalAlignment="Stretch"
                                                      TextBlock.Foreground="{TemplateBinding ContentForegroundBrush}"
                                                      VerticalAlignment="Stretch" />
                                </Grid>

                                

                                <TextBlock Text="{TemplateBinding Text}"
                                           x:Name="buttonText"
                                           Visibility="Collapsed"
                                           Grid.Row="1"
                                           Foreground="{TemplateBinding Foreground}"
                                           HorizontalAlignment="Center"
                                           VerticalAlignment="Center"
                                           TextTrimming="CharacterEllipsis" />



                            </Grid>
                            <ControlTemplate.Triggers>

                                <Trigger Property="IsMouseOver"
                                         Value="True">

                                    <Trigger.EnterActions>
                                        <BeginStoryboard>
                                            <Storyboard>
                                                <DoubleAnimation Storyboard.TargetName="ellipse"
                                                                 Storyboard.TargetProperty="Opacity"
                                                                 From="0"
                                                                 To="1"
                                                                 Duration="0:0:0.2" />

                                            </Storyboard>
                                        </BeginStoryboard>
                                    </Trigger.EnterActions>


                                    <Trigger.ExitActions>
                                        <BeginStoryboard>
                                            <Storyboard>
                                                <DoubleAnimation Storyboard.TargetName="ellipse"
                                                                 Storyboard.TargetProperty="Opacity"
                                                                 To="0"
                                                                 Duration="0:0:0.3" />

                                            </Storyboard>
                                        </BeginStoryboard>
                                    </Trigger.ExitActions>
                                </Trigger>

                            </ControlTemplate.Triggers>
                        </ControlTemplate>

                    </Setter.Value>

                </Setter>

            </Style>

            <Style TargetType="{x:Type controls:MetroCircleTextButton}"
                   x:Key="BackButton"
                   BasedOn="{StaticResource NavigationButtonBase}">
                <Setter Property="Diameter"
                        Value="20" />
                <Setter Property="BorderThickness"
                        Value="2" />
                <Setter Property="Padding"
                        Value="4" />
                <Setter Property="BorderBrush"
                        Value="White" />
                <Setter Property="IconBrush"
                        Value="White" />
                <Setter Property="Icon"
                        Value="{StaticResource Geometry/NavigateLeft}" />
            </Style>

            <Style TargetType="{x:Type controls:MetroCircleTextButton}"
                   x:Key="OverlayButton"
                   BasedOn="{StaticResource NavigationButtonBase}">
                <Setter Property="Diameter"
                        Value="35" />
                <Setter Property="BorderThickness"
                        Value="2" />
                <Setter Property="BorderBrush"
                        Value="{StaticResource Brush/RdeBlue}" />
                <Setter Property="IconBrush"
                        Value="{StaticResource Brush/RdeBlue}" />
                <Setter Property="Icon"
                        Value="{StaticResource Geometry/RightArrow}" />
            </Style>

            <Style TargetType="{x:Type controls:MetroCircleTextButton}"
                   BasedOn="{StaticResource OverlayButton}"
                   x:Key="OverlayPlayButton">
                <Setter Property="Icon"
                        Value="{StaticResource Geometry/RightArrow}" />
                <Setter Property="Padding"
                        Value="14" />
            </Style>

            <Style TargetType="{x:Type controls:MetroCircleTextButton}"
                   BasedOn="{StaticResource OverlayButton}"
                   x:Key="OverlayInfoButton">
                <Setter Property="Icon"
                        Value="{StaticResource Geometry/Info}" />
            </Style>




            
            <system:Double x:Key="SubHeaderHeight">40.0</system:Double>

            <Style TargetType="TextBlock"
                   BasedOn="{StaticResource MetaNormalCaps}"
                   x:Key="SubHeaderStyle">
                <Setter Property="VerticalAlignment"
                        Value="Center" />
                <Setter Property="Foreground"
                        Value="{StaticResource Brush/RdeDarkGray}" />
                <Setter Property="FontSize"
                        Value="18" />
                <Setter Property="Margin"
                        Value="0,0,0,0" />
            </Style>

            <Style TargetType="Rectangle"
                   x:Key="SubHeaderLineStyle">
                <Setter Property="VerticalAlignment"
                        Value="Top" />
                <Setter Property="Height"
                        Value="4" />

                <Setter Property="Fill"
                        Value="{StaticResource Brush/RdeBlue}" />
            </Style>



            





            <DataTemplate x:Key="ExerciseTemplate/List"
                          DataType="exercises:ExerciseViewModel">
                <Grid Margin="0,0,0,0"
                      x:Name="root">
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="Auto" />
                        <ColumnDefinition Width="*" />
                    </Grid.ColumnDefinitions>

                    <Image Margin="2,2,2,2" Width="100"
                           Height="80"
                           Stretch="UniformToFill"
                           Source="{Binding Exercise.Image}" />
                    <StackPanel Grid.Column="1"
                                Margin="10">
                        <TextBlock Text="{Binding Exercise.Title}"
                                   Style="{StaticResource MetaBoldRoman}" />
                        <TextBlock Text="{Binding Exercise.Description}"
                                   TextWrapping="Wrap"
                                   Style="{StaticResource MetaNormalRoman}"
                                   TextTrimming="CharacterEllipsis"
                                   Height="40" />
                    </StackPanel>

                </Grid>
            </DataTemplate>

            <DataTemplate x:Key="ExerciseTemplate/Large"
                          DataType="exercises:ExerciseViewModel">
                <Grid Background="White">
                    <Grid.RowDefinitions>
                        <RowDefinition Height="3*" />
                        <RowDefinition Height="1*" />
                    </Grid.RowDefinitions>

                    <Image Stretch="UniformToFill"
                           Source="{Binding Exercise.Image}" VerticalAlignment="Center" HorizontalAlignment="Center" />



                    <Rectangle Fill="{StaticResource Brush/RdeBlue}"
                               Grid.Row="1" />
                    <StackPanel Grid.Row="1"
                                Margin="10"
                                TextElement.Foreground="White">
                        <TextBlock Text="{Binding Exercise.Title}"
                                   Style="{StaticResource MetaBoldRoman}" />
                        <TextBlock Text="{Binding Exercise.Description}"
                                   TextWrapping="Wrap"
                                   TextTrimming="CharacterEllipsis"
                                   Style="{StaticResource MetaNormalRoman}"
                                   Height="60" />
                    </StackPanel>

                </Grid>
            </DataTemplate>

            <DataTemplate x:Key="ExerciseTemplate/Medium"
                          DataType="exercises:ExerciseViewModel">
                <Grid Background="White">
                    <Grid.RowDefinitions>
                        <RowDefinition Height="3*" />
                        <RowDefinition Height="1*" />
                    </Grid.RowDefinitions>

                    <Image Stretch="UniformToFill"
                           Source="{Binding Exercise.Image}" />

                    <Rectangle Fill="{StaticResource Brush/RdeBlue}"
                               Grid.Row="1" />

                    <StackPanel Grid.Row="1"
                                Margin="10">
                        <TextBlock Text="{Binding Exercise.Title}"
                                   Style="{StaticResource MetaBoldRoman}"
                                   Foreground="White" />
                        
                    </StackPanel>

                </Grid>
            </DataTemplate>



            <Style TargetType="{x:Type Button}"
                   x:Key="TransparentButton">
                <Setter Property="Template">
                    <Setter.Value>
                        <ControlTemplate TargetType="{x:Type Button}">
                            <Border Background="Transparent">
                                <ContentPresenter />
                            </Border>
                        </ControlTemplate>
                    </Setter.Value>
                </Setter>
            </Style>





            




            <SolidColorBrush x:Key="SelectedBackgroundBrush"
                             Color="LightGray" />

            <SolidColorBrush x:Key="DisabledForegroundBrush"
                             Color="#888" />




            <SolidColorBrush x:Key="Brush/MetroButton/IconBrush"
                             Color="{StaticResource Color/RdeBlue}" />

            <SolidColorBrush x:Key="Brush/MetroButton/BorderBrush"
                             Color="{StaticResource Color/RdeBlue}" />

            <SolidColorBrush x:Key="Brush/MetroButton/BackgroundBrush"
                             Color="{StaticResource Color/RdeLightGray}" />

            <SolidColorBrush x:Key="Brush/MetroButton/Foreground"
                             Color="Black" />






            <SolidColorBrush x:Key="AccentColorBrush"
                             Color="DimGray" />


            <SolidColorBrush x:Key="Brush/IconBrushIsChecked"
                             Color="White" />

            <SolidColorBrush x:Key="Brush/CacheBrush"
                             Color="#DEFFFFFF" />

            <SolidColorBrush x:Key="Brush/BorderBrush"
                             Color="Gray" />




            <SolidColorBrush x:Key="Brush/ParameterView/HeaderBackground"
                             Color="#F4F4F4" />

            <SolidColorBrush x:Key="Brush/ParameterView/HeaderBorder"
                             Color="LightGray" />

            <SolidColorBrush x:Key="AccentSelectedForegroundBrush"
                             Color="White" />

            <SolidColorBrush x:Key="AccentSelectedColorBrush"
                             Color="White" />

        </ResourceDictionary>
    </Application.Resources>
</Application>

**Comment by beachwalker** [comment]
Ahhh, seems to be fixed by adding BaseLight and Colors again. Sorry, my fault.
