### ISSUE TITLE
MetroDialogSettings not being propagated to ProgressDialog by DialogManager

### ISSUE THREAD

**Issue by lagwagon667** [MahApps/MahApps.Metro#2459]
## What steps will reproduce this issue?

Call `DialogManagers` `ShowProgressAsync()` method to show a progress dialog and pass settings with `AnimateHide` and `AnimateShow` set to `false`.

### Expected outcome

The progress dialog shows up immediately without animation

### Actual outcome

The progress dialog shows up using an animation

### Reason

The aforementioned `ShowProgressAsync()` method instantiates the `ProgressDialog` class without passing the `MetroDialogSettings` object, thus the dialog gets initialized using default settings. This is different to all other `Show*Async()` methods of `DialogManager`.

--
### Environment

- MahApps.Metro v1.2.4, also not fixed on master and develop branches
- Windows 7
- Visual Studio 2015
- .NET Framework 4.6

**Comment by punker76** [comment]
@lagwagon667 fixed now
