### ISSUE TITLE
MetroContentControl Issue in MahApps.Metro

### ISSUE THREAD

**Issue by kishorekumarhemraj** [MahApps/MahApps.Metro#246]
I am getting this exception in designer view of my Windows & UserControls

`System.Windows.Media.Animation.DoubleAnimationUsingKeyFrames' animation object cannot be used to animate property 'RenderTransform' because it is of incompatible type 'System.Windows.Media.Transform`

**Comment by TheMask88** [comment]
I am experience the same issue in designer in  year  of 2015.
