### ISSUE TITLE
TextboxHelper property error

### ISSUE THREAD

**Issue by xavierblue** [MahApps/MahApps.Metro#2461]
Trying to create a textbox that shows the search button and the clear text button when there is text in the textbox.

![image](https://cloud.githubusercontent.com/assets/18314318/14329171/2912015a-fc08-11e5-8114-ab30ea1493d2.png)

Here is a pic of the error I'm receiving. Am I missing something here? I have Controls defined where it should be and haven't had an issue using it in other ways throughout the project.

Anyone able to help?

- MahApps.Metro v1.2.4.0
- Windows 7
- Visual Studio 2015
- .NET Framework 4.5

**Comment by punker76** [comment]
@xavierblue Looks good for me. You can try clear bin/obj folders, reopen VS and rebuild complete solution. Make sure you are using the correct dlls (sometimes there are different dlls in bin folder than as reference)

**Comment by xavierblue** [comment]
I tried all of that already and just went back and tried everything you listed again and still no luck. I've been at this for a few hours and can't figure out what the issue would be.

**Comment by xavierblue** [comment]
I opened up several other projects I'm using MahApps in and am having the same issue.

**Comment by xavierblue** [comment]
I figured it out...this was my fault. I put TextboxHelper instead of TextBoxHelper. It's been a long day of coding...

Thanks for your help.
