### ISSUE TITLE
When building my file i cant share it with other people

### ISSUE THREAD

**Issue by HupHupscripts** [MahApps/MahApps.Metro#2464]
## What steps will reproduce this issue?
create a wpf application and send it to a friend
_Write problem description here_
the program wont even open
### Expected outcome
the program wont even open
_Write expected outcome here_
the program wont even open

--
### Environment
C# wpf
- MahApps.Metro __latest__
- Windows __10__
- Visual Studio __2013__
- .NET Framework __4.5__

**Comment by punker76** [comment]
@HupHupscripts So do you send all necessary dlls to your friend? Any other infos? Stacktrace?
