### ISSUE TITLE
Controls:PackIconMaterial Binding issue

### ISSUE THREAD

**Issue by chris579** [MahApps/MahApps.Metro#2469]
## What steps will reproduce this issue?

Binding to the Kind Property of Controls:PackIconMaterial doesn't works. The result looks like this:
![image](https://cloud.githubusercontent.com/assets/6552521/14474728/cee88fcc-00fe-11e6-8383-c684f6bb2adc.png)

The code looks like this:
```
<Button Name="button" HorizontalAlignment="Left" Height="38" Margin="425,10,0,0" VerticalAlignment="Top" Width="125" BorderBrush="Black" Background="{Binding Path=ConnectButtonColor}" HorizontalContentAlignment="Left">
    <Grid Width="115">
        <Label Content="{Binding Path=ConnectButtonText}" Width="100" Height="35" FontSize="15"  Margin="-11,-3,0,0" Foreground="WhiteSmoke"/>
        <!-- <Controls:ProgressRing IsActive="{Binding Path=Refreshing}" Background="Transparent" Foreground="WhiteSmoke" Height="10" Width="10" Margin="90,0,0,0"/> -->
        <Controls:PackIconMaterial Height="14" Width="14" Kind="{Binding Path=Icon}" Foreground="WhiteSmoke" Margin="95,0,0,0" VerticalAlignment="Center" />
    </Grid>                
</Button>
```

When changing the property the icon is not changing/updating. This appears in window preview and in the running program aswell.
 The ViewModel looks fine:
```
public string Icon
{
    get
    {
        return icon;
    }

    set
    {
        if(icon != value)
        {
            icon = value;
            RaisePropertyChanged("Icon");
        }
    }
}
```

### Expected outcome

The icon should be empty at all if the property is String.Empty. Updating the property should result in an icon change.

--
### Environment

- MahApps.Metro __v1.3.0-ALPHA121__
- Windows __10 x64 v1511 b10586.164__
- Visual Studio __2015__
- .NET Framework __4.5__

**Comment by thoemmi** [comment]
The type of the `Icon` property in your view model is wrong. The type of `PackIconMaterial.Kind` is not `string` but `PackIconMaterialKind`.

**Comment by chris579** [comment]
Thanks for the hint. Now it works.
