### ISSUE TITLE
Olive theme looks gray on some notebooks

### ISSUE THREAD

**Issue by xmedeko** [MahApps/MahApps.Metro#2470]
## What steps will reproduce this issue?
Use a notebook screen. Start the sample app, switch to the Olive accent. 

The theme color looks gray on 4 notebooks I have seen so far. On an external LCS screens it looks fine. It is hard to distinguish enabled/disabled switch, etc..

### Expected outcome
I would expect the Olive accent to have more contrast on the notebooks screens, too.

--
### Environment

- Notebook screen, I guess a cheap to mid price notebook. Maybe some notebooks may have better screens. 32-bit colors.
- MahApps.Metro __v1.2.4.0__
- Windows __W10__
- Visual Studio __2015__
- .NET Framework __4.6__

**Comment by punker76** [comment]
@xmedeko I don't  think this is MahApps related. You can create your own Olive accent with better contrast value.

**Comment by xmedeko** [comment]
It depends on the point of view. E.g. if MahApps would have some localizations and I would report a mistype in German localization. Would you just say create own German localization? I think it's better either to care about colors shipped with MahApps or to remove some accents if they do not look well on common hardware. I know the problems with color are more subjective problems than mistypes. So I will not feel any resentment if you close the issue without any action.

Unfortunately, I have no design skills, otherwise I would change the Olive accent and send the PR. So I just switch to another accent. Thanks that MahApps have more than 20 of them :smile:

**Comment by punker76** [comment]
@xmedeko Don't know if this a good comparison of mistypes in localization and colors. i think colors are subjective, please do not misunderstand me, but if you change this, then another person creates another issue, where he says that the color of this accent is wrong... and yes, I'm also not  enough design skills to say what color is really good and what color is really bad...

**Comment by xmedeko** [comment]
Maybe someone with design skill may have shed a light about this? What about @xxMUROxx as the original author of the accent colors from Git history?

Anyway, as I have already said, I understand this is partly subjective problem. I have reported this issue to help the other users of MahApps. Personally, I am OK with switching to another accent. Feel free to close the issue if you like.

**Comment by xxMUROxx** [comment]
@xmedeko The colors were not choosen by me. The HEX-code for the colors are the predefined accents for the [Windows Phone Platform].(https://msdn.microsoft.com/library/windows/apps/ff402557(v=vs.105).aspx#BKMK_Supportedthemes)

**Comment by xmedeko** [comment]
Interesting, that's a reason not to touch it.
I hope Windows Phones have better screens than my notebook :smiley:
