### ISSUE TITLE
Flyout from element instead of window

### ISSUE THREAD

**Issue by Krustocious** [MahApps/MahApps.Metro#2471]
Hi there,
Not really an issue, more of a question. Is it possible to have Mahapp flyouts come out of elements, such as an edge of a grid? I'm aiming to have a flyout emerge from the top of a grid when prompted, and then slide back down to the top of the grid. I'd like to have the grid visible throughout the whole process, hence why I'd like to fly out from the grid rather than the actual window. 

I've only just started using Mahapps, but so far it's working quite well and looks really nice!

Cheers

Edit: Sorry if this is not the appropriate place for a question, just wanted to put it out there in case others are having a similar problem.

### Environment

- MahApps.Metro __v1.2.4__
- Windows __7__
- Visual Studio __2015__
- .NET Framework __4.5__

**Comment by punker76** [comment]
@Krustocious It's possible, but the Flyout uses the Window Height/Width positioning for it's animation. Maybe it's better to create your own Storyboard animation for a custom control for such tiny stuff.
