### ISSUE TITLE
Cannot use DialogCoordinator from background threads.

### ISSUE THREAD

**Issue by xxMUROxx** [MahApps/MahApps.Metro#2473]
## What steps will reproduce this issue?

Call of any method in DialogCoordinator from a background thread does not work

### Expected outcome

Ability to show messages from background threads.

I will provide a PR when needed. In the meantime checkout branch: https://github.com/xxMUROxx/MahApps.Metro/tree/feature/Background-DialogCoordinator

**Comment by punker76** [comment]
fixed with 50e084e4b654d832f39b4e59a0d082857bbab0a1
