### ISSUE TITLE
right to left DatePicker

### ISSUE THREAD

**Issue by ahmedflix25** [MahApps/MahApps.Metro#2474]
## What steps will reproduce this issue?
just add new right to left DatePicker
_Write problem description here_
when I make the datepicker flow direction right to left the the control image get flipped too
http://i.imgur.com/XU2o2Sm.png
### Expected outcome

_Write expected outcome here_
http://i.imgur.com/RBl7Fss.png
--
### Environment

- MahApps.Metro __v?.?.?__
1.2.4.0
- Windows __??__
windows 10
- Visual Studio __
2015 com update 2
- .NET Framework __?.?__
4.0

**Comment by punker76** [comment]
@ahmedflix25 I fixed it in 721548b5b0eb55d7de6fe000b06f3d9bdaf08cfd
