### ISSUE TITLE
Extending BaseLight/BaseDark theme

### ISSUE THREAD

**Issue by x000000** [MahApps/MahApps.Metro#2475]
I'm trying to extend standart themes, and everything seem good except dialogs' inputs. 
When i change theme to the dark one TextBox in the standart input dialog still uses white background.

My test setup looks like that:

CustomLight.xaml (CustomDark.xaml)
```xaml
<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                    xmlns:options="http://schemas.microsoft.com/winfx/2006/xaml/presentation/options"
                    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
                    mc:Ignorable="options">
    <ResourceDictionary.MergedDictionaries>
        <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/BaseLight.xaml" />
    </ResourceDictionary.MergedDictionaries>
</ResourceDictionary>
```

Main window logic
```cs
using System;
using System.Windows;
using MahApps.Metro;
using MahApps.Metro.Controls.Dialogs;

namespace DialogTest 
{

	public partial class MainWindow 
	{

		private bool _isDark = false;
		public  bool  IsDark
		{
			get
			{
				return _isDark;
			}
			set
			{
				ThemeManager.ChangeAppTheme(App.Current, value ? "CustomDark" : "CustomLight");
				_isDark = value;
			}
		}

		public MainWindow() 
		{
			ThemeManager.AddAppTheme("CustomLight", new Uri("pack://application:,,,/CustomLight.xaml"));
			ThemeManager.AddAppTheme("CustomDark",  new Uri("pack://application:,,,/CustomDark.xaml"));

			IsDark = false;

			InitializeComponent();
		}

		private void ToggleButtonClick(object sender, RoutedEventArgs e) 
			=> IsDark = !IsDark;

		private async void DialogButtonClick(object sender, RoutedEventArgs e) 
			=> await this.ShowInputAsync("Some title", "Some message");

	}

}
```

Screenshots:
![mahlight](https://cloud.githubusercontent.com/assets/1010098/14612007/af3a86b4-059d-11e6-9339-0ea23aef3101.png)
![mahdark](https://cloud.githubusercontent.com/assets/1010098/14612008/af3d9084-059d-11e6-9db8-5128ac3dd7a5.png)

--
#### Environment

- MahApps.Metro __v1.2.4__ (current master HEAD)
- Windows __8.1__
- Visual Studio __2015__
- .NET Framework __4.6.1__

**Comment by punker76** [comment]
@x000000 Can you try the latest pre-release? And can you show us your custom themes? Thx!

**Comment by x000000** [comment]
Latest pre-release acts the same way. 
Custom theme is CustomLight.xaml / CustomDark.xaml listed above. It's literaly just "MergedDictionary" of original theme.

**Comment by punker76** [comment]
@x000000 your custom resource dictionaries must contains all brushes and colors like in BaseLight or BaseDark.

**Comment by punker76** [comment]
@x000000 here is a good sample solution https://github.com/punker76/code-samples/tree/master/MahAppsMetroThemesSample with this [custom theme](https://github.com/punker76/code-samples/blob/master/MahAppsMetroThemesSample/MahAppsMetroThemesSample/CustomAccents/CustomTheme.xaml)

**Comment by x000000** [comment]
If i have to re-define all resources then it's not an extension of a theme, it's just new theme from a scratch. But if there is no other way then i'll do it as you suggest.

**Comment by punker76** [comment]
@x000000 Yeah, you're right. Maybe this can be even made better, but for now it works since months... maybe for v2.0...

**Comment by JobaDiniz** [comment]
How can I create a grayish `BaseLight` theme?
For example, [this custom theme](https://github.com/punker76/code-samples/blob/master/MahAppsMetroThemesSample/MahAppsMetroThemesSample/CustomAccents/CustomTheme.xaml) is gray, however **everything** is gray. Textbox, combobox should be white.

My goal is to create a theme much like VS light theme:
![untitled](https://cloud.githubusercontent.com/assets/165290/18515379/8dcf83ce-7a6b-11e6-9db0-48d6ccd48a2c.png)

You can see that the base color is gray, but textbox, combox, avalonedit (which I set the BackgroundColor to `WhiteColorBrush`)

The current BaseLight theme is just too bright :)

**Comment by thoemmi** [comment]
There's a tutorial how to create your own custom theme: http://mahapps.com/guides/styles.html#custom
