### ISSUE TITLE
DefaultButtonFocus Not Working As Expected

### ISSUE THREAD

**Issue by BMXerDan** [MahApps/MahApps.Metro#2479]
## What steps will reproduce this issue?

Creating a Metro dialog as below:

MetroDialogSettings mds2 = new MetroDialogSettings();
mds2.ColorScheme = MetroDialogColorScheme.Accented;
mds2.DefaultButtonFocus = MessageDialogResult.Negative;
mds2.AffirmativeButtonText = "Yes";
mds2.NegativeButtonText = "No";
MessageDialogStyle Style2 = MessageDialogStyle.AffirmativeAndNegative;

var result = await this.ShowMessageAsync("What next...", "Would you like to import more files?", Style2, mds2);

Default button focus seems to be focused on the "Affirmative" button as it's style shows it highlighted in a slightly lighter colour. Pressing the "Enter" key selects the "Negative" button instead of the "Affirmative" button.

Trying to set the DefaultButtonFocus to the MessageDialogResult.Negative button has no effect on the display.

### Expected outcome

If DefaultButtonFocus is set to Affirmative, it should be highlighted and pressing enter should select that button.

If DefaultButtonFocus is set to Negative, it should be highlighted and pressing enter should select that button.

--
### Environment

- MahApps.Metro v1.2.4
- Windows 10 Pro 64Bit
- Visual Studio Professional 2013 Version 12.0.31101.00 Update4
- .NET Framework 4.5.1

**Comment by punker76** [comment]
It's time for using the [KeyboardNavigationHack](https://github.com/punker76/KeyboardNavigationHack) :smile:
