### ISSUE TITLE
Windows 10 SplitView 

### ISSUE THREAD

**Issue by amoamare** [MahApps/MahApps.Metro#2480]
Would like to see new control similar to the windows 10 SplitView example here: 
https://blogs.msdn.microsoft.com/quick_thoughts/2015/06/01/windows-10-splitview-build-your-first-hamburger-menu/

Would be great addition the controls already available.

**Comment by Evangelink** [comment]
I have created one SplitView for the [UniversalWPF](https://github.com/dotMorten/UniversalWPF) project. But it seems like the project is on pause (or abandoned?).

**Comment by punker76** [comment]
@Evangelink :-) I know this project... If you want then create this here, but it is old school WPF 4+ :see_no_evil:

**Comment by Evangelink** [comment]
@punker76 No problem! It might take me some time to provide the full code + demo for now (quite a lot of things to do right now).

**Comment by Evangelink** [comment]
See PR #2610

**Comment by punker76** [comment]
Added with https://github.com/MahApps/MahApps.Metro/pull/2704
