### ISSUE TITLE
Error messages for missing .cs files during debugging

### ISSUE THREAD

**Issue by i-yotov** [MahApps/MahApps.Metro#2484]
Hi, I'm having issues when debugging (stepping). 

For example, if I call this.InitializeComponent() for a Page, this is shown:
![1](https://cloud.githubusercontent.com/assets/15329949/14781925/3fb82444-0aee-11e6-8ee2-37d8c0c95d18.jpg)
![2](https://cloud.githubusercontent.com/assets/15329949/14781927/431b01a6-0aee-11e6-8dcc-81f6539a0d3a.jpg)

plus a couple more error messages for other .cs files.

The strange thing is than the code compiles and works just fine.

Any suggestions on what I'm doing wrong? (Windows 7, Visual Studio 2013 Express, .NET 4.5)

**Comment by punker76** [comment]
@i-yotov MahApps uses [GitLink](https://github.com/GitTools/GitLink) for pdb files. But the 1.2.4 pdb files doesn't. So you have 2 options for debug settings
- check "Just my Code" 
- or use the pre-release and enable "Enable source server support" and as an option uncheck "Just my Code"

**Comment by i-yotov** [comment]
@punker76 Do you know if there's a way to fool VS's internet connection check? The "Enable source server support" option is not included in VS Express.

**Comment by punker76** [comment]
@i-yotov if the nuget package manager works then internet shoudl be work. Maybe the "Enable source server support" is available in VS Community 2015

**Comment by i-yotov** [comment]
Just tried it with VS Community 2015, still getting the errors. It seems to be an issue with VS, people are complaing on MSDN forums about the same problem and there seems to be no real solution, somebody even created a library for muting the errors, lol. Oh well, thanks anyway for responding.
