### ISSUE TITLE
Set Foreground color of Flyouts does not work for complete Flyout

### ISSUE THREAD

**Issue by evilbaschdi** [MahApps/MahApps.Metro#2490]
I have added some custom styles to my applications. Setting the theme to dark now makes it impossible to read labels for example. If I set the Foreground color of the whole flyout only the description of the flyout is getting changed and I have to change every control it selve.

How do you manage to switch color from black to white if the application is getting set from light to dark?

**Comment by punker76** [comment]
@evilbaschdi The Flyout tries to handle the correct theming, so I think maybe the `Adapt` setting for the Flyout theme could be the correct way for you...

```csharp
        internal void ChangeFlyoutTheme(Accent windowAccent, AppTheme windowTheme)
        {
            // Beware: Über-dumb code ahead!
            switch (this.Theme)
            {
                case FlyoutTheme.Accent:
                    ThemeManager.ChangeAppStyle(this.Resources, windowAccent, windowTheme);
                    this.SetResourceReference(BackgroundProperty, "HighlightBrush");
                    this.SetResourceReference(ForegroundProperty, "IdealForegroundColorBrush");
                    break;

                case FlyoutTheme.Adapt:
                    ThemeManager.ChangeAppStyle(this.Resources, windowAccent, windowTheme);
                    break;

                case FlyoutTheme.Inverse:
                    AppTheme inverseTheme = ThemeManager.GetInverseAppTheme(windowTheme);

                    if (inverseTheme == null)
                        throw new InvalidOperationException("The inverse flyout theme only works if the window theme abides the naming convention. " +
                                                            "See ThemeManager.GetInverseAppTheme for more infos");

                    ThemeManager.ChangeAppStyle(this.Resources, windowAccent, inverseTheme);
                    break;

                case FlyoutTheme.Dark:
                    ThemeManager.ChangeAppStyle(this.Resources, windowAccent, ThemeManager.GetAppTheme("BaseDark"));
                    break;

                case FlyoutTheme.Light:
                    ThemeManager.ChangeAppStyle(this.Resources, windowAccent, ThemeManager.GetAppTheme("BaseLight"));
                    break;
            }
        }
```

**Comment by evilbaschdi** [comment]
Well, using the "Adapt" theme leaves me a white background for all my flyouts. That is not really, what I want.
I already have some code that is determining to use white or black as a ForegroungColor.
I hoped that that would also be possible by adding or changeing a special resource in my new accent.
Otherwise I would have to overwrite both of the base themes or create my own special theme to automatically calculate the correct foregrounc color.

Here is, what I try to do:
https://github.com/evilbaschdi/EvilBaschdi.Core/blob/master/EvilBaschdi.Core/Wpf/ThemeManagerHelper.cs

**Comment by punker76** [comment]
@evilbaschdi Ah I see you inspired from this https://github.com/punker76/code-samples/blob/master/MahAppsMetroThemesSample/MahAppsMetroThemesSample/ThemeManagerHelper.cs :-D
So it seems that you additional need a custom theme... but I'll thought about a better solution

**Comment by evilbaschdi** [comment]
oh yes! I was looking for a solution to overwrite Highlight Color to fit the current selected windows theme (working backwards untill vista - on xp I had other problems with mahapps). after some <<enter your web search provider here>>ing I found you solution.

**Comment by punker76** [comment]
Please test the latest 1.5.0-alpha015. This should be fixed now.
