### ISSUE TITLE
MetroProgressBar / IsIndeterminate / Animation Warning 6

### ISSUE THREAD

**Issue by fremuc** [MahApps/MahApps.Metro#2492]
## What steps will reproduce this issue?
Use MetroProgressBar in a ControlTemplate. (in my case containing a grid and that is containing the MetroProgressBar)
Bind Property IsIndeterminate to a boolean view model property.
Toggle the view model property.

### Problem

System.Windows.Media.Animation Warning: 6 : Unable to perform action because the specified Storyboard was never applied to this object for interactive control.; Action='Stop'; Storyboard='System.Windows.Media.Animation.Storyboard'; Storyboard.HashCode='40295706'; Storyboard.Type='System.Windows.Media.Animation.Storyboard'; TargetElement='System.Windows.Controls.Grid'; TargetElement.HashCode='14546126'; TargetElement.Type='System.Windows.Controls.Grid'

System.Windows.Media.Animation Warning: 6 : Unable to perform action because the specified Storyboard was never applied to this object for interactive control.; Action='Remove'; Storyboard='System.Windows.Media.Animation.Storyboard'; Storyboard.HashCode='40295706'; Storyboard.Type='System.Windows.Media.Animation.Storyboard'; TargetElement='System.Windows.Controls.Grid'; TargetElement.HashCode='14546126'; TargetElement.Type='System.Windows.Controls.Grid'
### Expected outcome

No warnings would be nice.

### Environment

- MahApps.Metro v1.2.4.0
- Windows 10
- Visual Studio 2013 Update 5
- .NET Framework 4.5.1

**Comment by punker76** [comment]
@fremuc Can you provide a short sample on your GitHub account? And please let me know, if this already happens with the latest pre-release? Thx!!!

**Comment by fremuc** [comment]
Sorry, i don't have much spare time for a while. I just wanted to notify about that issue.
As far as i see, the warning occurs on destroying the content (represented by the ControlTemplate). There are only 'stop' and 'remove' actions which fails. Inside the code of the MetroProgressBar, there is a method to get the 'ChildGrid' of the current ControlTemplate. I guess that the problem is somehow located there.

Maybe i will have some time at the upcoming weekend. So please don't close this issue, it really exists and the warnings in the output window are really annoying... :/

**Comment by fremuc** [comment]
Here's the requested example:
https://github.com/fremuc/Code-Samples

**Comment by punker76** [comment]
@fremuc Thx for the sample! The issue should be fixed now with f84426d19a7bca6e237ed8ecf66214360dc493aa
