### ISSUE TITLE
Minimize and Maximize Visible during runtime

### ISSUE THREAD

**Issue by akhalid** [MahApps/MahApps.Metro#2493]
## What steps will reproduce this issue?
Upgrading from version 1.3.0-ALPHA139 to ALPHA47

When in full screen mode, the Minimize and Maximize buttons are visible in the TitleBar

### Expected outcome
The Minimize and Mazimize should not be visible
I am using the following which was giving the desired results:

WindowStartupLocation="CenterScreen"  
ResizeMode="NoResize" 
ShowTitleBar="False"
ShowCloseButton="False"
WindowStyle="None"

--
### Environment

- MahApps.Metro 1.3.0-ALPHA147
- Windows 10 
- Visual Studio 2013
- .NET Framework 4.6.1

**Comment by punker76** [comment]
@akhalid should be fixed with 143168e382764507f49a6a4ea41928e238c71fe1

**Comment by akhalid** [comment]
Thank you very much!
