### ISSUE TITLE
I am unable to Get the Selected Item Text of Combobox(I had tried each and Every Property)   Combobox with Auto Complete

### ISSUE THREAD

**Issue by akshithrajesh290** [MahApps/MahApps.Metro#2494]
## What steps will reproduce this issue?

_Write problem description here_

### Expected outcome

_Write expected outcome here_

--
### Environment

- MahApps.Metro __v?.?.?__
- Windows __??__
- Visual Studio __20xx__
- .NET Framework __?.?__

**Comment by punker76** [comment]
@akshithrajesh290 
- Which version of MahApps?
- Reproducing instructions?
- Sample code?
- Maybe not MahApps related? Have you tried normal ComboBox (without MahApps sytel)?

**Comment by akshithrajesh290** [comment]
Combo Box (Autocomplete with Grouping)

 <ComboBox  Grid.Column="1" Grid.ColumnSpan="3" Grid.Row="2"   Height="30" VerticalAlignment="Stretch" HorizontalAlignment="Stretch"
                          
                          Controls:TextBoxHelper.Watermark="Select The Product"
                          ToolTip="Select Product"
                          DisplayMemberPath="Title"
                          IsEditable="True"
                          IsEnabled="True"
                          ItemsSource="{Binding Albums}"
                          Text="{Binding Path=Title}"
                          Controls:ComboBoxHelper.EnableVirtualizationWithGrouping="True"
                          Name="Cmb_Products" SelectionChanged="groupingComboBox1_SelectionChanged">
                <ComboBox.GroupStyle>
                    <GroupStyle>
                        <GroupStyle.HeaderTemplate>
                            <DataTemplate>
                                <TextBlock  Text="{Binding Path=Name.Name}" />
                            </DataTemplate>
                        </GroupStyle.HeaderTemplate>
                    </GroupStyle>
                </ComboBox.GroupStyle>
            </ComboBox>


![image](https://cloud.githubusercontent.com/assets/16162616/15139594/9ded08a0-16b4-11e6-8c11-c6fdd1f6a7f4.png)

**Comment by punker76** [comment]
@akshithrajesh290 Here are good explainations for this/your issue http://stackoverflow.com/a/31574510/920384 and http://stackoverflow.com/a/2961144/920384
