### ISSUE TITLE
Default for ControlsHelper.HeaderFontSizeProperty should be SystemFonts.MessageFontSize

### ISSUE THREAD

**Issue by pfattisc** [MahApps/MahApps.Metro#2495]
## What steps will reproduce this issue?

The default ControlsHelper.HeaderFontSize is way too big. I have several GroupBoxes and Expander controls in my application and I don't use the MahApps.Fonts.xaml so all controls use the system settings.
However all controls using ControlsHelper.HeaderFontSize apply it's default which is 26.67.

### Expected outcome

The default of ControlsHelper.HeaderFontSize should be **SystemFonts.MessageFontSize**.
With that all controls would take the system settings if **ContentFontSize** is not set.

--
### Environment

- MahApps.Metro __v1.2.4__
- Windows __7 x64__
- Visual Studio __2013__
- .NET Framework __4.5__

**Comment by punker76** [comment]
@pfattisc fixed/added with 9c90a09c0669f42c293e14b5df691d677ffd1dd6
