### ISSUE TITLE
Vertical space for Title still being taken up even though Title is blank

### ISSUE THREAD

**Issue by makingbloke** [MahApps/MahApps.Metro#2498]
If I have a custom dialog with no title then the vertical space on the screen is still taken up where the title should be. This makes custom dialogs look a little weird as you have a very large top margin and a small bottom one. I can get round this by using a custom style / template / triggers but surely if there is no title then there should not be a gap for the title.

**Comment by punker76** [comment]
@makingbloke Fixed with 1707586aba3db2c13821e8dc4060d9efbea93918
