### ISSUE TITLE
Customize MessageDialog button style

### ISSUE THREAD

**Issue by smlacombe** [MahApps/MahApps.Metro#2500]
Hi, I know that the question has been asked before but no provided answers have helped me. About the solution provided for this [issue ](https://github.com/MahApps/MahApps.Metro/issues/2283), is there a documentation for the usage of CustomResourceDictionary ? I noticed that it is just a resource dictionary included in the BaseMetroDialog resource, I guess it must be useful for a complete custom dialog but I don't understand how it can be useful for overiding the default template for the MessageDialog button style. 

About this [post ](http://stackoverflow.com/questions/30751663/how-to-change-mahapps-metro-dialog-content-template-width), the provided solution has only the effect of overriding the BaseMetroDialogTemplate and not the MessageDialogTemplate. Am I missing something ?

Thanks

**Comment by punker76** [comment]
@smlacombe With v1.6.0 it will be easier to change the styles of the buttons or the style/template of dialogs.

e.g. Changing the button styles for the message dialog:

```xaml
<Style TargetType="{x:Type Dialogs:MessageDialog}" BasedOn="{StaticResource {x:Type Dialogs:BaseMetroDialog}}">
    <Style.Resources>
        <Style BasedOn="{StaticResource MetroFlatButton}" TargetType="{x:Type Button}">
            <Setter Property="controls:ControlsHelper.ContentCharacterCasing" Value="Upper" />
        </Style>

        <Style x:Key="AccentedDialogSquareButton"
                BasedOn="{StaticResource MetroFlatButton}"
                TargetType="{x:Type Button}">
            <Setter Property="Background" Value="{DynamicResource AccentColorBrush}" />
            <Setter Property="Foreground" Value="{DynamicResource IdealForegroundColorBrush}" />
            <Setter Property="controls:ControlsHelper.ContentCharacterCasing" Value="Upper" />
        </Style>

        <Style x:Key="AccentedDialogHighlightedSquareButton"
                BasedOn="{StaticResource MetroFlatButton}"
                TargetType="{x:Type Button}">
            <Setter Property="Background" Value="{DynamicResource HighlightBrush}" />
            <Setter Property="Foreground" Value="{DynamicResource IdealForegroundColorBrush}" />
            <Setter Property="controls:ControlsHelper.ContentCharacterCasing" Value="Upper" />
        </Style>
    </Style.Resources>
</Style>
```

![image](https://user-images.githubusercontent.com/658431/34921019-80b3b048-f97c-11e7-8263-973e5c340581.png)

So, it's not necessary to use the `CustomResourceDictionary` which can be set at the settings class for each dialog. This property was added as a workaround to override the dialog styles or other parts of the dialog, cause during the initialization of the dialogs all MahApps resources are added again to the resources of these dialogs. This is now not necessary anymore.

**Comment by abhinovpankaj** [comment]
I have a WPF application, which is using MaterialDesign.
For showing progress and dialogs I have integrated with Mah dialogs.
But following this suggestion, I have not been able to apply the Material style to the dialog. I am creating the DialogController from code behind and showing/hiding from my VM. Need some help.
My app.xaml looks like this.

<Style TargetType="{x:Type Dialogs:MessageDialog}" BasedOn="{StaticResource {x:Type Dialogs:BaseMetroDialog}}">
                <Style.Resources>
                    <Style  TargetType="{x:Type Button}">
                        <Setter Property="controls:ControlsHelper.ContentCharacterCasing" Value="Upper" />
                    </Style>

                    <Style x:Key="AccentedDialogSquareButton"  TargetType="{x:Type Button}">
                        <Setter Property="Background" Value="{DynamicResource AccentColorBrush}" />
                        <Setter Property="Foreground" Value="{DynamicResource IdealForegroundColorBrush}" />
                        <Setter Property="controls:ControlsHelper.ContentCharacterCasing" Value="Upper" />
                    </Style>

                    <Style x:Key="AccentedDialogHighlightedSquareButton" 
                TargetType="{x:Type Button}">
                        <Setter Property="Background" Value="{DynamicResource HighlightBrush}" />
                        <Setter Property="Foreground" Value="{DynamicResource IdealForegroundColorBrush}" />
                        <Setter Property="controls:ControlsHelper.ContentCharacterCasing" Value="Upper" />
                    </Style>
                    <Style  x:Key="MahApps.Styles.BaseMetroDialog" TargetType="{x:Type Dialogs:BaseMetroDialog}">
                        <Setter Property="Background" Value="{DynamicResource PrimaryHueDarkBrush}" />
                        <Setter Property="Foreground" Value="{StaticResource PrimaryHueDarkForegroundBrush}"/>
                    </Style>
                </Style.Resources>
            </Style>

I have also added the Basedon MetroFlatButton as well, but none of it worked.
