### ISSUE TITLE
Adding spinning functionality for icon packs

### ISSUE THREAD

**Issue by realies** [MahApps/MahApps.Metro#2501]
Hi, I've recently used Font-Awesome-WPF which has a nice Spin property that allows the user to spin an icon and even set duration of the spin. This was quite useful in certain situations and was wondering if embedding it to the Metro icon packs would be possible?

https://github.com/charri/Font-Awesome-WPF/blob/master/README-WPF.md#spinning-icons

PS: Adding font-awesome to the packs could also be cool :)

**Comment by punker76** [comment]
Hi @realies the spimming couls be possible.

**Comment by punker76** [comment]
-> https://github.com/MahApps/MahApps.Metro.IconPacks/issues/9
