### ISSUE TITLE
DataGrid causes lag when switching content

### ISSUE THREAD

**Issue by R74NN** [MahApps/MahApps.Metro#2504]
## What steps will reproduce this issue?

I'm using basic WPF DataGrid with MahApps styles. When switching content in ContentControl the page containing the DataGrid causes noticeable lag when switching from it.

The lag is not present on an empty grid. But when it contains some rows (tested on 100 rows and 10 columns) the lag appears. When I disable MahApps and all other code stays in place, the lag is not present and the switching is instant.

I'm not sure but a clue could be DataGridCellHelper and DataGridCellUnloaded event.

### Environment

- MahApps.Metro __v1.3.0-ALPHA150__
- Windows __10__
- Visual Studio __2015__
- .NET Framework __4.6__

**Comment by punker76** [comment]
@R74NN Thx for reporting this. Can you create a repo app for this issue, so we can try to find the problem. thx

**Comment by R74NN** [comment]
One another thing I have noticed. I have 1000 items in the grid and when I run the application with default window size of something like 1024x720, the grid scrolls quite fine and smoothly. When I maximize and restore the window few times, the grid scrolling becomes jerky and the grid exhibits very high CPU usage.

And again, without MahApps styles the behaviour is without these problems.

Unfortunately I can't send you my current project where the issue is present, however I hope I will be able to prepare a demo over the weekend.

Thanks.

**Comment by punker76** [comment]
@R74NN A demo would be very useful. Thx!

**Comment by R74NN** [comment]
Hi, sorry for the delay. Here is the app demonstrating the issue.

When you run it, the DataGrid scrolls nicely and smoothly. If you maximize the window and then restore to original size again, the scrolling is more jerky and takes more processor power. It is more noticeable when running from Visual Studio. If you run the exe alone, the problem is not that significant, but still there.

https://www.dropbox.com/s/l8czkfnk58j2six/WpfApplication1.zip?dl=0

Thanks.

**Comment by GAMP** [comment]
I think it can be blamed on DataGridCellHelper. In general it degrades performance and make datagrid lag behind from the native style.

**Comment by punker76** [comment]
@R74NN @GAMP I'm looking for this

**Comment by punker76** [comment]
@R74NN @GAMP You can test this PR for better performance https://github.com/MahApps/MahApps.Metro/pull/2570
