### ISSUE TITLE
ComboBoxItem ToolTip styling issue

### ISSUE THREAD

**Issue by realies** [MahApps/MahApps.Metro#2506]
I've found out a bug in the styling when using ToolTop on each ComboBoxItem in a ComboBox.
Using the latest alpha you can reproduce it with this code:

```
 <ComboBox DisplayMemberPath="CountryName"
           SelectedItem="{Binding Country, UpdateSourceTrigger=PropertyChanged}"
           ItemsSource="{Binding Path=DataContext.Countries, RelativeSource={RelativeSource FindAncestor, AncestorType={x:Type UserControl}}}">
  <ComboBox.ItemContainerStyle>
   <Style>
    <Setter Property="Control.ToolTip" Value="{Binding Alpha}" />
   </Style>
  </ComboBox.ItemContainerStyle>
 </ComboBox>
```
![image](https://cloud.githubusercontent.com/assets/5107843/15297483/581f5a5c-1b92-11e6-9e45-e239844618ee.png)

and without the tooltip code

![image](https://cloud.githubusercontent.com/assets/5107843/15297526/88516436-1b92-11e6-9ea5-f0b612ab6d3d.png)

**Comment by punker76** [comment]
@realies You must inherit from `MetroComboBoxItem` style if you override the ItemContainerStyle.

**Comment by realies** [comment]
@punker76 Good point, thanks. This solved the problem:
`<Style TargetType="ComboBoxItem" BasedOn="{StaticResource MetroComboBoxItem}">`

I guess the issue could be deleted.
