### ISSUE TITLE
The close button of the Windows10 WindowsButtons template is a little lighter than the other buttons

### ISSUE THREAD

**Issue by smlacombe** [MahApps/MahApps.Metro#2507]
I've noticed that the Close Button of the Windows10 style is not as light as the Max/Min buttons.

I've attached the image to see the difference between the MetroApps Demo with the Windows 10 template (at the top) and the Windows Photos application (at the bottom). 

I suspect that a thicker path may fix the issue.

![xclosebuttondifferences](https://cloud.githubusercontent.com/assets/724851/15301542/2538d930-1b7c-11e6-9fe4-7a45a82a7107.png)

**Comment by punker76** [comment]
@smlacombe I've changed a little bit the close button in bd571c06dbe56d5fca3844c1bacd70d093f60f88.

**Comment by smlacombe** [comment]
Thanks, this is much better.
