### ISSUE TITLE
Dialog without focus when more than one is called.

### ISSUE THREAD

**Issue by adeniltonbs** [MahApps/MahApps.Metro#2511]
## What steps will reproduce this issue?

In the file \samples\MetroDemo\MainWindow.xaml.cs change the method "public ICommand ShowMessageDialogCommand..." code to:
```cs
        public ICommand ShowMessageDialogCommand
        {
            get
            {
                return this.showMessageDialogCommand ?? (this.showMessageDialogCommand = new SimpleCommand
                {
                    CanExecuteDelegate = x => true,
                    ExecuteDelegate = x =>
                    {
                        _dialogCoordinator.ShowMessageAsync(this, "Message from VM 01", "MVVM based messages!").ContinueWith(t => Console.WriteLine(t.Result));
                        _dialogCoordinator.ShowMessageAsync(this, "Message from VM 02", "MVVM based messages!").ContinueWith(t => Console.WriteLine(t.Result));
                    }
                });
            }
        }
```

Execute the sample MetroDemo.NET45 and Click in the menu Dialogs > Show MessageDialog via VM. See below image:
![image](https://cloud.githubusercontent.com/assets/6733483/15361093/91980e0a-1ce6-11e6-9be7-ef65a6754136.png)

When two dialogs are called, the second dialog is showed without focus. 
The keys Enter and Escape doesn't work in second dialog and the user have to click directly in the Button.
See below images:
![image](https://cloud.githubusercontent.com/assets/6733483/15360859/b71d3110-1ce5-11e6-9437-72a831879d76.png)
![image](https://cloud.githubusercontent.com/assets/6733483/15360863/bbbbd46a-1ce5-11e6-97cb-6917a430fadf.png)

### Expected outcome

I think that second, third, etc. window should be focused.

--
### Environment

- MahApps.Metro v1.24 and last commit (bd571c06dbe56d5fca3844c1bacd70d093f60f88).
- Windows 10x64
- Visual Studio 2015 update 2
- .NET Framework 4.5

**Comment by punker76** [comment]
@adeniltonbs You need the async/await to get this working (I used the latest source)

```csharp
                    ExecuteDelegate = async x =>
                    {
                        await _dialogCoordinator.ShowMessageAsync(this, "Message from VM", "MVVM based messages!").ContinueWith(t => Console.WriteLine(t.Result));
                        await _dialogCoordinator.ShowMessageAsync(this, "Message from VM 02", "MVVM based messages!").ContinueWith(t => Console.WriteLine(t.Result));
                    }
```

**Comment by adeniltonbs** [comment]
thank you, worked perfectly
