### ISSUE TITLE
NumericUpDown UseFloatingWatermark Issue

### ISSUE THREAD

**Issue by AndrzejKl** [MahApps/MahApps.Metro#2514]
## What steps will reproduce this issue?

Just add this to Your MetroWindow:
```xaml
 <Controls:NumericUpDown Value="40"
                                Controls:TextBoxHelper.Watermark="Watermark:"
                                Controls:TextBoxHelper.UseFloatingWatermark="True" />
```

With those styles:

```xaml
<ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Colors.xaml" />
                <!-- Accent and AppTheme setting -->
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/Blue.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/BaseLight.xaml" />
            </ResourceDictionary.MergedDictionaries>```
```

### Expected outcome

In this case Floating watermark shows only **after** pressing plus or minus button. 
In my opinion it should work like in TextBox (if value !=null then it's visible)...

--
### Environment

- MahApps.Metro __v1.2.4__
- Windows __10__
- Visual Studio __2013 Pro__
- .NET Framework __4.5__

**Comment by punker76** [comment]
@AndrzejKl thx for reporting, fixed with 1c6480d647ddb39b2fafd4e28ea157a82a006e88

**Comment by AndrzejKl** [comment]
Thx, also TextBoxHelper properties aren't visible in Intelisearch in visual Studio for NumericUpDown, like for TextBoxes. It's possible to fix that, R not?

**Comment by punker76** [comment]
@AndrzejKl really?

![2016-05-20_13h53_54](https://cloud.githubusercontent.com/assets/658431/15427012/66b5ada2-1e92-11e6-92c2-96e3f41810bb.png)

**Comment by AndrzejKl** [comment]
Yes, really:
![image](https://cloud.githubusercontent.com/assets/19487797/15427156/5c618cf8-1e93-11e6-81a2-a7100e756ddf.png)

**Comment by punker76** [comment]
@AndrzejKl Is this v1.2.4 ? Can you try the latest pre-release? (note: my last changes are only available tomorrow)

**Comment by AndrzejKl** [comment]
@punker76 With 1.3.0.153 (via Nuget) it looks like this:
![image](https://cloud.githubusercontent.com/assets/19487797/15427309/74bd77fc-1e94-11e6-8db2-4f5deb1103ed.png)

Under CleartextButton, are only 2 more properties: "SelectAllOnFocus" and "TextButton"

**Comment by punker76** [comment]
@AndrzejKl Ah, it's not showing, cause you have the Watermark and UseFloatingWatermark already choosen...

**Comment by AndrzejKl** [comment]
@punker76 Nope:
![image](https://cloud.githubusercontent.com/assets/19487797/15427566/511f4f4e-1e96-11e6-8012-47df3fdec4d2.png)

Btw: Maybe here it's a problem. After chose prerelase version, I have in Designer 2 errors:
![image](https://cloud.githubusercontent.com/assets/19487797/15427604/9758d5ca-1e96-11e6-9ff0-393883f9d2e8.png)

But I can run it without problems...

**Comment by punker76** [comment]
@AndrzejKl @drunkvs try closing vs, deleting obj/bin folders, reopen your solution and rebuild your stuff...

**Comment by AndrzejKl** [comment]
@punker76 Thx, errors R gone, but still no watermark and other options in InteliSense...

**Comment by punker76** [comment]
@AndrzejKl Ok, found it, 1.3.0-ALPHA154 (available tomorrow) will contain the fix for it

**Comment by AndrzejKl** [comment]
THX!

BTW: This project is really nice, good job!
