### ISSUE TITLE
NumericUpDown Value not displayed

### ISSUE THREAD

**Issue by puchs** [MahApps/MahApps.Metro#2515]
I know it sounds weird, but the NumericUpDown control will not show a value if:

1.) it is part of a DataTemplate
2.) and it contains a converter in a Binding of the Value property.
3.) and if either the Maximum or Minimum properties are set.

I have created a small sample solution, that exhibits the problem:

[NumericUpDownTest.zip](https://github.com/MahApps/MahApps.Metro/files/274516/NumericUpDownTest.zip)

The main window contains a ContentControl binding to the property "V" of the code-behind of the MainWindow class. It also contains a DataTemplate with two NumericUpDownControls. They are almost identical: 

`<NumericUpDown Grid.Row="0"
                                Grid.Column="0"
                                Height="23"
                                Margin="5,5,5,5"
                                Interval="1"
                                StringFormat="{}{0:###0}"
                                Value="{Binding Path=V,
                                                Converter={StaticResource identityConverter},
                                                UpdateSourceTrigger=LostFocus}" />`

The only difference is that one of the controls also contains the following two attributes (one is sufficient to trigger the problem):

`Maximum="2000"
 Minimum="-273"`

This control will not display the value bound to the NumericUpDown. The two attributes 

`diag:PresentationTraceSources.TraceLevel=High,
Mode=TwoWay,
`

of the Binding do not change the situation and neither does the StringFormat attribute. The BindingExpression seems to "vanish" - at least that is what I see in the WPF debugger of Visual Studio 2015. I can also see (thanks to the Binding diagnostics) that the converter is called and returns a correct value.

How did I find the problem: I exchanged all occurences of the DoubleUpDown from the Extended WPF Toolkit in my application with the MahApps.Metro NumericUpDown. The problem appeared only after this exchange.
### Expected outcome

Both NumericUpDownControls should display the same value.
### Environment
- MahApps.Metro 1.2.4, but I also could reproduce the problem with the development branch @ commit: 1c6480d
- Windows 7 x64 all patches installed
- Visual Studio 2015 Community
- .NET Framework 4.5.2 (and also 4.6.1)

**Comment by barjonas** [comment]
Even though it sounds obscure, I just stumbled this same bug with exactly the same 3 criteria met.  Everything works if I remove either the converter or the min and max properties.  Otherwise I can see that it Convert is called on the converter, but no value is displayed.  When value is set through the control's UI, ConvertBack is never called.

**Comment by bradley-dotnet** [comment]
This issue is still present, and seems to occur even without the converter; just a bound value in a data template breaks it.

**Comment by sbrett9** [comment]
For me this seem to occur if the following are true.

A) The NumericUpDown is part of a DataTemplate
B) The Value is bound to a property of the data context of the DataTemplate
C) Maximum and/or Minimum values have been set in the xaml.

After looking through the source for 1.30 (as that is what I am currently dedicated to), i found that there seems to be issues with the order the Max, Min and Value properties are read in on load.
If the read order is Value, and then either Max or Min, things seem to work fine.
If the min or max is read prior to the value, the binding expression bound to Value up and disappears and the control's DependencyProperty named ValueProperty remains null.

As I needed all 3, I figured out a work around.

Create a style for the NumericUpDown that checks the control's load flag and if it is loaded, set the max and min to the desired values.

The following is my full data template.

            <DataTemplate DataType="{x:Type volume:UniformVolumeData}">
                <Grid>
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition />
                        <ColumnDefinition />
                    </Grid.ColumnDefinitions>
                    <TextBlock Grid.Column="0"
                               HorizontalAlignment="Left"
                               Text="Volume: " />
                    <controls1:NumericUpDown x:Name="volumeUpDown"
                                             Grid.Column="1"
                                             MaxWidth="200"
                                             controls1:TextBoxHelper.ClearTextButton="True" controls1:TextBoxHelper.SelectAllOnFocus="True" controls1:TextBoxHelper.Watermark="Enter Volume"
                                             Focusable="True" HasDecimals="True" StringFormat=" {0:N2} μL"
                                             Value="{Binding Path=DataContext.Volume, ElementName=volumeUpDown, Converter={StaticResource ConstantExpressionToNumberConverter}, NotifyOnTargetUpdated=True, NotifyOnSourceUpdated=True, PresentationTraceSources.TraceLevel=High}">
                        <controls1:NumericUpDown.Style>
                            <Style TargetType="{x:Type controls1:NumericUpDown}">
                                <Style.Triggers>
                                    <DataTrigger Binding="{Binding Path=IsLoaded, ElementName=volumeUpDown}" Value="true">
                                        <Setter Property="Maximum" Value="1000000" />
                                        <Setter Property="Minimum" Value="0" />
                                    </DataTrigger>
                                </Style.Triggers>
                            </Style>
                        </controls1:NumericUpDown.Style>
                    </controls1:NumericUpDown>
                </Grid>
            </DataTemplate>

**Comment by iXab3r** [comment]
There is some bizarre behavior regarding conversion. I was using version 1.1.2.0 beforehand, yesterday I've decided to update to 1.4.3 and all my NumericUpDown usages broke - changes were not propagated from controls to viewmodels. 

I have used same approach with Converter="{StaticResource ConverterKey}" for my Value binding and it appears that replacing StaticResource usage with in-place instantiation of Converter has helped. I.e. instead of referencing converter by Key you should either reference it as a static field 

- Converter={x:Static

 Converters.MyFavoriteConverter} 
or create a new one 

- <Converter.Value><MyFavoriteConverter/></Converter.Value>.

**Comment by punker76** [comment]
@puchs Thx for the test app. This issue will be fixed and available in 1.5.0
