### ISSUE TITLE
Style trigger breaks the validation error template

### ISSUE THREAD

**Issue by MurariAlex** [MahApps/MahApps.Metro#2520]
## What steps will reproduce this issue?

If you set a style trigger like the following, targeting a textbox, the validation red adorner gets all messed up and the popup error won't show up.

I'm trying to implement a style trigger that makes the error validation enabled only if the control is enabled.

```xml
            <Style x:Key="ValidationOnlyIfEnabled" TargetType="{x:Type FrameworkElement}">
                <Style.Triggers>
                    <Trigger Property="IsEnabled" Value="false">
                        <Setter Property="Validation.ErrorTemplate">
                            <Setter.Value>
                                <ControlTemplate>
                                    <DockPanel>
                                        <Border BorderBrush="Gray" BorderThickness="0">
                                            <AdornedElementPlaceholder />
                                        </Border>
                                    </DockPanel>
                                </ControlTemplate>
                            </Setter.Value>
                        </Setter>
                    </Trigger>
                </Style.Triggers>
            </Style>
            <Style BasedOn="{StaticResource ValidationOnlyIfEnabled}" TargetType="TextBox" />
``` 
Here's how the textbox error looks like. And no pop-up.
![error](https://cloud.githubusercontent.com/assets/11204378/15456244/98a5d774-2040-11e6-8f76-62866c01432e.jpg)

### Expected outcome

Even with this trigger, the validation style isn't supposed to be overwritted and messed up.

--
### Environment

- MahApps.Metro __v1.2.4__
- Windows __10__
- Visual Studio __2015__
- .NET Framework __4.6.1__

**Comment by punker76** [comment]
@MurariAlex You break the MahApps TextBox style, cause you don't inheirt from the MetroTextBox style...
