### ISSUE TITLE
DatePicker and DateTimePicker UseFloatingWatermark don't work

### ISSUE THREAD

**Issue by AndrzejKl** [MahApps/MahApps.Metro#2524]
## What steps will reproduce this issue?
````xaml
<DatePicker  Controls:TextBoxHelper.UseFloatingWatermark="True"
             Controls:TextBoxHelper.Watermark="Watermark:"  />
````
If SelectedDate is null, then Watermark is visible, but FloatingWatermark don't work when SelectedDate != null.

### Expected outcome

Should work like on others controls

--
### Environment

- MahApps.Metro __v1.3.0.155__
- Windows __10__
- Visual Studio __2013 & 2015__
- .NET Framework __4.5__

**Comment by punker76** [comment]
@AndrzejKl yeah, `UseFloatingWatermark` not implemented yet for `DatePicker`...

**Comment by xxMUROxx** [comment]
@punker76 are you already developing this feature. Otherwise I could do that for `DateTimePicker` and for `TimePicker` too.

**Comment by punker76** [comment]
@xxMUROxx you can do it for DateTimePicker and for TimePicker, I'm currently on the Flyout PR

**Comment by AndrzejKl** [comment]
@xxMUROxx and for DatePicker ;)

**Comment by AndrzejKl** [comment]
@punker76 @xxMUROxx 
in prerelase Alpha 162 it should work?
If yes, still are some problems:
1. Datepicker in grid works somehow, but height doesn't get smaller, when You delete selectedDate:
Before selecting date:
![image](https://cloud.githubusercontent.com/assets/19487797/16117561/0feaa67a-33d3-11e6-848a-b62fe6ace7d1.png)
After selecting:
![image](https://cloud.githubusercontent.com/assets/19487797/16117570/1c469686-33d3-11e6-9943-99707150cac8.png)
After deleting date:
![image](https://cloud.githubusercontent.com/assets/19487797/16117419/4963e020-33d2-11e6-8a00-7f0cbe544163.png)
The same is for DateTimePicker, but at least Watermark vertically centering.
 For TextBox it works fine.
2. Problems start when You add DatePicker or DateTimePicker to StackPanel. Window start to increase and it doesn't stop. Just add that code and select date from calendar.
````xaml
<Controls:MetroWindow x:Class="wpf_test.MainWindow"
                      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                      xmlns:Controls="http://metro.mahapps.com/winfx/xaml/controls"
                      xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
                      xmlns:local="clr-namespace:wpf_test"
                      xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
                      Title="MainWindow"
                      GlowBrush="{DynamicResource AccentColorBrush}"
                      SizeToContent="WidthAndHeight"
                      mc:Ignorable="d">
    <StackPanel>
        <DatePicker Controls:TextBoxHelper.UseFloatingWatermark="True"
                    Controls:TextBoxHelper.Watermark="Watermark"
                    SelectedDateFormat="Long" />
    </StackPanel>
</Controls:MetroWindow>
````

**Comment by punker76** [comment]
@AndrzejKl should work after 6a954d152c3493bc0e533459b4f6ec352b745cc4 MahApps.Metro 1.3.0-ALPHA163

**Comment by AndrzejKl** [comment]
@punker76 @xxMUROxx Thanks, it looks that it works (Alpha 165)

BTW: Maybe it will be possible to add for DatePicker, DateTimePicker and TimePicker "IsWaitingForData" functionality? R should I open new issue?

**Comment by punker76** [comment]
@AndrzejKl Good! But I must say, that I don't like the IsWaitingForData effect stuff. IsWaitingForData for itself is good, but the effect has nasty effects 😭 if you use it with floating watermarks.

**Comment by AndrzejKl** [comment]
@punker76 You mean visual effects or technical ones? IMO Visually it looks fine (with floating watermark)...
