### ISSUE TITLE
System.Windows.Media.Animation.DoubleAnimation' cannot use default origin value of 'Infinity

### ISSUE THREAD

**Issue by AndrzejKl** [MahApps/MahApps.Metro#2525]
## What steps will reproduce this issue?
Just in clean MetroWindow designer add:
````xaml
   <Controls:NumericUpDown Controls:TextBoxHelper.UseFloatingWatermark="True"
                           Controls:TextBoxHelper.Watermark="test"
                           Value="40" />   
````
then save changes, close designer's tab and open it again, it will show that error in designer. Without  UseFloatingWatermark property, error doesn't show. So delete this property, save it, reopen it and error is gone.

### Expected outcome

--
### Environment

- MahApps.Metro __v1.3.0.155__
- Windows __10__
- Visual Studio __2013 and 2015__
- .NET Framework __4.5__

**Comment by punker76** [comment]
@AndrzejKl fixed with 7b05d8865f2b72b4e8c5904347ee1e11f4c1e01c
