### ISSUE TITLE
Coded UI Testing in not working Properly on this UI

### ISSUE THREAD

**Issue by akshithrajesh290** [MahApps/MahApps.Metro#2527]
on user controls it works good but when we come to Message Dialog (Coded UI is unable to record the Dialog windows)

Any Alternate solution for this 
- MahApps.Metro **v2.0.0**
- Windows  7 ultimate
- Visual Studio **2015**
- .NET Framework  4.5.2

**Comment by anshumittal47** [comment]
Coded UI is unable to record Mahapps Flyout on its latest version

**Comment by punker76** [comment]
@anshumittal47 @akshithrajesh290 There are now AutomationPeer support for Dialogs and Flyouts, available in v.1.6.0

![2018-01-14_19h58_48](https://user-images.githubusercontent.com/658431/34920625-cc1a56b0-f975-11e7-92d2-9b13c3efb172.png)
