### ISSUE TITLE
Setting TitleFontSize & CountFontSize in Tile is no longer working

### ISSUE THREAD

**Issue by p76984275** [MahApps/MahApps.Metro#2531]
## What steps will reproduce this issue?

After upgrade from **v1.2.4** to **v1.3.0-ALPHA155**.
Setting **TitleFontSize & CountFontSize** in **Tile** is no longer working.
e.g.
```
<controls:Tile Title="Finance" TitleFontSize="24" Background="Green" />
```
Or in samples [TilesExample.xaml](https://github.com/MahApps/MahApps.Metro/blob/develop/samples/MetroDemo/ExampleViews/TilesExample.xaml)

```
<Style x:Key="LargeTileStyle" TargetType="Controls:Tile">
        <Setter Property="Height" Value="125" />
        <Setter Property="TitleFontSize" Value="12" />
        <Setter Property="Width" Value="300" />
</Style>
```

### Expected outcome
It should work as v1.2.4.
Also in [Tile's ControlTemplate](https://github.com/MahApps/MahApps.Metro/blob/develop/MahApps.Metro/Themes/Tile.xaml):

Reverting from
```
FontSize="{TemplateBinding TitleFontSize}"
```
back to
```
FontSize="{Binding TitleFontSize, RelativeSource={RelativeSource TemplatedParent}}"
```
works as before.

I'm wondering why TemplateBinding is not working on TitleFontSize/CountFontSize.
Is TemplateBinding not supporting custom dependency property?
But Count is also a custom DP and works normally.

--
### Environment

- MahApps.Metro __v1.3.0-ALPHA155__
- Windows __7 x64__
- Visual Studio __2015__
- .NET Framework __4.6.1__

**Comment by punker76** [comment]
@p76984275 fixed with d3f3629bb0dd2bf0a3d24c8d9a8485adf250df07
The properties had the wrong value types, so maybe `{TemplateBinding xyz}` tries matching exactly to the types...
