### ISSUE TITLE
Setting Global Style makes control not get theme

### ISSUE THREAD

**Issue by Memphizzz** [MahApps/MahApps.Metro#2535]
## What steps will reproduce this issue?

If I set something like this in App.xaml: 

```
            <Style TargetType="ScrollBar" BasedOn="{StaticResource {x:Type ScrollBar}}">
                <Style.Triggers>
                    <Trigger Property="Orientation" Value="Horizontal">
                        <Setter Property="Height" Value="30"/>
                    </Trigger>
                    <Trigger Property="Orientation" Value="Vertical">
                        <Setter Property="Width" Value="30"/>
                    </Trigger>
                </Style.Triggers>
            </Style>

```
### Expected outcome

I would expect the control to still use the MahApps.Metro theme applied as its using "BasedOn" but unfortunately its not themed, its back to its default colors. If I set that Style in the ScrollViewer.Resources of an existing ScrollViewer it works fine. But I would like to have this Application Wide.

--
### Environment

- MahApps.Metro __v1.2.4__
- Windows __10__
- Visual Studio __2015__
- .NET Framework __4.5__

**Comment by amoamare** [comment]
Your based in should be pointed to MetroScrollBar

BasedOn="{StaticResource {x:Type MetroScrollBar}}"

**Comment by Memphizzz** [comment]
What namespace is that in?

**Comment by punker76** [comment]
@Memphizzz the styles located in
```
<ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.Scrollbars.xaml" />
```
and the keys are globally set in `Controls.xaml`
```
    <Style BasedOn="{StaticResource MetroScrollBar}" TargetType="ScrollBar" />
    <Style BasedOn="{StaticResource MetroScrollViewer}" TargetType="ScrollViewer" />
```

**Comment by punker76** [comment]
@Memphizzz it's also possible to override width or height of the scrollbars globally without restyling the styles
you must only override these keys after the MahApps resource dictionaries in your App.xaml.
```
    <System:Double x:Key="MetroScrollBarHeight">14</System:Double>
    <System:Double x:Key="MetroScrollBarWidth">14</System:Double>

    <System:Double x:Key="HorizontalScrollBarRepeatButtonWidth">14</System:Double>
    <System:Double x:Key="VerticalScrollBarRepeatButtonHeight">14</System:Double>
```
It's recommend to use the latest pre-release, cause there was a bug with these styles and keys usage.

**Comment by Memphizzz** [comment]
Works great! Thank you!
