### ISSUE TITLE
Validation Message is displayed twice when Target Framework is .Net Framework 4.5 or 4.6.1 

### ISSUE THREAD

**Issue by llgarrido** [MahApps/MahApps.Metro#2536]
## What steps will reproduce this issue?

1. Create a **Catel Wpf Application** targeting **.Net Framework 4.5 or 4.6.1**
2. Create a **model class** with a **Required** data annotation on its "Name" property.
3. Map the model and it property on the main viewmodel.
4. Insert a **TextBox** Control in the main view with **ValidatesOnDataErrors=True** in the text binding.

![net461validationmessage](https://cloud.githubusercontent.com/assets/18642700/15820492/a7d0c928-2be1-11e6-8cd7-b52c6ffe34a4.png)

### Expected outcome

![net40validationmessage](https://cloud.githubusercontent.com/assets/18642700/15820281/568b4a30-2be0-11e6-998c-229d1067d917.png)

The expected behaviour occurs If the sample application is written with .Net 4.0.
--
If I remove ValidatesOnDataErrors=True from the text binding then It displays the validation message once in the application written in .Net 4.61 but  it never displays in the version written with .Net 4.0.

I am wondering if Its something wrong on my styles and DataTemplate in the App.xaml resources.

**Both applications are attached in this message.**

[ValidationMessageSolution.zip](https://github.com/MahApps/MahApps.Metro/files/300283/ValidationMessageSolution.zip)

### Environment

- MahApps.Metro __v1.2.4.0__
- Windows __10__
- Visual Studio __2015__
- .NET Framework __4.6.1__

**Comment by punker76** [comment]
@llgarrido I think this is caused by the fact, that we have 2 notifies since 4.5 `ValidatesOnNotifyDataErrors` and `ValidatesOnDataErrors` So if both are `True` we see the error twice. You can handle this by setting
```
ValidatesOnNotifyDataErrors=True, ValidatesOnDataErrors=False
```
or
```
ValidatesOnNotifyDataErrors=False, ValidatesOnDataErrors=True
```

**Comment by llgarrido** [comment]
I am very grateful for your answer @punker76 . I was not aware of the new **INotifyDataErrorInfo** interface since we started to develop with .Net 4.5 recently.

My problem was that I have a nuget dependency that contains a couple of user controls with ValidatesOnDataErrors=True set in n the xaml and I needed to solve this conflict with our .Net 4.0 applications.

So I decided to write an specific Binding implementation just for those user controls. Taking into account that this dependency is a multi-target nuget package I wrote a conditional compilation to set  ValidatesOnDataErrors=True only for .Net 4.0 assemblies:

```cs
public class Binding : System.Windows.Data.Binding
    {

        private void initialize()
        {
#if NET40
            ValidatesOnDataErrors = true;
#endif
        }

        public Binding() : base()
        {
            initialize();
        }

        public Binding(string path) : base(path)
        {
            initialize();
        }
    }
```

Xaml changes:

```xml
<catel:UserControl
  xmlns:b="clr-namespace:MyAssembly.Bindings">
    <TextBox Text="{b:Binding name, UpdateSourceTrigger=PropertyChanged, Mode=TwoWay}"/>
</catel:UserControl>
```
