### ISSUE TITLE
Bad contrast in ProgressDialog's progress bar

### ISSUE THREAD

**Issue by brather1ng** [MahApps/MahApps.Metro#2537]
## What steps will reproduce this issue?

1. Set Theme to Dark and Accent to Steel.
2. Open any ProgressDialog that has a progress bar.
3. The progress is really hard to see 
![unbenannt](https://cloud.githubusercontent.com/assets/7596346/15836993/9fe67fd6-2c37-11e6-9a7a-b0ce16deb48d.PNG)

### Expected outcome

The progress bar foreground should have proper contrast to the background. Since the foreground color is overriden in the ProgressDialog style (to the Accent color) and the background color isn't (it's hardcoded in MetroProgressBar), this poor contrast can occur.

--
### Environment

- MahApps.Metro __v1.2.4__
- Windows __10__
- Visual Studio __2015__
- .NET Framework __4.5__

**Comment by punker76** [comment]
@brather1ng Should be better now after this change 3f9cbbb57df35c2c0d856d741e348ce20e6a66f2

![image](https://cloud.githubusercontent.com/assets/658431/15872802/8b1f19ea-2cfb-11e6-8108-94f7a13c3917.png)
![image](https://cloud.githubusercontent.com/assets/658431/15872803/8e71e0aa-2cfb-11e6-9994-e9258afd4b3d.png)

**Comment by brather1ng** [comment]
Thanks, that's much better.
