### ISSUE TITLE
Focus Message Dialog from flyout

### ISSUE THREAD

**Issue by dxdx347** [MahApps/MahApps.Metro#2538]
## What steps will reproduce this issue?

The user presses a button inside Flyout to execute a command and if an error message dialog appears, he has to click twice in order to close it (one time to close Flyout and the second time to close the message box). The problem appears only if the user clicks the message box affirmative button; if Enter is pressed, then the button is pressed.

### Expected outcome

The dialog should have focus so the user does not need to click it twice in order to close it, or the Flyout should be closed when the message box appears.

--
### Environment

- MahApps.Metro __v1.2.4__
- Windows __10__
- Visual Studio __2015__
- .NET Framework __4.6.1__

**Comment by dxdx347** [comment]
The attached project reproduces the problem as closely as possible as it is in my project. I observed that the problem is appears when flyout IsPinned="false".
[Test.zip](https://github.com/MahApps/MahApps.Metro/files/302336/Test.zip)

**Comment by punker76** [comment]
@dxdx347 Thx for the sample! It's now fixed with fe98adc7aa9983d7ce550f8a93b515db54da2498 (coming in 1.3.0-ALPHA160)
