### ISSUE TITLE
DataGrid does paint properly while scrolling the horizontal scroll bar 

### ISSUE THREAD

**Issue by EyalYasovsky** [MahApps/MahApps.Metro#2539]
![datagridissue](https://cloud.githubusercontent.com/assets/15193919/15892909/3edecd7a-2d85-11e6-96fe-cd48d567f24d.png)
## What steps will reproduce this issue?
Scroll horizontally quickly a DataGrid view from the left to the right
Please look at the attached screen shot.
The image to the left shows the UI before the scroll, and the image to the right shows the result after scrolling right and back to the left.
It looks as if you can continue scrolling to the left, but the scroll bar won't let you.
_Write problem description here_
The left column header get's cut off, or even disappears completely. 
### Expected outcome
The left header text should appear properly
_Write expected outcome here_

--
### Environment

- MahApps.Metro 1.1.3.223
- Windows 7
- Visual Studio 2013
- .NET Framework 4.5

**Comment by punker76** [comment]
@EyalYasovsky You say that you use 1.1.3.223 Can you try use stable 1.2.4 and/or pre-release 1.3.0-ALPHA160 THX!

**Comment by EyalYasovsky** [comment]
I set EnableRowVirtualization="True" and EnableColumnVirtualization="True", and the issue seems to be solved.
Thanks for the help,
Eyal
