### ISSUE TITLE
IsThreeState property on ToggleSwitch

### ISSUE THREAD

**Issue by fredericoregateiro** [MahApps/MahApps.Metro#2541]
## What steps will reproduce this issue?

Is it possible to handle the null values visually on a ToggleSwitch control like on the CheckBox?

### Expected outcome

The ToggleSwitch control should have 3 states, Checked, Unchecked and not defined

--
### Environment

- MahApps.Metro __v2.1.4
- Windows 10
- Visual Studio __2013
- .NET Framework 4.5

**Comment by punker76** [comment]
@fredericoregateiro I think this is not the right control for ThreeState, see also https://msdn.microsoft.com/en-us/windows/uwp/controls-and-patterns/toggles

**Comment by fredericoregateiro** [comment]
Thanks @punker76,
So i should stick with the good old checkbox.
