### ISSUE TITLE
NumericUpDown SelectAllOnFocus doesn't work

### ISSUE THREAD

**Issue by fredericoregateiro** [MahApps/MahApps.Metro#2542]
## What steps will reproduce this issue?

Setting the SelectAllOnFocus="True" property on a NumericUpDown control has no efect, on other and using the Controls:TextBoxHelper.SelectAllOnFocus="True" work as expected, selecting all text.

### Expected outcome

Setting the SelectAllOnFocus="True" on a NumericUpDown control should have the same behavior like the Controls:TextBoxHelper.SelectAllOnFocus="True"

--
### Environment

- MahApps.Metro v1.2.4
- Windows 10
- Visual Studio 2013
- .NET Framework 4.5

**Comment by xxMUROxx** [comment]
@punker76 I saw that you introduced the `SelectAllOnFocus` property in `NumericUpDown`. Wouldn't it be better to remove it, because no other control (also .NET internal controls) has such a property and completely rely on `TextBoxHelper.SelectAllOnFocus`

**Comment by punker76** [comment]
@xxMUROxx I'll look on this

**Comment by collegedude** [comment]
Hi,
I cannot enable the "select all on focus" for NumericUpDown control, it won't work neither with latest release 1.3 nor 1.4.0-ALPHA026
`<NumericUpDown metro:TextBoxHelper.SelectAllOnFocus="True" SelectAllOnFocus="True"/>`
Do you have any ideas?
Thanks,
collegedude

**Comment by punker76** [comment]
@collegedude You need only `metro:TextBoxHelper.SelectAllOnFocus="True"` the other one is obsolete. It works at the main demo.

```xaml
<Controls:NumericUpDown Controls:TextBoxHelper.SelectAllOnFocus="True"
                        ButtonsAlignment="Left"
                        HasDecimals="{Binding ElementName=HasDecimalsCheckBox, Path=IsChecked, Mode=TwoWay}"
                        Interval="5"
                        IsReadOnly="{Binding ElementName=ReadOnlyCheck, Path=IsChecked, Mode=TwoWay}"
                        Value="500" />
```

![2016-11-02_15h16_24](https://cloud.githubusercontent.com/assets/658431/19932174/548e601a-a10f-11e6-955b-00d87018078f.png)

**Comment by collegedude** [comment]
Hi again,
Thank you! The demo application is in fact working, but not my own application (also with MetroWindow). I will try to reproduce the problem with the demo application...
I have added both, the obsolete property and the TextBoxHelper, just to show that they are both not working.

**Comment by Cicciomnz** [comment]
Hello everyone,

i want to say thanks for your effort for this amazing work.
Like @collegedude say, the attached property Controls:TextBoxHelper.SelectAllOnFocus is working fine on the application demo, but i cannot use it in my own applications.

Also, the control won't take focus even if i simply click on it, but just when you click the contained value.

**Comment by collegedude** [comment]
Hello @Cicciomnz,
In my case it works if I add the following line in every UserControl that makes use of the TextBoxHelper:
```
    <UserControl.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </UserControl.Resources>

```

**Comment by Cicciomnz** [comment]
It works! Thanks a lot @collegedude

**Comment by punker76** [comment]
@Cicciomnz @collegedude It should also work if this resource is added in App.xaml

**Comment by punker76** [comment]
@Cicciomnz @collegedude

[MahAppsAndIconPacks.zip](https://github.com/MahApps/MahApps.Metro/files/595037/MahAppsAndIconPacks.zip)

![numupdown](https://cloud.githubusercontent.com/assets/658431/20352794/e7b84d92-ac18-11e6-926f-d182687f691f.gif)

**Comment by punker76** [comment]
@Cicciomnz 

>Also, the control won't take focus even if i simply click on it, but just when you click the contained value.

That's the behavior of all TextBoxHelper stuff like clear button or search button on TextBoxes.
