### ISSUE TITLE
DataGridNumericUpDownColumn PrepareCellForEdit (SelectAll) not working as intended (imho)

### ISSUE THREAD

**Issue by puchs** [MahApps/MahApps.Metro#2543]
## What steps will reproduce this issue?

1.) Start MetroDemo.Net45
2.) Navigate to "datagrid"
3.) Click twice on e.g. "Jazz" in the "genre" column, thrid line. This will select "Jazz", so any input will overwrite it.
4.) Single "Tab" to the "price" column. The price should be selected, if I do not misinterpret the intention of the method PrepareCellForEdit, but isn't.

### Expected outcome

If one "tabs" from column to column in editing mode, the current value should always be selected.

### Solution (imho)

I propose to add _valueTextBox.Focus() to NumericUpDown.SelectAll, since the _valueTextBox.SelectAll() is meaningless if the TextBox does not have focus.

1.)
`public void SelectAll()
 {
     if (_valueTextBox != null)
     {
         _valueTextBox.Focus();
         _valueTextBox.SelectAll();
     }
  }`

2.) Remove `numericUpDown.Focus();` from DataGridNumericUpDownColumn.PrepareCellForEdit, since the focus should be on the TextBox and not its parent.

I don't think that this changes will interfere with the intended behavior of the NumericUpDown control itself.

--
### Environment

- MahApps.Metro commit 12557bd, but also 1.2.4
- Windows 7 64 Bit
- Visual Studio 2015 SP2
- .NET Framework 4.5

**Comment by punker76** [comment]
@puchs fixed with d306bebfd7ba13a7ef742d40cb04182a54298b39
