### ISSUE TITLE
ShowMetroDialogAsync for ViewModel-First frameworks

### ISSUE THREAD

**Issue by realies** [MahApps/MahApps.Metro#2544]
Trying to display a subview + its viewmodel as a metro dialog in the MainWindow using [Stylet](https://github.com/canton7/Stylet/wiki), but can only see the CustomDialog.Title in the displayed dialog with the UserControl missing underneath.

Running it with this, not sure if there is a more efficient and of course working way of doing it.

```
var customDialog = new CustomDialog()
{
    Title = "Custom Dialog",
    Content = new OptionsView { DataContext = new OptionsViewModel() }
};
await dialogCoordinator.ShowMetroDialogAsync(this, customDialog);
```

UPDATE: I was missing InitializeComponent() in the UserControl as used to have this called by the framework, adding it fixes what was thought to be unexpected. 

UPDATE 2: Apparently the framework's IoC construction is trying to bind the DataContext to it's view and calling actions from the metro dialog redirects them to the MainWindow's DataContext.

**Comment by bloritsch** [comment]
Isn't it normal for there to be a XYZ.xaml and XYZ.xaml.cs with a constructor that calls `InitializeComponent()`?  I wouldn't want to have that as something that needs to be pushed off on MahApps.

However, reassigning the DataContext would be something I would not expect MahApps to do.

**Comment by realies** [comment]
I'm unsure how to to use the framework dependency injection with a CustomDialog as the constructor of the custom dialog VM requires Action<ViewModel> closeHandler for it to be closed. Making that VM as a singleton doesn't seem like a rational option.

**Comment by bloritsch** [comment]
Did you check out how custom dialog was (currently) designed to be used? https://github.com/MahApps/MahApps.Metro/blob/develop/samples/MetroDemo/MainWindowViewModel.cs

The `IDialogCoordinator` was obtained using `DialogCoordinator.Instance`, and that also works with `DialogParticipation` to register an association between one `DependencyObject` and the associated MetroWindow.  I'm hoping at least that this can give you some options.

**Comment by realies** [comment]
As you can see, I'm using a similar call structure as used in the RunCustomFromVm method from the link above. Am I missing something? Not sure why this doesn't get the correct DataContext
`new OptionsView { DataContext = new OptionsViewModel() }`

PS: Stylet's IoC tries to bind all Views with their ViewModels upon initializing.

**Comment by bloritsch** [comment]
I am not sure myself, but it appears that you might be able to replace
certain implementations to hook your framework in as well
On Jun 13, 2016 11:02 AM, "realies" <notifications@github.com> wrote:

As you can see, I'm using a similar call structure as used in the
RunCustomFromVm method from the link above. Am I missing something? Not
sure why this doesn't get the correct DataContext
new OptionsView { DataContext = new OptionsViewModel() }

PS: Stylet's IoC tries to bind all Views with their ViewModels upon
initializing.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/MahApps/MahApps.Metro/issues/2544#issuecomment-225607933>,
or mute the thread
<https://github.com/notifications/unsubscribe/AAL4DvvPTlsA7Cv-rle8hTyu1U4AwLB-ks5qLXDkgaJpZM4I0Leg>
.

**Comment by realies** [comment]
Stylet has a [WindowManager](https://github.com/canton7/Stylet/wiki/The-WindowManager), but I believe IDialogService is part of MahApps.Metro, although I'm able to inject IDialogService in whichever ViewModel I would like.

PS: It turned out that the ActionTarget has to be set for the framework command calling to work in the correct DataContext.

**Comment by punker76** [comment]
@realies Is this still an issue for you?

**Comment by thoemmi** [comment]
@bloritsch 
> Isn't it normal for there to be a XYZ.xaml and XYZ.xaml.cs with a constructor that calls InitializeComponent()?

I've written a small MVVM framework myself, [TinyLittleMvvm](https://github.com/thoemmi/TinyLittleMvvm). The first thing I do when adding a new view is deleting the code-behind file. That prevents yourself from adding functionality in the view, and enforces separating business logic from presentation.

**Comment by realies** [comment]
@punker76, I've found out that the child ViewModel's DataContext has been set correctly, but I was wrong assuming that the ICommand sugars that [Stylet](https://github.com/canton7/Stylet/wiki/Actions) provides would set command calls to the appropriate context automagically.

Essentially this is not a MahApps.Metro issue, but framework configuration unawareness.

Was able to accomplish the integration with the following:

MainViewModel:
```
public async void Options()
{
    var customDialog = new CustomDialog();

    var vm = new OptionsViewModel(this, instance => dialogCoordinator.HideMetroDialogAsync(this, customDialog));

    customDialog.Content = new OptionsView { DataContext = vm };
    await dialogCoordinator.ShowMetroDialogAsync(this, customDialog);
}
```

OptionsViewModel:
```
public OptionsViewModel Self { get { return this; } }
public void SomeMethod() { Console.WriteLine("It works!"); }
```

OptionsView:
```
<Button Content="Ha!" s:View.ActionTarget="{Binding Self}" Command="{s:Action SomeMethod}" />
```
