### ISSUE TITLE
SplitButton does not mark mouse events handled

### ISSUE THREAD

**Issue by bloritsch** [MahApps/MahApps.Metro#2545]
## What steps will reproduce this issue?

We have an application that has a canvas that allows users to add elements by mouse click.  We had some formatting controls accessible via a SplitButton.  When a user opened the drop down, the mouse was also over the canvas.  When they selected an option, the mouse click was bubbled through to our canvas and our code attempted to create an element at that position.

### Expected outcome

We expected the SplitButton drop down to behave more like a ComboBox.  When the user selects an option from the ComboBox, the mouse up event is marked as `e.Handled = true`.  That prevents the erroneous click on the canvas.

Our short term fix for now is to use a ComboBox and a separate button.

--
### Environment

- MahApps.Metro __v1.1.2__
- Windows __7 pro__
- Visual Studio __2013__
- .NET Framework __4.5__

**Comment by punker76** [comment]
@bloritsch Please test this again after merged PR https://github.com/MahApps/MahApps.Metro/pull/2572 thx!

**Comment by punker76** [comment]
@bloritsch Could you retest this with latest pre-release?

**Comment by bloritsch** [comment]
I'm sorry, I haven't gotten back to you yet.  I've been so crazy busy with
this software release and then a bunch of busy stuff at home.  Hopefully I
will be able to test it tomorrow.  Is the fix in a Pre-release or the
official release?

**Comment by punker76** [comment]
@bloritsch np, try latest pre-release, thx.

**Comment by bloritsch** [comment]
Confirmed.  It's working now.
