### ISSUE TITLE
DataGridNumericUpDownColumn has two Tabstops

### ISSUE THREAD

**Issue by puchs** [MahApps/MahApps.Metro#2546]
## What steps will reproduce this issue?

1.) Start MetroDemo.NET45
2.) navigate to "datagrid"
3.) Click once into the DataGrid, e.g. on "Jazz" in the third row.
4.) One Tab moves to the "price" column.
5.) One Tab tabs to the TextBox of the "prize" column, and the second Tab moves to the next column. 

### Expected outcome

I think the DataGridNumericUpDownColumn should behave like e.g. a DataGridTextColumn and that the TextBox should not be a TabStop if the DataGrid is not in editing-mode.

### Proposed Solution

1.) Add `numericUpDown.IsTabStop = isEditing ? true : false;` to line 135 of GenerateNumericUpDown. This makes sure that the NumericUpDown (and its child, the TextBox) is never a TabStop if the DataGrid is not in editing-mode. 

2.) There is another problem, that is connected to this issue: It should be possible to switch the DataGrid into editing-mode whenever a DataGridCell is "selected" (meaning one "tabbed" to the cell) by pressing a key. This was not possible up to now. Without this change (and ignoring the issue #2543), it was possible to (double-)tab to the TextBox and enter a new value without switching to the editing-mode via a mouse-click. This change makes this impossible. The best solution would be to use the OnInput method of the DataGridColumn (the DataGridTextColumn does just this), but this method is internal, and thus is not usable. It therefore is IMHO not possible to solve this problem within the DataGridNumericUpDownColumn class, but only via an attached property to the DataGrid:

`
controls:DataGridHelper.OnTextInputEdit="True"
`

with the following helper class:

`
using System;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;

namespace MahApps.Metro.Controls
{
    public class DataGridHelper
    {
        public static readonly DependencyProperty OnTextInputEditProperty =
      DependencyProperty.RegisterAttached("OnTextInputEdit",
                              typeof(bool),
                              typeof(DataGridHelper),
                              new UIPropertyMetadata(false, OnTextInputEditChanged));

        public static bool GetOnTextInputEdit(DependencyObject target)
        {
            if (target == null)
                throw new ArgumentNullException("target");

            return (bool)target.GetValue(OnTextInputEditProperty);
        }

        public static void SetOnTextInputEdit(DependencyObject target, bool value)
        {
            if (target == null)
                throw new ArgumentNullException("target");

            target.SetValue(OnTextInputEditProperty, value);
        }

        static void OnTextInputEditChanged(DependencyObject target, DependencyPropertyChangedEventArgs e)
        {
            System.Windows.Controls.DataGrid dataGrid = target as System.Windows.Controls.DataGrid;
            if (dataGrid == null || !(e.NewValue is bool))
                return;

            if ((bool)e.NewValue) {
                dataGrid.PreviewTextInput += DataGrid_OnTextInput;
            }
            else {
                dataGrid.PreviewTextInput -= DataGrid_OnTextInput;
            }
        }

        // perhaps there are other cases, that make handling the PreviewKeyDown event
        // necessary.
        static void DataGrid_OnTextInput(object sender, TextCompositionEventArgs e)
        {
            System.Windows.Controls.DataGrid grid = sender as System.Windows.Controls.DataGrid;

            // The DataGridTextColumn can handle the OnInput event itself.
            // ... perhaps I need to add other column types here
            if (grid.CurrentColumn is DataGridTextColumn)
                return;
            
            if (ContainsNonEscapeCharacters(e.Text))
                grid.BeginEdit(e as InputEventArgs);
        }

        static bool ContainsNonEscapeCharacters(string text)
        {
            for (int i = 0; i < text.Length; ++i) {
                if (text[i] != '\u001b')
                    return true;
            }

            return false;
        }
    }
}
` 

With the proposed change, issue #2543 fixed and the attached property, the DataGrid containing any number of DataGridNumericUpDownColumns should behave like the "original" WPF columns, e.g. DataGridTextColumn.

--
### Environment

- MahApps.Metro commit @12557bd and 1.2.4
- Windows 7 x64
- Visual Studio 2015 SP2
- .NET Framework 4.5

**Comment by punker76** [comment]
@puchs should be fixed with d306bebfd7ba13a7ef742d40cb04182a54298b39
