### ISSUE TITLE
Window Flyout before close event

### ISSUE THREAD

**Issue by makingbloke** [MahApps/MahApps.Metro#2548]
Is there any event or command that gets fired before a Flyout panel is closed to let me have the option of cancelling the close?

I've investigated CloseCommand but this happens after the panel is closed.

Cheers,

**Comment by punker76** [comment]
@makingbloke  The `CloseCommand` should be work well with their CanExecute usage (with the latest pre-realse)

**Comment by makingbloke** [comment]
That seems to work well thanks, I'm using the following execute function. Cheers.
`private async void ExecuteCloseFlyoutCommand()
{
        IsFlyoutOpen = await this.dialogService.ShowMessageBox("Lose unsaved changes?", "Database Connections", MessageBoxButton.OKCancel) == MessageBoxResult.Cancel;
}`
