### ISSUE TITLE
Feature Request: NonActiveWindowTitleColorBrush

### ISSUE THREAD

**Issue by dgadelha** [MahApps/MahApps.Metro#2551]
The same way we have `<SolidColorBrush x:Key="WindowTitleColorBrush" Color="">`, there should be a `<SolidColorBrush x:Key="NonActiveWindowTitleColorBrush" Color="">`.

**Comment by punker76** [comment]
@dgadelha  added in ece553203350f0a674f7918ae61dc23ae57c5e5b
