### ISSUE TITLE
How to hide flyout title

### ISSUE THREAD

**Issue by biless** [MahApps/MahApps.Metro#2552]
## How to hide flyout title

_I Can't Hide Flyout title_

![pic…](https://raw.githubusercontent.com/biless/AopKernel/master/QQ%E6%88%AA%E5%9B%BE20160616121630.png)

--
### Environment

- MahApps.Metro __v1.2.4__
- Windows __10__
- Visual Studio __2015__
- .NET Framework __4.5.2__

**Comment by biless** [comment]
@punker76

**Comment by punker76** [comment]
@biless Do you use the Flyout without Flyouts control? Can you post your Xaml code?

**Comment by biless** [comment]
<controls:MetroWindow x:Class="FlyoutHide.MainWindow"
                      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                      xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
                      xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
                      xmlns:local="clr-namespace:FlyoutHide"
                      xmlns:controls="http://metro.mahapps.com/winfx/xaml/controls"
                      mc:Ignorable="d"
                      WindowTitleBrush="Transparent"
                      Background="BurlyWood"
                      Title="MainWindow" Height="350" Width="525">
    <controls:Flyout
                     
                         TitleVisibility="Collapsed"
                         Width="{Binding RelativeSource={RelativeSource Mode=FindAncestor,AncestorType=controls:MetroWindow},Path=Width}"
                         IsOpen="True" Padding="0" UseLayoutRounding="False" CloseButtonVisibility="Collapsed" RenderTransformOrigin="0,0" Visibility="Visible" >
        
        <Button Width="30" Height="30" Cursor="Hand" HorizontalAlignment="Left" VerticalAlignment="Top" Click="Button_Click"></Button>
    </controls:Flyout>
</controls:MetroWindow>

**Comment by punker76** [comment]
@biless This is already fixed in pre-release. I disabled the title thumb usage with 7397c0cfc9ab207acf1499a0eec853ca339a8803 if a Flyout is not in the Flyouts collection. Available with MahApps.Metro 1.3.0-ALPHA164
