### ISSUE TITLE
Using dialogs with user controls

### ISSUE THREAD

**Issue by shaggygi** [MahApps/MahApps.Metro#2553]
Is there a way to call dialogs within a user control.  It appears you must pass a MetroWindow when instantiating.

**Comment by brather1ng** [comment]
If you know your user control is in a MetroWindow, you can get it with
```csharp
(MetroWindow) Window.GetWindow(yourUserControl)
```

and use that to open a dialog:

```csharp
var metroWindow = (MetroWindow) Window.GetWindow(yourUserControl);
await metroWindow.ShowMessageDialogAsync(...);
```

**Comment by shaggygi** [comment]
That did the trick. Thx!

I guess you could use "as MetroWindow" so it doesn't throw and returns null instead.

MetroWindow parentWindow = Window.GetWindow(this) as MetroWindow;
await parentWindow.ShowMessageAsync("Error", exception.Message);
