### ISSUE TITLE
RightWindowsCommand background

### ISSUE THREAD

**Issue by anthony1969** [MahApps/MahApps.Metro#2555]
Sorry but my issue isn't  for a bug report, but for a suggestion...i define a title template that set a black background, but my rightwindowscommand always have a default title background color...how can i change it to black ? 

note : i have updated to rev. 1.2.4.0

![windowtitle](https://cloud.githubusercontent.com/assets/12933032/16187493/df3a7b80-36d0-11e6-8c28-dea0dae38a44.jpg)

**Comment by punker76** [comment]
@anthony1969 You can set `WindowTitleBrush` and `NonActiveWindowTitleBrush` on your MetroWindow instead setting the Background brush in your TitleTemplate.

**Comment by anthony1969** [comment]
Clear and simple.....thank's
