### ISSUE TITLE
Add a custom control to mahapps metro form

### ISSUE THREAD

**Issue by Ungihan** [MahApps/MahApps.Metro#2559]
Guys i want to add piano control which i made in wpf to mahapps metro form .. can someone please tell me a way to add it

**Comment by AndrzejKl** [comment]
You add it like others controls in standard Window...

**Comment by punker76** [comment]
@Ungihan Is this still an issue? If so, can you post more informations what do you try to do?

**Comment by Ungihan** [comment]
@AndrzejKl Yeah i did that :)
@punker76 No i solved it :) thanks guys
