### ISSUE TITLE
SplitButton and DropDownButton WindowCommand styles

### ISSUE THREAD

**Issue by shawnshaddock** [MahApps/MahApps.Metro#2560]
It would be nice to have styles for the SplitButton and DropDownButton when used in the WindowCommands.

![windowscommands-dropdownbutton](https://cloud.githubusercontent.com/assets/6936864/16255353/26f0f58e-3817-11e6-805c-f12c3e66a222.PNG)

**Comment by djengineerllc** [comment]
I actually need this too.  I was trying to get the style the same as the minimize/maximize/restore buttons for a "menu" I have in the title bar.  So I'd like to add the "Menu" control for a style to have too.

**Comment by shawnshaddock** [comment]
Yeah menu would be great too.

**Comment by p76984275** [comment]
I got the same requirement for the logout and resort to DropDownButton at first time.
But for simplicity's sake and more customization I end up with the ToggleButton and Popup:

![1](https://cloud.githubusercontent.com/assets/14271763/17577561/d85fb85c-5fb1-11e6-8aa0-bfd2fb1ee750.jpg)

![2](https://cloud.githubusercontent.com/assets/14271763/17577560/d85e4dd2-5fb1-11e6-81b2-caf6034401f9.jpg)

The sample code:
```xaml
<mah:MetroWindow.RightWindowCommands>
        <mah:WindowCommands>
            <StackPanel>
                <ToggleButton x:Name="AccountToggle">
                    <ToggleButton.Content>
                        <Path Stretch="Uniform" Height="20" Fill="{StaticResource IconBrush}" Data="{StaticResource Icons.Account.Data}"/>
                    </ToggleButton.Content>
                </ToggleButton>
                <Popup SnapsToDevicePixels="True" RenderOptions.ClearTypeHint="Enabled" TextOptions.TextFormattingMode="Ideal"
                       StaysOpen="False" DataContext="{Binding ElementName=AccountToggle}" Width="160"
                       PlacementTarget="{Binding }" Placement="Bottom" VerticalOffset="0" HorizontalOffset="-40" IsOpen="{Binding IsChecked}">
                    <Border BorderBrush="{StaticResource ContextMenuBorderBrush}" BorderThickness="1"
                            Background="{StaticResource ContextMenuBackgroundBrush}">
                        <StackPanel DataContext="{Binding DataContext, RelativeSource={RelativeSource AncestorType=mah:MetroWindow}}">
                            <TextBlock Margin="15" VerticalAlignment="Center" HorizontalAlignment="Center" FontSize="18" TextTrimming="CharacterEllipsis"
                                       Text="{Binding SignedInAccount.Name}" ToolTip="{Binding SignedInAccount.Name}"/>
                            <Separator Margin="2,0"/>
                            <MenuItem Padding="10" ToolTip="{DynamicResource SignOut}" Header="{DynamicResource SignOut}" FontSize="{StaticResource MenuFontSize}">
                                <MenuItem.Icon>
                                    <Path Stretch="Uniform" Height="16" Margin="12,0,-8,0" Fill="{StaticResource IconBrush}" Data="{StaticResource Icons.Logout.Data}"/>
                                </MenuItem.Icon>
                            </MenuItem>
                        </StackPanel>
                    </Border>
                </Popup>
            </StackPanel>
        </mah:WindowCommands>
    </mah:MetroWindow.RightWindowCommands>
```

**Comment by gmbeas** [comment]
complete solution pls =(

**Comment by esride-mag** [comment]
Could we please have a DropDownButton style for WindowCommands? I would appriciate.

**Comment by Indigo744** [comment]
I have the same issue as @esride-mag, I am sadly not able to set the hover background.
I tried with some `IsMouseOver` custom triggers, but to no avail. If somebody could help...? 

Thanks.

**Comment by timunie** [comment]
Hi @punker76 
I also need a control like this is the next few days. Should I raise a PR for this if I'm done or should I do it in my own Themes? 

Happy coding
Tim
