### ISSUE TITLE
Tabitem reloading issue

### ISSUE THREAD

**Issue by williamwallace** [MahApps/MahApps.Metro#2561]
## Issue description

I am facing a strange behavior with tabitems, so i would like to share it with you and i hope i get some explanations that helps me understand what's happening.

My tabitems are initially empty, the content is set by clicking them. 
when clicking the first time the content is set in no time (0.0000006 ms), the second time it takes about 500 ms, so i started digging and i found out that this instruction takes around 400 ms "tabitem.content = null;"  (this happens only when tabitem.content != null), 
i am using it in order to clear the tabitem content and re-fill it.

Any help will be appreciated, thanks in advance for the attention you will pay to my issue
### Environment
- MahApps.Metro : v0.14
- Windows Server 2012
- Visual Studio 2013
- .NET Framework 4.0

**Comment by punker76** [comment]
@williamwallace Can you try it out with v1.2.4 and/or pre-release v1.3.0.x instead very old v0.14? Thx!

**Comment by williamwallace** [comment]
hi @punker76 thx for the quick reply, I am planning to do it, i've tried it and i saw the major changes that has been added, so it is going to take some time. Do you think it is Mahapps related issue? my tabitems contains expanders (that contains labels, textboxes, combobox etc...) and empty Gridviews(i need only the columns, don't need the data in my case).

**Comment by williamwallace** [comment]
Hi again,
well I tried v1.2.4, the issue persists.cc @punker76

**Comment by punker76** [comment]
@williamwallace Which TabControl (style) do you use? Can you post it? And, if it's possible for you, a short application which shows the issue would help massive.

**Comment by williamwallace** [comment]
Hi @punker76 sorry for the delay,
I am using AnimatedSingleRowTabControl, the tabitems content depends on xml files, i am using expanders as fieldsets (and for fields am using labels, textboxes, comboboxes, buttons etc...) and gridviews to show grid structures, users can add fieldsets, fields and grids as much as they want, The tabitems are created in code behind, their content as well.

**Comment by punker76** [comment]
@williamwallace Can you please create a short app if this still an issue for you. Feel free to reopen it.
