### ISSUE TITLE
Feature-Request

### ISSUE THREAD

**Issue by MWFIAE** [MahApps/MahApps.Metro#2562]
Is it possible to automatically include an item template for the MetroWindow? 

It takes some time to always create a new WpfWindow, then include the namespace, rename the window, and finally deleting the baseclass from the code behind..

If it's not clear what I'm meaning then look here:
https://msdn.microsoft.com/en-us/library/tsyyf0yh.aspx

I don't know anything about the whole nugget thingy, so I don't know if its even possible to automatically include it, but I think it would be a good enhancement, even if we have to manually copy files :)

**Comment by punker76** [comment]
@MWFIAE This is already available https://github.com/MahApps/MahApps.Metro#visual-studio-templates

**Comment by MWFIAE** [comment]
Ok, this should really be on the quick start guide or in the MetroWindow control page, because it should make working with metro much easier :) 
But thx for helping me out. And shame on me for not rtfm good enough^^
