### ISSUE TITLE
FlatButton brushes are not affected by theming

### ISSUE THREAD

**Issue by waacton** [MahApps/MahApps.Metro#2564]
## Issue

I am unable to modify the FlatButton with light/dark theming.

I have my own _light.xaml_ and _dark.xaml_ files to customise theming, and use the ThemeManager to switch between them.  I've added the following brushes used by _MetroFlatButton_ style to my light/dark.xaml:

- FlatButtonBackgroundBrush
- FlatButtonForegroundBrush
- FlatButtonPressedBackgroundBrush
- FlatButtonPressedForegroundBrush

However, these brushes do not appear to update when the theme changes, and the FlatButton remains the same colour.

My workaround for the moment is to write my own version of MetroFlatButton style, but change the references to the 4 brushes above to brushes that _are_ updated (e.g. GrayBrush1, etc.).

(There is also no obvious theme change to the FlatButton in the demo app.)

--
### Environment

- MahApps.Metro __v1.2.4__
- Windows __7__
- Visual Studio __2014__
- .NET Framework __4.6__

**Comment by punker76** [comment]
@waacton just added the brushes to dark and light and get no issues (I used the actual source)

**BaseDark**
```
    <SolidColorBrush x:Key="FlatButtonBackgroundBrush" Color="Red" options:Freeze="True" />
    <SolidColorBrush x:Key="FlatButtonForegroundBrush" Color="Black" options:Freeze="True" />
    <SolidColorBrush x:Key="FlatButtonPressedBackgroundBrush" Color="DarkRed" options:Freeze="True" />
    <SolidColorBrush x:Key="FlatButtonPressedForegroundBrush" Color="White" options:Freeze="True" />
```

**BaseLight**
```
    <SolidColorBrush x:Key="FlatButtonBackgroundBrush" Color="Green" options:Freeze="True" />
    <SolidColorBrush x:Key="FlatButtonForegroundBrush" Color="White" options:Freeze="True" />
    <SolidColorBrush x:Key="FlatButtonPressedBackgroundBrush" Color="GreenYellow" options:Freeze="True" />
    <SolidColorBrush x:Key="FlatButtonPressedForegroundBrush" Color="Black" options:Freeze="True" />
```

![2016-06-27_16h37_41](https://cloud.githubusercontent.com/assets/658431/16383494/92d7ad66-3c85-11e6-8561-d43b8b14646d.png)
![2016-06-27_16h37_49](https://cloud.githubusercontent.com/assets/658431/16383493/92d15b3c-3c85-11e6-8d1a-1189803e9fdd.png)
![2016-06-27_16h38_00](https://cloud.githubusercontent.com/assets/658431/16383495/92ea7e0a-3c85-11e6-9be2-00aee0a66279.png)
![2016-06-27_16h38_12](https://cloud.githubusercontent.com/assets/658431/16383496/9312066e-3c85-11e6-8213-54d3603552a7.png)

**Comment by waacton** [comment]
I'll investigate a little bit more on my side, maybe whip up a demo app.  Suspected a bug because the other brushes work as expected but I could easily be doing something wrong.

**Comment by waacton** [comment]
Sorry, I think I've misunderstood the issue, and I'm pretty sure it is not MahApps specific.

It turns out: the accent and light/dark resources are used as expected if the key in colors.xaml uses a DynamicResource.  If it is not a DynamicResource, it uses the value in colors.xaml - this is the bit that is confusing me.  Do you know what kind of issue would cause this to happen?  (I've reached the limits of my WPF resource dictionary knowledge...)

**Comment by waacton** [comment]
@punker76 I think I've narrowed down the issue:

I call `ThemeManager.ChangeAppStyle(myWindow, myAccent, myTheme)` to update the brush resources, and `ThemeManager` adds the accent/theme to `myWindow.Resources`.  However, my UserControls also reference `Colors.xaml` (for intellisense), so I think these are using a different instance of the resource dictionary which are not affected by the changes to the window's resources.

My current solution is to pass `ThemeManager` the actual `Colors.xaml` resource dictionary, instead of passing the window.  

This seems to work nicely, except for the `WindowCommand` buttons (while using `CleanWindowStyleKey`) - the base theme brushes for them are only updated if I pass the window (which I now do as well as the `Colors.xaml` resource).

Confusingly, if I try to pass `myWindow.Resources` instead of `myWindow` (which is what it looked like ThemeManager was doing in the end), the window command buttons do not get updated.  Is this expected?

Hope all this makes some kind of sense to you!

**Comment by punker76** [comment]
@waacton There is definitely something wrong with you Color stuff. MahApps needs 2 rules to work correctly with the Colors.

1) Put all resources (inc. the Colors resources) at the App.xaml
2) Or put all resources (inc. Colors res) in every Window resources tag

If you have now your own colors or a complete custom accent and / or theme, so add these via ThemeManager and select it after this step.

If you re-add any Colors resources in an UserControl you break this rules and the ThemeManager could not manage the accent and themes anymore.

**Comment by waacton** [comment]
@punker76 so, referencing Colors resource in a UserControl - to provide VS intellisense - will break accents and themes?  Must be only in Window resources?

**Comment by punker76** [comment]
@waacton Yes, cause you override the top level resources. The ThemeManager put the accent/theme resource keys only in the top level resource dictionary of App.xaml or WindowsXYZ.xaml

**Comment by punker76** [comment]
@waacton By the way, here is a screenshot from the main demo which has also UserControls. The resources all located in the App.xaml

![image](https://cloud.githubusercontent.com/assets/658431/16431513/430a30fe-3d81-11e6-9d35-9b3a3ebf5ef7.png)

**Comment by waacton** [comment]
@punker76 Thanks for clearing that up.  Part of my problem is that my UserControls are in a class library - _separate from the App.xaml_ - and the resources intellisense doesn't seem to be able to handle that :disappointed:  (and my attempts to get intellisense to work have caused these other problems).

As I said, I believe there might be a workaround by giving the ThemeManager a shared instance of just the Colors resource (instead of the window), but probably not something for MahApps to worry about!
