### ISSUE TITLE
Metro Dialogs - always full screen width?

### ISSUE THREAD

**Issue by JohnLeavey** [MahApps/MahApps.Metro#2565]
I'm developing a new app using Mahapps Metro, and one of the frequent comments from users is that the dialog windows are stretched to the full width of the screen. I know this is the "metro" style, but it's getting some resistance from users who are more used to standard windows apps.

I've written a small fix to get around this - an new property on MetroDialogSettings and appropriate changes to the BaseMetroDialog control template, so that dialog windows can either be fully stretched, or centered on the screen. Is this something you would be interested in including in Mahapps.Metro - if so I'll submit my changes as a pull request.

**Comment by punker76** [comment]
@JohnLeavey Hi, do you see the new ones in pre-release? Maybe this is what you need? If not, feel free to create a PR.

- Added new methods ShowModalInputExternal, ShowModalLoginExternal and ShowModalMessageExternal. #2518 (@adeniltonbs)

**Comment by punker76** [comment]
@JohnLeavey Or maybe my side project is a good alternative variant of dialogs https://github.com/punker76/MahApps.Metro.SimpleChildWindow

**Comment by JohnLeavey** [comment]
Hi @punker76 thanks for the quick response.
I'll have a look at your sample child window project, as my fix is working fine for the standard dialog, but has issues with ProgressDialog - something is forcing it to full screen width.

**Comment by pfattisc** [comment]
@JohnLeavey You could also set the BaseMetroDialog's _VerticalAlignment_ and _HorizontalAlignment_ to _Center_

**Comment by WELL-E** [comment]
@pfattisc How to custom BaseMetroDialog's style?

**Comment by pfattisc** [comment]
@WELL-E This should help #2468
