### ISSUE TITLE
How to change the metro dialog style?

### ISSUE THREAD

**Issue by WELL-E** [MahApps/MahApps.Metro#2566]
I get MahApps.Metro from nuget. 

The metro dialog's button is too big, how can i change the metro dialog's button?

--
### Environment

- MahApps.Metro 1.2.4.0
- Windows 7
- Visual Studio 2013
- .NET Framework 4.5

**Comment by Malavos** [comment]
What button are you talking about? Could you provide a screenshot?

Besides helping me understanding the problem, it's good for future reference.
