### ISSUE TITLE
'PART_FloatingMessageContainer' name cannot be found in the name scope of 'System.Windows.Controls.ControlTemplate'.

### ISSUE THREAD

**Issue by tusharjain28** [MahApps/MahApps.Metro#2567]
## What steps will reproduce this issue?
Upgrade from Mahapps 1.0.0.0 to 1.2.4.0

_Write problem description here_
The application was working fine on 1.0.0.0 but started throwing 'PART_FloatingMessageContainer' name cannot be found in the name scope of 'System.Windows.Controls.ControlTemplate'. exception when upgraded to 1.2.4.0
### Expected outcome

_Write expected outcome here_

The application should work fine
[ErrorLogs.txt](https://github.com/MahApps/MahApps.Metro/files/346337/ErrorLogs.txt)

--
### Environment

- MahApps.Metro 1.2.4.0
- Windows Windows 7
- Visual Studio 2012
- .NET Framework 4.5

**Comment by punker76** [comment]
@tusharjain28 Can you find out on which control this happens?

**Comment by tusharjain28** [comment]
It does not come on any specific control, comes as i navigate through my application

**Comment by punker76** [comment]
@tusharjain28 The floating message is only available on ComboBox, PasswordBox, TextBox and NumericUpDown (in v1.2.4). So, do you have some custom styles?

**Comment by tusharjain28** [comment]
Yes we have some custom styles defined for these , for eg.this is one of the style for Combo box

<Style x:Key="TemplateB2ComboBox" BasedOn="{StaticResource MetroComboBox}" TargetType="ComboBox">
        <Setter Property="Controls:ControlsHelper.MouseOverBorderBrush" Value="{StaticResource DarkGrayBrush}" />
        <Setter Property="Controls:ControlsHelper.FocusBorderBrush" Value="{StaticResource DarkGrayBrush}" />
        <Setter Property="Background" Value="{StaticResource LGWhiteBrush}" />
        <Setter Property="BorderThickness" Value="2" />
        <Setter Property="BorderBrush" Value="{StaticResource MediumGrayBrush}" />
        <Setter Property="Foreground" Value="{StaticResource TextGrayBrush}" />
        <Setter Property="Width" Value="225" />
        <Setter Property="Height" Value="38" />
        <Setter Property="FontWeight" Value="SemiBold" />
        <Setter Property="FontSize" Value="16" />
        <Setter Property="Margin" Value="0,5,0,5" />
        <Setter Property="Padding" Value="4,0,4,0" />
        <Setter Property="VerticalContentAlignment" Value="Center" />
        <Setter Property="HorizontalAlignment" Value="Left" />
        <Setter Property="ItemContainerStyle">
            <Setter.Value>
                <Style TargetType="ComboBoxItem">
                    <Setter Property="Background" Value="Transparent" />
                    <Setter Property="BorderThickness" Value="0" />
                    <Setter Property="Foreground" Value="{StaticResource TextGrayBrush}" />
                    <Setter Property="Height" Value="38" />
                    <Setter Property="Margin" Value="0" />
                    <Setter Property="Padding" Value="4,0,4,0" />
                    <Setter Property="Template">
                        <Setter.Value>
                            <ControlTemplate TargetType="ComboBoxItem">
                                <Grid Background="{TemplateBinding Background}" Margin="0,0.5">
                                    <VisualStateManager.VisualStateGroups>
                                        <VisualStateGroup x:Name="CommonStates">
                                            <VisualState x:Name="Normal" />
                                            <VisualState x:Name="MouseOver" />
                                            <VisualState x:Name="Disabled">
                                                <Storyboard>
                                                    <DoubleAnimationUsingKeyFrames Storyboard.TargetProperty="Opacity"
                                                                                   Storyboard.TargetName="contentPresenter">
                                                        <SplineDoubleKeyFrame KeyTime="0" Value=".55" />
                                                    </DoubleAnimationUsingKeyFrames>
                                                </Storyboard>
                                            </VisualState>
                                        </VisualStateGroup>
                                    </VisualStateManager.VisualStateGroups>
                                    <Border x:Name="ItemBackground"
                                            IsHitTestVisible="False"
                                            SnapsToDevicePixels="{TemplateBinding SnapsToDevicePixels}"
                                            BorderThickness="{TemplateBinding BorderThickness}"
                                            BorderBrush="{TemplateBinding BorderBrush}"
                                            Background="{TemplateBinding Background}" />
                                    <ContentPresenter x:Name="contentPresenter"
                                                      TextElement.Foreground="{TemplateBinding Foreground}"
                                                      Margin="{TemplateBinding Padding}"
                                                      VerticalAlignment="{TemplateBinding VerticalContentAlignment}"
                                                      HorizontalAlignment="{TemplateBinding HorizontalContentAlignment}" />
                                </Grid>

                                <ControlTemplate.Triggers>
                                    <Trigger Property="IsSelected" Value="True">
                                        <Setter TargetName="ItemBackground" Property="Background" Value="{DynamicResource LGGreenBrush}" />
                                    </Trigger>
                                    <Trigger Property="IsMouseOver" Value="True">
                                        <Setter TargetName="ItemBackground" Property="Background" Value="{DynamicResource LightGreenBrush}" />
                                    </Trigger>
                                </ControlTemplate.Triggers>
                            </ControlTemplate>
                        </Setter.Value>
                    </Setter>
                </Style>
            </Setter.Value>
        </Setter>
        <Style.Triggers>
            <Trigger Property="IsFocused" Value="True">
                <Setter Property="BorderThickness" Value="3" />
            </Trigger>
            <Trigger Property="IsMouseOver" Value="True">
                <Setter Property="BorderBrush" Value="{StaticResource MediumGrayBrush}" />
            </Trigger>
            <Trigger Property="Validation.HasError" Value="True">
                <Setter Property="BorderThickness" Value="2" />
            </Trigger>
            <Trigger Property="Validation.HasError" Value="True">
                <Setter Property="BorderBrush" Value="{DynamicResource ValidationBrush}" />
            </Trigger>
        </Style.Triggers>
    </Style>

**Comment by tusharjain28** [comment]
missed the top most line

 <Style x:Key="TemplateB2ComboBox" BasedOn="{StaticResource MetroComboBox}" TargetType="ComboBox">

**Comment by punker76** [comment]
@tusharjain28 This style looks ok and should work. Try to clear all bin/obj folders and rebuild the solution again against the v1.2.4

**Comment by tusharjain28** [comment]
Did that but it still fails, This is only one of the styles i posted just to give an example, there are many custom styles we have for ComboBox, PasswordBox, TextBox and NumericUpDown. Can you share any views on possible cause for this exception so that i can look into our code to check if we are doing anything wrong while consuming Mahapps framework. Thanks a lot for your prompt responses.

**Comment by tusharjain28** [comment]
I think i got the code which was causing the issue, if i comment out the below mentioned data triggers the application works fine. Any idea what is wrong with these triggers in 1.2.4 version

                      <DataTrigger Binding="{Binding RelativeSource={RelativeSource Self}, Path=(MahAppsControls:TextBoxHelper.HasText)}"
                                     Value="False">
                            <DataTrigger.EnterActions>
                                <BeginStoryboard Storyboard="{StaticResource HideFloatingMessageStoryboard}"/>
                            </DataTrigger.EnterActions>
                            <DataTrigger.ExitActions>
                                <BeginStoryboard Storyboard="{StaticResource ShowFloatingMessageStoryboard}"/>
                            </DataTrigger.ExitActions>
                        </DataTrigger>
             
                        <DataTrigger Binding="{Binding RelativeSource={RelativeSource Self}, Path=(MahAppsControls:TextBoxHelper.Watermark)}"
                                     Value="">
                            <DataTrigger.EnterActions>
                                <BeginStoryboard Storyboard="{StaticResource HideFloatingMessageStoryboard}"/>
                            </DataTrigger.EnterActions>
                            <DataTrigger.ExitActions>
                                <BeginStoryboard Storyboard="{StaticResource ShowFloatingMessageStoryboard}"/>
                            </DataTrigger.ExitActions>
                        </DataTrigger>
             
                        <DataTrigger Binding="{Binding RelativeSource={RelativeSource Self}, Path=(MahAppsControls:TextBoxHelper.UseFloatingWatermark)}"
                                     Value="False">
                            <DataTrigger.EnterActions>
                                <BeginStoryboard Storyboard="{StaticResource HideFloatingMessageStoryboard}"/>
                            </DataTrigger.EnterActions>
                            <DataTrigger.ExitActions>
                                <BeginStoryboard Storyboard="{StaticResource ShowFloatingMessageStoryboard}"/>
                            </DataTrigger.ExitActions>
                        </DataTrigger>

**Comment by punker76** [comment]
@tusharjain28 I think this happens by inner style changes from 1.0.0 -> 1.2.4 The `FloatingMessageContainer` is now a ContentControl and has the name `PART_FloatingMessageContainer`

So if you have a custom style copied from 1.0.0 you must update this to work correctly with 1.2.4

Why do you need this custom styles? Is it for using different colors? Is it in this case not better for you to create a custom accent/theme?

**Comment by tusharjain28** [comment]
Could you help me out on replacement of this code with the code which is compatible with 1.2.4.0 version, precisely substitution of what HideFloatingMessageStoryboard and ShowFloatingMessageStoryboard were doing in 1.0.0.0. Thanks !

**Comment by tusharjain28** [comment]
One more information required, i am looking for solution to the bug 
"2396 show metro dialog async dialog opened fix #2397" which is targeted in 1.3 release. When do we expect a stable release for 1.3 ?

**Comment by punker76** [comment]
@tusharjain28 

>Could you help me out on replacement of this code with the code which is compatible with 1.2.4.0 version

Yes I can, but I need then your styles. Other way could be to look what are the changes to the original style of 1.0 So, if it's only the brushes and colors you can grab the new styles and replace again the brushes and colors.Another way is to create a custom accent. You don't need to replace the styles if you have it.

**Comment by tusharjain28** [comment]
I fixed it , needed to change a grid to a Content control and name it as PART_FloatingMessage.

Thanks for the help !
