### ISSUE TITLE
Question: Does Mahapps support MVVM?

### ISSUE THREAD

**Issue by sherry-ummen** [MahApps/MahApps.Metro#2571]
I have problem with this following code:
```xml
<controls:MetroWindow x:Class="ServerDbSetup.MainWindow"
                      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                      xmlns:controls="http://metro.mahapps.com/winfx/xaml/controls"
                      xmlns:local="clr-namespace:ServerDbSetup.ViewModel"
                      xmlns:view="clr-namespace:ServerDbSetup.View"
                      Title="MainWindow"
                      Height="350"
                      Width="525">
    <Window.Resources>
        <DataTemplate DataType="{x:Type local:WelcomeViewModel}">
            <view:Welcome />
        </DataTemplate>
        <DataTemplate DataType="{x:Type local:LicenseViewModel}">
            <view:License />
        </DataTemplate>
        <DataTemplate DataType="{x:Type local:UserInputViewModel}">
            <view:UserInput />
        </DataTemplate>
        <DataTemplate DataType="{x:Type local:FinishViewModel}">
            <view:Finish />
        </DataTemplate>
    </Window.Resources>
   <StackPanel>
        <ContentControl Content="{Binding CurrentPageViewModel}" />
   </StackPanel>
</controls:MetroWindow>
```

I get compilation error
`Severity	Code	Description	Project	File	Line	Suppression State
Error		The name "WelcomeViewModel" does not exist in the namespace "clr-namespace:ServerDbSetup.ViewModel".	ServerDbSetup	C:\MyDrive\work\ServerDB\DatabaseInstaller\ServerDbSetup\MainWindow.xaml	11	
`
For some reason it does not find it. When I change to Window and not MetroWindow then it finds it correctly.

Could someone tell me what is wrong here or how to overcome this?
--
### Environment

- MahApps.Metroversion="0.14.0.0" targetFramework="net40"
- Windows 10
- Visual Studio 2015
- .NET Framework 4.0

**Comment by punker76** [comment]
@sherry-ummen Yes, MahApps support MVVM. By the way, you use a very old version of MahApps. Can you please test it again with v1.2.4? Can you post the full stacktrace and the code behind file of the MainWindow?

**Comment by sherry-ummen** [comment]
aaaahhh @punker76 thanks for pointing it out about the old version, after upgrading it now it works. Btw how I got this old version was that I used the Visual Studio templated and then restored the nuget package. Probably that needs an update. Thanks

**Comment by punker76** [comment]
@sherry-ummen Ah, thx for the template note...
