### ISSUE TITLE
Minus icon displays a filled block

### ISSUE THREAD

**Issue by shaggygi** [MahApps/MahApps.Metro#2576]
## What steps will reproduce this issue?
Added the XAML for a Rectangle in a WPF app within Button content.
```Visual="{DynamicResource appbar_minus}"```

_Write problem description here_
It displays a filled squared.

### Expected outcome
It should display a minus icon.

--
### Environment

- MahApps.Metro v1.2.4
- Windows 10
- Visual Studio 2015 Update 3
- .NET Framework 4.6.1

**Comment by punker76** [comment]
@shaggygi Do you use it in the correct way? Here is a sample from the main demo.

```xaml
<Button Width="50"
        Height="50"
        Style="{DynamicResource MetroCircleButtonStyle}">
    <Rectangle Width="20"
               Height="20"
               Fill="{Binding Path=Foreground, RelativeSource={RelativeSource FindAncestor, AncestorType={x:Type Button}}}">
        <Rectangle.OpacityMask>
            <VisualBrush Stretch="Fill" Visual="{DynamicResource appbar_city}" />
        </Rectangle.OpacityMask>
    </Rectangle>
</Button>
```

There are better IconPacks available after v1.3.0 release. I'll update the Icon usage section at mahapps.com...

**Comment by shaggygi** [comment]
Yes, I originally copied the sample into my project.  The appbar_city icon works, but the appbar_minus is a filled block instead of the '-' symbol.

**Comment by thoemmi** [comment]
I guess the `VisualBrush`'s property `Stretch` should be set to `Uniform`. When set to `Fill`, the icon is stretched in both direction independently. For more information, see [the documentation](https://msdn.microsoft.com/en-us/library/system.windows.media.stretch(v=vs.110).aspx).

**Comment by punker76** [comment]
@thoemmi You're right!

```xaml
<ToggleButton Width="50"
                Height="50"
                Style="{DynamicResource MetroCircleToggleButtonStyle}">
    <Rectangle Width="20"
                Height="20"
                Fill="{Binding Path=Foreground, RelativeSource={RelativeSource FindAncestor, AncestorType={x:Type ToggleButton}}}">
        <Rectangle.OpacityMask>
            <VisualBrush Stretch="Uniform" Visual="{DynamicResource appbar_minus}" />
        </Rectangle.OpacityMask>
    </Rectangle>
</ToggleButton>
```

![2016-07-12_22h20_52](https://cloud.githubusercontent.com/assets/658431/16782522/4144f8da-4880-11e6-8c5e-b1805d851895.png)

**Comment by shaggygi** [comment]
I confirmed, as well.  Thanks for the help!
