### ISSUE TITLE
Window Resizing Erroneously Acts Deferred

### ISSUE THREAD

**Issue by AdditionalPylons** [MahApps/MahApps.Metro#2577]
## What steps will reproduce this issue?

Resizing a Metro Window when window is not focused. For example, focus on your desktop, then resize the window.

Gif is [here](http://d.pr/i/19oMl) 
Sorry, couldn't figure out how to embed gif :(

### Expected outcome

The window should Live Resize, but instead remains still until the resize drag is finished.

### Environment

- MahApps.Metro 1.3 commit 1707586aba3db2c13821e8dc4060d9efbea93918
- Windows 10 Latest Stable
- Visual Studio 2015
- .NET Framework 4.5

**Comment by AdditionalPylons** [comment]
Were you able to reproduce this issue? If so, then I'll do some debugging when I get home from work.

**Comment by punker76** [comment]
@AdditionalPylons Yes I can reprocude it. I know what the problem is, so I'm currently try to fix it...

**Comment by AdditionalPylons** [comment]
@punker76 Awesome, let me know if I can help in anyway!
