### ISSUE TITLE
NumericUpDown looks really being in designer, but as expected when running

### ISSUE THREAD

**Issue by shaggygi** [MahApps/MahApps.Metro#2578]
## What steps will reproduce this issue?
Create new MetroWindow and add NumericUpDown in a Grid.

_Write problem description here_
NumericUpDown looks larger in VS designer.

### Expected outcome
Should be normal size in designer mode.

_Write expected outcome here_
Should be normal size in designer mode.

--
### Environment

- MahApps.Metro __v1.3.?__
- Windows __10__
- Visual Studio __2015 Update 3__
- .NET Framework __4.6.1__

**Comment by punker76** [comment]
@shaggygi Is your designer view in the 100% level? Can you provide a screenshot?

**Comment by shaggygi** [comment]
It appears to occur when changing the theme color in the app.xaml file.  It will go back to normal after restarting Visual Studio.  The resize will occur again if you change the theme color.  I tried a couple of tests going from Blue > Pink > Cyan.  

![mahappsnumericupdownchangessize](https://cloud.githubusercontent.com/assets/2956825/16751243/d4e389ac-47a5-11e6-9b83-585ecb293b37.png)

**Comment by punker76** [comment]
@shaggygi This sounds like that VS designer isn't correctly updated while changing a resource dictionary...

**Comment by AndrzejKl** [comment]
it has something to do with styles, check my issue with datepicker: 
https://github.com/MahApps/MahApps.Metro/issues/2558

**Comment by punker76** [comment]
I close this, cause it's a followed issue from this https://github.com/MahApps/MahApps.Metro/issues/2558
