### ISSUE TITLE
SourceMinutes binding Error in TimePicker

### ISSUE THREAD

**Issue by ramazanulucay** [MahApps/MahApps.Metro#2579]
## What steps will reproduce this issue?

If I set SourceMinutes field for TimePicker, throw Exception
### Expected outcome
CourseSource60 method doesn't return Collection.

```
        private static object CoerceSource60(DependencyObject d, object basevalue)
        {
            var list = basevalue as ICollection<int>;
            if (list != null)
            {
                return new Collection<int>(list.Where(i => i >= 0 && i < 60).OrderBy(i => i, new AmPmComparer()).ToList());
            }
             
            return null;
        }
```

--
### Environment

- MahApps.Metro __v1.3.0-ALPHA175__
- Windows __8.1__
- Visual Studio __2015__
- .NET Framework __4.5__

**Comment by punker76** [comment]
@ramazanulucay Thx for reporting! How do you bind to this property? And what do you bind?

**Comment by ramazanulucay** [comment]
I bind for interval every 5 minutes.

**Comment by xxMUROxx** [comment]
@punker76 I will check that

**Comment by xxMUROxx** [comment]
@punker76 Then the question arises: Does it make sense to have following?
~~~
public static readonly IEnumerable<int> IntervalOf5 = Enumerable.Range(0, 12).Select(i => i * 5);
public static readonly IEnumerable<int> IntervalOf15 = Enumerable.Range(0, 4).Select(i => i * 15);
~~~

to allow:

~~~
SourceMinutes="{x:Static Controls:TimePickerBase.IntervalOf15}"
~~~

**Comment by thoemmi** [comment]
You have to add `.ToList()` to 
```
public static readonly IEnumerable<int> IntervalOf5 = Enumerable.Range(0, 12).Select(i => i * 5);
public static readonly IEnumerable<int> IntervalOf15 = Enumerable.Range(0, 4).Select(i => i * 15);
```
Otherwise only the first invocation of the fields actually returns the sequences. Later calls would get an finished sequence.

**Comment by xxMUROxx** [comment]
@thoemmi Thanks.
But should we add this helper-feature?

**Comment by punker76** [comment]
@xxMUROxx I think it's ok. 5, 10, 15 @thoemmi ?

**Comment by thoemmi** [comment]
Fair enough

**Comment by xxMUROxx** [comment]
@thoemmi, @punker76 Done, see PR #2588

**Comment by ramazanulucay** [comment]
Thank you, everything is ok.
