### ISSUE TITLE
No non animated custom dialog possible

### ISSUE THREAD

**Issue by panhans** [MahApps/MahApps.Metro#2582]
## What steps will reproduce this issue?

I use following dialog settings:

```
dialogSettings = new MetroDialogSettings
            {
                AffirmativeButtonText = "OK",
                NegativeButtonText = "Nein",
                FirstAuxiliaryButtonText = "Abbrechen",
                AnimateHide = false,
                AnimateShow = false
            };
```

I let shown up an custom dialog like this:

```
            var dialog = new PrinterDialogView();
 
            var printerDialogViewModel = new PrinterDialogViewModel(instance =>
            {
                this.dialogCoordinator.HideMetroDialogAsync(context, dialog);
            });

            dialog.Content = new PrinterDialogView() { DataContext = printerDialogViewModel };

            return await this.Dispatcher.Invoke(async () =>
            {
                await this.dialogCoordinator.ShowMetroDialogAsync(context, dialog, dialogSettings);

                await dialog.WaitUntilUnloadedAsync();

                return printerDialogViewModel.PrinterDialogResult;
            });
```

### Expected outcome

As you can see I want to shown up a non animated custom dialog. The settings working great with standard dialogs, but not with my custom dialog. It's always animated. In my customdialog I use no extra style. It just inherites from CustomDialog.

--
### Environment

- MahApps.Metro __v1.2.4__
- Windows __10__
- Visual Studio __2015__
- .NET Framework __4.6.1__

**Comment by punker76** [comment]
@panhans This should be already fixed. So please try the pre-release version from NuGet. Thx

**Comment by panhans** [comment]
@punker76 I tried out the pre release. The shown animation is deactivated but the unload animation is still persistent in my case. :\

**Comment by punker76** [comment]
@panhans You must put your custom dialog settings to the hide method too...

```csharp
var printerDialogViewModel = new PrinterDialogViewModel(instance =>
            {
                this.dialogCoordinator.HideMetroDialogAsync(context, dialog, dialogSettings);
            });
```
