### ISSUE TITLE
System.Windows.Interactivity referenced version issue

### ISSUE THREAD

**Issue by SkinnySackboy** [MahApps/MahApps.Metro#2583]
Hi,

I came across this old thread as we are currently facing the same issue:
https://github.com/MahApps/MahApps.Metro/issues/384

The thing is we are already referencing System.Windows.Interactivity in plenty of places, and it feels a bit strange to me to reference MahApps in all packages where we wish to use System.Windows.Interactivity, just to ensure we are using the right version, instead of referencing System.Windows.Interactivity.

Has anyone managed to find an adequate solution to this problem? Is there any plan to ensure MahApps references System.Windows.Interactivity as a dependency (I'm aware this may not be straightforward due to 4/4.5 issues) rather than bundling an assembly which is already itself a seperate, widely used NuGet package?

Thanks!

Mark

**Comment by punker76** [comment]
@SkinnySackboy I don't know what the best way is, but MahApps adds for .Net4 and .Net45 the correct dll. You don't need to add MahApps dll in all your packages where you use the interactivity dll, but you should ensure that you use the correct dlls at your current target framework.

**Comment by xxMUROxx** [comment]
This issue bothered me a while. The reason is that you use 3rd party dlls that request different versions of *System.Windows.Interactivity*. The solution that worked for me is to add following code to *App.config*
to the [assemblyBinding](https://msdn.microsoft.com/en-us/library/twy1dw1e(v=vs.110).aspx) element.

~~~xaml
<dependentAssembly>
    <assemblyIdentity name="System.Windows.Interactivity" 
                      publicKeyToken="31bf3856ad364e35" 
                      culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-4.5.0.0" newVersion="4.5.0.0" />
</dependentAssembly>
~~~
