### ISSUE TITLE
ComboBox UseFloatingWatermark Issue

### ISSUE THREAD

**Issue by oskarkaczmarek** [MahApps/MahApps.Metro#2584]
## What steps will reproduce this issue?

Setting up properties for ComboBox:
```
TextBoxHelper.UseFloatingWatermark="True"
TextBoxHelper.Watermark="some not floating text"
```

While it is not editable. (`IsEditable="False"`)

![description](https://cloud.githubusercontent.com/assets/6690581/16872864/f804faaa-4a8f-11e6-87f5-abd2b1472c07.gif)

### Expected outcome

ComboBox should behave like TextBox in the example shown above, with `IsEnabled="True"`. While it is not editable, after selection was made, watermark should appear in the corner of the Control.

Example from gif:
https://github.com/oskarkaczmarek/MahAppsIssueCB.git
--
### Environment

- MahApps.Metro __v1.2.4__
- Windows __8.1__
- Visual Studio __2015__
- .NET Framework __4.5.2__

**Comment by shawnshaddock** [comment]
Please add the DatePicker as well, it has the same issue.

**Comment by punker76** [comment]
@shawnshaddock DatePicker has this in pre-release.

**Comment by oskarkaczmarek** [comment]
Both works great, thank you.

**Comment by shawnshaddock** [comment]
Awesome can't wait to try it out, thanks!
