### ISSUE TITLE
HotKeyBox gives wrong names to multimedia buttons

### ISSUE THREAD

**Issue by bigworld12** [MahApps/MahApps.Metro#2585]
## What steps will reproduce this issue?

when assigning a multimedia key to the HotKeyBox it will display it with wrong name e.g.
Key.MediaPlayPause > shows like this : http://puu.sh/q3BTW/da94bd8c0d.png
![G Instead of MediaPlayPause](http://puu.sh/q3BTW/da94bd8c0d.png)
### Expected outcome

it should view MediaPlayPause instead of G
## 
### Environment
- MahApps.Metro **v1.3.0-ALPHA176**
- Windows **10**
- Visual Studio **2015**
- .NET Framework **4.5.2**

**Comment by thoemmi** [comment]
I can reproduce the issue. However, I don't know how to fix it at the moment. [`GetKeyNameText`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646300(v=vs.85).aspx) just returns `G` for `MediaPlayPause`. I'll have to investigate further...

**Comment by bigworld12** [comment]
Why not use Key.ToString() instead ?

**Comment by thoemmi** [comment]
Unfortunately, the Windows API can't help. I asked at [StackOverflow](http://stackoverflow.com/q/38584015/4747), and there's no standard way to get the names of special keys such as the media buttons. 😫

**Comment by bigworld12** [comment]
then maybe create a simple dictionary of Key,string for special keys ,and then we can handle localization later ?
