### ISSUE TITLE
LoginDialog/Any Dialog app background

### ISSUE THREAD

**Issue by apresmoi** [MahApps/MahApps.Metro#2586]
Hello!

Sorry in advance.. but I didn't find anywhere how to do this. Im trying to go from here:

![image](https://cloud.githubusercontent.com/assets/11778792/16897869/7d4bbd96-4b96-11e6-9e73-29df5e3f33a7.png)

to here:

![image](https://cloud.githubusercontent.com/assets/11778792/16897875/c28875a2-4b96-11e6-810e-8eb66e1cdce2.png)

I want to change the background of the dialog, not the background of the dialog itself. And, maybe, if there is a way, to also blur the background.

Thanks!

--
### Environment

- MahApps.Metro __v1.3.0__
- Windows __10__
- Visual Studio __2015__
- .NET Framework __4.5__

**Comment by yoker** [comment]
for test, you can add `<SolidColorBrush x:Key="BlackColorBrush" Color="Red" />`  In `app.xaml` file.

**Comment by apresmoi** [comment]
Hello, nope, that didn't work.

**Comment by yoker** [comment]
![20160722084432](https://cloud.githubusercontent.com/assets/444806/17043587/8730803c-4fea-11e6-9d7a-1c03d43d3a65.png)

App.xml in MetraDemo.NET45:
`xaml
<Application x:Class="MetroDemo.App"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:controls="http://metro.mahapps.com/winfx/xaml/controls"
             x:Name="App"
             StartupUri="MainWindow.xaml">

    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Colors.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/Blue.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/BaseLight.xaml" />
            </ResourceDictionary.MergedDictionaries>
            <SolidColorBrush x:Key="BlackColorBrush" Color="Red" />

            <Style x:Key="DescriptionHeaderStyle" TargetType="Label">
                <Setter Property="FontSize" Value="22" />
                <Setter Property="HorizontalAlignment" Value="Center" />
            </Style>

            <Style BasedOn="{StaticResource MetroValidationPopup}" TargetType="{x:Type controls:CustomValidationPopup}">
                <Setter Property="CloseOnMouseLeftButtonDown" Value="False" />
            </Style>
        </ResourceDictionary>
    </Application.Resources>
</Application>
`

**Comment by apresmoi** [comment]
Thanks a lot! That is working.

Do you imagine some way to also blur the background?

**Comment by apresmoi** [comment]
Nevermind find a way:

Example:

`<Button Width="100" Content="Save config">
                            <Button.BitmapEffect>
                                <BlurBitmapEffect></BlurBitmapEffect></Button.BitmapEffect></Button>`

**Comment by HelloKitty** [comment]
@apresmoi It's not obvious if you were able to achieve background blur and/or how. Could you post your results?

**Comment by valentasm1** [comment]
@HelloKitty from windows where you invoke set 
```
OverlayBrush = Brushes.DarkRed;
await this.ShowMetroDialogAsync(dialog, metroDialogSettings);
```
