### ISSUE TITLE
Changing ThumbIndicatorWidth for ToggleSwitch does not work

### ISSUE THREAD

**Issue by olegfeferman** [MahApps/MahApps.Metro#2587]
## What steps will reproduce this issue?

I am overriding ToggleSwitchButtonStyle for a ToggleSwitch like this:
```
<Style x:Key="SmallerMetroToggleSwitchButton" TargetType="{x:Type Controls:ToggleSwitchButton}" BasedOn="{StaticResource MetroToggleSwitchButton}">
  <Setter Property="Width" Value="40" />
  <Setter Property="Height" Value="20" />
  <Setter Property="ThumbIndicatorWidth" Value="4" />
</Style>
```
![demo](https://cloud.githubusercontent.com/assets/4115056/16926448/07812030-4d29-11e6-8f11-9b9d23e70c8d.png)

I see that Width and Height values are applied while thumb indicator width is not (it has default width).

### Expected outcome

Thumb indicator width should be changed

--
### Environment

- MahApps.Metro __v 1.3.0-ALPHA176__
- Windows __7__
- Visual Studio __2015__
- .NET Framework __4.5__

**Comment by olegfeferman** [comment]
Actually it works if I set `ThumbIndicatorWidth` directly in a `ToggleSwitch` e.g. like this: `<ctrl:ToggleSwitch ThumbIndicatorWidth="7" />` so maybe it is not a bug.

**Comment by punker76** [comment]
@olegfeferman Yeah, this is by design, the `ToggleSwitch` use TemplateBinding for this values, so the values from the Style are overriden.
