### ISSUE TITLE
MahApps.Metro 1.3.x is huge, can we split the icons from the dll?

### ISSUE THREAD

**Issue by Lakritzator** [MahApps/MahApps.Metro#2589]
This was my primary comment, which was for "MahApps.Metro.Resources", please read the second...

Just out of curiosity, after installing the "MahApps.Metro.Resources" nuget package, **both** Icons.xaml and IconsNonShared.xaml are active and compiled into the final .exe. This blows the size of a simple application with 2x 1MB. On top of that, I assume that only one of each icon is active...  probably undefine which, is this behaviour known? I can't find much documentation on the IconsNonShared.xaml, besides in #2440 and it's not described somewhere I should manually disable this.

## What steps will reproduce this issue?
Install MahApps.Metro.Resources nuget package 0.6.1, build application

### Expected outcome
After compiling I want to have the icons once, this should increases the .exe size with ~1MB.

--
### Environment

- MahApps.Metro.Resources 0.6.1
- Windows 7
- Visual Studio 2015 Update 3
- .NET Framework 4.6.1

I can live with it, just disabling the one I don't need, but there might be many people who don't notice what happened.

Thanks for the cool product.

**Comment by Lakritzator** [comment]
After spending some time with your product, I noticed that in the pre-release a lot has changed.
I like the way the icons are done, this really solve a lot of issues.

BUT the size of MahApps.Metro.dll went from 919KB to 4691KB, which is extreme especially as most applications only use a few. I was considering this project for the next Greenshot version, but the DLL is about 3x as big as the complete application... which would be no go.

Are there any solutions to the size issue, or any plans to at least split the icon from the main library?

**Comment by punker76** [comment]
@Lakritzator I think no go's are bugs or something else, but yes, the icons will be outsourced https://github.com/MahApps/MahApps.Metro/issues/2580

**Comment by Lakritzator** [comment]
The no-go is not for MahApps, but for the **decision** if I will use MahApps in Greenshot.
It doesn't make MahApps bad, it just wouldn't fit to our requirements by increasing the application size 4x for a UI library.

Thanks for the quick answer, I think I didn't find the ticket as I was looking for the wrong keywords.

Closing this, #2580 covers my question!!!!

Thanks again!

**Comment by Lakritzator** [comment]
I will follow the progress of #2580, as the decision to split doesn't answer how it's split :smile:
