### ISSUE TITLE
Weird MetroProgressBar animation with IsIndeterminate=true

### ISSUE THREAD

**Issue by p76984275** [MahApps/MahApps.Metro#2591]
## What steps will reproduce this issue?

This happens after upgrading from **1.3.0-ALPHA155** to **1.3.0-ALPHA178**

I use the MetroProgressBar in a custom control to make a busy indicator.
It only occurs when the **MetroProgressBar's IsIndeterminate=true** and **Visibility is not Visible** at first.
It is fine if the bar's Visibility is Visible at first.

**The Issue's Sample Code**
https://github.com/p76984275/ProgressBarIssue

**Normal (1.3.0-ALPHA155)**
The animation is normal no matter **at first time** or not.
![1 3 0-alpha155](https://cloud.githubusercontent.com/assets/14271763/17015072/bb52b168-4f5a-11e6-9f9a-6c1c11c73546.gif)

**Weird (1.3.0-ALPHA178)**
When the bar becomes visible **at first time**, the animation starts with a delay and the width is wrong. But after that the animation keeps normal as above. **Only at first time** this issue happens.
![1 3 0-alpha178](https://cloud.githubusercontent.com/assets/14271763/17015073/bb581180-4f5a-11e6-9c6f-b53d553040ff.gif)
### Expected outcome

I found that at first time, [`bar.ActualSize()`](https://github.com/MahApps/MahApps.Metro/blob/develop/MahApps.Metro/Controls/MetroProgressBar.cs#L79) will return 0 with **Weird (1.3.0-ALPHA178)** but the right width with **Normal (1.3.0-ALPHA155)**.

It works as before if changing [`bar.Invoke(resetAction);`](https://github.com/MahApps/MahApps.Metro/blob/develop/MahApps.Metro/Controls/MetroProgressBar.cs#L82) back to `bar.Dispatcher.BeginInvoke(DispatcherPriority.Background, resetAction);`

I'm not sure if there is any concern to use that workaround or maybe there are some mistakes in my custom control. Would you please give me some advice? Many thanks.
.
## 
### Environment
- MahApps.Metro **1.3.0-ALPHA178**
- Windows **7 x64**
- Visual Studio **2015**
- .NET Framework **4.5.2**

**Comment by punker76** [comment]
@p76984275 Thx for your sample, should be work now.

**Comment by h82258652** [comment]
@punker76 
It is still not fixed in 1.3.0.
Here is my code.
![sp161009_104347](https://cloud.githubusercontent.com/assets/5144550/19217432/9b74ee32-8e0d-11e6-8187-301fb0e19376.png)
![sp161009_104401](https://cloud.githubusercontent.com/assets/5144550/19217437/a245f5f8-8e0d-11e6-9471-5e2fa299f8f8.png)
And the result.
![aaa](https://cloud.githubusercontent.com/assets/5144550/19217441/a960b3dc-8e0d-11e6-94e8-34587320374c.gif)
Does any code to solve this problem with next version?

**Comment by h82258652** [comment]
@punker76 still here? Maybe I should open another issue?

**Comment by oliverw** [comment]
Confirmed. Not fixed in 1.4.1

**Comment by punker76** [comment]
@oliverw Got it. Will be fixed in 1.4.2
