### ISSUE TITLE
Style detection always returns null

### ISSUE THREAD

**Issue by panhans** [MahApps/MahApps.Metro#2592]
## What steps will reproduce this issue?

ThemeManager returns null when detect appstyle.

`var detectAppStyle = ThemeManager.DetectAppStyle(Application.Current);`

### Expected outcome

Tuple with AppTheme and Accent

--
### Environment

- MahApps.Metro __v1.3.0-ALPHA178__
- Windows __10__
- Visual Studio __2015__
- .NET Framework __4.6.1__

**Comment by punker76** [comment]
@panhans Where do you specify the MahApps resource dictionaries? Where do you call it?

**Comment by panhans** [comment]
@punker76 

In the StartUp-Method of my App.xaml.cs

`protected override void OnStartup(StartupEventArgs e)
        {
            ThemeManager.AddAccent("MyCustomStyle", new Uri("pack://application:,,,/My.Wpf.Controls;component/Styles/MyCustomStyle.xaml"));

            ThemeManager.ChangeAppStyle(Application.Current,
                                        ThemeManager.GetAccent("MyCustomStyle"),
                                        ThemeManager.GetAppTheme("BaseLight"));

            //var detectAppStyle = ThemeManager.DetectAppStyle(Application.Current);

            base.OnStartup(e);
        }`

The other resources are included in App.xaml like described here: http://mahapps.com/guides/styles.html except the Accents.

In version 1.2.4 it worked well. I can call the DetectAppStyle method immediately after ChangeAppStyle method and it's going to return null.

Greets!

**Comment by punker76** [comment]
@panhans Can you show us your App.xaml? Just a note, it's necessary to declare both, an accent an the theme in App.xaml to make sure that the ThemeManager correctly works.

**Comment by panhans** [comment]
Ofcourse:

`<Application x:Class="MyApp.Metro.App"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:local="clr-namespace:MyApp.Metro"
             xmlns:Converters="http://metro.mahapps.com/winfx/xaml/shared">
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>

                
                <ResourceDictionary Source="/MahApps.Metro;component/Styles/Controls.xaml" />
                <ResourceDictionary Source="/MahApps.Metro;component/Styles/Fonts.xaml" />
                <ResourceDictionary Source="/MahApps.Metro;component/Styles/Colors.xaml" />
                
                
                
                
                
                <ResourceDictionary Source="/MahApps.Metro.Resources;component/Icons.xaml"/>
        </ResourceDictionary>
    </Application.Resources>
</Application>`

**Comment by punker76** [comment]
@panhans Adding all necessary dictionaries is a must have to work correctly with the ThemeManager and MahApps. Hope this is ok for you.
