### ISSUE TITLE
Inconsistent Text Case - MessageDialog Button

### ISSUE THREAD

**Issue by MurariAlex** [MahApps/MahApps.Metro#2593]
## What steps will reproduce this issue?

Just create an MessageDialog with an 'Yes' and 'No' for the Affirmative and Negative button's text's, respectively.

` var result = await Dialog.ShowMessageAsync(this, "title", "Description", MessageDialogStyle.AffirmativeAndNegative,  new MetroDialogSettings { AffirmativeButtonText = "Yes", NegativeButtonText = "No" });`

The No is rendered incorrectly as 'NO', as though it has as a call to 'ToUpper()', thus not respecting the text case.
The Yes is rendered corectly.

My application's default language is pt-BR(Brazilian Portuguese), so the 'Não' (No) is shown as 'NÃO', and 'Sim' (Yes) is shown as 'Sim', making it look like it's an typo because they have inconsistent cases. 

![mdialogerror](https://cloud.githubusercontent.com/assets/11204378/17086720/ee5de74a-51cf-11e6-9355-03ef53b8ccd1.jpg)

### Expected outcome

The button's should respect the text case.

--
### Environment

- MahApps.Metro __v1.3.0-ALPHA-179__
- Windows __10__
- Visual Studio __2015__
- .NET Framework __4.6.1__

**Comment by punker76** [comment]
@MurariAlex Thx for reporting. It's a mistake created by me, but it's already fixed 33dc5ca6f8f07f362314092f12f393870a814dbc and available in next pre-release.
