### ISSUE TITLE
MahApps Datepicker Control allowing special Characters and Alphabets

### ISSUE THREAD

**Issue by akshithrajesh290** [MahApps/MahApps.Metro#2599]
## What steps will reproduce this issue?

MahApps Datepicker Control allowing special Characters and Alphabets  
### Expected outcome

It should not allow special characters and Alphabets other than numbers
## 
### Environment
- MahApps.Metro 2.0
- Windows  7
- Visual Studio  2013
- .NET Framework 4.5

**Comment by xxMUROxx** [comment]
@akshithrajesh290 I think you mean DateTimePicker/TimePicker. This is because also the original DatePicker allows entering any character.
