### ISSUE TITLE
About the time when TemplatePart being instantiated

### ISSUE THREAD

**Issue by Ace8793** [MahApps/MahApps.Metro#2600]
hi  @punker76 
    I love MahApps.Metro very much.
    But In my case , I need the TemplatePart be instantiated when its owner Control being instantiated.Do you konw how to realize it?

**Comment by punker76** [comment]
@Ace8793 In most cases you can do this at the `OnApplyTemplate` method of the owner. Sometimes it's also ok if you do this at the `Loaded` event.
