### ISSUE TITLE
Complex GroupBox header

### ISSUE THREAD

**Issue by PhilPJL** [MahApps/MahApps.Metro#2602]
## What steps will reproduce this issue?

If I create a complex header, say like

                <GroupBox Grid.Row="2">
                    <GroupBox.Header>
                        <StackPanel Orientation="Horizontal">
                            <TextBlock Text="Some text"/>
                            
                        </StackPanel>

Then the header text is proper case and black.  

![capture](https://cloud.githubusercontent.com/assets/271656/17456503/765e1c72-5bd1-11e6-9bda-513a9cb26a2c.PNG)

### Expected outcome

What is the easiest way to have the text rendered in upper case with the correct foreground color?
Note the text is retrieved from resources so is actually Text="{x:Static properties:Resources.SomeText}".

![capture1](https://cloud.githubusercontent.com/assets/271656/17456515/0b5a21cc-5bd2-11e6-83fa-055f82038007.PNG)

--
### Environment

- MahApps.Metro 1.2.4.0
- Windows 10
- Visual Studio 2015
- .NET Framework 4.5

**Comment by punker76** [comment]
@PhilPJL It's better for you tonuse HeaderTemplate

**Comment by PhilPJL** [comment]
Ok thanks.  That's closer, I now get white text, but not upper case.

This is how I currently get resources into upper case.  Seems a bit messy

<Run  Text="{Binding Source={StaticResource ResourceWrapper}, Path=Resources.ParentSpool, Mode=OneWay, Converter={StaticResource ToUpperConverter}}" />

Where I have

....
        <xyz:ResourceWrapper x:Key="ResourceWrapper" />
    </UserControl.Resources>

    /// <summary>
    ///     A wrapper to make some XAML bindings easier
    /// </summary>
    public class ResourceWrapper
    {
        public Resources Resources { get; } = new Resources();

        [SuppressMessage("ReSharper", "UnusedMember.Global")]
        public static CultureInfo CurrentCulture => CultureInfo.CurrentCulture;
    }

**Comment by punker76** [comment]
@PhilPJL Yes I know, if you use the HeaderTemplate then set your text to the Header and use Binding at the template. Then you will get the upper case.

**Comment by PhilPJL** [comment]
@punker76 Any chance of an example?

**Comment by punker76** [comment]
@PhilPJL yes, but later

**Comment by punker76** [comment]
@PhilPJL Her is an example with Header and HeaderTemplate.

```xaml
<GroupBox Header="Some text">
    <GroupBox.HeaderTemplate>
        <DataTemplate>
            <StackPanel Orientation="Horizontal">
                <TextBlock Text="{Binding}" Margin="2" VerticalAlignment="Center" />
                <Button Content="You can click me..." Margin="2" VerticalAlignment="Center" />
            </StackPanel>
        </DataTemplate>
    </GroupBox.HeaderTemplate>
</GroupBox>
```

![2016-08-08_17h31_39](https://cloud.githubusercontent.com/assets/658431/17485550/31ae916a-5d8e-11e6-844f-d0b4d6e7fd7f.png)
