### ISSUE TITLE
IconPack demo

### ISSUE THREAD

**Issue by PhilPJL** [MahApps/MahApps.Metro#2603]
Maybe I'm missing something obvious but where is the IconPack demo I can see at https://github.com/MahApps/MahApps.Metro?

I've cloned the latest source code and run the MetroDemo which gives this, which isn't the same 
![capture](https://cloud.githubusercontent.com/assets/271656/17456555/7104140a-5bd3-11e6-8a80-54689185c3c8.PNG)

and MetroDemo.NET45 just opens https://github.com/MahApps/MahApps.Metro.IconPacks in the browser.

**Comment by punker76** [comment]
@PhilPJL I'm currently working on a new demo
