### ISSUE TITLE
ComboxBox grouping

### ISSUE THREAD

**Issue by PhilPJL** [MahApps/MahApps.Metro#2605]
I don't understand the ComboBox grouping example.  The GroupStyle is bound as

            <TextBlock Text="{Binding Path=Name.Name}" />

But there doesn't seem to be any corresponding property in the Album type. 

I was expecting this to be 

            <TextBlock Text="{Binding Path=Album.Name}" />

but that doesn't work.  

What is Name.Name and why is that working?

Does grouping work in MahApps 1.2.4?

**Comment by punker76** [comment]
@PhilPJL The first 'Name' ist the content/datacontext of the group, in this case an Album. And the second is the 'Name' of the Album. So, yes, grouping works also in 1.2.4
