### ISSUE TITLE
Automatic keyboard focus change to child on ShowMetroDialogAsync

### ISSUE THREAD

**Issue by realies** [MahApps/MahApps.Metro#2606]
If you do a new CustomDialog and use the dialog coordinator to display it, the focus does not change - if you have a shortcut such as Esc for closing the dialog, you need to focus the newly appeared view first. It would make sense for the focus to automatically change to the view from the dialog. I'm currently dealing with this with code-behind code in the view.xaml.cs, which is not ideal.

Parent ViewModel call:

```
    var customDialog = new CustomDialog();
    var vm = new AboutViewModel(instance => dialogCoordinator.HideMetroDialogAsync(this, customDialog));
    customDialog.Content = new AboutView { DataContext = vm };
    await dialogCoordinator.ShowMetroDialogAsync(this, customDialog);
```

Child View constructor:
```
    public partial class AboutView : UserControl
    {
        public AboutView()
        {
            InitializeComponent();
            Focusable = true;
            Loaded += (o, e) => Keyboard.Focus(this);
        }
    }
```

With **FocusVisualStyle="{x:Null}"** in the UserControl properties to avoid dotted lines around TabStop controls.

**Comment by punker76** [comment]
@realies Please test and use the latest pre-release. Thx

**Comment by realies** [comment]
@punker76 I am indeed using MahApps.Metro.1.3.0-ALPHA186 and the issue is present :-)

**Comment by punker76** [comment]
@realies So you can use this extension to see the focus visual

KeyboardNavigationEx.Focus(TheButtonToFocus);
