### ISSUE TITLE
A way of detecting shown dialog instances

### ISSUE THREAD

**Issue by realies** [MahApps/MahApps.Metro#2607]
Using keyboard shortcuts to show metro dialog asynchronously.
Pressing the shortcut again while the dialog is displayed causes it to be overlayed with another instance on top.
Finding it worth having a way of detecting if an instance is present from the dialog coordinator.

**Comment by punker76** [comment]
@realies The `DialogCoordinator` instance has a method to get the current active dialog.

```csharp
public Task<TDialog> GetCurrentDialogAsync<TDialog>(object context) where TDialog : BaseMetroDialog;
```
