### ISSUE TITLE
SliderHelper.EnableMouseWheel is working only once when using TabControl

### ISSUE THREAD

**Issue by Evangelink** [MahApps/MahApps.Metro#2611]
With the last version of MahApps development branch (haven't tried on others), if you use the EnableMouseWheel attached property on the slider the mouse wheel behavior will work while you are on the same page and will stop when you get to another page and get back to the first page.

As a quick repro case, add `Controls:SliderHelper.ChangeValueBy="SmallChange" Controls:SliderHelper.EnableMouseWheel="MouseHover"` to one of the slider of the `SliderProgressExamples.xaml` page. Now if you go to this page and scroll over the slider the value changes properly. Now click on another tab and then get back to this tab page, the mouse wheel scrolling no longer works.

Putting some breakpoints into the code you can clearly see that we get to the Unloaded event (unsubscribe) but never get back to the Loaded event. I am happy to fix this but I don't know what is the good practice around this problem. I normally tend to subscribe directly to the event I am interested in and not through Loaded/Unloaded steps.

**Comment by punker76** [comment]
@Evangelink The UnLoaded event is not necessary in this case. I changed this and use the attached properties in the main demo.
