### ISSUE TITLE
DropDownButton with any drop down content

### ISSUE THREAD

**Issue by shawnshaddock** [MahApps/MahApps.Metro#2612]
It would be nice if there was a DropDownButton that could contain any drop down content instead of being an ItemsControl with a ContextMenu.

An example of one can be seen in Telerik's WPF control library
http://docs.telerik.com/devtools/wpf/controls/radbuttons/features/dropdown-button

The DropDownContent property is of type Object, so any UI element can be added to it.

**Comment by punker76** [comment]
@shawnshaddock This issue should be aalready fixed  with https://github.com/MahApps/MahApps.Metro/pull/2572

**Comment by shawnshaddock** [comment]
@punker76  I was unable to find where this was implemented. Do you happen to have a sample demonstrating how it works? Thanks!

**Comment by punker76** [comment]
@shawnshaddock You can use Items property to add what you want.

```xaml
<Controls:DropDownButton Content="The Content" Orientation="Vertical">
    <Controls:DropDownButton.Items>
        <ListBoxItem Content="A ListBoxItem" />
        <TextBlock Text="A TextBlock" />
    </Controls:DropDownButton.Items>
    <Controls:DropDownButton.Icon>
        <Viewbox Width="32" Height="32" Stretch="Uniform">
            <ContentControl Content="{DynamicResource appbar_journal}" Focusable="False" />
        </Viewbox>
    </Controls:DropDownButton.Icon>
</Controls:DropDownButton>
```

![2016-08-18_10h18_32](https://cloud.githubusercontent.com/assets/658431/17766848/63b2f718-652d-11e6-87c6-332f37b95866.png)

**Comment by shawnshaddock** [comment]
@punker76 That's not quite what I was suggesting. To better illustrate the product I am talking about, consider the FireFox menu button. It is much more then a button with a context menu, the drop down contains rich UI content.
![ff-29-tour-1](https://cloud.githubusercontent.com/assets/6936864/17781893/23ced178-653f-11e6-8127-05ddd1b85ace.png)

**Comment by punker76** [comment]
@shawnshaddock Now I understand what you want. But I think the Firefox custom drop doen button is also not a real drop down with context menu, it's really custom. So I think what you need is more like this one https://github.com/MahApps/MahApps.Metro/pull/1603

**Comment by shawnshaddock** [comment]
@punker76 Yes, it is not a context menu. Telerik has designed their DropDownButton just like this. The drop down part is just a popup, and they provide a DropDownContent property which is of type object and can contain any UI. This would be a great addition to MahApps.Metro, maybe call it DropDownContentButton? I could potentially contribute to the effort of developing this control.

I have had a lot of success developing complex drop down content from a button using this control from Telerik in other projects. I will provide a screenshot of a customer search I implemented using it. The search results grid doesn't display until the drop down button is activated.
![dropdowncontentbutton](https://cloud.githubusercontent.com/assets/6936864/17827308/adcbd772-6648-11e6-9a22-8787971ac486.png)
