### ISSUE TITLE
Localizing the Window button tooltips - how?

### ISSUE THREAD

**Issue by llifon** [MahApps/MahApps.Metro#2613]
## Intention
I need to localize the "minimize", "maximize" and "close" tooltips on the Window.

### Issue

I've attempted to set the ToolTip property for the Window buttons via a Style, but the ToolTip values never change at runtime. Is it possible to localize these ToolTips?

I've tried setting it using the deprecated CloseButtonStyle as described here:

https://github.com/MahApps/MahApps.Metro/issues/1682

... and I've also tried setting the ToolTip using the newer Style implementation as described here:

http://stackoverflow.com/questions/34563155/setting-windowbuttoncommands-styles-in-mahapps-metro

As of yet, none of these values affect the ToolTip.

--
### Environment

- MahApps.Metro __v1.2.4.0__
- Windows __10__
- Visual Studio __2013__
- .NET Framework __4.5__

**Comment by punker76** [comment]
@llifon Normally the tooltips are localized by the OS. But in v1.3.0 (pre-release) you can override the tooltips.

Simply put this in your MetroWindow.

```xaml
<controls:MetroWindow.WindowButtonCommands>
    <controls:WindowButtonCommands Minimize="A custom Tooltip which will be shown on Min button"
                                   Maximize="Maximize the window"
                                   Restore="Restore the window"
                                   Close="Noooo... don't close me!" />
</controls:MetroWindow.WindowButtonCommands>
```

![2016-08-17_11h10_21](https://cloud.githubusercontent.com/assets/658431/17730939/616b0044-646b-11e6-9c2d-484c1a2de933.png)

![2016-08-17_11h10_26](https://cloud.githubusercontent.com/assets/658431/17730942/636112bc-646b-11e6-9eb5-26224320e757.png)

![2016-08-17_11h10_30](https://cloud.githubusercontent.com/assets/658431/17730945/6565f8ac-646b-11e6-8e36-c5ba67d618f6.png)

**Comment by punker76** [comment]
@llifon You can look at this sample how it works https://github.com/punker76/code-samples#mahappsmetro-custom-windowbuttoncommands
