### ISSUE TITLE
metro:PackIconModern

### ISSUE THREAD

**Issue by smygarn** [MahApps/MahApps.Metro#2614]
I've just updated the mahapps metro (1.3.0) and got compile errors.

This is my code for an arrow-button

 `<Button Command="{Binding ExpandCommand}" ToolTip="Expand" Visibility="{Binding ExpandButtonVisibility}" Style="{DynamicResource buttonstyle}">
                    <metro:PackIconModern Width="Auto" Height="Auto" Kind="ArrowExpand" />
                </Button>`

Now, it's given me compile error: metro:PackIconModern was not found.

If I look into the example application, you need waaay to much xaml code to represent a simple button:

`  <Button Width="50"
                        Height="50"
                        Style="{DynamicResource MetroCircleButtonStyle}">
                    <Rectangle Width="20"
                               Height="20"
                               Fill="{Binding Path=Foreground, RelativeSource={RelativeSource FindAncestor, AncestorType={x:Type Button}}}">
                        <Rectangle.OpacityMask>
                            <VisualBrush Stretch="Uniform" Visual="{DynamicResource appbar_city}" />
                        </Rectangle.OpacityMask>
                    </Rectangle>
                </Button>`

Any ideas to simplify the code for this particular xaml-button??

The metro:PackIconModern worked in a previous version of mahapps.

**Comment by punker76** [comment]
@smygarn The IconPacks are now outsourced...

https://github.com/MahApps/MahApps.Metro.IconPacks

Why

https://github.com/MahApps/MahApps.Metro/issues/2580

**Comment by smygarn** [comment]
Understand! Does that mean you can't use the <metro:PackIconModern> class to create styled buttons?

**Comment by punker76** [comment]
@smygarn Yes, you can! It's only in a different package now.
