### ISSUE TITLE
DateTimePicker - Format

### ISSUE THREAD

**Issue by pavelkocich** [MahApps/MahApps.Metro#2622]
It will be great if I can set DateTime format of string shown in DataPickerTextbox.
- MahApps.Metro __v1.3.0-ALPHA189 
- Windows 10
- Visual Studio 2015
- .NET Framework 4.5

**Comment by stanleyipc** [comment]
Can you be more specific?

**Comment by xxMUROxx** [comment]
Set `Culture` property. `DateTimeFormat` property is also not present on DatePicker

**Comment by pavelkocich** [comment]
I can set `Culture` property of course, but it will be great to have more straightforward solution with property e.g. `StringFormat`, like Label control.

`<Label ContentStringFormat="dd.MM.yyyy hh:mm" Content="{Binding MyDateTime}"/>`

`<controls:DateTimePicker StringFormat="dd.MM.yyyy hh:mm" SelectedDate="{Binding MyDateTime}" />`

**Comment by anders9ustafsson** [comment]
Since this feature still is not implemented, are there any quick fixes that I could use instead? For example, I am using `Culture` `sv-SE` which gives me a date-time format `yyyy-MM-dd HH:mm:ss`. However, I don't want to display the seconds. Is there any way I can accomplish this using the `Culture` property only?

**Comment by punker76** [comment]
@anders9ustafsson As a workaround you can override the time pattern with at a custom CultureInfo, cause the DateTimePicker uses this to format the text

```
var dateTimeFormat = string.Intern($"{formatInfo.ShortDatePattern} {formatInfo.LongTimePattern}");
```

e.g.

```
var ci = new CultureInfo("sv-SE");
ci.DateTimeFormat.LongTimePattern = ci.DateTimeFormat.ShortTimePattern;
```

then set this to the `Culture` property of the DateTimePicker.

/cc @xxMUROxx This should be easier to do in future release...

**Comment by anders9ustafsson** [comment]
@punker76 Thanks for the suggestion! I'll try it out.

**Comment by xxMUROxx** [comment]
@punker76 I will provide a PR soon
