### ISSUE TITLE
MahApps.Metro solution does not compile

### ISSUE THREAD

**Issue by bnayak** [MahApps/MahApps.Metro#2623]
## What steps will reproduce this issue?
Download MahApps.Metro-develop and compile in Visual Studio 2013
MahApps.Metro sln does not compile in Visual Studio 2013 and throws errors.

![mahapps metro-compile-error](https://cloud.githubusercontent.com/assets/10992085/17971622/399db93c-6af9-11e6-8e2b-7e19ce77a2b9.png)
Below is the first error observed:
Paket failed with:
Could not download from https://raw.githubusercontent.com/ControlzEx/ControlzEx/72aa238cd565ef63e8d52c29982a587e039d04ec/src/ControlzEx/KeyboardNavigationEx.cs
Message: Invalid URI: The hostname could not be parsed.

### Expected outcome

Build properly and run the MahApps.Metro samples.

### Environment

- MahApps.Metro __v?.?.?__
- Windows _7
- Visual Studio 2013
- .NET Framework 4.5

**Comment by punker76** [comment]
@bnayak Yes that's right. You need minimum VS 2015 Community Edition to compile the source.

https://github.com/MahApps/MahApps.Metro#contributing-to-this-project

You can find an earlier version of the pre-release sample application here

https://github.com/MahApps/MahApps.Metro/releases/tag/1.3.0-alpha164

**Comment by bnayak** [comment]
Thank you
