### ISSUE TITLE
No checkmark visible in checkboxes on Win7 Classic Theme

### ISSUE THREAD

**Issue by Prodigio** [MahApps/MahApps.Metro#2624]
## What steps will reproduce this issue?

Change the theme to Windows Classis on Windows 7 and start a application where you've used MA.M.
### Expected outcome

You cannot see the checkmark in checkboxes and no dots in round checkboxes.

If the boxes are checked but disabled, you can see the checkmark/dot.
## 
### Environment
- MahApps.Metro v1.2.4.0
- Windows 7 with Classic Theme
- Visual Studio 2012
- .NET Framework v4.5.1

**Comment by punker76** [comment]
@Prodigio If this still an issue then reopen it, maybe with a screenshot. thx
