### ISSUE TITLE
MessageDialog text not showing

### ISSUE THREAD

**Issue by BasicsCoding** [MahApps/MahApps.Metro#2626]
### Expected outcome

_The message box would show properly with text_

### Outcome
[See here](http://imgur.com/a/WXYoo)
--
### Environment

- MahApps.Metro __v1.2.4__
- Windows __10 Pro__
- Visual Studio __2015 Professional__
- .NET Framework __4.5__

**Comment by AndrzejKl** [comment]
How do You create MessageDialog?
