### ISSUE TITLE
Inconsistent FloatingWatermark Alignment

### ISSUE THREAD

**Issue by AndrzejKl** [MahApps/MahApps.Metro#2627]
## What steps will reproduce this issue?

Just add TextBox, DatePicker and NumericUpDown to MetroWindow and activate Floating Watermarks
_Write problem description here_
For TextBox Alignment is Left;
For DatePicker is Center;
For NumericUpDown is Right;

![image](https://cloud.githubusercontent.com/assets/19487797/18033563/c1b7edd4-6d28-11e6-8704-252c66fd4ac1.png)
![image](https://cloud.githubusercontent.com/assets/19487797/18033566/cd5f9f10-6d28-11e6-8214-65f7b11badeb.png)
### Expected outcome

Should be the same or should be possible to change it, like: 
**Controls:TextBoxHelper.FloatingWatermarkAlignment="Left, Center, Right"**

**EDIT:**
I found way to align it - it reacts for HorizontalContentAlignment, but DatePicker and TextBox Text also reacts on it. Only it works correctly with NumericUpDown control. It have own property TextAlignment, so I can separately align Text and Watermark.
### Environment
- MahApps.Metro **v1.3.0.ALPHA 190**
- Windows **10**
- Visual Studio **2015**
- .NET Framework **4.5**

**Comment by xxMUROxx** [comment]
I will look into that issue

**Comment by xxMUROxx** [comment]
I checked the issue with the newest sources and the floating watermarks are always aligned to the value set to HorizontalContentAlignment. Is NumericUpDown this value is set by default to Right

**Comment by AndrzejKl** [comment]
@xxMUROxx that's right, see my Edit.
But, don't you think that's better to decide how should be align watermark? In my opinion on DatePicker from my first post Watermark will look better left aligned, but when I set HorizontalContentAlignment to Left, also DatePicker Text will be left Aligned, but Text looks better on center...
It shouldn't be a big problem to Add new feature like in my first post "Expected outcome"...

**Comment by xxMUROxx** [comment]
@punker76
