### ISSUE TITLE
NumericUpDown issue with StringFormat and with TrackMouseWheelWhenMouseOver

### ISSUE THREAD

**Issue by AndrzejKl** [MahApps/MahApps.Metro#2628]
## What steps will reproduce this issue?

``` xaml
<Controls:NumericUpDown Interval="1"
                        HasDecimals="True"
                        StringFormat="0.0 szt"
                        InterceptManualEnter="True"
                        Value="{Binding count, Mode=TwoWay, 
                                               UpdateSourceTrigger=PropertyChanged, 
                                               ValidatesOnDataErrors=True, 
                                               NotifyOnValidationError=True}"
                        Validation.Error="validation_Error"/>
```

``` c#
code behind
private void validation_Error(object sender, System.Windows.Controls.ValidationErrorEventArgs e)
        {
            (this.DataContext as viewmodel).validationError(sender, e);
        }
```

``` c#
viewmodel
public double count { get; set; }  //with INotifyPropertyChanged off course

 public void validationError(object sender, System.Windows.Controls.ValidationErrorEventArgs e)
        {
            if (e.Action == System.Windows.Controls.ValidationErrorEventAction.Added)
                numOfErrors++;
            else if (e.Action == System.Windows.Controls.ValidationErrorEventAction.Removed)
                numOfErrors--;
        }
```
1. Everything is fine when i type numbers with max one decimal (declared in StringFormat). But if I type from keyboard number with more decimals than is declared in StringFormat, Value is changed (with more than one decimal), but StringFormat is not applied. 

![bb](https://cloud.githubusercontent.com/assets/19487797/18044372/d0062248-6dcd-11e6-9eac-a2f1869d4f88.gif)
1. When TrackMouseWheelWhenMouseOver="True" and I use mouse Wheel over control, then Validation.Error is fired up after focus is lost, even when UpdateSourceTrigger is PropertyChanged (numOfErrors != 0 and save button is disabled). Clicking on plus or minus button, then it works fine.

![aa](https://cloud.githubusercontent.com/assets/19487797/18037339/7a706682-6d81-11e6-8023-f08d8376b261.gif)

"dodaj" button IsEnabled only when value is > 0. As You can see validation Error appears (red frame), but button isn't active when I use scroll wheel over not focused control. Buttons works fine. 
### Expected outcome
1. Max decimals digits what I can type, should be connected with StringFormat (0.0 means one decimal) or there should be next property called 'DecimalPlaces' stored how much digits I can type after decimal symbol.
2. Validation.Error should fired every use of mouse wheel.
## 
### Environment
- MahApps.Metro **v1.3.0.ALPHA190**
- Windows **10**
- Visual Studio **2015**
- .NET Framework **4.5**

**Comment by punker76** [comment]
@xxMUROxx Can you look at this?

**Comment by xxMUROxx** [comment]
@punker76 both reported issues are not reproducible. I have validated with current `dev-branch`
![numericupdown](https://cloud.githubusercontent.com/assets/4341039/21092276/a9c75dc4-c04b-11e6-8cd1-75758c463deb.gif)
![numericupdown-1](https://cloud.githubusercontent.com/assets/4341039/21092275/a9c41fce-c04b-11e6-8474-a940fd6cdfd5.gif)

**Comment by punker76** [comment]
@AndrzejKl If this is still an issue for you, then please create a short app which demonstrates this one. thx.
