### ISSUE TITLE
Should ProgressDialogController have an interface?

### ISSUE THREAD

**Issue by Bemjamin** [MahApps/MahApps.Metro#2630]
I am writing some tests for my ViewModel and I need to keep the instance of ProgressDialogController to change the messages based on some async tasks but I am not capable of mock the class because its constructor is internal. 

There is another way to do this?

**Comment by Bemjamin** [comment]
I just wrote a service to encapsulate the show/close progress methods.

**Comment by thoemmi** [comment]
The `ProgressDialogController` is only for convenience, just like the other default dialogs like Login, Input etc.
If your requirements include special handling, I recommend to replicate the default dialogs from MahApps.Metro and change them to match your demands.
