### ISSUE TITLE
Application flickers when scrolling up or down on a touch screen

### ISSUE THREAD

**Issue by astavria4** [MahApps/MahApps.Metro#2631]
with a touchscreen laptop or tablet, if you go to a view that has a scrollbar, and you scroll as high or low as you can, the app is being dragged up or down. If you put the app into its max screen, and you go to a view with a scrollbar and scroll with your finger and go as high and low as you can, then the app flickers.

I have a metrowindow and within it, I have a content control that displays different usercontrols. I am using PRISM and entity framework. 

I am wondering if you have ever encountered a bug like this before? 

### Environment

- MahApps.Metro v 1.2.4.0
- Windows 8.1
- Visual Studio 2013
- .NET Framework 4.5

**Comment by Evangelink** [comment]
@astavria4 If you try to run the demo app or try to create a dumb Wpf project with only a listbox do you end up with the same issue?
