### ISSUE TITLE
RangeSlider Inaccuracy compared to a Slider

### ISSUE THREAD

**Issue by bigworld12** [MahApps/MahApps.Metro#2633]
## What steps will reproduce this issue?

making a simple comparison

```
<StackPanel VerticalAlignment="Center">
        <Slider Value="50" Minimum="0" Maximum="100" Margin="5"/>
        <controls:RangeSlider LowerValue="0" UpperValue="50" Minimum="0" Maximum="100" Margin="5"/>
    </StackPanel>
```

gives this result 
![Problem 1](http://i.imgur.com/GiKzP4b.png)
then when setting 
`MinRangeWidth="0"` for the `RangeSlider` fixes it a little bit
![Problem 2](http://i.imgur.com/xOkITl1.png)

and to get the perfect match the `UpperValue` must be different "With UpperValue=50,Slider Value should be 52"
and it varies from range to range
so this code 

```
<StackPanel VerticalAlignment="Center">
        <Slider Value="50" Minimum="0" Maximum="100" Margin="5"/>
        <controls:RangeSlider MinRangeWidth="0" LowerValue="0" UpperValue="48" Minimum="0" Maximum="100" Margin="5"/>
    </StackPanel>
```

gives the Expected outcome
![Fix](http://i.imgur.com/lOAEaQR.png)

Edit 1:
I noticed also that the left thumb doesn't go all the way to the left
it exactly leaves 0.6593406593406593 % of the total control width from the left
## 
### Environment
- MahApps.Metro **v1.3.0-ALPHA176**
- Windows **8.1**
- Visual Studio **2015**
- .NET Framework **4.5**

**Comment by QuantumDeveloper** [comment]
@punker76 Do you really agree this is an issue regarding inaccurancy?
In my opinion RangeSlider control phisycally could not match Slider. Correct me if I am wrong.

**Comment by bigworld12** [comment]
@QuantumDeveloper well, the `MinRangeWidth` property controlling the accuracy of the thumb is a bug anyway

**Comment by QuantumDeveloper** [comment]
Its not a bug. Why do you think `MinRangeWidth` property controlling accuracy? Accuracy in range slider is quite good, because its calculating according to formula: `(free_space_from_left+free_space_from_right)/range`. So, doing that we know how much value corresponds to each **free** pixel. `MinRangeWidth` is not accessible for usage. Its just for convenience of moving the whole range at one time. In simple slider using the same formula, I sure. The only difference here that Slider has only 1 Thumb, and RangeSlider - 2. Second Thumb also has its own width, which eats the whole width and **free** width for calculating becomes a little bit smaller. Thats why you see that `Value - 2` is at the same position as in Slider. I am sure that RangeSlider and Slider just could not position its Tumbs at the same place on the monitor just because of difference in their "nature".

**Comment by bigworld12** [comment]
i believe this shouldn't be the default behavior, and for a music player for instance, accuracy is important for the user

**Comment by QuantumDeveloper** [comment]
Once again - its not an accuracy issue - its just visual presentation. Why do you actually think that RangleSlider and Slider visual position of Thumbs should be the same? Its different controls and works a bit differently.

**Comment by AndrzejKl** [comment]
Personally I must to agree with @bigworld12 .
Half should be half, if I set:
````xaml
<controls:RangeSlider LowerValue="0" UpperValue="50" Minimum="0" Maximum="100" Margin="5"/>
````
then both parts should be equal, but they aren't.
![image](https://cloud.githubusercontent.com/assets/19487797/18215454/a082a67c-7151-11e6-87dd-74d988900b33.png)

Both red line are the same length...

**Comment by QuantumDeveloper** [comment]
You forgot to set ``MinRangeWidth="0"``
![screen](https://cloud.githubusercontent.com/assets/6085009/18218421/4c869ece-716b-11e6-8433-4a70b89e1343.png)
As you can see both parts of the RangeSlider is completely equal to each other. They should not be equal to slider. Please, dont compare them.

**Comment by bigworld12** [comment]
@QuantumDeveloper did you see my edit ?

**Comment by punker76** [comment]
@bigworld12 @AndrzejKl I'm with @QuantumDeveloper and would say that this is not an issue with the UI or an inaccuracy. The `RangeSlider` works different to a Slider cause it has a Range which must be displayed and calculated. So if I set the `LowerValue` and `UpperValue` to the same value it can not be displayed like a normal Slider.

![2018-01-22_23h57_52](https://user-images.githubusercontent.com/658431/35249039-bb672c24-ffd0-11e7-9f1f-a87481fd57bc.png)

![2018-01-22_23h58_12](https://user-images.githubusercontent.com/658431/35249040-bb8729a2-ffd0-11e7-90f8-5a664dac367f.png)

![2018-01-22_23h58_24](https://user-images.githubusercontent.com/658431/35249041-bba278ce-ffd0-11e7-99ac-484119fb46c7.png)

The sample which I used for the screenshots

```xaml
<StackPanel Margin="20" VerticalAlignment="Center">
    <Slider IsSelectionRangeEnabled="True"
            Maximum="100"
            Minimum="0"
            SelectionEnd="60"
            SelectionStart="30"
            TickFrequency="10"
            TickPlacement="TopLeft"
            Value="50" />
    <Controls:RangeSlider LowerValue="50"
                            Maximum="100"
                            MinRangeWidth="0"
                            Minimum="0"
                            TickFrequency="10"
                            TickPlacement="BottomRight"
                            UpperValue="50" />
</StackPanel>
```
