### ISSUE TITLE
Showing any Window before Main Window causes Left and Right window commands not work properly.

### ISSUE THREAD

**Issue by amithasan** [MahApps/MahApps.Metro#2635]
I have added a splash screen window to a mahapps metro application with a progress ring. The splash screen is shown and closed before the main window is shown using the following code.

```
protected async override void OnStartup(System.Windows.StartupEventArgs e)
    {
        //Other code

        MainWindow mainWindow = new MainWindow();

        SplashScreen sp = new SplashScreen();
        sp.Show();
        await Task.Delay(3000);
        sp.Close();

        mainWindow.Show();

        //Other code
    }
```

Splash screen is shown correctly but the main window’s RightWindowCommands and LeftWindowCommands are not working correctly. Maybe styles and data binding of WindowCommands are not working. For example, a button icon on the left is not visible and a button icon on right is visible but data binding is not working.

However, If the main window is showed first then everything works as expected.

### Environment

- MahApps.Metro __v1.2.4__
- Windows __10__
- Visual Studio __2015__
- .NET Framework __4.5__

**Comment by punker76** [comment]
@amithasan Can you create a short sample for this issue? Thx. By the way, I don't think it's MahApps related.

**Comment by amithasan** [comment]
[SplashScreen.zip](https://github.com/MahApps/MahApps.Metro/files/479235/SplashScreen.zip)

This is a short sample for the issue. Thank you.

**Comment by punker76** [comment]
@amithasan Hi, I fixed the BindingExpression error in pre-release 1.3.0.197. Here is your sample with some minor changes from me.

[SplashScreenForLatestPreRelease.zip](https://github.com/MahApps/MahApps.Metro/files/479569/SplashScreenForLatestPreRelease.zip)

**Comment by amithasan** [comment]
Thank you very much.
