### ISSUE TITLE
Setting Focusable=True on NumericUpDownControl breaks Tab Navigation (Shift + Tab)

### ISSUE THREAD

**Issue by pfattisc** [MahApps/MahApps.Metro#2637]
## What steps will reproduce this issue?
I have a input mask with several Textboxes and a NumericUpDownControl. In the UI I use Labels with access keys ([_ALT + Mnemonic_]) to jump to an associated control defined in Label's Target property. To make this work the control defined in Label's Target property need to be Focusable.
After I set Focusable=True on the NumericUpDownControl moving the focus with [_TAB_] key works but when I hit [_SHIFT + TAB_] on the focused NumericUpDownControl the focus remains on the control.
This is also reproducable with the 1.3.0-alpha164.
### Expected outcome
[_TAB_] and [_SHIFT + TAB_] should work as with Focusable=False

--
### Environment

- MahApps.Metro __v1.2.4__
- Windows __7 x64__
- Visual Studio __2013__
- .NET Framework __4.5.1__

**Comment by punker76** [comment]
@pfattisc Please use the latest pre-release (1.3.0-ALPHA192) cause this should be already fixed.

**Comment by pfattisc** [comment]
@punker76 You're right it is fixed in 1.3.0-ALPHA192
