### ISSUE TITLE
Ignore Swipes

### ISSUE THREAD

**Issue by sleman** [MahApps/MahApps.Metro#2638]
I am running a kiosk application which should be in full screen in Windows 10 and it should ignore edge swipes so users don't exit the app.

I set IgnoreTaskbarOnMaximize = True, WindowState.Maximized, WindowStyle.None ReizeMode.NoResize

This puts main window in full screen and hides the taskbar which is great.

Any idea how to ignore swipes from edge of screen? 

--
### Environment

- MahApps.Metro v1.3
- Windows 10.0.14393
- .NET Framework 4.6.1

**Comment by punker76** [comment]
@sleman Do you mean swipe with touch device? Have you tried to set TopMost property to true?

**Comment by sleman** [comment]
Yeah, no difference.

**Comment by punker76** [comment]
@sleman But it sounds like that this feature is a OS feature... Maybe it's not possibel to prevent this by an app.
