### ISSUE TITLE
Style SolidColorBrush create an System.InvalidOperationException

### ISSUE THREAD

**Issue by AurelioRighetti** [MahApps/MahApps.Metro#2639]
[T416066.zip](https://github.com/MahApps/MahApps.Metro/files/459719/T416066.zip)
## What steps will reproduce this issue?

Then open a View in a separate thread:

void Test()
        {
            StartInSeparateThread();
        }

        static void StartInSeparateThread() {
            var InternalThread = new Thread(InternalThreadEntryPoint);
            InternalThread.SetApartmentState(ApartmentState.STA);
            InternalThread.Start();
        }

        static void InternalThreadEntryPoint() {
            var window = new Window { Width = 200, Height = 200 };
            window.Content = CreateContent();
            window.ShowDialog();
        }

        static object CreateContent() {
            return new ProgressBar();
        }

this style resource:

<SolidColorBrush x:Key="{x:Static SystemColors.WindowBrushKey}" Color="{DynamicResource WhiteColor}" />
<SolidColorBrush x:Key="{x:Static SystemColors.ControlTextBrushKey}" Color="{DynamicResource BlackColor}" />

create an System.InvalidOperationException

if replace with:
<SolidColorBrush x:Key="{x:Static SystemColors.WindowBrushKey}" Color="White" />
            <SolidColorBrush x:Key="{x:Static SystemColors.ControlTextBrushKey}" Color="Black" />

it's work OK

- MahApps.Metro __v1.3.0.193__
- Windows __10__
- Visual Studio __2015__
- .NET Framework __4.5__

Many thanks
PS) I have attached a sample to reproduce the exception. In the App.xaml i have insert the fix 
Aurelio

**Comment by punker76** [comment]
@AurelioRighetti You must add all MahApps resource dictionaries to thos window if it should work in a different thread.

**Comment by punker76** [comment]
@AurelioRighetti I wrote something about this here http://jkarger.de/archive/2016/01/22/create-new-mahapps-window-in-separate-thread/

**Comment by AurelioRighetti** [comment]
Hi punker76
Thanks for you explanation.
For now i have apply the fix in the app.

Aurelio
