### ISSUE TITLE
result from customdialog

### ISSUE THREAD

**Issue by MannusEtten** [MahApps/MahApps.Metro#2640]
I followed the example of the custom dialog from viewmodel

i get it working, the datacontext of the viewmodel is set correctly
how do i know get the information from the fields which are part of the viewmodel after the action dialogCoordinator.HideMetroDialogAsync has been called?

**Comment by thoemmi** [comment]
I'm not sure I get your question. After calling `HideMetroDialogAsync` your viewmodel should have all the information as required.
