### ISSUE TITLE
reuse tabcontrol after switch

### ISSUE THREAD

**Issue by hackereg35** [MahApps/MahApps.Metro#2647]
can i reuse the tabcontrol, i mean without recalling the "loaded" event, like if i have a registration form on a tab and to complete the registration i have to get a key from another tab , so i want to go to the other tab and then come back without starting over, doing this
`<Controls:MetroAnimatedTabControl>
            <TabItem Header="MainTab">
                <local:MainPage/>
            </TabItem
<Controls:MetroAnimatedTabControl>`
create a new instance of the usercontrol every time i go to the tab

**Comment by punker76** [comment]
@hackereg35 You can use the `TabControlEx` from [ControlzEx](https://github.com/ControlzEx/ControlzEx#tabcontrolex). Use this togeter with the `Controls.AnimatedTabControl.xaml` to get the MahApps style, e.g.

```xaml
<Grid>
  <Grid.Resources>
    <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.AnimatedTabControl.xaml" />
  </Grid.Resources>
  <controlz:TabControlEx Style="{StaticResource {x:Type TabControl}}">
      <TabItem Header="Lorem">
      </TabItem>
      <TabItem Header="ipsum">
      </TabItem>
  </controlz:TabControlEx>
</Grid>
```

**Comment by punker76** [comment]
@hackereg35 not testes :shipit:

**Comment by hackereg35** [comment]
i'll test it right now, but thank you any way

**Comment by hackereg35** [comment]
it didn't work,
![wpf-tab](https://cloud.githubusercontent.com/assets/11955541/18488613/76ae15dc-79fa-11e6-903a-1fc6941d633a.PNG)
the "Console.WriteLine" is the usercontrol_loaded event

**Comment by punker76** [comment]
@hackereg35 Great, thx, you found a bug 👍  I will fix this!

**Comment by punker76** [comment]
I move this to https://github.com/ControlzEx/ControlzEx/issues/18
