### ISSUE TITLE
CenterWindowCommand

### ISSUE THREAD

**Issue by MJomaa** [MahApps/MahApps.Metro#2648]
Hi,

is there something that simulates a "CenterWindowCommand"?
I see there is a LeftWindowCommand and a RightWindowCommand, but I didn't find an option to center a command in the titlebar.

Best Regards,
MJomaa

**Comment by punker76** [comment]
@MJomaa Hi, there is no such command thing, but you can use the `TitleTemplate` to make your own title.  If you want to put some stuff in there then you should use the latest pre-release.

e.g.

```xaml
<Controls:MetroWindow.TitleTemplate>
    <DataTemplate>
        <StackPanel Orientation="Horizontal" HorizontalAlignment="Right">
            <TextBlock Margin="0 -1 8 0"
                       VerticalAlignment="Center"
                       FontFamily="{DynamicResource HeaderFontFamily}"
                       FontSize="{DynamicResource WindowTitleFontSize}"
                       Text="{TemplateBinding Content}"
                       TextTrimming="CharacterEllipsis" />
            <Controls:WindowCommands>
                <Button Content="Cool" />
                <Button Content="Really!" />
            </Controls:WindowCommands>
            <Button Content="Click Me..." Margin="1" Click="ClickMeOnClick" />
        </StackPanel>
    </DataTemplate>
</Controls:MetroWindow.TitleTemplate>
```

![2016-09-14_09h36_52](https://cloud.githubusercontent.com/assets/658431/18503776/0ea3e362-7a5f-11e6-97a9-d51d1baf5088.png)

**Comment by punker76** [comment]
@MJomaa Do you need more help?

**Comment by MJomaa** [comment]
@punker76 Sorry for the late response. Nope, thanks! It worked perfectly. Danke nochmals!
