### ISSUE TITLE
NumericUpDown won't focus

### ISSUE THREAD

**Issue by shaggygi** [MahApps/MahApps.Metro#2651]
## What steps will reproduce this issue?
Added NumericUpDown control to UI along with required XAML references in WPF app.
In C# code, call a Focus() Method.  e.g. Quantity.Focus();

Cursor does not move to the NumericUpDown control.

### Expected outcome
Cursor should move to the NumericUpDown control.

### Environment

- MahApps.Metro __v1.3 and alpha
- Windows Windows 7 64bit
- Visual Studio VS2015 with Update 3
- .NET Framework 4.6.1

**Comment by punker76** [comment]
@shaggygi Which alpha version do you tested?

**Comment by shaggygi** [comment]
Just realized the Alpha 1.3.0-ALPHA195 works.  I thought I updated the NuGet before testing that version.  I'll close out  issue.

Speaking of Alpha, when will next stable release be available with these fixes?

Thx

**Comment by kyelisavenko** [comment]
Current bug is still reproduced at version 1.6.0
Environment
Windows Windows 10 64bit
Visual Studio VS2017
.NET Framework 4.6.1
