### ISSUE TITLE
Flyout problem with ActualWidth

### ISSUE THREAD

**Issue by osnoser1** [MahApps/MahApps.Metro#2656]
## What steps will reproduce this issue?

_Window maximixe and open flyout_

### Expected outcome

_Correct width_

--
### Environment

- MahApps.Metro __v1.2.4, v1.3.0-ALPHA189__
- Windows __7, 10__
- Visual Studio __2015__
- .NET Framework __4.5.1__

### Image

![captura de pantalla 2016-09-17 11 48 23](https://cloud.githubusercontent.com/assets/1179744/18609348/eb45d2f6-7ccd-11e6-89be-af46c3bdb90f.png)

**Comment by punker76** [comment]
@osnoser1 I've updated the demo for this, cause we should use the `FlyoutsControl` for the binding. The `ActualWidth` of the Window gives us a wrong value if it's maximized, maybe another WPF bug...

```xaml
<Controls:Flyout x:Name="settingsFlyout"
                 Controls:ControlsHelper.ContentCharacterCasing="Upper"
                 Width="{Binding RelativeSource={RelativeSource FindAncestor, AncestorType=Controls:FlyoutsControl}, Path=ActualWidth}"
                 Margin="200 0 0 0"
                 AreAnimationsEnabled="False"
                 Header="Settings"
                 Position="Right">
</Controls:Flyout>
```
