### ISSUE TITLE
[Question] Dialog auto close after certain time

### ISSUE THREAD

**Issue by AndrzejKl** [MahApps/MahApps.Metro#2658]
What's is the simplest solution to show dialog which close itself after let's say 5 seconds if user will not click "OK" button? I know that I can use Task.Delay(5000),  but it will better look when it will show counter (seconds remaining)...

**Comment by mvschmaedeck1** [comment]
I've been through this a while ago. I was able to find a solution, but it isn't as simple as I would like it to be.

I created a class with some methods that I find usefull, like:

ShowMessage**Async**(string title, string message, MetroWindow parent, int **timeout**, MessageDialogStyle style, MetroDialogSettings settings, MessageDialogResult **defaultResult**)
 

ShowMessage(string title, string message, MetroWindow parent, **int timeout**, MessageDialogStyle style, MetroDialogSettings settings, MessageDialogResult **defaultResult**)


Here's the class, in case you're interested: [http://pastebin.com/5Cz4pNvD](Pastebin)

**Comment by AndrzejKl** [comment]
@mvschmaedeck1 Thanks, but I'm looking for built ed in functionality.

I've figure it out, that I can use ProgressDialog, works really fine, but I want to use counter in button (as You), so question is, how I can change button text in a loop?

````c#
var mySetting = new MetroDialogSettings()                    
 {
   ColorScheme = MetroDialogOptions.ColorScheme,
   NegativeButtonText = "Ok",
   AnimateShow = false,
   AnimateHide = false
  };

var controller = await this.ShowProgressAsync("Deleted", "", true, mySetting);

     controller.Maximum = 5;
     double i = 5;
           
     while (i > 0.5)
      {
         i -= 0.5;
         if (i % 1 == 0)
         {
           mySetting.NegativeButtonText = string.Format("Ok({0})", i);  //This doesn't work

           controller.SetMessage("Auto close in: " + i);
           controller.SetProgress(i);
           }
           if (controller.IsCanceled)
               break; //canceled progressdialog auto closes.

          await Task.Delay(500);
         }
   await controller.CloseAsync();
