### ISSUE TITLE
Flyout close button location on full screen (Maximize)

### ISSUE THREAD

**Issue by TOKN2** [MahApps/MahApps.Metro#2661]
## Flyout close button location on full screen (maximize).

_When Flyout in window is set to full screen mode (maximized) close button location is too close to left screen edge._

### Expected outcome

_Close button should be with same width from left sceen edge in maximize mode as when windows is not maximized_

Not Maximized:
![notmaximize2](https://cloud.githubusercontent.com/assets/12743741/18737245/c0a0bbec-8097-11e6-882b-3782433a81cb.png)

Maximized:
![maximize](https://cloud.githubusercontent.com/assets/12743741/18737226/90e0c4ec-8097-11e6-8b02-210c56892e9e.png)

It can be seen in Mahapps.Metro - Demo application: Flyouts > Show 2 > Maximize

--
### Environment

- MahApps.Metro __v1.2.4__

Thanks! 👍

**Comment by punker76** [comment]
@TOKN2 Thx for reporting. It's already fixed https://github.com/MahApps/MahApps.Metro/commit/2396569e189adb94d48344f19d8065f6735b81b6
