### ISSUE TITLE
MetroWindow Closing Event Internal Error

### ISSUE THREAD

**Issue by AndrzejKl** [MahApps/MahApps.Metro#2664]
## What steps will reproduce this issue?
Add to MetroWindow Closing Event and there put this:

````csharp
 private void MetroWindow_Closing(object sender, System.ComponentModel.CancelEventArgs e)
        {
            var dc = DataContext;
        }
````
it will produce Internal error:
![image](https://cloud.githubusercontent.com/assets/19487797/18756204/5274d3d0-80ef-11e6-9398-41e1ee082962.png)

In normal Window it works as it should (without error)

--
### Environment

- MahApps.Metro __v?.?.?Aplha 199__
- Windows __10__
- Visual Studio __2015__
- .NET Framework __4.5__

**Comment by punker76** [comment]
@AndrzejKl Can you add a full stackstrace? At which line comes the exception?

**Comment by AndrzejKl** [comment]
from output window? nothing - output window is empty.
Exception is throwing immediately after clicking close button, brake point  on top of event isn't fired.

**Comment by AndrzejKl** [comment]
@punker76  look at this:
![bb](https://cloud.githubusercontent.com/assets/19487797/18757278/8268e2f8-80f3-11e6-91fc-b75d006b4304.gif)

**Comment by punker76** [comment]
@AndrzejKl Can you provide your app? and can you please switch your os to english, or your installed .net language runtime? Thx

**Comment by AndrzejKl** [comment]
@punker76 
Sure it's just clean playground project. If I change MetroWindow to normal Window - it works fine
<a href=http://www.filedropper.com/wpftest><img src=http://www.filedropper.com/download_button.png width=127 height=145 border=0/></a><br />

**Comment by punker76** [comment]
@AndrzejKl Thx for the sample. First you use MahApps.Metro.1.3.0-ALPHA166 and not 199. Second, it runs on my machine™ without any error. It feels like there is something wrong with your vs or debugging sessions. Which vs version do you have?

Happens this crash also without the vs debugger?

**Comment by AndrzejKl** [comment]
@punker76 Thx, I was afraid it... 
On this playground app It was 166, but on my main project I have 199.
No, just debugging shows such a things (vs community 2015), 

I've reinstall visual studio, now works fine, but for me it's so unstable like hell...

Again thanks @punker76
