### ISSUE TITLE
Setting TitleCharacterCasing in App.xaml is not working

### ISSUE THREAD

**Issue by p76984275** [MahApps/MahApps.Metro#2665]
## What steps will reproduce this issue?

To unify all character casing style in entire application, we usually put those styles in App.xaml.
For example, set button's character casing from Upper to Normal as default:
```xaml
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                ...MahApps stuff here...
            </ResourceDictionary.MergedDictionaries>

            <Style TargetType="Button" BasedOn="{StaticResource MetroButton}">
                <Setter Property="controls:ControlsHelper.ContentCharacterCasing"  Value="Normal"/>
            </Style>

        </ResourceDictionary>
    </Application.Resources>
```

But this is not working for MetroWindow's TitleCharacterCasing:
```xaml
    <Style TargetType="controls:MetroWindow" BasedOn="{StaticResource {x:Type controls:MetroWindow}}">
        <Setter Property="TitleCharacterCasing" Value="Normal"/>
    </Style>
```

**The Issue's Sample Code**
https://github.com/p76984275/MetroWindowTitleCharacterCasing

It doesn't work if we new a existed MetroWindow control(has .xaml, .cs) and show.
However it works as expected if we new a nonexisted MetroWindow in code and show.

### Expected outcome
So far, Button, GroupBox, GridViewColumnHeader, DataGridColumnHeader... can be character casing unified with style setters in App.xaml.

It will be great and convenient to let MetroWindos's TitleCharacterCasing style setter work as expected just like others.

Many thanks.

--
### Environment

- MahApps.Metro __1.3.0-ALPHA200__
- Windows __7 x64__
- Visual Studio __2015__
- .NET Framework __4.5.2__

**Comment by punker76** [comment]
@p76984275 That's not MahApps related, it's limited by WPF. You must create an explicit style with a key and use it on every MetroWindow where you want it (you can see this at the clean window demo).

**Comment by p76984275** [comment]
It seems we must explicitly include the custom window-related style on every Window xaml.
Just a little inconvenience.

Really thanks for the detailed explanation.
