### ISSUE TITLE
Flyout animation and placement

### ISSUE THREAD

**Issue by LeafyDev** [MahApps/MahApps.Metro#2668]
Hi, I'm having a little issue concerning flyouts. I'm trying to use 1.4.0-ALPHA001 (latest from nuget) as it has the expected functionality in the metrodemo solution, however I'm only getting a centered flyout with no sliding, only a little opacity animation...

Do note I'm also using MaterialDesignThemes but I doubt this has such effect. (I may be wrong)

![image](https://cloud.githubusercontent.com/assets/1693101/18809704/b23bc5a4-8283-11e6-8af7-e3804a5e53b9.png)

I've managed to dock it on the right by using `HorizontalAlignment="Right"` but it still doesn't have the desired animation... Am I missing something?

## What steps will reproduce this issue?

```
<packages>
  <package id="Caliburn.Micro" version="3.0.1" targetFramework="net452" />
  <package id="Caliburn.Micro.Core" version="3.0.1" targetFramework="net452" />
  <package id="LoadingIndicators.WPF" version="0.0.1" targetFramework="net452" />
  <package id="MahApps.Metro" version="1.4.0-ALPHA001" targetFramework="net452" />
  <package id="MahApps.Metro.IconPacks.Modern" version="1.1.0" targetFramework="net452" />
  <package id="MahApps.Metro.Resources.Standalone" version="0.1.0.0" targetFramework="net452" />
  <package id="MaterialDesignColors" version="1.1.3" targetFramework="net452" />
  <package id="MaterialDesignThemes" version="2.2.0-ci688" targetFramework="net452" />
  <package id="MaterialDesignThemes.MahApps" version="0.0.7" targetFramework="net452" />
  <package id="Metro.Dialogs" version="0.0.0.2" targetFramework="net452" />
</packages>
```

```
<controls:MetroWindow.Flyouts>
        <controls:FlyoutsControl>
            <controls:Flyout Width="500"
                             Header="Notifications"
                             IsModal="True"
                             Position="Right"
                             Theme="Accent">
                <Grid>
                    <TextBlock Text="Nothing here yet m8." />
                </Grid>
            </controls:Flyout>
        </controls:FlyoutsControl>
    </controls:MetroWindow.Flyouts>
```

### Expected outcome

A nice little flyout on the right side sliding in. (MetroDemo does this)

--
### Environment

- MahApps.Metro v1.4.0-ALPHA001
- Windows 10 build 14926
- Visual Studio 2015 Enterprise
- .NET Framework 4.5.2

**Comment by LeafyDev** [comment]
Kind of embarrassing... this is what happens when you re-use old code... MaterialDesign does in fact break this, as it styles the flyouts in its own way which seems to break the animation...

**Comment by Insire** [comment]
luckily its already fixed [here](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/pull/506)

**Comment by LeafyDev** [comment]
oh indeed, I somehow missed that while looking through...

Thanks a lot 👍
