### ISSUE TITLE
DialogManager.ShowMetroDialogAsync line 319 throws null reference exception

### ISSUE THREAD

**Issue by khteh** [MahApps/MahApps.Metro#2669]
No matter how I have tried, `DialogManager.ShowMetroDialogAsync` throws null-reference exception at line 319. This is line 319 in DialogManager.cs:
```cs
if (window.metroActiveDialogContainer.Children.Contains(dialog) || window.metroInactiveDialogContainer.Children.Contains(dialog))
```
I can't step into the code from my application but I suspect the `metroActiveDialogContainer` or `metroInactiveDialogContainer` is not initialized properly.

## What steps will reproduce this issue?
Here is my code:
```cs
public async void ShowSessionDialog()
{
    try
    {
        CustomDialog customDialog = new CustomDialog() { Title = "Session Dialog" };
        SessionControl control = new SessionControl();
        SessionViewModel vm = new SessionViewModel(instance =>
        {
            dialogCoordinator_.HideMetroDialogAsync(this, customDialog);
            //System.Diagnostics.Debug.WriteLine(instance.FirstName);
        }, control);
        control.DataContext = vm;
        customDialog.Content = control;
        object context = DialogParticipation.GetRegister(view_ as MainWindow);
        Debug.Assert(context != null);
        await dialogCoordinator_.ShowMetroDialogAsync(this, customDialog);
    } catch (Exception e)
    {
        log.Error($"{nameof(ShowSessionDialog)}: Exception {e}");
    }
}
```
_Write problem description here_

### Expected outcome

_Write expected outcome here_

--
### Environment

- MahApps.Metro __v1.3.0.198
- Windows __10
- Visual Studio __2015
- .NET Framework __4.6.1

**Comment by thoemmi** [comment]
When do you try to show the dialog? If you're calling the code in your constructor, it won't work, because `metroActiveDialogContainer` and `metroInactiveDialogContainer` are initialized in `MetroWindow.OnApplyTemplate`.

**Comment by khteh** [comment]
I called it from MainWindows code-behind:

(DataContext as MainViewModel).ShowSessionDialog();

**Comment by punker76** [comment]
@khteh So like @thoemmi wrote, you should call your method at the Loaded event, cause the dialog containers are created at `OnApplyTemplate` of the `MetroWindow`.

```csharp
            this.Loaded += async (s, e) => {
                await (DataContext as MainViewModel).ShowSessionDialog();
            }
```

**Comment by punker76** [comment]
@khteh Also avoiding void async methods...

```csharp
public async Task ShowSessionDialog() { ... }
```

http://haacked.com/archive/2014/11/11/async-void-methods/

**Comment by khteh** [comment]
It works now. Thanks @thoemmi and @punker76 , especially for the pointer to avoid "async void".
