### ISSUE TITLE
Metro Debug OK Relase No Go 

### ISSUE THREAD

**Issue by jon60074** [MahApps/MahApps.Metro#2670]
## What steps will reproduce this issue?
      Metro Window with standard 3 links, 8 text boxes , 12 buttons 
_Write problem description here_
   Debug mode displays UI and works fine. Release mode throws exception below . 
Exception thrown: 'System.Windows.Markup.XamlParseException' in PresentationFramework.dll
### Expected outcome
   UI Displays
_Write expected outcome here_
   UI displays ( works in debug mode )

--
### Environment

- MahApps.Metro1.3 
- Windows 7  pro
- Visual Studio __2015__
- .NET Framework 4.5.6

**Comment by punker76** [comment]
@jon60074 Hi, sorry about your issue. Can you maybe show me the complete stacktrace and your Xaml? It would be really cool if you can publish your short sample or create a sample which shows the issue. Thx.

**Comment by jon60074** [comment]
Working now !!! Thanks for your time ! Having some reference issues so its on my end ! 

Please let me know if there is any way I can remove the issue totally .. 

Thanks ! 

Jon
