### ISSUE TITLE
Maximize, minimize and close buttion shown as basic windows style even they are hided.

### ISSUE THREAD

**Issue by lasikye** [MahApps/MahApps.Metro#2672]
## What steps will reproduce this issue?
1. 1 window which has 1 content container inside the window. 
2. The window will switch 2 different usercontrol but using same viewmodel.
3. Switching the view will change the window style as below.
   `this.ShowTitleBar = false;
                           this.ShowCloseButton = false;
                           this.ShowMaxRestoreButton = false;
                           this.WindowState = WindowState.Normal;
                           this.ResizeMode = ResizeMode.NoResize;`
4. When switching the view repeatly the issue will occurre

At step 4, when repeatly switching view, the close button and maximize button will suddenly show out with basic windows style.
### Expected outcome

The buttons hided should never show out.
## 
### Environment
- MahApps.Metro __v1.2.4.0
- Windows **7**
- Visual Studio **2015**
- .NET Framework **4.5**

**Comment by punker76** [comment]
@lasikye `this.WindowState = WindowState.Normal` is not supported by this library, cause `this.WindowState = WindowState.None` is the main feature of this. If you need __really__ none window style you should use the `UseNoneWindowStyle = true`.
You should also try to use the new v1.3.0 :-D

**Comment by lasikye** [comment]
@punker76 , thanks. I will try to update mahapp to 1.3.0 and update the codes also. :+1:

**Comment by lasikye** [comment]
@punker76 

I have another senario that the maxrestore button need hide but close button need show out, as your suggerstion if set `UseNoneWindowStyle = true`, it will make `ShowCloseButton = true` useless.

**Comment by punker76** [comment]
@lasikye I don't understand your last comment with the ShowCloseButton. Can you explain this in more details? Maybe a Screenhot?
