### ISSUE TITLE
DataGridCheckBoxColumn databinding and Style

### ISSUE THREAD

**Issue by ghost** [MahApps/MahApps.Metro#2675]
## What steps will reproduce this issue?

Use a DataGridCheckBoxColumn in a DataGrid.
Bind a property to it via DataBinding (triggered on "tick" change)
Apply the style ElementStyle="{DynamicResource MetroDataGridCheckBox}" to the column.
### Expected outcome

Bound property should change when a checkbox is ticked/unticked but it does not.
Removing the style, the attached property is triggered correctly.
## 
### Environment
- MahApps.Metro **v1.3.0**
- Windows **10**
- Visual Studio **2013**
- .NET Framework **4.5**

**Comment by half-evil** [comment]
I've got the same issue. 
If I apply the style ElementStyle="{DynamicResource MetroDataGridCheckBox}" , then I get no change notification. if I only apply the style EditingElementStyle="{DynamicResource MetroDataGridCheckBox}", then I get the change notification. But the visible style of the box changes through the editing process. The initial visual state is a standart WPF checkbox, after a click it changes to a MetroCheckbox and after the editing it returns to a standart checkbox.

### Environment
- MahApps.Metro v1.4.1
- Windows 10
- Visual Studio 2015
- .NET Framework 4.5

**Comment by ndavis10** [comment]
With both the ElementStyle and EditingElementStyle set to MetroDataGridCheckbox, I was able to get data binding from the checkbox to work by adding "UpdateSourceTrigger=PropertyChanged" to the DataGridCheckBoxColumn.

### Environment

* MahApps.Metro v1.4.3
* Windows 10
* Visual Studio 2015
* .NET Framework 4.5.1
