### ISSUE TITLE
Cannot load MahApps.Metro.Resources

### ISSUE THREAD

**Issue by khteh** [MahApps/MahApps.Metro#2677]
## What steps will reproduce this issue?
I want to use some of the icons in MahApps.Metro.Resources.Icons for my buttons. I do this in my viewmodel:

var dict = new ResourceDictionary { Source = new Uri("pack://application:,,,/MahApps.Metro.Resources;component/Icons.xaml") };

I use NuGet / PackageManagerConsole to install the package. However, that assembly does not appear in References in the project.

_Write problem description here_
Runtime error: Could not load file or assembly 'MahApps.Metro.Resources, Culture=neutral' or one of its dependencies. The system cannot find the file specified.

### Expected outcome

_Write expected outcome here_

--
### Environment

- MahApps.Metro __v1.4.0.3
- Windows __10__
- Visual Studio __2015__
- .NET Framework _4.6.1__

**Comment by punker76** [comment]
@khteh If you use the NuGet package and want load all icons in code behind then you must do this

```
var dict = new ResourceDictionary { Source = new Uri("pack://application:,,,/YourApplicationName;component/YourResourceFolder/Icons.xaml") };
```

https://github.com/MahApps/MahApps.Metro.Resources#usage

**Comment by khteh** [comment]
I use IconPacks instead. Thanks.
