### ISSUE TITLE
SearchMetroTextBox style, IsReadOnly

### ISSUE THREAD

**Issue by robertorp** [MahApps/MahApps.Metro#2678]
## What steps will reproduce this issue?

SearchMetroTextBox
I want to make it to read-only but can click on the search button.

_Write problem description here_
When I put the textbox to read only the same does not allow me to click the search button
### Expected outcome

_Write expected outcome here_
Clicking the search button with the active isReadOnly property
## 
### Environment
- MahApps.Metro **v1.3.0**
- Windows **10**
- Visual Studio **2015**
- .NET Framework **4.61**

**Comment by thoemmi** [comment]
@punker76 I agree with @robertorp that the clear button should be enabled even if the `TextBox` is readonly. Only if it's **disabled**, the button should be disabled too.

Currently, the button is disabled [here](https://github.com/MahApps/MahApps.Metro/blob/develop/MahApps.Metro/Styles/Controls.TextBox.xaml#L186-L188) and [here](https://github.com/MahApps/MahApps.Metro/blob/develop/MahApps.Metro/Styles/Controls.TextBox.xaml#L410-L412) respectively.

**Comment by punker76** [comment]
@thoemmi I'm with you with the `MetroButtonTextBox` but not for the textbox style, cause it clears the text if you click the button. I think this will maybe surprise the user?

**Comment by thoemmi** [comment]
😕 Yes, you're right. However, think of a "Browse" button. The user should not be able to enter the filename directly, therefore the textbox is readonly. But if the user clicks on the button, a File Open dialog should open.

So the button should be enabled even if the textbox is readonly, **only** if `TextBoxHelper.ButtonCommand` is set. 😎

**Comment by punker76** [comment]
@robertorp This feature will be available in 1.4.0
