### ISSUE TITLE
Drag and drop from a stackpanel in a flyout to a canvas in the window?

### ISSUE THREAD

**Issue by robault** [MahApps/MahApps.Metro#2680]
## What steps will reproduce this issue?
Implement rudimentary drag & drop using preview mouse button down and mouse move on the stack panel, allow drop on the canvas along with drag enter and drop events.

_Write problem description here_
The drag enter and drop events on the canvas don't seem to fire when dragging an element from the stack panel in the flyout. Is a flyout some kind of modal dialogue or does the rendering overlay elements in the WPF window under it? I very well could be doing this wrong. Is there an example somewhere?

### Expected outcome
When releasing the left mouse button the drop event on the canvas should fire.

--
### Environment

- MahApps.Metro __v1.2.4.0__ (nuget package)
- Windows __10__
- Visual Studio __2013__
- .NET Framework __4.5__

**Comment by punker76** [comment]
@robault Without your code (Xaml, code behind) I can't say what's wrong. Also please use v1.3.0

**Comment by robault** [comment]
Thanks for the quick response. I published a repo here showing the problem. 

[https://github.com/robault/MahappsDragAndDrop](https://github.com/robault/MahappsDragAndDrop)

The more I played around with this the more I get the impression I'm doing something wrong and this isn't a Mahapps bug.

**Comment by robault** [comment]
I created a new repo with DropList commented out, DragList moved outside of the flyout and I can drag and drop images onto the canvas just fine. Here's the repo showing this:

[https://github.com/robault/MahappsDragAndDropCanvasOnly](https://github.com/robault/MahappsDragAndDropCanvasOnly)

**Comment by robault** [comment]
Looks like it has nothing to do with MahApps. I just found this, tested it and it worked. 

[http://stackoverflow.com/questions/7762957/why-doesnt-wpf-canvas-alow-drop#7763045](http://stackoverflow.com/questions/7762957/why-doesnt-wpf-canvas-alow-drop#7763045)

For posterity, from the marked answer on SO:

"By default, Canvas has no background so hit-testing is not picking up that the cursor is over the Canvas element, but is instead bubbling up to the Grid or Window which don't allow drop. Set the background to Transparent as follows and it should work:

<Window x:Class="ImageViewer.Window1"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
   xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
   Title="Window1" Height="398" Width="434">
   <Grid>
      <Canvas AllowDrop="True" Background="Transparent" />
   </Grid>
</Window>"

If you pull the latest of this repo you'll see it works. 

https://github.com/robault/MahappsDragAndDrop

Thanks for checking into this anyway. What an odd behavior for WPF to have. 

--Robert
