### ISSUE TITLE
zoom in/out and fullsceen problem

### ISSUE THREAD

**Issue by godsosome** [MahApps/MahApps.Metro#2681]
with version .net 4.0 in vs2010, i take dockpanel as child of metrowindow, put an image and starusbar in this dockpanel, image will auto fill the free space of dockpanel, a toggle full screen button in statusbar, when zoom out image, how could it cover title bar and status bar, the window can not drag moving any more, reset z-index will resolve it but another issue coming, the toggle full screen button can just click once.
any ideas?

**Comment by punker76** [comment]
@godsosome Have you read the contribution guidelines? Which MahApps version? Please post some code, maybe your Window properties. How do you toggle fullscreen?

**Comment by godsosome** [comment]
sorry, my buddy, MahApps.Metro v1.3.0 for .net 4.0, win7 sp1 and vs2010 with .net 4.0; 
xaml is just like:
`<Controls:MetroWindow x:Class="WireNettingCli.MainWindow"   
    Title="{x:Static Res:Resources.appTitle}" Icon="logo.ico"
    TitleCharacterCasing="Normal"
    Dialog:DialogParticipation.Register="{Binding}"
    GlowBrush="{DynamicResource AccentColorBrush}"
    NonActiveGlowBrush="#CDFF0000"
    ShowIconOnTitleBar="True"
    ShowTitleBar="True"
    WindowStartupLocation="CenterScreen"
    BorderBrush="{DynamicResource AccentColorBrush}"
    BorderThickness="1"
    SaveWindowPosition="True"
    Width="800" Height="600"
    Closing="MetroWindow_Closing" 
    x:Name="mainWindow"                  
    >  	
	<DockPanel LastChildFill="True">        
        <StatusBar DockPanel.Dock="Bottom" Height="25" HorizontalAlignment="Stretch" x:Name="myStarusBar">
			<StatusBarItem>
                <StackPanel Orientation="Horizontal" Margin="3,0,3,0">                    
                    <Button Margin="3,0,0,0" x:Name="fullScrenn" Click="fullScrenn_Click"
                            Padding="2"
                            HorizontalContentAlignment="Stretch" 
                            VerticalContentAlignment="Stretch">
                        <Image Source="Images/full_16.png" x:Name="fullImage"></Image>
                    </Button>
                </StackPanel>
            </StatusBarItem>
		</StatusBar>
		<Image/>
	</DockPanel>
</Controls:MetroWindow>`

code behind:

`private bool fullScreen = false;
private void fullScrenn_Click(object sender, RoutedEventArgs e)
{
	fullScreen = !fullScreen;
    if (fullScreen)
    {
        metroWindow.IgnoreTaskbarOnMaximize = true;
        metroWindow.WindowState = WindowState.Maximized;
        metroWindow.UseNoneWindowStyle = true;
    }
    else
    {
        metroWindow.WindowState = WindowState.Normal;
        metroWindow.UseNoneWindowStyle = false;
        metroWindow.ShowTitleBar = true; // <-- this must be set to true
        metroWindow.IgnoreTaskbarOnMaximize = false;
    }
}`

**Comment by punker76** [comment]
@godsosome Thx. My suggestion: toggle the StatusBar invisible on Fullscreen and bring it back (also non Fullscreen) with Esc in PreviewKeydown of the Window.

**Comment by godsosome** [comment]
for fullscreen, this is an acceptable way, but i want all function buttons on status bar make sense when window is full screen and image zoom in/out do not cover title bar and status bar so that window is draggable/moveable.

**Comment by punker76** [comment]
@godsosome Then don't set `IgnoreTaskbarOnMaximize=true`

**Comment by godsosome** [comment]
@punker76 this is not the pain point, status bar is my statusbar within the fullsceen button not the taskbar of OS. code behind, i do following and this makes buttons on my status bar not working when full screen.
`public override void OnApplyTemplate()
 {
     base.OnApplyTemplate();
     this.Template.FindName("PART_TitleBar", this);
     var back = this.Template.FindName("PART_WindowTitleBackground", this) as UIElement;
     Panel.SetZIndex(back, 1);
     var thumb = this.Template.FindName("PART_WindowTitleThumb", this) as UIElement;
     Panel.SetZIndex(thumb, 1);
     var bar = this.Template.FindName("PART_TitleBar", this) as UIElement;
     Panel.SetZIndex(bar, 1);
     var left = this.Template.FindName("PART_LeftWindowCommands", this) as UIElement;
     Panel.SetZIndex(left, 2);
     var right = this.Template.FindName("PART_RightWindowCommands", this) as UIElement;
     Panel.SetZIndex(right, 2);
	 Panel.SetZIndex(this.myStarusBar, -1);
     Panel.SetZIndex(this.myImage, -9);
 }`

**Comment by punker76** [comment]
@godsosome Why do you set all these ZIndex's

**Comment by godsosome** [comment]
i want the image is behind all the controls so that when zoom out it the window's title bar, my status bar are still visible. window is till  draggable.

**Comment by punker76** [comment]
I don't think that this is an MahApps issue, so I close it for now.
