### ISSUE TITLE
[Question] Force TextBox uppercase in ShowLoginAsync

### ISSUE THREAD

**Issue by shaggygi** [MahApps/MahApps.Metro#2683]
Is there a way to force the TextBox text to uppercase in ShowLoginAsync?  This would be similar to CharacterCasing property in regular TextBox control.

Thanks

**Comment by punker76** [comment]
@shaggygi It's available in next 1.5.0 release with a new LoginSettings proiperty.

**Comment by shaggygi** [comment]
@punker76 as always, thanks 👍

**Comment by jimbobsmith** [comment]
how about having a TextBox  attached property to force all caps on the text?
