### ISSUE TITLE
ToggleButton will not preserve text case

### ISSUE THREAD

**Issue by shaggygi** [MahApps/MahApps.Metro#2686]
## What steps will reproduce this issue?
Create WPF app.
Add MahApps reference NuGet package.
Add ToggleButton to Window.
Add mahapps:ButtonHelper.PreserveTextCase="True" to XAML.

### Expected outcome
The text should be preserved similar to Button.

### Environment
- MahApps.Metro v1.3
- Windows 7
- Visual Studio 2015 Update 3
- .NET Framework 4.6.1

**Comment by punker76** [comment]
@shaggygi `ButtonHelper.PreserveTextCase` is obsolete and doesn't work for the `ToggleButton`. You should use `ControlsHelper.ContentCharacterCasing` instead with the possible values `Normal`, `Upper` and `Lower`.

**Comment by shaggygi** [comment]
That did the trick.  Thanks
