### ISSUE TITLE
Implement SecureStrng into LoginDialogData and ShowLoginDialog

### ISSUE THREAD

**Issue by dartvalince** [MahApps/MahApps.Metro#2687]
This is a feature request, if already implemented I'm unable to find it.  
The `ShowLoginDialog` and `ShowModalLoginExternal`both return a `LoginDialogData`object.  The implementation of these two dialogs use a normal `Textbox`for the password input and place a plain string in memory when put within the `LoginDialogData`.  If possible, please give an option to use a `PasswordBox`instead of the `TextBox`and return the `SecureString` object from the password box.  

It's a counterproductive to have he password as a plain string in memory and then having to convert it to a `SecureString`after the fact.

**Comment by punker76** [comment]
@dartvalince The usage of the SecureString will be  available in 1.4.0
