### ISSUE TITLE
Menu dropdown design

### ISSUE THREAD

**Issue by Dinevv** [MahApps/MahApps.Metro#2692]
Hello! 
Can someone help me with styling the dropdown of the menu? (first is current, second is what it should be)

![qj1omwj](https://cloud.githubusercontent.com/assets/658431/20402996/5209aeca-acff-11e6-9c2d-6ce5720d3f2f.png)

I've tried something like this:

```
<MenuItem Header="Файл" Foreground="White">
    <MenuItem Header="_Нов" />
</MenuItem>
```

but all text items becomes white even in the dropdown.
I can't also figure out how to change the black border of the dropdown.

And my second question - it there any way to get the current accent color? I've tried with {DynamicResource AccentColorBrush} but it returns different color than the actual in the windows bar.
- MahApps.Metro **v1.3.0**
- Windows **10**
- Visual Studio **2015**
- .NET Framework **4.5**

**Comment by punker76** [comment]
@Dinevv The VS styles uses such a menu, so please take a look to the [source](https://github.com/MahApps/MahApps.Metro/blob/develop/src/MahApps.Metro/MahApps.Metro/Styles/VS/Menu.xaml). I think you can create your own style with the help from this style.

![image](https://cloud.githubusercontent.com/assets/658431/21048474/d9b65b0e-be0f-11e6-9ecb-360f14a78ce7.png)
