### ISSUE TITLE
Flyout opened below some controls

### ISSUE THREAD

**Issue by alexeygritsenko** [MahApps/MahApps.Metro#2693]
## What steps will reproduce this issue?

Flyout opened below some controls. He turns from the bottom, but must be on top. This happens if you use WindowsFormsHost or infragistics controls.
Video Bug: https://1drv.ms/v/s!Aq6ZQkyoPcuM9ATS8qNqViwO5zHm
Download my program: https://yadi.sk/d/NTrO4sOepjjQq

### Expected outcome

I want to Flyout opened on top of all the program interface

--
### Environment

- MahApps.Metro __v1.3__
- Windows __7 x64__
- Visual Studio __2015__
- .NET Framework __4.0__

**Comment by punker76** [comment]
@alexeygritsenko This is not MahApps related but a known issue by WPF and WindowsFormsHost, so please try the `AirspaceDecorator` from [Microsoft.DwayneNeed](https://microsoftdwayneneed.codeplex.com/) to avoid this (https://github.com/MahApps/MahApps.Metro/wiki/FAQ#solution-2)

**Comment by jenokizm** [comment]
thanks for the reply. 
Solution 1 does not work,
error: Unable to find property "AllowsTransparency" in type "BorderlessWindowBehavior".
after i write line: this.AllowsTransparency = true;
display healed now Flyout from the top looks good, but the buttons located on it do not click. It turns out he is the top only in appearance, but in fact there is less control and interact with it is impossible.
Solution 2, I will check and let you know later. they do not have ready-made library, it needs to be compiled (yet I fail)

**Comment by alexeygritsenko** [comment]
thanks for the reply. 
Solution 1 does not work,
error: Unable to find property "AllowsTransparency" in type "BorderlessWindowBehavior".
after i write line: this.AllowsTransparency = true;
display healed now Flyout from the top looks good, but the buttons located on it do not click. It turns out he is the top only in appearance, but in fact there is less control and interact with it is impossible.
Solution 2, I will check and let you know later. they do not have ready-made library, it needs to be compiled (yet I fail)

**Comment by punker76** [comment]
@alexeygritsenko Sorry for this, AllowTransparency is old solutiin, I should dekete it. For the second, I can compile it for you...

**Comment by alexeygritsenko** [comment]
I was able to compile the library and follow your example (Solution 2). However, I get an error in my project:

> Error		The tag 'AirspaceDecorator' does not exist in XML namespace 'clr-namespace:Microsoft.DwayneNeed.Interop;assembly=Microsoft.DwayneNeed'. Line 270 Position 30.

**Comment by punker76** [comment]
@alexeygritsenko 
[Microsoft.DwayneNeed.zip](https://github.com/MahApps/MahApps.Metro/files/521220/Microsoft.DwayneNeed.zip)

**Comment by alexeygritsenko** [comment]
unfortunately your library the same error (
checking them in?

**Comment by alexeygritsenko** [comment]
I realized what was happening. Your assembly (Microsoft.DwayneNeed.zip) for Net 4.5, but my project 4.0. I rebuilt under 4.0 and now it works! The program really shows Flyout top and controls on it are clickable. But the downside is that the visual studio fell off a visual interface editor. He is now constantly crash, I can only view the xaml code(

**Comment by punker76** [comment]
@alexeygritsenko Sorry about the VS designer crashes. I'll close this issue cause this is not MahApps related.
