### ISSUE TITLE
Maximized Window is "Always on Top" when IgnoreTaskbarOnMaximize=True. Window remains "Always on Top" on Restore

### ISSUE THREAD

**Issue by mike-ward** [MahApps/MahApps.Metro#2694]
## What steps will reproduce this issue?
- Open Markdown Edit, press F9 and ensure IgnoreTaskbarOnMaximize is true.
- Maximize MDE.
- Notice that MDE is now "Always on Top" by trying to place another window over MDE.
- Restore MDE to a normal Window
- Notice that MDE is still "Always on Top"

If you repeat these steps with IgnoreTaskbarOnMaximize = false, the behavior is correct.
### Expected outcome

Always on Top is a bit unexpected when Maximized but I can see why that might be necessary. Restoring the Window should remove the Always on Top behavior.
## 
### Environment
- MahApps.Metro .3
- Windows 10
- Visual Studio 2015
- .NET Framework 4.6+

**Comment by punker76** [comment]
@mike-ward I noticed this also by using MDE. I'll try to fix this possible as soon.

**Comment by mike-ward** [comment]
No worries. The workaround is easy enough.

**Comment by ipandya** [comment]
@punker76  I have also noticed this. Though, restoring the windows does not take any effect.

**Comment by sleman** [comment]
@mike-ward What's the workaround?

**Comment by ipandya** [comment]
@sleman set **IgnoreTaskbarOnMaximize** to **false**. This solved the problem for me as of now.

**Comment by sleman** [comment]
Unfortunately I need that setting or else taskbar shows when app is fullscreen.

**Comment by ben2talk** [comment]
Wow, why is this closed?
If I maximise firefox and then restore it, it's permanently pinned on top - and I disabled the titlebar so I have to quit and restart the app to reset it!!!

**Comment by timunie** [comment]
@ben2talk feel free to open a new issue, fill in the issue template and provide the code which does not work. Also please tell us what exactly you are meaning by firefox? I don't think that Firefox uses MahApps?

Moreover please be more kind to people working in their free time to provide this package to you and everyone else. It really keeps the enthusiasm up if we get more positive feedback. Thank you in advance.

Happy coding
Tim

**Comment by ben2talk** [comment]
> @ben2talk feel free to open a new issue
> Tim
Sorry, my humble apology - this header looks identical to an issue I'm having with Krohnkite... it is not related to MahApps at all, but with Krohnkite running on KDE (Kwin script).
