### ISSUE TITLE
Typo error in MahApps (?

### ISSUE THREAD

**Issue by avechuche** [MahApps/MahApps.Metro#2697]
Between the words "campo" and "es" there are two blank spaces. It is an typo error in MahApps? This is a default message by using IDataErrorInfo with "[Required (AllowEmptyStrings = false)]".
It is easy to fix, overwriting the message, but it is always better solve the root problem. Thanks for your job!

![captura](https://cloud.githubusercontent.com/assets/11781418/19312458/c847820a-9068-11e6-981b-4301d3628335.JPG)

--
### Environment

- MahApps.Metro 1.3.0
- Windows 8.1
- Visual Studio 2015
- .NET Framework 4.5.0

**Comment by punker76** [comment]
@avechuche I think this is not related to MahApps.
