### ISSUE TITLE
Style incompatibility with Windows Workflow Foundation 4 designer

### ISSUE THREAD

**Issue by geoffbennett** [MahApps/MahApps.Metro#27]
Applying the style in the <code>Controls.xaml</code> style causes the "Browse for Types" option in the type drop-down combo boxes to stop working. None of the other styles have any impact. To reproduce (in VS2010), create a new WPF application. In the code-behind for the Window1.xaml, import the following namespaces:

<pre>
using System.Activities;
using System.Activities.Presentation;
using System.Activities.Core.Presentation;
</pre>

Then declare two class members:

<pre>
private DesignerMetadata _designerMetadata;
private WorkflowDesigner _designer;
</pre>

Lastly, add the following lines to the constructor:

<pre>
_designerMetadata = new DesignerMetadata();
_designerMetadata.Register();
_designer = new WorkflowDesigner();
DesignerGrid.Children.Add(_designer.View);
_designer.Load(new ActivityBuilder {Name = "Test Workflow"});
</pre>

Where <code>DesignerGrid</code> is the name of the grid layout control at the root of the window.

Apply the resources as mentioned in the MahApps.Metro guide page, and change the <code>Window</code> to a <code>MetroWindow</code>.

Run the application, and in the workflow designer, at the bottom of the window, choose "Arguments". Click on the text to "Create a new argument" and an argument with some default settings will be added. Drop down the type combo box, and click on the "Browse for Types..." option. Nothing will happen.

Go back to the resources added to the window and comment out the <code>Controls.xaml</code> resource. Rerun the application and repeat the steps above. The type browser will now load.

**Comment by sirdet** [comment]
Hi Geoff,
I am currently experiencing this same issue with the MetroWindow theme and embeding the Windows Workflow Foundation designer. What was your approach to solve the issue?  is there a workaround? I am using the latest version of both and I can not get the nested data types to work (unless I removed the MetroWindow layout altogether)
