### ISSUE TITLE
AssemblyFileVersion between Stable and Prerelease(ALPHA)

### ISSUE THREAD

**Issue by p76984275** [MahApps/MahApps.Metro#2702]
## What steps will reproduce this issue?
The assembly file/product version comes from NuGet stable 1.3.0 is **1.3.0.0**.
While the formal NuGet prerelease 1.3.0-ALPHA186 is **1.3.0.186**

If we ship our software v1.0 with prelease MahApps.Metro 1.3.0-ALPHA186.
And now we want to upgrade to v2.0 with stable MahApps.Metro 1.3.0.

Windows installer in InstallShield LE, WiX, will delete MahApps.Metro.dll during product upgrade according to the File Versioning Rules since **_1.3.0.0 < 1.3.0.186_**:
https://msdn.microsoft.com/en-us/library/windows/desktop/aa368599(v=vs.85).aspx

The rule's behavior:
https://blogs.msdn.microsoft.com/astebner/2015/11/16/why-windows-installer-removes-files-during-a-major-upgrade-if-they-go-backwards-in-version-numbers/
http://stackoverflow.com/questions/4227456/windows-installer-deletes-versioned-file-during-product-upgrade-instead-of-down

![q](https://cloud.githubusercontent.com/assets/14271763/19380616/9091c1cc-922a-11e6-8f3c-adf1d0153878.png)

### Expected outcome

Now we are using the lastest NuGet prerelease version as a workaround since 1.4.0.xxx > 1.3.0.xxx.
But it will happen again if the next stable release 1.4.0's assembly version is less than the prelease 1.4.0 one.

Might I ask if there is an appropriate way to handle this issue?
Could the assembly version of stable release 1.4.0 be larger than the one of prelease 1.4.0?
Really thanks for your help.

--
### Environment

- MahApps.Metro __v1.3.0__
- Windows __7__
- Visual Studio __2015__
- .NET Framework __4.6.2__

**Comment by punker76** [comment]
@p76984275 I don't know what happens if we only change the `Product version` on every build and leave the other always the same...

Is the 1.4.0 with same product version 1.4.0 greater than a dll with 1.4.0 and 1.4.0.xyz as product version?

![2016-10-14_15h46_27](https://cloud.githubusercontent.com/assets/658431/19389808/ae42dc7e-9225-11e6-8d60-8af8f0a13c47.png)

**Comment by punker76** [comment]
@p76984275 ...or something like this...

![2016-10-14_16h17_04](https://cloud.githubusercontent.com/assets/658431/19390744/b77f1236-9229-11e6-90de-d3030cf9ca23.png)

**Comment by punker76** [comment]
@p76984275 ...and finally this... `Assembly Version` always 1.x.0 for pre-release and for the stable version all the same => 1.x.0

![2016-10-14_16h23_08](https://cloud.githubusercontent.com/assets/658431/19390928/a2f2778a-922a-11e6-9762-a34ef3b372ed.png)

**Comment by punker76** [comment]
@p76984275 -> MahApps.Metro 1.4.0-ALPHA021

**Comment by p76984275** [comment]
@punker76 Sorry for not replying you sooner.

The issue is caused by the file version (**AssemblyFileVersion**) which is used in deployment. Windows Installer will check it when performing upgrading. 

1.4.0-alpha21 is not a valid AssemblyFileVersion format which caused the file version to be 0.0.0.0 :
![2016-10-17_14-48-03](https://cloud.githubusercontent.com/assets/14271763/19427807/d6bfb532-9478-11e6-926b-f4d69d8aeddd.png)

The AssemblyFileVersion format is a string of four numbers, separated by periods :
https://msdn.microsoft.com/en-us/library/system.reflection.assemblyfileversionattribute.assemblyfileversionattribute.aspx

After some manual versioning tests (Note that the information in AssemblyInfo.cs is edited manually which may be different than automatically generated by script or something), there are 2 approaches to handle this:

1. Increment AssemblyFileVersion for each build and ensure stable's file version is always larger than the last prelease. For example, assume for 1.4.0, ALPHA22 is the last alpha build:
![1-1](https://cloud.githubusercontent.com/assets/14271763/19430969/006a7b78-9489-11e6-88a0-2519fb9979e4.png)
![1-2](https://cloud.githubusercontent.com/assets/14271763/19430563/43922d4e-9487-11e6-98c4-27c447fe5476.png)
![1-0](https://cloud.githubusercontent.com/assets/14271763/19430599/5f9700f0-9487-11e6-8ae6-9a46b859f2ff.png)

2. Keep AssemblyFileVersion the same for prerelease and stable:
![2-1](https://cloud.githubusercontent.com/assets/14271763/19430958/f9654ccc-9488-11e6-83cd-b294d86d8e93.png)
![2-2](https://cloud.githubusercontent.com/assets/14271763/19430329/6d74294c-9486-11e6-80e8-a310e1f5b8cd.png)
![2016-10-17_15-31-56](https://cloud.githubusercontent.com/assets/14271763/19428948/a8668ed4-947f-11e6-9486-9a7b35e52ded.png)

Approach 1 makes more sense to me since AssemblyFileVersion can represent and distinguish each different build.

Thanks for the discussion.

**Comment by punker76** [comment]
@p76984275 First approach is now live -> MahApps.Metro.1.4.0-ALPHA022
