### ISSUE TITLE
Can not get flyout's to open/close by either input binding or a button

### ISSUE THREAD

**Issue by alex-nicholas** [MahApps/MahApps.Metro#2703]
Im trying to open / close a flyout in in my View and can not get it to work.

```
<mah:Flyout x:Name="quickLinks"
                    Header="Quick-Links"
                    FontFamily="GlacialIndiference"
                    Width="400"
                    Grid.RowSpan="3"
                    IsOpen="{Binding IsQuickLinksOpen}"
                    Position="Right">
            </mah:Flyout>
```

I am expecting that when I change IsQuickLinksOpen from false to true, the flyout should appear and vice versa however I can not get the flyout to appear despite debugging shows me the property is changing.. If I set the property to true then open the window I am seeing the flyout open, but I can not open it again after I close it. 

- MahApps.Metro  v1.3.0
- Windows 10
- Visual Studio 2015
- .NET Framework 4.6
App wired up with Caliburn Micro

**Comment by punker76** [comment]
@alex-nicholas Can you create a short app for this scenario?
