### ISSUE TITLE
Mahapps' behaviors broken starting from .Net 4.5

### ISSUE THREAD

**Issue by jumulr** [MahApps/MahApps.Metro#2705]
Hi, using **Visual Studio 2015 update 3, .Net 4.6.2** i get those two errors, alternatively and randomely :

-  The type BorderlessWindowBehavior from assembly MahApps.Metro was created with a previous version of Blend SDK which is not supported in a Windows Presentation Framework 4 project.
-     Can't add an instance of type 'BorderlessWindowBehavior' to a collection of type 'BehaviorCollection'. Only elements of type 'T' are allowed.

It doesn't prevent from executing the app, but the behavior isn't applied.
Same goes for other Mahapps' behaviors.
**It breaks starting from .Net 4.5 and System.Windows.Interactivity.dll 4.5.0.0**

You can reproduce the issue using the templates you provide [WPF MahApps.Metro Application (.NET45)](https://github.com/MahApps/MahApps.Metro/blob/develop/Visual%20Studio%20Templates/Templates.zip).
Just add a Mahapps' behavior.

**Related issue : #1970**

--
### Environment

- MahApps.Metro 1.3.0 and 1.4.0-ALPHA022
- Visual Studio 2015
- .NET Framework 4.5+

**Comment by punker76** [comment]
@jumulr The Templates are very old, so have you tried to create an app without them? Only using NuGet and the Quick start?

**Comment by jumulr** [comment]
Yes i tried, i mentioned the templates so you can reproduce it.
Anyway, it turns out to be a Visual Studio 2015 installer issue related to [this one ](https://connect.microsoft.com/VisualStudio/feedbackdetail/view/755407/xaml-designer-will-not-display-when-using-blend-sdk-behaviors).
Everything is working fine now !
