### ISSUE TITLE
Set MetroTabItem ControlsHelper.HeaderFontSize using code

### ISSUE THREAD

**Issue by vladano** [MahApps/MahApps.Metro#2708]
## What steps will reproduce this issue?

I add additional button on TabControlExamples.xaml from MetroDemo
    <Button Click="AddNewTab_Click">Add New Tab</Button>
	
On click event I try to add additional MetroTabItem using code to existing MetroTabControl 
```
<Controls:MetroTabControl Name="TabCloseControl" TabItemClosingEvent="MetroTabControl_TabItemClosingEvent">
...
</Controls:MetroTabControl>
```

```
private void AddNewTab_Click(object sender, RoutedEventArgs e)
{
	MetroTabControl tc = (MetroTabControl)this.FindName("TabCloseControl");
	MetroTabItem cti = new MetroTabItem();
	cti.Header = "can";
	cti.CloseButtonEnabled = true;
	cti.FontSize = 16;
	tc.Items.Insert(2,cti);
}
```

I don't know how to set value for HeaderFontSize using code ?
In XAML that can be set using Controls:ControlsHelper.HeaderFontSize="20", how to do this using code ?
I try do that using "cti.FontSize = 16;", but it doesn't work.

Any idea ?

_Write problem description here_

### Expected outcome

_Write expected outcome here_

--
### Environment

- MahApps.Metro __v1.4.0__
- Windows __10__Pro_x64
- Visual Studio __2015__Enterprise
- .NET Framework __4__

**Comment by vladano** [comment]
I find the "work around" solution ... Not perfect but working
Inside TabControlExamples.xaml I add MetroTabControl.Resources 

```
<Controls:MetroTabControl Name="TabCloseControl" 
              TabItemClosingEvent="MetroTabControl_TabItemClosingEvent">
	<Controls:MetroTabControl.Resources>
		<System:Double x:Key="TabItemFontSize">22.00</System:Double>
	</Controls:MetroTabControl.Resources>
         ...
</Controls:MetroTabControl> 

```

```
private void AddNewTab_Click(object sender, RoutedEventArgs e)
{
    MetroTabControl tc = (MetroTabControl)this.FindName("TabCloseControl");
    MetroTabItem cti = new MetroTabItem();
    cti.Header = "can";
    cti.CloseButtonEnabled = true;
    tc.Items.Insert(2,cti);
}
```

**Comment by AndrzejKl** [comment]
try to add this:
````c#
ControlsHelper.SetHeaderFontSize(cti, 20);
````
