### ISSUE TITLE
TextBox "Auto" Watermark-text

### ISSUE THREAD

**Issue by kamilkosek** [MahApps/MahApps.Metro#2712]
## What steps will reproduce this issue?

Not a real issue but a question. 
Would it be possible to automatically set the watermark text to the bound property name ?
Or even better, take automatically the value of the Display-Attribute from the property as the Watermark text.
Lets say I got this Model

``` csharp
public class Device
    {
        [Display(Name = "Geräte Id")]
        public int DeviceId { get; set; }
        [Display(Name = "Geräte Name")]
        public string DeviceName { get; set; }
    }
```

and on the textbox looks e.g. like this

``` xaml
<StackPanel DataContext="{Binding MyDevice}">
                    <TextBox mah:TextBoxHelper.AutoWatermark="True" Text="{Binding DeviceId}"></TextBox>
                </StackPanel>
```

All the best,
Kamil

**Comment by punker76** [comment]
@kamilkosek I think that's not so easy. Cause for this it's necessary to look at the binded property for the DisplayAttribute. I don't know yet how we can do this in an easy way.
/cc @thoemmi

**Comment by xxMUROxx** [comment]
@punker76 Yes it is possible and easy to implement. I am working on a PR. But the requested feature is NET45 only

**Comment by punker76** [comment]
@xxMUROxx Getting the DisplayAttrubute and Binding should be also available in .Net 4, or not? What restriction is it?
