### ISSUE TITLE
Weird animation on combobox with only one item

### ISSUE THREAD

**Issue by muriloebsantos** [MahApps/MahApps.Metro#2713]
## What steps will reproduce this issue?
Load a combox with only one item
Click on the combox to show the items

### Expected outcome

It will open the combobox with one animation that will increase the text legiblity. When it just opens it's difficult to read the content, it seems like I'm not wearing my glasses.

http://stackoverflow.com/questions/40262033/remove-combobox-animation-on-mahapps

I would like to know how to remove this animation.
--
### Environment

- MahApps.Metro __1.3.0__
- Windows __8.1__
- Visual Studio __2015__
- .NET Framework 4.5

**Comment by punker76** [comment]
@muriloebsantos This is a known problem of WPF itself https://blogs.msdn.microsoft.com/text/2010/01/14/cleartypehint/ or http://stackoverflow.com/a/508596/920384
I will look and add this to MahApps as possible as soon for 1.4.0.

**Comment by punker76** [comment]
@muriloebsantos Please try 1.4.0-ALPHA026 for this issue. You must set `RenderOptions.ClearTypeHint="Enabled"` for the ComboBox to enable this for the scrollviewer content presenter. Please let me know if this works. Thx.

**Comment by muriloebsantos** [comment]
Unfortunately it didn't work. I updated the package and I set RenderOptions.ClearTypeHint="Enabled"

**Comment by punker76** [comment]
@muriloebsantos The ClearType or the animation? The animation is not affected by this

**Comment by muriloebsantos** [comment]
Sorry, the animation.

**Comment by punker76** [comment]
@muriloebsantos Animation is controlled by SystemParameters.ComboBoxPopupAnimationKey

**Comment by muriloebsantos** [comment]
You gave me keyword I needed! Then I search on stackoverflow and found the solution: http://stackoverflow.com/a/25502880/3517029

 <Controls:MetroWindow.Resources>
        <PopupAnimation x:Key="{x:Static SystemParameters.ComboBoxPopupAnimationKey}">None</PopupAnimation>
    </Controls:MetroWindow.Resources>
