### ISSUE TITLE
Flyouts in a view/usercontrol

### ISSUE THREAD

**Issue by maciz84** [MahApps/MahApps.Metro#2714]
Hi Guys,

I know this wasn't possible a year ago but I honestly believe that the Flyout control needs to be available to be used in a view/usercontrol. Using it only in a windows is very limiting.

Is this still the case and so is there any future possibility in this happening.

Currently I am using an expander in my view to mimic it and it ain't great :(

**Comment by thoemmi** [comment]
The scope of flyouts is still the window. I assume you already read @flagbug's [comment](https://github.com/MahApps/MahApps.Metro/issues/1620#issuecomment-65072244):

> The flyouts heavily depend on the hosting `MetroWindow` for various things, so this isn't possible currently

**Comment by punker76** [comment]
@maciz84 I think Flyouts should live at the Window level. You can access Flyouts with MVVM from UserControls. If you need a easier way to do this then you can use the [TinyLittleMvvm](https://github.com/thoemmi/TinyLittleMvvm) from @thoemmi which contains a easy interface for this.

**Comment by maciz84** [comment]
Fair enough I won't ask this question again. Thank you guys
