### ISSUE TITLE
Tiny cosmetical bug

### ISSUE THREAD

**Issue by Prodigio** [MahApps/MahApps.Metro#2717]
It's just a really tiny UI bug. But small issues are important as well. :)

Open a drop down menu with more than one item. Hit Tab so a dashed border will appear around an item. Hit enter to select it. The drop down will collapse again and the dashed border will stay. If you now hover with your mouse over the arrow, so that it'll change it's color, the mouse over color and the dashed border touch each other.

--
### Environment

- MahApps.Metro v1.2.4.0
- Windows 7
- Visual Studio 2012
- .NET Framework 4.5.2

**Comment by punker76** [comment]
@Prodigio Do you mean a ComboBox?

**Comment by punker76** [comment]
@Prodigio Please try v1.3.0

**Comment by Prodigio** [comment]
@punker76 Yes I meant the ComboBox. I tried v1.3.0; issue is still present.

Here's a picture of it.
[http://pasteboard.co/kqozXb2CJ.png](url)

**Comment by punker76** [comment]
@Prodigio This is not a bug, it's a feature... the FocusVisualStyle. It's normal behavior of a ComboBox...

![2016-10-28_16h23_23](https://cloud.githubusercontent.com/assets/658431/19809745/e29a01c2-9d2a-11e6-93c6-00bb9ec5e109.png)

![2016-10-28_16h23_32](https://cloud.githubusercontent.com/assets/658431/19809746/e3ee50be-9d2a-11e6-8f74-ed2c0be938e9.png)

**Comment by Prodigio** [comment]
@punker76 Well my picture is looking different to yours.

**Comment by punker76** [comment]
@Prodigio The screenshots are from a normal Combobox. But the v1.3.0 MahApps style looks similar. It seems yours is from 1.2.4?

**Comment by punker76** [comment]
@Prodigio It could also a inner Control imside DataTemplate that get the focus

**Comment by Prodigio** [comment]
@punker76 Mine is from a normal ComboBox too. Unfortunately no, it's v.1.3.0.

Back to german: Es ist direkt nach dem Grid eingefügt. Kein DataTemplate o.ä. umschweift es.

**Comment by punker76** [comment]
@Prodigio You can prevent this focus style by setting `FocusVisualStyle="{x:Null}"` on the Combobox.
