### ISSUE TITLE
DateTimePicker combo boxes not populating on Edit Template

### ISSUE THREAD

**Issue by yeasin90** [MahApps/MahApps.Metro#2718]
## What steps will reproduce this issue?

Added DateTimePicker. 
```
<UserControl x:Class="MainModule.Views.Utility.DateTimePickerControl"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
             xmlns:Controls="clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro"
             mc:Ignorable="d">
    <Controls:DateTimePicker 
                             Background="Transparent"
                             HandVisibility="{Binding SelectedItem, ElementName=DateTimePickerHandVisibility, Mode=TwoWay}"
                             IsClockVisible="{Binding IsChecked, ElementName=DateTimePickerIsClockVisible, Mode=TwoWay}"
                             IsEnabled="{Binding IsChecked, ElementName=DateTimePickerIsEnabled, Mode=TwoWay}"
                             IsReadOnly="False"
                             Orientation="{Binding SelectedItem, ElementName=DateTimePickerOrientation, Mode=TwoWay}"
                             PickerVisibility="{Binding SelectedItem, ElementName=DateTimePickerPickerVisibility, Mode=TwoWay}" 
                             Controls:TextBoxHelper.UseFloatingWatermark="False" />
</UserControl>
```
Edit default template of DateTimePicker : 
![untitled](https://cloud.githubusercontent.com/assets/8789577/19808298/0cdc4024-9d46-11e6-9508-01c8a6c81d1e.png)

When I ran project, Hour-Minute-Second combobox is not working (I didn't changed anything in the generated template) : 

![untitled2](https://cloud.githubusercontent.com/assets/8789577/19808431/a91d4eec-9d46-11e6-8e63-68404b475d13.png)

### Expected outcome

Hour-Minute-Second combobox suppose to be populated (I did not changed anythings inside generated template)

--
### Environment

- MahApps.Metro __v1.3.0__
- Windows __10__
- Visual Studio __2015__
- .NET Framework __4.5__

**Comment by punker76** [comment]
@yeasin90 I don't know what Blend is doing here. But you can grab the style from this file https://github.com/MahApps/MahApps.Metro/blob/develop/src/MahApps.Metro/MahApps.Metro/Themes/DateTimePicker.xaml

**Comment by yeasin90** [comment]
@punker76 thanks for the solution, getting a build error :( :(
![untitled3](https://cloud.githubusercontent.com/assets/8789577/19809355/c9892850-9d4a-11e6-802c-5eecacaa6548.png)

**Comment by punker76** [comment]
@yeasin90 uups, it's internal, I'll change this. but maybe you don't need completely re-style the control, so delete the Controltemplate stuff...

**Comment by yeasin90** [comment]
@punker76 OK, thanks :) . Adding the style solved the issue.  Probably Blend generates something which was conflicting
