### ISSUE TITLE
ShowMessageAsync Bounds issue

### ISSUE THREAD

**Issue by boatschl** [MahApps/MahApps.Metro#2719]
## What steps will reproduce this issue?

First of all I love your work, its awesome!
I frequently use ShowMessageAsync() for popups. 
Today I noticed that if you have a window (not maximized) and move said window out of the visible screen, the popup still takes the window's width as its size, but is moved into the visible part of the screen.
Happens when moving the window out in Y direction as well.
### Expected outcome

I'd expect the popup to still be centered within the window instead of always displaying the control on screen.
## 
### Environment
- MahApps.Metro 1.3.0
- Windows 10
- Visual Studio 2015
- .NET Framework 4.5

**Comment by punker76** [comment]
@boatschl Do you mean the external Message? Can you make a screenshot?

**Comment by boatschl** [comment]
Hi,
here is the screenshot: http://imgur.com/a/ApNpy
I moved the main window 50% out of the screen to the right, thus you see parts of my desktop. I use this code:

private static MahApps.Metro.Controls.MetroWindow Wnd()
{
    return System.Windows.Application.Current.MainWindow as MahApps.Metro.Controls.MetroWindow;
}
public static Task<MessageDialogResult> ShowMessageBoxOkCancel_Async(string message, string title)
{
    return Wnd().ShowMessageAsync(title, message, MessageDialogStyle.AffirmativeAndNegative);
}

**Comment by punker76** [comment]
@boatschl but your screenshot uses the external variant of the message dialog... cause I cannot reproduce this issue with the normal message box which is always shown inside the window.

**Comment by punker76** [comment]
@boatschl Any news?
