### ISSUE TITLE
Problem With Flat Button Animation

### ISSUE THREAD

**Issue by TheBottleGit** [MahApps/MahApps.Metro#2728]
## What steps will reproduce this issue?

I change background and foreground for a flat button.

### Expected outcome

Animation don't work.

How to make animation like a flat button?
--
### Environment

- MahApps.Metro __v1.4.0-ALPHA026__
- Windows __10__
- Visual Studio __2015__
- .NET Framework __4.5__

**Comment by TheBottleGit** [comment]
Template:
```
<Controls:MetroWindow.Resources>
        <ControlTemplate x:Key="ButtonTemplate" TargetType="Button">
            <Border Background="#2FA9E2" TextBlock.Foreground="{DynamicResource WhiteBrush}">
                <ContentPresenter VerticalAlignment="Center" HorizontalAlignment="Center">
                </ContentPresenter>
            </Border>
        </ControlTemplate>
    </Controls:MetroWindow.Resources>
```

App.xaml : `<ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/FlatButton.xaml" />`

**Comment by punker76** [comment]
@TheBottleGit If you mean the mouse over action, then it seems this is a bug for the button itself. I found this and can confirm that it's not working if you set the Background on the Button itself. [MSDN link](https://social.msdn.microsoft.com/Forums/vstudio/en-US/bfb9d5d0-c526-4c34-b675-84020d2de189/buuton-ismouseover-trigger-not-working?forum=wpf) Craziness, yes. 

This works sample works for me™

```xaml
        <Button Content="Test"
                Width="100"
                FontSize="28"
                Foreground="WhiteSmoke"
                HorizontalAlignment="Center"
                VerticalAlignment="Center"
                FontWeight="Light">
            <Button.Style>
                <Style TargetType="{x:Type Button}"
                       BasedOn="{StaticResource MetroFlatButton}">
                    <Setter Property="Background" Value="Crimson" />
                </Style>
            </Button.Style>
        </Button>
```
