### ISSUE TITLE
NumericUpDown Parent Click Event

### ISSUE THREAD

**Issue by alinateghi** [MahApps/MahApps.Metro#2732]
Hello

I used this control in a button. Button has click event so when i try to use up/down buttons, button event fired too. also when i touch other part this issue happen expected the textbox of it.

So, how can prevent parent event ?!

Thanks,
Ali
- MahApps.Metro __v1.3__

**Comment by punker76** [comment]
@alinateghi You can handle/prevent this at the Button's click event.

```csharp
private async void ButtonClick(object sender, RoutedEventArgs e)
{
    if (e.OriginalSource != sender)
    {
        // do nothing if clicked the ToggleSwitch
        e.Handled = true;
    }
    else
    {
        // handle the button click action
        await this.ShowMessageAsync(string.Empty, "Yeah, you clicked the real button!");
    }
}
```

![buttonclick2](https://cloud.githubusercontent.com/assets/658431/19946817/bcdf6f7a-a145-11e6-9657-f969b02486ce.gif)
