### ISSUE TITLE
Flyout IsPinned = False

### ISSUE THREAD

**Issue by Trakcf** [MahApps/MahApps.Metro#2733]
When a Flyout is not pinned clicking elsewhere in the window will close the Flyout but the click event is captured and not passed on to the button or textbox or what have you that is being clicked.

I think [#1517](https://github.com/MahApps/MahApps.Metro/issues/1517) was about this same issue but it never really got resolved.  In FlyoutsPreviewMouseDown it has "e.Handled = true;"  which seems to be the culprit, I tried commenting those Handleds out and everything seems to function fine but I was unsure if there was some reason why that event was being handled in there that would be impacted by removing it.  Any idea?

--

- MahApps.Metro v1.4.0-ALPHA026
- Windows 7
- Visual Studio 2015
- .NET Framework 4.6.1

**Comment by punker76** [comment]
@Trakcf Can you maybe create a short sample which demonstrates this issue? I checked the sample at the Flyout demo and can't reproduce this one... thx!

**Comment by Trakcf** [comment]
I just added the "flyout.IsPinned = false;" line to ToggleFlyout in the demo so it is now
```
private void ToggleFlyout(int index)
        {
            var flyout = this.Flyouts.Items[index] as Flyout;
            if (flyout == null)
            {
                return;
            }
            flyout.IsPinned = false;
            flyout.IsOpen = !flyout.IsOpen;
        }
```

Then in the flyouts demo window alternate clicking on Show 1 and Show 3, with the current code the progression goes: Click Show 1 -> Flyout 1 Displays -> Click Show 3 -> Flyout 1 Hides -> Click Show 3 Again -> Flyout 3 Displays.

The Show 3 button click is getting swallowed making you click it twice.

With the e.Handled commented out it goes: Click Show 1 -> Flyout 1 Displays -> Click Show 3 -> Flyout 1 Hides and Flyout 3 Displays.

**Comment by punker76** [comment]
@Trakcf You should  use and set `IsPinned="False"` in Xaml or in code behind if you create a Flyout completely there.

**Comment by Trakcf** [comment]
I just put it there for ease in example.  Putting the IsPinned in the Xaml has the same results when testing with and without the Handled.  I can come up with a full example later if you want one all in the xaml.

**Comment by Trakcf** [comment]
OK, I just gutted the FlyoutDemo.xaml file since I figured you would have that around for easy testing, replaced all the body of the MetroWindow with as follows,

```
<Controls:MetroWindow.Flyouts>
        <Controls:FlyoutsControl x:Name="flyoutsControl">
            <Controls:Flyout
                             Width="300"
                             Header="Flyout 1"
                             IsPinned="False"
                             Position="Right">
            </Controls:Flyout>
            <Controls:Flyout
                             Width="150"
                             Header="Flyout 2"
                             IsPinned="False"
                             Position="Right">
            </Controls:Flyout>
        </Controls:FlyoutsControl>
    </Controls:MetroWindow.Flyouts>
    <Grid>
        <StackPanel Margin="5"
                    HorizontalAlignment="Left">
            <Button Margin="2"
                    Command="{Binding ElementName=flyoutsDemo, Path=OpenFirstFlyoutCommand}"
                    Content="Show 1" />
            <Button Margin="2"
                    Click="ShowSecond"
                    Content="Show 2" />
        </StackPanel>
    </Grid>
```

Current version goes
Click Show 1 and Flyout 1 Displays
Click Show 2 and Flyout 1 Dissapears (only FlyoutsPreviewMouseDown handles the event)
Click Show 2 again and Flyout 2 Displays

e.Handled in FlyoutsPreviewMouseDown commented out goes
Click Show 1 and Flyout 1 Displays
Click Show 2 and Flyout 1 Dissapears and Flyout 2 Displays

You can even see in the current version when you click "Show 2" that the border never goes black around that button since the mousedown event doesn't ever get to it.

Hopefully I am explaining it well enough.

**Comment by punker76** [comment]
->#2744
