### ISSUE TITLE
Failure to compile the project (Version 1.3.0.0) with Visual Studio

### ISSUE THREAD

**Issue by boukenka** [MahApps/MahApps.Metro#2736]
Hello,

I have downloaded MahApps.Metro.1.3.0.0.nupkg and Source code (zip).
I am using Windows 7 and Visual Studio 2013.
.NET Framework 4.0, 4.5, 4.5.1, 4.5.2, 4.6 and 4.6.1 are installed.

I have opened the project from the ZIP and install the package (nupkg) without problem.
When I try to build the project, I get 68 errors and 1 warning (The 'packages' element is not declared).
I get that type of error during compilation:
A) ValidationResult(false, $"The price {album.Price} of the album '{album.Title}' by '{album.Artist.Name}' is too much!") ==> Unexpected character '$' for the error (class AlbumPriceIsTooMuchConverter)
B) bindingGroup?.Items.OfType<Album>().ElementAtOrDefault(0);  ==> Invalid expression term '.'
C) internal static KeyboardNavigationEx Instance => _instance ?? (_instance = new KeyboardNavigationEx()); ==> Invalid token '??' in class, struct, or interface member declaration (class KeyboardNavigationEx)

Could you help / guide me so I can compile and make run the project please.

PS: Files were downloaded from here: https://github.com/MahApps/MahApps.Metro/releases/tag/1.3.0

**Comment by punker76** [comment]
@boukenka You need VS 2015 if you want to use C# 6 features. You can take the Community edition -> it's free

**Comment by boukenka** [comment]
Thanks for the answer. I have installed VS2015 and install the package.
But now I am getting other type of errors.

Error	CS0121	The call is ambiguous between the following methods or properties: 'MahApps.Metro.Controls.Extensions.BeginInvoke(System.Windows.Threading.DispatcherObject, System.Action, System.Windows.Threading.DispatcherPriority)' and 'MahApps.Metro.Controls.Extensions.BeginInvoke(System.Windows.Threading.DispatcherObject, System.Action, System.Windows.Threading.DispatcherPriority)'	MahApps.Metro.NET45

**Comment by boukenka** [comment]
I have a total of 265 errors and 1615 warnings. Could you please let me know how to solve it please.

**Comment by boukenka** [comment]
Hello, Is there someone who could answer to me?

**Comment by punker76** [comment]
@boukenka It looks like you referenced the compiled dll and the source project in your solution. Make sure you do only one of them.

**Comment by boukenka** [comment]
Thanks. It is solving the issue.

I have just a remark. When the 'MahApps.Metro.1.3.0.0.nupkg' package is applied, it creates reference of 'MahApps.Metro' in the 'MahApps.Metro.NET45' project.
![metro package](https://cloud.githubusercontent.com/assets/16502423/20059281/b794414a-a4f5-11e6-8924-7f03ccbd6ebe.png)

**Comment by punker76** [comment]
@boukenka You don't need the Nuget package if you compile the source of MahApps.
