### ISSUE TITLE
Design for textbox

### ISSUE THREAD

**Issue by boukenka** [MahApps/MahApps.Metro#2737]
Hello,

Since the release of 1.3.0, the textboxes have in their low border (horizontal) like a shadow.
It was not present before (in the 1.2.4). How can I make that this change of design for 
textbox is no present (meaning that the 'shadow' is removed)? I have put a 'RED' color to show it (Normally the original color replaced by the 'RED' is E5E5E5) 
![textbox](https://cloud.githubusercontent.com/assets/16502423/20066385/ad82ece4-a511-11e6-9b01-b028b8a57870.png)

The first textbox has the XAML coding: <TextBox HorizontalAlignment="Left" Margin="100,10,10,10" Height="23" Text="12345" />
The second textbox has the XAML coding: <TextBox HorizontalAlignment="Left" Height="23" Margin="156,40,0,0" VerticalAlignment="Top" Width="180" Text="1234" />
As soon there is the "VerticalAlignment" property, the "shadow" is displayed. Is it a bug? Or is there a solution not to have it?

**Comment by boukenka** [comment]
I wanted to update my application with the last version (from 1.2.4 to 1.3.0). But with that problem, I will wait until there is a solution for the 'shadow' border of the textbox.

**Comment by punker76** [comment]
@boukenka Can you maybe post a little bit more Xaml code around your TextBox?

**Comment by boukenka** [comment]
Hello,

Here is a project to reproduce the problem. Hope it helps.
PS: Please rename 'TXT' to 'zip'.


[Metro130.TXT](https://github.com/MahApps/MahApps.Metro/files/583771/Metro130.TXT)

**Comment by punker76** [comment]
@boukenka I got it and will fix it in 1.4

**Comment by punker76** [comment]
@boukenka The fix will be available in 1.4.0

**Comment by boukenka** [comment]
@punker76 Thank you
