### ISSUE TITLE
Mahapps icons

### ISSUE THREAD

**Issue by sagevpremium** [MahApps/MahApps.Metro#2738]
Hi, 

i don't know how to dynamic change icons in <Controls:MetroWindow.LeftWindowCommands>.

I have somethink like that:

` <Rectangle.OpacityMask>
                            <VisualBrush Stretch="Fill" Visual="{Binding myIcon}" />
                        </Rectangle.OpacityMask>`

But how change it in ViewModel?

Thx for help :)

**Comment by Evangelink** [comment]
Which version of MahApps are you using?
I would not recommend doing a binding like this because it will force your ViewModel to expose a property with a strong view type. Instead I would recommend to expose a property of some enum type and use a converter to map the enum value to some icon.

**Comment by punker76** [comment]
@sagevpremium @Evangelink I would recommend to use the IconPacks :-D More power in an easy way https://github.com/MahApps/MahApps.Metro.IconPacks

**Comment by punker76** [comment]
@sagevpremium With the IconPacks you can have a property in your ModelView with where you can bind and the set a different Icon with the give enum kind.
