### ISSUE TITLE
InteropDemo - WindowsFormsHost - Win7Aero flicker

### ISSUE THREAD

**Issue by Lillifee** [MahApps/MahApps.Metro#2739]
Hello,

first of all thx for the MahApps it's really great!
I was searching a while but i think I've found the issue which causes me transparent flicker in the interop demo while resizing with the Windows 7 Aero theme. I already saw the solution from DwayneNeed with the interop:AirspaceDecorator and some posts.. but i want to go for the first solution in from issue 1093.

It seems that the animations in the MainWindow - SliderProgressExamples fix the flicker in the InteropDemo. 

If i comment these lines in the MainWindow.xaml line 243 - 245
>              

Use Window7 Aero Themes.
Start the solution WITHOUT debugger attached (VS2015).
And resize the interop window - flickers transparent..
 
Adding an random animation to the window also reduces this flickering...
Is there another clean solution than adding several animations behind the WindowsFormsHost?

Thanks a lot

Environment
- Windows 7 - Aero Theme
- Visual Studio 2015
- .NET Framework 4.5

**Comment by punker76** [comment]
@Lillifee Adding/using animations is not the solution to avoid flickering with WindowsFormsHost or WebBrowser. So please use the DwayneNeed dll. I will update the Interop demo with this one.

**Comment by punker76** [comment]
@Lillifee FAQ is now updated https://github.com/MahApps/MahApps.Metro/wiki/FAQ
