### ISSUE TITLE
show PasswordBox content

### ISSUE THREAD

**Issue by omp-git** [MahApps/MahApps.Metro#2740]
I use PasswordBox control in my login form.
but i dont able to show it`s content 
i use PasswordChar = '\0'; not work Correctly
does Material Design have tools for show password box characters ?

**Comment by punker76** [comment]
@omp-git You can show a Password in clear text with the `MetroButtonRevealedPasswordBox` or `Win8MetroPasswordBox` style.

**Comment by VeronicaGeek** [comment]
Hey - I'm trying to use the 'MetroButtonRevealedPasswordBox' and can insert it no problem. However, when clicking on the eye to reveal, the _"stars"_ are still showing...

![revealpwdbox_charatersissue](https://user-images.githubusercontent.com/25181757/48262485-90894d00-e41a-11e8-9279-49e1880bbe7c.png)

Tried on 2 diff computers but same issue.
Nothing special in my XAML code, just 'Watermarks' and 'ClearTextButton'

Thanks

**Comment by VeronicaGeek** [comment]
@punker76 I'm using MahApps 1.6.5 and my project is on .NET Framework 4.5.2

**Comment by punker76** [comment]
@VeronicaGeek Can you show me your Xaml code for the password box? I tested it with the following lines and doesn't see this issue:

```xaml
<PasswordBox Controls:TextBoxHelper.ClearTextButton="True"
             Controls:TextBoxHelper.Watermark="Revealed PasswordBox"
             Style="{StaticResource MetroButtonRevealedPasswordBox}" />
```

![2018-11-09_16h03_11](https://user-images.githubusercontent.com/658431/48269917-056b7f80-e439-11e8-88ad-2b72a842fa40.png)

![2018-11-09_16h03_30](https://user-images.githubusercontent.com/658431/48269923-08667000-e439-11e8-9158-bf4e2f3d70ac.png)

**Comment by VeronicaGeek** [comment]
@punker76  Sure
`<PasswordBox x:Name="AdminPwdTextbox" HorizontalAlignment="Left" Margin="1505,50,-1435,0" VerticalAlignment="Top" Width="230"  Controls:TextBoxHelper.Watermark="Enter your Global Admin password" Controls:TextBoxHelper.ClearTextButton="True" Style="{StaticResource MetroButtonRevealedPasswordBox}" Height="21" PasswordChar="*"/>`

**Comment by GreatFireWall** [comment]
Is it possible to keep password visible (cleartext) without press the "eye button" ?

**Comment by timunie** [comment]
@GreatFireWall,

please ask questions like this in the future on gitter or StackOverflow. 
You can override the Style (get it here: https://github.com/MahApps/MahApps.Metro/blob/develop/src/MahApps.Metro/Styles/Controls.PasswordBox.xaml ) to match your needs. But I think this is not what a `PasswordBox` should do 

Happy coding
Tim

**Comment by Vishal708** [comment]
RevealButtonContentTemplate is this property can we use in Dot net Core 3.0 ?

**Comment by timunie** [comment]
Hi @Vishal708 ,
yes you can use this Style but in the latest pre-release (which you need to target .NET Core3.x) the Key changed to `MahApps.Styles.PasswordBox.ButtonRevealed` 
See:  https://github.com/MahApps/MahApps.Metro/blob/00c221bbc57fda4f9d48cce486eee9425d4b6b0c/src/MahApps.Metro/Styles/Controls.PasswordBox.xaml#L577 

Happy coding
Tim
