### ISSUE TITLE
AutoComplete TextBox

### ISSUE THREAD

**Issue by Rivolvan** [MahApps/MahApps.Metro#2741]
Is there a way to add autocomplete functionality to the MahApps TextBox by using attached properties? Because if I will use another framework just for this, i think it's overkill and the style will not be coherent with MahApps.

--
### Environment

- MahApps.Metro v1.3.0
- Windows 10
- Visual Studio 2015
- .NET Framework 4.5.1

**Comment by thoemmi** [comment]
Thanks for your request, this was already asked in #2625.
