### ISSUE TITLE
non reloading mtero tab controls

### ISSUE THREAD

**Issue by jmecosta** [MahApps/MahApps.Metro#2743]
Hi,

i am using a metro tab control, works really well. Now i have added a Cef control to one of the tabs so i can display some html pages on it.

Now when i change tabs, the content of each tab is reloaded locking out the ui when it reloads. I have implemented this: http://stackoverflow.com/questions/9794151/stop-tabcontrol-from-recreating-its-children

But from the code

```
    /// <summary>
    /// Get the ItemsHolder and generate any children
    /// </summary>
    public override void OnApplyTemplate()
    {
        base.OnApplyTemplate();
        ItemsHolderPanel = GetTemplateChild("PART_ItemsHolder") as Panel;
        UpdateSelectedItem();
    }
```

It always return null for PART_ItemsHolder, i tried to see this part in the Visual Tree but did not find such thing there. Is Mahapps somehow changing that, and if so what would be the correct part that i should hook up the ItemsHolderPanel

Thanks in advance

Best Regards
Jorge Costa

**Comment by punker76** [comment]
@jmecosta You need to re-style the TabControl style like in http://stackoverflow.com/a/9802346/920384 for the MahApps one. Cause the `PART_ItemsHolder´ is not the default name for the TabControl style. I will enhance the `TabControlEx` in [ControlzEx](https://github.com/ControlzEx/ControlzEx) to make it possible that it works for different styles too...

**Comment by jmecosta** [comment]
@punker76 thanks for the help, i will keep an eye on controlzEx for your chnages
