### ISSUE TITLE
Flyout IsPinned = False/True

### ISSUE THREAD

**Issue by avechuche** [MahApps/MahApps.Metro#2744]
## What steps will reproduce this issue?

1) When IsPinned="False" and ExternalCloseButton="Left", two clicks are required to give focus to a control (textbox in this case), 1 to close flyout, and 1 to focus control.

2) When "IsPinned = True", and a control has the focus, when the flyout automatically close, the control loses focus.

### Expected outcome

1) Is it possible that with a 1 click, close the flyout and focus on the control?

2) When closing the flyout, the control that has the focus, do not lose it.

Example
Change ".jpg" to ".zip"

![ispinned](https://cloud.githubusercontent.com/assets/11781418/20199428/138669ca-a789-11e6-955c-9d29b6495641.jpg)

--
### Environment

- MahApps.Metro 1.3.0
- Windows 8.1 Update 3 x64
- Visual Studio 2016
- .NET Framework 4.5

**Comment by Trakcf** [comment]
1 is the same as my [#2733](https://github.com/MahApps/MahApps.Metro/issues/2733)
Handled needs to not be set when mouse is clicked outside the flyout, what needs to change is as follows but I had just wanted to check and see if that Handled was in there for any specific reason.

```
if (Flyouts.OverrideExternalCloseButton == null)
            {
                foreach (var flyout in Flyouts.GetFlyouts().Where(x => x.IsOpen && x.ExternalCloseButton == e.ChangedButton && (!x.IsPinned || Flyouts.OverrideIsPinned)))
                {
                    flyout.IsOpen = false;
                    //e.Handled = true;
                }
            }
            else if (Flyouts.OverrideExternalCloseButton == e.ChangedButton)
            {
                foreach (var flyout in Flyouts.GetFlyouts().Where(x => x.IsOpen && (!x.IsPinned || Flyouts.OverrideIsPinned)))
                {
                    flyout.IsOpen = false;
                    //e.Handled = true;
                }
            }
```

**Comment by Kumar2Harsh** [comment]
when we make IsPinned =false or true
there is no effect in flyout
