### ISSUE TITLE
Why change App Style in Flyout if the theme Adapt is chosen?

### ISSUE THREAD

**Issue by Anapher** [MahApps/MahApps.Metro#2745]
I don't get why this line is necessary:
https://github.com/MahApps/MahApps.Metro/blob/develop/src/MahApps.Metro/MahApps.Metro.Shared/Controls/Flyout.cs#L355

It just changes the current theme to the current theme. My problem is that i made my own themes and this is destroying everything because it overrides my theme. Would it be possible to remove that line?

**Comment by punker76** [comment]
@Alkalinee Woul dbe nice if you can test the latest source or/and the upcoming 1.5.0

**Comment by punker76** [comment]
This should work in v1.6.0 since the Dialog and Flyout controls try to find the current theme. So a custom theme or accent wont be override anymore.
