### ISSUE TITLE
Image/Icon on showMessageAsync

### ISSUE THREAD

**Issue by balbinott** [MahApps/MahApps.Metro#2747]
Im sorry for posting this here...
Is possible to load a image/icon on a ShowLoginAsync for example ? Like if was the title ?
thanks in advance and congratulations for this awesome toolkit!

**Comment by thoemmi** [comment]
MahApps.Metro provides a couple of standard dialogs, like Input, Login, Message or Progress. If you want to diverge from the defaults, you have to create your own custom dialog. Nevertheless you can take the default dialogs as a template.
