### ISSUE TITLE
Race condition in ShowMetroDialogAsync/HideMetroDialogAsync

### ISSUE THREAD

**Issue by magla42** [MahApps/MahApps.Metro#2753]
## What steps will reproduce this issue?
We have a MetroDialog that when closed triggers an asynchronous operation that causes another MetroDialog to briefly get shown and then removed again. 
_Flashing dialogs like that is of course not a desireable behavior on our applications part and we are on it, but it uncovered a race condition in MahApps that I think ought to be fixed._

Depending on timing in ShowMetroDialogAsync and HideMetroDialogAsync, sometimes the original dialog is never removed from screen and that call to HideMetroDialogAsync never completes.

We have tracked down the problem to BaseMetroDialog._WaitForCloseAsync(), where the closingStoryboard.Completed event is never triggered, so the task never completes. 
_I would guess the storyboard is interrupted or suchlike due to the moving around of the dialog in the visual tree (metroActiveDialogContainer <--> metroInactiveDialogContainer)?_

A workaround is to set DialogSettings.AnimateHide=false on the dialog (a related issue seems to be #2735).

--
### Environment

- MahApps.Metro __v1.3.0__
- Windows __10__
- Visual Studio __2015__
- .NET Framework __4.6__

**Comment by punker76** [comment]
@magla42 Can you create a short repo which shows exactly this issue?

**Comment by magla42** [comment]
I think I can do that. Probably won't be today though...

**Comment by magla42** [comment]
Here is a very small project that on my computer easily repeats the problem. 
[MahAppsRace.zip](https://github.com/MahApps/MahApps.Metro/files/624471/MahAppsRace.zip)

You open a CustomDialog with the button in the title bar, and when you close the dialog another CustomDialog is shown a (ridicilously) short time while the first dialog is closing. Almost every time this causes the HideMetroDialogAsync of the first dialog to never complete and the dialog to remain visible.
