### ISSUE TITLE
MetroAnimatedTabControl first tab font not changing

### ISSUE THREAD

**Issue by ToMer-K** [MahApps/MahApps.Metro#2755]
## What steps will reproduce this issue?
When using MetroAnimatedTabControl and specifying a font in the FontFamily property the first tab has the default font instead of the new font.   In the designer window all the tabs have the new font, the problem is at execution time.   For example:
```
<controls:MetroAnimatedTabControl x:Name="tabControl" Grid.Column="1" HorizontalAlignment="Left" Height="100" Grid.RowSpan="2" VerticalAlignment="Top" FontFamily="Bauhaus 93" controls:TabControlHelper.IsUnderlined="True">
                <controls:MetroTabItem Header="TabItem2">
                    <Grid Background="#FFE5E5E5"/>
                </controls:MetroTabItem>
                <controls:MetroTabItem Header="TabItem2">
                    <Grid Background="#FFE5E5E5"/>
                </controls:MetroTabItem>
                <controls:MetroTabItem Header="TabItem2">
                    <Grid Background="#FFE5E5E5"/>
                </controls:MetroTabItem>                
</controls:MetroAnimatedTabControl>
```

### Expected outcome
![image](https://cloud.githubusercontent.com/assets/18401157/20655980/510b44fc-b4ed-11e6-8e1d-bb7652ed5be6.png)

### Environment

- MahApps.Metro v1.3.0
- Windows 8.1 64bit
- Visual Studio 2015
- .NET Framework   #4.5.2

**Comment by punker76** [comment]
@ToMer-K This is fixed now and will be available in 1.4.0
