### ISSUE TITLE
Checkmark in ContextMenu MenuItem not rendering

### ISSUE THREAD

**Issue by chrism00ch** [MahApps/MahApps.Metro#2757]
## What steps will reproduce this issue?

To reproduce this issue, I created a simple project containing a window with a button and a context menu. For each menu item in the context menu, I set the IsCheckable property to true. The properties are properly set with MenuItem clicks, however, the check mark is not rendered when IsChecked is set to true. I've attached the project where I reproduced the issue.
[ContextMenuCheckmarkIssue.zip](https://github.com/MahApps/MahApps.Metro/files/628321/ContextMenuCheckmarkIssue.zip)

### Expected outcome

The checkmark simply needs to render properly. There is a Geometry object in Styles/Controls.ContextMenu.xaml that supposedly defines the checkmark. It seems as though that is the issue, but I'm not very familiar with the Geometry object to determine with certainty

--
### Environment

- MahApps.Metro __v1.3.0__
- Windows __10__
- Visual Studio __2015 Community Edition__
- .NET Framework __4.5.2__

**Comment by chrism00ch** [comment]
I was able to get the check mark to show up by changing the Fill Property of the GlyphPanel to Black from UnsetValue using Snoop. I am unsure why, but the CheckMarkFill DynamicResource is not being set properly.

**Comment by chrism00ch** [comment]
I was able to work around this issue by manually setting the application scope resource to a brush that I desired. A possible production ready solution until this is fixed would be to create a static class that edited resources wherever the application entry point was.

``
Application.Current.Resources["CheckmarkFill"] = Brushes.Black;
``

**Comment by punker76** [comment]
@chrism00ch You forgot to add the complete MahApps resources. https://github.com/MahApps/MahApps.Metro#a-short-how-to
Maybe you not followed the quick start guide http://mahapps.com/guides/quick-start.html

So with these resources your problem should be fixed.

```xaml
<Application x:Class="WpfApplication.App"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             StartupUri="MainWindow.xaml">
  <Application.Resources>
    <ResourceDictionary>
      <ResourceDictionary.MergedDictionaries>
        <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
        <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
        <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Colors.xaml" />
        <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/Blue.xaml" />
        <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/BaseLight.xaml" />
      </ResourceDictionary.MergedDictionaries>
    </ResourceDictionary>
  </Application.Resources>
</Application>
```

![2016-12-03_21h38_03](https://cloud.githubusercontent.com/assets/658431/20862057/cd7f90da-b9a0-11e6-80bc-4d02ea3eeb11.png)
