### ISSUE TITLE
DatePicker SelectionBackground doesn't match accent color

### ISSUE THREAD

**Issue by chrisklepeis** [MahApps/MahApps.Metro#2760]
I have my accent color set to Steel. When set to steel, and text is selected in a TextBox, the SelectionBackground is changed from the default WPF uses. 

When selecting the date text in a DatePicker, using the steel account color, the SelectionBackground remains blue.

I think the expected behavior is that the DatePickers SelectionBackground would match the set accent color theme.

**Comment by punker76** [comment]
@chrisklepeis This will be available in 1.4.0 (and pre-release)
