### ISSUE TITLE
Flyout - Strange issue with a listview

### ISSUE THREAD

**Issue by anthony1969** [MahApps/MahApps.Metro#2766]
Hi,
installing the new version of MahApps i've find a very strange behaviour while using a usercontrol that simply contains a listview. The content of the flyout look like this:

            <mhControls:Flyout Position="Top" IsOpen="{Binding IsOpen}" IsModal="False" Theme="Accent" Margin="0,17,0,0">
                <StackPanel Orientation="Vertical">
                    <TextBlock Text="My sources list" FontSize="24" Padding="0,10">
                        <TextBlock.Effect>
                            <DropShadowEffect ShadowDepth="3" />
                        </TextBlock.Effect>
                    </TextBlock>
                    <uc:ucAvailableSource Padding="0,30" BorderBrush="Silver" BorderThickness="0,2" x:Name="_availableSrc">
                        <i:Interaction.Triggers>
                            <i:EventTrigger EventName="onSelectionChanged">
                                <i:InvokeCommandAction Command="{Binding AvailableSourceSelectedCommand}" CommandParameter="{Binding SelectedItem, ElementName=_availableSrc}" />
                            </i:EventTrigger>
                        </i:Interaction.Triggers>
                    </uc:ucAvailableSource>
                </StackPanel>
            </mhControls:Flyout>
--

What's happens is that when opening the Flyout the list was empty....if i put the same control outside the flyout all works fine, and using the previuos version of MahApps (1.2.4) works fine too.
Any idea ?

- MahApps.Metro __v1.3.0__
- Windows __10__
- Visual Studio __2013__
- .NET Framework __4.6.1__

**Comment by punker76** [comment]
@anthony1969 can you test the latest pre-release too? Thx
