### ISSUE TITLE
Increase Win10 ToggleSwitch Default Margins

### ISSUE THREAD

**Issue by RichiCoder1** [MahApps/MahApps.Metro#2770]
Increase the Header and Content default margins up from 2 & 3 to something closer to 9 to match the spacing on Windows 10 toggles.

![Example](https://i.imgur.com/tJgY4jA.png)

**Comment by punker76** [comment]
@RichiCoder1 It's possible with v1.4.2 to change this via `Padding` property. I will change this finally in 1.5.0 or later, cause it's a breaking change (not hard but ui). So do this and you got it...

```xaml
<Style x:Key="Custom.ToggleSwitch.Win10"
       BasedOn="{StaticResource MahApps.Metro.Styles.ToggleSwitch.Win10}"
       TargetType="{x:Type Controls:ToggleSwitch}">
    <Setter Property="Padding" Value="0 0 10 0" />
    <Style.Triggers>
        <Trigger Property="ContentDirection" Value="RightToLeft">
            <Setter Property="Padding" Value="10 0 0 0" />
        </Trigger>
    </Style.Triggers>
</Style>
```
