### ISSUE TITLE
Double Click on title bar of the Metro Window

### ISSUE THREAD

**Issue by tusharjain28** [MahApps/MahApps.Metro#2773]
Double Click on title bar of the Metro Window

When i double click on the  title bar of the Metro Window, the window resizes

### Expected outcome

The Metro window should not resize on double click on the  title bar of the Metro Window

I have the code to use the windows Hook (Win32 API) to disable resizing but that code disables it for both double click on the  title bar of the Metro Window  as well as the Standard restore button

My requirement is that i still need to resize when i click on the standard restore button 
--
### Environment

- MahApps.Metro 1.2.4.0
- Windows  10
- Visual Studio 2015
- .NET Framework 4.6.2

Snippet from the Main window XAML:

<Controls:MetroWindow x:Name="LGMainWindow"
                      x:Class="LandisGyr.FieldTools.Leatherman.Main.MainWindow.MainWindow"
                      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                      xmlns:i="http://schemas.microsoft.com/expression/2010/interactivity"
                      xmlns:Command="http://www.galasoft.ch/mvvmlight"
                      xmlns:Controls="clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro"
                       DataContext="{Binding Main, Source={StaticResource Locator}}"
                      IgnoreTaskbarOnMaximize="{Binding  IsMaximized, Mode=TwoWay}" 
                      ResizeMode="CanResizeWithGrip"
                      WindowStartupLocation="CenterScreen"
                       WindowState="Maximized"
                      WindowTransitionsEnabled="False"
                     ShowTitleBar="False"                                         
                      MinWidth="{Binding MinAppWidth}"

**Comment by punker76** [comment]
@tusharjain28 I think this behavior is not common and should not be handled by MahApps. Why do you want to prevent the double click to maximize/restore the window but allow it via the max/restore button?
/cc @thoemmi

**Comment by thoemmi** [comment]
Double-clicking a window's title to maximize it is standard behavior in Windows. Therefore I think @tusharjain28 expected outcome is wrong.

**Comment by tusharjain28** [comment]
Thoemmi,
I know its a standard behaviour in Windows to maximize the application on clicking the title bar, but due to the nature of our application , we wanted to some how restrict it.
Anyhow thanks for your comments, we can close the issue.

**Comment by laurencee** [comment]
For anyone else finding this in the future I put together a behavior to disable this

```C#
using System.Windows;
using MahApps.Metro.Controls;

public static class DisableMetroDoubleClickBehavior
{
    public static readonly DependencyProperty EnabledProperty =
        DependencyProperty.RegisterAttached(
            "Enabled",
            typeof(bool),
            typeof(DisableMetroDoubleClickBehavior),
            new PropertyMetadata(false, OnEnabledChanged));

    public static void SetEnabled(DependencyObject element, bool value)
        => element.SetValue(EnabledProperty, value);

    public static bool GetEnabled(DependencyObject element)
        => (bool)element.GetValue(EnabledProperty);

    private static void OnEnabledChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
        if (!(d is MetroWindow window) || !(bool)e.NewValue)
            return;

        window.Loaded += (s, args) =>
        {
            if (window.Template.FindName("PART_TitleBar", window) is UIElement titleBar)
            {
                titleBar.PreviewMouseLeftButtonDown += (s2, e2) =>
                {
                    if (e2.ClickCount == 2)
                        e2.Handled = true;
                };
            }
        };
    }
}
```

Usage (you'll need to define `local` for whatever namespace you put `DisableMetroDoubleClickBehavior` in)
```xaml
<mah:MetroWindow 
  local:DisableMetroDoubleClickBehavior.Enabled="True">
...
```
