### ISSUE TITLE
I want to make tiles selection like Windows 8 tiles

### ISSUE THREAD

**Issue by Sankey28** [MahApps/MahApps.Metro#2776]
###Problem
I want to change the color of tiles which are selected, but I am not able to Select tiles and add tick mark to them.

### Expected outcome
I want to make Mahapps.Metro tiles look like Windows 8 tiles after selection.
--
### Environment

- MahApps.Metro: V.1.3.0
- Windows: Windows 7
- Visual Studio: VS2015 Community
- .NET Framework: 4.5.2

**Comment by punker76** [comment]
@Sankey28 Can you explain this a little bit more? Maybe with some screenshots or a sample app?

**Comment by Sankey28** [comment]
![temp](https://cloud.githubusercontent.com/assets/24712341/21448109/b5134cc6-c904-11e6-8381-b42c56845ded.png)
These are my tiles. I want to selected multiple tiles, just like Windows 8 tiles shown below.
![windows-8-selecting-multiple-tiles1](https://cloud.githubusercontent.com/assets/24712341/21448110/b513a9b4-c904-11e6-9765-03bb6bd1f5d6.png)

After selecting these tiles, I want to loop through all the Tiles in selected StackPanel and change their background color.
This is the primary requirement.

**Comment by punker76** [comment]
I think you need a ListBox which holds your tiles (which comes from a collection bound to ItemsSource). So you can create a custom Style for the ListBoxItem which shows a Tile and handles the selection and focusing stuff.
