### ISSUE TITLE
FlatSlider does not stretch horizontally

### ISSUE THREAD

**Issue by realies** [MahApps/MahApps.Metro#2777]
Using a FlatSlider style on a slider with `HorizontalAlignment="Stretch"` does not work. Stays fixed to the width property instead.

Can be replicated with `<Slider Style="{StaticResource FlatSlider}" HorizontalAlignment="Stretch" />`

MahApps.Metro 1.3.0-ALPHA186
Win10x64, VS2015, .NET 4.5

**Comment by punker76** [comment]
@realies this is already fixed in finaly 1.3.0
