### ISSUE TITLE
Build demo project with Visual Studio 2017 RC and it reports error.

### ISSUE THREAD

**Issue by yuwenhuisama** [MahApps/MahApps.Metro#2778]
When I use Visual Studio 2017 RC to build demo project it reports error to me, and the component cannot show in the design window correctly either.

--
### Environment

- MahApps.Metro __v1.4.0__
- Windows  10
- Visual Studio 2017RC
- .NET Framework 4.5

**Comment by punker76** [comment]
@yuwenhuisama We should wait for the final release and look if it's working then...
