### ISSUE TITLE
可不可以添加一个grid全选的功能

### ISSUE THREAD

**Issue by wangGuangXu** [MahApps/MahApps.Metro#2781]
不知道基于什么原因，我发现你们外国人好像没有喜欢在Grid上做全选操作，不知道可不可以为中国人设计一个Grid上全选的功能

**Comment by ye4241** [comment]
（你用中文谁会搭理你的啊，我猜你可能问题是DataGrid的全选吧）
自己实在这种个性化的需求的吧，用WPF的CommandBindings。
http://stackoverflow.com/a/9499537

**Comment by wangGuangXu** [comment]
我好奇的是外国人平常不这么操作吗？我其实不在于有人回答我，只要引起外国人重视就可以了。

**Comment by winnerlbm** [comment]
建议将问题翻译为英文之后再发送。



winnerlbm@163.com
 
发件人： 王光旭
发送时间： 2016-12-26 16:18
收件人： MahApps/MahApps.Metro
抄送： Subscribed
主题： Re: [MahApps/MahApps.Metro] 可不可以添加一个grid全选的功能 (#2781)
我好奇的是外国人平常不这么操作吗？我其实不在于有人回答我，只要引起外国人重视就可以了。
