### ISSUE TITLE
EventTrigger in NumericUpDown not work

### ISSUE THREAD

**Issue by avechuche** [MahApps/MahApps.Metro#2782]
## What steps will reproduce this issue?

I need to run a command every time I change the value of numericUpDown. I Try this but I can not make it work.

```
<DataGridTemplateColumn MinWidth="100"
			Header="Cantidad"
			MaxWidth="{Binding MinWidth, RelativeSource={RelativeSource Self}}">
	<DataGridTemplateColumn.CellTemplate>
		<DataTemplate>
			<mahApps:NumericUpDown Minimum="1"
						Width="100"
						IsTabStop="False"
						Value="{Binding Cantidad, UpdateSourceTrigger=PropertyChanged}">
				<i:Interaction.Triggers>
					<i:EventTrigger EventName="OnValueChanged">
						<i:InvokeCommandAction Command="{Binding RefreshPropertiesCommand}" />
					</i:EventTrigger>
				</i:Interaction.Triggers>
			</mahApps:NumericUpDown>
		</DataTemplate>
	</DataGridTemplateColumn.CellTemplate>
</DataGridTemplateColumn>
```

```
private ICommand _refreshPropertiesCommand;

public ICommand RefreshPropertiesCommand => _refreshPropertiesCommand ??
							(_refreshPropertiesCommand =
								new RelayCommand(RefreshProperties));
```

I tried with each EventName (TextChanged, OnTextChanged, ValueChanged, OnValueChanged)

--
### Environment

- MahApps.Metro v1.4.0
- Windows 7
- Visual Studio 2015
- .NET Framework 4.0

**Comment by xxMUROxx** [comment]
@avechuche Have you tried `ValueChanged` as `EventName` insted of `OnValueChanged`?

**Comment by xxMUROxx** [comment]
@avechuche I have tested it with `ValueChanged` and it worked

**Comment by thoemmi** [comment]
Yeah, the event is named `ValueChanged`, see [NumericUpDown.cs](https://github.com/MahApps/MahApps.Metro/blob/develop/src/MahApps.Metro/MahApps.Metro.Shared/Controls/NumericUpDown.cs#L27).

**Comment by avechuche** [comment]
Yes, it was my mistake, the binding path was wrong. Please close de "bug"
