### ISSUE TITLE
Binding DateTimePicker DisplayDateEnd and DisplayDateStart

### ISSUE THREAD

**Issue by Nkmol** [MahApps/MahApps.Metro#2791]
## What steps will reproduce this issue?

```xaml
<controls:DateTimePicker DisplayDateEnd="{Binding BoundryEndDate}" DisplayDateStart="{Binding BoundryStartDate}" />
```

**ViewModel binding:**
```
public DateTime? BoundryStartDate { get; set; }
public DateTime? BoundryEndDate { get; set; }
```

Whenever I update one of these bindable properties, the `DateTimePicker` will not update the [`DisplayDateEnd`](https://github.com/MahApps/MahApps.Metro/blob/21dfea15048661627da6cffce3548c42122938af/src/MahApps.Metro/MahApps.Metro.Shared/Controls/TimePicker/DateTimePicker.cs#L70) and [`DisplayDateStart`](https://github.com/MahApps/MahApps.Metro/blob/21dfea15048661627da6cffce3548c42122938af/src/MahApps.Metro/MahApps.Metro.Shared/Controls/TimePicker/DateTimePicker.cs#L80).

Note that it **will work** if it is done at initializing of the `ViewModel` (and thus the `DateTimePicker`?):

`public DateTime? BoundryStartDate { get; set; } = DateTime.Now;`

### Expected outcome

To update both the `DisplayDateEnd` and `DisplayDateStart` properties accordingly.

-------
### Environment

- MahApps.Metro __v1.4.0__
- Windows __10 x64__
- Visual Studio __2017 Professional 4.6__
- .NET Framework __4.6__

**Comment by punker76** [comment]
@Nkmol Do you implement the `INotifyPropertyChanged` interface for your ViewModel? It doesn't seems so.

**Comment by Nkmol** [comment]
@punker76 Thanks for your reaction! 
I am using MVVM Light and my ViewModel uses the `ViewModelBase` which uses the `INotifyPropertyChanged` interface: `public class InspectionViewModel : ViewModelBase, ICreateUpdatePopup`.

Other bindings, for example with a `TextBox.Content`, works fine.

With kind regards,
Nkmol

**Comment by thoemmi** [comment]
Are sure the `INotifyPropertyChanged.PropertyChanged` event is raised? If not, use a backing field for the property and change your properties like this:
```cs
private public DateTime? _boundryStartDate;

public DateTime? BoundryStartDate { 
    get { return _boundryStartDate; }
    set {
        if (_boundryStartDate != value) {
            _boundryStartDate = value;
            RaisePropertyChanged(() => BoundryStartDate);
        }
    }
}
```

**Comment by Insire** [comment]
If there is not some compiletime magick implemented like fody, then those properties wont notify the UI about changes. Throwing the mvvm light viewmodelbase doesnt change that. you have to actually invoke the event for updates to show. @thoemmi approach is a good start, even though i dont recommend using expressions for triggering INPC, but either CallerMembername or the use of nameof().

**Comment by thoemmi** [comment]
@Insire  :+1: for `nameof()`, but I never liked `CallerMembername` because you don't see it on the caller side.

**Comment by Nkmol** [comment]
@Insire and @thoemmi I feel so stupid for this simple mistake, thank you both for taking the time to help me! Time for "Back to basic" 😄 

Thanks!
