### ISSUE TITLE
Text filled button helper for TextBox

### ISSUE THREAD

**Issue by realies** [MahApps/MahApps.Metro#2794]
I though this was already implemented, but just found out that TextBoxHelper.ButtonContent stands for the text character of the icon font. Is it possible to have an option for text filled buttons within textboxes?

**Comment by punker76** [comment]
@realies Yes, you have several capabilities to get this

- use the `TextBoxHelper.ButtonFontFamily` attached property to change the font for the content
- or use the `TextBoxHelper.ButtonContentTemplate` attached property to change the template for the content, so you can put in what you want (TextBlock, etc)

You can also change the font of the content with the `TextBoxHelper.ButtonFontFamily` attached property.
