### ISSUE TITLE
async/await is difficult to incorporate in older projects unless complete solution is adjusted...

### ISSUE THREAD

**Issue by Dirkster99** [MahApps/MahApps.Metro#2800]
Hi I am interested in the ContentDialog that is available in MahApps.Metro, so I refactored this portion of the library into a service based architecture only to find out that the async methods cannot be used in conjunction with normal synchronous methods as I had previously implemented and wanted to continue to use in my existing projects:

https://social.msdn.microsoft.com/Forums/vstudio/en-US/650e69f9-5f4d-4d77-8107-93fb6646f26d/block-synchronous-method-while-waiting-for-async-method-to-complete?forum=netfxbcl

I was wondering if anyone else has run into this problem or whether there is an alternative solution that does not require async/await?

ANyways, this library is a great source of creative solution. Thanks for providing this great work :-)

**Comment by pfattisc** [comment]
@Dirkster99 you could use the WaitWithPumping method from [here](https://social.msdn.microsoft.com/Forums/en-US/163ef755-ff7b-4ea5-b226-bbe8ef5f4796/is-there-a-pattern-for-calling-an-async-method-synchronously?forum=async). 
Have a look at Stephen Toub's answer.

**Comment by Dirkster99** [comment]
Thanks a lot the solution works great for me - I think this issue is resolved :-)
