### ISSUE TITLE
Visual Studio 2015 - XAML errors for all Metro* resources

### ISSUE THREAD

**Issue by MrCroix** [MahApps/MahApps.Metro#2801]
I'm not certain of the precipitating cause of my errors.  I've been using MahApps Metro for about a year without any issues but very suddenly, possibly after upgrading from 1.2.x to 1.4.1, I see XAML errors stating "The resource "[metro resource here]" could not be resolved.".

My googling this suggests the following:

Ensure the App.xaml contains the metro merged dictionaries correctly.  Check. (file attached)

Delete the ComponentModelCache.  Check, no effect.
Do a "Repair Install" of Visual Studio.  Check, no effect.
Reinstall MahApps.Metro from GitHub.  Check. no effect.
Reboot. Check (numerous), no effect.

Running the program and everything works flawlessly, the Visual Studio designer does not display correctly and shows errors for all references to Metro resources.  See screenshot.

This is driving me CRAZY!!

![app](https://cloud.githubusercontent.com/assets/25080690/21892481/b389f434-d89c-11e6-8b49-3c704071ee04.png)
![vsmetroerrors](https://cloud.githubusercontent.com/assets/25080690/21892480/b3894732-d89c-11e6-93ae-2085f8012ecc.png)

### Expected outcome

There shouldn't be resource errors.  Once corrected, the designer will display correctly.

--
### Environment

- MahApps.Metro __v1.4.1__
- Windows __7__
- Visual Studio __2015__
- .NET Framework __4.5.2__

**Comment by punker76** [comment]
@MrCroix VS is sometimes... nah, ok, try these steps

1. override MahApps styles after original styles
2. clear the VS shadow cache `C:\Users\<USER>\AppData\Local\Microsoft\VisualStudio\14.0\Designer\ShadowCache`
3. cleab obj/bin folders
4. build all and look if it's now working

**Comment by MrCroix** [comment]
Can you tell me what you mean by "override MahAps styles after original styles".

And

Yes, I know this isn't MahApps metros fault but it is still a problem.

**Comment by MrCroix** [comment]
I tried everything else, no effect, still broken.

**Comment by MrCroix** [comment]
Oh, and, thank you.

**Comment by punker76** [comment]
@MrCroix Sorry about this nasty issue with your VS.

>Can you tell me what you mean by "override MahAps styles after original styles".

In your screen first screenshot you change TextBox style inheirted from MahApps `MetroTextBox`. This should be done after defining the resources from MahApps, not before.

>I tried everything else, no effect, still broken.

Do you cleared the shadowcache? Also check your references if they correct with the dlls in the output.

Sorry, I don't know what's going wrong on your machine... (do you have VS 2015 Update 3?)...

**Comment by MrCroix** [comment]
Moving the one MetroTextBox reference above or below the resource declarations makes no difference.  Must be a two pass compile.

Yes, Visual Studio 2015 Update 3.

Still have the errors.

**Comment by dovegq** [comment]
Same in Visual Studio 2019, but VS2015 is OK

**Comment by margy82** [comment]
Same here. Last update VS2019 Community. Mahapps 1.6.5, Controlz 3.0.2.4
Full of error in designer preview, compilation and run ok.
