### ISSUE TITLE
Content of expander with margin is cut off

### ISSUE THREAD

**Issue by MLanghof** [MahApps/MahApps.Metro#2809]
## What steps will reproduce this issue?

Run current version of https://github.com/MLanghof/ExpanderBugRedux.
Open the expander.
Result: The expander content is cut off.

Additionally, if the window is horizontally resized until the expander content no longer fits the window width, it is displayed properly. Also see this gif:

![2545f2830f579d52d744d8ba11ec97e0](https://cloud.githubusercontent.com/assets/658431/22060756/6f52187a-dd72-11e6-8dc6-40cf457e2e70.gif)

![ky0cjrt](https://cloud.githubusercontent.com/assets/658431/22060781/86c85866-dd72-11e6-9d12-66cf884667a3.gif)

### Expected outcome

The expander content is always fully visible (as long as the expander is expanded).

---
### Environment

- MahApps.Metro __v1.2.4__
- Windows __8__ and Windows __7__
- Visual Studio __2015__
- .NET Framework __4.5__ (unsure which one is asked for here - please instruct where to look)

---
### Additional information

Padding and BorderThickness of the expander have an influence on whether this bug surfaces. See [here](https://github.com/EmmittJ/PoESkillTree/issues/376#issuecomment-272044905) for slightly more details. Changing the expander orientation does not affect the issue.
This bug only surfaces for some users but has been reproduced on at least three different setups.

**Comment by punker76** [comment]
@MLanghof Thx for the repo sample. I tested with latest MahApps v1.4.1 and get the same result (maybe a clipping stuff), cause you set the Margin of the inner Grid to `-107,0,0,0`. I know you do this to simulate a popup dropdown, but It's better to set the Padding of the Expander to this value...

```xaml
<Expander Margin="108 -30 0 0"
            Style="{StaticResource TopRowExpander}"
            Header="EXPANDER WITH MARGIN"
            Padding="-107,0,0,0">
    <Grid Background="Bisque">
        <TabControl x:Name="tabControlSheet"
                    HorizontalAlignment="Left"
                    Width="500"
                    Margin="1,0,0,0"
                    controls:TabControlHelper.IsUnderlined="True"
                    Focusable="True">
            <TabItem Margin="0"
                        controls:ControlsHelper.HeaderFontSize="15"
                        Header="LONG TEST STRING TO SEE 1">
            </TabItem>
            <TabItem Margin="0"
                        controls:ControlsHelper.HeaderFontSize="15"
                        Header="LONG TEST STRING TO SEE 2">
            </TabItem>
        </TabControl>
    </Grid>
</Expander>
```

![expander](https://cloud.githubusercontent.com/assets/658431/22062843/240e5eb4-dd7c-11e6-8fda-a97f19455b86.gif)

**Comment by MLanghof** [comment]
Well, feel free to close this, depending on how much of a bug you think it is.

**Comment by punker76** [comment]
@MLanghof glad to help
