### ISSUE TITLE
WPf Datagrid with NumericUpDown control as a column: why when the grid is empty and I put values before complete the edit of the row, these values pass to the next line?

### ISSUE THREAD

**Issue by oriolmortem** [MahApps/MahApps.Metro#2810]
## What steps will reproduce this issue?

When my datagrid is empty...
![image](https://cloud.githubusercontent.com/assets/4039341/22071170/5760bc68-dd6c-11e6-9401-17625472936e.png)

And I put some values on the NumericUpDown controls -but I don't finish to complete the row-
![image](https://cloud.githubusercontent.com/assets/4039341/22072015/f7a12544-dd6e-11e6-8bf6-8e531220f8cd.png)

ThenI put another text on another column and hit ENTER
![image](https://cloud.githubusercontent.com/assets/4039341/22072070/1881002c-dd6f-11e6-978d-df31e781586f.png)

The datagrid sets a new line, but with the previous values puted on the first row..
![image](https://cloud.githubusercontent.com/assets/4039341/22072099/33674cb6-dd6f-11e6-86f1-38228faed81b.png)

### Expected outcome

Expected to see a new line but without the previous values .

--
### Environment

- MahApps.Metro __v1.4.1__
- Windows __07__
- Visual Studio __2015__
- .NET Framework __4.5__

**Comment by punker76** [comment]
@oriolmortem How do you implemented your view model? Can you show us some Code? A short sample would be useful. Thx
