### ISSUE TITLE
MetroWindow Maximized Wrongly

### ISSUE THREAD

**Issue by hausenism** [MahApps/MahApps.Metro#2811]
## What steps will reproduce this issue?

Create a new wpf application project.
Change the default MainWindow class to inherit MetroWindow.
Run the project.
(double click the titlebar or click on buttons) Maximize and Restore the MainWindow several times.

### Expected outcome

(this won't always happen) The MainWindow is maximized but displayed strangely as below screenshot.

![image](https://cloud.githubusercontent.com/assets/5018178/22173451/603e780e-dffe-11e6-8118-4723dcca4e9a.png)

--
### Environment

- MahApps.Metro __v1.4.0__
- Windows __10__
- Visual Studio __2015__
- .NET Framework __4.5__

**Comment by punker76** [comment]
@hausenism Can you retest it with v1.4.1? thx

**Comment by hausenism** [comment]
@punker76 Sorry, my test was on __1.4.0__

I will retest it with v1.4.1

**Comment by hausenism** [comment]
@punker76 , I just update submodule to v1.4.1, and the problem still exists.

**Comment by punker76** [comment]
@hausenism OK, thx

**Comment by punker76** [comment]
@hausenism another question. is this running on a VM?

**Comment by hausenism** [comment]
@punker76 
No. I use Teamviewer to connecto to my remote desktop. 
Our test manager find the problem on her desktop a few days ago.

**Comment by Deadpikle** [comment]
@hausenism Related to #2727 ? Are Windows animations turned off? (Due to the remote session, I'm guessing they are.)

**Comment by hausenism** [comment]
@Deadpikle Yes, you are right, my windows animations are turned off.

**Comment by punker76** [comment]
duplicate to #2727
