### ISSUE TITLE
Font family in Flyout.xaml and MetroNavigationWindow.xaml

### ISSUE THREAD

**Issue by draco1023** [MahApps/MahApps.Metro#2812]
## What steps will reproduce this issue?

_Simplified Chinese is not displayed the right way using Segoe UI (Symbol) as described in issue [2033](https://github.com/MahApps/MahApps.Metro/issues/2033) on Windows 7/8._
_Most font family settings can be modified by override the resource keys in Styles/Fonts.xaml._
_Except [https://github.com/MahApps/MahApps.Metro/blob/984ecf4aa1b778d40b3a041d95b788eb9daeb6a9/src/MahApps.Metro/MahApps.Metro/Themes/Flyout.xaml#L24](https://github.com/MahApps/MahApps.Metro/blob/984ecf4aa1b778d40b3a041d95b788eb9daeb6a9/src/MahApps.Metro/MahApps.Metro/Themes/Flyout.xaml#L24)_
_[https://github.com/MahApps/MahApps.Metro/blob/2fed9c9d91695903d0548fc4dffb7f1af3a1a917/src/MahApps.Metro/MahApps.Metro/Themes/MetroNavigationWindow.xaml#L20](https://github.com/MahApps/MahApps.Metro/blob/2fed9c9d91695903d0548fc4dffb7f1af3a1a917/src/MahApps.Metro/MahApps.Metro/Themes/MetroNavigationWindow.xaml#L20)_
_[https://github.com/MahApps/MahApps.Metro/blob/2fed9c9d91695903d0548fc4dffb7f1af3a1a917/src/MahApps.Metro/MahApps.Metro/Themes/MetroNavigationWindow.xaml#L33](https://github.com/MahApps/MahApps.Metro/blob/2fed9c9d91695903d0548fc4dffb7f1af3a1a917/src/MahApps.Metro/MahApps.Metro/Themes/MetroNavigationWindow.xaml#L33)_

### Expected outcome

_Use DynamicResource instead of fixed value_

--
### Environment

- MahApps.Metro __v1.4.1__
- Windows __7__
- Visual Studio __2013__
- .NET Framework __4.0__

**Comment by punker76** [comment]
@draco1023 Thx for pointing to this. Will remove this, cause this buttons uses icons inside...
