### ISSUE TITLE
Proper usage of the Demo Project and how to move it from on to another pc and keep the functionality of the project ? 

### ISSUE THREAD

**Issue by ivanbojan** [MahApps/MahApps.Metro#2816]
Hello everyone,

I am quite new with the framework so I have downloaded the demo project with all the src files.
I have run it successfully on my notebook to check how things work and everything is fine.
When I try to move it to my pc and added it to my TFS on another pc I copy - paste the whole folder.
I try to run the solution but I am Constantly getting errors that namespaces are missing.

Is there any tutorial or help on how properly to use this demo project and extended with other projcets.
I would like to add  new projects into the solution that will use the provided controls in the MahApps.Metro.Demo.Shared ?!

- MahApps.Metro latest
- Windows 10
- Visual Studio 2015
- .NET Framework net45

**Comment by thoemmi** [comment]
Is there a reason why you don't use the NuGet package in your project?

**Comment by ivanbojan** [comment]
I have tried using nuget (Manage nuget Packages & Console as well) but no luck.
Is this anyhow connected to .paket folder with dependencies ?!

I have ran the cmd file on my notebook but is not possible to run it again on the the other PC.

**Comment by thoemmi** [comment]
The paket stuff is required only if you're compiling MahApps.Metro by yourself.

In your own project you only need to follow the [Quick Start guide](http://mahapps.com/guides/quick-start.html).
