### ISSUE TITLE
Can't compile with VS2015

### ISSUE THREAD

**Issue by sooqua** [MahApps/MahApps.Metro#2824]
## What steps will reproduce this issue?
1. git clone https://github.com/MahApps/MahApps.Metro.git
2. Open .\MahApps.Metro\src\MahApps.Metro.sln
3. Press Build -> Build Solution

### Expected outcome
Everything compiles. Especially the "demo application".

### Actual outcome
1>------ Build started: Project: MahApps.Metro.NET40, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "JetBrains.Annotations". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
1>CSC : error CS2001: Source file 'C:\Users\sooqua\Documents\Visual Studio 2015\Projects\MahApps.Metro\src\MahApps.Metro\MahApps.Metro\..\..\paket-files\ControlzEx\ControlzEx\src\ControlzEx\KeyboardNavigationEx.cs' could not be found.
2>------ Build started: Project: MahApps.Metro.NET45, Configuration: Debug Any CPU ------
2>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "JetBrains.Annotations". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
2>CSC : error CS2001: Source file 'C:\Users\sooqua\Documents\Visual Studio 2015\Projects\MahApps.Metro\src\MahApps.Metro\MahApps.Metro\..\..\paket-files\ControlzEx\ControlzEx\src\ControlzEx\KeyboardNavigationEx.cs' could not be found.
Build has been canceled.

### Environment
- MahApps.Metro v1.4.1.0
- Windows 10
- Visual Studio 2015
- .NET Framework 4.5

**Comment by sooqua** [comment]
### Actual outcome
1>------ Build started: Project: MahApps.Metro.NET40, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "JetBrains.Annotations". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
1>CSC : error CS2001: Source file 'C:\Users\sooqua\Documents\Visual Studio 2015\Projects\MahApps.Metro\src\MahApps.Metro\MahApps.Metro\..\..\paket-files\ControlzEx\ControlzEx\src\ControlzEx\KeyboardNavigationEx.cs' could not be found.
2>------ Build started: Project: MahApps.Metro.NET45, Configuration: Debug Any CPU ------
2>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "JetBrains.Annotations". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
2>CSC : error CS2001: Source file 'C:\Users\sooqua\Documents\Visual Studio 2015\Projects\MahApps.Metro\src\MahApps.Metro\MahApps.Metro\..\..\paket-files\ControlzEx\ControlzEx\src\ControlzEx\KeyboardNavigationEx.cs' could not be found.
Build has been canceled.

**Comment by sooqua** [comment]
Also I get this output from IntelliSense:
[Failure] Could not find a part of the path 'C:\Users\sooqua\Documents\Visual Studio 2015\Projects\MahApps.Metro\src\paket-files\ControlzEx\ControlzEx\src\ControlzEx\KeyboardNavigationEx.cs'.
[Failure] Could not find a part of the path 'C:\Users\sooqua\Documents\Visual Studio 2015\Projects\MahApps.Metro\src\paket-files\ControlzEx\ControlzEx\src\ControlzEx\KeyboardNavigationEx.cs'.

And I actually don't have the 'paket-files' folder. Any idea what's going on and how to get this to work?

**Comment by sooqua** [comment]
Ok I found this paket.dependencies file. Everything seems clear now. It needs to be somehow documented though...

**Comment by Eternal21** [comment]
Ran into the same problem.  For anyone else that gets tons of errors while trying to build the demo app.  Here are the steps (I also wish it was documented somewhere):
1. Download 'Paket for Visual Studio' extension ([here](https://marketplace.visualstudio.com/items?itemName=SteffenForkmann.PaketforVisualStudio)).
2. Open the MahApps.Metro solution.
3. Right click on paket.dependencies file in Solution Explorer (it's located inside .paket folder at the top), and click Install.
4. All the dependencies will be downloaded, and you'll be able to build your solution then.
