### ISSUE TITLE
Shorten Dialog Show/Hide animation duration

### ISSUE THREAD

**Issue by oliverw** [MahApps/MahApps.Metro#2825]
I would like to shorten the Dialog Show/Hide animation duration significantly while not resorting to <code>MetroDialogSettings.AnimateHide = false</code>. What is the recommending approach to accomplish this?

**Comment by ghord** [comment]
+1 Dialog animation feels too long. I guess having some setting to control duration in `MetroDialogSettings` would be ideal.

**Comment by xxMUROxx** [comment]
Yes, a global configuration would be cool 👍
