### ISSUE TITLE
AccentColorBrush could not be resolved using 1.4.2.0 but works fine with 1.1.2.0

### ISSUE THREAD

**Issue by dsmprojects** [MahApps/MahApps.Metro#2831]
## What steps will reproduce this issue?
Followed the example steps to add GlowBrush and it would not resolve AccentColorBrush.
The rest of the example worked fine.

I found an example code on codeproject and referenced the older MahApp.Metro.dll in my project and then it resolved GlowBrush.

Is there a new step needed so VS can resolve in the newer version?
--
### Environment

- MahApps.Metro __v 1.4.2.0
- Windows __1511 and 1607__
- Visual Studio __2015__
- .NET Framework __4.5__

**Comment by punker76** [comment]
@dsmprojects Can you show me your window xaml where you defined the brush? And do you put all necessary resources to the App.xaml?

**Comment by dsmprojects** [comment]
<controls:MetroWindow x:Class="WpfMetroLike.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:controls="http://metro.mahapps.com/winfx/xaml/controls"
        GlowBrush="{DynamicResource AccentColorBrush}"
                       
        Title="Metro WPF" Height="350" Width="525" ResizeMode="CanResizeWithGrip" BorderThickness="1" >
    <Grid>
        <controls:ProgressRing IsActive="True" />
    </Grid>
</controls:MetroWindow>


and...

<Application x:Class="WpfMetroLike.App"
           xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             StartupUri="MainWindow.xaml">
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Colors.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/emerald.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/basedark.xaml" />
                <ResourceDictionary Source="/Resources/Icons.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
        </Application.Resources>
</Application>

Thank you!

**Comment by dsmprojects** [comment]
[WpfMetroLike.zip](https://github.com/MahApps/MahApps.Metro/files/746287/WpfMetroLike.zip)

**Comment by punker76** [comment]
@dsmprojects Make sure that all file names are Case Sensitive!

It should be

```
<ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/Emerald.xaml" />
<ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/BaseDark.xaml" />
```

all other looks good

**Comment by punker76** [comment]
@dsmprojects http://mahapps.com/guides/quick-start.html#using-built-in-styles
