### ISSUE TITLE
Wrong window maximize on two monitor systems.

### ISSUE THREAD

**Issue by chuuddo** [MahApps/MahApps.Metro#2832]
## What steps will reproduce this issue?

I have two monitors and after update from v1.4.1 to v1.4.2 window maximizing start ignore taskbar with z-order behind tasbar (see screenshots). On one monitor systems this issue not reproduced.

v.1.4.1 two monitors maximized window.
![screenshot_1](https://cloud.githubusercontent.com/assets/526086/22537617/7bf2c67e-e925-11e6-87ca-c5e9611ce721.png)

v.1.4.2 two monitors maximized window.
![screenshot_2](https://cloud.githubusercontent.com/assets/526086/22537632/9f72c810-e925-11e6-8799-df8653b29fb5.png)

### Expected outcome

Window maximizing should work same on any number of monitors

--
### Environment

- MahApps.Metro __v1.4.2__
- Windows __7__
- Visual Studio __2015__
- .NET Framework __4.5.1__

**Comment by punker76** [comment]
@chuuddo your screenshots seems to be the same? Damn, maybe I fixed to much...

**Comment by chuuddo** [comment]
@punker76 look at ActualHeight on screenshots. If maximized right it should be 1080-TaskbarHeight on FullHD resolution.

Code of window on screenshots.

```xaml
<controls:MetroWindow x:Class="MahappsTest.MainWindow"
                      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                      xmlns:controls="http://metro.mahapps.com/winfx/xaml/controls"
                      xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
                      xmlns:local="clr-namespace:MahappsTest"
                      xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
                      Title="MainWindow"
                      Width="525"
                      Height="350"
                      WindowStartupLocation="CenterScreen"
                      mc:Ignorable="d">
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition />
            <RowDefinition Height="Auto" />
        </Grid.RowDefinitions>
        <Grid Grid.Row="0" VerticalAlignment="Bottom">
            <StackPanel Orientation="Horizontal">
                <TextBlock Text="{Binding ActualWidth, Mode=OneWay, RelativeSource={RelativeSource FindAncestor, AncestorType={x:Type controls:MetroWindow}}}" />
                <TextBlock Text="x" />
                <TextBlock Text="{Binding ActualHeight, Mode=OneWay, RelativeSource={RelativeSource FindAncestor, AncestorType={x:Type controls:MetroWindow}}}" />
            </StackPanel>
        </Grid>
        <StatusBar Grid.Row="1" Height="70" />
    </Grid>
</controls:MetroWindow>
```

**Comment by punker76** [comment]
@chuuddo OK, but in both screenshots the maximization is wrong...

**Comment by chuuddo** [comment]
@punker76 dont understand why maximization is wrong on both sreenshots. 
I think in 1.4.1 maximization work right. All screenshots made on two monitor system.
![screenshot_5](https://cloud.githubusercontent.com/assets/526086/22539936/b9a85298-e936-11e6-98dc-7f7c43d3d167.png)
![screenshot_6](https://cloud.githubusercontent.com/assets/526086/22539938/b9aa6f7e-e936-11e6-8c4e-461da11d6300.png)
![screenshot_7](https://cloud.githubusercontent.com/assets/526086/22539937/b9a9f9d6-e936-11e6-807d-939b5f1187a2.png)

**Comment by punker76** [comment]
@chuuddo Can you try this one? I think I optimized to much in last release 😁 
[MahApps.Metro.zip](https://github.com/MahApps/MahApps.Metro/files/747112/MahApps.Metro.zip)

**Comment by chuuddo** [comment]
@punker76 it works fine, like in 1.4.1!

**Comment by punker76** [comment]
@chuuddo Thx for clarifying the problem and testing!

**Comment by BornToBeRoot** [comment]
When will you release 1.4.3 ? This happens on systems with 1 Monitor too. 

I dont want to go back to 1.4.1 :smile:

**Comment by punker76** [comment]
@BornToBeRoot this evening (de)
