### ISSUE TITLE
ShowMessageAsync() hidden by hosted process

### ISSUE THREAD

**Issue by dontbyte** [MahApps/MahApps.Metro#2833]
## What steps will reproduce this issue?

Set parent of a process to a WPF container via SetParent() and show async message dialog.

### Expected outcome

Message dialog is hidden by the hosted process. Can't be closed anymore because message dialog is not accessable.

### Environment

- MahApps.Metro __v1.4.2.0__
- Windows __7__
- Visual Studio __2015__
- .NET Framework __4.5__

**Comment by punker76** [comment]
@dontbyte I don't know if this right what you do with SetParent. I never seen and do this. Can you create a short app with this? thx

**Comment by dontbyte** [comment]
Here you go (quick and dirty):

[MahAppsIssue.pptx](https://github.com/MahApps/MahApps.Metro/files/747155/MahAppsIssue.pptx)
Change file type .pptx to .zip. I wasn't able to upload the zip file due to unsupported file tye..

At the bottom are 2 buttons, first button host child process to the WPF control and second button opens async message dialog.

**Comment by punker76** [comment]
@dontbyte Your sample is really hacky :-D I don't know if we can / should support this. The main reason is in my view the z-order of the processes itself... /cc @thoemmi

**Comment by thoemmi** [comment]
I guess this is an airspace issue: you're showing a notepad window (with its own Window handle) in front of the WPF window. The dialog is shown inside the WPF window, and therefore is displayed behind notepad.

If you want to show the message box in front of Notepad, use `ShowModalMessageExternal`:
```csharp
private void Button_Click(object sender, RoutedEventArgs e)
{
    this.ShowModalMessageExternal("", "Message!");
}

```

**Comment by dontbyte** [comment]
Works great, thank you thoemmi!
