### ISSUE TITLE
TabItem

### ISSUE THREAD

**Issue by brianshansen** [MahApps/MahApps.Metro#2834]
Hi

I have a tabcontrol, where I want the tabs that are disabled to be red how to do I do?
Have made this style to bind tabheader and the enable properties

        <Style TargetType="{x:Type TabItem}" BasedOn="{StaticResource MetroTabItem}">
            <Setter Property="Header" Value="{Binding TabHeader}"/>
            <Setter Property="IsEnabled" Value="{Binding IsEnabled, UpdateSourceTrigger=PropertyChanged, Mode=TwoWay}"></Setter>
        </Style>

**Comment by punker76** [comment]
@brianshansen You can use a trigger for this and change e.g. the background of your item or you use a converter which binds to IsEnabled and converts it to a background...
