### ISSUE TITLE
Questions about the - Demo Application ( A toolkit for creating Metro / Modern UI styled WPF apps)

### ISSUE THREAD

**Issue by ivanbojan** [MahApps/MahApps.Metro#2839]
Hello,

first of all I would like to say thank you for the great open source that you have developed so far, it will really help me my project to look professional. I have founded thanks to the Pluralsight tutorial (https://www.pluralsight.com/courses/mahappsdotmetro-creating-modern-wpf-apps) about the framework done by Mark Heath.

I have downloaded the demo application from Git (https://github.com/MahApps/MahApps.Metro) with all the control examples put into the MainWindow.xaml.

I am bit new to WPF and all related stuff so I have spent few days to dive deeper into the project structure and I have got to few questions which I would really appreciate if you can help me :)
 
#1 Question - How to create new project that will have everything as the MahApps.Metro.Demo.NET45 Project but afterwards edit it according to the requirements (more info in the paragraph below) ?! 

I would like to keep all the shared projects and I would like to create 6 projects that will use the Shared projects from the Demo project.
I would need 6 projects (replications) at the beginning of the MahApps.Metro.Demo.NET45 project but I want each MainWindow.xaml to be independent.
Why I am asking this because this is what i did (Copy / Paste the MahApps.Metro.Demo.NET45 Project, changed the Project name into NewProject1 and .csproj file respectively, and finally Added as an Existing project in the same solution). 
Everything is fine and works, but when I change (add/edit something in the code of NewProject1 -> MainWindow.xaml or MainWindow.xaml.cs it is replicated in the MahApps.Metro.Demo.NET45 MainWindow.xaml or MainWindow.xaml.cs  respectively).
I need this to be independent but to keep all other shared functionality from this projects MahApps.Metro.NET45, MahApps.Metro.Shared, MahApps.Metro.Core.Demo.Shared and MahApps.Metro.Demo.Shared. 
With this approach I would like to keep change of the design on one central place and to be reflected in all 6 projects that have different independent functionality. 

#2 Question - I have other Projects BL, DAL, Custom Controls that I need to reference into each of the 6 Projects I will create.
What is the best way to do this but not interrupt the beauty of the mahapps control toolkit that is well done in the Demo Project (downloaded from git) ?!

#3 I looking into the .csproj file of the MahApps.Metro.Demo.Shared project and trying to figure it out what and how is connected everything there between the projects from the Solution. I have downloaded this https://github.com/MahApps/MahApps.Metro
and I would like to build my 6 projects into the same solution.
 
#4 Please let me know if I am on right track with this approach or not ?!
If not please share with me any useful tips (I appreciate it).

Thanks in advance :)

**Comment by thoemmi** [comment]
If you don't have any experience with WPF, don't start with MahApps.Metro. Instead, create a plain vanilla WPF project and learn that framework.

If you later want to apply this library, you don't have use MahApps.Metro's sources directly. Instead, follow the [Quick Start guide](http://mahapps.com/guides/quick-start.html) to get the nice Metro style.

**Comment by ivanbojan** [comment]
@thoemmi can you please answer my questions if possible.
Maybe @punker76 can help with this ?!

**Comment by thoemmi** [comment]
As I said, you don't have to copy the MahApps.Metro sources. Just create a new WPF application, and then follow the [Quick Start guide](http://mahapps.com/guides/quick-start.html). You have to reference MahApps.Metro only in your presentation layer, it's a control-only library. Your DAL and BL should not be affected by MahApps.Metro.
