### ISSUE TITLE
Modal flyout issue

### ISSUE THREAD

**Issue by adragoner** [MahApps/MahApps.Metro#2841]
## What steps will reproduce this issue?

Flyout with `IsModal=true` doesn't block other window commands (left or right) to be executed.

### Expected outcome

All window interactivity except the flyout is disabled.

**Comment by punker76** [comment]
@adragoner You can additionally set `LeftWindowCommandsOverlayBehavior`, `RightWindowCommandsOverlayBehavior` and `WindowButtonCommandsOverlayBehavior` to prevent execution by mouse (menus and key shortcuts still works, but this is already issued)

**Comment by avechuche** [comment]
These options do not work if the Flyout does not pass over the controls.

![1](https://cloud.githubusercontent.com/assets/11781418/23001975/f0db0784-f3c6-11e6-8ce6-7a283ec4db0e.gif)

**Comment by punker76** [comment]
@adragoner All title bar commands now behind the overlay if a Flyout is modal (available in 1.5.0 and alpha). The functionality are still there like Alt+F4, so you must handle this by yourself.
