### ISSUE TITLE
Custom Dialog Storyboard Error

### ISSUE THREAD

**Issue by saltypoison** [MahApps/MahApps.Metro#2842]
Hello,

It is very likely this is user error, but I would like to submit it just in case it is not.  When I create a custom dialog and I go to close it, I am getting the error below:

`"Unable to find the dialog closing storyboard. Did you forget to add BaseMetroDialog.xaml to your merged dictionaries?"`

I've isolated it to it happening when I am adding the Bool to Vis converter in the dialog (though I assume it isn't specifically that, but just adding a resource dictionary).

```
<dialogs:CustomDialog.Resources>
  <ResourceDictionary>
    <BooleanToVisibilityConverter x:Key="BoolToVis" />
  </ResourceDictionary>
</dialogs:CustomDialog.Resources>
```

I feel like it is a case of RTFM (RTFError in this case?) but I can't figure the proper way to add it, or if something is actually wrong.

I've put together a sample that reproduces this.  Run the code, click the button to open the dialog, click the button to close the dialog, and you get the error.

https://github.com/saltypoison/MahAppsStoryboardErrorExample

- MahApps.Metro v1.3.0
- Windows OS Win 10 Enterprise
- Visual Studio 2013 Update 5
- .NET Framework 4.6.1

Hopefully I've provided all the info needed.

Thank you, and as an aside, love MahApps.Metro.  Great stuff!  ~Ryan

**Comment by punker76** [comment]
@saltypoison -> https://github.com/saltypoison/MahAppsStoryboardErrorExample/pull/1

The resources for the dialogs and custom dialogs are set in code behind, so if you reset this in xaml you will get this warning. To add additional resources put it to another resources tag inside a container.

**Comment by saltypoison** [comment]
Thanks for looking at it!  

When I added it to app.xaml I still received an error that was resolved when switching it from `DynamicResource` to `StaticResource`

Would it be best practice to add converters like that to app.xaml, or is it a special case with the custom dialog?
