### ISSUE TITLE
calling MetroWindow from different class

### ISSUE THREAD

**Issue by tpatel11** [MahApps/MahApps.Metro#2843]
I am trying to call the **MetroWindow** from a class (inside the same project - inheriting **_DialogDebuggerVisualizer_**). 
I am using ShowDialog() method to popup the window.
Problem is, when I am using ShowDialog method to show the form, it is not loading the metro style, it is just a black form with normal UI controls. UI stays plain old WPF style and not the metro style.
If I directly try to show this form from MainWindow (WPF window), it is something like this:
![image](https://cloud.githubusercontent.com/assets/7439786/22666952/b065bd06-ec88-11e6-9556-60721deaaec9.png)

But,if I call from the class, it is something like this:
![image](https://cloud.githubusercontent.com/assets/7439786/22667028/efaaaaee-ec88-11e6-9bb5-618042767781.png)

If anyone has faced this issue, please let me know how to fix this?

**Comment by punker76** [comment]
@tpatel11 seems like you must put all necessary resources inside the resource tag of the window itself.

**Comment by tpatel11** [comment]
Yes, you are right. I figured out that I have defined all of the styles in App.xaml where as I should have done that in window.Resources.
