### ISSUE TITLE
HamburgerMenu Themes

### ISSUE THREAD

**Issue by amkuchta** [MahApps/MahApps.Metro#2846]
Not necessarily an issue, but more of an enhancement request - it would be great to be able to apply themes to the `HamburgerMenu` control similar to those found for the `Flyout` control:

* Inverse
* Accent
* Dark
* Light
* Adapt

In the meantime, is there an easy way to get an `InverseForegroundColorBrush` or `InverseBackgroundColorBrush` to use with the control?

**Comment by punker76** [comment]
I think this would be too much. The upcoming 1.5.0 has 2 new brushes to handle the background and foreground for the items.

**Comment by amkuchta** [comment]
@punker76 just updated to the latest pre-release; 👍 for the brush for look of the HamburgerMenu with the new BackgroundBrush - it looks great, and helps distinguish the HamburgerMenu from the rest of the window
