### ISSUE TITLE
IsModal for MetroWindows

### ISSUE THREAD

**Issue by avechuche** [MahApps/MahApps.Metro#2850]
This is not a problem, but could you add the "IsModal" option to the main window? Today I am using the "IsModal" of the Flyouts (with 0px high and 0px wide) but it is not "the right thing". If possible, like the "IsModal" used by customDialog, these prevent interaction with the maximize, minimize, and close buttons. The "IsModal" version of the flyouts let them use them. Thx!

**Comment by punker76** [comment]
@avechuche Seems like it's the same issue as here #2841

**Comment by avechuche** [comment]
@punker76 Sir, I edited the description to make it more understandable. Can you check it? Thank you!
