### ISSUE TITLE
ToggleSwitch IsChecked OneWay Binding Is Broken By User Interaction

### ISSUE THREAD

**Issue by ryanknopf** [MahApps/MahApps.Metro#2852]
Hello all,

I'm having an issue in which I'm trying to use a ToggleSwitch to represent the connection status of a communication interface that is handled in a separate thread.  I've bound the ToggleSwitch IsChecked property to a boolean property in my View Model.  The idea is that the binding is OneWay, such that when the user clicks the ToggleSwitch it triggers a "Click" event but the IsChecked value is unchanged (as it is bound to the View Model source which is still false at the time).  At some time latter the communication interface fully opens, it sets the IsConnected property in the View Model to which IsChecked is bound and the ToggleSwitch transitions to being checked (true).  Somehow though the user clicking the Toggle Switch is always able to override the binding and the the OneWay binding is broken the first time the control is clicked.

Do you have any ideas on what may be causing this or a workaround that might get the behavior I'm looking for?

Best,
- Ryan

**Comment by punker76** [comment]
@ryanknopf Here is an example which could work for you (not tested)

``` csharp
public class OneWayToggleSwitch : ToggleSwitch
{
  protected override void OnClick() {
    OneWayToggleSwitchClick(this);
  }

  public static void OneWayToggleSwitchClick(ToggleSwitch sender) {
    sender.RaiseEvent(new RoutedEventArgs(ClickEvent, sender));

    var command = sender.CheckChangedCommand;
    var commandParameter = sender.CheckChangedCommandParameter ?? sender;
    if (command != null && command.CanExecute(commandParameter))
    {
        command.Execute(commandParameter);
    }

    var eh = sender.IsCheckedChanged;
    if (eh != null)
    {
        eh(v, EventArgs.Empty);
    }
  }
}
```

Don't forget to set the MahApps ToggleSwitch style to it when you use it in Xaml.

**Comment by captainst** [comment]
I came across the same problem. @punker76 unfortunately your code does not compile.

**Comment by chm-tm** [comment]
Please reopen this issue.

According to [this repro](https://github.com/chm-tm/ToggleSwitchIsCheckedBindingLoss), only the `ToggleSwitch` suffers from this issue, while the `ToggleSwitchButton` works correctly. This can be an indication that the `ToggleSwitch` actually should work as expected, too.

Also note the work around in the repro's readme.
