### ISSUE TITLE
Writing WindowCommand Controls programatically

### ISSUE THREAD

**Issue by SkyEngine-OSP** [MahApps/MahApps.Metro#2853]
is there any possible way to write the WindowCommand Controls programmatically or from the code behind ? like for example, if a specific user type logged in, specific WindowCommand Controls will be rendered and/or the user's name will appear on the right side etc etc.

- MahApps.Metro __v1.4.3__
- Windows OS __8.1__
- Visual Studio __2015
- .NET Framework __4.6.2__

**Comment by punker76** [comment]
@SkyEngine-OSP You can handle this also by using flags in your view model and bind to it to set the visibility of your window command controls (buttons), so you don't need to create these controls in code behind.
