### ISSUE TITLE
Maximize Window with Animations On and Max Width/Height Fails

### ISSUE THREAD

**Issue by Deadpikle** [MahApps/MahApps.Metro#2855]
## What steps will reproduce this issue?

If Windows (system) animations are turned *on* and `MaxWidth`/`MaxHeight` of the `MetroWindow` are < the screen width/height, the window has a little gap between the top of the left of the application window and the user's screen. This happens when you "maximize" the window by dragging it to the top of the Windows screen or by clicking the maximize button but *not* when you drag to the left side of the screen.

GIF (top of the window doesn't show, but it looks the same as the left, aka there is a gap):

![buggybug](https://cloud.githubusercontent.com/assets/5092399/22903060/503edebc-f205-11e6-8631-349c83cb96a8.gif)

Possibly related (though not identical): #2727 

### Expected outcome

The left and top sides of the `MetroWindow` should be flush with the screen.

### Repo

https://github.com/Deadpikle/MahApps-Maximize-Bug

Repo is just a stock MahApps project on 1.4.3 with the following `MainWindow` adjustments:
```
Height="800"
Width="600"
MaxWidth="500"
MaxHeight="500"
```

### Environment

- MahApps.Metro v1.4.3
- Windows OS 10 Anniversary Edition
- Visual Studio 2015
- .NET Framework 4.5

**Comment by Deadpikle** [comment]
If there needs to be a check as to whether Windows animations are turned on or off (http://stackoverflow.com/a/37672048/3938401):
```
[StructLayout(LayoutKind.Sequential)]
public struct ANIMATIONINFO
{
      public uint cbSize;
      public int iMinAnimate;
}

[DllImport("User32.dll", SetLastError = true)]
static extern bool SystemParametersInfo(uint uiAction, uint uiParam, ref ANIMATIONINFO pvParam, uint fWinIni);

...

ANIMATIONINFO anim = new ANIMATIONINFO();
anim.cbSize = (uint)Marshal.SizeOf(anim);
anim.iMinAnimate = 0;
SystemParametersInfo(SPI_GETANIMATION, (uint)Marshal.SizeOf(anim), ref anim, 0);
bool areAnimationsOn = anim.iMinAnimate != 0;
```

**Comment by Deadpikle** [comment]
Just leaving a note here as a research that this does *not* exist in 1.0.0, but does exist in 1.1.

**Comment by batzen** [comment]
@Deadpikle This should be fixed in the develop branch now, as it's using ControlzEx for the window chrome.

**Comment by Deadpikle** [comment]
@batzen Sweet! Thank you! 👍
