### ISSUE TITLE
[Question or Bug] ShowMessageAsync Highlight Buttons 

### ISSUE THREAD

**Issue by BornToBeRoot** [MahApps/MahApps.Metro#2856]
The colors of the buttons should be swapped.

## What steps will reproduce this issue?

When calling the follwing code: 

```csharp
 MetroDialogSettings dialogSettings = new MetroDialogSettings();

                dialogSettings.CustomResourceDictionary = new ResourceDictionary
                {
                    Source = new Uri("NETworkManager;component/Resources/Styles/MetroDialogStyles.xaml", UriKind.RelativeOrAbsolute)
                };

                await dialogCoordinator.ShowMessageAsync(this, "Error", "Could not resolve host name", MessageDialogStyle.AffirmativeAndNegative,dialogSettings)
```

MetroDialogStyles.xaml
```xaml
<Style BasedOn="{StaticResource MetroFlatButton}" TargetType="{x:Type Button}" />

    <Style x:Key="AccentedDialogSquareButton"
           BasedOn="{StaticResource MetroFlatButton}"
           TargetType="{x:Type Button}">
        <Setter Property="Foreground" Value="{DynamicResource WhiteColorBrush}" />
        <Setter Property="Background" Value="{DynamicResource AccentColorBrush}" />
    </Style>

    <Style x:Key="AccentedDialogHighlightedSquareButton"
           BasedOn="{StaticResource MetroFlatButton}"
           TargetType="{x:Type Button}">
        <Setter Property="Foreground" Value="{DynamicResource WhiteColorBrush}" />
        <Setter Property="Background" Value="{DynamicResource HighlightBrush}" />
    </Style>
```

It looks like this:

![image](https://cloud.githubusercontent.com/assets/16019165/22905191/b54538f8-f23f-11e6-8caa-a01ccbf76dac.png)

Shouldn't be the OK-Button highlighted? 

### Expected outcome

The "OK" Button should be highlighted... 

### Repo

https://github.com/BornToBeRoot/NETworkManager

### Environment

- MahApps.Metro __v1.4.3__
- Windows OS __10__
- Visual Studio __2015__
- .NET Framework __4.5/4.6__

**Comment by Deadpikle** [comment]
Try setting the `DefaultButtonFocus` to `MessageDialogResult.Affirmative`.

**Comment by thoemmi** [comment]
Like @Deadpikle said. The default value for `MetroDialogSettings.DefaultButtonFocus` is `MessageDialogResult.Negative`, see
https://github.com/MahApps/MahApps.Metro/blob/develop/src/MahApps.Metro/MahApps.Metro.Shared/Controls/Dialogs/BaseMetroDialog.cs#L394

**Comment by BornToBeRoot** [comment]
Thanks!

This would be great in the documentation😃
