### ISSUE TITLE
RangeSlider with more than 2-thumbs

### ISSUE THREAD

**Issue by yeasin90** [MahApps/MahApps.Metro#2859]
Hi,

In current samples, there are two thumbs in RangeSlider. Is there any option/way to put more than two thumbs on RangeSlider?

It will be great to have this on up-coming version :) (if not available for now)

**Comment by punker76** [comment]
@yeasin90 What is your intention to need this?
/cc @thoemmi I think we should leave this as is with 2-thumbs.

**Comment by thoemmi** [comment]
@punker I second that. This would be a new control, as having `LowerValue` and `UpperValue` wouldn't make sense anymore.

**Comment by yeasin90** [comment]
@punker76  I wanted to have a vertical slider to control more than two values say : A1, A2, A3.... where A1 < A2 < A3 ......

**Comment by punker76** [comment]
@yeasin90 I think this is already possible. You can handle this with the `Minimum`, `Maximum` and the `TickFrequency` or `Ticks` property.

```xaml
<Controls:RangeSlider x:Name="RangeSlider"
                      AutoToolTipPlacement="BottomRight"
                      AutoToolTipPrecision="2"
                      ExtendedMode="True"
                      IsMoveToPointEnabled="True"
                      IsSnapToTickEnabled="True"
                      LowerValue="-70"
                      LowerValueChanged="RangeSlider_OnLowerValueChanged"
                      Maximum="200"
                      MinRange="0"
                      MinRangeWidth="20"
                      Minimum="-200"
                      MoveWholeRange="False"
                      Orientation="Vertical"
                      SmallChange="0.1"
                      TickFrequency="20"
                      TickPlacement="Both"
                      UpperValue="60"
                      UpperValueChanged="RangeSlider_OnUpperValueChanged" />
```

**Comment by yeasin90** [comment]
@punker76 : thanks for the suggestion - i am giving it a try. Actually i wanted to add a Thumb for each value, like for A1, A2, A3 etc, so that Thumb for A1 does not exceed Thumb for A2....so on and so forth

**Comment by punker76** [comment]
@yeasin90 So why not style this custom slider from the link?
