### ISSUE TITLE
Crash Mahapps In Release

### ISSUE THREAD

**Issue by HashemKalan** [MahApps/MahApps.Metro#2860]
Hello When I Run Project On My PC It's Work
But When I Run It On Client PC It's Crashed
Here is the Message:

Problem signature:
  Problem Event Name:  CLR20r3
  Problem Signature 01:  DoctorNobatDehi.exe
  Problem Signature 02:  1.0.0.0
  Problem Signature 03:  58a712cd
  Problem Signature 04:  MahApps.Metro
  Problem Signature 05:  1.4.3.0
  Problem Signature 06:  5893a46a
  Problem Signature 07:  372
  Problem Signature 08:  127
  Problem Signature 09:  System.NullReferenceException
  OS Version:  6.3.9600.2.0.0.256.48
  Locale ID:  1033
  Additional Information 1:  5861
  Additional Information 2:  5861822e1919d7c014bbb064c64908b2
  Additional Information 3:  f0d1
  Additional Information 4:  f0d1dbd1567564468dabe2f29efc18be

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=280262

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt
---------------------------------------------
The Client Has .net Framework4 and 4.5 
the program target is .net framework4 client
i use vs 2015 and mahapps version is 1.4.0
I test it first on 1.3.0 the update it but the issue did not fix

**Comment by punker76** [comment]
@HashemKalan That's odd. Can you try catch all exceptions? So maybe you can see what's really happen. Is this running on a normal pc? Or is it running over remote desktop? Has the user really the same .Net Framework? And hat about the user rights?

Found this, but don't know if it can help http://hasstoppedworking.com/fix-clr20r3-event-issues/

**Comment by punker76** [comment]
@HashemKalan Any news for your issue? Did you tried to get more information for this exception?
