### ISSUE TITLE
Flyout close button icon is incorrect when setting flow direction right to left

### ISSUE THREAD

**Issue by mahdi-ataollahi** [MahApps/MahApps.Metro#2862]
Hello, when I use flyout in a Right-to-left window, the close button's icon keeps its direction like Left-to-right mode. It's should change. Just look at this a simple code:
`<UserControl FlowDirection="RightToLeft">`
`    <Controls:Flyout IsOpen="True"/>`
`</UserControl>`

**Left to right**
![image](https://cloud.githubusercontent.com/assets/7458725/23116294/147767a0-f75f-11e6-94f6-391be48e319d.png)

**Right to left**
![image](https://cloud.githubusercontent.com/assets/7458725/23116276/f60c0442-f75e-11e6-988b-f3c5d642628f.png)

I know I can use my custom header to fix it, but I think it's a bug, so I report it, thnx

**Comment by punker76** [comment]
This will be fixed and available in 1.5.0
