### ISSUE TITLE
[Feature request]Enable/Disable of Hamburger Menu Item

### ISSUE THREAD

**Issue by Bitexirtz** [MahApps/MahApps.Metro#2865]
As shown on the screenshot, I would like to request for enabling/disabling the hamburger menu item.
Thank you very much.

![hamburger item](https://cloud.githubusercontent.com/assets/7827862/23212995/2ebfc508-f944-11e6-8789-d5695684b146.png)

**Comment by avechuche** [comment]
I think with the new implementation of Command you can disable it

**Comment by Bitexirtz** [comment]
We already tried 1.5.0-alpha002 but it seems that the ICommand is to wire only an event. You can respond to the event but disable the menu item it not possible.
I may be wrong but anywone who could help me on this?
Thank you.

**Comment by punker76** [comment]
@Bitexirtz This will be available in 1.5.0
