### ISSUE TITLE
designer view different from debug view

### ISSUE THREAD

**Issue by madalilng** [MahApps/MahApps.Metro#2873]
hello i have this issue first i thought it only exist in vs2015 community
then i try to install vs2013 community too and the issue seems to exist too..
my problem was in design mode it shows black panel while in debug mode the metro ui shows.. 
its hard to design where you cant see what you are designing .. anyone can help please thanks. 
here's the screenshot for more info.

![bug](http://i.imgur.com/wQvmUGp.png)

**Comment by punker76** [comment]
@madalilng This is not a bug by MahApps. This is usual view of a Window in the VS designer (it's also happen with normal Window).

**Comment by madalilng** [comment]
o okay .. how can i change that to follow mahapps design, is there a way?

**Comment by Dondor17** [comment]
Having the same issue. Not sure if its meant  to be this way.
