### ISSUE TITLE
How to prevent selected row background override when setting cell style

### ISSUE THREAD

**Issue by ksobon** [MahApps/MahApps.Metro#2874]
I am setting a cell background style with a `DataTrigger` but when the cell is selected it changes its background color to this Blue one: 

![image](https://cloud.githubusercontent.com/assets/529781/23512473/abbff24a-ff2e-11e6-9435-14e3ad495ec4.png)

When I just hover over it looks good: 

![image](https://cloud.githubusercontent.com/assets/529781/23512520/dbcfee90-ff2e-11e6-881e-ab3b7e1c93ba.png)

Here's my XAML:
```
<Style x:Key="dgCellStyleViewGroup" TargetType="{x:Type DataGridCell}" BasedOn="{StaticResource {x:Type DataGridCell}}">
            <Style.Triggers>
                <DataTrigger Binding="{Binding ViewGroupEditable}" Value="False">
                    <Setter Property="IsEnabled" Value="False"/>
                        <Setter Property="Foreground" Value="LightGray"/>
                    </DataTrigger>
                <DataTrigger Binding="{Binding ViewGroupEditable}" Value="True">
                    <Setter Property="IsEnabled" Value="True"/>
                        <Setter Property="Foreground" Value="LightGray"/>
                    </DataTrigger>
            </Style.Triggers>
        </Style>
```

I am setting it like this: 

`<DataGridTextColumn Header="ViewGroup" Binding="{Binding ViewGroup, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}" Width="130" CellStyle="{StaticResource dgCellStyleViewGroup}"/>`

**Comment by makingbloke** [comment]
I had the same issue recently. You need to base your style for the cell on MetroDataGridCell not DataGridCell. I'm modifying the style in code so in my case I just added the following:

<Style TargetType="DataGridCell" BasedOn="{StaticResource MetroDataGridCell}" />

Cheers

**Comment by punker76** [comment]
@makingbloke Yes, that's correct. 👍
