### ISSUE TITLE
Error is showing in vertical orientation.

### ISSUE THREAD

**Issue by manprit-sahota** [MahApps/MahApps.Metro#2876]
I have implemented logic to validate my model and while validating, it is working as expect. The only think that is not working is that, the orientation of error message is vertical which is surprising. Look as the attached image:
![orientation](https://cloud.githubusercontent.com/assets/19249055/23522884/b04fb83c-ffaa-11e6-9637-6ba500a6a749.png)

I don't know what is problem with this.
### Environment

- MahApps.Metro __v1.4.3.0
- Windows OS __8__
- Visual Studio __2015__
- .NET Framework __4.5.1__

**Comment by punker76** [comment]
@manprit-sahota maybe the same like this? https://github.com/MahApps/MahApps.Metro/issues/2536
How do you implemented the error stuff?
