### ISSUE TITLE
Can't bind to ShowTitleBar

### ISSUE THREAD

**Issue by Blinxar** [MahApps/MahApps.Metro#2877]
## What steps will reproduce this issue?
I've bound the `ShowTitleBar` property on my window to a property on my view model

`ShowTitleBar="{Binding ShowTitleBar}"`

```
bool showTitleBar= false;
public bool ShowTitleBar
{
    get => showTitleBar;
    set => Set(ref showTitleBar, value);
}

protected virtual bool Set<T>(ref T property, T value, [CallerMemberName] string propName = null)
{
    if (EqualityComparer<T>.Default.Equals(property, value)) return false;
    RaisePropertyChanging(propName);
    property = value;
    RaisePropertyChanged(propName);
    return true;
}
```
The property on the window does take the initial value of the property on the view model, however, updating the property on the view model doesn't update the window.

Using snoop, there's no reference to the binding on the ShowTitleBarProperty

![image](https://cloud.githubusercontent.com/assets/7197616/23552086/f7d71a4e-0011-11e7-9597-296945ed4b38.png)

All other bindings are working. If I change the binding to `IsEnabled="{Binding ShowTitleBar}"` then it works as expected

![image](https://cloud.githubusercontent.com/assets/7197616/23552104/18892552-0012-11e7-92bb-4f8e19cd49a8.png)

- MahApps.Metro v1.4.3
- Windows OS: Windows 8.1 x64
- Visual Studio 2017 RC
- .NET Framework 4.5.2

**Comment by punker76** [comment]
This will be fixed in 1.5.0
