### ISSUE TITLE
[Feature Request] Watermark Trimming

### ISSUE THREAD

**Issue by amkuchta** [MahApps/MahApps.Metro#2884]
## What steps will reproduce this issue?

_Currently, any watermark applied to a `TextBox` or `ComboBox` control will not trim when the control becomes too short to display the information_

### Expected outcome

_Text should trim at the character/word level, followed by a set of ellipses_

**Comment by amkuchta** [comment]
Personally, I think that the watermark should follow the same setting as the `TextBox` instead of having to set a separate property (if possible) @xxMUROxx, thoughts?

**Comment by xxMUROxx** [comment]
Yes, that would be a good option@punker76Am 13.03.2017 14:43 schrieb Alex Kuchta <notifications@github.com>:Personally, I think that the watermark should follow the same setting as the TextBox instead of having to set a separate property (if possible) @xxMUROxx, thoughts?

**Comment by amkuchta** [comment]
@xxMUROxx once I get #2892 done and approved / rejected, I will look at tackling this and #2889 (I added commits to the above PR that shouldn't have been there 💩 , so now I want to get it taken care of before I tackle anything else)

**Comment by xxMUROxx** [comment]
@amkuchta You can remove the commits that are wrong on the branch representing the PR. Then you can `git push -f` to update the PR. Since no merge is done yet, there is no problem if you rewrite history.

**Comment by amkuchta** [comment]
@punker76 do you want me to roll this and #2889 into #2898 (I would rename the PR to "Watermark Enhancements", but this seems to fit there), or are you actively working it now?

@xxMUROxx thanks for the advice - I separated the PR, so now I can work this without any guilt 😄

**Comment by amkuchta** [comment]
@xxMUROxx I mixed the `TextBox` and `TextBlock` controls up... `TextBox` does not have a `TextTrimming` property.  I am integrating a new DependencyProperty to handle this.

**Comment by amkuchta** [comment]
@xxMUROxx @punker76 So, if I have both `TextTrimming` and `TextWrapping` set for the watermark, `TextWrapping` overrides `TextTrimming`.  Should we keep it this way, or should I make `TextTrimming` the dominant behavior?
