### ISSUE TITLE
[Bug] Badged Control Causes Window Loading to Hang

### ISSUE THREAD

**Issue by amkuchta** [MahApps/MahApps.Metro#2885]
## What steps will reproduce this issue?

_Wrapping a `TextBox` in a `Badged` control (bound to the `TextBox`'s `Text.Length` property) causes the window to hang when loading - the `GlowBoarder` will load, but nothing else.  Code Snippet provided below:_

```xaml
<Controls:Badged Margin="5,0,5,5" Badge="{Binding ElementName=badgeTest, Path=Text.Length}" BadgePlacementMode="TopLeft">
  <TextBox x:Name="badgeTest" Controls:TextBoxHelper.Watermark="Enter sometext!" />
</Controls:Badged>
```

### Expected outcome

_Window should load and the badge should show the length of the text in the named `TextBox`_

### Repo

_https://github.com/amkuchta/Vulnerator/tree/code_cleanup (code can be found in the "RmfView.xaml" file and is currently commented out)_

### Environment

- MahApps.Metro __v1.5.0-alpha007__
- Windows OS __10__
- Visual Studio __2017__
- .NET Framework __4.5.2__

**Comment by amkuchta** [comment]
@ButchersBoy this one might interest you, since you implemented the `Badge` Control

**Comment by punker76** [comment]
@amkuchta I can't start your Vulnerator sample, so I extracted the view and put it into the main demo and can not reproduce what you say. So please, try to figure it out if this is really the problem of the badged control, try to create a short sample app which reproduces your issue, thx

![badged_test](https://cloud.githubusercontent.com/assets/658431/23861551/b548e0b2-080a-11e7-87c1-b2ae58b6eac0.gif)

**Comment by amkuchta** [comment]
@punker76 to get the Vulnerator app to build, try copying the `x86` and `x64` folders from the main "Vulnerator" folder into "/bin/Debug".  I think that should solve your issues.

**Comment by amkuchta** [comment]
@punker76 new info - I am now getting an exception (had to disable "Just My Code"):

_"Exception = 'BadseScaleTransform' name cannot be found in the name scope of 'System.Windows.Controls.ControlTemplate'."_
