### ISSUE TITLE
Unwanted window dragging and mini/maximizing

### ISSUE THREAD

**Issue by Ziriax** [MahApps/MahApps.Metro#2893]
First of all thanks a lot for this great library!

I have a question, maybe an issue. 

I placed a button on the titlebar. When the button is disabled, double clicking on it will  mini/maximizing the window. Also when dragging the disabled button, the window also drags.

The same happens for flyouts that cover  the titlebar. Double clicking resp dragging on the flyout in the titlebar region  mini/maximizing resp drags the window.

I don't think this is expected behavior? Do you have a way to disable titlebar interaction on some elements, like flyouts?

Currently I made an attached behavior that suppressed all double click preview events and click events, but this feels like a hack.

Thanks a lot,
Peter Verswyvelen

**Comment by punker76** [comment]
@Ziriax 

>I placed a button on the titlebar. When the button is disabled, double clicking on it will mini/maximizing the window. Also when dragging the disabled button, the window also drags.

yes, the titlebar is the control which handles double click and dragging. so if you put e.g. buttons on it and this buttons are disabled the titlebar wins. to prevent this you can put your button on the left or right window commands.

>The same happens for flyouts that cover the titlebar. Double clicking resp dragging on the flyout in the titlebar region mini/maximizing resp drags the window.

yes, that's correct, this is a feature of MahApps.

**Comment by punker76** [comment]
@Ziriax Can I close this? Or do you need more help?
