### ISSUE TITLE
[RFC] [Enhancement] Proposed TabControlHelper.IsUnderlined Change

### ISSUE THREAD

**Issue by amkuchta** [MahApps/MahApps.Metro#2895]
### Description
Since the TabControl got an underline a while back, I have wanted to update it to have an underline all the way across, but wasn't able to get around to it.  I wanted to put the idea to a vote and see how the community at large feels.  If you like it, please 👍 .  If you would prefer to keep the underline how it is, please 👎 .  As always, @punker76 and the rest of the contributors, please feel free to override me.  Additionally, I can look into creating a new attached property, e.g. `TabControlHelper.UnderlineHeaderPanel` to make it an optional feature.

### Sample Screenshot
![updatedtabcontrolunderline](https://cloud.githubusercontent.com/assets/6255186/24024856/ec2d2186-0a8c-11e7-9978-51ba634eba20.gif)

**Comment by amkuchta** [comment]
@flagbug @Amrykid @laicasaane @Malavos @DylanDoppelt @100GPing100 since you guys all had some input for the original underline, I am especially interested in hearing what you have to say about this

**Comment by punker76** [comment]
@amkuchta I'll look what we can do

**Comment by amkuchta** [comment]
@punker76 I can handle this one if you'd rather assign me to it.  I already started working it in on my side, and can take this off of your plate

**Comment by amkuchta** [comment]
I'm trying to pull my weight 😆

**Comment by 100GPing100** [comment]
As long as it stays optional and does not break any current features I'd say why not :+1:

**Comment by amkuchta** [comment]
@punker76 I'll work this on https://github.com/amkuchta/MahApps.Metro/tree/underlined_tabcontrol_enhancement.  You'll see a PR for it sometime this weekend.
