### ISSUE TITLE
[Suggestion] MetroDemo Re-Organization

### ISSUE THREAD

**Issue by amkuchta** [MahApps/MahApps.Metro#2896]
With all of the awesome enhancements, MetroDemo has gotten a bit... unruly.  I propose restructuring the examples so that they are easier to follow and better give users an idea of how to implement controls.  Some suggestions:

- More `CheckBoxes` / `ToggleSwitches` to control DependencyProperties
- `HamburgerMenu` for navigation instead of `TabControl`
- A tiny editor to help users grab WPF snippets

I'm willing to take this on if everyone is on board.  What does everyone think?

**Comment by DavidNgugi** [comment]
That will be awesome

**Comment by amkuchta** [comment]
I'm gonna give it a go @DavidNgugi  - progress can be watched [here](https://github.com/amkuchta/MahApps.Metro/tree/metrodemo-rework)

**Comment by punker76** [comment]
This will continued in #3818
