### ISSUE TITLE
[Suggestion Request] Metro Style Charts Framework working with Mahapps. 

### ISSUE THREAD

**Issue by lasikye** [MahApps/MahApps.Metro#2900]
Hi Guys.

I`m looking for a metro style charts framework which can work with Mahapps perfectly.

By right, I have found one named 'WPF Metro UI Charts' (http://gamandelkowcharts.codeplex.com/), but I don`t kown whether it can work good because it has stopped updating since Oct 8, 2015.

 Can anyone give me some suggestions ?

**Comment by MoiraG** [comment]
my favourite: https://github.com/beto-rodriguez/Live-Charts

**Comment by amkuchta** [comment]
I second [LiveCharts](https://github.com/beto-rodriguez/Live-Charts) - I have started integrating it with my app, and I love the layout / design.  Additionally, it is also _very_ actively maintained, which is important - they even have a Gitter room that is always in use.
