### ISSUE TITLE
MahApps.Metro Compatibility issues with Windows 7 and Windows 10

### ISSUE THREAD

**Issue by nikhilSulibhavi** [MahApps/MahApps.Metro#2901]
I am using Visual studio 2015 Professional (running in Windows 7) to build a WPF application with MetroUI (MahApps.Metro). I installed the MahApps.Metro.dll for the application through NuGet Manager. The behaviour I observed is that, the application built in Windows 7 OS does not work in Windows 10 and vice versa. When I remove MahApps.Metro.dll dependency from the application, then the application works fine in both Windows 7 and Windows 10 OSs. But for CSS, I need MahApps.Metro.dll. 
Is there any way in which I can access the MahApps.Metro.dll such that irrespective of the OS, it works fine.

.Net Framework - 4.5
Visual Studio - 2015
MahApps.Metro - 1.5.0.0
Development OS - Windows 7
Deployment OS - Windows 10
Error when deployed - Cannot start this application.

**Comment by punker76** [comment]
@nikhilSulibhavi Did you also include the `System.Windows.Interactivity.dll` (which also comes with MahApps NuGet)?
