### ISSUE TITLE
TextBoxHelper.IsClearTextButtonBehaviorEnabled can not be attached to a textbox

### ISSUE THREAD

**Issue by panhans** [MahApps/MahApps.Metro#2904]
## What steps will reproduce this issue?

```
<TextBox Controls:TextBoxHelper.ClearTextButton="True"
                     Controls:TextBoxHelper.IsClearTextButtonBehaviorEnabled="False"/>
```

### Expected outcome

No warning and no clear behaviour ;)

### Environment

- MahApps.Metro __v1.4.3__
- Windows OS __10__
- Visual Studio __2015__
- .NET Framework __4.6__

**Comment by punker76** [comment]
@panhans The `IsClearTextButtonBehaviorEnabled` is a style helper attached property and should not use from outside. (maybe it's better to put it on the new updated documentation)
