### ISSUE TITLE
XamlStyler Configuration File Format Update

### ISSUE THREAD

**Issue by amkuchta** [MahApps/MahApps.Metro#2906]
XmlStyler now has the ability to support a per-project or per-solution style via the use of `Settings.XamlStyler` files - create a file for each project or solution, then drop it into the file structure.  I recommend moving to this instead of globally overriding the default settings via the current *.vssettings file - I moved all of the settings to the appropriate file, which is attached.  Going down this route allows users to maintain the formatting for MahApps without changing the formatting of other projects.
[Settings.XamlStyler.zip](https://github.com/MahApps/MahApps.Metro/files/864480/Settings.XamlStyler.zip)

**Comment by amkuchta** [comment]
Change: `ReorderSetters` would need to be changed from `TargetNameThenProperty` to `3`

**Comment by punker76** [comment]
XamlStyler settings now up to date (both added, the XamStyler.Settings and vs settings files)
