### ISSUE TITLE
MetroTabControl & Caliburn.Micro binding issue.

### ISSUE THREAD

**Issue by C1rdec** [MahApps/MahApps.Metro#2907]
The binding is lost inside a MetroTabControl.
I've overridden `ViewModelBinder.HandleUnmatchedElements` of Caliburn Micro and there's 5 elements unmatched.

As soon as I add a regular TabControl in the Xaml the binding of the MetroTabControl is fixed and those 5 unmatched elements are gone.

Here is a simple repo : https://github.com/C1rdec/Mahapps.SimpleRepo.TabControl

The ViewModelBinder.HandleUnmatchedElements is in the Bootstrapper and the regular TabControl is commented. To fix the binding you just need to uncomment the regular TabControl.

**Comment by punker76** [comment]
@C1rdec Is fixed (take current alpha) and will be available in 1.5.0.
