### ISSUE TITLE
Is it possible to load User Control in Flyout

### ISSUE THREAD

**Issue by obrana-boranija** [MahApps/MahApps.Metro#2908]
As title says:
Is it possible to load user control in flyout?

Do we have an example anywhere. I'm googleing it for a couple of days, but i cant find anything that might help...

Thanks in advance.

**Comment by punker76** [comment]
@obrana-boranija Have you tried this one?

```xaml
<Controls:MetroWindow.Flyouts>
    <Controls:FlyoutsControl x:Name="flyoutsControl">
        <Controls:Flyout x:Name="superFlyout">
        	<local:YourUserControl />
        </Controls:Flyout>
    </Controls:FlyoutsControl>
</Controls:MetroWindow.Flyouts>
```

**Comment by obrana-boranija** [comment]
Well... yes, but i'm trying to open it from another user control... i just saw that i forgot to mention it...

And that is exact problem... So, i cant use <Controls:MetroWindow.Flyouts>

**Comment by obrana-boranija** [comment]
My mistake... I forgot to add Row Span... Actually it was showing only in grid row 0 which height is only 25...

I couldn't see that flyout :)

                    <Controls:FlyoutsControl Grid.RowSpan="4" >
                        <Controls:Flyout x:Name="Flyout">
                            <local:ArtikliDodajNovi />
                        </Controls:Flyout>
                    </Controls:FlyoutsControl>
