### ISSUE TITLE
Question - How can i use an icon from an icon pack in the code behind?

### ISSUE THREAD

**Issue by BornToBeRoot** [MahApps/MahApps.Metro#2909]
```
static PackIconMaterial IconTrendingUp = new PackIconMaterial()
        {
            Kind = PackIconMaterialKind.TrendingUp
        };
```
I need it as canvas for my application list... this list is bound in different windows.

This won't work with icons from the pack... 
`Application.Current.Resources["appbar_network"] as Canvas`

**Comment by punker76** [comment]
@BornToBeRoot The PackIconXYZ are controls, so you can't cast it to Canvas. You can add it to a canvas like

```
var canvas = new Canvas();
var icon = new PackIconMaterial() {  Kind = PackIconMaterialKind.TrendingUp };
canvas.Children.Add(icon);
Canvas.SetLeft(icon, 5);
Canvas.SetTop(icon, 5);
```

**Comment by BornToBeRoot** [comment]
Thx, i will try it :+1:

**Comment by thopper** [comment]
![image](https://user-images.githubusercontent.com/43042526/60439956-5e12a700-9bd9-11e9-8825-b3bb5fcd94fb.png)
