### ISSUE TITLE
WPF How to use MahApps.Metro MessagBox in UserControl

### ISSUE THREAD

**Issue by a516117636** [MahApps/MahApps.Metro#2910]
In UserControl,I can not use the method ShowMessageAsync().What can I do to use it.

**Comment by punker76** [comment]
@a516117636 You have 2 options to do that

1) Find the parent MetroWindow and call it with the ShowMessageAsync method. You can use the `TryFindParent` method located in the `TreeHelper` class.
2) Use the DialogCoordinator  described [here](https://dragablz.net/2015/05/29/using-mahapps-dialog-boxes-in-a-mvvm-setup/) This isn't currently shown in the latest docs, but will be coming soon.

**Comment by a516117636** [comment]
Thanks for you reply!
