### ISSUE TITLE
[Enhancement] Create ToggleButton Styles to Match Button Styles

### ISSUE THREAD

**Issue by amkuchta** [MahApps/MahApps.Metro#2912]
Working on a new MetroDemo, I have noticed that there are not `ToggleButton` styles for each of the `Button` Styles available.  For continuity within users' applications, MahApps.Metro should offer the same styles for both types of buttons.  Current style status:

- [x] Default
- [x] Flat
- [x] Circle
- [ ] Square
- [ ] Accented Square
- [ ] Highlighted Square
- [ ] Accented
- DropDownButton?
- SplitViewButton?

**Comment by amkuchta** [comment]
@punker76 I noticed that the same issue applies for `DropDownButton` and `SplitViewButton` controls - should I create a separate issue for those, or would you like me to update this one to include them?

**Comment by punker76** [comment]
@amkuchta I included them, but make this on hold. I'm not sure if this is really needed to make square and accented styles for DropDownButton or SplitViewButton, cause these controls a little bit different to normal Buttons / ToggleButons.

**Comment by amkuchta** [comment]
@punker76 I know that from personal use, I have a `SplitViewButton` lying next to a standard button, and I ended up rolling my own style to  match the two.  For me, having that similar styling helps to show the users that it is still a `Button`-type of control, not a `ComboBox` (and it just looks cleaner in my application).  Maybe once 1.5.0 is out, we could put this up to a vote using Gitter?
