### ISSUE TITLE
How to use Mahapps Progress Dialog Box in WPF Page?

### ISSUE THREAD

**Issue by GaneshSingaravelu** [MahApps/MahApps.Metro#2913]
Hi,

User can upload the excel sheet through WPF page. It takes some time to process the data. So i want to show Progress Dialog box in WPF page. Please let me know the solution to achieve this.

Note : I'm not using MVVM architecture.

### Expected outcome

Need to show progress bar in WPF Page.

### Environment

- MahApps.Metro __1.4.3
- Windows OS __ Windows 7
- Visual Studio __2013
- .NET Framework __ 4.5.1

**Comment by punker76** [comment]
@GaneshSingaravelu This is currently not possible, the Dialogs need always a MetroWindow. I'll create something like a DialogManager and some Interfaces in the future to use Dialogs in Pages and UserControls...

**Comment by Foxtrek64** [comment]
It's not a perfect solution, but here's what I do:

1. In my main window, I create the following method:
```csharp
public async Task<MessageDialogResult> PromptAsync(string title, string message, MessageDialogStyle style = MessageDialogStyle.Affirmative, MetroDialogSettings settings = null)
{
    return await this.ShowMessageAsync(title, message, style, settings);
}
```
2. In your page configuration, do the following:
```csharp
    public partial class MyPage : Page
    {
        MainWindow mainWindow;
        public MyPage(MainWindow mw)
        {
            InitializeComponent();
            mainWindow = mw;
        }
}
```
3. Build your button and add a click handler with the following code:
```csharp
private void ShowMessage_Click(object sender, RoutedEventArgs e)
{
    mainWindow.ShowMessageAsync("This is the title", "This is the message");
}
```

As stated, this is not a *perfect* solution, but it will get you what you're looking for.

This assumes that
1. The body of your MainWindow contains a Frame object
2. You are generating your pages on the fly

```csharp
public MainWindow()
{
    MyPage myPage = new MyPage(this);
    _MainFrame.Navigate(myPage);
}
```

**Comment by Rkolbe69** [comment]
Hello good People,
i tryed to use this code but i'm got this error:

_System.MissingMethodException: "No default constructor was found for the type "MyApp.FunctionPages.pgMyPage". The type can be created using the Arguments or FactoryMethod directive"._

What can i do to solve this problem... The code is the same like above...

Thanks for help

**Comment by timunie** [comment]
Hi @Rkolbe69 

please open a new issue for this with all needed information if you think it is an issue (fill the template!) or ask on gitter ( https://gitter.im/MahApps/MahApps.Metro ) if you just need support to get your App running. Sounds like there is an issue in your `ViewModel`, not in MahApps.

Thank you and happy coding 
Tim

**Comment by Rkolbe69** [comment]
Thanks for your information...
