### ISSUE TITLE
System.ArgumentException: Width and Height must be non-negative.

### ISSUE THREAD

**Issue by Marco-MUC** [MahApps/MahApps.Metro#2915]
## Repro Requirements
A screen where orientation can be changed from landscape to portrait mode in Windows.

## What steps will reproduce this issue?
- start the Demo application: MahApps.Metro.Demo.NET40 or NET45 which is included in the repository
- change orientation of screen to portrait
- maximize the Demo Application
- wait until timer will reset the orientation back to landscape (or reset manually if "keep changes" was pressed before)
- click the minimize button
-> System.ArgumentException: "Width and Height must be non-negative." occurs

### Expected outcome
- The application must not crash 
- The application gets minimized

### Repo
[MahApps.Metro](https://github.com/MahApps/MahApps.Metro)

### Environment
- MahApps.Metro v1.4.3
- Windows 7 Professional
- Visual Studio 2015
- .NET Framework 4.6.2

## Remarks
In our case the app crash occurs when using our own app on a notebook while presenting the app on different beamers and resolutions (but without having different orientations). But this is really hard to reproduce.

**Comment by punker76** [comment]
@Marco-MUC Can you maybe proviede a stracktrace? thx.

**Comment by Marco-MUC** [comment]
There is no stacktrace. The stacktrace only states [external]
see:
![screenshot1](https://cloud.githubusercontent.com/assets/26785019/24491474/b7b6ec0c-1527-11e7-8701-6042e535efde.png)

**Comment by punker76** [comment]
@Marco-MUC I can't reproduce this under my Win10 machine™. If I have time then I will create a Win 7 VM to test this. For the stack trace, maybe you should switch on the exceptions, otherwise you can see it on the main thread.

**Comment by Marco-MUC** [comment]
I tried to reproduce the bug with Windows 10 and I was unable to reproduce it, also. It looks like there is some kind of hardware combination necessary, because I'm also unable to reproduce this bug with 3 monitors on Windows 7. But we have seen this bug on different machines with different hardware.

According the StackTrace:
The exception will be thrown in Main Thread. It looks like someone tries to create a Windows.Rect (constructor call) with negative width or height. There are no more details. Even there is no exception dialog with more information:

![screenshot2](https://cloud.githubusercontent.com/assets/26785019/24505451/385ceabe-155a-11e7-9013-6b7757538f29.png)

Content of "Copy exception details to the clipboard):
System.ArgumentException was unhandled
Message: An unhandled exception of type 'System.ArgumentException' occurred in WindowsBase.dll
Additional information: Width and Height must be non-negative.

**Comment by punker76** [comment]
@Marco-MUC thx. I'll try to find it out.

**Comment by punker76** [comment]
@Marco-MUC Can you try to reproduce this with these scenarios and a simple app (only a MetroWindow)?

- with a BorderBrush
- with a GlowBrush

thx.

**Comment by Marco-MUC** [comment]
@punker76 I've tracked it down to the following statement in the csproj file:
`<Prefer32Bit>false</Prefer32Bit>`
If this one is added to the project the error occurs. Otherwise the application can be maximized and minimized without having problems.

To identify that, I've created a new WCFApplication and added only MahApps as NuGet package and changed Window to MetroWindow. But this application was running without any problem. So I've started to strip down the demo application to only have the same empty window without any other classes that could cause the problem. But the problem was still there. So at last I've checked the csproj file and then I was able to identify the XmlNode that decides between app crash or not.

My MainWindow consists only of the following code:
```
<controls:MetroWindow x:Class="WpfApplication1.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:controls="http://metro.mahapps.com/winfx/xaml/controls"
        Title="MahApps.Metro - Demo Application"
        Width="960" 
        Height="600"
        Icon="mahapps.metro.logo2.ico"
	ShowIconOnTitleBar="True"
        WindowStartupLocation="CenterScreen">
    <Grid>
    </Grid>
</controls:MetroWindow>
```

Should I still try the different brushes?

**Comment by Marco-MUC** [comment]
Addendum:
Our application runs in 32Bit but also has the problem.

**Comment by punker76** [comment]
@Marco-MUC would be nice if you test the brush stuff. thx. is your win os also 32bit or 64bit win 7?

**Comment by Marco-MUC** [comment]
@punker76:
added  
`GlowBrush="Aqua"`
-> same Problem

added 
`BorderBrush="Aqua"`
(and removed GlowBrush)
-> same Problem

OS is 64bit

**Comment by punker76** [comment]
@Marco-MUC He, can you try it agian with 1.6.0-alpha015? there are some changes under the hood. thx
