### ISSUE TITLE
Can I making the slider slide with one click anywhere on the slider?

### ISSUE THREAD

**Issue by xue-blood** [MahApps/MahApps.Metro#2919]
Hey guys,

I am trying to get the Slider to behave like this:
If the user clicks (mouse down) on the slider somewhere the thumb is moved to the location of the click immediately
when the user clicked on the slider and he moves the mouse, the thumb is sliding with the cursor...
1.
Apparently there is a property called "IsMoveToPointEnabled" that if set to True causes the RepeatButton behaviour of the Slider to disappear and the thumb immediately moves to the point where clicked. 

2.
This is the default behaviour of the slider if you click on the thumb anyway but unfortunately if you click not on the thumb (thus using the IsMoveToPointEnabled) you cannot move the thumb after the first click without clicking on the thumb again.

Any ideas on how to overcome this? Any hints appreciated.

**Comment by punker76** [comment]
@xue-blood Have you tries to look at SO? You're right this is the default behavior of a Slider, cause there are different Controls, the Thumb and the 2 Repeat Buttons which handles the increase and decrease change.

**Comment by xue-blood** [comment]
@punker76  Yes you are right , so now I write a new slider inherit the default Slider.
