### ISSUE TITLE
TitlebarHeight in MVVM

### ISSUE THREAD

**Issue by sagevpremium** [MahApps/MahApps.Metro#2924]
Hi, i have short question:

How can I change TitlebarHeight dynamically in MVVM? 
That's what i want to do:
I have one main window and user control's in it, and title bar must be visible with one user control in different cases must be hided.

How can I do it?
Thx for help

**Comment by punker76** [comment]
@sagevpremium TitlebarHeight and ShowTitleBar are DependencyProperty of the MetroWindow, so you can simply bind to it via MVVM properties.

**Comment by StefanK1** [comment]
Is it possible to animate the TitlebarHeight from 0 to 30 and from 30 to 0 (for example) ?
Thanks
