### ISSUE TITLE
[Error] Textbox Select All On Focus

### ISSUE THREAD

**Issue by trangthancb** [MahApps/MahApps.Metro#2925]
Hi,
I have little problem when using TextBoxHelper.SelectAllOnFocus = "True"
When I click outside the text, the program can not select all the text in the textbox.
If I click on the text, the function will work perfectly,
http://imgur.com/a/EFMKL

Thank you, It's not a serious problem, you can ignore this request.

### Environment

- MahApps.Metro 1.5.0.23
- Windows OS 10 64bit
- Visual Studio 2013
- .NET Framework 4.0

**Comment by punker76** [comment]
I don't really understand what's wrong, just tested and it works. If I click on free space the text is completely selected. If I keep the mouse down I can change the selection by dragging the mouse.

**Comment by trangthancb** [comment]
Hi, 

Thanks for your feedback
If the textbox has many lines, and each line is short. An error occurs when you click outside the text line (single click)
You can view photos described below:
http://i.imgur.com/cUsLoD0.png
If I click on the yellow dot (click outside the text line - the line of text has ended): I will get an error
And if I click on the blue point: everything is fine
You can review the gif image below:
http://imgur.com/a/EFMKL

**Comment by punker76** [comment]
@trangthancb Can you try this without setting the MahApps style? The TextBoxHelper should work with normal TextBox too. I think this is not a bug, more the normal behavior of the SelectAll method.

```
<TextBox Style="{x:Null}" TextBoxHelper.SelectAllOnFocus = "True" />
```

**Comment by trangthancb** [comment]
Thanks you very much!
<TextBox Style="{x:Null}" **TextBoxHelper.SelectAllOnFocus = "True"** />
TextBoxHelper.SelectAllOnFocus = "True" not working if Style="{x:Null}"
I think it does not affect anything. Thanks for supporting me!
Love

**Comment by punker76** [comment]
@trangthancb Did you tested with my last note? I think this isn't an issue by MahApps...

**Comment by trangthancb** [comment]
Although it was not as expected but thank you very much
I think it's all right, the MahApps project is awesome!
Thank you!
