### ISSUE TITLE
IsPaneOpen property in Hamburger Menu is not properly set after opening/closing pane

### ISSUE THREAD

**Issue by wornr** [MahApps/MahApps.Metro#2926]
Hello,

I'm trying to implement (with MVVM) auto closing hamburger pane after selection is done. To make this happen I've tried to bind IsPaneOpen to IsPaneOpened property in my view model.

`<mahApps:HamburgerMenu IsPaneOpen="{Binding IsPaneOpened}" ...>`

But it seems that IsPaneOpen is not setting my property properly when I open/close pane with this button.
![image](https://cloud.githubusercontent.com/assets/17750885/25064498/adc01210-21fb-11e7-8bd0-d15ce5325b9e.png)

Is that normal behaviour or am I doing something wrong?

Btw. In my opinion this property has really weird explanation.
![image](https://cloud.githubusercontent.com/assets/17750885/25064548/9ea12a70-21fc-11e7-8361-3bf1dd4e5a28.png)

### Environment
MahApps.Metro v1.5.0
Windows OS 10
Visual Studio 2017
.NET Framework 4.5.2

**Comment by punker76** [comment]
@wornr The `IsPaneOpen` is not set automatically, this is in your hand e.g https://github.com/MahApps/MahApps.Metro/blob/develop/src/MahApps.Metro.Samples/MahApps.Metro.Demo/MahApps.Metro.Demo.Shared/ExampleViews/HamburgerMenuSample.xaml.cs#L23-L27. The wrong documentation will be fixed.

**Comment by punker76** [comment]
@wornr A short tipp, set the mode explicit: `IsPaneOpen="{Binding IsHamburgerMenuPaneOpen, Mode=TwoWay}"`

**Comment by wornr** [comment]
I didn't realize it's so simple. Now everything works like a charm. Thank for fast reply and help.

**Comment by punker76** [comment]
@wornr ok, I will add `FrameworkPropertyMetadataOptions.BindsTwoWayByDefault` to this property.
