### ISSUE TITLE
Checkbox checkmark accent is hard to see against dark flyout

### ISSUE THREAD

**Issue by Jehoel** [MahApps/MahApps.Metro#2927]
My WPF application using MahApps.Metro uses a Flyout for the app's Settings UI. Most of the users use the default "Light" theme with the "Blue" accent color. The Flyout is `Modal="True"` and configured with the defaults). Under these conditions checkboxes in the flyout have checkmarks that don't stand-out very well:

![image](https://cloud.githubusercontent.com/assets/1693078/25081132/4ed4ad08-22fd-11e7-8c16-3b2df9c13044.png)

A quickfix is to change the checkmark brush to use a lighter shade of accent, if not white, when a checkbox is displayed in a flyout.

### Environment

- MahApps.Metro v1.5.0
- Windows 10
- Visual Studio 2015
- .NET Framework 4.6.1

**Comment by punker76** [comment]
@Jehoel The CheckBox and RadioBox uses the `HighlightBrush` brush for the check mark and pressed status. You can override these in your Flyout resources like this

```xaml
<Style TargetType="{x:Type CheckBox}"
        BasedOn="{StaticResource MetroCheckBox}">
    <Style.Resources>
        <SolidColorBrush x:Key="HighlightBrush" Color="{DynamicResource AccentColor}" />
    </Style.Resources>
</Style>
```

(or whatever color you need)

Hope this helps.

**Comment by punker76** [comment]
@Jehoel Do you need more help?

**Comment by Jehoel** [comment]
Sorry, I had my Github notifications turned off. I'll try this later tonight and let you know.

**Comment by Jehoel** [comment]
Using `AccentColor` is still too dark - and I noticed the other shades (e.g. `AccentColorBrush4`) are just differing opacity levels, so they're even harder to see on a black background.

I would like to reference the color used by the current FlyoutForegroundBrush`, however that color is defined by `StaticResource BlackColor` (which is actually white) which I cannot directly access (`{StaticResource BlackColor}` gives me black).

How should I get white color if the flyout is dark, but a dark color if the flyout is white?

**Comment by punker76** [comment]
@Jehoel If you have a dark Flyout you need the `WhiteColor` or `IdealForegroundColor` and vice versa, for light Flyout the `BlackColor`.

```
<SolidColorBrush x:Key="HighlightBrush" Color="{DynamicResource WhiteColor}" />
```
```
<SolidColorBrush x:Key="HighlightBrush" Color="{DynamicResource IdealForegroundColor}" />
```
![image](https://cloud.githubusercontent.com/assets/658431/25887568/f3b9f464-3562-11e7-847d-3e4b090dab67.png)

**Comment by Jehoel** [comment]
Perfect, thanks!

**Comment by Mgamerz** [comment]
Has this changed for the Mahapps 2.0? I added your code to the window resources that contains the checkbox (and adjusted to be based on the Mahapps.Styles.Checkbox style), but it still doesn't let me change the color.

![image](https://user-images.githubusercontent.com/2738836/105640784-1ac3fd00-5e3d-11eb-945a-7428291007f6.png)

I see a lot of extensions in CheckboxHelper, but not sure if these do anything, as there is no documentation on them. https://mahapps.com/api/MahApps.Metro.Controls/CheckBoxHelper/

**Comment by Jehoel** [comment]
@Mgamerz Yes, it changed to `MahApps.Brushes.Highlight` in MahApps 2.0.

Here's the updated XAML (I've also included my style changes for Radio buttons and Hyperlinks as well):

```
<Style x:Key="inputCheckbox" TargetType="CheckBox" BasedOn="{StaticResource MahApps.Styles.CheckBox}">
		<Setter Property="Margin" Value="0 0 0 6" />
		<!-- Make checkbox checkmarks more visible: https://github.com/MahApps/MahApps.Metro/issues/2927#issuecomment-294739088 -->
		<Style.Resources>
			<SolidColorBrush x:Key="MahApps.Brushes.Highlight" Color="{DynamicResource MahApps.Colors.IdealForeground}"  />
		</Style.Resources>
	</Style>
	<Style x:Key="inputRadio" TargetType="RadioButton" BasedOn="{StaticResource MahApps.Styles.RadioButton}">
		<Setter Property="Margin" Value="0 0 0 6" />
		<Style.Resources>
			<SolidColorBrush x:Key="MahApps.Brushes.Highlight" Color="{DynamicResource MahApps.Colors.IdealForeground}"  />
		</Style.Resources>
	</Style>
	<Style x:Key="settingsHyperlink" TargetType="{x:Type Hyperlink}" BasedOn="{StaticResource {x:Type Hyperlink}}">
		<!-- https://stackoverflow.com/questions/1252889/changing-hyperlink-foreground-without-losing-hover-color -->
		<!--<Setter Property="Foreground" Value="{DynamicResource LabelTextBrush}" /> 2020-07-01: `LabelTextBrush` is removed. -->
		<Setter Property="Foreground" Value="{DynamicResource MahApps.Brushes.IdealForeground}" />
	</Style>
```

**Comment by timunie** [comment]
Hi @Jehoel 

I am not sure if your code will work in the latest version of MahApps. The `CheckBox-Glyph` does not use `MahApps.Brushes.Highlight` anymore but has its own `Brushes`. 

I transferred the question and my answer to #4026 

Happy coding 
Tim

**Comment by Jehoel** [comment]
@timunie Ah, I'm using MahApps.Metro 2.1.1. I see the latest is 2.4.3 - so yeah, I'm a bit out of date.
