### ISSUE TITLE
Window border brush

### ISSUE THREAD

**Issue by Pekshev** [MahApps/MahApps.Metro#2929]
I'm update from version 1.1.2.0 to 1.5.0.0. I have in my code such part:
```
public static void ChangeWindowBordes(string borderType, MetroWindow window)
{
    try
    {
        if (borderType.Equals("AccentBorder"))
        {
            window.BorderThickness = new Thickness(1);
            window.SetResourceReference(Control.BorderBrushProperty, "AccentColorBrush");
            window.GlowBrush = Brushes.Transparent;
        }
        if (borderType.Equals("NoBorder"))
        {
            window.BorderThickness = new Thickness(0);
            window.BorderBrush = Brushes.Transparent;
            window.GlowBrush = Brushes.Transparent;
        }
        if (borderType.Equals("AccentGlowBrush"))
        {
            window.BorderThickness = new Thickness(0);
            window.SetResourceReference(MetroWindow.GlowBrushProperty, "AccentColorBrush");
            window.BorderBrush = Brushes.Transparent;
        }
        if (borderType.Equals("AccentBorderGlowBrush"))
        {
            window.BorderThickness = new Thickness(1);
            window.SetResourceReference(MetroWindow.GlowBrushProperty, "AccentColorBrush");
            window.BorderBrush = Brushes.Transparent;
        }
        if (borderType.Equals("Shadow") || string.IsNullOrEmpty(borderType))
        {
            window.BorderThickness = new Thickness(0);
            window.GlowBrush = Brushes.Black;
            window.BorderBrush = Brushes.Transparent;
        }
    }
    catch
    {
        window.BorderThickness = new Thickness(0);
        window.GlowBrush = Brushes.Black;
        window.BorderBrush = Brushes.Transparent;
    }
}
```
so, before update it work fine. Now dont work when set variant "AccentBorder"

**Comment by punker76** [comment]
@Pekshev Mh, maybe a undocumented breaking change, so sorry for that. To fix this, set the BorderBrush and GlowBrush to `null` instead to `Brushes.Transparent`.

**Comment by Pekshev** [comment]
O, thx! It's work now

**Comment by Pekshev** [comment]
This is my code to change borders:
`public static void ChangeWindowBordes(string borderType, MetroWindow window)
        {
            try
            {
                if (borderType.Equals("AccentBorder"))
                {
                    window.BorderThickness = new Thickness(1);
                    window.SetResourceReference(Control.BorderBrushProperty, "AccentColorBrush");
                    window.GlowBrush = null;
                }
                if (borderType.Equals("NoBorder"))
                {
                    window.BorderThickness = new Thickness(0);
                    window.BorderBrush = null;
                    window.GlowBrush = null;
                }
                if (borderType.Equals("AccentGlowBrush"))
                {
                    window.BorderThickness = new Thickness(0);
                    window.SetResourceReference(MetroWindow.GlowBrushProperty, "AccentColorBrush");
                    window.BorderBrush = null;
                }
                if (borderType.Equals("AccentBorderGlowBrush"))
                {
                    window.BorderThickness = new Thickness(1);
                    window.SetResourceReference(MetroWindow.GlowBrushProperty, "AccentColorBrush");
                    window.BorderBrush = null;
                }
                if (borderType.Equals("Shadow"))
                {
                    window.BorderThickness = new Thickness(0);
                    window.GlowBrush = Brushes.Black;
                    window.BorderBrush = null;
                }
                if (string.IsNullOrEmpty(borderType))
                {
                    window.BorderThickness = new Thickness(1);
                    window.SetResourceReference(Control.BorderBrushProperty, "AccentColorBrush");
                    window.GlowBrush = null;
                }
                Action EmptyDelegate = delegate () { };
                window.Dispatcher.Invoke(DispatcherPriority.Render, EmptyDelegate);
            }
            catch (Exception exception)
            {
                ExceptionBox.ShowForConfigurator(exception);
                window.BorderThickness = new Thickness(0);
                window.GlowBrush = Brushes.Black;
                window.BorderBrush = null;
            }
        }`
I make gif: first time i open app borders sets to "AccentBorder" variant - as you can see there is problem on change borders/ At second time on app's open sets "AccentGlowBrush" varian and then borders changing without problems
![borders](https://user-images.githubusercontent.com/12638819/35062796-51dc147a-fbd6-11e7-958c-0f58bbc55b13.gif)

**Comment by Pekshev** [comment]
![borders](https://user-images.githubusercontent.com/12638819/35062796-51dc147a-fbd6-11e7-958c-0f58bbc55b13.gif)

**Comment by punker76** [comment]
@Pekshev Just got it.

It's currently not possible to change the GlowBrush at runtime if it's not set before that, e.g. in Xaml.

To solve this, you can

- set a dummy brush to the GlowBrush property in Xaml on your MetroWindow
- or call your code once at the ctor

```csharp
public MainWindow()
{
    InitializeComponent();
    this.DataContext = new Model();

    TestBorder("AccentBorderGlowBrush");
    this.Loaded += MainWindow_Loaded;
}

private void MainWindow_Loaded(object sender, RoutedEventArgs e)
{
    TestBorder("AccentBorder");
}

private void TestBorder(string borderType)
{
    var window = this;
    try
    {
        if (borderType.Equals("AccentBorder"))
        {
            window.BorderThickness = new Thickness(1);
            window.GlowBrush = null;
            window.SetResourceReference(Control.BorderBrushProperty, "AccentColorBrush");
        }

        if (borderType.Equals("NoBorder"))
        {
            window.BorderThickness = new Thickness(0);
            window.BorderBrush = null;
            window.GlowBrush = null;
        }

        if (borderType.Equals("AccentGlowBrush"))
        {
            window.BorderThickness = new Thickness(0);
            window.BorderBrush = null;
            window.SetResourceReference(MetroWindow.GlowBrushProperty, "AccentColorBrush");
        }

        if (borderType.Equals("AccentBorderGlowBrush"))
        {
            window.BorderThickness = new Thickness(1);
            window.SetResourceReference(MetroWindow.GlowBrushProperty, "AccentColorBrush");
            window.SetResourceReference(MetroWindow.BorderBrushProperty, "AccentColorBrush");
        }

        if (borderType.Equals("Shadow"))
        {
            window.BorderThickness = new Thickness(0);
            window.BorderBrush = null;
            window.GlowBrush = Brushes.Black;
        }

        if (string.IsNullOrEmpty(borderType))
        {
            window.BorderThickness = new Thickness(1);
            window.GlowBrush = null;
            window.SetResourceReference(Control.BorderBrushProperty, "AccentColorBrush");
        }
    }
    catch (Exception exception)
    {
        window.BorderThickness = new Thickness(0);
        window.GlowBrush = Brushes.Black;
        window.BorderBrush = null;
    }
}
```

![mahapps_border_change](https://user-images.githubusercontent.com/658431/35740191-50b4d5c2-0834-11e8-8791-03712cb4b785.gif)

Hope this helps!

**Comment by Pekshev** [comment]
Set BorderBrush and GlowBrush in xaml - not help =(
Tested on 1.5 version

**Comment by punker76** [comment]
@Pekshev You must use the latest source or the NuGet package from the nightly build (1.6.0-alpha.345) https://ci.appveyor.com/nuget/mahapps.metr

**Comment by Pekshev** [comment]
@punker76 thanks for the answer. But, unfortunately, I'll have to wait for the official release of version 1.6, since I need to update more than 50 projects. I will refrain while from the alpha version.
Have you decided yet when you will make an official release? At least roughly
