### ISSUE TITLE
Hamburgermenu with sub item 

### ISSUE THREAD

**Issue by Chintangandhi007** [MahApps/MahApps.Metro#2934]
Hamburgermenu with sub item 

HI,

I Used the Hamburger menu and now i need to add sub item like bgpatterns.com. Is it Possible??

If Yes, then how with MahApps and I also need the menu at right side same as bgpatterns.com .

### Environment

- MahApps.Metro 1.5.0 
- Windows OS 7,8,8.1,10
- Visual Studio 2015
- .NET Framework 4.5

**Comment by punker76** [comment]
follow up #3018
