### ISSUE TITLE
Fuzzy button outline

### ISSUE THREAD

**Issue by Pekshev** [MahApps/MahApps.Metro#2937]
After the upgrade from 1.1.2.0 to 1.5.0.23, some of the buttons began to look weird-as if blurred along the contour:
![screenshot_1](https://cloud.githubusercontent.com/assets/12638819/25284270/2cc9020c-26bf-11e7-8818-65399eb295ab.png)
On all buttons same style:
```
<Style x:Key="BtStyle" TargetType="{x:Type Button}" BasedOn="{StaticResource SquareMetroButton}">
    <Setter Property="BorderThickness" Value="1" />
</Style>
```

**Comment by punker76** [comment]
@Pekshev From 1.1.2 to 1.5.0 is a big step. Can you give us a sample app with this? Or show us the complete Xaml of the window? Do you use a special DPI setting? Or other styles? thx

**Comment by Pekshev** [comment]
No problem. Demo project from screen - https://modplus.org/www/tmp/mpMsgTest.zip
i dont use anything else - only mahapps.metr.dll

**Comment by punker76** [comment]
@Pekshev Thx for the sample. I'll look for the style which is a older one.

**Comment by Pekshev** [comment]
I have old versions =)

**Comment by n00bje** [comment]
@punker76 Adding `SnapsToDevicePixels="{TemplateBinding SnapsToDevicePixels}"` to the Border in the SquareMetroButton-style and adding `<Setter Property="SnapsToDevicePixels" Value="True" />` fixes this.
(line 990 in Controls.Buttons.xaml)
