### ISSUE TITLE
The Flyout control can not customize the border.

### ISSUE THREAD

**Issue by a516117636** [MahApps/MahApps.Metro#2939]
I set the BorderThickness and BorderBrush property,but  there is not any change.How can i change the border of flyout?Thank you!

**Comment by punker76** [comment]
@a516117636 You can set the border of a Flyout with v1.5.0

```xaml
<Flyout BorderThickness="1" BorderBrush="{DynamicResource AccentColorBrush}" />
```

**Comment by a516117636** [comment]
That is so cool,THANKS!
