### ISSUE TITLE
DataGridCheckBoxColumn IsReadOnly="False" not clickable

### ISSUE THREAD

**Issue by olegsavelos** [MahApps/MahApps.Metro#2940]
It is impossible to mouse click/check DataGridCheckBoxColumn with the latest code bits.
In my case the datagrid itself is set to isreadonly=true and DataGridCheckBoxColumn isreadonly=false.

Here is the source
`     <DataGridCheckBoxColumn IsReadOnly="False"
                                        Binding="{Binding IsEnabled, UpdateSourceTrigger=PropertyChanged}"
                                        EditingElementStyle="{DynamicResource MetroDataGridCheckBox}"
                                        ElementStyle="{DynamicResource MetroDataGridCheckBox}"
                                        Header="{lex:Loc Key=ENABLE}" />`

Also it is now required to move selection to row in order to be able to check the checkbox.

**Comment by punker76** [comment]
@olegsavelos This was a bug, cause `IsReadOnly` should mean read only. But you can set `IsReadOnly="False"` and  `DataGridHelper.EnableCellEditAssist="True"` for your column to enable this again.

**Comment by olegsavelos** [comment]
That doesn't seem to work.
If IsReadonly=True on DataGrid it's impossible to override it and make DataGridCheckBoxColumn work.
I am using the latest source of MahApps.
