### ISSUE TITLE
GlowBrush is causing an error in Windows XP SP3

### ISSUE THREAD

**Issue by EmadDeveloper** [MahApps/MahApps.Metro#2942]
Once I set the GlowBrush for the window, and run the application. Put the mouse on the edge for 1 second, this will crash the application. After debugging the error was talking about GlowWindow.

[System.EntryPointNotFoundException]	{"Unable to find an entry point named '**GetPhysicalCursorPos**' in DLL 'user32.dll'.":""}	System.EntryPointNotFoundException

the call stack is showing the error in GlowWindow.WndProc(...){ ... }
_Link to the Repo_

### Environment

- MahApps.Metro __ v 1.5.0 __ __dll v1.5.0.23__
- Windows OS __Windows XP SP3__
- Visual Studio __2017__
- .NET Framework __4.0__

**Comment by thoemmi** [comment]
[`GetPhysicalCursorPos`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa969464(v=vs.85).aspx) was introduced with Windows Vista. 
MahApps.Metro doesn't support Windows XP anymore, and so does Microsoft for 3 years already.
