### ISSUE TITLE
Custom dialog sometimes couldn`t hide correctly

### ISSUE THREAD

**Issue by lasikye** [MahApps/MahApps.Metro#2944]
I implamented an custom dialog within viewmodel, but sometimes it called the function 'HideMetroDialogAsync' to close the dialog but useless. Here are the code below.

ViewModel
Class Contructor 
```
private CustomDialog bdPopupDialog;
bdPopupDialog = new CustomDialog(((MetroWindow)App.Current.MainWindow).MetroDialogOptions);
```

Open function
```
bdPopupDialog.Content = new BDPopup() { DataContext = this };
DialogCoordinator.Instance.ShowMetroDialogAsync(this, bdPopupDialog);
```

Close function
```DialogCoordinator.Instance.HideMetroDialogAsync(this, bdPopupDialog);```

Additonal, I registered the dialog in view loaded event like below
```DialogParticipation.SetRegister(this, DataContext);```

Environment: Windows 10 / .Net 4.0 Framework / Mahapps 1.4.1.0

**Comment by punker76** [comment]
@lasikye Do you use teh async/await key words? Can you try this with v1.5.0.x? If you still need help, then please create a short sample for this issue. Thx.
