### ISSUE TITLE
Flyout overlay WindowButtonCommands

### ISSUE THREAD

**Issue by tm69** [MahApps/MahApps.Metro#2946]
When update from 1.4.3 to 1.5.0 the flyout is over the commands

1.4.3 
![noerror](https://cloud.githubusercontent.com/assets/28063419/25450986/86c7e9bc-2a75-11e7-954f-d2dbf0c1b56a.PNG)

1.5.0
![error](https://cloud.githubusercontent.com/assets/28063419/25451004/963c728c-2a75-11e7-9475-0d1514ee4b53.PNG)

- MahApps.Metro __v1.5.0.23
- Windows OS 10
- Visual Studio 2013
- .NET Framework 4.5

**Comment by punker76** [comment]
@tm69 what type of Flyout is this? Top or Right? Do you use some of the overlay behaviors?

**Comment by tm69** [comment]
The Flyout is Left, and yes i have IconOverlayBehavior="Always" in the window, but I just discover that happens when the Flyout is modal IsModal="True" if i set false the commands are visible again

**Comment by punker76** [comment]
@tm69 ah, yes this was a fix. IsModal = means really modal... -> #2841

**Comment by tm69** [comment]
@punker76 Thak you for you time :D
