### ISSUE TITLE
TextBox Attribute Trim=true or TextBoxHelper.Trim=true 

### ISSUE THREAD

**Issue by robertorp** [MahApps/MahApps.Metro#2947]
## What steps will reproduce this issue?

_TextBox has the Trim = true attribute, the Trim = true attribute would implement the Changed event by doing a TrimStart () and would implement LostFocus that would do the Trim_
or helper TextoBoxHelper.Trim=true

### Expected outcome

_The text would have no spaces at the beginning or end_

Code example
[trimtextbox.txt](https://github.com/MahApps/MahApps.Metro/files/965190/trimtextbox.txt)

**Comment by amkuchta** [comment]
@punker76 @robertorp I like the idea, perhaps something along the lines of `TextBoxHelper.Trimming` with options for `TrimBeginning`, `TrimEnd`, or `None`?  I know that @thoemmi has concerns with the `TextBox` style becoming too bloated - any thoughts?

**Comment by punker76** [comment]
I think IMO this should not be added to MahApps. I know MahApps has a lot of other attached properties, but this functionality has nothing to do with the styling itself...
/cc @thoemmi

**Comment by thoemmi** [comment]
@amkuchta caught me 😉 I agree with @punker76, it's out of MahApps.Metro's scope.

(BTW, I would make it a behaviour, not an attached dependency property)
