### ISSUE TITLE
Main window does not display with .NET 4.7 / Windows 10 Creators Update

### ISSUE THREAD

**Issue by sleman** [MahApps/MahApps.Metro#2950]
MahApp Main Window does not display at all with latest Windows 10 Creators Update: 460798 (.NET Framework 4.7). Tried searching online to see if anyone had this issue with WPF/.NET Framework but with no luck.

This seems to be a pretty major issue. Anyone know anything about it?

- MahApps.Metro 1.4
- Windows OS 10 Creators Update
- Visual Studio 2015
- .NET Framework 4.7

**Comment by punker76** [comment]
@sleman Can you say what's going wrong? I can't reproduce it with these settings

- MahApps.Metro 1.5.0 (latest version)
- Windows 10 Creators Update 1703 15063.250
- VS 2017
- .NET Target Framework 4.7

**Comment by sleman** [comment]
Application window does not appear at all but clicking around proves that window exists. I turned off hardware acceleration and window appeared. I think issue might be related to 4.7 framework or display driver for Intel Graphics card.
