### ISSUE TITLE
Window with showactivated=false and sizetocontent=WidthAndHeight is activated in Mahapps.Metro v1.5

### ISSUE THREAD

**Issue by gerthermans** [MahApps/MahApps.Metro#2951]
[HoverIssuemahapps.zip](https://github.com/MahApps/MahApps.Metro/files/970848/HoverIssuemahapps.zip)
### Issue
When SizeToContent is set on a wpf window it ignores the ShowActivated=false setting

### Steps to reproduce
Unzip the HoverIssuemahapps zip file
Open and run the solution
Move the mouse over the 'hover here' area
expected result:
Window1 stays active window as CheckWindow has ShowActivated=False
Actual result:
CheckWindow becomes activated

This was working in Mahapps.Metro version 1.4.2

Is there a workaround for this? (window still needs to size to it's content.

### Environment

- MahApps.Metro __v1.5
- Windows 10
- Visual Studio __2015__
- .NET Framework __4.5.2__

**Comment by punker76** [comment]
@gerthermans Is fixed now and will be available in 1.6.0
