### ISSUE TITLE
Can't run MahApps 1.5.0 Caliburn Demos on VS2015 

### ISSUE THREAD

**Issue by oschwab** [MahApps/MahApps.Metro#2953]
Hello,

I can't run Caliburn demo projects (4.0 and 4.5) from my VS2015 workstation.
Both fails on AppBootstrapper GetInstance method , finding no contract for **settings**

![image](https://cloud.githubusercontent.com/assets/2461647/25655128/1693c57e-2ff4-11e7-8841-bccd01bf7631.png)

### Environment

- MahApps.Metro 1.5.0
- Windows 10
- Visual Studio 2015
- .NET Framework 4.0 && 4.5

**Comment by punker76** [comment]
@oschwab Saw this too after 1.5.0 release, but I'm not a good Caliburn user

**Comment by oschwab** [comment]
@punker76 I had an issue on my own project with flyouts after mahapps update ; as I used Caliburn sample as a basis, I tried to see how it was done in it, and **boom** !

**Comment by Eternal21** [comment]
Looks like caliburn can't locate viewmodels for the flyout views.  I got the project to run by commenting out all fly-outs inside OnInitialize() function.  Kind of defeats the purpose, since fly-outs are all there is to the demo.  I will look into actually fixing the problem when I get some spare time.

![image](https://cloud.githubusercontent.com/assets/9355996/25722342/e3b4fb48-30e1-11e7-9012-23d5cf5c3bcc.png)

**Comment by oschwab** [comment]
I think it might be linked to this change :

_Change Flyout from ContentControl to HeaderedContentControl which has the correct properties for headers._

**Comment by Eternal21** [comment]
There's a related stackoverflow question, with no answers so far: http://stackoverflow.com/questions/43735278/wpf-mahapps-metro-caliburn-micro-flyout-headeredcontentcontrol

**Comment by oschwab** [comment]
@Eternal21 We're both exactly at the same point ...

**Comment by oschwab** [comment]
@Eternal21  @punker76 Commenting the Binding to Header in ShellView.xaml makes the demo work again
![image](https://cloud.githubusercontent.com/assets/2461647/25748297/e263dca4-31aa-11e7-8181-4bd82cdb6608.png)

**Comment by Eternal21** [comment]
Yes it does.  The only problem now is, it displays the path to viewmodel now instead of the header title.

**Comment by seb30** [comment]
> There's a related stackoverflow question, with no answers so far

Hey guys, it's me.

**Comment by seb30** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/28293949/25790643/c18e1b2c-33ba-11e7-803d-7d447c5af6a7.png)

This works, but only if 1 Flyout is opened. If you're going to open another one, only the Header of the old one will be visible.

**Comment by punker76** [comment]
It seems it is a generally problem of Caliburn and HeaderedContentControl and/or the sample must be rewritten to work correctly.

**Comment by jamithiran** [comment]
@seb30 , your suggestion (setting the content) finally brought the agony of many hours to and end but as you mentioned the second one has problems. It shows only the header. 

The one that shows the content is usually the first flyout added in viewmodel. I'm referring to my development project in VS2017. Did you have any success in resolving this situation? I chose to use CM only because I could not open/close flyout from viewmodel. 

Thanks

**Comment by seb30** [comment]
Not really. In the end I'm showing only one Flyout and the other stuff in a dialog.

**Comment by jamithiran** [comment]
@seb30  Thank you for the reply. I have dropped the idea of using CM and going the normal way. Just to clarify to others on previous message, only the last added flyout shows the content and previous flyouts (1 or more)  ones the header. 
Cheers

**Comment by nigel-sampson** [comment]
I've dropped a work around in Caliburn-Micro/Caliburn.Micro#451 for the sample along with an explanation of what's happening.

Short story is that it appears that the `ItemTemplate` on the `FlyoutsControl` ends up as the `HeaderTemplate` of the `Flyout`. My gut says this part isn't related to Caliburn.Micro, but I need to spike a sample to test that out.

**Comment by jamithiran** [comment]
@nigel-sampson  Thanks Nigel. Your workout seems to fix it. Cheers

**Comment by nigel-sampson** [comment]
So I was able to recreate the problem outside of Caliburn.Micro with the following.

``` xml
<ma:MetroWindow.Resources>
    <Style x:Key="CustomFlyoutStyle"
       BasedOn="{StaticResource {x:Type ma:Flyout}}"
       TargetType="{x:Type ma:Flyout}">
        <Setter Property="Header" Value="{Binding Title}" />
    </Style>
</ma:MetroWindow.Resources>

<ma:MetroWindow.Flyouts>
    <ma:FlyoutsControl x:Name="MyFlyouts" ItemContainerStyle="{StaticResource CustomFlyoutStyle}">
        <ma:FlyoutsControl.ItemTemplate>
            <DataTemplate>
                <StackPanel Orientation="Horizontal">
                    <TextBlock Text="Item Template" />
                    <TextBlock Text="{Binding}" />
                </StackPanel>
            </DataTemplate>
        </ma:FlyoutsControl.ItemTemplate>
    </ma:FlyoutsControl>
</ma:MetroWindow.Flyouts>

<StackPanel>
    <Button x:Name="OpenFlyout" Content="Open" />
</StackPanel>
```

``` csharp
public class FlyoutViewModel
{
	public FlyoutViewModel(string title, string content)
	{
		Title = title;
		Content = content;
	}

	public string Title { get; }
	public string Content { get; }
}

public partial class MainWindow
{
	public MainWindow()
	{
		InitializeComponent();

		Loaded += (s, e) =>
		{
			MyFlyouts.ItemsSource = Enumerable.Range(0, 10).Select(i => new FlyoutViewModel($"Title {i}", "Content for the flyout"));
		};

		OpenFlyout.Click += (s, e) =>
		{
			//var viewModel = MyFlyouts.Items[0] as FlyoutViewModel;
			var flyout = MyFlyouts.ItemContainerGenerator.ContainerFromIndex(0) as Flyout;

			if (flyout == null)
				return;

			flyout.IsOpen = !flyout.IsOpen;
		};
	}
}
```
Which results in the following:
![flyout](https://user-images.githubusercontent.com/1256017/27206006-7aac7a9a-5288-11e7-87b2-6be2b498fe38.png)

As you an see the `ItemTemplate` of the `FlyoutsControl` is being applied to the `HeaderTemplate` of the child `Flyout`s. Can't see anything immediately obvious in the code about why this is though.

**Comment by Eternal21** [comment]
I don't know if it's related, but from what I remember the problems began when the Flyout base class was changed from ContentControl to HeaderedContentControl a while back: https://github.com/MahApps/MahApps.Metro/commit/2874108dd9df3cc5f3198f09d1681a135554200b
