### ISSUE TITLE
[Enhancement] MarkdownTextBlock

### ISSUE THREAD

**Issue by amkuchta** [MahApps/MahApps.Metro#2955]
In one o the recent releases to the UWP Toolkit, a `MarkdownTextBlock` control was introduced, and it looks pretty awesome.  Would anyone else find this useful (thought - it could be used in the MetroDemo rework to display a user guide)

**Comment by avechuche** [comment]
+1. Great idea

**Comment by punker76** [comment]
@amkuchta @avechuche  This is a huge control and can not add line by line from UWPCommunityToolkit. There is a lot of code which is only available now in UWP.

**Comment by amkuchta** [comment]
@punker76 I figured it would be a lot - I took a second to look at the code, and it is definitely intimidating.

If you want to say no to this, I completely understand.  I'd offer to take a shot at implementing, but I don't have the time right now to commit to it.

**Comment by amkuchta** [comment]
@punker76 you can also "on hold" this, if you want - maybe I can pick it up another time.

**Comment by thoemmi** [comment]
There's a nice markdown control available, [Markdig.wpf](https://github.com/Kryptos-FR/markdig.wpf).

I created a demo app using the MahApps's Quick Start guide and added following lines to `MainWindow.xaml`:
```xml
<Grid>
    <Grid.ColumnDefinitions>
        <ColumnDefinition Width="*" />
        <ColumnDefinition Width="*" />
    </Grid.ColumnDefinitions>
    <TextBox
        x:Name="source"
        Grid.Column="0"
        Margin="5"
        AcceptsReturn="True"
        FontFamily="Consolas" />
    <wpf:MarkdownViewer
        Grid.Column="1"
        Margin="5"
        Markdown="{Binding ElementName=source, Path=Text, UpdateSourceTrigger=PropertyChanged, Mode=OneWay}" />
</Grid>
```
Here's the result:
![demo](https://user-images.githubusercontent.com/73690/31320235-685a29da-ac71-11e7-8b11-d2af7c194903.gif)

**Comment by thoemmi** [comment]
Thanks, but the credits go to [Nicolas Musset](https://github.com/Kryptos-FR), the author of [Markdig.wpf](https://github.com/Kryptos-FR/markdig.wpf). 😉
