### ISSUE TITLE
How can I display the Metro MessageBox in a class

### ISSUE THREAD

**Issue by a516117636** [MahApps/MahApps.Metro#2957]
How can I display the Metro MessageBox in a class?For example,I can use 
`MessageBox.Show("", "");`
in a class(NOT in Window or UserControl),but can not use 
`ShowMessageAsync("","")`,
Is there a way to implement that?THANKS!!

**Comment by BornToBeRoot** [comment]
There is a support for viewmodels...

Window/UserControl.xaml
```
xmlns:Dialog="clr-namespace:MahApps.Metro.Controls.Dialogs;assembly=MahApps.Metro"
Dialog:DialogParticipation.Register="{Binding}"
```

Window/UserControl.xaml.cs

```cs
using MahApps.Metro.Controls.Dialogs;

// Your viewmodel
VIEWMODELNAME vm = new VIEWMODELNAME(DialogCoordinator.Instance);

public USERCONTROLNAME()
{
  DialogCoordinator.Instance;
  DataContext = vm;
}
```


And in your ViewModel add this:

```cs
using MahApps.Metro.Controls.Dialogs;

// Variable
private IDialogCoordinator dialogCoordinator;

// Constructor
public VIEWMODELNAME (IDialogCoordinator instance)
{
  dialogCoordinator = instance;
}

private foo()
{
  await dialogCoordinator.ShowMessageAsync(this, "HEADER","MESSAGE");
}

```

**Comment by punker76** [comment]
@BornToBeRoot Thx. Do you want to add this to the doc site? https://github.com/MahApps/mahapps.github.com/blob/master/controls/dialogs.md
