### ISSUE TITLE
NumericUpDown: If HasDecimals is set to false and StringFormat was bound, HasDecimals will be set to true after unloading and loading the control

### ISSUE THREAD

**Issue by davericardo** [MahApps/MahApps.Metro#2958]
Prerequisites: Place the NumericUpDown control in an panel that uses virtualization and make it scrollable so that the NumericUpDown will be unloaded if it is not visible. Bind the Property StringFormat (e.g. '{0} s') with the corresponding ViewModel and set HasDecimals to false.

If the control is unloaded the StringFormat will be reset to an empty string. This causes that RegEx.IsMatch will return true. Now HasDecimals is also set to true.

**Comment by punker76** [comment]
@davericardo In which version?

**Comment by davericardo** [comment]
Sorry, in version 1.5.0.23.
