### ISSUE TITLE
IS THERE ANYWAY TO CHANGE ONLY LOOK AND FEEL OF A CONTROL BUT STILL KEEP ANIMATION, TRIGGER OF IT ?

### ISSUE THREAD

**Issue by HuaTrung** [MahApps/MahApps.Metro#2960]
Hi everyone, i'm a beginner. I have learnt WPF and used mahapps some time ago.So i have a issue "CHANGE ONLY LOOK AND FEEL OF A CONTROL BUT STILL KEEP ANIMATION, TRIGGER OF IT ". To more clearly, i want to override controltemplate but don't want override controltemplate.trigger. 
Is there a way to implement that? Many thanks.

**Comment by JobaDiniz** [comment]
why yelling like that? *chill out* man

**Comment by HuaTrung** [comment]
Just a question guy, writing it in upper case is my favorite. Sorry if it makes you frustrated.

**Comment by Eternal21** [comment]
˙sʎnƃ ʎsɐǝ ʇᴉ ǝʞɐ┴

**Comment by C1rdec** [comment]
First this is not an issue an should be closed.
If you have any question regarding the Mahapps framework you should use the [Gitter](https://gitter.im/MahApps/MahApps.Metro)

Here is a [video ](https://www.youtube.com/watch?v=lY0RSBipZhw) of how to accomplish style inheritance in WPF.
