### ISSUE TITLE
[Enhancement] WindowsCommandButtons separate styles

### ISSUE THREAD

**Issue by avechuche** [MahApps/MahApps.Metro#2961]
Hi, is it possible to separate styles (windows 10) from minimize, maximize and close buttons? To be able to use it when UseNoneWindowStyle = "True".

**Comment by punker76** [comment]
@avechuche No, cause if UseNoneWindowStyle is set to true the title bar will be collapsed and also if you use the WindowButtonCommands directly the UseNoneWindowStyle wins for all 3 buttons and collapse it. The only way is to add your own Button(s) or restyle the WindowButtonCommands.

**Comment by avechuche** [comment]
@punker76 I think I explained wrong. What I want is that it is possible to make a style (Style={StaticResource Win10WindowCloseButton}, for example) for a button, so that it has the design of the button to close a window in Windows 10. Thx!

**Comment by punker76** [comment]
@avechuche You have 2 options

1) at the `MetroWindow` level

```
<Controls:MetroWindow.WindowButtonCommands>
        <Controls:WindowButtonCommands Template="{DynamicResource MahApps.Metro.Templates.WindowButtonCommands.Win10}" />
</Controls:MetroWindow.WindowButtonCommands>
```

2) or for all windows at the `App.xaml`

```
<!-- Win 10 style for window buttons -->
<Style TargetType="{x:Type controls:WindowButtonCommands}" BasedOn="{StaticResource MahApps.Metro.Styles.WindowButtonCommands.Win10}" />
```
