### ISSUE TITLE
WindowCommands with ItemTemplateSelector not working

### ISSUE THREAD

**Issue by JerryJian** [MahApps/MahApps.Metro#2963]
## What steps will reproduce this issue?

1. Create a window.
2. Assign DataTemplateSelector to LeftWindowCommands.ItemTemplateSelecotr
3. The SelectTemplate method is not called

### Environment

- MahApps.Metro __v1.5.0.23__
- Windows OS __Win10 x64__
- Visual Studio __2017__
- .NET Framework __4.0__

**Comment by AmirMahdiNassiri** [comment]
Unfortunately, I can report that this issue still exists on the latest stable version. The commit 3182a1e utilizes `ContentTemplateSelector` but the `WindowCommands` control does not expose such a property. Instead, the `WindowCommands` inherits from `ItemsControl` which exposes the `ItemTemplateSelector` property. Sadly the `ItemTemplateSelector` is not used in the control's template.

**Environment**
- MahApps.Metro v2.4.5
- Windows 10 x64 v19042
- Visual Studio 2019
- Net Core 3.1 WPF

**Comment by timunie** [comment]
@AmirMahdiNassiri if I were you I would open a new issue instead answering closed issues...
