### ISSUE TITLE
[Only visual] PasswordBox bug

### ISSUE THREAD

**Issue by avechuche** [MahApps/MahApps.Metro#2966]
1) It is nothing serious at all, but if it is not difficult it could be fixed. When you reveal a password, the cursor does not match.

2) This may be more "serious". If you type while you press the "Reveal password" button, SelectAllOnFocus (or double clic), it does not work correctly

![1](https://cloud.githubusercontent.com/assets/11781418/26013829/689bd65c-3730-11e7-8a70-154fdbb41ddc.png)

### Environment

- MahApps.Metro __v1.5.0__
- Windows OS __8.1__
- Visual Studio __2015__
- .NET Framework __4.5__

**Comment by anandkishore987** [comment]
I'm also facing the same problem. When you revel a password the cursor blink in middle.
Environment 
*Win 10
*MahApps.Metro v1.5.0
* visual studio 2015
*.Net framework 4.5

**Comment by MurariAlex** [comment]
@punker76 The selection is still broken. After you reveal and edit the password just like you did in the gif in the PR, if you try to select all text, with ctrl+a or double clicking the box, only part of the text can be selected. Using latest version from appveyor nuget feed (PR 3082).

**Comment by punker76** [comment]
@MurariAlex I'll look for this next days

**Comment by punker76** [comment]
@MurariAlex Should be fixed now

**Comment by MurariAlex** [comment]
@punker76 It´s fixed. Ty.
