### ISSUE TITLE
How to open in the frame UserControlMy.xaml type Controls: MetroWindow?

### ISSUE THREAD

**Issue by codenameUsernameisalreadytaken** [MahApps/MahApps.Metro#2970]
How to open in the frame UserControlMy.xaml type Controls: MetroWindow?

UserControlMy : MetroWindow

var fra = new Frame();
fra.Source = new Uri("UserControlMy.xaml", UriKind.RelativeOrAbsolute);

The program hangs when you insert into the frame xaml

**Comment by punker76** [comment]
@codenameUsernameisalreadytaken I think you need this method

```
fra.Navigate(new Uri("UserControlMy.xaml", UriKind.RelativeOrAbsolute));
```

but it's not MahApps related issue.
