### ISSUE TITLE
MetroProgressBar // Value == Maximum // Resize window

### ISSUE THREAD

**Issue by seb30** [MahApps/MahApps.Metro#2974]
When resizing a window with a MetroProgressBar (MPB), where the `Value != Maximum`, then the behavior is fine. But if `Value == Maximum`, the desired size is wrong.

Expected behavior on resizing the window:
![metroprogressbar_issue_a](https://cloud.githubusercontent.com/assets/28293949/26350557/f316416a-3fb3-11e7-9f60-f37d38a64798.png)

Unexpected behavior on resizing the window:
![metroprogressbar_issue_b](https://cloud.githubusercontent.com/assets/28293949/26350564/f7cfe1e8-3fb3-11e7-90f1-e2fbfe7f0625.png)

Here from my Project (without resizing, just setting the Value with snoop):
![metroprogressbar_issue_1](https://cloud.githubusercontent.com/assets/28293949/26350610/1a690c3e-3fb4-11e7-9813-b9684620af98.png)

![metroprogressbar_issue_2](https://cloud.githubusercontent.com/assets/28293949/26350613/1d586a48-3fb4-11e7-88f0-b420f1ddeac7.png)

- MahApps.Metro v1.5.0
- Windows OS 10
- Visual Studio 2017
- .NET Framework 4.5

**Comment by punker76** [comment]
@seb30 Can you give me the complete Xaml code of this scenario?

**Comment by seb30** [comment]
XAML pasting isn't working.

![image](https://cloud.githubusercontent.com/assets/28293949/26354342/7fc1c3fe-3fc4-11e7-9aa1-e69a3087f4d5.png)

**Comment by seb30** [comment]
And Code behind is just 

`
private void Button_Click(object sender, RoutedEventArgs e)
{
	if (_metroProgressBar.Value == _metroProgressBar.Maximum)
	{
		_metroProgressBar.Value = 50;
	}
	else
	{
		_metroProgressBar.Value = _metroProgressBar.Maximum;
	}
}
`

**Comment by seb30** [comment]
It is no Mahapps problem. I was able to reproduce with normal WPF. This thread can be closed.
