### ISSUE TITLE
Badge must have a different look when disabled

### ISSUE THREAD

**Issue by xxMUROxx** [MahApps/MahApps.Metro#2977]
## What steps will reproduce this issue?

The Badge has no diffent appearance if the object itself or any parent visual element are disabled:

### Expected outcome

Badge should look different if disabled

|current|proposed|
|---|---|
|![badge-currentbehavior](https://cloud.githubusercontent.com/assets/4341039/26441569/4bc58d06-4131-11e7-8bcb-dc8655660588.PNG)|![badge-newbehavior](https://cloud.githubusercontent.com/assets/4341039/26441570/4bd1896c-4131-11e7-9e77-1e89db6c17cb.PNG)|

### Implementation

https://github.com/xxMUROxx/MahApps.Metro/tree/feature/Badge-Disabled-Style

If desired I will create a PR with the above linked branch.

**Comment by thoemmi** [comment]
Can a badge be disabled? It's not interactive anyway. The number shown on the badge is still relevant.

Anyway, **if** a different appearance is desired, I wouldn't change the opacity but the color. The button shining through the badge in your proposal looks strange. I would prefer a solid badge background, something gray-ish maybe.

**Comment by amkuchta** [comment]
I'm with @thoemmi (I'm glad I wasn't the only one who took issue with the button showing through).  I think a grey would be awesome, but it would have to be a different grey than the control that the badge adorns

**Comment by xxMUROxx** [comment]
@thoemmi since a badge has no command, yes it is not interactive. But it looks strange if the parent control is disabled and the badge has the bright color (accented if default).
I like your and @amkuchta's idea.

**Comment by xxMUROxx** [comment]
@punker76 what do you think?

**Comment by punker76** [comment]
@xxMUROxx I've added your changes from your branch. thx! 👍  I only renamed the brush to `MahApps.Metro.Brushes.Badged.DisabledBackgroundBrush`
