### ISSUE TITLE
can't change window title

### ISSUE THREAD

**Issue by FinlayDaG33k** [MahApps/MahApps.Metro#2978]
Hii there,

Today, I started to create a little application.
However, when I want to update the title from my window, it won't let me.

I have this code as mentioned in [this issue](https://github.com/MahApps/MahApps.Metro/issues/138):
```
public static readonly DependencyProperty WindowTitleProperty = DependencyProperty.Register("WindowTitle", typeof(string), typeof(MetroWindow), new PropertyMetadata(string.Empty));
        public string WindowTitle {
            get { return TitleCaps ? (GetValue(WindowTitleProperty) as string).ToUpper() : (GetValue(WindowTitleProperty) as string); }
            set { SetValue(WindowTitleProperty, value); }
        }
public MainWindow() {
            InitializeComponent();
            this.WindowTitle = "This Is My Title";
}
```

It doesn't throw an error, but it just doesn't change the title.

Any suggestions?

Cheers

**Comment by thoemmi** [comment]
Can't you use the existing `DependencyProperty` `Title`?

**Comment by FinlayDaG33k** [comment]
if you mean using `this.title = "This Is My Title";` then no, the title doesn't seem to change.

**Comment by thoemmi** [comment]
Can you provide a small repro?

**Comment by thoemmi** [comment]
> EDIT: seems that after rebuilding the project, it worked :)
