### ISSUE TITLE
[Request]Win 10 Fluent Design Hamburger Menu

### ISSUE THREAD

**Issue by Lerosbeef** [MahApps/MahApps.Metro#2979]
Hi, similar to #2931 I'm trying to copy Microsoft Fluent Design/Project Neon transparent behind blur on the HamburgerMenu; tried with VisualBrush on PaneBackground, no success so far. Please help, MahApps.Metro is great, example : [ProjectNeon](https://twitter.com/MichaelGillett/status/861123430321721345)

![c_vh2imxsaeevic](https://cloud.githubusercontent.com/assets/28889975/26526917/4f0eb91a-4389-11e7-9065-d1d0236a20e4.jpg)

### Environment

- MahApps.Metro __v1.5.0__
- Windows OS __7__
- Visual Studio __2017__
- .NET Framework __4.0__

**Comment by amkuchta** [comment]
@punker76 @thoemmi to my knowledge, "Acrylic" is UWP only - is that right?

**Comment by Lerosbeef** [comment]
Thanks @amkuchta, I'd be happy with just a radial blur; it's for a client, so exit Windows Vista DwmEnableBlurBehindWindow and Windows 10 SetWindowCompositionAttribute.
That's why I gave a Windows 10 Mobile example, it just blurs the application behind, not the desktop.

**Comment by Lerosbeef** [comment]
Liking the materiel design ripple effet, we managed a more fluent design by bluring the entire panel.
