### ISSUE TITLE
TimePicker 24hour format selection

### ISSUE THREAD

**Issue by honzasram** [MahApps/MahApps.Metro#2985]
Hi. I'd like to set 24 hour format selection in TimePicker. So far I have to set if this is AM or PM, which is not pretty common in Czech format.

Environment

MahApps.Metro v1.5.0.23
Windows OS 10/7
Visual Studio 2015
.NET Framework 4.5.2

**Comment by punker76** [comment]
@honzasram The AM/PM comes from the Cultures properties `DateTimeFormat.AMDesignator` and `DateTimeFormat.PMDesignator`.

**Comment by honzasram** [comment]
@punker76  Thank you for reply. However, I'm not pretty sure if I understand. What exactly should i add to code?

Even if I set up Culture to "cs-CZ" which uses 24 hour format by default, I Get this 
![bez nazvu](https://user-images.githubusercontent.com/9151345/27129436-8bc06148-5102-11e7-9803-7f34def03ae4.png)

I want to get rid of AM/PM selector (in this case dop./odp.) and get all 24 hour to hour combobox. 

Code:
` <controls:TimePicker Margin="2" 
                                                     IsClockVisible="False" Culture="cs-CZ" 
                                                     PickerVisibility="HourMinute" 
                                                     SelectedTime="{Binding ActionSelectedTime, 
                                                                        ValidatesOnDataErrors=True, 
                                                                        UpdateSourceTrigger=PropertyChanged, 
                                                                        NotifyOnValidationError=True}"/>`

**Comment by punker76** [comment]
@honzasram Ok, you're right. I found the problem and will fix it in 1.6.0 (and alpha).

**Comment by punker76** [comment]
@honzasram You can test the latest alpha version.
