### ISSUE TITLE
Closing Progress or Login Dialogs doesn't restore focus on Window/Flyout

### ISSUE THREAD

**Issue by MurariAlex** [MahApps/MahApps.Metro#2986]
## What steps will reproduce this issue?

**For Flyouts and Progress Dialogs:**

1. Create a flyout and add an `InputBinding `to the `Escape` key that closes the flyout when pressed.
2. Show a progress dialog in the flyout (using the Flyout as the context for the Dialog) and close the progress dialog.
3. If you press the escape key, nothing happens, if you click on some element in the flyout, the focus is restored and pressing the Escape key again closes the flyout as it should happen.

**For MetroWindow and Login Dialogs:**

1. Create a `MetroWindow`.
2. Show a login dialog and close it, the focus will be restored normally.
3. Show a login dialog again and close it, this time the focus won't be restored.

### Expected outcome

The focus should be restored automatically to the view when the dialog is closed.

### Environment

- MahApps.Metro __v1.6.0 Alpha__
- Windows OS __10__
- Visual Studio __2015__
- .NET Framework __4.6.2__

**Comment by punker76** [comment]
@MurariAlex Can you create a short sample (on Github)? Thx.

I can't reproduce this one

>For MetroWindow and Login Dialogs:
>
>Create a MetroWindow.
>Show a login dialog and close it, the focus will be restored normally.
>Show a login dialog again and close it, this time the focus won't be restored.
