### ISSUE TITLE
Licence issues

### ISSUE THREAD

**Issue by Brogie** [MahApps/MahApps.Metro#2987]
## What steps will reproduce this issue?

There are two licences in the root of the repo one is the MIT licence (LICENCE) and one is the Ms-PL licence (LICENCE+) both added at the same time in a commit named test 2 (commit dbb70247c5071141c4fee491c3dc3ae44a42d274), which one pertains to MahApps.Metro? I'm going to reference MahApps as MIT for now as that is what is shown on the header for the project but having Licence and Licence+ makes correctly attributing your work confusing. 

### Expected outcome

Easier attribution by clearing up licence confusion  

### Repo

All repos

### Environment

n/a

**Comment by xxMUROxx** [comment]
@Brogie There are some files licenced under Ms-PL. See https://github.com/MahApps/MahApps.Metro/blob/develop/LICENSE%2B#L5-L7
 The whole project is licenced under MIT

**Comment by punker76** [comment]
@Brogie As @xxMUROxx  says, MahApps itself is licensed under MIT and uses code which is licensed under Ms-PL and compatible with the terms of MIT.
