### ISSUE TITLE
Badge drawing issue when resized

### ISSUE THREAD

**Issue by TheProxyRE** [MahApps/MahApps.Metro#2988]
## What steps will reproduce this issue?

_When grid size is less than minimal size than badges fails to draw propperly_

### Expected outcome

Here is normaly how it look
![image](https://user-images.githubusercontent.com/12687236/27241202-18c315e6-52d8-11e7-9f78-aa7132345d3e.png)

And this is how it looks when resized
![image](https://user-images.githubusercontent.com/12687236/27241210-23522254-52d8-11e7-8515-ad25edc518e7.png)

### Environment

- MahApps.Metro __v1.5.0__
- Windows OS __7__
- Visual Studio __2015__
- .NET Framework __4.6__

**Comment by punker76** [comment]
Duplicate of #2994
