### ISSUE TITLE
TextBox memory leak

### ISSUE THREAD

**Issue by TwoBee** [MahApps/MahApps.Metro#2990]
```xaml
<TextBox Controls:TextBoxHelper.IsWaitingForData="true"/>
```
window minimize

### Environment

- MahApps.Metro __v1.4.3__
- Windows OS __8.1__
- Visual Studio __2013__
- .NET Framework __4.5__

**Comment by punker76** [comment]
@TwoBee Can you give us more information about this? Why should this a memory leak?

**Comment by TwoBee** [comment]
@punker76 I am sorry! I can't compile source code for debugging. I am using is releases version that does not provide more information.

**Comment by punker76** [comment]
@TwoBee So, how can I help you? Where do you think is this memory leak? Have you tried the latest stabel version 1.5.0 (or pre-release of 1.6.0) instead the 1.4.3?

**Comment by wiki1980** [comment]
I am seeing this issue, as well. 

I have textbox using TextBoxHelper.IsWaitingForData="true". If the app is minimized, the memory footprint will increase every second until either the app is restored or the system hangs.

**Comment by punker76** [comment]
@wiki1980 thx for your report, now I see it too...
