### ISSUE TITLE
Auto complete text box

### ISSUE THREAD

**Issue by BlythMeister** [MahApps/MahApps.Metro#2993]
I would really like to include an auto complete text box in my app similar to how https://wpfautocomplete.codeplex.com works.
But I'm not sure how to get that example of auto complete to have all the mahapps styling.

Essentially, a text box which can provide suggestions based on entered data is what I am after 🙂

**Comment by fredericoregateiro** [comment]
+1

**Comment by punker76** [comment]
Duplicate of #2625
