### ISSUE TITLE
Empty Watermark leaves blank border on date time controls

### ISSUE THREAD

**Issue by makingbloke** [MahApps/MahApps.Metro#3000]
With the DatePicker / TimePicker / DateTimePicker (and no custom styles applied) if I set the watermark to "" using TextBoxHelper.Watermark then I get a blank square on the control (as shown below). However, if I set the watermark to "{x:Null}" then the box does not get displayed
![screenshot1](https://user-images.githubusercontent.com/6209853/27808370-580b6b3a-603f-11e7-90ba-0b42f6ae4d7b.png)
. 

If there is no watermark then surely the control should be blank?

**Comment by punker76** [comment]
@makingbloke should be fixed now. you can test it with the latest pre-release.

**Comment by makingbloke** [comment]
Downloaded the pre-release last night and compiled it. "" still gives the default watermark and null clears it. (This is using the .Net 4.5 Demo).
