### ISSUE TITLE
DatePicker padding do not work

### ISSUE THREAD

**Issue by JerryJian** [MahApps/MahApps.Metro#3001]
## What steps will reproduce this issue?

`<DatePicker Padding="10"/>` not working, but wpf default style works.

### Expected outcome

Expect the same logic as the WPF default style

### Environment

- MahApps.Metro __v1.5.0.23__
- Windows OS __Win7 64Bit SP1__
- Visual Studio __2015__
- .NET Framework __4.0__

**Comment by punker76** [comment]
@JerryJian should be fixed now. you can test it with the latest pre-release.

**Comment by JerryJian** [comment]
@punker76 Thanks
