### ISSUE TITLE
Can't compile all demos on VS2017

### ISSUE THREAD

**Issue by stulzq** [MahApps/MahApps.Metro#3004]
### Environment

- MahApps.Metro __v1.6.0__
- Windows OS __10__
- Visual Studio __2017__
- .NET Framework __4.5&4.0__

Today,I download MahApps.Metro-develop source code.I can compile MahApps.Metro,but I cant't compile MahApps.Metro'demo（MahApps.Metro.Caliburn.Demo & MahApps.Metro.Demo）
![image](https://user-images.githubusercontent.com/13200155/27847593-1164e368-6171-11e7-94cc-4116806532ad.png)

Error prompt

How to solve the problem?

**Comment by ye4241** [comment]
you need restore/reinstall all packages with paket.

**Comment by jtattreo** [comment]
I also cannot build the solution. I followed the build instructions and ran .paket\paket restore, but it did not solve the problem. I just need the demo. Is there anywhere to get the demo from in binary format?

**Comment by punker76** [comment]
@jtattreo A compiled demo is available at the release page https://github.com/MahApps/MahApps.Metro/releases

**Comment by punker76** [comment]
@stulzq Please try again with the latest source. I will close this for now. Feel free to re-open if this still an issue for you.
