### ISSUE TITLE
SplitView Inline Animation

### ISSUE THREAD

**Issue by amkuchta** [MahApps/MahApps.Metro#3005]
## What steps will reproduce this issue?

_Utilizing the `SplitView` control with an `Inline` or `CompactInline` pane does not animate in the same manner as `Overlay` or `CompactOverlay`_

### Expected outcome

_The Pane for the `SplitView` control should always slide out to the right or left_

### Repo

_Evident in MetroDemo_

### Environment

- MahApps.Metro __v1.6.0_alpha007__
- Windows OS __7/10__
- Visual Studio __2015/17__
- .NET Framework __4.5.2__

**Comment by punker76** [comment]
@amkuchta I will leave it as it is, cause the UWP HamburgerControl pendant does the same.
