### ISSUE TITLE
Fix given in #3000 for watermark in DateTime picker doesn't work

### ISSUE THREAD

**Issue by makingbloke** [MahApps/MahApps.Metro#3006]
#3000 Downloaded the pre-release last night and compiled it. "" still gives the default watermark and null clears it. (This is using the .Net 4.5 Demo).

![capture](https://user-images.githubusercontent.com/6209853/27884169-3b067a74-61cb-11e7-8dea-abd782418663.PNG)

**Comment by punker76** [comment]
@makingbloke Yes that's correct, cause the `DatePickerTextBox` has also a internal Watermark property which will be shown if you set the `TextBoxHelper.Watermark=""` use the the picker without any helper attached properties. It will show the `Select a date` term in your language.

**Comment by makingbloke** [comment]
Yes sorry, I see what you mean. My mistake :)
