### ISSUE TITLE
HamburgerMenu ignores Focusable and IsHitTestVisible properties

### ISSUE THREAD

**Issue by BittyGitty** [MahApps/MahApps.Metro#3010]
## What steps will reproduce this issue?

Add an HamburgerMenu, set Focusable=False, IsHitTestVisible=False.

### Expected outcome

Cannot focus to it with Tab key, as with all other controls.

This happens with everything contained in the hamburgermenu, both the 'menu' itself as with the content.

**Comment by punker76** [comment]
@BittyGitty The `Focusable` property has no effect for tabbing. If I set the `IsHitTestVisible` to false then I can't click on any inner control of the HamburgerMenu, so it work. If you want to disable tab function you could set `IsTabStop` to false which is now fixed.

**Comment by BittyGitty** [comment]
Focusable does effect tabbing, as only the focused element can receive keyboard input. This works the same with all other controls and can be used to temporarily disable user access to the menu (which is not the same as disabling tab stop).

Jan Karger wrote:

@BittyGitty <https://github.com/bittygitty> The |Focusable| property
has no effect for tabbing. If I set the |IsHitTestVisible| to false
then I can't click on any inner control of the HamburgerMenu, so it
work. If you want to disable tab function you could set |IsTabStop| to
false which is now fixed.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/MahApps/MahApps.Metro/issues/3010#issuecomment-338501837>,
or mute the thread
<https://github.com/notific ations/unsubscribe-auth/AcuNUlI4R1XAKxvb8izZ9DjBF0qWQKWHks5su5TNgaJpZM4OVjf9>.
