### ISSUE TITLE
Validation red border still there until i empty the text box

### ISSUE THREAD

**Issue by MajedDH** [MahApps/MahApps.Metro#3012]
## What steps will reproduce this issue?

I have a custom `UserControl`  with custom `dependenecyProperties` that implements `IDataErrorInfo`, inside the control there are some `textboxes`  with values bound to it's `depenedency properties`.

When i use the control i bind to it some properties from the Viewmodel , in one specific case (i want to update something already in the Database) , the values of the properties are full and ready inside the Viewmodel even before Attaching it as a datacontext to the window .

after attaching the datacontext to the window and `ShowDialog` it, the textboxes inside the usercontrol are filled with validated data but the red border of validation is still visible, and no floating message of the error is visible , i debugged the code and found this:

 program execution enters the errors indexer of `IDataErrorInfo`   in those cases:

first time the `datacontext` is null so all values are null (obviously there will be validation errors and red boxes all over the window) 

but after each property change,  program execution enters the  indexer and it returns `null` (no errors) but the validation red box around the textbox doesn't disappear, it still visible and no floating message
### what is happening

Validation red border around the `textbox` doesn't disappear, it still visible and no floating message.
Even if i write into the textbox each time property changes it enters the errors indexer of `IDataErrorInfo` and it returns null and the border doesn't disappear. 
**until i delete all of the contents of the textbox and refill it again, then it gets back to normal behaviour**

### what should happen

a textbox full of valid information , so validation red border should disappear from around it.

### Repo

It is ready and the proplem appears inside this solution:

[_Link to the Repo_](https://github.com/MajedDH/Mahapps.MetroIssue)

### Environment

- MahApps.Metro 1.5.0.23
- Windows  7
- Visual Studio 2012
- .NET Framework 4.5

**Comment by punker76** [comment]
@MajedDH The connection to your DataContext was wrong -> PR https://github.com/MajedDH/Mahapps.MetroIssue/pull/1

**Comment by MajedDH** [comment]
well, shouldn't the metro library update the validation after changing the data context( changing the data context in runtime ) ?
