### ISSUE TITLE
please publish MahApps.Metro base on .NETCore framework

### ISSUE THREAD

**Issue by tjubuntu** [MahApps/MahApps.Metro#3015]
when i plan using MahApps.Metro  to devloping windows 8 metro app,i used vs2012,and .net framework is .NETCore,Version=v4.5,but MahApps.Metro not match. By the way the OS of computer is Windows 8 not 8.1 in our company . thanks!

**Comment by punker76** [comment]
@tjubuntu MahApps is compiled for .NET4 and .NET45+ and I think it's currently not possible to compile for .NETCore

**Comment by thoemmi** [comment]
WPF does not work with .NET Core.
