### ISSUE TITLE
GlowBrush bug 

### ISSUE THREAD

**Issue by khspace** [MahApps/MahApps.Metro#3016]
If set MetroWindow owner to a Winforms window, after MetroWindow  has been dragged to other position  the glow of MetroWindow remain in original position. 
![picture1](https://user-images.githubusercontent.com/20200828/28711957-eabbc260-73bb-11e7-9bdb-e55990375288.png)

**Comment by punker76** [comment]
@khspace Can you provide a sample app for this (on GitHub)?

**Comment by punker76** [comment]
@khspace I'm little confused cause the Owner can only be a Window and not a WindowForms...

![image](https://user-images.githubusercontent.com/658431/30615013-c08cdfd2-9d8d-11e7-8164-2558389823a7.png)

**Comment by punker76** [comment]
@khspace The only way to set a WinForms owner is this one

```
private void button1_Click(object sender, EventArgs e)
{
  var window = new GlowWindowTest();
  WindowInteropHelper helper = new WindowInteropHelper(window);
  helper.Owner = this.Handle;
  window.Show();
}
```

and this seems to work.

![mahapps_winforms](https://user-images.githubusercontent.com/658431/30616367-4a9d14ae-9d92-11e7-81ba-3cf3152015eb.gif)
