### ISSUE TITLE
SplitButton with custom ItemTemplate - Source change does not always update layout

### ISSUE THREAD

**Issue by alexeygritsenko** [MahApps/MahApps.Metro#3017]
For example, I install a source with 1 element, then I reset it and install it with 3 elements. In this case, the control is not redrawn, and shows only 1 element, although there are 3 of them.

`splitButtonPlay.ItemsSource = null;
            splitButtonPlay.ItemsSource = buttonList;`

Full source sample bug project: https://yadi.sk/d/jCWvN8aT3Ljgo6

### Environment

- MahApps.Metro __v1.5__
- Windows OS __7 x64__
- Visual Studio __2015__
- .NET Framework __4.0__

**Comment by punker76** [comment]
@alexeygritsenko This fix will be available in 1.6.0
