### ISSUE TITLE
Attach button to combobox without clearing selection 

### ISSUE THREAD

**Issue by NourZohdy** [MahApps/MahApps.Metro#3020]
I want to add button to ComboBox that allow me to handle command without clearing selection..
like the case in [This Scenario](https://github.com/MahApps/MahApps.Metro/issues/2597) but with ComboBox NOT TextBox

Do i miss specific style to set in ComboBox to achieve what i want ?

**Comment by JobaDiniz** [comment]
@NourZohdy I've opened [this issue](https://github.com/MahApps/MahApps.Metro/issues/3191).
As a workaround, I've copied all the `ComboBox` style and added the steps I mentioned in the issue, and it works.
