### ISSUE TITLE
ComboBox popup border thickness problem

### ISSUE THREAD

**Issue by JerryJian** [MahApps/MahApps.Metro#3025]
## What steps will reproduce this issue?

_Set BorderThickness of ComboBox, affect the popup's border thickness._

### Expected outcome

_I personally expect popup's border thickness is set from a dynamic resource or hard coded to 1, 1, 1, 1 _

- MahApps.Metro __v1.5__
- Windows OS __7 SP1__
- Visual Studio __2015__
- .NET Framework __4.0__

**Comment by punker76** [comment]
@JerryJian It's now possible to change the popup border thickness and padding for `ComboBox`. So there are 3 new resource keys added. (available in 1.6.0)
  + `ComboBoxBorderThemeThickness` (default 1)
  + `ComboBoxPopupBorderThemeThickness` (default 1)
  + `ComboBoxPopupBorderThemePadding` (default 1)

**Comment by JerryJian** [comment]
Thanks very much! @punker76
