### ISSUE TITLE
How do i limit the number of digits input to a NumericUpDown control? 

### ISSUE THREAD

**Issue by ShannonZ** [MahApps/MahApps.Metro#3027]
How do I limit the number of digits input to a NumericUpDown control? Just like the MaxLength of a TextBox control.

Dig deeper, how do I limit the number of digits after '.' (dot) ?

**Comment by svendu** [comment]
By setting StringFormat property. By setting it to "0.00" two digits after the dot will be displayed.

**Comment by ShannonZ** [comment]
I want to limit the number of digits including both those before and after dot.

**Comment by ShannonZ** [comment]
@svendu  If you type enough number of digits( until you see the horizontal scrollbar), an overflow exception will be throw...
