### ISSUE TITLE
StrongName signed assembly? Hey, it's 2017...

### ISSUE THREAD

**Issue by punker76** [MahApps/MahApps.Metro#3029]
MahApps v1.6.0 will not be strong-named.

Why?

Strong-named assemblies are only useful in some rare scenarios. If you need strong-named assembly then you can compile the source by yourself ore use the [Strong Namer](https://github.com/dsplaisted/strongnamer) from Daniel Plaisted @dsplaisted or [Strong-Name Signer](https://github.com/brutaldev/StrongNameSigner) from Werner van Deventer @brutaldev.

More informations about the reason of this decision can be found here:

- [Still Strong-Naming your Assemblies? You do know it’s 2016, right?](https://www.pedrolamas.com/2016/03/01/still-strong-naming-your-assemblies-you-do-know-its-2016-right/)
- [XAML Behaviors UWP Managed 1.1.0](https://www.pedrolamas.com/2016/02/23/xaml-behaviors-uwp-managed-1-1-0/)
- [Strong-Named Assemblies](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/strong-named-assemblies)

**Comment by maggarwal** [comment]
This is really annoying. I have been using this library for years and all our products are signed. Now I have dilemma that should I continue to use this or look for alternatives. Hack you suggest to sign it is not ideal as it does not work in lots of scenarios. What I don't understand is what is the harm having it signed? Also, if there is an issue why not have both versions available so that you are not breaking things for audience who is already using it.

**Comment by simpert** [comment]
What a bummer. I too have been using MahApps for a few years now and the projects I am working on, COM Addin, require all assemblies to be signed. Putting things in GAC to prevent from needed to simply sign assemblies is not ideal for me. I am in the team of what's the harm. It takes 2.5 seconds in Visual Studio to sign the source and if you think that it is ideal to offer assemblies up through nuget that are not signed, why is MahApps Metro the single only assembly I have ever come across that isn't signed. I am referencing 45 nuget packages including all the Roslyn packages and MahApps is the only problem package. I think I would be hard pressed to find any assembly on my computer that isn't signed.

**Comment by LaurelJay** [comment]
And why you listen to their post? Signed assembly is compatible with all project whether it is signed or not. While not signed give headache to all signed obfuscated assemblies. Pls. sign the MahApps again. thanks..
