### ISSUE TITLE
NumericUpDown do not fire at certain conditions

### ISSUE THREAD

**Issue by ShannonZ** [MahApps/MahApps.Metro#3031]
### FYI

_Link to the Repo_
![capture-1](https://user-images.githubusercontent.com/7865691/29863479-6aee22de-8da2-11e7-91df-385f5d950e3c.gif)

### Environment

- MahApps.Metro __v1.5.0__
- Windows OS __win7 x64__
- Visual Studio __2015__
- .NET Framework __4.5__

**Comment by ShannonZ** [comment]
Not fixed in V1.6.0 alpha 011

**Comment by punker76** [comment]
@ShannonZ can you put this sample on GitHub?

**Comment by ShannonZ** [comment]
I've done some trials and I find that this bug was produce by Softfluent.Windows.
Even though, I still update a demo to reproduce this issue.[demo](https://github.com/ShannonZ/playground.git)

**Comment by punker76** [comment]
@ShannonZ Please try MahApps.Metro 1.6.0-alpha012. One reason for not accepting the value was the string format (without braces), the other reason was a missing UpdateSourceTrigger=PropertyChanged in the template.

```xaml
<DataTemplate x:Key="NUDEditor">
    <Controls:NumericUpDown Interval="1"
                            Maximum="10000"
                            Minimum="0"
                            StringFormat="00.000 munit"
                            Value="{Binding Value, UpdateSourceTrigger=PropertyChanged}" />
</DataTemplate>
```

**Comment by ShannonZ** [comment]
Thanks!!! All is present as expected now.
