### ISSUE TITLE
GlowBrush="{DynamicResource AccentColorBrush}" is causing a ComponentModel Exception in UpdateCore

### ISSUE THREAD

**Issue by evilbaschdi** [MahApps/MahApps.Metro#3034]
testing the current alpha versions of mahapps.metro I currently resolve an error using a GlowBrush.
The error thrown is a "invalid window handle" in
MahApps.Metro\MahApps.Metro.Shared\Controls\GlowWindow.xaml.cs line 274.

At the moment I'm not able to reproduce that error in the sample apps contained in the mahapps.metro repository but with my own applications for example "TestUI" from https://github.com/evilbaschdi/EvilBaschdi.Core/tree/develop but I have no Idea were to search for the problem. with 1.5.0 everything's working fine.

**Comment by punker76** [comment]
@evilbaschdi Which alpha version did you use?

**Comment by evilbaschdi** [comment]
currently I'm using 012, it also happened with 009 until 011.
I think I just found the problem my selfe. There was a AllowsTransparency="True" in my code and I don't know why it is there. But with 1.5.0 that problem does not occur.

**Comment by punker76** [comment]
@evilbaschdi MahApps uses now ControlzEx dll. The Problem is by NuGet which doesn't get always the highest dependency from ControlzEx for MahApps. This can be set in the NuGet package manager in VS (or you use the paket manager).

**Comment by evilbaschdi** [comment]
I know about that. And I've been on 3.0.66 (or what is the current) ControlzEz. I've even referenced the your repository directly for better debugging.

**Comment by punker76** [comment]
@evilbaschdi This should be fixed now and is available with 1.6.0-alpha013

**Comment by evilbaschdi** [comment]
yes, it's working now. thx!
