### ISSUE TITLE
Should we remove install.ps1 from nuspec?

### ISSUE THREAD

**Issue by punker76** [MahApps/MahApps.Metro#3037]
The NuGet package of MahApps open up the [Quick-Start](http://mahapps.com/guides/quick-start.html) guide on installation and updating.

Some people don't want this, some people say this is a bad practice...

So please give a

- 👍 all is fine, nothing should be changed
- 👎 for removing

Thx

**Comment by amkuchta** [comment]
I'm all for removing it, but let's make sure that the quick start is easy to find on the home page (readme) or in the wiki.

**Comment by punker76** [comment]
@amkuchta This should be the case right now.

**Comment by feinstein** [comment]
👎 remove it, I always hated it, the quick start website is on the nuget and github websites, everyone knows it exists, and if someone doesn't, Google will surely show him when he searches for help. I think it annoys more than helps.

**Comment by amkuchta** [comment]
Looks like the overwhelming response is to kill it with :fire: :laughing:
