### ISSUE TITLE
NumericUpDown

### ISSUE THREAD

**Issue by seb30** [MahApps/MahApps.Metro#3039]
- MahApps.Metro v1.6.0-alpha013
- Windows OS 10
- Visual Studio 2017
- .NET Framework 4.7

NumericUpDown is bound to byte?, Minimum = 0 and Maximum = 255. If value decrements to 0, the Button is disabled, but with MouseWheel it is possible to decrement more.

![image](https://user-images.githubusercontent.com/28293949/30108824-336fe010-9304-11e7-871c-77f7c8a33323.png)

Next issue is, that the value is parsed immediatly:

![image](https://user-images.githubusercontent.com/28293949/30109045-2273859a-9305-11e7-94aa-6bd664873e9f.png)

None of this issues are seen in 1.6.0-alpha011.

**Comment by punker76** [comment]
@seb30 Thx for testing the latest changes 👍 

- I'll look for the MouseWheel stuff
- "..., that the value is parsed immediatly" I think this is now correct so. Isn't it?

**Comment by seb30** [comment]
2nd point: I'm not sure, because now I got this ugly message from WPF. In alpha011 I was able to fill the whole NUD with 99999999999999999 and then changed the focus; the value was set to Maximum.

**Comment by seb30** [comment]
Are there any updates here?

**Comment by punker76** [comment]
- using the MouseWheel works as expected (tested on my machine™ and the current source)
- parsing the value while the user types a number isn't a nice solution (and also complicated to solve), cause every input parses the value and changes the text...

**Comment by seb30** [comment]
Regarding the MouseWheel issue: I've downloaded the sources yesterday and bound the Value property of the NUD to the TestValue. Minus button is disabled, because we're at the Minimum. So far, so good. But if I use the MouseWheel, the TestValue gets decremented to -1 and my ViewModel has the wrong value. The NUD still shows 0.

![nud_1](https://user-images.githubusercontent.com/28293949/35665481-ba37bf82-0726-11e8-936a-81357cd287b7.png)

![nud_2](https://user-images.githubusercontent.com/28293949/35665484-bb999120-0726-11e8-8c96-1e5d54a77489.png)

If the NUD then loses the focus, the TestValue will be updated to 0. But my own expectation of such an control is, that the (bound) Value should never fall below the Minimum.

**Comment by seb30** [comment]
A deeper look into the code shows me that NUD.ChangeValueBy is called first, then my TestValue setter and finally the NUD.CoerceValue, where the value is limited to the Minimum.
