### ISSUE TITLE
Width parse error

### ISSUE THREAD

**Issue by ShannonZ** [MahApps/MahApps.Metro#3043]
Source code for this issue [github](https://github.com/ShannonZ/playground.git)

- Reproduce
![capture-8](https://user-images.githubusercontent.com/7865691/30194814-097af5c6-9488-11e7-8ce8-f2862a0ad759.gif)

- Expected Results
The width of editor in different tab items should be corrected!
If I use a standard WPF TabControl, like this:

    <TabControl>
        <TabItem  Header="SF1" >
            <windows:PropertyGrid x:Name="pg1" Grid.Column="0"  ScrollViewer.VerticalScrollBarVisibility="Auto" ScrollViewer.HorizontalScrollBarVisibility="Hidden" />
        </TabItem>
        <TabItem Header="SF2" >
            <windows:PropertyGrid x:Name="pg2" Grid.Column="0"  ScrollViewer.VerticalScrollBarVisibility="Auto" ScrollViewer.HorizontalScrollBarVisibility="Hidden" />
        </TabItem>
    </TabControl>

it works fine. So I guess it's related to Mahapps, maybe due to the funny animation transition when you change tabs.

**Comment by punker76** [comment]
@ShannonZ I think this is a problem of `SoftFluent.Windows`. If I put a NUD in a Tab all is fine.

![2017-09-08_11h33_25](https://user-images.githubusercontent.com/658431/30205638-b3dc7a7a-9489-11e7-85c5-f9edc405f5c8.png)

**Comment by punker76** [comment]
@ShannonZ If I replace the NUD with a TextBox then I get the same result.

**Comment by ShannonZ** [comment]
@punker76  In SoftFluent.Windows, the width of the second column of DataGrid was simply set to be "*". (<DataGridTemplateColumn Header="Value" Width="*">   in PropertyGrid.xaml #line 219) . Nothing else was done~

**Comment by punker76** [comment]
The problem is maybe, that the second one isn't visible on start. But all this happens also without MahApps.

**Comment by ShannonZ** [comment]
@punker76  I think you should using an NUD in DataGrid to reproduce this issue. And in my machine, when putting NUD in the last column of a DataGrid cell, the width seems to be not fixed.

[Demo(I used SF)](https://github.com/ShannonZ/playground.git)
Click more than one times of the "change" button, you will see the same code produce different results. 
![capture-9](https://user-images.githubusercontent.com/7865691/30237747-f9e839fa-956a-11e7-95a8-9a76c1ed7401.gif)


If you start a project from scratch and add a standard WPF TabControl, like this:

    <TabControl>
        <TabItem  Header="SF1" >
            <windows:PropertyGrid x:Name="pg1" Grid.Column="0"  ScrollViewer.VerticalScrollBarVisibility="Auto" ScrollViewer.HorizontalScrollBarVisibility="Hidden" />
        </TabItem>
        <TabItem Header="SF2" >
            <windows:PropertyGrid x:Name="pg2" Grid.Column="0"  ScrollViewer.VerticalScrollBarVisibility="Auto" ScrollViewer.HorizontalScrollBarVisibility="Hidden" />
        </TabItem>
    </TabControl>
it works fine. So I guess it's related to Mahapps, maybe due to the funny animation transition when you change tabs.

**Comment by punker76** [comment]
@ShannonZ If I deactivate the Expander MahApps style the issue is gone, so I will investigate what's going wrong with this.

**Comment by ShannonZ** [comment]
@punker76  Thanks for your kindness work! And the great MahApps will become more perfect.

**Comment by punker76** [comment]
@ShannonZ Found it. A fix will be available with 1.6.0-alpha016

**Comment by ShannonZ** [comment]
great work! Can't thank you enough~~~
