### ISSUE TITLE
TextBox validation problem

### ISSUE THREAD

**Issue by predlona** [MahApps/MahApps.Metro#3044]
Hello, I want to validate a textbox but i always failed. I didn't find any tutorial for MahApps. Can some one help me about this please ? 

Thank you.

**Comment by punker76** [comment]
@predlona This is out of scope of MahApps, please take a look e.g. [here}(https://docs.microsoft.com/en-us/dotnet/framework/wpf/data/how-to-implement-binding-validation). Thx

**Comment by ShannonZ** [comment]
@predlona  you can refer the textbox demo of MahApp Samples. There is an "IntegerGreater10Property" textbox using IDataErrorInfo to implement validation.[xaml](https://github.com/MahApps/MahApps.Metro/blob/develop/src/MahApps.Metro.Samples/MahApps.Metro.Demo/MahApps.Metro.Demo.Shared/ExampleViews/TextExamples.xaml)

Generally, you can implement input validation through at least 4 ways:
- IDataErrorInfo
- ValidationRule
- Exception
- Custom Control
And as punker76 says, it's in scope of C# WPF,not MahApps. You'd better search these topics in google.
