### ISSUE TITLE
Clicking on the "X" button added by TextBoxHelper.ClearTextButton does not clear the databinding target

### ISSUE THREAD

**Issue by programatix** [MahApps/MahApps.Metro#3045]
## What steps will reproduce this issue?

1. Click on Textbox1
2. Enter some string, eg "123"
3. Press TAB or click on other textboxes
4. The string, "123" will be shown in Textbox2 (due to data binding)
5. Click the "X" button on Textbox1
6. The string on Textbox2 is not cleared

I noted that for the "X" button to clear the databinding target,
1) The textbox where the "X" is going to be clicked on must be the active control (focused)
or
2) After clicking the "X" button, focus the textbox which the "X" button was clicked on by clicking on it, and then click on other control to make to lose focus.

### Expected outcome
Upon clicking the "X" button, the databinding target should be cleared immediately.

### Code
cs
```
using System.Windows;

namespace Test
{
    /// <summary>
    /// Interaction logic for Window1.xaml
    /// </summary>
    public partial class Window1 : Window
    {


        public string MyString
        {
            get { return (string)GetValue(MyStringProperty); }
            set { SetValue(MyStringProperty, value); }
        }

        // Using a DependencyProperty as the backing store for MyString.  This enables animation, styling, binding, etc...
        public static readonly DependencyProperty MyStringProperty =
            DependencyProperty.Register("MyString", typeof(string), typeof(Window1), new PropertyMetadata());



        public Window1()
        {
            InitializeComponent();
        }
    }
}
```

XAML
```
<Window x:Class="Test.Window1"
        x:Name="this"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:Test"
        xmlns:mahapps="http://metro.mahapps.com/winfx/xaml/controls"
        mc:Ignorable="d"
        Title="Window1" Height="300" Width="300">
    <StackPanel DataContext="{Binding ElementName=this}">
        <Label Content="Textbox1" />
        <TextBox Text="{Binding MyString}" mahapps:TextBoxHelper.ClearTextButton="True" />

        <Label Content="Textbox2" />
        <TextBox Text="{Binding MyString}" mahapps:TextBoxHelper.ClearTextButton="True" />

        <Label Content="Textbox3" />
        <TextBox />
    </StackPanel>
</Window>
```

### Environment

- MahApps.Metro 1.6.0-alpha013 (nuget)
- Windows OS 10
- Visual Studio 2017
- .NET Framework 4.6.2

**Comment by punker76** [comment]
@programatix This is by WPF, cause the default of `UpdateSourceTrigger` for Text() is LostFocus, so if you change this to `UpdateSourceTrigger=PropertyChanged` all should work as expected.

```xaml
<Label Content="Textbox1" />
<TextBox Controls:TextBoxHelper.ClearTextButton="True" Text="{Binding MyString, UpdateSourceTrigger=PropertyChanged}" />
<Label Content="Textbox2" />
<TextBox Controls:TextBoxHelper.ClearTextButton="True" Text="{Binding MyString, UpdateSourceTrigger=PropertyChanged}" />
```

>One of the UpdateSourceTrigger values. The default is Default, which returns the default UpdateSourceTrigger value of the target dependency property. However, the default value for most dependency properties is PropertyChanged, while the Text property has a default value of LostFocus.

https://msdn.microsoft.com/en-us/library/system.windows.data.binding.updatesourcetrigger(v=vs.110).aspx

**Comment by programatix** [comment]
Ok, got it working. Weird that I previously did change UpdateSourceTrigger to PropertyChanged before logging this issue but I doesn't seem to work.

However changing the UpdateSourceTrigger to PropertyChanged would degrade the performance a little as it now caused the textbox to update the datasource on every single key input, where the original task is to just cause the "X" button to clear the string.

**Comment by punker76** [comment]
@programatix If you use WPF 4.5+ you can use Delay binding

**Comment by programatix** [comment]
How about executing the following code on clearing of the textbox value by the `TextBoxHelper`?
```
var expression = targetTextBox.GetBindingExpression(TextBox.TextProperty);
if (expression != null) expression.UpdateSource();
```

**Comment by punker76** [comment]
@thoemmi what do you think?

>How about executing the following code on clearing of the textbox value by the TextBoxHelper?

**Comment by programatix** [comment]
I tried updating TextBoxHelper.cs (line 837) to,
```
            if (GetClearTextButton(parent))
            {
                BindingExpression expression=null;
                if (parent is TextBox)
                {
                    ((TextBox)parent).Clear();
                    expression = ((TextBox)parent).GetBindingExpression(TextBox.TextProperty);
                }
                else if (parent is PasswordBox)
                {
                    ((PasswordBox)parent).Clear();
                }
                else if (parent is ComboBox)
                {
                    if (((ComboBox)parent).IsEditable)
                    {
                        ((ComboBox)parent).Text = string.Empty;
                    }
                    ((ComboBox)parent).SelectedItem = null;
                    expression = ((ComboBox)parent).GetBindingExpression(ComboBox.SelectedItemProperty);
                }
                expression?.UpdateSource();
```

and it seems to work. However, I'm not sure that Property it is for PasswordBox. I wonder whether I should put this into a Pull Request?

**Comment by thoemmi** [comment]
Looking at PR #3046, I think it makes sense. :+1:

**Comment by punker76** [comment]
@programatix thx 👍
