### ISSUE TITLE
Issues with the ControlzEx dependency

### ISSUE THREAD

**Issue by Nuklon** [MahApps/MahApps.Metro#3047]
Thanks for this library, I like it. However, I've some issues with the latest changes.
I pulled the latest alpha from NuGet but I'm rolling back to the 009. Besides the extra dependency (which currently doesn't pull the correct version (it's missing some class and you need to update to 3.xx)) it's resizing MUCH slower (2-3 times) and the glow border on the window is about twice as big and a lot darker.

**Comment by punker76** [comment]
@Nuklon Make sure that you get the highest dependency by NuGet packager manager

![2017-08-31_19h58_48](https://user-images.githubusercontent.com/658431/30214109-8a88db60-94ab-11e7-9c76-51e3bb72cbbb.png)

**Comment by punker76** [comment]
@Nuklon Latest version for ControlzEx is 3.0.1.66

**Comment by Nuklon** [comment]
Yes, when updating manually to it it's working, but when you pull the latest alpha of MahApps.Metro it's downloading the 2.0xx build of it.

**Comment by Nuklon** [comment]
Only alpha-010 has the dependency correctly (> 3.0.1), the newer alphas have > 2.0, but 2.0 doesn't work. So the NuGet package dependency version should be increased as it was on alpha-010.

**Comment by punker76** [comment]
@Nuklon I'll look for this fu... NuGet stuff, normally > should mean greater and not greater equal...

**Comment by punker76** [comment]
@Nuklon  so `(2.0,4.0)` should be `2.0 < x < 4.0 Exact range, exclusive`

**Comment by punker76** [comment]
@Nuklon 🙈  so yeah mmh, it should be `(2.2,4.0)`

**Comment by Nuklon** [comment]
Yes, that should work I think. 2.0 won't work as there's 2.1 and 2.2, so I'd expect (2.2, 4.0) to work.

**Comment by Nuklon** [comment]
(besides the nuget issues there's also the other two issues btw, not sure if you want those separately or not)

**Comment by punker76** [comment]
@Nuklon 

>it's resizing MUCH slower (2-3 times) and the glow border on the window is about twice as big and a lot darker.

I don't see this with the main demo :-(

**Comment by Nuklon** [comment]
The resize is very easy to check with the demo, 1.5.0 resizes a ton faster than 1.6.0 demo. Since this ControlzEx has been added the resizing is extremely jerky. 
You can check it here:
https://i.imgur.com/1MPsds4.gifv
(left one is 1.5.0, right one is the latest 1.6.0 build). 

If you need the original video:
[170908_16-1559.zip](https://github.com/MahApps/MahApps.Metro/files/1288143/170908_16-1559.zip)

I don't really see a difference with the border in the demo, I'll check why it's different in my app.

**Comment by punker76** [comment]
@Nuklon Can you check Release compiled?

**Comment by Nuklon** [comment]
It doesn't matter if you use debug or release build, both are as very slow in resize.

**Comment by Nuklon** [comment]
The other issue I think comes when you set BorderThickness="0" in the MainWindow. I think the cutoff of the glow is 1-2px further away.

**Comment by punker76** [comment]
@Nuklon 1.6.0-alpha014 is out

**Comment by punker76** [comment]
@Nuklon I cannot confirm your behavior and the difference between 1.5.0 and 1.6.0 (by updating to 1.6). I find that 1.6.0 works even better (subjectively speaking). These test is debug compiled and uses the latest source and ControlzEx 3.0.1.66.

### 1.5

![mahapps_1 5](https://user-images.githubusercontent.com/658431/30220314-451ff554-94bf-11e7-9fa4-3ed8d467c06e.gif)

### 1.6

![mahapps_1 6](https://user-images.githubusercontent.com/658431/30220336-5766f3ca-94bf-11e7-8d05-cd5cde76dd55.gif)

(maybe some frames dropped in the gif)

**Comment by batzen** [comment]
@Nuklon  In the video you started one version using the debugger and one version without the debugger, maybe that's the problem?

**Comment by Nuklon** [comment]
No, I already said it doesn't matter how you run it.
________________________________

**Comment by batzen** [comment]
@Nuklon Could you create a new video without the debugger attached? Which version/build of windows 10 are you running on? Are you using the latest graphics card drivers?

Could you try to force software rendering on the window and see if that changes something?

In Window constructor:
```
this.SourceInitialized += this.Window_SourceInitialized;
```

```
private void Window_SourceInitialized(object sender, System.EventArgs e)
{
    var hwndSource = (HwndSource)PresentationSource.FromVisual(this);
    var hwndTarget = hwndSource.CompositionTarget;
    hwndTarget.RenderMode = RenderMode.SoftwareOnly;
}
```

Could you comment out the line saying `new BorderlessWindowBehavior()` in `InitializeStylizedBehaviors``of `MetroWindow.cs` and see if resizing is still slow?

**Comment by Nuklon** [comment]
I'm running the latest W10 build (all up-to-date), including the drivers (one with AMD and the other is using NVIDIA).
I've been experimenting with it a little and debugger on/off matters _some_ (it's a bit better without the debugger attached but not perfect yet).  software rendering doesn't help. However, what I noticed is that if I disable the window glow everything is fast (regardless if a debugger is attached or not).

**Comment by batzen** [comment]
@Nuklon Could you run the performance profiler in visual studio, profile resizing and attach the results to this issue?

**Comment by punker76** [comment]
@Nuklon Any updates for this? Yes, using the GlowWindowBehavior influences the ui/gpu/cpu performance, cause there are 4 fake windows for this glow effect (there will be maybe an update to this in the future). I will close this for now. I tested also a little bit with different machnies, os, virtual machines and I can see on each that the performance is better then before. If you have some reports from the performance profiler of VS feel free to report these here. thx

**Comment by Nuklon** [comment]
Currently on holidays, will look into it when I get back.
On Sep 29, 2017, at 23:51, Jan Karger <notifications@github.com<mailto:notifications@github.com>> wrote:

@Nuklon<https://github.com/nuklon> Any updates for this? Yes, using the GlowWindowBehavior influences the ui/gpu/cpu performance, cause there are 4 fake windows for this glow effect (there will be maybe an update to this in the future). I will close this for now. I tested also a little bit with different machnies, os, virtual machines and I can see on each that the performance is better then before. If you have some reports from the performance profiler of VS feel free to report these here. thx
