### ISSUE TITLE
MetroNavigationWindow HomePage Button ?

### ISSUE THREAD

**Issue by predlona** [MahApps/MahApps.Metro#3052]
Hello guys, i am using MetroNavigationWindow for my project's navigations. But there is just Back and Forward buttons. How can i add a HomePage button ?

Thank you for your helping.

**Comment by xe7485** [comment]
Hi. I saw this request and modified my code from #1828 with a simple implementation.

[NavigationWindowWithHome.cs.txt](https://github.com/MahApps/MahApps.Metro/files/1547605/NavigationWindowWithHome.cs.txt)
