### ISSUE TITLE
Setting DisplayDate property of DateTimePicker does not change the displayed date

### ISSUE THREAD

**Issue by captainst** [MahApps/MahApps.Metro#3056]
I suppose that it is an issue which could be easily reproduced. Just add a DateTimePicker to the window. 
In the code behind, set the DisplayDate property. But the DateTimePicker control remains empty with the default hint text.

I was thinking that the term "DisplayDate" should be the date/time actually displayed in the box. While it seems that DisplayDate value gets updated when SelectedDate changes. Setting DisplayDate from user code just does not have any effect.

Is this normal ?

### Environment

- MahApps.Metro __v1.4.3__
- Windows OS __win7 64bit__
- Visual Studio __2013__
- .NET Framework __4.5__

**Comment by punker76** [comment]
@captainst This is not related to MahApps (same result with default style)

>This property affects the Calendar of the DatePicker. For more information, see the Calendar.DisplayDate property.

>This property allows the developer to specify a date to display if SelectedDate is null.

https://msdn.microsoft.com/en-us/library/system.windows.controls.datepicker.displaydate(v=vs.110).aspx#United States (English)

**Comment by captainst** [comment]
@punker76 Thank you. I mis-interpreted the meaning of DisplayDate.
