### ISSUE TITLE
Feature request: Allow to use VisibilityHelper for DataGridColumn (and possibly other)

### ISSUE THREAD

**Issue by SylwesterZarebski** [MahApps/MahApps.Metro#3058]
### Current state
Now VisibilityHelper allow to simpler use without converters for every element which is a child of FrameworkElement. But there are classes which are not descendants of FrameworkElement like DataGridColumn, but have Visibility property and VisibilityHelper do not work for them.

### Expected
VisibilityHelper should work also for DataGridColumn and possibly other WPF elements which are not descendants of FrameworkElement.

### Environment

- MahApps.Metro 1.5.0 (current stable)
- Windows OS - any
- Visual Studio 2015
- .NET Framework - any

**Comment by punker76** [comment]
@SylwesterZarebski You can use a `BindingProxy` for these elements which doesn't inherit the DataContext through the visual tree.

[[WPF] HOW TO BIND TO DATA WHEN THE DATACONTEXT IS NOT INHERITED](https://www.thomaslevesque.com/2011/03/21/wpf-how-to-bind-to-data-when-the-datacontext-is-not-inherited/)

**Comment by SylwesterZarebski** [comment]
Yes, i know - i do this similar way now, but this request is not for context binding, but using VisibilityHelper instead of converters for elements which are not descendant of FrameworkElement.
