### ISSUE TITLE
Unable to build the solution

### ISSUE THREAD

**Issue by amkuchta** [MahApps/MahApps.Metro#3061]
## What steps will reproduce this issue?

_Using the latest `develop` branch, attempted to build the demo projects.  Though Paket is installed and the `paket.dependencies` file has been installed, I am still getting errors at build time:_

`Error during cleaning of C:\Users\amkuc\Source\Repos\MahApps.Metro\src\packages\Fody`

### Expected outcome

_Projects should build so that controls and changes can be seen_

### Repo

_Latest `develop` branch_

### Environment
- Windows OS __10__
- Visual Studio __2017__

**Comment by punker76** [comment]
@amkuchta Seems like Fody is still running/hanging from a previous run. I don't know what this caused.

**Comment by amkuchta** [comment]
@punker76, any thoughts on how to fix it? maybe delete the local repo and clone again?

**Comment by Insire** [comment]
are you building in parallel? try disabling that, then close any open msbuild instances

**Comment by thoemmi** [comment]
Fody includes a MsBuild task. Once the project is loaded, Visual Studio blocks the assembly file.

**Comment by amkuchta** [comment]
@thoemmi any insight on how to fix visual studio blocking the file?

**Comment by thoemmi** [comment]
@amkuchta yes: close Visual Studio :wink:

**Comment by amkuchta** [comment]
@thoemmi no joy (P.S. I tried that first 😝 )

Screenshot to demonstrate:
![image](https://user-images.githubusercontent.com/6255186/30994116-4ed80124-a480-11e7-877d-f98094698554.png)

**Comment by amkuchta** [comment]
Ok, got the issue resolved.  Steps to fix:

1. Close Visual Studio
2. Open a command prompt, navigate to the .NET directory:
  - `cd C:\Windows\Microsoft.NET\Framework\v4*`
3. Run MSBuild.exe to compile the solution:
  - msbuild "%PathToMahApps%\MahApps.Metro.sln" /t:Rebuild /p:Configuration=Debug /p:Platform="Any CPU"
4. Re-Open Visual Studio
5. Clean the solution (for some reason, I got an issue with finding `GlowWindow.xaml` before I did this)
6. Build in VS
7. Profit

@thoemmi @punker76 it's worth noting that the command line build process shoots me a suggestion:

`Please use the new syntax: '--references-files' has been replaced by '--references-file'.`
