### ISSUE TITLE
The idea to expand the ListBox with expand wrappanel

### ISSUE THREAD

**Issue by ORRNY66** [MahApps/MahApps.Metro#3062]
Hello,
I really like your work. I like to use MahApps.

I got an interesting idea to extend the style of the ListBox.
see picture:

![ListBox with ElasticWrapPanel](https://i.stack.imgur.com/6Uyep.gif)

Items in the ListBox would be sorted into [ElasticWrapPanel .](https://gist.github.com/ORRNY66/8062491cd37c5cbf713cd87da6ad12d1)
When selecting an item from the ListBox, the item details appear.

**Comment by punker76** [comment]
@ORRNY66 Nice idea 👍  but I think this is too specific to add this to MahApps.

/cc @thoemmi

**Comment by thoemmi** [comment]
Yeah, @punker76 knows I'm always reluctant to add features which are out of scope of MahApps.Metro 😉 
Nevertheless, nice work @ORRNY66.
