### ISSUE TITLE
TabControl blocks UI thread when Item is added dynamically

### ISSUE THREAD

**Issue by helmerm** [MahApps/MahApps.Metro#3063]
## What steps will reproduce this issue?

Given a TabControl with TabStripPlacement=Left
When a TabItem with Header="ServiceRegistry" is added dynamically
Then UI Thread is blocked

I guess this has to do with the recalculation of the column width. 
It does not occure if the text is changed. I assume that I found a magic key word which causes this 😄 

### Expected outcome

No blocking UI Thread

### Repo

[MahAppTabControlIssue](https://github.com/helmerm/MahAppTabControlIssue)

### Environment

- MahApps.Metro __v1.5.0__
- Windows OS __Win10__
- Visual Studio __2017 15.3.5__
- .NET Framework __4.7__
- Display: ASUS PB287Q 4K --> 3840x2160

**Comment by punker76** [comment]
@helmerm I could not found an issue here. Tested on win 10 vs 2015, normal DPI. Is there anything else what can cause this?

![mahapps_tab_performance](https://user-images.githubusercontent.com/658431/31059505-9b16c9be-a703-11e7-927a-36eac56259cb.gif)

**Comment by helmerm** [comment]
@punker76 It only occures with the exact word "ServiceRegistry" on my machine. Maybe this issue depends on the resolution (mine is 3840x2160). What is yours?

I will try to reproduce it with different resolutions and try to figure out the text width which causes the issue.

**Comment by punker76** [comment]
@helmerm tested on 1920x1080 DPI 100% Intel HD-Graphics 530

**Comment by punker76** [comment]
@helmerm same result with 125% DPI

**Comment by helmerm** [comment]
@punker76 I can reproduce this on my machine with different settings. I tried within and without Visual Studio, Release/Debug build, different resolutions and DPI settings. 

However, it is not blocking the thread, but seems like causing some never ending recursion, which causes the UI thread to use 100% of its core. If I pause with the debugger, you can see the call stack bellow. 

![image](https://user-images.githubusercontent.com/3226548/31097042-430a3c68-a7be-11e7-9dbc-50404c4c98ed.png)

![image](https://user-images.githubusercontent.com/3226548/31096899-c58270ee-a7bd-11e7-8078-a3985519ed41.png)

![image](https://user-images.githubusercontent.com/3226548/31097228-d9415a36-a7be-11e7-93b8-020cca6e4eb7.png)

**Comment by punker76** [comment]
@helmerm wow... Can you try this with .NET Framework 4.6.2 or lower and maybe without MahApps...

**Comment by helmerm** [comment]
@punker76 It only happens with 4.7, works with 4.6.1 or lower (I do not have 4.6.2 installed).

I am not sure, how I can reproduce it without MahApps. This seems to be related to the resize of the HeaderedPanelGrid Column (when the MetroTabItem is added) which depends on the control template...

**Comment by punker76** [comment]
@helmerm I have no idea what's going wrong on your machine. I've tested with my [forked ](https://github.com/punker76/MahAppTabControlIssue) repo and can't reproduce your issue. I've tested this on 2 different machines with different DPI and monitor size. Also with .Net framwork 4.6 - 4.7

So can you maybe test this also on a different machine? Is maybe your 4.7 not correct installed (maybe corrupt)

thx
