### ISSUE TITLE
Only can change app style one time

### ISSUE THREAD

**Issue by heerheer** [MahApps/MahApps.Metro#3065]
ThemeManager.ChangeAppStyle(Application.Current, ThemeManager.GetAccent(Name), ThemeManager.GetAppTheme("BaseLight"));

but if i change 2 times,it will error

**Comment by punker76** [comment]
@heerheer Please provide a better bug report! What error occurs? What do you mean with change 2 times? Do you have an example?

**Comment by heerheer** [comment]
I can change the style only once。
If i change it again,it will crash。and throw System.NullReferenceException

**Comment by heerheer** [comment]
发生了 System.NullReferenceException
  HResult=0x80004003
  Message=未将对象引用设置到对象的实例。
  Source=<无法计算异常源>
  StackTrace:
   在 MahApps.Metro.ThemeManager.ChangeAppStyle(ResourceDictionary resources, Tuple`2 oldThemeInfo, Accent newAccent, AppTheme newTheme) 在 d:\projects\git\MahApps.Metro\src\MahApps.Metro\MahApps.Metro.Shared\ThemeManager\ThemeManager.cs 中: 第 371 行
   在 MahApps.Metro.ThemeManager.ChangeAppStyle(Application app, Accent newAccent, AppTheme newTheme) 在 d:\projects\git\MahApps.Metro\src\MahApps.Metro\MahApps.Metro.Shared\ThemeManager\ThemeManager.cs 中: 第 344 行
   在 Heer_MC_Launcher.Window_t.Button_Click(Object sender, RoutedEventArgs e) 在 E:\visual studio 2017\Projects\Heer MC Luancher\Heer MC Luancher\Window_t.xaml.cs 中: 第 56 行
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   在 System.Windows.Controls.Primitives.ButtonBase.OnClick()
   在 System.Windows.Controls.Button.OnClick()
   在 System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   在 System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   在 System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   在 System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   在 System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   在 System.Windows.Input.InputManager.ProcessStagingArea()
   在 System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   在 System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   在 System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   在 System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   在 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   在 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   在 MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   在 System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   在 System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   在 System.Windows.Application.RunDispatcher(Object ignore)
   在 System.Windows.Application.RunInternal(Window window)
   在 System.Windows.Application.Run(Window window)
   在 Heer_MC_Launcher.App.Main()

**Comment by punker76** [comment]
@heerheer Can you provide a short sample which produces your issue? thx.

**Comment by punker76** [comment]
@heerheer Seems like you forgot to add the MahApps resources to the App.xaml, cause `ThemeManager.GetAppTheme("BaseLight")` gets only a null pointer which is passed to the `ChangeAppStyle` method. A quick start guide is [here](https://github.com/MahApps/MahApps.Metro/wiki/Quick-Start) available.

**Comment by MarioGK** [comment]
I am getting the same error, the first time it changes the color perfectly fine, but the second time it gives a null exception, example code https://i.imgur.com/pk44uqN.png,

Exception:
10-13 12:55 |ERROR| (MainViewModel.LoaderThemeManager_OnThemeChange) Failed to change the theme color
===============================================================
Entropy.Loader :: Error in: LoaderThemeManager_OnThemeChange
--With Type: System.NullReferenceException
--With Message: Object reference not set to an instance of an object.
--With Stracktrace:
   at MahApps.Metro.ThemeManager.ChangeAppStyle(ResourceDictionary resources, Tuple`2 oldThemeInfo, Accent newAccent, AppTheme newTheme) in d:\projects\git\MahApps.Metro\src\MahApps.Metro\MahApps.Metro.Shared\ThemeManager\ThemeManager.cs:line 371
   at MahApps.Metro.ThemeManager.ChangeAppStyle(Application app, Accent newAccent, AppTheme newTheme) in d:\projects\git\MahApps.Metro\src\MahApps.Metro\MahApps.Metro.Shared\ThemeManager\ThemeManager.cs:line 344
   at Entropy.Loader.ViewModels.MainViewModel.LoaderThemeManager_OnThemeChange(LoaderTheme theme) in D:\EntropyProjects\Entropy.Loader\Entropy.Loader\ViewModels\MainViewModel.cs:line 85
--At Line:371
===============================================================

**Comment by punker76** [comment]
@MarioGK do you put all necessary MahApps resource dictionaries to the App.xaml? what contains your PrimaryColor property?

**Comment by HaloEleven** [comment]
Backing up what the OP said, if I implement the following code and call it multiple times (while handling a checkbox event), I get and "Object reference not set to an instance of an object" exception:

            if (nightMode)
            {
                ThemeManager.ChangeAppStyle(Application.Current,
                                        ThemeManager.GetAccent("Indigo"),
                                        ThemeManager.GetAppTheme("BaseDark"));
            }
            else
            {
                ThemeManager.ChangeAppStyle(Application.Current,
                                        ThemeManager.GetAccent("Teal"),
                                        ThemeManager.GetAppTheme("BaseLight"));
            }

I tried delegating to the UI thread, but it still throws the exception.

**Comment by HaloEleven** [comment]
OP: I got a similar exception when I added the Theme in the App.xaml AND subsequently called ThemeManager.ChangeAppStyle in code-behind. You can only do one or the other.
