### ISSUE TITLE
Controls not visibles in design mode

### ISSUE THREAD

**Issue by DiegoGFritz** [MahApps/MahApps.Metro#3080]
## What steps will reproduce this issue?

I follow Quick Start Guide and the controls are visible only in runtime but not in design mode.

### Expected outcome

Controls should be viewed in design mode

### Repo

No repo.

### Environment

- MahApps.Metro v1.5.0.23
- Windows OS 10 Version 1703 (OS Build 15063.674) x64
- Visual Studio 2017 Enterprise 
- .NET Framework 4.5

**Comment by punker76** [comment]
@DiegoGFritz Which controls?

**Comment by DiegoGFritz** [comment]
Sorry. MetroWindow

**Comment by punker76** [comment]
@DiegoGFritz A window style will not be shown by a VS designer. Sorry, but this is a limitation by the VS designer.
