### ISSUE TITLE
Dialog unaffected by dark-theme when using local copy of Blue.xaml

### ISSUE THREAD

**Issue by JVimes** [MahApps/MahApps.Metro#3083]
## What steps will reproduce this issue?

1. In App.xaml:
    * Merge BaseDark.xaml to set dark theme
    * Merge a *local* copy of Blue.xaml
2. Show a CustomDialog similarly to how it's done [in the demo app](https://github.com/MahApps/MahApps.Metro/blob/1.5.0/src/MahApps.Metro.Samples/MahApps.Metro.Demo/MahApps.Metro.Demo.Shared/MainWindow.xaml#L78).

![image](https://user-images.githubusercontent.com/6148201/31640619-bac8fc56-b29c-11e7-9203-873bc49e92d5.png)

### Expected outcome

The dialog should have a dark background:

![image](https://user-images.githubusercontent.com/6148201/31640692-074ffcdc-b29d-11e7-882a-49dda60ae91d.png)

### Repo

https://github.com/JVimes/MahAppsMetroBugRepro1.git

### Environment

- MahApps.Metro __v1.5.0__
- Windows OS __10__
- Visual Studio __2017__
- .NET Framework __4.5__

**Comment by punker76** [comment]
@JVimes You must add customized accent or theme resources to the ThemeManager. Only adding it to the App.xaml is not enough. You can do this at the App startup for example

```
  public partial class App : Application
  {
    protected override void OnStartup(StartupEventArgs e)
    {
      base.OnStartup(e);
      ThemeManager.AddAccent("CustomBlue", new Uri("Blue.xaml", UriKind.RelativeOrAbsolute));
    }
  }
```

![2017-10-18_00h06_33](https://user-images.githubusercontent.com/658431/31691979-35a37388-b398-11e7-8d66-832f578703fa.png)

**Comment by JVimes** [comment]
Thanks! Sorry I overlooked [the doc page on that](http://mahapps.com/guides/styles.html#custom).

**Comment by punker76** [comment]
@JVimes np
