### ISSUE TITLE
HamburgerMenu PanePlacement="Right"

### ISSUE THREAD

**Issue by Stakhmi4** [MahApps/MahApps.Metro#3085]
By default HamburgerMenu looks like
![ham1](https://user-images.githubusercontent.com/10836966/31662224-36d47434-b346-11e7-93f7-7ade57a97425.jpg)

`<mah:HamburgerMenu PaneBackground="#FF444444" 
                           PanePlacement="Left"
                           DisplayMode="CompactOverlay"
                           ItemTemplate="{StaticResource HamburgerMenuItemTemplate}"
                           OptionsItemTemplate="{StaticResource HamburgerMenuItemTemplate}"
                           VerticalScrollBarOnLeftSide="False">
        </mah:HamburgerMenu>`

when i change PanePlacement=Right

![ham2](https://user-images.githubusercontent.com/10836966/31662558-8184a73c-b347-11e7-975d-4478cb7a39b5.jpg)

can i change position "HamburgerButton" (ball at screen) on Right?

- MahApps.Metro 1.6.0-alpha0150
- Windows 10
- Visual Studio 2015
- .NET Framework 4.5

**Comment by punker76** [comment]
@Stakhmi4 The `PanePlacement` handling will be improved in v1.6. But for the MenuItem templates you must handle this by yourself, like

```xaml
            <!--  This is the template for all menu items. In this sample we use the glyph items.  -->
            <DataTemplate x:Key="HamburgerMenuItem" DataType="{x:Type Controls:HamburgerMenuGlyphItem}">
                <DockPanel Height="48" LastChildFill="True">
                    <Grid x:Name="IconPart"
                          Width="48"
                          DockPanel.Dock="Left">
                        <Image Margin="12"
                               HorizontalAlignment="Center"
                               VerticalAlignment="Center"
                               Source="{Binding Glyph}"
                               Stretch="UniformToFill" />
                    </Grid>
                    <TextBlock x:Name="TextPart"
                               VerticalAlignment="Center"
                               FontSize="16"
                               Text="{Binding Label}" />
                </DockPanel>
                <DataTemplate.Triggers>
                    <DataTrigger Binding="{Binding RelativeSource={RelativeSource FindAncestor, AncestorType={x:Type Controls:HamburgerMenu}}, Path=PanePlacement}" Value="Right">
                        <Setter TargetName="IconPart" Property="DockPanel.Dock" Value="Right" />
                        <Setter TargetName="TextPart" Property="Margin" Value="8 0 0 0" />
                    </DataTrigger>
                </DataTemplate.Triggers>
            </DataTemplate>
```
