### ISSUE TITLE
Setting HamburgerMenu.SelectedIndex or Item cause the lost of its content

### ISSUE THREAD

**Issue by OrihuelaConde** [MahApps/MahApps.Metro#3089]
It could be my error but I need assistance.

## What steps will reproduce this issue?

When I set HamburgerMenu.SelectedIndex it lost its content.

### Expected outcome

I want to open the app and select the first item in the menu.

### Environment

- MahApps.Metro 1.5.0
- Windows 10 1703
- Visual Studio 2017 14.4
- .NET Framework 4.6.1

### Code

C#

public MainWindow()
        {
            InitializeComponent();
            HamburgerMenu.SelectedIndex = 0;
            MainFrame.Navigate(_ventasPage);
        }

XAML

<Grid>
        <Grid.Resources>
            <DataTemplate x:Key="MenuItemTemplate" DataType="{x:Type Controls:HamburgerMenuIconItem}">
                <Grid x:Name="RootGrid"
                      Height="48"
                      Background="Transparent"
                      Margin="0 2 0 2">
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="48" />
                        <ColumnDefinition />
                    </Grid.ColumnDefinitions>
                    <ContentControl Grid.Column="0"
                                    HorizontalAlignment="Center"
                                    VerticalAlignment="Center"
                                    Content="{Binding Icon}"
                                    Focusable="False"
                                    Foreground="White"/>
                    <TextBlock Grid.Column="1"
                               VerticalAlignment="Center"
                               FontSize="16"
                               Foreground="White"
                               Text="{Binding Label}" />
                </Grid>
            </DataTemplate>
        </Grid.Resources>

        <Controls:HamburgerMenu x:Name="HamburgerMenu" DisplayMode="CompactInline"
                                Foreground="White"
                                IsPaneOpen="False"
                                ItemTemplate="{StaticResource MenuItemTemplate}"
                                OptionsItemTemplate="{StaticResource MenuItemTemplate}"
                                PaneBackground="#FF444444"
                                ItemClick="HamburgerMenu_ItemClick">
            <Controls:HamburgerMenu.ItemsSource>
                <Controls:HamburgerMenuItemCollection>
                    <Controls:HamburgerMenuIconItem Icon="{iconPacks:PackIconModern Tag, Width=25, Height=25}" Label="Ventas" Tag="Ventas"/>
                    <Controls:HamburgerMenuIconItem Icon="{iconPacks:PackIconModern Settings, Width=25, Height=25}" Label="Administración" Tag="Administracion"/>
                    <Controls:HamburgerMenuIconItem Icon="{iconPacks:PackIconModern SocialDropbox, Width=25, Height=25}" Label="Stock" Tag="Stock"/>
                </Controls:HamburgerMenuItemCollection>
            </Controls:HamburgerMenu.ItemsSource>

            
            <Controls:HamburgerMenu.Content>
                <Grid>
                    <Frame x:Name="MainFrame" NavigationUIVisibility="Hidden" Navigating="MainFrame_Navigating" LoadCompleted="MainFrame_LoadCompleted"/>
                    <Controls:ProgressRing x:Name="Progreso"/>
                </Grid>
            </Controls:HamburgerMenu.Content>
        </Controls:HamburgerMenu>
    </Grid>

**Comment by dchaib** [comment]
I believe that's the same issue as the one here: https://stackoverflow.com/questions/45878823/conducting-mahapps-metro-hamburgermenu-with-caliburn-micro/. @punker76 is looking into it.
