### ISSUE TITLE
Use custom time difference between selecting minutes of Datetimepicker  

### ISSUE THREAD

**Issue by peererror** [MahApps/MahApps.Metro#3092]
Hi All
I am using DateTimepicker in my application .  I want to change the difference between minutes when selecting time currently it is using 1 minutes difference .I have seen the code I can see there is FiveMinuteKeys .But I don't know where to set it  in xaml

**Comment by punker76** [comment]
@peererror There are 3 different lists which you can use for the properties `SourceHours`, `SourceMinutes` and `SourceSeconds` like

```xaml
<Controls:DateTimePicker SourceMinutes="{x:Static Controls:TimePickerBase.IntervalOf5}" />
```

or `IntervalOf10` and `IntervalOf15`. They all type of `IEnumerable<int>`.
