### ISSUE TITLE
Namespace/Assembly Not Found when File Name is different after a Git Clone

### ISSUE THREAD

**Issue by DrakeOlson** [MahApps/MahApps.Metro#3094]
## What steps will reproduce this issue?

The problem is that I have a folder named "Test Name". When I push that to a remote repository (Visual Studio Online) and clone that into a different folder. You get a file named "Test%20Name". When you launch the cloned project and build you get a few errors saying can't find Assembly/Namespace for MahApps.Metro.

It seems that the package is looking for the same solution folder name or a solution folder name without "%20" in the name.

I fixed this by, changing the name to the original, launched, build and run.

### Expected outcome

I expect that the cloned project folder should run.

### Environment

- MahApps.Metro1.5.09
- Windows OS 10
- Visual Studio 2017 Community
- .NET Framework 4.5

I did try just about everything before finding this out. On the cloned version, I tried cleaning and rebuilding, reinstalling it, manually putting in the dlls, changing my .gitignore file to ignore everything.

**Comment by punker76** [comment]
@DrakeOlson I think this is not related to MahApps. It seems like it's more a problem from VS and msbuild

https://github.com/Microsoft/msbuild/issues/2178
