### ISSUE TITLE
SplitView: Cannot set properties in datatrigger

### ISSUE THREAD

**Issue by Stakhmi4** [MahApps/MahApps.Metro#3095]
Cannot set properties in datatrigger. 
<Setter Property="Margin" Value="20"/> - work correct. Another setters doesnot work.

     <ListBox ItemsSource="{Binding Path=Players}">
            <ListBox.ItemTemplate>
                <DataTemplate DataType="{x:Type ListBoxItem}">
                    <Grid>
                        <mah:SplitView x:Name="SplitView1" DisplayMode="Inline" IsPaneOpen="True" 
                                        CompactPaneLength="48"  OpenPaneLength="100" 
                                       Background="PaleVioletRed" PaneBackground="Blue"
                                        PanePlacement="Right">
                            <TextBlock Text="Main" HorizontalAlignment="Center" VerticalAlignment="Center"/>
                            <mah:SplitView.Pane>
                                <TextBlock Text="Pane"/>
                            </mah:SplitView.Pane>
                            <mah:SplitView.Style>
                                <Style TargetType="{x:Type mah:SplitView}">
                                    <Style.Triggers>
                                        <DataTrigger Binding="{Binding Path=IsSelected, RelativeSource={RelativeSource AncestorType=ListBoxItem, Mode=FindAncestor}}" Value="True">
                                            <Setter Property="IsPaneOpen" Value="True"/>
                                            <Setter Property="Background" Value="YellowGreen"/>
                                            <Setter Property="mah:SplitView.PaneBackground" Value="OrangeRed"/>
                                            <Setter Property="Margin" Value="20"/>
                                        </DataTrigger>
                                    </Style.Triggers>
                                </Style>
                            </mah:SplitView.Style>
                        </mah:SplitView>
                    </Grid>
                </DataTemplate>
            </ListBox.ItemTemplate>
        </ListBox>`

![1](https://user-images.githubusercontent.com/10836966/32095260-3e0ffe2c-bb0b-11e7-91ff-2b2fbe8094eb.png)

![2](https://user-images.githubusercontent.com/10836966/32095303-5ef1424a-bb0b-11e7-96b1-63ea2e374017.png)

### Environment

- MahApps.Metro 1.6.0-alpha0184
- Windows OS 10
- Visual Studio 2017
- .NET Framework 4.6.1

**Comment by punker76** [comment]
@Stakhmi4 I don't understand what you try to do. Why do you use a SplitView for every ListBoxItem inside a ListBox?
