### ISSUE TITLE
Hyperlink in Metro.Controls.Dialogs

### ISSUE THREAD

**Issue by Lumani123** [MahApps/MahApps.Metro#3096]
Hi there,

I've been trying to add a hyperlink (in message parameter) into a simple message show dialog `await this.ShowMessageAsync("This is the title", "Some message");` however, unable to, it keeps on returning a string.
I've tried hyperlink, button, uri, adding html tags in string, etc to get a hyperlink, but couldn't.
Is there a way for the message dialog to contain hyperlink? if not, is there any other dialog methods that enables?

Thanks

**Comment by punker76** [comment]
@Lumani123 The message dialog uses only a simple `TextBlock` to show the given string

https://github.com/MahApps/MahApps.Metro/blob/94d476bf498e5e34cb2f37e511a12993fb1d4134/src/MahApps.Metro/MahApps.Metro/Themes/Dialogs/MessageDialog.xaml#L18-L23

You can create your own message dialog. Here is a simple sample for a custom dialog https://github.com/MahApps/MahApps.Metro/blob/develop/src/MahApps.Metro.Samples/MahApps.Metro.Demo/MahApps.Metro.Demo.Shared/ExampleViews/CustomDialogExample.xaml

https://github.com/MahApps/MahApps.Metro/blob/94d476bf498e5e34cb2f37e511a12993fb1d4134/src/MahApps.Metro.Samples/MahApps.Metro.Demo/MahApps.Metro.Demo.Shared/MainWindowViewModel.cs#L458-L484

**Comment by Lumani123** [comment]
Thanks problem solved! :)

**Comment by saf-itpro** [comment]
@punker76 T[his link](https://github.com/MahApps/MahApps.Metro/blob/develop/src/MahApps.Metro.Samples/MahApps.Metro.Demo/MahApps.Metro.Demo.Shared/ExampleViews/CustomDialogExample.xaml) for the sample that you provided in your response above is broken. Could you please provide the new correct link? Thank you.
