### ISSUE TITLE
[Enhancement] Allow to change the Reveal Icon in the PasswordBox

### ISSUE THREAD

**Issue by gigios** [MahApps/MahApps.Metro#3105]
I searched in the repository if was present a solution on my problem.
I want to change the 'default' Reveal icon used in the PasswordBox with the 'standard' icon used in Windows 10.
From: ![immagine](https://user-images.githubusercontent.com/8749627/32945402-856fcd40-cb93-11e7-80ba-452db03cb113.png)
To: ![immagine](https://user-images.githubusercontent.com/8749627/32945648-866ebcfa-cb94-11e7-8cf9-4bcea5e99678.png)

It's clear that I can replace the PasswordBox style with a my custom style but, probably, the best solution could be the implementation of a new attached property in the PasswordBoxHelper in the similar way of the CapsLockIcon property.

Do you think that could be a good solution?

Thanks for the support

**Comment by punker76** [comment]
@gigios I will changed this

https://github.com/MahApps/MahApps.Metro/blob/94d476bf498e5e34cb2f37e511a12993fb1d4134/src/MahApps.Metro/MahApps.Metro/Styles/Controls.PasswordBox.xaml#L775

to `DynamicResource`, then you can override it with your own style.

https://github.com/MahApps/MahApps.Metro/blob/94d476bf498e5e34cb2f37e511a12993fb1d4134/src/MahApps.Metro/MahApps.Metro/Styles/Controls.PasswordBox.xaml#L39-L69

**Comment by gigios** [comment]
Ok! Thanks
In this way it's possible override a small portion of the 'original' style.
