### ISSUE TITLE
DateTimePicker selectedDate throws exception when selected date is null

### ISSUE THREAD

**Issue by Raghava56** [MahApps/MahApps.Metro#3112]
Hi,
Initially am initializing a **CustomValue** to null for showing **Watermark** then it is throwing exception i.e
**String was not recognized as a valid date**(converter failed to convert value)

```
<DateTimePicker Height="25"
   Width="200"
   Focusable="False"
   controls:TextBoxHelper.AutoWatermark="True"
   SelectedDate="{Binding CustomValue, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}"
   Margin="5,5"
   HorizontalAlignment="Stretch"/>
```

How to handle these exception or initially how to show watermark ?

Thanks,
Raghav

**Comment by punker76** [comment]
@Raghava56 Can you provide the stacktrace? What type is the CustomValue? Which version of MahApps are you use?

**Comment by Raghava56** [comment]
Hi,
datatype of custom value is string and the version is 1.5.0 stable.
Here is the stacktrace
Activated	Event	Time	Duration	Thread
	Program Output: 'SystemConvertConverter' converter failed to convert value '<null>' (type '<null>'); fallback value will be used, if available. BindingExpression:Path=CustomValue; DataItem='Properties' (HashCode=58427303); target element is 'DateTimePicker' (Name=''); target property is 'SelectedDate' (type 'Nullable`1') InvalidCastException:'System.InvalidCastException: Null object cannot be converted to a value type.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Windows.Data.BindingExpression.ConvertHelper(IValueConverter converter, Object value, Type targetType, Object parameter, CultureInfo culture)'	28.96s

**Comment by punker76** [comment]
@Raghava56 The SelectedDate property is a nullable DateTime ([link](https://msdn.microsoft.com/en-us/library/system.windows.controls.datepicker.selecteddate(v=vs.110).aspx)), so if you want to bind to a nullable string, you must use a converter which returns a valid value for SelectedDate.

**Comment by Raghava56** [comment]
@punker76  Then why it is throwing exception. if SelectedDate is a nullable type then it should accept null value.

**Comment by punker76** [comment]
@Raghava56 It's a nullable DateTime: `public Nullable<DateTime> SelectedDate { get; set; }`
