### ISSUE TITLE
In DateTimePicker we cant select previous date

### ISSUE THREAD

**Issue by bshemanth** [MahApps/MahApps.Metro#3113]
# PLEASE READ BEFORE POSTING AN ISSUE

This is a place for issues for MahApps itself. Questions are better asked in the [Gitter](https://gitter.im/MahApps/MahApps.Metro) room or at [stackoverflow](http://stackoverflow.com/questions/tagged/mahapps.metro).

### Seriously consider creating and linking to a test repo which takes absolutely minimal setup to illustrate how reproduce the problem.

My time is limited and .Zip files, code snippets and partial examples are often a time sink. GitHub also provides great communication and code review tools which can be utilised.

## HOW TO POST A GOOD SAMPLE.

Follow these guidelines and I will most likely look at the issue sooner:

* Post a full GitHub repository. Not a zip file, half baked snippet etc. If GitHub is new to you consider it a great learning opportunity and chance to get involved.
* The repository should have just ONE step max for me to get running, and that is "Restore NuGet Packages". If there are any other missing dependencies, or uncompiling features I will most likely move on to another issue.
* I'm not trying to be awkward. I'm just busy and I'm helping a lot of people, not just you, so help me out and I will help you out.

## What steps will reproduce this issue?

_Write problem description here_

### Expected outcome

_Write expected outcome here_

### Repo

_Link to the Repo_

### Environment

- MahApps.Metro __v?.?.?__
- Windows OS __??__
- Visual Studio __20xx__
- .NET Framework __?.?__

**Comment by bshemanth** [comment]
i have used DateTimePicker in one of the application, but i cant select previous date from calendar. here i tried to select novemeber 15 date but i am unable to do that.  How to achieve that
![datetimepicker](https://user-images.githubusercontent.com/5047071/33413458-9f85bb4e-d5b7-11e7-8a82-476cfab7dc17.PNG)

**Comment by punker76** [comment]
@bshemanth In this sample is a behavior attached which sets the selected date time every second. If you use this control in your app then it should work as expected.
