### ISSUE TITLE
Wait until dialog is shown

### ISSUE THREAD

**Issue by Symbai** [MahApps/MahApps.Metro#3115]
Hi,

is there a way to check if the progress dialog is fully shown? I call the ShowProgressAsync method before running code which will freeze the UI and all I get is the black hide out screen but the dialog itself shows up if my code has finished.

```
  private async void BtnTest(object sender, MouseButtonEventArgs e)
         {
 var controller = await this.ShowProgressAsync("Please wait...", "Progress message");
             controller.SetIndeterminate();
 //code which will lock UI
  await controller.CloseAsync();
         }
```

**Comment by punker76** [comment]
@Symbai It would be nice if you can create a sample (on GitHub) which shows this issue. Thx.
