### ISSUE TITLE
Suggestion: Hassle-free support for Windows 10 system accent color

### ISSUE THREAD

**Issue by lostmsu** [MahApps/MahApps.Metro#3116]
Problem is: default theme is basically blue, while in Windows 10 it would make sense to use user-chosen accent color.

Steps: pick any sample, check out titlebar color

Expected: titlebar color should be user's selected accent color (see Groove for example)
Actual: titlebar color is blue (or whatever theme's color used).

- MahApps.Metro 1.5.0
- Windows 10 Fall Creators
- .NET Framework 4.7

**Comment by MikeAtETI** [comment]
I've found this gets you close:

`  public static class ThemeHelper
    {
        public enum ThemeChoices
        {
            Light = 0,
            Dark = 1
        }

        private static ThemeChoices GetCurrentTheme()
        {
            using (RegistryKey rv = Registry.CurrentUser.OpenSubKey("Software\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize"))
            {
                if (rv != null)
                {
                    var value = rv.GetValue("AppsUseLightTheme");
                    if (value != null)
                    {
                        UInt32 lightTheme = (UInt32)(int)value;
                        if (lightTheme == 0)
                        {
                            return ThemeChoices.Dark;
                        }
                    }
                }
            }

            return ThemeChoices.Light;
        }

        private static int GetDiff(System.Windows.Media.Color clr, Accent item2)
        {
            System.Windows.Media.Color clr2 = (System.Windows.Media.Color)item2.Resources["AccentColor"];
            return GetDiff(System.Drawing.Color.FromArgb(clr.A, clr.R, clr.G, clr.B), System.Drawing.Color.FromArgb(clr2.A, clr2.R, clr2.G, clr2.B));
        }

        private static int GetDiff(System.Drawing.Color color, System.Drawing.Color baseColor)
        {
            int a = color.A - baseColor.A,
                r = color.R - baseColor.R,
                g = color.G - baseColor.G,
                b = color.B - baseColor.B;
            return a * a + r * r + g * g + b * b;
        }
        public static void ChooseTheme()
        {
            System.Windows.Media.Color clr = SystemParameters.WindowGlassColor;
            using (var rk = Registry.CurrentUser.OpenSubKey("Software\\Microsoft\\Windows\\DWM"))
            {
                var p = rk.GetValue("ColorizationColor", 0);
                if (p != null)
                {
                    UInt32 pp = (UInt32)(int)p;
                    if (pp > 0)
                    {
                        var bytes = BitConverter.GetBytes(pp);
                        clr = System.Windows.Media.Color.FromArgb(bytes[3], bytes[2], bytes[1], bytes[0]);
                    }
                }
            }

            Tuple<AppTheme, Accent> appStyle = ThemeManager.DetectAppStyle(Application.Current);
            Tuple<Accent, int> newAccent = new Tuple<Accent, int>(appStyle.Item2, GetDiff(clr, appStyle.Item2));
            foreach (var accent in ThemeManager.Accents)
            {
                int a = GetDiff(clr, accent);
                if (a < newAccent.Item2)
                {
                    newAccent = new Tuple<Accent, int>(accent, a);
                }
            }
            var application = Application.Current;
            ThemeManager.ChangeAppStyle(application, newAccent.Item1, (GetCurrentTheme() == ThemeChoices.Dark) ? ThemeManager.GetAppTheme("BaseDark") : ThemeManager.GetAppTheme("BaseLight"));
        }
    }`

**Comment by neilt6** [comment]
This should get you what you want, provided you're ok with [bringing in some UWP dependencies](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-enhance):

```
using MahApps.Metro;
using System;
using System.Windows;
using System.Windows.Media;
using Windows.UI.ViewManagement;

namespace Windows_10_Accent_Experiments
{
    public static class AccentHelper
    {
        #region Public Methods

        public static Accent GetSystemAccent(bool darkTheme = false)
        {
            //Get the system accent colors
            UISettings uiSettings = new UISettings();
            Color accentColor = ConvertColor(uiSettings.GetColorValue(UIColorType.Accent));
            Color accentColor2;
            Color accentColor3;
            Color accentColor4;
            if (!darkTheme)
            {
                accentColor2 = ConvertColor(uiSettings.GetColorValue(UIColorType.AccentLight1));
                accentColor3 = ConvertColor(uiSettings.GetColorValue(UIColorType.AccentLight2));
                accentColor4 = ConvertColor(uiSettings.GetColorValue(UIColorType.AccentLight3));
            }
            else
            {
                accentColor2 = ConvertColor(uiSettings.GetColorValue(UIColorType.AccentDark1));
                accentColor3 = ConvertColor(uiSettings.GetColorValue(UIColorType.AccentDark2));
                accentColor4 = ConvertColor(uiSettings.GetColorValue(UIColorType.AccentDark3));
            }

            //Generate a resource dictionary based on the specified color
            ResourceDictionary resourceDictionary = new ResourceDictionary();
            resourceDictionary.Add("HighlightColor", accentColor);
            resourceDictionary.Add("AccentBaseColor", accentColor);
            resourceDictionary.Add("AccentColor", accentColor);
            resourceDictionary.Add("AccentColor2", accentColor2);
            resourceDictionary.Add("AccentColor3", accentColor3);
            resourceDictionary.Add("AccentColor4", accentColor4);
            resourceDictionary.Add("HighlightBrush", GetSolidColorBrush((Color)resourceDictionary["HighlightColor"]));
            resourceDictionary.Add("AccentBaseColorBrush", GetSolidColorBrush((Color)resourceDictionary["AccentBaseColor"]));
            resourceDictionary.Add("AccentColorBrush", GetSolidColorBrush((Color)resourceDictionary["AccentColor"]));
            resourceDictionary.Add("AccentColorBrush2", GetSolidColorBrush((Color)resourceDictionary["AccentColor2"]));
            resourceDictionary.Add("AccentColorBrush3", GetSolidColorBrush((Color)resourceDictionary["AccentColor3"]));
            resourceDictionary.Add("AccentColorBrush4", GetSolidColorBrush((Color)resourceDictionary["AccentColor4"]));
            resourceDictionary.Add("WindowTitleColorBrush", GetSolidColorBrush((Color)resourceDictionary["AccentColor"]));
            resourceDictionary.Add("ProgressBrush", new LinearGradientBrush(
                new GradientStopCollection(new[]
                {
                    new GradientStop((Color)resourceDictionary["HighlightColor"], 0),
                    new GradientStop((Color)resourceDictionary["AccentColor3"], 1)
                }),
                startPoint: new Point(1.002, 0.5), endPoint: new Point(0.001, 0.5))
            );
            resourceDictionary.Add("CheckmarkFill", GetSolidColorBrush((Color)resourceDictionary["AccentColor"]));
            resourceDictionary.Add("RightArrowFill", GetSolidColorBrush((Color)resourceDictionary["AccentColor"]));
            resourceDictionary.Add("IdealForegroundColor", GetIdealForegroundColor(accentColor));
            resourceDictionary.Add("IdealForegroundColorBrush", GetSolidColorBrush((Color)resourceDictionary["IdealForegroundColor"]));
            resourceDictionary.Add("IdealForegroundDisabledBrush", GetSolidColorBrush((Color)resourceDictionary["IdealForegroundColor"], 0.4));
            resourceDictionary.Add("AccentSelectedColorBrush", GetSolidColorBrush((Color)resourceDictionary["IdealForegroundColor"]));
            resourceDictionary.Add("MetroDataGrid.HighlightBrush", GetSolidColorBrush((Color)resourceDictionary["AccentColor"]));
            resourceDictionary.Add("MetroDataGrid.HighlightTextBrush", GetSolidColorBrush((Color)resourceDictionary["IdealForegroundColor"]));
            resourceDictionary.Add("MetroDataGrid.MouseOverHighlightBrush", GetSolidColorBrush((Color)resourceDictionary["AccentColor3"]));
            resourceDictionary.Add("MetroDataGrid.FocusBorderBrush", GetSolidColorBrush((Color)resourceDictionary["AccentColor"]));
            resourceDictionary.Add("MetroDataGrid.InactiveSelectionHighlightBrush", GetSolidColorBrush((Color)resourceDictionary["AccentColor2"]));
            resourceDictionary.Add("MetroDataGrid.InactiveSelectionHighlightTextBrush", GetSolidColorBrush((Color)resourceDictionary["IdealForegroundColor"]));
            resourceDictionary.Add("MahApps.Metro.Brushes.ToggleSwitchButton.OnSwitchBrush.Win10", GetSolidColorBrush((Color)resourceDictionary["AccentColor"]));
            resourceDictionary.Add("MahApps.Metro.Brushes.ToggleSwitchButton.OnSwitchMouseOverBrush.Win10", GetSolidColorBrush((Color)resourceDictionary["AccentColor2"]));
            resourceDictionary.Add("MahApps.Metro.Brushes.ToggleSwitchButton.ThumbIndicatorCheckedBrush.Win10", GetSolidColorBrush((Color)resourceDictionary["IdealForegroundColor"]));

            //Create an accent based on the generated resource dictionary
            return ThemeManager.GetAccent(resourceDictionary);
        }

        #endregion

        #region Private Methods

        private static Color ConvertColor(Windows.UI.Color color)
        {
            //Convert the specified UWP color to a WPF color
            return Color.FromArgb(color.A, color.R, color.G, color.B);
        }

        private static Color GetIdealForegroundColor(Color bgColor)
        {
            //Determine the ideal foreground color
            int bgDelta = Convert.ToInt32((bgColor.R * 0.299) + (bgColor.G * 0.587) + (bgColor.B * 0.114));
            return ((255 - bgDelta) < 105) ? Colors.Black : Colors.White;
        }

        private static SolidColorBrush GetSolidColorBrush(Color color, double opacity = 1.0)
        {
            //Return a solid color brush with the specified color and opacity
            SolidColorBrush brush = new SolidColorBrush(color);
            brush.Opacity = opacity;
            brush.Freeze();
            return brush;
        }

        #endregion
    }
}
```
`UISettings` even has a convenient `ColorValuesChanged` event that's fired when the accent color changes. However, setting the accent this way will only work once right now due to the way `ThemeManager` handles runtime-generated accent resource dictionaries: #3227.

**Comment by lostmsu** [comment]
BTW, thank you guys for providing code samples. The most important idea of this bug though is that this should be the default behavior.

**Comment by evilbaschdi** [comment]
What's the current state her? With the latest preview version I still can change the former "accent" color to everything I want, but I'm not able to switch between "Light" and "Dark" anymore.

**Comment by batzen** [comment]
> but I'm not able to switch between "Light" and "Dark" anymore.

What do you mean exactly and what have you tried?

**Comment by evilbaschdi** [comment]
I've created a new dark theme - hopefully. (https://github.com/evilbaschdi/EvilBaschdi.CoreExtended/blob/feature/mahapps2/EvilBaschdi.TestUi.New/ThemeManagerHelper.cs)
switching the application to that theme the application stays "Light" (theme with white background).
In case of switching to "Dark.Cyan" everything works like expected. So the difference defining a new theme as "Light theme" and "Dark theme" for custom theme resources is missing currently that worked fine with version 1.x (https://github.com/evilbaschdi/EvilBaschdi.CoreExtended/blob/master/EvilBaschdi.CoreExtended/Metro/ThemeManagerHelper.cs)

**Comment by batzen** [comment]
Your theme generating code omits most of what's needed for a theme. Just calling your theme Dark or Light while omitting resource present in the shipped themes won't work.
I will discuss possible solutions for a built in theme generator with punker76 as soon as i have some free time to solve the request made by the issue reporter and to meet the need for an easy way to generate custom themes during runtime.
