### ISSUE TITLE
iconpack bug?

### ISSUE THREAD

**Issue by sergeypyrkin** [MahApps/MahApps.Metro#3117]
Don't show icon in VS constructor. When programm run icon work right!

xml constructor write: property "KIND" already reserved by "ControlzEx_PackIcon_1_0_208"

![xaml](https://user-images.githubusercontent.com/25052795/33711851-7b350d0e-db56-11e7-9516-2b10d2021f71.png)

**Comment by punker76** [comment]
@sergeypyrkin It's a known issue with the VS Designer and the MarkupExtensions. This will be fixed with https://github.com/MahApps/MahApps.Metro.IconPacks/pull/60
