### ISSUE TITLE
WPF：A subset of element binding values can not be tied up

### ISSUE THREAD

**Issue by OKCLi** [MahApps/MahApps.Metro#3124]
How to bind textBox2 and textBox3?
public partial class MainWindow : Window
    {
        List<Country> countryList = new List<Country>()
        {
            new Country()
            {
                Name ="China",
                ProvinceList =new List<Province>()
                {
                    new Province()
                    {
                        Name="广东",
                        CityList=new List<City>()
                        {
                            new City() {Name="佛山" },
                            new City() {Name="广州" },
                            new City() {Name="茂名" },
                            new City() {Name="深圳" },
                        }
                    },
                    new Province()
                    {
                        Name="四川",
                        CityList=new List<City>()
                        {
                            new City() {Name="成都" },
                            new City() {Name="自贡" },
                            new City() {Name="攀枝花" },
                            new City() {Name="宜宾" },
                        }
                    }
                }
            },

            new Country() {Name="USA",ProvinceList=new List<Province>()
            {
                new Province()
                {
                    Name="LA",
                    CityList=new List<City>()
                    {
                        new City() {Name="AA" },
                        new City() {Name="BB" },
                        new City() {Name="CC" },
                        new City() {Name="DD" },
                    }
                },
            } },
        };
        public MainWindow()
        {
            InitializeComponent();
            textBox1.SetBinding(TextBox.TextProperty, new Binding("/Name") { Source = countryList });
            textBox2.SetBinding(TextBox.TextProperty, new Binding("/ProvinceList.Name") { Source = countryList});
            textBox3.SetBinding(TextBox.TextProperty, new Binding("/Provinces/CityList.Name") { Source = countryList});
        }
    }
}

**Comment by punker76** [comment]
@OKCLi Here are some links for you where you can learn something about binding:


http://www.wpf-tutorial.com/data-binding/introduction/
https://www.codeproject.com/Articles/29054/WPF-Data-Binding-Part
https://docs.microsoft.com/en-us/dotnet/framework/wpf/data/data-binding-wpf
https://wpftutorial.net/Databinding.html
https://www.wpftutorial.net/DataBindingOverview.html
