### ISSUE TITLE
TimePicker issues

### ISSUE THREAD

**Issue by avechuche** [MahApps/MahApps.Metro#3128]
Hello, I found two problems in the TimePicker control
1) It is possible to put in the TimePicker, the "IsReadOnly" mode, but let me select the time, but not write it?

I try with this (not work)
```
<mahApps:TimePicker.Resources>
	<Style TargetType="DatePickerTextBox">
		<Setter Property="IsReadOnly"
				Value="True" />
	</Style>
</mahApps:TimePicker.Resources>
```
and  (not work)
```
<mahApps:TimePicker.Style>
	<Style TargetType="{x:Type mahApps:TimePicker}"
		   BasedOn="{StaticResource {x:Type mahApps:TimePicker}}">
		<Setter Property="IsEnabled"
				Value="False" />
		<Style.Triggers>
			<Trigger Property="IsDropDownOpen"
					 Value="True">
				<Setter Property="IsEnabled"
						Value="True" />
			</Trigger>
		</Style.Triggers>
	</Style>
</mahApps:TimePicker.Style>
```
The latter causes the clock (icon) to disappear in order to select the time

and 2 - The number 12 is first in the list
![1](https://user-images.githubusercontent.com/11781418/34123427-3d2bdd06-e40e-11e7-9a84-fa84cdd77ea8.png)

**Comment by punker76** [comment]
@avechuche Select a time or date in read only mode makes IMO no sense. The second one is a feature for the 12 am/pm hours selection:

https://github.com/MahApps/MahApps.Metro/blob/478b5e28d3bd53a2bdad2ba204290032d60c64fe/src/MahApps.Metro/MahApps.Metro.Shared/Controls/Helper/AmPmComparer.cs#L5-L13
