### ISSUE TITLE
TextBox clear text button font family being inherited.

### ISSUE THREAD

**Issue by MajedDH** [MahApps/MahApps.Metro#3130]
In my project I changed the default font of the project by setting:
```
<Style TargetType="TextBlock" BasedOn="{StaticResource MetroTextBlock}">
    <Setter Property="FontFamily" Value="somefont"  />
</Style>
```
and in text box style:
```
<Style TargetType="TextBox" BasedOn="{StaticResource MetroTextBox}">
    <Setter Property="controls:TextBoxHelper.ButtonFontFamily" Value="Marlett" />
</Style>
```
but the latter style has no effect and still so I'm getting the letter 'r' instead of the X on the clear text button

Is this the expected behavior? Or I am the one doing it wrong?

**Comment by punker76** [comment]
@MajedDH Setting a style for TextBlock in App.xaml which affects all of these is NOT recommended. You will always get such nasty side effects.

https://github.com/MahApps/MahApps.Metro/blob/9071379b5e17f05a3b41262998858497990b258f/src/MahApps.Metro/MahApps.Metro/Styles/Controls.TextBlock.xaml#L4-L6

FontSize, FontFamily, etc. should always be set only on the base controls which uses TextBlocks inside like TextBox or other ones.
