### ISSUE TITLE
Strange behaviour when calling ChangeAppStyle() with unregistered accents

### ISSUE THREAD

**Issue by mowmoth** [MahApps/MahApps.Metro#3132]
- MahApps.Metro v1.6.0-alpha
- .NET Framework 4.5

Calling `ChangeAppStyle()` with an accent (haven't tested for themes) that is not registered in the App.xaml works fine the first time. The second time however you get a NullRefException on the old accent's `Accent.Resources.Source` as the property wasn't set since it's not registered in the App.xaml. Took me quiet a while to figure this out, since it always worked the first time without fail. I (now) get that you're supposed to register what you're planning on using, but a more telling exception would have been helpful or even better: enforce that the source is set in the new accent when calling the method.

**Comment by punker76** [comment]
@mowmoth Isn't the explanation at the [main documentation](http://mahapps.com/guides/quick-start.html#using-built-in-styles) enought? If you want to change the Accent color or the theme then it's necessary to add it at the App.xaml.
