### ISSUE TITLE
Checkbox colors on dark theme arent good

### ISSUE THREAD

**Issue by Symbai** [MahApps/MahApps.Metro#3136]
Below is a screenshot of the demo showing the default white theme and dark puple. As you can see the checkbox on white theme is okay but on dark theme hardly seeable because the purple color is too dark. Same problem with lots of other colors on dark theme. I don't think this issue needs a sample as you can reproduce this in a second on the demo app.

![theme](https://user-images.githubusercontent.com/14368203/34463604-72e13e70-ee61-11e7-8ebd-64a015f4aa62.jpg)

//edit: For some reasons I've noticed the color on checkboxes are different than the color used on other controls:

![theme2](https://user-images.githubusercontent.com/14368203/34463629-b48dd684-ee62-11e7-8490-128adaf13813.jpg)

**Comment by punker76** [comment]
@Symbai Yes, the modern Win 10 checkbox and radiobox styles invert the brushes. I must agree it looks with some accent brushes not so good. But I think we can not do this in 1.6 cause it's a bigger visual breaking change.

![2018-01-05_13h39_27](https://user-images.githubusercontent.com/658431/34609728-211b5ee8-f21e-11e7-9ed0-faa9c1300796.png)
![2018-01-05_13h39_33](https://user-images.githubusercontent.com/658431/34609729-228441aa-f21e-11e7-84f0-c597d0457430.png)

/cc @thoemmi

**Comment by thoemmi** [comment]
I agree with @punker76 . As far as I can see 1.6 is almost finished.

**Comment by amkuchta** [comment]
@punker76 @Symbai @thoemmi this might also be a good time to adjust how the various accent colors are produced.  Currently, it looks like the same color is utilized, but the alpha is adjusted to let the background bleed through.  I think that a better way to handle this would be to utilize a tool like [Coolors.co](https://coolors.co) to define a base color, then get alternative shades for it.

**Comment by Symbai** [comment]
Downloaded the latest demo but it looks like there hasn't been any progress on this?
