### ISSUE TITLE
Can System.Windows.Interactivity.dll be a package dependency?

### ISSUE THREAD

**Issue by andrew-stephens** [MahApps/MahApps.Metro#3139]
The MahApps NuGet package includes System.Windows.Interactivity.dll (v4.5.0.0), but I reference another NuGet package (Prism v4.1) that also includes S.W.I.dll, but v4.0.0.0. In my solution I have several projects that reference both packages, and noticed that some projects reference S.W.I.dll from the MahApps package while others reference the one from the Prism package. (I assume this inconsistency is down to the order in which the packages were installed).

Depending on which project(s) I make a code change to (and therefore get built), either v4.0 or v4.5 of S.W.I.dll would be copied to the build output folder. On the occasions where v4.0 was copied I see a runtime error from MahApps ("Could not load file or assembly System.Windows.Interactivity ... 4.5.0.0"). I then have to "touch" one of the other projects and build again, to get v4.5.0.0 into the build output folder.

I ended up "fixing" the problem by upgrading to Prism 6, as this package no longer includes S.W.I.dll, so avoids clashing with MahApps. I realise this is a bit of an "edge case" but wouldn't it be safer for MahApps to reference a "System.Windows.Interactivity" NuGet package, rather than include the DLL in its package?

**Comment by thoemmi** [comment]
>  I realise this is a bit of an "edge case" but wouldn't it be safer for MahApps to reference a "System.Windows.Interactivity" NuGet package, rather than include the DLL in its package?

That's the exact problem: there is no **official** NuGet package for *System.Windows.Interactivity*. Just [search of it in the NuGet Gallery](https://www.nuget.org/packages?q=System.Windows.Interactivity), and you will find lots of packages, but none of those is official.
