### ISSUE TITLE
Flyout's header not binding to XmlProvider

### ISSUE THREAD

**Issue by Pekshev** [MahApps/MahApps.Metro#3143]
I'm use XmlProvider for localization of my app. All good but flyout's header not binding:

![screenshot_1](https://user-images.githubusercontent.com/12638819/34792043-e5b0e236-f657-11e7-8265-d4a8d9db92fb.png)
and result:

![image](https://user-images.githubusercontent.com/12638819/34792119-17258358-f658-11e7-947d-786caad7db94.png)

**Comment by punker76** [comment]
@Pekshev What version of MahApps do you use?

**Comment by Pekshev** [comment]
1.5.0.23

**Comment by Pekshev** [comment]
I found the solution - I set the header in the code when the window is loaded. But I would like to do this in the xaml

**Comment by punker76** [comment]
@Pekshev Can you create a short sample on GitHub? With one Flyout and such a XmlProvider?

**Comment by Pekshev** [comment]
Yes =)
https://github.com/Pekshev/MahappsFlyoutHeaderProblem

**Comment by punker76** [comment]
@Pekshev Thank you for this sample! 👏  It helps me to find the bug :-D

![image](https://user-images.githubusercontent.com/658431/34817012-fae54ed0-f6b6-11e7-87ba-9248496f5204.png)

This fix will be available in 1.6.0 (and next pre-release)

**Comment by Pekshev** [comment]
I will not create a new issue.
There is also a bug - when binding is not set the upper case for text in many controls. The simplest example is the groupBox.

![screenshot_9](https://user-images.githubusercontent.com/12638819/34817859-30aa94b8-f6ca-11e7-8ebe-d2fa4c35352e.png)

I updated the demo project

**Comment by punker76** [comment]
@Pekshev the same happens at the Buttons (these captions should be also upper cased). The problem here is, that the ToUpper (and ToLower) converters gets a XmlNode and not a string through the binding (Header or Content).

https://github.com/MahApps/MahApps.Metro/blob/1f052fd898d1ba7c692b78913525863ff096c69f/src/MahApps.Metro/MahApps.Metro.Shared/Converters/ToUpperConverter.cs#L26-L27

You can create a simple converter to solve this

```
    public class XmlNodeToTextConverter : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            var xmlNode = value as XmlNode;
            if (xmlNode != null)
            {
                value = xmlNode.InnerText;
            }
            return value;
        }

        public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            return Binding.DoNothing;
        }
    }
```
