### ISSUE TITLE
Additional colors

### ISSUE THREAD

**Issue by Pekshev** [MahApps/MahApps.Metro#3154]
There are very lacking additional colors (brushes) that would be used as "Warning", "Success", "Error" and at the same time harmoniously combined with themes and accent colors. Well, at least with the themes

**Comment by punker76** [comment]
@Pekshev I think the exisiting brushes (accents and theme) are enough as base starting point. If you need more brushes then you can create your own brushes. It's also possible to create own accent and theme resources which contains your custom brushes...
