### ISSUE TITLE
Bug On NumericUpDown

### ISSUE THREAD

**Issue by ikeas68** [MahApps/MahApps.Metro#3166]
i have discover a bug in numericUpDown
if i have a string format like this
StringFormat="0.###"
and set a value to 0.33333333333
the vaue is truncat to 0.333

if i want to preserv initial value it's not possible

**Comment by punker76** [comment]
@ikeas68 Can you create a short sample? thx!

**Comment by ikeas68** [comment]
a complete project ?

**Comment by punker76** [comment]
@ikeas68 Yes. Short and simple as possible.

**Comment by ikeas68** [comment]
ok tomorrow morning

**Comment by ikeas68** [comment]
i check with version 1.4.1 and 1.5 and in the sample i have no problem
i check directly in my software

**Comment by ikeas68** [comment]
it's seem to be a problem with lost focus 
the binded value is updated with string format when focus lost
see my project
- set value in numeric up down to 5.33333333333
- click on bbutton

**Comment by ikeas68** [comment]
set value in numeric up down to 5.33333333333
click on bbutton
click on button
set the cursor on numeric up down
click on button

**Comment by ikeas68** [comment]
[MAHapp numeric.zip](https://github.com/MahApps/MahApps.Metro/files/1654763/MAHapp.numeric.zip)

**Comment by ikeas68** [comment]
after discuss whith my friend the better solution is to re-set the original value in numeric updow when the component get focus

**Comment by ikeas68** [comment]
thanks
