### ISSUE TITLE
ComboBox item alignment

### ISSUE THREAD

**Issue by Nuklon** [MahApps/MahApps.Metro#3167]
A minor issue, currently the combobox child items are not aligned according to their selected 'parent'. It'd be nice if these could have the same margin at the left side. This looks better and is easier to read for very wide characters (as they currently run almost against the side line).

![image](https://user-images.githubusercontent.com/7643972/35222642-e3001fb8-ff7e-11e7-88e6-ffcda31494c6.png)

(I looked in the xaml but I'm not sure what to edit for this)

**Comment by punker76** [comment]
@Nuklon I think this is more a subjective perceive and can be solved by the users itself. e.g.

```xaml
<Style TargetType="{x:Type ComboBox}" BasedOn="{StaticResource MetroComboBox}">
    <Setter Property="ItemContainerStyle">
        <Setter.Value>
            <Style TargetType="{x:Type ComboBoxItem}" BasedOn="{StaticResource MetroComboBoxItem}">
                <Setter Property="Padding" Value="5" />
            </Style>
        </Setter.Value>
    </Setter>
</Style>
```

**Comment by Nuklon** [comment]
Great, thank you, I wasn't sure what was needed for this, I'll test that out.
