### ISSUE TITLE
NumericUpDown.StringFormat not working via Code behind

### ISSUE THREAD

**Issue by skelvir** [MahApps/MahApps.Metro#3168]
## What steps will reproduce this issue?

NumericUpDown.StringFormat is working fine if declared in XAML, but if you try to change it via Code behind, it will cause an exception.

### Expected outcome

Changing StringFormat should update the content while preserving the Value

### Repo

https://github.com/skelvir/Wpf_NumericUDissue.git

### Environment

- MahApps.Metro 1.5.0.23
- Windows 7 64-bit
- Visual Studio 2017 Community
- .NET Framework 4.5

**Comment by punker76** [comment]
@skelvir Thank you for the sample! 👍  This issue is already fixed and will be available in v1.6 (or via appveyor nightly build).

PS: Why do you want to change the format on any value change?

**Comment by skelvir** [comment]
@punker76 I do not intend to change on any value change, I just used that as a quick sample. 
In reality I only need to change once during initialization.
