### ISSUE TITLE
HamburgerMenuIconItem ToolTip

### ISSUE THREAD

**Issue by amkuchta** [MahApps/MahApps.Metro#3169]
Currently, there is no way to utilize a `ToolTip` with a `HamburgerMenuIconItem`.  I think that this should be an out-of-the-box feature, as it would be nice for users to simply be able to get an icon's name by hovering as opposed to having to open the `HamburgerMenu`

### Environment

- MahApps.Metro __v1.6.0.231__
- Windows OS __10__
- Visual Studio __2017__
- .NET Framework __4.5.2__

**Comment by punker76** [comment]
@amkuchta This is already possible with minor code change.
I don't know if there is a benefit to add this `ToolTip` property to the base class, cause the user must still implement their own `DataTemplate` for the MenuItem, with or without the extra property.

```csharp
    public class CustomHamburgerMenuIconItem : HamburgerMenuIconItem
    {
        public static readonly DependencyProperty ToolTipProperty
            = DependencyProperty.Register("ToolTip",
                typeof(object),
                typeof(CustomHamburgerMenuIconItem),
                new PropertyMetadata(null));

        public object ToolTip
        {
            get { return (object)GetValue(ToolTipProperty); }
            set { SetValue(ToolTipProperty, value); }
        }
    }
```

```xaml
            <DataTemplate x:Key="MenuItemTemplate" DataType="{x:Type local:CustomHamburgerMenuIconItem}">
                <Grid x:Name="RootGrid"
                      Height="48"
                      Background="Transparent">
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="48" />
                        <ColumnDefinition />
                    </Grid.ColumnDefinitions>
                    <ContentControl Grid.Column="0"
                                    HorizontalAlignment="Center"
                                    VerticalAlignment="Center"
                                    Content="{Binding Icon}"
                                    Focusable="False"
                                    Foreground="White" />
                    <TextBlock Grid.Column="1"
                               VerticalAlignment="Center"
                               FontSize="16"
                               Foreground="White"
                               Text="{Binding Label}" />
                </Grid>
                <DataTemplate.Triggers>
                    <DataTrigger Binding="{Binding RelativeSource={RelativeSource FindAncestor, AncestorType={x:Type controls:HamburgerMenu}}, Path=IsPaneOpen}" Value="False">
                        <Setter TargetName="RootGrid" Property="ToolTip" Value="{Binding ToolTip, Mode=OneWay}" />
                    </DataTrigger>
                </DataTemplate.Triggers>
            </DataTemplate>
```

https://github.com/punker76/code-samples/blob/687dca0055fb4d26275ce11c881fd3167e542132/MahAppsMetroHamburgerMenu/HamburgerMenuApp.V3/CustomHamburgerMenuIconItem.cs#L7-L20

https://github.com/punker76/code-samples/blob/687dca0055fb4d26275ce11c881fd3167e542132/MahAppsMetroHamburgerMenu/HamburgerMenuApp.V3/MainWindow.xaml#L30-L55

**Comment by amkuchta** [comment]
@punker76 wouldn't it make more sense to have `ToolTip` be offered directly under `HamburgerMenuIconItem` as opposed to having users roll their own class on top of it?  I understand having to implement their own `DataTemplate`, but this seems like an easy offering to throw in that can be a solid (optional) feature, should users decide to utilize it.
