### ISSUE TITLE
Enhancement request? - Disable the MetroWindow while a Dialog mode is active.

### ISSUE THREAD

**Issue by AgentFire** [MahApps/MahApps.Metro#3173]
When a "Delete something" button is pressed, simply calling the:

    if (await this.ShowMessageAsync("Delete?", $"You sure to delete // etc.

is enough only if it is clicked by mouse.

If I select a button and press Enter twice, then TWO dialogs will be opened - one after another.
The dialog mode (`ShowMessageAsync` etc) are supposed to disable input while active, so I propose setting `IsEnabled=false`  temporarily while a dialog mode is active to eliminate undesired keyboard inputs on the main window.

**Comment by pfattisc** [comment]
I encountered the same issue,
I came up with an extension method that prevents command execution while a command's execute method is running.

```
public static ICommand DiscardReentrantCalls(this ICommand command)   
 {
      ICommand decoratedCommand;
      bool discardExecution = false;

      decoratedCommand = new ParameterlessRelayCommand(
        () =>
        {
          if (!discardExecution)
          {
            discardExecution = true;
            try
            {
              command.Execute(null);
            }
            finally
            {
              discardExecution = false;
            }
          }
        }, () => command.CanExecute(null));
      return decoratedCommand;
    }
```

**Comment by punker76** [comment]
@AgentFire Another solution is to disable the button

```csharp
private async void Button_OnClick(object sender, RoutedEventArgs e)
{
    if (e.OriginalSource is Button button)
    {
        // This dialog should be displayed only once!
        // So disable the button while the dialog is open.
        button.IsEnabled = false;
        await this.ShowMessageAsync("Delete?", $"You sure to delete.....).ConfigureAwait(true);
        button.IsEnabled = true;
    }
}
```

**Comment by AgentFire** [comment]
Yeah, you disable one button, and the focus simply jumps to the next element... which would be some other button, no doubt.
