### ISSUE TITLE
How to set the masquerade in "ShowInputAsync"?

### ISSUE THREAD

**Issue by matmiranda** [MahApps/MahApps.Metro#3174]
Example:

```
var mySettings = new MetroDialogSettings
{
    Mask = "&&&&-&&&&-&&&&-&&&&"
};

var key = await this.ShowInputAsync("Hello!", "Type license key:", mySettings);
```

Is it possible to set the mask in the textbox?

**Comment by Daniel-Cong** [comment]
Also it will be great if we can put default value inside the Input Box.
Currently, we can only display a title, a prompt, and an empty Input Box.
