### ISSUE TITLE
[Enhancement] Selected TabItem Underline Width

### ISSUE THREAD

**Issue by amkuchta** [MahApps/MahApps.Metro#3179]
A tiny and purely stylistic enhancement, but would there be any interest in updating the `Underline` of the selected `TabItem` so that it was the width of the Header text, not the width of the entire tab?  It's a small change, but one that makes the application look more modern.  If interested, I can complete a quick PR - I have already modified the template on my end to make the update, as seen below:

## Before:
![tabitembefore](https://user-images.githubusercontent.com/6255186/35403209-0cc2efec-01cd-11e8-9001-6ec3bb0cd391.jpg)

## After:
![tabitemafter](https://user-images.githubusercontent.com/6255186/35403226-18dd96c4-01cd-11e8-8845-c63fe6514881.jpg)

@punker76, I'll leave this one up to you - I don't want to waste your time with a PR if you don't want the change.  As a side note, is there a way to change the `FontFamily` of just the `TabItem`'s header?

**Comment by amkuchta** [comment]
After looking, this breaks the style for `TabPanel` - I'll go ahead and close this.

**Comment by Brains** [comment]
@amkuchta Maybe @punker76 didn't want it but I want.
This is what I have:
![image](https://user-images.githubusercontent.com/5301844/57569007-008f8480-73f8-11e9-9636-852e4d60163c.png)
and this is what I need:
![image](https://user-images.githubusercontent.com/5301844/57569028-46e4e380-73f8-11e9-886f-da6bc6abb246.png)

Can you share the code here just for me (and somebody else found this topic in future)?

**Comment by Brains** [comment]
I tried that before discovered `TabControlHelper`
But sadly, it underlines the icon too.

```xaml
<TabControl.Resources>
    <ResourceDictionary>
        <Style TargetType="TabItem" BasedOn="{StaticResource {x:Type TabItem}}">
            <Style.Triggers>
                
                <Trigger Property="IsSelected" Value="True">
                    <Setter Property="BorderBrush" Value="{StaticResource AccentColorBrush}"/>
                    <Setter Property="BorderThickness" Value="0,0,0,2"/>
                </Trigger>                        
                
                <Trigger Property="IsMouseOver" Value="True">
                    <Setter Property="RenderTransformOrigin" Value=".5,.5" />
                    <Setter Property="RenderTransform">
                        <Setter.Value>
                            <ScaleTransform ScaleX="1.1" ScaleY="1.1"/>
                        </Setter.Value>
                    </Setter>
                </Trigger>
            
            </Style.Triggers>
        </Style>
    </ResourceDictionary>
</TabControl.Resources>
```
