### ISSUE TITLE
MouseOver Rotation (customized style) cannot be triggered

### ISSUE THREAD

**Issue by ShannonZ** [MahApps/MahApps.Metro#3187]
## A MouseOver rotation was made in ButtonStyle.xaml  BUT NEVER Triggered.

_The style xaml was produced by blend._

### Repo

_https://github.com/ShannonZ/playground_

### Environment

- MahApps.Metro __v1.6__
- Windows OS __7 x64__
- Visual Studio __2017__
- .NET Framework __4.7__

**Comment by punker76** [comment]
@ShannonZ This is not related to MahApps. It's more an issue with your defined visual states. Here is a sample which should work. Please note, you must define the `Normal` state too, cause without the `MouseOver` is only triggered once.

```xaml
<VisualStateManager.VisualStateGroups>
    <VisualStateGroup x:Name="CommonStates">
        <VisualState x:Name="Normal" />
        <VisualState x:Name="MouseOver">
            <Storyboard>
                <DoubleAnimationUsingKeyFrames Storyboard.TargetProperty="(UIElement.RenderTransform).(TransformGroup.Children)[2].(RotateTransform.Angle)" Storyboard.TargetName="PART_ContentPresenter">
                    <EasingDoubleKeyFrame KeyTime="0:0:1" Value="360">
                        <EasingDoubleKeyFrame.EasingFunction>
                            <SineEase EasingMode="EaseInOut"/>
                        </EasingDoubleKeyFrame.EasingFunction>
                    </EasingDoubleKeyFrame>
                </DoubleAnimationUsingKeyFrames>
            </Storyboard>
        </VisualState>
    </VisualStateGroup>
</VisualStateManager.VisualStateGroups>
```

![visualstate_mouseover](https://user-images.githubusercontent.com/658431/36018294-86c59b28-0d7b-11e8-9b3c-bef0bfa49b41.gif)

**Comment by ShannonZ** [comment]
The code for style( including VisualStates) was generated using VS Blend 2017. So I think there exist some conflicts between Mahapps.Metro and the customized style.

**Comment by ShannonZ** [comment]
It's wired that the mouse over animation works well in preview mode of VS blend 2017, but not works after compiling.
