### ISSUE TITLE
modal Flyout not pinned allow controls in the backgroud to receive MouseUp event

### ISSUE THREAD

**Issue by pfigueiredo** [MahApps/MahApps.Metro#3188]
I have a Flyout with IsModal="True" IsPinned="False" when I click outside the flyout to close it the controls in the background receive the MouseUp Event.

- MahApps.Metro 1.5.0
- Windows OS 10
- Visual Studio 2017 Community Edition
- .NET Framework 4.5.2

**Comment by punker76** [comment]
@pfigueiredo I can't reproduce this with the current source. So can you please create a short sample which shows your issue with that? Thx!
