### ISSUE TITLE
Support for TextBoxHelper.ButtonCommand in ComboBox

### ISSUE THREAD

**Issue by JobaDiniz** [MahApps/MahApps.Metro#3191]
ComboBox [style](https://github.com/MahApps/MahApps.Metro/blob/develop/src/MahApps.Metro/MahApps.Metro/Styles/Controls.ComboBox.xaml#L266) does not support `TextBoxHelper.ButtonCommand`.

In order to support it, two things have to happen:
- `PART_EditableTextBox` have to bind to _ButtonCommand_: `Controls:TextBoxHelper.ButtonCommand="{TemplateBinding Controls:TextBoxHelper.ButtonCommand}"`
- `PART_EditableTextBox` must have the `MetroButtonTextBox` style, as reported [here](https://github.com/MahApps/MahApps.Metro/issues/2597#issuecomment-236224606).
  - For this, we could expose a new dependency property for `ComboBox` in order to be able to override `PART_EditableTextBox` style.

Wouldn't this make sense?

**Comment by punker76** [comment]
@JobaDiniz I set this to `on hold`, cause I plan to re-write this with a `TriggerAction` which can be used then for TextBox, ComboBox, PasswordBox, etc...
