### ISSUE TITLE
Wrong behavior with ShowTitleBar="False" in XAML control metrowindow settings

### ISSUE THREAD

**Issue by whentotrade** [MahApps/MahApps.Metro#3192]
Setting ShowTitleBar to "False" in the controls metrowindow xaml results in the still shown title bar in the window. The dynamic binding in the demo works, but if it is set to "false" in the xaml control definition, the title bar is still there.

## What steps will reproduce this issue?
You can check by replacing the MahApps.Metro.Demo.NET45

_from_
```
<Controls:MetroWindow x:Class="MetroDemo.MainWindow"
                    ....
                      ShowTitleBar="ShowTitleBar="{Binding ShowMyTitleBar, Mode=OneWay}"
```

_to_
```
<Controls:MetroWindow x:Class="MetroDemo.MainWindow"
                    ....
                      ShowTitleBar="False"
```

### Expected outcome

TitleBar should be hidden when set to False in XAML definition.

### Environment
- MahApps.Metro v1.6
- Windows OS 10
- Visual Studio 2017
- .NET Framework 4.61

**Comment by Pekshev** [comment]
I did a demo project and bound **ShowTitleBar** to the ViewModel property. As in your demo project. However, it also does not work - the titlebar does not collapse, but hides
```xml
<mah:MetroWindow x:Class="WpfApp3.MainWindow"
                 xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                 xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                 xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
                 xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
                 xmlns:local="clr-namespace:WpfApp3"
                 xmlns:mah="http://metro.mahapps.com/winfx/xaml/controls"
                 mc:Ignorable="d" SaveWindowPosition="True"
                 Height="250" Width="525"
                 ShowTitleBar="{Binding Path=ShowTitleBar, Mode=OneWay}" 
                 Loaded="MainWindow_OnLoaded">
    <Window.Resources>
        <ResourceDictionary>
        <ResourceDictionary.MergedDictionaries>
            <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
            <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
            <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Colors.xaml" />
            <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/Blue.xaml" />
            <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/BaseLight.xaml" />
            <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/FlatSlider.xaml"/>
        </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Window.Resources>
    <Window.DataContext>
        <local:ViewModel></local:ViewModel>
    </Window.DataContext>
    <Grid>
        <TextBlock FontSize="16" Text="MY TITLE" 
                   PreviewMouseLeftButtonDown="UIElement_OnPreviewMouseLeftButtonDown"></TextBlock>
        <CheckBox Content="show title bar" IsChecked="{Binding Path=ShowTitleBar, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}"
                  HorizontalAlignment="Center" VerticalAlignment="Bottom" Margin="5"></CheckBox>
        <Button VerticalAlignment="Center" HorizontalAlignment="Center"
                Content="Show child window" Click="ButtonBase_OnClick"></Button>
    </Grid>
</mah:MetroWindow>
```
ViewModel:
```csharp
using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace WpfApp3
{
    public class ViewModel : INotifyPropertyChanged
    {
        private bool _showTitleBar = true;
        public bool ShowTitleBar
        {
            get => _showTitleBar;
            set
            {
                _showTitleBar = value;
                OnPropertyChanged();
            }
        }


        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    }
}
```
![screenshot_3](https://user-images.githubusercontent.com/12638819/36449950-78492684-169d-11e8-87e7-e927643e1c5e.png)
![screenshot_4](https://user-images.githubusercontent.com/12638819/36449959-7bb797ec-169d-11e8-99dd-d74fb07c5124.png)

**Comment by punker76** [comment]
@whentotrade @Pekshev I'm working on this...

**Comment by Pekshev** [comment]
Suddenly it will help: in your demo project, if you first use item **Toggle Fillscreen (no taskbar, window style = none)**, then the titlebar also stops disabling

**Comment by wojtpl2** [comment]
There is a workaround?

**Comment by lagwagon667** [comment]
Maybe #3212 is related

**Comment by batzen** [comment]
@bbougot This is open source. If you need a fix ASAP, fix it yourself and create a pull request.

**Comment by bbougot** [comment]
@batzen Am I supposed to know how to fix it?

**Comment by batzen** [comment]
@bbougot Is anyone supposed to fix it for you if you need it ASAP?

**Comment by bbougot** [comment]
No, I am only highlighting this is a very handicapping issue and, regarding the impacted users and the fact it has been living for a long time (release > 1.5),  it should be considered as highly prioritized. No more less.

**Comment by batzen** [comment]
Then add your reaction through the reaction function.
This project is maintained in the peoples spare time, so don't add pressure on them by saying "Really need to see a fix and a NuGet release".

If you think it takes too long to fix the issue then jump in and fix the issue.

Regarding priority, it impacts you but by far not everyone else. It only impacts people using this particular feature.
