### ISSUE TITLE
BorderlessWindowBehavior turning Window Topmost when minimized and restored

### ISSUE THREAD

**Issue by JobaDiniz** [MahApps/MahApps.Metro#3195]
[Rolling your own window](http://mahapps.com/guides/advanced-guide.html) doesn't work anymore because of the `BorderlessWindowBehavior`.

When we override `MetroWindow` behaviors like so:

```
<metro:MetroWindow 
    x:Class="Gemini.Modules.MainWindow.Views.MainWindowView"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:metro="clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro"
    xmlns:cal="http://www.caliburnproject.org"
    xmlns:i="http://schemas.microsoft.com/expression/2010/interactivity"
    xmlns:behaviours="http://metro.mahapps.com/winfx/xaml/shared"
    xmlns:behaviors="clr-namespace:Gemini.Framework.Behaviors"
    xmlns:converters="clr-namespace:Gemini.Framework.Converters"
    xmlns:gong="clr-namespace:GongSolutions.Wpf.DragDrop;assembly=GongSolutions.Wpf.DragDrop"
    Title="{Binding Title}" Icon="{Binding Icon}" Width="{Binding Width, Mode=TwoWay}" Height="{Binding Height, Mode=TwoWay}" 
    WindowState="{Binding WindowState}" WindowStartupLocation="CenterScreen" TitleCaps="False"
    WindowTransitionsEnabled="False" ResizeMode="CanResizeWithGrip" UseLayoutRounding="True" EnableDWMDropShadow="True"
    gong:DragDrop.IsDropTarget="True" gong:DragDrop.DropHandler="{Binding Shell}">
    <i:Interaction.Behaviors>
        <behaviors:MyNewBehavior />
        <behaviours:BorderlessWindowBehavior />
        <behaviours:WindowsSettingBehaviour />
        <behaviours:GlowWindowBehavior />
    </i:Interaction.Behaviors>
```

When we minimize the window, and then restore it, it becomes *Topmost* window. If we remove `BorderlessWindowBehavior`, the window behavior works just fine, that is, it doesn't become topmost window.

## What steps will reproduce this issue?

Override MetroWindow behaviors, adding the default ones manually, like `BorderlessWindowBehavior`.

### Expected outcome

Window should not become Topmost when minimized and restored.

### Environment

- MahApps.Metro __v1.6.0__
- .NET Framework __4.5__

### Workaround

I was able to workaround this by adding my behavior in window constructor (code behind).

**Comment by batzen** [comment]
You should not use the behavior outside the constructor.
If you use it outside the constructor it will cause performance issues, early fired loaded events and other issues.

Guess the guide should be updated to reflect this.

**Comment by punker76** [comment]
This usage of the `Behaviours:BorderlessWindowBehavior ` is obsolete and will be deleted at the official documenattion site.

**Comment by matteomigliore** [comment]
So how is possible to solve the issue?

**Comment by matteomigliore** [comment]
Found, remove Behaviours:BorderlessWindowBehavior.
