### ISSUE TITLE
ThemeManager.ChangeAppStyle don't work when open window in thread

### ISSUE THREAD

**Issue by Pekshev** [MahApps/MahApps.Metro#3196]
Perhaps this is not a bug, but I just do not know how to do it right in this case.
When the window is initialized, I change the window theme:
```csharp
public SubWindow()
{
    InitializeComponent();
    ThemeManager.ChangeAppStyle(this,
        ThemeManager.Accents.First(x => x.Name.Equals("Red")),
        ThemeManager.GetAppTheme("BaseLight"));
}
```
But if I start the window from the thread, I get an error: **The calling thread can not access this object, since the owner of this object is another thread**
```csharp
private void BtOpenNewWindow_OnClick(object sender, RoutedEventArgs e)
{
    Thread subWindowThread = new Thread(() =>
    {
        SubWindow subWindow = new SubWindow();
        subWindow.ShowDialog();
    });
    subWindowThread.SetApartmentState(ApartmentState.STA);
    subWindowThread.IsBackground = true;
    subWindowThread.Start();
}
```

Test project I attach: https://github.com/Pekshev/MyMetroWindowThreadThemeTest

### Environment

- MahApps.Metro __v1.6.0__

**Comment by punker76** [comment]
@Pekshev The exception which you got is correct. If you create a window in a different thread, then all nested respurce dictionaries must add in the same thread. Otherwise you will get this exception. You can read a little bit bout here [`Create new MahApps window in separate thread`](http://jkarger.de/2016/01/22/create-new-mahapps-window-in-separate-thread/).

**Comment by Pekshev** [comment]
I'm find better way) Just change:
```csharp
public SubWindow()
{
    InitializeComponent();
    ThemeManager.ChangeAppStyle(this,
        ThemeManager.Accents.First(x => x.Name.Equals("Red")),
        ThemeManager.GetAppTheme("BaseLight"));
}
```
to
```csharp
public SubWindow()
{
    InitializeComponent();
    ThemeManager.ChangeAppStyle(this.Resources,
        ThemeManager.Accents.First(x => x.Name.Equals("Red")),
        ThemeManager.GetAppTheme("BaseLight"));
}
```
