### ISSUE TITLE
Possible conflict with CefSharp.WPF and/or Newtonsoft.Json on .NET 4.5

### ISSUE THREAD

**Issue by Atulin** [MahApps/MahApps.Metro#3198]
## What steps will reproduce this issue?

1. Create a MahApps.Metro application
2. Install MahApps.Metro.Icons NuGet
3. Install Newtonsoft.Json NuGet and its dependencies (WindowsAPICodePack-Core and -Shell)
4. Create x64 and x86 solution platforms
5. Install CefSharp.Wpf and its dependencies
6. Exit VS and open it again, open the solution

### Expected outcome

`The name MetroWindow does not exist in the namespace "clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro"` XAML designer error, and a similar error on all elements of MahApps.Metro.

Problem doesn't occur on .NET 4.6.1

### Environment

- MahApps.Metro __v1.6.0__
- Windows OS __Win10 x64__
- Visual Studio __2017__
- .NET Framework __4.5__

**Comment by punker76** [comment]
@Atulin This is caused by a VS designer issue. If you choose the x64 as the target, then the designer will not work correctly.

**Comment by Malavos** [comment]
@Atulin  I also tried to check over if Newtonsoft could cause any crashes related to the one reported by you, but I didn't see anything coming up. I guess what punker answered is precise. Can we close this up?

**Comment by Atulin** [comment]
Since it cannot be reproduced otherwise, I'd say so.
