### ISSUE TITLE
Will MahApps works with Silverlight?

### ISSUE THREAD

**Issue by peererror** [MahApps/MahApps.Metro#3199]
I want to port my application to silverlight the application currently using MahApps .I want to ask will maha works with silverlight as it is or there any workaround. 
cheers

**Comment by thoemmi** [comment]
Do you know that Silverlight is dead already? It's not supported by any major browser anymore, see [Wikipedia](https://en.wikipedia.org/wiki/Microsoft_Silverlight#Supported_platforms) and [Microsoft's list of compatible OS and browsers](https://www.microsoft.com/getsilverlight/locale/en-us/html/installation-win-SL5.html).

And back to your question: No, MahApps.Metro does not support Silverlight.
