### ISSUE TITLE
NuGet Package 1.6.0 Lacks of StrongName

### ISSUE THREAD

**Issue by gruendpk** [MahApps/MahApps.Metro#3201]
Hi there, 
the current available nuget package version 1.6.0 lacks of strong name. Is there any good reason why not signing it?
The same issue targets the new dependency ControlsEx.

Exception on application start:
`Additional information: Could not load file or assembly 'MahApps.Metro, Version=1.6.0.362, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)`

**Comment by thoemmi** [comment]
Please see the [release notes for v1.6](https://github.com/MahApps/MahApps.Metro/releases/tag/1.6.0):

> __Strong naming__
> 
> MahApps will no longer be strong-named beginning with this version. [#3029](https://github.com/MahApps/MahApps.Metro/issues/3029)
> 
> Why?
> 
> Strong-named assemblies are only useful in some rare scenarios. If you need strong-named assembly then you can compile the source by yourself ore use the [Strong Namer](https://github.com/dsplaisted/strongnamer) from Daniel Plaisted @dsplaisted or [Strong-Name Signer](https://github.com/brutaldev/StrongNameSigner) from Werner van Deventer @brutaldev.
> 
> More informations about the reason of this decision can be found here:
> 
> - [Still Strong-Naming your Assemblies? You do know it’s 2016, right?](https://www.pedrolamas.com/2016/03/01/still-strong-naming-your-assemblies-you-do-know-its-2016-right/)
> - [XAML Behaviors UWP Managed 1.1.0](https://www.pedrolamas.com/2016/02/23/xaml-behaviors-uwp-managed-1-1-0/)
> - [Strong-Named Assemblies](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/strong-named-assemblies)
