### ISSUE TITLE
Missing System.Windows.Interactivity in nuget package

### ISSUE THREAD

**Issue by tokm** [MahApps/MahApps.Metro#3203]
System.Windows.Interactivity used to be included in the nuget package.  In version 1.5 it is included, but 1.6 does not.  Since I make use of this for behaviors my build does not compile when I updated to v1.6 via nuget.

If you download and open the nuget package for v1.6 here and open it in 7-zip you can see the dll is no longer included.
https://www.nuget.org/api/v2/package/MahApps.Metro/1.6.0

**Comment by punker76** [comment]
@tokm It comes now with the [ControlzEx](https://github.com/ControlzEx/ControlzEx) package which is a dependency since 1.6

**Comment by tokm** [comment]
So if it's a dependency wouldn't it install when I upgraded the nuget package from 1.5 to 1.6?  After the upgraded nuget package the reference for System.Windows.Interactivity disappears from my project.

**Comment by thoemmi** [comment]
Please try to add [ControlzEx](https://www.nuget.org/packages/ControlzEx) as an explicit dependency to your project.

**Comment by tokm** [comment]
I think the problem is the dependency install order.  I see the controlez package but no system.windows.interactive.dll in my references. Maybe it gets updated when controlez is installed but removed when mahapps.metro 1.5 is uninstalled.

________________________________
