### ISSUE TITLE
NumericUpDown watermark align not working

### ISSUE THREAD

**Issue by scccboom** [MahApps/MahApps.Metro#3205]
```xaml
<Controls:NumericUpDown Name="Period" Maximum="100" Minimum="0"
           Interval="0.5"
           TextAlignment="Left"
           Controls:TextBoxHelper.ClearTextButton="True"
           Controls:TextBoxHelper.UseFloatingWatermark="True"
           Controls:TextBoxHelper.WatermarkAlignment="Left"/>
```
This control in flyout, and flyout position property is left.
Open flyout, NumericUpDown watermark align is right.

### Environment

- MahApps.Metro __v1.6.0.150
- Windows OS 8.1 64bit
- Visual Studio __2015
- .NET Framework 4.6

**Comment by punker76** [comment]
@scccboom You must set `HorizontalContentAlignment="Stretch"` to get what you want, cause the styling default is `Right`.
