### ISSUE TITLE
How to set fix watermark ?

### ISSUE THREAD

**Issue by scccboom** [MahApps/MahApps.Metro#3207]
When text is empty, like this

| Watermark            |
|--------------------|
| Waiting for input   |

**Comment by punker76** [comment]
@scccboom You can set a watermark by using the `TextBoxHelper` helper class

```xaml
<TextBox Controls:TextBoxHelper.Watermark="Waiting for input" />
```

with `xmlns:Controls="http://metro.mahapps.com/winfx/xaml/controls"`.

**Comment by scccboom** [comment]
@punker76 un! I want the watermark to float when there is no input.

**Comment by punker76** [comment]
@scccboom Then you can use `Controls:TextBoxHelper.UseFloatingWatermark="True"`

**Comment by scccboom** [comment]
@punker76 I hope like this
![textbox](https://user-images.githubusercontent.com/12345850/37759996-52b11b9c-2df0-11e8-9d93-ee8c8054b561.jpg)

**Comment by punker76** [comment]
@scccboom that's not possible.
