### ISSUE TITLE
Question: Will The Official Website & NuGet Be Updated With 1.6.0

### ISSUE THREAD

**Issue by Pirajew** [MahApps/MahApps.Metro#3210]
Just wondering, because it's been on 1.5.0 for a year now, but on GitHub it says you've entered version 1.6.0

**Comment by Deadpikle** [comment]
Can't answer about the website, but NuGet is already set to 1.6.1. See [here](https://www.nuget.org/packages/MahApps.Metro/).

**Comment by thoemmi** [comment]
I guess @Pirajew refers to http://mahapps.com/news/

**Comment by Pirajew** [comment]
@thoemmi Yes, that is what I was referring to.

**Comment by ahmedflix25** [comment]
also the documentation there is very old very weak very basic

**Comment by punker76** [comment]
@Pirajew 1.6.0 and 1.6.1 release notes now added http://mahapps.com/news/
@ahmedflix25 I know and I'm working on it.
