### ISSUE TITLE
[Feature request] NumericUpDown - Hexdecimal input mode

### ISSUE THREAD

**Issue by Symbai** [MahApps/MahApps.Metro#3215]
I would like an option to allow hexdecimal input in the NumericUpDown control besides of numerics and decimals. I haven't filled out the issue template since this is not a bug report, hope that's okay.

//edit: The reason I'm asking for is that with stringformat we can format the value as hex but there is no option to allow hexdecimal input. For example the user cannot enter "1A" himself.

**Comment by Stephen-Ross** [comment]
I've created a PR which covers this in #3256 as this is something that I also require.
