### ISSUE TITLE
Enhancement Request: HamburgerMenu customization

### ISSUE THREAD

**Issue by shon3322** [MahApps/MahApps.Metro#3218]
It turned out a handy control, but it does not have enough customization.
![screenshot_1](https://user-images.githubusercontent.com/19240430/38900441-2563dd14-42a4-11e8-8eea-97a0bc37c6be.png)
Here best to add a basic customization as Style of HamburgerMenuItem for each item, it would be nice to inherit HamburgerMenu from TabControl and HamburgerMenuItem from TabItem or something like that.

**Comment by punker76** [comment]
@shon3322 The `HamburgerMenuItem` class and their derived classes are only helper classes to hold the content for each "Page". If you want to change the template for each item you can use the properties `ItemTemplate` and `OptionsItemTemplate`. It's also possible to change the style with `ItemContainerStyle` and `OptionsItemContainerStyle` (default style is `HamburgerMenuItemStyle`).
