### ISSUE TITLE
ThemeManager: dynamic accents only work once

### ISSUE THREAD

**Issue by neilt6** [MahApps/MahApps.Metro#3227]
I'm trying to use `ThemeManager` to set dynamically-generated accents like so:

```
Accent newAccent = MyHelperClass.GetAccent(accentColor);
Tuple<AppTheme, Accent> appStyle = ThemeManager.DetectAppStyle(Application.Current);
ThemeManager.ChangeAppStyle(Application.Current, newAccent, appStyle.Item1);
```

This works the first time, but the second time I get a null reference exception from line 372 in ThemeManager.cs:

```
var key = oldAccent.Resources.Source.ToString().ToLower();
```

The line fails since the dynamically-generated resource dictionary has a null `Source` property.

**Comment by punker76** [comment]
@neilt6 You must add your custom accent to the `ThemeManager`, so then it is known by them.

```csharp
ThemeManager.AddAccent("CustomAccent1", new Uri("pack://application:,,,/YOURAPP;component/CustomAccent.xaml"));
```

**Comment by neilt6** [comment]
@punker76 The accent is using a dynamically-generated resource dictionary, so it has no Uri.

For what it's worth, my goal here is to automatically adopt the Windows 10 accent color.

**Comment by neilt6** [comment]
@punker76 I'm aware of that sample, and in fact my code is based on it. However, I don't think we should be required to save a dynamically-generated resource dictionary to disk and reload it just to sidestep what's clearly a bug.
