### ISSUE TITLE
Feature request - Change visibility in expander toogle button

### ISSUE THREAD

**Issue by avechuche** [MahApps/MahApps.Metro#3228]
Hello, is it possible to add an option that can change the "Visibility" property in the toogle button of an expander? something like **Controls: ExpanderHelper.ToogleButtonVisibility="Collapse"**
Of course, it can be expanded by clicking on the row. Thx

**Comment by punker76** [comment]
@avechuche An expander control should always shown it's state to make it different to a GroupBox. If you don't need this difference then please make your own style for the header template.
