### ISSUE TITLE
TransitioningcontentControl animation and DataValidation

### ISSUE THREAD

**Issue by RegisLaine** [MahApps/MahApps.Metro#3229]
## What steps will reproduce this issue?

_When I use transitioningContentControl in my wizardApp the validation and especially Error Template appears before the end of the animation played by transition which is unsightly._

The following URL is an animated GIf to expose the problem :

![Issue](http://blogdeployment.fr/wp-content/uploads/2018/04/Mahapps_Transition_ErrorTemplate.gif)

### Expected outcome

1. Wait for the end of TransitioningContentControl animation before diplaying Validation Error controls. 
2. Remove Any ValidationError Controls before starting TransitioningContentControl animation

### Environment

- MahApps.Metro __v1.6.1__
- Windows OS __7-8-8.1-10__
- Visual Studio __2017__
- .NET Framework __4.0__

**Comment by punker76** [comment]
@RegisLaine Try to put your content inside an `AdornerDecorator`

```xaml
<AdornerDecorator>

  <Grid>
    <!-- your inner content -->

  </Grid>

</AdornerDecorator>
```

**Comment by RegisLaine** [comment]
It works like a charm :-)
Thanks a lot !
