### ISSUE TITLE
Frozen DataGrid row

### ISSUE THREAD

**Issue by avechuche** [MahApps/MahApps.Metro#3242]
Hello, is it possible to add to mahapps the option to freeze the last row of a datagrid? To show results of the sum of the elements, for example. Thx

https://msdnshared.blob.core.windows.net/media/MSDNBlogsFS/prod.evol.blogs.msdn.com/CommunityServer.Components.PostAttachments/00/09/02/72/84/DataGrid_V1_FrozenRowSample.zip

**Comment by punker76** [comment]
Yeah this would be a nice feature. But I don't want to implement this here from the (older) sample, because of some points:

- need to handle virtualization
- need to handle grouping
- need to handle maybe other things?
