### ISSUE TITLE
RightWindowCommands no more visible when ShowTitleBar is False

### ISSUE THREAD

**Issue by bbougot** [MahApps/MahApps.Metro#3244]
Starting from MahApps 1.6.2, setting **ShowTitleBar** to _False_ along with **RightWindowCommands** does not work anymore. The RightWindowCommands is not shown whereas it should be.

### Expected outcome

The RightWindowCommands should always be visible, like it was before and behave the same than WindowButtonCommands.

### Environment

- MahApps.Metro __v1.6.2__
- Windows OS __16299__
- Visual Studio __2017__
- .NET Framework __4.7.1__

**Comment by punker76** [comment]
@bbougot It's more a combination with a feature and a bug (which I fixed now). Normally if you set the `ShowTitleBar` to false then all window commands except the button window commands should be collapsed. If you don't want this, then you can set then `LeftWindowCommandsOverlayBehavior` and `RightWindowCommandsOverlayBehavior` to `HiddenTitleBar` or `Always` to force it to shown.

**Comment by programatix** [comment]
In version 1.6.4, if I set ```ShowTitleBar``` to false, and ```RightWindowCommandsOverlayBehavior``` to ```Always```, then a white background title bar would appear. Previously, in older version, the commands overlay blend into the window.

**Comment by midium81** [comment]
As programatix say, even with that overlay behavior set, the buttons didn't overlay into the window like it happens for the WindowButtonCommands, they actually restore the entire title bar that was supposed to be hidden having set ShowTitleBar to false.

**Comment by midium** [comment]
I confirm what programatix say, the behavior didn't work as expected, when the behavior is set the title bar is simply show even if the ShowTitleBar is set to false
