### ISSUE TITLE
Close Dialog with Alt + F4

### ISSUE THREAD

**Issue by Nova669** [MahApps/MahApps.Metro#3252]
When we use MetroWindow.ShowMessageAsync(...) we want to close the dialog when the user presses Alt+F4.
In other programs (for example Word/Excel etc.) this behaviour is implemented and we want to get the same in our application. 

Maybe it should be possible to pass a keyhandler to the ShowMessageAsync().

### Expected outcome

Dialog closes with same result as ESC.

### Environment

- MahApps.Metro __v1.6.4__
- Windows OS __10__
- Visual Studio __2017 (15.5.6)__
- .NET Framework __4.7__

**Comment by zeluisping** [comment]
Oh c'mon guys is this project really stalling? This was one year ago and it's not hard to do

**Comment by gep13** [comment]
>@zeluisping said...
Oh c'mon guys is this project really stalling? This was one year ago and it's not hard to do

Are you familiar with how OpenSource, and contributing to Open Source Projects works?

**Comment by zeluisping** [comment]
Yes I am, it's just sad, used to be one of the main projects I contributed to while working with Windows. I know my comment was a bit off, and I do apologize for it
