### ISSUE TITLE
Theme names and Accent names not localized

### ISSUE THREAD

**Issue by fjlaga** [MahApps/MahApps.Metro#3253]
**Description**
My app uses the ThemeManager to allow the user to specify the colors. My app also supports localization. After setting the Windows display language to a non-English language (Spanish, German, Chinese, etc...) the Theme and Accent names are not localized.

This is because the names are hard-coded in ThemeManager.cs:

` var colors = new[] {
                                       "Red", "Green", "Blue", "Purple", "Orange", "Lime", "Emerald", "Teal", "Cyan", "Cobalt",
                                       "Indigo", "Violet", "Pink", "Magenta", "Crimson", "Amber", "Yellow", "Brown", "Olive", "Steel", "Mauve", "Taupe", "Sienna"
                                   };
...`

**Expected behavior**
Theme names and Accent names are localized according to the Windows display language.

**Screenshots**
![image](https://user-images.githubusercontent.com/7451688/40499825-f59dc76a-5f37-11e8-95a0-6519974dc0c1.png)

**Environment(please complete the following information):**
 - MahApps.Metro version 1.6.0
 - OS: Win10 1709
 - Visual Studio 2015 14.0.25431.01 Update 3
 - .NET Framework 4.7.02556

**Comment by jean309** [comment]
I agree; it's also a problem for me

**Comment by punker76** [comment]
I think this is not an assignement for this lib. These names are also the keys for the resource dictionaries.
