### ISSUE TITLE
MetroWindow Invisible with Windows 10 April 2018 Creator's Update 1803

### ISSUE THREAD

**Issue by sleman** [MahApps/MahApps.Metro#3255]
**Describe the bug**
My app's main window is invisible after upgrading to win 10 april 2018 creator's update 1803.

**To Reproduce**
Set MainWindow.xaml to

`<controls:MetroWindow x:Class="a.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:wpf="clr-namespace:a.classes.Wpf"
        xmlns:controls="http://metro.mahapps.com/winfx/xaml/controls"
        xmlns:i="http://schemas.microsoft.com/expression/2010/interactivity"
        Height="728" Width="1024" VerticalAlignment="Top" VerticalContentAlignment="Center"
        WindowTitleBrush="#191919" WindowStyle="SingleBorderWindow" 
        WindowStartupLocation="CenterScreen">`

**Expected behavior**
Application main window should appear

**Environment(please complete the following information):**
 - MahApps.Metro  v1.4.0
 - OS: Win10 1803
 - Visual Studio: 2017 15.7.1
 - .NET Framework: 4.6.2

**Comment by punker76** [comment]
@sleman Can you try update your app to use MahApps v1.6.4 (the latest)?

**Comment by sleman** [comment]
Just did. Updated from nuget. Same issue.

**Comment by punker76** [comment]
@sleman mh, I have no problems with 1803 on my machine ™️ Do you do something special in code behind or Xaml of the main window or the application?

**Comment by sleman** [comment]
It's very strange. I only see the issue on one machine and not on another. Trying to figure out what's different.

**Comment by Antonyo** [comment]
We have also some users reporting similar issue after Windows 10 April update. In our case the border of the window is still shown, maybe because we use a glowindow border.

One user reported fixing it by forcing software rendering:

`RenderOptions.ProcessRenderMode = Global.Settings.ForceSoftwareRendering`

Our configuration is:

- MahApps.Metro v1.2.4.0
- .Net Framework 4.5.2
- 64bit application

**Comment by punker76** [comment]
@Antonyo Please try with the latest version 1.6.4 again. What window properties did you set in Xaml and code behind? Any other special stuff like setting `AllowsTransparency` to true or something else? Can you create a short simple App with latest MahApps version and test it on the failing machine?

**Comment by sleman** [comment]
Updated machine's graphics card drivers from Intel's website and window appears fine now.
