### ISSUE TITLE
[Question] Always keep Metro Dialog in front of screen in WPF application

### ISSUE THREAD

**Issue by ferstljo** [MahApps/MahApps.Metro#3258]
Hello there,

I'm pretty new to WPF and the Metro styling and I ran into the following problem:

I open all my message dialogs from the main window of my application by calling ShowMessageAsync()., even when the actual caller is another window (e.g. a settings window). Now when for example this settings window is open and wants to show a message that the settings have been saved, the dialog appears in between the main and the settings window (which makes sense because the main window is the caller and the settings window is a child of that main window). 
What I want is for all dialogs created by ShowMessageAsynch() to be displayed always in front of the screen.

Any ideas on how to achieve that?

Thanks in advance for your answers!

**Comment by punker76** [comment]
@ferstljo If you settings window is also a MetroWindow, then you can use this to show message dialog inside your settings window.
