### ISSUE TITLE
BadgeControl does not respect size properties

### ISSUE THREAD

**Issue by JobaDiniz** [MahApps/MahApps.Metro#3261]
**Describe the bug**
No matter what I set in width, height, max-height, max-width, the badged always stays the same size... Even when I set `FontSize` of the content within the bagde, the bagded does not "shrink" to its content.
Maybe the constraint that cannot be changed is in [these lines](https://github.com/MahApps/MahApps.Metro/blob/develop/src/MahApps.Metro/Themes/Badged.xaml#L46-L47)

**Expected behavior**
Bagded control should shrink if its contents is small, or at least we should be able to control this behavior, either by setting MinHeight/MinWidth or other configuration.

**Screenshots**
![image](https://user-images.githubusercontent.com/165290/41106442-6a058bf6-6a46-11e8-8ebe-ad422b73c2bd.png)

**Environment(please complete the following information):**
 - MahApps.Metro version [e.g. v1.6.2]

**Comment by punker76** [comment]
The BadgedControl has now some extra properties to change the Badge in an easier way. (see #3790)
