### ISSUE TITLE
Possible NullReferenceException in GlowWindowBehavior 

### ISSUE THREAD

**Issue by andy294** [MahApps/MahApps.Metro#3263]
Missing cleanup in MahApps.Metro.Behaviours.GlowWindowBehavior leads to possible NullReferenceExceptions.

**To Reproduce**
1. Add code for reproducing the issue:
a. Open MetroDemo.MainWindow.MenuWindowWithGlowOnClick in VS
b. Add `StylizedBehaviors.SetBehaviors(w, null);` before `w.Show();`
2. Start the demo application
3. Go to "Window" => "Window with glow" => NullReferenceException in GlowWindowBehavior

**Environment:**
 - MahApps.Metro version v1.6.4
 - OS: Windows 7
 - Visual Studio 2017 15.6.6
 - .NET Framework 4.6.2

**Comment by punker76** [comment]
@andy294 There will be a re-write of the GlowWindow in [ControlzEx](https://github.com/ControlzEx/ControlzEx/pull/46), so I will close this here.
