### ISSUE TITLE
Datagridnumericupdown: change default currency per row, based on a currency cell, via MMV

### ISSUE THREAD

**Issue by oriolmortem** [MahApps/MahApps.Metro#3267]
**Is your feature request related to a problem? Please describe.**
I want to ask you how to change the default currency showed in a datagridnumericupdown cell, based on the currency setted in a cell of the same datagrid.
Thank you

**Comment by punker76** [comment]
@oriolmortem Can you describe that in more detail? I don't understand what you are mean with "default currency". Maybe a small example will help to show this.
