### ISSUE TITLE
how to reset the window position when used SaveWindowPosition

### ISSUE THREAD

**Issue by Motorcure** [MahApps/MahApps.Metro#3269]
I am having an issue where having SaveWindowPosition="True" and causes layout issues. Is there a way to reset the window position?

BTW,where is the settings saved?

**Comment by Motorcure** [comment]
resolved by myself

**Comment by punker76** [comment]
@Motorcure Maybe you can post your solution?

**Comment by Motorcure** [comment]
the window placement information is saved in %LOCALAPPDATA%\MetroWFPTest
so, if deleted the corresponding directory, the window position can be restore to initial state

Please forgive me, so bad English:(
