### ISSUE TITLE
DataGridCheckBoxColumn databinding and Style Ref #2675

### ISSUE THREAD

**Issue by jammerxd** [MahApps/MahApps.Metro#3271]
When using the DataGridCheckBoxColumn or DataGridTemplateColumn with a checkbox the expected behavior was that clicking on the checkbox regardless of whether or not the row is selected, would check or uncheck the box and update the property binding accordingly. However, we found that when we apply the MetroDataGridCheckBox style either via `Style="{DynamicResource MetroDataGridCheckBox}"` or via `EditingElementStyle="{DynamicResource MetroDataGridCheckBox}" ElementStyle="{DynamicResource MetroDataGridCheckBox}"` as shown in the example program, a double click is required for the box to check and uncheck.

**To Reproduce**
Create a DataGrid with at least 1 checkbox column using either `DataGridCheckBoxColumn` or `DataGridTemplateColumn`(as a single checkbox) using a binding to a property of the row object.

Set the following attributes:
For a template column, set `Style="{DynamicResource MetroDataGridCheckbox}"` on the checkbox element
For a checkboxcolumn set `EditingElementStyle="{DynamicResource MetroDataGridCheckBox}"` and `ElementStyle="{DynamicResource MetroDataGridCheckBox}"`

Attempt to check the checkbox by clicking on it. Count number of clicks needed to check the box.

Remove the `EditingElementStyle`, `ElementStyle`, and `Style` attributes from the column.

Attempt to check the checkbox by clicking on it. It should now check with only 1 click.

**Expected behavior**
When clicking on a checkbox column, I expect a click on the checkbox to immediately check/uncheck the box regardless to the row selection state. 

**Environment(please complete the following information):**
 - MahApps.Metro version 1.6.4
 - OS: Windows 7 x64
 - Visual Studio 2015 14.0.25431.01
 - .NET Framework 4.5.2

**Repo**
Unfortunately code cannot be posted due to it being a work/company project.

**Comment by punker76** [comment]
@jammerxd You can use the `DataGridHelper.EnableCellEditAssist` attached property to allow a single click on the checkbox.
