### ISSUE TITLE
[Build] Not building "CustomValidationPopup does not exist"

### ISSUE THREAD

**Issue by auxua** [MahApps/MahApps.Metro#3273]
Building the MahApps.Metro project (commit cb92648) results in error

`"CustomValidationPopup" does not exist in namespace "http://metro.mahapps.com/winfx/xaml/controls`

The  error was reproduced on multiple machines with

Windows 10 Build 16299
Visual Studio 2017 Professional (15.7.4)
.Net Framework SDKs for 4.6.1, 4.6.2, 4.7, 4.7.1

We tried on three different machines with the same software setup as above. The error remains the same.

**Comment by punker76** [comment]
@auxua Appveyor and local build works, so what are you exactly doing? Building MahApps inside your app? Or standalone?

**Comment by auxua** [comment]
Standalone, clean clone from this repo using the Visual Studio build pipeline

**Comment by punker76** [comment]
@auxua Does this also happen if you run `powershell .\build.ps1` inside the `src` folder? (Can you also try to clone the rep again before you build it?)

**Comment by auxua** [comment]
When using the ps1 script I get an error durcing the Restore chapter  naming, that the target restore is not existing in the project (MSB4057)

**Comment by punker76** [comment]
@auxua Any chance to try again with the latest dev source?
