### ISSUE TITLE
No components found on dll when adding to Toolbox

### ISSUE THREAD

**Issue by alvpickmans** [MahApps/MahApps.Metro#3274]
**Describe the bug**
MahApps Controls not found when loading to Toolbox panel on Visual Studio 2017.

**To Reproduce**
1. Install MahApps 1.6.5 from Nuget.
2. Once installed, open Visual Studio's Toolbox, right click and select *Choose Items*
3. On `WPF Components` tab, click on *Browse*
4. Select dll from ../*{projectFolder}*/packages/MahApps.Metro.1.x.x\lib\net4x
5. After quite a while, "*There are no components...*" error is thrown.

**Expected behavior**
MahApps controls loaded into the Toolbox panel

**Screenshots**
![image](https://user-images.githubusercontent.com/12413808/41654374-2d3caa70-7481-11e8-8073-f0f1f1e3d3f7.png)

**Environment(please complete the following information):**
 - MahApps.Metro version v1.6.5
 - OS: Win10 Pro
 - Visual Studio 2017 15.6.7
 - .NET Framework 4.5.2

**Repo**
*None at the moment*

**Additional context**
I followed the same process to load MaterialDesign Controls to test if it was a VisualStudio issue, but they got loaded straight away as shown on the screenshot.

**Comment by punker76** [comment]
@alvpickmans MahApps has a dependency to ControlzEx, so you must add the ControlzEx.dll too. Put both dlls inside a single folder for easier selection.

![2018-06-20_14h03_23](https://user-images.githubusercontent.com/658431/41657190-dac38342-7492-11e8-9f5f-e41b8968a0d6.png)

**Comment by alvpickmans** [comment]
@punker76 it worked like a charm. Thanks!
