### ISSUE TITLE
TransitioningContentControl vs. ContentControl

### ISSUE THREAD

**Issue by seb30** [MahApps/MahApps.Metro#3275]
- MahApps.Metro version 1.6.4
 - OS: Win10 1803
 - Visual Studio 2017 15.7.4
 - .NET Framework 4.7.2

The DataContext of the (Transitioning)ContentControl is bound to a class with a Enum property CardTypeValue which fires INotifyPropertyChanged. The ContentTemplate is set via DataTriggers (one for each Enum value). The default ContentControl recognizes the notification and changes its ContentTemplate. The TransitioningContentControl doesn't do this.

ContentControl :
![contentcontrol](https://user-images.githubusercontent.com/28293949/41658244-12cbbc3e-7496-11e8-9338-318a6fff168c.gif)

TransitioningContentControl:
![transitioningcontentcontrol](https://user-images.githubusercontent.com/28293949/41658248-1602e6b6-7496-11e8-8005-783137e9762e.gif)

**Comment by seb30** [comment]
Additional info:

![01](https://user-images.githubusercontent.com/28293949/41658371-714c55a2-7496-11e8-89a5-fc4668fd1c7b.png)

**Comment by punker76** [comment]
@seb30 I think I know what's the problem is, but it would be nice if you can separate this one in a simple app.

**Comment by seb30** [comment]
I'm out of office for a week. I will do this after my vacation.

**Comment by punker76** [comment]
@seb30 It would be nice if you can test the latest changes against your app after your vacation :-D

The latest v2.0 alpha NuGet package can be found [her](https://ci.appveyor.com/nuget/mahapps.metro)
