### ISSUE TITLE
ToastNotification is required!

### ISSUE THREAD

**Issue by wjkhappy14** [MahApps/MahApps.Metro#3277]
**Is your feature request related to a problem? Please describe.**

[https://github.com/raflop/ToastNotifications](https://github.com/raflop/ToastNotifications)

Toast Notify  may be  much better  when finish some   command actions !
**Describe the solution you'd like**

**Additional context**

**Closed Issues**

**Comment by punker76** [comment]
@wjkhappy14 I don't understand what do you want/need? This library can be used in any WPF app together or without MahApps.
