### ISSUE TITLE
Memory leak by using Mahapps with WindowsFormsIntegration

### ISSUE THREAD

**Issue by seti247** [MahApps/MahApps.Metro#3278]
Hello,

I use the MahApps-Design in WPF-DLL. 
One Control of this DLL ist used in a Windows-Forms application within a HostElement control.

After more times creating an object of this control, opening a window from this control and relogin in windows the system ist total busy in cpu and ram.

The visualtree is ok and the application isn't blocked, but you can't see the elements.

Here is a simple example project with the problem:
[test.zip](https://github.com/MahApps/MahApps.Metro/files/2137638/test.zip)

To reproduce it, start the Windows-Forms application and click multiple times on the "Button1" and on the "Test" button. Then lock windows and relogin and try to use "Button1" or the "Test"-button again, or switch the visibility of the TransitioningContent in the "Window1". 
Some times you must do it two or three times, but then you can see the effect.

Here a screenshot of the hanging application and the system resources:

![application](https://user-images.githubusercontent.com/40603465/41918981-b958918c-795d-11e8-9c32-7bf72de8f958.JPG)

![taskmanager](https://user-images.githubusercontent.com/40603465/41918467-af906d2e-795c-11e8-9f1a-2d15dd4d29fb.JPG)

I use Windows 10, Visual Stidio 2017 and the newest versions of the following NuGet-Packages:
ControlzEx" version="3.0.2.4" targetFramework="net452" 
Dragablz" version="0.0.3.203" targetFramework="net452"
MahApps.Metro" version="1.6.5" targetFramework="net452"
MahApps.Metro.IconPacks" version="2.3.0" targetFramework="net452"
MaterialDesignColors" version="1.1.3" targetFramework="net452"
MaterialDesignThemes" version="2.4.0.1044" targetFramework="net452"
MaterialDesignThemes.MahApps" version="0.0.11" targetFramework="net452"

I hope you can solved this bug or see my fault.

Best regards

**Comment by n00bje** [comment]
You forgot to dispose your ElementHost.
Add this line in removeCtr():
`host?.Dispose()`

**Comment by seti247** [comment]
You are absolutely right, very special thanks for the quick help.
