### ISSUE TITLE
Override ListViewItem Style

### ISSUE THREAD

**Issue by RegisLaine** [MahApps/MahApps.Metro#3282]
Hello, 

I'm working on Overriding ListViewItem Style. 
So I created a copy of ListViewItem Style with Blend. 
I Successfully obtain a style. 
I Updated the first line as above : 
`<Style x:Key="ListViewItemStyle1" TargetType="{x:Type ListViewItem}" BasedOn="{StaticResource MetroListViewItem}">`

When I Apply this Style to en existing ListViewItem it is applied but with DataBinding Errors especially concerning `Mah:ItemHelper` 

Example :  `"(mah:ItemHelper.HoverSelectedBackgroundBrush)' property not found on 'object'"
`
Do you have an idea about why this Databinding does not occurs on mah;ItemHelper ? 
Thank you

**Comment by punker76** [comment]
@RegisLaine It could be that Blend doesn't work well with custom helper classes on custom styles. But if you want to know the default style of MahApps for ListViewItem then you can take a look at the source here:

https://github.com/MahApps/MahApps.Metro/blob/0dffed2b9a98ed928d3ac0b5c8d5c7708f1aa413/src/MahApps.Metro/Styles/Controls.ListView.xaml#L147-L240
