### ISSUE TITLE
Windows 10 close, minimize and maximize button

### ISSUE THREAD

**Issue by hampoelz** [MahApps/MahApps.Metro#3283]
I have put the code

```XAML
<Style TargetType="{x:Type Controls:WindowButtonCommands}" BasedOn="{StaticResource MahApps.Metro.Styles.WindowButtonCommands.Win10}" />
```
in my App.xaml under

```XAML
</ResourceDictionary.MergedDictionaries>
```

But when I start the application I get this error:
```
Exception: Die Ressource mit dem Namen "MahApps.Metro.Styles.WindowButtonCommands.Win10" kann nicht gefunden werden. Bei Ressourcennamen wird die Groß- und Kleinschreibung berücksichtigt.
```

**Comment by punker76** [comment]
@hampoelz Can you write which MahApps version do you use? Did you add the complete MahApps resources?

**Comment by hampoelz** [comment]
Hello,

Have just looked into the NuGet package manager and have noticed that I have installed the version 1.2.4 of MahApps.Metro ... XD - Have it updated and now it works

Thanks for your help
