### ISSUE TITLE
DateTimePicker: Calendar.SelectedDate not always updated and consistent

### ISSUE THREAD

**Issue by lightwalker01** [MahApps/MahApps.Metro#3286]
**Describe the bug**
The Calendar part of the DateTimePicker component shows an inconsistent date if the user edit the date writing in the textbox.

**To Reproduce**
1. Select _01/01/2018_ (european format) via the calendar popup
2. Close the calendar popup
3. Edit the selected date writing in the DateTimePicker textbox: _02/01/2018_
4. Open the calendar popup
5. The calendar shows _01/01/2018_ as selected date

**Expected behavior**
The calendar shows _02/01/2018_ as selected date

**Screenshots**
![image](https://user-images.githubusercontent.com/7263833/42565917-1e3b68b0-8505-11e8-8be1-eac9438b71bb.png)

**Environment(please complete the following information):**
 - MahApps.Metro v1.6.5
 - OS: Windows 10 Pro 1803
 - Visual Studio 2017 15.7.4
 - .NET Framework 4.7.1

**Comment by tymorrow** [comment]
I've also seen an issue similar to this when loading the same data template with a DateTimePicker with different Data Contexts.  The time selections in the picker get set properly with the new data context, and the date displayed in the box is correct, but the selected date in the calendar is the last selection I made for a different data context.
