### ISSUE TITLE
Hide() method on window with GlowBrush applied leaves behind outline of artifact on screen

### ISSUE THREAD

**Issue by mmashwani** [MahApps/MahApps.Metro#3288]
1) Using latest v1.6.5.
2) Create a window with a GlowBrush applied to it.
3) Use Hide() method to hide the window.
4) You will notice an outline of an artifact on the screen until you exit the program.

**Comment by batzen** [comment]
Could you try to reproduce this using the GlowWindowBehavior from https://github.com/ControlzEx/ControlzEx?
You either have to use the latest sources from the develop branch there or use the nuget from the appveyor nuget feed at https://ci.appveyor.com/nuget/controlzex.
The Glow in MahApps will be replaced with the one from ControlzEx in the future and i can't reproduce your issue there.
If you can reproduce the issue there please create an issue at ControlzEx.

**Comment by batzen** [comment]
@mmashwani ping

**Comment by MajedDH** [comment]
Same problem I'm having.
@batzen  When will MahApps.Metro will be updated with this fix?

**Comment by batzen** [comment]
@MajedDH I guess you will have to wait for version 2.0 of MahApps.Metro or you could try to backport the fix made in ControlzEx to fix this issue. I don't remember which changes were made to fix this particular issue.
