### ISSUE TITLE
Metro based Window doesn't show properly after windows 10 updated.

### ISSUE THREAD

**Issue by willtk0113** [MahApps/MahApps.Metro#3290]
Hi-
i have wpf app using latest version mahapps(v1.6.5) running perfectly until I updated windows 10 recently. It seems that a Mahapps based metro window creates a frame but doesn't show any within it. other than that, app runs okay(no pending, etc). 

I repaired .net framework using repair tool offered by Microsoft, but still have same issue.

If anyone got same issue and resolved, please help me out. Thanks :)
(I attached a captured image that show only window system buttons(min, max, close))

![20180724_112253822](https://user-images.githubusercontent.com/5689594/43113835-04cfcbbe-8f37-11e8-8bf2-4400ec042155.png)

**Comment by punker76** [comment]
@willtk0113 Can you write exactly which OS version you are now running on? Did you any special stuff inside your app using MahApps.Metro (like setting AllowsTransparany or something else)?

**Comment by punker76** [comment]
@willtk0113 ping
