### ISSUE TITLE
metro window keeps glow on top of owned window on restored

### ISSUE THREAD

**Issue by MajedDH** [MahApps/MahApps.Metro#3291]
**Describe the bug**
When you show a `MetroWindow` and show another one with the first one as an owner and you minimize the main one, it's glow is still visible above the owned one.

**To Reproduce**
1. Create a MetroWindow and show it.
2. Inside it (on click or load) create another metro window and set it's owner to the first one.
3. now maximize the main window
4. Click on the child window to activate it
5. click on the minimize button of the main window
6. you can see that only the glow is still visible above the child window
7. If you switch to the main window and then switch to the child window, then the expected behavior is done.
**Expected behavior**
the glow should be behind the child window.
**Screenshots**
# the bug:
![The bug](https://user-images.githubusercontent.com/3973115/43192146-73062d16-9005-11e8-99e2-969ad46d7fb2.png)
# the expected bihavior:
![The Expected behivior](https://user-images.githubusercontent.com/3973115/43192221-a9170bd2-9005-11e8-9b73-5f9515465612.png)

**Environment(please complete the following information):**
 - MahApps.Metro version 1.6.4
 - OS: Win 7
 - Visual Studio 2017 15.3.2
 - .NET Framework 4.6

**Comment by batzen** [comment]
This issue will be fixed in ControlzEx as MahApps.Metro will depend on the GlowWindow etc. from there in the future.
If it's a small fix i might port it back to the current version of MahApps.

**Comment by batzen** [comment]
Fixed in the ControlzEx version of the behavior now.
