### ISSUE TITLE
MahApps.Metro.Demo Build issue

### ISSUE THREAD

**Issue by PhilPJL** [MahApps/MahApps.Metro#3292]
MapApps.Metro.Demo won't build due to package issues with .NET4

Using VS 2017 l5.7.5
Clone MahApps.Metro develop

**Expected behavior**
builds ok

**Screenshots**

![image](https://user-images.githubusercontent.com/271656/43336187-6900ab42-91c8-11e8-8e53-535b1ad4fbce.png)

![image](https://user-images.githubusercontent.com/271656/43336500-0622e502-91c9-11e8-88d3-3dcd8e275026.png)

**Environment(please complete the following information):**
 - Latest develop branch
 - OS: Win10 10.0.17134
 - Visual Studio 2017 15.7.5
 - .NET Framework 4.7.2

The issue is fixed by removing the dependency on .NET 4 in the demo.csproj

**Comment by punker76** [comment]
Closed by #3317
