### ISSUE TITLE
How to use mahapps.metro window usercontrol

### ISSUE THREAD

**Issue by Torchok19081986** [MahApps/MahApps.Metro#3294]
Hallo. Im new in WPF. I created a managementconsole in wpf with some help. Console is with listviewitem and icons. Now i wanted open new mahapps.metro window if i clicked one of listviewitem. But to show it , new window item should be a usercontrol. Is there some posibility to create usercontrol with mahapps.metro or some workaround for it ?

**Comment by Anapher** [comment]
That is called Shell Window creation. It is actually pretty easy, create a new `Window` called `MetroShellWindow` with no content at all. Now, you can just execute this code to show the user control in a window:
```cs
var userControl = .... //get your UserControl instance here
var shellWindow = new MetroShellWindow();
shellWindow.Content = userControl;
shellWindow.Show/*Dialog*/();
```
