### ISSUE TITLE
how to set Header and closeButton position in flyout?

### ISSUE THREAD

**Issue by xlp100** [MahApps/MahApps.Metro#3297]
**Is your feature request related to a problem? Please describe.**
how do i set Header and closeButton position in flyout?

**Describe the solution you'd like**
i want to  set closebutton and Header horizon position with parameters

**Additional context**

**Closed Issues**

**Comment by Anapher** [comment]
Sadly this is hard coded in the [Flyout HeaderTemplate](https://github.com/MahApps/MahApps.Metro/blob/develop/src/MahApps.Metro/Themes/Flyout.xaml#L54). You may have to write a custom HeaderTemplate in order to change the position.

**Comment by punker76** [comment]
@xlp100 A possible solution would be to create your own header template by modifying the original one https://github.com/MahApps/MahApps.Metro/blob/0024f3282e9fd6cb780fc18c08637be44b51696c/src/MahApps.Metro/Themes/Flyout.xaml#L13-L72
