### ISSUE TITLE
[1.6.5.1] white window on startup

### ISSUE THREAD

**Issue by ikeas68** [MahApps/MahApps.Metro#3305]
if you have a window
 SaveWindowPosition="true"
1-run it and maximze
2-close
3-restart
during a few second (1 or 2) a blank screen is showed

**Comment by Anapher** [comment]
I was not able to reproduce your issue. Did you try to isolate it in a completely new and clean project? How many screens do you have?

**Comment by ikeas68** [comment]
ok i made a sample software for shoing this probleme
i have two screen
