### ISSUE TITLE
ListView default border only on top

### ISSUE THREAD

**Issue by JVimes** [MahApps/MahApps.Metro#3307]
**Describe the bug**
By default, the ListView has only a top border. It seems like it should either have none, or uniform all around.

**To Reproduce**

If you remove `BorderThickness="0"` from the ListView in the demo app, you can see.

**Expected behavior**
It seems like it should either have no border, or have uniform border all around by default.

**Screenshots**
![image](https://user-images.githubusercontent.com/6148201/44107286-213b8940-9fb4-11e8-862a-c21762c8c744.png)

![image](https://user-images.githubusercontent.com/6148201/44107541-f2a9c4c4-9fb4-11e8-8c85-255135c1ac28.png)

**WPF default ListView for reference:**

![image](https://user-images.githubusercontent.com/6148201/44107413-87ba1d44-9fb4-11e8-8ede-5f66f386903f.png)

**Environment(please complete the following information):**
 - MahApps.Metro version v1.6.5
 - OS: Win10
 - Visual Studio 2017
 - .NET Framework 4.6.2

**Comment by Anapher** [comment]
Ideally, a ListView has a GridView/Headers, and then a top border makes sense because else the column separators just look stupid (IMO). If you want to use the ListView like that, just use a ListBox (which doesn't have this border).

**Comment by JVimes** [comment]
I haven't used it much, but it doesn't sound right that ListView would have styling to support just one of it's possible views. Views other than GridView can be used, and they might not have headers (or their headers won't require a line). Let me know if I'm missing something.

**Comment by JVimes** [comment]
It's a valid report of a design flaw. It's not top priority, but that's what backlogs are for.

**Comment by punker76** [comment]
Closed by 0024f32

**Comment by shijobaby** [comment]
https://www.tacsllc.com/hrms-dubai.htm
https://www.tacsllc.com/access-control-dubai.htm
