### ISSUE TITLE
Hamburger button icon missing

### ISSUE THREAD

**Issue by savaged** [MahApps/MahApps.Metro#3311]
**Describe the bug**
The hamburger 'icon' is not showing

**To Reproduce**
Used NuGet package manager to add MahApps
Simply run WPF app (see repo below)

**Expected behavior**
The three white lines hamburger 'icon' should always show

**Screenshots**
![image](https://user-images.githubusercontent.com/112491/44513843-6abf9800-a6b6-11e8-8864-652f94dd84b0.png)

**Environment(please complete the following information):**
 - MahApps.Metro version v1.6.5
 - OS: Win10 Pro 17134
 - Visual Studio Pro 2017 15.8.1
 - .NET Framework 4.6.1

**Repo**
https://github.com/savaged/SixNations
This should simply need NuGet restore and F5

**Comment by punker76** [comment]
@savaged Hi, you forgot some necessary steps to use MahApps.Metro. I created a [PR](https://github.com/savaged/SixNations/pull/2) on your repo. By the way, thx for the repo :-D Hope my PR helps you a little bit.

![image](https://user-images.githubusercontent.com/658431/44515399-c55ef100-a6c2-11e8-8032-db0fa7c6df9a.png)
