### ISSUE TITLE
[Question] Show Dialog from library class

### ISSUE THREAD

**Issue by AndrzejKl** [MahApps/MahApps.Metro#3312]
Vanila Solution to download with explanation: https://1drv.ms/u/s!Ah3HeDSZXp_FhcMvbycQiR1_LIBUeg

I use IDialogCoordinator on ViewModel and everything works fine.

But if in viewmodel i have instance of other class, it doesn't work. I try to pass dialogCoordinator in constructor, but I've got a message "Context is not registered".

How to achieve that?

Viewmodel:

```c#
public viewModel
{
  private IDialogCoordinator dialogCoordinator;
  public ICommand SyncCommand { get { return new RelayCommand(SyncCommand_ExecutedAsync); } }  

  public viewModel(IDialogCoordinator _coordinator)
  {
    coordinator = _coordinator;
  }

  private void SyncCommand_ExecutedAsync()
  {
        var sync = new IndexUpdater(dialogCoordinator);
        var b = sync.Start().Result;
  }
}
```
IndexUpdater:

```c#
public IndexUpdater(IDialogCoordinator _dialogCoordinator)
    {
        dialogCoordinator = _dialogCoordinator;
    }

public async Task<bool> Start(bool reset = false)
    {
        var output = true;

        ProgressDialogController controller = await dialogCoordinator.ShowProgressAsync(this, "HEADER", "MESSAGE", true, new MetroDialogSettings { NegativeButtonText = "Close" });
         controller.Minimum = 0;
        controller.Maximum = 100;

        for (int x = 0; x < 100; x++)
        {
            if (controller.IsCanceled)
            {
                output = false;
                break;
            }

            Thread.Sleep(200);

            controller.SetProgress(x + 1);
            controller.SetMessage("x = " + x);
        }

        await controller.CloseAsync();
        return output;
}
```
In this case I got Exception: "InvalidOperationException: Context is not registered. Consider using DialogParticipation.Register in XAML to bind in the DataContext."

If I create baseVM class like this:
```c#
private baseVM parrent;

        public IndexUpdater(IDialogCoordinator _dialogCoordinator, baseVM _parrent)
        {
            dialogCoordinator = _dialogCoordinator;
            parrent = _parrent;         
        }
```
and in MainViewModel class:
```c#
public class MainWindowViewModel : baseVM
    {
...

private void SyncCommand_ExecutedAsync()
        {
           var sync = new IndexUpdater(dialogCoordinator, this);
            var b = sync.Start().Result;
        }
```
I don't get error, but application will hang after this line:
```c#
 ProgressDialogController controller = await dialogCoordinator.ShowProgressAsync(parrent, "HEADER", "MESSAGE", true, new MetroDialogSettings { NegativeButtonText = "Close" });
```

But if I put ProgressDialogController directly in viewModel.SyncCommand_ExecutedAsync() method, then it works fine.

How to Register IndexUpdater class or how to pass dialogCoordinator there? I want to separate update class from viewmodel.

Thanks in Advance

**Environment(please complete the following information):**
 - MahApps.Metro version [v1.6.5]
 - OS: [Win10]
 - Visual Studio [2017 Comunity ]
 - .NET Framework [4.6.1]

**Comment by AndrzejKl** [comment]
One month and no one?

**Comment by punker76** [comment]
@AndrzejKl I modified your `ThisNotApplicationHangs_Executed` method and can run your sample

```csharp
private void ThisNotApplicationHangs_Executed()
{
    //var correct = sync.StartWithBaseVM().Result;
    Task.Run(async () =>
    {
        var sync = new IndexUpdater(dialogCoordinator, this);
        var result = await sync.StartWithBaseVM();
    });
}
```

Your idea was right, you need the context which was registered to show the dialogs.
