### ISSUE TITLE
VS 15.8.1 update causes "Package is not compatible"

### ISSUE THREAD

**Issue by s0ciopa7h** [MahApps/MahApps.Metro#3313]
After upgrading to VS 15.8.1  "Package is not compatible"
    MahApps.Metro version v1.6.5
    OS: Win10 1803
    Visual Studio 2017 15.8.1
    .NET Framework : net40

![2018-08-26_115254](https://user-images.githubusercontent.com/42713227/44627477-a1034e80-a926-11e8-9926-598e60a314d0.png)

**Comment by QuantumDeveloper** [comment]
Its not 15.8.1. I have 15.7.5 and see the same issue.
