### ISSUE TITLE
DataGrid show row errors

### ISSUE THREAD

**Issue by AndreasReitberger** [MahApps/MahApps.Metro#3314]
Hi, 
that's not really bug, more a question.
Is it possible to show that the row has an error or is not valid? Like shown on the image below?

![nvjlh](https://user-images.githubusercontent.com/658431/44769372-b4036200-ab64-11e8-9204-527afa694897.png)

I have a DataTable binded to a datagrid. The datatable has primary keys. When there is a violation, the new row cannot be added, what's fine. However there is no way to "catch the error" or show a visual sign that there is actually a problem with the typed in data.

Thanks!

**Comment by punker76** [comment]
@AndreasReitberger Yes, this is possible and you can see it in action at the main demo.

https://github.com/MahApps/MahApps.Metro/blob/cb9264828def32d2c55ec32dc0426c8a72aa793d/src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/DataGridExamples.xaml#L207-L209

![image](https://user-images.githubusercontent.com/658431/44769407-cc737c80-ab64-11e8-95b4-29e14c526c15.png)

**Comment by AndreasReitberger** [comment]
Perfect, that's what I was looking for. 
Can you show me where I can activate the first column with the <!>,
which is showing the error message?
I couldn't find it in the example code...
thanks a lot!

**Comment by AndreasReitberger** [comment]
Never mind, got it! Thanks!
