### ISSUE TITLE
In HambergerMenu, pane is expressed as abnormal.

### ISSUE THREAD

**Issue by xitech-kms** [MahApps/MahApps.Metro#3316]
Hi! Thank you.

In HambergerMenu, pane is expressed as abnormal.
Even if I look for other codes, I think I'm the only one to have this problem.

![image](https://user-images.githubusercontent.com/18713723/44835576-95d65880-ac6f-11e8-9d7c-57164e56ab3f.png)

```
<mah:HamburgerMenu x:Name="HamburgerMenuControl"
                        Foreground="White"
                        PaneBackground="#FF444444"
                        ItemTemplate="{StaticResource MenuItemTemplate}"
                        OptionsItemTemplate="{StaticResource MenuItemTemplate}"
                        ItemClick="HamburgerMenuControl_OnItemClick"
                        OptionsItemClick="HamburgerMenuControl_OnItemClick"
                        PaneForeground="White"
                        >
</mah:HamburgerMenu>
```

Top M3, ... The mark is still visible. It's the same weird thing to describe FontFamili as "Sego MDL2 Assets."

I want to solve this problem. Thanks.

**Comment by punker76** [comment]
@xitech-kms Please, can you publish a short sample app which shows this error? Are you using all necessary MahApps resources in your app? Here is a short [Quick-Start](https://github.com/MahApps/MahApps.Metro/wiki/Quick-Start)

**Comment by xitech-kms** [comment]
@punker76 
Omg... I refer to other content, and I can not check the contents of the link. I'm so sorry to have taken your time. Thanks.
