### ISSUE TITLE
Validation.Error Tooltip showing on the wrong side of textbox

### ISSUE THREAD

**Issue by riebrieb** [MahApps/MahApps.Metro#3320]
I encounter the problem, that the validation tooltip is showing on the left side of the textbox.

This occours only on one machine running windows 10. I cannot reproduce the issue on several other machines running the same code.

I tried to rewrite the whole controltemplate for the errortooltip. I can adjust the position with property "placement" on any machine except the windows 10 one not working. Tooltip here is always shown on the left side of the textbox no matter what placement I define.

Is there any option in Windows 10 or known issues I don't consider?

![image](https://user-images.githubusercontent.com/20015538/45148768-52786e80-b1c8-11e8-822d-d64cf5478c0e.png)

**Comment by punker76** [comment]
@riebrieb Maybe this pc has a wrong settings for Tablet: https://stackoverflow.com/a/42057716/920384

![2018-09-06_11h49_33](https://user-images.githubusercontent.com/658431/45149977-1a265f80-b1cb-11e8-9a85-829709f42bd4.png)

**Comment by riebrieb** [comment]
You are a f**** genius!

I knew it was not an error in my code. 

That worked! Thank you so much. <3
