### ISSUE TITLE
MyGet / NuGet prerelease

### ISSUE THREAD

**Issue by Nuklon** [MahApps/MahApps.Metro#3325]
It would be nice to have a MyGet feed (or have the prerelease on NuGet updated) so we could take advantage of the latest changes (such as the hamburger menu one).

**Comment by punker76** [comment]
@Nuklon You can get always the latest via this appveyor feed https://ci.appveyor.com/nuget/mahapps.metro

**Comment by Nuklon** [comment]
Cool, didn't know appveyor had that, thanks @punker76 (maybe this could be added to readme somewhere).
