### ISSUE TITLE
TimePicker

### ISSUE THREAD

**Issue by egalley** [MahApps/MahApps.Metro#3333]
When I clear the value of a TimePicker field, SelectedTime is not set to null.
The field is empty but does not become a required field.

Thanks for help.

**Comment by punker76** [comment]
@egalley Which MahApps version are you using? How are you bind to the property?

**Comment by egalley** [comment]
I use the lastest version available for nugets : 1.6.5.1

I added this to the DateExamples.xaml of the Demo

                <Controls:TimePicker Width="200"
                            Margin="0 10 0 0"
                            HorizontalAlignment="Center"
                            Controls:TextBoxHelper.AutoWatermark="True"
                            IsClockVisible="False" PickerVisibility="HourMinute" SelectedTimeFormat="Short" 
                            SelectedTime="{Binding TimePickerDate, ValidatesOnDataErrors=True, UpdateSourceTrigger=PropertyChanged, NotifyOnValidationError=True}" />

And this in MainWindowViewModel.cs

        TimeSpan? _timePickerDate;

        [Display(Prompt = "Auto resolved Watermark time")]
        public TimeSpan? TimePickerDate {
            get { return this._timePickerDate; }
            set {
                if (Equals(value, _timePickerDate)) {
                    return;
                }

                _timePickerDate = value;
                RaisePropertyChanged("TimePickerDate");
            }
        }
....
        public string this[string columnName]
...
                if (columnName == "TimePickerDate" && this.TimePickerDate == null) {
                    return "No time given!";
                }
