### ISSUE TITLE
Metro controls do not appear in Toolbox

### ISSUE THREAD

**Issue by frynio** [MahApps/MahApps.Metro#3336]
**Describe the bug**
Basically, the metro controls (style manager) etc., are not present in visual studio toolbox

**To Reproduce**
1. Toolbox doesn't have those controls (mahapps.metro installed, I already have a working app)
2. Tools -> Choose toolbox items -> WPF Compontents -> Browse
3. Browsed into packages -> Mahapps.Metro... -> lib -> net46 (project is also net46) -> select mahapps.metro.dll
4. Visual Studio tries to import and this error pops up:

![image](https://user-images.githubusercontent.com/15190180/45908326-5a592500-bdfc-11e8-8daa-4148eae35940.png)

**Environment(please complete the following information):**
 - MahApps.Metro version: 1.6.5
 - OS: Windows 10
 - Visual Studio 2017 Enterprise
 - .NET Framework 4.6.1

**Comment by punker76** [comment]
@frynio You must add the ControlzEx.dll too.
