### ISSUE TITLE
Can not open Demo application source code in vs 2015 or 2017

### ISSUE THREAD

**Issue by vaheedxp** [MahApps/MahApps.Metro#3337]
I downloaded the source code for MahApps Metro demo application but in **vs 2015** and **vs 2017** the projects are unavailable. I cloned the source code directly from the GitHub but it does not work.
Please help me.

![sshot-2](https://user-images.githubusercontent.com/34465387/45926116-4ca6bb00-bf34-11e8-9dba-42e53e9fa40e.png)

**Comment by vaheedxp** [comment]
Thanks for your reply. I will try the steps in the link.

**Comment by punker76** [comment]
@vaheedxp Were you able to compile the project now without errors?

**Comment by vaheedxp** [comment]
@punker76 Not yet completely. I updated my vs and installed the core sdk. This time i can load the project but i build the project or restore the packages, it unloads the project. I think i have problems with .paket.

**Comment by vaheedxp** [comment]
@punker76 It can't restore the .NETFramework 47 dependency.

**Comment by vaheedxp** [comment]
@punker76 Finaly i did it. I installed the .netframework 4.7 devpack and now everything is ok. Thanks @punker76.
