### ISSUE TITLE
StrongName signed assembly? Hey, it's 2018...

### ISSUE THREAD

**Issue by Jehoel** [MahApps/MahApps.Metro#3339]
The NuGet package binaries were signed before version 1.6, where the decision was made to stop signing the project because of the (then) realities of the .NET Core ecosystem:

> https://github.com/MahApps/MahApps.Metro/issues/3029
>  
> MahApps v1.6.0 will not be strong-named.

...but now it's 2018 and things have changed again! The author of the (in)famous "Still strong naming your assemblies?" blog article has now done an about-face and now advocates strong-naming your assemblies again in an update to that same blog post:

> https://www.pedrolamas.com/2016/03/01/still-strong-naming-your-assemblies-you-do-know-its-2016-right/  
>
> Though the information and concerns in this blog post are still very true, I’ve actually had a change of heart and **I’m now advocating to Start Strong-Naming your Assemblies!!**

Microsoft's corefx team also now strong-names and while they say not every assembly needs it, it's still useful: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md  

-----------

I did try to use the recommended **StrongNamer** NuGet package to strong-name the assembly during the build process, but I get build errors when I use it on all of my machines as-directed. I filed a bug report with StrongNamer that still has not been addressed: https://github.com/dsplaisted/strongnamer/issues/23 - so using StrongNamer is not an option for me - so for now I'm having to either build MahApps.Metro from source myself, or use the last strong-named version of MahApps.Metro, neither of which is ideal.

**Comment by pedritin91** [comment]
> > [b9ab758](https://github.com/MahApps/MahApps.Metro/commit/b9ab758aa8bb2d4514a55ee779034d564ddc7774)
> > `<SignAssembly>True</SignAssembly>`
> 
> Wow, thank you :D

What did you do @Jehoel?
