### ISSUE TITLE
Build fail when running the demo application "MahApps.Metro.Demo" - Could not load file or assembly ControlzEx

### ISSUE THREAD

**Issue by yousufctec** [MahApps/MahApps.Metro#3340]
Build fail when running the demo application.
![image](https://user-images.githubusercontent.com/12121901/46056316-9b499480-c182-11e8-8bd8-70df4437d330.png)

**Comment by punker76** [comment]
@yousufctec Please, provide more information like: which MahApps version.

**Comment by yousufctec** [comment]
Just downloaded the project this morning and ran it. Just same as git
version.

**Comment by punker76** [comment]
@yousufctec Which project? If you use the latest dev branch or the latest MahApps alpha then you need a newer [ControlzEx](https://www.nuget.org/packages/ControlzEx/4.0.0-alpha0176) version now. It seems like that NuGet doesn't update the dependency correctly.

**Comment by punker76** [comment]
@yousufctec The MahApps v1.6.5 is pointed to ControlzEx v3.0.2.4

**Comment by yousufctec** [comment]
@punker76 Can you please download the current version from git and give it a try to run the project "MahApps.Metro.Demo"? Thanks!

**Comment by jhasenfuss** [comment]
Hello, ive downloaded the latest version as a zip file from github and i get the exact same error as @yousufctec 
The message is in german, but the error is the same.
![image](https://user-images.githubusercontent.com/15813447/46078647-0dc37000-c195-11e8-9cc3-3639274c11ac.png)

**Comment by punker76** [comment]
@jhasenfuss It's the missing strong-name IconPacks dll. An updated package is coming soon...

**Comment by Logic-Bits** [comment]
current Fix: after installing MetroWindow manually downgrade ControlzEx to last stable Version!

**Comment by punker76** [comment]
@Logic-Bits or use the latest alpha version of MahApps.IconPacks which is now also strong named and doesn't has the ControlzEx dependency
