### ISSUE TITLE
Validation disappear on tab item change

### ISSUE THREAD

**Issue by Pekshev** [MahApps/MahApps.Metro#3344]
All in gif
![validation](https://user-images.githubusercontent.com/12638819/46248383-4a0b0080-c421-11e8-8129-8817976913a1.gif)

**Comment by Pekshev** [comment]
I'm found how to fix it in my project - http://www.andyfrench.info/2014/03/validation-adorners-not-displaying-in.html
Maybe somehow it will be possible to apply this solution in the library itself?

**Comment by punker76** [comment]
The AdornerDecorator must be placed close to the content. Placing around the ContentPresenter of e.g. the TabItem doesn't work.
