### ISSUE TITLE
NumericUpDown for values less than 1

### ISSUE THREAD

**Issue by EMostafaAli** [MahApps/MahApps.Metro#3345]
**Describe the bug**
I noticed that entering values less than 1 behaves unexpectedly. If I enter 0.4 it works fine but If I tried .4 (without leading zero), the value changed to 4 (decimal point removed) even if numeric input mode set to All.
 
**To Reproduce**
1. a numericupdown that binds to double property
2. Try to enter value less than 1 without leading zero (e.g. .4 or .3)
3. Leave the textbox.

**Expected behavior**
If I enter .4, I expected to be converted to 0.4

**Environment(please complete the following information):**
 - MahApps.Metro version 1.6.5
 - OS: Win10 1803
 - Visual Studio 2017 15.8.5
 - .NET Framework 4.6.1

**Comment by punker76** [comment]
@EMostafaAli This is fixed in the latest dev source and will be published with v2.0
