### ISSUE TITLE
Glow size like win10

### ISSUE THREAD

**Issue by Pekshev** [MahApps/MahApps.Metro#3346]
Glow looks bad.
![screenshot_3](https://user-images.githubusercontent.com/12638819/46260048-e3054e80-c4e9-11e8-897b-71140bb663e9.png)
How can i change it?

**Comment by punker76** [comment]
@Pekshev Yes, it's different to the Windows OS shadow. It's a glow with a color. In v2.0 you can change this by setting the ResizeBorderThickness.
