### ISSUE TITLE
PowerShell and MahApps assambly 1.6.5.0, only Net4.0 versjon works.

### ISSUE THREAD

**Issue by nilssol** [MahApps/MahApps.Metro#3347]
Getting this message when trying to use MahApps assembly for Net 4.5, 4.6 or 4,7. 

Computer has Net 4.7 installed.

Exception calling "Load" with "1" argument(s): "The invocation of the constructor on type 'MahApps.Metro.Controls.MetroWindow' that matches the specified binding constraints threw an exception."

**Comment by nilssol** [comment]
Solved the issue.
There was som incorrect .Net version of the ControlzEx assambly loaded into the script.

**Comment by kantzy** [comment]
I am facing the same issue. Would you be able to guide me how to fix it?
Also i have been using System.Windows.Interactivity.dll and not ControlzEx.dll. I have tried loading both the dll files but still get the same error.

**Comment by nilssol** [comment]
Hi

ControlzEx.dll 4.0 is a dependency of MahApps 1.6.5, you need to make sure you have the right version of the assembly's.

**Comment by punker76** [comment]
@kantzy @nilssol MahApps v1.6.5 depends on ControlzEx (>= 3.0.2.4 && < 4.0.0) It doesn't includes 4.xx

![image](https://user-images.githubusercontent.com/658431/52326238-3af81880-29e8-11e9-85ff-7e78def4b48a.png)

**Comment by smunger25216** [comment]
What about MahApps 2.4.3?  VS Studio works fine but when porting to VS Code it errors out as seen   below...   Windows 10 with .Net 4.8;   When I downgrade to MahApp 1.6.5 and lower Controlz it works but missing many new features.  

 GAC    Version        Location
---    -------        --------
True   v4.0.30319     C:\Windows\Microsoft.Net\assembly\GAC_MSIL\MahApps.Metro\v4.0_4.0.0.0__31bf3856ad364e35\MahApps.Metro.dll
True   v4.0.30319     C:\Windows\Microsoft.Net\assembly\GAC_MSIL\ControlzEx\v4.0_4.0.0.0__31bf3856ad364e35\ControlzEx.dll
True   v4.0.30319     C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Interactivity\v4.0_4.0.0.0__31bf3856ad364e35\System.Windows.Interactivity.dll

Exception calling "Load" with "1" argument(s): "The invocation of the constructor on type 'MahApps.Metro.Controls.MetroWindow' that matches the specified binding constraints threw an 
exception."
At C:\Users\smunger.ESXILABS.000\OneDrive\METROUI.ps1:63 char:1
+ $Form = [Windows.Markup.XamlReader]::Load($reader).
