### ISSUE TITLE
How to change button font size in dialog?

### ISSUE THREAD

**Issue by yuzifu** [MahApps/MahApps.Metro#3353]
I use DialogCoordinator.Instance.ShowMessageAsync() show a dialog, I can change title/message font size of dialog with MetroDialogSettings, but I can't find a way to change button font size。
Is there any way to do this?

**Comment by yuzifu** [comment]
I use follow code to change font size of dialog's button:
```<Style TargetType="{x:Type Dialogs:MessageDialog}" BasedOn="{StaticResource {x:Type Dialogs:BaseMetroDialog}}">
    <Style.Resources>
        <Style BasedOn="{StaticResource MetroFlatButton}" TargetType="{x:Type Button}">
            <Setter Property="FontSize" Value="16" />
        </Style>

        <Style x:Key="AccentedDialogSquareButton"
                BasedOn="{StaticResource MetroFlatButton}"
                TargetType="{x:Type Button}">
            <Setter Property="FontSize" Value="16" />
        </Style>

        <Style x:Key="AccentedDialogHighlightedSquareButton"
                BasedOn="{StaticResource MetroFlatButton}"
                TargetType="{x:Type Button}">
            <Setter Property="FontSize" Value="16" />
        </Style>
    </Style.Resources>
</Style>```

**Comment by FlashDeviant** [comment]
It would be handy to get this implemented as a property of MetroDialogSettings similar to `DialogTitleFontSize`

**Comment by timunie** [comment]
Hi @FlashDeviant,

i cannot promise anything, but the chance for this feature to be implemented will be higher if you make a feature request and discribe how you want the feature be implemented. The chance will be even higher if you make a PR 🥇 

Happy coding
Tim
