### ISSUE TITLE
MetroWindow as a pure Window Style

### ISSUE THREAD

**Issue by ironhide91** [MahApps/MahApps.Metro#3354]
**Is your feature request related to a problem? Please describe.**
I want to use Mahapps.Metro for styling my app.
This is unique situation where, the app is composed of vairous WPF User Control class libraries.
Our firm uses a custom bootstrapper to launch these components.
It automatically creates a shell window for the app and host's the views inside it.
I cannot touch the bootstrapper in anyway.

**Describe the solution you'd like**
What I want is a standalone Window style, which targets a Window object.
I just need the basic MetroWindow style like window tile bar along with min, max & close buttons.

**Comment by punker76** [comment]
@ironhide91 This is currently not possible. The MetroWindow does many code behind action which is not possible to do only with a style.
