### ISSUE TITLE
DataGrid with rowheader

### ISSUE THREAD

**Issue by EMostafaAli** [MahApps/MahApps.Metro#3358]
**Describe the bug**
It looks like there is a problem with the Datagrid style, I was unable to show row header with the following code:

```
<DataGrid Grid.Row="0" Grid.Column="0" ItemsSource="{Binding Parameters}" GridLinesVisibility="All">
            <DataGrid.RowHeaderTemplate>
                <DataTemplate>
                    <Grid>
                        <CheckBox IsChecked="False"/>
                    </Grid>
                </DataTemplate>
            </DataGrid.RowHeaderTemplate>
</DataGrid>
```
The result is as shown in this picture 
![image 002](https://user-images.githubusercontent.com/11354102/47475136-84c14800-d7d7-11e8-9e26-689bd9e02450.png)

However, by removing the following line, 
`                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
`
the datagrid looks like this 
![image 001](https://user-images.githubusercontent.com/11354102/47475179-a1f61680-d7d7-11e8-9485-4c0f86dd5106.png)

**To Reproduce**
1. Create a wpf app and style it as in Mahapps start guide
2. Add datagrid with the previous code shown.

**Expected behavior**
It should show a datagrid with row header (checkbox)

**Screenshots**
Please see above.

**Environment(please complete the following information):**
 - MahApps.Metro version 1.6.5
 - OS: Win10 1803
 - Visual Studio 2017
 - .NET Framework 4.6.1

**Comment by punker76** [comment]
@EMostafaAli The MahApps default style for `DataGrid` sets the `HeadersVisibility` to `Column` and doesn't set the `RowHeaderWidth`. If you want to see the row headers then change these properties on your `DataGrid` like

```xaml
<DataGrid
  Grid.Row="0"
  Grid.Column="0"
  ItemsSource="{Binding Parameters}"
  HeadersVisibility="All"
  RowHeaderWidth="20"
  GridLinesVisibility="All">
            <DataGrid.RowHeaderTemplate>
                <DataTemplate>
                    <Grid>
                        <CheckBox IsChecked="False"/>
                    </Grid>
                </DataTemplate>
            </DataGrid.RowHeaderTemplate>
</DataGrid>
```
