### ISSUE TITLE
Numbericupdown data binding error

### ISSUE THREAD

**Issue by jackylinwh** [MahApps/MahApps.Metro#3359]
**Describe the bug**
When the keyboard is used to change the value, the Numbericupdown control produces a data binding error.

**To Reproduce**
1. My xaml use NumericUpDown control like below:

<Controls:NumericUpDown Minimum="1" Maximum="8" TextAlignment="Left" Value="{Binding Path=SignalWave, Mode=TwoWay}"  UpDownButtonsWidth="32" >

Note: The Maximum is 8.

2. And my the binding source property defind like below:

public int SignalWave
{
	get
	{
		return mSetting.ETConfig.SignalWave + 1;
	}
set
{
		if (mSetting.ETConfig.SignalWave + 1 != value)
		{
			mSetting.ETConfig.SignalWave = value - 1;
			Console.WriteLine("Current signal wave {0}", mSetting.ETConfig.SignalWave);
			OnPropertyChanged("SignalWave");
		}
	}
}

3. Change the value by keyboard, i.e. you can input 9
4. Error: The 'SignalWave' is changed to 9, but 9 is an invalid value
5. The control won't change to a valid value until it lost focus,even i press ENTER key.

**Comment by punker76** [comment]
@jackylinwh Why do you inc and dec in code behind? The NUD do this for you.
