### ISSUE TITLE
An error occurred while finding the resource dictionary

### ISSUE THREAD

**Issue by FinlayDaG33k** [MahApps/MahApps.Metro#3361]
**Describe the bug**
I have tried installing the package using `Install-Package MahApps.Metro -Pre`, this installs version `2.0.0-alpha0104`(version `1.6.5` throws all kinds of errors in my face).  

When going through the quickstart, I get to the step where I have to add my ResourceDictionaries.
This is what my `App.xaml` looks like:
```xml
<Application x:Class="_9AnimeDl.App"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:local="clr-namespace:_9AnimeDl"
             StartupUri="DownloadDeps.xaml">
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <!-- MahApps.Metro resource dictionaries. Make sure that all file names are Case Sensitive! -->
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Colors.xaml" />
                <!-- Accent and AppTheme setting -->
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/Blue.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/BaseLight.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>
</Application>
```

This, however throws the following errors:
> An error occurred while finding the resource dictionary "pack://application:,,,/MahApps.Metro;component/Styles/Accents/Blue.xaml".

> An error occurred while finding the resource dictionary "pack://application:,,,/MahApps.Metro;component/Styles/Accents/BaseLight.xaml".

Removing the lines that specify those accents gets rid of the error (and the app runs just fine).

**Expected behavior**
No errors showing up and the app compiling just fine

**Screenshots**

![](https://i.imgur.com/XhBbFbt.png)
![](https://i.imgur.com/9nIXSQN.png)

**Environment(please complete the following information):**
 - MahApps.Metro version: 2.0.0-alpha0104
 - OS: Win10 Pro x64 build 1803
 - Visual Studio: 2017 Community 15.8.2
 - .NET Framework: 4.6.1 (Target)

**Comment by punker76** [comment]
@FinlayDaG33k This was a breaking change for v2.0 (#3296, #3350) which is not yet official documented. For now I changed the wiki [quick start ](https://github.com/MahApps/MahApps.Metro/wiki/Quick-Start). The detailed documentation will be published soon.

**Comment by FinlayDaG33k** [comment]
Thanks, this solved the issue for me :)
