### ISSUE TITLE
 Window jitters

### ISSUE THREAD

**Issue by 306room** [MahApps/MahApps.Metro#3362]
**Describe the bug**
When 
After the window is maximized, hold down the mouse and drag in the title bar, and the window will be abnormal, when **enabled: Prevent windows from being automatically arranged when moved to the edge of the screen** on Control Panel (Control Panel, navigate to Ease of Access Center → Change how your mouse works)

**To Reproduce**
1. from control panel, enabled: Prevent windows from being automatically arranged when moved to the edge of the screen
2. Run MahApps.Metro.Demo.exe
3. Maximum it
4. mouse pressed titlebar, and move
5. bug appears

**Screenshots**
![image](https://user-images.githubusercontent.com/7467289/48037170-3c763280-e1a6-11e8-8ea5-aefda599cb95.png)

![image](https://user-images.githubusercontent.com/7467289/48037086-f4571000-e1a5-11e8-8d11-8f7c8c97d8c8.png)

**Environment(please complete the following information):**
 - MahApps.Metro version [v1.6.0 - v2.0]
 - OS: [Win7]

**Comment by punker76** [comment]
@306room mh, I don't have a Win7, so maybe I can not investigate this issue. I tested it under Win10 and can not see such issue (as far as I understand your described issue)

**Comment by punker76** [comment]
@306room Is it possible you record this issue to see it in action?
