### ISSUE TITLE
Range slider, won't response to left or right thumb drag when the range is close to min\max

### ISSUE THREAD

**Issue by Zeleksonob** [MahApps/MahApps.Metro#3364]
As Described in the title ,when the values are both close to the min max values , ranger silder won't response to value dragging both from the left and right thumb.

you could repreduce it also with draging only the left value to the max slider value and vice versa

![capture](https://user-images.githubusercontent.com/7282333/48124485-1c697080-e285-11e8-84f4-fd2bdc98281d.PNG)

**Environment(please complete the following information):**
 - MahApps.Metro version 1.6.5.1
- windows 10
 - Visual Studio  2017 
 - .NET Framework 4.6.2

**Comment by punker76** [comment]
@Zeleksonob I can't reproduce this issue, so please, can you create a short sample which shows this issue? Thx.
