### ISSUE TITLE
Wrong foreground/text color with dark theme under frame

### ISSUE THREAD

**Issue by realivanjx** [MahApps/MahApps.Metro#3365]
**Describe the bug**
When im using this library's dark theme (BaseDark), i noticed that text color is not converted/applied properly if the control is under a Frame (currently only textblock faced this issue). Please fix this.

**To Reproduce**
1. Apply base dark theme.
2. Add a frame under mainwindow.
3. Add a new page.
4. Add a textblock on that newly created page.
5. Load that page under mainwindow's Frame.
6. Run the app.

**Expected behavior**
Textblock control text color converted properly to match the theme (should be white).

**Screenshots**

Running app result:
![screenshot_34](https://user-images.githubusercontent.com/12814796/48135778-72afd100-e2d0-11e8-9b50-3cf0a816bf3a.png)

**Environment:**
 - MahApps.Metro version v1.6.5

App.xaml contents:
```
<Application x:Class="xtreme_unlock_gui_new.App"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:local="clr-namespace:xtreme_unlock_gui_new"
             Startup="Application_Startup">
    <Application.Resources>
        <ResourceDictionary>
            <FontFamily x:Key="FontAwesomeSolid">Resources/Fonts/fa-solid.otf#Font Awesome 5 Free Solid</FontFamily>
            <FontFamily x:Key="FontAwesomeBrand">Resources/Fonts/fa-brands.otf#Font Awesome 5 Brands Regular</FontFamily>

            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Colors.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/Blue.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/BaseDark.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.AnimatedSingleRowTabControl.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/FlatButton.xaml" />                
                <ResourceDictionary Source="Styles/BlackDataGridStyle.xaml" />
                <ResourceDictionary Source="Styles/HamburgerMenuStyle.xaml" />

                <ResourceDictionary Source="Resources/Languages/EN.xaml"></ResourceDictionary>
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>
</Application>
```

**Comment by punker76** [comment]
@realivanjx To fix this issue just add the style to the page `Style="{DynamicResource MetroPage}"`. This is the same WPF issue like if you want to use a default style for a Window. I can fix this only by adding the style explicit to the Page or I create a derived class like `MetroPage` which get's the style with the DefaultStyle key.

**Comment by realivanjx** [comment]
Is `MetroPage` style available on version `1.6.5`? I tried but vs2017 seems to not detecting it

**Comment by punker76** [comment]
@realivanjx Yes, it's added via Controls.xaml.

**Comment by realivanjx** [comment]
Is it under this? I use this for `MetroWindow` but idk for `MetroPage`:

```
xmlns:Controls="clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro"
```

**Comment by punker76** [comment]
@realivanjx It's a style not a Control.

**Comment by realivanjx** [comment]
Thanks. It runs successfully and fixes the issue but vs2017 somehow throws an error:
```
'Page' TargetType does not match type of element 'PageInstance'
```

Is that normal?

**Comment by punker76** [comment]
@realivanjx I don't know, this is related to which VS you use and/or which SDK...
