### ISSUE TITLE
HamburgerMenu doesn't handle DataContext inheritance for Menu items

### ISSUE THREAD

**Issue by damusthe** [MahApps/MahApps.Metro#3367]
I'm trying tu use HamburgerMenu with custom UserControls as items.
Unfortunately, the Datacontext link is not propagated to the items usercontrol.

```xaml
<Border Grid.Column="0"
                Margin="10 10 0 10"
                BorderBrush="{DynamicResource GrayBrush7}"
                BorderThickness="1">
		<Controls:HamburgerMenu x:Name="HamburgerMenuControl"
                                    HamburgerWidth="40"
                                    IsPaneOpen="True"
									ItemInvoked="HamburgerMenuControl_OnItemInvoked"
									ItemTemplate="{StaticResource MenuItemTemplate}"
                                    OptionsItemTemplate="{StaticResource MenuItemTemplate}"
                                    SelectedIndex="2"
                                    Style="{StaticResource HamburgerMenuCreatorsStyle}"
                                    VerticalScrollBarOnLeftSide="False">
			<!--  Items  -->
			<Controls:HamburgerMenu.ItemsSource>
				<Controls:HamburgerMenuItemCollection>
					<Controls:HamburgerMenuIconItem Icon="{iconPacks:Modern Kind=Clean}" Label="Clean">
						<Controls:HamburgerMenuIconItem.Tag>
								<views:Clean/>
							</Controls:HamburgerMenuIconItem.Tag>
					</Controls:HamburgerMenuIconItem>
```

I added in code behind the following event 

```csharp
private void HamburgerMenuControl_OnItemInvoked(object sender, HamburgerMenuItemInvokedEventArgs e)
		{
			HamburgerMenuControl.Content = e.InvokedItem;
			// Set the DataContext to the UserControl created dynamically when clicking on the menu
			((e.InvokedItem as HamburgerMenuIconItem).Tag as UserControl).DataContext = this.DataContext;
		}
```

This solve the problem, but not for the first time. Indeed when the application starts, the event is not invoked.
Adding this kind of XAML code doesn't work also.
```xaml
DataContext="{Binding RelativeSource={RelativeSource AncestorType=UserControl}}"
```

Any idea ?
Thank you

**Comment by punker76** [comment]
@damusthe Can you create a short sample which shows your issue? Thx!

**Comment by punker76** [comment]
@damusthe ping

**Comment by Laurnz** [comment]
I have the exact same Problem. I need some views in the HamburgerMenu to bind to the same ViewModel als to control the code is in, but setting the DataContext is doing nothing in the XAML code.

Currently the code looks something like this:
`
<controls:HamburgerMenu x:Name="createProject_hamburgerMenuMain"
        ItemTemplate="{DynamicResource Global_Template_HamburgerMenuItem}"
        OptionsItemTemplate="{DynamicResource Global_Template_HamburgerMenuItem}"
        Style="{DynamicResource Global_Style_HamburgerMenuCreators}"
        SelectedIndex="0"
        ItemClick="CreateProject_hamburgerMenuMain_ItemClick">

    
    <controls:HamburgerMenu.ItemsSource>
        <controls:HamburgerMenuItemCollection>
            <controls:HamburgerMenuGlyphItem Glyph="&#xE946;" Label="Project info">
                <controls:HamburgerMenuGlyphItem.Tag>
                    <views:View_CreateProject_General DataContext="{Binding}"/>
                </controls:HamburgerMenuGlyphItem.Tag>
            </controls:HamburgerMenuGlyphItem>

            <controls:HamburgerMenuGlyphItem Glyph="&#xE71D;" Label="Jobs">
                <controls:HamburgerMenuGlyphItem.Tag>
                    <views:View_CreateProject_Jobs DataContext="{Binding}" />
                </controls:HamburgerMenuGlyphItem.Tag>
            </controls:HamburgerMenuGlyphItem>
        </controls:HamburgerMenuItemCollection>
    </controls:HamburgerMenu.ItemsSource>

    
    <controls:HamburgerMenu.OptionsItemsSource>
        <controls:HamburgerMenuItemCollection>
            <controls:HamburgerMenuGlyphItem Glyph="&#xE713;" Label="Settings">
            </controls:HamburgerMenuGlyphItem>
        </controls:HamburgerMenuItemCollection>
    </controls:HamburgerMenu.OptionsItemsSource>

    
    <controls:HamburgerMenu.ContentTemplate>
        <DataTemplate DataType="{x:Type controls:HamburgerMenuItem}">
            <ContentControl x:Name="TheContent"
                Grid.Row="1"
                Focusable="False"
                Foreground="{DynamicResource BlackBrush}"
                Content="{Binding Tag}" />

        </DataTemplate>
    </controls:HamburgerMenu.ContentTemplate>


</controls:HamburgerMenu >
`

If I just put my view in the code without the HamburgerMenu everything is binding fine:
`<views:View_CreateProject_General DataContext="{Binding}" />`

**Comment by Laurnz** [comment]
I found the "problem" in this StackOverflow thread: [https://stackoverflow.com/questions/15494226/cannot-find-source-for-binding-with-reference-relativesource-findancestor](url)

According to the awnser is the HamburgerMenuGlyphItem is not be part of the visual or logical tree, there is no binding ancestor for the DataContext. i.e. the binding has no source to bind to. So to work around this you have to add a binding proxy.

Is this something that is fixable or just the way the control works?

**Comment by SkinnySackboy** [comment]
I have just come across precisely the same issue, same symptoms as OP. The bizarre thing is that if I use Snoop and hit the control suddenly the DataContext gets set correctly. I’ve tried the binding proxy trick, it works but like the OP said not the first time, unless I use Snoop to “prod” it into action.

**Comment by punker76** [comment]
There are 3 options to solve this "known" problem:

System.Windows.Data Error: 2 : Cannot find governing FrameworkElement or FrameworkContentElement for target element. BindingExpression:Path=SomeProperty; DataItem=null; target element is ‘SomeElement’ (HashCode=123456789); target property is ‘AProperty’ (type ‘TypeOfTheProperty’)

This could be solved...

- by using a [BindingProxy](https://thomaslevesque.com/2011/03/21/wpf-how-to-bind-to-data-when-the-datacontext-is-not-inherited/)
- by using [x:Reference](https://xstatic2.wordpress.com/2011/12/16/cannot-find-governing-frameworkelement/)
```xaml
<Controls:HamburgerMenuIconItem x:Name="AboutOption"
                                Command="{Binding Source={x:Reference theHamburgerMenuElement}, Path=DataContext.ShowHamburgerAboutCommand}"
                                Label="About">
    <Controls:HamburgerMenuIconItem.Icon>
        <iconPacks:PackIconMaterial Width="22"
                                    Height="22"
                                    HorizontalAlignment="Center"
                                    VerticalAlignment="Center"
                                    Kind="Help" />
    </Controls:HamburgerMenuIconItem.Icon>
</Controls:HamburgerMenuIconItem>
```
- or simply adding the x:Name to the element [SO](https://stackoverflow.com/a/7632833/920384)
```xaml
<Controls:HamburgerMenuIconItem x:Name="AboutOption"
                                Command="{Binding RelativeSource={RelativeSource FindAncestor, AncestorType=Controls:HamburgerMenu}, Path=DataContext.ShowHamburgerAboutCommand}"
                                Label="About">
    <Controls:HamburgerMenuIconItem.Icon>
        <iconPacks:PackIconMaterial Width="22"
                                    Height="22"
                                    HorizontalAlignment="Center"
                                    VerticalAlignment="Center"
                                    Kind="Help" />
    </Controls:HamburgerMenuIconItem.Icon>
</Controls:HamburgerMenuIconItem>
```

**Comment by kmark17** [comment]
> I have the exact same Problem. I need some views in the HamburgerMenu to bind to the same ViewModel als to control the code is in, but setting the DataContext is doing nothing in the XAML code.
> 
> Currently the code looks something like this:
> 
> ```
> <controls:HamburgerMenu x:Name="createProject_hamburgerMenuMain"
>         ItemTemplate="{DynamicResource Global_Template_HamburgerMenuItem}"
>         OptionsItemTemplate="{DynamicResource Global_Template_HamburgerMenuItem}"
>         Style="{DynamicResource Global_Style_HamburgerMenuCreators}"
>         SelectedIndex="0">
> 
>     
>     <controls:HamburgerMenu.ItemsSource>
>         <controls:HamburgerMenuItemCollection>
>             <controls:HamburgerMenuGlyphItem Glyph="&#xE946;" Label="Project info">
>                 <controls:HamburgerMenuGlyphItem.Tag>
>                     <views:View_CreateProject_General DataContext="{Binding}"/>
>                 </controls:HamburgerMenuGlyphItem.Tag>
>             </controls:HamburgerMenuGlyphItem>
> 
>             <controls:HamburgerMenuGlyphItem Glyph="&#xE71D;" Label="Jobs">
>                 <controls:HamburgerMenuGlyphItem.Tag>
>                     <views:View_CreateProject_Jobs DataContext="{Binding}" />
>                 </controls:HamburgerMenuGlyphItem.Tag>
>             </controls:HamburgerMenuGlyphItem>
>         </controls:HamburgerMenuItemCollection>
>     </controls:HamburgerMenu.ItemsSource>
> 
>     
>     <controls:HamburgerMenu.ContentTemplate>
>         <DataTemplate DataType="{x:Type controls:HamburgerMenuItem}">
>             <ContentControl x:Name="TheContent"
>                 Grid.Row="1"
>                 Focusable="False"
>                 Foreground="{DynamicResource BlackBrush}"
>                 Content="{Binding Tag}" />
> 
>         </DataTemplate>
>     </controls:HamburgerMenu.ContentTemplate>
> </controls:HamburgerMenu >
> ```
> 
> If I just put my view in the code without the HamburgerMenu everything is binding fine:
> 
> ```
> <views:View_CreateProject_General DataContext="{Binding}" />
> ```

Can you provide the code for how you did it?
