### ISSUE TITLE
MetroWindow.ShowMessageAsync overlapped by frame content

### ISSUE THREAD

**Issue by AndreasReitberger** [MahApps/MahApps.Metro#3368]
**Describe the bug**
I'm using the "Frame" object to load a html file located in the project folder. Moreover I have implemented the "OnCloseMessage" from your template.

Now, if I click the close button of the main form, the dialog asking to quit is overlapped by the content in the Frame object.

**To Reproduce**
1. Create a MetroWindow form
2. add the HamburgerMenu to it
3. Load a UserControl / page with a Frame inside (maybe load a html file too).
4. Get the parent MetroWindow from the UserControl currently shown from the Hamburger Menu
5. Click the close button (make sure to use the function to show a message on closing from the Mahapps template) 
See the screenshot for more information

**Expected behavior**
The Dialog should overlap the frames content.

**Screenshots**
![image](https://user-images.githubusercontent.com/2952443/48401752-275f4d80-e72a-11e8-9839-b1d44505c2ad.png)

**Environment(please complete the following information):**
 - MahApps.Metro version 1.6.5
 - OS: Win7 32 Bit
 - Visual Studio 2017 15.7.1
 - .NET Framework 4.5

Thanks for helping out!

**Comment by punker76** [comment]
@AndreasReitberger The Dialogs are always shown above the whole window. It's currently not possible to show it on a different "container" position.

**Comment by AndreasReitberger** [comment]
@punker76 
Yes, that would be fine when the dialog is shown above the whole window. However the frame, which should be shown underneath the dialog, is shown above.

Here is a screenshot of the window when the Message is not shown.
Here you can see the "EULA" in a Frame object.
![image](https://user-images.githubusercontent.com/2952443/48406917-f4bb5200-e735-11e8-95af-64aa46ce331e.png)

And here is the Dialog on another Hamburger Menu Item. Here it's working fine.
![image](https://user-images.githubusercontent.com/2952443/48406969-11578a00-e736-11e8-9b6d-b026d8d4d23e.png)

Only when a Frame object with a HTML page is in the UserControl, the Frame content overlaps the dialog.

Hope this helps understanding me ;)

Best,
Andreas

**Comment by AndreasReitberger** [comment]
@punker76 
I checked the FAQ, but I did not set the "AllowsTransparency " to true.

> By default, the vanilla Window class and MahApps.Metro's MetroWindow has AllowsTransparency set to false. If you set this in MahApps.Metro's MetroWindow initialized event to true you will get this issue.

Does this solution still work for me? Thanks a lot!

**Comment by punker76** [comment]
@AndreasReitberger In your case it's this one

> What you are facing is an issue colloquially called the Airspace issue. Due to the different underlying graphical engines used in WinForms (GDI) and WPF (DirectX and such), there are some interop issues. Sometimes, your controls appear will be invisible. Sometimes, your WinForms control may overlap your WPF controls.

**Comment by AndreasReitberger** [comment]
@punker76 
Thanks, when I implement the fix it's working at runtime, however the XAML Designer in VS 2017 crashes once I open the specific XAML file.
I guess I rather work arround the Frame instead of using the provided fix.

Thanks for helping. I'll close the issue.
