### ISSUE TITLE
I want the title bar, status bar, and border style of the form to remain unchanged after the form activation state becomes inactive

### ISSUE THREAD

**Issue by GanZhiXiong** [MahApps/MahApps.Metro#3371]
Active state
![image](https://user-images.githubusercontent.com/27394631/48590913-65ec4680-e97c-11e8-8ec8-c08c5513657f.png)

State when inactive（I want and maintain the activation style）
![image](https://user-images.githubusercontent.com/27394631/48590921-6e448180-e97c-11e8-8139-f64606b60ce8.png)

My English is not very good, if you do not understand it please ask, I am looking forward to your answer！ Thanks！

**Comment by punker76** [comment]
@GanZhiXiong You can change these properties to prevent this behavior

```xaml
NonActiveWindowTitleBrush="{DynamicResource WindowTitleColorBrush}"
NonActiveBorderBrush="{DynamicResource AccentColorBrush}"
```
or
```xaml
NonActiveGlowBrush="{DynamicResource AccentColorBrush}"
```

**Comment by GanZhiXiong** [comment]
@punker76   Thank you so much for solving my problem!👍👍👍
