### ISSUE TITLE
SelectedDate showing incorrect in editor in DateTimePicker

### ISSUE THREAD

**Issue by Raghava56** [MahApps/MahApps.Metro#3373]
Hi,

am using mvvm the actual **selectedDate** is **7/3/2018 4:07:35 PM** but in the control showing wrong date. See below image.
![image](https://user-images.githubusercontent.com/25173908/48623086-bab8ad00-e9ce-11e8-88ed-4a608bcad6ec.png)

But in the popup it is showing correct.

![datetimepicker](https://user-images.githubusercontent.com/25173908/48623004-7a592f00-e9ce-11e8-8011-f09531bb23a4.PNG)

I tried without using mvvm there is no issue in that,but using mvvm issue found.

**Control Code**
`<controls:DateTimePicker  Width="180" Focusable="False" Margin="0,6,0,8" SelectedDate="{Binding StartFrom,UpdateSourceTrigger=PropertyChanged}" DisplayDateStart="{Binding StartFrom}" IsClockVisible="False" />`

can someone help me about this.

Thanks and Regards,

**Comment by punker76** [comment]
@Raghava56 Can you post the MahApps version? thx

**Comment by Raghava56** [comment]
@punker76 MahApps versions is V1.5.0

**Comment by punker76** [comment]
@Raghava56 Ok, please, try v1.6.5

**Comment by punker76** [comment]
@Raghava56 ping
