### ISSUE TITLE
Application start theme color problem

### ISSUE THREAD

**Issue by oeksymz** [MahApps/MahApps.Metro#3378]
Hello friends,
My application start theme color problem. Theme change procedure.

![2018-11-23-17-56-14](https://user-images.githubusercontent.com/45292151/48950814-805e8b00-ef4d-11e8-810c-634843552c81.png)

![2018-11-23-17-57-02](https://user-images.githubusercontent.com/45292151/48950766-586f2780-ef4d-11e8-828b-4f7279fa6291.png)

![2018-11-23-18-31-45](https://user-images.githubusercontent.com/45292151/48951300-147d2200-ef4f-11e8-9966-49847e3e3549.png)

Application start

![2018-11-23-17-54-12](https://user-images.githubusercontent.com/45292151/48951362-58702700-ef4f-11e8-89ac-da193f49e6ae.png)

Color change button click problem fixing.

![2018-11-23-17-54-30](https://user-images.githubusercontent.com/45292151/48951543-011e8680-ef50-11e8-8f9c-626afb076e82.png)

**Environment**

1. MahApps.Metro version [v1.6.5]
2. OS: [Win10]
3. Visual Studio [2017 Comunity 15.8.6]
4. .NET Framework [4.6.2]

**Comment by punker76** [comment]
@oeksymz Hi, are you saving these 2 values? It seems so if I look to the screenshots. If you start without any saved value and use the Theme manager to get the current values for accent and rheme then it's recommend to leave a default accent and theme at the App.xaml.

**Comment by oeksymz** [comment]
Thank you @punker76.
My problem fixed. 

![2018-11-24-19-55-36](https://user-images.githubusercontent.com/45292151/48970920-0d741380-f024-11e8-8345-c61be8308311.png)

Application start theme color problem fixed. But different problem.

Application start no problem

![2018-11-24-20-01-46](https://user-images.githubusercontent.com/45292151/48971008-7e67fb00-f025-11e8-97e3-ed2804066b9e.png)

Theme color change no problem

![2018-11-24-20-04-24](https://user-images.githubusercontent.com/45292151/48971015-9475bb80-f025-11e8-942f-ca5d1df262c4.png)

First theme color change problem. Theme color no change.

![2018-11-24-20-04-56](https://user-images.githubusercontent.com/45292151/48971036-cdae2b80-f025-11e8-807e-9ec5cc85f29d.png)

**Comment by punker76** [comment]
@oeksymz Can you provide the source of this app?

**Comment by oeksymz** [comment]
Hi @punker76 
App source code

https://mega.nz/#!UZZiGKAT!n_EGEzOM-pmOJGiu1mjU7FMEL2Hi1eCRcgoGJbpigXE

**Comment by punker76** [comment]
@oeksymz Hi, you set the app style at startup to app current and in your settings to main window. You should set it also to app current then it works.

```
        private void TemaDegistir(string accents, string appThemeName)
        {
            ThemeManager.ChangeAppStyle(Application.Current.MainWindow as MetroWindow,
                ThemeManager.GetAccent(accents),
                ThemeManager.GetAppTheme(appThemeName));


            Properties.Settings.Default.AppThemeName = appThemeName;
            Properties.Settings.Default.AccentsName = accents;
            Properties.Settings.Default.Save();
        }
```

but in App.xaml.cs
```
// now set the Green accent and dark theme
ThemeManager.ChangeAppStyle(Application.Current,
    ThemeManager.GetAccent(accentName),
    ThemeManager.GetAppTheme(appThemeName)); // or appStyle.Item1
```

so with this it works
```
        private void TemaDegistir(string accents, string appThemeName)
        {
            ThemeManager.ChangeAppStyle(Application.Current
                ThemeManager.GetAccent(accents),
                ThemeManager.GetAppTheme(appThemeName));


            Properties.Settings.Default.AppThemeName = appThemeName;
            Properties.Settings.Default.AccentsName = accents;
            Properties.Settings.Default.Save();
        }
```

**Comment by oeksymz** [comment]
Thank you @punker76
