### ISSUE TITLE
Unable to open the project in VS2017

### ISSUE THREAD

**Issue by s0ciopa7h** [MahApps/MahApps.Metro#3380]
Hi Sir
OS: [Win10 1803]
Visual Studio [2017 15.9.2]
![2018-11-24_031427](https://user-images.githubusercontent.com/42713227/48963639-1ff43b80-ef97-11e8-9d52-eecbd163193a.png)

**Comment by punker76** [comment]
@s0ciopa7h You need to install the .Net Core 3.0 preview to use the latest source. I will update the wiki to show this information.

**Comment by s0ciopa7h** [comment]
Please Download Link Sir

**Comment by punker76** [comment]
@s0ciopa7h https://github.com/dotnet/core-sdk
