### ISSUE TITLE
Problem With Build Project

### ISSUE THREAD

**Issue by s0ciopa7h** [MahApps/MahApps.Metro#3381]
OS: [Win10 PRO 1803]
Visual Studio [2017 15.9.2]
![2018-11-25_172200](https://user-images.githubusercontent.com/42713227/48981528-db6fb980-f0d6-11e8-8ed2-2d60d36486c8.png)
![2018-11-25_172218](https://user-images.githubusercontent.com/42713227/48981529-dc085000-f0d6-11e8-8632-3a931fc3cb8b.png)

**Comment by punker76** [comment]
https://github.com/MahApps/MahApps.Metro/wiki/Building-the-MahApps.Metro-solution

**Comment by s0ciopa7h** [comment]
i try like this and same problem
