### ISSUE TITLE
GlowBrush low performance

### ISSUE THREAD

**Issue by hektorpc** [MahApps/MahApps.Metro#3382]
When using the glowbrush on a metro window the startup time for the window is really high and the shadow pops up with a delay.

Can I somehow have a shadow effect on the window without affecting the startup time and have it ready when the window shows up?

Thank you.

**Comment by punker76** [comment]
@hektorpc I don't know what pc configuration you have or which MahApps version are you using. I never saw such "is really high" behavior. But in v2.0 alpha this one was moved from here to ControlzEx with some re-implementation and should be now a little bit faster.

> Can I somehow have a shadow effect on the window without affecting the startup time and have it ready when the window shows up?

Yes, don't use the GlowBrush instead use the BorderBrush and no glow will be shown.
