### ISSUE TITLE
CustomDialog height can not be changed... 

### ISSUE THREAD

**Issue by Lelyuss** [MahApps/MahApps.Metro#3383]
Hello,
I am using the normal MessageDialog (with ShowMessageAsync from MetroWindow class) to show Infos/Warnings/etc, but there are some situations where the Dialog does not looks nice. For example:
 - Show a very short text in the Dialog with the main window maximized. There is a lot of non used space.

![grafik](https://user-images.githubusercontent.com/45175478/49020916-d15ec100-f191-11e8-8e08-ca695e6241fd.png)
 
I want to change the height of the dialog. To do that, I have tried to create an own message dialog using the CustomDialog class, but I have the same problem. It is not possible to change the height from this dialog... Somebody knows if it is possible?? And how?
I could reduce the space at the right and at the left of the messagetext, with the CustomDialog and an own Style (as here is explained: https://stackoverflow.com/questions/30751663/how-to-change-mahapps-metro-dialog-content-template-width/30797630#30797630 ).

I hope someone can help me.

Thank you very much in advance.

**Comment by punker76** [comment]
@Lelyuss How looks your own message dialog using CustomDialog?

**Comment by Lelyuss** [comment]
@punker76 here my dialog using CustomDialog:
![grafik](https://user-images.githubusercontent.com/45175478/49645286-9f641f00-fa1b-11e8-9608-26a229b6a1db.png)

I have set everything in the middle but I would like to reduce the space between title, message and button....

**Comment by punker76** [comment]
@Lelyuss Can you please add the Xaml code too?

**Comment by Lelyuss** [comment]
[TestCustomDialogMahApps.zip](https://github.com/MahApps/MahApps.Metro/files/2666667/TestCustomDialogMahApps.zip)
Hello,
here is an small project with the code.
thanks!

**Comment by punker76** [comment]
@Lelyuss So, in your case , you must add these lines in your `CustomDialogAffirmative`

```csharp
        protected override void OnShown()
        {
            base.OnShown();
            this.Invoke(() => this.MinHeight = 0);
        }
```

The reason is by design, because MahApps calculates always the same MinHeight for all Dialogs to get a harmonic UI.

https://github.com/MahApps/MahApps.Metro/blob/72f69b37de10231e55e9eaa9838faf32a8355998/src/MahApps.Metro/Controls/Dialogs/DialogManager.cs#L479-L480

Hope this helps!

**Comment by Lelyuss** [comment]
Thank you! It worked :)
