### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by fehdem** [MahApps/MahApps.Metro#3386]
Hi!

I cloned the master this morning and I'm struggling with the VS2017 compiler since then.
The error message I get is:  _The reference assemblies for framework ".NETFramework,Version=v4.7" were not found._ 
The target framework selection is grayed out so I can't change anything. However, I've v4.7 installed, as well as 4.7.1 and 4.7.2.

I've no idea what's going wrong here. The MahApps solution is the only one making trouble so far, therefore I assume that my build environment is generally functional.

Any help is appreciated.

-Marcus

**Comment by punker76** [comment]
@fehdem Did you also install the v4.7.x SDK?

**Comment by fehdem** [comment]
We're talking about the thing Microsoft named "Developer Pack" - right? Contrary to the sole Runtime. 
If so - yes, I did. I reinstalled them this morgning, too.

**Comment by fehdem** [comment]
Installing .Net Core SDK 2.1 did it. THANK YOU!
VS didn't give any hint regarding a missing .net Core SDK and I wasn't aware of this dependency.

I'm sorry for bothering you with this...

-Marcus
