### ISSUE TITLE
Checkbox in datagrid selecting others that not was selected

### ISSUE THREAD

**Issue by willerhreis** [MahApps/MahApps.Metro#3387]
**Describe the bug**
In a datagrid, I have many rows with check buttons. When I select some rows and scroll down the datagrid, other rows are selected automatically.

**To Reproduce**
1. Go to dataGrid
2. Click on checkbox and select many rows
3. Scroll down and you can see that others rows was selected

**Expected behavior**
Only selected rows should be marked.

**Environment(please complete the following information):**
 - MahApps.Metro version 1.6.5.1
 - OS: Win 10
 - Visual Studio 2015
 - .NET Framework v4.0.30319

**Comment by punker76** [comment]
@willerhreis ping
