### ISSUE TITLE
Build fail when running the demo application "MahApps.Metro.Demo" - Could not load file or assembly ControlzEx 

### ISSUE THREAD

**Issue by DavidXanatos** [MahApps/MahApps.Metro#3388]
I have this issue: https://github.com/MahApps/MahApps.Metro/issues/3340
but i cant manage to fix it, any advise?

Cheers
David X.

**Comment by punker76** [comment]
@DavidXanatos What VS? Which libs? Any additional debug output? Did you follow these [notes](https://github.com/MahApps/MahApps.Metro/wiki/Building-the-MahApps.Metro-solution)?

**Comment by punker76** [comment]
@FastChen This is not very helpful!

**Comment by punker76** [comment]
@DavidXanatos Have you looked to the [notes](https://github.com/MahApps/MahApps.Metro/wiki/Building-the-MahApps.Metro-solution)? Is this still an issue for you?
