### ISSUE TITLE
ItemContainerStyleSelector on ComboBox does not work with MahApps

### ISSUE THREAD

**Issue by DavidXanatos** [MahApps/MahApps.Metro#3391]
I was using ItemContainerStyleSelector on a ComboBox, in order to make some entries not selectable.
after adding MahApps styling, the ItemContainerStyleSelector stopped working.

How can I make some ComboBox entries not selectable using MahApps ?

**Comment by GreatFireWall** [comment]
Is there any workaround for `v1.6.5`?
