### ISSUE TITLE
Nuget Warning

### ISSUE THREAD

**Issue by abdulraooof** [MahApps/MahApps.Metro#3392]
Warning NU1602 MahApps.Metro 1.6.0 does not provide an inclusive lower bound for dependency ControlzEx (> 3.0.2 && < 4.0.0). An approximate best match of ControlzEx 3.0.2.4 was resolved.

**Comment by punker76** [comment]
@abdulraooof I think this is fixed in later versions > 1.6.0

**Comment by abdulraooof** [comment]
Oh sorry, It was installed as and WPF material design dependency. Now I have install it seperately and issue gone away.

Thanks!
