### ISSUE TITLE
Introduce a property to change the overlay brush for modal Flyouts

### ISSUE THREAD

**Issue by punker76** [MahApps/MahApps.Metro#3394]
Currently it's not possible to change the overlay brush for modal Flyouts.

So it would be nice to change this with a new property.

**Comment by nighthound** [comment]
This commit added the FlyoutOverlayBrush property but in the MetroWindow xaml definition, the FlyoutOverlayBrush property setter defines a SolidColorBrush which does not have Freeze="True" set. This causes issues when trying to create windows in separate threads.
