### ISSUE TITLE
Unable to locate repository containing directory '...\MahApps.Metro-develop\src\MahApps.Metro'.	MahApps.Metro	...\.nuget\packages\microsoft.build.tasks.git\1.0.0-beta-63127-02\build\Microsoft.Build.Tasks.Git.targets	20	

### ISSUE THREAD

**Issue by hamerstandr** [MahApps/MahApps.Metro#3398]
Error :
Unable to locate repository containing directory '...\MahApps.Metro-develop\src\MahApps.Metro'.	MahApps.Metro	...\.nuget\packages\microsoft.build.tasks.git\1.0.0-beta-63127-02\build\Microsoft.Build.Tasks.Git.targets	20

**Comment by punker76** [comment]
https://github.com/MahApps/MahApps.Metro/wiki/Building-the-MahApps.Metro-solution

**Comment by hamerstandr** [comment]
@punker76  Thank you for the answer
