### ISSUE TITLE
Error GitVersion: Process returned an error (exit code 1).

### ISSUE THREAD

**Issue by hamerstandr** [MahApps/MahApps.Metro#3399]
run build.ps1 error :
Cake.exe : Error: One or more errors occurred.
At line:1 char:1
+ & "C:\Intel\Progect\MahApps.Metro-develop new\tools\Cake\Cake.exe" "b ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Error: One or more errors occurred.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
	
GitVersion: Process returned an error (exit code 1).

**Comment by punker76** [comment]
@hamerstandr Please provide more information about your issue with compiling the source! Which VS are you using? Did you install the .NET Core preview? Where did you run the build.ps1? At commandline `powershell .\build.ps1` or in powershell bash?

**Comment by thoemmi** [comment]
@hamerstandr Have you cloned the repository or downloaded the sources?

**Comment by hamerstandr** [comment]
installed the .NET Core preview!
and run powershell .\build.ps1

**Comment by hamerstandr** [comment]
> Have you cloned the repository or downloaded the sources?

Yes!

**Comment by punker76** [comment]
@hamerstandr The cake script works only with a cloned repository.

```ps
INFO [12/12/18 9:11:38:23] ERROR: fatal: not a git repository (or any of the parent directories): .git

Error: One or more errors occurred.
        GitVersion: Process returned an error (exit code 1).

```

**Comment by hamerstandr** [comment]
> The cake script works only with a cloned repository.

how cloned repository

**Comment by hamerstandr** [comment]
> @hamerstandr The cake script works only with a cloned repository.
> 
> ```postscript
> INFO [12/12/18 9:11:38:23] ERROR: fatal: not a git repository (or any of the parent directories): .git
> 
> Error: One or more errors occurred.
>         GitVersion: Process returned an error (exit code 1).
> ```

how cloned repository
