### ISSUE TITLE
Use Microsoft.Xaml.Behaviors.Wpf instead the System.Windows.Interactivity

### ISSUE THREAD

**Issue by punker76** [MahApps/MahApps.Metro#3400]
Use Microsoft.Xaml.Behaviors.Wpf as dependency from NuGet instead the System.Windows.Interactivity.dll

This will remove the reference to System.Windows.Interactivity.dll which is sometimes bad for other projects which are also use this dll.

With this change it's necessary to change the namespace too, so this is a breaking change for all others too.

https://blogs.msdn.microsoft.com/dotnet/2018/12/10/open-sourcing-xaml-behaviors-for-wpf/

**Comment by navin21** [comment]
System.Windows.Markup.XamlParseException
  HResult=0x80131501
  Message='Add value to collection of type 'Microsoft.Xaml.Behaviors.TriggerCollection' threw an exception.' Line number '132' and line position '60'.
  Source=PresentationFramework

Inner Exception 1:
ArgumentException: "EventTrigger" is not a valid type for the TriggerType parameter. Make sure "EventTrigger" derives from TriggerBase

for dotnetframework 4.7.2 for my wpf project how can I resolve this any idea

**Comment by batzen** [comment]
Maybe you are trying to mix types from Microsoft.Xaml.Behaviors.Wpf and System.Windows.Interactivity?
Are you using both assemblies?

**Comment by navin21** [comment]
Apologies for late reply. I found issue as u mention scenario and changed its got work.

Thanks for the support.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
