### ISSUE TITLE
Build the lasted MahApps.Metro solution failed(2018.12.12)

### ISSUE THREAD

**Issue by li-zheng-hao** [MahApps/MahApps.Metro#3403]
I followed the Quick Start for developers list,here is my steps:
1 Download the latest  .net core 3.0.x and only have the lasted version in my computer.
2 my VS2017 version is 15.9.x and I have enabled Use previews of the .Net Core SDK
3 Clone the repository
4 clean the solution and rebuild
5  build failed

here are more information:
![.net core sdk](https://user-images.githubusercontent.com/22129824/49910484-dc1d9380-febd-11e8-9c73-85d6bb69e769.png)
![image](https://user-images.githubusercontent.com/22129824/49910679-990ff000-febe-11e8-9962-ff9330007395.png)
![image](https://user-images.githubusercontent.com/22129824/49910753-e3916c80-febe-11e8-95fb-d16102c41b1d.png)
![image](https://user-images.githubusercontent.com/22129824/49910782-002da480-febf-11e8-91ab-fd1077e97268.png)
![image](https://user-images.githubusercontent.com/22129824/49910797-0ae83980-febf-11e8-8ed8-2a4bd555ce82.png)

Warning:Package 'xamlcolor .....3.0.0.31' was restored using '.Net Framework Version=4.6.1' instead the project target framework '.Net Core  version =3.0'. This package may not be fully compatible with your project.

Can someone help me?

**Comment by li-zheng-hao** [comment]
![image](https://user-images.githubusercontent.com/22129824/49912387-f60ea480-fec4-11e8-8cc8-825095855d76.png)
I try the command in project folder:
`.paket\paket restore`
But it doesn't work.

**Comment by li-zheng-hao** [comment]
Here are some information in output window :
```
Error occurred while restoring NuGet packages: The operation failed as details for project MahApps.Metro.Caliburn.Demo could not be loaded.
```
```
1>Paket version 5.194.0
1>The last restore is still up to date. Nothing left to do.
1>Performance:
1> - Runtime: 320 milliseconds
1>Paket version 5.194.0
1>The last restore is still up to date. Nothing left to do.
1>Performance:
1> - Runtime: 316 milliseconds
1>Paket version 5.194.0
1>The last restore is still up to date. Nothing left to do.
1>Performance:
1> - Runtime: 258 milliseconds
1>Paket version 5.194.0
1>The last restore is still up to date. Nothing left to do.
1>Performance:
1> - Runtime: 166 milliseconds
```
```
1>C:\Users\lizhenghao\.nuget\packages\microsoft.build.tasks.git\1.0.0-beta-63127-02\build\Microsoft.Build.Tasks.Git.targets(20,5): 
error : Unable to locate repository containing directory C:\Users\lizhenghao\Downloads\MahApps.Metro-develop\src\MahApps.Metro'.
1>Done building project "MahApps.Metro.csproj" -- FAILED.
1>C:\Users\lizhenghao\.nuget\packages\microsoft.build.tasks.git\1.0.0-beta-63127-02\build\Microsoft.Build.Tasks.Git.targets(20,5):
error : Unable to locate repository containing directory
C:\Users\lizhenghao\Downloads\MahApps.Metro-develop\src\MahApps.Metro'.
1>Done building project "MahApps.Metro.csproj" -- FAILED.
1>C:\Users\lizhenghao\.nuget\packages\microsoft.build.tasks.git\1.0.0-beta-63127-02\build\Microsoft.Build.Tasks.Git.targets(20,5): 
error : Unable to locate repository containing directory C:\Users\lizhenghao\Downloads\MahApps.Metro-develop\src\MahApps.Metro'.
1>Done building project "MahApps.Metro.csproj" -- FAILED.
```

And when I write the command  `.paket\paket restore` ,it occurs some errors:
![image](https://user-images.githubusercontent.com/22129824/49918638-da17fc80-fede-11e8-9823-5101a798953f.png)

**Comment by caidt3** [comment]
Did you solved the problem? I have encounted the same problem.

**Comment by li-zheng-hao** [comment]
> Did you solved the problem? I have encounted the same problem.
not yet. I download 1.6.0 version and it works well. So maybe you can git an older version and try again

**Comment by li-zheng-hao** [comment]
> Did you solved the problem? I have encounted the same problem.

you can get it from here ：
[https://github.com/MahApps/MahApps.Metro/releases](url)

**Comment by caidt3** [comment]
> > Did you solved the problem? I have encounted the same problem.
> 
> you can get it from here ：
> https://github.com/MahApps/MahApps.Metro/releases

thank you, I tried  the older version 1.6.0 before, it works well.

**Comment by punker76** [comment]
Since dotnet core 3.0 sdk 009831 it no longer works with Visual Studio 2017 https://github.com/MahApps/MahApps.Metro/wiki/Building-the-MahApps.Metro-solution
