### ISSUE TITLE
Custom ContextMenu on NumericUpDown will not show on text input

### ISSUE THREAD

**Issue by punker76** [MahApps/MahApps.Metro#3406]
**Describe the bug**
A custom ContextMenu will not shown on the text input for
- NumericUpDown
- HotKeyBox
- DateTimePicker, TimePicker
- DatePicker

**To Reproduce**
Create a ContextMenu and set it to one of these controls.

**Expected behavior**
The ContextMenu should be shown at the text input.

**Environment(please complete the following information):**
 - MahApps.Metro version >= v1.6.5

**Additional context**
Thx to @SR84 who found this issue.

**Comment by SR84** [comment]
Super, danke.
