### ISSUE TITLE
error run build.ps1

### ISSUE THREAD

**Issue by hamerstandr** [MahApps/MahApps.Metro#3407]
PS C:\Intel\Progect\MahApps.Metro-develop new> C:\Intel\Progect\MahApps.Metro-develop new\build.ps1
Preparing to run build script...
Running build script...
Analyzing build script...
Processing build script...
Installing tools...
The 'tool' directive is attempting to install the 'GitVersion.CommandLine' package 
without specifying a package version number.  
More information on this can be found at https://cakebuild.net/docs/tutorials/pinning-cake-version 
It's not recommended, but you can explicitly override this warning 
by configuring the Skip Package Version Check setting to true 
(i.e. command line parameter "--settings_skippackageversioncheck=true", 
environment variable "CAKE_SETTINGS_SKIPPACKAGEVERSIONCHECK=true", 
read more about configuration at https://cakebuild.net/docs/fundamentals/configuration)
PackageSignatureVerificationLog: PackageIdentity: GitVersion.CommandLine.4.0.0 Source: C:\Users\Hamed\.nuget\packages\
 PackageSignatureValidity: True
The 'tool' directive is attempting to install the 'gitreleasemanager' package 
without specifying a package version number.  
More information on this can be found at https://cakebuild.net/docs/tutorials/pinning-cake-version 
It's not recommended, but you can explicitly override this warning 
by configuring the Skip Package Version Check setting to true 
(i.e. command line parameter "--settings_skippackageversioncheck=true", 
environment variable "CAKE_SETTINGS_SKIPPACKAGEVERSIONCHECK=true", 
read more about configuration at https://cakebuild.net/docs/fundamentals/configuration)
The 'tool' directive is attempting to install the 'xunit.runner.console' package 
without specifying a package version number.  
More information on this can be found at https://cakebuild.net/docs/tutorials/pinning-cake-version 
It's not recommended, but you can explicitly override this warning 
by configuring the Skip Package Version Check setting to true 
(i.e. command line parameter "--settings_skippackageversioncheck=true", 
environment variable "CAKE_SETTINGS_SKIPPACKAGEVERSIONCHECK=true", 
read more about configuration at https://cakebuild.net/docs/fundamentals/configuration)
PackageSignatureVerificationLog: PackageIdentity: xunit.runner.console.2.4.1 Source: C:\Users\Hamed\.nuget\packages\ P
ackageSignatureValidity: True
The 'tool' directive is attempting to install the 'vswhere' package 
without specifying a package version number.  
More information on this can be found at https://cakebuild.net/docs/tutorials/pinning-cake-version 
It's not recommended, but you can explicitly override this warning 
by configuring the Skip Package Version Check setting to true 
(i.e. command line parameter "--settings_skippackageversioncheck=true", 
environment variable "CAKE_SETTINGS_SKIPPACKAGEVERSIONCHECK=true", 
read more about configuration at https://cakebuild.net/docs/fundamentals/configuration)
PackageSignatureVerificationLog: PackageIdentity: vswhere.2.5.2 Source: C:\Users\Hamed\.nuget\packages\ PackageSignatu
reValidity: True
Installing addins...
The 'addin' directive is attempting to install the 'Cake.Figlet' package 
without specifying a package version number.  
More information on this can be found at https://cakebuild.net/docs/tutorials/pinning-cake-version 
It's not recommended, but you can explicitly override this warning 
by configuring the Skip Package Version Check setting to true 
(i.e. command line parameter "--settings_skippackageversioncheck=true", 
environment variable "CAKE_SETTINGS_SKIPPACKAGEVERSIONCHECK=true", 
read more about configuration at https://cakebuild.net/docs/fundamentals/configuration)
PackageSignatureVerificationLog: PackageIdentity: Cake.Figlet.1.2.0 Source: C:\Users\Hamed\.nuget\packages\ PackageSig
natureValidity: True
The 'addin' directive is attempting to install the 'Cake.Paket' package 
without specifying a package version number.  
More information on this can be found at https://cakebuild.net/docs/tutorials/pinning-cake-version 
It's not recommended, but you can explicitly override this warning 
by configuring the Skip Package Version Check setting to true 
(i.e. command line parameter "--settings_skippackageversioncheck=true", 
environment variable "CAKE_SETTINGS_SKIPPACKAGEVERSIONCHECK=true", 
read more about configuration at https://cakebuild.net/docs/fundamentals/configuration)
Compiling build script...
INFO [12/14/18 7:10:19:57] Working directory: C:\Intel\Progect\MahApps.Metro-develop new
INFO [12/14/18 7:10:19:64] IsDynamicGitRepository: False
ERROR [12/14/18 7:10:19:72] An unexpected error occurred:
System.IO.DirectoryNotFoundException: Can't find the .git directory in C:\Intel\Progect\MahApps.Metro-develop new
   at GitVersion.GitPreparer.GetDotGitDirectory()
   at GitVersion.GitPreparer.GetProjectRootDirectory()
   at GitVersion.ConfigurationProvider.Verify(GitPreparer gitPreparer, IFileSystem fileSystem)
   at GitVersion.Program.VerifyArgumentsAndRun()
INFO [12/14/18 7:10:19:72] 
INFO [12/14/18 7:10:19:72] Attempting to show the current git graph (please include in issue): 
INFO [12/14/18 7:10:19:72] Showing max of 100 commits
INFO [12/14/18 7:10:19:74] Could not execute 'git log' due to the following error:
System.IO.FileNotFoundException: The executable file 'git' could not be found.
File name: 'git' ---> System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at GitTools.ProcessHelper.Start(ProcessStartInfo startInfo)
   at GitTools.ProcessHelper.Start(ProcessStartInfo startInfo)
   at GitTools.ProcessHelper.Run(Action`1 output, Action`1 errorOutput, TextReader input, String exe, String args, Str
ing workingDirectory, KeyValuePair`2[] environmentalVariables)
   at GitTools.LibGitExtensions.DumpGraph(String workingDirectory, Action`1 writer, Nullable`1 maxCommits)

INFO [12/14/18 7:10:19:57] Working directory: C:\Intel\Progect\MahApps.Metro-develop new
INFO [12/14/18 7:10:19:64] IsDynamicGitRepository: False
ERROR [12/14/18 7:10:19:72] An unexpected error occurred:
System.IO.DirectoryNotFoundException: Can't find the .git directory in C:\Intel\Progect\MahApps.Metro-develop new
   at GitVersion.GitPreparer.GetDotGitDirectory()
   at GitVersion.GitPreparer.GetProjectRootDirectory()
   at GitVersion.ConfigurationProvider.Verify(GitPreparer gitPreparer, IFileSystem fileSystem)
   at GitVersion.Program.VerifyArgumentsAndRun()
INFO [12/14/18 7:10:19:72] 
INFO [12/14/18 7:10:19:72] Attempting to show the current git graph (please include in issue): 
INFO [12/14/18 7:10:19:72] Showing max of 100 commits
INFO [12/14/18 7:10:19:74] Could not execute 'git log' due to the following error:
System.IO.FileNotFoundException: The executable file 'git' could not be found.
File name: 'git' ---> System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at GitTools.ProcessHelper.Start(ProcessStartInfo startInfo)
   at GitTools.ProcessHelper.Start(ProcessStartInfo startInfo)
   at GitTools.ProcessHelper.Run(Action`1 output, Action`1 errorOutput, TextReader input, String exe, String args, Str
ing workingDirectory, KeyValuePair`2[] environmentalVariables)
   at GitTools.LibGitExtensions.DumpGraph(String workingDirectory, Action`1 writer, Nullable`1 maxCommits)

Cake.exe : Error: One or more errors occurred.
At line:1 char:1
+ & "C:\Intel\Progect\MahApps.Metro-develop new\tools\Cake\Cake.exe" "b ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Error: One or more errors occurred.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
	
GitVersion: Process returned an error (exit code 1).

PS C:\Intel\Progect\MahApps.Metro-develop new>

**Comment by thoemmi** [comment]
@hamerstandr The same question as in #3399: did you clone the repository or just download the sources?

**Comment by punker76** [comment]
@hamerstandr You must clone the repository. Here are some helpful links.

- [Cloning a repository](https://help.github.com/articles/cloning-a-repository/)
- [Git Basics - Getting a Git Repository](https://git-scm.com/book/en/v2/Git-Basics-Getting-a-Git-Repository)
- [Git download](https://git-scm.com/downloads)

So your commandline will be

```
git clone https://github.com/MahApps/MahApps.Metro.git
```
