### ISSUE TITLE
TrayIcon

### ISSUE THREAD

**Issue by hamerstandr** [MahApps/MahApps.Metro#3410]
Add TrayIcon style windows 10
![image](https://user-images.githubusercontent.com/16276736/50113656-d0342780-0257-11e9-86a6-558aaf3e4520.png)
or
![image](https://user-images.githubusercontent.com/16276736/50113714-01acf300-0258-11e9-9460-36e6b5e16a0d.png)
simple 
https://github.com/File-New-Project/EarTrumpet/tree/master/EarTrumpet/UI/Controls
and
https://github.com/File-New-Project/EarTrumpet/tree/master/EarTrumpet/UI/ViewModels

**Comment by punker76** [comment]
@hamerstandr ?

**Comment by hamerstandr** [comment]
add style to TrayIcon System Color and Acont Color

**Comment by punker76** [comment]
@hamerstandr I don't see why we should do this. TrayIcon is an external source at EarTrumpet.

**Comment by thoemmi** [comment]
@hamerstandr a tray icon is out of scope of MahApps.Metro. However, I can recommend [Hardcodet.NotifyIcon.Wpf](https://www.nuget.org/packages/Hardcodet.NotifyIcon.Wpf/) which I have used in a project or two. It works great with MahApps.Metro.
