### ISSUE TITLE
BaseMetroDialog DialogBottom: CommandBinding doesn't work

### ISSUE THREAD

**Issue by pfattisc** [MahApps/MahApps.Metro#3412]
**Describe the bug**
I have a [demo](https://github.com/pfattisc/DialogBottomBug) with a custom dialog. Within the custom dialog's DialogBottom there are two buttons OK and Cancel (to accept resp. cancel).
The button's commands are bound to the CloseCommand of the dialog. This is a relative source binding.
Quite often this binding doesn't work while the same binding of a button within the dialog's content does always work.

**To Reproduce**
1. Get & Run [demo](https://github.com/pfattisc/DialogBottomBug) 
2. Click on the (big) button 'start demo' in the main window. This will show a CustomDialog with a button as content and two buttons (OK, Cancel) in the DialogBottom.
3. Press the OK button in the bottom. Normally this should close the dialog, but most of the times it doesn't. Now press the button in the dialog content, which is bound the same way => And notice that this time the binding works and the dialog closes as expected

I also attached a gif that demonstrates the behaviour.
Note: That time when the OK button doesn't seem to work and you snoop the binding two things will happen:
1. First the bound command is NULL
2. Snooping it will refresh the binding and it will magically work.

Trivia: When the dialog first comes up and you close it with the 'ESC' Key and reopen it, most of the times the OK button binding will work as expected.

**Expected behavior**
(RelativeSource) Bindings of buttons within the DialogBottom part should always work.

**Screenshots**
![dialogbottom_bug](https://user-images.githubusercontent.com/11867529/50154145-c8609b80-02c8-11e9-98a2-9b69e66746f1.gif)

**Environment(please complete the following information):**
 - MahApps.Metro version 1.6.5
 - OS: Win10 1607 (N 2016 LTSB)
 - Visual Studio 2017
 - .NET Framework 4.7.2

**Repo**
[demo](https://github.com/pfattisc/DialogBottomBug)

**Additional context**
Originally this problem occurs in a desktop application. Interestingly the reported issue occurs in this application quite sporadically. This led me to the conclusion that the problem might be triggered by a race condition. The more I was surprised that the demo app demonstrates the problem quite constantly...

**Comment by punker76** [comment]
@pfattisc Thx for the repo 👍  and this is fixed now
