### ISSUE TITLE
Which Version Is The Latest Version Of Hamburger Menu

### ISSUE THREAD

**Issue by WeaponizedMeme** [MahApps/MahApps.Metro#3414]
I downloaded the [code samples](https://github.com/punker76/code-samples) for the hamburger menu, and the solution includes 4 different examples! All of them are significantly different, and I'm not sure which one I should be using. For example one is using "glyphs" for the button icons, which I can't find a list of anywhere, and another is using icon packs. Is one of these deprecated? Which should I be using, which is the "current standard" of HamburgerMenuApp, HamburgerMenuAppV2, HamburgerMenuAppV3, HamburgerMenuAppV4?

**Comment by punker76** [comment]
@WeaponizedMeme You can use one of these samples. There is no deprecated or prefered one. The glyphs items can be used for font icons.
