### ISSUE TITLE
A Stupid question  

### ISSUE THREAD

**Issue by larryhwang** [MahApps/MahApps.Metro#3415]
um, may this is a stupid  issus, but I  am very upset  cause I  can'nt  open and Excute and debug This Project ， files download on this  https://github.com/MahApps/MahApps.Metro/archive/develop.zip
I just wanna Some Samples 
It‘s  doubtless ThatMahApps is a awesome UIKit ， But i can't  debug its offical samples ,make me 
 very depressed ,pool me 
Anyone may help me  ？ 
![image](https://user-images.githubusercontent.com/11872375/50438258-22480d80-0928-11e9-93c1-4c2909e7ed0c.png)

**Comment by punker76** [comment]
@larryhwang If you installed the latest .Net Core 3.0 then you need also the VS 2019 preview.

https://github.com/MahApps/MahApps.Metro/wiki/Building-the-MahApps.Metro-solution

**Comment by larryhwang** [comment]
It works !  Thank your advises ,  so kind of  My  friends  : ）
