### ISSUE TITLE
I dont understand the demo of the binding method

### ISSUE THREAD

**Issue by zeroyjk** [MahApps/MahApps.Metro#3422]
```xaml
        <Controls:MetroAnimatedSingleRowTabControl x:Name="MainTabControl" Grid.Row="1">
            <TabItem Header="buttons">
                <exampleViews:ButtonsExample DataContext="{Binding}" />
            </TabItem>
            <TabItem Header="text">
                <exampleViews:TextExamples DataContext="{Binding}" />
            </TabItem>
```

How it binding to

`MahApps.Metro.Demo > folder (ExampleViews) > ButtonsExample.xaml`

**Comment by punker76** [comment]
@zeroyjk The DataContext of the ButtonsExample binds to the DataContext of the main window -> `DataContext="{Binding}" `

**Comment by zeroyjk** [comment]
I have google and bing it, but i dont understand it MVVM you using..

**Comment by punker76** [comment]
Here are some help about that

- https://www.tutorialspoint.com/mvvm/mvvm_wpf_data_bindings.htm
- https://youtu.be/WYBoTT2ce8c?t=1096
- https://docs.microsoft.com/en-us/dotnet/framework/wpf/data/data-binding-overview
