### ISSUE TITLE
sluggishness of MetroWindow on 144Hz monitor

### ISSUE THREAD

**Issue by NeomMob** [MahApps/MahApps.Metro#3423]
Sluggishness of MetroWindow on 144Hz monitor

**To Reproduce**
Standard MetroWindow with 
	WindowTransitionsEnabled="False"
	AllowsTransparency="True"
	Background="Transparent"
	WindowStyle="None"

**Expected behavior**
A smooth and high performance behavior

**Environment(please complete the following information):**
 - MahApps.Metro version .1.6..51
 - OS: Win10 
 - Visual Studio 2017 
 - .NET Framework 4.6.2

**Comment by punker76** [comment]
AllowsTransparency="True" will not be supported by MahApps, because of these sluggishness (you can set it, but with these consequences). It's an issue of WPF. The other issue will be that you lost all ClearType for every control which shows text.

**Comment by NeomMob** [comment]
@punker76 , How then can you achieve windows like this one (having the transluscent part)
https://user-images.githubusercontent.com/326762/43661562-075aeab0-9763-11e8-910c-1f98f790f492.png
