### ISSUE TITLE
Maximize icon drawn incorrect

### ISSUE THREAD

**Issue by NeomMob** [MahApps/MahApps.Metro#3424]
The maximize icon has unwanted shadow.

**To Reproduce**
Using the Win10 buttonsCommands on a HiDPI screen with custom scale

	<Controls:MetroWindow.WindowButtonCommands>
		<Controls:WindowButtonCommands Style="{DynamicResource MahApps.Metro.Styles.WindowButtonCommands.Win10}" />
	</Controls:MetroWindow.WindowButtonCommands>

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/326762/51084303-8ab82c80-1727-11e9-8869-c0f1a3960c96.png)

**Environment(please complete the following information):**
 - MahApps.Metro version 1.6.5.1
 - OS: Win10
 - Visual Studio 2017
 - .NET Framework 4.6.2

**Comment by punker76** [comment]
This is already fixed by https://github.com/MahApps/MahApps.Metro/commit/fc6b529b945d902b2211080dcf765490ba242d05#diff-75ed7bf48da87bab8adfd142701009d8
Duplicates to #3329
