### ISSUE TITLE
Solution load failed

### ISSUE THREAD

**Issue by FGallotti** [MahApps/MahApps.Metro#3435]
I downloaded the zip from develop brunch, when I go in the subfolder src, I try to open the solution MahApps.Metro.sln

when visual studio load the solution fails to opend the projects MahApps.Metro, MahApps.Metro.Caliburn.Demo, MahApps.Metro.Demo, MahApps.Metro.Tests

Output Windows show me this description:
C:\Users\SOFTWARE2\Desktop\MahApps.Metro-develop\src\MahApps.Metro\MahApps.Metro.csproj : error  : Project file is incomplete. Expected imports are missing.

C:\Users\SOFTWARE2\Desktop\MahApps.Metro-develop\src\MahApps.Metro.Samples\MahApps.Metro.Demo\MahApps.Metro.Demo.csproj : error  : Project file is incomplete. Expected imports are missing.

C:\Users\SOFTWARE2\Desktop\MahApps.Metro-develop\src\MahApps.Metro.Samples\MahApps.Metro.Caliburn.Demo\MahApps.Metro.Caliburn.Demo.csproj : error  : Project file is incomplete. Expected imports are missing.

C:\Users\SOFTWARE2\Desktop\MahApps.Metro-develop\src\Mahapps.Metro.Tests\MahApps.Metro.Tests.csproj : error  : Project file is incomplete. Expected imports are missing.

**Screenshots**
![mahapps metro](https://user-images.githubusercontent.com/43636414/51663797-af29c980-1faf-11e9-8386-0aa53e6cb3dd.PNG)

**Environment(please complete the following information):**
 - Win10 Pro 1803 (OS build 17134.523)
 - Visual Studio Community 2017 15.9.4

**Comment by punker76** [comment]
@FGallotti Sorry for the inconvenience, but you need at least the VS 2019 Preview Community Edition.

https://github.com/MahApps/MahApps.Metro/wiki/Building-the-MahApps.Metro-solution#quick-started-for-developers

**Comment by FGallotti** [comment]
Sorry, I did not read the quick start because I am using this framework from 1 year, at home I have an old version of the example project and still works there, In the office I changed the machine and I thought simply to download it.
Thank you very much for the quick answer.

**Comment by zeroyjk** [comment]
@FGallotti can you share the link for old version example project.. i really need it..

**Comment by FGallotti** [comment]
try this one.
[MahApps.Metro.Demo.zip](https://github.com/MahApps/MahApps.Metro/files/2799210/MahApps.Metro.Demo.zip)
