### ISSUE TITLE
HamburgerMenu ItemInvoked doesn't fire automatically

### ISSUE THREAD

**Issue by furqansafdar** [MahApps/MahApps.Metro#3436]
**Problem**
I have found a small glitch or bug you may say in `HamburgerMenu` when using it with PRISM library to load dynamic modules.

I have a navigation pane on left and content pane on right (as shown in the screenshot below). Every module is loaded with navigation item and upon clicking the item, the corresponding content is loaded in the right pane. I have set the HamburgerMenu's SelectedIndex to 0, so that once the loading it completed the first item is selected and its corresponding content is loaded. The logic of loading the content is residing in HamburgerMenu's `ItemInvoked` event but it is not fired automatically for the selected item. Hence the following layout is produced.

![hamburgerissue](https://user-images.githubusercontent.com/14292272/51688541-df03bc00-2005-11e9-99b2-385c888ead55.png)

Now when i click the first item again, event fires and content is loaded. I think this issue can be solved if ItemInvoked fires for selected item automatically.

```csharp
private void HamburgerMenu_OnItemInvoked(object sender, HamburgerMenuItemInvokedEventArgs e)
{            
    var option = (HamburgerMenuGlyphItem)e.InvokedItem;
    var viewName = (string)option.Tag;
    var region = _regionManager.Regions[RegionNames.TabRegion];
    region?.RequestNavigate(viewName);
}
```

**Environment**
 - MahApps.Metro version 1.6.5
 - OS: Win10 1803
 - Visual Studio 2017/2019
 - .NET Framework 4.6.1

**Comment by punker76** [comment]
@furqansafdar Can you create for this issue a sample? Thx

**Comment by punker76** [comment]
@furqansafdar Or did you mean, that the OnItemInvoked will not be fired for the first time load of the control?

**Comment by furqansafdar** [comment]
@punker76 Yes, i think OnItemInvoked should fire after loading because essentially it hold the logic to load the corresponding content.

**Comment by timunie** [comment]
@furqansafdar must probably be a different issue. Please use discussions and show your xaml and ViewModel involved. Maybe there is something missing...

Note: In general, do not answer closed issues. There's a high chance your comment gets lost.
