### ISSUE TITLE
Left padding of icon in MenuItem is too less

### ISSUE THREAD

**Issue by GreatFireWall** [MahApps/MahApps.Metro#3439]
![image](https://user-images.githubusercontent.com/4510984/51790257-8da62900-21cd-11e9-8ff4-09e037ef7b6e.png)

**Comment by punker76** [comment]
@GreatFireWall Please, post more informations when you open an issue! https://github.com/MahApps/MahApps.Metro/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by GreatFireWall** [comment]
@punker76 sorry, it may not be a bug ? just the left side edge too less, seems like no edges between Icon and menu item left edge.

![image](https://user-images.githubusercontent.com/4510984/51804927-c0215600-22a1-11e9-80ee-750b7484064a.png)

**Comment by GreatFireWall** [comment]
![image](https://user-images.githubusercontent.com/4510984/51804961-40e05200-22a2-11e9-9d42-0a1ce8450bbd.png)

**Comment by GreatFireWall** [comment]
@punker76 Well, Solved ! Thank You !

**Comment by GreatFireWall** [comment]
By the way, Can I use style for {iconPacks:Modern xxx} to make it effect all instance, because I want to keep my code as short as possible.

**Comment by punker76** [comment]
@GreatFireWall Yes, you can define a global style at the App.xaml or at the main window where you use the IconPacks.

```xaml
<Style TargetType="{x:Type iconPacks:PackIconModern}" BasedOn="{StaticResource {x:Type iconPacks:PackIconModern}}">
    <Setter Property="HorizontalAlignment" Value="Center" />
</Style>
```

**Comment by GreatFireWall** [comment]
@punker76 ok, thanks your guide !
