### ISSUE TITLE
Why the icon color not grayed which inside a disabled Circle Button 

### ISSUE THREAD

**Issue by GreatFireWall** [MahApps/MahApps.Metro#3442]
![image](https://user-images.githubusercontent.com/4510984/51843958-11d3ea00-234f-11e9-8066-60fef6030fbb.png)

The first one is enabled, second one is disabled.

I'm using `BaseLight` theme and `Steel` accent, my code:

![image](https://user-images.githubusercontent.com/4510984/51844279-cff77380-234f-11e9-87d3-473ff3ce060f.png)

**Comment by punker76** [comment]
@GreatFireWall This is not a problem of MahApps itself. Look at [this](https://github.com/MahApps/MahApps.Metro/issues/3101#issuecomment-376786019) and my [blog post](https://jkarger.de/2017/12/10/disabled-button-foreground/).
