### ISSUE TITLE
Do I have to install the package before starting a WPF app?

### ISSUE THREAD

**Issue by Rod-in-NM** [MahApps/MahApps.Metro#3449]
I've used another quick start WPF suite, but found problems with it. I'd like to give MahApps.Metro a try. Do I run the PowerShell command to install MahApps.Metro before I start a new WPF app? Or do I start a WPF app and then run the Install-Package command?

**Comment by punker76** [comment]
@Rod-in-NM For only usage: you start a WPF app and then install the MahApps [NuGet package](https://www.nuget.org/packages/MahApps.Metro) and follow the [quick start guide](https://github.com/MahApps/MahApps.Metro/wiki/Quick-Start).
