### ISSUE TITLE
How can I disable DefaultButtonFocus ?

### ISSUE THREAD

**Issue by GreatFireWall** [MahApps/MahApps.Metro#3450]
In other words, do not show any focus dashed at any buttons.

**Comment by punker76** [comment]
@GreatFireWall You can set the `FocusVisualStyle` via style

```xaml
<Setter Property="FocusVisualStyle" Value="{x:Null}" />
```

or at the control itself

```xaml
FocusVisualStyle="{x:Null}"
```

**Comment by GreatFireWall** [comment]
@punker76  I'm sorry I didn't make it clear. 
I means the `MetroDialogSettings.DefaultButtonFocus` when I calling `DialogCoordinator.ShowMessageAsync`.
