### ISSUE TITLE
Move window resize border to the usual location

### ISSUE THREAD

**Issue by JVimes** [MahApps/MahApps.Metro#3454]
**Is your feature request related to a problem? Please describe.**

Clicking window resize borders behaves unexpectedly with MetroWindow because the resize border isn't at the same location as with most apps in Windows 10. Most apps place it outside the visible window, with the exception that some place the top edge inside (not sure why).

Apps I tried: File Explorer, Settings, Visual Studio, Word, Notepad++, Chrome, Edge, default WPF/Winforms Apps.

**Describe the solution you'd like**

Move the resize border outside of the visible part of the window, and make sure it's the same thickness as most other apps (looks about 5px). It should not depend on glow/shadow (it does now).

This will reduce death-by-papercuts, and give the user 100% of the window to click on.

**Additional context**
On the left is an example congruent with most apps, on the right is a simple MetroWindow in the latest developer commit:
![image](https://user-images.githubusercontent.com/6148201/52894123-f3009080-3161-11e9-90b2-b7c6e9aa3bb4.png)

**Comment by swdriessen** [comment]
I agree. It usually takes a number of tries to resize the metro window using touch or pen.

**Comment by punker76** [comment]
@JVimes This is by design of normal `BorderBrush` usage in MahApps (and the borderless stuff). If you use the `GlowBrush` then you will get a better resize border behavior.

**Comment by JVimes** [comment]
@punker76 That's just a description of current implementation, not a reason to keep the UX this way. No?
