### ISSUE TITLE
Is it possible to put a ToggleSwitch in HamburgerMenu as an item ?

### ISSUE THREAD

**Issue by GreatFireWall** [MahApps/MahApps.Metro#3459]
Like this

![image](https://user-images.githubusercontent.com/4510984/53222216-c5f33700-36a7-11e9-9e27-ab8ddec9a730.png)

**Comment by Nuklon** [comment]
I don't think so, not really out of the box I think. A few more options in HamburgerMenu would be greatly appreciated, such as the ability to add the "badge" as well (to right side for example), can be used to show a number for example.

**Comment by punker76** [comment]
@GreatFireWall Yes, this is possible. Here is a simple sample to show a ToggleSwitch on a option item:

You can use the HamburgerMenuIconItem to show an icon and a custom content.
```xaml
<Controls:HamburgerMenu.OptionsItemsSource>
    <Controls:HamburgerMenuItemCollection>
        <Controls:HamburgerMenuIconItem>
            <Controls:HamburgerMenuIconItem.Icon>
                <iconPacks:PackIconMaterial Width="22"
                                            Height="22"
                                            HorizontalAlignment="Center"
                                            VerticalAlignment="Center"
                                            Kind="Switch" />
            </Controls:HamburgerMenuIconItem.Icon>
            <Controls:HamburgerMenuIconItem.Tag>
                <Controls:ToggleSwitch Header="A Switch" Foreground="{DynamicResource MahApps.Metro.HamburgerMenu.PaneForegroundBrush}" />
            </Controls:HamburgerMenuIconItem.Tag>
        </Controls:HamburgerMenuIconItem>
    </Controls:HamburgerMenuItemCollection>
</Controls:HamburgerMenu.OptionsItemsSource>
```

Here is the DataTemplate for the specific view of the HamburgerMenuIconItem.
```xaml
<!--  This is the template for all option menu items.  -->
<DataTemplate x:Key="HamburgerOptionsMenuItem" DataType="{x:Type Controls:HamburgerMenuIconItem}">
    <DockPanel Height="48" LastChildFill="True">
        <ContentControl x:Name="IconPart"
                        Width="48"
                        Content="{Binding Icon}"
                        DockPanel.Dock="Left"
                        Focusable="False"
                        IsTabStop="False" />
        <ContentControl Content="{Binding Tag}"
                        Focusable="False"
                        IsTabStop="False" />
    </DockPanel>
</DataTemplate>
```

![2019-04-17_15h37_57](https://user-images.githubusercontent.com/658431/56292497-969cfb80-6127-11e9-9e68-e69d1d6706f3.png)

**Comment by GreatFireWall** [comment]
@punker76 Thanks your sample, it's great. 
But is it possible place the `switch` at left side instead of the `icon` even the `HamburgerMenu` is **Not** open ?

![image](https://user-images.githubusercontent.com/4510984/56333977-0b744200-61c9-11e9-8901-8766b8920e4b.png)

**Comment by punker76** [comment]
@GreatFireWall simply change the DataTemplate.

**Comment by GreatFireWall** [comment]
@punker76 But it will cause a new page, I only want to put a switch here without page. Is it possible ?
