### ISSUE TITLE
Can't Load Solution With VS2017 

### ISSUE THREAD

**Issue by AlBannaTechno** [MahApps/MahApps.Metro#3462]
### Hi
I just clone the repo from GitHub and try to open the solution with visual studio 2017 `15.9.7`
But the solution does not load the projects `marked as (unavailable)`
And when I try to reload any project I get this message 

```
C:\.......\MahApps.Metro-develop\src\MahApps.Metro\MahApps.Metro.csproj : error  : Project file is incomplete. Expected imports are missing.

C:\.......\MahApps.Metro-develop\src\MahApps.Metro.Samples\MahApps.Metro.Demo\MahApps.Metro.Demo.csproj : error  : Project file is incomplete. Expected imports are missing.

C:\.......\MahApps.Metro-develop\src\MahApps.Metro.Samples\MahApps.Metro.Caliburn.Demo\MahApps.Metro.Caliburn.Demo.csproj : error  : Project file is incomplete. Expected imports are missing.

C:\.......\MahApps.Metro-develop\src\Mahapps.Metro.Tests\MahApps.Metro.Tests.csproj : error  : Project file is incomplete. Expected imports are missing.

C:\.......\MahApps.Metro-develop\src\Mahapps.Metro.Tests\MahApps.Metro.Tests.csproj : error  : Project file is incomplete. Expected imports are missing.

```

here `https://github.com/MahApps/MahApps.Metro/wiki/Building-the-MahApps.Metro-solution`

say: need 2019 version: so is there any built version of a demo to download if I can't install vs2019 now?

**Comment by punker76** [comment]
@AlBannaTechno Because you need VS 2019 to build the current dev branch https://github.com/MahApps/MahApps.Metro/wiki/Building-the-MahApps.Metro-solution
