### ISSUE TITLE
Question: How to set window icon from iconpack

### ISSUE THREAD

**Issue by Torchok19081986** [MahApps/MahApps.Metro#3464]
Hallo, i am new in WPF and i tried to set icon on mainwindow with iconpacks. But unfortenally, vs says it not from type image. Is it possible to set anyway or do i need custom image? i would gladly use icons from iconpacks modern or classic.

**Comment by punker76** [comment]
@Torchok19081986 You can use the `IconTemplate` property to set a custom Icon at the title bar.

https://github.com/MahApps/MahApps.Metro/blob/d1b8eadfa1880d7dafac128f29cb67b61019e777/src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleWindows/FlyoutDemo.xaml#L42-L50

**Comment by tim-elmer** [comment]
It would be nice if this were incorporated into the documentation.

**Comment by timunie** [comment]
Hi @tim-elmer 

If you want to you are welcome to create a PR in the docs on your own. https://github.com/MahApps/mahapps.com

Happy documenting
Tim

**Comment by JackDjTom** [comment]
@punker76 This doesn't work anymore right?
Is there another way now?

When i try the given solution I get the following Exception on building my project:
MainWindow.xaml(21, 8): [MC4108] The root of a Template content section cannot contain an element of type 'MahApps.Metro.IconPacks.EntypoExtension'. Only FrameworkElement and FrameworkContentElement types are valid.

**Comment by punker76** [comment]
> @punker76 This doesn't work anymore right? Is there another way now?
> 
> When i try the given solution I get the following Exception on building my project: MainWindow.xaml(21, 8): [MC4108] The root of a Template content section cannot contain an element of type 'MahApps.Metro.IconPacks.EntypoExtension'. Only FrameworkElement and FrameworkContentElement types are valid.

You use the extension and not the control, which produces this error.
