### ISSUE TITLE
无法加载项目，所有项目均显示已卸载 ，无法重新加载到开发工具

### ISSUE THREAD

**Issue by GhostDevil** [MahApps/MahApps.Metro#3465]
无法加载项目，所有项目均显示已卸载 ，无法重新加载到开发工具。最近的版本一直如此，不明白什么原因？
![image](https://user-images.githubusercontent.com/19898700/53552512-6c42af00-3b76-11e9-9fd9-3f10f32c9e4f.png)

**Comment by punker76** [comment]
@GhostDevil You need VS 2019 Preview (or now RC) to build the latest source from the dev branch https://github.com/MahApps/MahApps.Metro/wiki/Building-the-MahApps.Metro-solution

**Comment by GhostDevil** [comment]
谢谢！ 查看回复后得知需要独立安装core3.0，vs2019本身安装没有core3.0选项，已经可以打开！

发送自 Windows 10 版邮件应用

发件人: Jan Karger
发送时间: 2019年2月28日 16:53
收件人: MahApps/MahApps.Metro
抄送: GhostDevil; Mention
主题: Re: [MahApps/MahApps.Metro] 无法加载项目，所有项目均显示已卸载 ，无法重新加载到开发工具 (#3465)

Closed #3465.
