### ISSUE TITLE
TabControl navigation with keyboard doesn't work

### ISSUE THREAD

**Issue by garnbleiche** [MahApps/MahApps.Metro#3466]
I can't navigate through the tabitems with the keyboard.

Expected:
keyboard navigation like the standard wpf tabcontrol

**Comment by punker76** [comment]
@garnbleiche I can no reproduce this with the latest demo. Can you provide more infos? Maybe create a short app?

**Comment by garnbleiche** [comment]
okay, I made a simple app with three tabitems. I can't select the tabitems with the keyboard, same with the demo.

[mahappsTab.zip](https://github.com/MahApps/MahApps.Metro/files/2916590/mahappsTab.zip)

**Comment by timunie** [comment]
Hello @garnbleiche,

I downloaded your sample and tried to switch the Tabs with Keyboard. You have to make sure that the keyboard focus is within your window. Then you can use [Ctrl] + [Tab] to switch the tabs. Which keyboard shortcut did you use?

Best regards

**Comment by garnbleiche** [comment]
Hello @timunie ,

switch the tab with [Ctrl] + [Tab] works. I tried the right/left arrow keys which doesn't work!
On the standard wpf tabcontrol i can use the arrow keys. I did not know the [Ctrl] + [Tab] shortcut.
