### ISSUE TITLE
Question: How to keep WindowTitleBrush Background Color after loosing focus

### ISSUE THREAD

**Issue by Torchok19081986** [MahApps/MahApps.Metro#3467]
Hallo i have a question. Is it possible to keep WindowTitleBrush Background Color after loosing focus ? 
i have project a window, where i can show new metrowindow, but if i show new Metrowindow mainwindow looses WindowTitleBrush Background Color and switch it to system color. Current i set color ot Titlebrush WindowTitleBrush="#1BBC9B" like that, but after looses it going to be gray or current windows system color. How can i define or programm my color ?

**Comment by punker76** [comment]
@Torchok19081986 You can set the `NonActiveWindowTitleBrush` property to the same brush

https://github.com/MahApps/MahApps.Metro/blob/b7348bd42bf34a34a52e1613e62a486b6b54850f/src/MahApps.Metro/Controls/MetroWindow.cs#L101
