### ISSUE TITLE
Minimize button in system menu still appear

### ISSUE THREAD

**Issue by LuanPham97** [MahApps/MahApps.Metro#3473]
**Describe the bug**
I want to hide minimize button so I use property `ShowMinButton="False"` to hide, minimize button on `MainWindow` is hidden but when I Right-click on titlebar, System Menu show up and Minimize Button stilll appear

**Expected behavior**
Minimize button in System menu is hidden (or disabled)

**Screenshots**
![image](https://user-images.githubusercontent.com/24811783/54171458-f2cb8a80-44ac-11e9-9ac1-9e6034de56ca.png)

**Environment:**
 - MahApps.Metro version 1.6.5

**Comment by punker76** [comment]
@LuanPham97 this has now been fixed, and it will be released in the next version of MahApps.Metro v2.0

**Comment by LuanPham97** [comment]
> @LuanPham97 this has now been fixed, and it will be released in the next version of MahApps.Metro v2.0

Okay that’s great. Thank you!
