### ISSUE TITLE
Theme Light.Blue.xaml no longer exists

### ISSUE THREAD

**Issue by faint220** [MahApps/MahApps.Metro#3474]
Hello, 

I've followed the '[Quick start](https://mahapps.com/guides/quick-start.html)' and Rider underlined a line /Styles/**Themes/Light.Blue.xaml**" as not existing in the metro .dll. anymore. I couldn't find this theme in a different location. I'm writing this because I wanted to inform you that it doesn't work anymore and may discourage some developers from using this awesome .dll. 

Cheers!

**Comment by punker76** [comment]
@faint220 Did you install the correct (alpha) version via NuGet?

**Comment by faint220** [comment]
> 
> 
> @faint220 Did you install the correct (alpha) version via NuGet?

I did not... I have just upgraded to the latest alpha right now and it works as in 'quick start' section. Sorry for bothering you:(

**Comment by punker76** [comment]
@faint220 NP
