### ISSUE TITLE
Splitview Animation

### ISSUE THREAD

**Issue by PharazFadaei** [MahApps/MahApps.Metro#3478]
**Describe the bug**
I checked the source of SplitView, there are animations in there. But when I use it (through HamburgerMenu) or inside the demo app, it just disappears. Is it supposed to support sliding animations?

**Expected behavior**
A sliding animation upon opening and closing

**Environment:**
 - MahApps.Metro version 1.6.4 and 2 demo
 - OS: Win10 1803
 - Visual Studio 2017 15.9.9
 - .NET Framework 4.7

**Comment by punker76** [comment]
@PharazFadaei Thanks for raising this issue and looking in to this. The animations should be shown with the `Overlay` display modes (the inline doesn't habe animations). But I introduced a bug after improving the demos which kills these animations. I will fix this.
