### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by Symbai** [MahApps/MahApps.Metro#3479]
The latest release is rather old and over 190 commits have been done meanwhile. Would be nice to get a new release including a recent demo application.

**Comment by punker76** [comment]
@Symbai A new final release needs still some time, but you can look at the [appveyor build ci](https://ci.appveyor.com/project/punker76/mahapps-metro/history) to get the latest (hot) pre-release and the main demo.

**Comment by timunie** [comment]
@punker76 I would like to help getting the release done, as I really like this framework. Because I dont know what you are working on: On which topic should I work next? I think about #3299 .

Happy coding 
Tim
