### ISSUE TITLE
Multiline for InputDialog

### ISSUE THREAD

**Issue by ryuuc** [MahApps/MahApps.Metro#3481]
in MetroDialogSettings, i did like
 ` CustomResourceDictionary =
                        new ResourceDictionary
                        {
                            {"TextWrapping", "Wrap"},
                            {"AcceptsReturn", "True"}
                        }`
but not work

**Comment by punker76** [comment]
@ryuuc The ´InputDialog` already accepts `Return` as commit and the inner TextBox wraps the Text if it's too long.

**Comment by ryuuc** [comment]
thanks
