### ISSUE TITLE
Can support changing the global font size ?

### ISSUE THREAD

**Issue by waleswood** [MahApps/MahApps.Metro#3488]

**Comment by punker76** [comment]
@waleswood All fonts are defined [here](https://github.com/MahApps/MahApps.Metro/blob/develop/src/MahApps.Metro/Styles/Fonts.xaml). You can override these keys at the App.xaml.

**Comment by waleswood** [comment]
for example, As the font gets larger, the button will also become larger. Adaptive UI interface

**Comment by punker76** [comment]
@waleswood This was not yout intial question, and it's already there...

The first button has a larger Font size, the rest the default font size.

```xaml
<Button Content="Test" FontSize="48" />
```

![2019-05-08_10h11_37](https://user-images.githubusercontent.com/658431/57360189-cdd85880-7179-11e9-9bbb-263d06528471.png)

**Comment by waleswood** [comment]
thanks
