### ISSUE TITLE
Validation errors don't disappear for valid data.

### ISSUE THREAD

**Issue by amellini** [MahApps/MahApps.Metro#349]
Hi all,
When using your kit in my app with fluentvalidation the red rectangle for the textbox don't disappear when i update the value in a valid way.

The only way to update the view is change the active tab and return to the previous one.

Repro steps:
- Setup a view with a textbox with validation properties like this:

`<TextBox Margin="12,101,8,0" TextWrapping="Wrap" VerticalAlignment="Top" Text="{Binding Ospite.TipoDocumento, Mode=TwoWay, UpdateSourceTrigger=LostFocus,NotifyOnValidationError=True,ValidatesOnDataErrors=True}" Grid.Column="1" Height="26" />`
- Enter some text that will fail validation
- Trigger LostFocus by switching to the next input

Expected Behaviour: validation messsage appears
Actual Behaviour: only validation highlight around box appears

When switching between tabs, the validation message returns.

I've added two picture displaying the wrong state and the right state (after the tab switch)

![Phase1](https://f.cloud.github.com/assets/1766396/166874/41d340ca-79b9-11e2-96ac-3eb124ed7f23.PNG)
![Phase2](https://f.cloud.github.com/assets/1766396/166875/41ec7874-79b9-11e2-97e6-2802e4ca2e04.PNG)

**Comment by AmirGaraje** [comment]
Thanks
