### ISSUE TITLE
Compatibility issue in a plugin system

### ISSUE THREAD

**Issue by KennanChan** [MahApps/MahApps.Metro#3492]
**Describe the bug**
In a plugin system, different plugins may use different versions of a library. We notice that MahApps.Metro fails to run correctly in this circumstance. More precisely, the plugin referencing the higher version lib fails to locate the embedded resource like "underline.xaml" maybe because the lower version is used

**To Reproduce**
I built a simple plugin project to demonstrate this issue. Just restore the nuget package and run.
[Demo](https://github.com/KennanChan/MahAppsCompatibilityIssueDemo)

**Expected behavior**
In the demo project, both two windows are shown with no error.

**Screenshots**

**Environment(please complete the following information):**
 - MahApps.Metro v1.5.0 & MahApps.Metro v1.4.3
 - OS: Win10 1809
 - Visual Studio 2017 Community
 - .NET Framework 4.5

**Repo**
https://github.com/KennanChan/MahAppsCompatibilityIssueDemo

**Additional context**
In the demo repo, PluginA references MahApps.Metro v1.5.0 and PluginB references MahApps.Metro v1.4.3 and they both can be referenced dynamically by the host application project since I watched the AppDomain assemblies and both two versions of MahApps.Metro are correctly resolved. But the MetroWindow in PluginA cannot be shown because the underline.xaml cannot be located.

**Comment by punker76** [comment]
IMO this is not related to MahApps. Using different versions of an assembly seems to be a general problem. If anyone find a solution then I'm interested in too.
