### ISSUE TITLE
How can I set the default MetroDialogSettings.ColorScheme to all dialog ?

### ISSUE THREAD

**Issue by GreatFireWall** [MahApps/MahApps.Metro#3496]
I want to set a default value to `MetroDialogSettings.ColorScheme = MetroDialogColorScheme.Accented`. 

So I don't have to add a new `MetroDialogSettings {  ColorScheme = MetroDialogColorScheme.Accented }`  every call for `DialogCoordinator.ShowMessageAsync`.

**Comment by punker76** [comment]
@GreatFireWall You can override the default dialog settings at the MetroWindow:

```xaml
<Controls:MetroWindow ...>

    <Controls:MetroWindow.MetroDialogOptions>
        <Dialog:MetroDialogSettings ColorScheme="Accented" />
    </Controls:MetroWindow.MetroDialogOptions>

</Controls:MetroWindow>
```

**Comment by GreatFireWall** [comment]
And how can I binding `MetroDialogSettings.AffirmativeButtonText` ? It's not a `DependencyObject`, I want to make it localized string.

**Comment by timunie** [comment]
I had the same problem as you, @GreatFireWall . I ended up making a static helper class that holds some predefined DialogSettings. I can now use e.g. a translated string for my buttons. 

```
    public static class MetroDialogHelper
    {
        public static MetroDialogSettings YesNoStyle = new MetroDialogSettings()
        {
            AffirmativeButtonText = Dialogs.Yes,   // String comes from a RESX-File 
            NegativeButtonText = Dialogs.No,       // String comes from a RESX-File 
            DefaultButtonFocus = MessageDialogResult.Negative
        };
    }
```

**Comment by GreatFireWall** [comment]
@timunie Is there an example using in `MetroWindow.MetroDialogOptions` for global defintion ?

**Comment by timunie** [comment]
@GreatFireWall Sorry, but I cannot share my application with you. 

The Helper class is just a file that is public for the whole project. If i need to show a dialog i call it like this, e.g. from the code behind: 

```
var result = await this.ShowMessageAsync(
                             "Title", 
                             "Message",
                             MessageDialogStyle.AffirmativeAndNegative, 
                             MetroDialogHelper.YesNoStyle); // This line does the trick
```

Best regards and happy coding :-)
