### ISSUE TITLE
Question: How to change Style of MessagBox

### ISSUE THREAD

**Issue by Torchok19081986** [MahApps/MahApps.Metro#3497]
Hallo, i have a question and hope someone can help me with. 
I try to change appearance of default MessageBox in metrowindow.ShowMessageAsync() Method. 
unfortunately without success. 
There ist parameter for MetroDialogSettings, which i try to change. 
my code looks like :

```
var mymessageboxsettings = new MetroDialogSettings()
{
    AffirmativeButtonText = "OK",
    NegativeButtonText = "Cancel",
    AnimateShow = true,
    AnimateHide = false,
    DialogMessageFontSize = 12,
};
var result = await this.ShowMessageAsync("Info", "Load", MessageDialogStyle.AffirmativeAndNegative, mymessageboxsettings);
var theme = ThemeManager.GetAppTheme("BaseDark");
var accent = ThemeManager.GetAccent("LightGreen");
ThemeManager.ChangeAppStyle(Application.Current, accent, theme);
```

In ThemeManager  should be are Method  
ThemeManager doesnt change MessageBox Colors / Style. Is always default, white backgroundcolor and blue buttons for ok and cancel.

I use VIsual Studio 2019, .NET Framework 4.6.2 und Mah.Apps.Metro 1.6.5.

**Comment by punker76** [comment]
@Torchok19081986 You change the theme and accent after closed dialog, that's maybe the problem.

**Comment by Torchok19081986** [comment]
Thanks for answer, @punker76. That was the problem. I set it too early. After i set it after line 
ThemeManager.ChangeAppStyle(Application.Current, accent, theme); It works fine. Only one question: 
currently thememanager change also my main window in theme and accent. How do i set it only for messageBox ?

**Comment by timunie** [comment]
Hello @Torchok19081986 ,

you can use a custom resourcedictionary and aplly it just to the dialog. See the screenshots below.

The window:
![image](https://user-images.githubusercontent.com/47110241/57852121-a1a88180-77e2-11e9-8daa-b9abee261950.png)

The dialog: 
![image](https://user-images.githubusercontent.com/47110241/57852142-b258f780-77e2-11e9-94ba-28413aba73ce.png)

```
        private async void Button_Click(object sender, RoutedEventArgs e)
        {
            var accent = ThemeManager.GetAccent("Red").Resources;  // Get a theme of your choise 
            accent["AccentColorBrush"]=  Brushes.Pink;             // Change the resources you like 

            var settings = new MetroDialogSettings()
            {
                AffirmativeButtonText = "Yeah",
                NegativeButtonText = "No :-(",
                CustomResourceDictionary = accent                   // And finally applay it in the MetroDialogSettings
            };

            await this.ShowMessageAsync("TEST", "This is a test", MessageDialogStyle.AffirmativeAndNegative, settings);
        }
```

Happy Coding :-)

**Comment by Torchok19081986** [comment]
Hallo and thanks for answer @timunie . Unfortenally isnt work for me. My MessageBox is always white with blue buttons. I show messagebox on WPF Form loaded event . Maybe is the problem . 
Do i need to add custom Dictonarie or custom ressource im app.xaml oder my form ? I didnt until now.

**Comment by timunie** [comment]
@Torchok19081986 do you have a sample app? It works for me also in the loaded event.

**Comment by Torchok19081986** [comment]
thanks for quick answer, @timunie. if you mean some screenshot, unfortunally no. i try to create it just like you write, with only one change, i choose green for  accent["AccentColorBrush"]=  Brushes.Pink Line.
But its dont work for me. 
in app.xaml i have 
 <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Colors.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/Blue.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/BaseLight.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.TextBox.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Shared.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.Buttons.xaml" />
as source added. 
Could be one of this ressources doesnt allow apply new style for messagebox ?

**Comment by timunie** [comment]
hmmmm ... sorry, no idea. Maybe you should try the latest pre-release 2.0.0-alpha. There are some breaking changes, so you need to make a few modifications to your code.
