### ISSUE TITLE
TextBoxHelper.WatermarkAlignment not working

### ISSUE THREAD

**Issue by PlAn-K** [MahApps/MahApps.Metro#3498]
**Describe the bug**
I want to edit the alignment of watermark, so I use TextBoxHelper.WatermarkAlignment property in Textbox. but It's not working.

**Expected behavior**
Watermark Alignment is changed

**Screenshots**
![1](https://user-images.githubusercontent.com/21980585/57568792-0f416000-7427-11e9-8fc5-8a2332c58507.png)
![2](https://user-images.githubusercontent.com/21980585/57568793-0f416000-7427-11e9-94f1-6e9b3914afbc.png)

**Environment**
 - MahApps.Metro v1.6.5
 - OS: Windows 10 1809
 - Visual Studio 2019 16.0.3
 - .NET Framework 4.7.2

**Comment by punker76** [comment]
@PlAn-K You must set `HorizontalContentAlignment="Stretch"`, which is necessary to enable changing the watermark alignment.
