### ISSUE TITLE
ShowModalLoginExternal problem

### ISSUE THREAD

**Issue by nilssol** [MahApps/MahApps.Metro#3500]
I'm having problems when creating LoginDialogSettings together with ShowModalLoginExternal

1.  Watermark does not show in application for username and password.
2.  When enabling "EnablePasswordPreview" the application crashes

I'm using PowerShell and MahApps together, WPF and MahApps for the visual and runspaces, PowerShell for the tasks in the application.

$Settings                          = [MahApps.Metro.Controls.Dialogs.LoginDialogSettings]::new()
$Settings.EnablePasswordPreview    = "True"

**Environment(please complete the following information):**
 - MahApps.Metro version v1.6.5
 - OS: [Server 2012 R2 and Server 2016]
 - Visual Studio 15.6.7
 - .NET Framework 4.6.01586

**Comment by punker76** [comment]
@nilssol Did you pass your login settings as parameter on ShowModalLoginExternal?

like

```
LoginDialogData result = this.ShowModalLoginExternal("Authentication",
                                                     "Enter your credentials",
                                                     new LoginDialogSettings
                                                     {
                                                         ColorScheme = this.MetroDialogOptions.ColorScheme,
                                                         InitialUsername = "MahApps",
                                                         EnablePasswordPreview = true
                                                     });
```

**Comment by nilssol** [comment]
Yes, pass login settings as parameter like this:
https://pastebin.com/Y1w9FWy4

**Comment by punker76** [comment]
@nilssol I don't know why this happens. I didn't use MahApps together with PS. Have you any stack trace or logging about the crash?

**Comment by nilssol** [comment]
I have standard try catch to resolve errors, but the application crashes i cant receive anything because it shut down completely.  I have tried to debug the runspace and get this message when it crashes.

The background process reported an error with the following message: "The 
named pipe target process has ended.".
    + CategoryInfo          : ResourceUnavailable: (:) [], ParentContainsError 
   RecordException
    + FullyQualifiedErrorId : System.Management.Automation.Remoting.PSRemoting 
   DataStructureException

**Comment by punker76** [comment]
@nilssol I don't know what this exception means in powershell.

**Comment by JM2K69** [comment]
I make test to your PowerShell code It works great
```powershell
$Settings                          = [MahApps.Metro.Controls.Dialogs.LoginDialogSettings]::new()
    $Settings.ColorScheme              = "Accented"
    $Settings.DialogMessageFontSize    = "16"
    $Settings.DialogTitleFontSize      = "18"
    $Settings.NegativeButtonVisibility = "Visible"
    #$Settings.DialogResultOnCancel     = "Canceled"    
    $Settings.UsernameWatermark        = "Username..."   
    $Settings.PasswordWatermark        = "Password..."    
    $Settings.UsernameCharacterCasing  = "Normal"         
    $Settings.DefaultButtonFocus       = "Affirmative"    
    $Settings.EnablePasswordPreview    = "True"          
    
    $Global:DialogResults              = [MahApps.Metro.Controls.Dialogs.DialogManager]::ShowModalLoginExternal ($UI.Window,"Authentication","Enter your admin credentials :",$Settings)

I just remove the $Settings.DialogResultOnCancel because the property doesn't exist for the object.

![login](https://user-images.githubusercontent.com/17923944/58730362-32d74500-83ec-11e9-9d68-17ba1c70e6fb.PNG)

**Comment by nilssol** [comment]
You got it working with MahApps v1.6.5 ?

**Comment by JM2K69** [comment]
No I Have the 1.5.0.23 I tried With 1.6.5 and the Apps close immediately without any error but if use this code it works great with 1.6.5
## This code works in 1.5.0.23 and 1.6.5
```powershell
 $Identifiants = [MahApps.Metro.Controls.Dialogs.DialogManager]::ShowModalLoginExternal($Form,"Authentication","Enter your admin credentials :") 
``` 
## This code works in 1.5.0.23 and 1.6.5
```powershell
   $Settings                          = [MahApps.Metro.Controls.Dialogs.LoginDialogSettings]::new()
    $Settings.ColorScheme              = "Accented"
    $Settings.DialogMessageFontSize    = "16"
    $Settings.DialogTitleFontSize      = "18"
    $Settings.NegativeButtonVisibility = "Visible"
    $Settings.DialogResultOnCancel     = "Canceled"    
    $Settings.UsernameWatermark        = "Username..."   
    $Settings.PasswordWatermark        = "Password..."    
    $Settings.UsernameCharacterCasing  = "Normal"         
    $Settings.DefaultButtonFocus       = "Affirmative"    
    #$Settings.EnablePasswordPreview    = "True"          
    
    $Global:DialogResults              = [MahApps.Metro.Controls.Dialogs.DialogManager]::ShowModalLoginExternal($Form,"Authentication","Enter your admin credentials :",$Settings)
})
```
 If you enable the setting EnablePasswordPreview the Dialog don't show and the Apps close itself with 1.6.5 but work on 1.5.0.23. @punker76

**Comment by JM2K69** [comment]
But Settings **$Settings.UsernameWatermark** and **$Settings.PasswordWatermark** have no effect to the DialogBox in 1.6.5 and the button don't have the Mahapps Design @punker76
