### ISSUE TITLE
Unable to build project solution (Release 1.6.5 under VS 2019)

### ISSUE THREAD

**Issue by erotavlas** [MahApps/MahApps.Metro#3501]
I tried to build and run project solution from release 1.6.5 in VS 2019 and it complains of the following

```

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3644	The reference assemblies for framework ".NETFramework,Version=v4.7" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.	MahApps.Metro.Demo	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets	1183	


```

![Capture](https://user-images.githubusercontent.com/10454265/57974360-de13e300-7984-11e9-917e-7599b6bfdc27.PNG)

Even though I have .Net 4.7 installed

Also I tried to download the latest .NET Core 3.0 preview as indicated in the info for developers, and I tried to open the latest development branch, without success

![1Capture](https://user-images.githubusercontent.com/10454265/57974473-8d04ee80-7986-11e9-9ded-fd99ce0ae81e.PNG)

So not really sure what has happened here.  I used to be able to open and run the previous releases 1.6.x in visual studio but not anymore.

**Comment by punker76** [comment]
@erotavlas Have you really installed the .Net 4.7 SDK?

**Comment by andyb1979** [comment]
VS can be a pain. Is there a global.json file in the root of the directory? I recently had this issue with a project I'm working on and adding global.json to specify SDK locations solved it.

**Comment by punker76** [comment]
@andyb1979 I don't know how to add multiple sdk specifications inside the global.json. @erotavlas I would suggest to install also the .NET Framework 4.7 Developer Pack to build the solution.
