### ISSUE TITLE
.NET Core 3 support

### ISSUE THREAD

**Issue by andyb1979** [MahApps/MahApps.Metro#3502]
Hello! 

I'm updating a number of WPF applications to .NET Core 3 and they depend on MahApps.Metro, which as yet doesn't support netcoreapp3.0. 

Are there any plans to do this? Mostly it's just csproj and build script changes as .NET Core 3 / WindowsDesktop is fully compatible with WPF.

**Comment by punker76** [comment]
@andyb1979 The dev branch and the latest alpha release on NuGet already support .Net Core 3.0 Preview 5.

**Comment by punker76** [comment]
@andyb1979 https://github.com/MahApps/MahApps.Metro/wiki/Building-the-MahApps.Metro-solution

**Comment by andyb1979** [comment]
Nice! Thank you. The NuGet package is what I was looking for.

**Comment by punker76** [comment]
@andyb1979 If you want always the latest source as a NuGet package then you can use the [appveyor](https://ci.appveyor.com/nuget/mahapps.metro) feed. From time to time I update the official NuGet, but it's not always the latest one.
