### ISSUE TITLE
Bad scaling of MetroWindow controls when Windows display scaling is set to anything but 100%

### ISSUE THREAD

**Issue by HTD** [MahApps/MahApps.Metro#3510]
To reproduce - use demo application and change Windows display settings, the one called "Change the size of text, apps, and other items" to let's say 150%. Notice how the MetroWindow controls like "Close", "Minimize" and "Maximize" are drawn differently than those on original Windows 10 windows. The line thickness is changed, which looks very ugly and breaks overall "system" appearance. The lines of those symbols are also jagged and irregular, as a kind of interpolation artifact. Scaling above 100% is very common on high resolution screens.

**Comment by proemmer** [comment]
As a workaround you can add an app manifest and uncomment the following section

```xml
  <!-- Indicates that the application is DPI-aware and will not be automatically scaled by Windows at higher
       DPIs. Windows Presentation Foundation (WPF) applications are automatically DPI-aware and do not need 
       to opt in. Windows Forms applications targeting .NET Framework 4.6 that opt into this setting, should 
       also set the 'EnableWindowsFormsHighDpiAutoResizing' setting to 'true' in their app.config. -->
  
  <application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings>
      <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true</dpiAware>
    </windowsSettings>
  </application>
```

**Comment by punker76** [comment]
@HTD Which MahApps version are you using? The demo sample uses this [app manifest](https://github.com/MahApps/MahApps.Metro/blob/cb7141733df160a8239bdf102587f1d19a2e6da1/src/MahApps.Metro.Samples/MahApps.Metro.Demo/app.manifest#L34-L42). With these settings the DPI scaling works at my machines™

**Comment by HTD** [comment]
The workaround doesn't work either for version 1.6.5 or 2.0.0-alpha-0316 (from NuGet), and the problem is not that DPI scaling doesn't work at all - it is built in WPF so it works by default. The problem is with window icons, as in attached files.

Is it possible to change window title bar styles in 2.0? All title bar styles were marked as errors after upgrade to 2.0.0-alpha-0316.

Here: my settings:
![1-my-settings](https://user-images.githubusercontent.com/263558/59174762-042b3e00-8b53-11e9-827f-d3eeb060d22e.png)

How my application title bar looks like (both in v1.6.5 and v2.0.0):
![2-my-controls](https://user-images.githubusercontent.com/263558/59174767-07262e80-8b53-11e9-8b01-e381b7059e17.png)

Here's like the demo from source (2.0.0) looks like (looks correctly - but IDK why):
![3-demo-from-source](https://user-images.githubusercontent.com/263558/59174772-0a211f00-8b53-11e9-8f5c-920ea5abd0ad.png)
