### ISSUE TITLE
Window Style goes wrong

### ISSUE THREAD

**Issue by wunianqing** [MahApps/MahApps.Metro#3516]
**Describe the bug**
Original window style can be seen when switch window in Win7.

**To Reproduce**
1. Open demo application. Notice the top-left corner and top-right corner of window.
2. Open VS window.
3. Switch between VS window and main window. Notice the style of VS window.
5. Maximize and restore VS window. Switch between windows. Style won't change anymore.

**Expected behavior**
CornerRadius should be 0. And style of window should not change.

**Screenshots**
[Expected]
![Expected](https://user-images.githubusercontent.com/12225840/58779481-a9508e80-8608-11e9-9a82-8d170e7bf201.PNG)    
[Actual]
![Actual](https://user-images.githubusercontent.com/12225840/58779501-b5d4e700-8608-11e9-9840-3a897aa9aeaf.PNG)    
[Screen record]
![record](https://user-images.githubusercontent.com/12225840/58779883-b9b53900-8609-11e9-8eba-9ee59c8a1f8c.gif)

**Environment(please complete the following information):**
 - MahApps.Metro version [latest code in develop branch]
 - OS: [Win7 SP1]
 - Visual Studio [dotenet core 3.0 preview 5]
 - .NET Framework [4.6]

**Additional context**
This only happen in some real machines. But it can be easy reproduced on virtual machine. And once you set Performance Options -> Visual Effects -> Adjust for best performance. This problem will no longer exist.

**Comment by wunianqing** [comment]
I just found that version 1.6 and 1.6.1 are good.
I cannot compile the 1.6.2, 1.6.3 and 1.6.4.
And 1.6.5 is NG.

**Comment by punker76** [comment]
@wunianqing This is related to the new/changed implementation of the borderless behavior in ControlzEx v4.0 alpha.

/cc @batzen I can reproduce this in a Win7 test VM, but didn't know how to solve this. (Another effect is while changing focus from Window to another Window is that the win 7 aero theme is shown  for one second. I don't know if I want to fix this... 🙈  )

![2019-06-03_12h50_42](https://user-images.githubusercontent.com/658431/58797475-5d99e700-8600-11e9-884b-261a2ce5f21a.png)

![mahapps_controlzex_win7](https://user-images.githubusercontent.com/658431/58797679-e57ff100-8600-11e9-9cca-07ac2b70fb11.gif)

**Comment by batzen** [comment]
@punker76 Could you move this issue to ControlzEx? Will have a look at this.

**Comment by punker76** [comment]
@batzen Transfering issues is only allowed in the same organization level, so I will create a new one at ControlzEx and reference this one.

**Comment by punker76** [comment]
https://github.com/ControlzEx/ControlzEx/issues/80

**Comment by wunianqing** [comment]
Thx. @punker76 
I replaced the `InitializeWindowChromeBehavior` in MetroWinow.cs with the following code before issue is fixed. For now, it works fine. I don't know if this will cause other problems.
```cs
        private void InitializeWindowChromeBehavior()
        {
            WindowStyle = WindowStyle.None;
            WindowChrome.SetWindowChrome(this, new WindowChrome()
            {
                CaptionHeight = 0,
                CornerRadius = new CornerRadius(0.0),
                GlassFrameThickness = new Thickness(1),
                UseAeroCaptionButtons = false,
                NonClientFrameEdges = NonClientFrameEdges.None
            });
            //var behavior = new BorderlessWindowBehavior();
            //Interaction.GetBehaviors(this).Add(behavior);
        }
```
