### ISSUE TITLE
ColorPicker Control

### ISSUE THREAD

**Issue by timunie** [MahApps/MahApps.Metro#3520]
**Is your feature request related to a problem? Please describe.**
I wanted to give my users the option to hava a custom accent color. My result is a custom class for now, but may be someday it will be implemented for others, too. ( see #3515 ). I think it would be nice to have a colorpicker, as there is none in WPF by default

**Describe the solution you'd like**
have a colorpicker for selecting colors

**Additional context**
There are several ideas what we can do:
* make a custom controltemplate for this one: https://github.com/xceedsoftware/wpftoolkit/wiki/ColorPicker 
* make a new control similar to this colorpicker https://github.com/xceedsoftware/wpftoolkit/wiki/ColorPicker (I don't know if we are allowed to take code from there)
* Create a now control from scratch

**Closed Issues**
None 

@punker76 I would like to help with this topic, if you want me to. If you don't want to have a colorpicker at all, just close this issue. I wont blame you.

**Comment by RejectKid** [comment]
It'd be cool to have this inside of the mahapps kit imo.  Currently I'm using 

https://github.com/Dirkster99/ColorPickerLib

but it'd be nice to have them in one place.  maybe could use his colorPicker as a starting point?

**Comment by timunie** [comment]
@RejectKid this control is based on [this](https://github.com/xceedsoftware/wpftoolkit/wiki/ColorPicker) toolkit, as far as I can see. There are a few resons why I am trying to implement it on my own:

- Localization only shows when the Control is active, I want it shown all the time
- The control is hard to style imo
- what about the license? Can we use it without any permission?
- it is sometimes slow when having many colors 
- the list of available colors is static, so if you want to provide different `ColorPickers` for different proposes you need to workaround this. 

I still need some time to get this working and @punker76 has more important stuff to do, so we need to be a bit patient at the moment

current state: 
![image](https://user-images.githubusercontent.com/47110241/62319095-85d98100-b49d-11e9-9a56-ea05444a54ed.png)


Happy coding
Tim

**Comment by timunie** [comment]
Update:
![image](https://user-images.githubusercontent.com/47110241/62536950-96984700-b84f-11e9-9476-5719d869bda1.png)

If someone is interested, here is my code: 
[https://github.com/timunie/MahApps.Metro/tree/ColorPicker](https://github.com/timunie/MahApps.Metro/tree/ColorPicker)

Any feedback is welcome.

Happy coding
Tim
