### ISSUE TITLE
Recent Alpha breaks embedded HamburgerMenu

### ISSUE THREAD

**Issue by xagon0** [MahApps/MahApps.Metro#3525]
As of Alpha 0312, a HamburgerMenu in a UserControl displaying a HamburgerMenu with sub views, no longer functions correctly. It appears the index of the control is drawn incorrectly.

To Reproduce: Place HamburgerMenu in MainWindow, Create UserControl with HamburgerMenu, Create UserControl with details.

Point HamburgerMenu1 to HamburgerMenu2 User Control.

Selecting Option 1, then Option 1 (of Menu 2) results in the entire control disappearing.

Initial Load
![image](https://user-images.githubusercontent.com/39174540/59046683-a7bcdb80-883f-11e9-9ad7-187b028e79fe.png)

Select Item 1 - HamburgerMenu 1
![image](https://user-images.githubusercontent.com/39174540/59046694-ae4b5300-883f-11e9-900e-8209447ee8b0.png)

Select Item 2 - Hamburger Menu 2
![image](https://user-images.githubusercontent.com/39174540/59046702-b1464380-883f-11e9-8df6-888a13781aac.png)

On Alpha 0262: Initial Load
![image](https://user-images.githubusercontent.com/39174540/59046798-dd61c480-883f-11e9-8905-d2a156d2979b.png)

On Alpha 0262: Select Item 1 - HamburgerMenu 1
![image](https://user-images.githubusercontent.com/39174540/59046807-e18de200-883f-11e9-9491-5c581d556bbe.png)

On Alpha 0262: Select Item 2 - Hamburger Menu 2
![image](https://user-images.githubusercontent.com/39174540/59046813-e3f03c00-883f-11e9-8392-740dde4f459d.png)

 - OS: [Win10 1803]
 - Visual Studio [e.g. 2019 16.2.0 P1]
 - .NET Framework [e.g. 4.5.2]

Example Repo at: https://github.com/xagon0/ad0042e9-4c13-4a7c-a729-8d05444714cb

**Comment by punker76** [comment]
@xagon0 I found the problem for this issue and will fix it soon

**Comment by punker76** [comment]
@xagon0  this has now been fixed, and it will be released in the next version of MahApps.Metro v2.0
