### ISSUE TITLE
How to make small width of the dialogs?

### ISSUE THREAD

**Issue by truocpham-agilityio** [MahApps/MahApps.Metro#3530]
Im using mahapps dialogs control and try to custom the width of the dialogs but don't see any document for that. Please help on this issue.

**Comment by timunie** [comment]
Hello @truocpham-agilityio. In the current release the width of the dialog is not adjustable, but there will be an enhancement in the upcoming version 2.0.0. For details please see this discussion #3484 .

If you need even more control over your dialog you can use a `SimpleChildWindow`: [https://github.com/punker76/MahApps.Metro.SimpleChildWindow](https://github.com/punker76/MahApps.Metro.SimpleChildWindow)


Happy Coding
