### ISSUE TITLE
In full-screen mode, the dialog window pops out on 2 monitor

### ISSUE THREAD

**Issue by ACXap** [MahApps/MahApps.Metro#3538]
Good day. Desktop on 2 monitors, in full-screen mode, the dialog window pops out on 2 monitor and outside the application window

`public bool NotificationWithConfirmation(string header, string body)
        {
            var dialog = _dialogCoordinator.ShowModalMessageExternal(this, header, body, MessageDialogStyle.AffirmativeAndNegative, new MetroDialogSettings()
            {
                AffirmativeButtonText = "Yes",
                NegativeButtonText = "No"
            });
            if (dialog == MessageDialogResult.Affirmative)
            {
                return true;
            }
            else
            {
                return false;
            }
        }`
![Error](https://user-images.githubusercontent.com/19235372/60317968-68dff880-999b-11e9-811d-ebe3edb53719.JPG)

**Environment(please complete the following information):**
 - MahApps.Metro version v2.0.0-alpha0391
 - OS: Win10 1607
 - Visual Studio 2019 16.1.4]
 - .NET Framework  4.7.1

**Comment by AKruimink** [comment]
This seems to be an issue where when a window state is set to `Maximized` it actualy extends the window resolution by several pixels to hide everything of non importance, when an external dialog is created it uses the actual  parent window it's width, which now extends the bounds of your screen resulting in a dialog bigger then your monitor size.
