### ISSUE TITLE
IdealForegroundColorBrush is not ideal

### ISSUE THREAD

**Issue by Foxtrek64** [MahApps/MahApps.Metro#3541]
**Describe the bug**
When a control brush is bound to `IdealForegroundColorBrush`, the control looks fine in dark theme but breaks in light theme.

**To Reproduce**
1. Make a 3x3 grid
2. Make a border: 
```xml
<Border Grid.Row="1" Grid.Column="1" BorderBrush="{StaticResource IdealForegroundColorBrush}" BorderThickness="1" />
```
3. Switch theme between light and dark.

**Expected behavior**
On dark theme, the `IdealForegroundColorBrush` maps to a white or near-white color. This works well for displaying items with high contrast between light and dark. On light theme, this should map to a black or near-black color, but instead it continues to map to a white or near-white color. This has lead to any text, borders, or other such items with a binding to this color brush looking great on dark theme but becoming invisible on light theme.

**Screenshots**
Dark Theme:
![image](https://user-images.githubusercontent.com/7003081/60407041-a05aca80-9b7e-11e9-9d37-17741e2e6f77.png)

Light theme:
![image](https://user-images.githubusercontent.com/7003081/60407065-b8cae500-9b7e-11e9-8329-1e33d4fec033.png)

The border on the right is defined in markup very similarly to the above example in the reproduction section. The differences are that it does not have grid declarations and its only drawing the right hand border (`BorderThickness="0 0 1 0"`). The tabcontrol on the side is a modified MahApps.Metro tab control.

```xml
<TabControl.ItemContainerStyle>
	<Style TargetType="TabItem" BasedOn="{StaticResource {x:Type TabItem}}">
		<Setter Property="LayoutTransform">
			<Setter.Value>
				<RotateTransform Angle="90" />
			</Setter.Value>
		</Setter>
		<Setter Property="Template">
			<Setter.Value>
				<ControlTemplate TargetType="TabItem">
					<Border Name="Border" BorderThickness="0 0 0 5" BorderBrush="{StaticResource IdealForegroundDisabledBrush}" Height="30px" Margin="0 0 15 0">
						<TextBlock Name="Tag">
							<ContentPresenter x:Name="ContentSite"
										  VerticalAlignment="Center"
										  HorizontalAlignment="Center"
										  ContentSource="Header"
										  />
						</TextBlock>
					</Border>
					<ControlTemplate.Triggers>
						<Trigger Property="IsSelected" Value="False">
							<Setter TargetName="Tag" Property="Foreground" Value="{StaticResource IdealForegroundColorBrush}" />
							<Setter TargetName="Border" Property="BorderBrush" Value="{StaticResource IdealForegroundDisabledBrush}" />
						</Trigger>
						<Trigger Property="IsMouseOver" Value="True">
							<Setter TargetName="Tag" Property="Foreground" Value="{StaticResource AccentBaseColorBrush}" />
							<Setter TargetName="Border" Property="BorderBrush" Value="{StaticResource HighlightBrush}" />
						</Trigger>
						<Trigger Property="IsSelected" Value="True">
							<Setter TargetName="Tag" Property="Foreground" Value="{StaticResource AccentBaseColorBrush}" />
							<Setter TargetName="Border" Property="BorderBrush" Value="{StaticResource HighlightBrush}" />
						</Trigger>
					</ControlTemplate.Triggers>
				</ControlTemplate>
			</Setter.Value>
		</Setter>
	</Style>
</TabControl.ItemContainerStyle>
```

These are not the only locations this color brush issue is present, but it is among the most apparent since this is visible as soon as you open the app.

**Environment:**
 - MahApps.Metro version: 1.6.5
 - OS: Win10 1809
 - Visual Studio 2019 16.1.3
 - .NET Framework 4.7.2

**Repo**
https://github.com/Foxtrek64/BZ2UIEdit/tree/feature/newProject
(Make sure you get the `feature/newProject` branch.)

**Additional Info**
If there's a different binding I should be using instead, do let me know! I picked this one because I felt it would be the "ideal" color for a foreground item. If it's white because it's meant to be displayed on blue, then that would make sense.

Here's my App.xaml resource dictionary:
```xml
<ResourceDictionary.MergedDictionaries>
	<!-- MahApps.Metro resource dictionaries. Make sure that all file names are Case Sensitive! -->
	<ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
	<ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
	<ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Colors.xaml" />
	<ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/FlatButton.xaml" />
	<!-- Accent and AppTheme setting -->
	<ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/Blue.xaml" />
	<ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/BaseLight.xaml" />
</ResourceDictionary.MergedDictionaries>
```

**Comment by timunie** [comment]
Hello @Foxtrek64 

you are almost on the right track. `IdealForegroundColorBrush` is meant to be the foreground for the selected `AccentColor`. It is White for most of the `AccentColors` and Black for bright `AccentColors` (e.g. Yellow). 

In your case you should use `{DynamicResource BlackBrush}` instead. This Brush is Black for the `LightTheme` and White for the `DarkTheme`. `WhiteBrush` does the same, just the other way around. 

Happy coding
Tim

**Comment by Foxtrek64** [comment]
That'd explain that. Thanks for the help @timunie!
