### ISSUE TITLE
ComboBox does not work well with Text Binding IDataErrorInfo

### ISSUE THREAD

**Issue by waleswood** [MahApps/MahApps.Metro#3543]
**Describe the bug**
I Binding Text to a parameter in Class whice Implementation Interface IDataErrorInfo，but it dose display the error msg

code like this
``` Xaml
<ComboBox Text="{Binding Path=Glu1, ValidatesOnExceptions=True, UpdateSourceTrigger=PropertyChanged, NotifyOnValidationError=True}">
    <ComboBoxItem>1.5</ComboBoxItem>
    <ComboBoxItem>2.5</ComboBoxItem>
    <ComboBoxItem>400.25</ComboBoxItem>
</ComboBox>
```

**Comment by timunie** [comment]
Could you provide a short sample of your IDataError implementation or a sample App?

**Comment by timunie** [comment]
Just an info: [https://docs.microsoft.com/de-de/dotnet/api/system.windows.data.binding.validatesondataerrors?view=netframework-4.8](https://docs.microsoft.com/de-de/dotnet/api/system.windows.data.binding.validatesondataerrors?view=netframework-4.8)

**Comment by waleswood** [comment]
My fault, I forgot to write “ValidatesOnDataErrors=True”
