### ISSUE TITLE
NumericUpDown StringFormat does not work well if I set StringFormat="{}{0}mmHg"

### ISSUE THREAD

**Issue by waleswood** [MahApps/MahApps.Metro#3551]
**Describe the bug**
NumericUpDown StringFormat does not work well if I set StringFormat="{}{0}mmHg". I know Add a space between '{0}' and 'mmHg' can solve this problem, but Will cause the number I entered after the space to be invalid.

**Comment by timunie** [comment]
See also #3376 

Happy coding
Tim

**Comment by timunie** [comment]
@waleswood which version of MahApps do you use? I tried your `StringFormat` with the latest prerelease and it works for me (with and without a space). 

![image](https://user-images.githubusercontent.com/47110241/61247925-56630e80-a752-11e9-94f8-7497537f5262.png)

Happy coding 
Tim

**Comment by waleswood** [comment]
@timunie MahApps.Metro 1.6.5，you can test like this, input a number in front of ‘mmHg'. Is the result still 10?

**Comment by timunie** [comment]
@waleswood input:
![image](https://user-images.githubusercontent.com/47110241/61315728-a946cf80-a7ff-11e9-88b5-cda50d6ff1af.png)
output after lost focus:
![image](https://user-images.githubusercontent.com/47110241/61315749-be236300-a7ff-11e9-86a5-529ac2864451.png)

Another try ... input:
![image](https://user-images.githubusercontent.com/47110241/61315785-d4c9ba00-a7ff-11e9-9d53-a4007fb09d28.png)
output:
![image](https://user-images.githubusercontent.com/47110241/61315835-ed39d480-a7ff-11e9-8970-0d698b7e1764.png)

And another try:
![image](https://user-images.githubusercontent.com/47110241/61315881-080c4900-a800-11e9-9aac-c5d6c9916d22.png)
output: 
![image](https://user-images.githubusercontent.com/47110241/61315893-10fd1a80-a800-11e9-9b86-9f31e7fcfc0e.png)

I use the latest prerelease. If I try it with 1.6.5 it dosn't work 😞 . You could make a short sample App and try it yourself with the latest prerelease. 
If you want to update MahApps in your App please keep in mind, that there are some breaking changes.

Happy coding
Tim

**Comment by waleswood** [comment]
@timunie thanks very much, where can i get prerelease version，I did not found  it :disappointed_relieved:

**Comment by punker76** [comment]
@waleswood The pre-release is also available on NuGet. [How to get it](https://docs.microsoft.com/en-us/nuget/create-packages/prerelease-packages#installing-and-updating-pre-release-packages)

**Comment by waleswood** [comment]
@punker76  pre-release  does not support .net 4.0

**Comment by punker76** [comment]
> @punker76 pre-release does not support .net 4.0

That's correct.

**Comment by waleswood** [comment]
It would be great if MahApps.Metro still supported .net 4.0.

**Comment by timunie** [comment]
@waleswood there was a discussion on this topic going on, Finally MahApps decided to drop .NET 4.0 as it is not supported by M$. This also opens more possibilities for new features.
[https://github.com/MahApps/MahApps.Metro/issues/3041](https://github.com/MahApps/MahApps.Metro/issues/3041)

Happy coding
Tim

**Comment by waleswood** [comment]
I see. Thank you for your help.
