### ISSUE TITLE
Documentation references unreleased version

### ISSUE THREAD

**Issue by richbryant** [MahApps/MahApps.Metro#3553]
**Describe the bug**

The Quick Start clearly references "App.xaml (v2.0.0 and newer)" in the "Styling the window" section.

Latest actual version is 1.6.n.  This is highly misleading.

**To Reproduce**
1. Go to https://mahapps.com/guides/quick-start.html#styling
2. Observe

**Expected behavior**
Instructions dealing with a default install first.

**Comment by punker76** [comment]
@richbryant If you scroll down then you will see there is also the old v1.6.5 section with the resources instructions.
