### ISSUE TITLE
Minor Issue: Debugger shows GlowWindow for Title

### ISSUE THREAD

**Issue by RickStrahl** [MahApps/MahApps.Metro#3556]
When using a Debugger to attach externally or using a process viewer the Window title of a MetroWindow based application will show `GlowWindow` for the Title:

![image](https://user-images.githubusercontent.com/1374013/61581730-3cdf0f80-ab22-11e9-96c8-f754ac5b0ae6.png)

**To Reproduce**  
Run your MahAPps based application. Open a separate instance of Visual Studio and attach debugger. Search for your app's name in the process list.

**Expected behavior**  
This should probably show the actual Window title, rather than GlowWindow.

**Environment(please complete the following information):**
 - MahApps.Metro version v1.6.5]
 - OS: [e.g. Win10 1903]
 - Visual Studio [e.g. 2019 (16.1.4)]
 - .NET Framework [e.g. 4.6.2]

**Other**  
This is obviously a minor issue - it appears that Task Manager and Process Explorer are properly picking up the Window name, and the title must be something else that is getting picked up. Checking other WinForm and WPF apps they appear to leave this value empty, which would be preferable to the GlowWindow setting.

**Comment by batzen** [comment]
This should be fixed in the current alpha as it was an issue originating from ControlzEx.

**Comment by punker76** [comment]
@batzen After maximizing and restoring the MahApps main demo I got the same issue :-(

![image](https://user-images.githubusercontent.com/658431/74425969-d40c0b80-4e54-11ea-951e-d876ccdb451a.png)

**Comment by punker76** [comment]
I moved this to [ControlzEx](https://github.com/ControlzEx/ControlzEx/issues/140)
