### ISSUE TITLE
MetroWindow Memory leak

### ISSUE THREAD

**Issue by wunianqing** [MahApps/MahApps.Metro#3559]
**Describe the bug**
new a MetroWindow. Show it. Then close. See the memory. The window still there.

**To Reproduce**
1. Create a new class inherit MetroWindow.(just for easier search in memory)
2. create an instance of new class.
2. Show it.
3. Then close.
4. Take a snapshot of memory.
5. See the memory. The window still there.

**Expected behavior**
The window should be disposed.

**Screenshots**
![image](https://user-images.githubusercontent.com/12225840/61702610-b2d9b580-ad72-11e9-962a-b45ddb94a775.png)

**Environment(please complete the following information):**
 - MahApps.Metro version [latest]
 - OS: [Win10 1903]

**Additional context**
You can just try with the VSDemo window.

**Comment by wunianqing** [comment]
First, I saw the instance was referred by WindowCommands.cs. So I set ParentWindow to null when unloaded. Then I saw it was referred by other control. I don't know how to fix it now.

**Comment by punker76** [comment]
@wunianqing I can't reproduce this with dotMemory 2019, the VSDemo is always destroyed. I don't know what's the difference in the Diagnostic Tools. Maybe this is normal, because if I open and close the VS Demo much more times then there is exactly always only one "instance" when I look into the Heap.

**Comment by wunianqing** [comment]
I will try it with dotMemory 2019 then update.

**Comment by wunianqing** [comment]
OK, I tried it with dotMemory. And it does works fine. It is a issue of Diagnostic Tools. It can not tell me the correct count of objects.
