### ISSUE TITLE
How to move text to center in MetroTabItem

### ISSUE THREAD

**Issue by Hyung-Kim** [MahApps/MahApps.Metro#3562]
<Style TargetType="{x:Type metroControls:MetroTabItem}">
                        <Setter Property="metroControls:ControlsHelper.HeaderFontSize" Value="34"/>
                        <Setter Property="HorizontalContentAlignment" Value="Center"/>
                        <Setter Property="Width" Value="200"/>
                        <Setter Property="Background" Value="Transparent"/>
                        <Setter Property="Header" Value="{Binding Header}"/>
                    </Style>
Above code is not working . How to change text alignment to center?

**Comment by seba30** [comment]
Take a look at [here](https://github.com/MahApps/MahApps.Metro/blob/develop/src/MahApps.Metro/Themes/MetroTabItem.xaml) and search for **Alignment**. What do you see?

**Comment by Hyung-Kim** [comment]
HorizontalAlignment is fixed value to stretch. But I want to change value to center.
But, I am already solved this issue. 

<Style TargetType="{x:Type metroControls:MetroTabItem}">
                        <Setter Property="metroControls:ControlsHelper.HeaderFontSize" Value="34"/>
                        <Setter Property="HorizontalContentAlignment" Value="Center"/>
                        <Setter Property="Width" Value="200"/>
                        <Setter Property="Background" Value="Transparent"/>
                        <Setter Property="HeaderTemplate">
                            <Setter.Value>
                                <DataTemplate DataType="{x:Type TabItem}">
                                    <TextBlock Text="{Binding Header}" HorizontalAlignment="Center"/>
                                </DataTemplate>
                            </Setter.Value>
                        </Setter>
                    </Style>

**Comment by timunie** [comment]
@Hyung-Kim if you want to I can have a look if I can fix your issue in the template. Just reopen this issue and I will make a PR. If you are happy with the current solution you don't need to do anything. 

Happy coding 
Tim

**Comment by punker76** [comment]
@Hyung-Kim The horizontal and vertical content alignment will be set inherited. The real mistake of the issue is, that you are not inherit your style from the base MetroTabItem style, like

```
<Style TargetType="{x:Type metroControls:MetroTabItem}" BasedOn="{StaticResource {x:Type metroControls:MetroTabItem}}">
	<Setter Property="metroControls:ControlsHelper.HeaderFontSize" Value="34"/>
	<Setter Property="HorizontalContentAlignment" Value="Center"/>
	<Setter Property="Width" Value="200"/>
	<Setter Property="Background" Value="Transparent"/>
	<Setter Property="Header" Value="{Binding Header}"/>
</Style>
```
