### ISSUE TITLE
Using MahApps.Metro with Xamarin.Forms

### ISSUE THREAD

**Issue by Nessitro** [MahApps/MahApps.Metro#3569]
**Is your feature request related to a problem? Please describe.**
Hi! As Xamarin.Forms requires you to add:
xmlns:wpf="clr-namespace:Xamarin.Forms.Platform.WPF;assembly=Xamarin.Forms.Platform.WPF"
and
<wpf:FormsApplicationPage></wpf:FormsApplicationPage>
with 
public partial class MainWindow : FormsApplicationPage

Just like how this plugin is setup

**Describe the solution you'd like**
 I need another way of applying the theme to a window without specifying the base class if possible

**Additional context**
I took a look at https://mahapps.com/guides/advanced-guide.html but the methods described are obsolete

**Comment by punker76** [comment]
@Nessitro I'm sorry, but MahApps is not available for Xamarin.Forms, because it's a WPF library.

**Comment by Nessitro** [comment]
I don't know if you understand my question or if it's me who didn't understand your answer. I get that it's a wpf library. What I mean it that the way it's setup is similar to the way Xamarin.Forms is initialized in the wpf project and I cannot inherit from both classes (MetroWindow & FormsApplicationPage)

MahApps is working fine for me, i'm wondering if a Window can inherit from Xamarin.Forms's FormsApplicationPage class and still use MahApps.Metro as the underlying visual framework

**Comment by Nessitro** [comment]
@punker76 Hi again!
So I used Xamarin.Forms with Wpf & It's working good. I want to incorporate Mah's Metro style but I dunno how
[https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/other/wpf](WPF platform setup)

```xaml
<wpf:FormsApplicationPage x:Class="BoxViewClock.WPF.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:BoxViewClock.WPF"
        xmlns:wpf="clr-namespace:Xamarin.Forms.Platform.WPF;assembly=Xamarin.Forms.Platform.WPF"            
        mc:Ignorable="d"
        Title="BoxViewClock" Height="450" Width="800">
    <Grid>

    </Grid>
</wpf:FormsApplicationPage>
```

```c#
using Xamarin.Forms;
using Xamarin.Forms.Platform.WPF;

namespace BoxViewClock.WPF
{
    public partial class MainWindow : FormsApplicationPage
    {
        public MainWindow()
        {
            InitializeComponent();

            Forms.Init();
            LoadApplication(new BoxViewClock.App());
        }
    }
}
```

As you can see, once I inherit from FormsApplicationPage I cannot inherit from MetroWindow as well...

Is there a way to use MetroWindow without making my window inherit from it?

**Comment by drewkeller** [comment]
Yeah, I tried WPF in my Xamarin.Forms project using the same Microsoft instructions. It doesn't look very good, so I was looking into MahApps. Unfortunately, MetroWindow inherits from System.Windows.Window, so it is not going to work with FormsApplicationPage which comes from Xamarin.Forms.Platform.WPF. I imagine many things in MahApps are in the same situation.
