### ISSUE TITLE
Dependancy issue: ControlzEx 4.0.1

### ISSUE THREAD

**Issue by erikthysell** [MahApps/MahApps.Metro#3570]
Trying to update ControlzEz to latest stable (4.0.1) is not possible (yet).

> Unable to resolve dependencies. 'ControlzEx 4.0.1' is not compatible with 'MahApps.Metro 1.6.5 constraint: ControlzEx (>= 3.0.2.4 && < 4.0.0)'.

It would be nice if that would be fixed. Thanks for a great product!

**Comment by timunie** [comment]
Hello @erikthysell the latest Prerelease should support this Version. 

Happy coding 
Tim

**Comment by erikthysell** [comment]
Great! Thanks a lot.

tir. 6. aug. 2019 15.21 skrev Tim <notifications@github.com>:
