### ISSUE TITLE
Flyout z-index issue

### ISSUE THREAD

**Issue by gnewtzie** [MahApps/MahApps.Metro#3571]
**Is your feature request related to a problem? Please describe.**
Flyout on the Main Window is "underneath" the dialog overlay when a dialog is open. 
If you open a dialog on the main window and then from the dialog trigger a flyout, like a "Save Successfully" flyout that is on the Main Window, the overlay for opacity of the dialog is overtop the flyout shown on the main page. 

**Describe the solution you'd like**
Flyouts to be overtop of (higher in the z-index) than the dialog overlay.

**Additional context**

**Closed Issues**

**Comment by punker76** [comment]
@gnewtzie IMO, Dialogs should always have the higher priority.
