### ISSUE TITLE
How to adjust Badge offset ?

### ISSUE THREAD

**Issue by GreatFireWall** [MahApps/MahApps.Metro#3573]
I want to make it closer to the circle button

![image](https://user-images.githubusercontent.com/4510984/62984391-9a3a5800-be65-11e9-8506-3eca45d502ec.png)

**Comment by seba30** [comment]
```
<controls:Badged BadgePlacementMode="TopRight" Padding="-10" Margin="10">
    ...
</controls:Badged>
```

**Comment by GreatFireWall** [comment]
> ```
> <controls:Badged BadgePlacementMode="TopRight" Padding="-10" Margin="10">
>     ...
> </controls:Badged>
> ```

If i change `10` to `5`, and `-10` to `-5`, it like this:

![image](https://user-images.githubusercontent.com/4510984/62994687-c5d23800-be8f-11e9-94cf-7c16d9321aca.png)

**Comment by seba30** [comment]
The arrow circle needs more space. Do you have some XAML?

**Comment by GreatFireWall** [comment]
My xaml is too complex.. I think I should take some time to adjust it according to your instructions. Thank you.

**Comment by GreatFireWall** [comment]
![image](https://user-images.githubusercontent.com/4510984/62995107-c9ff5500-be91-11e9-8538-eb48e21d4398.png)

This works well. Thank you. 😄

**Comment by seba30** [comment]
You're welcome.
