### ISSUE TITLE
Copy All Menu RichTextBox

### ISSUE THREAD

**Issue by realivanjx** [MahApps/MahApps.Metro#3577]
Hi,

I think it would be better if we add "Copy All" to the right-click menu for richtextbox. My users sometimes wants to copy all text from richtextbox in my app and i want to make it easier by just a simple right click.

If you want to add keyboard shortcut too maybe either CTRL+SHIFT+C or CTRL+ALT+C but it is not required for my case.

Thanks.

![image](https://user-images.githubusercontent.com/12814796/63276848-6bd9d400-c2ce-11e9-8036-799247d97920.png)

**Comment by timunie** [comment]
@realivanjx I think this is more or less the normal behavoir for a textbox. This screenshot is from the google search field:
![image](https://user-images.githubusercontent.com/47110241/63294784-7cd51600-c2cb-11e9-9fef-ca9d9271218c.png)

I think we may add the select all item some day. For now you have the following options:
- Implement your own ContextMenu 
- Use the `AttachedProptery` for selecting all (I didn't try it with `RichTextBox`): `Controls:TextBoxHelper.SelectAllOnFocus="True"`

Happy coding 
Tim

**Comment by realivanjx** [comment]
Thanks for the response.

I thought this is common in windows. I saw Copy All in textbox menu on android. Thought that would be good too for mahapps to add this feature.

**Comment by realivanjx** [comment]
I would just stick to option one creating my own contextmenu

**Comment by timunie** [comment]
@realivanjx please reopen this issue as a reminder.  Thanks

**Comment by punker76** [comment]
@realivanjx You can override the ContextMenu for your RichTextBox and add the "Select All" Menu.

```xaml
    <ContextMenu x:Key="MahApps.TextBox.ContextMenu" Style="{StaticResource MahApps.Styles.ContextMenu}">
        <MenuItem Command="ApplicationCommands.Cut" Style="{DynamicResource MahApps.Styles.MenuItem}" />
        <MenuItem Command="ApplicationCommands.Copy" Style="{DynamicResource MahApps.Styles.MenuItem}" />
        <MenuItem Command="ApplicationCommands.Paste" Style="{DynamicResource MahApps.Styles.MenuItem}" />
        <Separator />
        <MenuItem Command="ApplicationCommands.SelectAll" Style="{DynamicResource MahApps.Styles.MenuItem}" />
    </ContextMenu>
```

But note: The menu is always Enabled, no matter if there is a text or not. This has to be handled by yourself.

e.g.

```xaml
<RichTextBox Name="txtSomeText"
  CommandManager.PreviewCanExecute="txtSomeText_PreviewCanExecute"
  Width="220" Height="25" Margin="10"/>
```

```csharp
private void txtSomeText_PreviewCanExecute(object sender, CanExecuteRoutedEventArgs e)
{
    if (e.Command == ApplicationCommands.SelectAll)
    {
        e.Handled = true;
        e.CanExecute = false; // enable/disable the menu
    }
}
```


@timunie This is also the reason why I don't like to offer the menu as default in MahApps, because then there are a lot of side effects to consider.

**Comment by timunie** [comment]
@punker76 I didn't know that this common feature is so hard to implement :confused: . Sometimes :m::heavy_dollar_sign: makes hard things easy and vice versa. 

Thank you anyway for your feedback and happy coding
Tim
