### ISSUE TITLE
HamburgerMenu Item OnClick "Page can have only Window or Frame as parent"

### ISSUE THREAD

**Issue by selimser** [MahApps/MahApps.Metro#3579]
Hi guys,

I have followed the exact steps to create my metro app from scratch with a hamburger menu. I have exact solution structure, same .net framework version (4.6.1) and same nuget package versions. I pretty much created the exact copy of the sample app I got from this link: [from this github repo](https://github.com/punker76/code-samples/tree/master/MahAppsMetroHamburgerMenuNavigation/MahAppsMetroHamburgerMenuNavigation) but no luck. I am getting the following error:

> System.InvalidOperationException: 'Page can have only Window or Frame as parent.'

However, for some reason, the demo app works perfectly but when I click on a menu item on the hamburger menu, it just throws this exception.

My MainWindow.xaml is the **Window** but it does not inherit from the Window class, instead inheriting **MetroWindow** class. Also my XAML for the main window starts with the **<controls:MetroWindow .....** tags.

The views are just simple pages which should be placed inside the content.

**Comment by punker76** [comment]
@selimser I've updated the code samples, so it should now work together with the latest MahApps v2.0 alpha.
