### ISSUE TITLE
PasswordBox Corner Radius

### ISSUE THREAD

**Issue by Jacquers** [MahApps/MahApps.Metro#3582]
I've successfully set the corner radius on textboxes, but I'm struggling to do the same on a password box. It just doesn't have any effect.

Here is part of my app.xaml

The background change works, but not the border.

Any help appreciated, thanks!

`<Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Colors.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/Red.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/BaseLight.xaml" />
            </ResourceDictionary.MergedDictionaries>
            
            <Style TargetType="{x:Type TextBox}">
                <Style.Resources>
                    <Style TargetType="{x:Type Border}">
                        <Setter Property="CornerRadius" Value="4" />
                    </Style>
                </Style.Resources>
            </Style>
            <Style TargetType="{x:Type PasswordBox}">
                <Setter Property="Background" Value="LightGreen" />
                <Style.Resources>
                    <Style TargetType="{x:Type Border}">
                        <Setter Property="CornerRadius" Value="4" />
                    </Style>
                </Style.Resources>
            </Style>`

**Comment by timunie** [comment]
@Jacquers I had a look in the template and it is a bug there. There is nothing you can do right now (if you do not want to reimplement the style.) I think we will have a fix for this issue soon. 

Happy coding 
Tim

**Comment by Jacquers** [comment]
Thanks, much appreciated.

In the mean time I've found a workaround using this: https://codereview.stackexchange.com/questions/197042/rounded-borders-for-different-controls-button-textbox-combobox-via-attached

But had to change some code:

// setting borders for non-combobox controls
Border border = control.Template.FindName("border", control) as Border;

to

// setting borders for non-combobox controls
Border border = control.Template.FindName("Base", control) as Border;
