### ISSUE TITLE
Font Naming Convention

### ISSUE THREAD

**Issue by amkuchta** [MahApps/MahApps.Metro#3584]
### Is your feature request related to a problem? Please describe.
Looking through the new naming conventions, `Fonts` are structured as follows:

- **FontFamily:** `MahApps.Fonts.[Family]` (e.g. `MahApps.Fonts.Header`)
- **Font Sizes:** `MahApps.Sizes.Font.[Size]` (e.g. `MahApps.Sizes.Font.Header`)

I think that this is namespacing is inconsistent, and that a small update could make things easier for other users to follow.

### Describe the solution you'd like
I suggest updating to the following naming convention for consistency:

- **FontFamily:** `MahApps.Font.Family.[Family]` (e.g. `MahApps.Font.Family.Header`)
- **Font Sizes:** `MahApps.Font.Size.[Size]` (e.g. `MahApps.Font.Size.Header`)

This creates a more consistent (and therefore easier to use) namespacing.

### Additional context
N/A

### Closed Issues
N/A

**Comment by Evangelink** [comment]
Yeah :D
I was having the same feeling when working on adding MUI styles.

**Comment by Evangelink** [comment]
That's ok on my side @amkuchta! Regarding the `.Default` suffix, it's up to you, I was a bit out of time lately to make progress on MUI.
