### ISSUE TITLE
Styles vs Themes Namespaces

### ISSUE THREAD

**Issue by amkuchta** [MahApps/MahApps.Metro#3587]
### Is your feature request related to a problem? Please describe.
Within MA.M, there are two separate namespaces for `Theme` vs `Style` (which also contains a `Theme` directory).  This is not intuitive, as the `Theme` Directory contains some styles (e.g. `HamburgerMenu`), and the actual themes for the application are located in the `Style/Theme` directory.

### Describe the solution you'd like
I suggest re-ordering the name spaces as follows:

- Move the application theme and accents under `MA.M/Themes`
- Move all styles under `MA.M/Styles`; include custom templates in the file with the appropriate themes (e.g. `HamburgerMenuTemplate` belongs in `Styles/Controls.HamburgerMenu.xaml`)

This makes it much easier to find the code needed to make an update to a control for a user's personal implementation.  It also makes application theme information much easier to find, as it is in the most logical location.

### Additional context
N/A

### Closed Issues
N/A

**Comment by bigworld12** [comment]
this has been bugging me for years, it is so hard to find a specific style or a template without searching every folder in the project, would love to see that change, i also agree on the last convention you proposed. (`MA.M/Styles/Button.Styles.xaml` and `MA.M/Styles/Button.Templates.xaml`)

**Comment by amkuchta** [comment]
@punker76 how do you feel about this?  I can start tackling it, but given the scope of the changes, I am worried that it will affect the work that you are putting in with regards to #3585 . If you don't think it will mess you up, I can take a swing at this.

**Comment by punker76** [comment]
@amkuchta I’m still investigating this, how we can provide this in an easy way. The upcoming Visual Studio will help us, because it has a better Intellisence for own resource dictionaries included. R# helps me and other since years. So please wait for a change for this issue. I’m not a friend for such a big change of separating each style and template to it’s own file. Thx

**Comment by amkuchta** [comment]
@punker76 I agree that improved Intellisense will help, but that does not help advanced users who have to search through the code to find entire templates or styles that they may need to override (or modify in a way that requires copying large chunks of code).  For that reason, I think that a refactor should occur, especially since there are multiple locations where directories like `Styles` and `Themes` occur.
