### ISSUE TITLE
Can't build 1.6.5 in VS2019

### ISSUE THREAD

**Issue by JVimes** [MahApps/MahApps.Metro#3588]
I tried:

1. Only the .NET Core SDK from the [build instructions](https://github.com/MahApps/MahApps.Metro/wiki/Building-the-MahApps.Metro-solution) is installed.
2. Checkout 1.6.5 (cb9264828def32d2c55ec32dc0426c8a72aa793d)
3. Run `.\.paket\paket.exe restore`
4. Rebuild twice in Visual Studio

    I get:
    ```
    1>Properties\AssemblyInfo.cs(7,12,7,21): error CS0246: The type or namespace name 'ThemeInfoAttribute' could not be found (are you missing a using directive or an assembly reference?)
    1>Properties\AssemblyInfo.cs(7,12,7,21): error CS0246: The type or namespace name 'ThemeInfo' could not be found (are you missing a using directive or an assembly reference?)
    1>Properties\AssemblyInfo.cs(9,12,9,23): error CS0246: The type or namespace name 'XmlnsPrefixAttribute' could not be found (are you missing a using directive or an assembly reference?)
    1>Properties\AssemblyInfo.cs(9,12,9,23): error CS0246: The type or namespace name 'XmlnsPrefix' could not be found (are you missing a using directive or an assembly reference?)
    1>Properties\AssemblyInfo.cs(10,12,10,23): error CS0246: The type or namespace name 'XmlnsPrefixAttribute' could not be found (are you missing a using directive or an assembly reference?)
    1>Properties\AssemblyInfo.cs(10,12,10,23): error CS0246: The type or namespace name 'XmlnsPrefix' could not be found (are you missing a using directive or an assembly reference?)
    1>Properties\AssemblyInfo.cs(12,12,12,27): error CS0246: The type or namespace name 'XmlnsDefinitionAttribute' could not be found (are you missing a using directive or an assembly reference?)
    1>Properties\AssemblyInfo.cs(12,12,12,27): error CS0246: The type or namespace name 'XmlnsDefinition' could not be found (are you missing a using directive or an assembly reference?)
    1>Properties\AssemblyInfo.cs(13,12,13,27): error CS0246: The type or namespace name 'XmlnsDefinitionAttribute' could not be found (are you missing a using directive or an assembly reference?)
    1>Properties\AssemblyInfo.cs(13,12,13,27): error CS0246: The type or namespace name 'XmlnsDefinition' could not be found (are you missing a using directive or an assembly reference?)
    1>Properties\AssemblyInfo.cs(14,12,14,27): error CS0246: The type or namespace name 'XmlnsDefinitionAttribute' could not be found (are you missing a using directive or an assembly reference?)
    1>Properties\AssemblyInfo.cs(14,12,14,27): error CS0246: The type or namespace name 'XmlnsDefinition' could not be found (are you missing a using directive or an assembly reference?)

    ...14000 more errors...
    ```

4. `.\build.ps1`

    I get:
    ```
    MahApps.Metro\src\MahApps.Metro.sln.metaproj : error MSB4057: The target "restore" does not exist in the project.
    ```

I'm running VS 16.2.3.

Any ideas?

**Comment by StuRamsey** [comment]
I'm running VS16.3.0 and 1.6.5 runs fine, maybe try updating VS

**Comment by ahmediddma** [comment]
getting the same error

**Comment by Coder-Bryan** [comment]
I also got the same errors when rebuilding the solution with VS 2019 16.2.2...

**Comment by JVimes** [comment]
@StuRamsey I tried VS 16.3.0 Preview, same errors. What Visual Studio workloads do you have installed? And did you install any individual components? What versions of .NET Core SDK do you have installed?

I'm guessing there's a prerequisite not mentioned in the [build instructions](https://github.com/MahApps/MahApps.Metro/wiki/Building-the-MahApps.Metro-solution).

**Comment by ahmediddma** [comment]
> 
> 
> @StuRamsey I tried VS 16.3.0 Preview, same errors. What Visual Studio workloads do you have installed? And did you install any individual components? What versions of .NET Core SDK do you have installed?
> 
> I'm guessing there's a prerequisite not mentioned in the [build instructions](https://github.com/MahApps/MahApps.Metro/wiki/Building-the-MahApps.Metro-solution).

i think 1.6.5 doesn't target dot net core anyway i have preview 6, 7 and 8 and i can use it from within the visual studio but i still can't build it

**Comment by StuRamsey** [comment]
I don't have anything special loaded, work load C#, VB, C++ with Code Maid (but had that on 2017 as well) I've got RDCL installed, but that was much later. To be truefull I just installed Mahapps and it worked

**Comment by JVimes** [comment]
@ahmediddma, don't forget to upvote 👍 this issue, above.

**Comment by punker76** [comment]
I created this branch to allow a build in VS 2019 (without .Net 4.0 target)

https://github.com/MahApps/MahApps.Metro/tree/master-vs2019-v1.6.5

**Comment by JVimes** [comment]
@punker76 I get the same errors on that branch. Why did you close this ticket before verifying the issue is fixed? We can't build it on your computer.

**Comment by punker76** [comment]
@JVimes Sorry for this, I tried this with the latest VS 16.x.y version and it compiled with the powershell script ‘.\build.ps1’. I will try this at home again with my machine. I must say that the 1.6.5 was created with the VS 2017.
Why do you need to compile this again on your machine?

**Comment by JVimes** [comment]
@punker76 Thank you. I build 1.6.5 so I can learn the latest release by reading/modifying the demo app source code.

The new branch's build.ps1 gives me, "An error occurred when executing task 'Restore'.". I set verbosity to diagnostic, but no more details emerged.

**Comment by punker76** [comment]
@JVimes Please try again the latest change at this branch. I've updated the cake script to use the NuGetRestore instead calling the NuGet executable directly. 🙏

**Comment by JVimes** [comment]
Thank you. Build.ps1 now gives:

> C:\Users\username\MahApps.Metro\src\Mahapps.Metro.Tests\MahApps.Metro.Tests.csproj : error : Unable to locate the .NET Core SDK. Check that it is installed and that the version specified in global.json (if any) matches the installed
> version.
>
> C:\Users\username\.nuget\packages\msbuild.sdk.extras\2.0.31\Sdk\Sdk.props(7,3): error : Unable to locate the .NET Core SDK. Check that it is installed and that the version specified in global.json (if any) matches the installed versi on.
>
> C:\Users\username\.nuget\packages\msbuild.sdk.extras\2.0.31\Sdk\Sdk.props(7,31): error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found. [C:\Users\username\MahApps.Metro\src\MahApps.Metro\MahApps.Metro.csproj]
>
> An error occurred when executing task 'Build'.

The only .NET Core SDK I have is 3.0.100 preview 9. I tried reinstalling it.

If I open the .sln, each project shows "(load failed)" in solution explorer. If I select "reload project", I get :

> C:\Users\username\MahApps.Metro\src\MahApps.Metro\MahApps.Metro.csproj : error  : The expression "[System.IO.Path]::GetDirectoryName('')" cannot be evaluated. The path is not of a legal form.  C:\Users\username\.nuget\packages\msbuild.sdk.extras\2.0.31\Sdk\Sdk.props
> 
> C:\Users\username\MahApps.Metro\src\MahApps.Metro.Samples\MahApps.Metro.Demo\MahApps.Metro.Demo.csproj : error  : The expression "[System.IO.Path]::GetDirectoryName('')" cannot be evaluated. The path is not of a legal form.  C:\Users\username\.nuget\packages\msbuild.sdk.extras\2.0.31\Sdk\Sdk.props
> 
> C:\Users\username\MahApps.Metro\src\MahApps.Metro.Samples\MahApps.Metro.Caliburn.Demo\MahApps.Metro.Caliburn.Demo.csproj : error  : The expression "[System.IO.Path]::GetDirectoryName('')" cannot be evaluated. The path is not of a legal form.  C:\Users\username\.nuget\packages\msbuild.sdk.extras\2.0.31\Sdk\Sdk.props
> 
> C:\Users\username\MahApps.Metro\src\Mahapps.Metro.Tests\MahApps.Metro.Tests.csproj : error  : The project file cannot be opened by the project system, because it is missing some critical imports or the referenced SDK cannot be found.
> 
> Detailed Information:
> Unable to locate the .NET Core SDK. Check that it is installed and that the version specified in global.json (if any) matches the installed version.
> 
> 
> C:\Users\username\MahApps.Metro\src\MahApps.Metro\MahApps.Metro.csproj : error  : The expression "[System.IO.Path]::GetDirectoryName('')" cannot be evaluated. The path is not of a legal form.  C:\Users\username\.nuget\packages\msbuild.sdk.extras\2.0.31\Sdk\Sdk.props
> 
> C:\Users\username\MahApps.Metro\src\MahApps.Metro\MahApps.Metro.csproj : error  : The expression "[System.IO.Path]::GetDirectoryName('')" cannot be evaluated. The path is not of a legal form.  C:\Users\username\.nuget\packages\msbuild.sdk.extras\2.0.31\Sdk\Sdk.props
> 
>

**Comment by donos-63** [comment]
Hi all,

I have the same issue than JVimes. Could you please re-open the ticket?
master => VS2017 ok
develop => VS2019 ok
master-2019-1.6.5 KO
thank you.

**Comment by oghenez** [comment]
> I created this branch to allow a build in VS 2019 (without .Net 4.0 target)
> 
> https://github.com/MahApps/MahApps.Metro/tree/master-vs2019-v1.6.5

I Tried opening this branch, but get an error saying it does not exists

> 404 - page not found
> The develop branch of MahApps.Metro  does not contain the path -vs2019-v1.6.5.

**Comment by punker76** [comment]
> I am usinf vs v 16.9.0 and have the same error loading the MahApps v1.6.5 , i tried the link provided, but no success
> 
> > I created this branch to allow a build in VS 2019 (without .Net 4.0 target)
> > https://github.com/MahApps/MahApps.Metro/tree/master-vs2019-v1.6.5
> 
> I Tried opening this branch, but get an error saying it does not exists
> 
> > 404 - page not found
> > The develop branch of MahApps.Metro  does not contain the path -vs2019-v1.6.5.

@oghenez The v1.6.5 is deprecated for years now, so I deleted this branch. What you can do is, use v2.x and VS 2022.
