### ISSUE TITLE
Various errors building latest commit on develop

### ISSUE THREAD

**Issue by Evangelink** [MahApps/MahApps.Metro#3589]
**Describe the bug**

I did a fresh clone of MahApps.Metro and when trying to compile the solution I have the following issues (they might be related that's why I am opening only one ticket).

Various **NU1701**:
```
Warning	NU1701	Package 'Microsoft.Xaml.Behaviors.Wpf 1.0.1' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.0'. This package may not be fully compatible with your project.
```

Various **NU1605**:
```
Error	NU1605	Detected package downgrade: Fody from 6.0.0 to 5.2.0. Reference the package directly from the project to select a different version. 
 MahApps.Metro.Demo -> Costura.Fody 4.1.0 -> Fody (>= 6.0.0) 
 MahApps.Metro.Demo -> Fody (>= 5.0.0)
```

It seems that the last commit is correctly building on the CI agent so I am assuming there is some missing resource or misconfigured thing on my machine. I am open to suggestion on what could be wrong.

Thank you!

**Environment**
 - MahApps.Metro commit 87e7bb10e620a74c8249f99895093f3c5eb49e2c
 - OS: Win10
 - Visual Studio 16.2.2
 - .NET Core SDKs installed:
  1.1.14 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.604 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.202 [C:\Program Files\dotnet\sdk]
  2.2.204 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  2.2.301 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.0.100-preview6-012264 [C:\Program Files\dotnet\sdk]

**Comment by punker76** [comment]
@Evangelink is fixed now

**Comment by punker76** [comment]
@Evangelink The `NU1701` warning is ok for now, because this package is still not available for .Net Core 3

**Comment by Evangelink** [comment]
You rock!
