### ISSUE TITLE
TextBoxHelper.WatermarkAlignment doesn't work as it should

### ISSUE THREAD

**Issue by StuRamsey** [MahApps/MahApps.Metro#3594]
The alignment of the Watermark in the Textbox doesn't seem to work correctly. I'm using the Textbox to input numbers, so the HorizontalContentAlignment of the Textbox is set to Right, but I want the Watermark to stay left aligned. It doesn't it moves over to the right, even thought it clearly is set to left at TextBoxHelper.WatermarkAlignment. I've seen the comment about setting the HorizontalContentAlignment to Stretch, but that moves the input content back to the left and as its a number input I want it to be right aligned.

**Comment by StuRamsey** [comment]
Sorry forgot to put 
Mahapps.Metro v1.6.5 on Visual Studio 2016 v16.3.0 Preview 2.0

**Comment by punker76** [comment]
@StuRamsey If you set HorizontalContentAlignment to Stretch then you can set the TextAlignment to Right.

**Comment by StuRamsey** [comment]
Many thanks, not quite how I thought it would be done, but perfect result.

Thanks again
Stu
