### ISSUE TITLE
All elements in window are moving a less or more from right to left after app startup

### ISSUE THREAD

**Issue by rabambar** [MahApps/MahApps.Metro#3595]
I've tried all versions, it occurs on my machine at home and on various machines at work.

**Comment by seba30** [comment]
Can you please make a [GIF](https://www.screentogif.com/)?

**Comment by punker76** [comment]
@rabambar Sounds like, that you mean the transition effect. This can be disabled with the MetroWindow Property WindowTransitionsEnabled when you set it to false.

**Comment by rabambar** [comment]
WindowTransitionsEnabled helped. Thx
