### ISSUE TITLE
The type of OverrideDefaultWindowCommandsBrush should be Brush rather then SolidColorBrush

### ISSUE THREAD

**Issue by punker76** [MahApps/MahApps.Metro#3598]
by @whopacha asked in Gitter

Any reason why OverrideDefaultWindowCommandsBrushProperty uses SolidColorBrush rather than Brush?

**Comment by timunie** [comment]
@punker76 I am wondering why this change is a breaking change? I always thought that `SolidColorBrush` inherits `Brush`, so the change should work with previous code. Am I wrong? 

Happy coding
Tim

**Comment by punker76** [comment]
@timunie You're right! 👍
