### ISSUE TITLE
Unable to add Toolbox Controls

### ISSUE THREAD

**Issue by Klaseek** [MahApps/MahApps.Metro#3601]
I've noticed this one reported many times before and I've tried to the fixes outlined in the resolve notes,

When adding the ControlzEx.dll & MahApps.Metro.dll files I received the generic error that they contain no components to be added. I've tried VS 2019 .net 4.5, 4.6 4.7 & VS 2019 Preview 3.0 Core preview 9.0.

Any assistance as to what I'm doing wrong would be greatly appreciated.

**Comment by punker76** [comment]
@Klaseek To add the controls to the Toolbox it's necessary to add all these dlls

- ControlzEx.dll
- MahApps.Metro.dll
- Microsoft.Xaml.Behaviors.dll

I tested this via drag&drop this 3 dlls from the file explorer to the ToolBox.

**Comment by Klaseek** [comment]
@punker76 - Thanks for the response, I've tried with adding in all 3 and just receive the error 3 times over. When drag & dropping there is no error or message and no tools are added, is there a specific version of modules to .net framework required? Not sure why this is proving to be so difficult, have tested on a fresh machine as well with the same error.

Is there a known working config I can try and replicate? In terms of which .Net framework and which module version?

**Comment by punker76** [comment]
> EDIT - Have got it working with .Net 4.5 when using version 45 of the respective modules,

Good to hear.

> was unable to get it working with .net core, 4.6 or 4.7

This seems legit. I don't know what's wrong with VS when this issue pops up. The MahApps dlls are normal ones and should be allowed to add.
