### ISSUE TITLE
Display Message Dialog after starting a new thread not working

### ISSUE THREAD

**Issue by mostafa901** [MahApps/MahApps.Metro#3602]
Hi, not sure if I am missing something... If i started a new thread from the 1st window to show another window (window 2, which works fine) and then I notify by a message dialog via DialogCoordinator (on the 1st window) I receive this error
The calling thread cannot access this object because a different thread owns it

```
async public Task StartNewThread()
    {
            var thread = new Thread(new ThreadStart(() =>
            {
                var win = new ThreadWindow();
                win.ShowDialog();
            }));
            thread.SetApartmentState(ApartmentState.STA);
            thread.IsBackground = true;
            thread.Start();

            //the below statement works fine if the above thread did not start
            await instance.ShowMessageAsync(this, "Test", "Message");

        }
```
 a quick repo for this issue:
[https://github.com/mostafa901/Mahapps_Test/tree/Show_Message_MThread](https://github.com/mostafa901/Mahapps_Test/tree/Show_Message_MThread)
 
  I just checked again now Release: 2.0.0-alpha0480, but still not working :(

**Comment by punker76** [comment]
@mostafa901 I tested your sample with the latest v2.3.4 and it seems that it works now with the following change for showing the message dialog.

```
public async Task StartNewThread(Dispatcher mydisp)
{
    var thread = new Thread(() =>
    {
        var win = new ThreadWindow();
        win.ShowDialog();
    });
    thread.SetApartmentState(ApartmentState.STA);
    thread.IsBackground = true;
    thread.Start();

    await Task.Delay(1000); //give time to open the above window

    await instance.ShowMessageAsync(this, "Test", "Message");
}
```

**Comment by mostafa901** [comment]
@punker76 Thanks. It now indeed works...partially. if you clicked o test thread window button. the second time it gets frozen.
to reproduce that:
1. click on the test button
2. close the new window
3. click ok on the message dialog.
4. repeat steps 1->3,  !! you would get the original window frozen.

**Comment by punker76** [comment]
@mostafa901 I forgot to give you the complete working code. So here is it

```
public async Task StartNewThread()
{
    var thread = new Thread(() =>
    {
        var win = new ThreadWindow();
        win.Closed += ThreadWindow_Closed;
        win.ShowDialog();
        // do this
        Dispatcher.Run();
    });
    thread.SetApartmentState(ApartmentState.STA);
    thread.IsBackground = true;
    thread.Start();

    await Task.Delay(1000); //give time to open the above window

    await instance.ShowMessageAsync(this, "Test", "Message");
}

private void ThreadWindow_Closed(object sender, EventArgs e)
{
    // and this
    ((ThreadWindow) sender).Dispatcher.BeginInvokeShutdown(DispatcherPriority.Background);
}
```
