### ISSUE TITLE
Custom Dialog ignoring Accent color

### ISSUE THREAD

**Issue by KKauK** [MahApps/MahApps.Metro#3603]
Custom Dialog ignoring Accent color.

1. Go to 'Dialog'
2. Check "Use accent"
3. Open Customer Dialog

Custom dialog should use accent color.

 - MahApps.Metro version [v2.0.0]

**Comment by KKauK** [comment]
@Tim Okay, might be true.

Thanks again
KKauK

**Comment by punker76** [comment]
@KKauK this has now been fixed, and it will be released in the next version of MahApps.Metro v2.0
