### ISSUE TITLE
Right/Left WindowCommandsOverlayBehavior missing members

### ISSUE THREAD

**Issue by telmer6** [MahApps/MahApps.Metro#3604]
**Description**
The `LeftWindowCommandsOverlayBehavior` and `RightWindowCommandsOverlayBehavior` properties of the `MetroWindow` class do not offer the members listed on https://mahapps.com/controls/flyouts.html `Flyouts` and `Always`.

**To Reproduce**
1. Create a `MetroWindow`
2. Attempt to set `LeftWindowCommandsOverlayBehavior` or `RightWindowCommandsOverlayBehavior` to `Flyouts` and `Always`

**Expected behavior**
Window commands should be drawable over flyouts.

**Environment(please complete the following information):**
 - Lib: MahApps.Metro version 2.0.0-alpha0479
 - OS: Windows 10 Pro 10.0.18362
 - IDE: Ryder JetBrains Rider 2019.2.2
 - Build Tool: Visual Studio Enterprise 2017 15.9.15
 - .NET Framework: 4.7.2

**Additional context**
The properties `LeftWindowCommandsOverlayBehavior` and `RightWindowCommandsOverlayBehavior` use the `WindowCommandsOverlayBehavior` enum, rather than the `OverlayBehavior` enum used by the `WindowButtonCommandsOverlayBehavior` property, which does not offer members `Flyouts` and `Always`. The documentation at https://mahapps.com/controls/flyouts.html may be out of date, but the existing functionality still seems undesirable.

**Comment by punker76** [comment]
@telmer6 You're right, the documentation is out of date for the upcoming v2.0. And there was a breaking change for these behaviors: After #3511 and ca9c76ceb1cb82aa904b19fec09c052d728d6573 the default for the left and right window commands behavior is set to `WindowCommandsOverlayBehavior.Never`. So if you set `ShowTitleBar` to false they will not shown and will now also not shown over flyouts. They only visible if you set this to `WindowCommandsOverlayBehavior.HiddenTitleBar`.

**Comment by telmer6** [comment]
That's unfortunate. I'd rather have the prior behavior, but I can live without it.

**Comment by H1-N1** [comment]
> Member

hi punker 
can you provide an exemple pleas ?
i dont get it :)
