### ISSUE TITLE
HamburgerMenu: Previous view controls can still be clicked.

### ISSUE THREAD

**Issue by HispidaBytes** [MahApps/MahApps.Metro#3605]
**Describe the bug**
An HamburgerMenu with the "Content" property bound to a ViewModel property in the ViewModel. Clicking on a menu item changes the ViewModel bound to the "Content" property.
The issue is that items of the View before the ViewModel change can still be clicked.

This seems to be caused by the change in commit 32d263c0b37f19bb043824a4f82e2edd7ed03bbf 

**To Reproduce**

I've created a demo solution to show the problem:
[https://github.com/HispidaBytes/HamburgerMenuIssue](https://github.com/HispidaBytes/HamburgerMenuIssue)

**Screenshots**
![mah issue](https://user-images.githubusercontent.com/34475384/64955059-82505c80-d887-11e9-9509-464644403725.gif)

**Environment:**
 - MahApps.Metro version 2.0.0-alpha0479
 - OS: Win10 1903 x64
 - Visual Studio 2019 16.3.0
 - .NET Core 3 Preview 8

**Comment by punker76** [comment]
@HispidaBytes this has now been fixed, and it will be released in the next version of MahApps.Metro v2.0 Thank you for the short sample!
