### ISSUE TITLE
TooltipText information??

### ISSUE THREAD

**Issue by mummyildiz** [MahApps/MahApps.Metro#3606]
If Tooltip Text is full on TextBox objects, can we inform the end user as in the picture?
Can we determine the color at the bottom right and separately?

![tooltipText](https://user-images.githubusercontent.com/5136066/65027942-e0427a00-d943-11e9-976d-81e45f2df866.png)

**Comment by punker76** [comment]
@mummyildiz This text comes from the WPF validation [Link 1](https://docs.microsoft.com/en-us/dotnet/framework/wpf/data/how-to-implement-validation-logic-on-custom-objects), [Link 2](https://docs.microsoft.com/en-us/dotnet/framework/wpf/data/how-to-implement-binding-validation). 

The style can be changed if you override this [validation template](https://github.com/MahApps/MahApps.Metro/blob/cb9264828def32d2c55ec32dc0426c8a72aa793d/src/MahApps.Metro/Styles/ValidationErrorTemplate.xaml#L13) and use it at your TextBox.
