### ISSUE TITLE
the resource "MahApps.Styles.ComboBox.Virtualized" could bot be resolved?

### ISSUE THREAD

**Issue by mummyildiz** [MahApps/MahApps.Metro#3607]
![Screenshot_4](https://user-images.githubusercontent.com/5136066/65053497-b6557b80-d974-11e9-8a45-3f08bd122e67.png)

which is taken to add resources. We have added the following.

![Screenshot_5](https://user-images.githubusercontent.com/5136066/65053756-26640180-d975-11e9-86e0-d1388d039b99.png)

**Comment by mxsoftware** [comment]
Try to create

Properties\DesignTimeResources.xaml

with content:

<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
    <ResourceDictionary.MergedDictionaries>

        <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
        <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
        <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Colors.xaml" />

        
        

        <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/Cobalt.xaml" />

        
        
        <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/BaseLight.xaml" />

        <ResourceDictionary Source="pack://application:,,,/MxMvvm.Resources;component/Resources/Icons.xaml" />

    </ResourceDictionary.MergedDictionaries>
</ResourceDictionary>

and modify manually project file with:

    <Page Include="Properties\DesignTimeResources.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
      <ContainsDesignTimeResources>true</ContainsDesignTimeResources>
    </Page>

**Comment by punker76** [comment]
@mummyildiz You need to add the new accent / theme resources if you use the new style names together with the latest NuGet alpha (or source): https://github.com/MahApps/MahApps.Metro/wiki/Quick-Start

**Comment by mummyildiz** [comment]
I am using v1.6.5. I still can't fix it.

**Comment by punker76** [comment]
@mummyildiz In v1.6.5 the key for the virtual CombBox style is `VirtualisedMetroComboBox` .

https://github.com/MahApps/MahApps.Metro/blob/cb9264828def32d2c55ec32dc0426c8a72aa793d/src/MahApps.Metro/Styles/Controls.ComboBox.xaml#L612

**Comment by mummyildiz** [comment]
Thank you. The problem has improved.
