### ISSUE TITLE
Unable to globally change TitleCharacterCasing in MetroWindow

### ISSUE THREAD

**Issue by nandre15** [MahApps/MahApps.Metro#3608]
**Describe the bug**
I have a Resource Dictionary that styles the MetroWindow control. I have set the TitleCharacterCasing to normal; however, this value is still being overridden by MetroWindow control somewhere. When I modify this property within the MainWindow, the setting sticks, however, I need this property to be set to Normal on all my windows without having to explicitly set this property within all my windows. 

Is there anyway to modify this property globally?

XAML within my resource dictionary
<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                    xmlns:controls="http://metro.mahapps.com/winfx/xaml/controls"
                    xmlns:controls1="clr-namespace:USFS.DocHub.UI.Desktop.Controls"
                    xmlns:system="clr-namespace:System;assembly=mscorlib"
                    xmlns:cal="http://www.caliburnproject.org"
                    xmlns:desktop="clr-namespace:USFS.DocHub.UI.Desktop">

    <Style TargetType="{x:Type controls:MetroWindow}"  >
        <Setter Property="WindowTransitionsEnabled" Value="False" />
        <Setter Property="EnableDWMDropShadow" Value="True" />
        <Setter Property="TitleCharacterCasing" Value="Normal"></Setter>
        <Setter Property="controls:ControlsHelper.ContentCharacterCasing" Value="Normal" />
    </Style>

    
</ResourceDictionary>

**Screenshots**
![image](https://user-images.githubusercontent.com/43477657/65175956-d42cea00-da21-11e9-9ea2-b5161b50bba5.png)

**Comment by punker76** [comment]
@nandre15 You can create a style like yours with a key and use it then on your windows. Here two links from SO with more information and help

- https://stackoverflow.com/a/4284229/920384
- https://stackoverflow.com/q/431940/920384

**Comment by nandre15** [comment]
Thank you. I was hoping those weren't the solutions, but understand why they are.
