### ISSUE TITLE
Question: How to add progressbar to datagrid 

### ISSUE THREAD

**Issue by Torchok19081986** [MahApps/MahApps.Metro#3615]
Hallo, i have some problems to add progressbar from controls to datagrid. 
I simple dont know how to add it.  My goal is datagrid with 3 or 4 columns. One columns should be as Progressbar, where i can show some downloadprogress. 
I try to add it in DataGrid , but datagrid doesnt show metro progressbar in one of column. 
Can someone help me with and provide some code or link  ?
I want to use WPF and Visual Studio 2019 with 16.3 Update  (24.09.2019) with Net Framework 4.7.2

**Comment by seba30** [comment]
Something like this?

![image](https://user-images.githubusercontent.com/48946764/65598041-d56a9380-df9a-11e9-982d-f44570581a8f.png)

**Comment by Torchok19081986** [comment]
Hallo, @seba30. Yes, only one change, i have to show in downloadprogress in proggressbar.

**Comment by seba30** [comment]
Here's the code:

![image](https://user-images.githubusercontent.com/48946764/65598229-401bcf00-df9b-11e9-9cea-3cff660aa076.png)

You can bind the progress to any value in your model.

**Comment by Torchok19081986** [comment]
Many Thanks, @seba30. I going  to try it. converter and cal are alias to class with some converter and your class for Wi-Fi, i am rght ?

**Comment by seba30** [comment]
`cal` is the namespace for Caliburn.Micro

and

`converter` for my translation engine

**Comment by Torchok19081986** [comment]
Ok. Last question, do you use mahapps.metro pacakge in 1.6.5 or already 2.0 or better ?

**Comment by seba30** [comment]
1.6.5

**Comment by Torchok19081986** [comment]
Thanks a lot, @seba30.

**Comment by seba30** [comment]
You're welcome, @Torchok19081986
