### ISSUE TITLE
Could not load file or assembly 'ControlzEx.XmlSerializers, Version=3.0.2.4'

### ISSUE THREAD

**Issue by jtattreo** [MahApps/MahApps.Metro#3617]
Hi,

I have an application built using Mahapps.Metro, which in turn has a dependency on version 3.0.2.4 of ControlzEx, and I am getting an exception at program startup complaining that ControlzEx.XmlSerializers, Version=3.0.2.4, Culture=neutral, PublicKeyToken=null or one of it's dependencies could not be loaded.

I am not sure how to go about troubleshooting this. I cannot upgrade to a newer version of the Nuget package because 3.0.2.4 is the newest version that Mahapps will work with. I have tried uninstalling/reinstalling both packages to no avail. 

![image](https://user-images.githubusercontent.com/3751294/65818691-282d9080-e1d1-11e9-9ae3-16a56acba061.png)

 - MahApps.Metro version v1.6.5
 - OS: Win10 1903
 - Visual Studio 2019 16.3.1
 - .NET Framework 4.8

**Comment by timunie** [comment]
Hi @jtattreo 

There is a prerelease of MahApps.Metro v2.0 available. It uses a newer version of ControlzEX. IMO it is safe to use, but keep in mind that there are several breaking changes, especially for the resource names (see #3552 )
![image](https://user-images.githubusercontent.com/47110241/65819505-b16ab480-e21d-11e9-9f33-06eeeef36b97.png)

Happy coding
Tim

**Comment by punker76** [comment]
@jtattreo Never saw such an issue and it seem like an issue, but also looks like it is the normal behavior of .NET Framework and it is expected.

- https://www.telerik.com/support/kb/winforms/details/could-not-load-file-or-assembly-telerik-wincontrols-xmlserializers
- https://social.msdn.microsoft.com/Forums/en-US/9f0c169f-c45e-4898-b2c4-f72c816d4b55/strange-xmlserializer-error?forum=asmxandxml
- https://stackoverflow.com/questions/1127431/xmlserializer-giving-filenotfoundexception-at-constructor
- https://stackoverflow.com/questions/934411/what-is-myassembly-xmlserializers-dll-generated-for

**Comment by jtattreo** [comment]
Thank you both for your quick replies. @punker76 , good find on the references. I was fixated on it being a Mahapps or ControlzEx problem, and should have broadened my search before posting. 

ps. Love this project!
