### ISSUE TITLE
[Feature Request] Add a property to set the font size of dialog buttons

### ISSUE THREAD

**Issue by FlashDeviant** [MahApps/MahApps.Metro#3618]
**Is your feature request related to a problem? Please describe.**
It's great having easy control over different elements of the MahApps dialogs but one absent feature is the font size of the buttons themselves. One app that I am making is destined for a tablet which needs enlarged text to make it easily readable for all users. Being able to boost the Dialog title and message font size through the MetroDialogOptions is extremely helpful for this, but adding functionality to allow the same for buttons would make it all round helpful for me. It would allow the buttons to be easily read and tapped.

**Describe the solution you'd like**
Currently when making a dialog with adjusted font sizes I use MetroDialogOptions to achieve this like below:
```csharp
result = await ShowMessageAsync(
    "Warning", 
    "Do you wish to proceed?",
    MessageDialogStyle.AffirmativeAndNegative,
    new MetroDialogSettings
    {
        AffirmativeButtonText = "Yes",
        NegativeButtonText    = "No",
        DialogMessageFontSize = 26, DialogTitleFontSize = 36
    });
```

It would be great to add a property to it similar to `DialogMessageFontSize` and `DialogTitleFontSize`, such as `DialogButtonFontSize`.

I am not sure how easily this can be done. I'm reading through the code myself to understand this now and if I can find a way I'll attach it here.

**Closed Issues**
https://github.com/MahApps/MahApps.Metro/issues/3353

**Comment by MeikTranel** [comment]
Hey @punker76 seems simple. I'd like to do this. Seems to me that code has to be mostly identical to the code for DialogMessageFontSize etc.

**Comment by FlashDeviant** [comment]
Many thanks @MeikTranel and @punker76 for helping with this!
