### ISSUE TITLE
MeroWindow incorrect Glow behavior

### ISSUE THREAD

**Issue by minskowl** [MahApps/MahApps.Metro#3621]
**Describe the bug**
When on monitor have scale 125% GlowWindowBehavior draw shadow in invalid position when window place between to monitors ![InvalidGlow](https://user-images.githubusercontent.com/8179501/66042238-99987680-e524-11e9-961b-a868221df5d3.png)

**To Reproduce**

1. Use two monitors setup. 
2. Screen Settings: Muliple displays (Extend these display). Change size of text (125%)
3. Create MetroWindow with   GlowBrush="Black" 
4. Try to move this window between to monitors

**Expected behavior**

**Screenshots**
 ![InvalidGlow](https://user-images.githubusercontent.com/8179501/66042238-99987680-e524-11e9-961b-a868221df5d3.png)

![Settings](https://user-images.githubusercontent.com/8179501/66042791-20018800-e526-11e9-8023-3c937f4ea798.png)

**Environment:**
 - MahApps.Metro version  v1.6.5
 - OS: Win10 1803
 - Visual Studio 2015
 - .NET Framework  4.6

**Comment by punker76** [comment]
@minskowl This should be fixed and is availabel with the latest source (v2.0 alpha) and also available at NuGet.
