### ISSUE TITLE
Interest in addition?

### ISSUE THREAD

**Issue by jmiddour** [MahApps/MahApps.Metro#3630]
All,

I began working on a .Net Core 3.0 based MVVM wpf application shell for my employer.  After I found the IconPack packages, I showed this project to my colleague.  We really like what you folks have done with the MetroWindow and theming.

Would you have any interest in adapting and including what I've started into your project?
I'm still in the early stages and it's not feature complete.  But that also means I'm early enough in design to not have too much to change.

My vision for this "shell" is to ultimately have something similar to the WinUI NavigationWindow (possibly even using it once it's fully wpf compatible) and using .NetCore DI to build the menu structure.  I also want to include an Authorization filter in the future.

I've removed my organization specific code and uploaded the source [here](https://github.com/CodexObscura/ApplicationPages)

(solution file is in the ApplicationPages folder)

Please review and let me know if you have any interest.

Thanks,

Joe

**Comment by punker76** [comment]
@jmiddour Thank you for your offer to contribute here. If you have concrete changes, then introduce them in various PRs here and everyone can look at them and discuss them.
