### ISSUE TITLE
CornerRadius improvent for HeaderedControls

### ISSUE THREAD

**Issue by timunie** [MahApps/MahApps.Metro#3632]
**Is your feature request related to a problem? Please describe.**
In the latest alpha version many more controls may have a `CornerRadius`, including `GroupBox`. At the moment the `Header` gets just the top `CornerRadius`. IMO there should be a away to override this.  

**Describe the solution you'd like**
Introduce a new `AttachedProperty` that lets the user decide, if the Header gets the `CornerRadus` everywhere or not. 

**Additional context**
Current implementation:
![image](https://user-images.githubusercontent.com/47110241/66269158-8b5c9a00-e845-11e9-9083-886ada1ab444.png)

Expected result (optional to the user):
![image](https://user-images.githubusercontent.com/47110241/66269191-ea221380-e845-11e9-8a60-c9cb35d8304a.png)

**Closed Issues**
I will make a suggestion in a PR until next week

@punker76 if you don't like the idea, just close this FeatureRequest

**Comment by timunie** [comment]
Hello @punker76 ,

I have implemented my idea and have to see, that it will not work due to the usage of the transparent `AccentBrush`of the Border. If we would use Colors without transparency it might work. here is an image of my current implementation: 
![image](https://user-images.githubusercontent.com/47110241/66273392-c1b10e00-e873-11e9-8cf0-7400a7ac9962.png)

This border overlapping is my problem: 
![image](https://user-images.githubusercontent.com/47110241/66273425-181e4c80-e874-11e9-9d89-902584ac9f20.png)

I would be happy to hear your opinion to my suggestion. Should I make a PR that we can discuss then anyway?

Happy coding 
Tim

**Comment by punker76** [comment]
@timunie Thank you for that suggestion. 🙏  IMHO Do we really need this? It is not only the problem with the BorderBrush but also, e.g. with the Expander, the different directions in which the header is aligned. I think to consider this, makes the style even more complicated than that the user simply overwrites the style and uses his own.

**Comment by timunie** [comment]
Good Morning @punker76 ,

Thank you for your fast feedback. I have a solution for my problem with the `AccentColorBrush`. If the users need this feature is a different discussion, which I don't know. - I dont't need it at all - 

While working on this issue I made a few more changes, which may be discussed. Just check the things you like and I will make a PR for them.  

- [ ] Added `CornerRadius` to the Header of `GroupBox` (see pic. 1)
- [ ] Renamed `GroupBoxHelper` to `HeaderedControlHelper` as it supports `Expander` as well
- [ ] Reordered the Styles of `GroupBox` for easier finding all the different `Styles` in the soultion Folder (see pic. 2)

![image](https://user-images.githubusercontent.com/47110241/66292328-55222780-e8e4-11e9-8ef3-750eadd06f66.png)
**Picture 1 - Result** 

![image](https://user-images.githubusercontent.com/47110241/66292374-75ea7d00-e8e4-11e9-9e74-fe1651c7a436.png)
**Picture 2 - New folder structure proposal**

Here is the link to my draft if some wants to implement this feautre. 
[https://github.com/timunie/MahApps.Metro/tree/GroupBoxHeader_CornerRadius](https://github.com/timunie/MahApps.Metro/tree/GroupBoxHeader_CornerRadius)

*This feature request is closed because the benefit of this feature compared to the effort is too less, see answer from @punker76 above*

Happy coding 
Tim
