### ISSUE TITLE
Question: How to use template in visual studio 2019

### ISSUE THREAD

**Issue by Torchok19081986** [MahApps/MahApps.Metro#3635]
Hallo everyone, i have some trouble in vs 2019. I just downloaded template and crearte new project from template. Unfortunatally, in vs 2019 seems doenst show tempalte in designer on mainwindow.xaml, only if i execute it. 
Code for startwindow got from tutorials and quick start. 
```csharp
<Controls:MetroWindow
    x:Class="ProjectfromTemplate.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:Controls="http://metro.mahapps.com/winfx/xaml/controls"
    xmlns:iconPacks="http://metro.mahapps.com/winfx/xaml/iconpacks"
    Title="MainWindow"
    Width="525"
    Height="350"
    WindowStartupLocation="CenterScreen">
    <Controls:MetroWindow.RightWindowCommands>
        <Controls:WindowCommands>
            <Button Content="settings" />
            <Button>
                <StackPanel Orientation="Horizontal">
                    <iconPacks:PackIconModern
                        Width="24"
                        Height="24"
                        Kind="FoodCupcake" />
                    <TextBlock
                        Margin="4,0,0,0"
                        VerticalAlignment="Center"
                        Text="deploy cupcakes" />
                </StackPanel>
            </Button>
        </Controls:WindowCommands>
    </Controls:MetroWindow.RightWindowCommands>
    <Grid />
</Controls:MetroWindow>
```
i use visual studio 2019 and target .net framework 4.7.2.

P.S.: after i created new project from template , i update mahapps.metro libraries to newest 2.0 . 

Can someone help me with my "question" or suggest workaround ?

**Comment by punker76** [comment]
> Unfortunatally, in vs 2019 seems doenst show tempalte in designer on mainwindow.xaml, only if i execute it.

@Torchok19081986 Can you post a screenshot? Which MahApps version do you use?

**Comment by Torchok19081986** [comment]
Hallo, @punker76. Looks folowing 
![Window](https://user-images.githubusercontent.com/25432729/67405750-79a12380-f5b5-11e9-869b-0934ad7b7ebd.JPG)
I use MahApps.Metro Version. 1.6.5
After i start my project my mainwindow looks folowing:
![Window 2](https://user-images.githubusercontent.com/25432729/67405971-bc62fb80-f5b5-11e9-8fb0-6c0940e3edd0.JPG)

**Comment by punker76** [comment]
@Torchok19081986 The designer can't display the caption of a Window. So you will also don't see the window commands or min/max/close buttons. This is a designer limitation.
