### ISSUE TITLE
Accent Button

### ISSUE THREAD

**Issue by kalatchev** [MahApps/MahApps.Metro#3639]
Recently I found in Office 2019 kind of **accent button**, pointing a user to right, proper or good action. Here is the example:

![accent-button](https://user-images.githubusercontent.com/10154711/66389013-02be3500-e9d0-11e9-9c18-49f042d5899c.png)

Bootstrap and similar web UI kits also have a concept for button styles such as **success**, **danger**, **warning**, **primary**, **secondary**, etc.
It will be nice to have such predefined styles in MahApps. Having in mind different accent colors and themes, **I think the best option is to have an accent button with attached propeerty such as AccentColor**. With such as property, anyone can choose right color for action, depends on its needs and use case.

**Comment by kalatchev** [comment]
Thanks, I've found it. Meanwhile, I did for myself few other buttons, inspired from Bootstrap. Let me know if it worths to include in library.

![image](https://user-images.githubusercontent.com/10154711/66976813-f90d8f00-f0ab-11e9-9b56-94af791d604b.png)

**Comment by timunie** [comment]
Hi @kalatchev ,
At least you can upload your styles here so everyone can copy them, if you want to. 
Your buttons look great. 

Happy coding 
Tim

**Comment by kalatchev** [comment]
Thanks @timunie.  My code is just a copy-paste of original styles, mixed with CSS of Bootstrap :-) Anyway, I upload it in case someone find it usefull.

[SpecialButtons.zip](https://github.com/MahApps/MahApps.Metro/files/3739631/SpecialButtons.zip)
