### ISSUE TITLE
MetroCircleButtonStyle is not working with the 2.0 alpha release 0490

### ISSUE THREAD

**Issue by kunjiangkun** [MahApps/MahApps.Metro#3640]
MetroCircleButtonStyle is not working with the latest 2.0 alpha release 0490. It's working for me with alpha release 0262. In release 0490, the button appears to be rectangular. Do I need to make any changes to make it work?

**Environment(please complete the following information):**
 - MahApps.Metro version [v2.0.0-alpha0490]
 - OS: [Win10 1803]
 - Visual Studio [2019 16.2.5]
 - .NET Framework [4.6.1]

**Comment by timunie** [comment]
Hi @kunjiangkun 
can you post a sample code / xaml of your Button? We had a breaking change for the styles, so maybe the resource key is wrong.

Happy coding
Tim

**Comment by kunjiangkun** [comment]
`<Button x:Name="NewTestConfigurationFile"  
                        HorizontalAlignment="Left" 
                        Margin="0,5,5,0" 
                        VerticalAlignment="Top" 
                        Width="32" 
                        Height="32" 
                        Style="{DynamicResource MahApps.Metro.Styles.MetroCircleButtonStyle}"
                        Command="{Binding Path=NewTestConfigurationFileCommand}">
                        <iconPacks:PackIconMaterial Kind="Plus" Width="18" Height="18"/>
  </Button>`

**Comment by timunie** [comment]
Hi @kunjiangkun ,
please try: 
```
<Button x:Name="NewTestConfigurationFile"
        Width="32"
        Height="32"
        Margin="0,5,5,0"
        HorizontalAlignment="Left"
        VerticalAlignment="Top"
        Command="{Binding Path=NewTestConfigurationFileCommand}"
        Style="{DynamicResource MahApps.Styles.Button.Circle}">
    <iconPacks:PackIconMaterial Width="18"
                                Height="18"
                                Kind="Plus" />
</Button>
```
![image](https://user-images.githubusercontent.com/47110241/66511761-dee61680-ead7-11e9-9991-7eff4ccb553f.png)

Happy coding
Tim

**Comment by kunjiangkun** [comment]
Thanks for the feedback.
