### ISSUE TITLE
GlowBrush applied to MetroWindow too early

### ISSUE THREAD

**Issue by MisterNobody123** [MahApps/MahApps.Metro#3641]
**Bug description**
When opening a window in Windows 10, the window will both fade in and "grow" to its actual size (normal and intended behavior). When adding a GlowBrush to a MetroWindow, it visually interferes with the mentioned animation effect - the GlowBrush is applied immediately, i.e. before the window has reached its actual size. As a consequence, the brush is perceived as a "border" floating in midair while the window is opening

**To Reproduce**
1. Add a GlowBrush (e.g. of Color "Black") to a MetroWindow
2. Open the window

**Requested behavior**
Is it possible to either apply the GlowBrush only once the window animation has completed or expand the GlowBrush together with the window? It would be a bit painful to handle this manually for each and every window...

**Screenshots**
![MetroWindowGlowBrushIssue](https://user-images.githubusercontent.com/4752958/66503476-a50d1400-eac7-11e9-8c67-4178b212c52f.gif)

**Environment(please complete the following information):**
 - MahApps.Metro version 1.6.5
 - OS: Win10
 - Visual Studio 2017 15.9.11
 - .NET Framework 4.7.03190

**Comment by timunie** [comment]
Hi @MisterNobody123,

i think this issue will be solved with v2.0.0 (at least i can't reproduce it). You can test it with the prerelease if you want to. But please be aware, that there are some breaking changes.

Happy coding,
Tim

**Comment by MisterNobody123** [comment]
Hi @timunie,

thanks for the quick response! I did a short test with the 2.0.0-alpha0490 prerelease (used NuGet Package Manager Console to update within my Visual Studio project, hope this was correct) but I still see the same behavior as before... Makes me wonder if I'm doing something wrong on my side...

**Comment by MisterNobody123** [comment]
Okay, just realized that this doesn't happen when I use a brand new MetroWindow and setting only the GlowBrush while leaving everything else behind. That is, some of my adjustments cause the issue. (Regard my "steps to reproduce" from above as invalid. My apologies...)

**Comment by MisterNobody123** [comment]
Found it! (Lucky guess...)

When setting `WindowTransitionsEnabled="False"` on `<MetroWindow>`, the `GlowBrush` is applied immediately when the window is opening, hence causing the described appearance/behavior.
With `WindowTransitionsEnabled="True"`, the `GlowBrush` is applied with a smooth fade-in.

However, with the window transistions enabled, everything in my window below the title bar does this "fly-in" when the window opens. I want to get rid of that, that's why I set `WindowTransitionsEnabled="False"` in the first place... Any help, please?

Best regards,
MisterNobody123

**Comment by timunie** [comment]
mhhh ok I'm out, sorry. 
I hope someone else can help you out. 

Happy coding
Tim

**Comment by MisterNobody123** [comment]
In the unlikely event of anybody having the same problem, here's a solution:

Set `GlowBrush="Transparent"` and add the following snippet to your `<MetroWindow>`:

```
<MetroControls:MetroWindow.Triggers>
    <EventTrigger RoutedEvent="Loaded">
        <BeginStoryboard>
            <Storyboard>
                <ColorAnimation
                    Storyboard.TargetProperty="GlowBrush.Color"
                    Duration="0:0:0.450" From="Transparent" To="Black"/>
            </Storyboard>
        </BeginStoryboard>
    </EventTrigger>
</MetroControls:MetroWindow.Triggers>
```

This will fade in the `<GlowBrush>` effect smoothly when the window is opening. You may want to play around with the `Duration` and/or add an `<EasingFunction>` to optimize the appearance.

Best regards,
MisterNobody123
