### ISSUE TITLE
GlowBrush shows on all desktops

### ISSUE THREAD

**Issue by Herohtar** [MahApps/MahApps.Metro#3642]
When using `GlowBrush` on a `MetroWindow`, the `GlowBrush` outline shows on all virtual desktops in Windows 10. If you're running from Visual Studio, the WPF inspection tools will show with it, though if you click on them, it will take you back to the desktop that actually contains the window.

**Steps to reproduce:**
1. Create a WPF project that uses `MetroWindow`
2. Set `GlowBrush` to any color
3. Press `Win+Tab` and switch to a different virtual desktop
4. See glow without window

**Expected behavior:**
No glow on desktops that don't have the window

**Environment:**
 - MahApps.Metro v2.0.0-alpha0490
 - Win10 1903
 - Visual Studio 2019 16.3.3
 - .NET Core 3.0

**Repo**
I'm experiencing the problem with [this repo](https://github.com/Herohtar/TemperatureMonitor), but I can try to put together a simple demo repo if you need me to.

**Comment by punker76** [comment]
@Herohtar I moved this to ControlzEx, because the Glow lives there https://github.com/ControlzEx/ControlzEx/issues/92
