### ISSUE TITLE
ComboBox popup bottom border almost disappeared

### ISSUE THREAD

**Issue by GreatFireWall** [MahApps/MahApps.Metro#3643]
**Describe the bug**
When the app window is **not** maximum, the `ComboBox` popup bottom border almost disappeared,
When the app window is maximum, it appeared.

**My Code**
```xaml
...
<controls:MetroHeader Padding="0 5" Header="xxx">
            <ComboBox MinWidth="400" 
                      HorizontalAlignment="Left" 
                      ItemsSource="{Binding XXXCollection}" />
</controls:MetroHeader>
...
```

**Screenshots**

*Not Maximum*
![image](https://user-images.githubusercontent.com/4510984/66569809-e8868180-eb9e-11e9-8ac8-f029e84da627.png)

*Maximum*
![image](https://user-images.githubusercontent.com/4510984/66569980-3dc29300-eb9f-11e9-857f-bb48919d6b52.png)

**Environment(please complete the following information):**
 - MahApps.Metro version [v1.6.5]
 - OS: [Win10 1809]
 - Visual Studio [2017 15.9.11]
 - .NET Framework [4.7.2]

**Comment by timunie** [comment]
Good morning @GreatFireWall ,

I tried to reproduce your issue with the lastest alpha version and it works for me. 
**Info:** v1.6.5 will not be updated anymore as far as I know. 

![ComboBox_BorderVisibility](https://user-images.githubusercontent.com/47110241/66893535-9a361000-efee-11e9-9b58-a27f8b045169.gif)
*Sample image made with prerelease*

Happy coding 
Tim

**Comment by GreatFireWall** [comment]
Hi @timunie , thanks your reply, do you know when will release 2.0 to NuGet ?

**Comment by timunie** [comment]
Hi @GreatFireWall . I don't know an exact due date. The current back lock is the documentation. 
You can test the prerelease if you want to. 
![image](https://user-images.githubusercontent.com/47110241/66906259-ad090e80-f007-11e9-8409-81593fc538d3.png)

Happy coding
Tim

**Comment by GreatFireWall** [comment]
There isn't any docs about breaking change.. I dare not try it out in my production environment.. 😢

**Comment by timunie** [comment]
@GreatFireWall Documentation is in work. I can understand that you don't want to try it in a production environment yet :+1: .
