### ISSUE TITLE
Hard to resize window

### ISSUE THREAD

**Issue by kalatchev** [MahApps/MahApps.Metro#3651]
**Hard to resize window**
MetroWindow has a very tiny area where mouse pointer turns to a resize style, especially if you try to resize both height and width (down right corner). Compare with standard Windows Notepad for example. 

This issue is present in all versions I've used.

**Comment by timunie** [comment]
Hi  @kalatchev ,

please try to add this Attribute to your `MetroWindow(s)`
```
ResizeMode="CanResizeWithGrip"
```
You will get a `Thumb` in the bottom right corner 

Happy coding
Tim

**Comment by punker76** [comment]
@kalatchev This behavior is by design. You can try to set the ResizeMode to CanResizeWithGrip as @timunie suggested or set the GlowBrush instead the BorderBrush.

**Comment by kalatchev** [comment]
I allways set **ResizeMode="CanResizeWithGrip"** and the issue still exists. **GlowBrush** mitigate the problem a lot, thanks @punker76 . However, I still think this is an issue. I spent some time to look carefully how it is implemented in Notepad, and here is the picture with my findings:

![image](https://user-images.githubusercontent.com/10154711/67013569-00f51f80-f0fc-11e9-8120-7733987716d3.png)

I have tested both on HD and UHD (4K, my primary display), no differences.

**Comment by timunie** [comment]
Hi @kalatchev ,
which version of MahApps do you use? I cannot reproduce your issue. Here is a gif of my mouse pointer.
![ResizeGrip](https://user-images.githubusercontent.com/47110241/67014728-99d46c80-f0f5-11e9-8ae0-2893082163ca.gif)

Happy coding
Tim

**Comment by kalatchev** [comment]
Thanks @timunie . It seems it works in your case. I use version **1.6.5.1** . And here are my results (taken on 4k UHD).:

![ma-m-resize](https://user-images.githubusercontent.com/10154711/67017303-3e5cab80-f102-11e9-90f1-258f0538098c.gif)

**Comment by timunie** [comment]
@kalatchev I used the lastest prerelease. So I think your issue will be solved with the next release v2.0.0. 
You can also try the prerelease but please be aware that there are some breaking changes. The documentation is in work, but needs still some time. 

Happy coding
Tim

**Comment by kalatchev** [comment]
Thank you @timunie , I appreciate your attention. I have a deadline for version release in the end of november, so I will stay for now at 1.6.5. I will migrate another module of our sysytem to MahApps, and there I will try 2.0. I will open a new issue if problem still occurs there. Once again - thanks!

**Comment by timunie** [comment]
You're welcome
