### ISSUE TITLE
Invalid window control icons.

### ISSUE THREAD

**Issue by HTD** [MahApps/MahApps.Metro#3655]
**Describe the bug**
Invalid shape of window controls. See screenshot.
Done on Windows 10, 4K resolution, scaling 150%.
Using latest version from GH.

**To Reproduce**
1. Set Windows desktop resolution to 3840x2160.
2. Set the scaling to 150%.
3. Run the MahApps.Metro.Demo.
4. Click the "Flyouts" link.

**Expected behavior**
The window controls in both displayed windows should look the same, like the controls marked green (OK) on the supplied screenshot.
The newly opened window looks differend, the controls are distorted and pixelated.

**Screenshots**
![image](https://user-images.githubusercontent.com/263558/67289133-653e2780-f4de-11e9-816f-0fd6a25217f5.png)

**Environment(please complete the following information):**
 - MahApps.Metro development version, but reproducible on most versions,
 - OS: Win10 1903
 - Visual Studio 2019 16.3.5
 - .NET Framework 4.8

**Comment by punker76** [comment]
@HTD this has now been fixed, and it will be released in the next version of MahApps.Metro v2.0
