### ISSUE TITLE
Clear Button in DatePicker

### ISSUE THREAD

**Issue by uday-teja** [MahApps/MahApps.Metro#3656]
Hi.. it will be nice to have a clear button in Date Picker. 

Some times we want to select the date and proceed 
Some time we don`t want to select the date and proceed.

We can edit the text when it is read only is set to false for the picker but it is not possible when read only is true in picker

**Comment by timunie** [comment]
@punker76 should I have a look if I can add `TextBoxHelper.ClearTextButton` to this Control? It seems to be missing in the template.

Happy coding
Tim

**Comment by uday-teja** [comment]
> @punker76 should I have a look if I can add `TextBoxHelper.ClearTextButton` to this Control? It seems to be missing in the template.
> 
> Happy coding
> Tim

Any Update ?

**Comment by timunie** [comment]
Good morning @uday-teja ,

please keep in mind that this project is a freetime project mainly driven by Jan. He spends a lot of time to make everything work for us, but unfortunatally there are more important issues right now. So if you need this feature urgent, I think you will have to override the `ControlTemplate` by yourself. Thanks to the available source this should be doable.

I hope for your understanding & happy coding
Tim
