### ISSUE TITLE
MahApps RangeSlider cannot change foregroundcolor

### ISSUE THREAD

**Issue by GeorgLink** [MahApps/MahApps.Metro#3658]
[Disclaimer, I'm posting this issue for my godfather who does not have a GitHub account.]

Describe the bug 

For the MahApps RangeSlider control the property foreground color cannot be set via XAML or code behind.

Using a style does not solve the problem either.

Environment(please complete the following information):

MahApps.Metro version v1.6.5
OS: Win10 
Visual Studio  2017 15.5.3
.NET Framework 4.6

A picture says more than 1000 words:

![image](https://user-images.githubusercontent.com/8862021/67501309-adc62400-f649-11e9-857e-b2959d0d2e99.png)

**Comment by timunie** [comment]
Hi @GeorgLink 

do you want to have something like this? 
![image](https://user-images.githubusercontent.com/47110241/67508872-251fa600-f692-11e9-8730-00b0ccf57341.png)

if yes, try this attachted property:

```
Controls:SliderHelper.TrackValueFillBrush="DeepPink"
Controls:SliderHelper.ThumbFillBrush="DeepPink"
```

Happy coding to you and your godfather
Tim

**Comment by GeorgLink** [comment]
Thanks @timunie, it looks interesting. I'll let you know once I hear whether it solves my godfather's issue 😉

**Comment by GeorgLink** [comment]
Thanks again @timunie. Your solution worked!
