### ISSUE TITLE
Question: how to use mahapps metro in net core and C#

### ISSUE THREAD

**Issue by Torchok19081986** [MahApps/MahApps.Metro#3659]
Hallo, i have few questions and hope someone can help me with. 
i startet my new project as wpf and net core app in c# and would like to add mahapps metro controls, icons etc. in my project. Which version of mahapps do i need to install ? Obviously 1.6.5 is not working. 
Is exists some manuals or guides how to use mahapps in net core app with wpf and C# ?  
Some limitations for use net core with mahapps like controls not available or something like that.
Many thanks for answer.

**Comment by timunie** [comment]
Hi @Torchok19081986 

yes, MahApps supports .Net-Core in the upcomming version 2.0.0. If you want to test this, you have to use the prereslease:
![image](https://user-images.githubusercontent.com/47110241/67550807-ac5b3100-f707-11e9-8b83-f30145f5589b.png)

happy coding
Tim

**Comment by punker76** [comment]
@Torchok19081986 You can use the latest NuGet package (pre-release) together with .Net Core 3. Keep in mind the alpha version has some breaking changes regarding to the brushes and styles (key namings). [Here](https://github.com/punker76/MahApps.Metro.netcoreapp30) is a simple sample which works together with .Net Core 3.
