### ISSUE TITLE
Animated Single Row Tab Control arrow icon is incorrect when setting flow direction right to left

### ISSUE THREAD

**Issue by VahidHajizadeh** [MahApps/MahApps.Metro#3660]
Hello, when I use Tab Control in a Right-to-left window, the arrow's icon keeps its direction like Left-to-right mode. It's should change. 

```xaml
<Grid>
    <Grid.Resources>
        <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.AnimatedSingleRowTabControl.xaml"/>
    </Grid.Resources>

    <TabControl mah:TabControlHelper.IsUnderlined="True"
                mah:TabControlHelper.Underlined="TabPanel"
                x:Name="MainTab"
                controlzex:KeyboardNavigationEx.AlwaysShowFocusVisual="True"
                Loaded="MainTab_Loaded">
        <mah:MetroTabItem Header="لیست دانش آموزان" CloseButtonEnabled="True"  CloseButtonMargin="10,15,10,0"/>
    </TabControl>
</Grid>
```

Screenshot:

![Untitled](https://user-images.githubusercontent.com/42106785/67561449-bb52db00-f729-11e9-8b7f-c8a6f5ffeedb.jpg)

How to solve this? Please Guide me.

**Comment by VahidHajizadeh** [comment]
when I changed flow diretction at runtime, problem solved temporarily

screenshots:
1:
![1](https://user-images.githubusercontent.com/42106785/67572834-e518fb80-f743-11e9-93c3-64dcad792ecc.jpg)

2:
![2](https://user-images.githubusercontent.com/42106785/67572865-f2ce8100-f743-11e9-8d27-e41f01d5fa92.jpg)

3:
![3](https://user-images.githubusercontent.com/42106785/67572909-07ab1480-f744-11e9-851a-50c6a7a7cd1d.jpg)

**Comment by punker76** [comment]
@VahidHajizadeh this has now been fixed, and it will be released in the next version of MahApps.Metro v2.0

**Comment by VahidHajizadeh** [comment]
thanks a lot for your fix and lovely mahapps
