### ISSUE TITLE
Can not enter negative number with negative exponent number with StringFormat set to "G" or "E"

### ISSUE THREAD

**Issue by kunjiangkun** [MahApps/MahApps.Metro#3662]
**Describe the bug**
When use Controls:DataGridNumericUpDownColumn, a negative number with negative exponent can not be entered in the field. The negative exponent is ignored. The binding data type is "double".

```xaml
<Controls:DataGridNumericUpDownColumn Header=" LSL " Binding="{Binding Path=LSL, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}" 
                                                          StringFormat="E" HideUpDownButtons="True" /
<Controls:DataGridNumericUpDownColumn Header=" USL "
                                                          Binding="{Binding Path=USL, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}" 
                                                          StringFormat="G" Interval="1" HideUpDownButtons="True"/>
```

**Comment by timunie** [comment]
Hi @kunjiangkun which version of MahApps do you use? 

Happy coding
Tim

**Comment by punker76** [comment]
@kunjiangkun I don't have a problem with v1.6.5 but I can reproduce this with latest source. Thx for reporting this.

![image](https://user-images.githubusercontent.com/658431/67635495-57b2e400-f8c8-11e9-9eef-e6c2c2f10537.png)

**Comment by punker76** [comment]
@kunjiangkun this has now been fixed, and it will be released in the next version of MahApps.Metro v2.0
