### ISSUE TITLE
add multiple tab on tab control and don't scroll

### ISSUE THREAD

**Issue by VahidHajizadeh** [MahApps/MahApps.Metro#3663]
when add multiple tabs in AnimatedSingleRowTabControl, tab list on the tab control don't scrolled to end and new tab stay in out of bound.
i want to scrolled when add new tab from viewmodel.

Is there a solution to this problem?

sorry for my bad english!

**Comment by punker76** [comment]
@VahidHajizadeh You need to get the ScrollViewer from the TabControl style in code behind. With this you can scroll after you added the Tabs.

```csharp
this.YourTabControl.FindChild<ScrollViewer>()?.ScrollToRightEnd();
```

**Comment by VahidHajizadeh** [comment]
Thank you @punker76 

In my project:
`this.MainTab.FindChild<ScrollViewer>("HeaderPanelScroll")?.ScrollToRightEnd();`
