### ISSUE TITLE
Datagrid TextColumn does not get styled

### ISSUE THREAD

**Issue by timunie** [MahApps/MahApps.Metro#3667]
**Describe the bug**
the `DataGridTextColumn` does not get stlyed in the editing mode.

**To Reproduce**
Have a look at the demo app
![image](https://user-images.githubusercontent.com/47110241/67874376-212dd100-fb35-11e9-9f4c-f4d95c748700.png)
![image](https://user-images.githubusercontent.com/47110241/67874407-2e4ac000-fb35-11e9-828c-621381d0cb4f.png)

**Expected behavior**
the `TexBox` and its `ContextMenu` should be styled according to the selected theme

**Screenshots**
see above

**Environment(please complete the following information):**
 - MahApps.Metro version latest alpha
 - OS: Windows 7
 - Visual Studio 2019
 - .NET Framework tested with different

Happy coding
Tim

**Comment by punker76** [comment]
@timunie This doesn't work in v1.6.5 either.
