### ISSUE TITLE
NumericUpDown must set minimum on value deleting

### ISSUE THREAD

**Issue by Pekshev** [MahApps/MahApps.Metro#3668]
**Describe the bug**
If the minimum value is set, then when deleting the contents (Delete or Backspace button), the minimum value must be set. Instead, a conversion error is displayed.
The problem is observed when using mvvm

**To Reproduce**
See demo-project

**Screenshots**
![image](https://user-images.githubusercontent.com/12638819/67974191-09347b00-fc23-11e9-8330-efa99d615ba9.png)

**Environment(please complete the following information):**
 - MahApps.Metro version - v1.6.5
 - OS: Win10
 - .NET Framework - 4.7

**Repo**
https://github.com/Pekshev/MahAppsTestNumericUpDown

**Comment by timunie** [comment]
Hi @Pekshev 
I tried the same in the past and I have to say that it was not good UI in my point of view. What you can do is to check for null in your VM and then return the default. 

Happy coding
Tim

**Comment by Pekshev** [comment]
Hi @timunie 
In my opinion, the logic should be in control. A compromise is to add a new Boolean property, for example **SetMinimumOnNull**
Well of course the developers decide )

**Comment by Pekshev** [comment]
@timunie, by the way, how can I check this in the property setter?
```
        private double _testValue;

        public double TestValue
        {
            get => _testValue;
            set
            {
                if (Equals(value, _testValue)) return;
                _testValue = value;
                OnPropertyChanged();
            }
        }
```

**Comment by timunie** [comment]
@Pekshev Maybe this helps you. If not I will have a deeper look when I find some time. 
 https://searchwindevelopment.techtarget.com/tip/Setting-defaults-for-null-values-in-data-sources-in-WPF

Happy coding 
Tim

**Comment by Pekshev** [comment]
@timunie OU! I know this, I just didn’t immediately realize that it is possible to bring the type to Nullable =))
However- I am still sure that all this logic should be inside the control, since the use of nullable in the VM introduces many unnecessary problems (at least a constant check for null in other methods of business logic)

**Comment by timunie** [comment]
What about a converter?

**Comment by Pekshev** [comment]
@timunie You can come up with a lot of options. I’m trying to say that all the options lead to a certain number of actions in the project. And there can be a lot of similar cases. But if all this logic goes into control and will be taken into account with just one property (as I wrote earlier), then it will be much more convenient for end users

**Comment by timunie** [comment]
Hi @Pekshev 
have a look at this: 
https://github.com/timunie/MahAppsTestNumericUpDown
I have two properties in the Model. One is the actual value which you can use for your business logic and one is a nullable value which does the magic. (see: https://en.wikipedia.org/wiki/Model–view–viewmodel ).
That way one can also set any defualt value or do some magic calculation on empty field  

As I am not a member of MahApps I cannot say if they want to implement a default value or not. Just taking the minimum may be a bad idea. Imagine you have a value from -5 to 5 and your default is 0. Setting -5 would be wrong in this case.

Happy coding
Tim

**Comment by punker76** [comment]
@Pekshev I'm with @timunie . I'm with Tim on this. It doesn't make the handling of the `Value` easier. Especially since it's already very complex.

**Comment by Gerardo-Sista** [comment]
Same problem here, very annoying to null check everywhere... 
I agree with @Pekshev: logic should be in control with a DefaultValueIfError property.
My (useless) opinion of course  🤣

**Comment by timunie** [comment]
Hi @Pekshev , @Gerardo-Sista 

I was thinking about this issue one more time and came up with an idea 💡 I had for the `ColorPicker`. The idea would be to add a new `DefaultValue`-Property which will be used if the result is `null`. That way we don't get a breaking change and your usecase should be coverd. 

You will have to opt this in either on every control or in your `Style`

Happy coding
Tim

**Comment by Gerardo-Sista** [comment]
> Hi @Pekshev , @Gerardo-Sista
> 
> I was thinking about this issue one more time and came up with an idea 💡 I had for the `ColorPicker`. The idea would be to add a new `DefaultValue`-Property which will be used if the result is `null`. That way we don't get a breaking change and your usecase should be coverd.
> 
> You will have to opt this in either on every control or in your `Style`
> 
> Happy coding
> Tim

It seems a very good idea. This way I can bind also my defined default value in ViewModel. Would be a great solution. 👍

**Comment by timunie** [comment]
Hi @Pekshev and @Gerardo-Sista 

I made a proposal here: #4090. I would be happy if you could test this in the demo with your use-case and give me a 👍 or 👎 it your use-case is covered with the given solution. 

Thank you and happy coding
Tim
