### ISSUE TITLE
Clear Button in ComboBox

### ISSUE THREAD

**Issue by kalatchev** [MahApps/MahApps.Metro#3669]
I have an issue with Clear button on ComboBox. My use case is form for searching with filters. Here is what I done:
``` XAML
...
xmlns:Controls="http://metro.mahapps.com/winfx/xaml/controls"
...

<ComboBox Grid.Column="1" x:Name="ComboBoxSchemas"
   DisplayMemberPath="Name" Margin="0,0,0,4" Height="{Binding  ActualHeight, ElementName=TextBoxPid}"
   ItemsSource="{Binding Filter.Schemas}"
   SelectedItem="{Binding Filter.Schema, Mode=TwoWay}" IsSynchronizedWithCurrentItem="False"
   Controls:TextBoxHelper.ClearTextButton="True"
   Controls:TextBoxHelper.ButtonCommand="{Binding ClearSchemaCmd}"
   Style="{StaticResource SwVirtualisedMetroComboBox}">
</ComboBox>
```
And then, in my ViewModel (I use [Prism llibrary](http://prismlibrary.github.io/docs/commanding.html)) I have:
``` VB.NET
Public Property ClearSchemaCmd As DelegateCommand(Of Object) = New DelegateCommand(Of Object)(AddressOf Me.ClearSchema)

Private Sub ClearSchema(obj As Object)
   Me.Filter.Schema = Me.Filter.Schemas.FirstOrDefault
End Sub
```
So far so good. **Command is executed as expected**. Essentially, command set selected item to a special value, in my case with meaning of "All items" (which is first item in bound collection). 

The problem is that **instead of having selected (special) desired item, ComboBox selection is cleared**. 
![ma-m-combo-clear](https://user-images.githubusercontent.com/10154711/67990575-faf45800-fc3e-11e9-9cdc-ea1e0d8f7283.gif)

I am pretty sure ViewModel raises `PropertyChanged`. It works when same code is executed in other command, which clears all filters, and mentioned above code `Me.Filter.Schema = Me.Filter.Schemas.FirstOrDefault` **sets desired item properly**. Here is an example:

![ma-m-combo-clear-2](https://user-images.githubusercontent.com/10154711/67999936-d44a1780-fc66-11e9-9a53-91f82101348a.gif)

Am I doing something wrong or it's by design? IMHO in case of attached command, clearing should be implemented in command, and button should just call tho command.

MahApps version I use: **1.6.5.1**.

Any ideas what to do?

**Comment by timunie** [comment]
Hi @kalatchev ,
I had a look in the samples and can confirm that you cannot override the command at the moment. Here is the `XAML` of the `SearchTextBox` - Example:

``` XAML
<TextBox Margin="{StaticResource ControlMargin}"
            Controls:TextBoxHelper.ButtonCommand="{Binding TextBoxButtonCmd, Mode=OneWay}"
            Controls:TextBoxHelper.ButtonContent="s"
            Controls:TextBoxHelper.Watermark="Custom icon style"
            Style="{DynamicResource MahApps.Styles.TextBox.Button}" />
```
There seems to be a speacial `TextBox-Style` with another `Button`. This `Button` seems to get the `Command`.

Happy coding
Tim
