### ISSUE TITLE
Range slider thumbs are gone in .NET core 3

### ISSUE THREAD

**Issue by Azengar** [MahApps/MahApps.Metro#3671]
**Bug description**
When using the RangeSlider in the alpha 2.0.0-alpha0531 and .NET core 3 with the metro theme (light or dark) the slider range can be moved correctly but the thumbs won't appear making it impossible to resize it.

**To Reproduce**
1. Create a .NET core 3 WPF application
2. Set the theme to light blue
3. Add a simple RangeSlider, such as:
```xaml
<Controls:RangeSlider Minimum="0" Maximum="100" LowerValue="10" 
    UpperValue="30" AutoToolTipPlacement="TopLeft" 
    AutoToolTipPrecision="2" MoveWholeRange="True" 
    IsSnapToTickEnabled="True" IsMoveToPointEnabled="True" 
    ExtendedMode="True" />
```
4. Thumbs at the left and right of the slider range do not appear

**Expected behavior**
Thumbs are supposed to appear on the left and right of the slider so that the range
can be resized.

**Screenshots**
![range-slider](https://user-images.githubusercontent.com/7602099/68087388-97904300-fe55-11e9-85b3-86b1a2183003.png)

**Environment**
 - MahApps.Metro version 2.0.0-alpha0531 
 - OS: Win10
 - Visual Studio 2019
 - .NET Core 3

**Comment by punker76** [comment]
@Azengar this has now been fixed, and it will be released in the next version of MahApps.Metro v2.0

**Comment by Azengar** [comment]
Thanks a lot for the quick reply and fix, you rock!

**Comment by lihongfang16** [comment]
Temporary solution
 <mah:RangeSlider >
                    <mah:RangeSlider.Resources>
                        <ResourceDictionary>
                            <system:Double x:Key="HorizontalThumbWidth">10</system:Double>
                            <system:Double x:Key="VerticalThumbHeight">10</system:Double>
                        </ResourceDictionary>
                    </mah:RangeSlider.Resources>
</mah:RangeSlider>
