### ISSUE TITLE
cannot locate resource themes/underline.xaml

### ISSUE THREAD

**Issue by victorklimkovich** [MahApps/MahApps.Metro#3676]
**Describe the bug**
When add controls in designer  has an exception
XamlParseException: Initialization of 'MahApps.Metro.Controls.NumericUpDown' threw an exception.
IOException: Cannot locate resource 'themes/underline.xaml'.

**Environment(please complete the following information):**
 - MahApps.Metro version e.g. v1.6.5

 - Visual Studio 2017 15.7.1
 - .NET Framework  4.6

**Comment by timunie** [comment]
Hi @victorklimkovich ,
does your App compile and start correctly? 

Happy coding
Tim

**Comment by punker76** [comment]
@victorklimkovich Have you integrated all the necessary resources? https://github.com/MahApps/MahApps.Metro/wiki/Quick-Start#add-the-resources-in-appxaml-v165-and-older

**Comment by victorklimkovich** [comment]
Yes it's works fine .. only XAML Designer was corrupted.
It's error appear when i change controls version from 1.2.4.0 net451 to 1.6.5.0 net46
in packages.config

**Comment by punker76** [comment]
@victorklimkovich Please try these steps

- make sure your VS is closed
- delete all bin and obj folders
- [Optional] locate the folder `C:\Users\<USER>\AppData\Local\Microsoft\VisualStudio\<VERSION>\Designer\ShadowCache` and delete all in there
- now open your solution and choose `Rebuild Solution`

Hope that helps!

**Comment by punker76** [comment]
@victorklimkovich Any news on this?
