### ISSUE TITLE
PowerShell script crashes on ShowModalInputExternal

### ISSUE THREAD

**Issue by amazingalyx** [MahApps/MahApps.Metro#3684]
**Describe the bug**
When running ShowModalInputExternal, or any type of MahApps external modal, from a button click the PowerShell process will crash. I know an earlier alpha from ~October 28 the external modal worked, but the OK and Cancel buttons were missing their styles.

(This works perfectly on 1.6.5, though.)

**To Reproduce**
1. Download the repo. linked below.
2. Right-click "Run Me.ps1", click "Run with PowerShell"
3. Click the "Open external input modal" button in the window.
4. PowerShell will crash along with the window...

**Expected behavior**
The dialog should be appearing above the main window.

**Environment**
 - MahApps.Metro version 2.0.0
 - Windows 10 (1903)
 - PowerShell 5 (5.1.18362.145)
 - Visual Studio 2019 (16.3.8)
 - .NET Core 3

**Repo**
https://github.com/slashpowered/PS-MahApps

**Comment by AKruimink** [comment]
Might this one have something related to #3500 ?
