### ISSUE TITLE
Colors not changing dinamically for some properties

### ISSUE THREAD

**Issue by Gerardo-Sista** [MahApps/MahApps.Metro#3686]
Hello everyone,
**THE PROBLEM**: 
using  ````ThemeManager.ChangeAppStyle(Application.Current, ThemeManager.GetAccent(MyStringColor), ThemeManager.GetAppTheme(MyStringTheme));````   the color for some properties of TextBox and MetroHeader doesn't change properly. 

I have this style defined in App.XAML:
````
<Style TargetType="{x:Type TextBox}" BasedOn="{StaticResource MetroTextBox}">
  <Setter Property="FontSize" Value="20" />
  <Setter Property="Foreground">
   <Setter.Value>
    <SolidColorBrush Color="{DynamicResource  AccentBaseColor}" />
    </Setter.Value>
     </Setter>

   <Setter Property="BorderBrush">
   <Setter.Value>
   <SolidColorBrush Color="{DynamicResource  AccentBaseColor}"  />
   </Setter.Value>
    </Setter>

// and, for  MetroHeader
    <Style TargetType="{x:Type mah:MetroHeader}">
     <Setter Property="Foreground" Value="{DynamicResource AccentBaseColor}" />
    </Style>
````
I first run ````ThemeManager.ChangeAppStyle(...)```` in App.xaml OnStartup()
![image](https://user-images.githubusercontent.com/34858800/68622992-b3d65480-04d3-11ea-9018-503c75e7877a.png)

then, when I change color clicking on the button 

![image](https://user-images.githubusercontent.com/34858800/68623410-bdac8780-04d4-11ea-9238-f3ac84f6b6eb.png)

Is it an issue or am I doing something wrong?
Thank you for assitance.

**Comment by timunie** [comment]
Hello @Gerardo-Sista 

please try:
```xaml
<Setter Property="BorderBrush" Value="{DynamicResource  AccentColorBrush}" />
```

For the other `Properties the same

Happy coding
Tim`

**Comment by Gerardo-Sista** [comment]
Hello, 
I already tried your code (for borders) that but gives always an error:
**System.Windows.Markup.XamlParseException: ''#FF119EDA' is an invalid value for property 'BorderBrush'.**

I solved for MetroHeader with this code (if someone has same requirements):
````
 <Style TargetType="{x:Type mah:MetroHeader}">
                <Setter Property="Foreground">
                    <Setter.Value>
                        <SolidColorBrush Color="{DynamicResource AccentBaseColor}" />
                    </Setter.Value>
                </Setter>
            </Style>
````
**but for textbox borders no solution works**. Please help

**Comment by punker76** [comment]
@Gerardo-Sista You need to use the v1.6.5 brushes like `AccentBaseColorBrush`

```
<Application.Resources>
    <ResourceDictionary>
        <ResourceDictionary.MergedDictionaries>
            <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
            <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
            <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Colors.xaml" />
            <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/Blue.xaml" />
            <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/BaseLight.xaml" />
        </ResourceDictionary.MergedDictionaries>

        <Style TargetType="{x:Type TextBox}" BasedOn="{StaticResource MetroTextBox}">
            <Setter Property="FontSize" Value="20" />
            <Setter Property="Foreground" Value="{DynamicResource AccentBaseColorBrush}" />
            <Setter Property="BorderBrush" Value="{DynamicResource AccentBaseColorBrush}" />
        </Style>

        <Style TargetType="{x:Type mah:MetroHeader}">
            <Setter Property="Foreground" Value="{DynamicResource AccentBaseColorBrush}" />
        </Style>
    </ResourceDictionary>
</Application.Resources>
```

![2019-11-12_14h45_58](https://user-images.githubusercontent.com/658431/68676890-479f3380-055b-11ea-831b-e70c99f829d1.png)

![2019-11-12_14h46_07](https://user-images.githubusercontent.com/658431/68676901-4b32ba80-055b-11ea-87d3-624925475c64.png)

**Comment by Gerardo-Sista** [comment]
Done! Now it works perfectly @punker76 
Thank to everyone for the quick support  and help. :)
