### ISSUE TITLE
How to set MetroHeader's  Header font, fontfamily, fontsize etc?

### ISSUE THREAD

**Issue by Gerardo-Sista** [MahApps/MahApps.Metro#3693]
Hello,
how can I set MetroHeader's Header  font, fontfamily, fontsize etc?
Can someone show me a style to achieve this?

````   <!--METROHEADER STYLE-->
            <Style TargetType="{x:Type mah:MetroHeader}" >
             
                     //What is the correct code here to style header's font stuff?             
                
            </Style>
````
Thank you

**Comment by Gerardo-Sista** [comment]
I think I solved with this:
````
     <!--METROHEADER STYLE-->
            <Style TargetType="{x:Type mah:MetroHeader}" >
                <Setter Property="Foreground" Value="{DynamicResource AccentBaseColorBrush}" />
                <Setter Property="HeaderTemplate">
                    <Setter.Value>
                        <DataTemplate>
                            <TextBlock FontSize="36" FontStyle="Italic"  Text="{Binding}"/>
                        </DataTemplate>
                    </Setter.Value>
                </Setter>
            </Style>
````
Is it the correct way?

Thank you

**Comment by timunie** [comment]
Hi @Gerardo-Sista ,
I think there are always more than one way to get the expected result. So if it works for you, I think there is nothing wrong with your solution. Another way would be to set the Header Property with any visual you like (TextBlock,  Image, 
... ). 

Happy coding 
Tim

**Comment by Gerardo-Sista** [comment]
Thank you very much.

**Comment by punker76** [comment]
@Gerardo-Sista In upcoming v2.0 you can also use these attached properties

```
HeaderedControlHelper.HeaderForeground
HeaderedControlHelper.HeaderBackground
ControlsHelper.HeaderFontFamily
ControlsHelper.HeaderFontSize
ControlsHelper.HeaderFontStretch
ControlsHelper.HeaderFontWeight
ControlsHelper.HeaderMargin
```

**Comment by timunie** [comment]
> @Gerardo-Sista In upcoming v2.0 you can also use these attached properties
> 
> ```
> HeaderedControlHelper.HeaderForeground
> HeaderedControlHelper.HeaderBackground
> ControlsHelper.HeaderFontFamily
> ControlsHelper.HeaderFontSize
> ControlsHelper.HeaderFontStretch
> ControlsHelper.HeaderFontWeight
> ControlsHelper.HeaderMargin
> ```

Hi @punker76 ,
One thought on your replay. Shouldn't we move ghese properties all to `HeaderedControlHelper`?

Happy coding 
Tim

**Comment by Gerardo-Sista** [comment]
Hello @punker76 , I agree with @timunie
All the attached properties should be under `HeaderedControlHelper`
for clarity and easiness of use.

Thann you :)
