### ISSUE TITLE
DateTimePicker binding error

### ISSUE THREAD

**Issue by Coke21** [MahApps/MahApps.Metro#3694]
Hi, I'm using MahApps.Metro 1.6.5, NET Framework 4.8, Windows 10 and Visual Studio 2019, whenever I debug my program, I'm getting:
```
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.DatePicker', AncestorLevel='1''. BindingExpression:Path=(0); DataItem=null; target element is 'DatePickerTextBox' (Name='PART_TextBox'); target property is 'Name' (type 'String')

System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.DatePicker', AncestorLevel='1''. BindingExpression:Path=(0); DataItem=null; target element is 'DatePickerTextBox' (Name='PART_TextBox'); target property is 'LabeledBy' (type 'UIElement')

System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.DatePicker', AncestorLevel='1''. BindingExpression:Path=(0); DataItem=null; target element is 'DatePickerTextBox' (Name='PART_TextBox'); target property is 'HelpText' (type 'String')
```
This is how my XAML looks like:
```
      xmlns:sys="clr-namespace:System;assembly=mscorlib"
      xmlns:Controls="clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro"

      <Controls:DateTimePicker x:Name="DateTimePicker" Width="170" SelectedDate="{x:Static sys:DateTime.Now}" DisplayDateEnd="{x:Static sys:DateTime.Now}" HorizontalContentAlignment="Center"/>
```
I tried to just create a new DateTimePicker like this:
                   ` <Controls:DateTimePicker/>`
But still the same above error. Not sure what I'm doing wrong. I believe everything is working even with the above binding eror.

Edit: Also I tried to use DateTimePicker in another program that uses the same environment as above and I'm still getting the same above binding error.

**Comment by punker76** [comment]
@Coke21 I can’t reproduce this, so have you maybe a sample?

**Comment by Coke21** [comment]
@punker76 https://github.com/Coke21/MahApps.Metro-Sample I didn't upload the bin folder, hopefully you can get the same error as I do.
When I debug it I get the same error:
```
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.DatePicker', AncestorLevel='1''. BindingExpression:Path=(0); DataItem=null; target element is 'DatePickerTextBox' (Name='PART_TextBox'); target property is 'Name' (type 'String')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.DatePicker', AncestorLevel='1''. BindingExpression:Path=(0); DataItem=null; target element is 'DatePickerTextBox' (Name='PART_TextBox'); target property is 'LabeledBy' (type 'UIElement')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.DatePicker', AncestorLevel='1''. BindingExpression:Path=(0); DataItem=null; target element is 'DatePickerTextBox' (Name='PART_TextBox'); target property is 'HelpText' (type 'String')
```

**Comment by punker76** [comment]
@Coke21 Thank you for the sample. It seems like this is related to the .Net 4.8 target framework, because I got the same errors if I use the `DatePickerTextBox` without MahApps. This `DatePickerTextBox` is used inside the `DateTimePicker`, but I can not say why these errors happens. Maybe you can raise an issue at the team on Microsoft feedback system.

**Comment by Licantrop0** [comment]
@punker76 I'm actually reproing the bug with the 2.0.0 alpha0660 and .NET Core 3.1
If I switch back to the original datepicker, I don't see the error.

**Comment by punker76** [comment]
@Coke21 @Licantrop0 The BindingExpression error has now been fixed, and it will be released in the next version of MahApps.Metro
