### ISSUE TITLE
How to get supported colors and themes and change theme at runtime in version 2.0 ?

### ISSUE THREAD

**Issue by Gerardo-Sista** [MahApps/MahApps.Metro#3698]
Hello,
this is not a bug but is a very common task, I searched everywhere but didn't find a working example to make run this in **Mahapps v2:**

**SCENARIO:**
 When user selects a color or a theme from UI, App or current window/page/usercontrol must change theme gracefully.

**REQUESTS**
**1.** What's **the code** to get supported accent themes from resources (list to bind in a combobox)?
**2.** What's **the code** to get supported themes from resources (list to bind in a combobox)?
**3.** What's **the code** to switch Theme to entire App or current window in v2? 

Thank you in advance for help!

**Comment by AKruimink** [comment]
1.  `ThemeManager.Themes` could give you a list of available themes, [Sample](https://github.com/MahApps/MahApps.Metro/blob/develop/src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindowViewModel.cs#L73)

2. `ThemeManager.ColorSchemes`  could give you a list of available accents. [Sample](https://github.com/MahApps/MahApps.Metro/blob/develop/src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindowViewModel.cs#L68)

3.  You can use T`hemeManager.ChangeThemeBaseColor`, or `ThemeManager.ChangeThemeColorScheme` to change the theme and accent respectivly.

Both take an instance of the applicatie or window of which you want to change any of the 2. [Sample ](https://github.com/MahApps/MahApps.Metro/blob/develop/src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindowViewModel.cs#L43) and [Sample2](https://github.com/MahApps/MahApps.Metro/blob/develop/src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindowViewModel.cs#L51)

**Comment by Gerardo-Sista** [comment]
@AKruimink 
I love straight to the point answers! 
I test immediately.
Thank you very much :)

**Comment by AKruimink** [comment]
@Gerardo-Sista  If this issue has been resolved, feel free to close the issue 👍

**Comment by Gerardo-Sista** [comment]
@AKruimink 
I'm very sorry, I usually always close.
This time I forgot. Thank you for notice me :)
