### ISSUE TITLE
Error: Could not find an installer for the 'dotnet' scheme.

### ISSUE THREAD

**Issue by LItterBoy-GB** [MahApps/MahApps.Metro#3702]
**Describe the bug**
I want build a project, but I got an error of "Error: Could not find an installer for the 'dotnet' scheme.". 

**To Reproduce**
cd Metro-develop
./build.ps1

**Expected behavior**
build success

**Screenshots**
![image](https://user-images.githubusercontent.com/28385638/69784360-8cc89400-11f0-11ea-94cc-9d1365eaa45b.png)

**Environment(please complete the following information):**
 - MahApps.Metro version v1.6.4
 - OS: Win10 1803
 - Visual Studio 2015
 - .NET Framework 4.8

**Comment by punker76** [comment]
@LItterBoy-GB this has now been fixed, and it will be released in the next version of MahApps.Metro v2.0
