### ISSUE TITLE
Cannot build 1.6.5

### ISSUE THREAD

**Issue by corradolab** [MahApps/MahApps.Metro#3705]
Just downloaded 1.6.5 sources (MahApps.Metro-1.6.5)

Trying to build Mahapps.Metro with Visual Studio 16.3.10 I get thousands errors about missing references.
I added references to the following assemblies:
- PresentationCore
- PresentationFramework
- System.Xaml
- WindowsBase

Now there are 163 errors left related to:
- 'InputDialog' missing 'InitializeComponent'. 
- 'InputDialog' does not contains 'PART_TextBox', 'PART_NegativeButton', etc.
Similar errors also in LoginDialog.cs, MessageDialog.cs, ProgressDialog.cs, GlowWindow.xaml.cs, MetroNavigationWindow.xaml.cs

2.0 Alpha (MahApps.Metro-develop) builds correctly out of the box.

Am I missing something?

Thank you!

**Comment by punker76** [comment]
@corradolab Please look on #3588. I created a special branch to make this possible https://github.com/MahApps/MahApps.Metro/issues/3588#issuecomment-531137061

**Comment by oghenez** [comment]
@corradolab did you find a solution to load MahApps v1.6.5? what did you do?
