### ISSUE TITLE
Nuget Package Update

### ISSUE THREAD

**Issue by hassaanmasood** [MahApps/MahApps.Metro#3707]
Hi, Can someone please update the Nuget package for MahApps with all the changes made for .net core and with the updated third parties dependencies.

**Comment by punker76** [comment]
@hassaanmasood The latest stable alpha is already available on [NuGet](https://www.nuget.org/packages/MahApps.Metro/2.0.0-alpha0605). If you want the latest CI NuGet package then put [this feed](https://ci.appveyor.com/nuget/mahapps.metro) in your NuGet list.

**Comment by hassaanmasood** [comment]
The problem is that nuget package has dependency on ControlzEx version < 4.0. But I want to use another nuget package which has requirement for ControlzEx version > 4.0. This is why I am requesting to update the dependencies version.

**Comment by timunie** [comment]
@hassaanmasood ,
just install the prerelease of MahApps. But please keep in mind that there are many breaking changes, especially for the `ResourceKeys`.
![image](https://user-images.githubusercontent.com/47110241/69945686-65bcdb80-14ea-11ea-9997-79c965fe1d6f.png)

Happy coding
Tim
