### ISSUE TITLE
DataContext is not passed to UIElement in CustomDialog.DialogTop

### ISSUE THREAD

**Issue by seba30** [MahApps/MahApps.Metro#3708]
Hello,

I've started a new project with .NET Core, MahApps 2.0.0-alpha0605 and observed an ugly behavior.

If I'm using a CustomDialog and override the DialogTop property, then the DataContext of the View is not passed to the Content element (here a Button), but the ContentPresenter around the Button has the DataContext set to my ViewModel.

![image](https://user-images.githubusercontent.com/48946764/70035734-bf3d0d00-15b3-11ea-89a2-857a52372101.png)

But the UIElement in the CustomDialog's content gets the DataContext.

![image](https://user-images.githubusercontent.com/48946764/70035777-d1b74680-15b3-11ea-915e-d3ecb42958f9.png)

---

Compared to MahApps 1.6.5 the behavior has changed.

![image](https://user-images.githubusercontent.com/48946764/70035823-e8f63400-15b3-11ea-9ad0-ae3b40c0bf74.png)

Any ideas? Thank you!

**Comment by punker76** [comment]
@seba30 I think I know what's wrong. I'll try to fix it later.

**Comment by punker76** [comment]
@seba30 this has now been fixed, and it will be released in the next version of MahApps.Metro v2.0

**Comment by seba30** [comment]
I'll give it a try. Thank you for your fast support!
