### ISSUE TITLE
TabControl & HeaderFontSize

### ISSUE THREAD

**Issue by esso23** [MahApps/MahApps.Metro#3711]
Hello,

Not sure if this should be bug report or feature request because I can't find how exactly the 2.0.0 branch works (like if the features will be the same as in 1.6.5).

**Describe the bug**
Controls:ControlsHelper.HeaderFontSize is no longer present in alpha version for TabControl.
I'm using this solution:
https://stackoverflow.com/a/31841229/1906905
Worked fine on .NET Framework 4.6.1 with MahApps.Metro 1.6.5.

**To Reproduce**
Use this code:

```cs
<TabControl>
            <TabControl.Resources>
                <Style TargetType="{x:Type TabItem}" BasedOn="{StaticResource {x:Type TabItem}}">
                    <Setter Property="Controls:ControlsHelper.HeaderFontSize" Value="14" />
                </Style>
            </TabControl.Resources>
</TabControl>
```

**Environment:**
 - MahApps.Metro version v2.0.0-alpha0660
 - OS: Win 10 Pro 1809 (OS Build 17763.864)
 - Visual Studio 2019 16.4
 - .NET Core 3.1

I ported an entire project to MahApps.Metro and this is the only thing that's not compatible.

**Comment by timunie** [comment]
Hi @esso23 ,

there are a few breaking changes in the prerelease. It is now 
`Controls:HeaderedControlHelper.HeaderFontSize`
There are now also some more `Properties` to control the `Header`.
@punker76 is updating the documentation 📝 

Happy coding
Tim

**Comment by esso23** [comment]
Great! Thanks for the info.
