### ISSUE TITLE
Element Overlapping With Window TitleBar Unclickable In TitleBar Area

### ISSUE THREAD

**Issue by NimbusHex** [MahApps/MahApps.Metro#3713]
I'm using MetroWindow in a project (2.0.0-alpha0660).  I have a control overlapping the TitleBar, a button.  The button used to be fine in this area, but it seems with an update the part of the button overlapping the TitleBar part can no longer be clicked.

![thumbnail_image001](https://user-images.githubusercontent.com/7635180/70866354-995e2380-1f36-11ea-8a1e-d0f79e7089aa.png)

I have the control overlapping the TitleBar with a negative margin that puts it in that area.  Is there possibly a better way to accomplish this?

**Comment by punker76** [comment]
@NimbusHex this has now been fixed, and it will be released in the next version of MahApps.Metro v2.0
