### ISSUE TITLE
Header Text with underscore not working

### ISSUE THREAD

**Issue by thomas-karl** [MahApps/MahApps.Metro#3715]
**Describe the bug**
If you bind the GroupBox header to a text property in your view model like that:
`<GroupBox Header="{Binding HeaderText}" />`
and your property HeaderText is a string with Content "Header_Text", the text is not displayed as expected.

**Expected behavior**
I would expect the header text to display "Header_Text", while it displays "HeaderText". 

Reason for this seems to be the ContentPresenter.RecognizesAccessKey Property, which is set to true by default for the GroupBox's HeaderContent via ContentControlEx.

Is this by design and if so, should it be configurable?

As a workaround I put a TextBlock in Header like this:
```
<GroupBox>
    <GroupBox.Header>
        <TextBlock Text="{Binding HeaderText}" />
    </GroupBox.Header>
</GroupBox>
```

**Environment**
 - MahApps.Metro version 1.6.5
 - OS: Win10 1903
 - Visual Studio 2017 15.9.17
 - .NET Framework 4.6.1

Many thanks in advance!

**Comment by punker76** [comment]
@thomas-karl You can change this default behavior (from WPF) with the new attached property `ControlsHelper.RecognizesAccessKey`.

**Comment by thomas-karl** [comment]
Thank you very much! 👍
