### ISSUE TITLE
Missing System.Management

### ISSUE THREAD

**Issue by JorundMartinsen** [MahApps/MahApps.Metro#3719]
**Describe the bug**
When using Metrowindow in a dotnet core 3.1 wpf project, I get an IO exception: 

System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Management, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.'

**To Reproduce**
1. Create a new WPF .net core 3.1 project
2. Install MahApps
3. Change MainWindow to a MetroWindow.
4. Run project

**Expected behavior**
Normal execution

**Environment(please complete the following information):**
 - MahApps.Metro version v1.6.5
 - OS: Win10 1903
 - Visual Studio 2019 16.4.1
 - .NET Framework Core 3.1

** Additionally ***
ControlzEx has removed the dependency in v4.0.0.

**Comment by punker76** [comment]
@JorundMartinsen v1.6.5 does not support .NET Core 3.0 or 3.1. If you need this then use the latest alpha version (but keep in mind, there are a lot of breaking changes inside).
