### ISSUE TITLE
Change color of dialog fade out

### ISSUE THREAD

**Issue by Symbai** [MahApps/MahApps.Metro#3721]
How do I change the color of the overlay outside the dialog but inside the application window? Using dark theme this getting a white fade out color which I would like to change to a gray color.

**Comment by punker76** [comment]
@Symbai You can change this with this property on MetroWindow

https://github.com/MahApps/MahApps.Metro/blob/cb9264828def32d2c55ec32dc0426c8a72aa793d/src/MahApps.Metro/Controls/MetroWindow.cs#L722-L729
