### ISSUE TITLE
[Bug] RangeSlider is incorrectly drawn when the maximum value is a high number

### ISSUE THREAD

**Issue by Symbai** [MahApps/MahApps.Metro#3722]
**Describe the bug**
RangeSlider is incorrectly drawn when the maximum value is a high number. In the example below the second slider should start where the first slider ends.

**To Reproduce**
See repo

**Screenshots**
![image](https://user-images.githubusercontent.com/14368203/71643875-13bcd080-2cb7-11ea-9362-19037e321531.png)

**Environment(please complete the following information):**
 - MahApps.Metro version 2.0.0-alpha0660
 - OS:  Win10
 - Visual Studio 2019
 - .NET Core 3.1

**Repo**
```
<StackPanel>
    <mah:RangeSlider
        Width="200"
        Height="20"
        AutoToolTipPlacement="TopLeft"
        LowerValue="190"
        Maximum="400000"
        UpperValue="300" />
        <mah:RangeSlider
        Width="200"
        Height="20"
        AutoToolTipPlacement="TopLeft"
        LowerValue="300"
        Maximum="400000"
        UpperValue="350" />
    </StackPanel>
```

**Comment by timunie** [comment]
Hi @Symbai and a happy new year.

The `RangeSlider` has a `MinRangeWidth`-Property. This changes how the `Slider` is drawn. You can set this to even to `0` if you want to.
![image](https://user-images.githubusercontent.com/47110241/71685493-c2850d80-2d98-11ea-8c3b-e703d89b78ae.png)

If I got you wrong please let me know. 

Happy coding
Tim
