### ISSUE TITLE
Individual row styling in datagrid

### ISSUE THREAD

**Issue by KKauK** [MahApps/MahApps.Metro#3726]
Hello,

I'm trying to do some individual row styling in my datagrid using a datatrigger (see attached screenshots). As soon as I use the MahApps datagrid styling the datatrigger won't work any more.

Please find attached a small test application (Just correct the MahApps reference). You can reproduce the behavior by uncommenting the following line in App.xaml:

ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml"

 - MahApps.Metro version: current development path (2.0)
 - OS: [e.g. Win10 1909
 - Visual Studio [e.g. 2019 16.4.3]
 - .NET Framework [e.g. 4.7.2]

![Screenshot not using Mahapps](https://user-images.githubusercontent.com/7251838/72518605-04608a00-3856-11ea-8838-d459e6091500.jpg)
![Screenshot using Mahapps](https://user-images.githubusercontent.com/7251838/72518617-075b7a80-3856-11ea-9336-da9e4a518d07.jpg)
[WpfApp1.zip](https://github.com/MahApps/MahApps.Metro/files/4070770/WpfApp1.zip)

**Comment by KKauK** [comment]
Uncomment:

**Comment by KKauK** [comment]
ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml"

**Comment by timunie** [comment]
Hi @KKauK ,
it runs for me if I change `ItemContainerStyle` to `RowStyle`. Can you try if this solves your issue?
![image](https://user-images.githubusercontent.com/47110241/72523854-f8c69080-3860-11ea-9410-3e112fdc3ba3.png)

Just out of interest: Why do you want to make this? Is it for grouping the items? 

Happy coding 
Tim

**Comment by KKauK** [comment]
Hi @Tim,

I simply missed that line! (sorry about). It fixes the issue!

The demand comes from our engineers, They have one data record in the dataset that has the same values for all properties and they don't want to adjust all of them. I'm personally not very lucky of that solution but as long as I can't offer a better way...

Thankx for the quick response and all the work you are doing!
