### ISSUE TITLE
Maximizing MetroWindow doesn't work with AllowsTransparency="True"

### ISSUE THREAD

**Issue by skel35** [MahApps/MahApps.Metro#3728]
**Describe the bug**
When `MetroWindow` has `AllowsTransparency="True"` then maximizing it via click on Maximize button, double-click on titlebar, or context menu Maximize click doesn't work.

**To Reproduce**
1. Create `MetroWindow` with `AllowsTransparency="True"`
2. Try to maximize the window

**Expected behavior**
The window is properly maximized.

**Screenshots**
https://i.imgur.com/wPIaKrA.png
This is how the window looks after an attempt to maximize (window content is in top left corner, but it doesn't respond to anything except dragging by the titlebar to remove maximization).

**Environment(please complete the following information):**
 - MahApps.Metro version v1.6.5, v2.0.0-alpha0660
 - OS: Win10 1909
 - .NET Framework 4.6.1, .NET Core 3.0

**Repo**

I've created the repo to follow the guidelines https://github.com/skel35/MetroWindowMaximizeBugRepro,
but the repro is very simple:
```
<mah:MetroWindow x:Class="NetCoreRepro.MainWindow"
                 xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                 xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                 xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
                 xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
                 xmlns:mah="http://metro.mahapps.com/winfx/xaml/controls"
                 mc:Ignorable="d"
                 Title="MainWindow" Height="350" Width="525"
                 AllowsTransparency="True"
                 Background="White">
    <Grid />
</mah:MetroWindow>
```

**Additional context**

Maximizing works properly if I drag the titlebar to the top edge of the screen. 

I'd appreciate if you can recommend any workaround to this issue.

**Comment by timunie** [comment]
Hi @skel35 
please try to implement this: https://github.com/MahApps/MahApps.Metro/wiki/Quick-Start and tell us, if the problem still exists then

Happy coding
Tim

**Comment by skel35** [comment]
Hi @timunie !
Yes, the problem still exists after adding the resource dictionaries. Screenshot https://i.imgur.com/JZAC2VY.png

**Comment by punker76** [comment]
@skel35 `AllowsTransparency="True"` is not allowed for MahApps, because of issues and performance probolems in WPF.

**Comment by skel35** [comment]
@punker76 OK, thanks for the quick answer. Sad to hear this as it seems to work for me fine except for the Maximize issue, and even then it's possible to get it maximized by snapping to the edge of the screen.

**Comment by punker76** [comment]
@skel35 If you don't need transparency window then you don't need to set `AllowsTransparency="True"`.

**Comment by skel35** [comment]
@punker76 In my case I wanted to achieve the transparency effects for the window itself. Without those, if transparency is disabled everything works as expected.

Anyway, thanks for the great work on this framework.

**Comment by mxsoftware** [comment]
Goodmorning everyone,
first of all, congratulations for the enormous work that you are carrying out.

Also I had problems with "AllowsTransparency", I solved, surely in a non elegant and completed way, with the following code:

public class BaseWindow : MahApps.Metro.Controls.MetroWindow

...

#region " private vars "
        private static bool _ManageWpfAllowsTrasparencyBug = true;

        private bool _FirstEnteredOnActivated;
        private object _OldDataContext;

        private bool _DisableStoreWindowCoordinates;
        private double? _Top;
        private double? _Left;
        private double? _Height;
        private double? _Width;
        private WindowState _PreviousWindowState;
#endregion

...

#region " constructors "
        public MxBaseWindow()
        {
            if (_ManageWpfAllowsTrasparencyBug)
            {
                _PreviousWindowState = this.WindowState;

                this.SizeChanged += BaseWindow_SizeChanged;
                this.StateChanged += BaseWindow_StateChanged;
            }
        }
#endregion

#region " methods "
        private void BaseWindow_SizeChanged(object sender, SizeChangedEventArgs e)
        {
            if (!_DisableStoreWindowCoordinates)
            {
                _Top = Top;
                _Left = Left;
                _Height = Height;
                _Width = Width;
            }
        }

        private void BaseWindow_StateChanged(object sender, EventArgs e)
        {
            if ((this.WindowState == WindowState.Maximized) && (_PreviousWindowState == WindowState.Maximized))
            {
                if (_Top.HasValue)
                {
                    _DisableStoreWindowCoordinates = true;

                    _PreviousWindowState = WindowState.Normal;

                    this.StateChanged -= MxBaseWindow_StateChanged;
                    this.WindowState = WindowState.Normal;
                    this.StateChanged += MxBaseWindow_StateChanged;

                    this.Top = this._Top.Value;
                    this.Left = this._Left.Value;
                    this.Height = this._Height.Value;
                    this.Width = this._Width.Value;

                    _DisableStoreWindowCoordinates = false;
                }
            }
            else if ((this.WindowState == WindowState.Maximized) && (_PreviousWindowState != WindowState.Maximized))
            {
                _DisableStoreWindowCoordinates = true;

                _PreviousWindowState = this.WindowState;

                this.StateChanged -= MxBaseWindow_StateChanged;
                this.WindowState = WindowState.Normal;
                this.StateChanged += MxBaseWindow_StateChanged;

                this.Top = 0;
                this.Left = 0;
                this.Width = SystemParameters.WorkArea.Width;
                this.Height = SystemParameters.WorkArea.Height;

                _DisableStoreWindowCoordinates = false;
            }
            else
            {
                _PreviousWindowState = this.WindowState;
            }
        }
#endregion

**Comment by NimbusHex** [comment]
Just curious, isn't the true problem with AllowsTransparency the infamous WPF airspace issue?  I guess if you're not using WindowsFormHost it may not matter, but in my experience enabling it just causes unpredictability in the app in general.

**Comment by mxsoftware** [comment]
If the question is addressed to me, I don't use WindowsFormHost.
I don't like mixing different technologies.
The project from which I extracted the code is native WPF with MahApps.Metro 1.6.5.
I have not found any stability problems, but as already highlighted I have no experience with the WindowsFormHost control.
