### ISSUE TITLE
Support .NET Framework 4.0

### ISSUE THREAD

**Issue by e-karaulov** [MahApps/MahApps.Metro#3730]
**Is your feature request related to a problem? Please describe.**
I can't download MahApps.Metro for .NET Framework 4.0 (latest with WinXP support)
**Describe the solution you'd like**

**Additional context**

**Closed Issues**

**Comment by batzen** [comment]
Which version of MahApps.Metro are you trying to use? Newer versions, like the current alpha of version 2.0, don't support.net 4.0 anymore.

**Comment by gitjsdr26** [comment]
Dear @batzen ,
I've the same concern which is to make working an application on Windows XP with .Net Framework 4.0.
Which version shall I use to compile it to target .Net Framework 4.0 (or 4.1) ?

Thank you very much
Best Regards

**Comment by batzen** [comment]
I strongly advise against developing applications for Windows XP as it's out of support from Microsoft for a long time now. The same applies to .NET 4.1.
The last version of MahApps.Metro supporting .NET 4.0 is 1.6.5 as far as i remember.

**Comment by timunie** [comment]
Hi @e-karaulov and @gitjsdr26 ,

I am with @batzen that you should not run XP anymore, especially when your PC is connected to the internet. But I also know that some companies still run a few PCs with Win XP, e.g. when a machine control runs only on Win XP. 

There is a brunch available that supports .Net 4.0 and should be compile able: https://github.com/MahApps/MahApps.Metro/tree/master-net40 

Happy coding,
Tim

**Comment by punker76** [comment]
@e-karaulov @gitjsdr26 MahApps v2.0 will do not support .Net 4.0 and XP anymore (see #3041). If you still need it then use v1.6.5.

**Comment by gitjsdr26** [comment]
Some of our customers are still using Windows XP in local network mode.
Thank you anyway, I'll try v1.6.5 and will keep you informed.
Best Regards.

**Comment by e-karaulov** [comment]
@punker76 i tried use it for wrote client for one game. Old game, and many players using WinXP. Thanks for answer, i just remove METRO and use own styles for controls. 
Very hard to add .NET Framework 4.0 support?

**Comment by timunie** [comment]
Hi @e-karaulov ,
this is a free time project and we do not have the time to support XP anymore and even can't test it. But feel free to fork MahApps.Metro and implement support for .Net4.0

Happy coding and thanks for understanding,
Tim

**Comment by e-karaulov** [comment]
@timunie , what problems cause .NET Framework 4.0 support?

**Comment by batzen** [comment]
It consumes time and requires to keep machines with Windows XP around for testing.

**Comment by punker76** [comment]
@e-karaulov 

> @timunie , what problems cause .NET Framework 4.0 support?

There is no support or any updates from Microsoft!

**Comment by e-karaulov** [comment]
@punker76 this is problem ?

**Comment by batzen** [comment]
@e-karaulov Yes it is a problem. As we already said it consumes time, our time. And it's not supported by the vendor.

**Comment by punker76** [comment]
@e-karaulov As I said above,  If you still need to run with .Net 4 then use v1.6.5.
