### ISSUE TITLE
Is there any easy way to make SplitButton use MetroFlatButton style?

### ISSUE THREAD

**Issue by GreatFireWall** [MahApps/MahApps.Metro#3731]
MahApps.Metro: v1.6.5

**Comment by timunie** [comment]
Hi @GreatFireWall ,
unfortunatally not. But you can overide the `Style` to your needs. Here is the link to the source: 
https://github.com/MahApps/MahApps.Metro/blob/master/src/MahApps.Metro/Themes/SplitButton.xaml

Happy coding,
Tim

**Comment by GreatFireWall** [comment]
Ok, thanks.
