### ISSUE TITLE
Metro Progress Bar's UpdateLayout method (inside ActualSize) cannot access the UI thread if the UI thread is busy(??)

### ISSUE THREAD

**Issue by PeterHidvegiPrezi** [MahApps/MahApps.Metro#3732]
**Describe the bug**
Metro Progress Bar's UpdateLayout method (inside ActualSize) cannot access the requirement resource (UI thread?) if It was allocated for another process. (For example during Caliburn micro's ShowDialog.)
UpdateLayout will wait until the Dialog window is returned with result.

[Gitter](https://github.com/MahApps/MahApps.Metro/blob/develop/src/MahApps.Metro/Controls/MetroProgressBar.cs)

**Expected behavior**
UpdateLayout method of ActualSize function should not wait another UI process.

**Comment by punker76** [comment]
@PeterHidvegiPrezi Thx for reporting this issue. I'm not a good Caliburn micro user, so it would be nice if you can create a simple tiny app with this scenario. Also, please post the MahApps version which you use. Thx 🙏

**Comment by punker76** [comment]
@PeterHidvegiPrezi Any chance to create a simple Caliburn micro ShowDiaolg sample?
