### ISSUE TITLE
Error adding 'MahApps.Metro.dll' into WPF Toolbox (VS2019)

### ISSUE THREAD

**Issue by Unknown6656** [MahApps/MahApps.Metro#3734]
**Bug description**
I'm trying to import the MahApps.Metro control collection into the WPF designer toolbox in VS2019, however I get the following error messages:

> `"[...]/ControlzEx.dll" targets a platform whose toolbox items cannot be enumerated dynamically.`
> `"[...]/MahApps.Metro.dll" targets a platform whose toolbox items cannot be enumerated dynamically.`

**To Reproduce**
1. Go to the WPF designer toolbox
2. Left-Click > "Choose Items ..."
3. Click "Browse ..."
4. Select `ControlzEx.dll` and `MahApps.Metro.dll` referenced by the application.

**Screenshots**
![image](https://user-images.githubusercontent.com/8807985/73868001-fea00800-4847-11ea-936a-835aefc93f4d.png)

**Environment:**
 - MahApps.Metro `2.0.0-alpha0660`
 - Win10 Professional x64 18363
 - Visual Studio Community 2019 16.5.0 Preview 2.0
 - .NET Core 3.1.200-preview-014883

**Comment by Unknown6656** [comment]
I found a _temporary_ workaround:
1) Create a second project in the solution. This project must target the .NET Framework instead of .NET Core
2) Reference `MahApps.Metro` via Nuget
3) Compile
4) Copy the `.dll`s into an other directory
5) Drag them into the WPF toolbox
6) Delete the second project.

At least, I can now drag-&-drop the controls into the designer. However, the designer does not render them correctly.

**Comment by batzen** [comment]
If the designer has issues with components or does not render them correctly, but everything works fine at runtime it's almost always the designers fault.
You should report such issues to Microsoft as there is nothing we can do to fix this on our side.

**Comment by Unknown6656** [comment]
> You should report such issues to Microsoft as there is nothing we can do to fix this on our side.

Ok. That, I can understand. And I should mention, that it is the preview-version of VS2019, so I guess that bugs are kinda to be expected.

However, do you maybe know the origin of the original error message?

**Comment by batzen** [comment]
I don't think it's because you are using a preview. The designer is kinda buggy ever since.

The original error occurs because visual studio is using the "full" .net framework and so does the designer. Loading a .net core dll is not supported by the .net runtime.
As far as i know the designer does not fully support .net core yet.

**Comment by Unknown6656** [comment]
Oh okay :/
Thank you for your insight and response!

**Comment by punker76** [comment]
@Unknown6656 Can I close this issue? Or have you still some questions about this? Thx.

**Comment by Unknown6656** [comment]
Oh yeah you're right. I forgot to close this issue. Thanks for all the feedback!

**Comment by Luk164** [comment]
@Unknown6656 Sorry to bother you but did you manage to find a solution for this? Or do we still have to use the workaround?

**Comment by Unknown6656** [comment]
@Luk164 I still had to use the workaround to this date.
To be honest, I mainly design the MahApps-based windows purely using XAML (without really using the window designer).

**Comment by Luk164** [comment]
@Unknown6656 Yeah I am not very good at front-end stuff so designer is a huge help to me. Though if I ever want to use Xamarin I will have to learn to work without it eventually.
