### ISSUE TITLE
MahApps.Metro apps blurry when used as RemoteApp

### ISSUE THREAD

**Issue by darxis** [MahApps/MahApps.Metro#3737]
I am using a WPF app with MahApps.Metro as a RemoteApp. When it is launched as a RemoteApp, the entire window is a little blurry. I am reproducing this bug using the MapApps Demo.

I am using a 4k monitor with 150% scaling. When I set 100% scaling, the window is not blurry at all, the bug occurs only on scalings higher than 100%.

Please see the images below:
This one is clean, not using RemoteApp
<img width="675" alt="no_remoteapp_clean" src="https://user-images.githubusercontent.com/10614436/74386631-bf008f80-4df6-11ea-8a10-c1971ea5a3e7.png">

This one uses RemoteApp and is blurry
<img width="675" alt="remoteapp_blurry" src="https://user-images.githubusercontent.com/10614436/74386636-c1fb8000-4df6-11ea-81e4-93d397801dce.png">

I am using other RemoteApp apps and they don't have this problem so I guess the problem should be in the code rather than the RDP/Windows configuration.

PS: If I launch the app in a standard Remote Desktop session the bug doesn't occur, the app not blurry.

**Comment by punker76** [comment]
@darxis Which .Net Framework target did you try? It could be that .Net 4.6 handles the DPI better than .Net 4.5.

**Comment by darxis** [comment]
Hi @punker76, thanks for your response!

In the .csproj file I have `<TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>` and the host server is running .NET Framework .NET Framework 4.8.

The client is running Windows 10 fully updated, and the host server Windows Server 2012 R2.

I wonder if the problem is that Windows 8.1 does not handle DPI scaling as good as Windows 10 as there were improvements, and the host Windows Server 2012 R2 could also have this problem as Windows 8.1. I won't upgrade to Windows Server 2016 right now but I will probably install a VM with Windows Server 2016 and check if this problem occurs.

**Comment by darxis** [comment]
Well, I have installed a test Windows Server 2016 virtual machine with RemoteApp deployed and the app is not blurry anymore, so I guess that since Windows 10 and WS 2016 they enhanced DPI scaling so that my WPF apps in RemoteApp are not blurry. I guess that the Per-Monitor V2 DPI awareness mode introduced in Win10 fixed this.

https://docs.microsoft.com/en-us/windows/win32/hidpi/high-dpi-desktop-application-development-on-windows

**Comment by darxis** [comment]
For people having this problem, I have just upgraded Windows Server 2012 R2 to Windows Server 2019 and it fixed this issue.
