### ISSUE TITLE
Win10's checkbox style height/width is overriden

### ISSUE THREAD

**Issue by DoubleOhmSeven** [MahApps/MahApps.Metro#3744]
**Describe the bug**
The Win10 checkbox style seems to have a minimum width of ~120 and height of ~30. No matter what is specified for Width/MaxWidth/Height/MaxHeight on it, this is ignored.

**To Reproduce**
Add a checkbox and use the Win10 style. Easy to see if a background color is used for the checkbox.

**Expected behavior**
This style should inherit the sizes from template.

**Environment(please complete the following information):**
 - MahApps.Metro version https://github.com/MahApps/MahApps.Metro/commit/bf0f75e4a3668de8f817b34a6ce0e8a06e1318db
 - OS: Win10 1909
 - Visual Studio 2019
 - .NET Framework 4.8

**Comment by punker76** [comment]
@DoubleOhmSeven Yes, that's correct, the Win10 style has a minimum width of 120 pixel and height of 32 pixel. 

> This style should inherit the sizes from template.

I don't understand why it should inherit from template?

**Comment by DoubleOhmSeven** [comment]
I meant as TemplateBinding. The normal style doesn't force 120px on you either and now you cannot just use the checkbox anymore (without any content in it) as it will always make a big gap between the checkbox and content.

**Comment by punker76** [comment]
@DoubleOhmSeven Then simply reset these settings. MinHeight=“0” and MinWidth=“0” should do that for you.

**Comment by punker76** [comment]
@DoubleOhmSeven The values for MinHeight and MinWidth are coming from the original Win10 UWP style. So I will leave these values. If you want to change this then you can change it on CheckBox itself or create a global inherited style with changed values for these properties.
