### ISSUE TITLE
Add CheckGlyphSize attached property for Win10 checkbox style

### ISSUE THREAD

**Issue by DoubleOhmSeven** [MahApps/MahApps.Metro#3745]
**Is your feature request related to a problem? Please describe.**
Yes, you can change the CheckSize with CheckBoxHelper, but not the FontSize of the CheckGlyph. Now you need to override the CheckGlyphCheckedTemplate and CheckGlyphIndeterminateTemplate. 

**Describe the solution you'd like**
Add another attached property to control the check glyph size.

**Comment by punker76** [comment]
@DoubleOhmSeven Sorry, but I will not add such a attached property. Yes, the CheckSize attached property was a helper to change this size easily on the 2 styles. But the FontSize is only be used at the Win10 style. I think it's easy enough to create a global custom style with bigger CheckSize and different CheckGlyphCheckedTemplate and CheckGlyphIndeterminateTemplate.
