### ISSUE TITLE
DateTimePicker changes date to 1/1/0001 when selecting time first

### ISSUE THREAD

**Issue by didster** [MahApps/MahApps.Metro#3746]
Firstly great work!

Using DateTimePicker in 2.0.0-alpha0660

Selecting a time from the dropdown before selecting the date changes the date to 01/01/0001.

DateTimePicker is bound to a nullable date time.  Same occurs when DateTimePicker is not bound to anything at all actually.

It works fine in 1.6.5 where selecting the time first still results in the textbox saying "select a date"

I must target .net core, so sadly can't use 1.6.5

Here is an example of both

[Doesnt work using 2.0.0 alpha](https://github.com/didster/DateTimePickerDoesntWork)
[Works using 1.6.5](https://github.com/didster/DateTimePickerWorks)

**Comment by didster** [comment]
Unsure if this is related but also when ever I use DateTimePicker in alpha, I get these three binding errors:

`System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.DatePicker', AncestorLevel='1''. BindingExpression:Path=(0); DataItem=null; target element is 'DatePickerTextBox' (Name='PART_TextBox'); target property is 'Name' (type 'String')`

`System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.DatePicker', AncestorLevel='1''. BindingExpression:Path=(0); DataItem=null; target element is 'DatePickerTextBox' (Name='PART_TextBox'); target property is 'LabeledBy' (type 'UIElement')`

`System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.DatePicker', AncestorLevel='1''. BindingExpression:Path=(0); DataItem=null; target element is 'DatePickerTextBox' (Name='PART_TextBox'); target property is 'HelpText' (type 'String')`

**Comment by punker76** [comment]
@didster Are you targeting .Net Framework 4.8? If yes, then it's a problem there.

**Comment by didster** [comment]
@punker76 No, I'm targeting .NET Core 3.1.  I have also tried Core 3.0, same result.  The non-alpha project using 1.6.5 targets Framework 4.7.2 and works fine.  I have not tried 4.8.

I have also just tried using Framework 4.7.2 and the alpha version just out of interest.  No binding errors shown, but the original reported problem of the date showing 1/1/0001 when you change the time is still exhibited so I guess they are not related anyway.

**Comment by didster** [comment]
A further point for this is I hadn't noticed is that it does the same in reverse when you select the date first - the time time resets to 00:00.

**Comment by dj060004** [comment]
+1 for this fix as the control is pretty much unusable currently.  Is their an ETA?  Many thanks.

**Comment by punker76** [comment]
> Unsure if this is related but also when ever I use DateTimePicker in alpha, I get these three binding errors:
> 
> `System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.DatePicker', AncestorLevel='1''. BindingExpression:Path=(0); DataItem=null; target element is 'DatePickerTextBox' (Name='PART_TextBox'); target property is 'Name' (type 'String')`
> 
> `System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.DatePicker', AncestorLevel='1''. BindingExpression:Path=(0); DataItem=null; target element is 'DatePickerTextBox' (Name='PART_TextBox'); target property is 'LabeledBy' (type 'UIElement')`
> 
> `System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.DatePicker', AncestorLevel='1''. BindingExpression:Path=(0); DataItem=null; target element is 'DatePickerTextBox' (Name='PART_TextBox'); target property is 'HelpText' (type 'String')`

@didster This seems a bug in WPF together with .Net Core. I creates a simple WPF .Net Core 3.1. app and added a DatePicker and got these messages too. I tried then to prevent this by adding switches to the app.config

```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <runtime>
    <!-- AppContextSwitchOverrides value attribute is in the form of 'key1=true|false;key2=true|false  -->
    <AppContextSwitchOverrides value="Switch.UseLegacyAccessibilityFeatures.3=true" />
  </runtime>
</configuration>
```

But this doesn't work.

**Comment by dj060004** [comment]
@punker76 Yes indeed I came to the same conclusion.  Doesn't seem to impact actual use so I've just filtered them from my output log ;-).  The main thing for me is the fix for the actual issue raised and many thanks @timunie for the PR :-)

**Comment by punker76** [comment]
@didster The BindingExpression error has now been fixed, and it will be released in the next version of MahApps.Metro
