### ISSUE TITLE
https://mahapps.com/ is dead.

### ISSUE THREAD

**Issue by EPurpl3** [MahApps/MahApps.Metro#3748]
Hello, i have another type of bug. The website https://mahapps.com/ with the documentation is dead, i cant access it. I get the error (in Chrome) "mahapps.com’s server IP address could not be found.". Unfortunate https://web.archive.org/ doesnt have saved the pages that i need.

 I have managed to implement in my project MahApps window but the controls do not work and i can not access the main website to be able to solve this problem.

Any idea about how to access the website or why the modern controls do not work out of the box in?

Thank you.

**Comment by punker76** [comment]
@EPurpl3 I don't know what's wrong with your Chrome or network, but the site is online...

**Chrome

![2020-02-19_09h49_44](https://user-images.githubusercontent.com/658431/74817474-3ce3ff80-52fd-11ea-9f9f-e363dbb63d46.png)

**Firefox

![2020-02-19_09h48_43](https://user-images.githubusercontent.com/658431/74817482-3f465980-52fd-11ea-8042-dfbad264b494.png)

**Comment by EPurpl3** [comment]
Well, is the only website that doesnt work on my network. I will talk to the administrator to see what's going on. I have checked from my phone and indeed, is working :o. Sorry for this, my bad.

Great app, by the way, very useful, if i manage to make it work. Thank you.
