### ISSUE TITLE
TimePicker: Is there a way to show/select only minute and seconds?

### ISSUE THREAD

**Issue by gigios** [MahApps/MahApps.Metro#3750]
I'm using MahApps.Metro 1.6.5 on my project and I need to allow the user to select a time to set for a countdown.
For this reason I want to use the TimePicker but I'm not able to 'hide' the hour and the AM/PM info.

Is there any way to use the TimePicker control to select a only minutes and seconds without rewrite the control?

**Comment by timunie** [comment]
Hi @gigios,
I think the `TimePicker` is intended to select the time part of a `DateTime`. See also this issue for a feature request about `TimeSpan`-Picker: https://github.com/MahApps/MahApps.Metro/issues/3718

I think for now you will need to create a new `Control`.

Happy coding
Tim

**Comment by gigios** [comment]
Hi @timunie,
Thanks for the answer.

Regards
Luigi
