### ISSUE TITLE
DataGrid - Theme based alternate background colour

### ISSUE THREAD

**Issue by mpogra** [MahApps/MahApps.Metro#3752]
Hello Team,

First of all, thanks for this awesome UI toolkit and it's working very well so far. We just started using it and it's going very well. Thanks again!!

We are integrating Datagrid in our app and finding it difficult (or maybe with our little knowledge) to set Theme based row background color. We have light and dark theme support in the app and our Datagrid uses custom alternate background colors. Initially, the app was just in the light mode so it was defined at grid level styles and was working very well but now we have added dark mode support and alternate colors are not working very well. I tried to override the colors using the below technique but it didn't work very well (in App.xml file, it though for light theme)- 

```xaml
<ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Themes/Light.Blue.xaml">

    <Style TargetType="DataGridRow" BasedOn="{StaticResource MahApps.Styles.DataGridRow}">
        <Style.Triggers>
            <Trigger Property="ItemsControl.AlternationIndex" Value="0">
                <Setter Property="Background" Value="#fff" />
            </Trigger>
            <Trigger Property="ItemsControl.AlternationIndex" Value="1">
                <Setter Property="Background" Value="#330A7AFF" />
            </Trigger>
        </Style.Triggers>
    </Style>

</ResourceDictionary>
```

I am sure there must be an easy solution for this but I am not able to figure it out yet. Please advise.

Also If I include Dark.Blue theme in App.xml becomes the base style for the app whereas I need light theme to be the base theme for the app. 

Thanks.

**Comment by timunie** [comment]
Hi @mpogra ,
Please ask questions like this on gitter first because I think it is not a bug. 
Join the chat: https://gitter.im/MahApps/MahApps.Metro 

Thank you for understanding
Tim

**Comment by mpogra** [comment]
Thanks, Looks like I missed that point. Asking there.

**Comment by mpogra** [comment]
Thanks for quick help by @timunie , Was able to change color of rows using DynanicResources. 

In details, I have defined below SolidColorBrushes into the App.xaml - 

 <SolidColorBrush x:Key="DataGrid.EvenRow.Background" Color="#FFF"/>
 <SolidColorBrush x:Key="DataGrid.OddRow.Background" Color="#330A7AFF"/>

Applied them to Grid style like below (using DynamicResources) - 

`<Trigger Property="ItemsControl.AlternationIndex" Value="0">
                        <Setter Property="Background" Value="{DynamicResource DataGrid.EvenRow.Background}" />
                    </Trigger>
                    <Trigger Property="ItemsControl.AlternationIndex" Value="1">
                        <Setter Property="Background" Value="{DynamicResource DataGrid.OddRow.Background}" />
                    </Trigger>`

Then changing these when the user is changing Theme at run like below - 
` Application.Current.Resources["DataGrid.EvenRow.Background"] = new SolidColorBrush(Color.FromArgb(255, 255, 255, 255));
                Application.Current.Resources["DataGrid.OddRow.Background"] = new SolidColorBrush(Color.FromArgb(255, 115, 194, 251));
            `
Hope it will help someone.
