### ISSUE TITLE
Remove old ToggleSwitch and replace with UWP like ToggleSwitch

### ISSUE THREAD

**Issue by punker76** [MahApps/MahApps.Metro#3753]
Remove old ToggleSwitch and ToggleSwitchButton class and create UWP like ToggleSwitch.

- Simplify ToggleSwitch (remove the old one incl. the ToggleSwitchButton)
- Use some additional properties from the old one
- No indeterminate state (use IsOn/IsChecked property with bool instead bool?)
Why?
  + https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/toggles
  + https://www.nngroup.com/articles/toggle-switch-guidelines/

![image](https://user-images.githubusercontent.com/658431/75387024-f84efa00-58e2-11ea-9962-44697cb91af8.png)

Closes #3276 
Closes #3527 
Closes #3690 
Closes #2762

**Comment by timunie** [comment]
Hi @punker76 ,
is it possible to implement an indeterminate state to this control, so we can bind to `bool?`. see https://github.com/MahApps/MahApps.Metro/pull/3527 

Thank you and happy coding,
Tim

**Comment by punker76** [comment]
@timunie No, I will not implement this here for this ToggleSwitch. IMO a ToggleSwitch should not have this behavior. If you need this, then this is the wrong control for this.

- https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/toggles
- https://www.nngroup.com/articles/toggle-switch-guidelines/

**Comment by timunie** [comment]
Hi Jan,
thank you for the feedback. I get your point, but in my special use case I have to let the user do a choice. So I will maybe stick with a custom control which does what I need, or switch to another control if I find one.
