### ISSUE TITLE
Hamburgermenu Styles not included with MahApps?

### ISSUE THREAD

**Issue by Swiftpaws** [MahApps/MahApps.Metro#3758]
Are the "Creators Style" and "Ripple Effect" styles not included as styles in the Mahapps.Metro package ?

I feel like they could be included as optional styles - ready to use of of the box.

**Comment by punker76** [comment]
@Swiftpaws "Creators Style" maybe, "Ripple Style" not, because it depends on MDIX library.

**Comment by punker76** [comment]
@Swiftpaws I added the Creators Update styles to the themes

- MahApps.Styles.ListBoxItem.HamburgerMenuItem.CreatorsUpdate
- MahApps.Styles.HamburgerMenu.CreatorsUpdate
