### ISSUE TITLE
Visual studio desginer stop show metro ui in desginer 

### ISSUE THREAD

**Issue by Zeleksonob** [MahApps/MahApps.Metro#3759]
Start simple application of metro ui , after some time in development i'm losing the design ui to this one. and from here I can't develop any UI.

what I'm doing wrong ? or this a known issue?

screenshot: 

![1fPsVaQ - Imgur](https://user-images.githubusercontent.com/658431/76565067-194e4800-64aa-11ea-9bf5-78fb6867dea0.png)

here my code : 

```xaml
<Controls:MetroWindow x:Class="AnnotationManagerWPF.MainWindow"                     
                      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                       xmlns:iconPacks="http://metro.mahapps.com/winfx/xaml/iconpacks"
                      xmlns:local ="clr-namespace:AnnotationManagerWPF"
                      xmlns:Customers ="clr-namespace:AnnotationManagerWPF.ActiveAnnotations"
                      xmlns:AnnoationRe="clr-namespace:AnnotationManagerWPF.AnnotationRequests"
                      xmlns:Controls="clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro"
                      Title="MainWindow"
                      Height="830"
                      Width="1200">
    <Controls:MetroWindow.Resources>
        
    </Controls:MetroWindow.Resources>
    <Controls:MetroWindow.DataContext>
        <local:MainWindowModel/>
    </Controls:MetroWindow.DataContext>
    <!-- your content -->
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="100"></RowDefinition>
            <RowDefinition ></RowDefinition>
        </Grid.RowDefinitions>
        <Canvas Height="100" Background="Silver" Margin="0,0,0,0">
            <Controls:Tile
                Command="{Binding SwitchToRequest}"
            Title="Annotaion Requests"
            Count="         10"
             Margin="0" Width="144" Height="62" Canvas.Left="622" Canvas.Top="20"
            />
            <Controls:Tile Name="TasksTag" Width="130" Height="60" Title="Tasks" Count="        10" Margin="0"  Canvas.Left="784" Canvas.Top="22"/>
            <Controls:Tile   Command="{Binding SwitchToActive}" Name="activeProfileTag" Width="148" Height="60" Title="Active Profile Annotations"   Count="            10" Margin="0" Canvas.Top="20" Canvas.Left="450"/>
        </Canvas>
        <ContentControl Grid.Row="1" Content="{Binding CurrentViewModel}"></ContentControl>
        <!--<VIControls:ProfileAnnotationControl x:Name="alexControl" Grid.Row="1" />-->
    </Grid>
</Controls:MetroWindow>
```

**Comment by batzen** [comment]
Designer issues should be reported to Microsoft as there is nothing we can do to fix this on our side.

**Comment by punker76** [comment]
@Zeleksonob Make sure that you have added all necessary MahApps resources at App.xaml. What you are missing exactly?

**Comment by Zeleksonob** [comment]
@punker76 

I'm missing buttons,Tile , properties like text, count, image, and background color.

, maybe I'll do missing a resource, could you look at the images below, please?

App.xaml

[Imgur](https://i.imgur.com/e8HbBYJ.png)

this is what my designer looks like : 

[Imgur](https://i.imgur.com/knYezvA.png)

This is my UserContorl reference :
[Imgur](https://i.imgur.com/zInxFgf.png)

**Comment by Zeleksonob** [comment]
@punker76  any suggestions?

**Comment by timunie** [comment]
Hi @Zeleksonob ,

make sure the project is build correctly and that custom controls are activated in the designer. 
![image](https://user-images.githubusercontent.com/47110241/76700421-926eba80-66b7-11ea-89f6-1c5390782a61.png)

Even then like @batzen already said the designer for WPF is buggy, but we cannot solve it. I personally write my UI completly in XAML

Happy coding
Tim
