### ISSUE TITLE
An error occurred while finding the resource dictionary

### ISSUE THREAD

**Issue by LFMV** [MahApps/MahApps.Metro#3760]
Problem : 

I can't find the library "Themes", what do I do solve this error.

Help

Error Code: \
Line >>>> "MahApps.Metro;component/Styles/Themes/Light.Orange.xaml"

Complete code:
```xaml
<Application x:Class="SampleBurguer.App"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mah="http://metro.mahapps.com/winfx/xaml/controls"
             xmlns:local="clr-namespace:SampleBurguer"
             StartupUri="MainWindow.xaml">
    <Application.Resources>

        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />                
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Themes/Light.Orange.xaml" />
            </ResourceDictionary.MergedDictionaries>
            <Style TargetType="{x:Type mah:WindowButtonCommands}" BasedOn="{StaticResource MahApps.Styles.WindowButtonCommands.Win10}" />
        </ResourceDictionary>

    </Application.Resources>
</Application>
```

**Comment by punker76** [comment]
@LFMV Which MahApps version are you use?

**Comment by LFMV** [comment]
I have tried from 1.6.0 to 1.6.5 but doesn't work.
Any Suggestion?

**Comment by timunie** [comment]
Hi @LFMV ,
we have a breaking change here. The code you have is just for the upcoming v2.0.0 available. If you need v1.6.5 try this: https://github.com/MahApps/MahApps.Metro/wiki/Quick-Start#add-the-resources-in-appxaml-v165-and-older 

Happy coding 
Tim

**Comment by LFMV** [comment]
Tnk timunie:

if you have already tried it and if the problem works it is presented the following "Exception: Cannot find resource named 'MahApps.Styles.WindowButtonCommands.Win10'. Resource names are case sensitive."

**Comment by timunie** [comment]
If you need this styles then you need to use the alpha version of MahApps. Because this is also a breaking change. 

You can try the Alpha Version like this: 
![image](https://user-images.githubusercontent.com/47110241/76654527-6cd49a80-656b-11ea-9a60-a3af2bd77655.png)

**Comment by timunie** [comment]
If you have more questions you can also use gitter: https://gitter.im/MahApps/MahApps.Metro

**Comment by LFMV** [comment]
Thank so much,
I´m getting to know this environment  reviewing everything in detail with practices.

I already joined the group

Regards

**Comment by timunie** [comment]
Hi @LFMV 
If your issue is solved please remember to close this issue. 

Thank you and happy coding, 
Tim
