### ISSUE TITLE
Interesting bug that should totally be a feature

### ISSUE THREAD

**Issue by ShadCanard** [MahApps/MahApps.Metro#3762]
**Describe the bug**
First, little bit of context is needed.
I'm trying to do a SBB in C# using MahApps as a GUI and CEFSharp as a browser. The goal is to make an immersive as possible browser to allow people to run a webapp as an actual app (Same as Ice for example in Linux). I was playing around with Fullscreen events from CEFSharp and trying to set the window Fullscreen. But when the site is minimized, the whole Title bar is gone transparent (except the min, max and close buttons).

**To Reproduce**
In my project, launch SBBWindow with URL.
Comment (opaque title bar) or uncomment (transparent title bar) SetImmersiveScreen on the SBBWindow(string url) constructor.

SetImmersiveScreen Method is just that :

`        private void SetImmersiveScreen()`
`        {`
`            UseNoneWindowStyle = true;`
`            UseNoneWindowStyle = false;`
`        }`

**Expected behavior**
I was first expecting the Title Bar to be fully visible. but now, I'm expecting it to have this behavior of transparent title bar when I want. :-)

**Screenshots**
With code applied : https://i.imgur.com/5z7vbuZ.png
With code non applied : https://i.imgur.com/UQ0nyjK.png
(The URL is just an embedded Youtube video)
Edit:  Tested this on other media platform that allows "full-frame" video and the bug is reproduced as well.

**Environment(please complete the following information):**
 - MahApps.Metro version v2.0.0-alpha0748
 - ControlzEx v4.2.2
 - Microsoft.Xaml.Behaviors.Wpf v1.1.19
 - CefSharp.Wpf 79.1.360
 - cef.redist.x64 v79.1.36
 - cef.redist.x86 v79.1.36
 - CefSharp.Common v79.1.360

 - OS: Win10
 - Visual Studio 2019 16.4.2
 - .NET Framework 4.8

**Source Code**
[https://github.com/shadcanard/shadsbb](https://github.com/shadcanard/shadsbb)

**Comment by punker76** [comment]
@ShadCanard You can also use these properties to show/hide titlebar and buttons

```
internal void SetImmersiveScreen()
{
    ShowTitleBar = false;
    ShowMinButton = false;
    ShowMaxRestoreButton = false;
    ShowCloseButton = false;
}
```

But keep in mind that you lost drag move for the window itself.

![image](https://user-images.githubusercontent.com/658431/77308508-57920580-6cfb-11ea-91b9-9995f9c04a06.png)
