### ISSUE TITLE
Can SplitView have a GridSplitter or similar so that user can resize the left and right parts?

### ISSUE THREAD

**Issue by kernel-coder** [MahApps/MahApps.Metro#3763]
**Is your feature request related to a problem? Please describe.**
I need a SplitView to have a GridSplitter like control in it so that user can resize the left and right panel.

**Comment by timunie** [comment]
Hi @kernel-coder ,

it is currently not build in, but I think you can create a `Style` on your own with a new `ControlTemplate`, which implements this. 

here is the original one: https://github.com/MahApps/MahApps.Metro/blob/develop/src/MahApps.Metro/Themes/SplitView.xaml

You can keep this ticket on, and maybe we add this feature later (v2.0.0 has priority at the moment)

Happy coding,
Tim
