### ISSUE TITLE
The Loaded&Unloaded event of usercontrol always executed twice when the usercontrol embeded in MetroTabItem

### ISSUE THREAD

**Issue by kevinlee0625** [MahApps/MahApps.Metro#3764]
**Environment(please complete the following information):**
 - MahApps.Metro version [e.g. v1.6.4]
 - OS: [e.g. Win10 1803]
 - Visual Studio [e.g. 2017 15.7.1]
 - .NET Framework [e.g. 4.7.1]

**Additional context**

```xaml
   <Grid>
       <metro:MetroAnimatedTabControl >
            <metro:MetroTabItem>
                <local:UserControl1 />
            </metro:MetroTabItem>
        </metro:MetroAnimatedTabControl>
    </Grid>
```

```csharp
public partial class UserControl1 : UserControl
    {
        public UserControl1()
        {
            InitializeComponent();
            this.Loaded += UserControl1_Loaded;
        }

        private void UserControl1_Loaded(object sender, RoutedEventArgs e)
        {
            
        }
    }
```

**Comment by batzen** [comment]
That's a bug/issue in wpf itself. Please report this issue in the dotnet/wpf repo.
There is nothing we can do in MahApps.Metro about it ☹️

**Comment by punker76** [comment]
@kevinlee0625 I created a sample without using MahApps to show you that this is not releated to MahApps. https://github.com/punker76/WPF.UserControl.Inside.TabControl

![tabcontrol_loaded_unloaded](https://user-images.githubusercontent.com/658431/77297625-dd0cba00-6ce9-11ea-91f0-078b8d4b5678.gif)
