### ISSUE TITLE
MahApps.Metro does not work with WPF on .Net Core 3

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [MahApps/MahApps.Metro#3769]
**Describe the bug**
When I try to use MahApps.Metro in a WPF .Net Core 3 project in Visual Studio 2019, it says that is it isn't fully compatible with .Net Core 3. Please update MahApps.Metro to work with .Net Core 3 WPF.

**To Reproduce**
1. Create a new WPF Project (.Net Core 3) project in Visual Studio 2019.
2. Install MahApps.Metro using Nuget.
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/45227503/78253693-673af680-7512-11ea-9ebf-5b795baca531.png)

**Environment (please complete the following information):**
 - MahApps.Metro version: v1.6.5
 - OS: Win10 Pro 20H1 Insider Preview
 - Visual Studio 2019 16.4.5
 - .NET Core 3

**Comment by timunie** [comment]
Hi @Jaiganeshkumaran ,

the current Release v1.6.5 does not (and will never) support .Net-Core. The upcoming version 2.0.0 will support .Net-Core. It is available as a prerelase via Nuget. The planned release date is May 2020.

Happy coding 
Tim
