### ISSUE TITLE
MahApps 2.0 ToggleSwitch and Coded UI Missing InOn/IsChecked State Property

### ISSUE THREAD

**Issue by SheriSteeves** [MahApps/MahApps.Metro#3770]
This is a followup to #3690. The new ToggleSwitch now populates the AutomationId, Name and FriendlyName based on the names I have set in my XML but there is no property to test the state of the toggle. 

![image](https://user-images.githubusercontent.com/18488212/78361235-11079b00-7586-11ea-9e05-27d69c61bc8c.png)

The properties shown are the same when the thumb indicator is selected:
![image](https://user-images.githubusercontent.com/18488212/78361433-65127f80-7586-11ea-8d94-094257c94b66.png)

I tested this using a small test WPF app in VS2017 using the pre-release v2.0.0-alpha0748 and .NET 4.5.2.

**Comment by timunie** [comment]
Hi @SheriSteeves 

Many thanks for posting this issue. Can you provide your sample App via Github? It may be very useful for Analyzing the issue.

Happy coding
Tim

**Comment by SheriSteeves** [comment]
I can do that, did you need a CodedUI sample project as well or just the sample app?

**Comment by timunie** [comment]
Hi @SheriSteeves ,
if the sample App shows the error I think it should be enough. Many thanks by the way.

Happy coding,
Tim

**Comment by SheriSteeves** [comment]
Hi @timunie,

I've uploaded the project here:  [https://github.com/SheriSteeves/MapApps-ToggleTest](url)

**Comment by punker76** [comment]
@SheriSteeves I found a possible bug for this and tried to fix it.

**Comment by SheriSteeves** [comment]
Will the alpha be updated via Nuget with this or should I download and build it my self? I've only access to v2.0.0-alpha0748 through the  Visual Studio package manager right now.

**Comment by SheriSteeves** [comment]
The changes did not fix the Coded UI state issue. I saw the class change and was looking (hoping) for a ToggleState property but no luck. Still the same list of properties as before.

![image](https://user-images.githubusercontent.com/18488212/79341158-5c606880-7ef9-11ea-960d-c67c8b80498f.png)

**Comment by punker76** [comment]
@SheriSteeves I got this with VisualUIAVerifyNative. And I read about thet Coded UI is obsolete.

![image](https://user-images.githubusercontent.com/658431/79355265-b71bb380-7f3d-11ea-854e-930038bcb823.png)

![image](https://user-images.githubusercontent.com/658431/79355284-bb47d100-7f3d-11ea-83a2-71ab0124ee62.png)
