### ISSUE TITLE
MetroWindow runtime controls hidden

### ISSUE THREAD

**Issue by PJonHar** [MahApps/MahApps.Metro#3772]
I am using Fluent and MahApps. I have an issue whereby when i bring up a second window the controls are not visible.

The MetroWindow design time controls are shown correctly.
When running the application and bringing up the MetroWindow using ShowDialog the controls are not shown:
I have used snoop and it appears the controls are actually there, they are just not displayed:
If i change the MetroWindow to a normal Window, the controls appear as expected.

**Screenshots**
![2020-04-12 13_45_12-](https://user-images.githubusercontent.com/1200267/79069308-2470df80-7cc5-11ea-9220-9cdb2543c9fd.png)
![2020-04-12 13_42_43-](https://user-images.githubusercontent.com/1200267/79069309-25097600-7cc5-11ea-84f6-95833c5ffbde.png)
![2020-04-12 13_54_58-KUKA RGI v3 - Microsoft Visual Studio](https://user-images.githubusercontent.com/1200267/79069324-381c4600-7cc5-11ea-92ad-25487d4e3810.png)

**Environment(please complete the following information):**
 - Fluent version [e.g. v7.1.0]
 - MahApps.Metro version [e.g. v2.0.0.0]
 - OS: [e.g. Win10 1903]
 - Visual Studio [e.g. 2019 16.5.3]
 - .NET Framework [e.g. 4.6.2]

**Comment by batzen** [comment]
Any chance you could share a repro?

**Comment by PJonHar** [comment]
So it appears to be something to do with Helix.
I have commented out the helix control i am using and it works.

**Comment by timunie** [comment]
@PJonHar please remember to close the issue if it is not MahApps related. Thank you and happy easter
