### ISSUE TITLE
Hamburger Menu, Pane closing/opening animation

### ISSUE THREAD

**Issue by DaaWaan** [MahApps/MahApps.Metro#3773]
The title already says it all, just a smooth easing animation when the pane will open or close. Would also like to suggest an animation for the hamburger if it will open or close, like it would turn into an X button.

**Comment by timunie** [comment]
Hi @DaaWaan 

> Would also like to suggest an animation for the hamburger if it will open or close, like it would turn into an X button.

I don't know if it is possible to animate this, but you can already change the content of the button: 
![HamburgerMenuCloseButton](https://user-images.githubusercontent.com/47110241/85667607-0e689d80-b6be-11ea-93ea-476b5b66557d.png)

```xaml
<Style TargetType="{x:Type mah:HamburgerMenu}">
    <Setter Property="HamburgerButtonTemplate">
        <Setter.Value>
            <DataTemplate>
                <mah:FontIcon Glyph="&#xE700;" />
            </DataTemplate>
        </Setter.Value>
    </Setter>
    <Style.Triggers>
        <Trigger Property="IsPaneOpen" Value="True">
            <Setter Property="HamburgerButtonTemplate">
                <Setter.Value>
                    <DataTemplate>
                        <mah:FontIcon Glyph="&#xE711;" />
                    </DataTemplate>
                </Setter.Value>
            </Setter>
        </Trigger>
    </Style.Triggers>
</Style>
```

Here is the shown sample: 
https://github.com/timunie/MahApps.Metro.Examples 

Happy coding 
Tim
