### ISSUE TITLE
Question : Example for Tile like in Demo

### ISSUE THREAD

**Issue by Torchok19081986** [MahApps/MahApps.Metro#3774]
Hallo, i have a difficulty to find a example for Tile like in MahApps.Metro.Demo.exe. Im rather new in WPF (not so much programmed in WPF C#).  Can someone give me source or link to start with tiles and WPF ? My goal is create a dashboard with some Tiles in it.  Do i have to use new Version of Mahapps 2.0 alpha or Version 1.6.5 enough ? Many thanks for any help.

**Comment by timunie** [comment]
Hi @Torchok19081986 
as your question is neither a bug nor a feature request, please ask it on [gitter](https://gitter.im/MahApps/MahApps.Metro). We can chat there about your questions. 

Thank you for understanding and please close this issue.

Happy coding
Tim

**Comment by Torchok19081986** [comment]
o, thanks tim.
