### ISSUE TITLE
NumericUpDown it is not possible to start with decimal separator

### ISSUE THREAD

**Issue by SeFiROOTpitu** [MahApps/MahApps.Metro#3778]
**Describe the bug**
When I start with the separator I should take the following as decimals, but nevertheless ignore the point.
How can I make this work?
**To Reproduce**
1. Go to 'NumericUpDown'
2. first value to start is "."
3. input value ".1234"
4. when accept value "1234", the correct value is "0.1234"

**Expected behavior**
I need to start value with separator is very used in my work

**Comment by punker76** [comment]
@SeFiROOTpitu This is already fixed in the latest source (also available via NuGet as pre-release)

![mahapps_nud_sep](https://user-images.githubusercontent.com/658431/80197473-fa051780-861e-11ea-8d9f-62c70eb56775.gif)
