### ISSUE TITLE
I can't reduce the height of a button at 10

### ISSUE THREAD

**Issue by Marko97IT** [MahApps/MahApps.Metro#3780]
I need to reduce the height for a button to 1 but I can't.
![hgfds](https://user-images.githubusercontent.com/29895535/80284638-01601a00-8720-11ea-9aac-c413631d268f.png)

**Comment by punker76** [comment]
@Marko97IT That’s because the default style defines a MinHeight of 25.


https://github.com/MahApps/MahApps.Metro/blob/443389cdc6e83fbd9a1d5584a48c0466ee5f3cd4/src/MahApps.Metro/Styles/Controls.Buttons.xaml#L399

So just set it to 0 and your issue is gone.
