### ISSUE TITLE
CheckedCommand and UnCheckedCommand Missing in 2.0.0-Alpha0748

### ISSUE THREAD

**Issue by fradsham** [MahApps/MahApps.Metro#3783]
*Missing Commands in the new alpha version**

Not to repeat but I asked this on  [stackoverflow](https://stackoverflow.com/questions/61378557/mahapps-toggleswitch-not-found-in-version-2-0-in-net-core-3-1) but never got a response, so I would like to ask here because I do not know if this removal of the two commands is intentional or not? If it is intentionally removed, is there an example to develop a work around?

**To Reproduce**
1. Create a new ToggleSwitch in and xaml file
` <mahapps:ToggleSwitch  OnContent="{Binding OnLabelText}" 
                                           OffContent="{Binding OffLabelText}" 
                                       Style="{StaticResource ToggleSwitch.Win10}"/>`
2. The properties from version 1.65 (CheckedCommand and UnCheckedCommand) are not available in version 2.0.0-Alpha0748

**Environment:**
 - Nuget: MahApps.Metro version v2.0.0-Alpha0748
 - OS: Windows 10 Build 177763
 - Visual Studio 2019 v16.5.1
 - .NET Core 3.1.200

**Comment by timunie** [comment]
Hi @fradsham ,

it seems it was replaced by just one `Command`. see: https://github.com/MahApps/MahApps.Metro/blob/5873948e0fcb72704961b54abb92781ef0e5e8a2/src/MahApps.Metro/Controls/ToggleSwitch.cs#L332-L339

I hope this helps you

Happy coding,
Tim

**Comment by fradsham** [comment]
Thanks, Tim for the information. 
I can re-write the command in my ViewModel but the two commands allowed me to keep the logic simple for starting and stopping a service without having track status of the UI logic in my code. It helped a lot to keep things separate.

Would there be an appetite if someone wanted to do a pull-request and add the OnCommand and OffCommand based on the Command mentioned above, so there are three options for developers?

Happy Coding 
@fradsham

**Comment by punker76** [comment]
@fradsham This will be available in next release again.

```xaml
<Controls:ToggleSwitch CommandParameter="{Binding}"
                       OnCommand="{Binding ToggleSwitchOnCommand}"
                       OffCommand="{Binding ToggleSwitchOffCommand}" />
```
