### ISSUE TITLE
different design 32/64bit

### ISSUE THREAD

**Issue by 723461234** [MahApps/MahApps.Metro#3791]
when you change your project from 32 to 64 bit only, mahapps will change the design to non-mahapps, however if you build or run the solution it is still mahapps metro style

![32bit](https://user-images.githubusercontent.com/64864383/81104098-04a59380-8ee0-11ea-9bf2-910148c8a5f1.png)
![64bit release version](https://user-images.githubusercontent.com/64864383/81104100-053e2a00-8ee0-11ea-8e1a-7654a7b9d038.png)

**Comment by timunie** [comment]
Hi @723461234 
This issue is caused by the designer. The VS designer is 32 bit as far as I remember. There is nothing we can do on our side to solve this. I am sorry. 

happy coding anyway
Tim

**Comment by 723461234** [comment]
> 
> 
> Hi @723461234


ohhh i see it has nothing to do with mahapps 
well keep up the good work :)
