### ISSUE TITLE
MahApps 2.0: Customize accent colors

### ISSUE THREAD

**Issue by jahnotto** [MahApps/MahApps.Metro#3792]
Is it possible to customize accent colors in MahApps 2.0?

I guess it's possible to copy and modify e.g. Styles/Themes/Light.Blue.xaml with my own colors, but requires me to keep it in sync with any other changes in the theme file whenever I update MahApps.

**Comment by batzen** [comment]
Do you want to customize the accent color or sync it with the current windows accent color?

**Comment by jahnotto** [comment]
Not sure what the difference is. Basically I'd like to use my own color scheme for the window title bar buttons, highlight etc instead of using those that are defined in the themes.

**Comment by batzen** [comment]
You could try to use `RuntimeThemeGenerator` from ControlzEx and change the current theme to the new generated one. It automatically generates new themes and MahApps.Metro already depends on it.

**Comment by timunie** [comment]
@jahnotto I think the feature that @batzen mentioned will be released in short. The current development version already includes it.

**Comment by jahnotto** [comment]
Ok, thanks a lot! I'll have a look on it.
