### ISSUE TITLE
Cannot change fore/background colour of checkboxes

### ISSUE THREAD

**Issue by Inzanit** [MahApps/MahApps.Metro#3797]
**Describe the bug**
When adding a checkbox in pre-release 2.0, I cannot change the colour of checkboxes. In stable 1.6.5 I can.

**To Reproduce**
1. Start new WPF application on .NET Framework 4.8 or .NET Core 3
2. Add MahApps pre-release
3. Add checkbox
4. Change checkbox foreground to "Red"

See reproducible repo here: https://github.com/Inzanit/MahApps.Repro

3 projects included: .NET Core, .NET Framework pre-release MahApps in `MahApps.Repro.Core` and `MahApps.Repro.NetFX`. Stable MahApps release on `MahApps.Repro.NetFXStable`.

**Expected behavior**
For the foreground text colour to change to red

**Repo**
https://github.com/Inzanit/MahApps.Repro

**Edit**
Seems like I can change it with `mah:CheckBoxHelper.ForegroundChecked`, is this the new way of achieving this? And if so, follow up question, are the docs open to contribution?

**Comment by punker76** [comment]
@Inzanit The new CheckBox has new brushes. If you want to override the Foreground then you can change it with the CheckBoxHelper or by changing the brushes itself.

```
Controls:CheckBoxHelper.ForegroundChecked
Controls:CheckBoxHelper.ForegroundCheckedDisabled
Controls:CheckBoxHelper.ForegroundCheckedMouseOver
Controls:CheckBoxHelper.ForegroundCheckedPressed
Controls:CheckBoxHelper.ForegroundIndeterminate
Controls:CheckBoxHelper.ForegroundIndeterminateDisabled
Controls:CheckBoxHelper.ForegroundIndeterminateMouseOver
Controls:CheckBoxHelper.ForegroundIndeterminatePressed
Controls:CheckBoxHelper.ForegroundUnchecked
Controls:CheckBoxHelper.ForegroundUncheckedDisabled
Controls:CheckBoxHelper.ForegroundUncheckedMouseOver
Controls:CheckBoxHelper.ForegroundUncheckedPressed
```

```
MahApps.Brushes.CheckBox.ForegroundChecked
MahApps.Brushes.CheckBox.ForegroundCheckedDisabled
MahApps.Brushes.CheckBox.ForegroundCheckedMouseOver
MahApps.Brushes.CheckBox.ForegroundCheckedPressed
MahApps.Brushes.CheckBox.ForegroundIndeterminate
MahApps.Brushes.CheckBox.ForegroundIndeterminateDisabled
MahApps.Brushes.CheckBox.ForegroundIndeterminateMouseOver
MahApps.Brushes.CheckBox.ForegroundIndeterminatePressed
MahApps.Brushes.CheckBox.ForegroundUnchecked
MahApps.Brushes.CheckBox.ForegroundUncheckedDisabled
MahApps.Brushes.CheckBox.ForegroundUncheckedMouseOver
MahApps.Brushes.CheckBox.ForegroundUncheckedPressed
```
