### ISSUE TITLE
Range Slider Upper/Lower value coercion

### ISSUE THREAD

**Issue by lipchev** [MahApps/MahApps.Metro#3798]
The actual position of the upper/lower thumbs may become out of sync with the actual values, when the coercion of the bound properties takes effect during dragging operations.

**To Reproduce**

Consider the following dependency property:

        public static readonly DependencyProperty MaxValueDisplayedProperty = DependencyProperty.Register(
            "MaxValueDisplayed", typeof(double), typeof(MainWindow), new PropertyMetadata(75d, PropertyChangedCallback, CoerceValueCallback ));

        private static object CoerceValueCallback(DependencyObject dependencyObject, object baseValue)
        {
            var value = (double) baseValue;
            if (value < 50)
                return 50.0;
            return baseValue;
        }
 
1. Start dragging the UpperThumb (e.g. the right thumb with initial value of 75) towards the LowerLimit (0 in our case)
2. As the UpperLimit reaches 50 the value is coerced to 50 (both the MaxValueDisplayed and the RangeSlider.UpperLimit show 50)
3. The user is however free to _drag on_ - that is the actual thumb position becomes out of sync with the current value
4. Even after releasing the mouse button, the position of the thumb is out of sync
5. The behavior is the same regardless of whether we're dragging the whole range or just the upper tracker.

**Expected behavior**
The thumb position respects the coerced value at all times: similar to how the slider stops moving when reaching the same coercion limit (3rd screenshot)

**Screenshots**
![image](https://user-images.githubusercontent.com/5253184/82143615-d31cb880-984d-11ea-8a1e-80b790fb23bf.png)
![image](https://user-images.githubusercontent.com/5253184/82143627-e3cd2e80-984d-11ea-91f5-335ab9501e90.png)
![image](https://user-images.githubusercontent.com/5253184/82143639-fba4b280-984d-11ea-92bb-061d7882673e.png)

**Environment:**
 - MahApps.Metro version [both v1.6.4 & 2.0.0-alpha0821]
 - OS: [Win10]
 - Visual Studio [2017]
 - .NET Framework [4.7.2]

**Repo**
[Here](https://github.com/lipchev/RangeSlider-ValueCoercion) is the very simple example from the screenshots, with the very basic designer definition:
```
        <mah:RangeSlider Minimum="0" Maximum="100" LowerValue="25" UpperValue="{Binding MaxValueDisplayed}"  x:Name="RangeSlider"/>
        <Slider Minimum="0" Maximum="100" Value="{Binding MaxValueDisplayed}" Grid.Row="1" x:Name="Slider"/>
        <UniformGrid Columns="3" Grid.Row="2">
            <mah:MetroHeader Header="RangeSlider.UpperValue" Content="{Binding ElementName=RangeSlider, Path=UpperValue}" />
            <mah:MetroHeader Header="Slider.Value" Content="{Binding ElementName=Slider, Path=Value}" />
            <mah:MetroHeader Header="Max Value Displayed" Content="{Binding MaxValueDisplayed}" />
        </UniformGrid>
```

**Comment by punker76** [comment]
@lipchev This is now fixed and will be available with next v2.0 release. Thx for using the latest alpha hot stuff and reporting the issue. And thx for the sample! 👍
