### ISSUE TITLE
Expander with a nested expander

### ISSUE THREAD

**Issue by offan** [MahApps/MahApps.Metro#3803]
When a nested expander closes, the upper expander close.
Example
` <Expander
                             ExpandDirection="Down"

                            Header="Hidden Stuff">

                            <StackPanel Orientation="Vertical">

                                <TextBlock Text="...42" />

                                <Expander

                                     ExpandDirection="Down"

                                    Header="Hidden Stuff1">

                                    <StackPanel Orientation="Vertical">

                                        <TextBlock  Text="...43" />

                                    </StackPanel>

                                </Expander>

                            </StackPanel>

                        </Expander>`

**Comment by batzen** [comment]
Would you mind posting the versions you are currently using? May i ask why you didn't follow the bug report template?

**Comment by offan** [comment]
Sorry. 
- MahApps.Metro version last commit  hash: 4eb466820e7564ef5aad3c87dceba2cb52015d91
 - OS:  Win10 1909
 - Visual Studio  2019 16.6.0
 - .NET Framework  4.7.1
Screenshot:
![1](https://user-images.githubusercontent.com/8559841/82580231-f1611c00-9b9f-11ea-836c-43c22be40b27.png)

![1](https://user-images.githubusercontent.com/8559841/82580354-15bcf880-9ba0-11ea-8fe4-ce729abe28db.png)

**Comment by punker76** [comment]
@offan Thanks for reporting this nasty behavior. This will be fixed in next release (final release).

The problem here is that the first parent Expander also get the Expanded and Collapsed events. So we must look for the OriginalSource which must be also the sender.

/cc @batzen
