### ISSUE TITLE
Open the window to display only the left glowbrush. After moving the windows, the glowbrush will display normally

### ISSUE THREAD

**Issue by 3400442579** [MahApps/MahApps.Metro#3810]
**Screenshots**

![1](https://user-images.githubusercontent.com/34226979/82774292-00352080-9e77-11ea-8d0c-424a2af48314.png)
![2](https://user-images.githubusercontent.com/34226979/82774298-04613e00-9e77-11ea-992c-4d5ac9adf0be.png)
![3](https://user-images.githubusercontent.com/34226979/82774301-04f9d480-9e77-11ea-9976-9eb3feb8eefd.png)

**Environment(please complete the following information):**
 - MahApps.Metro version [2.0]
 - Win10 : [e.g. Win10 1803]
 - Visual Studio 2019 16.6
 - .NET core 3.1

**Comment by punker76** [comment]
@3400442579 Can you check the version of ControlzEx lib too?

**Comment by punker76** [comment]
@3400442579 This is fixed now and will be available with v2.3.4

**Comment by milanLavic** [comment]
I'm using version 2.4.9 and window behaves the same way .
Is it fixed yet?
