### ISSUE TITLE
Regression in v2.0: Effect of parent's IsEnabled on DropDownButton

### ISSUE THREAD

**Issue by yjagota** [MahApps/MahApps.Metro#3811]
**Description of the bug**
If a parent containing a `DropDownButton` has a bound `IsEnabled` property, and the property is switched to disabled and enabled again, the `DropDownButton` remains disabled. This only happens in v2.0.0 but works as expected in v1.6.5.

**Expected behavior**
The `DropDownButton` should be enabled again when parent's `IsEnabled` is set to `true`.

**Environment:**
 - MahApps.Metro version v2.0.0
 - Win10 1909
 - Visual Studio 2019 16.6.0
 - .NET Framework 4.7.2

**Repo**
https://github.com/yjagota/MahAppsTest

**Comment by punker76** [comment]
@yjagota Thanks for reporting this issue! It's now fixed with #3819 and will be available with next release.
