### ISSUE TITLE
Expander reserves internal needed space before expanding

### ISSUE THREAD

**Issue by seba30** [MahApps/MahApps.Metro#3812]
Hey folks,

I've created a small project to see, whether my observations are coming from my project or MahApps. And sadly it comes from MahApps.

An Expander, nested in a Grid, reserves the space for the internal elements, before it will be expanded. After collapsing the Expander behaves like expected.

MahApps.Metro v2.0.0
![image](https://user-images.githubusercontent.com/48946764/82879622-7a2fdd00-9f3d-11ea-983e-593275a2c005.png)
![image](https://user-images.githubusercontent.com/48946764/82879627-7d2acd80-9f3d-11ea-9eba-d01538a00e2e.png)
![image](https://user-images.githubusercontent.com/48946764/82879633-7ef49100-9f3d-11ea-9f51-f788c3c99ce7.png)

So I changed the version to the previous stable v1.6.5:

MahApps.Metro v1.6.5
![image](https://user-images.githubusercontent.com/48946764/82879711-a4819a80-9f3d-11ea-91c3-64a63dc97c95.png)
![image](https://user-images.githubusercontent.com/48946764/82879721-a64b5e00-9f3d-11ea-9b8f-5d204d606a45.png)
![image](https://user-images.githubusercontent.com/48946764/82879729-a8adb800-9f3d-11ea-9f8c-8304c09e5be6.png)

- MahApps.Metro version v2.0.0 and v1.6.5
- Win10 1909
- Visual Studio 2019 16.6.0
- .NET Framework 4.8

![image](https://user-images.githubusercontent.com/48946764/82880071-2ec9fe80-9f3e-11ea-882a-db6e7b2fd401.png)

**Comment by punker76** [comment]
@seba30 Thx for reporting this issue. It's now fixed with #3816 and will be available with the next release.
