### ISSUE TITLE
Visual-Studio-Templates     Does not work in vs2019

### ISSUE THREAD

**Issue by outputlog** [MahApps/MahApps.Metro#3820]
After the template is placed in the specified path, Unable to retrieve when creating project

How to simply modify and use

I searched the Internet. I haven't found a way yet. I didn't know it before

Could you help me, please

**Comment by outputlog** [comment]
vs2019 
Unexpected restart of PC, resolved

**Comment by goldcode** [comment]
Perhaps one can add some info on https://mahapps.com/docs/guides/quick-start that Visual Studio Template Projects exist?

**Comment by outputlog** [comment]
> Perhaps one can add some info on https://mahapps.com/docs/guides/quick-start that Visual Studio Template Projects exist?

existence
