### ISSUE TITLE
In RadioButton the OuterEllipse.Fill shouldn't be bound to the RadioButton's background

### ISSUE THREAD

**Issue by paulovila** [MahApps/MahApps.Metro#3821]
in [RadioButton.xaml](https://github.com/MahApps/MahApps.Metro/blob/develop/src/MahApps.Metro/Styles/Controls.RadioButton.xaml) the ```OuterEllipse.Fill``` and ```CheckOuterEllipse.Fill``` are bound to the ```RadioButton.Background```. This is not 'correct' in the sense that it looks like disabled when the ```RadioButton.Background``` is set to ```Transparent```.
For example: V2.0 is on the left, V1.6.5 on the right:
![image](https://user-images.githubusercontent.com/888391/82923392-c9443500-9f72-11ea-8f28-07d393d70bd1.png)

 - MahApps.Metro version [ v2.0]

**Comment by timunie** [comment]
Maybe this is a good point to implement the `CheckBoxHelper` for this Control as well.

**Comment by yjagota** [comment]
Same happens with CheckBox.

**Comment by paulovila** [comment]
This is just a styling issue; differentiate the general background from the radio _'activation area'_ background with another name. 
Now if the ```CheckBox``` has the same problem, use the same naming convention for each case.
For example ```RadioButton.ActivationArea.Background``` and ```CheckBox.ActivationArea.Background``` respectively.
