### ISSUE TITLE
BadgedControl should have controllable visibility on just the badge

### ISSUE THREAD

**Issue by 240026763** [MahApps/MahApps.Metro#3823]
**Is your feature request related to a problem? Please describe.**
Typically a badge only shows when there is new information or updates. The badged control doesn't appear to have a method to disappear when the value is 0. Visibility controls the child control as well so that doesn't work to hide just the badge.

**Describe the solution you'd like**
A property such as BadgeVisibility that can be bound to would be great.

**Comment by timunie** [comment]
Hi @240026763 ,
it will disappear if you set your property to `null` instead of `0`. You can use `int? MyBadge {get; set;}` for Binding

![BadgedDemo](https://user-images.githubusercontent.com/47110241/83176676-1dd7e380-a11e-11ea-9213-4ee304df2ddf.png)

Happy coding 
Tim

**Comment by 240026763** [comment]
Thanks, this seems to work fine. I had to put in a value converter to basically make anything 0 or less return null.
