### ISSUE TITLE
Version 2.0.0 doesn't install /Styles/Colors.xaml correctly

### ISSUE THREAD

**Issue by will-scc** [MahApps/MahApps.Metro#3828]
**Describe the bug**
If you install version 2.0.0 via NuGet the files /Styles/Colors.xaml cannot be located.

**To Reproduce**
1. Install package version 2.0.0 via NuGet
2. Attempt to reference in App.xaml, e.g.: <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Colors.xaml" />
3. Try to start application (or something VS will warn before)
4. Exception `IOException: Cannot locate resource 'styles/colors.xaml'` is thrown

Doing same steps with version 1.6.5 does not reproduce this issue.

**Comment by punker76** [comment]
@will-scc The styles, colors and brushes are now located in new resource dictionaries. Please read the new [quick-start guide](https://mahapps.com/docs/guides/quick-start#mahapps-build-in-styles-and-themes) or here at the [wiki](https://github.com/MahApps/MahApps.Metro/wiki/Quick-Start). It should help you. Thx 🙏
