### ISSUE TITLE
Using DateTimePicker leads into error

### ISSUE THREAD

**Issue by seba30** [MahApps/MahApps.Metro#3829]
Hey there,

With using the DateTimePicker, I get an error with the following message:

Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.DatePicker', AncestorLevel='1''. BindingExpression:Path=(0); DataItem=null; target element is 'DatePickerTextBox' (Name='PART_TextBox'); target property is 'HelpText' (type 'String')

Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.DatePicker', AncestorLevel='1''. BindingExpression:Path=(0); DataItem=null; target element is 'DatePickerTextBox' (Name='PART_TextBox'); target property is 'LabeledBy' (type 'UIElement')

Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.DatePicker', AncestorLevel='1''. BindingExpression:Path=(0); DataItem=null; target element is 'DatePickerTextBox' (Name='PART_TextBox'); target property is 'Name' (type 'String')

A repository with the error can be found [here](https://github.com/seba30/MahApps.Theme).

MahApps.Metro: v2.0.0
Windows: Win10 1909 [Version 10.0.18363.836]
Visual Studio: 2019 16.6.0
Target Framework: v4.8

**Comment by punker76** [comment]
@seba30  this has now been fixed, and it will be released in the next version of MahApps.Metro

**Comment by seba30** [comment]
Thank you so much!
