### ISSUE TITLE
Introduce attached properties to set RadioButton's brush states

### ISSUE THREAD

**Issue by punker76** [MahApps/MahApps.Metro#3834]
## Describe the feature

Currently, every brush must be overwritten at the App.xaml or where the RadioButton is used.

Changing the brushes of a RadioButton could be simplified by using attached properties, as it is already done with the CheckBox.

## Additional context

This Feature Request comes form these Issues #3821 , #3833 .

**Comment by ye4241** [comment]
Should it be implemented into Button, ToggleButton to control mouseover/checked state easily without overwritten any style.
