### ISSUE TITLE
Checkboxes using Dark theme within DataGrid column appear unchecked (Server 2012 R2)

### ISSUE THREAD

**Issue by webprofusion-chrisc** [MahApps/MahApps.Metro#3840]
## Describe the bug

On Windows Server 2012 R2, using a Dark theme, checked DataGridCheckBoxColumn appears unchecked.

## Steps to reproduce

On Windows Server 2012 R2, using a Dark theme, 
```
 <DataGridCheckBoxColumn Binding="{Binding IsSelected}" Header="Include" />
```
Or, download https://certifytheweb.com, add a contact using New Certificate, then Add new Certificate with at least one domain. `Include` column should be checked in light or dark mode (changed under settings).

## Expected behavior

![image](https://user-images.githubusercontent.com/2445502/83939245-109db180-a80e-11ea-9311-26ed90f4dd31.png)

## Actual behavior

The checkboxes in this image are checked, but they don't look it until the theme is set back to light.

![image](https://user-images.githubusercontent.com/2445502/83939210-c0265400-a80d-11ea-8983-91f030634d8b.png)

## Environment

```
MahApps.Metro version: v2.0.1
Windows build number:  Windows 2012 R2 standard (via AWS lightsail)
Visual Studio: 2019 16.7.0
Target Framework: v4.6.2
```

_Originally posted by @webprofusion-chrisc in https://github.com/MahApps/MahApps.Metro/issues/3833#issuecomment-640007729_

**Comment by punker76** [comment]
@webprofusion-chrisc It seems like that you use a different style for the CheckBox. So can you show this style?

**Comment by webprofusion-chrisc** [comment]
@punker76 hmm, I do? Maybe! I did have a couple of naive style hacks (some of the borders were too white and the tab item grey was hard to read) but I don't know if they are affecting this:

https://github.com/webprofusion/certify/blob/development/src/Certify.UI/App.xaml

This is the actual usage in-situ: https://github.com/webprofusion/certify/blob/65e7257b50358e885d1f1bd26b8c6773d299522a/src/Certify.UI/Controls/ManagedCertificate/CertificateDomains.xaml#L218

**Comment by punker76** [comment]
@webprofusion-chrisc Oh I see, you don’t use autogenerated columns, so you need to set the style for the CheckBox column like in this sample

https://github.com/MahApps/MahApps.Metro/blob/5a79c0479496c73291858685cb20b81c3adc0f39/src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/DataGridExamples.xaml

**Comment by webprofusion-chrisc** [comment]
Thanks! I just figured this out at the exact same time, I reproduced it using the MahApps.Metro.Demo and removing those attributes. I'll do that. Does this still count as a bug (i.e. should there be a default instead of just not being set)?

**Comment by timunie** [comment]
@webprofusion-chrisc I think this is not possible due to the way the DataGrid is implemented. 🙁

**Comment by punker76** [comment]
@webprofusion-chrisc @timunie I found a way to do this.

**Comment by timunie** [comment]
@punker76 Did you ask Chuck Norris? I read abot it on a MS page that said it is not possible. 

If it works this would be a huge improvement.

**Comment by webprofusion-chrisc** [comment]
Chuck Norris doesn't implement data grid improvements, the IL reconfigures dynamically according to his will.

**Comment by punker76** [comment]
@webprofusion-chrisc  this has now been fixed, and it will be released in the next version of MahApps.Metro

**Comment by webprofusion-chrisc** [comment]
@punker76 fantastic! Much appreciated, I know this was quite complicated but hopefully it makes it easier for people to use.
