### ISSUE TITLE
Add the ability to customize the default ContentCharacterCasing of buttons

### ISSUE THREAD

**Issue by jeremyVignelles** [MahApps/MahApps.Metro#3848]
## Describe the feature

I don't personally like that all my (square) buttons texts are written as lower case.
I read the source code and found this:

```xml
<Setter Property="Controls:ControlsHelper.ContentCharacterCasing" Value="Lower" />
```

but I didn't find a way to override it properly (same for FontWeight), so I had to write my own style:

```xml
    <Style x:Key="My.Styles.Button.Square" TargetType="{x:Type ButtonBase}" BasedOn="{StaticResource MahApps.Styles.Button.Square}">
        <Setter Property="mah:ControlsHelper.ContentCharacterCasing" Value="Normal" />
        <Setter Property="FontWeight" Value="Normal" />
    </Style>
```

If I want to apply the same "rollback" on accented square buttons, I have to define another style for it, based on `Square.Accent`.

What I'd like is to be able to define something like this in my resources

```xml
<Controls:CharacterCasing x:key="MahApps.Casing.Button.Square">Normal</Controls:CharacterCasing>
<FontWeight x:key="MahApps.Font.Weight.Button.Square">Normal</FontWeight>
```

## Additional context

Don't know what to put here.

**Comment by timunie** [comment]
Hi @jeremyVignelles 

you can also override the `Style` with the same `Key`, so you don't need to change all the keys:
```xaml
    <Style x:Key="MahApps.Styles.Button.Square" TargetType="{x:Type ButtonBase}" BasedOn="{StaticResource MahApps.Styles.Button.Square}">
        <Setter Property="mah:ControlsHelper.ContentCharacterCasing" Value="Normal" />
        <Setter Property="FontWeight" Value="Normal" />
    </Style>
```

Happy coding
Tim

**Comment by punker76** [comment]
@jeremyVignelles I will close this for now. If the answer from @timunie doesn't help then you can reopen this issue. Thx

**Comment by jeremyVignelles** [comment]
It's been a while, so I had to look in the code. Either that didn't work, or I didn't have time to check, but I still have my own style keys, and repeated for each button type, which is quite inconvenient.

I think the feature request still stand, because a one-liner would be better:
```xml
<Controls:CharacterCasing x:key="MahApps.Casing.Button">Normal</Controls:CharacterCasing>
```
could reset all button styles. with `MahApps.Casing.Button.Square` that would, by default, be based on `MahApps.Casing.Button`
What do you think ?

I'll reopen so you can tell me 🙂

**Comment by jeremyVignelles** [comment]
@punker76 : Seems that I don't have the permission to reopen an issue
