### ISSUE TITLE
IOException: Die Ressource "styles/controls.animatedtabcontrol.xaml" kann nicht gefunden werden.

### ISSUE THREAD

**Issue by jogibear9988** [MahApps/MahApps.Metro#3857]
I get this exception when running a Net4.8 app using the lib

**Comment by jogibear9988** [comment]
I'm using v2.1

**Comment by jogibear9988** [comment]
Was my fault... I refrenced this style...

**Comment by punker76** [comment]
@jogibear9988 Yes, sorry, the docs not updated yet, this animated TabControl has now a key and is located in [Controls.TabControl.xaml](https://github.com/MahApps/MahApps.Metro/blob/develop/src/MahApps.Metro/Styles/Controls.TabControl.xaml)

https://github.com/MahApps/MahApps.Metro/blob/df066b364cd2ebf0770929b217168a9dbd21cb06/src/MahApps.Metro/Styles/Controls.TabControl.xaml#L800

**Comment by andrescirulo** [comment]
I'm getting this error when using MetroAnimatedSingleRowTabControl
I tried doing <MetroAnimatedSingleRowTabControl Style="{StaticResource MahApps.Styles.TabControl.Animated}"> but it seems i'm missing something or that's not what I need to do to solve it

**Comment by andrescirulo** [comment]
Got it, i was doing the same as @jogibear9988 ...... i was referencing this style in Application.xml 🤦‍♂️
