### ISSUE TITLE
ShowModalMessageExternal doesn't work together with Powershell

### ISSUE THREAD

**Issue by kafej** [MahApps/MahApps.Metro#3861]
Hi,

I'm a little bit confused here... I want to migrate from 1.6 to newest one 2.0.1 and have a problem with dialog control. 
I want to use my PowerShell dialog in the simplest way, so I used something like this:

```ps
    $ok      = [MahApps.Metro.Controls.Dialogs.MessageDialogStyle]::Affirmative
    $result = [MahApps.Metro.Controls.Dialogs.DialogManager]::ShowModalMessageExternal($Win,"text","text",$ok)
    $dialgResult.Text = $result
    If ($result -eq "Affirmative"){ 
        $dialgResult.Foreground = "Green"
    }
    else{
        $dialgResult.Foreground = "Red"
    }
```

That was simple, clean, and easy to run with 1.6, but it doesn't work with 2.0.1. This kind of usage of MahApps (PowerShell) is still possible or it's C# or die ;D

MahApps.Metro version: v2.0.1
Windows build number: Win10 1909 [Version 10.0.18363.836]
Visual Studio: 2015 & 2019
Target Framework: .NET 4.5.2

**Comment by damienvanrobaeys** [comment]
Hello Jan, as mentioned I have the same issue.
As requested, see my example here below:
https://github.com/damienvanrobaeys/dialog_validation_test
