### ISSUE TITLE
HeaderedControlHelper.HeaderFontSize not working on text

### ISSUE THREAD

**Issue by MitchWenceInfocorp** [MahApps/MahApps.Metro#3863]
## Describe the bug

I am setting up a `MetroTabControl`, and want to use the `HeaderedControlHelper.HeaderFontSize`, however, the font is not changing.   Set `CloseButtonEnabled="True"` shows that the "X" button changing size, however, the text is not.

## Steps to reproduce
This an issue with my app and I believe a "rogue" style (maybe Material Design In XAML?) is overwriting this.  However, I cannot find it.   

## Expected behavior

I figured doing this will force it:

```
<Controls:MetroTabItem Header="headers" CloseButtonEnabled="True">
	<Controls:MetroTabItem.Style>
		<Style TargetType="{x:Type Controls:MetroTabItem}">
			<Setter Property="Controls:HeaderedControlHelper.HeaderFontSize"  Value="50"/>
		</Style>
	</Controls:MetroTabItem.Style>
</Controls:MetroTabItem>
```

This did not change anything.
## Actual behavior

The text of the header isn't changing, but if `CloseButtonEnabled="True"` then the X button increases in size

## Environment

```
MahApps.Metro version: v2.0.1
Windows build number: Win10 1903 [Version 10.0.18362.900]
Visual Studio: 2019 16.6.1
Target Framework: .Net Core 3.1.5
```

## Screenshots
This code:
```
<Controls:MetroTabItem 
    Controls:HeaderedControlHelper.HeaderFontSize="50"
    CloseButtonEnabled="True"
    Header="Font Set to size 50"/>
<Controls:MetroTabItem 
    Controls:HeaderedControlHelper.HeaderFontSize="5"
    CloseButtonEnabled="True"
    Header="Font Set to Size 5"/>
```
Produces this:
![Screenshot_1](https://user-images.githubusercontent.com/8904275/85299655-28f70880-b46b-11ea-851a-ab9a108877bb.png)

FYI: the 5 point font "X" is there but you only see it when moving the mouse over

**Comment by punker76** [comment]
@MitchWenceInfocorp I can't reproduce this with following code. So it would help if you can create a short sample with this issue. Thx

```xaml
        <Controls:MetroTabControl x:Name="MainTabControl2" Grid.Row="1" Controls:HeaderedControlHelper.HeaderFontSize="25">
            <Controls:MetroTabItem 
                Header="Font Set to size 25"/>
            <Controls:MetroTabItem 
                Header="Font Set to Size 15"/>
            <Controls:MetroTabItem 
                CloseButtonEnabled="True"
                Header="Font Set to size 25"/>
            <Controls:MetroTabItem 
                CloseButtonEnabled="True"
                Header="Font Set to Size 15"/>
        </Controls:MetroTabControl>
```

![image](https://user-images.githubusercontent.com/658431/85301155-c53f0080-b4a7-11ea-87aa-384c9ccb8749.png)

or

```xaml
        <Controls:MetroTabControl x:Name="MainTabControl2" Grid.Row="1">
            <Controls:MetroTabItem 
                Controls:HeaderedControlHelper.HeaderFontSize="25"
                Header="Font Set to size 25"/>
            <Controls:MetroTabItem 
                Controls:HeaderedControlHelper.HeaderFontSize="15"
                Header="Font Set to Size 15"/>
            <Controls:MetroTabItem 
                Controls:HeaderedControlHelper.HeaderFontSize="25"
                CloseButtonEnabled="True"
                Header="Font Set to size 25"/>
            <Controls:MetroTabItem 
                Controls:HeaderedControlHelper.HeaderFontSize="15"
                CloseButtonEnabled="True"
                Header="Font Set to Size 15"/>
        </Controls:MetroTabControl>
```

![image](https://user-images.githubusercontent.com/658431/85301233-dee04800-b4a7-11ea-822a-f5e30b4ad6b2.png)

**Comment by MitchWenceInfocorp** [comment]
@punker76 yes, if I create a small test app it works perfectly.  So it must be something in my style themes that is doing.  Is there a way to force the style per tab?

**Comment by timunie** [comment]
HI @MitchWenceInfocorp ,
it should work like any in normal WPF control. If you are able to provide a "non-working" sample one might have a deeper look what is wrong. Right now it is just guessing. 

Maybe you set the `Style` or `ControlTemplate` somewhere globally, which overrides the default one. Please double check this and post any `TabItem`-`Style` you find.

Happy coding 
Tim
