### ISSUE TITLE
TextBox watermark opacity/color override

### ISSUE THREAD

**Issue by Waexu** [MahApps/MahApps.Metro#3868]
It would be great to have an ability to override watermark style. I found out that watermark changing it's opacity to 0.2 on focus using storyboard, not style. I didn't find the way to override this storyboard (any suggestions??). I'm my case old  people are working with software and they barely can read watermarks despite that I've made it larger.

**Comment by timunie** [comment]
Hi @Waexu ,

as far as I can see there is no "easy" way to change the `Storyboard`, which comes by WPF intern performance reasons. You need to override the entire `ControlTemplate`. 

Here is the original `Template` / `Style`: github.com/MahApps/MahApps.Metro/blob/develop/src/MahApps.Metro/Styles/Controls.TextBox.xaml

And here is the original `Storyboard`:https://github.com/MahApps/MahApps.Metro/blob/07dcfc57a22bfe3fd684cb54593f27532387b178/src/MahApps.Metro/Styles/Controls.Shared.xaml#L17

Happy coding 
Tim

**Comment by Waexu** [comment]
> Hi @Waexu ,
> 
> as far as I can see there is no "easy" way to change the `Storyboard`, which comes by WPF intern performance reasons. You need to override the entire `ControlTemplate`.
> 
> Here is the original `Template` / `Style`: github.com/MahApps/MahApps.Metro/blob/develop/src/MahApps.Metro/Styles/Controls.TextBox.xaml
> 
> And here is the original `Storyboard`:
> 
> https://github.com/MahApps/MahApps.Metro/blob/07dcfc57a22bfe3fd684cb54593f27532387b178/src/MahApps.Metro/Styles/Controls.Shared.xaml#L17
> 
> Happy coding
> Tim

Thank you for a reply! 
Do you have any plans for customizing opacity values? I'm asking because I need to decide what to do: override ControlTemplate or just wait. Also I can implement it by myself however I never did commits to open source projects so if there are any special rules - let me know. Thank you

**Comment by timunie** [comment]
Hi @Waexu ,
I was not able to get it customized using `DynamicResource` or `Binding`, so I think it is tricky to implement customization here (I only found a workaround: https://stackoverflow.com/questions/2186933/wpf-animation-binding-to-the-to-attribute-of-storyboard-animation ). 

You are welcome to contribute to MahApps, but I have one point for you. There are Templates for `Bugs`, `Feature Requests` and `Pull Requests`. Next time, please fill them out. see: https://github.com/MahApps/MahApps.Metro/wiki/Contributing

Maybe some might find a solution for it, so you can leave this issue open.
