### ISSUE TITLE
Controls.AnimatedSingleRowTabControl.xaml not found

### ISSUE THREAD

**Issue by realivanjx** [MahApps/MahApps.Metro#3870]
Hi,

I am trying to apply animated single row tab control style based on this page https://mahapps.com/docs/styles/tabcontrol
However when i tried to run the app it says the style is not found. It works on mahapps older version (like < 2). 

![image](https://user-images.githubusercontent.com/12814796/86424594-2dde7680-bd0d-11ea-8bc5-854f8742389b.png)

Versions:
![image](https://user-images.githubusercontent.com/12814796/86424662-549cad00-bd0d-11ea-95b7-18e87741ce39.png)

Any help is appreciated.

Thanks

**Comment by timunie** [comment]
Hi @realivanjx 

I think the `Style` just moved and was renamed, so it is no longer necessary to import this in App.xaml.
See: https://github.com/MahApps/MahApps.Metro/blob/d57ce8abb94e7603351d87c86a0999743551389f/src/MahApps.Metro/Styles/Controls.TabControl.xaml#L506 

The documentation will be updated one by one. sorry for the inconviniece

Happy coding, 
Tim

**Comment by realivanjx** [comment]
Thanks @timunie 

Here is the final result:

```
<TabControl
        Style="{StaticResource MahApps.Styles.TabControl.AnimatedSingleRow}">
        ...tab items here
    </TabControl>
```
