### ISSUE TITLE
Installing MahApps.Metro.Resources does not create Resources folder in project on .NET Core 3.1

### ISSUE THREAD

**Issue by fracampit** [MahApps/MahApps.Metro#3871]
## Describe the bug

The Resources folder is not created automatically when you install the nuget package "MahApps.Metro.Resources" on a .NET Core 3.1. WPF project.

## Steps to reproduce

- Create new .NET Core 3.1 WPF project
- Install MahApps.Metro.Resources nuget package

## Expected behavior

- Install MahApps.Metro.Resources
- Resources folder is automatically created in project

## Actual behavior

- Install MahApps.Metro.Resources
- Resources folder is NOT automatically created in project

## Environment

```
MahApps.Metro version: v2.1.1
Windows build number: Win10 1909 [Version 10.0.18363.0]
Visual Studio: 2019 16.6.3 / JetBrains Rider 2020.1.3 (I have tested on both and get the same results)
Target Framework: .Net Core 3.1
```

## Screenshots

Install package:
![image](https://user-images.githubusercontent.com/18556389/86533524-b570e480-bec9-11ea-97f3-1232b861acee.png)

No Resources folder is created:
![image](https://user-images.githubusercontent.com/18556389/86533537-d5a0a380-bec9-11ea-9fe0-4f0480045313.png)

Now the same in .NET Framework works fine:
Install package:
![image](https://user-images.githubusercontent.com/18556389/86533569-fff26100-bec9-11ea-880a-64dc301e68ee.png)

Resources folder is created:
![image](https://user-images.githubusercontent.com/18556389/86533606-30d29600-beca-11ea-9997-ffc0d0641a41.png)

Finally, notice how installing MahApps.Metro.Resources does NOT automatically install MahApps.Metro on .NET Core 3.1, but it does install MahApps.Metro on .NET Framework.
[I have tried installing MahApps.Metro.Resources after installing MahApps.Metro on .NET Core 3.1, but it still does not create the Resources folder]

**Comment by punker76** [comment]
@fracampit I'm sorry, but the MahApps.Metro.Resources repo and NuGet is obsolete and will no longer be updated. Please use the IconPacks (which you already use). Thx!

**Comment by fracampit** [comment]
I see, thank you very much for making that clear!
