### ISSUE TITLE
Theme Manager wont work with 2 Main windows on different (STA) Threads

### ISSUE THREAD

**Issue by johanneswanzek** [MahApps/MahApps.Metro#3872]
I have a Prism Application with a Bootstrapper and App.MainWindow (MetroWindow) running on MainThread and a seperate Login Window (also MetroWindow) running on sperate STA Thread to keep the UI responsive while Bootstrapper is running.

When switching the Theme in any situation the Application throws an exception: "The calling thread cannot access this object because a different thread owns it."

![image](https://user-images.githubusercontent.com/7391918/86593977-84aab100-bf96-11ea-93f6-4d73091e9118.png)

![image](https://user-images.githubusercontent.com/7391918/86594092-b3c12280-bf96-11ea-88ef-3a44149e3de5.png)

My assumption is that static Implementation and Event subscription from MetroWindow causes the Metro Window to crash when it does not belong to the Mainthread.

Thanks in advance,
Johannes

**Comment by punker76** [comment]
@johanneswanzek Please create and publish a sample app with your implementation of this situation. Thx!

**Comment by johanneswanzek** [comment]
Hello @punker76 Thanks for the fast response! :)

Please find my little Demo attached. I tried to keep it as simple as possible.

[MahAppsSTAThreadApp.zip](https://github.com/MahApps/MahApps.Metro/files/4879232/MahAppsSTAThreadApp.zip)

**Comment by punker76** [comment]
@johanneswanzek Thank you for the sample! This helped me to find the problem. 👍 

![mahapps_thread_dialogs](https://user-images.githubusercontent.com/658431/86741752-ec650880-c037-11ea-8745-ecdd987de71a.gif)
