### ISSUE TITLE
Expander Background not applied

### ISSUE THREAD

**Issue by enrico-padovani** [MahApps/MahApps.Metro#3879]
## Describe the bug

I'm in the process to upgrade MahApps from version 1.6.5 to version 2.1.1. I've an expander which has a custom background color set but it's not applied. This was working with version 1.6.5

## Steps to reproduce

Change a background color of an expander, whatever color you set It will not be displayed. The default color theme is always applied.

## Expected behavior

The color to change

## Actual behavior

The color does not change from the default style.

## Environment

```
MahApps.Metro version: v2.1.1
Windows build number: Win10 1909 [Version 10.0.18363.900]
Visual Studio: 2019 16.6.3
Target Framework: .Net v4.8
```

**Comment by punker76** [comment]
@enrico-padovani Which background are you want to change? The header or the content background? Can you post the Xaml of the expander? Thx

**Comment by enrico-padovani** [comment]
<Expander Background="Yellow"/>

**Comment by punker76** [comment]
@enrico-padovani Works for me...

```xaml
<Expander Margin="20"
          Height="100"
          Background="Yellow"
          mah:HeaderedControlHelper.HeaderBackground="OrangeRed">
</Expander>
```

with `xmlns:mah="http://metro.mahapps.com/winfx/xaml/controls"`

![mahapps_expander](https://user-images.githubusercontent.com/658431/87255953-5abe2680-c48f-11ea-992e-e097f82a9016.gif)

**Comment by enrico-padovani** [comment]
I did not know about `mah:HeaderedControlHelper.HeaderBackground`. In the older version of the library I just used to set the header background color.

So, thanks for helping out!

Cheers,
Enrico
