### ISSUE TITLE
High contrast theme is not getting applied 

### ISSUE THREAD

**Issue by sibille** [MahApps/MahApps.Metro#3880]
We want to add the possibility to use the Default Windows Theme in the Apps generated by Windows Template Studio and support High contrast. 
 
Adding the sync option was quite straight forward, but we're having trouble implementing High Contrast support. You can find a repro project at https://github.com/sibille/WTS.WPF.HighContrastSupport. Are we missing something? 
 
Problems we are facing:
 1. When selecting "Windows default", I can see a the following theme getting applied in the OnThemeChanged event 
`{DisplayName=Runtime #C400B7C3 (Light) HighContrast, Name=Light.Runtime_#C400B7C3, IsHighContrast=True, IsRuntimeGenerated=True}` but no colors do seem to change.
 

 2. When selecting Dark or Light the OnThemeChanged event does not get fired.

Other questions: 

 - Do we need to add a custom high contrast theme for Dark/Light High Contrast support ? 
 - Do we need to explicitly set the high contrast theme using `ThemeManager.Current.ChangeTheme`?

**Comment by batzen** [comment]
@sibille The themes you are providing in the sample app are not complete themes. 
They just contain a different `PrimaryAccentColor` thus they don't change all the colors loaded by the default generic theme.
The only reason your app does not loose all colors and stays at the Dark.Blue theme is that you merge two themes in your App.xaml. This causes the Light.Blue theme to be the current theme, but as you change the theme to one of your high contrast themes immediately on start the Light.Blue gets unloaded, Dark.Blue stays and your theme is used on top of that.

The reason why you don't get theme changed events when changing from dark to light is that you tell the `ThemeManager` to only sync high contrast and then call sync. As high contrast might not be enabled this just ends in a no-op call.
If you want to use fixed base colors you have to call `ThemeManager.Current.ChangeThemeBaseColor` ( in your case `ThemeManager.Current.ChangeThemeBaseColor(Application.Current, theme.ToString());`)

MahApps.Metro does not provide a high contrast theme out of the box as of now, i don't know if @punker76 plans to add some.
So currently you have to write your own ones. Contributing those to MahApps.Metro might be a good idea then. ;-)

**Comment by sibille** [comment]
Hi @batzen, 
 thanks for looking into this and your help.

> @sibille The themes you are providing in the sample app are not complete themes.
> They just contain a different PrimaryAccentColor thus they don't change all the colors loaded by the default generic theme.
> The only reason your app does not loose all colors and stays at the Dark.Blue theme is that you merge two themes in your App.xaml. This causes the Light.Blue theme to be the current theme, but as you change the theme to one of your high contrast themes immediately on start the Light.Blue gets unloaded, Dark.Blue stays and your theme is used on top of that.

Ok, I see! That makes sence.

I added some basic colors to the High Contrast themes and can see they get applied now when activating High Contrast and switching either to Dark or Light because I'm calling ` ThemeManager.Current.ChangeTheme(Application.Current, $"{theme}.Blue", IsHighContrastActive);
`  I tried to replace this call by `ThemeManager.Current.ChangeThemeBaseColor(Application.Current, theme.ToString());` which works fine with Dark and Light but doesn't apply high contrast themes.

I was expecting that if I had selected Dark Theme and activate High Contrast on my system the App would switch to High Contrast. I added a SyncTheme() call on OnUserPreferenceChanging event, but this doesn't trigger HighContrast neither.
Setting the theme on OnUserPreferenceChanging works, but not sure if this is the correct approach.

I feel like I'm missing something basic in the SyncTheme approach. Is there a sample or docs on this?

**Comment by sibille** [comment]
@punker76 , did you have the chance to look into this?
I just updated the repro app to the last version of MahApps but no changes. 
If I start the app in HC the HC theme is applied correctly now. But I expected that calling SyncTheme with ThemeSyncMode.SyncWithHighContrast to automatically change to High Contrast if I enable HC while the App is running. 
Is this assumption wrong or am I missing something in the code?

**Comment by batzen** [comment]
@sibille That's a bug in ControlzEx. Will have a look and fix it. I forgot some cases inside SyncTheme when i added high contrast support.

**Comment by batzen** [comment]
While fixing the issue i noticed that you named your HC themes "Dark.Blue" and "Light.Blue".
That causes issues in theme detection, which is another bug 😢, as theme names are supposed to be unique.

**Comment by batzen** [comment]
I fixed all issues and will push the changes now.
UnitTests will follow during the next few days.
To try the fixes in your app you will have to use the ControlzEx version from its CI nuget feed.

**Comment by sibille** [comment]
Works great! Thanks @batzen

**Comment by sibille** [comment]
@punker76, @batzen do you think this fix can be included in version 2.3.0?

**Comment by punker76** [comment]
@sibille This will be fixed with the next release of ControlzEx.
/cc @batzen

**Comment by punker76** [comment]
@sibille ControlzEx v4.4.0 is out now https://github.com/ControlzEx/ControlzEx/releases

**Comment by sibille** [comment]
Thank you both!
