### ISSUE TITLE
TabControl: allow for some tweak without to redefine the full style

### ISSUE THREAD

**Issue by Evangelink** [MahApps/MahApps.Metro#3882]
## Describe the feature

I am trying to mimic the style from Microsoft Money app, see following screenshot:

![image](https://user-images.githubusercontent.com/11340282/87520201-ee0b7d80-c682-11ea-80e9-7d017aec2637.png)

So I'd like to be able to change the width of the underline bar, it's height and also the spacing between the text and the underline and I couldn't find any easy way to do so except from doing a copy paste of the style and doing some manual tweaks. 

I know that you have to keep a line between how much customization you can allow but I think that some of the points could be made easy looking at the style definition.

I am not gonna lie, I am a little rusty with styling but I am happy to try and submit a PR once we have aligned on what makes sense and what doesn't.

**Comment by timunie** [comment]
Hi @Evangelink 
Have also a look at the IconPacksBrowser: https://github.com/MahApps/MahApps.Metro.IconPacks
The `Style` here might be close to the one you are looking for.

![image](https://user-images.githubusercontent.com/47110241/87523229-f9f93e80-c686-11ea-9b78-797c6c231e50.png)

Happy styling,
Tim

**Comment by punker76** [comment]
@Evangelink I think one helper could be to set also the MinWidth and MinHeight of the TabItem. We should keep an eye on the different Underline styles for the TabControl.

**Comment by Evangelink** [comment]
@timunie Interesting I totally forgot that the icon browser had a similar style and looking at the implementation I can see that I did WAY TOO complex xD

@punker76 What about adding tabcontrol helpers for:
- setting the "thickness" of the underline bar?
- setting the margin/padding of the bar?

Again I am not sure where the bar shall be between having helpers and having styles. Maybe the only thing I would have liked to see is some more advanced examples of how I could create some minimal custom style to do some few tweaks.

**Comment by Evangelink** [comment]
Thanks @punker76! Really grateful for all your work on this awesome lib!

**Comment by punker76** [comment]
@Evangelink Thx. A little bit late, but now it's done...

**Comment by Evangelink** [comment]
I disagree, if it was too late, I mean too urgent for me, I should have done it :). It's OSS, it's not like you are my freelancer :P
