### ISSUE TITLE
Potential bug with windows button alignment when increasing the title bar height

### ISSUE THREAD

**Issue by Evangelink** [MahApps/MahApps.Metro#3883]
I am playing with MahApps, trying to mimic a couple of windows application to try to get back on track with UI development and I am facing a little issue with the windows command buttons position. 

I am trying to do the following header style:

![image](https://user-images.githubusercontent.com/11340282/87525266-8ad11980-c689-11ea-9a58-a99a8172a33f.png)

I have set the `TitleBarHeight` property and also the `TitleTemplate` property but now the minimize, maximize and close buttons are vertically centered instead of being top aligned:

![image](https://user-images.githubusercontent.com/11340282/87525885-6590db00-c68a-11ea-99ee-bf9180b0da6a.png)

What's strange to me is that when I look at the `MetroWindow` style I can see that the `VerticalAlignment` is set to `Top`: https://github.com/MahApps/MahApps.Metro/blob/develop/src/MahApps.Metro/Themes/MetroWindow.xaml#L116

Is it a bug or am I missing something?

**Comment by punker76** [comment]
@Evangelink The thing is the binding to the TitleBarHeight and the vertical alignment of the window button commands. This here is a quick workaround for you, I'll take a look for a simpler change (when this here is not ok).

```xaml
<mah:MetroWindow.WindowButtonCommands>
    <mah:WindowButtonCommands VerticalAlignment="Top" Height="30" />
</mah:MetroWindow.WindowButtonCommands>
```

![image](https://user-images.githubusercontent.com/658431/87527770-e05af580-c68c-11ea-9981-24a036df4c17.png)

**Comment by Evangelink** [comment]
Hey thanks for the prompt answer! I feel dumb, I really didn't think of that...
