### ISSUE TITLE
Validation appears on top of all controls.

### ISSUE THREAD

**Issue by aBerna** [MahApps/MahApps.Metro#3884]
Hello,

The validation border and triangle is showing above of all controls in the window. In my case I'm using a custom alert control when it showin and a validation error occurs, the border and the triangle are shown above the alert control.

![image](https://user-images.githubusercontent.com/8634690/87574580-2e272c00-c694-11ea-88df-9105822e2fb5.png)

Can someone help me to solve this? The Panel.ZIndex property is not working.

Thanks.

**Comment by punker76** [comment]
@aBerna You can wrap your content with the control which validates inside an `AdornerDecorator`.

```xaml
<AdornerDecorator>
  <Grid>
    ...
  </Grid>
</AdornerDecorator>
```

**Comment by aBerna** [comment]
Great, it works!

Thank you for your help!
