### ISSUE TITLE
How to use same theme on pages as in main window? 

### ISSUE THREAD

**Issue by testniracun** [MahApps/MahApps.Metro#3885]
How to use same teme as in main window also in different pages and elements on page?

I have application which has button, to change theme on main window. 
So when I change theme on main window I want to update teme also on all subpages.

Should i change page on load method and apply new theme on new page load out?
But there is problem, with updating already loaded up pages.

**Comment by punker76** [comment]
@testniracun If you use straight forward the resources from MahApps the you don't need extra work to get this. Which version of MahApps are you using? Can you publich some code or the app? Thx

**Comment by testniracun** [comment]
I use nuget v2.1.1 
My main window is hamburger 2 example, with few modifications like tool tip on buttons. 
https://mahapps.com/docs/controls/HamburgerMenu

For sub page I use navigator as in example which opens my custom "Views"/Pages.

I added on main form button at top which changes theme on main page, and it works okay for main page.  
`<mah:MetroWindow.RightWindowCommands>
   <mah:WindowCommands>
      <Button x:Name="DarkLightTheme" Click="DarkLightTheme_Click" ToolTip="Switch between dark/light theme">
         <iconPacks:Zondicons Width="22" Height="22" Kind="YinYang" />
      </Button>
   </mah:WindowCommands>
</mah:MetroWindow.RightWindowCommands>`

And event (I have static array "THEME_COLOR", of strings in which there are theme names - Blue, Green, etc. So each time i press button new theme is applied):

`private void DarkLightTheme_Click(object sender, RoutedEventArgs e)
        {
            try
            {                
                _themeType++;
                if (_themeType > 45)
                {
                    _themeType = 0;
                }
                int theme = (_themeType / 2);
                int darkLight = _themeType % 2;
                //ThemeManager.Current.ChangeTheme(this, "Light.Blue");
                ThemeString = $"{THEME_MODE[darkLight]}.{THEME_COLOR[theme]}";
                ThemeManager.Current.ChangeTheme(this, ThemeString);
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex.Message);
            }
        }`

When I change theme I save new theme string in public main form variable "ThemeString"
So when I load new page I can access this variable and set theme in sub pages.

Pages constructor:

`private void Page_Loaded(object sender, RoutedEventArgs e)
{
            Debug.WriteLine("Script page loaded");
            // apply theme
            ThemeManager.Current.ChangeTheme(this, ((MainWindow)Application.Current.MainWindow).ThemeString);
}`

This only works for new pages, I can not update already opened page.
So I'm wondering if there is any better way, to do this.
Page code. (if I reload page theme is applied correctly. so should I trigger reload event in navigator when I press change theme button?) 

`<Page x:Class="PanTiltToolMahApps.Views.DiscoveryPage"
      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
      xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
      xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
      xmlns:iconPacks="http://metro.mahapps.com/winfx/xaml/iconpacks"
      xmlns:local="clr-namespace:PanTiltToolMahApps.Views"
      xmlns:classes="clr-namespace:PanTiltToolMahApps.Classes"
      Style="{DynamicResource PageStyle}"
      mc:Ignorable="d" 
      MinHeight="300"
      MinWidth="400"
      Title="DiscoveryPage"
      Loaded="Page_Loaded"
      Unloaded="Page_Unloaded">
    <Grid>
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="*"></ColumnDefinition>
            <ColumnDefinition Width="*"></ColumnDefinition>
        </Grid.ColumnDefinitions>
        <Grid.RowDefinitions>
            <RowDefinition Height="40"></RowDefinition>
            <RowDefinition Height="40"></RowDefinition>
            <RowDefinition Height="*"></RowDefinition>
            <RowDefinition Height="10"></RowDefinition>
        </Grid.RowDefinitions>
        <TextBlock Text="Discovery"
                   TextAlignment="Center"
                   Grid.Column="0"
                   Grid.ColumnSpan="2"
                   Grid.Row="0"
                   FontSize="26"
                   Background="{DynamicResource MahApps.Brushes.Accent2}" />
        <TextBlock Text="Detected Devices:" 
                   FontSize="20"
                   Grid.Column="0"
                   Grid.ColumnSpan="1" 
                   Grid.Row="1"
                   Padding="10 10 0 0" />
 </Grid>
</Page>`

**Comment by batzen** [comment]
That's because you change the theme for `this`. You should instead change the theme for `Application.Current`. By doing so you can remove all other theme changes.

**Comment by testniracun** [comment]
Thank you for help, now is working fine.

I still have one more question.
MahApps don't have TreeView control?
I'm using default control, and on left of TreeViewItem element I have picture.
So depending on dark or light theme I should change picture, to white or black.
Can I somehow access event theme change on my page, so I can rebuild tree view, so it will have correct icons? 

`<TreeView x:Name="SearchDevices" 
                  ItemsSource="{Binding Items}" 
                  Background="LightCyan"
                  Margin="10" 
                  Grid.Column="0" 
                  Grid.ColumnSpan="1" 
                  Grid.Row="1" 
                  Grid.RowSpan="1" 
                  HorizontalContentAlignment="Stretch" 
                  HorizontalAlignment="Stretch"
                  SelectedItemChanged="SearchDeviceTree_SelectedItemChanged"
                  MouseDoubleClick="SearchDevices_MouseDoubleClick" >
            <TreeView.ItemContainerStyle>
                <Style TargetType="{x:Type TreeViewItem}">
                    <Setter Property="IsExpanded" Value="true" />
                </Style>
            </TreeView.ItemContainerStyle>
            <TreeView.ItemTemplate>
                <HierarchicalDataTemplate ItemsSource="{Binding Children}">
                    <StackPanel Orientation="Horizontal">
                        <Image Width="20" Margin="3" 
                                    Source="{Binding ImageName,
                                        Converter={x:Static local:HeaderToImageConverter.Instance}}" />
                        <TextBlock VerticalAlignment="Center" Text="{Binding Name}" />
                    </StackPanel>
                </HierarchicalDataTemplate>
            </TreeView.ItemTemplate>
        </TreeView>`

I have PNG pictures ethernet.png and ethernetW.png for black or white version of same picture. And convert method, depending on theme, choses correct PNG image. HeaderToImageConverter class: 

[ValueConversion(typeof(TVD_ViewItem.DirectoryItemType), typeof(BitmapImage))]
public class HeaderToImageConverter : IValueConverter
{
        public static HeaderToImageConverter Instance = new HeaderToImageConverter();
        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            if(((MainWindow)Application.Current.MainWindow).ThemeString.Contains("Dark"))
            {
                value += "W";
            }
            return new BitmapImage(new Uri($"pack://application:,,,/Assets/PNG/{value}.png"));
        }
        public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            throw new NotImplementedException();
        }
    }

**Comment by timunie** [comment]
Hi @testniracun 

first of all if you have questions about the usage please use gitter instead of creating issues. https://gitter.im/MahApps/MahApps.Metro 

There are several ways to do this. If the icons are just one color I would use the great [IconPacks](https://github.com/MahApps/MahApps.Metro.IconPacks) or a custom Path. If it must be an image I would create 2 Resources by adding `x:Key` and then change the Resource in the theme changed event. 

Happy coding
Tim
