### ISSUE TITLE
MathConverter should either implement convert back or return Binding.UnsetValue

### ISSUE THREAD

**Issue by timunie** [MahApps/MahApps.Metro#3888]
## Describe the problem
I binded a `Slider` to a value which I converted using the `MathMultiplyConverter`. it was shown correctly but never reported the changed value back to the source. It even did not throw any `Exception` so I didn't knew it would not work until I had a look into the source of MahApps

## Soulution option 1
All `MathConvter` should implement a `ConvertBack`-Method. Example: `value+parameter=result` will be converted back to `result-parameter=value`.

## Solution option 2
All `MathConvter` should return `Binding.UnsetValue` indestead of `Binding.DoNothing`. So if the user tries to implement a twoway bindig he will get notified that it is not supported. 

Happy coding
Tim

**Comment by punker76** [comment]
@timunie Solution 2 is bad, because a converter should never raise an exception.

**Comment by timunie** [comment]
@punker76 thank you for the prompt answer. I didn't knew this because I often saw this in other Converters in some tutorials. 
Maybe we can at least write a message into the debugging output?

**Comment by timunie** [comment]
Changed to return `Binding.UnsetValue`. if you tell me your favorite solution I will make a PR on it. If you want to stick with the current implementation, please close this feature request.
