### ISSUE TITLE
Update from 1.6.5 to 2.1.1 wasted my application!

### ISSUE THREAD

**Issue by Marko97IT** [MahApps/MahApps.Metro#3890]
MahApps.Metro;component/Styles/Colors.xaml NOT FOUND
MahApps.Metro;component/Styles/Accents/Blue.xaml NOT FOUND
MahApps.Metro;component/Styles/Accents/BaseDark.xaml NOT FOUND
MahApps.Metro;component/Styles/Controls.AnimatedSingleRowTabControl.xaml NOT FOUND
Property Controls:ControlsHelper.HeaderFontSize NOT FOUND

Also the documentation is not updated.

**Comment by timunie** [comment]
Hi @Marko97IT 

please have a look here: https://mahapps.com/docs/guides/migration-to-v2.0

... and yes it takes some time to migrate, but it is worth the effort. 
... and yes documentation is still in progress. Please keep in mind that this is a free time project, so it can only be done in spare free time. 

Happy coding anyway
Tim

**Comment by Marko97IT** [comment]
Issue is now resolved! Thanks a lot.

**Comment by timunie** [comment]
@Marko97IT you are welcome. If you have any other issues while migrating you can also ask us on gitter: https://gitter.im/MahApps/MahApps.Metro
