### ISSUE TITLE
It's not possible  to override ListBoxItem triggered brushes

### ISSUE THREAD

**Issue by punker76** [MahApps/MahApps.Metro#3900]
## Describe the bug

This issue results from #3899 

It's not possible  to override ListBoxItem triggered brushes via own style like

```xaml
<Style TargetType="{x:Type ListBoxItem}" BasedOn="{StaticResource MahApps.Styles.ListBoxItem}">
    <Setter Property="Controls:ItemHelper.HoverBackgroundBrush" Value="{DynamicResource MahApps.Brushes.Gray}" />
    <Setter Property="Controls:ItemHelper.HoverSelectedBackgroundBrush" Value="{DynamicResource MahApps.Brushes.Gray1}" />
    <Style.Triggers>
        <EventTrigger RoutedEvent="PreviewMouseRightButtonDown">
            <BeginStoryboard x:Name="BeginStoryboard_IsPressed">
                <Storyboard>
                    <ObjectAnimationUsingKeyFrames Duration="0:0:0"
                                                   Storyboard.TargetProperty="Background">
                        <!--
                            Note: It's not possible to use DynamicResource inside a Storyboard.
                            So use StaticResource or a static Brush instead.
                         -->
                        <DiscreteObjectKeyFrame KeyTime="0:0:0" Value="{x:Static Brushes.Red}" />
                    </ObjectAnimationUsingKeyFrames>
                </Storyboard>
            </BeginStoryboard>
        </EventTrigger>
        <EventTrigger RoutedEvent="PreviewMouseRightButtonUp">
            <RemoveStoryboard BeginStoryboardName="BeginStoryboard_IsPressed" />
        </EventTrigger>
    </Style.Triggers>
</Style>
```

## Expected behavior

The Background of the ListBoxItem should be changed if the user clicks the right mouse button.

![mahapps_listbox_hover_better](https://user-images.githubusercontent.com/658431/89527099-12bdc580-d7e9-11ea-8db4-0d6e37a836ad.gif)

## Actual behavior

Nothing happens.

## Environment

```
MahApps.Metro version: v2.2.0
Target Framework: .Net Core 3.1 (v4.5.2, v4.7.2)
```

## Screenshots

![mahapps_listbox_hover](https://user-images.githubusercontent.com/658431/89527077-0b96b780-d7e9-11ea-953f-130a3c43c1b6.gif)

**Comment by PhyxionNL** [comment]
@punker76, these changes break if you're using an alternation index background on the container:

`<Style.Triggers>
            <Trigger Property="ItemsControl.AlternationIndex" Value="0">
                <Setter Property="Background" Value="{DynamicResource MahApps.Brushes.Gray10}" />
            </Trigger>
        </Style.Triggers>`

It's now no longer possible to set a normal background for these while retaining the hover backgrounds etc.
