### ISSUE TITLE
Make Window movable while dialog is shown

### ISSUE THREAD

**Issue by Symbai** [MahApps/MahApps.Metro#3909]
## Describe the feature

I don't know if this is a bug or a missing feature but the window should be movable while a dialog is shown (currently its only resizable then). Imagine there is a very long progress dialog. We don't want the user to do anything else within the application, but he should be allowed to move the window to another desktop (multi monitor) or out of his way.

There two ways of how this can be implemented:

- Hardcoded that click throughs are acceptable but only handled on click and drag
- Give each element in the window title a new property which make them clickable in dialogs (then, also the minimize/maximize could remain active. As well as custom buttons)

First way would be the easiest and fastest. Second way avoids the situation where this becomes requested in the future anyway. I leave the choice to you.

**Comment by punker76** [comment]
@Symbai This is already available with the `ShowDialogsOverTitleBar` property on the `MetroWindow`. If you set this to false then you can move the window together with an open dialog.

**Comment by Symbai** [comment]
But it also mean the user can close the window by clicking the X then (which is what I don't want)?

**Comment by punker76** [comment]
@Symbai This can be handled by the dialog settings and the `OwnerCanCloseWithDialog` property which can be set for each dialog.

https://github.com/MahApps/MahApps.Metro/blob/698e4d6fcf81016b05405be13bf66a573057ce4f/src/MahApps.Metro/Controls/Dialogs/MetroDialogSettings.cs#L37-L40

**Comment by Symbai** [comment]
Ah okay, then I will close this issue
