### ISSUE TITLE
Flipview to have styleable attributes like other controls

### ISSUE THREAD

**Issue by Christopher-Andrews** [MahApps/MahApps.Metro#3910]
Hi,

At the moment the Flipview controls banner and arrow colours are connected to the app theme and are only changed by setting either light or dark for the entire app itself. I propose it to be style-able via tags similar to other controls e.g.
```
    <mah:MetroWindow.Resources>
        <ResourceDictionary>
            <Style x:Key="{x:Type Flip}"
       TargetType="{x:Type ToolTip}">
                <Setter Property="Background" Value="#d9e1e9" />
                <Setter Property="Foreground" Value="#000000" />
            </Style>
        </ResourceDictionary>
    </mah:MetroWindow.Resources>
```
This would allow the control to use accent colours etc, maybe even variable sizes and make it a little more flexible overall.

**Comment by timunie** [comment]
I would like to jump in this Hacktoberfest

My idea is:
- [ ] Add a Style for the Buttons
- [ ] Add a DataTemplate for the Buttons Contents
- [ ] Add a DataTemplate for the Banner

Anything missing?
