### ISSUE TITLE
DatePicker CalendarStyle is not working

### ISSUE THREAD

**Issue by michaelmairegger** [MahApps/MahApps.Metro#3911]
Setting the CalendarStyle of DatePicker does not work. The default calendar style gets applied. I expeced that MahApps.Styles.Calendar.DateTimePicker should be applies. But if I set the CalendarStyle to that value nothing happens

**Comment by punker76** [comment]
@michaelmairegger That's weird, because this style is already set by the default style

https://github.com/MahApps/MahApps.Metro/blob/698e4d6fcf81016b05405be13bf66a573057ce4f/src/MahApps.Metro/Themes/DateTimePicker.xaml#L514

Which MahApps version are you using?

**Comment by michaelmairegger** [comment]
@punker76 the version 2.2.0

**Comment by timunie** [comment]
@michaelmairegger just for clarification: Are you talking about this control? 
https://github.com/MahApps/MahApps.Metro/blob/develop/src/MahApps.Metro/Styles/Controls.DatePicker.xaml

**Comment by michaelmairegger** [comment]
@timunie correct

**Comment by timunie** [comment]
@michaelmairegger I tried it in the demoapp and it also works there. the only difference in the style is the `Border` around the `Calendar`. 

If your problem still persists I would like to ask you to provide a short sample showing your issue.

**Comment by michaelmairegger** [comment]
@timunie I will try it again and check if I have missed something.

**Comment by punker76** [comment]
@michaelmairegger Hi Michael, is it now working?

**Comment by michaelmairegger** [comment]
@punker76 actually I have not tested. Have put on my TODO list for next week

**Comment by michaelmairegger** [comment]
@punker76 The issue have been resolved. I applied the CalendarStyle only on the target type DatePicker instead of adding a new Style based on DateTimePicker.
