### ISSUE TITLE
DropDownButton should allow for group styles

### ISSUE THREAD

**Issue by AKruimink** [MahApps/MahApps.Metro#3913]
## Describe the feature
Currently it seems like the DropDownButton does not allow for grouping items together (as for example seen in the ComboBox).
The snipped below is an implementation of it in the Demo App, that should work, but doesnt seem like it does.

```xaml

            <Controls:DropDownButton Margin="5"
                                     Content="Genres"
                                     DisplayMemberPath="Name"
                                     ItemsSource="{Binding Source={x:Static models:SampleData.Genres}}">
                <Controls:DropDownButton.GroupStyle>
                    <GroupStyle>
                        <GroupStyle.HeaderTemplate>
                            <DataTemplate>
                                <TextBlock Text="{Binding Path=Name}"/>
                            </DataTemplate>
                        </GroupStyle.HeaderTemplate>
                    </GroupStyle>
                </Controls:DropDownButton.GroupStyle>
            </Controls:DropDownButton>
```

**Comment by AKruimink** [comment]
Might actualy be a bug report instead?

**Comment by timunie** [comment]
I had a look in the source and it seems like this control uses `ContextMenu` to display the items. I think this needs to be changed, so it is for me a feature request and not a bug. 
But this also enables `SubMenus` 🤔 So I am not sure if both can be supported.

**Comment by AKruimink** [comment]
Thanks for looking into it @timunie , had alook around as well, seems like you might be correct, not sure if in that case it's worth in that case, as it would add a bunch of stuff that probably souldnt be part of the button (unless there is some way around it, or uncase anyone else is alright with it).

The only upside that it would create is a clearer list selection, nothing a  Combobox can't handle, except that you won't have to deal with selected items (which was my initial reasoning)

**Comment by timunie** [comment]
Maybe the `SplitButton` can be used for your need case?

**Comment by AKruimink** [comment]
I had a look at the spitbutton yesterday, didn't offer much more to me then the dropdown button already did.
The optimal controller would have been the combobox, was it not for the hassle it introduces when trying to deselect an item from the viewmodel, thats wat got me to use the DropDownButton, i assumed it would offer support for headers (which i was wrong in).

That being said, i did some resorting of my list and it looks alot cleaner now even without the headers, and don't think would should change wat the DropDown is right now, and try to make it into a controller that it isn't/isn't suppoe to be.
