### ISSUE TITLE
MetroWindow doesn't show Close, Min & Max button

### ISSUE THREAD

**Issue by AndreasReitberger** [MahApps/MahApps.Metro#3918]
## Describe the bug

I created my main window like shown below.

```
<Controls:MetroWindow x:Class="WpfFramework.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WpfFramework"
        
        xmlns:Controls="clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro"
        xmlns:iconPacks="http://metro.mahapps.com/winfx/xaml/iconpacks"
        xmlns:localization="clr-namespace:WpfFramework.Resources.Localization"
        xmlns:CSMS="clr-namespace:WpfFramework"
        xmlns:converters="clr-namespace:WpfFramework.Converters"
        xmlns:resources="clr-namespace:WpfFramework.Properties"
        xmlns:behaviors="http://schemas.microsoft.com/xaml/behaviors"            
        Style="{StaticResource DefaultWindow}"  
                 
        mc:Ignorable="d" d:DataContext="{d:DesignInstance CSMS:MainWindow}"
        SaveWindowPosition="True"
        Title="{x:Static localization:StaticStrings.ProductName}" Height="720" Width="1450" MinWidth="900"
        Closing="MetroWindowMain_Closing" StateChanged="MetroWindowMain_StateChanged"
                      >
    <Controls:MetroWindow.RightWindowCommands>
        <Controls:WindowCommands>
            <StackPanel Orientation="Horizontal">
                <!-- Some buttons here -->
            </StackPanel>
        </Controls:WindowCommands>
    </Controls:MetroWindow.RightWindowCommands>
    <Controls:MetroWindow.LeftWindowCommands>
        <Controls:WindowCommands>
            <StackPanel Orientation="Horizontal">
                <!-- Some buttons here -->
            </StackPanel>
        </Controls:WindowCommands>
    </Controls:MetroWindow.LeftWindowCommands>
    <Controls:MetroWindow.WindowButtonCommands>
        <Controls:WindowButtonCommands Template="{DynamicResource MahApps.Metro.Templates.WindowButtonCommands.Win10}" />
    </Controls:MetroWindow.WindowButtonCommands>
  </Controls:MetroWindow>
```

The refreneced `Style` looks like that.

    <Style x:Key="DefaultWindow" TargetType="{x:Type mahAppsControls:MetroWindow}" BasedOn="{StaticResource MahApps.Styles.MetroWindow.Clean}" >
        <Setter Property="IsWindowDraggable" Value="True"/>
        <Setter Property="ShowCloseButton" Value="True"/>
        <Setter Property="ShowMaxRestoreButton" Value="True"/>
        <Setter Property="ShowMinButton" Value="True"/>
        <Setter Property="IsCloseButtonEnabled" Value="True"/>
        
        <Setter Property="TitleForeground" Value="{DynamicResource MahApps.Brushes.Gray3}" />
        
    </Style>

I also tried to set the `Properties `directly in the XAML of the `MetroWindow`, however no changes.

## Expected behavior

Show the Close, Min, Max button (same code works finde with Mahapps 1.6)

## Actual behavior

No buttons are shown
![image](https://user-images.githubusercontent.com/2952443/92751020-e701a280-f387-11ea-9415-8b3461dc1974.png)

## Environment

MahApps.Metro version: v2.2.0
Windows build number: Win10 1909 [Version 10.0.18363.836]
Visual Studio: 2019 16.7.3
Target Framework:  v4.7.2)

**Comment by timunie** [comment]
Hi @AndreasReitberger 

this looks pretty strange. Any chance to create a short sample that shows your issue or provide access to the source? 

Happy coding
Tim

**Comment by AndreasReitberger** [comment]
Hi @timunie 
Sure, please find the example here:
https://github.com/AndreasReitberger/MahappsMetroWindowNoCloseButton

I stripped down my project to only the `MetroWindow`. Let me know if you need any additional infos.

**Comment by punker76** [comment]
@AndreasReitberger Thx for your sample. It should be fixed now (see my PR).

https://github.com/AndreasReitberger/MahappsMetroWindowNoCloseButton/pull/1

**Comment by AndreasReitberger** [comment]
@punker76 
thank you so much for that quick help :) I'll close the issue now.
Best,
Andreas
