### ISSUE TITLE
Colorpicker

### ISSUE THREAD

**Issue by TripleNico** [MahApps/MahApps.Metro#3920]
It would be awesome if someone could created (or already has created) a color picker in the MahApps style. Including some color converters Getting and Settings a Color or brush. Currently i'm using one from Xceed WPF Toolkit which is nice but it stands out that it's not the same theme as the rest of the application.

**Comment by timunie** [comment]
Hi @TripleNico ,

I have one in the pipeline. Right now I am waiting for the feedback of @punker76 . See #3710 

A preview is also available, but you need to build the dll on your own: https://github.com/timunie/TimsWpfControls

Happy coding
Tim

**Comment by TripleNico** [comment]
Ah, that's really awesome! I will follow this and hopefully it get's implemented. Until then i will stick with our current version but it's exited to know that this control will be added in the feature! Keep up the good work!
