### ISSUE TITLE
Cannot input "-" and "+" sign in TextBox control

### ISSUE THREAD

**Issue by RoboIndustries** [MahApps/MahApps.Metro#3921]
Applied the MahApps.Metro theme to my current WPF application. Found that all WPF TextBox controls cannot input the "+" and "-" signs anymore. There were lots of textbox controls in my application where the user input some digital numbers with the "-" sign to indicator minus numbers, now they are all "positive" only since the textbox under MahApps.Metro theme won't allow the textbox to take the "-" sign. 

Is there a way to restore the WPF textbox control to remove this kind of restriction?

Thanks

**Comment by AKruimink** [comment]
Could you show a little sample how you handle the TextBox input? as i don't have any issues using symbols, TextBox just returns a string so should be more about the way you parse it.
