### ISSUE TITLE
Binding updates for buttons from TextBoxHelper.ButtonCommand

### ISSUE THREAD

**Issue by Rerago** [MahApps/MahApps.Metro#3924]
## Describe the feature

I would like the bindings to be updated when clicking on the buttons created by "TextBoxHelper.ButtonCommand".

## Additional context

Good afternoon,

i have a question about the behaviour of ButtonCommand in a textbox and the update of bindings.

Let us assume you have a textbox and a button. If the user enters something into the textbox and then clicks on the button to perform the action the button will have access to the value of the text property (which is assigned by the binding of the ViewModel). Since TextBox.Text has the default binding update to "LostFocus".

If you want to replace the following constellation with "TextBoxHelper.ButtonCommand" there is a problem. Clicking on the button does not create a LostFocus (which I had expected or hoped for) and the binding is not updated. This has the consequence that you can't access the property in the command.

Of course you could work around this as follows:

- switch from "LostFocus" to "PropertyChanged"
- pass text as parameter (which does not work in every case if the command is already used elsewhere)
- Force update in every command you want to use

Couldn't we maybe add "UpdateSource" here:

https://github.com/MahApps/MahApps.Metro/blob/develop/src/MahApps.Metro/Controls/Helper/TextBoxHelper.cs#L895

Because I think that would reflect the expected behavior again? Or am I wrong?

## Some example code

If you enter text into the TextBox and then click on the created button the MessageBox is empty. If you click on the dummy button before (through the LostFocus) the MessageBox shows the content of the TextBox.

```
<mah:MetroWindow x:Class="WpfApp1.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:mah="http://metro.mahapps.com/winfx/xaml/controls" xmlns:wpfapp1="clr-namespace:WpfApp1"
        Title="MainWindow"
        Width="400"
        SizeToContent="Height">
    <mah:MetroWindow.DataContext>
        <wpfapp1:SampleViewModel />
    </mah:MetroWindow.DataContext>

    <StackPanel>
        <!-- TextBox with button -->
        <TextBox Text="{Binding Path=TestString}" 
                 mah:TextBoxHelper.ButtonContent="s" 
                 mah:TextBoxHelper.ButtonCommand="{Binding Path=TestMessageCommand, Mode=OneWay}" 
                 Style="{DynamicResource MahApps.Styles.TextBox.Button}" />

        <!-- Dummy button to lose the focus  -->
        <Button>Click here to lose Focus</Button>
    </StackPanel>
</mah:MetroWindow>
```

```
public class SampleViewModel : BindableBase
    {
        private string _title;

        public string TestString
        {
            get { return _title; }
            set { SetProperty(ref _title, value); }
        }

        private ICommand _testMessageCommand;
        public ICommand TestMessageCommand => _testMessageCommand ?? (_testMessageCommand = new RelayCommand<object>((x) => MessageBox.Show(TestString), (x) => true));
    }
```

**Comment by timunie** [comment]
Hi @Rerago 

I think your problem is this line: 
https://github.com/MahApps/MahApps.Metro/blob/698e4d6fcf81016b05405be13bf66a573057ce4f/src/MahApps.Metro/Styles/Controls.TextBox.xaml#L139 

You may try to copy the entire `ControlTemplate` and set `Focusable=True`. This may cause other problems, so be carefully. 

Also please have a look into the Demo App. There is an example for `Controls:TextBoxHelper.ButtonCommandParameter`
https://github.com/MahApps/MahApps.Metro/blob/698e4d6fcf81016b05405be13bf66a573057ce4f/src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/TextExamples.xaml#L150-L155 

Happy coding
Tim

**Comment by Rerago** [comment]
Hi @timunie 

I think that:

> Focusable="False"

is totally ok at this point. But I think that we need an ".UpdateSource();" before executing the command. This should not break and should lead to an expected result.

Rerago

**Comment by Rerago** [comment]
If @punker76 finds my idea in order I like to do a PR.

But it would be nice if he says something about it. Not that I make the work unnecessary :).

But I just did it now (hope its fine^^):

https://github.com/MahApps/MahApps.Metro/pull/3925/files

Unfortunately I do not know which one would be the corresponding property in the rich text box. But the others are built in correctly.

**Comment by Rerago** [comment]
So I have reworked my pull request again. I checked the other property and this one has the DefaultUpdateSourceTrigger not on LostFocus. And therefore no change is necessary here.

So the change is very small now.
