### ISSUE TITLE
Border Brush Behavior Issues

### ISSUE THREAD

**Issue by RickStrahl** [MahApps/MahApps.Metro#3926]
I've recently run into issues with the GlowBrush behavior for Windows and had to turn this off ([bug report in Markdown Monster here](https://github.com/RickStrahl/MarkdownMonster/issues/704)) and so had to use my main window with just a border to offset it on like colored backgrounds.

The default behavior for this based on the active theme is actually quite good and that's what I ended up using.

However, before I arrived there I played around with setting the BorderBrush, InactiveBorderBrush and, BorderWidth  and noticed that the color choices in BorderBrush are not actually respected.

Observed behavior (all with GlowBrush not set):

* BorderBrush set to a value (like Yellow)
Border stays at the default theme color when the Window is active. When deactivated the border shows yellow. Never shows yellow when active.

* BorderBrush set and/or NonActiveBorderBrush set
Active Border is not affected (ie. theme default). Inactive window displays NonActiveBorderBrush.

* Only NonActiveBorderBrush set
same as previous

* No BorderBrush set
Default them colors are used. Dark theme uses a silverish grey color. Color appears to be the same for active and inactive

The first two are the questionable scenarios with BorderBrush not having an effect.

Other weirdness: If I use Visual Studio's Live Edit features running in debug mode and I change the BorderBrush to a different color then it starts showing. But it won't work with the original form loading or even after reactivating. Apparently changing the BorderBrush after initial startup exhibits the correct behavior.

Looks like assigning the border brush in code in `Loaded()` works:

```cs
// in Window.Loaded
BorderBrush = new SolidColorBrush(System.Windows.Media.Colors.Green);
```

Kind of a nitpicky issue, especially since the default theme behavior is **actually working correctly**. However, unexpected to not see the border color respected when assigned as part of the `<window>` header.

**Comment by timunie** [comment]
I tried to reproduce it in the demo app. Seems like `MetroWindow` ignores the `BorderBrush` when one has a `GlowBrush` set. If I remove the `GlowBrush` it works, also in MM.

**Comment by RickStrahl** [comment]
@timunie that's not what I'm seeing at least in MM. 

There's a difference between border when active and inactive. Make sure you check that. Border color works on the inactive window, but not when the window is active.

**Comment by timunie** [comment]
@RickStrahl as long as the `NonActiveGlowBrush` is set the `Border` ignores the `BorderBrush` and uses the  `NonActiveGlowBrush`. In my environment also for MM. 

This was just meant as an additional information, I have no issue with it in my App.

**Comment by RickStrahl** [comment]
Again, I'm not setting the `NonActiveGlowBrush` and there is no GlowBrush styling, so it's not on by default either.  You can easily enough try this in MM by setting only borderwidth and color for both active and non active border widths.

**Comment by punker76** [comment]
@RickStrahl I‘ll look for it. It‘s maybe a fault by the active/inactive trigger.

**Comment by timunie** [comment]
Hi @RickStrahl ,
you got me wrong. **I** did change this in MarkdownMonster as a testing purpose and then this is what **I** observed. I did not want to blame you for anything :smiley: 

I am sure @punker76 will find a solution

**Comment by punker76** [comment]
@RickStrahl Hey Rick, I found what's going wrong... You override some brushes here

https://github.com/RickStrahl/MarkdownMonster/blob/682b357bc19658c6c318151c39faa8c55db295e7/MarkdownMonster/_Classes/Configuration/mmApp.cs#L615-L634

So setting a BorderBrish in main window has no effect!

**Comment by RickStrahl** [comment]
🤦‍♂️

Duh... sorry - guess that explains why it works for inactive window, and not the active window.
