### ISSUE TITLE
TimePicker reset on clock/popup click

### ISSUE THREAD

**Issue by TheCamel** [MahApps/MahApps.Metro#3931]
Each click on the clock to open the dropdown send a new value as 'null', something wrong ? Time is a "DateTime?" property
						
<MahApps:TimePicker SelectedDateTime="{Binding Time}"
											SelectedTimeFormat="Short" 
											PickerVisibility="HourMinute" HandVisibility="HourMinute"
											 />

was working with the 1.6.5 version

**Comment by timunie** [comment]
Hi @TheCamel ,

which version of MahApps do you use? It would be the best, if you use the Bug-Template next time. 

If you can share a sample App it might also be useful.

Thank you & Happy coding 
Tim

**Comment by TheCamel** [comment]
sorry for the issue template, version 2.2.0
btw,
why do you change from TimeSpan to DateTime ? 

I cannot compile the latest source of Demo (all errors related to time control or textboxhelper)
MahApps.Metro is build ok

and also had unexplained troubles with themes when i try to update from 1.6.5 to 220 :-)
sorry have to go back to 165 because application in production

**Comment by timunie** [comment]
@TheCamel please read this: https://mahapps.com/docs/guides/migration-to-v2.0 . I think it explains much about what is going on with `Theming`.

**Comment by TheCamel** [comment]
Thanks, i allready seens that one, but had trouble with the
		<ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Themes/Dark.Blue.xaml" />
i can't find out...
but don't care i go back to 165

**Comment by TheCamel** [comment]
I achieve to build the lastest source and you have the same problem with the time control (latest in the right panel ) in the demo application: click the clock and change the time, validate; it is ok
re click the clock, control gets empty and red, display an error
bye

**Comment by timunie** [comment]
Hi @TheCamel ,

thank you for this updated comment :+1:. I can now reproduce this issue with the latest demo. 
Seems like it comes from using `AM` and `PM` notation. `TimeSpan.TryParse` cannot accept this. I have an idea and will try to provide a fix for that. 

Happy coding
Tim

**Comment by TheCamel** [comment]
Hi @timunie ,
you're welcome, it seams it exist since 2.0
See u

**Comment by TheCamel** [comment]
hi, by the way I find it unfortunate that the control manages a DateTime and not a TimeSpan; the most logical unit of time in base is an "integer / long"; i don't want to manage a string or a date to store a time / hour for scheduling; this will lock me to the 165, do i have to create a feature request?

**Comment by punker76** [comment]
@TheCamel This was changed by this PR #3254 (original #2763 ) . So both classes , TimePicker and DateTimePicker, use `DateTime?` which is also used by the WPF DatePicker. One way is to use a value converter which stores the `DateTime?` as TimeSpan and back. Or you just use the `DateTime?` value.

**Comment by timunie** [comment]
@TheCamel why did you close this issue? There is definitive an issue with storing / converting the value. The possible solution (see #3932 ) is not implemented yet.

**Comment by TheCamel** [comment]
sorry, it's a mistake. I let you manage the status when done :-)
