### ISSUE TITLE
Can ShowProgressAsync be delayed?

### ISSUE THREAD

**Issue by sszeller** [MahApps/MahApps.Metro#3933]
I have some Tasks that can have highly variable durations (e.g. file uploads whose duration depends on the number of files ), so there is no need to show a progress banner for those cases completing quickly. Having a progress meter for these cases actually slows down access to the UI.

So, I've tried using Task.WhenAny() with a delay task, and I'm not able to get the indeterminate progress meter to clear. I am using Metro 1.6.5 in a C# WPF desktop app.

I did look in the demo source code and nothing immediately jumps out at me.

Is there a way to get the desired functionality?

**Comment by timunie** [comment]
Hi @sszeller 

next time please use gitter ( https://gitter.im/MahApps/MahApps.Metro ) for questions like these first as this is neither an issue nor a feature request. Anyway as it is currently Hacktoberfest 2020 I created an example for you and others here: https://github.com/timunie/MahApps.Metro.Examples/tree/master/src/MahApps.Metro.Examples/DelayShowProgressExample

Happy coding 
Tim

**Comment by sszeller** [comment]
Hi Tim,

Thanks, I appreciate the update and the example.

I hadn’t realized there was a separate site for questions, so thanks for pointing that out.

Best,
Scott

**Comment by timunie** [comment]
Hi Scott,

if your issue is solved please remember to close it. 

Thank you and happy coding
Tim

**Comment by sszeller** [comment]
Thanks @timunie, that is exactly what I was looking for.
