### ISSUE TITLE
Selected HamburgerMenu Item cannot be clicked again

### ISSUE THREAD

**Issue by ansabkhaliq** [MahApps/MahApps.Metro#3934]
## Describe the bug

Hi, I recently upgraded the MahApp nuget package from 1.6.0 to 2.2.0 and since then I started facing an issue with Hamburger Menu Item Selection. 

Say, there are 5 pages listed in the hamburger menu and each of these pages have child-pages which can be navigated to. Now I click page1 the first time, the hamburger menu will register the event and change the page as well and display me the tiles for navigating to the child page. If I navigated to the child page and clicked on Page1 again (already selected the first time i clicked it) in Hamburger Menu, the hamburger used to register that event and took me to Page1 again. (that is, out of the child page). This behavior was there in v1.6.0

However now, if I click again on the page1, it is selected in the hamburger menu and I will be navigated to Page1. Now, if I navigate to child pages and tried to click on the page1 menu item in the hamburger menu again. It will not register the event. I have to then click on page2, or someother other item in the hamburger menu to actually navigate away from the child page. 

This started happening since i upgraded to 2.2.0 and as you can see this behavior is totally different from what was int the 1.6.0 version.

I was hoping if you can advise me as to how to achieve the old behavior again.

## Expected behavior

Clicking on already selected Hamburger Menu item should reload the page again.

## Actual behavior

Clicking on already selected Hamburger Menu item does nothing. It doesn't even fire the "ItemClick" event

## Environment

```
MahApps.Metro version: v2.0.0
Windows build number: Win10 1909 [Version 10.0.18363.836]
Visual Studio: 2017 15.9.27
Target Framework: v4.5.2
```

## Screenshots
This screenshot just give an example of what I mean. 
If you require further clarification, please let me know.

![HamburgerIssue](https://user-images.githubusercontent.com/70895588/95299955-37f2b100-08ca-11eb-82c1-1683105b19c3.png)

**Comment by timunie** [comment]
@ansabkhaliq it would be very useful if you can create a sample on github and link it here. Then we can have a deeper look into it and maybe provide a solution. 

Happy coding
Tim

**Comment by ansabkhaliq** [comment]
@timunie Hi, 
As requested, I have created two small demo Apps. One if made with MahApps v1.6.0, while the other is with MahApps v2.2.0.

The links are:
MahApps v1.6.0: [https://github.com/ansabkhaliq/DemoAppV1.6](url)
MahApps v2.2.0: [https://github.com/ansabkhaliq/DemoAppV2.0](url)


I left some comments on the empty pages, to explain some of the behavior. If you require any other clarification, please feel free to ask.

Thank you for your help
Ansab

**Comment by AKruimink** [comment]
Someone please correct me if im wrong, but im pretty sure this is due to the removal of the MouseUp event handler in #3444 

Where before the list view would listen for both MouseUp events and a selectionChanged, in 2.0.0 it only listens for the selection changed event, which doesn't occure when the item is already selected (which would be the case here). 

As for how to fix this, im not sure, except using your own event handler on the click even and handling it yourself, which isn't great. Another option might be re-adding it but with a new dependency, potentialy a bool that can be set to listen for button clicks as well? im not really certain,. Maybe @timunie  or @punker76 have a better idea

**Comment by ansabkhaliq** [comment]
@timunie Hi,
Thanks for sharing the solution and the PR. It solves the issue at hand. I didn't stumble upon this MouseUp event being removed at some point.

@AKruimink 
Thanks for giving that info, I know now why it stopped working after the upgrade and @timunie provided a solution by introducing a trigger, which will work for my project.

Once again, thanks for a quick fix guys. I will close the request. :)
