### ISSUE TITLE
NumericUpDown shouldn't be able to be left empty

### ISSUE THREAD

**Issue by mtemmen-ww** [MahApps/MahApps.Metro#3936]
## Describe the feature

When you delete the value in a NumericUpDown control a message will appear telling the user the value '' couldn't be converted. That's fine, but in my opinion the control should go back to its previous value as soon as its losing focus and if the textbox is still empty. It already does that when you replace a number by a space, but not when the string is completely empty.
Alternatively it could go back to a user defined default value.

**Comment by DMtsdt** [comment]
I encountered it as well but haven't really looked into it. It has been mentioned before in regards to Validation handling if I remember correctly.
I agree that it would be nice to be able to use FallbackValue or TargetNullValue out of the box.
My quick and dirty solution is to use a nullable in the bound property and return the backing field if the setter value is null.

**Comment by aruyc** [comment]
When we select all value of NumericUpDown then press ESC then same type of issue is there. It do not fire value change event so original value is as it is(same as last value) and string shows in NumericUpDown is Empty. Please suggest step to avoid this.
