### ISSUE TITLE
How to references MahApps.Metro theme in custom FrameworkElements

### ISSUE THREAD

**Issue by sphet** [MahApps/MahApps.Metro#3938]
Sorry if I am obtuse or a newbie, but I have a host of FrameworkElements that are rendered as part of my custom controls. How do I go about using elements of the theme for brushes - for example, I want to use the same theming as a tab for a custom thumb-object in my track control. My motivation is to be forward compatible with future themes.

**Comment by timunie** [comment]
Hi @sphet ,

I am not sure what your need case is. If you want to set the foreground here is an Example: 
```xaml
<Button Foreground="{DynamicResource MahApps.Brushes.Accent}" />
```

Please note: If you have more questions about the usage please ask on gitter first: https://gitter.im/MahApps/MahApps.Metro 

Thank you and happy coding 
Tim
