### ISSUE TITLE
MetroAnimatedTabControl clip negative margin control

### ISSUE THREAD

**Issue by jysong74** [MahApps/MahApps.Metro#3939]
When resize window, negative margin stack control in MetroAnimatedTabControl get clipped.

## Expected behavior
Negative margin control placed in MetroTabItem of MetroAnimatedTabControl always correctly visible.

## Actual behavior
When resize window, negative margin control get clipped.

## Environment
MahApps.Metro version: v2.2.0
Windows build number: Win10 2004 [Version 10.0.19041.572]
Visual Studio: 2017 15.9.25
Target Framework: .Net Framework (v4.6.1)

## Screen Shot

Correctly rendered shot
![normal](https://user-images.githubusercontent.com/45708118/96553584-53a97e80-12f0-11eb-9b6a-9b0aca11727e.JPG)

Clipped Control shot
![clipped](https://user-images.githubusercontent.com/45708118/96553630-66bc4e80-12f0-11eb-9142-ae62705823bd.JPG)

## xaml file(unnecessary code removed)

```xaml
 <Controls:MetroAnimatedTabControl
                        Controls:TabControlHelper.Underlined="SelectedTabItem"  Background="{x:Null}" Padding="0" 
                        Margin="0,0,5,5">

                        <Controls:MetroTabItem Header="탐색종목" Controls:HeaderedControlHelper.HeaderFontSize="16" ClipToBounds="False">
                            <Grid x:Name="Grid_TradeStock" ClipToBounds="False" >
                                <StackPanel Height="26" Margin="0,-23,0,0" Orientation="Horizontal" HorizontalAlignment="Right" Grid.ZIndex="1" VerticalAlignment="Top" ScrollViewer.VerticalScrollBarVisibility="Disabled">   

                                </StackPanel>                              
                            </Grid>
                        </Controls:MetroTabItem>

</Controls:MetroAnimatedTabControl>
```

**Comment by punker76** [comment]
@jysong74 Can you give us a sample and screenshot? Thx.

**Comment by jysong74** [comment]
> @jysong74 Can you give us a sample and screenshot? Thx.

Updated issue report. Thank you!

**Comment by punker76** [comment]
@jysong74 Try to set `ClipToBounds="False"` also to the TabControl.

**Comment by jysong74** [comment]
> @jysong74 Try to set `ClipToBounds="False"` also to the TabControl.
ClipToBounds="False" to the TabControl also not work. When I tested MetroTabControl. It has no clipping problem.

**Comment by punker76** [comment]
@jysong74 So, is it now working with setting the ClipTobounds?

```
<Controls:MetroAnimatedTabControl
  Controls:TabControlHelper.Underlined="SelectedTabItem"
  ClipToBounds="False"
  Background="{x:Null}"
  Padding="0" 
  Margin="0,0,5,5">

  <Controls:MetroTabItem Header="탐색종목" Controls:HeaderedControlHelper.HeaderFontSize="16" ClipToBounds="False">
    <Grid x:Name="Grid_TradeStock" ClipToBounds="False" >
      <StackPanel Height="26" Margin="0,-23,0,0" Orientation="Horizontal" HorizontalAlignment="Right" Grid.ZIndex="1" VerticalAlignment="Top" ScrollViewer.VerticalScrollBarVisibility="Disabled">

      </StackPanel>                              
    </Grid>
  </Controls:MetroTabItem>

</Controls:MetroAnimatedTabControl>
```

**Comment by jysong74** [comment]
> ```
> Controls:MetroAnimatedTabControl
> ```

Not working. I also set ClipToBounds to all parent controls. 
But MetroTablControl has negative margin child works fine.

**Comment by punker76** [comment]
@jysong74 Then this must be something other. Doing this is not a common way to display something outside a TabItem, because of such clip to bounds stuff. And we do only styling to the TabControl, IMO this is not a MahApps bug. If you still think this is a MahApps related issue the please create a short app which shows exactly this issue, push it to GitHub and we can look in to it. Thx 🙏
