### ISSUE TITLE
How Change ToggleSwitch OffBrush To White

### ISSUE THREAD

**Issue by visualczm** [MahApps/MahApps.Metro#3940]
MahApps Version 2.0
How Change ToggleSwitch OffBrush To White

![image](https://user-images.githubusercontent.com/22953065/96587014-5c13b080-1314-11eb-90a5-f57a9f68af5f.png)

Thank you !!!

**Comment by timunie** [comment]
Hi @visualczm 

you can try to override the needed `Brushes`:
https://github.com/MahApps/MahApps.Metro/blob/363f79c9a5cc9bd605f41821b26f23350e1c2e0c/src/MahApps.Metro/Styles/Themes/Theme.Template.xaml#L483-L515

**Comment by visualczm** [comment]
Hi @timunie 
Thanks for your help!
but can be set by properties?  
or like this

`<Style x:Key="Custom.ToggleSwitch.Win10"
               BasedOn="{StaticResource MahApps.Styles.ToggleSwitch}"
                TargetType="{x:Type Controls:ToggleSwitch}">
            ...
        </Style>`

i hope ...

**Comment by timunie** [comment]
Hi @visualczm 

currently not. If you want it by `Style` I think you need to override the entire `ControlTemplate`. 

If you want to change the `Brush` globally you would do this in your `App.xaml`
```xaml
<Application [...]>
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <!--  Accent and AppTheme setting  -->
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Themes/Light.Blue.xaml" />
            </ResourceDictionary.MergedDictionaries>

            <!-- Do your override here -->
            <SolidColorBrush x:Key="MahApps.Brushes.ToggleSwitch.FillOff" Color="White" />

        </ResourceDictionary>
    </Application.Resources>
</Application>
```

You can also place this in any "subcontrol" you like, like `MetroWindow`, `UserControl` or `Statusbar`. All of them have their own `Resources`- Section, so then the `Brush` will only apply in this scope, i.E.:

```xaml 
<StatusBar [...]>
    <StatusBar.Resources>

            <!-- Do your override here -->
            <SolidColorBrush x:Key="MahApps.Brushes.ToggleSwitch.FillOff" Color="White" />

    </StatusBar.Resources>
</StatusBar>
```

PS: You can also ask questions on gitter: https://gitter.im/MahApps/MahApps.Metro 

Happy coding
Tim

**Comment by visualczm** [comment]
@timunie 
Thank you for your help
good job
