### ISSUE TITLE
Popup error in textbox is not displayed if textbox is placed in Flyout

### ISSUE THREAD

**Issue by omllmo** [MahApps/MahApps.Metro#3943]
Popup error in textbox is not displayed if textbox is placed in Flyout

**Comment by omllmo** [comment]
Environment
MahApps.Metro version: v2.2.0
Visual Studio: 2019 16.7.5
Target Framework: .Net Framework (v4.7)

**Comment by punker76** [comment]
@omllmo Please provide a sample or a code snippet. Thx

**Comment by omllmo** [comment]
The error message appears: 
<Grid>
	<TextBox Text="{Binding Number, ValidatesOnDataErrors=True, Mode=TwoWay,UpdateSourceTrigger=PropertyChanged}"/>
 </Grid>

**Comment by omllmo** [comment]
The error message appears:
<Grid>
     <TextBox Text="{Binding Number, ValidatesOnDataErrors=True, Mode=TwoWay,UpdateSourceTrigger=PropertyChanged}"/>
</Grid>

No error message appears:
<Grid>
  <controls:Flyout>
     <TextBox Text="{Binding Number, ValidatesOnDataErrors=True, Mode=TwoWay,UpdateSourceTrigger=PropertyChanged}"/>
  </controls:Flyout>
</Grid>

**Comment by omllmo** [comment]
The error message appears:
'<Grid>
    <TextBox Text="{Binding Number, ValidatesOnDataErrors=True, Mode=TwoWay,UpdateSourceTrigger=PropertyChanged}"/>
</Grid>'

No error message appears:
'<Grid>
  <controls:Flyout>
     <TextBox Text="{Binding Number, ValidatesOnDataErrors=True, Mode=TwoWay,UpdateSourceTrigger=PropertyChanged}"/>
  </controls:Flyout>
</Grid>'

**Comment by timunie** [comment]
Hi @omllmo 

please try to surround your `TextBox` with an `AdornerDecorator` like in the sample App: 
https://github.com/MahApps/MahApps.Metro/blob/85612908fffd071ed58affb389dcb0b8efa7d900/src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleWindows/FlyoutDemo.xaml#L423-L430

Happy coding 
Tim

**Comment by timunie** [comment]
Hi @omllmo 
I was wrong. The Popup does not open inside the `Flyout`, even not in the demo. Sorry. I hope we find a solution for this. 

Happy coding 
Tim
