### ISSUE TITLE
How to apply a glowing effect to a window

### ISSUE THREAD

**Issue by Xaalek** [MahApps/MahApps.Metro#3951]
When I start your example, I don't have a glowing effect on the window but on your screenshot there is a glowing effect. I would like to know how to apply this glowing effect on my window

My window :
![image](https://user-images.githubusercontent.com/54487782/97155502-c180fa80-1775-11eb-8a2e-71eede07f96e.png)

Your window :
![image](https://user-images.githubusercontent.com/54487782/97155614-eb3a2180-1775-11eb-8438-43ed77f5e348.png)

**Comment by punker76** [comment]
@Xaalek Just set the `GlowBrush` instead the `BorderBrush` of the window.

**Comment by Xaalek** [comment]
Thank you, I find the documentation about Windows 
https://mahapps.com/docs/controls/metrowindow
