### ISSUE TITLE
Setting ResizeMode to NoResize removes minimize to taskbar button

### ISSUE THREAD

**Issue by DannyDS** [MahApps/MahApps.Metro#3952]
Setting a windows property to  ResizeMode="NoResize"  removes both the minimize and full screen button from the windows title bar.

Under a normal themed window these buttons are still visible and the Minimize button still works as it should.

**Comment by punker76** [comment]
@DannyDS `ResizeMode="NoResize"` on a normal window does the same...

without MahApps

![2020-10-27_21h14_21](https://user-images.githubusercontent.com/658431/97357241-bf17c100-1899-11eb-97cf-35712f348982.png)

with MahApps

![2020-10-27_21h16_07](https://user-images.githubusercontent.com/658431/97357260-c4750b80-1899-11eb-9494-490a2c5ed826.png)

**Comment by DannyDS** [comment]
Sorry my mistake i meant when `ResizeMode="CanMinimize"`

Without MahApps
![Without MahApps](https://user-images.githubusercontent.com/6506579/97409683-f2883900-18f5-11eb-9aa3-0bc0068b2bfa.png)

With MahApps
![With MahApps](https://user-images.githubusercontent.com/6506579/97409705-fae07400-18f5-11eb-8e5a-b3835515a3aa.png)

**Comment by punker76** [comment]
@DannyDS Nope...

![image](https://user-images.githubusercontent.com/658431/97410142-fb313d00-18fe-11eb-982e-19b2382dcb61.png)

Which MahApps version are you using?

**Comment by DannyDS** [comment]
Version 2.3.1 
.Net 4.7.2

**Comment by punker76** [comment]
@DannyDS Please provide your Xaml of the window.
