### ISSUE TITLE
Mah metro not exist even when reinstall

### ISSUE THREAD

**Issue by letuan710** [MahApps/MahApps.Metro#3953]
## Describe the bug
![image](https://user-images.githubusercontent.com/46086222/97345434-a7056900-18bc-11eb-8ea4-9da24b4c8631.png)
I have a problem when running project in my laptop.
I try to reinstall by "Install-Package MahApps.Metro"
but it still have this problem 
![image](https://user-images.githubusercontent.com/46086222/97345792-1b400c80-18bd-11eb-9300-0e4a29afc85d.png)
could any one please help me

## Environment

```
MahApps.Metro version: v2.3.1
Windows build number: Win10 1909 [Version 10.0.18363.836]
Visual Studio: 2019 16.7.7
Target Framework: .Net Framework 4.8 
```

**Comment by punker76** [comment]
@letuan710 Are you trying to update the project from an old MahApps version to the new version?

**Comment by letuan710** [comment]
No. I just open the project and the xaml file. But it has this error, so I try to fix it by update to MahApps new version but it still has error

**Comment by punker76** [comment]
@letuan710 Before you start your solution, can you try to delete all bin and obj folders? Sometimes VS doesn't update all dependencies correctly. Then try to rebuild everything. It looks like that this is an VS issue.

**Comment by punker76** [comment]
@letuan710 Any news?

**Comment by letuan710** [comment]
I think you are right? It may be because of something else because I reinstall window but it not working but it's working on another laptop so I think It may be because of something else
