### ISSUE TITLE
View gets created multiple times when using navigation and DataTemplates

### ISSUE THREAD

**Issue by sszeller** [MahApps/MahApps.Metro#3959]
## Describe the bug

I am using DataTemplates to instantiate views when an underlying viewmodel is navigated to. This is creating duplicate views and thus duplicate event handlers, both handlers taking the same action and leading to potentially nondeterministic results. It is certainly possible that I'm misunderstanding something, but I've used similar navigation elsewhere

## Steps to reproduce

1. Build [sample code repo](https://github.com/sszeller/DoubleView.git) and run the sample code. Note the following in the Output window:

Creating MainView

2. Click on the Bug hamburger menu item, and note the following in the Output window:

Navigating to MahAppsMetroHamburgerMenuNavigation.ViewModels.BugsViewModel
Creating MainView
Creating BugsView
Unloading MainView
Unloading MainView

3. Click on the User hamburger menu item, and note the following in the Output window:

Navigating to MahAppsMetroHamburgerMenuNavigation.ViewModels.UserViewModel
Navigating to MahAppsMetroHamburgerMenuNavigation.ViewModels.UserViewModel
Creating BugsView
Creating UserView

Note that event handlers are being fired twice for each navigation due to two copies of MainView having been created. No doubt, the other views would do likewise if they had handlers.

## Expected behavior

A single view is created

## Actual behavior

Duplicate views are created, leading to multiple event handlers being fired when the appropriate event is signaled

## Environment

```
MahApps.Metro version: v2.3.1
Windows build number: Win10 (Version: 10.0.19041 Build 19041)
Visual Studio: 2019 16.7.6
Target Framework: .Net Framework v4.6.1
```

**Comment by punker76** [comment]
@sszeller The problem of the double loading content was the usage of the TransitioningContentControl which uses 2 ContentPresenter internally.

So I changed your sample to use an attached property for the Frame to set an animation for the navigation.

https://github.com/sszeller/DoubleView/pull/1

I will change my code-samples navigation sample to this too.

If you have any question then ping me. Thx
