### ISSUE TITLE
Version 2.3.3 - Can not open .exe file 'The assembly with display name 'MahApps.Metro' failed to load in the 'Load' binding context of the AppDomain with ID 1

### ISSUE THREAD

**Issue by matiaso11** [MahApps/MahApps.Metro#3962]
## Describe the bug
Everything works fine while Run app from VS. Problem occurre while run release .exe file manually.

.NET Framework 4.7.2
MahApps.Metro 2.3.3 (checked also on 2.0.0)

`Managed Debugging Assistant 'BindingFailure' : 'The assembly with display name 'MahApps.Metro' failed to load in the 'Load' binding context of the AppDomain with ID 1. The cause of the failure was: System.IO.FileNotFoundException: Could not load file or assembly 'MahApps.Metro, Version=2.0.0.0, Culture=neutral, PublicKeyToken=51482d6f650b2b3f' or one of its dependencies. The system cannot find the file specified.'`

## Steps to reproduce

1. Build WPF app with MahApps.Metro
2. Run exe file manually
3. Exception Thrown

## Expected behavior

.exe file should run

## Actual behavior

Exception tTown

## Environment

```
.NET Framework 4.7.2
MahApps.Metro 2.3.3 (checked also on 2.0.0)
Visual Studio: 2019 16.7.6
```

Thank you for help.

**Comment by punker76** [comment]
@matiaso11 Does this happen with a raw WPF app with MahApps, or with your special app? Does all dll exists at the same place as the executable (ControlzEx, MahApps, Behavior)?

**Comment by punker76** [comment]
@matiaso11 Any news? I've tested this with a complete new project, added MahApps (latest version) and all necessary resources and the used the MetroWindow, but can not reproduce this issue.

**Comment by punker76** [comment]
I close this for now. If you still have trouble with this issue then let us know. Thank you! 🙏
