### ISSUE TITLE
Make DropDownButton looks like default Mahapps button

### ISSUE THREAD

**Issue by GWawrzeniecki** [MahApps/MahApps.Metro#3968]
Hello
How can I change style/appearance of DropDownButton to looks like a button?
I have tried changing styles but every style looks different from that button on the following image.
![obraz](https://user-images.githubusercontent.com/23010883/99251411-971edc00-280d-11eb-8a65-29ffef8a99c1.png)
And how can I change a margin in each menu item? Because in each menu item in DropDownButton there is a space on the left and right side.

**Comment by punker76** [comment]
@GWawrzeniecki Here is a short example of a custom DropDownButton. The Menu item style can be changed if you set the ItemContainerStyle.

```
            <mah:DropDownButton Margin="5"
                                BorderThickness="0"
                                Padding="0"
                                BorderBrush="{DynamicResource MahApps.Brushes.Button.Border}"
                                ButtonStyle="{DynamicResource MahApps.Styles.Button}"
                                Content="Genres"
                                DisplayMemberPath="Name"
                                ItemsSource="{Binding Source={x:Static models:SampleData.Genres}}">
                <mah:DropDownButton.Icon>
                    <iconPacks:PackIconMaterial Margin="6 0" Kind="BookMusic" />
                </mah:DropDownButton.Icon>
            </mah:DropDownButton>
```

**Comment by GWawrzeniecki** [comment]
Awesome! Thank you very much
