### ISSUE TITLE
Memory leak in MahApps.Templates.ValidationError 

### ISSUE THREAD

**Issue by lipchev** [MahApps/MahApps.Metro#3969]
## Describe the bug

There is a minor memory leak with the default validation error template ([MahApps.Templates.ValidationError](https://github.com/MahApps/MahApps.Metro/blob/091132933e1db9dd38acae1737b8fd2589d060e9/src/MahApps.Metro/Styles/Controls.ValidationError.xaml#L16)): the binding `mode` on [this line](https://github.com/MahApps/MahApps.Metro/blob/091132933e1db9dd38acae1737b8fd2589d060e9/src/MahApps.Metro/Styles/Controls.ValidationError.xaml#L115) should be `OneTime`, as the underlying object ([System.Windows.Controls.ValidationError](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.validationerror?view=net-5.0)) does not implement INotifyPropertyChanged

## Steps to reproduce

Make the red validation popup appear by hovering over a control with a validation error. 

## Actual behavior

Observed the WPF binding leak is detected by the memory profiler

## Environment

```
MahApps.Metro version: v2.0.0
Windows build number: Win10 1909 [Version 10.0.18363.836]
Visual Studio: 2019 16.6.0
Target Framework: .Net Core 3.1 (v4.5.2, v4.7.2)
```

## Screenshots

![image](https://user-images.githubusercontent.com/5253184/99323424-e0594500-287a-11eb-9def-b89eb99d56a9.png)

**Comment by punker76** [comment]
@lipchev Thx for reporting this! If you want to fix this, then create a PR. I'll appreciate it! 👍
