### ISSUE TITLE
Memory leak created by the ColumnStylesHelper

### ISSUE THREAD

**Issue by lipchev** [MahApps/MahApps.Metro#3972]
## Describe the bug

The [DataGridColumnStylesHelperExtension](https://github.com/MahApps/MahApps.Metro/blob/c36f14da09ff70630d9e558a6f4564c34c176e9e/src/MahApps.Metro/Controls/Helper/DataGridColumnStylesHelperExtension.cs#L31) is [attached](https://github.com/MahApps/MahApps.Metro/blob/9f7344170ba5ed7c04775b597c6edcb4efb7bfcc/src/MahApps.Metro/Styles/Controls.DataGrid.xaml#L771) but never [detached](https://github.com/MahApps/MahApps.Metro/blob/c36f14da09ff70630d9e558a6f4564c34c176e9e/src/MahApps.Metro/Controls/Helper/DataGridHelper.cs#L627) from the grid, leaving a memory leak with the [Columns.CollectionChanged](https://github.com/MahApps/MahApps.Metro/blob/c36f14da09ff70630d9e558a6f4564c34c176e9e/src/MahApps.Metro/Controls/Helper/DataGridColumnStylesHelperExtension.cs#L41) handler. This causes the whole window that is hosting the data grid to remain in memory. 

## Steps to reproduce

1. [Replace](https://github.com/lipchev/MahApps.Metro/commit/47ae93fe438cf94019eefd94de42c669f28fd837) the albums list view in the CleanWindowDemo.xaml with an equivalent data grid  
2. Open and close the CleanWindowDemo

## Expected behavior

When the parent is unloaded the memory is liberated

## Actual behavior

The CleanWindowDemo window is retained in memory via the grid and the DataGridColumnStylesHelperExtension (see screenshot below)
Repeating the same steps with the `mah:DataGridHelper.ColumnStylesHelper="{x:Null}"` and the problem no longer occurs

## Environment

```
MahApps.Metro version: v2.0.0
Windows build number: Win10 1909 [Version 10.0.18363.836]
Visual Studio: 2019 16.6.0
Target Framework: .Net Core 3.1 (v4.5.2, v4.7.2)
```

## Screenshots

![image](https://user-images.githubusercontent.com/5253184/99867576-65b65f80-2bc3-11eb-92d5-82c13fa9eaa4.png)

**Comment by lipchev** [comment]
Ouch, I just realized there is only one instance of the DataGridColumnStylesHelperExtension markup extension ever created.

**Comment by punker76** [comment]
@lipchev Correct, for each DataGrid. But I still can not reproduce a memory leak with this extension.

**Comment by lipchev** [comment]
The attach is called per grid, but it only overrides the private DataGrid field

**Comment by lipchev** [comment]
Cool, I tried returning a new instance in the ProvideValue and the leak is gone (even without calling detach)
