### ISSUE TITLE
MetroAnimatedTab.SelectionChanged event fires whenever any control in any TabItem changes selection

### ISSUE THREAD

**Issue by Padanian** [MahApps/MahApps.Metro#3980]
## Describe the bug

MetroAnimatedTab.SelectionChanged shall change only when the active selected TabItem changes. The actual behaviour is such that the event is fired when any control within any child (e.g. a selectedItem in a Combobox in a Grid in a TabItem) changes selection.

## Steps to reproduce

Instantiate a MetroAnimatedTab with one TabItem, instatiate a Grid, and instatiate a Combobox within, having at least two items.
Changing the SelectedItem in the Combobox fires the MetroAnimatedTab.SelectionChanged

## Expected behavior

MetroAnimatedTab.SelectionChanged shall fire only when the selected TabItem changes

## Actual behavior

MetroAnimatedTab.SelectionChanged always fires for any changed selection 

## Environment

MahApps.Metro version: v2.3.4
Windows build number: Win10 20H2
Visual Studio: 2019 16.8.0
Target Framework: .Net fw, v4.8.2)

**Comment by punker76** [comment]
@Padanian Thx for reporting this issue, but it's not related to MahApps itself. If you use a normal TabControl then you will get exact the same result.

![tabcontrol_selectionchanged](https://user-images.githubusercontent.com/658431/100483396-1b6c3b80-30f9-11eb-8f40-ed625343fc5b.gif)

[WpfApp6.zip](https://github.com/MahApps/MahApps.Metro/files/5609493/WpfApp6.zip)
