### ISSUE TITLE
Visual Studio Designer doesn't render correctly

### ISSUE THREAD

**Issue by alan0428a** [MahApps/MahApps.Metro#4002]
## Describe the bug

I am following the QuickStart to get familiar with MahApps. However, my Visual Studio Designer seems like it doesn't render the window correctly. It still renders the original WPF window. But when I run and debug the project, it runs perfectly without any issue. 

I've uploaded the code to my [github](https://github.com/alan0428a/Mahapps).

## Steps to reproduce

1. Following the steps on QuickStart
2. See Visual Studio Designer

## Expected behavior

Visual Studio Designer should render MahApps window properly

## Actual behavior

Visual Studio Designer doesn't render properly

## Environment

```
MahApps.Metro version: v2.4.3
Windows build number: Win10 Enterprise 10.0.19042 Build 19042
Visual Studio: 2019 16.8.3 Professional
Target Framework: net5.0-windows
```

## Screenshots

Visual Studio Designer doesn't render properly
![image](https://user-images.githubusercontent.com/23318971/101737168-793c5280-3aff-11eb-8fd8-b38649d39c3a.png)
Run the project without any issue
![image](https://user-images.githubusercontent.com/23318971/101737253-94a75d80-3aff-11eb-8b30-2bfe4766ae7a.png)

**Comment by punker76** [comment]
@alan0428a This is a limitation of the Visual Studio Designer. It can not render the full window style (including caption).

**Comment by alan0428a** [comment]
Wow, thanks for the prompt reply!! (In 1 minute OMG)
Then what's the suggestion for the developers when using MetroWindow? Run the project directly and using Visual Studio Hot Reloading mechanism to modify XAML and check the result directly?

**Comment by punker76** [comment]
@alan0428a If this work, then yes. The inner Xaml content should be visible in the designer, it's only the caption and border which doesn't render.

**Comment by alan0428a** [comment]
Yes, the inner XAML content renders properly. Thanks for the clarification :)
