### ISSUE TITLE
Microsoft Ribbon Style

### ISSUE THREAD

**Issue by nathanhillyer** [MahApps/MahApps.Metro#401]
I was looking at some office 2013 screenshots and noticed the ribbon has a flat, metro look. Are there any plans to add a similar style to MahApps.Metro?

**Comment by bloritsch** [comment]
The ribbon style has some issues:

* It only works for "BaseLight" theme, and doesn't update for "BaseDark"
* Something happens with "BaseDark" where we see gradients on the control where they weren't there for "BaseLight".

Unfortunately, my modifications are on a private network where it's a lot harder to get things off than they are to put on.  The basic coloring issues can be made to work for both "BaseLight" and "BaseDark" by making the following changes:

* Ribbon/Setters Background={DynamicResource WhiteBrush}
* Ribbon/Setters Foreground={DynamicResource BlackBrush}
* RibbonTab/Setters Background={DynamicResource WhiteBrush}
* RibbonTab/ControlTemplate/Grid.Background={DynamicResource Gray9Brush}
* RibbonTabHeader/Setter Background={DynamicResource WhiteBrush}
* RibbonTabHeader/IsSelected Trigger/Setter Background={DynamicResource GrayBrush9}
* RibbonTabHeader/IsSelected Trigger/Setter BorderBrush={DynamicResource GrayBrush7}
* RibbonTabHeader/MouseOver Trigger/Setter Background={DynamicResource GrayBrush10}
* RibbonTabHeader/MouseOver Trigger/Setter BorderBrush={DynamicResource GrayBrush8}

That fixes the coloring issues that don't match the rest of Mahapps.Metro.  Still looking for a fix to the gradients and the glass effect on the main menu button.
