### ISSUE TITLE
Powershell Multi-CustomDialog

### ISSUE THREAD

**Issue by leroy23** [MahApps/MahApps.Metro#4010]
Hello Guys,
I try to use Mahapps.metro on powershell.
Seems, work fine, but i don't understand how organize multiple customdialog.
I need to open some csv, and requesto for each to open a dialog for ask a selection (combobox) and the user must click "ok" for confirm their selected item.

Now this is my simple code:

```ps
$cdcmbHeaders.ItemsSource = SelectHeaders($inpath)
$cdpath.Text = $inpath
[MahApps.Metro.Controls.Dialogs.DialogManager]::ShowMetroDialogAsync($Form, $CustomDialog, $settings)
```

Now, i have this code for call from click button:
```ps
function CreateCSV() {
$inpath = $cdpath.Text
    $addCSV = New-Object Itempxi
    $addCSV.lid = $observableCollection.Count + 1
    $addCSV.xpath = $inpath;
   $addCSV.headers = $cdcmbHeaders.ItemsSource;
$CSVname = [string]$addCSV.lid + "_" + $inpath.Substring($inpath.LastIndexOf("\") + 1)
    $addCSV.CSVname = $CSVname
    $selectedItem = $cdcmbHeaders.SelectedValue

    if ($cdcmbHeaders.SelectedValue -notlike $null) {
        $addCSV.selheader = $selectedItem
        $observableCollection.Add($addCSV)
    }
    else {
        Write-Host "CSV not import!"
    }
    $CustomDialog.RequestCloseAsync() 
}
```

Obviusly powershell return me this error:
```
Exception calling "ShowMetroDialogAsync" with "#number of CSV#" argument(s): "The provided dialog is already visible in the specified window."
```

I don't know how organize the dialogs, i read some documantation and some code, but was in c#. Powershell seems work differently.
I need only that every dialogs can show only when the previous one is closed. Thanks!

**Comment by batzen** [comment]
@leroy23 Could you post a full repro for this issue?

**Comment by leroy23** [comment]
> @leroy23 Could you post a full repro for this issue?

[https://github.com/leroy23/CSV-test.git](url)
(sorry, i'm new in github) miss only image file of CSV and DLL

**Comment by batzen** [comment]
I am not able to reproduce the issue when updating your script to the latest MahApps.Metro version.
Could you try to update and test it yourself?

Here is the code that worked for me:
[CSV-test.zip](https://github.com/MahApps/MahApps.Metro/files/5739327/CSV-test.zip)
