### ISSUE TITLE
Where do I find the full documentation?

### ISSUE THREAD

**Issue by Matix-Media** [MahApps/MahApps.Metro#4011]
Hi!

I'm starting up with MahApps.Metro. I'm pretty new and don't know anything about this framework.
I was looking for some documentations on the web, but the official documentation I found was not complete.

Is there a full documentation out there?

Regards, Max

**Comment by timunie** [comment]
Hi @Matix-Media 

the documentation is in deed not complete. We are working on it but as it is a free time project there is no due date. You can find it here: http://mahapps.com

More over you can ask us on gitter (https://gitter.im/MahApps/MahApps.Metro) or in the discussions section. Please do not open issues for questions. 

A good starting point is to download the source and digg into the incuded demo apps. 

Happy coding 
Tim

**Comment by Matix-Media** [comment]
Thanks, Tim! I take a look at the Gitter. Hopefully this issue will help people who have problems starting in the future.
