### ISSUE TITLE
NullReferenceException in WindowsSettingBehavior

### ISSUE THREAD

**Issue by Nuklon** [MahApps/MahApps.Metro#4013]
## Describe the bug

> System.NullReferenceException
> at MahApps.Metro.Behaviors.WindowsSettingBehavior.`<CleanUp>`b__7_0() at offset 17
> at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, System.Object args, System.Int32 numArgs) at offset 55
> at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object source, System.Delegate callback, System.Object args, System.Int32 numArgs, System.Delegate catchHandler) at offset 2

## Steps to reproduce

This sometimes happens on app shutdown. Looking at the code, I suspect Application.Current is null in BeginInvoke:
https://github.com/MahApps/MahApps.Metro/blob/844f85f8c74f006935e05693c2a5e3e2a7f359c3/src/MahApps.Metro/Behaviors/WindowsSettingBehavior.cs#L96

## Environment

```
MahApps.Metro version: v2.4.3
Windows build number: Win10 2004
Visual Studio: 2019 16.8.0
Target Framework: .Net v4.7.2
```

**Comment by RafalNiewinski** [comment]
It also affects me with env:

```
MahApps.Metro version: v2.4.3.5
Target Framework: .NET 5.0
```
