### ISSUE TITLE
Error template disappears from Cell after changing menu in HamburgerMenu

### ISSUE THREAD

**Issue by GWawrzeniecki** [MahApps/MahApps.Metro#4018]
## Describe the bug

Hello
I have a WPF application where I use Prism and Mahapps.
I have a DataGrid with model which implements INotifyDataErrorInfo Interface, after loading data to grid I see some cells with red border (the value is invalid there) but if go to another MenuItem in HamburgerMenu and then I back to the first MenuItem the red border are disappeared. I have tried using AdornerDecorator but it didn't help. Then I have tried custom styles, and data temples for ErrorTemplate but it didn't help too.
**But If I add following code, it works**.

```xaml
        <DataGrid.Resources>
            <Style  TargetType="{x:Type DataGridCell}" BasedOn="{StaticResource MahApps.Styles.DataGridCell}" >
                <Style.Triggers>
                    <MultiTrigger>
                        <MultiTrigger.Conditions>


                        </MultiTrigger.Conditions>


                    </MultiTrigger>
                </Style.Triggers>
            </Style>
        </DataGrid.Resources>
```

I have no idea why it behaves like that.

## Steps to reproduce
1. Make model which implements INotifyDataErrorInfo .
2. Load some data to DataGrid, cells with incorrect data (validated by functions from INotifyDataErrorInfo ) should have red borders now.
3. Change View via HamburgerMenu
4. Back to View with Grid. Now red borders disappears.
5. Add the code from description. Now it should work.

Here is the View with DataGrid
```xaml
<UserControl x:Class="PrismJPKEditor.Modules.JPK.Views.Declaration"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:prism="http://prismlibrary.com/"             
             prism:ViewModelLocator.AutoWireViewModel="True">

    
    
    <DataGrid GridLinesVisibility="All" ItemsSource="{Binding SessionContext.JPKDataSource.Declaration.Declarations}" AutoGenerateColumns="False" CanUserAddRows="False" CanUserDeleteRows="False" >

        <DataGrid.Resources>
            <Style  TargetType="{x:Type DataGridCell}" BasedOn="{StaticResource MahApps.Styles.DataGridCell}" >
                <Style.Triggers>
                    <MultiTrigger>
                        <MultiTrigger.Conditions>


                        </MultiTrigger.Conditions>


                    </MultiTrigger>
                </Style.Triggers>
            </Style>
        </DataGrid.Resources>


        <DataGrid.Columns>
            <DataGridTextColumn IsReadOnly="True" Width="auto" Header="Nazwa pola" Binding="{Binding FieldName}"/>
            <DataGridTextColumn IsReadOnly="True" Width="auto" Header="Opis pola" Binding="{Binding Description}"/>
            <DataGridTextColumn   IsReadOnly="False" Width="auto" Header="Wartość pola" Binding="{Binding GridValue, ValidatesOnDataErrors=True, UpdateSourceTrigger=PropertyChanged}"/>
        </DataGrid.Columns>
    </DataGrid>
</UserControl>

```

## Expected behavior

The error template should stays after changing view via HamburgerMenu.

## Actual behavior

The error template disappears.

## Environment

```
MahApps.Metro version: v2.0.0
Windows build number: Win10 1909 [Version 10.0.18363.836]
Visual Studio: 2019 16.6.0
Target Framework: .Net Core 3.1 (v4.5.2, v4.7.2)
```

**Comment by punker76** [comment]
@GWawrzeniecki The default cell style is set to the `CellStyle` of the `DataGrid`. So if you define a new global style in your App.xaml this style will not use (or only once). You can prevent this if you give your style a key and use this explicitly on your DataGrid.

```xaml
<Style x:Key="SpecialCellStyle" TargetType="{x:Type DataGridCell}" BasedOn="{StaticResource MahApps.Styles.DataGridCell}" >
    <Style.Triggers>
        <MultiTrigger>
            <MultiTrigger.Conditions>
            </MultiTrigger.Conditions>
        </MultiTrigger>
    </Style.Triggers>
</Style>
```

```xaml
<DataGrid Style="{StaticResource SpecialCellStyle}" ... />
```

If you use this style always then you can set this to a global DataGrid style.

```xaml
<Style TargetType="{x:Type DataGrid}" BasedOn="{StaticResource {x:Type DataGrid}}">
  <Setter Property="CellStyle" Value="{StaticResource SpecialCellStyle}" />
</Style>
```

**Comment by GWawrzeniecki** [comment]
Okay! But my question was why the error template disappears after changing view via hamburger menu. And why after using this empty style it's suddenly working.

**Comment by timunie** [comment]
Hi @GWawrzeniecki 

Somehow this looks like an issue in WPF itself that I am facing also when I have a large `DataGrid` with virtualization enabled. Then the `ErrorTemplate` disappears on some cells after scrolling. 

See also: https://stackoverflow.com/questions/2977568/issue-with-wpf-datagrid-cell-style-when-scrolling 

This line did the trick for me (don't know if it does for you): 
```xaml 
VirtualizingPanel.VirtualizationMode="Standard"
```

Happy coding 
Tim

**Comment by GWawrzeniecki** [comment]
Hi @timunie
Thank you for your answer!

But unfortunately it didn't help. And in my case red border from error template doesn't disappears after scrolling but after selecting another view via HamburgerMenu and then reverting back to the view with DataGrid

Something like  here:
[https://social.msdn.microsoft.com/Forums/vstudio/en-US/69a202ad-2da4-49c0-aca1-51d7978458ce/error-template-disappears-when-different-tab-item-revisited?forum=wpf](url)

But in my case I use HamburgerMenu not the TabControl and wraping DataGrid in AdornetDecorator doesn't help also.

**Comment by timunie** [comment]
Any chance you could upload a sample App showing your issue to github? I cannot reproduce your issue as described. Maybe there is something else going on?

Happy coding 
Tim

**Comment by GWawrzeniecki** [comment]
Sure! I will upload in about one hour.

**Comment by timunie** [comment]
Hi @GWawrzeniecki to be honest I have never worked with PRISM and it is far beyond my knowledge. I can confirm your issue but I have no idea how to solve this. I only found a workaround via using `TemplateColumn`

```xaml
<DataGridTemplateColumn>
	<DataGridTemplateColumn.CellTemplate>
		<DataTemplate>
			<AdornerDecorator>   
				<TextBlock Text="{Binding GridValue}" />
			</AdornerDecorator>
		</DataTemplate>
	</DataGridTemplateColumn.CellTemplate>
</DataGridTemplateColumn>
```

Happy coding 
Tim

**Comment by timunie** [comment]
Hi @GWawrzeniecki 

I made a simple test without prism and it works. https://github.com/GWawrzeniecki/JPK/pull/1 
Maybe it has to do with PRISM? 

Happy coding 
Tim
