### ISSUE TITLE
ColorCanvas has 14 Binding Expression Errors

### ISSUE THREAD

**Issue by nzain** [MahApps/MahApps.Metro#4019]
## Describe the bug
Using the MahApps `ColorCanvas` results in 14 binding expressions errors when the control is displayed. VS2019 shows them in the new XAML Binding Failures tool (Debug > Windows > XAML Binding Failures). Alternatively, you add a `TraceListener` via `PresentationTraceSources.DataBindingSource` (this is what we use during development to avoid binding errors).

## Steps to reproduce

Create a new WPF application (I used framework, but probably doesn't matter) and use a `ColorCanvas`, e.g. using the sample code from the [MahApps ColorPicker Documentation](https://mahapps.com/docs/controls/ColorPicker#colorcanvas).

```xml
<Window x:Class="MahAppsDemo.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:MahAppsDemo"
        xmlns:mah="http://metro.mahapps.com/winfx/xaml/controls"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <Grid>
        <mah:ColorCanvas x:Name="ColorCanvasExample"
                         SelectedColor="Blue"
                         DefaultColor="Transparent"
                         LabelAlphaChannel="Alpha"
                         LabelBlueChannel="Blue"
                         LabelGreenChannel="Green"
                         LabelRedChannel="Red" />
    </Grid>
</Window>
```

## Expected behavior
No binding expression errors occur.

## Actual behavior
14 binding expressions errors show up (see screenshot below). Using a `TraceListener` in combination with `Debugger.Break();` calls completely kills the development experience.

## Environment

```
MahApps.Metro version: v2.4.3
Windows build number: Win10 2004
Visual Studio: 2019 16.8.3
Target Framework: v4.7.2
```

## Screenshots

![image](https://user-images.githubusercontent.com/13961979/103900031-97de3b00-50f7-11eb-8837-9a274d8a44a2.png)

**Comment by timunie** [comment]
@punker76 can you assign me to this issue?
