### ISSUE TITLE
ColorCanvas disable some parts

### ISSUE THREAD

**Issue by seba30** [MahApps/MahApps.Metro#4020]
Hey there,

I use the ColorCanvas to adjust the LED color on our devices. Sadly I can't find a DP (or maybe I'm too stupid) to disable the following:

- Alpha channel (makes no sense here in my case)
- HSV
- Name

It would be great, if you plan to develop and integrate these features in the future.

Thank you!

**Comment by timunie** [comment]
@punker76 I am working on another issue for this control. #4019 . I think this should be done in one PR. Should I do or will you do the changes? 

Happy coding
Tim

**Comment by punker76** [comment]
@timunie This one here is a Feature Request, the other one a Bug, so it would be better to do this in separate PRs. Btw, I don't get any Binding Expression errors...

**Comment by seba30** [comment]
@punker76 For example, change the colour name to something wrong and you'll get a binding error.

**Comment by timunie** [comment]
Hi @seba30 Hiding the `ColorName` will also hide the `ColorEyeDropper`. Would this be OK for you or do you think we need another solution here ?

**Comment by seba30** [comment]
Hey @timunie, I think it is OK for the moment. But beware, other users will need this sooner or later. 😁

**Comment by timunie** [comment]
Yeah the thing is it might get quite complex at some point. There is always the option to change the entire `ControlTemplate` for very special needs.

**Comment by seba30** [comment]
I know, configurability leads into complexity. The most interesting thing for me is the possibility to hide HSV and Alpha.
