### ISSUE TITLE
ColorPicker - ColorName Options

### ISSUE THREAD

**Issue by Mindc0re** [MahApps/MahApps.Metro#4023]
After playing a bit with the ColorPicker, I thought it would be nice to have an option to change the Visibility of the ColorName property, to allow users to display it or not.

I also think it would be nice to let the developer choose if they want the hexadecimal code of the selected color to be displayed in the ColorName. For example, if the ColorPicker is used to select a Color in a RichTextBox, it may be disturbing for users to see an hexcode next to the color name (for example, the hexcode is not displayed in Microsoft Word, if I want to make a usecase analogy).

Thanks for reading me :)

**Comment by timunie** [comment]
Hi @Mindc0re 

I have already a PR open which should add more options to the `ColorPicker`. See: #4022 . If you are talking about the content inside the `DropDown` you already can create your own `DataTemplate`. 

If you just want to show the Color: 
```xaml
<mah:ColorPicker SelectedColorTemplate="{DynamicResource MahApps.Templates.ColorPickerContent.ColorOnly}" />
```

You may also roll your very own `DataTemplate`. Here you find the build in ones: https://github.com/MahApps/MahApps.Metro/blob/bbab412af829c9b565fdfdbfd7aeacd9a30805f3/src/MahApps.Metro/Themes/ColorPicker/ColorPicker.xaml#L13-L63

----

> Thanks for reading me :)

Please do us a favor and fill in the issue template next time. See also: http://github.com/MahApps/MahApps.Metro/blob/develop/.github/CONTRIBUTING.md 
Thank you in advance 🙏 

Happy coding 
Tim

**Comment by Mindc0re** [comment]
Hi @timunie,

Thanks a lot for your answer ! I actually searched for a DataTemplate or something like that in the documentation, but I did not find anything... The DataTemplate you showed is working just fine, thanks !!
Though, it is not listed in [the doc of the ColorPicker](https://mahapps.com/docs/controls/ColorPicker).

Your pull request seems very interesting indeed, I should have looked up these before posting a feature request, sorry about that :)

Thanks again for your answer :)
Simon
