### ISSUE TITLE
Use Controls without rest of Theme

### ISSUE THREAD

**Issue by jpwkeeper** [MahApps/MahApps.Metro#4028]
I'd like to use specific controls from the application, but I'd rather not apply the entire Metro theme to my application.  Right now no matter what combinations of Resource Dictionaries I include, either my entire app starts looking different OR the ToggleSwitch doesn't render (just see the text).

**Comment by punker76** [comment]
@jpwkeeper 👉🏻 https://github.com/MahApps/MahApps.Metro/discussions/4029
