### ISSUE TITLE
Time Picker Hours starts with 12

### ISSUE THREAD

**Issue by goldcode** [MahApps/MahApps.Metro#4036]
## Describe the bug

The hours combox box of the Time Picker U.I starts with 12. 
My regional format is English (Germany).

## Steps to reproduce

Use the Mahapps.Demo. see screenshot.
![image](https://user-images.githubusercontent.com/918655/106717426-0384cc80-6600-11eb-8952-a001fe0bb037.png)

## Expected behavior
The hours combox box of the Time Picker is numerically sorted from 1 - 12 with 12 at the bottom.

## Environment

```
MahApps.Metro version: v2.4.3
Target Framework: .NET framework .v4.7.2

```

**Comment by punker76** [comment]
@goldcode This was implemented as a feature if you have the AM/PM format. But I don't remember why we did that.

**Comment by goldcode** [comment]
Was wondering if it is because 12 (or 0 for programmers;)) is the start of the clock, similar to 0 to 23h format. If that's the reason, then we can close this.
