### ISSUE TITLE
ListView custom view functionality breaks up, errors in debug output

### ISSUE THREAD

**Issue by vladabuba** [MahApps/MahApps.Metro#4045]
## Describe the bug

Application I work on is WPF/.Net Core 3.1. It uses ListView with custom View (that show items in wrap panel). Everything works fine until I add reference to MahApps.Metro and include necessary MahApps.Metro resources in App. Afterwards ListView functionality breaks up, items are not longer shown as in wrap panel, just as ordinary list... Also I get errors in Debug output.

## Steps to reproduce

Add reference to simple application that uses custom view with ListView. More information could be get form test applications that I have created and uploaded on following link (one is with MahApps.Metro enabled, another is without it):
https://filebin.net/qooty5o674obw29h 

## Expected behavior

To show proper ListView with custom view and without errors in debug output.

## Actual behavior

ListView with custom view functionality breaks up with errors in debug output:

System.Windows.Data Error: 40 : BindingExpression path error: 'Columns' property not found on 'object' ''TileView' (HashCode=8352109)'. BindingExpression:Path=TemplatedParent.View.Columns; DataItem='ScrollViewer' (Name=''); target element is 'ScrollViewer' (Name=''); target property is 'NoTarget' (type 'Object')
System.Windows.Data Error: 40 : BindingExpression path error: 'ColumnHeaderContainerStyle' property not found on 'object' ''TileView' (HashCode=8352109)'. BindingExpression:Path=TemplatedParent.View.ColumnHeaderContainerStyle; DataItem='ScrollViewer' (Name=''); target element is 'GridViewHeaderRowPresenter' (Name=''); target property is 'ColumnHeaderContainerStyle' (type 'Style')
System.Windows.Data Error: 40 : BindingExpression path error: 'ColumnHeaderTemplate' property not found on 'object' ''TileView' (HashCode=8352109)'. BindingExpression:Path=TemplatedParent.View.ColumnHeaderTemplate; DataItem='ScrollViewer' (Name=''); target element is 'GridViewHeaderRowPresenter' (Name=''); target property is 'ColumnHeaderTemplate' (type 'DataTemplate')
...

## Environment

```
MahApps.Metro version: v2.4.3
Windows build number: Win10 2004 [Version 10.0.19041.804]
Visual Studio: 16.9.0 Preview 1.0
Target Framework: .Net Core 3.1 
```

## Screenshots

Ok, without MahApps.Metro enabled, items show in proper wrap panel:

![MahAppsDisabled](https://user-images.githubusercontent.com/9928044/108132624-776cad80-70b3-11eb-9056-c42e2d03b578.png)

With MahApps.Metro enabled, ListView with custom view Wrap panel functionality breaks up, errors in debug output:

![MahAppsEnabled](https://user-images.githubusercontent.com/9928044/108132638-7b98cb00-70b3-11eb-8f29-58ea27b45883.png)

**Comment by timunie** [comment]
@vladabuba 

I did not test your App right now but what I noticed is, that you mix up `ListBox` and `ListView`. You should take one of it. 

Example:
```xaml
<Style [...] TargetType="{x:Type ListViewItem}" BasedOn="{StaticResource {x:Type ListBoxItem}}"> [...] 
```

should be: 
```xaml
<Style [...] TargetType="{x:Type ListViewItem}" BasedOn="{StaticResource {x:Type ListViewItem}}"> [...] 
```

**Comment by vladabuba** [comment]
Thanks for the reply. If I change BasedOn property for ListView or for ListViewItem (or them both) I get startup XAML expections:

An exception of type 'System.Windows.Markup.XamlParseException' occurred in PresentationFramework.dll but was not handled in user code
'Provide value on 'System.Windows.Markup.StaticResourceHolder' threw an exception.' Line number '7' and line position '10'.

This is technique I had learnt from Matthews McDonalds book "Pro WPF 4.5 in C#". If there is any other solution that allows me to have MVVM panel that wraps items horizontally, have support for sorting and filtering (and works fine with MahApps.Metro) it would be great if I can get any pointer towards it.

**Comment by timunie** [comment]
Hi @vladabuba ,

sure. Have a look at this: https://github.com/MahApps/MahApps.Metro.IconPacks . It is open source so you can grab all the items you need. It is even virtualized which makes it quite fast for a lot of data. I hope this helps you.

One more point: Sharing a sample is very good and helps us supporting you 👍. If you create a repro on github and upload your code there I even can pass changes back to you. Keep this in mind for next time. 

@punker76 I think you should move this topic to the `Q&A` - Section. 

Happy coding 
Tim

**Comment by vladabuba** [comment]
Thanks @timunie . Regarding IconPacks I already use it in multiple projects besides MahApps.Metro. And I love it. Thanks for the github reference, will see to use it more frequently in the future when working on this issues.
Please could you clarify me how IconPacks can help me in resolving issue on this sample?

**Comment by timunie** [comment]
Isn't the Browsers design what you are looking for? 
- WrapPanel
- Filter
- Sorting

![image](https://user-images.githubusercontent.com/47110241/108183564-7e72da80-710a-11eb-9be6-918b8dd5a5d2.png)

**Comment by timunie** [comment]
@vladabuba any news?

**Comment by punker76** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/MahApps/MahApps.Metro/releases) and then please use the [issue template](https://github.com/MahApps/MahApps.Metro/issues/new/choose).

If you have enough time then it would be nice to test this issue against the latest alpha version (availabe via [NuGet](https://www.nuget.org/packages/MahApps.Metro) and [appveyor](https://ci.appveyor.com/project/punker76/mahapps-metro/history)).

Thank you! 🙏
