### ISSUE TITLE
EnableCellEditAssist should handle the message dispatched from the popup control

### ISSUE THREAD

**Issue by mzh3511** [MahApps/MahApps.Metro#4048]
## Describe the bug

I have a popup control that is opened from the column header, when the popup opened, it will cover the first cell (a checkbox cell), when the user clicks the popup and `EnableCellEditAssist ` is true, the checkbox cell will change the check state value.

## Environment

```
MahApps.Metro version: v2.3.0
Windows build number: Win10 1909 [Version 10.0.18363.836]
Visual Studio: 2019 16.6.0
Target Framework: .Net Core 3.1 (v4.5.2, v4.7.2)
```

## Screenshots

Screenshot 1, the popup not opened:

![image](https://user-images.githubusercontent.com/3412782/108669537-3263d380-7518-11eb-80a8-2715377971ea.png)

Screenshot 2, the popup opened by clicking the filter icon:

![image](https://user-images.githubusercontent.com/3412782/108669652-6d660700-7518-11eb-8ffb-d321b0a83200.png)

When the user click the space between 2 `Checkbox`s in screenshot2, the first check box cell in the `DataGrid` (I mean the checkbox cell in screenshot1) will be checked.

**Comment by timunie** [comment]
Hi @mzh3511 

can you please share a sample App? Seems like you are missing the required `Styles`. 

Thank you and happy coding
Tim

**Comment by punker76** [comment]
@mzh3511 Can you publish a sample with this issue? Because I think I have a solution for it. Thx

**Comment by punker76** [comment]
@mzh3511 ?

**Comment by mzh3511** [comment]
[WpfApp8.zip](https://github.com/MahApps/MahApps.Metro/files/6161804/WpfApp8.zip)
![image](https://user-images.githubusercontent.com/3412782/111584016-3c67b200-87f8-11eb-929d-f6a80a3c4b50.png)

Sorry for later

1 Open my `WpfApp8` from attachment and unzip it
2 Run the `WpfApp8`
3 Mouse click the filter icon in the second column header
4 Mouse click at my cursor position of the screenshot, 

Expect: Just the popup control clicked and without any change
Actual:  The cell[1, 1] checked
