### ISSUE TITLE
CheckBox CornerRadius not working

### ISSUE THREAD

**Issue by PJonHar** [MahApps/MahApps.Metro#4050]
I have tried to add a CornerRadius to the CheckBox control but it does not work?
Am I doing something wrong?

```
MahApps.Metro version: v2.4.3
Windows build number: Win10 1903 [Version 18362.1256]
Visual Studio: 2019 18.6.0
Target Framework: .Net 4.8
```

## Screenshots

![image](https://user-images.githubusercontent.com/1200267/108838647-38b78580-75d4-11eb-8f19-cfbde35ad2ce.png)

**Comment by timunie** [comment]
Hi @PJonHar 

seems like it is currently not supported. I will add it if @punker76 gives me a 👍 .

@punker76 I can think of three possible solutions. Please mark the one you like most and I'll make a PR for it:
- [ ] Change the `Recangle` to `Border` and use the `ControlsHelper.CornerRadius`-Property which is already available
- [ ] Keep the `Rectangle` and add `CheckBoxHelper.CheckMarkRadius`-Property. This will then control both `RadiusX` and `RadiusY` of the `Rectangle`
- [ ] Keep the `Rectangle` and add two `CheckBoxHelper.CheckMarkRadius`-Properties (one for `X` and one for `Y`. The user can control the appearance in more detail but needs to set two properties everytime.

My favorite is option 2 I think

Happy coding 
Tim

**Comment by PJonHar** [comment]
Hi Tim,

I think that changing the Rectangle to a Border will be the cleanest solution ? As you say, the ControlsHelper.CornerRadius-Property is already available.

Cheers.

**Comment by timunie** [comment]
mhh not necessarily. If you look into the `Style` you will notice that it is already used by another `Border`:

https://github.com/MahApps/MahApps.Metro/blob/711f987d9b697c77ad742d961c3d00dff0949e8d/src/MahApps.Metro/Styles/Controls.CheckBox.xaml#L25-L30 

![image](https://user-images.githubusercontent.com/47110241/109051106-74d50e00-76da-11eb-8046-2347dfb0ab17.png)

another point is that you control all `CheckMark`-related things in the `CheckBoxHelper`. So you why not the `CornerRadius`?

**Comment by PJonHar** [comment]
I used snoop and found this if it helps?
![image](https://user-images.githubusercontent.com/1200267/109064336-95a55f80-76ea-11eb-9b2c-641c73fbf11a.png)
