### ISSUE TITLE
The target process exited without raising a CoreCLR started event

### ISSUE THREAD

**Issue by khanziaullah** [MahApps/MahApps.Metro#4053]
Working on a WPF .Net App project.
The UI project won't launch after this I added reference to MahApps.Metro 2.4.3.  I see the below error.

The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core.
The program '[20892] <program>.exe' has exited with code -2147450740 (0x8000808c).
The program '[20892] <program>.exe: Program Trace' has exited with code 0 (0x0).

After I remove references to MahApps* things seems to be working again.

**Comment by khanziaullah** [comment]
It is a netcoreapp2.2 known issue and probably already resolved. 
Could you test it again for netcoreapp3.3 once again and update the version?

**Comment by punker76** [comment]
@khanziaullah I don't know exactly what to look for? Can you provide this sample?

**Comment by khanziaullah** [comment]
1. Create a WPF .Net App
2. My .csproj looks like below:

```
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

```
3. Run the Application. It launches fine.

4. Added reference to MahApps.Metro
```
  <ItemGroup>
      <PackageReference Include="MahApps.Metro" Version="2.4.3" />
  </ItemGroup>
```

5. Now when I run the project. I see the error from the issue.
```

The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core.
The program '[20892] .exe' has exited with code -2147450740 (0x8000808c).
The program '[20892] .exe: Program Trace' has exited with code 0 (0x0).


```

**Comment by punker76** [comment]
@khanziaullah It seems like that there is something missing on your machine. Idk exactly what, but maybe this link helps

https://stackoverflow.com/a/56672195/920384

**Comment by khanziaullah** [comment]
I've tried this already. Updated .NET Core SDK and the Visual Studio. Created New Projects. I see this in other new projects as well.

**Comment by timunie** [comment]
Hi @khanziaullah 

can you share a test project via github please? Maybe we can see what is going on there and provide a solution if it does not compile on our side as well.

Happy coding
Tim

**Comment by khanziaullah** [comment]
The problem occurs when I add a reference to a .net standard project (which is using NHibernate)

**Comment by Flunx** [comment]
I had a similar problem with a project where I had to remove any Post-build events.
