### ISSUE TITLE
wpf titlle seperator invisiable

### ISSUE THREAD

**Issue by qinaksd** [MahApps/MahApps.Metro#4059]
## Describe the feature

i used a mahapps.metro window with a icon and a title,  how to invisiable the seperator?

**Comment by timunie** [comment]
Hi @qinaksd 

first of all this is a question about usage and neither a bug nor a feature request. So it either belongs to [Discussions](https://github.com/MahApps/MahApps.Metro/discussions) or [gitter](https://gitter.im/MahApps/MahApps.Metro)

to answer your question: I see no separator between my icon and the title: 
![image](https://user-images.githubusercontent.com/47110241/109467126-0215bb00-7a6b-11eb-8d1d-d30e383b9fbe.png)

So please share your XAML and a sample App via github. Thank you. 

Happy coding
Tim

**Comment by punker76** [comment]
@qinaksd The visibility of the separators on the left side can be switched with the `ShowSeparators` property (the default is true):


```xaml
<mah:MetroWindow.LeftWindowCommands>
    <mah:WindowCommands ShowSeparators="False">

    </mah:WindowCommands>
</mah:MetroWindow.LeftWindowCommands>
```
