### ISSUE TITLE
Must have a Storyboard object reference before this trigger action can execute in TimePicker

### ISSUE THREAD

**Issue by shahshyam** [MahApps/MahApps.Metro#4065]
My XAML code 

 <mah:TimePicker Grid.Row="2" Grid.Column="0"  Margin="0,0,0,10" >
</mah:TimePicker>

Getting following error in TimePicker.

Error detail :
System.Windows.Markup.XamlParseException
  HResult=0x80131501
  Message=Provide value on 'System.Windows.Markup.StaticResourceHolder' threw an exception.

Inner Exception 1:
InvalidOperationException: Must have a Storyboard object reference before this trigger action can execute.

Visual Studio 2017 Enterprise /VS 2019 community 
Net 4.6.

**Comment by timunie** [comment]
Hi @shahshyam 

Please fill in the entire issue template and provide a sample App. I cannot reproduce your issue with the latest version of MahApps.

Happy coding
Tim

**Comment by punker76** [comment]
@shahshyam Which version of MahApps are you using?

**Comment by shahshyam** [comment]
Sorry for delay response. I am using latest version of Mahapp. My project structure is It is vsto addins which load sidebar . The sidebar was WinForms user control and its load WPF usercontrol on it. WPF user control is using MahAppControl called TimePicker.

**Comment by punker76** [comment]
@shahshyam So you have the WPF inside a WinForms control? Can you check if you add all necessary resources at your WPF control? Or is there also a App.xaml?

**Comment by shahshyam** [comment]
yes, I have wpf control in side WinForms control and there is not any App.xml and other control is working as expected like tabcontrol , calendarpicker etc

**Comment by punker76** [comment]
@shahshyam Ok, thx for the clarification.

**Comment by pacoweb** [comment]
I have the same problem. I´m using the latest version too and in my case the WPF is not inside WinForms control. 
In my case  it works on a UserControl but not in MainWindow.

**Comment by TSerious** [comment]
I have the same problem and it also doesn't work in a UserControl.

**Comment by derekdd23** [comment]
Is there a work around for this issue while this remains open?

**Comment by timunie** [comment]
Hi @derekdd23 

I still cannot reproduce this issue. May it be possible to provide a not working sample App? 

To answer your question: at least you can grab the original `Style` and replace `DynamicResource` with `StaticResource` in the `ControlTemplate.Triggers`:

See: https://github.com/MahApps/MahApps.Metro/pull/4075/commits/d6c712f9b182590ffede91911788b659141db363

Happy coding
Tim

**Comment by pacoweb** [comment]
Hi,
I have reproduced the error. 
I think it is related to how the application starts. 
I use DI and the application starts like this (more or less):
```
    public static class Program
    {
        [STAThread]
        static void Main(string[] args)
        {
            var app = new App();

            var mainWindow = new MainWindow();

            app.InitializeComponent();

            app.Run(mainWindow);
        }
    }
```

I am attaching a compressed file with the project that reproduces this problem when the application starts.
[WpfMahAppDatePickerError.zip](https://github.com/MahApps/MahApps.Metro/files/6342910/WpfMahAppDatePickerError.zip)

Thanks!!

**Comment by punker76** [comment]
@pacoweb It works now with the latest changes.

![image](https://user-images.githubusercontent.com/658431/115388181-dd70d080-a1db-11eb-8858-63f110dd1f8a.png)

**Comment by pacoweb** [comment]
Thanks!

When is the nuget package update scheduled?

**Comment by punker76** [comment]
@pacoweb v2.4.5 is out now

**Comment by pacoweb** [comment]
Thank you!

Great job!
