### ISSUE TITLE
Can't Expand the Expander

### ISSUE THREAD

**Issue by irjadah-dev** [MahApps/MahApps.Metro#4066]
Hi,
im using the Expander, when I switch to other Window and then return back to the Mainwindow, the Expander can't be opened.
MahApps Version 2.4.0

`The storyboard System.Windows.Media.Animation.Storyboard could not be applied: System.InvalidOperationException: Der Name "ExpandSite" kann im Namensbereich von "System.Windows.Controls.Border" nicht gefunden werden.
   bei System.Windows.Media.Animation.Storyboard.ResolveTargetName(String targetName, INameScope nameScope, DependencyObject element)
   bei System.Windows.Media.Animation.Storyboard.ClockTreeWalkRecursive(Clock currentClock, DependencyObject containingObject, INameScope nameScope, DependencyObject parentObject, String parentObjectName, PropertyPath parentPropertyPath, HandoffBehavior handoffBehavior, HybridDictionary clockMappings, Int64 layer)
   bei System.Windows.Media.Animation.Storyboard.ClockTreeWalkRecursive(Clock currentClock, DependencyObject containingObject, INameScope nameScope, DependencyObject parentObject, String parentObjectName, PropertyPath parentPropertyPath, HandoffBehavior handoffBehavior, HybridDictionary clockMappings, Int64 layer)
   bei System.Windows.Media.Animation.Storyboard.BeginCommon(DependencyObject containingObject, INameScope nameScope, HandoffBehavior handoffBehavior, Boolean isControllable, Int64 layer)
   bei MahApps.Metro.Controls.ExpanderHelper.Expander_Collapsed(Object sender, RoutedEventArgs e)`

**Comment by punker76** [comment]
@irjadah-dev Can you test this again the latest version (v2.4.4)? If this doesn't help then please create a short sample or post some code in here. Thx

**Comment by irjadah-dev** [comment]
@punker76 already done, we had a problem with the PagingControl! thx
