### ISSUE TITLE
TextBoxHelper.WatermarkAligment = Center not working?

### ISSUE THREAD

**Issue by TripleNico** [MahApps/MahApps.Metro#4068]
Currently using a ComboBox with a watermark like this:
```XAML
<ComboBox
    Grid.Row="4"
    Grid.Column="1"
    Margin="3"
    mah:TextBoxHelper.UseFloatingWatermark="True"
    mah:TextBoxHelper.Watermark="--- select something ---"
    mah:TextBoxHelper.WatermarkAlignment="Center"
    DisplayMemberPath="MyPropertyName"/>
```

But this shows up as:
![image](https://user-images.githubusercontent.com/64465421/110450709-bfd02780-80c3-11eb-84b8-094407daa912.png)

As you can see this is not centeraligned. Am i overlooking something or is it simply not working?

Currently using v2.4.4

**Comment by punker76** [comment]
@TripleNico You need to set the `HorizontalContentAlignment` to `Stretch`

```xaml
                <ComboBox
                    Grid.Row="4"
                    Grid.Column="1"
                    Margin="3"
                    mah:TextBoxHelper.UseFloatingWatermark="True"
                    mah:TextBoxHelper.Watermark="--- select something ---"
                    mah:TextBoxHelper.WatermarkAlignment="Center"
                    HorizontalContentAlignment="Stretch"
                    DisplayMemberPath="MyPropertyName"/>
```

**Comment by TripleNico** [comment]
Thanks, sometimes it's that easy! ;-)

Is there also an easy way to hide the watermark when `SelectedItem isnot Nothing`?

**Comment by timunie** [comment]
@TripleNico I am a bit confused. Why do you set ` mah:TextBoxHelper.UseFloatingWatermark="True"` when you don't want it to show up if something is selected? 

fyi: ` mah:TextBoxHelper.UseFloatingWatermark="False"` will hide the watermark once an item is selected. This is the default behavior

Happy coding
Tim

**Comment by TripleNico** [comment]
Doh! I overlooked it. Thanks!
