### ISSUE TITLE
Button fontsize cannot be changed in dialog

### ISSUE THREAD

**Issue by BornToBeRoot** [MahApps/MahApps.Metro#4069]
## Describe the bug

Hi, i try to change the font size of the (Base)MetroDialog. It seems like the font size is ignored. Everything else like Background or  FontStyle can be changed.

I set a custom resource dictionary

```
 MetroDialog.CustomResourceDictionary = new ResourceDictionary
            {
                Source = new Uri("NETworkManager;component/Resources/Styles/MetroDialogStyles.xaml", UriKind.RelativeOrAbsolute)
            };
```

```
 <Style x:Key="MahApps.Styles.Button.Dialogs" BasedOn="{StaticResource DefaultButton}" TargetType="{x:Type Button}">
        <Setter Property="VerticalAlignment" Value="Center" />
        <Setter Property="FontSize" Value="14" />
    </Style>

    <Style x:Key="MahApps.Styles.Button.Dialogs.Accent" BasedOn="{StaticResource HighlightedButton}" TargetType="{x:Type Button}">
        <Setter Property="VerticalAlignment" Value="Center" />
        <Setter Property="FontSize" Value="14" />
    </Style>
```

See this PR: https://github.com/BornToBeRoot/NETworkManager/pull/570

## Environment

```
MahApps.Metro version: v2.0.0
Windows build number: Win10 1909 [Version 10.0.18363.836]
Visual Studio: 2019 16.6.0
Target Framework: .NET 5.0.x
```

## Screenshots

![image](https://user-images.githubusercontent.com/16019165/111052184-2b661c00-8459-11eb-82c3-647a881a2096.png)

**Comment by timunie** [comment]
Hi @BornToBeRoot 

it works for me if I add this to the `MetroDialogSetting`:

```c#
MetroDialog.DialogButtonFontSize = 50; // What ever size you like
```

![image](https://user-images.githubusercontent.com/47110241/111069632-4161f400-84ce-11eb-8d36-b586f519a26e.png)

Happy coding
Tim

**Comment by BornToBeRoot** [comment]
Hi @timunie 

i can confirm that your solution is working!

```
MetroDialogSettings MetroDialog = new MetroDialogSettings()
MetroDialog.DialogButtonFontSize = 14
```

Thank you !!!
