### ISSUE TITLE
MetroWindow Owner effect not as we expected

### ISSUE THREAD

**Issue by hahanonym** [MahApps/MahApps.Metro#4071]
## Describe the bug
child metrowindow set filed Owner，but effect not as we expected。
I have tested wpf default window ，it worked as expected。 

## Steps to reproduce
1.  two MetroWindow（MainWindow and childwindow）
2. MainWindow  has a button，click ，then ShowDialog the childwindow who's owner set MainWindow  
3. minimize the child 

## Expected behavior
when you minimize the child ，the MainWindow  minimize。
 

## Actual behavior
when you minimize the child ，the MainWindow  not minimize 

## Environment

```
MahApps.Metro version: 2.4.4
Windows build number: Win10 [Version 10.0.19041.867]
Visual Studio: 2019 16.3.1
Target Framework: .net framework 4.6.1
```

## Screenshots
![image](https://user-images.githubusercontent.com/9391031/111597198-e94a2b00-8808-11eb-8aa1-1673ae6bb6a3.png)
after minimize 
![image](https://user-images.githubusercontent.com/9391031/111597391-11398e80-8809-11eb-8eaf-f2ad989016dd.png)

**Comment by punker76** [comment]
@hahanonym If I use a normal Window then I get the exact same behavior.

```cs
private void ButtonBase_OnClick(object sender, RoutedEventArgs e)
{
    var childWindow = new Window() {Title = "Child", Owner = this};
    childWindow.ShowDialog();
}
```

![mahapps_child_owner](https://user-images.githubusercontent.com/658431/111599283-6907d380-87d0-11eb-8958-0b86f2c377db.gif)

**Comment by hahanonym** [comment]
amazing!!!
I just test on my computer (version 10.0.19041). Performance as my expected。
then test on vmware system （version 10.0.14393）Performance  as your gif.
another computer (version 19042).Performance as my expected

**Comment by hahanonym** [comment]
I have found some Specification
[https://docs.microsoft.com/en-us/dotnet/api/system.windows.window.owner?view=netframework-4.6.1](url)
I‘m so confused.
If I need parent window min / max behavior same with child.How could I solve my problem?

**Comment by punker76** [comment]
@hahanonym Since this is now not an actual bug of MahApps, I will close the issue. I have never needed such behavior, maybe a search at SO or at Microsoft itself will help.
