### ISSUE TITLE
when lost focus，The WindowBar color become # 808080

### ISSUE THREAD

**Issue by EachTime-sys** [MahApps/MahApps.Metro#4073]
## Describe the feature
   MahApps.Metro.ThemeManager.AddAppTheme("SelfAppTheme", new Uri("pack://application:,,,/Resources/SelfAppTheme.xaml"));
            MahApps.Metro.ThemeManager.AddAccent("SelfAccent", new Uri("pack://application:,,,/Resources/SelfAccent.xaml"));
            MahApps.Metro.ThemeManager.ChangeAppStyle(Application.Current, MahApps.Metro.ThemeManager.GetAccent("SelfAccent"), MahApps.Metro.ThemeManager.GetAppTheme("SelfAppTheme"));

(Version 1.6.5) i use MetroWindow and used my custom style,  When the software loses the focus, the color of the windowbar  will become # 808080. I don't know how to change this color. Please help me. Thank you

**Comment by timunie** [comment]
hi @EachTime-sys 

next time please use either https://github.com/MahApps/MahApps.Metro/discussions or https://gitter.im/MahApps/MahApps.Metro. 

Thank you and happy coding
Tim
