### ISSUE TITLE
Attach and raise ValidationError popup on custom control

### ISSUE THREAD

**Issue by TripleNico** [MahApps/MahApps.Metro#4077]
This is not a feature but rather a question. In my application i have a "Enter pincode" screen. On the window i have four ellipses in a grid evenly spaced, beneath this there a 10 buttons with numbers. Now i have everything setup the way i want meaning when a user enters numbers that the ellipses will be filled until four digits are entered. Now in the code behind i validate the pincode. On error i want to raise a ValidationErrorPopup beside the four ellipses.

Normally this is easily done with textboxes but i don't want to use this. Some my question is what would be the right way to use this? I thought about adding a textbox behind the four ellipses and also enter the code there and then raise the error on the textbox?

**Comment by timunie** [comment]
> This is not a feature but rather a question

Then ...  why do you open an issue? There is a discussions section (https://github.com/MahApps/MahApps.Metro/discussions) and gitter (https://gitter.im/MahApps/MahApps.Metro). No need to open an issue.  

To your question: Yes it is possible to add validation to almost any control. You will need a `{Binding YourValidatedProperty}` which may also be the `Tag` if you don't want it as the content. Then set the `Validation.ErrorTemplate`.

```xaml
<StackPanel / Grid / Border / WhatEver 
     Tag={Binding YourValidatedProperty}
     Validation.ErrorTemplate="{StaticResource MahApps.Templates.ValidationError}">
     [Your Ellipses]
</StackPanel>
```

Happy coding
Tim

**Comment by TripleNico** [comment]
Hi Tim,

Thanks for your prompt answer! First of all my appoligize, i wasn't aware of the discussion section also the gitter. Now i know it's there i will certainly will use it next time :-)

Back your suggestion; Ah that was easy to add. I just tested it and the validation border appears but the popup doesn't appear, i also get this binding exception:"

```
System.Windows.Data Warning: 40 : BindingExpression path error: 'BorderThickness' property not found on 'object' ''Grid' (Name='')'. BindingExpression:Path=AdornedElement.BorderThickness; DataItem='AdornedElementPlaceholder' (Name='placeholder'); target element is 'Control' (Name=''); target property is 'NoTarget' (type 'Object')
```

**Comment by timunie** [comment]
Use `mah:ValidationHelper.ShowValidationErrorOnMouseOver="True"` in this case. 

The binding exception is ok. It looks for a border to get the desired borderthickness or 1 if no border found. 

Happy coding
Tim

**Comment by TripleNico** [comment]
> Use `mah:ValidationHelper.ShowValidationErrorOnMouseOver="True"` in this case.
> 
This indeed enables the popup upon MouseOver but i do want to show it without MouseOver. Is that possible or do i have to change something to the UI (grid) to get it to popup?

> The binding exception is ok. It looks for a border to get the desired borderthickness or 1 if no border found.
> 
Alright that i will ignore it :-)

**Comment by timunie** [comment]
> but i do want to show it without MouseOver. Is that possible or do i have to change something to the UI (grid) to get it to popup?

If this is your intention I think you have to create your own Validation-Style. Here is the original: 
https://github.com/MahApps/MahApps.Metro/blob/develop/src/MahApps.Metro/Styles/Controls.ValidationError.xaml

**Comment by TripleNico** [comment]
Thanks, i ended up to reuse a textbox behind it for this purpose, works like a charm :-)
