### ISSUE TITLE
MetroWindow with webview2 content not easy to resize

### ISSUE THREAD

**Issue by cuiliang** [MahApps/MahApps.Metro#4094]
## Describe the bug
Sample project: 
[WebView2WpfBrowser.zip](https://github.com/MahApps/MahApps.Metro/files/6389709/WebView2WpfBrowser.zip)

Can only resize window when mouse pointer just on window border, which is just 1 px width. Very hard to locate.

## Steps to reproduce
1. clone https://github.com/MicrosoftEdge/WebView2Samples 
2. import MahApps.Metro
3. Import styles
4. Change MainWindow base class to MetroWindow

## Environment

```
MahApps.Metro version: v2.4.5
Windows build number: Win10 20H2 [Version 10.0.19042.928]
Visual Studio: 2019 16.9.4
Target Framework: .Net Core 3.0
```

## Screenshots

**Gif Animation: Resize with MetroWindow (Please watch mouse pointer)**

![test_难以resize](https://user-images.githubusercontent.com/1972649/116360539-9b2a3d80-a832-11eb-90a2-af729e88f77e.gif)

**Gif Animation: Resize with normal wpf window:**

![test_resizewithnormalWindow](https://user-images.githubusercontent.com/1972649/116361774-e8f37580-a833-11eb-81b1-c536aa59a2ab.gif)

**Comment by punker76** [comment]
@cuiliang That's the price of borderless windows. But you have some options to fix this.

- set a `GlowBrush` instead using `BorderBrush` and set `controlzex:WindowChrome.IsHitTestVisibleInChrome="True"` to the WebView2

```xaml
<mah:MetroWindow
    GlowBrush="{DynamicResource MahApps.Brushes.Accent}"
    >

</mah:MetroWindow>
```

- or set a `Margin="5 0 5 5"` and `controlzex:WindowChrome.IsHitTestVisibleInChrome="True"` to the WebView2

**Comment by cuiliang** [comment]
@punker76 Thank you~

**Comment by punker76** [comment]
![mahapps_webview2](https://user-images.githubusercontent.com/658431/116366869-078f4780-a807-11eb-9edb-54267a4169b4.gif)

**Comment by cuiliang** [comment]
Report: Set margin not work, GlowBrush  works. Thank you.

**Comment by cuiliang** [comment]
Find a solution without GlowBrush:

```c#
 public MainWindow()
        {
            InitializeComponent();

            WindowChrome.SetWindowChrome(this, new WindowChrome()
            {
                CaptionHeight = 30,
                GlassFrameThickness = new Thickness(5),
                ResizeBorderThickness = new Thickness(5),
                NonClientFrameEdges = NonClientFrameEdges.Bottom| NonClientFrameEdges.Left
                | NonClientFrameEdges.Right 
            });
        }
```

NonClientFrameEdges does the trick.
