### ISSUE TITLE
Flyout color when change color in a single MetroWindow

### ISSUE THREAD

**Issue by recetarioMDWiki** [MahApps/MahApps.Metro#4096]
## Describe the bug

Hello everyone!
I have a problem with changing the color to a single window. I will try to explain it with an example.

## Expected behavior

I was hoping to change the color of the secondary window without affecting the main one

## Actual behavior

In my Application.xaml, in ResourcesDictionary, I have this:
```
<ResourceDictionary.MergedDictionaries>
    <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
    <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
    <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Themes/Light.Blue.xaml" />
    <ResourceDictionary Source="/Resources/Icons.xaml" />
    <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.TabControl.xaml" />
</ResourceDictionary.MergedDictionaries>
```

The user can choose which color he wants to apply. In the example, the user has chosen Pink.
Starting the application, I apply the theme and color that the user has saved in the configuration, using this:

```ThemeManager.Current.ChangeTheme(Application.Current, My.Settings.EstiloHUM, My.Settings.ColorHUM)```

![image](https://user-images.githubusercontent.com/50943477/116546245-aee8a900-a8f1-11eb-9f90-9263fa8b066e.png)

When I open the secondary window, according to a series of characteristics, that window may want to open it in Steel color.
I use this:

```ThemeManager.Current.ChangeTheme(Me, "Light.Steel")```

So far so good.

![image](https://user-images.githubusercontent.com/50943477/116546315-c1fb7900-a8f1-11eb-8b97-74e5dff24d71.png)

But if I look in the main window, everything is still Pink except for this flyout (which has Theme = "Accent" in the .xaml). This and other flyouts from main window are in design code (.xaml) and I used them as filters for different sections.

![image](https://user-images.githubusercontent.com/50943477/116546371-cfb0fe80-a8f1-11eb-9571-80f34a9082f2.png)

And also, when I close the second window, the main one seems to go back to Pink, but that flyout continues to show with Steel, and others flyouts, which has Theme = "Adapt", the content shows like this:

![image](https://user-images.githubusercontent.com/50943477/116546453-e9524600-a8f1-11eb-905b-29d2d959ce4c.png)

When closing the secondary window I have tried to correct it using:
```
ThemeManager.Current.ThemeSyncMode = ThemeSyncMode.SyncWithAccent
ThemeManager.Current.SyncTheme()
```
But it puts everything back to Blue, so I reassign the color Pink:
``` ThemeManager.Current.ChangeTheme (Application.Current, My.Settings.EstiloHUM, My.Settings.ColorHUM) ```

This solves it, but it entails a small delay of 3-4 seconds.

Has anyone else had this problem with the flyouts contained in the main window when changing the color in a secondary window?
**Thanks for your help!**

## Environment

```
.Net Framework 4.6.2
ControlzEx version: 4.4.0
MahApps.Metro version: 2.4.5
Visual Studio 2015 version 14.0 
```

**Comment by punker76** [comment]
@recetarioMDWiki In your second window you must change this call

```c#
ThemeManager.Current.ChangeTheme(Me, "Light.Steel")
```

to this which then changes the whole Application 

```
ThemeManager.Current.ChangeTheme(Application.Current, "Light.Steel")
```

**Comment by recetarioMDWiki** [comment]
@punker76 Thanks for your help! However, I think that I'm not explain the problem well, sorry. I try again.

That I want is have "window A" in Pink color. And to open other windows in the same color. But, in some cases, I want open "window B" in Steel color (just to show a kind of "read only" style to the user). But just "window B"; the other window, "window A", the main window of the application, must be Pink (although is in second plane and blurred). And, finally, when I close "window B", "window A" (the main window) must show all its elements in Pink (in the screenshots I drew red arrows to point that those elements remains in Steel).

I know that I just can change the color to whole application when I open "window B" and, at close it, change again whole application to color Pink. But, I tried and it provoques a small delay that I would like to avoid (if is possible).

Thanks!

**Comment by timunie** [comment]
Hi @recetarioMDWiki 

Any chance that you can provide a short sample showing your issue? Maybe we can find a solution then. I think it may be related to how you open the second window. 

Happy coding
Tim

**Comment by recetarioMDWiki** [comment]
Hi @timunie 

I'm sorry it took days to respond. I've been adapting a small project to simulate my problem, but it's done 🎉
How do I share it with you? Do I upload the .rar here?
It is a solution of visual studio 2015, in .NET VB.

Thanks!

**Comment by timunie** [comment]
Hi @recetarioMDWiki 

best way would be creating a new github repro and upload it there. If you want to keep it private you will need to invite me and @punker76 otherwise just share the link here. 

We can then just send you code changes. 

Happy coding 
Tim

**Comment by recetarioMDWiki** [comment]
Hi @timunie 
I just create a new repo and invite you and @punker76 . If you need any more action from me, please let me know.

On the other hand, I'm going to explain the sequence for the tests here:
When starting the application, go to the "List" item
![image](https://user-images.githubusercontent.com/50943477/116996464-bfc36100-acdb-11eb-969b-cf271373236f.png)

Then press "Search"
![image](https://user-images.githubusercontent.com/50943477/116996495-cce05000-acdb-11eb-89c1-38544a677e85.png)

Double click on any of the rows in the datagrid
![image](https://user-images.githubusercontent.com/50943477/116996600-f1d4c300-acdb-11eb-8146-2fd7c3e11b2b.png)

The second window will open in Steel. When you move it, you can see how the highlighted flyout turns Steel too, but not title or status bar when  you select the main window (althoug is blurred).
![image](https://user-images.githubusercontent.com/50943477/116996697-1f217100-acdc-11eb-976b-845803cbe998.png)

Close the second window. The tiny flyout on the right is Steel. 
![image](https://user-images.githubusercontent.com/50943477/116997024-8a6b4300-acdc-11eb-89d6-a88df3ab78b9.png)

And when opening the left flyout - with the button on the top right (1) or the tiny flyout on the rigth -
![image](https://user-images.githubusercontent.com/50943477/116997187-c3a3b300-acdc-11eb-932c-197d3f2a9c81.png)

it has also changed to Steel
![image](https://user-images.githubusercontent.com/50943477/116997234-d1f1cf00-acdc-11eb-9758-7565cdbc6151.png)

I hope it helps. **Thanks so much!**

**Comment by timunie** [comment]
Ok I can confirm that there is an issue where all flyout changes theme whereas the window doesnt. I managed to reproduce this in the demo as well: 

https://github.com/timunie/MahApps.Metro/tree/FlyoutThemingIssueInDemo

/cc @punker76 @batzen

**Comment by batzen** [comment]
The culprit for all of this is that inside of `ThemeManagerOnIsThemeChanged` in `MetroWindow` the new theme is applied to all Flyouts contained in that window.
But the `ThemeChanged` event from `ThemeManager` is fired globally and not on a per Window basis.
Instead of using `e.NewTheme` for changing flyout themes, unconditionally, the theme should be detected from the current window instance and that theme should then be used if the even sender is null, if the event sender is the current window take the theme from `e.NewTheme`.
At least that's what i think would be the right solution.

We should also investigate the delays @recetarioMDWiki mentioned.
My rough guess is that the application contains a lot of flyouts and because `ThemeChanged` is fired globally every flyout changes it's theme. So fixing the flyout theme change code should, in theory, also fix the delays.
