### ISSUE TITLE
Fill up the documentation

### ISSUE THREAD

**Issue by Alfagun74** [MahApps/MahApps.Metro#4099]
Seriously, every other page of the documentation says "coming soon".  It is literally unusable.  
Would somebody please sit down and fill that up?

**Comment by batzen** [comment]
While you might be correct about missing documentation, you should point it out way, way more friendly.

This project, as many other OSS project, is maintained by people in their spare time.
So treat them with respect, instead of demanding something from them.
You have no, and I really mean absolutely no (not the slightest), right to demand anything from them.

Would you want to be treated the way you just did?

P.S.: As you might have noticed, this project is OSS and it also accepts PRs.

**Comment by Alfagun74** [comment]
> While you might be correct about missing documentation, you should point it out way, way more friendly.
> 
> This project, as many other OSS project, is maintained by people in their spare time.
> So treat them with respect, instead of demanding something from them.
> You have no, and I really mean absolutely no (not the slightest), right to demand anything from them.
> 
> Would you want to be treated the way you just did?
> 
> P.S.: As you might have noticed, this project is OSS and it also accepts PRs.

@batzen Hello Mr. SJW Internet Police, 

i'm sorry but i don't know what you are talking about. I reported an Issue here, which actually is also a contribution in my freetime by itself and just pointed it out the way it is. I am currently struggling using this project and the documentation is in fact **unusable**, because every other page i want to read more on say's "Coming Soon". It wastes everyones frustation and time finding out everything by themselves and could improve for everybody if a 9 year old project would have a proper documentation. 

Also i did not demand anything and even said please. The text i have written above can be interpreted in different ways. I mean't it in a "We're all in the same boat. Lets improve this for everyone way.", but it seems you read it in a "YOU SIT DOWN AND DO THIS NOW" way. So maybe you should stop educating strangers in the internet and just regard the factual information provided instead of taking everything personally. 

Thanks

**Comment by batzen** [comment]
Ok, i totally expected such a response. And you, sadly, proofed my assumption about you being totally right.
No need to argue with you and waste further time.

**Comment by gep13** [comment]
@Alfagun74 so, based on what you have said, I am going to assume that once you figure out the information that you are looking for (have you seen the **very** active [Gitter room](https://gitter.im/MahApps/MahApps.Metro) where @punker76 and other members of the MahApps community go out of their way to answer questions), that you will be sending some PR's into the documentation section of the project, to help improve it?

I am also assuming that you have seen the [Samples](https://github.com/MahApps/MahApps.Metro/tree/develop/src/MahApps.Metro.Samples) project, which provides lots of examples of how to use the different parts of MahApps.

**Comment by iMandeep** [comment]
Can I help improve the documentation?

**Comment by timunie** [comment]
Hi @iMandeep 

Yes of course. I think any help is very welcome. 

The help source lives here https://github.com/MahApps/mahapps.com

Read also about how to contribute.

Happy documenting 
Tim
