### ISSUE TITLE
ShowProgressAsync Escape button

### ISSUE THREAD

**Issue by JackDjTom** [MahApps/MahApps.Metro#4114]
Would be nice to be able to specify if progress dialog should be closed on escape key/button press.

Same as #1976 for MessageDialog.

**Comment by marcelstrauss724** [comment]
I have attached a fix for the ProgressDialogController class. If requested, I can also create a pullrequest.
[ProgressDialogController.txt](https://github.com/MahApps/MahApps.Metro/files/6653570/ProgressDialogController.txt)
