### ISSUE TITLE
Style for WinUI/FluentUI

### ISSUE THREAD

**Issue by epflbutza** [MahApps/MahApps.Metro#4115]
Is there a roadmap for WinUI/FluenUI style support? In the documentation https://mahapps.com/docs/stylevariants/winui  "coming soon" is mentioned. 

Thanks

**Comment by timunie** [comment]
Hi @epflbutza 

do you really think this should be opened as an issue? There is a discussions section for questions like this. 

To the topic: MahApps is a free time project mainly maintained by @punker76 and some other contributors. So there is no official roadmap and it is done when its done. I know that is not the answer you hoped for but time is limited and especially free-time is. 

I hope for your understanding

Happy coding
Tim

**Comment by epflbutza** [comment]
Thanks for reply. Sorry yes it is a feature request. I only ask because WinUI is mentionend on the documentation page.

**Comment by epflbutza** [comment]
thanks
