### ISSUE TITLE
Unable to resolve resource on x64

### ISSUE THREAD

**Issue by raozhihao** [MahApps/MahApps.Metro#4116]
When i use in X64,this xaml desgin tips "Unable to resolve resource "

This project 
 <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>bin\x64\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <DebugType>full</DebugType>
    <PlatformTarget>x64</PlatformTarget>
    <LangVersion>7.3</LangVersion>
    <ErrorReport>prompt</ErrorReport>
  </PropertyGroup>

Error		Unable to resolve resource “MetroButtonTextBox”。	MetroAppTest	C:\Demo\DemoProject\MetroAppTest\MainWindow.xaml	18	

I use 1.6.5 or 2.4.5

Only desgin prompt failed

**Comment by punker76** [comment]
@raozhihao Sorry to hear that you have some trouble with MahApps. If you use x64 then the VS designer can't show this, because the VS designer is 32 bit.
