### ISSUE TITLE
ValidatesOnExceptions=True causes ValidationErrorTemplate to jump around

### ISSUE THREAD

**Issue by pfattisc** [MahApps/MahApps.Metro#4120]
## Describe the bug

Setting **ValidatesOnExceptions=True** on a binding causes the ValidationErrorTemplate to jump to the window title in case of exceptions.

## Steps to reproduce

1. Go to the MahAppsDemo project
2. Add **ValidatesOnExceptions=True** to the enabled TextBox with ValidationError (that binds to IntegerGreater10Property) on the TextExamples.xaml view. [here](https://github.com/MahApps/MahApps.Metro/blob/f1ad3164bb971de9a4775af1efa8b8d04f92ecf3/src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/TextExamples.xaml#L162)
3. Start the demo
4. Enter the TextBox and provoke an error by hitting the spacebar (entering a space instead of a number).

## Expected behavior

The ValidationErrorTemplate should not follow kriss kross and stop jumping around :-P

## Possible Fix
I think [CustomValidationPopup.ScrollViewer_ScrollChanged](https://github.com/MahApps/MahApps.Metro/blob/f1ad3164bb971de9a4775af1efa8b8d04f92ecf3/src/MahApps.Metro/Controls/CustomValidationPopup.cs#L263) is the culprit. The call to RefreshPosition() should be inside of the if-statement that checks whether scrolling actually happened. After I removed that line the jumping stopped. And since the scrollchanged event is fired even if the scrollposition didn't change, I think RefreshPosition() can be safely moved into that if-statement.

## Environment

```
MahApps.Metro version: v2.0.0
Windows build number: Win10 1607
Rider 2021.1.3
Target Framework: .Net v4.7.2
```

## Screenshots

![CustomValidationPopup_Bug](https://user-images.githubusercontent.com/11867529/121476094-8bbc1980-c9c6-11eb-90b0-289717ec7217.gif)

**Comment by punker76** [comment]
@pfattisc Which MahApps version is this?

**Comment by punker76** [comment]
@pfattisc Got it too.
