### ISSUE TITLE
Provide easy way to globally DISABLE FORCED ALL CAPS

### ISSUE THREAD

**Issue by larrye11ison** [MahApps/MahApps.Metro#4126]
It would be **super** convenient to easily disable the forced all caps **globally** for MahApps.Metro. 

I know about the TitleCharacterCasing property of the MetroWindow class, but it seems to only affect that one control. I've also seen a few examples of ways of doing this on other controls, but as far as I can tell, you have to do a fairly involved "restyling" of each control individually to make this happen - it's a lot of XAML code just to turn this one thing off and avoid having your app yell at your users.

If this already exists, apologies in advance. I swear, I really did look pretty extensively and didn't find it!

**Comment by timunie** [comment]
Hi @larrye11ison 

what exactly do you mean by "easy"? There is the `mah:ControlsHelper.ContentCharacterCasing`- Property which controls this. And you can set this for each control separately or by defining your own `Style`. 

Here is an example: 

```xaml
<!-- In your App.xaml -->

<Application
    [...]
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:mah="http://metro.mahapps.com/winfx/xaml/controls"
    [...] >
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <!--  MahApps.Metro resource dictionaries. Make sure that all file names are Case Sensitive!  -->
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Themes/Light.Blue.xaml" />
            </ResourceDictionary.MergedDictionaries>

             <!-- Repeat this for each control-->
            <Style TargetType="{x:Type Button}" BasedOn="{StaticResource {x:Type Button}}">
                <Setter Property="mah:ControlsHelper.ContentCharacterCasing" Value="Normal" />
            </Style>

             <!-- OR if you want to base on another Style than the default -->
            <Style TargetType="{x:Type Button}" BasedOn="{StaticResource MahApps.Styles.Button.Flat}">
                <Setter Property="mah:ControlsHelper.ContentCharacterCasing" Value="Normal" />
            </Style>
        </ResourceDictionary>
    </Application.Resources>
</Application>
```

I think this is easy enough and the way MahApps and WPF works. 

Happy coding 
Tim

**Comment by larrye11ison** [comment]
First off, I really appreciate the project! If someone does not want forced-upper-case, I think it’s incredibly likely they would want that across all controls, not mix-n-match per control type. So it would be really nice if there was one way to opt out of ALL CAPS across the board with one simple "statement” (chunk of XML in app.xaml, or whatever). Another way of putting it – this bit from your info below is what I’m saying makes it “not easy” (or perhaps I should say: “not as easy as my lazy a$$ would like it to be”!):             From: TimSent: Monday, June 14, 2021 1:22 AMTo: MahApps/MahApps.MetroCc: Not Larry Ellison; MentionSubject: Re: [MahApps/MahApps.Metro] Provide easy way to globally DISABLE FORCED ALL CAPS (#4126) Hi @larrye11isonwhat exactly do you mean by "easy"? There is the mah:ControlsHelper.ContentCharacterCasing- Property which controls this. And you can set this for each control separately or by defining your own Style.Here is an example: <Application    [...]    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"    xmlns:mah="http://metro.mahapps.com/winfx/xaml/controls"    [...] >    <Application.Resources>        <ResourceDictionary>            <ResourceDictionary.MergedDictionaries>                                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Themes/Light.Blue.xaml" />            </ResourceDictionary.MergedDictionaries>                          <Style TargetType="{x:Type Button}" BasedOn="{StaticResource {x:Type Button}}">                <Setter Property="mah:ControlsHelper.ContentCharacterCasing" Value="Normal" />            </Style>                          <Style TargetType="{x:Type Button}" BasedOn="{StaticResource MahApps.Styles.Button.Flat}">                <Setter Property="mah:ControlsHelper.ContentCharacterCasing" Value="Normal" />            </Style>        </ResourceDictionary>    </Application.Resources></Application>I think this is easy enough and the way MahApps and WPF works.Happy codingTim—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by timunie** [comment]
@larrye11ison ¿ ? 

Can you please review your answer? Thx

**Comment by larrye11ison** [comment]
Holy crap, I replied to the email and there seems to be some "interesting" additions... Let's try this again, this time directly in Github.

First off, I really appreciate the project!
 
If someone does not want forced-upper-case, I think it’s incredibly likely they would want that across all controls, not mix-n-match per control type. So it would be really nice if there was one way to opt out of ALL CAPS across the board with one small/simple "statement” (chunk of XML in app.xaml, or whatever).
 
Another way of putting it – this bit from your info below is what I’m saying makes it “not easy” (or perhaps I should say: “not as easy as my lazy a$$ would like it to be”!):

**Comment by timunie** [comment]
Hi @larrye11ison 

So yeah I think all developers are lazy a$$es, how else would you come to the idea that the computer should do most stuff? But anyway, having to write a few more lines of code IS easy. It may not be convinient but it IS easy. I think to provide a one liner to you there must be much more done on MahApps side. And this is a free time project, so I think for now you have to live with the code how it works...

Thank you for your understanding
Tim
