### ISSUE TITLE
Title Bar buttons not visible in light theme

### ISSUE THREAD

**Issue by BornToBeRoot** [MahApps/MahApps.Metro#4132]
## Describe the bug

Buttons not visible in light theme. (Maybe the same issue as here https://github.com/MahApps/MahApps.Metro/issues/3194 ?)

I use the MahApps.Styles.MetroWindow.Clean

![image](https://user-images.githubusercontent.com/16019165/122828304-c8044980-d2e5-11eb-9f4a-995b2ca3ba56.png)

![image](https://user-images.githubusercontent.com/16019165/122828374-e1a59100-d2e5-11eb-9b7e-0022bd371e06.png)

## Steps to reproduce
Repo: https://github.com/BornToBeRoot/NETworkManager/

Enable the light theme in the settings

## Environment

```
MahApps.Metro version: latest
Windows build number: Win10 2004
Visual Studio: 2019
Target Framework: 5.0.7
```

**Comment by FroggieFrog** [comment]
I was able to reproduce the problem and also found a solution (or is it a workaround?).
According to your source code in `App.xaml` you are using this line:

https://github.com/BornToBeRoot/NETworkManager/blob/0dbddfcfd6d9a90c9d75059737329bb423137d0d/Source/NETworkManager/App.xaml#L9

If you change it to this line it works:

`<ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Clean/Controls.xaml" />`

The `Controls.xaml` file also contains styles for `WindowButtonCommands` and other controls.

**Comment by BornToBeRoot** [comment]
I will try it. Do you mean the Clean/MetroWindow.xaml (Line 9) or  the Controls.xaml (Line 10) should be replaces with Clean/Controls.xaml ?

**Comment by FroggieFrog** [comment]
I tried it with replacing line 9 and it worked.

**Comment by punker76** [comment]
@BornToBeRoot If you only want the MetroWindow style then you need these resources:

```xaml
<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                    xmlns:mah="clr-namespace:MahApps.Metro.Controls">

    <ResourceDictionary.MergedDictionaries>
        <!-- <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Clean/GroupBox.xaml" /> -->
        <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Clean/MetroWindow.xaml" />
        <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Clean/WindowButtonCommands.xaml" />
        <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Clean/WindowCommands.xaml" />
        <!-- <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Clean/StatusBar.xaml" /> -->
    </ResourceDictionary.MergedDictionaries>

    <!-- <Style BasedOn="{StaticResource MahApps.Styles.GroupBox.Clean}" TargetType="{x:Type GroupBox}" /> -->
    <Style BasedOn="{StaticResource MahApps.Styles.MetroWindow.Clean}" TargetType="{x:Type mah:MetroWindow}" />
    <Style BasedOn="{StaticResource MahApps.Styles.WindowButtonCommands.Clean.Win10}" TargetType="{x:Type mah:WindowButtonCommands}" />
    <Style BasedOn="{StaticResource MahApps.Styles.WindowCommands.Clean}" TargetType="{x:Type mah:WindowCommands}" />
    <!-- <Style BasedOn="{StaticResource MahApps.Styles.StatusBar.Clean}" TargetType="{x:Type StatusBar}" /> -->

</ResourceDictionary>
```

**Comment by BornToBeRoot** [comment]
@punker76 @FroggieFrog Thanks! After adding `Clean/Controls.xaml` the buttons are visible.
