### ISSUE TITLE
Windows 11 integration

### ISSUE THREAD

**Issue by Nuklon** [MahApps/MahApps.Metro#4140]
## Describe the feature

I'm opening this request with a checklist for the upcoming Windows 11 release, I can append where necessary.

- [ ] Snap Layouts integration, see the screenshot below. Right now the maximize button from MahApps isn't detected.
![image](https://user-images.githubusercontent.com/23340481/123783289-7dcb2b80-d8d6-11eb-8ffa-dd860ddeebe8.png)
- [ ] Rounded corners at main window, e.g. with a ```CornerRadius```.
- [ ] Restyled HamburgerMenu, this is pretty similar to the already existing CreatorsUpdate style, but with some additional padding and rounded corners. See below:
![image](https://user-images.githubusercontent.com/23340481/123784220-7f492380-d8d7-11eb-84d1-4a94688bb4bf.png)
- [ ] Rounded flat buttons:
![image](https://user-images.githubusercontent.com/23340481/123784377-ad2e6800-d8d7-11eb-94c2-db8e69db3d4e.png)
- [ ] Rounded context menus.
![image](https://user-images.githubusercontent.com/23340481/123784559-dcdd7000-d8d7-11eb-9687-4f8b6a11b3eb.png)
- [ ] Rounded tooltips.
- [ ] Restyled radio buttons: 
![image](https://user-images.githubusercontent.com/23340481/123784865-2af27380-d8d8-11eb-878f-069558a70e81.png)
- [ ] Restyled check boxes:
![image](https://user-images.githubusercontent.com/23340481/123785042-59704e80-d8d8-11eb-82f2-b09be4a38c74.png)
- [ ] Style/colors (light & dark).

**Comment by DimitarCC** [comment]
Regarding the snap layouts integration...its not so easy. I did this for my own windows (WPF) with custom chrome and its real pain.
You have to detect btton hover and then to handle wndproc WM_NCHITTEST message and to return 9 to it. its really pain in WPF.
Oh and that work but only if you have custom chrome and GlassFrameThickness != 0.

**Comment by pavll** [comment]
I think this could be something to deal with if Windows 11 was officially released for the public and maybe some APIs changed to be more developer-friendly. But a must-have is the rounded corners, rounded context menus, and rounded buttons. Is this something you can integrate?

**Comment by timunie** [comment]
Hi @pavll 

I think the bottle-neck here is that it heavily depends on the free time available as it is a free-time project. So yes, it can be integrated and works already for some controls but when it will be done for every control, nobody knows yet. I hope for your understanding.
 
Happy coding Tim

**Comment by pavll** [comment]
Hi @timunie

Sure, I can understand that. Just wanted to make sure that this is on the "roadmap" ;).

Paul

**Comment by timunie** [comment]
I am just leaving this link here: https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/apply-rounded-corners 

It shows how to apply rounded corners

**Comment by carloslubbers** [comment]
I'm also interested in the Windows 11 style, especially the rounded corners on the main window. 

For now, to achieve this result I've set the following properties on my MetroWindow and Windows 11 seems to properly round the corners for me:
```<Setter Property="WindowChrome.WindowChrome">
    <Setter.Value>
        <WindowChrome CaptionHeight="0"/>
    </Setter.Value>
</Setter>
<Setter Property="WindowStyle" Value="None"/>
```

This doesn't play well with the glow brush, but since I'm not using it this is fine for me.

ControlzEx seems to also be working on an update on the WindowChromeBehavior to possibly allow for the snap layouts and rounded corners:
https://github.com/dotnet/wpf/issues/4825#issuecomment-927342914
https://github.com/ControlzEx/ControlzEx/tree/features/Win11Support

**Comment by Nuklon** [comment]
I don't think this should be closed, there are more items added than just window.

**Comment by punker76** [comment]
@Nuklon I will create a new one or re-open this with some sub tasks.

**Comment by batzen** [comment]
My mistake. Sorry. I should only have referenced this issue...
