### ISSUE TITLE
DataGridNumericUpDownColumn - Error binding properties

### ISSUE THREAD

**Issue by OrihuelaConde** [MahApps/MahApps.Metro#4150]
## Describe the bug

When I try to bind some properties of DataGridNumericUpDownColumn such as Maximum or NumericInputMode I get the next error:

`System.Windows.Data Error: 2 : Cannot find governing FrameworkElement or FrameworkContentElement for target element. BindingExpression:Path=Price; DataItem=null; target element is 'DataGridNumericUpDownColumn' (HashCode=46720306); target property is 'Maximum' (type 'Double')`

## Steps to reproduce

Go to ExampleViews/DataGridExamples.xaml and modify "dataGridNumericUpDownColumn" to bind the maximum:

`<mah:DataGridNumericUpDownColumn x:Name="dataGridNumericUpDownColumn" Binding="{Binding Price}"
                                                 Header="Price"
                                                 Minimum="0"
                                                 StringFormat="{}{0:C}"
                                                 Maximum="{Binding Price}"/>`

## Expected behavior

Bind any property without issue.

## Actual behavior

`System.Windows.Data Error: 2 : Cannot find governing FrameworkElement or FrameworkContentElement for target element. BindingExpression:Path=Price; DataItem=null; target element is 'DataGridNumericUpDownColumn' (HashCode=46720306); target property is 'Maximum' (type 'Double')`

## Environment

```
MahApps.Metro version: v2.4.6
Windows build number: Windows 10 Pro 21H1 [19043.1055]
Visual Studio: 2019 16.8.0
Target Framework: .Net Core 3.1 (v4.5.2, v4.7.2)
```

## Screenshots

![image](https://user-images.githubusercontent.com/12591371/124237795-4cc54380-daee-11eb-9847-709abd21ca4c.png)

![image](https://user-images.githubusercontent.com/12591371/124237887-68c8e500-daee-11eb-922b-f129b0ae79f2.png)

@punker76

**Comment by fredericoregateiro** [comment]
Also, the VS intellisense shows more info
![mahapps_error](https://user-images.githubusercontent.com/6304701/151378948-2f66dbe4-1f30-40f4-9394-07ce1e428615.png)

A NumericUpDown control inside a DataGridTemplateColumn works fine.

**Comment by punker76** [comment]
The problem here is that DataGrid columns are not inside the visual tree, so a normal Binding like yours doesn't work correctly. As a workaround you need to use a proxy like here:

https://github.com/MahApps/MahApps.Metro/blob/df4b55b4a40976aa47f6ac616a683daefc894927/src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/DataGridExamples.xaml#L135

https://github.com/MahApps/MahApps.Metro/blob/df4b55b4a40976aa47f6ac616a683daefc894927/src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/DataGridExamples.xaml#L219-L221
