### ISSUE TITLE
Accent color when Windows determines the accent color itself

### ISSUE THREAD

**Issue by Rerago** [MahApps/MahApps.Metro#4156]
## Describe the bug

Windows 10 has an option:

"Automatically select an accent color from my background".

This will select an accent color based on the background. But the color that MahApps / ControlzEx then sets is unfortunately not the same one that Windows then uses :/

Maybe the error is also in "ControlzEx". But since I only used MahApps I post it here :)

## Steps to reproduce

- create a project (.net 5 for example)
- include MahApps.Metro
- Overwrite "OnStartup" in the App.xaml.cs" and add the following:

```
ControlzEx.Theming.ThemeManager.Current.ThemeSyncMode = ControlzEx.Theming.ThemeSyncMode.SyncAll;
ControlzEx.Theming.ThemeManager.Current.SyncTheme();
```

- In Windows, set the "Automatically select an accent color from my background" setting.

- Compare accent colors

## Expected behavior

That the accent color MahApps.Metro uses is the same as in Windows.

## Actual behavior

The accent color MahApps.Metro uses is not the same as in Windows.
(Usually a little darker than the current color)

## Environment

```
MahApps.Metro version: v2.4.7
Windows build number: Win10 21H1 [Version 119043.1151]
Visual Studio: 2019 16.10.4
Target Framework: .Net Core 5.0 (but also happens in other versions)
```

## Screenshots

![sample](https://user-images.githubusercontent.com/65850767/127779661-e2dcba7a-b597-4b39-8c1a-a04e8ed088ec.png)

## Example project

[MahAccent.zip](https://github.com/MahApps/MahApps.Metro/files/6913084/MahAccent.zip)

Not really useful, but here it is when needed :)

**Comment by batzen** [comment]
Could you have a look at the value from HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM\ColorizationColor and post it here?

**Comment by Rerago** [comment]
So I updated my project again and extended the output with "AccentBase" and "ColorizationColor" (I used the function GetWindowsAccentColor from ControlzEx).

![test](https://user-images.githubusercontent.com/65850767/129171177-58dbde74-a535-40bb-a7cc-e1877828b365.png)

But now to "ColorizationColor". I copied the whole node out:

```
[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\DWM]
"Composition"=dword:00000001
"ColorizationColor"=dword:c41a445b
"ColorizationColorBalance"=dword:00000059
"ColorizationAfterglow"=dword:c41a445b
"ColorizationAfterglowBalance"=dword:0000000a
"ColorizationBlurBalance"=dword:00000001
"EnableWindowColorization"=dword:00000001
"ColorizationGlassAttribute"=dword:00000001
"AccentColor"=dword:ff5b441a
"ColorPrevalence"=dword:00000000
"EnableAeroPeek"=dword:00000001
```

When I take a screenshot of the window settings and use an colorpicker it reads "FF2992CC". I guess Windows adjusts the brightness of the accent color to improve readability, or it selects the accent color from the list that is closest to the read value (ColorizationColor).

[MahAccent.zip](https://github.com/MahApps/MahApps.Metro/files/6974207/MahAccent.zip)

**Comment by timunie** [comment]
Hi @Rerago,

I think Microsoft and MahApps are calculating the colors a bit differently. A change of this would be a breaking change I think, which may or may not happen in the future. But you also can provide your very own `Theme`: https://github.com/ControlzEx/ControlzEx/blob/develop/Wiki/ThemeManager.md#override-the-librarythemeprovider

Happy coding
Tim

**Comment by punker76** [comment]
@Rerago The `MahApps.Brushes.AccentBase` ist the accent color of Windows (the ColorizationColor). All other accent brushes (and colors) in MahApps are a variation of this (80, 60, 40, 20 % transparancy).

**Comment by Rerago** [comment]
@timunie

Why would that be a braking change? ESPECIALLY this is not a bug in MahApps either but rather in ControlzEx (should I make it open there?). MahApps does use 80% alpha on the AccentBase for Accent. But I don't see anything wrong with it.. The real problem is that ControlzEx does not correctly determine the Accent as Windows uses it (which is the purpose of the function). If ControlzEx would determine "FF2992CC" (The color I have determined via color picker). Then in MahApps it would look like this:

![sample](https://user-images.githubusercontent.com/65850767/129367545-d2ce189d-d4df-49c6-8c27-04a5b95f280e.png)
(Fake with RuntimeThemeGenerator)

And that would be perfect. Because as you can see, the value that ControlzEx determines is much too dark.

@Punkter76
I know I only included that for clarification.

@all
I guess the problem is that "ColorizationColorBalance" is not respected. Here:

https://stackoverflow.com/a/24600956

The determined color is mixed with a gray tone, based on "ColorizationColorBalance" (I guess that was Fix back then, today the base color is probably based on Dark or Light).

**Comment by batzen** [comment]
@punker76 Could you transfer this issue to ControlzEx?
I can't see the transfer button...
Will fix it there next week.

**Comment by punker76** [comment]
@batzen It's only possible to transfer inside of an organization. I'll create one at ControlzEx.

**Comment by punker76** [comment]
https://github.com/ControlzEx/ControlzEx/issues/148
