### ISSUE TITLE
Xaml reports binding errors when ColorPicker is in Flyout

### ISSUE THREAD

**Issue by raozhihao** [MahApps/MahApps.Metro#4157]
## This is example

```
  <mah:MetroWindow.Flyouts>
        <mah:FlyoutsControl>
            <mah:Flyout Header="ColorPicker"
                        Theme="Adapt"
                        Position="Right">
                <mah:ColorPicker />
            </mah:Flyout>
        </mah:FlyoutsControl>
    </mah:MetroWindow.Flyouts>
```

This is the error message reported by XAML
>System.Windows.Data Error: 2 : Cannot find governing FrameworkElement or FrameworkContentElement for target element. BindingExpression:Path=SelectedHSVColor; DataItem=null; target element is 'SolidColorBrush' (HashCode=58132325); target property is 'Color' (type 'Color')

>System.Windows.Data Error: 2 : Cannot find governing FrameworkElement or FrameworkContentElement for target element. BindingExpression:Path=SelectedColor; DataItem=null; target element is 'GradientStop' (HashCode=11097898); target property is 'Color' (type 'Color')

>System.Windows.Data Error: 2 : Cannot find governing FrameworkElement or FrameworkContentElement for target element. BindingExpression:Path=SelectedHSVColor; DataItem=null; target element is 'GradientStop' (HashCode=42759282); target property is 'Color' (type 'Color')

I'm not sure if this is a Bug
But it bothers me

**Comment by raozhihao** [comment]
When the application starts up, you can see the binding error message of XAML

**Comment by punker76** [comment]
@raozhihao Which MahApps version?

**Comment by raozhihao** [comment]
@punker76 
MahApps version 2.4.7
.Net Framework 4.5.2

**Comment by raozhihao** [comment]
@punker76 
MahApps version 2.4.8
.Net Framework 4.5.2

This is App.xaml

` <Application.Resources>
        <ResourceDictionary>

            <ResourceDictionary.MergedDictionaries>
                
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
                
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Themes/Light.Blue.xaml" />
            </ResourceDictionary.MergedDictionaries>

          
        </ResourceDictionary>

    </Application.Resources>`

This is MainWindow.xaml

`<mah:MetroWindow x:Class="MahDemo.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
               xmlns:mah="http://metro.mahapps.com/winfx/xaml/controls"
        xmlns:local="clr-namespace:MahDemo"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <mah:MetroWindow.RightWindowCommands>
        <mah:WindowCommands>

            <mah:ToggleSwitch Content="ColorFLyout"
                   Name="ColorFLout" />

       
        </mah:WindowCommands>

    </mah:MetroWindow.RightWindowCommands>
    <mah:MetroWindow.Flyouts>
        <mah:FlyoutsControl>
            <mah:Flyout Header="ColorPicker"
                        Theme="Adapt"
                        Position="Right"
                        IsOpen="{Binding ElementName=ColorFLout,Path=IsOn}">
                <mah:ColorPicker />
            </mah:Flyout>
        </mah:FlyoutsControl>
    </mah:MetroWindow.Flyouts>
    <Grid>
        
    </Grid>
</mah:MetroWindow>
`

When this app loaded
report error msg:

`System.Windows.Data Error: 2 : Cannot find governing FrameworkElement or FrameworkContentElement for target element. BindingExpression:Path=SelectedHSVColor; DataItem=null; target element is 'SolidColorBrush' (HashCode=51545483); target property is 'Color' (type 'Color')
System.Windows.Data Error: 2 : Cannot find governing FrameworkElement or FrameworkContentElement for target element. BindingExpression:Path=SelectedColor; DataItem=null; target element is 'GradientStop' (HashCode=14434584); target property is 'Color' (type 'Color')
System.Windows.Data Error: 2 : Cannot find governing FrameworkElement or FrameworkContentElement for target element. BindingExpression:Path=SelectedColor; DataItem=null; target element is 'GradientStop' (HashCode=28350637); target property is 'Color' (type 'Color')
System.Windows.Data Error: 2 : Cannot find governing FrameworkElement or FrameworkContentElement for target element. BindingExpression:Path=SelectedColor; DataItem=null; target element is 'GradientStop' (HashCode=14700275); target property is 'Color' (type 'Color')
System.Windows.Data Error: 2 : Cannot find governing FrameworkElement or FrameworkContentElement for target element. BindingExpression:Path=SelectedColor; DataItem=null; target element is 'GradientStop' (HashCode=49871633); target property is 'Color' (type 'Color')
System.Windows.Data Error: 2 : Cannot find governing FrameworkElement or FrameworkContentElement for target element. BindingExpression:Path=SelectedColor; DataItem=null; target element is 'GradientStop' (HashCode=13070512); target property is 'Color' (type 'Color')
System.Windows.Data Error: 2 : Cannot find governing FrameworkElement or FrameworkContentElement for target element. BindingExpression:Path=SelectedColor; DataItem=null; target element is 'GradientStop' (HashCode=52078584); target property is 'Color' (type 'Color')
System.Windows.Data Error: 2 : Cannot find governing FrameworkElement or FrameworkContentElement for target element. BindingExpression:Path=SelectedHSVColor; DataItem=null; target element is 'GradientStop' (HashCode=48779793); target property is 'Color' (type 'Color')
System.Windows.Data Error: 2 : Cannot find governing FrameworkElement or FrameworkContentElement for target element. BindingExpression:Path=SelectedHSVColor; DataItem=null; target element is 'GradientStop' (HashCode=58849189); target property is 'Color' (type 'Color')
System.Windows.Data Error: 2 : Cannot find governing FrameworkElement or FrameworkContentElement for target element. BindingExpression:Path=SelectedHSVColor; DataItem=null; target element is 'GradientStop' (HashCode=2055005); target property is 'Color' (type 'Color')
System.Windows.Data Error: 2 : Cannot find governing FrameworkElement or FrameworkContentElement for target element. BindingExpression:Path=SelectedHSVColor; DataItem=null; target element is 'GradientStop' (HashCode=32237730); target property is 'Color' (type 'Color')
System.Windows.Data Error: 2 : Cannot find governing FrameworkElement or FrameworkContentElement for target element. BindingExpression:Path=SelectedColor; DataItem=null; target element is 'GradientStop' (HashCode=61119323); target property is 'Color' (type 'Color')
System.Windows.Data Error: 2 : Cannot find governing FrameworkElement or FrameworkContentElement for target element. BindingExpression:Path=SelectedColor; DataItem=null; target element is 'GradientStop' (HashCode=51718129); target property is 'Color' (type 'Color')
`
