### ISSUE TITLE
Change theme of BaseMetroDialog

### ISSUE THREAD

**Issue by lpereira98** [MahApps/MahApps.Metro#4168]
Hello, im very new to this framework and im trying to change the theme of a BaseMetroDialog.

My goal is simple, if i have an error message i want the theme to be Red, if i have a warning message i want the theme to be Orange and so on.. 
I tried to do something like this:
https://stackoverflow.com/questions/44881218/metrodialog-with-custom-background-color
but i got nothing. 

Now im trying to execute this code:

```
            var themes = ThemeManager.Current.DetectTheme().Resources;
            themes["Theme.ThemeInstance"] = ThemeManager.Current.GetTheme("Light.Red");

            var mySettings = new MetroDialogSettings()
            {
                AffirmativeButtonText = "Hi",
                NegativeButtonText = "Go away!",
                FirstAuxiliaryButtonText = "Cancel",
                CustomResourceDictionary = themes,
                ColorScheme = MetroDialogColorScheme.Theme
            };

             
            MessageDialogResult result = await this.ShowMessageAsync("Hello!", "Welcome to the world of metro! ",
                MessageDialogStyle.AffirmativeAndNegativeAndSingleAuxiliary, mySettings);
```

But it was also unsuccessful.

![image](https://user-images.githubusercontent.com/44083899/130645607-9abf761e-fcf9-4452-a7e0-1d89f5eb9638.png)

But i noticed something interesting, if i change to this:

```
            var themes = ThemeManager.Current.DetectTheme().Resources;
            themes["Theme.ThemeInstance"] = Brushes.Red;

            var mySettings = new MetroDialogSettings()
            {
                AffirmativeButtonText = "Hi",
                NegativeButtonText = "Go away!",
                FirstAuxiliaryButtonText = "Cancel",
                CustomResourceDictionary = themes,
                ColorScheme = MetroDialogColorScheme.Inverted
            };

             
            MessageDialogResult result = await this.ShowMessageAsync("Hello!", "Welcome to the world of metro! ",
                MessageDialogStyle.AffirmativeAndNegativeAndSingleAuxiliary, mySettings);
```
i get an exception:
![image](https://user-images.githubusercontent.com/44083899/130645258-5969c500-87ad-4dbd-9f34-1e91d6e5c85a.png)
which means that, this value is converted somewhere to ControlzEx.Theming.Theme, but still it's never used or displayed.

I'd be very pleased for some help on this!

## Environment

```
MahApps.Metro version: v2.4.7
Windows build number: Win10
Visual Studio: 2019 16.10.2
Target Framework: .Net Core 3.1
```

**Comment by lpereira98** [comment]
Ok i understand now that App.xaml is executed before C# and so, having:
```
            <ResourceDictionary.MergedDictionaries>
                <!-- MahApps.Metro resource dictionaries. Make sure that all file names are Case Sensitive! -->
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
                <!-- Theme setting -->
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Themes/Light.Blue.xaml" />
            </ResourceDictionary.MergedDictionaries>
```
on App.xaml will always make the Dialog blue. 
So, every style must be changed on xaml or in C# and never in both.
I was able to do this on C# only, but it's a bad practice to change styles in C#.

Steps:
Deleted every style in App.xaml
on MainWindow constructor:
```
        public MainWindow()
        {
            InitializeComponent();
            ThemeManager.Current.ChangeTheme(this, ThemeManager.Current.GetTheme("Light.Blue"));
            Application.Current.MainWindow = this;
        }
```

When i wanna display the dialog, i change the style locally 

```
            var themes = ThemeManager.Current.DetectTheme().Resources;
            themes["Theme.ThemeInstance"] = ThemeManager.Current.GetTheme("Light.Red");

            var mySettings = new MetroDialogSettings()
            {
                AffirmativeButtonText = "Hi",
                NegativeButtonText = "Go away!",
                FirstAuxiliaryButtonText = "Cancel",
                CustomResourceDictionary = ThemeManager.Current.GetTheme("Light.Red").Resources,
                ColorScheme = MetroDialogColorScheme.Accented                
            };

             
            MessageDialogResult result = await this.ShowMessageAsync("Hello!", "Welcome to the world of metro! ",
                MessageDialogStyle.AffirmativeAndNegativeAndSingleAuxiliary, mySettings);
```

This will make my dialog look like this:
![image](https://user-images.githubusercontent.com/44083899/130662325-cbcf77a6-b7d3-408e-ac2a-becf3380d422.png)
when all the other styles are still LightBlue.

This is a bad practice and i would like to make a suggestion:

Make ShowMessageAsync to receive a new parameter that can change the color of the Dialog (Red for Error, Orange for Warning, Blue for Info).
Or on this PR https://github.com/MahApps/MahApps.Metro/pull/2282 also add that. If the user wants to display a Error message it should display a Red dialog with a Error icon and so on.

**Comment by timunie** [comment]
Hi @lpereira98 

I think you can pass a custom theme dictionary to the dialog, which will then theme only this particular control. 

If I find some time I'll send you a code snippet.

Happy coding

Tim

**Comment by timunie** [comment]
Hi all

I saw the same, any custom Style or Brush is ignored. So I think this is a bug and should be fixed in a separate ticket. 

The other question is a change request. I think Jan @punker76 should give us a feedback how one should handle that the easiest

Ideas could be
- provide different styles to the dialog (I would prefer this as it is quite flexible and also an icon can be implemented)
- add more properties to change
- add an enum as suggested by you @lpereira98 

Happy coding
Tim

**Comment by matthewsheeran** [comment]
I have tried every bit of code described here against the latest 2.4.9 to no avail as you can see from the code below: has the bug been fixed or feature added as it appears from the Merge above and https://github.com/MahApps/MahApps.Metro/pull/4209 as the only thing that appears to be working for me is setting the theme for the whole application then setting it back again!? :  
`
    public bool? MessageBox(string msg, string title = null, string buttonstext = "OK"/*, ...*/)
    {
        Trace.WriteLine(msg);
        MetroWindow owner = (MetroWindow)Application.Current.MainWindow;
        string cap = title ?? owner.Title;
        // TODO: Apply custom Theme()Theme ChangeTheme(object? target, ResourceDictionary resourceDictionary, Theme newTheme) to the Message Dialog object below and not the whole application... 
        //Theme oldTheme = ThemeManager.Current.DetectTheme(Application.Current);
        ResourceDictionary resourceDictionary = new ResourceDictionary();
        //ResourceDictionary themes = ThemeManager.Current.DetectTheme().Resources;
        MetroDialogSettings settings = new MetroDialogSettings()
        {
            ColorScheme = MetroDialogColorScheme.Accented
        };
        title = Titleise(title).ToUpper().Split(" ,;:|".ToCharArray(), StringSplitOptions.RemoveEmptyEntries).FirstOrDefault();
        switch (title)
        {
            case "INFORMATION":
                //ThemeManager.Current.ChangeTheme(Application.Current, "Light.Cobalt");
                //resourceDictionary.Add("Theme.Instance", ThemeManager.Current.GetTheme("Light.Cobalt"));
                resourceDictionary.Add("Theme.Instance", ThemeManager.Current.GetTheme("Light.Cobalt"));
                break;
            case "WARNING":
                //ThemeManager.Current.ChangeTheme(Application.Current, "Dark.Orange");
                resourceDictionary.Add("Theme.Instance", ThemeManager.Current.GetTheme("Dark.Orange"));
                //themes["Theme.Instance"] = ThemeManager.Current.GetTheme("Dark.Orange");
                break;
            case "ERROR":
            case "FATAL":
                //ThemeManager.Current.ChangeTheme(Application.Current, "Dark.Red");
                resourceDictionary.Add("Theme.Instance", ThemeManager.Current.GetTheme("Dark.Red"));
                //themes["Theme.Instance"] = ThemeManager.Current.GetTheme("Dark.Red");
                break;
            default:
                resourceDictionary.Add("Theme.Instance", ThemeManager.Current.DetectTheme(Application.Current));
                //themes["Theme.Instance"] = ThemeManager.Current.DetectTheme(Application.Current);
                break;
        }
        //settings.CustomResourceDictionary = ThemeManager.Current.GetTheme("Dark.Red").Resources;
        //settings.CustomResourceDictionary = ThemeManager.Current.GetTheme("Theme.Instance").Resources;
        settings.CustomResourceDictionary = resourceDictionary;
        MessageDialogStyle buttons = ButtonsStyle(buttonstext, ref settings);
        Task<MessageDialogResult> task = owner.ShowMessageAsync(cap, msg, buttons, settings);
        while (!task.IsCompleted)
            Application.Current?.Dispatcher?.Invoke(DispatcherPriority.Background, (Action)(() => { }));
        //ThemeManager.Current.ChangeTheme(Application.Current, oldTheme);
        return task.Result == MessageDialogResult.Affirmative;
    }
`

**Comment by matthewsheeran** [comment]
This is not desirable but works although it is not possible to get to the Task and change its theme once created nor do I wish to muck around with custom XAML Styles etc.:

    public bool? MessageBox(string msg, string title = null, string buttonstext = "OK"/*, ...*/)
    {
        Trace.WriteLine(msg);
        MetroWindow owner = (MetroWindow)Application.Current.MainWindow;
        string cap = title ?? owner.Title;
        // TODO: Apply custom Theme()Theme ChangeTheme(object? target, ResourceDictionary resourceDictionary, Theme newTheme) to the Message Dialog object below and not the whole application... 
        Theme oldTheme = ThemeManager.Current.DetectTheme(Application.Current);
        MetroDialogSettings settings = new MetroDialogSettings()
        {
            ColorScheme = MetroDialogColorScheme.Accented
        };
        title = Titleise(title).ToUpper().Split(" ,;:|".ToCharArray(), StringSplitOptions.RemoveEmptyEntries).FirstOrDefault();
        switch (title)
        {
            case "INFORMATION":
                ThemeManager.Current.ChangeTheme(Application.Current, "Light.Cobalt");
                break;
            case "WARNING":
                ThemeManager.Current.ChangeTheme(Application.Current, "Dark.Orange");
                break;
            case "ERROR":
            case "FATAL":
                ThemeManager.Current.ChangeTheme(Application.Current, "Dark.Red");
                break;
            default:
                break;
        }
        MessageDialogStyle buttons = ButtonsStyle(buttonstext, ref settings);
        Task<MessageDialogResult> task = owner.ShowMessageAsync(cap, msg, buttons, settings);
        while (!task.IsCompleted)
            Application.Current?.Dispatcher?.Invoke(DispatcherPriority.Background, (Action)(() => { }));
        ThemeManager.Current.ChangeTheme(Application.Current, oldTheme);
        return task.Result == MessageDialogResult.Affirmative;
    }

**Comment by matthewsheeran** [comment]
Can I get an answer here or should I have a new issue!?
Thanks in advance.
Matthew

**Comment by punker76** [comment]
@matthewsheeran The issue was fixed in #4209 and will be available with v3.0 (in the meantime you can use the pre-release from the appveyor nuget feed or compile the source by yourself). Thx

**Comment by matthewsheeran** [comment]
OK, Thankyou for the heads up: just killed the new Issue I began creating.
Is the appveyor nuget feed a big deal to setup? A HowTo!?..
Don't particularly want to compile all of the source (looks to be the "develop" branch) although maybe I should as I'll learn something and be able to look into the codebase.
Otherwise what is your ETA on 3.0 anyways?? Thanx.

**Comment by punker76** [comment]
@matthewsheeran Add this link to your NuGet config or in the VS

![image](https://user-images.githubusercontent.com/658431/166911688-25417c7f-e955-4282-a87d-9f9b144b0d1b.png)

![2022-05-05_13h12_35](https://user-images.githubusercontent.com/658431/166912207-604fa396-fd33-47b3-b7fe-53f4673b6c9b.png)

![2022-05-05_13h13_47](https://user-images.githubusercontent.com/658431/166912220-eeaf1897-6673-4d2b-a7c7-ae2ea8f3eab4.png)

**Comment by matthewsheeran** [comment]
https://ci.appveyor.com/nuget/mahapps.metro: only gives 2.4.9.
https://ci.appveyor.com/project/punker76/mahapps-metro/branch/develop: [Package source MahApps] 'doctype' is an unexpected token. The expected token is 'DOCTYPE'. Line 1, position 3.

BUT its ok I'll just grab and build a snapshot of "develop" source for now..

Thanks for your help!
