### ISSUE TITLE
MahApps.Metro v2.4.8 uses wrong version range for ControlzEx dependency

### ISSUE THREAD

**Issue by punker76** [MahApps/MahApps.Metro#4194]
### Discussed in https://github.com/MahApps/MahApps.Metro/discussions/4193

<div type='discussions-op-text'>

<sup>Originally posted by **pkMoser** October 14, 2021</sup>
I would like to update MahApps.Metro v2.4.8 via NuGet package, but I got this error:
"Unable to resolve dependencies. 'ControlzEx 5.0.1' is not compatible with 'MahApps.Metro 2.4.8 constraint: ControlzEx (>= 4.4.0 && < 5.0.0)'"
Is it possible to change this constraint?
Thank you for your response.</div>

**Comment by gabriel-vanca** [comment]
This problem occurs again now.
I'm getting: 	`Unable to resolve dependencies. 'ControlzEx 6.0.0' is not compatible with 'MahApps.Metro 2.4.10 constraint: ControlzEx (>= 4.4.0 && < 6.0.0)'.			`

**Comment by punker76** [comment]
@gabriel-vanca Is there perhaps another package that has a higher dependency on ControlzEx?

**Comment by gabriel-vanca** [comment]
I doubt that's the problem. I've tried with `-IgnoreDependencies` too. Still getting this error:

```
One or more unresolved package dependency constraints detected in the existing packages.config file. All dependency constraints must be resolved to add or update packages. If these packages are being updated this message may be ignored, if not the following error(s) may be blocking the current package operation: 'MahApps.Metro 2.4.10 constraint: ControlzEx (>= 4.4.0 && < 6.0.0)'
Update-Package : Unable to resolve dependencies. 'ControlzEx 6.0.0' is not compatible with 'MahApps.Metro 2.4.10 constraint: ControlzEx (>= 4.4.0 && < 6.0.0)'.
At line:1 char:1
+ Update-Package -IgnoreDependencies -IncludePrerelease -ToHighestPatch ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.UpdatePackageCommand
```

**Comment by Ntiwari03** [comment]
This change #4193 was submitted in Oct 2021 with MahApps.Metro/2.4.9 which has dependency constraint.
https://www.nuget.org/packages/MahApps.Metro/2.4.9

MahApps.Metro/2.4.10 was released on 7/6/2023

Post this ControlzEx/6.0.0 was released in July 2023. So, we need to have another version of MahApps.Metro/2.4.11 which must modify constraint: ControlzEx (>= 4.4.0 && < 6.0.0)' **to =>** ControlzEx (>= 4.4.0 && <= 6.0.0)'
https://www.nuget.org/packages/ControlzEx/6.0.0

**Comment by punker76** [comment]
@Ntiwari03 ControzlEx v6 is not compatible to MahApps v2.4.x. So if you have ControlzEx v6 installed, then you can only use MahApps v3 pre-alpha.

**Comment by Ntiwari03** [comment]
@punker76 Please let me know latest stable compatible versions of ControzlEx and MahApps.

**Comment by timunie** [comment]
@Ntiwari03 

> Install-Package : Unable to resolve dependencies. 'ControlzEx 6.0.0' is not compatible with 'MahApps.Metro 2.4.10 constraint: ControlzEx (>= 4.4.0 && < 6.0.0)'. 

this message means the version must be bigger than 4.4.0 and must be smaller than 6.0.0. ► So any package with version 5.*.* should be fine.
