### ISSUE TITLE
Why does this ClearTextButton not display an X

### ISSUE THREAD

**Issue by dante502** [MahApps/MahApps.Metro#4205]
![微信截图_20211104161053](https://user-images.githubusercontent.com/13428148/140279239-0f3ea313-9580-4b80-a89c-d492421ded80.png)

**Comment by timunie** [comment]
Hi @dante502 

Looks like a Font is wrong or missing on your end. Please create a sample repo on github and post the link here. Thank you

Happy coding
Tim

**Comment by punker76** [comment]
@dante502 It would be nice if you can create a sample (on GitHub) which shows this issue. Thx.
