### ISSUE TITLE
Drop .NET Framework 4.5.2 and 4.6 which will reach End of Support on April 26, 2022

### ISSUE THREAD

**Issue by punker76** [MahApps/MahApps.Metro#4214]
## Describe the feature

Would it make sense to stop supporting .Net 4.5.2 and 4.6 right now? After all, the end date is April 2022.

## Additional context

https://devblogs.microsoft.com/dotnet/net-framework-4-5-2-4-6-4-6-1-will-reach-end-of-support-on-april-26-2022/#closing

**Comment by timunie** [comment]
Hi Jan, 

even Windows 7 can run .Net 4.8 and .Net 5.0 (tested it recently), So I think dropping the older versions should be no problem in most cases. 

Have a great Sunday
Tim
