### ISSUE TITLE
Could not load file or assembly 'MahApps.Metro, Culture=neutral' or one of its dependencies. The system cannot find the file specified.

### ISSUE THREAD

**Issue by Learn123-hash** [MahApps/MahApps.Metro#4225]
I just downloaded MahApps off of nuget package installer inside of visual studio. And I am definitely missing a step because its too easy but I cant find that other step. I get those errors in the pictures and I thought i solved it in my other project but all the controls just went black and showed nothing being able to interact with. Im pretty sure that i need to download some more stuff or change the directory, im really new to wpf so help is appreciated. 

```
MahApps.Metro version: v2.0.0
Windows build number: Win10 1909 [Version 10.0.18363.836]
Visual Studio: 2021
Target Framework: .Net Core 3.1 (v4.5.2, v4.7.2)
```

## Screenshots

![](https://user-images.githubusercontent.com/52952472/144794885-5d7b0a1f-909c-4e51-9c93-411e48cfba84.PNG)

![](https://user-images.githubusercontent.com/52952472/144794877-67821cd5-8861-48cc-a1fb-f6050e44880f.PNG)

**Comment by timunie** [comment]
Hi @Learn123-hash 

First if all please do not report a bug if there is no bug. You can use [discussions](https://github.com/MahApps/MahApps.Metro/discussions) or [gitter](https://gitter.im/MahApps/MahApps.Metro) to ask questions like this. 

Back to your issue: Please make sure you read the start guide: https://mahapps.com/docs/guides/quick-start . Moreover you may want to download the source code and play around with the sample app. 

Happy coding 
Tim

**Comment by punker76** [comment]
@Learn123-hash Do you still have problems with it?

**Comment by MrCoolAndroid** [comment]
1 - Oh sorry, i answered it because it was the only one having my exact issue.
2 - Those are the only errors i have, in my previous PC i installed MahApps with NuGet and everything was OK, before moving to this PC i uploaded the code to a private GitHub repository and then i cloned it with VS and MahApps wont work, i tried reinstalling it but nothing, i got back to my previous PC and i tried to clone the repository too and there it did work, i dont know what is wrong

**Comment by timunie** [comment]
Do you have the NET-Runtime all installed? 
Maybe try clean and rebuild?

**Comment by MrCoolAndroid** [comment]
Yes i have .NET installed, im gonna try that rn

**Comment by timunie** [comment]
It needs to be the exact version you use in your App. So if you target NET 4.8, you need to install 4.8 SDK.

**Comment by MrCoolAndroid** [comment]
Thanks for your help! looks like cleaning and recompiling worked
