### ISSUE TITLE
Question: how to override Button styles?

### ISSUE THREAD

**Issue by HunteRoi** [MahApps/MahApps.Metro#4229]
I could not find anything related to directly overriding nor extending existing MahApps styles for buttons but I would like to be able to add margin, padding and change the border color of a button when it is selected/focused/pressed.

Do you happen to have the solution? I'm using .NET Framework 4.6.1 for a WPF app with MahApps.Metro v2.4.9.

**Comment by RayCarrot** [comment]
If you create a style without a key it will be treated as the default style for that control type. Then you can base if off of an existing style if you just want to change a few of the properties. For example:
```xaml
<Style TargetType="{x:Type Button}" BasedOn="{StaticResource MahApps.Styles.Button}">
    <Setter Property="Margin" Value="10" />
</Style>
```
You can also base it off of the previous default button style by using the type as the key:
```xaml
<Style TargetType="{x:Type Button}" BasedOn="{StaticResource {x:Type Button}}">
    <Setter Property="Margin" Value="10" />
</Style>
```

**Comment by HunteRoi** [comment]
Thank you very much!!

**Comment by amitha-achar** [comment]
Hi, Can you help me here. I am using the MahApps button  for WPF  and i want to change the trigger related to that .When the button is disabled, i want to change the foreground colour to black , instead of transparent. How can i do it from app.xaml. This should be for buttons across my application.
