### ISSUE TITLE
MultiSelectionComboBox SelectedItems Duplicate

### ISSUE THREAD

**Issue by Time2Code0** [MahApps/MahApps.Metro#4245]
## Describe the bug

I played around a bit with the MultiSelectionComboBox control and noticed that the SelectedItems are duplicated from the beginning. As you can see in the attached screenshot, there are always two instances of Dog, Cat and Zebra. For example, if you deselect Dog, the other instance remains selected.

## Steps to reproduce

For a better overview I created the following branch which generates the output shown in the screenshot.

https://github.com/Time2Code0/MahApps.Metro/tree/MultiSelectionComboBoxIssueSample

## Expected behavior

There should be only one instance of the selected item.

## Environment

MahApps.Metro version: v3.0.0
Visual Studio: 2022

## Screenshots

![Issue](https://user-images.githubusercontent.com/47297708/149312960-287782c4-7797-4d12-9af9-ce95e8aa1bdb.png)

**Comment by timunie** [comment]
Hi @Time2Code0,

I also have seen this when I was developing the control. But I have not found a way around this 😢 . The `ListBox` in the `Popup` triggers the selection when it first renders. If you have an idea how to solve this issue, I would be happy about any input. 

Happy coding
Tim

**Comment by Arvidas** [comment]
Downloaded and compiled yesterday.
