### ISSUE TITLE
Themes not work

### ISSUE THREAD

**Issue by tqk2811** [MahApps/MahApps.Metro#4246]
## Describe the bug
I follow `Quick Start` and result is back-light only.   
   
![image](https://user-images.githubusercontent.com/13986296/149618676-29893c88-212e-4b97-9f02-6136f26b9930.png)

```xaml
<Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Themes/Light.Blue.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>
```
## Steps to reproduce
I try to change `Light.Red.xaml` or some color list [here](https://mahapps.com/docs/themes/usage) ..... but result only black
`<ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Themes/Light.Red.xaml" />`

And `Dark.Blue`   
![image](https://user-images.githubusercontent.com/13986296/149619001-62d12efb-3a76-4913-b5f3-d32923283ad9.png)

## Environment

```
MahApps.Metro version: v2.4.9 
Windows build number: Win10 21h2
Visual Studio: 2022 17.0.4
Target Framework: .Net Framework 4.6.2
```

**Comment by punker76** [comment]
@tqk2811 You forgot to use the MetroWindow https://mahapps.com/docs/guides/quick-start#using-the-metrowindow
