### ISSUE TITLE
MessageDialog—— part of the affirmative button is not visible

### ISSUE THREAD

**Issue by li-zheng-hao** [MahApps/MahApps.Metro#4254]
## Describe the bug

![image](https://user-images.githubusercontent.com/22129824/150640996-33b29f34-801e-4cdb-a766-4a905cac9ce4.png)

when window width is min enough, part of the affirmative button is not visible. 

## Steps to reproduce

1. run  official demo.
2. click 'Dialogs'->'Show MessageDialog'.
3. reduce window width.

-->

## Expected behavior

when i reduce window width, i want the content of dialog can show completely at first, the blank area at left and right area can becom smaller.

## Actual behavior

the blank area is fixed ( may be set minwidth at some place?) , and the area of ​​the affirmative  button becomes partially visible

## Environment

```
MahApps.Metro version: v2.4.7
Windows build number: Win10
Visual Studio: 2022
Target Framework: .net framework 4.8
```

## My Question

Is there any way to set the blank area on both sides ？

**Comment by punker76** [comment]
@li-zheng-hao You can change this with the DialogContentMargin and DialogContentWidth properties.

https://github.com/MahApps/MahApps.Metro/pull/3518
