### ISSUE TITLE
Real-time plot flickering with MahApps.Metro controls 

### ISSUE THREAD

**Issue by alxkalinin** [MahApps/MahApps.Metro#4273]
## Describe the bug

I use [OxyPlot](https://github.com/oxyplot/oxyplot) library for real-time plotting in my WPF application. Now I want to use MahApps.Metro controls to improve visual style of my application.

But with MahApps.Metro controls the real-time plot is flickering. See demo video below.

Clear WPF application

https://user-images.githubusercontent.com/97022983/154469066-40fe2949-6020-42ee-97a1-19c63314fa54.mp4

WPF application with MahApps.Metro controls

https://user-images.githubusercontent.com/97022983/154469131-e8f1938c-f653-4e0c-86d3-f68f8c4ae75f.mp4

## Steps to reproduce

Please see [MahAppsRTPlotDemo demo application](https://github.com/alxkalinin/MahAppsRTPlotDemo) where the bug is demonstrated. 

With clear WPF application real-time plot works good. But after adding the MahApp styles into the App.xml

```xml
          <ResourceDictionary.MergedDictionaries>
              <!--  Comment the line below to remove the flickering from the plot  -->
              <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
          </ResourceDictionary.MergedDictionaries>
```
we got a flickering.

## Environment

```
MahApps.Metro version: v2.4.9
Windows build number: Windows 10 21H1 [OS Build 19043.1526]
Visual Studio: 2022
Target Framework: .Net 6.0
```

**Comment by alxkalinin** [comment]
I solve the problem by setting the parameter `SnapsToDevicePixels="False"`
```
        <GroupBox
            Width="200"
            Height="200"
            Margin="5"
            SnapsToDevicePixels="False">
            <oxy:PlotView Background="Transparent" Model="{Binding PlotModel}" />
        </GroupBox>
```

So probably this is not a bug, but the feature.

**Comment by punker76** [comment]
@alxkalinin Thx for the hint. The GroupBox style uses `SnapsToDevicePixels="True"` as the default. You can also set it directly to the PlotView:

```xaml
<oxy:PlotView Background="Transparent" Model="{Binding PlotModel}" SnapsToDevicePixels="False" />
```

**Comment by punker76** [comment]
@alxkalinin If you use the UseLayoutRounding then it will also stay pixel tune

```
        <GroupBox
            UseLayoutRounding="True"
            Width="200"
            Height="200"
            Margin="5">
            <oxy:PlotView Background="Transparent" Model="{Binding PlotModel}" SnapsToDevicePixels="False" />
        </GroupBox>
```

![oxyplot](https://user-images.githubusercontent.com/658431/154505328-12316c5a-bfbc-4792-8288-e5cf8e1024d8.gif)

![oxyplot2](https://user-images.githubusercontent.com/658431/154505366-9867e0d2-446b-4a3f-a534-1190d0fa69cc.gif)
