### ISSUE TITLE
DateTimePicker no longer supports milliseconds.

### ISSUE THREAD

**Issue by adamhewitt627** [MahApps/MahApps.Metro#4274]
My project requires millisecond timing in selecting dates. Under 1.6.5, we were able to re-template to add this because SelectedTime was a separate property.

Now that the only reading of time comes from GetSelectedTimeFromGUI, we cannot override that handling.

I'd like to propose that GetSelectedTimeFromGUI simply be made virtual.

**Comment by punker76** [comment]
@adamhewitt627 What about adding an optional millisecond selector?

**Comment by adamhewitt627** [comment]
That's certainly an option, though my project prefers a text entry there.

I can extend the control to bind the time to the box I'm adding, but SelectedDateTime gets set to null when the calendar date changes because `GetSelectedTimeFromGUI` returns null.
