### ISSUE TITLE
ColorPicker CloseOnSelectedColorChanged

### ISSUE THREAD

**Issue by PJonHar** [MahApps/MahApps.Metro#4278]
The property CloseOnSelectedColorChanged is not available on the ColorPicker control?

MahApps.Metro version: v2.4.9

![image](https://user-images.githubusercontent.com/1200267/156325617-2ad0cc98-ad71-4509-9437-23706e691304.png)

**Comment by PJonHar** [comment]
@punker76 , thanks. Whats the reasoning behind that?

**Comment by timunie** [comment]
Hi @PJonHar ,

It's just a new feature which was not released yet. Will be available in the next release. 

The work for preparing the next release is ongoing, so you will need to be a bit patience if you don't want to use a preview. As this is a free-time project, there is no due date. 

Happy coding
Tim

**Comment by PJonHar** [comment]
No worries, thanks for the info.
