### ISSUE TITLE
Flyout theme in MainWindow adapts to a theme generated for a different Metro Window

### ISSUE THREAD

**Issue by JendolaRajda** [MahApps/MahApps.Metro#4280]
## Describe the bug

I have a MahApps Flyout control as a part of my app's MainWindow, the main window gets a theme set upon loading up based on the app's configuration. Part of the app are multiple other Metro windows, which may have a different theme set in the configuration and this theme is set upon the MetroWindow_Loaded event. If this theme is generated form a .NET palette colour or a hexadecimal value by the ControlzEx RuntimeThemeGenerator, the colours in the Flyout in MainWindow change to those of the newly generated theme, while the rest of the MainWindow remains in its actual theme (as it should).

## Steps to reproduce

1. Have a MainWindow with a Flyout
2. Open a new MetroWindow with its own theme generated upon loading.
3. Open a Flyout in the MainWindow
4. Inspect its colours.

I made a simple sample here: [https://github.com/JendolaRajda/FlyoutThemingBug](https://github.com/JendolaRajda/FlyoutThemingBug)

## Expected behavior

I expect the theme to remain the same for all aspects of the MainWindow.

## Actual behavior

It seems like the Flyout captures the event of a different theme being generated (albeit for a different Metro Window) and adapts its colours to the newly generated runtime theme.

## Environment

```
MahApps.Metro version: v2.4.9
Visual Studio: 2019 16.11.7
Target Framework: .Net Framework 4.8
```

## Screenshots

Before opening the new window:
![Screen Shot 03-25-22 at 03 09 PM](https://user-images.githubusercontent.com/82883371/160136960-75067723-0d7b-43b4-8a79-223b3d807fa2.PNG)

After:
![Screen Shot 03-25-22 at 03 09 PM 001](https://user-images.githubusercontent.com/82883371/160137011-da5d1b40-9114-4250-9995-996846063dd5.PNG)

**Comment by batzen** [comment]
This is a "duplicate" of #4096 which should be part of the version 3.0 release.
