### ISSUE TITLE
What's with the slogan? It means the team has a political stance?

### ISSUE THREAD

**Issue by Luoyingliang** [MahApps/MahApps.Metro#4281]
What's with the slogan? It means the team has a political stance?  

This is your political stance?  

so, When America invaded Afghanistan,where you are? what you done?  

When the United States invaded Libya,where you are? what you done?  

When the United States invaded Iraq,where you are? what you done?  

When the United States invaded Iraq,where you are? what you done?  

When Ukrain slaughtered the people of Donbas,where you are? what you done?  

Many people died in wars initiated by the United States，you don't see that？

**Comment by Luoyingliang** [comment]
The United States has created the COVID-19 and many people died on COVID-19，what‘ you done?

**Comment by Luoyingliang** [comment]
The United States has established more than 300 laboratories around the world to manufacture chemical and biological weapons，do you know that?

**Comment by jamesport079** [comment]
🍿🍿🍿
