### ISSUE TITLE
Slider (Win 10 Default Style) Thumb Height

### ISSUE THREAD

**Issue by MrJacquers** [MahApps/MahApps.Metro#4287]
I'm trying to change the height of the slider's thumb, but I'm only able to change the older style's thumb so far. Any help / suggestions welcome. Thanks.

**Comment by Jacques-eMediaIT** [comment]
I had a look in the source code and there doesn't seem to be an easy way to do it via styles. I ended up using a VisualTreeHelper in code to set the height of the MetroThumb.
