### ISSUE TITLE
Cannot use MultiSelectionComboBox. The control is not found.

### ISSUE THREAD

**Issue by efdiloreto** [MahApps/MahApps.Metro#4292]
## Describe the bug

Cannot find MultiSelectionComboBox.

## Steps to reproduce

1. Create a simple MetroWindow
2. Try to create a MultiSelectionComboBox Control.

## Expected behavior

Use the control normally.

## Actual behavior

Cannot find the Control.

## Environment

```
MahApps.Metro version: v2.0.0
Windows build number: Win10 1909 [Version 10.0.18363.836]
Visual Studio: 2022
Target Framework: .Net Framework 4.8
```

## Screenshots

![4nUecuFCrS](https://user-images.githubusercontent.com/23631382/164726777-e87a16d8-8ff3-42fd-bd93-28abeb230a3a.png)
![IsBkaMwSSC](https://user-images.githubusercontent.com/23631382/164726784-b578077f-d28f-45aa-99f8-8b46d0d9e5e9.png)
![R32VZYKWAr](https://user-images.githubusercontent.com/23631382/164727419-ba09a6b9-1afb-4676-a44f-bb6e3ed19a4c.png)

**Comment by timunie** [comment]
This will be available in v3.0 or as a prerelease if you download the latest preview.

Happy coding
Tim

**Comment by timunie** [comment]
Sure. Read this chapter https://mahapps.com/docs/guides/quick-start#installation

**Comment by punker76** [comment]
@bsr203 You can add additional NuGet feeds to VS. If you add this https://ci.appveyor.com/nuget/mahapps.metro feed then you will get also pre-releases.

![image](https://user-images.githubusercontent.com/658431/169228223-afc49928-bed5-4507-b170-6443be51ad84.png)
