### ISSUE TITLE
Display attribute breaks Watermark text

### ISSUE THREAD

**Issue by AndrzejKl** [MahApps/MahApps.Metro#4295]
## Describe the bug

Hi,
I'm using floating Watermarks and works fine, but I want to use also Display attribute, and watermark dissapear.
I try to use AutoWatermark property, just watermark, but when Display attribute is set, watermark dissapear.
Any advice?

## Steps to reproduce

Just add to property Display attribute and watermark dissapear;

## Environment

```
MahApps.Metro version: v2.4.9
Windows build number: Win10 
Visual Studio: 2022 17.1.6
Target Framework: .Net Core 6
```

**Comment by punker76** [comment]
@AndrzejKl That's by design. If you use the AutoWatermark then the Watermark property will be set by the Display attribute of the property.

**Comment by AndrzejKl** [comment]
@punker76 , But, it's not. Display attribute is set, but in xaml watermark is empty.
I try to prepare demo solution.

**Comment by AndrzejKl** [comment]
@punker76 please check it: https://github.com/AndrzejKl/WatermarkIssue

**Comment by punker76** [comment]
@AndrzejKl Finally found your mistake. Instead using `[Display(Name = "Watermark")]` you need to use `[Display(Prompt = "Watermark")]`

![image](https://user-images.githubusercontent.com/658431/172055947-a7eb1436-3d62-41ed-9879-550b83e9f647.png)
