### ISSUE TITLE
Drag & Drop TabItem reordering

### ISSUE THREAD

**Issue by Dimigergo** [MahApps/MahApps.Metro#4304]
Is it possible to make TabItems reorderable with drag & drop?

Thanks in advance!

**Comment by punker76** [comment]
@Dimigergo Yes, you can use e.g. one of these libs or implement it self

- [Dragablz](https://github.com/ButchersBoy/Dragablz)
- [gong-wpf-dragdrop](https://github.com/punker76/gong-wpf-dragdrop)
