### ISSUE TITLE
DateTimePicker display only Date

### ISSUE THREAD

**Issue by valimaties** [MahApps/MahApps.Metro#4308]
Please add a boolean DependencyProperty in DateTimePicker control to be able to show or hide time portion in textbox area of DateTimePicker, and also in dropdown popup. 
For example, supposing this property will be named `DisplayTime`, if this DisplayTime property is false, then the clock and the comboboxes which allow user to select the time (hours, minutes..) whill be collapsed. If it is true, they will be displayed.

**Comment by punker76** [comment]
@valimaties Is it not possible for you to use the normal DatePicker?
