### ISSUE TITLE
NewUpperValue in RangeSlider is wrong

### ISSUE THREAD

**Issue by guyber** [MahApps/MahApps.Metro#4325]
## Describe the bug

NewUpperValue is not updated correctly in the RangeSelectionChanged event.

## Steps to reproduce

RangeSlider set with value 0-9999, when moving the range selection upper value to 14.2% (1/7) of the slider the NewUpperValue shows the value of ~1600, now drag the range so the lower side is on the same position (14.2%) - the value is around ~1400 - seems like the NewUpperValue is driffted for some reason - maybe related o the range between the upper and lower ends - but looks like a bit more complicated issue.

## Expected behavior

NewUpperValue  & NewLowerrValue values of the same location should be the same

## Actual behavior

the values are not the same for the same location

## Environment

```
MahApps.Metro version: v2.0.0
Windows build number: Win10 1909 [Version 10.0.18363.836]
Visual Studio: 2019 16.6.0
Target Framework: .Net Core 3.1 (v4.5.2, v4.7.2)
```

## Screenshots

![range slider](https://user-images.githubusercontent.com/7201649/177161083-de7ab761-6063-40ea-818a-6c1e891f03ec.png)

**Comment by punker76** [comment]
@guyber I can not reproduce this with the current source (dev). So it's better to create a sample with your issue for better debugging. Thx
