### ISSUE TITLE
Square Button light theme disabled status is too subtle to notice... 

### ISSUE THREAD

**Issue by Montago** [MahApps/MahApps.Metro#4330]
I have a button which is styled with MahApps (Current 2.5.0 pre-release ?.. latest from GIT) 
It's bound to a Command which IS functional - I have confirmed that the CanExecute is correctly returning false AND i've confirmed that the button can't be clicked nor does the hover style get activated. 

![image](https://user-images.githubusercontent.com/456040/178938087-9165a820-6efc-4429-8bc7-fce418b53f14.png)

`<Button Height="28"
		Padding="10,0"
		BorderThickness="1"
		Command="{Binding UpdateRegisterCommand}"
		Content="Opdater Register"
		Style="{DynamicResource MahApps.Styles.Button.Square}" />`

It looks like it blinks when i click it and then stays with the normal style until the CommandBinding activates the button again. 

I've tried re-organizing the CommandExecute method in various ways, with or without async - as well as trying various combinations of moving logic to Application Dispatcher.. 

Weird enough i have several other buttons that works perfectly with the "IsEnabled" binding - the buttons and text gray out like it should.

**Comment by Montago** [comment]
I just tried re-writing all the code related to this button.. 

now i'm using IsEnabled with a binding and the style still show as "enabled" ... I can't click the button nor does it change style when i hover it. 

so weird ...

**Comment by Montago** [comment]
Just discovered that all the buttons and checkboxes in thie whole usercontrol has similar issues. 
That they dont change style when disabled.........

**Comment by Montago** [comment]
Seems like the Light version are missing the Disabled colors while the Dark version has them... 

![image](https://user-images.githubusercontent.com/456040/178947210-a77a179c-ff6c-4afd-9b22-577e84aa81c6.png)

![image](https://user-images.githubusercontent.com/456040/178947323-7bb126cd-15be-49ce-95b0-7a4dcecfaa68.png)

**Comment by Montago** [comment]
Heh ... Apparantly the difference between Enabled and Disabled for the light theme is just too subtle to notice. 

![image](https://user-images.githubusercontent.com/456040/178947802-3872bfe3-3c2b-4621-b90a-7bb8bd583fb8.png)

**Comment by Montago** [comment]
suggested fix: 

`<Trigger Property="IsEnabled" Value="False">
							<Setter TargetName="DisabledVisualElement" Property="Opacity" Value="0.7" />
							<Setter Property="Background" Value="{DynamicResource MahApps.Brushes.Gray5}" />
							<Setter Property="Foreground" Value="{DynamicResource MahApps.Brushes.Gray1}" />
						</Trigger>`

**Comment by Montago** [comment]
Wow.. you removed the buttons? 
Which ones should i use now ? 😅

The Win10/11 button style doesn't match the rest of the 'metro' app.

**Comment by punker76** [comment]
I removed the MetroSquare styles the other Square styles are still there.

**Comment by Montago** [comment]
Ahh cool, I'll fetch the latest build and have a look
