### ISSUE TITLE
StatusBar binding a  value was not displayed

### ISSUE THREAD

**Issue by sawanhai** [MahApps/MahApps.Metro#4337]
## Describe the bug
i try to binding status ,and when keydown change status value. but OnHotKey method and propertyChanged event was not display status value to  window;

## Steps to reproduce
clone code, and edit MahApps.Metro demo;
MainWindowViewModel.cs
```C#
private async Task OnHotKey(object sender ,HotKeyEventArgs e){ 
       this NumericUpDownValue =2;
}
```
MainWindow.xaml
```
<StatusBar Grid.Row ="2">
     <StatusBarItem>number value</StatusBarItem>
     <StatusBarItme Content="{Binding NumericUpDownValue,Mode=TwoWay,UpdateSourceTrigger=PropertyChanged}" />
</StatusBar>
```
build and run ,keydown hotKey ;default ctrl+shift+home;

## Expected behavior
StatusBar should show number value :2 ;

## Actual behavior
StatusBar doesn't change;

## Environment
MahApps.Metro version: v2.4.9
Windows build number: Win10 
Visual Studio: 2019 16.8.3
Target Framework: .Net 4.5.2

**Comment by punker76** [comment]
@sawanhai I checked this with the current source but doesn't get your issue.

```xaml
<StatusBar Grid.Row="2">
    <StatusBarItem>MahApps.Metro DEMO Application</StatusBarItem>
    <Separator Style="{StaticResource MahApps.Styles.Separator.StatusBar}" />
    <StatusBarItem>Selected Tab:</StatusBarItem>
    <StatusBarItem Content="{Binding ElementName=MainTabControl, Path=SelectedItem.Header, Mode=OneWay}" />

    <StatusBarItem>Number value:</StatusBarItem>
    <StatusBarItem Content="{Binding NumericUpDownValue, Mode=TwoWay,UpdateSourceTrigger=PropertyChanged}" />
</StatusBar>
```

![2022-08-24_00h29_17](https://user-images.githubusercontent.com/658431/186278206-084bdfad-68dc-4f2b-8323-46fe6abcfa34.png)
