### ISSUE TITLE
dependency links broken, project dont compile

### ISSUE THREAD

**Issue by koolinoor** [MahApps/MahApps.Metro#4339]
## Describe the bug

downloading and opening the project, I have several dependency failures 

net47
net6.0-windows 

## Environment

visual studio 2019 

------------------- 

Do I need to have all these SDKs installed? And if, then why? 
I would just like to target netcoreapp3.1

**Comment by koolinoor** [comment]
I also tried to install MahApps via nuget, and add the sample to the new project.. 
that didnt work either :(

**Comment by punker76** [comment]
@koolinoor Please provide more information about your setup (which VS version etc). More build info https://github.com/MahApps/MahApps.Metro/wiki/Building-the-MahApps.Metro-solution
