### ISSUE TITLE
Setting the window RightWindowCommands on fly throws binding errors

### ISSUE THREAD

**Issue by will8372** [MahApps/MahApps.Metro#4342]
## Describe the bug
When setting the window.RightWindowCommands in code
`window.RightWindowCommands = TryFindResource("metroWinCommands") as WindowCommands;`
got some annoying binding errors
```
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='MahApps.Metro.Controls.MetroWindow', AncestorLevel='1''. BindingExpression:Path=Background; DataItem=null; target element is 'Grid' (Name='DropDownBorder'); target property is 'Background' (type 'Brush')
System.Windows.Data : 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='MahApps.Metro.Controls.MetroWindow', AncestorLevel='1''.BindingExpression:Path = WindowTitleBrush; DataItem = null; target element is 'ToolBarOverflowPanel'(Name = 'PART_ToolBarOverflowPanel'); target property is 'Background'(type 'Brush')
```

## Steps to reproduce

Hi, I want to customize the window RightWindowCommands in the following way:
1. Create a WrapDialogWindow like 
```
<metroControls:MetroWindow x:Class="WrapDialogWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
        xmlns:metroControls="clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro"
        ResizeMode="NoResize"
        ShowInTaskbar="False"
        ShowMaxRestoreButton="False"
        ShowMinButton="False"
        SizeToContent="WidthAndHeight"
        mc:Ignorable="d" 
        Title="{Binding Title}"
        d:DesignHeight="450" d:DesignWidth="800">
    <Grid>
    </Grid>
</metroControls:MetroWindow>
```
2. Register the dialog window by:
```
containerRegistry.RegisterDialogWindow<WrapDialogWindow>();
```
3. Register the View and ViewModel pairs
4. Show the window with the code, the MyTestView is a UserControl
```
            _dialogService.Show("MyTestView", paras, r =>
            {

            });
``` 
5. In the MyTestView.Loaded, I manually customize the window RightWindowCommands with following codes
```
var window = this.Parent as MetroWindow;
            if (window != null)
            {
                window.MaxWidth = 328;
                window.RightWindowCommands = TryFindResource("metroWinCommands") as WindowCommands;
            }
```
6. Found that after executing the code
` window.RightWindowCommands = TryFindResource("metroWinCommands") as WindowCommands;` some binding errors are shown:
```
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='MahApps.Metro.Controls.MetroWindow', AncestorLevel='1''. BindingExpression:Path=Background; DataItem=null; target element is 'Grid' (Name='DropDownBorder'); target property is 'Background' (type 'Brush')
System.Windows.Data : 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='MahApps.Metro.Controls.MetroWindow', AncestorLevel='1''.BindingExpression:Path = WindowTitleBrush; DataItem = null; target element is 'ToolBarOverflowPanel'(Name = 'PART_ToolBarOverflowPanel'); target property is 'Background'(type 'Brush')
```

If it's possible follow these guidelines for a good sample and I will most likely look at the issue sooner:

- Post a full GitHub repository. Not a zip file, half baked snippet etc. If GitHub is new to you consider it a great learning opportunity and chance to get involved.
- The repository should have just ONE step max for me to get running, and that is "Restore NuGet Packages". If there are any other missing dependencies, or new features I will most likely move on to another issue.
- I'm not trying to be awkward. I'm just busy and I'm helping a lot of people, not just you, so help me out and I will help you out.

-->

## Expected behavior

There should no binding errors when setting window.RightWindowCommands manually. 

## Actual behavior

Except the kind of not clean binding error, my codes work well for showing and operating window/dialog, and  

## Environment

```
MahApps.Metro version: v2.4.9
Windows build number: Win10 20H2 [Version 10.0.19042.1889]
Visual Studio: 2022 17.2.5
Target Framework: .Net 6  
```

**Comment by punker76** [comment]
@will8372 Is it possible for you to separate this and create a small sample? That would be nice. Thx

**Comment by will8372** [comment]
@punker76 That's OK, will create a sample.

**Comment by will8372** [comment]
Hi @punker76, this issue can't be reproduced in my clean sample codes. This issue very probably relates to my code environment.
This issue can be labeled invalid.

**Comment by timunie** [comment]
In that case I think you can just close this issue on your own.
