### ISSUE TITLE
MultiSelectionBox not available both in stable or prerelease

### ISSUE THREAD

**Issue by enricobenedos** [MahApps/MahApps.Metro#4346]
## Describe the bug

`MultiselectionComboBox` not available on prerelease or normal package.

## Expected behavior

Find `MultiselectionComboBox` available on prerelease or normal package.

## Actual behavior

Only version `2.4.9` available also with "Include Prerelease" enabled on VS 2022. In this version `MultiselectionComboBox` is not available.

## Environment

```
MahApps.Metro version: v2.4.9
Windows build number: Win11 21H2 
Visual Studio: 2022 17.3.3
Target Framework: .Net 6 
```

**Comment by timunie** [comment]
See https://github.com/MahApps/MahApps.Metro/wiki#appveyor-builds how to get prerelease packages

**Comment by enricobenedos** [comment]
Thanks, I've been already added the beta feed on nuget settings in Visual Studio. Probably there are some lags or problem in the VS nuget package manager interface. After some retry the beta package magically appeared. Thanks

**Comment by Chumba** [comment]
When might we see this control in the main release stream? Unfortunately using the prerelease is not an option for me

**Comment by timunie** [comment]
When 3.0.0 is ready. Due date? No - it's OSS and ready when it's ready.
