### ISSUE TITLE
Reset window position from code

### ISSUE THREAD

**Issue by BornToBeRoot** [MahApps/MahApps.Metro#4359]
## Describe the feature

Hi @punker76, 
is it possible to reset the window position (`SaveWindowPosition=true`) from the code?

I know i can delete the `user.config` in the `%localappdata%`, but a simple solution like `ResetPosition()` would be nice. Then i could implement a command line parameter to reset the window 😄 

## Additional context

https://github.com/BornToBeRoot/NETworkManager/issues/1623

**Comment by batzen** [comment]
@BornToBeRoot Wouldn't it be better to check if the saved position is valid and not restore it if it would be on a non existing screen?

**Comment by BornToBeRoot** [comment]
@batzen Yes, that would be better. 

I believe this affects several applications that use mahapps and regularly use different screen setups.
