### ISSUE TITLE
Corner radius on Metro Window

### ISSUE THREAD

**Issue by kalatchev** [MahApps/MahApps.Metro#4362]
## Windows 11 UI - rounded corners of the window

It will be great to have `mah:ControlsHelper.CornerRadius` working on `MetroWindow`. Even better would be to auto-detect the underlaying OS, and if it is Windows 11 to set it automatically.

**Comment by batzen** [comment]
This is already be available in the next major version.
Support for this was added in ControlzEx.

You can control wether the window borders should be rounded and if there should be glow windows or the native window borders should be colored.

Rounded windows and native border coloring are only available on Windows 11 of course.

**Comment by kalatchev** [comment]
Thanks a lot @batzen ! And Merry Christmas :-)

**Comment by LucaGanio** [comment]
any ideas on when the next major release will be available?
