### ISSUE TITLE
Domain metro.mahapps.com is down

### ISSUE THREAD

**Issue by khoazero123** [MahApps/MahApps.Metro#4366]
## Describe the bug

I got this error today in VS2022:

```
The name "IsNullConverter" does not exist in the namespace "http://metro.mahapps.com/winfx/xaml/controls".
```

Look like the domain `metro.mahapps.com` can't access anymore.

## Environment

```
MahApps.Metro version: v2.0.0
Windows build number: Win11
Visual Studio: 2022
Target Framework: .Net v4.7.2
```

**Comment by punker76** [comment]
@khoazero123 Can you provide a full short sample with this error? Thx! The `http://metro.mahapps.com/winfx/xaml/controls` i snot a real domain, it's the namespace of MahApps for WPF.
