### ISSUE TITLE
MultiSelectionComboBox looks like it's disabled in dark mode.

### ISSUE THREAD

**Issue by goldcode** [MahApps/MahApps.Metro#4375]
To get the same background look as a normal ComboBox i use mah:ControlsHelper.DisabledVisualElementVisibility="Collapsed" 
like so below. I guess it's just a hack. just trying to point you in the direction where the bug may be.

```
<mah:MultiSelectionComboBox
            mah:ControlsHelper.DisabledVisualElementVisibility="Collapsed"
            mah:MultiSelectorHelper.SelectedItems="{Binding blah}"
            ItemContainerStyle="{StaticResource MahApps.Styles.MultiSelectionComboBoxItem.CheckBox}"
            ItemsSource="{Binding DataContext.blah, ElementName=ItemsControlPoseViewModels}"
            SelectedItemContainerStyle="{StaticResource MahApps.Styles.MultiSelectionComboBoxSelectedItem.Removable}"
            Separator=", " />
```

MahApps.Metro Version="3.0.0-alpha0417" 
TFM: net6.0-windows
Visual Studio 2022 17.4.1

**Comment by timunie** [comment]
@goldcode thanks for your findings. This indeed helped me a lot. 👍
