### ISSUE TITLE
Using property ToolTip in HamburgerMenuIconItem doesn't work

### ISSUE THREAD

**Issue by shushu789** [MahApps/MahApps.Metro#4378]
## Describe the bug

My project uses HamburgerMenu. I hope that when the mouse moves over the HamburgerMenuIconItem, a text prompt will be given, that is, it can be implemented using ToolTip like other controls, but it does not work when the HamburgerMenuIconItem uses the Tooltip property. Of course it also No errors were reported. My project is version 2.4.9, I downloaded the latest source code and ran a test of the ToolTip property of this HamburgerMenuIconItem, the same problem, it doesn't work.This shouldn't be like this, I think it's a bug, can you guys check it out? thank you very much

## Steps to reproduce

A description of how to trigger this bug.

1. Runtime
2. When the mouse moves over the HamburgerMenuIconItem

If it's possible follow these guidelines for a good sample and I will most likely look at the issue sooner:

## Expected behavior
I hope that when the mouse moves over the HamburgerMenuIconItem, a text prompt will be given, that is, it can be implemented using ToolTip like other controls, but it does not work when the HamburgerMenuIconItem uses the Tooltip property. 

<mah:HamburgerMenuIconItem Icon="{iconPacks:Material Kind=Home}" Label="Home" ToolTip="Home">
              <mah:HamburgerMenuIconItem.Tag>
                  <local:HomeView />
              </mah:HamburgerMenuIconItem.Tag>
/mah:HamburgerMenuIconItem>

```
MahApps.Metro version: v2.4.9
Windows build number: Win10 21H2 [version:19044.2364]
Visual Studio: 2022 17.4.3
Target Framework: .Net Framework (v4.7.2)
```

## Screenshots
Here is the result of running the example from the source code：
![image](https://user-images.githubusercontent.com/85976805/212813268-d3c2be60-fab9-40ce-8a92-e0f1bd39435d.png)

This is the effect of running in my own project：
![image](https://user-images.githubusercontent.com/85976805/212813645-1cce6501-e742-46d5-a4f6-40e75b8c1335.png)

**Comment by punker76** [comment]
@shushu789 You need to extend your menu item template to use the ToolTip property:

e.g.

```xaml
<!--  This is the template for all menu items. In this sample we use the glyph items.  -->
<DataTemplate x:Key="HamburgerMenuItem" DataType="{x:Type mah:HamburgerMenuGlyphItem}">
    <!-- Add a binding to the ToolTip property of the menu item -->
    <DockPanel Height="48" LastChildFill="True" ToolTip="{Binding ToolTip}">
        <Grid x:Name="IconPart"
              Width="{Binding RelativeSource={RelativeSource AncestorType={x:Type mah:HamburgerMenu}}, Path=CompactPaneLength}"
              DockPanel.Dock="Left">
            <Image Margin="12"
                   HorizontalAlignment="Center"
                   VerticalAlignment="Center"
                   Source="{Binding Glyph}" />
        </Grid>
        <TextBlock x:Name="TextPart"
                   VerticalAlignment="Center"
                   FontSize="16"
                   Text="{Binding Label}" />
    </DockPanel>
    <DataTemplate.Triggers>
        <DataTrigger Binding="{Binding RelativeSource={RelativeSource AncestorType={x:Type mah:HamburgerMenu}}, Path=PanePlacement}" Value="Right">
            <Setter TargetName="IconPart" Property="DockPanel.Dock" Value="Right" />
            <Setter TargetName="TextPart" Property="Margin" Value="8 0 0 0" />
        </DataTrigger>
    </DataTemplate.Triggers>
</DataTemplate>
```

**Comment by shushu789** [comment]
Thank you very much for your reply, thank you for helping me solve this problem.
