### ISSUE TITLE
[DEV] Wrong colour for mouse-over of the close button

### ISSUE THREAD

**Issue by AleMcKee** [MahApps/MahApps.Metro#4379]
## Describe the bug

Since https://github.com/MahApps/MahApps.Metro/commit/a521dafe5c525f95e8abd2089903e60df0dfab84, the style of the `MetroWindow` close button is no longer correct. Normally, this should be red for `IsMouseOver`, but this is currently not the case.

@batzen

## Steps to reproduce

1. Build current develop-branch
2. Start Demo App
3. Move mouse over close button

## Expected behavior

`WindowButtonCommands.xaml`

remove those lines at 209/210

```xaml
controlzex:NonClientControlProperties.ClickStrategy="MouseEvent"
controlzex:NonClientControlProperties.HitTestResult="CLOSE"
```

![image](https://user-images.githubusercontent.com/92373483/216924029-18d6c83f-d362-4376-8468-b12019a5d54e.png)

## Actual behavior

![image](https://user-images.githubusercontent.com/92373483/216922867-134d817e-4afc-4f19-8087-3effe024def8.png)

## Environment

```
MahApps.Metro version: current develop-branch
Windows build number: Win10 20H2 [Build 19042.2486]
Visual Studio: 2022 17.4.4
Target Framework: v4.7.2
```
## Screenshots

Not required

**Comment by batzen** [comment]
@punker76 That's clearly my fault. Will fix as soon as I can.
