### ISSUE TITLE
The Parameter is incorrect.

### ISSUE THREAD

**Issue by Si1verfaux** [MahApps/MahApps.Metro#4382]
## Describe the bug
This error occurs seemingly at random.  it's a  Win32Exception usually raised by the GetWindowText with WindowAutomationPeer in its stack trace.  The above function are called by the system in response to a WPF Layout call.   It appears to be caused by a race condition that  occurs randomly when accessing the main thread using Dispatcher.BeginInvoke or DispatcherTimer.BeginInvoke  or some background-thread message passing that accesses the main GUI thread at some point.

```
int WinError = GetLastWinError();
If( WinError != 0 )
{
      Check(WinError) // Throws because WinError==0 
)
```

This indicates race condition because the value of WinError changes between the time it is checked (WinError != 0) and when it is used (WinError ==0).I know it is similar to another bug.  But it is still happening,

## Expected behavior
Random  crash
System.ComponentModel.Win32Exception The parameter is incorrect
   at MS.Win32.UnsafeNativeMethods.GetWindowText(HandleRef hWnd, StringBuilder lpString, Int32 nMaxCount)
   at System.Windows.Automation.Peers.WindowAutomationPeer.GetNameCore()

## Actual behavior

Crashes in Core Windows library with Win32 exception

The Paramter is incorrect.

## Environment

```
mahapps.metro 2.4.9
Version 17.4.4
.Net 7.0
caliburn.micro 4.0.212

```

## Screenshots
![ParameterIncorrect](https://user-images.githubusercontent.com/7660698/218779262-0d703674-d381-4675-beb8-2d4db16d9c5f.PNG)

**Comment by punker76** [comment]
@Si1verfaux I don't know if this is a MahApps related bug because I think this error is handled inside the `WindowAutomationPeer`.

**Comment by batzen** [comment]
It's a WPF issue.
Have a look at https://github.com/dotnet/wpf/issues/7344
