### ISSUE TITLE
TextBoxHelper ButtonContent ，displays  strange characters

### ISSUE THREAD

**Issue by khspace** [MahApps/MahApps.Metro#4391]
MahApps.Metro version: v2.4.9，win10
 ```
<TextBox 
            Width="356"
            Style="{DynamicResource MahApps.Styles.TextBox.Button}"
            mah:TextBoxHelper.ButtonContent="SaveAs" 
             mah:TextBoxHelper.ButtonWidth="80"
            mah:TextBoxHelper.Watermark="select dest path" VerticalAlignment="Center" Margin="12" >
        </TextBox>
```

![4125e101dc9acf36fff514098565bb1](https://user-images.githubusercontent.com/20200828/223075465-8c4b79dc-6824-460c-9224-6b20d50169f5.png)

**Comment by timunie** [comment]
It's just the FontFamily of the Button. 

See: https://github.com/MahApps/MahApps.Metro/blob/317b9bc40cdb4b56591673c05d8323db7663d0ca/src/MahApps.Metro/Styles/Controls.TextBox.xaml#L124

The default is Marlett: 

![image](https://user-images.githubusercontent.com/47110241/223077211-14b69455-9d0a-478f-a71a-acf453cdd8dc.png)

**Comment by khspace** [comment]
thanks @timunie.
add  mah:TextBoxHelper.ButtonFontFamily="Segoe UI, Lucida Sans Unicode, Verdana", works for me.

**Comment by timunie** [comment]
Can you close this issue in that case?
