### ISSUE TITLE
Issue using ToastBindingGeneric in VB.NET (B#)

### ISSUE THREAD

**Issue by rrvenki** [MahApps/MahApps.Metro#4395]
While converting C# to VB code in ToastNotifications, 
`BindingGeneric = new ToastBindingGeneric()
                {
                    Children =
                            {
                                new AdaptiveText()
                                {
                                    Text = title
                                },
                                new AdaptiveText()
                                {
                                    Text = content
                                },
                            }` 
we find ToastBindingGeneric cannot be added with Children in VB.NET. Is there any way to add AdaptiveText, AdaptiveImage, or AdaptiveGroup? Rosalyn language converter does not help here.

**Comment by rrvenki** [comment]
The converted code as below. Pls guide what is wrong in this VB code. The error says ToastBindingGeneric.Children and ToastButtons are both ReadOnly. If it was readyonly how the C# code works? Something like declaring a readonly variable and assigning value programmatically in C# works but not in B#.

`Dim Btns As New List(Of IToastButton)`
`Btns.Add(New ToastButton("OK", "ToastButtonActivationArguments") With {.ActivationType = ToastActivationType.Foreground})`
`Btns.Add(New ToastButtonDismiss("Cancel"))`

`Dim content = New ToastContent With {.Launch = "ToastContentActivationParams",
                                                 .Visual = New ToastVisual() With {.BindingGeneric = New ToastBindingGeneric().Children With {New AdaptiveText With {.Text = "First Text"}, New AdaptiveText With {.Text = "Second Text"}},
                                                 .Actions = New ToastActionsCustom() With {.Buttons = Btns}}`

**Comment by timunie** [comment]
@rrvenki I don't see how this is by any chance a MahApps issue? Can you please specify what exactly MahApps.Metro can do to help here? 

If you agree that it's not an issue of MahApps, please close the issue. Thx 🙏
