### ISSUE TITLE
Update ControlzEx version

### ISSUE THREAD

**Issue by kkbp58** [MahApps/MahApps.Metro#4400]
Hello,
When are you going to update the required version of ControlzEx (currently >=4.4 && < 6) ? 
I have another nuget that requires ControlzEx >= 6.
Regards,
Katerina

**Comment by timunie** [comment]
I think it is for the today released preview of [v3.0.0](https://www.nuget.org/packages/MahApps.Metro/3.0.0-alpha0457): 

https://github.com/MahApps/MahApps.Metro/blob/3fce0224bcdc62112dabecbb3757a438559bf86e/src/Directory.packages.props#LL8C64-L8C64

**Comment by kkbp58** [comment]
When is the stable v3.0 expected?
Thanks,
Katerina
