### ISSUE TITLE
Glowbrush behavior

### ISSUE THREAD

**Issue by flobuzzz** [MahApps/MahApps.Metro#4406]
Hi guys,

I love your Metro stuff!
just a request, or maybe there is something I am not using the right way...

Glowbrush always applies when activiated.
Would it be possible to make it active only when window is activated ?

**Comment by punker76** [comment]
@flobuzzz In the current source you can use `GlowColor` and `NonActiveGlowColor` to set different colors for this state. In the v2.x.x you can use `GlowBrush` and `NonActiveGlowBrush`.
