### ISSUE TITLE
Unsigned \de\MahApps.Metro.resources.dll 

### ISSUE THREAD

**Issue by emik-dev** [MahApps/MahApps.Metro#4410]
Hi,
is there a way to remove the globalization folders automatically created in the build folder? 
\de\MahApps.Metro.resources.dll 

or sign this dll library like the rest of the MahApps.dll files?

**Comment by punker76** [comment]
fixed with https://github.com/MahApps/MahApps.Metro/commit/ec43495283858675143e98289e0e05ea7f2695f9
