### ISSUE TITLE
There is no indication on the controller.

### ISSUE THREAD

**Issue by BIT-ACE** [MahApps/MahApps.Metro#4418]
## Describe the bug

There is no indication on the controller.

## Expected behavior

indication on the controller.

## Actual behavior

There is no indication on the controller.

## Environment

```
MahApps.Metro version: v2.4.10
Windows build number: Windows 11 Home, 22H2
Visual Studio: 2022 17.7.4
Target Framework: .Net Core 3.1 (v4.5.2, v4.7.2)
```

## Screenshots

![image](https://github.com/MahApps/MahApps.Metro/assets/92138501/19c3d675-ac71-4069-b3b2-95da4f72cdbe)

**Comment by timunie** [comment]
looks like missing styles to me. Did you make sure to add the needed MahApps Styles?

**Comment by BIT-ACE** [comment]
![image](https://github.com/MahApps/MahApps.Metro/assets/92138501/bf9af2ef-75be-42fa-b3fc-d7c15059499d)
opps...!
it was a problem that I didn't follow the procedure. I'm sorry! and thanks!
