### ISSUE TITLE
Add DateTimePicker

### ISSUE THREAD

**Issue by Torchok19081986** [MahApps/MahApps.Metro#4439]
Hallo,  How do i add DateTimepicker that only shows Time like in example. In Xaml are no Properties for change Behaviour of DateTimePicker. I use project for Target .NET Framework 4.8.

**Comment by punker76** [comment]
Just use the TimePicker for that

```xaml
<mah:TimePicker mah:TextBoxHelper.ClearTextButton="True" />
```

https://github.com/MahApps/MahApps.Metro/blob/d432fcc68c42025e6cffa57910bd97e2901efa2b/src/MahApps.Metro.Samples/MahApps.Metro.Demo/ExampleViews/DateExamples.xaml#L275-L283
