### ISSUE TITLE
Can't set the property 'Orientation' when using  MetroHeader

### ISSUE THREAD

**Issue by PadawanSJJ** [MahApps/MahApps.Metro#4441]
Can't set in my project

![cantset](https://github.com/MahApps/MahApps.Metro/assets/94749553/df21861e-6c22-42dd-ac88-1cceb8489f58)

can set in yours
![canset](https://github.com/MahApps/MahApps.Metro/assets/94749553/f77231fb-e43f-4a07-9979-59f27d63f15a)
![can](https://github.com/MahApps/MahApps.Metro/assets/94749553/386fa227-bb95-4ac4-b143-bf08652e5184)

nuget version: 2.4.10 
project target framework: .net framework 4.8.1
 
or is there any way that I can put the header and content in one line?

**Comment by timunie** [comment]
This will only be available in 3.0.0 or in current nightly builds, see: https://github.com/MahApps/MahApps.Metro/pull/4238
