### ISSUE TITLE
 'ControlzEx 6.0.0' is not compatible with 'MahApps.Metro 2.4.10 constraint: ControlzEx (>= 4.4.0 && < 6.0.0)'"

### ISSUE THREAD

**Issue by Gooni1518** [MahApps/MahApps.Metro#4442]
Hi, I would like to update MahApps.Metro v2.4.10 via NuGet package, but I got this error:

"Unable to resolve dependencies. 'ControlzEx 6.0.0' is not compatible with 'MahApps.Metro 2.4.10 constraint: ControlzEx (>= 4.4.0 && < 6.0.0)'"

Can it be fixed ? 

Thanks

**Comment by William-Joshua** [comment]
open nuget installed page  and update  ControlzEx to 5.0.X

**Comment by Gooni1518** [comment]
My version of ControlEx is 5.0.2

The error message above appears when i try to update to 6.0.0

**Comment by punker76** [comment]
@Gooni1518 You can't use ControlzEx v6.x with MahApps v2.x that's what the message says. If you want to use ControlzEx v6.x the you must use MahApps pre-release (over NuGet or appyeyor)
