### ISSUE TITLE
Install-Package : No match was found for the specified search criteria and package name 'MahApps.Metro'.

### ISSUE THREAD

**Issue by GronbergInfo** [MahApps/MahApps.Metro#4444]
I use JetBrain Rider with C#. 
I tried to run this command several times, but it fails with the same message.
Running the same in a PowerShell ISE/CMD Window gives same error message as below

I open powershell console in rider and run this:

> PS > **Install-Package MahApps.Metro**
> Install-Package : No match was found for the specified search criteria and package name 'MahApps.Metro'. Try Get-PackageSource to see all available registered package sources.
> At line:1 char:1
> + Install-Package MahApps.Metro
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
>     + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
> 
> PS > **Get-PackageSource**
> 
> Name                             ProviderName     IsTrusted  Location
> ----                             ------------     ---------  --------
> PSGallery                        PowerShellGet    False      https://www.powershellgallery.com/api/v2
> nuget.org                        NuGet            False      https://api.nuget.org/v3/index.json
> 
> 
> PS >
>

**Comment by timunie** [comment]
I consume MahApps.Metro in Rider with no issue. So must be some setup on your end I believe. Works also using PS for me.
