### ISSUE TITLE
MetroWindow: Application Crash on Double-Clicking Upper Left Icon

### ISSUE THREAD

**Issue by Fishayyy** [MahApps/MahApps.Metro#4445]
## Description
**Issue**: Double-clicking the icon in the upper left corner of a `MetroWindow` causes the application to crash. This behavior is observed even in the MahApps demo application.

**Expected Behavior**: Double-clicking the icon typically opens then closes the system menu, or should do nothing if 'ShowSystemMenu' is set to 'False'.

**Actual Behavior**: The application crashes upon double-clicking the upper left window icon.

## Steps to Reproduce
1. Open any application that utilizes `MetroWindow` from MahApps.
2. Double-click on the icon located in the upper left corner of the window.
3. Observe that the application crashes.

This issue is also reproducible in the official MahApps demo application.

## Environment
- MahApps Version: v2.4.10
- .NET Version: .NET 8.0
- Operating System: Windows 11
- Visual Studio Version: Visual Studio 2022
- Build Configuration: Debug and Release

## Additional Context
- The issue persists across different MahApps themes and configurations.
- No relevant exceptions or error messages are observed but I have not setup any special logging to monitor this.

**Comment by punker76** [comment]
@Fishayyy Hi, do you have an exception or something else which we can investigate?

**Comment by Fishayyy** [comment]
Unfortunately I have tried changing my debug settings to catch all unhandled exceptions and it appears that none are being thrown which makes me think that the application is actually closing instead of crashing. I also don't see anything in the Windows Event Viewer. I'm going to try and look through some of the code related to the MetroWindow Icon to see if I can find anything useful.

**Comment by Fishayyy** [comment]
> @Fishayyy Hi, do you have an exception or something else which we can investigate?

I found the code responsible for the behavior here:
https://github.com/MahApps/MahApps.Metro/blob/4b5ad8fbe56fbb330438595cbaed3c3e23ceafad/src/MahApps.Metro/Controls/MetroWindow.cs#L1530-L1545

Given that this is a private event for the MetroWindow is there a way I can prevent this behavior?

**Comment by punker76** [comment]
@Fishayyy This close behavior is the same as for other windows programs, just tested it with the explorer and it does exactly the same.

**Comment by timunie** [comment]
@punker76 interesting enough, it is not the default behavior for all programs. In win10 it does close explorer for me, in Win11 not. Some other programs do close, others not. So maybe this should be configurable somehow 🤔 

- make the void virtual to be able to override it?
- Add a property for it `CloseOnIconDoubleClick {get; set;} = true`

**Comment by Fishayyy** [comment]
> @punker76 interesting enough, it is not the default behavior for all programs. In win10 it does close explorer for me, in Win11 not. Some other programs do close, others not. So maybe this should be configurable somehow 🤔
> 
> * make the void virtual to be able to override it?
> * Add a property for it `CloseOnIconDoubleClick {get; set;} = true`

I like this idea! I've been playing around with different apps today and it defiantly seems like the default Windows behavior is to open system menu on click and close the window on double click for all my Microsoft Office apps and a few other various apps, but then there are things like Visual Studio Code and the Calculator app that treat the icon as a part of the title bar.
