### ISSUE TITLE
SaveWindowPosition not working when window is maximized on second screen with WindowState="Maximized"

### ISSUE THREAD

**Issue by LiTo96** [MahApps/MahApps.Metro#4449]
## Describe the bug

The MetroWindow has `WindowState="Maximized"` and `SaveWindowPosition="True"`.
When the window is opened for the very first time the window is maximized on the main screen.
When you move the window onto a second screen and maximize it and then close the window it should save that window position.
But when the window is reopened it's maximized on the main screen instead of the second screen where it was closed before.

## Steps to reproduce

1. Set WindowState="Maximized" on the MetroWindow
2. Set SaveWindowPosition="True" on the MetroWindow
3. Start the application
4. Move the window to a second screen and maximize it
5. Close the window
6. Reopen the window
7. The window is maximized on the main screen instead of the second screen

## Expected behavior

The window should open maximized on the main screen when it was opened for the very first time.
After that it always should open in the saved position aka the position it had when it was last closed even if it was maximized on another screen.

## Actual behavior

The window doesn't open maximized on a second screen when it was closed there.

## Environment

```
MahApps.Metro version: v2.4.10
Windows build number: Win10
Target Framework: .Net7
```

**Comment by punker76** [comment]
Thx for reporting this issue. I can reproduce this. I also found out that if I don't set the WindowState to Maximized the save/load behavior works.

1. don't set `WindowState="Maximized"`
2. set `SaveWindowPosition="True"` on the window
3. start app
4. move to second monitor and maximize it
5. close the app
6. start the app again
7. the window will be opened on the correct monitor

/cc @batzen maybe this is an issue for ControlzEx, but I don't know where I should look for

**Comment by batzen** [comment]
@punker76 @LiTo96 Saving the position works without any issues.
Restoring is the problem.
But it's not caused by something from MahApps.Metro or ControlzEx.
The real issue is that `SetWindowPlacement` does not change the position/monitor of an already maximized window.

If we call `MoveWindow` (if the window is already maximized and should be maximized) before calling `SetWindowPlacement`, the issue is fixed.

The code that would have to be added to `WinApiHelper.SetWindowPlacement`, just before the call to `PInvoke.SetWindowPlacement`, is:
```
var placementBefore = new WINDOWPLACEMENT
                     {
                         length = (uint)Marshal.SizeOf<WINDOWPLACEMENT>()
                     };
PInvoke.GetWindowPlacement((HWND)hWnd, &placementBefore);

if (placementBefore.showCmd is SHOW_WINDOW_CMD.SW_SHOWMAXIMIZED
    && placement.showCmd is SHOW_WINDOW_CMD.SW_SHOWMAXIMIZED)
{
    PInvoke.MoveWindow((HWND)hWnd, placement.rcNormalPosition.X, placement.rcNormalPosition.Y, placement.rcNormalPosition.Width, placement.rcNormalPosition.Height, false);
}
```
