### ISSUE TITLE
Missing PART in the datagrid

### ISSUE THREAD

**Issue by TheCamel** [MahApps/MahApps.Metro#4455]
## the "PART_FillerColumnHeader" in not present in the template

Create a new projet with a datagrid, columns and parse the xaml = at the end of the headers, this PART is filling the rest of the header grid.

I was using this in my code to remove a custom filter control in the last part
var filler = VisualHelper.FindChild<DataGridColumnHeader>(this, "PART_FillerColumnHeader");

you can also modify the header style to verify - below the original datagrid

`<Style x:Key="DataGridColumnHeadersPresenterStyle1" TargetType="{x:Type DataGridColumnHeadersPresenter}">
	<Setter Property="Template">
		<Setter.Value>
			<ControlTemplate TargetType="{x:Type DataGridColumnHeadersPresenter}">
				<Grid>
					<DataGridColumnHeader x:Name="**PART_FillerColumnHeader**" IsHitTestVisible="False"/>
					<ItemsPresenter/>
				</Grid>
			</ControlTemplate>
		</Setter.Value>
	</Setter>
</Style>`

## Environment

MahApps.Metro version: v2.4.10
Target Framework: .Net Core 8

**Comment by TheCamel** [comment]
Hi @punker76 ,
thanks for your feed back. You are right...but this code is not working anymore...
```
Loaded += (sender, x) =>
{
	//this to remove Controls:DataGridExtended the filter in the last empty column
	DataGridColumnHeader filler = VisualHelper.FindChild<DataGridColumnHeader>(this, "PART_FillerColumnHeader");
	if (filler != null)
	{
		filler.DataContext = null;
	}
```
As snoop is not working in core, I will check it in the demo app and in my app to understood what is wrong

I also found that trigger in my template
```
<DataTrigger Binding="{Binding Path=Name, RelativeSource={RelativeSource AncestorType={x:Type DataGridColumnHeader}}}"
										 Value="PART_FillerColumnHeader">
									<Setter TargetName="Filter"
											Property="Visibility"
											Value="Hidden" />
```

The strange thing is that the filter display in the last empty colunm only when the grid is displayed full or with some colunms Width="*" 

![image](https://github.com/MahApps/MahApps.Metro/assets/7381872/a4ce0dc7-2f19-4bb3-b2a0-c81840358747)

![image](https://github.com/MahApps/MahApps.Metro/assets/7381872/ead62d9b-019b-4351-a2b8-4a15dae02f6f)

the more is that the control can't be cliked but it exist in the tree view 
![image](https://github.com/MahApps/MahApps.Metro/assets/7381872/28295867-a4dd-48bd-9820-a358ebfc4813)

I let you know about my investiguation asap
Thanks

**Comment by TheCamel** [comment]
I found out that the `GetChildrenCount` in the method is not working anymore

`int childrenCount = VisualTreeHelper.GetChildrenCount(parent);`

**Comment by punker76** [comment]
@TheCamel If it's possible it would be nice to have a short/simple sample with this.

**Comment by TheCamel** [comment]
@punker76  I will try to reproduce it on the sample app, or it is due to my app. Tell you soon. 
I googled that GetChildrenCount does not work on virtualized grid... and getting the part by code does not work either

```
public override void OnApplyTemplate()
{
	base.OnApplyTemplate();
	var test = GetTemplateChild("PART_FillerColumnHeader");
}
```
