### ISSUE TITLE
Xaml warning: Resource '{x:Type MahApps.Metro.Controls.MetroWindow}' is not found

### ISSUE THREAD

**Issue by kgday** [MahApps/MahApps.Metro#4457]
## Describe the bug

I am not sure when this warning started to be emitted. But noticed it today. When creating a custom window style and attempting to base it from the MetroWindowStyle, I am getting Resource '{x:Type MahApps.Metro.Controls.MetroWindow}' is not found.

## Steps to reproduce
```
The xaml resources header is 
<ResourceDictionary
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:controls="http://metro.mahapps.com/winfx/xaml/controls"
    xmlns:mah="http://metro.mahapps.com/winfx/xaml/controls"
...
>
```
The custom style:
```
    <Style
        x:Key="CustomMetroWindow"
        TargetType="{x:Type controls:MetroWindow}"
        BasedOn="{StaticResource {x:Type controls:MetroWindow}}">
        <Setter Property="ShowTitleBar" Value="True" />
        <Setter Property="Height" Value="600" />
        <Setter Property="Width" Value="1024" />
        <Setter Property="FontFamily" Value="Roboto" />
    </Style>
```
It is on the BasedOn line that the warning is being emitted.

There should not be a warning emitted for this, I would have thought.  I have obviously done something wrong or something has changed.

I get the warning in both rider and visual studio with resharper

## Environment

```
MahApps.Metro version: v2.4.10
Windows build number: Windows 11 Pro, version 21H2, Build 22000.2538
JetBrains Rider: 2023.3.2
Visual Studio: 2022  17.8.0
JetBrains ReSharper 2023.3.2
Target Framework: .Net 8.0
```

**Comment by timunie** [comment]
Is it probalby a controls lib that doesn't reference MahApps on it's own?

**Comment by kgday** [comment]
This is directly in my wpf application with a main window, not in a controls lib and directly references mahapps.

**Comment by timunie** [comment]
ah wait looks like MetroWindow does not support this feature to inherit the style. Check original styles for reference.

**Comment by punker76** [comment]
I think this issue is not related to MahApps itself. Yes, it's not nice to see this, but at the end it's a waning and is a designer xaml parsing issue. One suggestion is to put the style in the App.xaml and use it then with DynamicResource.

```xaml
<mah:MetroWindow x:Class="MetroDemo.MainWindow"
                 xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                 xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                 xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
                 xmlns:mah="http://metro.mahapps.com/winfx/xaml/controls"
...
                 Style="{DynamicResource CustomMetroWindow}"
...

```
