### ISSUE TITLE
RichTextBox and Themes

### ISSUE THREAD

**Issue by victor-david** [MahApps/MahApps.Metro#4474]
Hello Team - My app uses RichTextBox. Mah provides the style, which uses Theme brushes

```xaml
<Setter Property="Background" Value="{DynamicResource MahApps.Brushes.Control.Background}" />
<Setter Property="Foreground" Value="{DynamicResource MahApps.Brushes.Text}" />
```

My app saves the contents of the RichTextBox:

```c#
TextRange range = new(Document.ContentStart, Document.ContentEnd);
range.Save(fileStream, DataFormats.XamlPackage);
```

The problem is that the current property values (such as foreground) on the Paragraph objects inside the FlowDocument get serialized. When the FlowDocument is deserialized, the paragraphs retain the color of the theme that was in use at the time of save. 

This means that if you save while on a light theme (dark foreground) and then later switch to a dark theme, you now have dark text on a dark background

![image](https://github.com/MahApps/MahApps.Metro/assets/17145322/4585fdb3-c234-442f-acb0-9c2e3bdb0ef7)

I realize this isn't really the fault of Mah, but any guidance appreciated. Thanks.

**Comment by timunie** [comment]
> [!NOTE]
> > I realize this isn't really the fault of Mah, but any guidance appreciated. Thanks.
> 
> Why do you open this as a bug report then? We have Discussions for questions. 

I think you can / should update your document background on loading in case you make use of the theming. App.Current should be able to find the resource. 

```cs
App.Current.TryFindResource("MahApps.Brushes.Control.Background");

// alternative
var mode = ThemeManager.Current.DetectTheme(App.Current)?.BaseColorScheme;
```

**Comment by victor-david** [comment]
Apologies. I didn't mean to open a bug report. Also, setting the background of the document doesn't resolve the issue because the foreground gets serialized hardcoded with the color of the current theme, overriding theme brushes when later the theme is switched.

```xaml
<Paragraph Foreground="#000000"><Run>My text</Run></Paragraph>
```

At any rate, I'll take a look at discussions.

**Comment by timunie** [comment]
Can you close this issue pls?

As said earlier, it's up to you to update the document, if it's hard coded we have no option to do so.
