### ISSUE TITLE
MetroWindow : Unloaded event

### ISSUE THREAD

**Issue by TheCamel** [MahApps/MahApps.Metro#4475]
## Describe the bug

Do not get any unloaded event in my app when i close the window with the top right "system" close button

Loaded and Close event are sent but not unloaded

## Steps to reproduce

just add a handler for unloaded and close

## Environment

```
MahApps.Metro version: 3.0.0-alpha0476
```

**Comment by punker76** [comment]
The same happens to a normal window, the unload event isn't fired.
