### ISSUE TITLE
Replace + and - for arrows in NumericUpDown

### ISSUE THREAD

**Issue by grizoood** [MahApps/MahApps.Metro#4476]
I'm looking for a way to replace the + and - in numericupdown with arrows. Could you help me do this.

Thk

![image](https://github.com/MahApps/MahApps.Metro/assets/25281140/cbf27737-4654-4f3d-b7b1-8e44ae55ff8f)

**Comment by timunie** [comment]
Why do you make it an issue instead of a Q&A? Please close this. 

Here is the original style: 
https://github.com/MahApps/MahApps.Metro/blob/8f1d02b457d21910fb0cedfff28b750db60ee6ee/src/MahApps.Metro/Themes/NumericUpDown.xaml#L75-L96

**Comment by grizoood** [comment]
I agree, but the buttons always remain vertical and not horizontal

**Comment by grizoood** [comment]
In fact, it's more of a question/answer.
