### ISSUE TITLE
MetroWindow Background

### ISSUE THREAD

**Issue by LeeCY-C** [MahApps/MahApps.Metro#4481]
After I Clip the MetroWindow, is alaway has black background . How can i remove it.
<img width="997" alt="20240425153807" src="https://github.com/MahApps/MahApps.Metro/assets/70256381/45a9679d-0bc9-4c6d-87af-e63276dc941c">

**Comment by punker76** [comment]
@LeeCY-C Which version are you using?

**Comment by punker76** [comment]
Here is comparison between file explorer and latest MahApps version (alpha) under Win 11 23H2

![2024-04-25_09h54_29](https://github.com/MahApps/MahApps.Metro/assets/658431/7db5cecd-3229-4ab9-a6f1-32f8c1d990f3)

![2024-04-25_09h56_04](https://github.com/MahApps/MahApps.Metro/assets/658431/135f40f8-2478-4c8b-8daa-d3e19ed61764)

**Comment by punker76** [comment]
@LeeCY-C Can I close this?

**Comment by LeeCY-C** [comment]
I'm sorry that I haven't noticed your reply because I've been too busy recently. I used the latest nuget bag. The picture you gave me still doesn't seem to make the background transparent, but I have given up the rounded corner window now, but thank you for your reply.
