### ISSUE TITLE
Font VerticalAlignment in button of the 3rd library is not center

### ISSUE THREAD

**Issue by ycyily** [MahApps/MahApps.Metro#4498]
Font VerticalAlignment in button of the 3rd library-Extended.Wpf.Toolkit is not center when i add

```xaml
<ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
```

in App.xaml

## Environment

```
MahApps.Metro version: v2.4.10
Windows build number: Win11  
Visual Studio: 2022  
Target Framework: .NetFramework  4.72 
```

## Screenshots 

![Center](https://github.com/MahApps/MahApps.Metro/assets/41577940/2c7b12b0-4521-4bd6-b1cc-8f48b5ea01cf)

![Not Center](https://github.com/MahApps/MahApps.Metro/assets/41577940/7ca547ee-c05a-454b-863e-2eba48f7f5a1)

**Comment by punker76** [comment]
@ycyily The vertical alignment of Label and TextBlock are not changed in MahApps. So maybe you can find out which control this is (with [Snoop](https://github.com/snoopwpf/snoopwpf)). Or you can also always override properties at this view:

```xaml
<Style BasedOn={StaticResource {x:Type Label}} TargetType="{x:Type Label}">
	<Setter Property="VerticalAlignment" Value="Center" />
</Style>

<Style BasedOn={StaticResource {x:Type TextBlock}} TargetType="{x:Type TextBlock}">
	<Setter Property="VerticalAlignment" Value="Center" />
</Style>
```
