### ISSUE TITLE
Is there version to support ControlzEx 6.0

### ISSUE THREAD

**Issue by ycyily** [MahApps/MahApps.Metro#4500]
When i use the 3rd library like Fluent.Ribbon,i found that the lastest version of Fluent.Ribbon supports ControlzEx 6.0 and the lastest version of MahApps can not support ControlzEx 6.0 .
But i want to use the new feature of the lastest theme in MahApps. So is there new version of MahApps to support ControlzEx 6.0 later.

**Comment by timunie** [comment]
You can try the pre-release of v3.0. 

> [!NOTE] 
> Please close this issue and ask such things on Discussions instead in order to keep issue list clean. Thx.
