### ISSUE TITLE
Is it possible not generated /de/MahApps.Metro.resources.dll?

### ISSUE THREAD

**Issue by sleepCat-sleep** [MahApps/MahApps.Metro#4503]
hello. Thanks you to develop nice library!
But ... I'm really sorry that I would like to know how to do not generate /de/MahApps.Metro.resources.dll when solution building.
This folder and file were generated automatically in bin/debug folder when build my solution.
I use ".NET Framework 4.8" and Visual Studio 2022.
I get MahApps is version 2.4.10 using Nuget package.

I'm beginner about Web development.
Sorry...Please help me...

**Comment by punker76** [comment]
@sleepCat-sleep These are the german color names which are used at the ColorPicker.
