### ISSUE TITLE
MahApps.Metro increases many processor usage when I start to use any item of it.

### ISSUE THREAD

**Issue by MaxophonyxCorporation** [MahApps/MahApps.Metro#4515]
## Actual behavior

When I use any item of MahApps.Metro in my WPF application, it increases the processor usage even if I don't do any processes in the application. Before starting to use it, my program was just used 0% - 2% (even if doing something on it.)

## Environment

```
MahApps.Metro version: v2.4.10
Windows build number: Win11 & Win10 (dualbooting them. Results was same for each OSes.)
Visual Studio: 2022 17.11.2
Target Framework: .Net Framework 4.8
```

## Screenshots

![image](https://github.com/user-attachments/assets/c669ba77-f434-4994-9983-2dd0887a0ed2)

**Comment by timunie** [comment]
depends on what you do in your App. Make sure to run it in release mode only without debugger attached.

**Comment by punker76** [comment]
Does this also happen if the application was started without Visual Studio as a release? If so, can this be reproduced in a test application? I'll close this here, but you can always reopen it if it persists. Thanks.
