### ISSUE TITLE
MahApps.Metro 2.4.10 does not support ControlzEx 6.0.0

### ISSUE THREAD

**Issue by alekdavis** [MahApps/MahApps.Metro#4516]
I tried to upgrade the `ControlzEx` Nuget package (source: https://github.com/ControlzEx/ControlzEx) from version 5.0.2 to 6.0.0 (they should be compatible), but the upgrade failed with message "_Unable to resolve dependencies. 'ControlzEx 6.0.0' is not compatible with 'MahApps.Metro 2.4.10 constraint: ControlzEx (>= 4.4.0 && < 6.0.0)'._" It would be nice if the MahApps.Metro library supported the latest versions of the dependencies.

**Comment by timunie** [comment]
They are not compatible. You need MahApps 3.0 preview package for it to support ControlsEx 6

**Comment by alekdavis** [comment]
@timunie Ah, didn't realize. Thank you.

**Comment by timunie** [comment]
Great. Please close this issue then.
