### ISSUE TITLE
Null reference exception in the MultiSelectorHelper

### ISSUE THREAD

**Issue by vicitacal** [MahApps/MahApps.Metro#4518]
## Describe the bug

I use MultiSelectorHelper.SelectedItems in the DataTemplate and get a NullReferenceException every time this DataTemplate is changed to another one. 

## Steps to reproduce

Run demo and just change selected value in the combo box.

https://github.com/vicitacal/MahAppsBugDemo

## Expected behavior

Template change successfully.

## Actual behavior

Exception crush application.

## Environment

```
MahApps.Metro version: v2.4.10
Windows build number: Win10 21H2
Visual Studio: 2022 17.9.2
Target Framework: .Net Core 6 (6.0.133)
```

**Comment by punker76** [comment]
This is fixed in the dev source. You can get it as pre-release on NuGet or as latest hot pre-release on appveyor via [https://ci.appveyor.com/nuget/mahapps.metro](https://ci.appveyor.com/nuget/mahapps.metro)
