### ISSUE TITLE
multi selection for combo box

### ISSUE THREAD

**Issue by ghost** [MahApps/MahApps.Metro#510]
I think that a multi select feature within the combo box control could be useful. In fact, I have tried to make a "multi select combo box" taking third party classes and then applying mahapps metro to them, but I get dissimilar results. 
This is how my control looks until now: 
http://sdrv.ms/10MeWDB
http://sdrv.ms/10MeXr0

My question is, will be added this feature to the combo box control? namely, multi select  feature.

![before](https://f.cloud.github.com/assets/2133022/601099/ba68a456-cc77-11e2-9333-f57870576449.png)
![while](https://f.cloud.github.com/assets/2133022/601100/ba6a17d2-cc77-11e2-8136-48d02953c363.png)

**Comment by Evangelink** [comment]
@punker76 @ferbraz89 Would be happy to help on this one. What's the current state of this feature? The screenshot from June 2013 looks like a finished control.

**Comment by ferbraz89** [comment]
@Evangelink Last time I checked (aka prior to v1.0) this specific control wasn't developed yet. I can't remember much about it but the screenshoot from June 2013 was merely the result of using the control (made by somebody else) side by side with Mahapps.Metro. I managed to get both to work in a classic MVVM scenario by writing extremely nasty code that simply did the trick that I was searching for in the moment. I wish I could tell you more but that's all I know.

**Comment by Speuline** [comment]
No news? This control would be very helpful :'(
The feature was abandonned?

**Comment by Speuline** [comment]
Still no news? This feature would be great...

**Comment by GreatFireWall** [comment]
need this feature too.

**Comment by Malavos** [comment]
I would plan this out, but it's not a urgent issue.  There are [some bugs](https://github.com/MahApps/MahApps.Metro/issues?q=is%3Aopen+is%3Aissue+label%3ABug) we need to check first. I will continue contribuing soon, but my backlog [is this issue here](https://github.com/MahApps/MahApps.Metro/issues/2808).

**Comment by ChriRosi** [comment]
I would also need this feature.

**Comment by Dragoneel009** [comment]
This feature would much appreciated and very useful to us

**Comment by Malavos** [comment]
How that would work? I am wondering that, if we have too many items selected, the combo box text will not appear to the user. I think multi-select combo box control needs a different design to handle this.

**Comment by Evangelink** [comment]
I have the feeling such control doesn't provide users with a good UX and can often be replaced by some other controls or be split into a multi step dialog.

**Comment by Malavos** [comment]
@Evangelink  take a look at the one I've referenced. Our UX and designer here approved to use this specific component for another project. I think it's a great solution, all things considered.

**Comment by timunie** [comment]
I have a `MultiSelectionComboBox` written on my own, but it only supports string input. If we need any object to be supportet, i don't have an idea. 

If someone wants me to post my code please give me a sign 😄 

Happy coding 
Tim

**Comment by punker76** [comment]
Duplicate of #3802 
It will be handled there.
