### ISSUE TITLE
cant't recognize MahApps.Metro.Controls in designmode

### ISSUE THREAD

**Issue by ghiboz** [MahApps/MahApps.Metro#535]
hi again..
in my project I've this as reference:

![image](https://f.cloud.github.com/assets/446533/642429/f9264aa6-d35a-11e2-9af9-111843e0926d.png)

and if I compile, it works all right, but in designtime appears this:

![image](https://f.cloud.github.com/assets/446533/642431/205600bc-d35b-11e2-83e0-46c80bd69690.png)

the blue underline tell this:
**'The name "MetroWindow" does not exists in the namespace "clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro".**
but this dll is referenced and works...

EDIT: in vs2010 the designtime is ok, in 2012 gives the issue above...

**Comment by GlennHostetler** [comment]
I was able to solve this issue in VS2015 by reinstalling MahApps (Tools->NuGet Package Manager->Package Manager Console and then type "Install-Package MahApps.Metro").

**Comment by YoanaDimitrova-kpmg** [comment]
I got rid of the nuget references in the project files since we decided to stick with paket for managing dependencies but it seems the WPF projects in particular are really unhappy with it. They seem to build ok when the dependencies are installed via nuget. Any ideas?
