### ISSUE TITLE
App made with MahApps.Metro won't run on other computers

### ISSUE THREAD

**Issue by segadude** [MahApps/MahApps.Metro#656]
I made a new version of my app with MahApps.Metro. I build the project for release, and copied the entire release folder to a flash drive to test on other machines. The first machine I tried was a Windows 7 Home Premium 32-bit machine (after installing .Net Framework 4.5) but after double clicking the app, nothing happens. The executable doesn't show up in task manager. Then I tried a Windows 8.1 Preview machine but it didn't run there either and didn't show up in the task manager. It runs just fine on my dev machine running Windows 8 Pro with Media Center. I am new to wpf, I've only used WinForms in the past. Am I missing something? Is there something I need to do?

Edit: Actually, It won't even run from the release folder on my development machine. It will only run if I launch it from Visual Studio.

**Comment by mtaradeh** [comment]
Remove: 
       <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" /> 

from App.Xaml and it will work

**Comment by amirhoseynfatemi** [comment]
Hi, I downloaded mahapps and extracted it on my computer. An error occurs when running. Which says error in loading project files
