### ISSUE TITLE
Styling my Custom DataGrid Based on MahAppsMetro MetroDataGrid

### ISSUE THREAD

**Issue by Camuvingian** [MahApps/MahApps.Metro#663]
All I have the following XAML for a custom `DataGrid` control

```
<Controls:ResourceDataGrid 
    x:Name="resourceDataGrid" 
    Style="{StaticResource MetroDataGrid}" 
    ItemsSource="{Binding Path=Resources, 
                          Mode=TwoWay,
                          UpdateSourceTrigger=PropertyChanged, 
                          IsAsync=True}" 
        <Controls:ResourceDataGrid.Columns>
            <DataGridTemplateColumn Header="KeyIndex" 
                                    SortMemberPath="KeyIndex" 
                                    CellTemplate="{StaticResource readOnlyCellUpdatedStyle}" 
                                    IsReadOnly="True"/>
            <DataGridTextColumn Header="FileName" 
                                Binding="{Binding FileName}" 
                                IsReadOnly="True"/>
            <DataGridTextColumn Header="ResourceName" 
                                Binding="{Binding ResourceName}" 
                                IsReadOnly="False"/>
            <Controls:CollectionTextColumn Collection="ResourceStringList" 
                                           Visibility="Collapsed"/>
        </Controls:ResourceDataGrid.Columns>
</Controls:ResourceDataGrid>
```

I am using the `MahAppsMetro` style for this `DataGrid`. This works well for `DataGrids` where I am not using a custom column template, but here I am using `Controls:ResourceDataGrid.Columns` and this is overriding the style for these columns. **How do I prevent this or enable the use of the MahAppsMetro style without effecting the metro template?**

Thanks for your time.

**Comment by abani1986** [comment]
Hi ,

Currently I am using version 1.2.0.0 and still am facing the same issue with right alignment.
If I make any column as horizontal alignment right, I can see a square while selecting the column data.

Please see the below screen shot.


![2016-09-15_13-50-04](https://cloud.githubusercontent.com/assets/22212348/18543077/9dcafda4-7b4b-11e6-85a7-205c188e4f51.jpg)
