### ISSUE TITLE
Setting Datagrid row background breaks row selection styling

### ISSUE THREAD

**Issue by brandonam** [MahApps/MahApps.Metro#666]
I switched from the ListViewcontrol to the DataGrid and I'm attempting to highlight certain rows within the data grid using the following 

var row = GlobalDataGrid.ItemContainerGenerator.ContainerFromIndex(index) as DataGridRow;
if (row != null) row.Background = Brushes.LightGreen;

However after the row gets updated with the selected color the style for row selection breaks for the entire control causing the selected items background to stay white while the text is also turned white, thus causing the selected row to basically appear blank. This does not happen with the ListView control.

Apologies if I'm doing something incorrect

Before:
![before](https://f.cloud.github.com/assets/1925792/1157860/cba8b772-1fa8-11e3-9f7f-b5e11d1bfe8d.png)

After:
![after](https://f.cloud.github.com/assets/1925792/1157884/3c98b536-1fa9-11e3-90e6-607c68b82d9c.png)

Thanks for a great project!

**Comment by olejorgensen** [comment]
Why is the Highlighted Text White in the firste place? It doesnt make any sense for a white theme

**Comment by olejorgensen** [comment]
I had this problem today apparently because I not using converters too (maybe I should).
To recreate assign a list of objects to a datagrid and update the selectedindex

            valuesDataGrid.ItemsSource = null;
            valuesDataGrid.ItemsSource = orderedPLs.ToList();
            valuesDataGrid.SelectedIndex = 0;

and in the LoadingRow event accidently set the background to null

        private void datagrid_LoadingRow(object sender, DataGridRowEventArgs e)
        {
                var theRow = e.Row.DataContext as SomeObject;
                if (   change bg-color on theRow??    )
                {        
                        e.Row.Tag = e.Row.Background;
                        e.Row.Background = Brushes.PaleGoldenrod;
                } else  
                    e.Row.Background = e.Row.Tag as Brush; // might be null

I got around it by handling the else properly

                    else if (e.Row.Tag as Brush != null)
                    {   
                         e.Row.Background = e.Row.Tag as Brush;
                         e.Row.Tag = null;
                    }
