### ISSUE TITLE
Customize TexBox ErrorTemplate

### ISSUE THREAD

**Issue by matteomigliore** [MahApps/MahApps.Metro#682]
How can I customize the ErrorTemplate of the TextBox?

I use this style, but if this way the Watermark text does not appear:

``` xml
<Style TargetType="TextBox">
    <Setter Property="Foreground" Value="Red" />
    <Setter Property="Padding" Value="3" />
    <Setter Property="Validation.ErrorTemplate">
        <Setter.Value>
            <ControlTemplate>
                <Grid>
                    <Polygon Margin="0,2,2,0" Points="10,10 10,0 0,0"
                            Fill="Red"
                            HorizontalAlignment="Right"
                            VerticalAlignment="Top"
                            ToolTip="{Binding ElementName=adorner, Path=AdornedElement.(Validation.Errors)[0].ErrorContent}"/>
                    <AdornedElementPlaceholder x:Name="adorner"/>
                </Grid>
            </ControlTemplate>
        </Setter.Value>
    </Setter>
</Style>
```

**Comment by Gerardo-Sista** [comment]
> I re created the Style of the TextBox and ajusted some colors in another file, to have this result:
> ![textbox](https://camo.githubusercontent.com/59963f103d531dae057938857d940e1beddcf4a7/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f3433323937342f313237303335362f61333335346231322d326430382d313165332d383630612d3235313137383931316631342e706e67)
> 
> Instead of the default graphic:
> ![textbox previous](https://camo.githubusercontent.com/ba0cc4ba72008b28929f78615fdc1a001a385db4/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f3433323937342f313237303437342f38336536316661612d326430612d313165332d393438342d3835653932623362366431372e706e67)

Could you share the code please? I wish to have the same result. Thank you.
