### ISSUE TITLE
Keep Flyout opened

### ISSUE THREAD

**Issue by robertstefan** [MahApps/MahApps.Metro#723]
So, I have a flyout on the bottom of the page with list of tiles. 
Each tile has a context menu, but when I right click on the tile to show the menu, the flyout collapses and the menu remains opened.

Now my question is: How can I maintain the flyout open until the user has chosen for an option from the menu?

**Comment by zeroyjk** [comment]
I have some question.. in contextmenu how to make the flyout open when it click 
`                          <ContextMenu>
                                 <MenuItem Header="Action1">
                                        <MenuItem Header="Sub-Action1" Click="SubAction1_Click"  />
                                          <MenuItem Header="Aub-Action2" Click="SubAction2_Click" />
                                  </MenuItem>
                                  <MenuItem Header="Action2" Click="Action2_Click" />
                          </ContextMenu>`

SubAction1 > it will open flyout... i stack on behide the code.. can someone give some guild.. Thank You..
