### ISSUE TITLE
WebBrowser control not visible

### ISSUE THREAD

**Issue by ssolomon** [MahApps/MahApps.Metro#727]
In the version available via Nuget, WebBrowser controls on a page are visible.  However, on the current latest, WebBrowsers controls are not displaying their content. The content is there, and you are able to view source, but the contents are not visible.  This could be related to a known issue with WebBrowser controls when used in a windows with AllowsTransparancy turned on.

**Comment by djmiller9975** [comment]
I'm trying your solution above and VS tells me that AllowsTransparency is not recognized or inaccessible.  It doesn't let me pick anything after BorderlessWindowBehavior
