### ISSUE TITLE
Hide ClearTextButton when no text is entered.

### ISSUE THREAD

**Issue by grokys** [MahApps/MahApps.Metro#788]
Hi there,

Would it be possible to hide the ClearTextButton when no text is entered in a TextBox? (Or even better show a different icon, such as a search icon) This is how search boxes are usually implemented.

I know I can use a style to hide the button, but this should be default behaviour - usually a user doesn't expect to see the clear icon unless text is present.

**Comment by prashantchoudhary** [comment]
I solved it By adding reference to Property in Binding,
` <TextBox Controls:TextBoxHelper.ClearTextButton="{Binding Path=(Controls:TextBoxHelper.HasText),RelativeSource= {RelativeSource Mode=Self}}/>`
