### ISSUE TITLE
Metro Window and SizeToContent.WidthAndHeight

### ISSUE THREAD

**Issue by clodewyks** [MahApps/MahApps.Metro#794]
Hi All,

I have picked up an issue where if I
 set my MetroWindow to SizeToContent.WidthAndHeight, it adds a black border to the window, I have tested and confirmed that it is only when you set SizeToContent.WidthAndHeight.

Is this a known issue that there is a solution for or a new issue?

Please see attached screenshot.

![dionysus_2013-11-11_08-48-43](https://f.cloud.github.com/assets/5906783/1510997/9ecdc236-4a9d-11e3-8c2f-3ad5112f333e.png)

Thanx,
Chris

**Comment by GhfDllT** [comment]
Hi all!

It seems I am having the same issue now (I am talking about black border). I am using version 1.5.0

**Comment by batzen** [comment]
@GhfDllT You should not comment on old & closed issues. You get way better responses by opening a new issue and referencing the old one there.
