### ISSUE TITLE
Accent color for toggled button's background

### ISSUE THREAD

**Issue by topvis** [MahApps/MahApps.Metro#963]
Current style as shown below (snapshot from MetroSample). Toggled button has dark gray background. Gray (dark or light) always gives an impression of disabled.
![image](https://f.cloud.github.com/assets/5996531/1954223/71eae9ee-81d2-11e3-91eb-111e5903ccae.png)

Would it look better if using Accent color for toggled button's background? Something like below (snapshot from GitHub desktop app). Just personal preference.
![image](https://f.cloud.github.com/assets/5996531/1954251/1168fba0-81d3-11e3-9f36-3e006b8e89c1.png)

**Comment by JobaDiniz** [comment]
Hi, as it seems, the PR only changes MetroCircleToggleButtonStyle, what about the default ToggleButton? It is still not showing AccentColor when toggled.

**Comment by kjeremy** [comment]
@100GPing100 How did you change the colors for avalondock?  I would like to do something similar so that it matches the MahApps theme.

**Comment by 100GPing100** [comment]
@kjeremy I created styles for each of the components belonging to AvalonDock. AvalonDock has some styles already, you can base yourself on them.

**Comment by kjeremy** [comment]
@100GPing100 Can you share them in a gist?  I tried to figure it out but I find the styling REALLY complicated for AvalonDock.

**Comment by 100GPing100** [comment]
@kjeremy Yes I sure can, I'll only be home either tonight or tomorrow though, so only then as I don't have those files here on my laptop.

**Comment by kjeremy** [comment]
@100GPing100 Great!  Please let me know when you have them up.

**Comment by kjeremy** [comment]
@100GPing100 any word?

**Comment by 100GPing100** [comment]
I'm really sorry for the delay, I have been away from my desktop, for a long time now, and have had a lot of stuff going on lately. I will try my best to get it up tomorrow, but I can't promise anything, I still have to look for the files, filter out what's not needed and upload them. Once again, I am sorry for the delay.
