### ISSUE TITLE
Hide buttons in titlebar when flyout is open

### ISSUE THREAD

**Issue by JohnSpruit** [MahApps/MahApps.Metro#966]
Sorry for my bad description.
I would like the have an option to not show the close, minimize en maximize buttons when a flyout on the right is open. Often i press the close window button when i want to close the flyout. Why would you show these buttons anyway?

**Comment by NicoTravassos** [comment]
@flagbug was this ShowWindowCommandsOnTop=False taken out because i tried this.ShowWindowCommandsOnTop=False; and its not working?

**Comment by TricellSoftware** [comment]
I'm trying to use the same ShowWindowCommandsOnTop="False" but is not working I get
The member "ShowWindowCommandsOnTop" is not recognized or is not accessible.

**Comment by punker76** [comment]
@NicoTravassos @TricellSoftware it's changed since v0.14 (https://github.com/MahApps/MahApps.Metro/pull/1427)
there are now

```csharp
        public static readonly DependencyProperty LeftWindowCommandsOverlayBehaviorProperty = DependencyProperty.Register("LeftWindowCommandsOverlayBehavior", typeof(WindowCommandsOverlayBehavior), typeof(MetroWindow), new PropertyMetadata(WindowCommandsOverlayBehavior.Always));
        public static readonly DependencyProperty RightWindowCommandsOverlayBehaviorProperty = DependencyProperty.Register("RightWindowCommandsOverlayBehavior", typeof(WindowCommandsOverlayBehavior), typeof(MetroWindow), new PropertyMetadata(WindowCommandsOverlayBehavior.Always));
        public static readonly DependencyProperty WindowButtonCommandsOverlayBehaviorProperty = DependencyProperty.Register("WindowButtonCommandsOverlayBehavior", typeof(WindowCommandsOverlayBehavior), typeof(MetroWindow), new PropertyMetadata(WindowCommandsOverlayBehavior.Always));
        public static readonly DependencyProperty IconOverlayBehaviorProperty = DependencyProperty.Register("IconOverlayBehavior", typeof(WindowCommandsOverlayBehavior), typeof(MetroWindow), new PropertyMetadata(WindowCommandsOverlayBehavior.Never));
```

**Comment by TricellSoftware** [comment]
So overlap the option. What option show I change to

**Comment by Naimish2612** [comment]
ShowCloseButton="False" only hides the CloseButton
