### ISSUE TITLE
Application Icon (Top Left Window) Stretches to fit title bar height

### ISSUE THREAD

**Issue by Qara-Penimah** [MahApps/MahApps.Metro#971]
How to stop the application icon from stretching to the height of title bar. This leaves no space between the icon and title bar edges and the icon quality deteriorates.

Example:
![example](https://f.cloud.github.com/assets/1212376/1974138/2b8366dc-8369-11e3-9a4d-6abcce28514b.png)

**Comment by qldevteam** [comment]
Good morning,with style CleanWindowStyle I've problem System.NullReferenceException with metrowindow_sizechanged ,what is?Only If I delete the property template it run?Have you got any idea?

**Comment by punker76** [comment]
@qldevteam Please create a new issue for your probelm. (incl. which MahApps version and maybe a source snippet or a simple app)

**Comment by qldevteam** [comment]
Why new issue?It's relative to issue of  @topvis  above !!

`<Controls:MetroWindow x:Class="BaseMVVM.View.BaccoMain"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:Controls="clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro"
        xmlns:Converters="clr-namespace:Utilities.Converters"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:Behaviours="clr-namespace:MahApps.Metro.Behaviours;assembly=MahApps.Metro"
        xmlns:local="clr-namespace:BaseMVVM.View"
        xmlns:Utility="clr-namespace:Utilities"
        xmlns:conv="clr-namespace:Utilities.Converter"
        mc:Ignorable="d"
        WindowStartupLocation="CenterScreen"
        Title="" Height="650" Width="1050"
        Icon="../Assets/Bacco02.ico"
        Style="{DynamicResource MyCleanWindowStyleKey}" AllowsTransparency="False"
        >
    
    <Controls:MetroWindow.Resources>
        <ResourceDictionary 
                            xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                    xmlns:Controls="clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro"
                    xmlns:Behaviours="clr-namespace:MahApps.Metro.Behaviours;assembly=MahApps.Metro"            
                            >

            <BooleanToVisibilityConverter x:Key="BooleanToVisibilityConverter" />
            <conv:ConverterComunication x:Key="bConvComunic" />
            <Utility:cListLiveDataPlc1 x:Key="mLLDataPlc1" />
            <CollectionViewSource x:Key="cvObsEProd1"  Source="{StaticResource mLLDataPlc1}"/>
            
            
            <Style TargetType="{x:Type Controls:MetroWindow}" BasedOn="{StaticResource CleanWindowStyleKey}" x:Key="MyCleanWindowStyleKey">
                <Setter Property="NonActiveWindowTitleBrush" Value="{DynamicResource TransparentWhiteBrush}" />
                <Setter Property="OverrideDefaultWindowCommandsBrush" Value="{DynamicResource BlackBrush}" />
                <Setter Property="TitleAlignment" Value="Center" />
                <Setter Property="TitleForeground" Value="{DynamicResource BlackBrush}" />
                <Setter Property="WindowTitleBrush" Value="{DynamicResource TransparentWhiteBrush}" />
                <Setter Property="Template">
                    <Setter.Value>
                        <ControlTemplate TargetType="{x:Type Controls:MetroWindow}">
                            <ControlTemplate.Resources>
                                <BooleanToVisibilityConverter x:Key="BooleanToVisibilityConverter" />

                                <Storyboard x:Key="OverlayFastSemiFadeIn" 
                                    BeginTime="0:0:0"
                                    AccelerationRatio=".97" 
                                    Storyboard.TargetProperty="Opacity"
                                    SpeedRatio="2.7">
                                    <DoubleAnimation To=".7" />
                                </Storyboard>
                            </ControlTemplate.Resources>
                        </ControlTemplate>
                    </Setter.Value>
                </Setter>
            </Style>
        </ResourceDictionary>
`

**Comment by punker76** [comment]
@qldevteam Because I think your problem has nothing to do with the initial started issue about the icon stretch... And where is the other part of your Template? Which version of MahApps do you use?

So please, create a new issue. Thx 🙏

**Comment by qldevteam** [comment]
Ok excuse me !

**Comment by zeluisping** [comment]
You should've referenced this issue for the people who got notification on this one to checkout
