### ISSUE TITLE
Showing second metro dialog

### ISSUE THREAD

**Issue by olegsavelos** [MahApps/MahApps.Metro#979]
Hi i am trying to show a second metro dialog when first dialog is already visible.
It seems that in this part of code 

```
if (IsOverlayVisible() && overlayStoryboard == null)
                return new System.Threading.Tasks.Task(() => { }); //No Task.FromResult in .NET 4.
```

overlayStoryboard is equal to null and new task is returned.
I dont know if this is a bug or by design but even so this new task returned actually blocks the calling thread for no reason?

**Comment by punker76** [comment]
this is solved by https://github.com/MahApps/MahApps.Metro/pull/2009
