### ISSUE TITLE
pack://application:,,,/ Uri's

### ISSUE THREAD

**Issue by remcoros** [MahApps/MahApps.Metro#992]
Ok, this is not much an issue. More a little advice and maybe you could add it to the quickstart or wiki.

I don't know if it is visual studio or the resharper extension (probably the latter) but I always get a warning in the editor (not the compiler) when using 'pack://application:,,,/' uri's. (Invalid characters in path).

This results in that intellisense does not suggest items included in those resource files and gives a warning that the resource could not be found.

Now all this is not much of a problem during compile/runtime. But having intellisense and less warnings in the editor makes for an overall beter experience in the ide :-).

So here's the tip:

Instead of using:

```
            <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
            <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
            <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Colors.xaml" />
```

you can use:

```
            <ResourceDictionary Source="/MahApps.Metro;component/Styles/Controls.xaml" />
            <ResourceDictionary Source="/MahApps.Metro;component/Styles/Fonts.xaml" />
            <ResourceDictionary Source="/MahApps.Metro;component/Styles/Colors.xaml" />
```

_Important Note:_ do not change the Uri of the 'Accents/*' resource dictionaries, as they are hardcoded and that would break theming.

**Comment by mertens3d** [comment]
@remcoros, Thanks. This was driving me crazy.

**Comment by remcoros** [comment]
@mertens3d I knew this would help someone, someday. cheers
