### ISSUE TITLE
Make MA.M more MVVM-friendly

### ISSUE THREAD

**Issue by Amrykid** [MahApps/MahApps.Metro#999]
There are some things in our library that can be made for or improved for MVVM scenarios. We should try to figure out how to make those non-friendly sections more friendly. (Feel free to discuss here or in [gitter](https://gitter.im/MahApps/MahApps.Metro).)

- Dialogs aren't exactly as MVVM friendly as they should be.
- FlipView isn't designed for MVVM scenarios. - #998 - see PR #1040 
- Flyouts.... ugh.

**Comment by dealproc** [comment]
Can a contrib project be launched, now that MahApps is in v1.0 stage, that folks can start dumping what they've done to solve common problems in the MVVM space (e.g. showing a dialog via an IDialogManager) in some sort of way that makese sense?

**Comment by thoemmi** [comment]
I've started with my own (opiniated) MVVM library based on MahApps.Metro, see [TinyLittleMvvm](https://github.com/thoemmi/TinyLittleMvvm)

**Comment by papuashu** [comment]
Meantime, I've discovered Caliburn.Metro which seems to be a good start in this direction (Caliburn.Micro + MA.M)

**Comment by dealproc** [comment]
link @papuashu ?

**Comment by keithrfung** [comment]
@dealproc [Caliburn.Metro](https://github.com/ziyasal/Caliburn.Metro)

**Comment by bhaidar** [comment]
@remcoros I might be missing something in here. Where do you specify the UserControl that should appear inside the Flyout? In case of multiple Flyouts, how do you specify that? Thanks
